<h1><center>Laboratorio 6: Optimización de modelos 🧪</center></h1>

<center><strong>MDS7202: Laboratorio de Programación Científica para Ciencia de Datos - Primavera 2025</strong></center>

### Cuerpo Docente:

- Profesores: Diego Cortez, Gabriel Iturra
- Auxiliares: Melanie Peña, Valentina Rojas
- Ayudantes: Nicolás Cabello, Cristopher Urbina

### Equipo: SUPER IMPORTANTE - notebooks sin nombre no serán revisados

- Nombre de alumno 1: Benito Fuentes
- Nombre de alumno 2: Sebastián Vergara


Reglas:

- **Grupos de 2 personas**
- Fecha de entrega: Entregas Martes a las 23:59.
- Instrucciones del lab el viernes a las 16:15 en formato online. Asistencia no es obligatoria, pero se recomienda **fuertemente** asistir.
- <u>Prohibidas las copias</u>. Cualquier intento de copia será debidamente penalizado con el reglamento de la escuela.
- Tienen que subir el laboratorio a u-cursos y a su repositorio de github. Labs que no estén en u-cursos no serán revisados. Recuerden que el repositorio también tiene nota.
- Cualquier duda fuera del horario de clases al foro. Mensajes al equipo docente serán respondidos por este medio.
- Pueden usar cualquier material del curso que estimen conveniente.

### **Link de repositorio de GitHub:** [Insertar Repositorio](https://github.com/blvckvenom/Laboratorios-MDS)

### Temas a tratar

- Predicción de demanda usando `xgboost`
- Búsqueda del modelo óptimo de clasificación usando `optuna`
- Uso de pipelines.


### Reglas:

- **Grupos de 2 personas**
- Fecha de entrega: 6 días de plazo con descuento de 1 punto por día. Entregas Martes a las 23:59.
- Instrucciones del lab el viernes a las 16:15 en formato online. Asistencia no es obligatoria, pero se recomienda fuertemente asistir.
- <u>Prohibidas las copias</u>. Cualquier intento de copia será debidamente penalizado con el reglamento de la escuela.
- Tienen que subir el laboratorio a u-cursos y a su repositorio de github. Labs que no estén en u-cursos no serán revisados. Recuerden que el repositorio también tiene nota.
- Cualquier duda fuera del horario de clases al foro. Mensajes al equipo docente serán respondidos por este medio.
- Pueden usar cualquier material del curso que estimen conveniente.

El laboratorio deberá ser desarrollado sin el uso indiscriminado de iteradores nativos de python (aka "for", "while"). La idea es que aprendan a exprimir al máximo las funciones optimizadas que nos entrega `pandas`, las cuales vale mencionar, son bastante más eficientes que los iteradores nativos sobre DataFrames.

# Importamos librerias útiles

In [1]:
pip install -qq xgboost optuna

Note: you may need to restart the kernel to use updated packages.

# El emprendimiento de Fiu

Tras liderar de manera exitosa la implementación de un proyecto de ciencia de datos para caracterizar los datos generados en Santiago 2023, el misterioso corpóreo **Fiu** se anima y decide levantar su propio negocio de consultoría en machine learning. Tras varias e intensas negociaciones, Fiu logra encontrar su *primera chamba*: predecir la demanda (cantidad de venta) de una famosa productora de bebidas de calibre mundial. Al ver el gran potencial y talento que usted ha demostrado en el campo de la ciencia de datos, Fiu lo contrata como data scientist para que forme parte de su nuevo emprendimiento.

Para este laboratorio deben trabajar con los datos `sales.csv` subidos a u-cursos, el cual contiene una muestra de ventas de la empresa para diferentes productos en un determinado tiempo.

Para comenzar, cargue el dataset señalado y visualice a través de un `.head` los atributos que posee el dataset.

<i><p align="center">Fiu siendo felicitado por su excelente desempeño en el proyecto de caracterización de datos</p></i>
<p align="center">
  <img src="https://media-front.elmostrador.cl/2023/09/A_UNO_1506411_2440e.jpg">
</p>

In [2]:
import pandas as pd
import numpy as np
from datetime import datetime

df = pd.read_csv("sales.csv")

df.head()

,id,date,city,lat,long,pop,shop,brand,container,capacity,price,quantity
0,0,31/01/12,Athens,37.97945,23.71622,672130,shop_1,kinder-cola,glass,500ml,0.96,13280
1,1,31/01/12,Athens,37.97945,23.71622,672130,shop_1,kinder-cola,plastic,1.5lt,2.86,6727
2,2,31/01/12,Athens,37.97945,23.71622,672130,shop_1,kinder-cola,can,330ml,0.87,9848
3,3,31/01/12,Athens,37.97945,23.71622,672130,shop_1,adult-cola,glass,500ml,1.00,20050
4,4,31/01/12,Athens,37.97945,23.71622,672130,shop_1,adult-cola,can,330ml,0.39,25696

## 1 Generando un Baseline (5 puntos)

<p align="center">
  <img src="https://media.tenor.com/O-lan6TkadUAAAAC/what-i-wnna-do-after-a-baseline.gif">
</p>

Antes de entrenar un algoritmo, usted recuerda los apuntes de su magíster en ciencia de datos y recuerda que debe seguir una serie de *buenas prácticas* para entrenar correcta y debidamente su modelo. Después de un par de vueltas, llega a las siguientes tareas:

1. Separe los datos en conjuntos de train (70%), validation (20%) y test (10%). Fije una semilla para controlar la aleatoriedad. [0.5 puntos]
2. Implemente un `FunctionTransformer` para extraer el día, mes y año de la variable `date`. Guarde estas variables en el formato categorical de pandas. [1 punto]
3. Implemente un `ColumnTransformer` para procesar de manera adecuada los datos numéricos y categóricos. Use `OneHotEncoder` para las variables categóricas. `Nota:` Utilice el método `.set_output(transform='pandas')` para obtener un DataFrame como salida del `ColumnTransformer` [1 punto]
4. Guarde los pasos anteriores en un `Pipeline`, dejando como último paso el regresor `DummyRegressor` para generar predicciones en base a promedios. [0.5 punto]
5. Entrene el pipeline anterior y reporte la métrica `mean_absolute_error` sobre los datos de validación. ¿Cómo se interpreta esta métrica para el contexto del negocio? [0.5 puntos]
6. Finalmente, vuelva a entrenar el `Pipeline` pero esta vez usando `XGBRegressor` como modelo **utilizando los parámetros por default**. ¿Cómo cambia el MAE al implementar este algoritmo? ¿Es mejor o peor que el `DummyRegressor`? [1 punto]
7. Guarde ambos modelos en un archivo .pkl (uno cada uno) [0.5 puntos]

In [3]:
from sklearn import set_config
set_config(transform_output="pandas")


# 1.1️ Carga de datos y separación en train/val/test (70/20/10)
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import FunctionTransformer, OneHotEncoder
from sklearn.compose import ColumnTransformer, make_column_selector
from sklearn.dummy import DummyRegressor
from sklearn.metrics import mean_absolute_error
import joblib
from xgboost import XGBRegressor

# Variable objetivo: 'quantity'
df = pd.read_csv("sales.csv")
y = df["quantity"]
X = df.drop(columns=["quantity"])

X_train, X_tmp, y_train, y_tmp = train_test_split(
    X, y, test_size=0.30, random_state=42
)
X_val, X_test, y_val, y_test = train_test_split(
    X_tmp, y_tmp, test_size=(1/3), random_state=42
)


# 1.2️ FunctionTransformer: extraer día, mes y año de 'date' como categóricas
def add_date_parts(X_df: pd.DataFrame) -> pd.DataFrame:
    Xo = X_df.copy()
    if "date" in Xo.columns:
        dt = pd.to_datetime(Xo["date"], errors="coerce")
        Xo["year"]  = dt.dt.year.astype("Int16").astype("category")
        Xo["month"] = dt.dt.month.astype("Int8").astype("category")
        Xo["day"]   = dt.dt.day.astype("Int8").astype("category")
        Xo = Xo.drop(columns=["date"])
    return Xo

date_ft = FunctionTransformer(add_date_parts)


# 1.3️ ColumnTransformer: numéricas (passthrough) y categóricas (OneHotEncoder)
num_sel = make_column_selector(dtype_include=np.number)
cat_sel = make_column_selector(dtype_include=["object", "category"])

preprocess = ColumnTransformer(
    transformers=[
        ("num", "passthrough", num_sel),
        ("cat", OneHotEncoder(handle_unknown="ignore", sparse_output=False), cat_sel),
    ]
)


# 1.4️ Pipeline con DummyRegressor (baseline por promedio)
pipe_dummy = Pipeline(steps=[
    ("date_features", date_ft),
    ("preprocess", preprocess),
    ("model", DummyRegressor(strategy="mean"))
])

# 1.5️ Entrenamiento y MAE en validación
pipe_dummy.fit(X_train, y_train)
mae_dummy = mean_absolute_error(y_val, pipe_dummy.predict(X_val))
print(f"MAE validación (DummyRegressor): {mae_dummy:.6f}")

# 1.6️ Pipeline con XGBRegressor
pipe_xgb = Pipeline(steps=[
    ("date_features", date_ft),
    ("preprocess", preprocess),
    ("model", XGBRegressor(random_state=42))
])

pipe_xgb.fit(X_train, y_train)
mae_xgb = mean_absolute_error(y_val, pipe_xgb.predict(X_val))
print(f"MAE validación (XGBRegressor default): {mae_xgb:.6f}")
print("Comparación:", "Mejor" if mae_xgb < mae_dummy else "Peor o igual")


# 1.7️ Guardar ambos modelos en .pkl
joblib.dump(pipe_dummy, "baseline_dummy.pkl")
joblib.dump(pipe_xgb, "baseline_xgb.pkl")

C:\Users\verga\AppData\Local\Temp\ipykernel_63312\3804908470.py:32: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_63312\3804908470.py:32: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_63312\3804908470.py:32: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

MAE validación (DummyRegressor): 13298.497767
MAE validación (XGBRegressor default): 2413.171360
Comparación: Mejor

C:\Users\verga\AppData\Local\Temp\ipykernel_63312\3804908470.py:32: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

['baseline_xgb.pkl']

## 2. Forzando relaciones entre parámetros con XGBoost (10 puntos)

<p align="center">
  <img src="https://64.media.tumblr.com/14cc45f9610a6ee341a45fd0d68f4dde/20d11b36022bca7b-bf/s640x960/67ab1db12ff73a530f649ac455c000945d99c0d6.gif">
</p>

Un colega aficionado a la economía le *sopla* que la demanda guarda una relación inversa con el precio del producto. Motivado para impresionar al querido corpóreo, se propone hacer uso de esta información para mejorar su modelo realizando las siguientes tareas:

1. Vuelva a entrenar el `Pipeline` con `XGBRegressor`, pero esta vez forzando una relación monótona negativa entre el precio y la cantidad. Para aplicar esta restricción apóyese en la siguiente <a href = https://xgboost.readthedocs.io/en/stable/tutorials/monotonic.html>documentación</a>. [6 puntos]

>Hint 1: Para implementar el constraint se le sugiere hacerlo especificando el nombre de la variable. De ser así, probablemente le sea útil **mantener el formato de pandas** antes del step de entrenamiento.

>Hint 2: Puede obtener el nombre de las columnas en el paso anterior al modelo regresor mediante el método `.get_feature_names_out()`

2. Luego, vuelva a reportar el `MAE` sobre el conjunto de validación. [1 puntos]

3. ¿Cómo cambia el error al incluir esta relación? ¿Tenía razón su amigo? [2 puntos]

4. Guarde su modelo en un archivo .pkl [1 punto]

In [4]:
# 2. Forzando relación monótona NEGATIVA en 'price' con XGBoost
from xgboost import XGBRegressor
from sklearn.metrics import mean_absolute_error
import joblib

# 2.1 Obtener nombres de features después del preprocesamiento
#     Primero aplicamos SOLO el paso de fechas, luego ajustamos el ColumnTransformer y pedimos los nombres.
X_train_dt = date_ft.fit_transform(X_train)        # aplica add_date_parts
preprocess.fit(X_train_dt)                         # ajusta selectores + OHE
feature_names = preprocess.get_feature_names_out() # nombres en el orden exacto que verá XGB

# Vector de constraints: -1 para 'price', 0 para el resto (alineado a feature_names)
idx_price = pd.Index(feature_names).map(lambda s: (s == "price") or str(s).endswith("price"))
constraints = np.where(idx_price, -1, 0).tolist()

# 2.1 Entrenar Pipeline con XGBRegressor usando el vector de constraints
pipe_xgb_mono = Pipeline(steps=[
    ("date_features", date_ft),
    ("preprocess", preprocess),
    ("model", XGBRegressor(
        random_state=42,
        monotone_constraints=tuple(constraints)
    ))
])

pipe_xgb_mono.fit(X_train, y_train)

# 2.2 MAE en validación
mae_xgb_mono = mean_absolute_error(y_val, pipe_xgb_mono.predict(X_val))
print(f"MAE validación (XGB con monotonía en 'price'): {mae_xgb_mono:.6f}")

# 2.3 Cambio del error vs XGB por defecto (de la Parte 1)
delta = mae_xgb - mae_xgb_mono
print(f"Cambio de MAE respecto a XGB default: {delta:+.6f}")
print("Conclusión:", "Mejoró con la restricción" if mae_xgb_mono < mae_xgb else "No mejoró con la restricción")

# 2.4 Guardar modelo
joblib.dump(pipe_xgb_mono, "xgb_monotonic_price_neg.pkl")
print("Modelo guardado: xgb_monotonic_price_neg.pkl")

MAE validación (XGB con monotonía en 'price'): 2499.159773
Cambio de MAE respecto a XGB default: -85.988414
Conclusión: No mejoró con la restricción
Modelo guardado: xgb_monotonic_price_neg.pkl

C:\Users\verga\AppData\Local\Temp\ipykernel_63312\3804908470.py:32: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_63312\3804908470.py:32: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_63312\3804908470.py:32: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

## 3 Optimización de Hiperparámetros con Optuna (20 puntos)

<p align="center">
  <img src="https://media.tenor.com/fmNdyGN4z5kAAAAi/hacking-lucy.gif">
</p>

Luego de presentarle sus resultados, Fiu le pregunta si es posible mejorar *aun más* su modelo. En particular, le comenta de la optimización de hiperparámetros con metodologías bayesianas a través del paquete `optuna`. Como usted es un aficionado al entrenamiento de modelos de ML, se propone implementar la descabellada idea de su jefe.

A partir de la mejor configuración obtenida en la sección anterior, utilice `optuna` para optimizar sus hiperparámetros. En particular, se pide que su optimización considere lo siguiente:

- Fijar una semilla en las instancias necesarias para garantizar la reproducibilidad de resultados
- Utilice `TPESampler` como método de muestreo
- De `XGBRegressor`, optimice los siguientes hiperparámetros:
    - `learning_rate` buscando valores flotantes en el rango (0.001, 0.1)
    - `n_estimators` buscando valores enteros en el rango (50, 1000)
    - `max_depth` buscando valores enteros en el rango (3, 10)
    - `max_leaves` buscando valores enteros en el rango (0, 100)
    - `min_child_weight` buscando valores enteros en el rango (1, 5)
    - `reg_alpha` buscando valores flotantes en el rango (0, 1)
    - `reg_lambda` buscando valores flotantes en el rango (0, 1)
- De `OneHotEncoder`, optimice el hiperparámetro `min_frequency` buscando el mejor valor flotante en el rango (0.0, 1.0)

Para ello se pide los siguientes pasos:
1. Implemente una función `objective()` que permita minimizar el `MAE` en el conjunto de validación. Use el método `.set_user_attr()` para almacenar el mejor pipeline entrenado. [10 puntos]
2. Fije el tiempo de entrenamiento a 5 minutos. [1 punto]
3. Optimizar el modelo y reportar el número de *trials*, el `MAE` y los mejores hiperparámetros encontrados. ¿Cómo cambian sus resultados con respecto a la sección anterior? ¿A qué se puede deber esto? [3 puntos]
4. Explique cada hiperparámetro y su rol en el modelo. ¿Hacen sentido los rangos de optimización indicados? [5 puntos]
5. Guardar su modelo en un archivo .pkl [1 punto]

In [6]:
import optuna
from optuna.samplers import TPESampler

RANDOM_STATE = 42

# 3.1 Definir la función objective() para minimizar el MAE
def objective(trial):
    # --- Hiperparámetros a optimizar según el enunciado ---
    learning_rate     = trial.suggest_float("learning_rate", 0.001, 0.1)
    n_estimators      = trial.suggest_int("n_estimators", 50, 1000)
    max_depth         = trial.suggest_int("max_depth", 3, 10)
    max_leaves        = trial.suggest_int("max_leaves", 0, 100)
    min_child_weight  = trial.suggest_int("min_child_weight", 1, 5)
    reg_alpha         = trial.suggest_float("reg_alpha", 0.0, 1.0)
    reg_lambda        = trial.suggest_float("reg_lambda", 0.0, 1.0)
    ohe_min_frequency = trial.suggest_float("ohe_min_frequency", 0.0, 1.0)

    # --- Preprocesamiento con OHE usando min_frequency optimizado ---
    num_sel = make_column_selector(dtype_include=np.number)
    cat_sel = make_column_selector(dtype_include=["object", "category"])
    preprocess_opt = ColumnTransformer(
        transformers=[
            ("num", "passthrough", num_sel),
            ("cat", OneHotEncoder(handle_unknown="ignore",
                                  sparse_output=False,
                                  min_frequency=ohe_min_frequency), cat_sel),
        ]
    )

    # --- Modelo XGBoost con parámetros a optimizar ---
    model = XGBRegressor(
        random_state=RANDOM_STATE,
        learning_rate=learning_rate,
        n_estimators=n_estimators,
        max_depth=max_depth,
        max_leaves=max_leaves,
        min_child_weight=min_child_weight,
        reg_alpha=reg_alpha,
        reg_lambda=reg_lambda,
    )

    # --- Pipeline completo ---
    pipe = Pipeline(steps=[
        ("date_features", date_ft),
        ("preprocess", preprocess_opt),
        ("model", model),
    ])

    # Entrenar y evaluar
    pipe.fit(X_train, y_train)
    mae = mean_absolute_error(y_val, pipe.predict(X_val))

    # Guardar el mejor pipeline encontrado hasta ahora
    best_so_far = trial.study.user_attrs.get("best_mae", float("inf"))
    if mae < best_so_far:
        trial.study.set_user_attr("best_mae", mae)
        trial.study.set_user_attr("best_pipeline", pipe)
        trial.study.set_user_attr("best_params", {
            "learning_rate": learning_rate,
            "n_estimators": n_estimators,
            "max_depth": max_depth,
            "max_leaves": max_leaves,
            "min_child_weight": min_child_weight,
            "reg_alpha": reg_alpha,
            "reg_lambda": reg_lambda,
            "ohe_min_frequency": ohe_min_frequency,
        })
    return mae

# 3.2 Crear estudio Optuna con TPESampler y límite de 5 minutos
sampler = TPESampler(seed=RANDOM_STATE)
study = optuna.create_study(direction="minimize", sampler=sampler)
study.optimize(objective, timeout=300)  # 300 segundos = 5 minutos

# 3.3 Reportar resultados: trials, MAE y mejores hiperparámetros
best_trial = study.best_trial
n_trials = len(study.trials)
best_mae = best_trial.value
best_params = study.user_attrs.get("best_params", best_trial.params)

print(f"N° de trials realizados: {n_trials}")
print(f"Mejor MAE (validación): {best_mae:.6f}")
print("Mejores hiperparámetros encontrados:")
for k, v in best_params.items():
    print(f"  - {k}: {v}")

# Comparación con el modelo anterior (XGB por defecto)
try:
    print(f"Cambio de MAE vs XGB default (Parte 1): {mae_xgb - best_mae:+.6f}")
except NameError:
    pass


# 3.5 Guardar el mejor modelo obtenido
best_pipe = study.user_attrs["best_pipeline"]
joblib.dump(best_pipe, "xgb_optuna.pkl")
print("Modelo guardado: xgb_optuna.pkl")

[I 2025-10-08 00:58:47,007] A new study created in memory with name: no-name-eeafcfe1-19b0-41c7-a91c-fcb1458f71ec
C:\Users\verga\AppData\Local\Temp\ipykernel_63312\3804908470.py:32: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_63312\3804908470.py:32: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
[I 2025-10-08 00:58:47,671] Trial 0 finished with value: 7007.956403296079 and parameters: {'learning_rate': 0.03807947176588889, 'n_estimators': 954, 'max_depth': 8, 'max_leaves': 60, 'min_child_weight': 1, 'reg_alpha': 0.15599452033620265, 'reg_lambda': 0.05808361216819946, 'ohe_min_frequency': 0.8661761457749352}. Best is trial 0 with value: 7007.956403296079.
C:\Users\verga\AppData\Local\Temp\ipykernel_63312\3804908470.py:32: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_63312\3804908470.py:32: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
[I 2025-10-08 00:58:48,036] Trial 1 finished with value: 3497.2607743629746 and parameters: {'learning_rate': 0.06051038616257767, 'n_estimators': 723, 'max_depth': 3, 'max_leaves': 97, 'min_child_weight': 5, 'reg_alpha': 0.21233911067827616, 'reg_lambda': 0.18182496720710062, 'ohe_min_frequency': 0.18340450985343382}. Best is trial 1 with value: 3497.2607743629746.
C:\Users\verga\AppData\Local\Temp\ipykernel_63312\3804908470.py:32: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_63312\3804908470.py:32: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
[I 2025-10-08 00:58:48,386] Trial 2 finished with value: 6635.28718117625 and parameters: {'learning_rate': 0.03111998205299424, 'n_estimators': 549, 'max_depth': 6, 'max_leaves': 29, 'min_child_weight': 4, 'reg_alpha': 0.13949386065204183, 'reg_lambda': 0.29214464853521815, 'ohe_min_frequency': 0.3663618432936917}. Best is trial 1 with value: 3497.2607743629746.
C:\Users\verga\AppData\Local\Temp\ipykernel_63312\3804908470.py:32: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_63312\3804908470.py:32: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
[I 2025-10-08 00:58:48,786] Trial 3 finished with value: 3079.800934758944 and parameters: {'learning_rate': 0.04615092843748656, 'n_estimators': 796, 'max_depth': 4, 'max_leaves': 51, 'min_child_weight': 3, 'reg_alpha': 0.046450412719997725, 'reg_lambda': 0.6075448519014384, 'ohe_min_frequency': 0.17052412368729153}. Best is trial 3 with value: 3079.800934758944.
C:\Users\verga\AppData\Local\Temp\ipykernel_63312\3804908470.py:32: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_63312\3804908470.py:32: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
[I 2025-10-08 00:58:49,538] Trial 4 finished with value: 6816.782863358537 and parameters: {'learning_rate': 0.0074401077055426725, 'n_estimators': 952, 'max_depth': 10, 'max_leaves': 81, 'min_child_weight': 2, 'reg_alpha': 0.09767211400638387, 'reg_lambda': 0.6842330265121569, 'ohe_min_frequency': 0.4401524937396013}. Best is trial 3 with value: 3079.800934758944.
C:\Users\verga\AppData\Local\Temp\ipykernel_63312\3804908470.py:32: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_63312\3804908470.py:32: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
[I 2025-10-08 00:58:49,818] Trial 5 finished with value: 7461.386558936955 and parameters: {'learning_rate': 0.013081785249633104, 'n_estimators': 520, 'max_depth': 3, 'max_leaves': 91, 'min_child_weight': 2, 'reg_alpha': 0.662522284353982, 'reg_lambda': 0.31171107608941095, 'ohe_min_frequency': 0.5200680211778108}. Best is trial 3 with value: 3079.800934758944.
C:\Users\verga\AppData\Local\Temp\ipykernel_63312\3804908470.py:32: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_63312\3804908470.py:32: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
[I 2025-10-08 00:58:50,125] Trial 6 finished with value: 6867.7679054470045 and parameters: {'learning_rate': 0.05512431765498469, 'n_estimators': 225, 'max_depth': 10, 'max_leaves': 78, 'min_child_weight': 5, 'reg_alpha': 0.8948273504276488, 'reg_lambda': 0.5978999788110851, 'ohe_min_frequency': 0.9218742350231168}. Best is trial 3 with value: 3079.800934758944.
C:\Users\verga\AppData\Local\Temp\ipykernel_63312\3804908470.py:32: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_63312\3804908470.py:32: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
[I 2025-10-08 00:58:50,312] Trial 7 finished with value: 8686.564986926769 and parameters: {'learning_rate': 0.00976075770314003, 'n_estimators': 236, 'max_depth': 3, 'max_leaves': 32, 'min_child_weight': 2, 'reg_alpha': 0.2713490317738959, 'reg_lambda': 0.8287375091519293, 'ohe_min_frequency': 0.3567533266935893}. Best is trial 3 with value: 3079.800934758944.
C:\Users\verga\AppData\Local\Temp\ipykernel_63312\3804908470.py:32: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_63312\3804908470.py:32: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
[I 2025-10-08 00:58:50,650] Trial 8 finished with value: 3974.4517835365054 and parameters: {'learning_rate': 0.028812516459050697, 'n_estimators': 566, 'max_depth': 4, 'max_leaves': 81, 'min_child_weight': 1, 'reg_alpha': 0.9868869366005173, 'reg_lambda': 0.7722447692966574, 'ohe_min_frequency': 0.1987156815341724}. Best is trial 3 with value: 3079.800934758944.
C:\Users\verga\AppData\Local\Temp\ipykernel_63312\3804908470.py:32: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_63312\3804908470.py:32: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
[I 2025-10-08 00:58:51,499] Trial 9 finished with value: 7344.230983557595 and parameters: {'learning_rate': 0.0015466895952366377, 'n_estimators': 825, 'max_depth': 8, 'max_leaves': 73, 'min_child_weight': 4, 'reg_alpha': 0.07404465173409036, 'reg_lambda': 0.3584657285442726, 'ohe_min_frequency': 0.11586905952512971}. Best is trial 3 with value: 3079.800934758944.
C:\Users\verga\AppData\Local\Temp\ipykernel_63312\3804908470.py:32: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_63312\3804908470.py:32: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
[I 2025-10-08 00:58:51,633] Trial 10 finished with value: 13298.497707599765 and parameters: {'learning_rate': 0.09229253483114683, 'n_estimators': 55, 'max_depth': 5, 'max_leaves': 1, 'min_child_weight': 3, 'reg_alpha': 0.4268128953833143, 'reg_lambda': 0.9597707459454198, 'ohe_min_frequency': 0.011852595611645367}. Best is trial 3 with value: 3079.800934758944.
C:\Users\verga\AppData\Local\Temp\ipykernel_63312\3804908470.py:32: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_63312\3804908470.py:32: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
[I 2025-10-08 00:58:52,104] Trial 11 finished with value: 6755.2025714672145 and parameters: {'learning_rate': 0.06569237816113468, 'n_estimators': 731, 'max_depth': 5, 'max_leaves': 44, 'min_child_weight': 5, 'reg_alpha': 0.35878629750969676, 'reg_lambda': 0.06782026776262096, 'ohe_min_frequency': 0.6355171476922923}. Best is trial 3 with value: 3079.800934758944.
C:\Users\verga\AppData\Local\Temp\ipykernel_63312\3804908470.py:32: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_63312\3804908470.py:32: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
[I 2025-10-08 00:58:52,408] Trial 12 finished with value: 4670.103021571814 and parameters: {'learning_rate': 0.07143256650213327, 'n_estimators': 714, 'max_depth': 3, 'max_leaves': 6, 'min_child_weight': 4, 'reg_alpha': 0.007757683332151474, 'reg_lambda': 0.4687052188878422, 'ohe_min_frequency': 0.23968278799454554}. Best is trial 3 with value: 3079.800934758944.
C:\Users\verga\AppData\Local\Temp\ipykernel_63312\3804908470.py:32: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_63312\3804908470.py:32: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
[I 2025-10-08 00:58:52,951] Trial 13 finished with value: 2236.0440135932786 and parameters: {'learning_rate': 0.07742047722562703, 'n_estimators': 753, 'max_depth': 5, 'max_leaves': 100, 'min_child_weight': 3, 'reg_alpha': 0.6608557252922866, 'reg_lambda': 0.49848817426378866, 'ohe_min_frequency': 0.004470039476462462}. Best is trial 13 with value: 2236.0440135932786.
C:\Users\verga\AppData\Local\Temp\ipykernel_63312\3804908470.py:32: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_63312\3804908470.py:32: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
[I 2025-10-08 00:58:53,524] Trial 14 finished with value: 2226.490540737917 and parameters: {'learning_rate': 0.08166358818148488, 'n_estimators': 829, 'max_depth': 5, 'max_leaves': 61, 'min_child_weight': 3, 'reg_alpha': 0.7267506372103786, 'reg_lambda': 0.462114758401128, 'ohe_min_frequency': 0.0016620296848777441}. Best is trial 14 with value: 2226.490540737917.
C:\Users\verga\AppData\Local\Temp\ipykernel_63312\3804908470.py:32: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_63312\3804908470.py:32: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
[I 2025-10-08 00:58:54,154] Trial 15 finished with value: 2132.6420584051184 and parameters: {'learning_rate': 0.0834448150492328, 'n_estimators': 620, 'max_depth': 7, 'max_leaves': 63, 'min_child_weight': 3, 'reg_alpha': 0.659028604808974, 'reg_lambda': 0.48011047785603334, 'ohe_min_frequency': 0.002413954811016586}. Best is trial 15 with value: 2132.6420584051184.
C:\Users\verga\AppData\Local\Temp\ipykernel_63312\3804908470.py:32: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_63312\3804908470.py:32: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
[I 2025-10-08 00:58:54,494] Trial 16 finished with value: 7032.22691290975 and parameters: {'learning_rate': 0.09449091931362905, 'n_estimators': 388, 'max_depth': 7, 'max_leaves': 61, 'min_child_weight': 2, 'reg_alpha': 0.6308314706796186, 'reg_lambda': 0.41492556852446144, 'ohe_min_frequency': 0.6394684662708776}. Best is trial 15 with value: 2132.6420584051184.
C:\Users\verga\AppData\Local\Temp\ipykernel_63312\3804908470.py:32: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_63312\3804908470.py:32: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
[I 2025-10-08 00:58:55,103] Trial 17 finished with value: 2100.4976042780117 and parameters: {'learning_rate': 0.08411438767878998, 'n_estimators': 616, 'max_depth': 7, 'max_leaves': 65, 'min_child_weight': 4, 'reg_alpha': 0.8041831949427773, 'reg_lambda': 0.582420524912213, 'ohe_min_frequency': 0.0047595058083930815}. Best is trial 17 with value: 2100.4976042780117.
C:\Users\verga\AppData\Local\Temp\ipykernel_63312\3804908470.py:32: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_63312\3804908470.py:32: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
[I 2025-10-08 00:58:55,483] Trial 18 finished with value: 4686.2335893207555 and parameters: {'learning_rate': 0.08507170657364552, 'n_estimators': 453, 'max_depth': 8, 'max_leaves': 38, 'min_child_weight': 4, 'reg_alpha': 0.8120700012360598, 'reg_lambda': 0.5736894675055919, 'ohe_min_frequency': 0.2929395149225298}. Best is trial 17 with value: 2100.4976042780117.
C:\Users\verga\AppData\Local\Temp\ipykernel_63312\3804908470.py:32: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_63312\3804908470.py:32: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
[I 2025-10-08 00:58:56,079] Trial 19 finished with value: 3069.143753716963 and parameters: {'learning_rate': 0.09984468836282745, 'n_estimators': 642, 'max_depth': 7, 'max_leaves': 69, 'min_child_weight': 4, 'reg_alpha': 0.5014570154223665, 'reg_lambda': 0.7255429663622144, 'ohe_min_frequency': 0.09017405294742792}. Best is trial 17 with value: 2100.4976042780117.
C:\Users\verga\AppData\Local\Temp\ipykernel_63312\3804908470.py:32: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

N° de trials realizados: 367
Mejor MAE (validación): 1999.587300
Mejores hiperparámetros encontrados:
  - learning_rate: 0.07227262157029046
  - n_estimators: 942
  - max_depth: 10
  - max_leaves: 85
  - min_child_weight: 4
  - reg_alpha: 0.8656429737249215
  - reg_lambda: 0.03555154159017143
  - ohe_min_frequency: 0.022615198875847117
Cambio de MAE vs XGB default (Parte 1): +413.584060
Modelo guardado: xgb_optuna.pkl

### 3.3 Resultados de la optimización con Optuna

Tras aplicar la optimización de hiperparámetros mediante Optuna con el método de muestreo bayesiano TPESampler, el modelo ejecutó un total de 321 pruebas en un tiempo límite de 5 minutos.
El mejor modelo obtenido alcanzó un MAE de 2012.35, frente al MAE de 2413.17 del modelo base con hiperparámetros por defecto.

Aunque en algunos casos el modelo mostró mejoras durante los trials, la diferencia final no representa un cambio sustancial, lo que indica que el modelo original ya presentaba un ajuste razonable sobre los datos.

Las posibles razones por las que la optimización no generó un aumento significativo en el rendimiento incluyen:

El espacio de búsqueda de hiperparámetros fue amplio, lo que puede haber dispersado las exploraciones sin converger hacia una mejor región.

La variable price presenta una relación compleja con la demanda, y el ruido en los datos puede limitar la capacidad del modelo para generalizar.

El modelo base de XGBoost ya se encontraba bien ajustado, por lo que las mejoras marginales son pequeñas.

En síntesis, la optimización no logró mejorar de forma significativa el rendimiento del modelo, lo cual sugiere que los parámetros por defecto de XGBoost eran ya apropiados para este conjunto de datos.

### 3.4 Explicación de los hiperparámetros y su interpretación

A continuación, se describe el rol de cada hiperparámetro optimizado y la justificación de sus rangos de búsqueda:

learning_rate (0.001 – 0.1): controla la tasa de aprendizaje del modelo. Valores bajos hacen que el aprendizaje sea más lento pero estable, mientras que valores altos pueden provocar sobreajuste.

n_estimators (50 – 1000): indica el número de árboles que se construyen. Más árboles pueden mejorar el desempeño, pero aumentan el riesgo de sobreajuste y el tiempo de cómputo.

max_depth (3 – 10): controla la profundidad máxima de los árboles. Profundidades bajas generan modelos simples (subajuste), mientras que valores altos permiten capturar interacciones complejas (mayor riesgo de sobreajuste).

max_leaves (0 – 100): define el número máximo de hojas por árbol. Controla la complejidad del modelo y su capacidad de dividir el espacio de características.

min_child_weight (1 – 5): especifica el peso mínimo de una hoja para realizar una partición. Valores más altos reducen la posibilidad de divisiones poco relevantes, ayudando a prevenir sobreajuste.

reg_alpha (0 – 1): coeficiente de regularización L1. Promueve la sparsidad de los pesos, eliminando características irrelevantes.

reg_lambda (0 – 1): coeficiente de regularización L2. Penaliza pesos grandes para mejorar la generalización.

ohe_min_frequency (0.0 – 1.0): hiperparámetro del OneHotEncoder que define la frecuencia mínima de las categorías que se conservan. Permite reducir la dimensionalidad del dataset eliminando categorías poco frecuentes.

Los rangos definidos en el enunciado son razonables: abarcan valores típicos para la mayoría de los problemas de regresión con XGBoost, permitiendo un balance adecuado entre capacidad de aprendizaje y regularización.

## 4. Optimización de Hiperparámetros con Optuna y Prunners (17 puntos)

<p align="center">
  <img src="https://i.pinimg.com/originals/90/16/f9/9016f919c2259f3d0e8fe465049638a7.gif">
</p>

Después de optimizar el rendimiento de su modelo varias veces, Fiu le pregunta si no es posible optimizar el entrenamiento del modelo en sí mismo. Después de leer un par de post de personas de dudosa reputación en la *deepweb*, usted llega a la conclusión que puede cumplir este objetivo mediante la implementación de **Prunning**.

Vuelva a optimizar los mismos hiperparámetros que la sección pasada, pero esta vez utilizando **Prunning** en la optimización. En particular, usted debe:

- Responder: ¿Qué es prunning? ¿De qué forma debería impactar en el entrenamiento? [2 puntos]
- Redefinir la función `objective()` utilizando `optuna.integration.XGBoostPruningCallback` como método de **Prunning** [10 puntos]
- Fijar nuevamente el tiempo de entrenamiento a 5 minutos [1 punto]
- Reportar el número de *trials*, el `MAE` y los mejores hiperparámetros encontrados. ¿Cómo cambian sus resultados con respecto a la sección anterior? ¿A qué se puede deber esto? [3 puntos]
- Guardar su modelo en un archivo .pkl [1 punto]

Nota: Si quieren silenciar los prints obtenidos en el prunning, pueden hacerlo mediante el siguiente comando:

```
optuna.logging.set_verbosity(optuna.logging.WARNING)
```

De implementar la opción anterior, pueden especificar `show_progress_bar = True` en el método `optimize` para *más sabor*.

Hint: Si quieren especificar parámetros del método .fit() del modelo a través del pipeline, pueden hacerlo por medio de la siguiente sintaxis: `pipeline.fit(stepmodelo__parametro = valor)`

Hint2: Este <a href = https://stackoverflow.com/questions/40329576/sklearn-pass-fit-parameters-to-xgboost-in-pipeline>enlace</a> les puede ser de ayuda en su implementación

In [ ]:
pip install optuna-integration[xgboost]

Collecting optuna-integration[xgboost]
  Downloading optuna_integration-4.5.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: optuna in c:\users\verga\appdata\local\programs\python\python310\lib\site-packages (from optuna-integration[xgboost]) (4.5.0)
Requirement already satisfied: xgboost in c:\users\verga\appdata\local\programs\python\python310\lib\site-packages (from optuna-integration[xgboost]) (3.0.5)
Requirement already satisfied: alembic>=1.5.0 in c:\users\verga\appdata\local\programs\python\python310\lib\site-packages (from optuna->optuna-integration[xgboost]) (1.16.5)
Requirement already satisfied: colorlog in c:\users\verga\appdata\local\programs\python\python310\lib\site-packages (from optuna->optuna-integration[xgboost]) (6.9.0)
Requirement already satisfied: numpy in c:\users\verga\appdata\local\programs\python\python310\lib\site-packages (from optuna->optuna-integration[xgboost]) (1.26.4)
Requirement already satisfied: packaging>=20.0 in c:\users\verga\appdata\local\programs\python\python310\lib\site-packages (from optuna->optuna-integration[xgboost]) (25.0)
Requirement already satisfied: sqlalchemy>=1.4.2 in c:\users\verga\appdata\local\programs\python\python310\lib\site-packages (from optuna->optuna-integration[xgboost]) (2.0.43)
Requirement already satisfied: tqdm in c:\users\verga\appdata\local\programs\python\python310\lib\site-packages (from optuna->optuna-integration[xgboost]) (4.67.1)
Requirement already satisfied: PyYAML in c:\users\verga\appdata\local\programs\python\python310\lib\site-packages (from optuna->optuna-integration[xgboost]) (6.0.2)
Requirement already satisfied: Mako in c:\users\verga\appdata\local\programs\python\python310\lib\site-packages (from alembic>=1.5.0->optuna->optuna-integration[xgboost]) (1.3.10)
Requirement already satisfied: typing-extensions>=4.12 in c:\users\verga\appdata\local\programs\python\python310\lib\site-packages (from alembic>=1.5.0->optuna->optuna-integration[xgboost]) (4.15.0)
Requirement already satisfied: tomli in c:\users\verga\appdata\local\programs\python\python310\lib\site-packages (from alembic>=1.5.0->optuna->optuna-integration[xgboost]) (2.2.1)
Requirement already satisfied: greenlet>=1 in c:\users\verga\appdata\local\programs\python\python310\lib\site-packages (from sqlalchemy>=1.4.2->optuna->optuna-integration[xgboost]) (3.2.4)
Requirement already satisfied: colorama in c:\users\verga\appdata\roaming\python\python310\site-packages (from colorlog->optuna->optuna-integration[xgboost]) (0.4.6)
Requirement already satisfied: MarkupSafe>=0.9.2 in c:\users\verga\appdata\local\programs\python\python310\lib\site-packages (from Mako->alembic>=1.5.0->optuna->optuna-integration[xgboost]) (3.0.2)
Requirement already satisfied: scipy in c:\users\verga\appdata\local\programs\python\python310\lib\site-packages (from xgboost->optuna-integration[xgboost]) (1.11.4)
Downloading optuna_integration-4.5.0-py3-none-any.whl (99 kB)
Installing collected packages: optuna-integration
Successfully installed optuna-integration-4.5.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
# 4. Optuna + Pruning con XGBoostPruningCallback (compatible con tu xgboost)

import optuna
from optuna.samplers import TPESampler
from optuna.pruners import MedianPruner
from optuna.integration import XGBoostPruningCallback

import xgboost as xgb 

optuna.logging.set_verbosity(optuna.logging.WARNING)
RANDOM_STATE = 42

# 4.2 Redefinir objective() usando XGBoostPruningCallback
def objective(trial):
    # --- Hiperparámetros (mismos de la sección 3) ---
    learning_rate     = trial.suggest_float("learning_rate", 0.001, 0.1)
    n_estimators      = trial.suggest_int("n_estimators", 50, 1000)
    max_depth         = trial.suggest_int("max_depth", 3, 10)
    max_leaves        = trial.suggest_int("max_leaves", 0, 100)
    min_child_weight  = trial.suggest_int("min_child_weight", 1, 5)
    reg_alpha         = trial.suggest_float("reg_alpha", 0.0, 1.0)
    reg_lambda        = trial.suggest_float("reg_lambda", 0.0, 1.0)
    ohe_min_frequency = trial.suggest_float("ohe_min_frequency", 0.0, 1.0)

    # --- Preprocesamiento: OneHotEncoder tunable  ---
    num_sel = make_column_selector(dtype_include=np.number)
    cat_sel = make_column_selector(dtype_include=["object", "category"])
    preprocess_opt = ColumnTransformer(
        transformers=[
            ("num", "passthrough", num_sel),
            ("cat", OneHotEncoder(handle_unknown="ignore",
                                  sparse_output=False,
                                  min_frequency=ohe_min_frequency), cat_sel),
        ]
    )

    # Aplicar el step de fechas y ajustar el preprocesador en TRAIN
    Xtr_dt = date_ft.fit_transform(X_train)
    Xval_dt = date_ft.transform(X_val)

    Xtr = preprocess_opt.fit_transform(Xtr_dt, y_train)
    Xva = preprocess_opt.transform(Xval_dt)

    # --- Configuración de xgboost.train ---
    # Monitoreamos 'validation_0' con métrica 'mae'
    dtrain = xgb.DMatrix(Xtr, label=y_train)
    dvalid = xgb.DMatrix(Xva, label=y_val)

    params = {
        "objective": "reg:squarederror",
        "eval_metric": "mae",        # métrica para pruning
        "eta": learning_rate,        # alias de learning_rate
        "max_depth": max_depth,
        "max_leaves": max_leaves,
        "min_child_weight": min_child_weight,
        "alpha": reg_alpha,          # alias de reg_alpha
        "lambda": reg_lambda,        # alias de reg_lambda
        "seed": RANDOM_STATE,
        "verbosity": 0,
    }

    pruning_cb = XGBoostPruningCallback(trial, "validation_0-mae")

    # Entrenamiento con callbacks
    booster = xgb.train(
        params=params,
        dtrain=dtrain,
        num_boost_round=n_estimators,
        evals=[(dvalid, "validation_0")],
        callbacks=[pruning_cb],
    )

    # Evaluación MAE en validación
    pred_val = booster.predict(dvalid)
    mae = mean_absolute_error(y_val, pred_val)

    # Guardar el MEJOR bundle (transformadores + booster)
    best_so_far = trial.study.user_attrs.get("best_mae_pruned", float("inf"))
    if mae < best_so_far:
        bundle = {
            "date_features": date_ft,        # fitted
            "preprocess": preprocess_opt,    # fitted
            "booster": booster,              # entrenado
        }
        trial.study.set_user_attr("best_mae_pruned", mae)
        trial.study.set_user_attr("best_bundle_pruned", bundle)
        trial.study.set_user_attr("best_params_pruned", {
            "learning_rate": learning_rate,
            "n_estimators": n_estimators,
            "max_depth": max_depth,
            "max_leaves": max_leaves,
            "min_child_weight": min_child_weight,
            "reg_alpha": reg_alpha,
            "reg_lambda": reg_lambda,
            "ohe_min_frequency": ohe_min_frequency,
        })
    return mae

# 4.3 Fijar nuevamente el tiempo de entrenamiento a 5 minutos
sampler = TPESampler(seed=RANDOM_STATE)
pruner = MedianPruner(n_warmup_steps=10)
study_pruned = optuna.create_study(direction="minimize", sampler=sampler, pruner=pruner)

study_pruned.optimize(objective, timeout=300, show_progress_bar=True)  # 300 s = 5 min


# 4.4 Reportar: #trials, MAE y mejores hiperparámetros
best_trial = study_pruned.best_trial
n_trials = len(study_pruned.trials)
best_mae = best_trial.value
best_params = study_pruned.user_attrs.get("best_params_pruned", best_trial.params)

print(f"N° de trials (con pruning): {n_trials}")
print(f"Mejor MAE (validación, pruning): {best_mae:.6f}")
print("Mejores hiperparámetros (pruning):")
for k, v in best_params.items():
    print(f"  - {k}: {v}")

# Comparaciones si están disponibles en el entorno
try:
    print(f"Cambio de MAE vs XGB default (Parte 1): {mae_xgb - best_mae:+.6f}")
except NameError:
    pass
try:
    # Si conservas el 'study' de la parte 3, se imprime la comparación:
    print(f"Cambio de MAE vs mejor Optuna (sin pruning): {study.best_trial.value - best_mae:+.6f}")
except NameError:
    pass


# 4.5 Guardar el modelo en .pkl
best_bundle_pruned = study_pruned.user_attrs["best_bundle_pruned"]
joblib.dump(best_bundle_pruned, "xgb_optuna_pruned.pkl")
print("Modelo guardado: xgb_optuna_pruned.pkl")

   0%|          | 00:00/05:00

[0]	validation_0-mae:12971.60505
[1]	validation_0-mae:12669.04620
[2]	validation_0-mae:12385.16134
[3]	validation_0-mae:12118.00451
[4]	validation_0-mae:11864.08316
[5]	validation_0-mae:11628.34682
[6]	validation_0-mae:11407.09136
[7]	validation_0-mae:11197.06999
[8]	validation_0-mae:10998.05094
[9]	validation_0-mae:10812.92009
[10]	validation_0-mae:10642.66024
[11]	validation_0-mae:10483.82881
[12]	validation_0-mae:10338.70377
[13]	validation_0-mae:10195.97628
[14]	validation_0-mae:10063.29099
[15]	validation_0-mae:9941.65901
[16]	validation_0-mae:9822.85926
[17]	validation_0-mae:9715.60466
[18]	validation_0-mae:9609.61170
[19]	validation_0-mae:9512.21550
[20]	validation_0-mae:9422.07816
[21]	validation_0-mae:9333.93715
[22]	validation_0-mae:9255.18620
[23]	validation_0-mae:9181.17312
[24]	validation_0-mae:9109.05779
[25]	validation_0-mae:9041.88575
[26]	validation_0-mae:8976.89101
[27]	validation_0-mae:8913.76690
[28]	validation_0-mae:8856.93625
[29]	validation_0-mae:8799.36239
[30]	validation_0-mae:8750.07331
[31]	validation_0-mae:8698.94458
[32]	validation_0-mae:8652.81608
[33]	validation_0-mae:8607.60903
[34]	validation_0-mae:8564.64636
[35]	validation_0-mae:8529.05822
[36]	validation_0-mae:8487.88377
[37]	validation_0-mae:8453.04401
[38]	validation_0-mae:8408.11887
[39]	validation_0-mae:8370.67723
[40]	validation_0-mae:8343.00740
[41]	validation_0-mae:8306.66558
[42]	validation_0-mae:8263.81074
[43]	validation_0-mae:8228.39381
[44]	validation_0-mae:8201.12741
[45]	validation_0-mae:8170.59405
[46]	validation_0-mae:8134.88658
[47]	validation_0-mae:8106.84331
[48]	validation_0-mae:8078.52797

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[49]	validation_0-mae:8040.36342
[50]	validation_0-mae:8013.85290
[51]	validation_0-mae:7982.34040
[52]	validation_0-mae:7950.59035
[53]	validation_0-mae:7922.39756
[54]	validation_0-mae:7902.70696
[55]	validation_0-mae:7887.17500
[56]	validation_0-mae:7868.84466
[57]	validation_0-mae:7857.74719
[58]	validation_0-mae:7841.70678
[59]	validation_0-mae:7820.95670
[60]	validation_0-mae:7803.03578
[61]	validation_0-mae:7781.42213
[62]	validation_0-mae:7756.43449
[63]	validation_0-mae:7727.89902
[64]	validation_0-mae:7709.14915
[65]	validation_0-mae:7689.93371
[66]	validation_0-mae:7669.36217
[67]	validation_0-mae:7649.79009
[68]	validation_0-mae:7639.08729
[69]	validation_0-mae:7627.54089
[70]	validation_0-mae:7612.33098
[71]	validation_0-mae:7591.83391
[72]	validation_0-mae:7566.90172
[73]	validation_0-mae:7555.10316
[74]	validation_0-mae:7536.87112
[75]	validation_0-mae:7525.03841
[76]	validation_0-mae:7508.72013
[77]	validation_0-mae:7490.41711
[78]	validation_0-mae:7473.63494
[79]	validation_0-mae:7457.56077
[80]	validation_0-mae:7447.13756
[81]	validation_0-mae:7435.20587
[82]	validation_0-mae:7421.04597
[83]	validation_0-mae:7412.52807
[84]	validation_0-mae:7398.13439
[85]	validation_0-mae:7376.67280
[86]	validation_0-mae:7374.75582
[87]	validation_0-mae:7339.27766
[88]	validation_0-mae:7321.91946
[89]	validation_0-mae:7319.56288
[90]	validation_0-mae:7285.99223
[91]	validation_0-mae:7268.62798
[92]	validation_0-mae:7236.72020
[93]	validation_0-mae:7221.63205
[94]	validation_0-mae:7210.54815
[95]	validation_0-mae:7192.12172
[96]	validation_0-mae:7178.56451
[97]	validation_0-mae:7176.31068
[98]	validation_0-mae:7150.79056
[99]	validation_0-mae:7137.13464
[100]	validation_0-mae:7124.94374
[101]	validation_0-mae:7123.71558
[102]	validation_0-mae:7100.25077
[103]	validation_0-mae:7088.53387
[104]	validation_0-mae:7078.10975
[105]	validation_0-mae:7073.99962
[106]	validation_0-mae:7064.51269
[107]	validation_0-mae:7043.77983
[108]	validation_0-mae:7034.54843
[109]	validation_0-mae:7034.03345
[110]	validation_0-mae:7023.93162
[111]	validation_0-mae:7021.55909
[112]	validation_0-mae:7003.08062
[113]	validation_0-mae:6994.95630
[114]	validation_0-mae:6986.95345
[115]	validation_0-mae:6980.85464
[116]	validation_0-mae:6975.61183
[117]	validation_0-mae:6966.36441
[118]	validation_0-mae:6958.24885
[119]	validation_0-mae:6950.52983
[120]	validation_0-mae:6934.30451
[121]	validation_0-mae:6927.13283
[122]	validation_0-mae:6923.52428
[123]	validation_0-mae:6917.45926
[124]	validation_0-mae:6909.73379
[125]	validation_0-mae:6898.14566
[126]	validation_0-mae:6893.67265
[127]	validation_0-mae:6894.22724
[128]	validation_0-mae:6889.13419
[129]	validation_0-mae:6888.15944
[130]	validation_0-mae:6875.78411
[131]	validation_0-mae:6868.00992
[132]	validation_0-mae:6863.12197
[133]	validation_0-mae:6861.43960
[134]	validation_0-mae:6856.97687
[135]	validation_0-mae:6844.89966
[136]	validation_0-mae:6840.70258
[137]	validation_0-mae:6835.27160
[138]	validation_0-mae:6831.72031
[139]	validation_0-mae:6827.74286
[140]	validation_0-mae:6823.41153
[141]	validation_0-mae:6818.58497
[142]	validation_0-mae:6814.10051
[143]	validation_0-mae:6810.49048
[144]	validation_0-mae:6807.26044
[145]	validation_0-mae:6803.88249
[146]	validation_0-mae:6802.15011
[147]	validation_0-mae:6798.15389
[148]	validation_0-mae:6794.57319
[149]	validation_0-mae:6790.93879
[150]	validation_0-mae:6787.11423
[151]	validation_0-mae:6779.37617
[152]	validation_0-mae:6776.75795
[153]	validation_0-mae:6775.07926
[154]	validation_0-mae:6771.92129
[155]	validation_0-mae:6770.13991
[156]	validation_0-mae:6768.09570
[157]	validation_0-mae:6765.32231
[158]	validation_0-mae:6758.14044
[159]	validation_0-mae:6753.75800
[160]	validation_0-mae:6751.12930
[161]	validation_0-mae:6751.14595
[162]	validation_0-mae:6747.23974
[163]	validation_0-mae:6748.76541
[164]	validation_0-mae:6747.32832
[165]	validation_0-mae:6748.40606
[166]	validation_0-mae:6745.83087
[167]	validation_0-mae:6743.27590
[168]	validation_0-mae:6736.64060
[169]	validation_0-mae:6733.79692
[170]	validation_0-mae:6727.95476
[171]	validation_0-mae:6726.57092
[172]	validation_0-mae:6724.91595
[173]	validation_0-mae:6724.32980
[174]	validation_0-mae:6722.11146
[175]	validation_0-mae:6717.30935
[176]	validation_0-mae:6716.35386
[177]	validation_0-mae:6717.82835
[178]	validation_0-mae:6715.59283
[179]	validation_0-mae:6714.54630
[180]	validation_0-mae:6713.50258
[181]	validation_0-mae:6707.57503
[182]	validation_0-mae:6706.98461
[183]	validation_0-mae:6706.55262
[184]	validation_0-mae:6704.02947
[185]	validation_0-mae:6703.54004
[186]	validation_0-mae:6701.80425
[187]	validation_0-mae:6703.51190
[188]	validation_0-mae:6704.91954
[189]	validation_0-mae:6700.69815
[190]	validation_0-mae:6700.03645
[191]	validation_0-mae:6698.74788
[192]	validation_0-mae:6698.42532
[193]	validation_0-mae:6700.80022
[194]	validation_0-mae:6700.08711
[195]	validation_0-mae:6700.79972
[196]	validation_0-mae:6699.71441
[197]	validation_0-mae:6695.84429
[198]	validation_0-mae:6693.94391
[199]	validation_0-mae:6691.91799
[200]	validation_0-mae:6692.80390
[201]	validation_0-mae:6689.76045
[202]	validation_0-mae:6688.19233
[203]	validation_0-mae:6689.34164
[204]	validation_0-mae:6688.04509
[205]	validation_0-mae:6686.54269
[206]	validation_0-mae:6687.22599
[207]	validation_0-mae:6685.52997
[208]	validation_0-mae:6683.48596
[209]	validation_0-mae:6684.21895
[210]	validation_0-mae:6681.78756
[211]	validation_0-mae:6681.60227
[212]	validation_0-mae:6681.52570
[213]	validation_0-mae:6679.09036
[214]	validation_0-mae:6676.46397
[215]	validation_0-mae:6677.55754
[216]	validation_0-mae:6679.69495
[217]	validation_0-mae:6678.88564
[218]	validation_0-mae:6677.30965
[219]	validation_0-mae:6677.11013
[220]	validation_0-mae:6676.93675
[221]	validation_0-mae:6679.07720
[222]	validation_0-mae:6677.47085
[223]	validation_0-mae:6680.46851
[224]	validation_0-mae:6678.14200
[225]	validation_0-mae:6678.12566
[226]	validation_0-mae:6679.22761
[227]	validation_0-mae:6681.75535
[228]	validation_0-mae:6679.50315
[229]	validation_0-mae:6676.42465
[230]	validation_0-mae:6678.31051
[231]	validation_0-mae:6677.02085
[232]	validation_0-mae:6677.84916
[233]	validation_0-mae:6677.10065
[234]	validation_0-mae:6675.77742
[235]	validation_0-mae:6673.01837
[236]	validation_0-mae:6674.23503
[237]	validation_0-mae:6674.55586
[238]	validation_0-mae:6672.44552
[239]	validation_0-mae:6670.76097
[240]	validation_0-mae:6669.68333
[241]	validation_0-mae:6667.14562
[242]	validation_0-mae:6666.83783
[243]	validation_0-mae:6666.48331
[244]	validation_0-mae:6664.43764
[245]	validation_0-mae:6663.47250
[246]	validation_0-mae:6665.18021
[247]	validation_0-mae:6664.20099
[248]	validation_0-mae:6662.72895
[249]	validation_0-mae:6663.04559
[250]	validation_0-mae:6662.28682
[251]	validation_0-mae:6660.66207
[252]	validation_0-mae:6661.01801
[253]	validation_0-mae:6662.01065
[254]	validation_0-mae:6661.20994
[255]	validation_0-mae:6659.79414
[256]	validation_0-mae:6661.41163
[257]	validation_0-mae:6663.20306
[258]	validation_0-mae:6663.81705
[259]	validation_0-mae:6662.82025
[260]	validation_0-mae:6662.30236
[261]	validation_0-mae:6662.39312
[262]	validation_0-mae:6660.33322
[263]	validation_0-mae:6659.97976
[264]	validation_0-mae:6660.28446
[265]	validation_0-mae:6661.47839
[266]	validation_0-mae:6661.10810
[267]	validation_0-mae:6661.62980
[268]	validation_0-mae:6661.01946
[269]	validation_0-mae:6659.61004
[270]	validation_0-mae:6657.58616
[271]	validation_0-mae:6657.49859
[272]	validation_0-mae:6657.67326
[273]	validation_0-mae:6656.48576
[274]	validation_0-mae:6656.11224
[275]	validation_0-mae:6657.76872
[276]	validation_0-mae:6658.27452
[277]	validation_0-mae:6657.76852
[278]	validation_0-mae:6657.90598
[279]	validation_0-mae:6657.83047
[280]	validation_0-mae:6658.91421
[281]	validation_0-mae:6659.17797
[282]	validation_0-mae:6658.00742
[283]	validation_0-mae:6656.63813
[284]	validation_0-mae:6656.15803
[285]	validation_0-mae:6656.64557
[286]	validation_0-mae:6657.38145
[287]	validation_0-mae:6658.12807
[288]	validation_0-mae:6659.50534
[289]	validation_0-mae:6660.78490
[290]	validation_0-mae:6660.43318
[291]	validation_0-mae:6661.98134
[292]	validation_0-mae:6662.10401
[293]	validation_0-mae:6664.22237
[294]	validation_0-mae:6663.45178
[295]	validation_0-mae:6663.56077
[296]	validation_0-mae:6662.82865
[297]	validation_0-mae:6663.59763
[298]	validation_0-mae:6663.23047
[299]	validation_0-mae:6663.36691
[300]	validation_0-mae:6664.35370
[301]	validation_0-mae:6665.40401
[302]	validation_0-mae:6665.66365
[303]	validation_0-mae:6666.85444
[304]	validation_0-mae:6666.82596
[305]	validation_0-mae:6668.40124
[306]	validation_0-mae:6668.77114
[307]	validation_0-mae:6669.09038
[308]	validation_0-mae:6670.83695
[309]	validation_0-mae:6672.00360
[310]	validation_0-mae:6673.49318
[311]	validation_0-mae:6674.16756
[312]	validation_0-mae:6674.65327
[313]	validation_0-mae:6677.07963
[314]	validation_0-mae:6678.87402
[315]	validation_0-mae:6677.95555
[316]	validation_0-mae:6678.92587
[317]	validation_0-mae:6679.92853
[318]	validation_0-mae:6679.00270
[319]	validation_0-mae:6679.30923
[320]	validation_0-mae:6681.21193
[321]	validation_0-mae:6681.24911
[322]	validation_0-mae:6681.30741
[323]	validation_0-mae:6681.82415
[324]	validation_0-mae:6681.30005
[325]	validation_0-mae:6682.43115
[326]	validation_0-mae:6682.12271
[327]	validation_0-mae:6683.42836
[328]	validation_0-mae:6683.28017
[329]	validation_0-mae:6685.48098
[330]	validation_0-mae:6686.31854
[331]	validation_0-mae:6684.80863
[332]	validation_0-mae:6684.63503
[333]	validation_0-mae:6684.27556
[334]	validation_0-mae:6685.08040
[335]	validation_0-mae:6685.03992
[336]	validation_0-mae:6686.76605
[337]	validation_0-mae:6686.91741
[338]	validation_0-mae:6687.30760
[339]	validation_0-mae:6688.29064
[340]	validation_0-mae:6687.78291
[341]	validation_0-mae:6688.71963
[342]	validation_0-mae:6688.60854
[343]	validation_0-mae:6688.27059
[344]	validation_0-mae:6689.18594
[345]	validation_0-mae:6689.44027
[346]	validation_0-mae:6690.70570
[347]	validation_0-mae:6692.44588
[348]	validation_0-mae:6692.57258
[349]	validation_0-mae:6692.49265
[350]	validation_0-mae:6693.01419
[351]	validation_0-mae:6694.63583
[352]	validation_0-mae:6694.99902
[353]	validation_0-mae:6696.06197
[354]	validation_0-mae:6696.46114
[355]	validation_0-mae:6696.68678
[356]	validation_0-mae:6697.14239
[357]	validation_0-mae:6697.73355
[358]	validation_0-mae:6697.64182
[359]	validation_0-mae:6698.47072
[360]	validation_0-mae:6697.28638
[361]	validation_0-mae:6697.91535
[362]	validation_0-mae:6698.68194
[363]	validation_0-mae:6697.06810
[364]	validation_0-mae:6697.34914
[365]	validation_0-mae:6698.04128
[366]	validation_0-mae:6696.85084
[367]	validation_0-mae:6698.00641
[368]	validation_0-mae:6698.06397
[369]	validation_0-mae:6698.51481
[370]	validation_0-mae:6699.67745
[371]	validation_0-mae:6700.27097
[372]	validation_0-mae:6700.35174
[373]	validation_0-mae:6698.95441
[374]	validation_0-mae:6698.96552
[375]	validation_0-mae:6699.80810
[376]	validation_0-mae:6700.40612
[377]	validation_0-mae:6699.66041
[378]	validation_0-mae:6700.84129
[379]	validation_0-mae:6702.28832
[380]	validation_0-mae:6700.33699
[381]	validation_0-mae:6700.76255
[382]	validation_0-mae:6700.37865
[383]	validation_0-mae:6701.82178
[384]	validation_0-mae:6701.97666
[385]	validation_0-mae:6702.85863
[386]	validation_0-mae:6701.42005
[387]	validation_0-mae:6701.08987
[388]	validation_0-mae:6702.71597
[389]	validation_0-mae:6702.58639
[390]	validation_0-mae:6703.80748
[391]	validation_0-mae:6703.77108
[392]	validation_0-mae:6705.53294
[393]	validation_0-mae:6705.63658
[394]	validation_0-mae:6704.89626
[395]	validation_0-mae:6705.05233
[396]	validation_0-mae:6705.79975
[397]	validation_0-mae:6708.22961
[398]	validation_0-mae:6707.33297
[399]	validation_0-mae:6709.01437
[400]	validation_0-mae:6708.79657
[401]	validation_0-mae:6709.09115
[402]	validation_0-mae:6708.76610
[403]	validation_0-mae:6709.95911
[404]	validation_0-mae:6711.65598
[405]	validation_0-mae:6712.99278
[406]	validation_0-mae:6714.58589
[407]	validation_0-mae:6715.09204
[408]	validation_0-mae:6715.13274
[409]	validation_0-mae:6715.54344
[410]	validation_0-mae:6717.00092
[411]	validation_0-mae:6716.73180
[412]	validation_0-mae:6715.90549
[413]	validation_0-mae:6715.49785
[414]	validation_0-mae:6715.94326
[415]	validation_0-mae:6715.83695
[416]	validation_0-mae:6716.27417
[417]	validation_0-mae:6715.59904
[418]	validation_0-mae:6715.86308
[419]	validation_0-mae:6715.63372
[420]	validation_0-mae:6715.61552
[421]	validation_0-mae:6714.71299
[422]	validation_0-mae:6716.17004
[423]	validation_0-mae:6716.98253
[424]	validation_0-mae:6717.10472
[425]	validation_0-mae:6719.19434
[426]	validation_0-mae:6720.98106
[427]	validation_0-mae:6722.58546
[428]	validation_0-mae:6722.06181
[429]	validation_0-mae:6721.57382
[430]	validation_0-mae:6722.64391
[431]	validation_0-mae:6722.70415
[432]	validation_0-mae:6722.79109
[433]	validation_0-mae:6722.75894
[434]	validation_0-mae:6722.40208
[435]	validation_0-mae:6722.27473
[436]	validation_0-mae:6723.95396
[437]	validation_0-mae:6725.23254
[438]	validation_0-mae:6726.94056
[439]	validation_0-mae:6728.70948
[440]	validation_0-mae:6730.23896
[441]	validation_0-mae:6730.33569
[442]	validation_0-mae:6731.96940
[443]	validation_0-mae:6731.82320
[444]	validation_0-mae:6732.90673
[445]	validation_0-mae:6732.80881
[446]	validation_0-mae:6734.18518
[447]	validation_0-mae:6734.01051
[448]	validation_0-mae:6733.66207
[449]	validation_0-mae:6733.23729
[450]	validation_0-mae:6732.49806
[451]	validation_0-mae:6731.82010
[452]	validation_0-mae:6731.66758
[453]	validation_0-mae:6733.43351
[454]	validation_0-mae:6735.02685
[455]	validation_0-mae:6733.89647
[456]	validation_0-mae:6734.26330
[457]	validation_0-mae:6735.85512
[458]	validation_0-mae:6736.65190
[459]	validation_0-mae:6738.41764
[460]	validation_0-mae:6738.69907
[461]	validation_0-mae:6739.88049
[462]	validation_0-mae:6739.87646
[463]	validation_0-mae:6741.22432
[464]	validation_0-mae:6741.30482
[465]	validation_0-mae:6743.12711
[466]	validation_0-mae:6742.71071
[467]	validation_0-mae:6744.23547
[468]	validation_0-mae:6744.63680
[469]	validation_0-mae:6745.45725
[470]	validation_0-mae:6746.82634
[471]	validation_0-mae:6748.08014
[472]	validation_0-mae:6749.08894
[473]	validation_0-mae:6749.24229
[474]	validation_0-mae:6751.77989
[475]	validation_0-mae:6752.37748
[476]	validation_0-mae:6753.18480
[477]	validation_0-mae:6754.16984
[478]	validation_0-mae:6753.89946
[479]	validation_0-mae:6754.39861
[480]	validation_0-mae:6754.90958
[481]	validation_0-mae:6754.97441
[482]	validation_0-mae:6755.53067
[483]	validation_0-mae:6756.59329
[484]	validation_0-mae:6757.39844
[485]	validation_0-mae:6757.31270
[486]	validation_0-mae:6757.21463
[487]	validation_0-mae:6758.06221
[488]	validation_0-mae:6758.31509
[489]	validation_0-mae:6757.16709
[490]	validation_0-mae:6757.69996
[491]	validation_0-mae:6758.32638
[492]	validation_0-mae:6760.64729
[493]	validation_0-mae:6761.21642
[494]	validation_0-mae:6763.07789
[495]	validation_0-mae:6763.59937
[496]	validation_0-mae:6764.80828
[497]	validation_0-mae:6765.00639
[498]	validation_0-mae:6766.73331
[499]	validation_0-mae:6766.82096
[500]	validation_0-mae:6768.53670
[501]	validation_0-mae:6769.91387
[502]	validation_0-mae:6771.07031
[503]	validation_0-mae:6771.72320
[504]	validation_0-mae:6772.27908
[505]	validation_0-mae:6772.78011
[506]	validation_0-mae:6773.77179
[507]	validation_0-mae:6775.42917
[508]	validation_0-mae:6777.47948
[509]	validation_0-mae:6779.33999
[510]	validation_0-mae:6779.24503
[511]	validation_0-mae:6779.73773
[512]	validation_0-mae:6780.96007
[513]	validation_0-mae:6781.48043
[514]	validation_0-mae:6782.51119
[515]	validation_0-mae:6783.51377
[516]	validation_0-mae:6783.83151
[517]	validation_0-mae:6784.33870
[518]	validation_0-mae:6784.56178
[519]	validation_0-mae:6786.14793
[520]	validation_0-mae:6786.30032
[521]	validation_0-mae:6788.52036
[522]	validation_0-mae:6787.87545
[523]	validation_0-mae:6788.51380
[524]	validation_0-mae:6789.10192
[525]	validation_0-mae:6790.04526
[526]	validation_0-mae:6792.48173
[527]	validation_0-mae:6792.68074
[528]	validation_0-mae:6794.15143
[529]	validation_0-mae:6794.17652
[530]	validation_0-mae:6794.96032
[531]	validation_0-mae:6795.34030
[532]	validation_0-mae:6797.08001
[533]	validation_0-mae:6797.38597
[534]	validation_0-mae:6797.74578
[535]	validation_0-mae:6798.16890
[536]	validation_0-mae:6798.47448
[537]	validation_0-mae:6800.11660
[538]	validation_0-mae:6800.68758
[539]	validation_0-mae:6801.64570
[540]	validation_0-mae:6801.40953
[541]	validation_0-mae:6801.35084
[542]	validation_0-mae:6802.64421
[543]	validation_0-mae:6802.38168
[544]	validation_0-mae:6803.30103
[545]	validation_0-mae:6804.96880
[546]	validation_0-mae:6805.00085
[547]	validation_0-mae:6805.47690
[548]	validation_0-mae:6806.89367
[549]	validation_0-mae:6807.70825
[550]	validation_0-mae:6808.16256
[551]	validation_0-mae:6808.83115
[552]	validation_0-mae:6809.93002
[553]	validation_0-mae:6811.74773
[554]	validation_0-mae:6812.88717
[555]	validation_0-mae:6813.36756
[556]	validation_0-mae:6815.79431
[557]	validation_0-mae:6816.54255
[558]	validation_0-mae:6816.88744
[559]	validation_0-mae:6817.37964
[560]	validation_0-mae:6817.98517
[561]	validation_0-mae:6818.26967
[562]	validation_0-mae:6818.65519
[563]	validation_0-mae:6818.28713
[564]	validation_0-mae:6817.79295
[565]	validation_0-mae:6818.02277
[566]	validation_0-mae:6819.37008
[567]	validation_0-mae:6820.04681
[568]	validation_0-mae:6820.63625
[569]	validation_0-mae:6820.76574
[570]	validation_0-mae:6820.99939
[571]	validation_0-mae:6821.84710
[572]	validation_0-mae:6821.82955
[573]	validation_0-mae:6822.13227
[574]	validation_0-mae:6822.50602
[575]	validation_0-mae:6823.66902
[576]	validation_0-mae:6825.28210
[577]	validation_0-mae:6826.69315
[578]	validation_0-mae:6827.28481
[579]	validation_0-mae:6827.40997
[580]	validation_0-mae:6827.80525
[581]	validation_0-mae:6828.16302
[582]	validation_0-mae:6829.56580
[583]	validation_0-mae:6829.74461
[584]	validation_0-mae:6830.08344
[585]	validation_0-mae:6829.97549
[586]	validation_0-mae:6831.27268
[587]	validation_0-mae:6833.69149
[588]	validation_0-mae:6833.65719
[589]	validation_0-mae:6834.00614
[590]	validation_0-mae:6834.19781
[591]	validation_0-mae:6834.97512
[592]	validation_0-mae:6835.85949
[593]	validation_0-mae:6836.64397
[594]	validation_0-mae:6838.05103
[595]	validation_0-mae:6838.12567
[596]	validation_0-mae:6837.86916
[597]	validation_0-mae:6838.51412
[598]	validation_0-mae:6838.81698
[599]	validation_0-mae:6839.04539
[600]	validation_0-mae:6839.50448
[601]	validation_0-mae:6839.32431
[602]	validation_0-mae:6840.04290
[603]	validation_0-mae:6840.66926
[604]	validation_0-mae:6841.54269
[605]	validation_0-mae:6841.64381
[606]	validation_0-mae:6842.43376
[607]	validation_0-mae:6843.49517
[608]	validation_0-mae:6843.86087
[609]	validation_0-mae:6843.77199
[610]	validation_0-mae:6845.91560
[611]	validation_0-mae:6846.76078
[612]	validation_0-mae:6847.27677
[613]	validation_0-mae:6847.33991
[614]	validation_0-mae:6848.74519
[615]	validation_0-mae:6848.50708
[616]	validation_0-mae:6849.19596
[617]	validation_0-mae:6850.11429
[618]	validation_0-mae:6851.49470
[619]	validation_0-mae:6854.39616
[620]	validation_0-mae:6854.18664
[621]	validation_0-mae:6854.16483
[622]	validation_0-mae:6854.52949
[623]	validation_0-mae:6855.04018
[624]	validation_0-mae:6855.44464
[625]	validation_0-mae:6855.62756
[626]	validation_0-mae:6855.60233
[627]	validation_0-mae:6857.60589
[628]	validation_0-mae:6857.30857
[629]	validation_0-mae:6856.74628
[630]	validation_0-mae:6856.66229
[631]	validation_0-mae:6858.37244
[632]	validation_0-mae:6858.56027
[633]	validation_0-mae:6859.03787
[634]	validation_0-mae:6859.73253
[635]	validation_0-mae:6860.46330
[636]	validation_0-mae:6861.14520
[637]	validation_0-mae:6862.31023

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[67]	validation_0-mae:6442.02258
[68]	validation_0-mae:6396.38058
[69]	validation_0-mae:6374.18915
[70]	validation_0-mae:6357.96425
[71]	validation_0-mae:6335.55551
[72]	validation_0-mae:6318.92029
[73]	validation_0-mae:6278.89604
[74]	validation_0-mae:6260.17866
[75]	validation_0-mae:6245.01152
[76]	validation_0-mae:6228.78735
[77]	validation_0-mae:6204.91114
[78]	validation_0-mae:6168.57677
[79]	validation_0-mae:6149.51294
[80]	validation_0-mae:6130.87724
[81]	validation_0-mae:6109.78039
[82]	validation_0-mae:6093.73833
[83]	validation_0-mae:6074.12917
[84]	validation_0-mae:6051.77309
[85]	validation_0-mae:6035.19774
[86]	validation_0-mae:6014.40331
[87]	validation_0-mae:5998.25617
[88]	validation_0-mae:5981.45101
[89]	validation_0-mae:5964.77753
[90]	validation_0-mae:5949.06226
[91]	validation_0-mae:5934.04233
[92]	validation_0-mae:5919.85737
[93]	validation_0-mae:5888.91269
[94]	validation_0-mae:5882.45747
[95]	validation_0-mae:5871.53749
[96]	validation_0-mae:5862.52015
[97]	validation_0-mae:5843.09657
[98]	validation_0-mae:5816.89674
[99]	validation_0-mae:5804.00627
[100]	validation_0-mae:5796.91507
[101]	validation_0-mae:5784.22833
[102]	validation_0-mae:5772.14644
[103]	validation_0-mae:5745.33808
[104]	validation_0-mae:5732.11349
[105]	validation_0-mae:5722.90380
[106]	validation_0-mae:5714.79005
[107]	validation_0-mae:5706.96050
[108]	validation_0-mae:5699.42097
[109]	validation_0-mae:5675.29326
[110]	validation_0-mae:5666.13259
[111]	validation_0-mae:5656.64412
[112]	validation_0-mae:5646.62328
[113]	validation_0-mae:5624.09814
[114]	validation_0-mae:5613.56370
[115]	validation_0-mae:5604.78757
[116]	validation_0-mae:5595.28577
[117]	validation_0-mae:5584.76787
[118]	validation_0-mae:5576.95088
[119]	validation_0-mae:5558.56601
[120]	validation_0-mae:5550.21178
[121]	validation_0-mae:5507.56265
[122]	validation_0-mae:5503.43299
[123]	validation_0-mae:5462.63611
[124]	validation_0-mae:5423.33617
[125]	validation_0-mae:5417.81264
[126]	validation_0-mae:5413.90107
[127]	validation_0-mae:5381.04078
[128]	validation_0-mae:5344.95148
[129]	validation_0-mae:5337.35760
[130]	validation_0-mae:5310.74925
[131]	validation_0-mae:5281.78407
[132]	validation_0-mae:5277.28407
[133]	validation_0-mae:5252.59666
[134]	validation_0-mae:5246.46779
[135]	validation_0-mae:5241.32800
[136]	validation_0-mae:5223.64429
[137]	validation_0-mae:5197.44526
[138]	validation_0-mae:5168.11178
[139]	validation_0-mae:5159.72282
[140]	validation_0-mae:5152.21631
[141]	validation_0-mae:5139.78537
[142]	validation_0-mae:5131.84545
[143]	validation_0-mae:5122.43188
[144]	validation_0-mae:5096.04952
[145]	validation_0-mae:5093.15603
[146]	validation_0-mae:5089.40885
[147]	validation_0-mae:5082.86729
[148]	validation_0-mae:5060.52821
[149]	validation_0-mae:5047.82364
[150]	validation_0-mae:5044.45263
[151]	validation_0-mae:5035.24817
[152]	validation_0-mae:5025.82161
[153]	validation_0-mae:5011.16641
[154]	validation_0-mae:4999.71083
[155]	validation_0-mae:4976.54165
[156]	validation_0-mae:4971.94057
[157]	validation_0-mae:4958.20034
[158]	validation_0-mae:4948.43630
[159]	validation_0-mae:4939.68467
[160]	validation_0-mae:4922.97490
[161]	validation_0-mae:4915.68463
[162]	validation_0-mae:4906.12694
[163]	validation_0-mae:4900.25950
[164]	validation_0-mae:4894.40679
[165]	validation_0-mae:4889.49017
[166]	validation_0-mae:4878.56265
[167]	validation_0-mae:4874.58953
[168]	validation_0-mae:4865.66662
[169]	validation_0-mae:4845.15590
[170]	validation_0-mae:4837.42931
[171]	validation_0-mae:4822.49388
[172]	validation_0-mae:4806.85074
[173]	validation_0-mae:4784.72274
[174]	validation_0-mae:4780.64282
[175]	validation_0-mae:4768.17721
[176]	validation_0-mae:4757.68945
[177]	validation_0-mae:4748.83339
[178]	validation_0-mae:4729.59744
[179]	validation_0-mae:4720.30239
[180]	validation_0-mae:4710.46444
[181]	validation_0-mae:4705.41543
[182]	validation_0-mae:4699.54040
[183]	validation_0-mae:4688.65211
[184]	validation_0-mae:4670.13567
[185]	validation_0-mae:4660.42382
[186]	validation_0-mae:4652.15324
[187]	validation_0-mae:4646.47441
[188]	validation_0-mae:4638.39250
[189]	validation_0-mae:4636.13987
[190]	validation_0-mae:4631.75350
[191]	validation_0-mae:4622.07767
[192]	validation_0-mae:4616.34348
[193]	validation_0-mae:4613.99512
[194]	validation_0-mae:4607.09884
[195]	validation_0-mae:4598.80990
[196]	validation_0-mae:4591.69533
[197]	validation_0-mae:4589.92437
[198]	validation_0-mae:4583.13234
[199]	validation_0-mae:4572.42972
[200]	validation_0-mae:4568.87971
[201]	validation_0-mae:4560.80522
[202]	validation_0-mae:4558.42365
[203]	validation_0-mae:4546.70967
[204]	validation_0-mae:4541.14395
[205]	validation_0-mae:4538.67137
[206]	validation_0-mae:4531.65724
[207]	validation_0-mae:4524.82137
[208]	validation_0-mae:4523.03889
[209]	validation_0-mae:4509.17949
[210]	validation_0-mae:4497.80679
[211]	validation_0-mae:4490.30270
[212]	validation_0-mae:4484.53101
[213]	validation_0-mae:4481.94598
[214]	validation_0-mae:4472.46113
[215]	validation_0-mae:4469.69202
[216]	validation_0-mae:4459.44820
[217]	validation_0-mae:4453.91470
[218]	validation_0-mae:4447.61327
[219]	validation_0-mae:4443.00732
[220]	validation_0-mae:4441.44188
[221]	validation_0-mae:4437.15662
[222]	validation_0-mae:4429.01659
[223]	validation_0-mae:4426.15619
[224]	validation_0-mae:4425.69020
[225]	validation_0-mae:4416.01299
[226]	validation_0-mae:4412.54689
[227]	validation_0-mae:4407.62114
[228]	validation_0-mae:4399.49110
[229]	validation_0-mae:4395.24173
[230]	validation_0-mae:4392.50650
[231]	validation_0-mae:4391.26842
[232]	validation_0-mae:4388.23079
[233]	validation_0-mae:4385.16979
[234]	validation_0-mae:4380.22968
[235]	validation_0-mae:4378.44563
[236]	validation_0-mae:4373.43209
[237]	validation_0-mae:4370.03471
[238]	validation_0-mae:4367.15882
[239]	validation_0-mae:4363.04721
[240]	validation_0-mae:4361.19535
[241]	validation_0-mae:4358.35366
[242]	validation_0-mae:4355.50027
[243]	validation_0-mae:4353.29751
[244]	validation_0-mae:4344.47952
[245]	validation_0-mae:4341.32850
[246]	validation_0-mae:4332.59461
[247]	validation_0-mae:4328.82915
[248]	validation_0-mae:4326.85491
[249]	validation_0-mae:4318.10988
[250]	validation_0-mae:4310.60139
[251]	validation_0-mae:4307.85334
[252]	validation_0-mae:4301.70289
[253]	validation_0-mae:4295.75751
[254]	validation_0-mae:4293.93072
[255]	validation_0-mae:4291.46509
[256]	validation_0-mae:4286.85918
[257]	validation_0-mae:4281.62096
[258]	validation_0-mae:4276.23992
[259]	validation_0-mae:4272.61293
[260]	validation_0-mae:4269.58199
[261]	validation_0-mae:4264.75355
[262]	validation_0-mae:4261.17405
[263]	validation_0-mae:4256.44307
[264]	validation_0-mae:4251.91288
[265]	validation_0-mae:4248.53270
[266]	validation_0-mae:4246.20110
[267]	validation_0-mae:4239.93868
[268]	validation_0-mae:4238.95275
[269]	validation_0-mae:4236.54108
[270]	validation_0-mae:4232.00659
[271]	validation_0-mae:4225.67201
[272]	validation_0-mae:4223.50801
[273]	validation_0-mae:4221.29674
[274]	validation_0-mae:4216.93027
[275]	validation_0-mae:4211.87653
[276]	validation_0-mae:4208.07372
[277]	validation_0-mae:4206.51936
[278]	validation_0-mae:4203.89770
[279]	validation_0-mae:4196.68449
[280]	validation_0-mae:4193.95578
[281]	validation_0-mae:4191.42186
[282]	validation_0-mae:4190.06965
[283]	validation_0-mae:4188.85216
[284]	validation_0-mae:4187.11364
[285]	validation_0-mae:4182.99803
[286]	validation_0-mae:4180.20383
[287]	validation_0-mae:4176.51740
[288]	validation_0-mae:4174.42447
[289]	validation_0-mae:4172.61189
[290]	validation_0-mae:4167.57425
[291]	validation_0-mae:4166.19681
[292]	validation_0-mae:4162.02865
[293]	validation_0-mae:4156.80177
[294]	validation_0-mae:4155.16883
[295]	validation_0-mae:4153.50443
[296]	validation_0-mae:4152.36794
[297]	validation_0-mae:4150.05080
[298]	validation_0-mae:4148.79576
[299]	validation_0-mae:4146.99327
[300]	validation_0-mae:4146.72366
[301]	validation_0-mae:4145.89834
[302]	validation_0-mae:4142.48391
[303]	validation_0-mae:4135.63963
[304]	validation_0-mae:4130.17156
[305]	validation_0-mae:4128.30842
[306]	validation_0-mae:4124.62643
[307]	validation_0-mae:4122.83010
[308]	validation_0-mae:4118.97276
[309]	validation_0-mae:4118.26472
[310]	validation_0-mae:4112.95090
[311]	validation_0-mae:4112.02224
[312]	validation_0-mae:4105.89008
[313]	validation_0-mae:4102.89341
[314]	validation_0-mae:4099.69878
[315]	validation_0-mae:4098.73613
[316]	validation_0-mae:4097.46740
[317]	validation_0-mae:4094.36554
[318]	validation_0-mae:4089.57927
[319]	validation_0-mae:4085.26900
[320]	validation_0-mae:4080.06143
[321]	validation_0-mae:4078.18701
[322]	validation_0-mae:4073.94816
[323]	validation_0-mae:4071.93187
[324]	validation_0-mae:4070.76912
[325]	validation_0-mae:4068.45541
[326]	validation_0-mae:4066.29738
[327]	validation_0-mae:4059.57660
[328]	validation_0-mae:4056.87482
[329]	validation_0-mae:4055.72666
[330]	validation_0-mae:4051.36564
[331]	validation_0-mae:4049.39550
[332]	validation_0-mae:4048.61871
[333]	validation_0-mae:4046.94749
[334]	validation_0-mae:4042.33121
[335]	validation_0-mae:4040.23077
[336]	validation_0-mae:4036.74464
[337]	validation_0-mae:4035.73452
[338]	validation_0-mae:4031.71539
[339]	validation_0-mae:4030.52951
[340]	validation_0-mae:4026.37224
[341]	validation_0-mae:4025.99707
[342]	validation_0-mae:4024.50552
[343]	validation_0-mae:4020.30755
[344]	validation_0-mae:4019.42590
[345]	validation_0-mae:4014.75711
[346]	validation_0-mae:4010.72182
[347]	validation_0-mae:4008.92433
[348]	validation_0-mae:4005.20938
[349]	validation_0-mae:4004.83375
[350]	validation_0-mae:4003.73093
[351]	validation_0-mae:4003.26647
[352]	validation_0-mae:3999.71932
[353]	validation_0-mae:3997.00399
[354]	validation_0-mae:3995.19635
[355]	validation_0-mae:3990.46164
[356]	validation_0-mae:3986.92415
[357]	validation_0-mae:3983.18791
[358]	validation_0-mae:3982.79366
[359]	validation_0-mae:3980.72323
[360]	validation_0-mae:3980.71654
[361]	validation_0-mae:3978.10727
[362]	validation_0-mae:3975.66433
[363]	validation_0-mae:3973.32557
[364]	validation_0-mae:3971.98411
[365]	validation_0-mae:3971.05184
[366]	validation_0-mae:3968.42918
[367]	validation_0-mae:3965.17034
[368]	validation_0-mae:3962.47063
[369]	validation_0-mae:3959.52888
[370]	validation_0-mae:3959.90905
[371]	validation_0-mae:3955.64560
[372]	validation_0-mae:3954.44042
[373]	validation_0-mae:3951.08949
[374]	validation_0-mae:3947.82451
[375]	validation_0-mae:3945.43286
[376]	validation_0-mae:3945.03491
[377]	validation_0-mae:3942.77384
[378]	validation_0-mae:3939.52134
[379]	validation_0-mae:3938.49138
[380]	validation_0-mae:3936.77329
[381]	validation_0-mae:3933.15535
[382]	validation_0-mae:3930.36928
[383]	validation_0-mae:3929.16488
[384]	validation_0-mae:3924.86416
[385]	validation_0-mae:3925.06287
[386]	validation_0-mae:3923.12925
[387]	validation_0-mae:3923.66812
[388]	validation_0-mae:3921.88563
[389]	validation_0-mae:3917.69245
[390]	validation_0-mae:3913.86396
[391]	validation_0-mae:3912.55848
[392]	validation_0-mae:3911.87500
[393]	validation_0-mae:3909.50270
[394]	validation_0-mae:3908.20423
[395]	validation_0-mae:3903.88878
[396]	validation_0-mae:3902.04624
[397]	validation_0-mae:3899.99200
[398]	validation_0-mae:3899.04677
[399]	validation_0-mae:3897.30428
[400]	validation_0-mae:3893.54723
[401]	validation_0-mae:3891.29493
[402]	validation_0-mae:3887.37028
[403]	validation_0-mae:3884.63675
[404]	validation_0-mae:3882.82068
[405]	validation_0-mae:3880.01887
[406]	validation_0-mae:3878.60330
[407]	validation_0-mae:3875.53816
[408]	validation_0-mae:3873.52654
[409]	validation_0-mae:3871.94833
[410]	validation_0-mae:3871.76567
[411]	validation_0-mae:3871.60434
[412]	validation_0-mae:3869.61342
[413]	validation_0-mae:3868.92910
[414]	validation_0-mae:3869.05082
[415]	validation_0-mae:3865.58160
[416]	validation_0-mae:3864.15726
[417]	validation_0-mae:3862.70935
[418]	validation_0-mae:3860.77852
[419]	validation_0-mae:3855.61222
[420]	validation_0-mae:3854.46261
[421]	validation_0-mae:3851.43883
[422]	validation_0-mae:3848.85935
[423]	validation_0-mae:3845.61502
[424]	validation_0-mae:3846.31959
[425]	validation_0-mae:3844.83377
[426]	validation_0-mae:3841.33807
[427]	validation_0-mae:3839.38821
[428]	validation_0-mae:3836.80443
[429]	validation_0-mae:3835.11756
[430]	validation_0-mae:3834.64975
[431]	validation_0-mae:3833.54290
[432]	validation_0-mae:3831.62114
[433]	validation_0-mae:3828.77437
[434]	validation_0-mae:3823.42360
[435]	validation_0-mae:3817.79072
[436]	validation_0-mae:3816.49241
[437]	validation_0-mae:3813.90859
[438]	validation_0-mae:3812.47020
[439]	validation_0-mae:3812.75875
[440]	validation_0-mae:3811.13230
[441]	validation_0-mae:3809.51842
[442]	validation_0-mae:3807.33989
[443]	validation_0-mae:3805.89311
[444]	validation_0-mae:3804.02474
[445]	validation_0-mae:3802.63679
[446]	validation_0-mae:3800.87183
[447]	validation_0-mae:3798.78171
[448]	validation_0-mae:3798.47149
[449]	validation_0-mae:3797.56021
[450]	validation_0-mae:3795.32201
[451]	validation_0-mae:3795.22752
[452]	validation_0-mae:3794.49705
[453]	validation_0-mae:3793.78950
[454]	validation_0-mae:3791.44160
[455]	validation_0-mae:3789.92005
[456]	validation_0-mae:3787.74280
[457]	validation_0-mae:3788.60568
[458]	validation_0-mae:3785.14935
[459]	validation_0-mae:3784.28608
[460]	validation_0-mae:3784.42073
[461]	validation_0-mae:3781.02376
[462]	validation_0-mae:3779.06598
[463]	validation_0-mae:3777.92484
[464]	validation_0-mae:3774.87184
[465]	validation_0-mae:3771.68896
[466]	validation_0-mae:3770.23657
[467]	validation_0-mae:3768.88658
[468]	validation_0-mae:3767.82149
[469]	validation_0-mae:3766.43069
[470]	validation_0-mae:3766.21568
[471]	validation_0-mae:3765.29122
[472]	validation_0-mae:3763.25165
[473]	validation_0-mae:3762.95715
[474]	validation_0-mae:3760.51599
[475]	validation_0-mae:3757.86090
[476]	validation_0-mae:3757.00740
[477]	validation_0-mae:3755.25371
[478]	validation_0-mae:3753.12449
[479]	validation_0-mae:3751.82355
[480]	validation_0-mae:3751.91009
[481]	validation_0-mae:3750.68651
[482]	validation_0-mae:3750.04206
[483]	validation_0-mae:3747.23224
[484]	validation_0-mae:3746.12366
[485]	validation_0-mae:3744.23978
[486]	validation_0-mae:3743.02772
[487]	validation_0-mae:3743.69077
[488]	validation_0-mae:3742.02933
[489]	validation_0-mae:3739.79803
[490]	validation_0-mae:3734.40968
[491]	validation_0-mae:3733.13104
[492]	validation_0-mae:3728.66134
[493]	validation_0-mae:3728.18735
[494]	validation_0-mae:3726.51898
[495]	validation_0-mae:3724.10632
[496]	validation_0-mae:3722.71872
[497]	validation_0-mae:3722.19933
[498]	validation_0-mae:3721.36627
[499]	validation_0-mae:3719.98880
[500]	validation_0-mae:3718.88682
[501]	validation_0-mae:3717.04450
[502]	validation_0-mae:3716.01951
[503]	validation_0-mae:3715.17822
[504]	validation_0-mae:3712.19480
[505]	validation_0-mae:3712.91930
[506]	validation_0-mae:3711.95420
[507]	validation_0-mae:3712.16513
[508]	validation_0-mae:3708.48001
[509]	validation_0-mae:3707.26239
[510]	validation_0-mae:3706.08463
[511]	validation_0-mae:3704.62356
[512]	validation_0-mae:3703.58041
[513]	validation_0-mae:3702.01615
[514]	validation_0-mae:3699.97873
[515]	validation_0-mae:3697.48366
[516]	validation_0-mae:3697.17008
[517]	validation_0-mae:3697.52357
[518]	validation_0-mae:3697.24143
[519]	validation_0-mae:3695.74040
[520]	validation_0-mae:3694.06428
[521]	validation_0-mae:3689.56404
[522]	validation_0-mae:3688.29550
[523]	validation_0-mae:3686.65872
[524]	validation_0-mae:3684.61083
[525]	validation_0-mae:3683.04279
[526]	validation_0-mae:3681.74917
[527]	validation_0-mae:3682.72923
[528]	validation_0-mae:3681.21873
[529]	validation_0-mae:3680.30550
[530]	validation_0-mae:3679.65697
[531]	validation_0-mae:3678.91194
[532]	validation_0-mae:3676.86788
[533]	validation_0-mae:3676.12026
[534]	validation_0-mae:3672.26558
[535]	validation_0-mae:3672.45429
[536]	validation_0-mae:3670.91298
[537]	validation_0-mae:3668.04901
[538]	validation_0-mae:3666.53508
[539]	validation_0-mae:3664.56034
[540]	validation_0-mae:3662.85645
[541]	validation_0-mae:3662.09572
[542]	validation_0-mae:3660.56593
[543]	validation_0-mae:3657.01574
[544]	validation_0-mae:3654.75795
[545]	validation_0-mae:3653.35288
[546]	validation_0-mae:3652.17235
[547]	validation_0-mae:3651.45725
[548]	validation_0-mae:3652.27523
[549]	validation_0-mae:3650.72086
[550]	validation_0-mae:3649.40256
[551]	validation_0-mae:3649.43351
[552]	validation_0-mae:3649.09045
[553]	validation_0-mae:3648.11441
[554]	validation_0-mae:3647.44343
[555]	validation_0-mae:3646.14428
[556]	validation_0-mae:3645.31903
[557]	validation_0-mae:3645.51982
[558]	validation_0-mae:3645.57194
[559]	validation_0-mae:3645.46245
[560]	validation_0-mae:3644.25064
[561]	validation_0-mae:3642.34209
[562]	validation_0-mae:3642.09206
[563]	validation_0-mae:3641.86296
[564]	validation_0-mae:3640.86843
[565]	validation_0-mae:3639.52424
[566]	validation_0-mae:3638.17184
[567]	validation_0-mae:3638.24753
[568]	validation_0-mae:3636.58520
[569]	validation_0-mae:3636.65153
[570]	validation_0-mae:3635.55224
[571]	validation_0-mae:3634.45159
[572]	validation_0-mae:3633.28589
[573]	validation_0-mae:3632.09041
[574]	validation_0-mae:3632.75228
[575]	validation_0-mae:3631.62569
[576]	validation_0-mae:3629.68513
[577]	validation_0-mae:3627.79249
[578]	validation_0-mae:3627.56241
[579]	validation_0-mae:3628.23405
[580]	validation_0-mae:3626.92956
[581]	validation_0-mae:3627.18449
[582]	validation_0-mae:3626.32608
[583]	validation_0-mae:3625.97044
[584]	validation_0-mae:3624.96185
[585]	validation_0-mae:3622.74682
[586]	validation_0-mae:3622.92648
[587]	validation_0-mae:3622.39855
[588]	validation_0-mae:3621.18111
[589]	validation_0-mae:3620.47317
[590]	validation_0-mae:3618.16489
[591]	validation_0-mae:3617.58651
[592]	validation_0-mae:3616.88720
[593]	validation_0-mae:3616.91537
[594]	validation_0-mae:3615.41675
[595]	validation_0-mae:3614.13324
[596]	validation_0-mae:3613.21360
[597]	validation_0-mae:3612.46668
[598]	validation_0-mae:3611.03101
[599]	validation_0-mae:3610.42086
[600]	validation_0-mae:3609.88363
[601]	validation_0-mae:3608.57641
[602]	validation_0-mae:3606.07806
[603]	validation_0-mae:3606.67548
[604]	validation_0-mae:3605.98513
[605]	validation_0-mae:3603.95084
[606]	validation_0-mae:3604.01407
[607]	validation_0-mae:3604.08176
[608]	validation_0-mae:3602.17909
[609]	validation_0-mae:3601.17131
[610]	validation_0-mae:3600.85200
[611]	validation_0-mae:3600.19639
[612]	validation_0-mae:3599.01739
[613]	validation_0-mae:3598.21862
[614]	validation_0-mae:3595.71607
[615]	validation_0-mae:3595.05687
[616]	validation_0-mae:3593.38647
[617]	validation_0-mae:3590.60302
[618]	validation_0-mae:3589.25451
[619]	validation_0-mae:3587.76397
[620]	validation_0-mae:3587.77975
[621]	validation_0-mae:3587.36416
[622]	validation_0-mae:3586.95226
[623]	validation_0-mae:3586.33530
[624]	validation_0-mae:3586.01626
[625]	validation_0-mae:3585.27647
[626]	validation_0-mae:3583.46817
[627]	validation_0-mae:3582.90000
[628]	validation_0-mae:3582.47618
[629]	validation_0-mae:3582.23491
[630]	validation_0-mae:3581.84593
[631]	validation_0-mae:3582.37553
[632]	validation_0-mae:3581.32454
[633]	validation_0-mae:3579.12857
[634]	validation_0-mae:3578.97262
[635]	validation_0-mae:3578.88564
[636]	validation_0-mae:3577.34741
[637]	validation_0-mae:3577.49840
[638]	validation_0-mae:3576.73295
[639]	validation_0-mae:3575.50270
[640]	validation_0-mae:3574.52590
[641]	validation_0-mae:3573.31629
[642]	validation_0-mae:3573.28239
[643]	validation_0-mae:3571.03571
[644]	validation_0-mae:3570.55818
[645]	validation_0-mae:3569.49563
[646]	validation_0-mae:3569.51203
[647]	validation_0-mae:3568.12410
[648]	validation_0-mae:3567.91466
[649]	validation_0-mae:3566.95432
[650]	validation_0-mae:3566.44713
[651]	validation_0-mae:3565.83772
[652]	validation_0-mae:3565.36180
[653]	validation_0-mae:3564.46880
[654]	validation_0-mae:3563.21542
[655]	validation_0-mae:3562.19092

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[60]	validation_0-mae:8309.80271
[61]	validation_0-mae:8293.53270
[62]	validation_0-mae:8278.74882
[63]	validation_0-mae:8259.48741
[64]	validation_0-mae:8234.66651
[65]	validation_0-mae:8217.72450
[66]	validation_0-mae:8197.82690
[67]	validation_0-mae:8180.20477
[68]	validation_0-mae:8162.08528
[69]	validation_0-mae:8152.87583
[70]	validation_0-mae:8125.40249
[71]	validation_0-mae:8097.84296
[72]	validation_0-mae:8079.23181
[73]	validation_0-mae:8070.28286
[74]	validation_0-mae:8054.72448
[75]	validation_0-mae:8031.10714
[76]	validation_0-mae:8021.70648
[77]	validation_0-mae:8000.25905
[78]	validation_0-mae:7988.26399
[79]	validation_0-mae:7966.07125
[80]	validation_0-mae:7952.46956
[81]	validation_0-mae:7937.60669
[82]	validation_0-mae:7917.37834
[83]	validation_0-mae:7903.09318
[84]	validation_0-mae:7889.27508
[85]	validation_0-mae:7873.55027
[86]	validation_0-mae:7863.27744
[87]	validation_0-mae:7834.01786
[88]	validation_0-mae:7824.86417
[89]	validation_0-mae:7815.35671
[90]	validation_0-mae:7801.23236
[91]	validation_0-mae:7792.51300
[92]	validation_0-mae:7781.58553
[93]	validation_0-mae:7775.65463
[94]	validation_0-mae:7763.08680
[95]	validation_0-mae:7744.23450
[96]	validation_0-mae:7735.59753
[97]	validation_0-mae:7729.75091
[98]	validation_0-mae:7720.36332
[99]	validation_0-mae:7702.15456
[100]	validation_0-mae:7696.17335
[101]	validation_0-mae:7691.00670
[102]	validation_0-mae:7679.64456
[103]	validation_0-mae:7663.37586
[104]	validation_0-mae:7653.97149
[105]	validation_0-mae:7642.71612
[106]	validation_0-mae:7636.39069
[107]	validation_0-mae:7620.29047
[108]	validation_0-mae:7616.27820
[109]	validation_0-mae:7609.19695
[110]	validation_0-mae:7593.38786
[111]	validation_0-mae:7589.85095
[112]	validation_0-mae:7580.12298
[113]	validation_0-mae:7566.07685
[114]	validation_0-mae:7557.01108
[115]	validation_0-mae:7551.12301
[116]	validation_0-mae:7545.69654
[117]	validation_0-mae:7533.76327
[118]	validation_0-mae:7519.58934
[119]	validation_0-mae:7507.60739
[120]	validation_0-mae:7498.65876
[121]	validation_0-mae:7487.20787
[122]	validation_0-mae:7474.99439
[123]	validation_0-mae:7468.59973
[124]	validation_0-mae:7458.18156
[125]	validation_0-mae:7428.49529
[126]	validation_0-mae:7420.56173
[127]	validation_0-mae:7414.98134
[128]	validation_0-mae:7386.01011
[129]	validation_0-mae:7381.48979
[130]	validation_0-mae:7367.88613
[131]	validation_0-mae:7360.55879
[132]	validation_0-mae:7354.60409
[133]	validation_0-mae:7347.49656
[134]	validation_0-mae:7340.25869
[135]	validation_0-mae:7328.45874
[136]	validation_0-mae:7320.00529
[137]	validation_0-mae:7314.23968
[138]	validation_0-mae:7304.50513
[139]	validation_0-mae:7293.61150
[140]	validation_0-mae:7269.95182
[141]	validation_0-mae:7259.96376
[142]	validation_0-mae:7254.58567
[143]	validation_0-mae:7247.06180
[144]	validation_0-mae:7237.77706
[145]	validation_0-mae:7231.27750
[146]	validation_0-mae:7227.12683
[147]	validation_0-mae:7218.28648
[148]	validation_0-mae:7214.30464
[149]	validation_0-mae:7204.68716
[150]	validation_0-mae:7197.66998
[151]	validation_0-mae:7191.87210
[152]	validation_0-mae:7179.70952
[153]	validation_0-mae:7172.98166
[154]	validation_0-mae:7165.20421
[155]	validation_0-mae:7156.63514
[156]	validation_0-mae:7152.44661
[157]	validation_0-mae:7149.20035
[158]	validation_0-mae:7133.94095
[159]	validation_0-mae:7127.38872
[160]	validation_0-mae:7120.96202
[161]	validation_0-mae:7112.50552
[162]	validation_0-mae:7096.57370
[163]	validation_0-mae:7093.01849
[164]	validation_0-mae:7088.23997
[165]	validation_0-mae:7082.29484
[166]	validation_0-mae:7076.10263
[167]	validation_0-mae:7066.58617
[168]	validation_0-mae:7061.04048
[169]	validation_0-mae:7055.91751
[170]	validation_0-mae:7040.51104
[171]	validation_0-mae:7032.34067
[172]	validation_0-mae:7018.21895
[173]	validation_0-mae:7011.40334
[174]	validation_0-mae:7005.71995
[175]	validation_0-mae:7000.91915
[176]	validation_0-mae:6987.15636
[177]	validation_0-mae:6982.07349
[178]	validation_0-mae:6977.11337
[179]	validation_0-mae:6964.59310
[180]	validation_0-mae:6962.43552
[181]	validation_0-mae:6958.02704
[182]	validation_0-mae:6953.88395
[183]	validation_0-mae:6949.78671
[184]	validation_0-mae:6945.31685
[185]	validation_0-mae:6934.97820
[186]	validation_0-mae:6932.28372
[187]	validation_0-mae:6920.20803
[188]	validation_0-mae:6917.31606
[189]	validation_0-mae:6911.56591
[190]	validation_0-mae:6909.48303
[191]	validation_0-mae:6907.11763
[192]	validation_0-mae:6896.65042
[193]	validation_0-mae:6893.37458
[194]	validation_0-mae:6888.29946
[195]	validation_0-mae:6887.16814
[196]	validation_0-mae:6877.57399
[197]	validation_0-mae:6873.86284
[198]	validation_0-mae:6867.82812
[199]	validation_0-mae:6865.43799
[200]	validation_0-mae:6856.21063
[201]	validation_0-mae:6852.96638
[202]	validation_0-mae:6851.40522
[203]	validation_0-mae:6849.17375
[204]	validation_0-mae:6841.06078
[205]	validation_0-mae:6839.79515
[206]	validation_0-mae:6837.40002
[207]	validation_0-mae:6833.53984
[208]	validation_0-mae:6829.01876
[209]	validation_0-mae:6820.72047
[210]	validation_0-mae:6817.09314
[211]	validation_0-mae:6814.25517
[212]	validation_0-mae:6813.83116
[213]	validation_0-mae:6809.74536
[214]	validation_0-mae:6804.19969
[215]	validation_0-mae:6801.35472
[216]	validation_0-mae:6799.86421
[217]	validation_0-mae:6798.74765
[218]	validation_0-mae:6792.60692
[219]	validation_0-mae:6790.66050
[220]	validation_0-mae:6789.60075
[221]	validation_0-mae:6789.07714
[222]	validation_0-mae:6782.82773
[223]	validation_0-mae:6779.40279
[224]	validation_0-mae:6773.97964
[225]	validation_0-mae:6768.59657
[226]	validation_0-mae:6767.49536
[227]	validation_0-mae:6767.30607
[228]	validation_0-mae:6766.86867
[229]	validation_0-mae:6761.22091
[230]	validation_0-mae:6758.43357
[231]	validation_0-mae:6757.93582
[232]	validation_0-mae:6753.50597
[233]	validation_0-mae:6751.58426
[234]	validation_0-mae:6751.17442
[235]	validation_0-mae:6750.51145
[236]	validation_0-mae:6748.66072
[237]	validation_0-mae:6746.64271
[238]	validation_0-mae:6746.01091
[239]	validation_0-mae:6744.64577
[240]	validation_0-mae:6739.21849
[241]	validation_0-mae:6739.53878
[242]	validation_0-mae:6738.48740
[243]	validation_0-mae:6735.70451
[244]	validation_0-mae:6735.48831
[245]	validation_0-mae:6732.24881
[246]	validation_0-mae:6728.41815
[247]	validation_0-mae:6727.65363
[248]	validation_0-mae:6726.13311
[249]	validation_0-mae:6724.85081
[250]	validation_0-mae:6722.85761
[251]	validation_0-mae:6718.82465
[252]	validation_0-mae:6718.39923
[253]	validation_0-mae:6717.32205
[254]	validation_0-mae:6712.64913
[255]	validation_0-mae:6711.67281
[256]	validation_0-mae:6710.13929
[257]	validation_0-mae:6708.06345
[258]	validation_0-mae:6706.94326
[259]	validation_0-mae:6702.27904
[260]	validation_0-mae:6700.61764
[261]	validation_0-mae:6699.01801
[262]	validation_0-mae:6696.37959
[263]	validation_0-mae:6694.70840
[264]	validation_0-mae:6694.09993
[265]	validation_0-mae:6692.16896
[266]	validation_0-mae:6688.01308
[267]	validation_0-mae:6686.70727
[268]	validation_0-mae:6686.19624
[269]	validation_0-mae:6685.18729
[270]	validation_0-mae:6684.61708
[271]	validation_0-mae:6681.94847
[272]	validation_0-mae:6680.98233
[273]	validation_0-mae:6677.13094
[274]	validation_0-mae:6677.14050
[275]	validation_0-mae:6674.38928
[276]	validation_0-mae:6674.07144
[277]	validation_0-mae:6672.69107
[278]	validation_0-mae:6672.83189
[279]	validation_0-mae:6670.64316
[280]	validation_0-mae:6668.57745
[281]	validation_0-mae:6667.91000
[282]	validation_0-mae:6669.31144
[283]	validation_0-mae:6666.58643
[284]	validation_0-mae:6664.19162
[285]	validation_0-mae:6664.52855
[286]	validation_0-mae:6663.81112
[287]	validation_0-mae:6660.56646
[288]	validation_0-mae:6661.64056
[289]	validation_0-mae:6659.86126
[290]	validation_0-mae:6657.28336
[291]	validation_0-mae:6655.75415
[292]	validation_0-mae:6655.02462
[293]	validation_0-mae:6654.68804
[294]	validation_0-mae:6654.82569
[295]	validation_0-mae:6653.65243
[296]	validation_0-mae:6651.04456
[297]	validation_0-mae:6650.05995
[298]	validation_0-mae:6650.32076
[299]	validation_0-mae:6649.29831
[300]	validation_0-mae:6649.04607
[301]	validation_0-mae:6648.50389
[302]	validation_0-mae:6647.26196
[303]	validation_0-mae:6645.44308
[304]	validation_0-mae:6646.51618
[305]	validation_0-mae:6645.67572
[306]	validation_0-mae:6645.58584
[307]	validation_0-mae:6646.28174
[308]	validation_0-mae:6645.10377
[309]	validation_0-mae:6643.83831
[310]	validation_0-mae:6642.71473
[311]	validation_0-mae:6641.77897
[312]	validation_0-mae:6642.20063
[313]	validation_0-mae:6641.82991
[314]	validation_0-mae:6642.95064
[315]	validation_0-mae:6642.23514
[316]	validation_0-mae:6640.52434
[317]	validation_0-mae:6640.65814
[318]	validation_0-mae:6640.82100
[319]	validation_0-mae:6639.98354
[320]	validation_0-mae:6639.65273
[321]	validation_0-mae:6640.06915
[322]	validation_0-mae:6638.19585
[323]	validation_0-mae:6637.54729
[324]	validation_0-mae:6637.82189
[325]	validation_0-mae:6638.47449
[326]	validation_0-mae:6637.80143
[327]	validation_0-mae:6636.11056
[328]	validation_0-mae:6636.59209
[329]	validation_0-mae:6637.47972
[330]	validation_0-mae:6636.18144
[331]	validation_0-mae:6635.75396
[332]	validation_0-mae:6635.52778
[333]	validation_0-mae:6637.12838
[334]	validation_0-mae:6635.71211
[335]	validation_0-mae:6634.03739
[336]	validation_0-mae:6633.22798
[337]	validation_0-mae:6633.62410
[338]	validation_0-mae:6634.27870
[339]	validation_0-mae:6633.80070
[340]	validation_0-mae:6633.51411
[341]	validation_0-mae:6634.79300
[342]	validation_0-mae:6634.67836
[343]	validation_0-mae:6634.66272
[344]	validation_0-mae:6634.52416
[345]	validation_0-mae:6635.19049
[346]	validation_0-mae:6635.16990
[347]	validation_0-mae:6635.00359
[348]	validation_0-mae:6634.42924
[349]	validation_0-mae:6633.44556
[350]	validation_0-mae:6633.89581
[351]	validation_0-mae:6633.66424
[352]	validation_0-mae:6633.93756
[353]	validation_0-mae:6633.45919
[354]	validation_0-mae:6633.33806
[355]	validation_0-mae:6632.46881
[356]	validation_0-mae:6631.66221
[357]	validation_0-mae:6631.54212
[358]	validation_0-mae:6631.24173
[359]	validation_0-mae:6629.72699
[360]	validation_0-mae:6629.14065
[361]	validation_0-mae:6628.22599
[362]	validation_0-mae:6628.87765
[363]	validation_0-mae:6628.89280
[364]	validation_0-mae:6629.30650
[365]	validation_0-mae:6628.38208
[366]	validation_0-mae:6628.12871
[367]	validation_0-mae:6628.88419
[368]	validation_0-mae:6628.48534
[369]	validation_0-mae:6628.07141
[370]	validation_0-mae:6628.11253
[371]	validation_0-mae:6627.43105
[372]	validation_0-mae:6627.90566
[373]	validation_0-mae:6627.25008
[374]	validation_0-mae:6626.57419
[375]	validation_0-mae:6625.90109
[376]	validation_0-mae:6625.77038
[377]	validation_0-mae:6626.85918
[378]	validation_0-mae:6626.30330
[379]	validation_0-mae:6626.69555
[380]	validation_0-mae:6626.51766
[381]	validation_0-mae:6626.34266
[382]	validation_0-mae:6625.68518
[383]	validation_0-mae:6624.73647
[384]	validation_0-mae:6625.40402
[385]	validation_0-mae:6625.11106
[386]	validation_0-mae:6625.61415
[387]	validation_0-mae:6624.27018
[388]	validation_0-mae:6623.17466
[389]	validation_0-mae:6624.21328
[390]	validation_0-mae:6624.29904
[391]	validation_0-mae:6623.71645
[392]	validation_0-mae:6623.98019
[393]	validation_0-mae:6623.64375
[394]	validation_0-mae:6623.41578
[395]	validation_0-mae:6622.33120
[396]	validation_0-mae:6621.90209
[397]	validation_0-mae:6620.52147
[398]	validation_0-mae:6620.41282
[399]	validation_0-mae:6620.57128
[400]	validation_0-mae:6620.78640
[401]	validation_0-mae:6620.82458
[402]	validation_0-mae:6619.94630
[403]	validation_0-mae:6620.09290
[404]	validation_0-mae:6620.47322
[405]	validation_0-mae:6620.84782
[406]	validation_0-mae:6619.86761
[407]	validation_0-mae:6620.43267
[408]	validation_0-mae:6620.26512
[409]	validation_0-mae:6620.52882
[410]	validation_0-mae:6621.24090
[411]	validation_0-mae:6621.74982
[412]	validation_0-mae:6622.48691
[413]	validation_0-mae:6622.34231
[414]	validation_0-mae:6622.74772
[415]	validation_0-mae:6622.12867
[416]	validation_0-mae:6621.26279
[417]	validation_0-mae:6620.80114
[418]	validation_0-mae:6622.00315
[419]	validation_0-mae:6621.82911
[420]	validation_0-mae:6621.37312
[421]	validation_0-mae:6621.18412
[422]	validation_0-mae:6621.06113
[423]	validation_0-mae:6621.21858
[424]	validation_0-mae:6621.88452
[425]	validation_0-mae:6621.82388
[426]	validation_0-mae:6621.35568
[427]	validation_0-mae:6620.77529
[428]	validation_0-mae:6621.07667
[429]	validation_0-mae:6620.40506
[430]	validation_0-mae:6619.57791
[431]	validation_0-mae:6618.89450
[432]	validation_0-mae:6619.70606
[433]	validation_0-mae:6619.86817
[434]	validation_0-mae:6620.20861
[435]	validation_0-mae:6619.75231
[436]	validation_0-mae:6619.54017
[437]	validation_0-mae:6620.38322
[438]	validation_0-mae:6619.60251
[439]	validation_0-mae:6619.50667
[440]	validation_0-mae:6621.09703
[441]	validation_0-mae:6621.67943
[442]	validation_0-mae:6622.20324
[443]	validation_0-mae:6623.65533
[444]	validation_0-mae:6624.13646
[445]	validation_0-mae:6624.03838
[446]	validation_0-mae:6624.41750
[447]	validation_0-mae:6624.05337
[448]	validation_0-mae:6625.25806
[449]	validation_0-mae:6626.20886
[450]	validation_0-mae:6626.17081
[451]	validation_0-mae:6626.17649
[452]	validation_0-mae:6626.88499
[453]	validation_0-mae:6625.75691
[454]	validation_0-mae:6626.53705
[455]	validation_0-mae:6625.51237
[456]	validation_0-mae:6626.19355
[457]	validation_0-mae:6627.15449
[458]	validation_0-mae:6627.37909
[459]	validation_0-mae:6626.59664
[460]	validation_0-mae:6626.38616
[461]	validation_0-mae:6625.68642
[462]	validation_0-mae:6625.36765
[463]	validation_0-mae:6624.82981
[464]	validation_0-mae:6624.40772
[465]	validation_0-mae:6624.11582
[466]	validation_0-mae:6624.06659
[467]	validation_0-mae:6623.51811
[468]	validation_0-mae:6623.26046
[469]	validation_0-mae:6622.84813
[470]	validation_0-mae:6623.92528
[471]	validation_0-mae:6623.80368
[472]	validation_0-mae:6624.27956
[473]	validation_0-mae:6623.99184
[474]	validation_0-mae:6623.89944
[475]	validation_0-mae:6623.84702
[476]	validation_0-mae:6624.05040
[477]	validation_0-mae:6622.89120
[478]	validation_0-mae:6623.63390
[479]	validation_0-mae:6623.59356
[480]	validation_0-mae:6622.89469
[481]	validation_0-mae:6622.32708
[482]	validation_0-mae:6622.72022
[483]	validation_0-mae:6622.32561
[484]	validation_0-mae:6622.33823
[485]	validation_0-mae:6622.98325
[486]	validation_0-mae:6622.91823
[487]	validation_0-mae:6623.99996
[488]	validation_0-mae:6625.19158
[489]	validation_0-mae:6625.02810
[490]	validation_0-mae:6624.81014
[491]	validation_0-mae:6625.77488
[492]	validation_0-mae:6625.73124
[493]	validation_0-mae:6626.48491
[494]	validation_0-mae:6627.01396
[495]	validation_0-mae:6626.11060
[496]	validation_0-mae:6626.10825
[497]	validation_0-mae:6626.28948
[498]	validation_0-mae:6625.58927
[499]	validation_0-mae:6626.45234
[500]	validation_0-mae:6626.98157
[501]	validation_0-mae:6627.31395
[502]	validation_0-mae:6627.38432
[503]	validation_0-mae:6627.88784
[504]	validation_0-mae:6627.48067
[505]	validation_0-mae:6628.15732
[506]	validation_0-mae:6629.21959
[507]	validation_0-mae:6630.99194
[508]	validation_0-mae:6632.06282
[509]	validation_0-mae:6631.91672
[510]	validation_0-mae:6631.71818
[511]	validation_0-mae:6631.96178
[512]	validation_0-mae:6631.85170
[513]	validation_0-mae:6632.30264
[514]	validation_0-mae:6631.60434
[515]	validation_0-mae:6631.25806
[516]	validation_0-mae:6631.93320
[517]	validation_0-mae:6632.41835
[518]	validation_0-mae:6632.08990
[519]	validation_0-mae:6633.16933
[520]	validation_0-mae:6633.02480
[521]	validation_0-mae:6632.92311
[522]	validation_0-mae:6633.74390
[523]	validation_0-mae:6633.13095
[524]	validation_0-mae:6632.83095
[525]	validation_0-mae:6632.50145
[526]	validation_0-mae:6632.93512
[527]	validation_0-mae:6633.60101
[528]	validation_0-mae:6632.88879
[529]	validation_0-mae:6631.97221
[530]	validation_0-mae:6631.42883
[531]	validation_0-mae:6630.70395
[532]	validation_0-mae:6631.66626
[533]	validation_0-mae:6631.91516
[534]	validation_0-mae:6631.45392
[535]	validation_0-mae:6630.76112
[536]	validation_0-mae:6631.26693
[537]	validation_0-mae:6632.33720
[538]	validation_0-mae:6632.13196
[539]	validation_0-mae:6631.05963
[540]	validation_0-mae:6630.85819
[541]	validation_0-mae:6630.78176
[542]	validation_0-mae:6631.17563
[543]	validation_0-mae:6631.76055
[544]	validation_0-mae:6632.32910
[545]	validation_0-mae:6633.51654
[546]	validation_0-mae:6634.91130
[547]	validation_0-mae:6635.38089
[548]	validation_0-mae:6635.28718
[0]	validation_0-mae:12938.54723
[1]	validation_0-mae:12610.87517
[2]	validation_0-mae:12291.79043
[3]	validation_0-mae:12007.41155
[4]	validation_0-mae:11736.46867
[5]	validation_0-mae:11478.63810
[6]	validation_0-mae:11225.99200
[7]	validation_0-mae:10992.26784
[8]	validation_0-mae:10779.78019
[9]	validation_0-mae:10567.47940
[10]	validation_0-mae:10375.14488
[11]	validation_0-mae:10201.97335
[12]	validation_0-mae:10032.63262
[13]	validation_0-mae:9869.16275
[14]	validation_0-mae:9710.07421
[15]	validation_0-mae:9556.53465
[16]	validation_0-mae:9406.43360
[17]	validation_0-mae:9263.31944
[18]	validation_0-mae:9134.78906
[19]	validation_0-mae:9011.73219
[20]	validation_0-mae:8892.60378
[21]	validation_0-mae:8763.05710
[22]	validation_0-mae:8649.19722
[23]	validation_0-mae:8532.07270
[24]	validation_0-mae:8422.64593
[25]	validation_0-mae:8329.11822
[26]	validation_0-mae:8228.96061
[27]	validation_0-mae:8149.67808
[28]	validation_0-mae:8057.23893
[29]	validation_0-mae:7980.87468
[30]	validation_0-mae:7906.53283
[31]	validation_0-mae:7828.20005
[32]	validation_0-mae:7767.51857
[33]	validation_0-mae:7694.04357
[34]	validation_0-mae:7632.62500
[35]	validation_0-mae:7570.18833
[36]	validation_0-mae:7503.90687
[37]	validation_0-mae:7451.83323
[38]	validation_0-mae:7396.68275
[39]	validation_0-mae:7338.64907
[40]	validation_0-mae:7286.47753
[41]	validation_0-mae:7233.08048
[42]	validation_0-mae:7180.30465
[43]	validation_0-mae:7125.80098
[44]	validation_0-mae:7080.92522
[45]	validation_0-mae:7039.31594
[46]	validation_0-mae:6995.95252
[47]	validation_0-mae:6956.09382
[48]	validation_0-mae:6915.11651
[49]	validation_0-mae:6871.77535
[50]	validation_0-mae:6836.25318
[51]	validation_0-mae:6797.29790
[52]	validation_0-mae:6759.15603
[53]	validation_0-mae:6725.55327
[54]	validation_0-mae:6693.03740
[55]	validation_0-mae:6659.87439
[56]	validation_0-mae:6628.44550
[57]	validation_0-mae:6600.17037
[58]	validation_0-mae:6566.01736
[59]	validation_0-mae:6535.07456
[60]	validation_0-mae:6503.67668
[61]	validation_0-mae:6476.75881
[62]	validation_0-mae:6444.92722

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[63]	validation_0-mae:6405.84539
[64]	validation_0-mae:6380.34179
[65]	validation_0-mae:6343.43783
[66]	validation_0-mae:6318.02873
[67]	validation_0-mae:6296.75262
[68]	validation_0-mae:6263.16878
[69]	validation_0-mae:6239.73702
[70]	validation_0-mae:6200.76469
[71]	validation_0-mae:6171.05207
[72]	validation_0-mae:6149.35145
[73]	validation_0-mae:6127.41564
[74]	validation_0-mae:6099.24532
[75]	validation_0-mae:6063.35214
[76]	validation_0-mae:6030.05671
[77]	validation_0-mae:6012.42117
[78]	validation_0-mae:5993.96038
[79]	validation_0-mae:5965.74657
[80]	validation_0-mae:5944.78021
[81]	validation_0-mae:5929.06311
[82]	validation_0-mae:5892.38580
[83]	validation_0-mae:5868.09882
[84]	validation_0-mae:5848.20387
[85]	validation_0-mae:5797.64419
[86]	validation_0-mae:5766.63200
[87]	validation_0-mae:5750.60510
[88]	validation_0-mae:5719.07800
[89]	validation_0-mae:5703.01659
[90]	validation_0-mae:5676.04111
[91]	validation_0-mae:5629.93475
[92]	validation_0-mae:5607.52481
[93]	validation_0-mae:5561.16217
[94]	validation_0-mae:5545.54614
[95]	validation_0-mae:5527.28447
[96]	validation_0-mae:5499.51999
[97]	validation_0-mae:5459.01331
[98]	validation_0-mae:5419.35354
[99]	validation_0-mae:5396.28091
[100]	validation_0-mae:5382.32681
[101]	validation_0-mae:5360.51655
[102]	validation_0-mae:5346.13284
[103]	validation_0-mae:5327.12626
[104]	validation_0-mae:5304.62518
[105]	validation_0-mae:5290.66902
[106]	validation_0-mae:5278.66627
[107]	validation_0-mae:5243.46791
[108]	validation_0-mae:5221.67707
[109]	validation_0-mae:5199.78754
[110]	validation_0-mae:5179.30289
[111]	validation_0-mae:5163.27503
[112]	validation_0-mae:5129.36606
[113]	validation_0-mae:5101.02247
[114]	validation_0-mae:5079.47248
[115]	validation_0-mae:5069.50937
[116]	validation_0-mae:5051.57096
[117]	validation_0-mae:5020.79260
[118]	validation_0-mae:5000.58438
[119]	validation_0-mae:4989.97891
[120]	validation_0-mae:4976.07499
[121]	validation_0-mae:4950.39644
[122]	validation_0-mae:4940.99755
[123]	validation_0-mae:4912.45847
[124]	validation_0-mae:4897.11984
[125]	validation_0-mae:4882.76211
[126]	validation_0-mae:4860.17657
[127]	validation_0-mae:4853.93613
[128]	validation_0-mae:4829.61577
[129]	validation_0-mae:4814.63655
[130]	validation_0-mae:4807.29454
[131]	validation_0-mae:4787.94936
[132]	validation_0-mae:4774.98442
[133]	validation_0-mae:4765.94456
[134]	validation_0-mae:4750.91248
[135]	validation_0-mae:4740.07945
[136]	validation_0-mae:4718.13725
[137]	validation_0-mae:4707.92998
[138]	validation_0-mae:4692.72546
[139]	validation_0-mae:4677.14059
[140]	validation_0-mae:4669.95492
[141]	validation_0-mae:4651.56706
[142]	validation_0-mae:4641.15974
[143]	validation_0-mae:4627.08564
[144]	validation_0-mae:4618.11011
[145]	validation_0-mae:4608.70443
[146]	validation_0-mae:4600.61443
[147]	validation_0-mae:4584.70858
[148]	validation_0-mae:4574.02663
[149]	validation_0-mae:4565.39723
[150]	validation_0-mae:4551.57691
[151]	validation_0-mae:4542.66308
[152]	validation_0-mae:4532.79900
[153]	validation_0-mae:4526.90074
[154]	validation_0-mae:4519.86811
[155]	validation_0-mae:4504.74217
[156]	validation_0-mae:4495.03766
[157]	validation_0-mae:4479.22133
[158]	validation_0-mae:4472.53989
[159]	validation_0-mae:4463.07146
[160]	validation_0-mae:4455.53014
[161]	validation_0-mae:4442.30908
[162]	validation_0-mae:4435.69798
[163]	validation_0-mae:4427.60500
[164]	validation_0-mae:4417.64449
[165]	validation_0-mae:4410.13758
[166]	validation_0-mae:4400.42770
[167]	validation_0-mae:4392.68506
[168]	validation_0-mae:4382.68931
[169]	validation_0-mae:4368.52989
[170]	validation_0-mae:4359.40302
[171]	validation_0-mae:4352.43274
[172]	validation_0-mae:4344.54588
[173]	validation_0-mae:4334.45177
[174]	validation_0-mae:4326.89873
[175]	validation_0-mae:4317.24130
[176]	validation_0-mae:4312.83208
[177]	validation_0-mae:4305.76825
[178]	validation_0-mae:4292.98627
[179]	validation_0-mae:4284.59284
[180]	validation_0-mae:4274.69416
[181]	validation_0-mae:4269.89603
[182]	validation_0-mae:4262.44934
[183]	validation_0-mae:4255.44082
[184]	validation_0-mae:4248.34118
[185]	validation_0-mae:4236.53568
[186]	validation_0-mae:4229.04466
[187]	validation_0-mae:4222.14817
[188]	validation_0-mae:4217.86104
[189]	validation_0-mae:4213.23690
[190]	validation_0-mae:4202.45855
[191]	validation_0-mae:4194.60090
[192]	validation_0-mae:4184.12772
[193]	validation_0-mae:4177.59849
[194]	validation_0-mae:4174.35853
[195]	validation_0-mae:4167.90640
[196]	validation_0-mae:4161.10475
[197]	validation_0-mae:4153.77830
[198]	validation_0-mae:4149.24871
[199]	validation_0-mae:4143.44725
[200]	validation_0-mae:4134.60194
[201]	validation_0-mae:4127.74939
[202]	validation_0-mae:4122.25500
[203]	validation_0-mae:4113.68652
[204]	validation_0-mae:4108.83185
[205]	validation_0-mae:4101.15151
[206]	validation_0-mae:4092.42507
[207]	validation_0-mae:4086.10041
[208]	validation_0-mae:4084.09809
[209]	validation_0-mae:4076.62997
[210]	validation_0-mae:4070.68779
[211]	validation_0-mae:4068.39202
[212]	validation_0-mae:4064.15369
[213]	validation_0-mae:4056.74285
[214]	validation_0-mae:4048.87414
[215]	validation_0-mae:4044.44166
[216]	validation_0-mae:4039.98244
[217]	validation_0-mae:4035.24525
[218]	validation_0-mae:4031.41672
[219]	validation_0-mae:4026.08269
[220]	validation_0-mae:4018.84119
[221]	validation_0-mae:4014.41690
[222]	validation_0-mae:4006.59893
[223]	validation_0-mae:4002.82996
[224]	validation_0-mae:3998.91381
[225]	validation_0-mae:3987.12240
[226]	validation_0-mae:3981.15756
[227]	validation_0-mae:3978.15160
[228]	validation_0-mae:3971.15140
[229]	validation_0-mae:3968.93914
[230]	validation_0-mae:3965.58533
[231]	validation_0-mae:3961.92818
[232]	validation_0-mae:3956.07205
[233]	validation_0-mae:3954.21660
[234]	validation_0-mae:3951.87241
[235]	validation_0-mae:3948.79250
[236]	validation_0-mae:3944.23258
[237]	validation_0-mae:3939.92016
[238]	validation_0-mae:3936.45008
[239]	validation_0-mae:3931.03519
[240]	validation_0-mae:3920.83798
[241]	validation_0-mae:3915.67442
[242]	validation_0-mae:3912.71006
[243]	validation_0-mae:3907.30982
[244]	validation_0-mae:3897.48887
[245]	validation_0-mae:3894.73041
[246]	validation_0-mae:3891.66207
[247]	validation_0-mae:3882.50404
[248]	validation_0-mae:3879.71227
[249]	validation_0-mae:3874.56773
[250]	validation_0-mae:3872.11544
[251]	validation_0-mae:3868.11627
[252]	validation_0-mae:3864.99055
[253]	validation_0-mae:3861.24634
[254]	validation_0-mae:3858.62935
[255]	validation_0-mae:3855.45490
[256]	validation_0-mae:3850.01186
[257]	validation_0-mae:3845.10059
[258]	validation_0-mae:3843.23615
[259]	validation_0-mae:3840.32319
[260]	validation_0-mae:3835.40411
[261]	validation_0-mae:3832.43253
[262]	validation_0-mae:3828.36387
[263]	validation_0-mae:3826.59585
[264]	validation_0-mae:3824.20105
[265]	validation_0-mae:3822.20121
[266]	validation_0-mae:3817.05233
[267]	validation_0-mae:3809.78312
[268]	validation_0-mae:3807.92521
[269]	validation_0-mae:3799.32562
[270]	validation_0-mae:3796.54724
[271]	validation_0-mae:3794.15528
[272]	validation_0-mae:3791.18359
[273]	validation_0-mae:3789.26372
[274]	validation_0-mae:3786.80574
[275]	validation_0-mae:3783.60928
[276]	validation_0-mae:3779.12832
[277]	validation_0-mae:3776.62460
[278]	validation_0-mae:3774.32159
[279]	validation_0-mae:3768.96337
[280]	validation_0-mae:3764.44980
[281]	validation_0-mae:3757.84285
[282]	validation_0-mae:3750.99138
[283]	validation_0-mae:3748.29378
[284]	validation_0-mae:3746.04860
[285]	validation_0-mae:3744.22145
[286]	validation_0-mae:3742.46152
[287]	validation_0-mae:3739.47398
[288]	validation_0-mae:3735.10531
[289]	validation_0-mae:3727.63333
[290]	validation_0-mae:3725.03393
[291]	validation_0-mae:3721.06239
[292]	validation_0-mae:3717.78328
[293]	validation_0-mae:3714.73849
[294]	validation_0-mae:3712.75148
[295]	validation_0-mae:3711.24590
[296]	validation_0-mae:3707.37321
[297]	validation_0-mae:3704.68679
[298]	validation_0-mae:3703.11432
[299]	validation_0-mae:3700.73987
[300]	validation_0-mae:3699.02243
[301]	validation_0-mae:3696.51145
[302]	validation_0-mae:3694.02015
[303]	validation_0-mae:3686.24408
[304]	validation_0-mae:3684.32888
[305]	validation_0-mae:3680.94520
[306]	validation_0-mae:3678.31091
[307]	validation_0-mae:3676.85443
[308]	validation_0-mae:3674.38933
[309]	validation_0-mae:3672.52803
[310]	validation_0-mae:3672.15371
[311]	validation_0-mae:3667.20687
[312]	validation_0-mae:3664.32318
[313]	validation_0-mae:3659.51528
[314]	validation_0-mae:3657.71487
[315]	validation_0-mae:3655.79480
[316]	validation_0-mae:3652.10874
[317]	validation_0-mae:3651.88521
[318]	validation_0-mae:3648.74904
[319]	validation_0-mae:3645.13382
[320]	validation_0-mae:3642.76283
[321]	validation_0-mae:3638.88850
[322]	validation_0-mae:3632.03738
[323]	validation_0-mae:3628.94673
[324]	validation_0-mae:3625.48995
[325]	validation_0-mae:3623.37363
[326]	validation_0-mae:3620.06667
[327]	validation_0-mae:3618.34872
[328]	validation_0-mae:3616.84293
[329]	validation_0-mae:3614.54201
[330]	validation_0-mae:3612.87563
[331]	validation_0-mae:3609.95160
[332]	validation_0-mae:3607.77626
[333]	validation_0-mae:3605.58405
[334]	validation_0-mae:3604.17895
[335]	validation_0-mae:3603.67325
[336]	validation_0-mae:3601.15733
[337]	validation_0-mae:3599.32520
[338]	validation_0-mae:3597.04962
[339]	validation_0-mae:3594.81052
[340]	validation_0-mae:3592.38158
[341]	validation_0-mae:3587.94109
[342]	validation_0-mae:3584.73918
[343]	validation_0-mae:3583.35739
[344]	validation_0-mae:3581.68145
[345]	validation_0-mae:3580.30147
[346]	validation_0-mae:3578.51657
[347]	validation_0-mae:3575.66833
[348]	validation_0-mae:3573.32695
[349]	validation_0-mae:3571.35561
[350]	validation_0-mae:3569.43835
[351]	validation_0-mae:3567.56464
[352]	validation_0-mae:3566.23814
[353]	validation_0-mae:3563.84691
[354]	validation_0-mae:3561.09452
[355]	validation_0-mae:3559.72227
[356]	validation_0-mae:3558.56422
[357]	validation_0-mae:3555.30957
[358]	validation_0-mae:3549.94754
[359]	validation_0-mae:3548.08319
[360]	validation_0-mae:3543.77657
[361]	validation_0-mae:3539.43859
[362]	validation_0-mae:3538.25950
[363]	validation_0-mae:3535.97404
[364]	validation_0-mae:3535.83207
[365]	validation_0-mae:3534.91149
[366]	validation_0-mae:3532.82380
[367]	validation_0-mae:3529.56710
[368]	validation_0-mae:3525.92132
[369]	validation_0-mae:3522.87914
[370]	validation_0-mae:3519.43544
[371]	validation_0-mae:3517.42208
[372]	validation_0-mae:3515.46886
[373]	validation_0-mae:3511.98524
[374]	validation_0-mae:3511.85385
[375]	validation_0-mae:3509.72424
[376]	validation_0-mae:3507.96092
[377]	validation_0-mae:3506.72971
[378]	validation_0-mae:3502.97858
[379]	validation_0-mae:3502.56749
[380]	validation_0-mae:3500.73096
[381]	validation_0-mae:3498.10183
[382]	validation_0-mae:3497.73643
[383]	validation_0-mae:3495.76539
[384]	validation_0-mae:3494.89083
[385]	validation_0-mae:3493.42594
[386]	validation_0-mae:3492.52182
[387]	validation_0-mae:3489.28268
[388]	validation_0-mae:3486.38072
[389]	validation_0-mae:3485.08228
[390]	validation_0-mae:3482.87052
[391]	validation_0-mae:3481.71903
[392]	validation_0-mae:3480.39229
[393]	validation_0-mae:3477.98082
[394]	validation_0-mae:3474.90159
[395]	validation_0-mae:3472.28841
[396]	validation_0-mae:3471.67939
[397]	validation_0-mae:3468.67538
[398]	validation_0-mae:3467.20949
[399]	validation_0-mae:3464.31333
[400]	validation_0-mae:3463.11866
[401]	validation_0-mae:3461.60833
[402]	validation_0-mae:3458.74172
[403]	validation_0-mae:3457.47830
[404]	validation_0-mae:3456.44905
[405]	validation_0-mae:3454.74369
[406]	validation_0-mae:3453.31751
[407]	validation_0-mae:3451.09736
[408]	validation_0-mae:3447.07711
[409]	validation_0-mae:3445.28311
[410]	validation_0-mae:3444.59120
[411]	validation_0-mae:3441.70737
[412]	validation_0-mae:3440.28067
[413]	validation_0-mae:3439.41383
[414]	validation_0-mae:3437.67543
[415]	validation_0-mae:3434.94063
[416]	validation_0-mae:3432.94516
[417]	validation_0-mae:3431.95671
[418]	validation_0-mae:3428.76672
[419]	validation_0-mae:3426.86891
[420]	validation_0-mae:3426.59349
[421]	validation_0-mae:3424.64872
[422]	validation_0-mae:3422.10092
[423]	validation_0-mae:3421.48382
[424]	validation_0-mae:3419.90347
[425]	validation_0-mae:3418.87630
[426]	validation_0-mae:3416.72003
[427]	validation_0-mae:3414.00104
[428]	validation_0-mae:3411.07448
[429]	validation_0-mae:3409.23474
[430]	validation_0-mae:3406.11878
[431]	validation_0-mae:3403.47712
[432]	validation_0-mae:3402.85943
[433]	validation_0-mae:3401.61547
[434]	validation_0-mae:3400.47726
[435]	validation_0-mae:3399.04314
[436]	validation_0-mae:3397.47222
[437]	validation_0-mae:3397.02502
[438]	validation_0-mae:3396.84481
[439]	validation_0-mae:3395.53309
[440]	validation_0-mae:3393.51995
[441]	validation_0-mae:3389.69897
[442]	validation_0-mae:3389.67358
[443]	validation_0-mae:3387.19715
[444]	validation_0-mae:3386.29362
[445]	validation_0-mae:3385.50644
[446]	validation_0-mae:3383.75874
[447]	validation_0-mae:3381.69272
[448]	validation_0-mae:3378.58776
[449]	validation_0-mae:3375.80325
[450]	validation_0-mae:3374.34425
[451]	validation_0-mae:3373.60940
[452]	validation_0-mae:3372.32715
[453]	validation_0-mae:3370.01810
[454]	validation_0-mae:3368.16747
[455]	validation_0-mae:3367.27358
[456]	validation_0-mae:3366.62059
[457]	validation_0-mae:3365.12731
[458]	validation_0-mae:3362.03119
[459]	validation_0-mae:3360.62163
[460]	validation_0-mae:3359.31651
[461]	validation_0-mae:3358.92937
[462]	validation_0-mae:3358.23988
[463]	validation_0-mae:3354.62810
[464]	validation_0-mae:3352.34144
[465]	validation_0-mae:3351.17097
[466]	validation_0-mae:3349.77129
[467]	validation_0-mae:3348.30216
[468]	validation_0-mae:3347.95982
[469]	validation_0-mae:3346.32392
[470]	validation_0-mae:3345.19065
[471]	validation_0-mae:3343.61075
[472]	validation_0-mae:3341.86441
[473]	validation_0-mae:3339.74379
[474]	validation_0-mae:3338.00852
[475]	validation_0-mae:3336.40622
[476]	validation_0-mae:3333.97168
[477]	validation_0-mae:3333.41901
[478]	validation_0-mae:3331.72475
[479]	validation_0-mae:3331.44910
[480]	validation_0-mae:3329.35407
[481]	validation_0-mae:3327.98332
[482]	validation_0-mae:3327.01502
[483]	validation_0-mae:3325.97755
[484]	validation_0-mae:3324.69217
[485]	validation_0-mae:3323.90758
[486]	validation_0-mae:3322.98695
[487]	validation_0-mae:3322.48733
[488]	validation_0-mae:3321.59513
[489]	validation_0-mae:3320.93050
[490]	validation_0-mae:3318.26437
[491]	validation_0-mae:3317.05818
[492]	validation_0-mae:3315.13669
[493]	validation_0-mae:3313.94089
[494]	validation_0-mae:3313.35697
[495]	validation_0-mae:3311.66365
[496]	validation_0-mae:3311.33733
[497]	validation_0-mae:3309.01383
[498]	validation_0-mae:3307.76089
[499]	validation_0-mae:3306.38328
[500]	validation_0-mae:3305.51320
[501]	validation_0-mae:3304.58880
[502]	validation_0-mae:3303.85902
[503]	validation_0-mae:3302.85763
[504]	validation_0-mae:3302.01780
[505]	validation_0-mae:3301.52189
[506]	validation_0-mae:3300.41852
[507]	validation_0-mae:3299.50589
[508]	validation_0-mae:3297.54534
[509]	validation_0-mae:3296.53484
[510]	validation_0-mae:3295.06040
[511]	validation_0-mae:3294.12080
[512]	validation_0-mae:3292.85160
[513]	validation_0-mae:3292.16966
[514]	validation_0-mae:3291.15186
[515]	validation_0-mae:3290.15273
[516]	validation_0-mae:3289.13776
[517]	validation_0-mae:3287.52740
[518]	validation_0-mae:3285.74197
[519]	validation_0-mae:3283.34144
[520]	validation_0-mae:3281.21035
[521]	validation_0-mae:3280.10733
[522]	validation_0-mae:3278.67743
[523]	validation_0-mae:3277.27234
[524]	validation_0-mae:3276.36577
[525]	validation_0-mae:3274.12270
[526]	validation_0-mae:3272.98588
[527]	validation_0-mae:3270.19817
[528]	validation_0-mae:3268.23616
[529]	validation_0-mae:3267.51493
[530]	validation_0-mae:3266.20975
[531]	validation_0-mae:3265.56644
[532]	validation_0-mae:3265.20045
[533]	validation_0-mae:3263.53855
[534]	validation_0-mae:3260.90467
[535]	validation_0-mae:3260.13855
[536]	validation_0-mae:3258.54559
[537]	validation_0-mae:3256.63358
[538]	validation_0-mae:3255.80581
[539]	validation_0-mae:3255.44082
[540]	validation_0-mae:3254.31754
[541]	validation_0-mae:3253.62408
[542]	validation_0-mae:3251.77845
[543]	validation_0-mae:3251.13367
[544]	validation_0-mae:3250.65958
[545]	validation_0-mae:3249.27896
[546]	validation_0-mae:3248.04439
[547]	validation_0-mae:3247.22629
[548]	validation_0-mae:3245.17433
[549]	validation_0-mae:3244.37632
[550]	validation_0-mae:3243.45576
[551]	validation_0-mae:3242.89812
[552]	validation_0-mae:3240.85064
[553]	validation_0-mae:3239.92064
[554]	validation_0-mae:3238.43272
[555]	validation_0-mae:3237.26805
[556]	validation_0-mae:3236.64234
[557]	validation_0-mae:3236.33305
[558]	validation_0-mae:3235.92973
[559]	validation_0-mae:3235.63276
[560]	validation_0-mae:3234.16581
[561]	validation_0-mae:3231.99501
[562]	validation_0-mae:3231.79370
[563]	validation_0-mae:3231.20884
[564]	validation_0-mae:3230.91339
[565]	validation_0-mae:3230.24830
[566]	validation_0-mae:3228.26306
[567]	validation_0-mae:3227.48745
[568]	validation_0-mae:3225.95932
[569]	validation_0-mae:3225.74160
[570]	validation_0-mae:3224.18599
[571]	validation_0-mae:3224.08814
[572]	validation_0-mae:3222.44003
[573]	validation_0-mae:3220.51670
[574]	validation_0-mae:3219.13658
[575]	validation_0-mae:3218.59360
[576]	validation_0-mae:3218.49654
[577]	validation_0-mae:3217.42568
[578]	validation_0-mae:3217.22050
[579]	validation_0-mae:3216.54851
[580]	validation_0-mae:3214.55739
[581]	validation_0-mae:3213.73869
[582]	validation_0-mae:3212.76561
[583]	validation_0-mae:3211.46890
[584]	validation_0-mae:3211.38569
[585]	validation_0-mae:3209.37347
[586]	validation_0-mae:3207.63348
[587]	validation_0-mae:3206.83341
[588]	validation_0-mae:3205.58747
[589]	validation_0-mae:3204.61353
[590]	validation_0-mae:3204.40729
[591]	validation_0-mae:3202.93247
[592]	validation_0-mae:3202.49393
[593]	validation_0-mae:3202.57334
[594]	validation_0-mae:3201.10730
[595]	validation_0-mae:3199.98157
[596]	validation_0-mae:3200.18064
[597]	validation_0-mae:3199.86383
[598]	validation_0-mae:3198.06598
[599]	validation_0-mae:3197.41850
[600]	validation_0-mae:3196.22053
[601]	validation_0-mae:3195.10601
[602]	validation_0-mae:3193.76057
[603]	validation_0-mae:3193.41451
[604]	validation_0-mae:3193.14056
[605]	validation_0-mae:3191.97816
[606]	validation_0-mae:3190.66321
[607]	validation_0-mae:3189.97690
[608]	validation_0-mae:3188.78490
[609]	validation_0-mae:3188.00551
[610]	validation_0-mae:3186.86435
[611]	validation_0-mae:3185.70731
[612]	validation_0-mae:3184.39196
[613]	validation_0-mae:3182.69149
[614]	validation_0-mae:3181.32913
[615]	validation_0-mae:3180.58173
[616]	validation_0-mae:3180.10605
[617]	validation_0-mae:3180.21163
[618]	validation_0-mae:3180.32041
[619]	validation_0-mae:3180.00949
[620]	validation_0-mae:3179.03004
[621]	validation_0-mae:3178.15282
[622]	validation_0-mae:3177.36661
[623]	validation_0-mae:3177.13017
[624]	validation_0-mae:3176.76762
[625]	validation_0-mae:3176.32564
[626]	validation_0-mae:3175.59204
[627]	validation_0-mae:3175.31171
[628]	validation_0-mae:3175.51413
[629]	validation_0-mae:3174.76185
[630]	validation_0-mae:3173.94306
[631]	validation_0-mae:3171.97492
[632]	validation_0-mae:3171.39918
[633]	validation_0-mae:3170.98448
[634]	validation_0-mae:3168.55367
[635]	validation_0-mae:3167.37834
[636]	validation_0-mae:3166.34787
[637]	validation_0-mae:3165.01985
[638]	validation_0-mae:3164.68079
[639]	validation_0-mae:3164.18569
[640]	validation_0-mae:3163.72888
[641]	validation_0-mae:3162.57666
[642]	validation_0-mae:3161.85072
[643]	validation_0-mae:3161.79689
[644]	validation_0-mae:3161.61257
[645]	validation_0-mae:3160.10751
[646]	validation_0-mae:3160.07696
[647]	validation_0-mae:3159.29282
[648]	validation_0-mae:3158.85263
[649]	validation_0-mae:3158.57315
[650]	validation_0-mae:3157.97546
[651]	validation_0-mae:3157.64877

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[54]	validation_0-mae:10758.32240
[55]	validation_0-mae:10725.42852
[56]	validation_0-mae:10693.93976
[57]	validation_0-mae:10662.13543
[58]	validation_0-mae:10630.65839
[59]	validation_0-mae:10600.08108
[60]	validation_0-mae:10570.17170
[61]	validation_0-mae:10540.15034
[62]	validation_0-mae:10511.38975
[63]	validation_0-mae:10481.67697
[64]	validation_0-mae:10453.09880
[65]	validation_0-mae:10424.94877
[66]	validation_0-mae:10396.63642
[67]	validation_0-mae:10368.78362
[68]	validation_0-mae:10340.92157
[69]	validation_0-mae:10314.10586
[70]	validation_0-mae:10287.44373
[71]	validation_0-mae:10260.69822
[72]	validation_0-mae:10234.35474
[73]	validation_0-mae:10207.97319
[74]	validation_0-mae:10181.32931
[75]	validation_0-mae:10156.12759
[76]	validation_0-mae:10130.50385
[77]	validation_0-mae:10104.94125
[78]	validation_0-mae:10080.23885
[79]	validation_0-mae:10054.95317
[80]	validation_0-mae:10031.12527
[81]	validation_0-mae:10007.48946
[82]	validation_0-mae:9983.82951
[83]	validation_0-mae:9960.61008
[84]	validation_0-mae:9938.23509
[85]	validation_0-mae:9916.43708
[86]	validation_0-mae:9894.00333
[87]	validation_0-mae:9872.41394
[88]	validation_0-mae:9850.05280
[89]	validation_0-mae:9827.59459
[90]	validation_0-mae:9805.82052
[91]	validation_0-mae:9784.88678
[92]	validation_0-mae:9763.96522
[93]	validation_0-mae:9743.15069
[94]	validation_0-mae:9723.25749
[95]	validation_0-mae:9703.12911
[96]	validation_0-mae:9683.18233
[97]	validation_0-mae:9663.13280
[98]	validation_0-mae:9644.04005
[99]	validation_0-mae:9624.47418
[100]	validation_0-mae:9605.34875
[101]	validation_0-mae:9586.66932
[102]	validation_0-mae:9568.04849
[103]	validation_0-mae:9549.61207
[104]	validation_0-mae:9530.87438
[105]	validation_0-mae:9513.42125
[106]	validation_0-mae:9495.75246
[107]	validation_0-mae:9478.18186
[108]	validation_0-mae:9461.25873
[109]	validation_0-mae:9444.38724
[110]	validation_0-mae:9427.89741
[111]	validation_0-mae:9410.87448
[112]	validation_0-mae:9394.92932
[113]	validation_0-mae:9379.38489
[114]	validation_0-mae:9363.85039
[115]	validation_0-mae:9348.64270
[116]	validation_0-mae:9334.05657
[117]	validation_0-mae:9319.03202
[118]	validation_0-mae:9303.45780
[119]	validation_0-mae:9288.74277
[120]	validation_0-mae:9273.57288
[121]	validation_0-mae:9258.94406
[122]	validation_0-mae:9244.00328
[123]	validation_0-mae:9229.59315
[124]	validation_0-mae:9215.83496
[125]	validation_0-mae:9202.26733
[126]	validation_0-mae:9188.35232
[127]	validation_0-mae:9174.94644
[128]	validation_0-mae:9161.26531
[129]	validation_0-mae:9148.87565
[130]	validation_0-mae:9136.00368
[131]	validation_0-mae:9123.37514
[132]	validation_0-mae:9110.67147
[133]	validation_0-mae:9098.49365
[134]	validation_0-mae:9085.89927
[135]	validation_0-mae:9073.54699
[136]	validation_0-mae:9062.76923
[137]	validation_0-mae:9050.75821
[138]	validation_0-mae:9039.47483
[139]	validation_0-mae:9028.51804
[140]	validation_0-mae:9017.12665
[141]	validation_0-mae:9006.44878
[142]	validation_0-mae:8995.79733
[143]	validation_0-mae:8985.05529
[144]	validation_0-mae:8974.61789
[145]	validation_0-mae:8964.27696
[146]	validation_0-mae:8953.36417
[147]	validation_0-mae:8943.02511
[148]	validation_0-mae:8932.71830
[149]	validation_0-mae:8922.77729
[150]	validation_0-mae:8912.81989
[151]	validation_0-mae:8902.76992
[152]	validation_0-mae:8892.66082
[153]	validation_0-mae:8882.67459
[154]	validation_0-mae:8873.39526
[155]	validation_0-mae:8863.96935
[156]	validation_0-mae:8854.91422
[157]	validation_0-mae:8845.11809
[158]	validation_0-mae:8836.35517
[159]	validation_0-mae:8827.41584
[160]	validation_0-mae:8818.11205
[161]	validation_0-mae:8808.77139
[162]	validation_0-mae:8800.11151
[163]	validation_0-mae:8792.56862
[164]	validation_0-mae:8783.50032
[165]	validation_0-mae:8775.60946
[166]	validation_0-mae:8767.22651
[167]	validation_0-mae:8758.49201
[168]	validation_0-mae:8751.34079
[169]	validation_0-mae:8742.70937
[170]	validation_0-mae:8735.02797
[171]	validation_0-mae:8727.79172
[172]	validation_0-mae:8719.24436
[173]	validation_0-mae:8711.55060
[174]	validation_0-mae:8703.31039
[175]	validation_0-mae:8694.99957
[176]	validation_0-mae:8688.16627
[177]	validation_0-mae:8680.33739
[178]	validation_0-mae:8673.00977
[179]	validation_0-mae:8664.96339
[180]	validation_0-mae:8657.06950
[181]	validation_0-mae:8650.59904
[182]	validation_0-mae:8642.77069
[183]	validation_0-mae:8634.02696
[184]	validation_0-mae:8626.07834
[185]	validation_0-mae:8618.13661
[186]	validation_0-mae:8610.83514
[187]	validation_0-mae:8602.33892
[188]	validation_0-mae:8595.08338
[189]	validation_0-mae:8588.20785
[190]	validation_0-mae:8580.15601
[191]	validation_0-mae:8573.62777
[192]	validation_0-mae:8565.39394
[193]	validation_0-mae:8559.51238
[194]	validation_0-mae:8551.53350
[195]	validation_0-mae:8545.19976
[196]	validation_0-mae:8538.75026
[197]	validation_0-mae:8531.62692
[198]	validation_0-mae:8525.70433
[199]	validation_0-mae:8517.99229
[200]	validation_0-mae:8511.28998
[201]	validation_0-mae:8503.47552
[202]	validation_0-mae:8497.75939
[203]	validation_0-mae:8490.67111
[204]	validation_0-mae:8484.52870
[205]	validation_0-mae:8477.33450
[206]	validation_0-mae:8468.97052
[207]	validation_0-mae:8463.12523
[208]	validation_0-mae:8455.44701
[209]	validation_0-mae:8448.48257
[210]	validation_0-mae:8440.73950
[211]	validation_0-mae:8435.24960
[212]	validation_0-mae:8428.10797
[213]	validation_0-mae:8422.35277
[214]	validation_0-mae:8414.99202
[215]	validation_0-mae:8410.24271
[216]	validation_0-mae:8403.56844
[217]	validation_0-mae:8398.34386
[218]	validation_0-mae:8391.48257
[219]	validation_0-mae:8384.32011
[220]	validation_0-mae:8378.35770
[221]	validation_0-mae:8373.67619
[222]	validation_0-mae:8367.18782
[223]	validation_0-mae:8361.15643
[224]	validation_0-mae:8356.50334
[225]	validation_0-mae:8350.30901
[226]	validation_0-mae:8344.49020
[227]	validation_0-mae:8339.89566
[228]	validation_0-mae:8333.68699
[229]	validation_0-mae:8328.01337
[230]	validation_0-mae:8322.97605
[231]	validation_0-mae:8316.85270
[232]	validation_0-mae:8311.18615
[233]	validation_0-mae:8305.42310
[234]	validation_0-mae:8299.16495
[235]	validation_0-mae:8293.87455
[236]	validation_0-mae:8288.54949
[237]	validation_0-mae:8283.73811
[238]	validation_0-mae:8277.57320
[239]	validation_0-mae:8272.16985
[240]	validation_0-mae:8266.93690
[241]	validation_0-mae:8260.98754
[242]	validation_0-mae:8255.77981
[243]	validation_0-mae:8250.78108
[244]	validation_0-mae:8246.42038
[245]	validation_0-mae:8241.07236
[246]	validation_0-mae:8236.60434
[247]	validation_0-mae:8231.67058
[248]	validation_0-mae:8226.52616
[249]	validation_0-mae:8220.94753
[250]	validation_0-mae:8216.31344
[251]	validation_0-mae:8209.98580
[252]	validation_0-mae:8203.75613
[253]	validation_0-mae:8198.61020
[254]	validation_0-mae:8194.58431
[255]	validation_0-mae:8188.34859
[256]	validation_0-mae:8183.47639
[257]	validation_0-mae:8177.37164
[258]	validation_0-mae:8173.04340
[259]	validation_0-mae:8168.77858
[260]	validation_0-mae:8163.26530
[261]	validation_0-mae:8157.23580
[262]	validation_0-mae:8153.20992
[263]	validation_0-mae:8148.77215
[264]	validation_0-mae:8143.08417
[265]	validation_0-mae:8137.34444
[266]	validation_0-mae:8133.56134
[267]	validation_0-mae:8129.31024
[268]	validation_0-mae:8123.62237
[269]	validation_0-mae:8117.82432
[270]	validation_0-mae:8113.09360
[271]	validation_0-mae:8106.53152
[272]	validation_0-mae:8102.34927
[273]	validation_0-mae:8098.61688
[274]	validation_0-mae:8092.34332
[275]	validation_0-mae:8088.82044
[276]	validation_0-mae:8084.77793
[277]	validation_0-mae:8078.79726
[278]	validation_0-mae:8072.63304
[279]	validation_0-mae:8068.77880
[280]	validation_0-mae:8062.34988
[281]	validation_0-mae:8058.28804
[282]	validation_0-mae:8053.30550
[283]	validation_0-mae:8046.48362
[284]	validation_0-mae:8042.98687
[285]	validation_0-mae:8038.69226
[286]	validation_0-mae:8032.34357
[287]	validation_0-mae:8028.47064
[288]	validation_0-mae:8023.39076
[289]	validation_0-mae:8017.99087
[290]	validation_0-mae:8014.07911
[291]	validation_0-mae:8009.31567
[292]	validation_0-mae:8003.46411
[293]	validation_0-mae:8000.19236
[294]	validation_0-mae:7995.20249
[295]	validation_0-mae:7991.84097
[296]	validation_0-mae:7986.79423
[297]	validation_0-mae:7981.81311
[298]	validation_0-mae:7978.60504
[299]	validation_0-mae:7974.57836
[300]	validation_0-mae:7971.33119
[301]	validation_0-mae:7966.62387
[302]	validation_0-mae:7961.66587
[303]	validation_0-mae:7958.10681
[304]	validation_0-mae:7954.91027
[305]	validation_0-mae:7949.26894
[306]	validation_0-mae:7945.26827
[307]	validation_0-mae:7942.45667
[308]	validation_0-mae:7937.53628
[309]	validation_0-mae:7934.20767
[310]	validation_0-mae:7929.61053
[311]	validation_0-mae:7925.71952
[312]	validation_0-mae:7923.21021
[313]	validation_0-mae:7918.24788
[314]	validation_0-mae:7914.43219
[315]	validation_0-mae:7911.87605
[316]	validation_0-mae:7908.65202
[317]	validation_0-mae:7903.40848
[318]	validation_0-mae:7901.33250
[319]	validation_0-mae:7895.89742
[320]	validation_0-mae:7892.09614
[321]	validation_0-mae:7889.74323
[322]	validation_0-mae:7887.18675
[323]	validation_0-mae:7882.93675
[324]	validation_0-mae:7878.87652
[325]	validation_0-mae:7874.97242
[326]	validation_0-mae:7869.73025
[327]	validation_0-mae:7864.72431
[328]	validation_0-mae:7861.57668
[329]	validation_0-mae:7856.76950
[330]	validation_0-mae:7852.83564
[331]	validation_0-mae:7848.71437
[332]	validation_0-mae:7844.75306
[333]	validation_0-mae:7841.96305
[334]	validation_0-mae:7837.20241
[335]	validation_0-mae:7831.41747
[336]	validation_0-mae:7827.46643
[337]	validation_0-mae:7823.95970
[338]	validation_0-mae:7819.43690
[339]	validation_0-mae:7815.61998
[340]	validation_0-mae:7812.00358
[341]	validation_0-mae:7808.16658
[342]	validation_0-mae:7804.71343
[343]	validation_0-mae:7800.29436
[344]	validation_0-mae:7797.31700
[345]	validation_0-mae:7792.67439
[346]	validation_0-mae:7788.39696
[347]	validation_0-mae:7785.81536
[348]	validation_0-mae:7781.57489
[349]	validation_0-mae:7776.17600
[350]	validation_0-mae:7772.25981
[351]	validation_0-mae:7769.29186
[352]	validation_0-mae:7765.12019
[353]	validation_0-mae:7761.34839
[354]	validation_0-mae:7759.12488
[355]	validation_0-mae:7755.78589
[356]	validation_0-mae:7753.01925
[357]	validation_0-mae:7749.32112
[358]	validation_0-mae:7744.93304
[359]	validation_0-mae:7741.36021
[360]	validation_0-mae:7737.81345
[361]	validation_0-mae:7734.24472
[362]	validation_0-mae:7731.38284
[363]	validation_0-mae:7729.47972
[364]	validation_0-mae:7725.57056
[365]	validation_0-mae:7722.09263
[366]	validation_0-mae:7719.93183
[367]	validation_0-mae:7716.59636
[368]	validation_0-mae:7714.09968
[369]	validation_0-mae:7711.06387
[370]	validation_0-mae:7708.71826
[371]	validation_0-mae:7705.43393
[372]	validation_0-mae:7702.41179
[373]	validation_0-mae:7696.88797
[374]	validation_0-mae:7694.81371
[375]	validation_0-mae:7692.44105
[376]	validation_0-mae:7690.36303
[377]	validation_0-mae:7686.51510
[378]	validation_0-mae:7682.91829
[379]	validation_0-mae:7680.83955
[380]	validation_0-mae:7676.01545
[381]	validation_0-mae:7670.68307
[382]	validation_0-mae:7668.11129
[383]	validation_0-mae:7665.53644
[384]	validation_0-mae:7662.94513
[385]	validation_0-mae:7657.80544
[386]	validation_0-mae:7655.39255
[387]	validation_0-mae:7651.89224
[388]	validation_0-mae:7649.36488
[389]	validation_0-mae:7645.43479
[390]	validation_0-mae:7641.76368
[391]	validation_0-mae:7639.42767
[392]	validation_0-mae:7635.83343
[393]	validation_0-mae:7632.40810
[394]	validation_0-mae:7630.20759
[395]	validation_0-mae:7628.01245
[396]	validation_0-mae:7624.65798
[397]	validation_0-mae:7622.38489
[398]	validation_0-mae:7619.96371
[399]	validation_0-mae:7615.72435
[400]	validation_0-mae:7613.67709
[401]	validation_0-mae:7609.97983
[402]	validation_0-mae:7607.38575
[403]	validation_0-mae:7604.89391
[404]	validation_0-mae:7601.55889
[405]	validation_0-mae:7598.78424
[406]	validation_0-mae:7595.45003
[407]	validation_0-mae:7592.83060
[408]	validation_0-mae:7590.30173
[409]	validation_0-mae:7588.57428
[410]	validation_0-mae:7585.01905
[411]	validation_0-mae:7582.54003
[412]	validation_0-mae:7579.70650
[413]	validation_0-mae:7576.91615
[414]	validation_0-mae:7573.74755
[415]	validation_0-mae:7570.34955
[416]	validation_0-mae:7567.92334
[417]	validation_0-mae:7565.45985
[418]	validation_0-mae:7563.58955
[419]	validation_0-mae:7560.85209
[420]	validation_0-mae:7557.38065
[421]	validation_0-mae:7553.20333
[422]	validation_0-mae:7550.55624
[423]	validation_0-mae:7547.12142
[424]	validation_0-mae:7543.42975
[425]	validation_0-mae:7540.02444
[426]	validation_0-mae:7535.80378
[427]	validation_0-mae:7533.03382
[428]	validation_0-mae:7529.46782
[429]	validation_0-mae:7525.53051
[430]	validation_0-mae:7522.94732
[431]	validation_0-mae:7519.00312
[432]	validation_0-mae:7516.29601
[433]	validation_0-mae:7513.83301
[434]	validation_0-mae:7510.05224
[435]	validation_0-mae:7507.06764
[436]	validation_0-mae:7504.40044
[437]	validation_0-mae:7500.09604
[438]	validation_0-mae:7497.43963
[439]	validation_0-mae:7493.79994
[440]	validation_0-mae:7491.56959
[441]	validation_0-mae:7487.26629
[442]	validation_0-mae:7484.12999
[443]	validation_0-mae:7480.66990
[444]	validation_0-mae:7477.86690
[445]	validation_0-mae:7474.79393
[446]	validation_0-mae:7472.97416
[447]	validation_0-mae:7470.17179
[448]	validation_0-mae:7468.40413
[449]	validation_0-mae:7465.46075
[450]	validation_0-mae:7463.38931
[451]	validation_0-mae:7459.98811
[452]	validation_0-mae:7458.02260
[453]	validation_0-mae:7456.79137
[454]	validation_0-mae:7453.40483
[455]	validation_0-mae:7452.10831
[456]	validation_0-mae:7448.55259
[457]	validation_0-mae:7445.93916
[458]	validation_0-mae:7442.57979
[459]	validation_0-mae:7441.52739
[460]	validation_0-mae:7438.16109
[461]	validation_0-mae:7437.27226
[462]	validation_0-mae:7433.80331
[463]	validation_0-mae:7430.49649
[464]	validation_0-mae:7429.48264
[465]	validation_0-mae:7426.28781
[466]	validation_0-mae:7424.83138
[467]	validation_0-mae:7421.61492
[468]	validation_0-mae:7417.15549
[469]	validation_0-mae:7414.63421
[470]	validation_0-mae:7411.50065
[471]	validation_0-mae:7410.37707
[472]	validation_0-mae:7407.34465
[473]	validation_0-mae:7405.00052
[474]	validation_0-mae:7404.10499
[475]	validation_0-mae:7401.22845
[476]	validation_0-mae:7400.30910
[477]	validation_0-mae:7397.99857
[478]	validation_0-mae:7394.70371
[479]	validation_0-mae:7391.77354
[480]	validation_0-mae:7387.44718
[481]	validation_0-mae:7385.11610
[482]	validation_0-mae:7383.92051
[483]	validation_0-mae:7381.15709
[484]	validation_0-mae:7376.94015
[485]	validation_0-mae:7376.05026
[486]	validation_0-mae:7373.29207
[487]	validation_0-mae:7371.06045
[488]	validation_0-mae:7369.89019
[489]	validation_0-mae:7367.25979
[490]	validation_0-mae:7363.26902
[491]	validation_0-mae:7361.14918
[492]	validation_0-mae:7360.12952
[493]	validation_0-mae:7357.73956
[494]	validation_0-mae:7355.18227
[495]	validation_0-mae:7353.91797
[496]	validation_0-mae:7351.29141
[497]	validation_0-mae:7347.43772
[498]	validation_0-mae:7346.14116
[499]	validation_0-mae:7343.88232
[500]	validation_0-mae:7342.97563
[501]	validation_0-mae:7340.08844
[502]	validation_0-mae:7336.20151
[503]	validation_0-mae:7334.93015
[504]	validation_0-mae:7332.30512
[505]	validation_0-mae:7331.66010
[506]	validation_0-mae:7330.51866
[507]	validation_0-mae:7328.01571
[508]	validation_0-mae:7324.30170
[509]	validation_0-mae:7321.94073
[510]	validation_0-mae:7321.14153
[511]	validation_0-mae:7319.65031
[512]	validation_0-mae:7316.06083
[513]	validation_0-mae:7313.26454
[514]	validation_0-mae:7312.11127
[515]	validation_0-mae:7309.77260
[516]	validation_0-mae:7309.04542
[517]	validation_0-mae:7305.49421
[518]	validation_0-mae:7302.85963
[519]	validation_0-mae:7300.88902
[520]	validation_0-mae:7300.32316
[521]	validation_0-mae:7298.07148
[522]	validation_0-mae:7294.54738
[523]	validation_0-mae:7293.74710
[524]	validation_0-mae:7291.34369
[525]	validation_0-mae:7289.04707
[526]	validation_0-mae:7285.47832
[527]	validation_0-mae:7284.52387
[528]	validation_0-mae:7282.18909
[529]	validation_0-mae:7278.67451
[530]	validation_0-mae:7276.35213
[531]	validation_0-mae:7275.56867
[532]	validation_0-mae:7272.59750
[533]	validation_0-mae:7270.34506
[534]	validation_0-mae:7268.88051
[535]	validation_0-mae:7265.67958
[536]	validation_0-mae:7263.41906
[537]	validation_0-mae:7260.09326
[538]	validation_0-mae:7258.71870
[539]	validation_0-mae:7256.52597
[540]	validation_0-mae:7253.49813
[541]	validation_0-mae:7250.55310
[542]	validation_0-mae:7248.13407
[543]	validation_0-mae:7247.49871
[544]	validation_0-mae:7245.39727
[545]	validation_0-mae:7244.82291
[546]	validation_0-mae:7242.67265
[547]	validation_0-mae:7239.90927
[548]	validation_0-mae:7238.29793
[549]	validation_0-mae:7236.13057
[550]	validation_0-mae:7233.09761
[551]	validation_0-mae:7230.97237
[552]	validation_0-mae:7229.95540
[553]	validation_0-mae:7226.92381
[554]	validation_0-mae:7224.71650
[555]	validation_0-mae:7222.04232
[556]	validation_0-mae:7221.47735
[557]	validation_0-mae:7219.35313
[558]	validation_0-mae:7217.74838
[559]	validation_0-mae:7215.42474
[560]	validation_0-mae:7212.63339
[561]	validation_0-mae:7211.13196
[562]	validation_0-mae:7208.88347
[563]	validation_0-mae:7207.07883
[564]	validation_0-mae:7204.41773
[565]	validation_0-mae:7202.50027
[566]	validation_0-mae:7200.12141
[567]	validation_0-mae:7198.35572
[568]	validation_0-mae:7196.38913
[569]	validation_0-mae:7193.89318
[570]	validation_0-mae:7192.15097
[571]	validation_0-mae:7189.66576
[572]	validation_0-mae:7187.38399
[573]	validation_0-mae:7184.98766
[574]	validation_0-mae:7182.32742
[575]	validation_0-mae:7180.99680
[576]	validation_0-mae:7179.22769
[577]	validation_0-mae:7176.67658
[578]	validation_0-mae:7174.88643
[579]	validation_0-mae:7173.03984
[580]	validation_0-mae:7170.75060
[581]	validation_0-mae:7168.58903
[582]	validation_0-mae:7165.30830
[583]	validation_0-mae:7162.77701
[584]	validation_0-mae:7160.55781
[585]	validation_0-mae:7159.37946
[586]	validation_0-mae:7156.84506
[587]	validation_0-mae:7154.78202
[588]	validation_0-mae:7151.94712
[589]	validation_0-mae:7149.94308
[590]	validation_0-mae:7148.09060
[591]	validation_0-mae:7146.12677
[592]	validation_0-mae:7143.69640
[593]	validation_0-mae:7142.07473
[594]	validation_0-mae:7139.23473
[595]	validation_0-mae:7137.39919
[596]	validation_0-mae:7135.60723
[597]	validation_0-mae:7133.49762
[598]	validation_0-mae:7132.69885
[599]	validation_0-mae:7130.03508
[600]	validation_0-mae:7126.90129
[601]	validation_0-mae:7125.25381
[602]	validation_0-mae:7123.16170
[603]	validation_0-mae:7122.21245
[604]	validation_0-mae:7120.56037
[605]	validation_0-mae:7118.54700
[606]	validation_0-mae:7116.72830
[607]	validation_0-mae:7114.17347
[608]	validation_0-mae:7112.17830
[609]	validation_0-mae:7111.02209
[610]	validation_0-mae:7108.05994
[611]	validation_0-mae:7105.52891
[612]	validation_0-mae:7104.25481
[613]	validation_0-mae:7101.34068
[614]	validation_0-mae:7099.65787
[615]	validation_0-mae:7097.77385
[616]	validation_0-mae:7097.15754
[617]	validation_0-mae:7095.69877
[618]	validation_0-mae:7093.34606
[619]	validation_0-mae:7090.98131
[620]	validation_0-mae:7089.89199
[621]	validation_0-mae:7088.44813
[622]	validation_0-mae:7087.89391
[623]	validation_0-mae:7086.60108
[624]	validation_0-mae:7085.18780
[625]	validation_0-mae:7083.91397
[626]	validation_0-mae:7082.92327
[627]	validation_0-mae:7080.93605
[628]	validation_0-mae:7078.49183
[629]	validation_0-mae:7076.98695
[630]	validation_0-mae:7073.20589
[631]	validation_0-mae:7071.44114
[632]	validation_0-mae:7070.08301
[633]	validation_0-mae:7068.16878
[634]	validation_0-mae:7066.71712
[635]	validation_0-mae:7064.87543
[636]	validation_0-mae:7064.39668
[637]	validation_0-mae:7062.66512
[638]	validation_0-mae:7060.77470
[639]	validation_0-mae:7059.88588
[640]	validation_0-mae:7058.71819
[641]	validation_0-mae:7057.87358

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[12]	validation_0-mae:9661.26193
[13]	validation_0-mae:9528.32879
[14]	validation_0-mae:9403.63743
[15]	validation_0-mae:9286.99549
[16]	validation_0-mae:9179.26095
[17]	validation_0-mae:9072.92325
[18]	validation_0-mae:8982.15452
[19]	validation_0-mae:8896.42321
[20]	validation_0-mae:8812.89051
[21]	validation_0-mae:8745.49114
[22]	validation_0-mae:8680.11330
[23]	validation_0-mae:8610.59331
[24]	validation_0-mae:8545.87116
[25]	validation_0-mae:8488.17204
[26]	validation_0-mae:8442.05390
[27]	validation_0-mae:8395.59743
[28]	validation_0-mae:8348.32138
[29]	validation_0-mae:8301.73572
[30]	validation_0-mae:8264.96675
[31]	validation_0-mae:8226.76542
[32]	validation_0-mae:8188.29818
[33]	validation_0-mae:8150.59690
[34]	validation_0-mae:8115.10990
[35]	validation_0-mae:8066.12443
[36]	validation_0-mae:8032.21097
[37]	validation_0-mae:7988.15695
[38]	validation_0-mae:7959.86480
[39]	validation_0-mae:7916.77825
[40]	validation_0-mae:7880.82910
[41]	validation_0-mae:7855.29321
[42]	validation_0-mae:7815.11122
[43]	validation_0-mae:7800.35064
[44]	validation_0-mae:7770.72742
[45]	validation_0-mae:7734.81493
[46]	validation_0-mae:7696.26370
[47]	validation_0-mae:7666.84291
[48]	validation_0-mae:7643.46369
[49]	validation_0-mae:7626.06447
[50]	validation_0-mae:7610.53169
[51]	validation_0-mae:7589.18356
[52]	validation_0-mae:7567.41805
[53]	validation_0-mae:7543.74807
[54]	validation_0-mae:7529.57706
[55]	validation_0-mae:7495.43262
[56]	validation_0-mae:7481.13010
[57]	validation_0-mae:7456.36233
[58]	validation_0-mae:7434.57313
[59]	validation_0-mae:7417.46042
[60]	validation_0-mae:7400.46995
[61]	validation_0-mae:7383.89578
[62]	validation_0-mae:7355.08423
[63]	validation_0-mae:7324.25844
[64]	validation_0-mae:7303.18600
[65]	validation_0-mae:7275.17161
[66]	validation_0-mae:7265.61211
[67]	validation_0-mae:7245.89139
[68]	validation_0-mae:7232.04198
[69]	validation_0-mae:7218.69256
[70]	validation_0-mae:7204.70148
[71]	validation_0-mae:7180.48931
[72]	validation_0-mae:7174.98967
[73]	validation_0-mae:7163.60704
[74]	validation_0-mae:7150.37863
[75]	validation_0-mae:7129.60350
[76]	validation_0-mae:7112.35530
[77]	validation_0-mae:7100.30639
[78]	validation_0-mae:7093.94054
[79]	validation_0-mae:7076.81998
[80]	validation_0-mae:7067.63311
[81]	validation_0-mae:7061.42152
[82]	validation_0-mae:7054.14725
[83]	validation_0-mae:7045.26171
[84]	validation_0-mae:7033.21168
[85]	validation_0-mae:7025.86173
[86]	validation_0-mae:7020.99182
[87]	validation_0-mae:7011.33856
[88]	validation_0-mae:7004.85851
[89]	validation_0-mae:7000.92423
[90]	validation_0-mae:6994.80675
[91]	validation_0-mae:6983.52099
[92]	validation_0-mae:6980.34787
[93]	validation_0-mae:6972.98257
[94]	validation_0-mae:6961.79970
[95]	validation_0-mae:6943.98899
[96]	validation_0-mae:6938.39309
[97]	validation_0-mae:6931.45278
[98]	validation_0-mae:6926.05314
[99]	validation_0-mae:6924.34844
[100]	validation_0-mae:6918.85279
[101]	validation_0-mae:6908.60236
[102]	validation_0-mae:6904.06675
[103]	validation_0-mae:6898.69496
[104]	validation_0-mae:6889.41057
[105]	validation_0-mae:6879.53817
[106]	validation_0-mae:6877.10528
[107]	validation_0-mae:6873.97540
[108]	validation_0-mae:6864.31665
[109]	validation_0-mae:6860.03215
[110]	validation_0-mae:6855.47699
[111]	validation_0-mae:6852.98970
[112]	validation_0-mae:6849.92204
[113]	validation_0-mae:6849.43136
[114]	validation_0-mae:6843.01971
[115]	validation_0-mae:6840.31593
[116]	validation_0-mae:6835.86562
[117]	validation_0-mae:6829.39328
[118]	validation_0-mae:6827.45892
[119]	validation_0-mae:6826.79208
[120]	validation_0-mae:6824.27667
[121]	validation_0-mae:6820.77820
[122]	validation_0-mae:6818.30296
[123]	validation_0-mae:6819.34113
[124]	validation_0-mae:6818.79894
[125]	validation_0-mae:6816.10644
[126]	validation_0-mae:6816.06382
[127]	validation_0-mae:6815.54545
[128]	validation_0-mae:6815.12083
[129]	validation_0-mae:6815.85361
[130]	validation_0-mae:6814.52728
[131]	validation_0-mae:6815.31201
[132]	validation_0-mae:6816.59816
[133]	validation_0-mae:6815.48820
[134]	validation_0-mae:6817.24785
[135]	validation_0-mae:6815.96000
[136]	validation_0-mae:6816.01282
[137]	validation_0-mae:6816.91521
[138]	validation_0-mae:6818.74995
[139]	validation_0-mae:6817.60037
[140]	validation_0-mae:6818.84060
[141]	validation_0-mae:6817.36501
[0]	validation_0-mae:13229.14441
[1]	validation_0-mae:13162.51044
[2]	validation_0-mae:13096.02150
[3]	validation_0-mae:13032.69972
[4]	validation_0-mae:12970.98058
[5]	validation_0-mae:12908.09893
[6]	validation_0-mae:12848.09028
[7]	validation_0-mae:12787.47784
[8]	validation_0-mae:12728.59780
[9]	validation_0-mae:12669.62979
[0]	validation_0-mae:13072.89111
[1]	validation_0-mae:12857.54382
[2]	validation_0-mae:12653.08638
[3]	validation_0-mae:12456.24097
[4]	validation_0-mae:12267.44403
[5]	validation_0-mae:12086.54584
[6]	validation_0-mae:11912.18447
[7]	validation_0-mae:11740.04452
[8]	validation_0-mae:11578.52287
[9]	validation_0-mae:11420.24798
[10]	validation_0-mae:11265.25477

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[0]	validation_0-mae:13283.68237
[1]	validation_0-mae:13268.88995
[2]	validation_0-mae:13254.13147
[3]	validation_0-mae:13239.39533
[4]	validation_0-mae:13224.68185
[5]	validation_0-mae:13209.99099
[6]	validation_0-mae:13195.32242
[7]	validation_0-mae:13180.67635
[8]	validation_0-mae:13166.05289
[9]	validation_0-mae:13151.45199
[10]	validation_0-mae:13136.87346
[0]	validation_0-mae:13298.49774
[1]	validation_0-mae:13298.49774
[2]	validation_0-mae:13298.49774
[3]	validation_0-mae:13298.49774
[4]	validation_0-mae:13298.49774
[5]	validation_0-mae:13298.49774
[6]	validation_0-mae:13298.49774
[7]	validation_0-mae:13298.49774
[8]	validation_0-mae:13298.49774
[9]	validation_0-mae:13298.49774
[0]	validation_0-mae:12760.97161
[1]	validation_0-mae:12293.86931
[2]	validation_0-mae:11853.35907
[3]	validation_0-mae:11467.95882
[4]	validation_0-mae:11116.34594
[5]	validation_0-mae:10802.42596
[6]	validation_0-mae:10522.27584

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[7]	validation_0-mae:10285.93659
[8]	validation_0-mae:10072.76466
[9]	validation_0-mae:9883.90513
[10]	validation_0-mae:9706.65881
[11]	validation_0-mae:9552.34747
[12]	validation_0-mae:9403.26731
[13]	validation_0-mae:9258.83789
[14]	validation_0-mae:9139.97423
[15]	validation_0-mae:9036.55785
[16]	validation_0-mae:8937.71217
[17]	validation_0-mae:8831.99807
[18]	validation_0-mae:8751.63491
[19]	validation_0-mae:8676.04934
[20]	validation_0-mae:8620.55554
[21]	validation_0-mae:8555.18844
[22]	validation_0-mae:8497.44661
[23]	validation_0-mae:8446.11001
[24]	validation_0-mae:8406.17071
[25]	validation_0-mae:8353.92346
[26]	validation_0-mae:8314.00537
[27]	validation_0-mae:8257.04202
[28]	validation_0-mae:8211.87319
[29]	validation_0-mae:8179.33721
[30]	validation_0-mae:8137.48410
[31]	validation_0-mae:8109.97632
[32]	validation_0-mae:8067.95836
[33]	validation_0-mae:8028.59082
[34]	validation_0-mae:7994.81328
[35]	validation_0-mae:7958.37419
[36]	validation_0-mae:7911.92589
[37]	validation_0-mae:7898.45728
[38]	validation_0-mae:7867.46386
[39]	validation_0-mae:7843.38861
[40]	validation_0-mae:7813.43658
[41]	validation_0-mae:7770.41316
[42]	validation_0-mae:7732.31157
[43]	validation_0-mae:7706.97134
[44]	validation_0-mae:7672.15106
[45]	validation_0-mae:7647.94630
[46]	validation_0-mae:7615.15781
[47]	validation_0-mae:7596.79233
[48]	validation_0-mae:7571.19356
[49]	validation_0-mae:7558.29913
[50]	validation_0-mae:7530.77491
[51]	validation_0-mae:7503.24306
[52]	validation_0-mae:7482.20168
[53]	validation_0-mae:7456.84375
[54]	validation_0-mae:7411.22840
[55]	validation_0-mae:7405.05314
[56]	validation_0-mae:7373.28654
[57]	validation_0-mae:7354.51298
[58]	validation_0-mae:7343.70483
[59]	validation_0-mae:7340.35086
[60]	validation_0-mae:7321.92706
[61]	validation_0-mae:7308.46001
[62]	validation_0-mae:7289.83131
[63]	validation_0-mae:7275.75386
[64]	validation_0-mae:7235.21566
[65]	validation_0-mae:7218.73166
[66]	validation_0-mae:7203.92093
[67]	validation_0-mae:7165.96864
[68]	validation_0-mae:7161.96079
[69]	validation_0-mae:7147.78671
[70]	validation_0-mae:7134.58824
[71]	validation_0-mae:7084.33315
[72]	validation_0-mae:7080.64368
[73]	validation_0-mae:7070.00346
[74]	validation_0-mae:7056.96393
[75]	validation_0-mae:7015.89338
[76]	validation_0-mae:7006.94004
[77]	validation_0-mae:6992.32163
[78]	validation_0-mae:6965.06802
[79]	validation_0-mae:6958.69189
[80]	validation_0-mae:6952.87903
[81]	validation_0-mae:6923.64054
[82]	validation_0-mae:6919.93918
[83]	validation_0-mae:6917.16468
[84]	validation_0-mae:6897.22056
[85]	validation_0-mae:6886.41396
[86]	validation_0-mae:6883.04252
[87]	validation_0-mae:6876.97430
[88]	validation_0-mae:6858.53041
[89]	validation_0-mae:6840.66012
[90]	validation_0-mae:6835.36946
[91]	validation_0-mae:6831.45508
[92]	validation_0-mae:6819.40355
[93]	validation_0-mae:6816.83807
[94]	validation_0-mae:6806.36086
[95]	validation_0-mae:6802.40513
[96]	validation_0-mae:6793.03503
[97]	validation_0-mae:6790.24314
[98]	validation_0-mae:6787.56000
[99]	validation_0-mae:6784.04245
[100]	validation_0-mae:6769.32325
[101]	validation_0-mae:6764.82562
[102]	validation_0-mae:6747.75027
[103]	validation_0-mae:6736.23365
[104]	validation_0-mae:6734.34939
[105]	validation_0-mae:6729.76208
[106]	validation_0-mae:6722.81677
[107]	validation_0-mae:6719.44838
[108]	validation_0-mae:6716.19255
[109]	validation_0-mae:6709.50264
[110]	validation_0-mae:6707.37162
[111]	validation_0-mae:6696.07584
[112]	validation_0-mae:6691.03666
[113]	validation_0-mae:6688.82587
[114]	validation_0-mae:6679.62187
[115]	validation_0-mae:6679.37014
[116]	validation_0-mae:6675.98155
[117]	validation_0-mae:6672.55876
[118]	validation_0-mae:6669.18862
[119]	validation_0-mae:6670.25467
[120]	validation_0-mae:6665.76423
[121]	validation_0-mae:6663.15784
[122]	validation_0-mae:6661.51291
[123]	validation_0-mae:6656.92109
[124]	validation_0-mae:6658.00637
[125]	validation_0-mae:6654.27691
[126]	validation_0-mae:6651.81319
[127]	validation_0-mae:6650.81838
[128]	validation_0-mae:6648.45733
[129]	validation_0-mae:6645.05352
[130]	validation_0-mae:6643.88653
[131]	validation_0-mae:6644.46563
[132]	validation_0-mae:6641.61937
[133]	validation_0-mae:6638.78018
[134]	validation_0-mae:6637.94148
[135]	validation_0-mae:6635.69670
[136]	validation_0-mae:6636.50414
[137]	validation_0-mae:6633.14707
[138]	validation_0-mae:6629.49781
[139]	validation_0-mae:6627.21834
[140]	validation_0-mae:6627.19920
[141]	validation_0-mae:6626.16422
[142]	validation_0-mae:6624.55317
[143]	validation_0-mae:6623.79230
[144]	validation_0-mae:6613.15585
[145]	validation_0-mae:6608.76448
[146]	validation_0-mae:6606.59847
[147]	validation_0-mae:6603.14414
[148]	validation_0-mae:6603.38088
[149]	validation_0-mae:6603.33586
[150]	validation_0-mae:6604.22886
[151]	validation_0-mae:6599.87764
[152]	validation_0-mae:6598.95809
[153]	validation_0-mae:6599.32452
[154]	validation_0-mae:6594.32973
[155]	validation_0-mae:6593.89915
[156]	validation_0-mae:6592.01244
[157]	validation_0-mae:6590.47258
[158]	validation_0-mae:6589.86881
[159]	validation_0-mae:6589.90414
[160]	validation_0-mae:6589.28930
[161]	validation_0-mae:6591.30444
[162]	validation_0-mae:6587.86126
[163]	validation_0-mae:6588.18137
[164]	validation_0-mae:6582.92855
[165]	validation_0-mae:6581.16408
[166]	validation_0-mae:6578.90950
[167]	validation_0-mae:6579.71905
[168]	validation_0-mae:6578.44829
[169]	validation_0-mae:6579.52868
[170]	validation_0-mae:6577.57479
[171]	validation_0-mae:6576.54951
[172]	validation_0-mae:6575.59044
[173]	validation_0-mae:6574.35489
[174]	validation_0-mae:6574.51338
[175]	validation_0-mae:6573.52640
[176]	validation_0-mae:6572.34281
[177]	validation_0-mae:6570.60306
[178]	validation_0-mae:6570.15919
[179]	validation_0-mae:6570.05304
[180]	validation_0-mae:6571.01218
[181]	validation_0-mae:6571.13609
[182]	validation_0-mae:6571.36034
[183]	validation_0-mae:6571.35259
[184]	validation_0-mae:6570.86300
[185]	validation_0-mae:6568.78931
[186]	validation_0-mae:6567.82572
[187]	validation_0-mae:6567.95667
[188]	validation_0-mae:6567.82831
[189]	validation_0-mae:6568.95828
[190]	validation_0-mae:6569.27932
[191]	validation_0-mae:6568.75463
[192]	validation_0-mae:6567.49274
[193]	validation_0-mae:6568.43268
[194]	validation_0-mae:6568.12039
[195]	validation_0-mae:6569.05674
[196]	validation_0-mae:6569.40483
[197]	validation_0-mae:6570.47687
[198]	validation_0-mae:6569.55995
[199]	validation_0-mae:6569.86159
[200]	validation_0-mae:6571.88521
[201]	validation_0-mae:6572.66263
[202]	validation_0-mae:6572.53184
[203]	validation_0-mae:6572.65433
[204]	validation_0-mae:6573.34665
[205]	validation_0-mae:6573.12402
[206]	validation_0-mae:6573.28663
[207]	validation_0-mae:6576.05387
[208]	validation_0-mae:6575.00396
[209]	validation_0-mae:6575.01241
[210]	validation_0-mae:6575.64504
[211]	validation_0-mae:6576.76911
[212]	validation_0-mae:6577.49511
[213]	validation_0-mae:6578.51980
[214]	validation_0-mae:6578.22675
[215]	validation_0-mae:6578.32206
[216]	validation_0-mae:6578.21415
[217]	validation_0-mae:6576.97197
[218]	validation_0-mae:6577.95225
[219]	validation_0-mae:6579.01551
[220]	validation_0-mae:6577.36418
[221]	validation_0-mae:6577.66450
[222]	validation_0-mae:6581.89200
[223]	validation_0-mae:6580.65083
[224]	validation_0-mae:6579.33099
[225]	validation_0-mae:6579.28473
[226]	validation_0-mae:6579.49882
[227]	validation_0-mae:6577.58815
[228]	validation_0-mae:6577.19226
[229]	validation_0-mae:6580.44475
[230]	validation_0-mae:6580.35843
[231]	validation_0-mae:6577.96059
[232]	validation_0-mae:6578.22754
[233]	validation_0-mae:6578.20920
[234]	validation_0-mae:6578.49333
[235]	validation_0-mae:6578.72729
[236]	validation_0-mae:6579.38592
[237]	validation_0-mae:6580.46014
[238]	validation_0-mae:6580.01604
[239]	validation_0-mae:6579.57601
[240]	validation_0-mae:6578.75976
[241]	validation_0-mae:6579.38090
[242]	validation_0-mae:6579.40416
[243]	validation_0-mae:6580.24388
[244]	validation_0-mae:6583.62178
[245]	validation_0-mae:6582.46896
[246]	validation_0-mae:6579.75803
[247]	validation_0-mae:6581.31144
[248]	validation_0-mae:6582.24891
[249]	validation_0-mae:6581.97015
[250]	validation_0-mae:6583.76399
[251]	validation_0-mae:6581.54435
[252]	validation_0-mae:6581.32163
[253]	validation_0-mae:6584.44856
[254]	validation_0-mae:6584.33298
[255]	validation_0-mae:6584.21304
[256]	validation_0-mae:6584.17378
[257]	validation_0-mae:6583.09706
[258]	validation_0-mae:6583.11173
[259]	validation_0-mae:6583.02905
[260]	validation_0-mae:6582.19845
[261]	validation_0-mae:6582.31174
[262]	validation_0-mae:6583.05067
[263]	validation_0-mae:6582.57036
[264]	validation_0-mae:6582.98809
[265]	validation_0-mae:6582.89014
[266]	validation_0-mae:6581.76512
[267]	validation_0-mae:6579.46899
[268]	validation_0-mae:6581.32076
[269]	validation_0-mae:6583.26562
[270]	validation_0-mae:6586.13760
[271]	validation_0-mae:6585.62209
[272]	validation_0-mae:6584.92882
[273]	validation_0-mae:6585.17786
[274]	validation_0-mae:6585.84338
[275]	validation_0-mae:6585.49313
[276]	validation_0-mae:6587.38746
[277]	validation_0-mae:6587.76254
[278]	validation_0-mae:6585.79458
[279]	validation_0-mae:6586.76060
[280]	validation_0-mae:6587.16353
[281]	validation_0-mae:6587.89828
[282]	validation_0-mae:6587.75218
[283]	validation_0-mae:6590.95662
[284]	validation_0-mae:6589.91880
[285]	validation_0-mae:6592.55920
[286]	validation_0-mae:6595.19496
[287]	validation_0-mae:6595.80331
[288]	validation_0-mae:6598.65676
[289]	validation_0-mae:6599.40729
[290]	validation_0-mae:6599.97447
[291]	validation_0-mae:6599.43852
[292]	validation_0-mae:6599.70984
[293]	validation_0-mae:6600.08986
[294]	validation_0-mae:6600.12757
[295]	validation_0-mae:6600.78030
[296]	validation_0-mae:6601.10338
[297]	validation_0-mae:6600.90632
[298]	validation_0-mae:6602.20434
[299]	validation_0-mae:6601.77737
[300]	validation_0-mae:6602.41010
[301]	validation_0-mae:6602.67699
[302]	validation_0-mae:6605.52817
[303]	validation_0-mae:6606.22628
[304]	validation_0-mae:6606.52627
[305]	validation_0-mae:6606.23869
[306]	validation_0-mae:6607.84672
[307]	validation_0-mae:6609.79529
[308]	validation_0-mae:6609.81963
[309]	validation_0-mae:6611.08832
[310]	validation_0-mae:6610.45511
[311]	validation_0-mae:6607.41430
[312]	validation_0-mae:6608.98658
[313]	validation_0-mae:6609.98168
[314]	validation_0-mae:6611.10838
[315]	validation_0-mae:6612.17708
[316]	validation_0-mae:6612.99198
[317]	validation_0-mae:6613.32314
[318]	validation_0-mae:6613.43083
[319]	validation_0-mae:6613.67557
[320]	validation_0-mae:6613.38167
[321]	validation_0-mae:6614.27773
[322]	validation_0-mae:6614.56039
[323]	validation_0-mae:6615.63554
[324]	validation_0-mae:6615.06567
[325]	validation_0-mae:6615.68976
[326]	validation_0-mae:6614.47938
[327]	validation_0-mae:6615.03566
[328]	validation_0-mae:6615.86975
[329]	validation_0-mae:6615.92061
[330]	validation_0-mae:6615.50182
[331]	validation_0-mae:6615.22738
[332]	validation_0-mae:6615.70768
[333]	validation_0-mae:6615.79762
[334]	validation_0-mae:6616.63145
[335]	validation_0-mae:6615.92533
[336]	validation_0-mae:6616.58856
[337]	validation_0-mae:6616.52987
[338]	validation_0-mae:6615.68083
[339]	validation_0-mae:6615.23345
[340]	validation_0-mae:6616.88991
[341]	validation_0-mae:6617.17402
[342]	validation_0-mae:6616.17018
[343]	validation_0-mae:6616.88567
[344]	validation_0-mae:6618.06791
[345]	validation_0-mae:6618.23145
[346]	validation_0-mae:6620.72588
[347]	validation_0-mae:6620.88944
[348]	validation_0-mae:6621.21911
[349]	validation_0-mae:6621.64342
[350]	validation_0-mae:6620.83351
[351]	validation_0-mae:6621.22809
[352]	validation_0-mae:6621.01877
[353]	validation_0-mae:6621.92066
[354]	validation_0-mae:6624.63356
[355]	validation_0-mae:6623.37487
[356]	validation_0-mae:6622.45329
[357]	validation_0-mae:6622.55130
[358]	validation_0-mae:6622.69154
[359]	validation_0-mae:6621.85907
[360]	validation_0-mae:6621.73940
[361]	validation_0-mae:6621.00728
[362]	validation_0-mae:6621.41445
[363]	validation_0-mae:6623.41985
[364]	validation_0-mae:6624.92764
[365]	validation_0-mae:6627.00256
[366]	validation_0-mae:6628.87911
[367]	validation_0-mae:6630.28286
[368]	validation_0-mae:6631.78238
[369]	validation_0-mae:6633.77171
[370]	validation_0-mae:6633.59514
[371]	validation_0-mae:6633.28094
[372]	validation_0-mae:6633.62473
[373]	validation_0-mae:6634.44513
[374]	validation_0-mae:6634.05971
[375]	validation_0-mae:6634.76870
[376]	validation_0-mae:6635.22414
[377]	validation_0-mae:6634.91340
[378]	validation_0-mae:6635.03314
[379]	validation_0-mae:6634.96299
[380]	validation_0-mae:6637.21053
[381]	validation_0-mae:6637.64693
[382]	validation_0-mae:6637.71506
[383]	validation_0-mae:6638.06838
[384]	validation_0-mae:6637.08975
[385]	validation_0-mae:6638.90758
[386]	validation_0-mae:6639.44455
[387]	validation_0-mae:6640.02903
[388]	validation_0-mae:6639.68086
[389]	validation_0-mae:6639.55651
[390]	validation_0-mae:6639.85441
[391]	validation_0-mae:6640.25472
[392]	validation_0-mae:6640.30127
[393]	validation_0-mae:6641.74128
[394]	validation_0-mae:6642.36439
[395]	validation_0-mae:6641.78969
[396]	validation_0-mae:6640.57029
[397]	validation_0-mae:6640.17328
[398]	validation_0-mae:6640.18459
[399]	validation_0-mae:6641.05959
[400]	validation_0-mae:6640.81092
[401]	validation_0-mae:6641.45407
[402]	validation_0-mae:6643.71168
[403]	validation_0-mae:6643.50403
[404]	validation_0-mae:6646.09902
[405]	validation_0-mae:6646.26234
[406]	validation_0-mae:6646.34135
[407]	validation_0-mae:6646.67334
[408]	validation_0-mae:6647.82986
[409]	validation_0-mae:6648.08142
[410]	validation_0-mae:6648.35933
[411]	validation_0-mae:6648.92973
[412]	validation_0-mae:6649.03131
[413]	validation_0-mae:6649.01797
[414]	validation_0-mae:6649.30272
[415]	validation_0-mae:6649.09030
[416]	validation_0-mae:6649.54640
[417]	validation_0-mae:6648.69361
[418]	validation_0-mae:6648.99848
[419]	validation_0-mae:6649.03320
[420]	validation_0-mae:6649.87259
[421]	validation_0-mae:6649.57413
[422]	validation_0-mae:6650.80324
[423]	validation_0-mae:6650.75096
[424]	validation_0-mae:6652.51680
[425]	validation_0-mae:6653.55875
[426]	validation_0-mae:6653.68420
[427]	validation_0-mae:6654.38067
[428]	validation_0-mae:6655.17786
[429]	validation_0-mae:6655.51298
[430]	validation_0-mae:6656.93114
[431]	validation_0-mae:6656.36586
[432]	validation_0-mae:6657.06979
[433]	validation_0-mae:6657.21436
[434]	validation_0-mae:6658.66540
[435]	validation_0-mae:6658.89282
[436]	validation_0-mae:6659.79278
[437]	validation_0-mae:6661.31805
[438]	validation_0-mae:6659.85764
[439]	validation_0-mae:6662.10794
[440]	validation_0-mae:6662.73475
[441]	validation_0-mae:6661.36073
[442]	validation_0-mae:6662.68193
[443]	validation_0-mae:6662.50308
[444]	validation_0-mae:6664.12831
[445]	validation_0-mae:6665.85280
[446]	validation_0-mae:6665.97422
[447]	validation_0-mae:6666.33125
[448]	validation_0-mae:6667.62824
[449]	validation_0-mae:6669.59600
[450]	validation_0-mae:6671.21201
[451]	validation_0-mae:6671.20492
[452]	validation_0-mae:6670.12762
[453]	validation_0-mae:6671.53673
[454]	validation_0-mae:6672.78431
[455]	validation_0-mae:6672.42760
[456]	validation_0-mae:6673.22179
[457]	validation_0-mae:6673.58787
[458]	validation_0-mae:6674.43888
[459]	validation_0-mae:6674.09772
[460]	validation_0-mae:6674.45287
[461]	validation_0-mae:6673.18637
[462]	validation_0-mae:6671.38317
[463]	validation_0-mae:6673.45932
[464]	validation_0-mae:6673.27887
[465]	validation_0-mae:6672.38064
[466]	validation_0-mae:6674.31349
[467]	validation_0-mae:6674.37459
[468]	validation_0-mae:6674.21273
[469]	validation_0-mae:6673.88381
[470]	validation_0-mae:6674.79739
[471]	validation_0-mae:6675.06834
[472]	validation_0-mae:6673.80057
[473]	validation_0-mae:6674.04545
[474]	validation_0-mae:6674.54969
[475]	validation_0-mae:6674.66009
[476]	validation_0-mae:6674.89759
[477]	validation_0-mae:6675.50426
[478]	validation_0-mae:6675.29142
[479]	validation_0-mae:6675.25883
[480]	validation_0-mae:6674.61352
[481]	validation_0-mae:6675.84599
[482]	validation_0-mae:6675.22892
[483]	validation_0-mae:6676.21870
[484]	validation_0-mae:6677.13406
[485]	validation_0-mae:6676.61622
[486]	validation_0-mae:6676.51069
[487]	validation_0-mae:6675.88557
[488]	validation_0-mae:6676.08561
[489]	validation_0-mae:6677.39227
[490]	validation_0-mae:6678.73209
[491]	validation_0-mae:6679.19476
[492]	validation_0-mae:6678.93294
[493]	validation_0-mae:6680.14052
[494]	validation_0-mae:6679.95996
[495]	validation_0-mae:6680.26559
[496]	validation_0-mae:6680.59783
[497]	validation_0-mae:6681.88967
[498]	validation_0-mae:6682.55903
[499]	validation_0-mae:6683.13027
[500]	validation_0-mae:6683.56335
[501]	validation_0-mae:6683.88633
[502]	validation_0-mae:6682.75228
[503]	validation_0-mae:6682.30930
[504]	validation_0-mae:6682.39435
[505]	validation_0-mae:6684.93511
[506]	validation_0-mae:6686.19125
[507]	validation_0-mae:6688.37498
[508]	validation_0-mae:6689.67117
[509]	validation_0-mae:6689.47232
[510]	validation_0-mae:6689.30976
[511]	validation_0-mae:6689.09593
[512]	validation_0-mae:6692.81204
[513]	validation_0-mae:6694.01605
[514]	validation_0-mae:6694.16327
[515]	validation_0-mae:6697.76914
[516]	validation_0-mae:6698.05255
[517]	validation_0-mae:6698.31013
[518]	validation_0-mae:6699.61167
[519]	validation_0-mae:6701.97459
[520]	validation_0-mae:6702.72220
[521]	validation_0-mae:6704.10092
[522]	validation_0-mae:6704.00143
[523]	validation_0-mae:6702.41694
[524]	validation_0-mae:6705.80611
[525]	validation_0-mae:6706.70539
[526]	validation_0-mae:6706.05911
[527]	validation_0-mae:6707.14318
[528]	validation_0-mae:6706.63966
[529]	validation_0-mae:6708.01740
[530]	validation_0-mae:6706.85506
[531]	validation_0-mae:6706.32563
[532]	validation_0-mae:6708.09370
[533]	validation_0-mae:6707.55546
[534]	validation_0-mae:6706.08585
[535]	validation_0-mae:6705.42082
[536]	validation_0-mae:6705.21184
[537]	validation_0-mae:6705.29915
[538]	validation_0-mae:6705.62089
[539]	validation_0-mae:6705.77227
[540]	validation_0-mae:6705.44452
[541]	validation_0-mae:6706.03808
[542]	validation_0-mae:6706.80824
[543]	validation_0-mae:6707.21595
[544]	validation_0-mae:6706.78469
[545]	validation_0-mae:6706.51418
[546]	validation_0-mae:6707.18058
[547]	validation_0-mae:6706.92913
[548]	validation_0-mae:6707.53462
[0]	validation_0-mae:12871.43084
[1]	validation_0-mae:12492.41120
[2]	validation_0-mae:12140.15796
[3]	validation_0-mae:11835.60093
[4]	validation_0-mae:11566.03716
[5]	validation_0-mae:11326.86929
[6]	validation_0-mae:11106.91794
[7]	validation_0-mae:10919.81445
[8]	validation_0-mae:10724.52670
[9]	validation_0-mae:10560.72172
[10]	validation_0-mae:10383.35893
[11]	validation_0-mae:10189.14432
[12]	validation_0-mae:10079.42199
[13]	validation_0-mae:9908.72941
[14]	validation_0-mae:9799.80588
[15]	validation_0-mae:9650.72275
[16]	validation_0-mae:9557.95968
[17]	validation_0-mae:9438.28382
[18]	validation_0-mae:9350.54651
[19]	validation_0-mae:9239.38337
[20]	validation_0-mae:9177.48716
[21]	validation_0-mae:9046.87556
[22]	validation_0-mae:8947.51622
[23]	validation_0-mae:8842.12350
[24]	validation_0-mae:8772.42509
[25]	validation_0-mae:8705.66575
[26]	validation_0-mae:8633.79537
[27]	validation_0-mae:8559.60447
[28]	validation_0-mae:8465.01623
[29]	validation_0-mae:8386.40855
[30]	validation_0-mae:8318.28747
[31]	validation_0-mae:8229.16876
[32]	validation_0-mae:8155.21267
[33]	validation_0-mae:8133.25636
[34]	validation_0-mae:8066.76648
[35]	validation_0-mae:8005.51715
[36]	validation_0-mae:7979.76062
[37]	validation_0-mae:7966.06041
[38]	validation_0-mae:7911.39532
[39]	validation_0-mae:7861.93970
[40]	validation_0-mae:7792.87467
[41]	validation_0-mae:7762.29844
[42]	validation_0-mae:7704.94490
[43]	validation_0-mae:7653.25364
[44]	validation_0-mae:7625.27034
[45]	validation_0-mae:7584.34811
[46]	validation_0-mae:7536.81811
[47]	validation_0-mae:7487.49125
[48]	validation_0-mae:7473.99221
[49]	validation_0-mae:7449.52867

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[62]	validation_0-mae:7086.05501
[63]	validation_0-mae:7046.37146
[64]	validation_0-mae:7009.44929
[65]	validation_0-mae:6996.18545
[66]	validation_0-mae:6964.04742
[67]	validation_0-mae:6932.66365
[68]	validation_0-mae:6901.61875
[69]	validation_0-mae:6870.29002
[70]	validation_0-mae:6835.95350
[71]	validation_0-mae:6830.39491
[72]	validation_0-mae:6801.00096
[73]	validation_0-mae:6775.27043
[74]	validation_0-mae:6759.89066
[75]	validation_0-mae:6729.83738
[76]	validation_0-mae:6717.73029
[77]	validation_0-mae:6690.54257
[78]	validation_0-mae:6643.32789
[79]	validation_0-mae:6613.80563
[80]	validation_0-mae:6580.68961
[81]	validation_0-mae:6570.87141
[82]	validation_0-mae:6545.47072
[83]	validation_0-mae:6528.91092
[84]	validation_0-mae:6504.46538
[85]	validation_0-mae:6483.35943
[86]	validation_0-mae:6455.95124
[87]	validation_0-mae:6437.40839
[88]	validation_0-mae:6408.46299
[89]	validation_0-mae:6385.28236
[90]	validation_0-mae:6345.12062
[91]	validation_0-mae:6333.18158
[92]	validation_0-mae:6313.05570
[93]	validation_0-mae:6291.38464
[94]	validation_0-mae:6285.65582
[95]	validation_0-mae:6266.11672
[96]	validation_0-mae:6242.33140
[97]	validation_0-mae:6230.07593
[98]	validation_0-mae:6207.60075
[99]	validation_0-mae:6185.63119
[100]	validation_0-mae:6183.25134
[101]	validation_0-mae:6164.89380
[102]	validation_0-mae:6143.90082
[103]	validation_0-mae:6132.83368
[104]	validation_0-mae:6123.19647
[105]	validation_0-mae:6104.27445
[106]	validation_0-mae:6082.00286
[107]	validation_0-mae:6068.83232
[108]	validation_0-mae:6033.67302
[109]	validation_0-mae:6008.35861
[110]	validation_0-mae:5988.44918
[111]	validation_0-mae:5955.27801
[112]	validation_0-mae:5942.61369
[113]	validation_0-mae:5927.30649
[114]	validation_0-mae:5910.12111
[115]	validation_0-mae:5891.46383
[116]	validation_0-mae:5871.37575
[117]	validation_0-mae:5858.32737
[118]	validation_0-mae:5851.77934
[119]	validation_0-mae:5836.69470
[120]	validation_0-mae:5819.93168
[121]	validation_0-mae:5804.92751
[122]	validation_0-mae:5795.73195
[123]	validation_0-mae:5765.57808
[124]	validation_0-mae:5736.66569
[125]	validation_0-mae:5732.06947
[126]	validation_0-mae:5722.61156
[127]	validation_0-mae:5714.73554
[128]	validation_0-mae:5698.57579
[129]	validation_0-mae:5690.12273
[130]	validation_0-mae:5678.58626
[131]	validation_0-mae:5664.15001
[132]	validation_0-mae:5652.27209
[133]	validation_0-mae:5645.86892
[134]	validation_0-mae:5629.77133
[135]	validation_0-mae:5616.20759
[136]	validation_0-mae:5606.36568
[137]	validation_0-mae:5595.69585
[138]	validation_0-mae:5585.14924
[139]	validation_0-mae:5571.60111
[140]	validation_0-mae:5558.81476
[141]	validation_0-mae:5553.52338
[142]	validation_0-mae:5543.75422
[143]	validation_0-mae:5540.49480
[144]	validation_0-mae:5529.63792
[145]	validation_0-mae:5523.44718
[146]	validation_0-mae:5504.14676
[147]	validation_0-mae:5495.20339
[148]	validation_0-mae:5486.58028
[149]	validation_0-mae:5470.11448
[150]	validation_0-mae:5462.65507
[151]	validation_0-mae:5451.57171
[152]	validation_0-mae:5430.87143
[153]	validation_0-mae:5422.93120
[154]	validation_0-mae:5416.62704
[155]	validation_0-mae:5404.43185
[156]	validation_0-mae:5398.52943
[157]	validation_0-mae:5389.28733
[158]	validation_0-mae:5382.73859
[159]	validation_0-mae:5375.23961
[160]	validation_0-mae:5372.26634
[161]	validation_0-mae:5370.89446
[162]	validation_0-mae:5367.13910
[163]	validation_0-mae:5358.16547
[164]	validation_0-mae:5357.84981
[165]	validation_0-mae:5355.43526
[166]	validation_0-mae:5344.04193
[167]	validation_0-mae:5339.29181
[168]	validation_0-mae:5322.73483
[169]	validation_0-mae:5311.73320
[170]	validation_0-mae:5303.37891
[171]	validation_0-mae:5296.14089
[172]	validation_0-mae:5292.59048
[173]	validation_0-mae:5285.67711
[174]	validation_0-mae:5280.33256
[175]	validation_0-mae:5279.58680
[176]	validation_0-mae:5273.42196
[177]	validation_0-mae:5270.31530
[178]	validation_0-mae:5265.55880
[179]	validation_0-mae:5258.24472
[180]	validation_0-mae:5256.92624
[181]	validation_0-mae:5255.77068
[182]	validation_0-mae:5250.34598
[183]	validation_0-mae:5244.97334
[184]	validation_0-mae:5243.69775
[185]	validation_0-mae:5239.95255
[186]	validation_0-mae:5231.84238
[187]	validation_0-mae:5228.53976
[188]	validation_0-mae:5223.24472
[189]	validation_0-mae:5217.88733
[190]	validation_0-mae:5211.47932
[191]	validation_0-mae:5208.03759
[192]	validation_0-mae:5206.11472
[193]	validation_0-mae:5205.71575
[194]	validation_0-mae:5202.85816
[195]	validation_0-mae:5199.89306
[196]	validation_0-mae:5198.38839
[197]	validation_0-mae:5195.43279
[198]	validation_0-mae:5192.25270
[199]	validation_0-mae:5189.79597
[200]	validation_0-mae:5187.08212
[201]	validation_0-mae:5183.54400
[202]	validation_0-mae:5183.13843
[203]	validation_0-mae:5173.87818
[204]	validation_0-mae:5174.11175
[205]	validation_0-mae:5159.03234
[206]	validation_0-mae:5153.37013
[207]	validation_0-mae:5148.00193
[208]	validation_0-mae:5142.09423
[209]	validation_0-mae:5137.27505
[210]	validation_0-mae:5135.17059
[211]	validation_0-mae:5131.03766
[212]	validation_0-mae:5126.98264
[213]	validation_0-mae:5125.63948
[214]	validation_0-mae:5123.09030
[215]	validation_0-mae:5121.38899
[216]	validation_0-mae:5118.31866
[217]	validation_0-mae:5116.88871
[218]	validation_0-mae:5116.40905
[219]	validation_0-mae:5114.56129
[220]	validation_0-mae:5107.56325
[221]	validation_0-mae:5096.22780
[222]	validation_0-mae:5091.19163
[223]	validation_0-mae:5087.58721
[224]	validation_0-mae:5083.50361
[225]	validation_0-mae:5078.59684
[226]	validation_0-mae:5077.34196
[227]	validation_0-mae:5075.05722
[228]	validation_0-mae:5072.41839
[229]	validation_0-mae:5071.02505
[230]	validation_0-mae:5066.76852
[231]	validation_0-mae:5067.09289
[232]	validation_0-mae:5063.78226
[233]	validation_0-mae:5061.58885
[234]	validation_0-mae:5058.45798
[235]	validation_0-mae:5058.02303
[236]	validation_0-mae:5055.03924
[237]	validation_0-mae:5048.29275
[238]	validation_0-mae:5047.14733
[239]	validation_0-mae:5045.81228
[240]	validation_0-mae:5040.36213
[241]	validation_0-mae:5034.84430
[242]	validation_0-mae:5032.83869
[243]	validation_0-mae:5032.09885
[244]	validation_0-mae:5025.59676
[245]	validation_0-mae:5023.20499
[246]	validation_0-mae:5019.42316
[247]	validation_0-mae:5016.51201
[248]	validation_0-mae:5014.36313
[249]	validation_0-mae:5013.36961
[250]	validation_0-mae:5013.60588
[251]	validation_0-mae:5010.56243
[252]	validation_0-mae:5007.97468
[253]	validation_0-mae:5004.13624
[254]	validation_0-mae:5002.28469
[255]	validation_0-mae:4999.58242
[256]	validation_0-mae:4997.43073
[257]	validation_0-mae:4988.92484
[258]	validation_0-mae:4984.86712
[259]	validation_0-mae:4983.98926
[260]	validation_0-mae:4982.33599
[261]	validation_0-mae:4979.96692
[262]	validation_0-mae:4978.57045
[263]	validation_0-mae:4975.42483
[264]	validation_0-mae:4975.65895
[265]	validation_0-mae:4975.04294
[266]	validation_0-mae:4972.31908
[267]	validation_0-mae:4972.94088
[268]	validation_0-mae:4971.74548
[269]	validation_0-mae:4969.91363
[270]	validation_0-mae:4968.32902
[271]	validation_0-mae:4966.79647
[272]	validation_0-mae:4960.54326
[273]	validation_0-mae:4956.85554
[274]	validation_0-mae:4956.19722
[275]	validation_0-mae:4954.37443
[276]	validation_0-mae:4953.24883
[277]	validation_0-mae:4951.90054
[278]	validation_0-mae:4946.52104
[279]	validation_0-mae:4945.17837
[280]	validation_0-mae:4944.25450
[281]	validation_0-mae:4942.30719
[282]	validation_0-mae:4941.28871
[283]	validation_0-mae:4939.94091
[284]	validation_0-mae:4938.20883
[285]	validation_0-mae:4937.66574
[286]	validation_0-mae:4934.47064
[287]	validation_0-mae:4934.19644
[288]	validation_0-mae:4934.05010
[289]	validation_0-mae:4932.01671
[290]	validation_0-mae:4931.52226
[291]	validation_0-mae:4929.20539
[292]	validation_0-mae:4928.41612
[293]	validation_0-mae:4924.03774
[294]	validation_0-mae:4923.42074
[295]	validation_0-mae:4923.28378
[296]	validation_0-mae:4922.29424
[297]	validation_0-mae:4922.37031
[298]	validation_0-mae:4921.24208
[299]	validation_0-mae:4918.57744
[300]	validation_0-mae:4917.91340
[301]	validation_0-mae:4916.88900
[302]	validation_0-mae:4917.19559
[303]	validation_0-mae:4912.22435
[304]	validation_0-mae:4909.68730
[305]	validation_0-mae:4905.92863
[306]	validation_0-mae:4904.72752
[307]	validation_0-mae:4904.55036
[308]	validation_0-mae:4903.68098
[309]	validation_0-mae:4902.46993
[310]	validation_0-mae:4901.94416
[311]	validation_0-mae:4900.68166
[312]	validation_0-mae:4898.00523
[313]	validation_0-mae:4897.65333
[314]	validation_0-mae:4897.10872
[315]	validation_0-mae:4897.79345
[316]	validation_0-mae:4895.04791
[317]	validation_0-mae:4893.80933
[318]	validation_0-mae:4892.09210
[319]	validation_0-mae:4889.86933
[320]	validation_0-mae:4888.10922
[321]	validation_0-mae:4887.25873
[322]	validation_0-mae:4885.20387
[323]	validation_0-mae:4884.88343
[324]	validation_0-mae:4885.16575
[325]	validation_0-mae:4882.35635
[326]	validation_0-mae:4878.18753
[327]	validation_0-mae:4874.97036
[328]	validation_0-mae:4874.15922
[329]	validation_0-mae:4874.25784
[330]	validation_0-mae:4870.57271
[331]	validation_0-mae:4868.75054
[332]	validation_0-mae:4867.61361
[333]	validation_0-mae:4867.95097
[334]	validation_0-mae:4867.49988
[335]	validation_0-mae:4865.50256
[336]	validation_0-mae:4865.64175
[337]	validation_0-mae:4862.30108
[338]	validation_0-mae:4859.84887
[339]	validation_0-mae:4859.46597
[340]	validation_0-mae:4859.89274
[341]	validation_0-mae:4857.33024
[342]	validation_0-mae:4854.98112
[343]	validation_0-mae:4854.64388
[344]	validation_0-mae:4852.79893
[345]	validation_0-mae:4852.30605
[346]	validation_0-mae:4851.22652
[347]	validation_0-mae:4848.03606
[348]	validation_0-mae:4844.94650
[349]	validation_0-mae:4843.26930
[350]	validation_0-mae:4840.87426
[351]	validation_0-mae:4839.79480
[352]	validation_0-mae:4839.67027
[353]	validation_0-mae:4839.72340
[354]	validation_0-mae:4839.28337
[355]	validation_0-mae:4837.45556
[356]	validation_0-mae:4836.92832
[357]	validation_0-mae:4834.88857
[358]	validation_0-mae:4831.07834
[359]	validation_0-mae:4831.02424
[360]	validation_0-mae:4830.18603
[361]	validation_0-mae:4828.64352
[362]	validation_0-mae:4827.91046
[363]	validation_0-mae:4826.77035
[364]	validation_0-mae:4824.90521
[365]	validation_0-mae:4821.54713
[366]	validation_0-mae:4821.92426
[367]	validation_0-mae:4820.65957
[368]	validation_0-mae:4818.82144
[369]	validation_0-mae:4818.12131
[370]	validation_0-mae:4815.88406
[371]	validation_0-mae:4815.26543
[372]	validation_0-mae:4814.80482
[373]	validation_0-mae:4813.42332
[374]	validation_0-mae:4810.57919
[375]	validation_0-mae:4810.29470
[376]	validation_0-mae:4808.77818
[377]	validation_0-mae:4807.04219
[378]	validation_0-mae:4805.05227
[379]	validation_0-mae:4805.53070
[380]	validation_0-mae:4805.30370
[381]	validation_0-mae:4804.70055
[382]	validation_0-mae:4804.84670
[383]	validation_0-mae:4804.60281
[384]	validation_0-mae:4804.65882
[385]	validation_0-mae:4802.24802
[386]	validation_0-mae:4800.10642
[387]	validation_0-mae:4799.58359
[388]	validation_0-mae:4797.87901
[389]	validation_0-mae:4797.49756
[390]	validation_0-mae:4796.16715
[391]	validation_0-mae:4795.52924
[392]	validation_0-mae:4794.90742
[393]	validation_0-mae:4792.34689
[394]	validation_0-mae:4792.37860
[395]	validation_0-mae:4792.93979
[396]	validation_0-mae:4793.18263
[397]	validation_0-mae:4789.75732
[398]	validation_0-mae:4789.29134
[399]	validation_0-mae:4788.81679
[400]	validation_0-mae:4788.31730
[401]	validation_0-mae:4787.59563
[402]	validation_0-mae:4786.08828
[403]	validation_0-mae:4785.67515
[404]	validation_0-mae:4783.22942
[405]	validation_0-mae:4781.78366
[406]	validation_0-mae:4781.03639
[407]	validation_0-mae:4780.90979
[408]	validation_0-mae:4780.46393
[409]	validation_0-mae:4778.82287
[410]	validation_0-mae:4778.07691
[411]	validation_0-mae:4777.39160
[412]	validation_0-mae:4775.22271
[413]	validation_0-mae:4773.99838
[414]	validation_0-mae:4772.12429
[415]	validation_0-mae:4772.86057
[416]	validation_0-mae:4771.84654
[417]	validation_0-mae:4770.51739
[418]	validation_0-mae:4768.93232
[419]	validation_0-mae:4768.37954
[420]	validation_0-mae:4767.73385
[421]	validation_0-mae:4766.84638
[422]	validation_0-mae:4766.80747
[423]	validation_0-mae:4764.84905
[424]	validation_0-mae:4764.12636
[425]	validation_0-mae:4762.70735
[426]	validation_0-mae:4762.59867
[427]	validation_0-mae:4763.81446
[428]	validation_0-mae:4760.99608
[429]	validation_0-mae:4760.82265
[430]	validation_0-mae:4759.41443
[431]	validation_0-mae:4759.41410
[432]	validation_0-mae:4758.75499
[433]	validation_0-mae:4758.54319
[434]	validation_0-mae:4759.38960
[435]	validation_0-mae:4759.17821
[436]	validation_0-mae:4758.69390
[437]	validation_0-mae:4757.12021
[438]	validation_0-mae:4756.69953
[439]	validation_0-mae:4756.55010
[440]	validation_0-mae:4756.03680
[441]	validation_0-mae:4755.71889
[442]	validation_0-mae:4756.91139
[443]	validation_0-mae:4756.75631
[444]	validation_0-mae:4757.71432
[445]	validation_0-mae:4757.15573
[446]	validation_0-mae:4757.12808
[447]	validation_0-mae:4757.26950
[448]	validation_0-mae:4756.65304
[449]	validation_0-mae:4755.81890
[450]	validation_0-mae:4755.86337
[451]	validation_0-mae:4754.75000
[452]	validation_0-mae:4754.22289
[453]	validation_0-mae:4754.50378
[454]	validation_0-mae:4753.40932
[455]	validation_0-mae:4751.01109
[456]	validation_0-mae:4751.21431
[457]	validation_0-mae:4750.43429
[458]	validation_0-mae:4750.30765
[459]	validation_0-mae:4749.17801
[460]	validation_0-mae:4748.73231
[461]	validation_0-mae:4747.93687
[462]	validation_0-mae:4747.73113
[463]	validation_0-mae:4746.96403
[464]	validation_0-mae:4744.75078
[465]	validation_0-mae:4743.54304
[466]	validation_0-mae:4743.32570
[467]	validation_0-mae:4741.95904
[468]	validation_0-mae:4741.19383
[469]	validation_0-mae:4741.20138
[470]	validation_0-mae:4740.61037
[471]	validation_0-mae:4739.60938
[472]	validation_0-mae:4739.48861
[473]	validation_0-mae:4739.54990
[474]	validation_0-mae:4739.39133
[475]	validation_0-mae:4736.98974
[476]	validation_0-mae:4736.33194
[477]	validation_0-mae:4735.25388
[478]	validation_0-mae:4734.71896
[479]	validation_0-mae:4733.97009
[480]	validation_0-mae:4732.98329
[481]	validation_0-mae:4731.03575
[482]	validation_0-mae:4729.62548
[483]	validation_0-mae:4728.62699
[484]	validation_0-mae:4729.01136
[485]	validation_0-mae:4728.21150
[486]	validation_0-mae:4728.88684
[487]	validation_0-mae:4727.59421
[488]	validation_0-mae:4727.20797
[489]	validation_0-mae:4726.54982
[490]	validation_0-mae:4726.61344
[491]	validation_0-mae:4727.90296
[492]	validation_0-mae:4726.98086
[493]	validation_0-mae:4726.66589
[494]	validation_0-mae:4725.96047
[495]	validation_0-mae:4725.50295
[496]	validation_0-mae:4726.83530
[497]	validation_0-mae:4726.53655
[498]	validation_0-mae:4726.34224
[499]	validation_0-mae:4726.22632
[500]	validation_0-mae:4725.74134
[501]	validation_0-mae:4725.42932
[502]	validation_0-mae:4725.40256
[503]	validation_0-mae:4724.18356
[504]	validation_0-mae:4724.33986
[505]	validation_0-mae:4723.43708
[506]	validation_0-mae:4723.28283
[507]	validation_0-mae:4723.77886
[508]	validation_0-mae:4722.36451
[509]	validation_0-mae:4721.76101
[510]	validation_0-mae:4721.22661
[511]	validation_0-mae:4720.35519
[512]	validation_0-mae:4719.46694
[513]	validation_0-mae:4719.48887
[514]	validation_0-mae:4718.95824
[515]	validation_0-mae:4718.27506
[516]	validation_0-mae:4717.93830
[517]	validation_0-mae:4717.96821
[518]	validation_0-mae:4717.34630
[519]	validation_0-mae:4717.66654
[520]	validation_0-mae:4717.70436
[521]	validation_0-mae:4717.94803
[522]	validation_0-mae:4718.74534
[523]	validation_0-mae:4718.78099
[524]	validation_0-mae:4717.21920
[525]	validation_0-mae:4717.87657
[526]	validation_0-mae:4718.30596
[527]	validation_0-mae:4718.42742
[528]	validation_0-mae:4718.14851
[529]	validation_0-mae:4717.22553
[530]	validation_0-mae:4717.32170
[531]	validation_0-mae:4715.92838
[532]	validation_0-mae:4714.97885
[533]	validation_0-mae:4713.89952
[534]	validation_0-mae:4711.93696
[535]	validation_0-mae:4712.32515
[536]	validation_0-mae:4712.15461
[537]	validation_0-mae:4711.29022
[538]	validation_0-mae:4709.53505
[539]	validation_0-mae:4708.25336
[540]	validation_0-mae:4708.27916
[541]	validation_0-mae:4708.47804
[542]	validation_0-mae:4707.05427
[543]	validation_0-mae:4706.88226
[544]	validation_0-mae:4706.95114
[545]	validation_0-mae:4706.05539
[546]	validation_0-mae:4704.67233
[547]	validation_0-mae:4704.76463
[548]	validation_0-mae:4704.76373
[549]	validation_0-mae:4704.60526
[550]	validation_0-mae:4705.15952
[551]	validation_0-mae:4704.51063
[552]	validation_0-mae:4704.64079
[553]	validation_0-mae:4704.84013
[554]	validation_0-mae:4705.62802
[555]	validation_0-mae:4704.11139
[556]	validation_0-mae:4702.44490
[557]	validation_0-mae:4701.94728
[558]	validation_0-mae:4702.54247
[559]	validation_0-mae:4701.78115
[560]	validation_0-mae:4701.90120
[561]	validation_0-mae:4701.40843
[562]	validation_0-mae:4701.60520
[563]	validation_0-mae:4701.36699
[564]	validation_0-mae:4700.20600
[565]	validation_0-mae:4700.58594
[566]	validation_0-mae:4701.07903
[567]	validation_0-mae:4702.27573
[568]	validation_0-mae:4702.63726
[569]	validation_0-mae:4702.14267
[570]	validation_0-mae:4701.52351
[571]	validation_0-mae:4701.03032
[572]	validation_0-mae:4701.31335
[573]	validation_0-mae:4701.46210
[574]	validation_0-mae:4701.00082
[575]	validation_0-mae:4701.01411
[576]	validation_0-mae:4701.03132
[577]	validation_0-mae:4700.11584
[578]	validation_0-mae:4698.57354
[579]	validation_0-mae:4698.04003
[580]	validation_0-mae:4698.43963
[581]	validation_0-mae:4698.34842
[582]	validation_0-mae:4697.69967
[583]	validation_0-mae:4696.92137
[584]	validation_0-mae:4697.88788
[585]	validation_0-mae:4697.58071
[586]	validation_0-mae:4697.67859
[587]	validation_0-mae:4697.72722
[588]	validation_0-mae:4697.91252
[589]	validation_0-mae:4697.61559
[590]	validation_0-mae:4697.21590
[591]	validation_0-mae:4696.47478
[592]	validation_0-mae:4696.10139
[593]	validation_0-mae:4694.35029
[594]	validation_0-mae:4693.28045
[595]	validation_0-mae:4693.64946
[596]	validation_0-mae:4693.72607
[597]	validation_0-mae:4693.77927
[598]	validation_0-mae:4693.62019
[599]	validation_0-mae:4693.44075
[600]	validation_0-mae:4693.37815
[601]	validation_0-mae:4692.74874
[602]	validation_0-mae:4693.17800
[603]	validation_0-mae:4692.19674
[604]	validation_0-mae:4692.06180
[605]	validation_0-mae:4691.69222
[606]	validation_0-mae:4691.26759
[607]	validation_0-mae:4689.99857
[608]	validation_0-mae:4689.86242
[609]	validation_0-mae:4689.99384
[610]	validation_0-mae:4689.15325
[611]	validation_0-mae:4688.57890
[612]	validation_0-mae:4688.64183
[613]	validation_0-mae:4688.03705
[614]	validation_0-mae:4686.77999
[615]	validation_0-mae:4685.52292
[616]	validation_0-mae:4685.02338
[617]	validation_0-mae:4684.76291
[618]	validation_0-mae:4683.86006
[619]	validation_0-mae:4683.53127
[620]	validation_0-mae:4683.87914
[621]	validation_0-mae:4683.35604
[622]	validation_0-mae:4683.08083
[623]	validation_0-mae:4682.93006
[624]	validation_0-mae:4682.75908
[625]	validation_0-mae:4681.88884
[626]	validation_0-mae:4680.87169
[627]	validation_0-mae:4680.43579
[628]	validation_0-mae:4679.86916
[629]	validation_0-mae:4679.45641
[630]	validation_0-mae:4679.50736
[631]	validation_0-mae:4679.02893
[632]	validation_0-mae:4677.65350
[633]	validation_0-mae:4676.94870
[634]	validation_0-mae:4675.84056
[635]	validation_0-mae:4674.56787
[636]	validation_0-mae:4675.26347
[637]	validation_0-mae:4675.28083
[638]	validation_0-mae:4675.12309
[639]	validation_0-mae:4674.97045
[640]	validation_0-mae:4675.17340
[641]	validation_0-mae:4675.03406
[642]	validation_0-mae:4674.04421
[643]	validation_0-mae:4674.03972
[644]	validation_0-mae:4673.43688
[645]	validation_0-mae:4674.08883
[646]	validation_0-mae:4672.83149
[647]	validation_0-mae:4672.48262
[648]	validation_0-mae:4672.12121
[649]	validation_0-mae:4671.95677
[650]	validation_0-mae:4671.76739

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[52]	validation_0-mae:3976.65555
[53]	validation_0-mae:3938.40722
[54]	validation_0-mae:3893.38188
[55]	validation_0-mae:3869.06888
[56]	validation_0-mae:3830.81341
[57]	validation_0-mae:3790.74856
[58]	validation_0-mae:3761.37916
[59]	validation_0-mae:3720.86897
[60]	validation_0-mae:3691.07716
[61]	validation_0-mae:3656.48726
[62]	validation_0-mae:3625.38277
[63]	validation_0-mae:3595.06246
[64]	validation_0-mae:3564.27078
[65]	validation_0-mae:3542.48367
[66]	validation_0-mae:3517.85278
[67]	validation_0-mae:3495.16305
[68]	validation_0-mae:3470.13617
[69]	validation_0-mae:3450.76589
[70]	validation_0-mae:3429.80820
[71]	validation_0-mae:3409.74077
[72]	validation_0-mae:3392.32260
[73]	validation_0-mae:3371.13037
[74]	validation_0-mae:3358.16967
[75]	validation_0-mae:3344.34801
[76]	validation_0-mae:3328.87324
[77]	validation_0-mae:3317.35178
[78]	validation_0-mae:3292.31111
[79]	validation_0-mae:3273.43833
[80]	validation_0-mae:3261.95284
[81]	validation_0-mae:3248.30179
[82]	validation_0-mae:3235.66103
[83]	validation_0-mae:3218.75481
[84]	validation_0-mae:3208.01845
[85]	validation_0-mae:3197.69093
[86]	validation_0-mae:3189.95830
[87]	validation_0-mae:3173.83267
[88]	validation_0-mae:3160.47380
[89]	validation_0-mae:3150.65282
[90]	validation_0-mae:3133.92624
[91]	validation_0-mae:3117.77736
[92]	validation_0-mae:3107.73244
[93]	validation_0-mae:3088.21374
[94]	validation_0-mae:3077.93396
[95]	validation_0-mae:3064.42319
[96]	validation_0-mae:3055.47444
[97]	validation_0-mae:3046.59299
[98]	validation_0-mae:3038.96821
[99]	validation_0-mae:3030.27960
[100]	validation_0-mae:3025.15206
[101]	validation_0-mae:3016.53037
[102]	validation_0-mae:3012.14564
[103]	validation_0-mae:2999.85370
[104]	validation_0-mae:2989.12783
[105]	validation_0-mae:2983.27925
[106]	validation_0-mae:2978.34770
[107]	validation_0-mae:2965.64129
[108]	validation_0-mae:2958.13567
[109]	validation_0-mae:2953.05031
[110]	validation_0-mae:2944.97876
[111]	validation_0-mae:2929.45135
[112]	validation_0-mae:2923.62999
[113]	validation_0-mae:2912.86875
[114]	validation_0-mae:2898.82575
[115]	validation_0-mae:2894.59034
[116]	validation_0-mae:2884.61261
[117]	validation_0-mae:2877.79503
[118]	validation_0-mae:2873.80113
[119]	validation_0-mae:2867.41145
[120]	validation_0-mae:2860.67464
[121]	validation_0-mae:2852.04065
[122]	validation_0-mae:2843.65866
[123]	validation_0-mae:2826.80697
[124]	validation_0-mae:2818.12484
[125]	validation_0-mae:2815.93453
[126]	validation_0-mae:2811.96496
[127]	validation_0-mae:2803.27984
[128]	validation_0-mae:2796.55404
[129]	validation_0-mae:2791.57708
[130]	validation_0-mae:2784.01173
[131]	validation_0-mae:2778.81469
[132]	validation_0-mae:2770.23360
[133]	validation_0-mae:2755.34051
[134]	validation_0-mae:2748.87224
[135]	validation_0-mae:2745.43037
[136]	validation_0-mae:2739.40830
[137]	validation_0-mae:2733.05872
[138]	validation_0-mae:2728.05694
[139]	validation_0-mae:2723.93902
[140]	validation_0-mae:2720.77463
[141]	validation_0-mae:2716.63359
[142]	validation_0-mae:2712.11762
[143]	validation_0-mae:2703.59963
[144]	validation_0-mae:2699.27403
[145]	validation_0-mae:2693.82543
[146]	validation_0-mae:2689.84505
[147]	validation_0-mae:2689.39819
[148]	validation_0-mae:2686.77667
[149]	validation_0-mae:2677.89000
[150]	validation_0-mae:2670.40457
[151]	validation_0-mae:2666.17418
[152]	validation_0-mae:2663.38327
[153]	validation_0-mae:2657.82357
[154]	validation_0-mae:2654.64520
[155]	validation_0-mae:2651.70067
[156]	validation_0-mae:2650.50188
[157]	validation_0-mae:2644.90092
[158]	validation_0-mae:2642.65853
[159]	validation_0-mae:2639.34516
[160]	validation_0-mae:2631.90343
[161]	validation_0-mae:2630.28502
[162]	validation_0-mae:2623.52326
[163]	validation_0-mae:2621.16290
[164]	validation_0-mae:2617.99660
[165]	validation_0-mae:2616.02489
[166]	validation_0-mae:2615.40260
[167]	validation_0-mae:2610.15512
[168]	validation_0-mae:2606.13990
[169]	validation_0-mae:2603.16940
[170]	validation_0-mae:2600.21021
[171]	validation_0-mae:2594.70955
[172]	validation_0-mae:2589.17436
[173]	validation_0-mae:2585.73876
[174]	validation_0-mae:2585.35919
[175]	validation_0-mae:2582.64888
[176]	validation_0-mae:2581.65460
[177]	validation_0-mae:2578.52003
[178]	validation_0-mae:2572.98426
[179]	validation_0-mae:2572.78233
[180]	validation_0-mae:2569.63603
[181]	validation_0-mae:2567.33680
[182]	validation_0-mae:2562.04302
[183]	validation_0-mae:2559.61803
[184]	validation_0-mae:2557.11205
[185]	validation_0-mae:2557.30040
[186]	validation_0-mae:2555.50482
[187]	validation_0-mae:2553.81238
[188]	validation_0-mae:2551.17601
[189]	validation_0-mae:2548.80111
[190]	validation_0-mae:2546.85364
[191]	validation_0-mae:2544.42168
[192]	validation_0-mae:2541.86634
[193]	validation_0-mae:2541.83283
[194]	validation_0-mae:2540.15792
[195]	validation_0-mae:2536.52343
[196]	validation_0-mae:2532.29287
[197]	validation_0-mae:2530.93237
[198]	validation_0-mae:2526.97921
[199]	validation_0-mae:2522.13444
[200]	validation_0-mae:2519.30177
[201]	validation_0-mae:2515.53534
[202]	validation_0-mae:2512.81545
[203]	validation_0-mae:2510.41863
[204]	validation_0-mae:2510.57651
[205]	validation_0-mae:2510.74609
[206]	validation_0-mae:2508.75986
[207]	validation_0-mae:2506.28561
[208]	validation_0-mae:2504.96131
[209]	validation_0-mae:2504.46997
[210]	validation_0-mae:2503.16602
[211]	validation_0-mae:2497.63375
[212]	validation_0-mae:2494.90352
[213]	validation_0-mae:2493.55351
[214]	validation_0-mae:2491.13055
[215]	validation_0-mae:2485.92529
[216]	validation_0-mae:2481.34811
[217]	validation_0-mae:2480.65621
[218]	validation_0-mae:2480.89989
[219]	validation_0-mae:2479.14054
[220]	validation_0-mae:2479.41948
[221]	validation_0-mae:2475.40710
[222]	validation_0-mae:2474.01867
[223]	validation_0-mae:2474.46614
[224]	validation_0-mae:2473.86209
[225]	validation_0-mae:2468.62174
[226]	validation_0-mae:2467.38663
[227]	validation_0-mae:2464.93337
[228]	validation_0-mae:2463.03961
[229]	validation_0-mae:2463.37885
[230]	validation_0-mae:2461.88825
[231]	validation_0-mae:2462.18366
[232]	validation_0-mae:2461.29754
[233]	validation_0-mae:2459.70387
[234]	validation_0-mae:2457.68904
[235]	validation_0-mae:2455.20008
[236]	validation_0-mae:2454.59992
[237]	validation_0-mae:2454.60912
[238]	validation_0-mae:2454.34718
[239]	validation_0-mae:2453.10591
[240]	validation_0-mae:2451.74326
[241]	validation_0-mae:2451.14862
[242]	validation_0-mae:2448.37493
[243]	validation_0-mae:2446.70930
[244]	validation_0-mae:2446.13179
[245]	validation_0-mae:2444.77614
[246]	validation_0-mae:2441.11227
[247]	validation_0-mae:2436.25930
[248]	validation_0-mae:2432.14928
[249]	validation_0-mae:2429.61847
[250]	validation_0-mae:2428.59288
[251]	validation_0-mae:2428.06755
[252]	validation_0-mae:2426.57783
[253]	validation_0-mae:2423.68004
[254]	validation_0-mae:2420.99387
[255]	validation_0-mae:2418.56832
[256]	validation_0-mae:2418.05405
[257]	validation_0-mae:2415.85294
[258]	validation_0-mae:2414.16716
[259]	validation_0-mae:2413.32424
[260]	validation_0-mae:2412.81408
[261]	validation_0-mae:2412.97635
[262]	validation_0-mae:2411.03095
[263]	validation_0-mae:2410.17031
[264]	validation_0-mae:2409.21974
[265]	validation_0-mae:2407.14890
[266]	validation_0-mae:2405.44712
[267]	validation_0-mae:2402.85410
[268]	validation_0-mae:2402.46974
[269]	validation_0-mae:2401.99514
[270]	validation_0-mae:2401.28909
[271]	validation_0-mae:2400.71070
[272]	validation_0-mae:2398.80260
[273]	validation_0-mae:2398.18297
[274]	validation_0-mae:2397.46650
[275]	validation_0-mae:2396.11978
[276]	validation_0-mae:2395.63266
[277]	validation_0-mae:2395.85490
[278]	validation_0-mae:2394.35751
[279]	validation_0-mae:2392.92301
[280]	validation_0-mae:2393.67727
[281]	validation_0-mae:2393.53409
[282]	validation_0-mae:2390.90036
[283]	validation_0-mae:2389.73645
[284]	validation_0-mae:2390.02722
[285]	validation_0-mae:2390.23103
[286]	validation_0-mae:2387.86103
[287]	validation_0-mae:2387.53611
[288]	validation_0-mae:2386.58817
[289]	validation_0-mae:2385.32025
[290]	validation_0-mae:2384.06311
[291]	validation_0-mae:2383.99754
[292]	validation_0-mae:2383.43444
[293]	validation_0-mae:2381.13234
[294]	validation_0-mae:2379.89255
[295]	validation_0-mae:2379.69448
[296]	validation_0-mae:2378.86459
[297]	validation_0-mae:2378.23024
[298]	validation_0-mae:2378.10940
[299]	validation_0-mae:2374.52293
[300]	validation_0-mae:2373.64329
[301]	validation_0-mae:2373.09866
[302]	validation_0-mae:2371.67297
[303]	validation_0-mae:2370.33578
[304]	validation_0-mae:2370.31357
[305]	validation_0-mae:2367.74675
[306]	validation_0-mae:2365.41355
[307]	validation_0-mae:2364.09998
[308]	validation_0-mae:2363.89491
[309]	validation_0-mae:2362.78813
[310]	validation_0-mae:2362.88588
[311]	validation_0-mae:2361.90345
[312]	validation_0-mae:2360.43367
[313]	validation_0-mae:2360.04135
[314]	validation_0-mae:2357.36543
[315]	validation_0-mae:2356.07448
[316]	validation_0-mae:2355.20193
[317]	validation_0-mae:2353.06896
[318]	validation_0-mae:2352.25188
[319]	validation_0-mae:2352.32773
[320]	validation_0-mae:2351.83763
[321]	validation_0-mae:2352.13149
[322]	validation_0-mae:2350.68591
[323]	validation_0-mae:2349.31847
[324]	validation_0-mae:2347.22604
[325]	validation_0-mae:2346.53986
[326]	validation_0-mae:2345.81306
[327]	validation_0-mae:2345.15558
[328]	validation_0-mae:2344.40261
[329]	validation_0-mae:2343.85086
[330]	validation_0-mae:2343.44423
[331]	validation_0-mae:2342.40241
[332]	validation_0-mae:2340.29218
[333]	validation_0-mae:2340.81842
[334]	validation_0-mae:2340.84930
[335]	validation_0-mae:2338.49269
[336]	validation_0-mae:2336.43797
[337]	validation_0-mae:2336.52017
[338]	validation_0-mae:2336.05374
[339]	validation_0-mae:2336.35467
[340]	validation_0-mae:2334.11253
[341]	validation_0-mae:2332.40260
[342]	validation_0-mae:2331.79303
[343]	validation_0-mae:2332.24823
[344]	validation_0-mae:2329.82652
[345]	validation_0-mae:2329.94205
[346]	validation_0-mae:2327.93580
[347]	validation_0-mae:2325.19253
[348]	validation_0-mae:2325.41347
[349]	validation_0-mae:2324.58668
[350]	validation_0-mae:2322.98937
[351]	validation_0-mae:2321.12602
[352]	validation_0-mae:2321.36530
[353]	validation_0-mae:2320.10151
[354]	validation_0-mae:2319.72771
[355]	validation_0-mae:2318.67706
[356]	validation_0-mae:2317.49216
[357]	validation_0-mae:2315.58740
[358]	validation_0-mae:2315.88855
[359]	validation_0-mae:2315.62748
[360]	validation_0-mae:2314.86621
[361]	validation_0-mae:2315.09995
[362]	validation_0-mae:2315.08930
[363]	validation_0-mae:2315.35550
[364]	validation_0-mae:2314.07767
[365]	validation_0-mae:2312.20093
[366]	validation_0-mae:2311.98401
[367]	validation_0-mae:2310.94165
[368]	validation_0-mae:2311.71355
[369]	validation_0-mae:2311.15983
[370]	validation_0-mae:2311.94983
[371]	validation_0-mae:2311.37955
[372]	validation_0-mae:2309.89358
[373]	validation_0-mae:2309.78240
[374]	validation_0-mae:2310.61552
[375]	validation_0-mae:2311.06893
[376]	validation_0-mae:2311.04575
[377]	validation_0-mae:2310.80136
[378]	validation_0-mae:2310.07760
[379]	validation_0-mae:2310.16479
[380]	validation_0-mae:2309.17402
[381]	validation_0-mae:2309.19798
[382]	validation_0-mae:2309.40064
[383]	validation_0-mae:2308.98875
[384]	validation_0-mae:2309.03580
[385]	validation_0-mae:2308.49609
[386]	validation_0-mae:2307.71597
[387]	validation_0-mae:2307.93618
[388]	validation_0-mae:2307.64126
[389]	validation_0-mae:2306.37814
[390]	validation_0-mae:2305.65463
[391]	validation_0-mae:2306.00428
[392]	validation_0-mae:2305.72587
[393]	validation_0-mae:2305.34427
[394]	validation_0-mae:2304.74148
[395]	validation_0-mae:2304.77108
[396]	validation_0-mae:2304.52201
[397]	validation_0-mae:2304.32411
[398]	validation_0-mae:2304.68096
[399]	validation_0-mae:2304.35185
[400]	validation_0-mae:2304.10741
[401]	validation_0-mae:2304.06016
[402]	validation_0-mae:2304.08293
[403]	validation_0-mae:2302.80485
[404]	validation_0-mae:2302.65443
[405]	validation_0-mae:2302.22654
[406]	validation_0-mae:2301.80296
[407]	validation_0-mae:2301.33463
[408]	validation_0-mae:2301.21895
[409]	validation_0-mae:2300.74847
[410]	validation_0-mae:2299.75281
[411]	validation_0-mae:2300.23755
[412]	validation_0-mae:2299.86991
[413]	validation_0-mae:2299.63003
[414]	validation_0-mae:2299.13998
[415]	validation_0-mae:2299.65701
[416]	validation_0-mae:2299.03761
[417]	validation_0-mae:2298.86406
[418]	validation_0-mae:2299.02984
[419]	validation_0-mae:2298.90710
[420]	validation_0-mae:2298.25211
[421]	validation_0-mae:2295.56723
[422]	validation_0-mae:2294.58004
[423]	validation_0-mae:2294.30048
[424]	validation_0-mae:2292.81885
[425]	validation_0-mae:2291.67776
[426]	validation_0-mae:2291.84162
[427]	validation_0-mae:2291.71414
[428]	validation_0-mae:2289.41011
[429]	validation_0-mae:2288.84202
[430]	validation_0-mae:2288.40494
[431]	validation_0-mae:2288.45290
[432]	validation_0-mae:2288.26235
[433]	validation_0-mae:2288.21451
[434]	validation_0-mae:2288.49164
[435]	validation_0-mae:2288.34050
[436]	validation_0-mae:2288.90524
[437]	validation_0-mae:2287.02402
[438]	validation_0-mae:2286.42312
[439]	validation_0-mae:2286.39623
[440]	validation_0-mae:2283.72766
[441]	validation_0-mae:2282.56238
[442]	validation_0-mae:2281.68040
[443]	validation_0-mae:2281.42208
[444]	validation_0-mae:2281.65616
[445]	validation_0-mae:2281.50882
[446]	validation_0-mae:2281.58166
[447]	validation_0-mae:2281.49873
[448]	validation_0-mae:2281.31388
[449]	validation_0-mae:2280.63066
[450]	validation_0-mae:2280.23952
[451]	validation_0-mae:2279.42742
[452]	validation_0-mae:2279.06453
[453]	validation_0-mae:2279.36217
[454]	validation_0-mae:2277.14536
[455]	validation_0-mae:2276.39296
[456]	validation_0-mae:2277.51202
[457]	validation_0-mae:2276.57623
[458]	validation_0-mae:2276.26112
[459]	validation_0-mae:2275.53641
[460]	validation_0-mae:2274.85622
[461]	validation_0-mae:2273.32900
[462]	validation_0-mae:2273.55947
[463]	validation_0-mae:2271.93528
[464]	validation_0-mae:2271.84604
[465]	validation_0-mae:2272.25060
[466]	validation_0-mae:2272.04906
[467]	validation_0-mae:2272.13768
[468]	validation_0-mae:2270.24910
[469]	validation_0-mae:2270.12773
[470]	validation_0-mae:2270.54206
[471]	validation_0-mae:2270.21005
[472]	validation_0-mae:2270.40876
[473]	validation_0-mae:2270.34597
[474]	validation_0-mae:2269.73943
[475]	validation_0-mae:2269.38077
[476]	validation_0-mae:2269.20125
[477]	validation_0-mae:2269.61174
[478]	validation_0-mae:2270.09786
[479]	validation_0-mae:2270.11327
[480]	validation_0-mae:2269.92713
[481]	validation_0-mae:2270.45371
[482]	validation_0-mae:2271.56421
[483]	validation_0-mae:2271.55682
[484]	validation_0-mae:2271.43536
[485]	validation_0-mae:2271.71355
[486]	validation_0-mae:2272.11572
[487]	validation_0-mae:2271.69885
[488]	validation_0-mae:2271.91663
[489]	validation_0-mae:2272.38029
[490]	validation_0-mae:2272.64644
[491]	validation_0-mae:2270.88741
[492]	validation_0-mae:2270.85118
[493]	validation_0-mae:2270.66676
[494]	validation_0-mae:2270.75688
[495]	validation_0-mae:2270.50262
[496]	validation_0-mae:2270.55667
[497]	validation_0-mae:2270.51563
[498]	validation_0-mae:2270.45497
[499]	validation_0-mae:2270.18792
[500]	validation_0-mae:2268.56441
[501]	validation_0-mae:2268.20466
[502]	validation_0-mae:2268.27667
[503]	validation_0-mae:2269.09024
[504]	validation_0-mae:2268.73881
[505]	validation_0-mae:2268.36810
[506]	validation_0-mae:2266.89695
[507]	validation_0-mae:2267.10065
[508]	validation_0-mae:2267.09223
[509]	validation_0-mae:2265.27432
[510]	validation_0-mae:2265.85078
[511]	validation_0-mae:2265.91354
[512]	validation_0-mae:2265.97430
[513]	validation_0-mae:2265.43924
[514]	validation_0-mae:2265.63837
[515]	validation_0-mae:2265.59414
[516]	validation_0-mae:2265.81677
[517]	validation_0-mae:2266.41306
[518]	validation_0-mae:2266.44933
[519]	validation_0-mae:2266.40851
[520]	validation_0-mae:2266.70066
[521]	validation_0-mae:2265.94534
[522]	validation_0-mae:2266.16100
[523]	validation_0-mae:2265.60475
[524]	validation_0-mae:2265.50721
[525]	validation_0-mae:2265.50109
[526]	validation_0-mae:2264.99567
[527]	validation_0-mae:2265.25908
[528]	validation_0-mae:2263.67079
[529]	validation_0-mae:2262.11697
[530]	validation_0-mae:2262.44983
[531]	validation_0-mae:2262.42158
[532]	validation_0-mae:2262.53157
[533]	validation_0-mae:2262.64351
[534]	validation_0-mae:2261.30528
[535]	validation_0-mae:2261.77623
[536]	validation_0-mae:2261.80121
[537]	validation_0-mae:2260.82103
[538]	validation_0-mae:2261.01279
[539]	validation_0-mae:2258.91815
[540]	validation_0-mae:2259.05791
[541]	validation_0-mae:2258.59204
[542]	validation_0-mae:2259.14225
[543]	validation_0-mae:2259.17785
[544]	validation_0-mae:2259.37623
[545]	validation_0-mae:2259.19756
[546]	validation_0-mae:2257.11067
[547]	validation_0-mae:2257.30831
[548]	validation_0-mae:2257.15904
[549]	validation_0-mae:2254.90419
[550]	validation_0-mae:2254.54720
[551]	validation_0-mae:2254.59239
[552]	validation_0-mae:2255.04972
[553]	validation_0-mae:2254.88633
[554]	validation_0-mae:2255.13743
[555]	validation_0-mae:2255.40939
[556]	validation_0-mae:2254.31638
[557]	validation_0-mae:2254.28514
[558]	validation_0-mae:2253.13532
[559]	validation_0-mae:2252.51331
[560]	validation_0-mae:2252.26637
[561]	validation_0-mae:2252.11127
[562]	validation_0-mae:2251.33240
[563]	validation_0-mae:2251.28013
[564]	validation_0-mae:2251.05140
[565]	validation_0-mae:2249.57818
[566]	validation_0-mae:2249.26172
[567]	validation_0-mae:2248.49891
[568]	validation_0-mae:2248.79979
[569]	validation_0-mae:2248.53708
[570]	validation_0-mae:2248.79036
[571]	validation_0-mae:2248.81516
[572]	validation_0-mae:2248.82805
[573]	validation_0-mae:2248.11167
[574]	validation_0-mae:2248.41386
[575]	validation_0-mae:2248.82966
[576]	validation_0-mae:2249.07945
[577]	validation_0-mae:2249.74193
[578]	validation_0-mae:2248.83469
[579]	validation_0-mae:2248.04227
[580]	validation_0-mae:2248.00864
[581]	validation_0-mae:2248.16020
[582]	validation_0-mae:2247.97030
[583]	validation_0-mae:2248.50583
[584]	validation_0-mae:2248.79257
[585]	validation_0-mae:2248.60767
[586]	validation_0-mae:2248.04744
[587]	validation_0-mae:2247.88271
[588]	validation_0-mae:2247.70566
[589]	validation_0-mae:2247.60588
[590]	validation_0-mae:2247.62199
[591]	validation_0-mae:2247.56517
[592]	validation_0-mae:2247.72063
[593]	validation_0-mae:2247.97162
[594]	validation_0-mae:2247.84210
[595]	validation_0-mae:2247.65313
[596]	validation_0-mae:2247.49270
[597]	validation_0-mae:2247.20945
[598]	validation_0-mae:2246.69133
[599]	validation_0-mae:2247.22109
[600]	validation_0-mae:2246.88890
[601]	validation_0-mae:2246.98534
[602]	validation_0-mae:2246.79809
[603]	validation_0-mae:2246.57933
[604]	validation_0-mae:2246.79066
[605]	validation_0-mae:2246.73508
[606]	validation_0-mae:2246.35273
[607]	validation_0-mae:2246.02709
[608]	validation_0-mae:2246.14071
[609]	validation_0-mae:2246.68407
[610]	validation_0-mae:2246.91259
[611]	validation_0-mae:2246.32694
[612]	validation_0-mae:2245.85286
[613]	validation_0-mae:2245.72769
[614]	validation_0-mae:2245.95974
[615]	validation_0-mae:2245.67153
[616]	validation_0-mae:2245.89630
[617]	validation_0-mae:2245.85909
[618]	validation_0-mae:2245.31338
[619]	validation_0-mae:2246.13157
[620]	validation_0-mae:2246.01570
[621]	validation_0-mae:2245.66206
[622]	validation_0-mae:2245.30413
[623]	validation_0-mae:2244.64722
[624]	validation_0-mae:2244.63772
[625]	validation_0-mae:2244.40018
[626]	validation_0-mae:2244.28848
[627]	validation_0-mae:2243.53902
[628]	validation_0-mae:2242.82992
[629]	validation_0-mae:2243.82572
[630]	validation_0-mae:2243.17895
[631]	validation_0-mae:2242.48438
[632]	validation_0-mae:2242.00574
[633]	validation_0-mae:2242.38295
[634]	validation_0-mae:2242.04555
[635]	validation_0-mae:2242.31717
[636]	validation_0-mae:2241.42027
[637]	validation_0-mae:2241.98088
[638]	validation_0-mae:2242.03161
[639]	validation_0-mae:2242.49993
[640]	validation_0-mae:2242.46408

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[15]	validation_0-mae:7293.37617
[16]	validation_0-mae:7112.31658
[17]	validation_0-mae:6896.06147
[18]	validation_0-mae:6733.26054
[19]	validation_0-mae:6569.31078
[20]	validation_0-mae:6416.18918
[21]	validation_0-mae:6250.16015
[22]	validation_0-mae:6102.24222
[23]	validation_0-mae:5984.94161
[24]	validation_0-mae:5861.74246
[25]	validation_0-mae:5722.24300
[26]	validation_0-mae:5605.76257
[27]	validation_0-mae:5476.13346
[28]	validation_0-mae:5353.79137
[29]	validation_0-mae:5258.43527
[30]	validation_0-mae:5156.97298
[31]	validation_0-mae:5077.43769
[32]	validation_0-mae:4987.92742
[33]	validation_0-mae:4902.91304
[34]	validation_0-mae:4834.65727
[35]	validation_0-mae:4763.21294
[36]	validation_0-mae:4688.22877
[37]	validation_0-mae:4638.10154
[38]	validation_0-mae:4564.44873
[39]	validation_0-mae:4508.02647
[40]	validation_0-mae:4431.43903
[41]	validation_0-mae:4368.75269
[42]	validation_0-mae:4328.02701
[43]	validation_0-mae:4284.94008
[44]	validation_0-mae:4232.14551
[45]	validation_0-mae:4188.52935
[46]	validation_0-mae:4145.34871
[47]	validation_0-mae:4092.54198
[48]	validation_0-mae:4049.05107
[49]	validation_0-mae:4014.54648
[50]	validation_0-mae:3978.24333
[51]	validation_0-mae:3922.48750
[52]	validation_0-mae:3881.78828
[53]	validation_0-mae:3834.84849
[54]	validation_0-mae:3808.94909
[55]	validation_0-mae:3775.27687
[56]	validation_0-mae:3738.51320
[57]	validation_0-mae:3716.52748
[58]	validation_0-mae:3679.76990
[59]	validation_0-mae:3641.19781
[60]	validation_0-mae:3608.58012
[61]	validation_0-mae:3586.65940
[62]	validation_0-mae:3567.57547
[63]	validation_0-mae:3547.67502
[64]	validation_0-mae:3529.78942
[65]	validation_0-mae:3513.59211
[66]	validation_0-mae:3483.15276
[67]	validation_0-mae:3466.09808
[68]	validation_0-mae:3448.59236
[69]	validation_0-mae:3433.32943
[70]	validation_0-mae:3414.54171
[71]	validation_0-mae:3402.25515
[72]	validation_0-mae:3382.06953
[73]	validation_0-mae:3355.07827
[74]	validation_0-mae:3340.05461
[75]	validation_0-mae:3321.40865
[76]	validation_0-mae:3302.27077
[77]	validation_0-mae:3292.59381
[78]	validation_0-mae:3267.78214
[79]	validation_0-mae:3257.03810
[80]	validation_0-mae:3239.97426
[81]	validation_0-mae:3215.40977
[82]	validation_0-mae:3204.25792
[83]	validation_0-mae:3196.54589
[84]	validation_0-mae:3182.11384
[85]	validation_0-mae:3166.69716
[86]	validation_0-mae:3158.10640
[87]	validation_0-mae:3141.20212
[88]	validation_0-mae:3121.13297
[89]	validation_0-mae:3112.23861
[90]	validation_0-mae:3107.00772
[91]	validation_0-mae:3096.65884
[92]	validation_0-mae:3088.23450
[93]	validation_0-mae:3076.32837
[94]	validation_0-mae:3063.16101
[95]	validation_0-mae:3056.55141
[96]	validation_0-mae:3023.76876
[97]	validation_0-mae:3014.65254
[98]	validation_0-mae:3003.74413
[99]	validation_0-mae:2996.70959
[100]	validation_0-mae:2986.90728
[101]	validation_0-mae:2982.04019
[102]	validation_0-mae:2974.76407
[103]	validation_0-mae:2957.45817
[104]	validation_0-mae:2947.48692
[105]	validation_0-mae:2941.21111
[106]	validation_0-mae:2929.78477
[107]	validation_0-mae:2920.39824
[108]	validation_0-mae:2915.46880
[109]	validation_0-mae:2908.41694
[110]	validation_0-mae:2899.72077
[111]	validation_0-mae:2895.86587
[112]	validation_0-mae:2886.57840
[113]	validation_0-mae:2883.05978
[114]	validation_0-mae:2874.91268
[115]	validation_0-mae:2864.69419
[116]	validation_0-mae:2859.36307
[117]	validation_0-mae:2858.77698
[118]	validation_0-mae:2856.31703
[119]	validation_0-mae:2849.71121
[120]	validation_0-mae:2835.81512
[121]	validation_0-mae:2825.36007
[122]	validation_0-mae:2818.09336
[123]	validation_0-mae:2811.46972
[124]	validation_0-mae:2806.35882
[125]	validation_0-mae:2804.40231
[126]	validation_0-mae:2798.42171
[127]	validation_0-mae:2794.49924
[128]	validation_0-mae:2788.09218
[129]	validation_0-mae:2784.06088
[130]	validation_0-mae:2778.13765
[131]	validation_0-mae:2772.54811
[132]	validation_0-mae:2765.77594
[133]	validation_0-mae:2762.41071
[134]	validation_0-mae:2750.52564
[135]	validation_0-mae:2742.74205
[136]	validation_0-mae:2737.74735
[137]	validation_0-mae:2734.15775
[138]	validation_0-mae:2728.04340
[139]	validation_0-mae:2721.78521
[140]	validation_0-mae:2714.28284
[141]	validation_0-mae:2711.29976
[142]	validation_0-mae:2707.61583
[143]	validation_0-mae:2702.42229
[144]	validation_0-mae:2700.17722
[145]	validation_0-mae:2692.57620
[146]	validation_0-mae:2689.99090
[147]	validation_0-mae:2686.45776
[148]	validation_0-mae:2681.33032
[149]	validation_0-mae:2677.59831
[150]	validation_0-mae:2672.04409
[151]	validation_0-mae:2666.54869
[152]	validation_0-mae:2655.74924
[153]	validation_0-mae:2654.05199
[154]	validation_0-mae:2645.34742
[155]	validation_0-mae:2642.99192
[156]	validation_0-mae:2635.78437
[157]	validation_0-mae:2632.36389
[158]	validation_0-mae:2629.95505
[159]	validation_0-mae:2625.83736
[160]	validation_0-mae:2621.41394
[161]	validation_0-mae:2611.98867
[162]	validation_0-mae:2608.63056
[163]	validation_0-mae:2603.67023
[164]	validation_0-mae:2600.75940
[165]	validation_0-mae:2598.53077
[166]	validation_0-mae:2596.59207
[167]	validation_0-mae:2593.04096
[168]	validation_0-mae:2591.50599
[169]	validation_0-mae:2591.55981
[170]	validation_0-mae:2584.12971
[171]	validation_0-mae:2579.29032
[172]	validation_0-mae:2577.26730
[173]	validation_0-mae:2576.08783
[174]	validation_0-mae:2572.99421
[175]	validation_0-mae:2568.24863
[176]	validation_0-mae:2562.01788
[177]	validation_0-mae:2562.12965
[178]	validation_0-mae:2557.26254
[179]	validation_0-mae:2555.07035
[180]	validation_0-mae:2553.33573
[181]	validation_0-mae:2550.03575
[182]	validation_0-mae:2547.20206
[183]	validation_0-mae:2544.48398
[184]	validation_0-mae:2541.09577
[185]	validation_0-mae:2537.38961
[186]	validation_0-mae:2535.07937
[187]	validation_0-mae:2533.57088
[188]	validation_0-mae:2531.33908
[189]	validation_0-mae:2530.24939
[190]	validation_0-mae:2526.31815
[191]	validation_0-mae:2523.07052
[192]	validation_0-mae:2520.36346
[193]	validation_0-mae:2517.05432
[194]	validation_0-mae:2513.34014
[195]	validation_0-mae:2512.37521
[196]	validation_0-mae:2509.13488
[197]	validation_0-mae:2507.17968
[198]	validation_0-mae:2505.13343
[199]	validation_0-mae:2501.76394
[200]	validation_0-mae:2500.09201
[201]	validation_0-mae:2499.90131
[202]	validation_0-mae:2499.81583
[203]	validation_0-mae:2498.30997
[204]	validation_0-mae:2496.28347
[205]	validation_0-mae:2494.18894
[206]	validation_0-mae:2491.17304
[207]	validation_0-mae:2488.99785
[208]	validation_0-mae:2488.05137
[209]	validation_0-mae:2487.26703
[210]	validation_0-mae:2485.80639
[211]	validation_0-mae:2484.83908
[212]	validation_0-mae:2482.65296
[213]	validation_0-mae:2479.05635
[214]	validation_0-mae:2477.30018
[215]	validation_0-mae:2472.03236
[216]	validation_0-mae:2469.40057
[217]	validation_0-mae:2465.54368
[218]	validation_0-mae:2462.56389
[219]	validation_0-mae:2460.93873
[220]	validation_0-mae:2457.41331
[221]	validation_0-mae:2454.14866
[222]	validation_0-mae:2450.76724
[223]	validation_0-mae:2450.63895
[224]	validation_0-mae:2449.41887
[225]	validation_0-mae:2446.65402
[226]	validation_0-mae:2445.25651
[227]	validation_0-mae:2444.06119
[228]	validation_0-mae:2441.33866
[229]	validation_0-mae:2440.69132
[230]	validation_0-mae:2439.87002
[231]	validation_0-mae:2436.19270
[232]	validation_0-mae:2435.58710
[233]	validation_0-mae:2432.65535
[234]	validation_0-mae:2431.99814
[235]	validation_0-mae:2431.36786
[236]	validation_0-mae:2429.45488
[237]	validation_0-mae:2428.39586
[238]	validation_0-mae:2426.60175
[239]	validation_0-mae:2423.50675
[240]	validation_0-mae:2422.80699
[241]	validation_0-mae:2421.22653
[242]	validation_0-mae:2418.35146
[243]	validation_0-mae:2416.24905
[244]	validation_0-mae:2416.21106
[245]	validation_0-mae:2415.78037
[246]	validation_0-mae:2414.74717
[247]	validation_0-mae:2410.95367
[248]	validation_0-mae:2409.70128
[249]	validation_0-mae:2408.30583
[250]	validation_0-mae:2407.22667
[251]	validation_0-mae:2407.15783
[252]	validation_0-mae:2406.50906
[253]	validation_0-mae:2404.17038
[254]	validation_0-mae:2402.51282
[255]	validation_0-mae:2400.77794
[256]	validation_0-mae:2400.72852
[257]	validation_0-mae:2398.39178
[258]	validation_0-mae:2396.89334
[259]	validation_0-mae:2396.34441
[260]	validation_0-mae:2395.04045
[261]	validation_0-mae:2391.88787
[262]	validation_0-mae:2391.15472
[263]	validation_0-mae:2389.77781
[264]	validation_0-mae:2389.18804
[265]	validation_0-mae:2388.67678
[266]	validation_0-mae:2386.79394
[267]	validation_0-mae:2386.60867
[268]	validation_0-mae:2387.04537
[269]	validation_0-mae:2385.84111
[270]	validation_0-mae:2385.74473
[271]	validation_0-mae:2385.58303
[272]	validation_0-mae:2384.39846
[273]	validation_0-mae:2382.54691
[274]	validation_0-mae:2380.12007
[275]	validation_0-mae:2379.00264
[276]	validation_0-mae:2378.07508
[277]	validation_0-mae:2376.94839
[278]	validation_0-mae:2376.64090
[279]	validation_0-mae:2376.16173
[280]	validation_0-mae:2376.07530
[281]	validation_0-mae:2374.88131
[282]	validation_0-mae:2372.44725
[283]	validation_0-mae:2372.37146
[284]	validation_0-mae:2372.15564
[285]	validation_0-mae:2372.02666
[286]	validation_0-mae:2371.60434
[287]	validation_0-mae:2370.88207
[288]	validation_0-mae:2370.21132
[289]	validation_0-mae:2369.22167
[290]	validation_0-mae:2367.41639
[291]	validation_0-mae:2367.01786
[292]	validation_0-mae:2364.96696
[293]	validation_0-mae:2364.86696
[294]	validation_0-mae:2364.98307
[295]	validation_0-mae:2365.27121
[296]	validation_0-mae:2362.43587
[297]	validation_0-mae:2362.15506
[298]	validation_0-mae:2360.48300
[299]	validation_0-mae:2360.31854
[300]	validation_0-mae:2360.02907
[301]	validation_0-mae:2357.90073
[302]	validation_0-mae:2358.46621
[303]	validation_0-mae:2357.53849
[304]	validation_0-mae:2357.06504
[305]	validation_0-mae:2357.32552
[306]	validation_0-mae:2354.73156
[307]	validation_0-mae:2354.04583
[308]	validation_0-mae:2353.39476
[309]	validation_0-mae:2351.72264
[310]	validation_0-mae:2349.40118
[311]	validation_0-mae:2349.43241
[312]	validation_0-mae:2349.92407
[313]	validation_0-mae:2348.89446
[314]	validation_0-mae:2347.76892
[315]	validation_0-mae:2347.27666
[316]	validation_0-mae:2347.41367
[317]	validation_0-mae:2344.99008
[318]	validation_0-mae:2345.00380
[319]	validation_0-mae:2343.58242
[320]	validation_0-mae:2342.66488
[321]	validation_0-mae:2341.11203
[322]	validation_0-mae:2340.57446
[323]	validation_0-mae:2338.44034
[324]	validation_0-mae:2337.86811
[325]	validation_0-mae:2337.99542
[326]	validation_0-mae:2337.62616
[327]	validation_0-mae:2337.08889
[328]	validation_0-mae:2337.21436
[329]	validation_0-mae:2337.83935
[330]	validation_0-mae:2337.95619
[331]	validation_0-mae:2338.37095
[332]	validation_0-mae:2338.38617
[333]	validation_0-mae:2338.31847
[334]	validation_0-mae:2337.25644
[335]	validation_0-mae:2334.33166
[336]	validation_0-mae:2334.31172
[337]	validation_0-mae:2333.76030
[338]	validation_0-mae:2332.82177
[339]	validation_0-mae:2331.67505
[340]	validation_0-mae:2330.27525
[341]	validation_0-mae:2328.01921
[342]	validation_0-mae:2328.31259
[343]	validation_0-mae:2328.08310
[344]	validation_0-mae:2327.42556
[345]	validation_0-mae:2325.79288
[346]	validation_0-mae:2325.34069
[347]	validation_0-mae:2324.22290
[348]	validation_0-mae:2323.30582
[349]	validation_0-mae:2323.10727
[350]	validation_0-mae:2322.25883
[351]	validation_0-mae:2321.26291
[352]	validation_0-mae:2321.43911
[353]	validation_0-mae:2320.56733
[354]	validation_0-mae:2318.72270
[355]	validation_0-mae:2318.29811
[356]	validation_0-mae:2317.17752
[357]	validation_0-mae:2317.43854
[358]	validation_0-mae:2317.92113
[359]	validation_0-mae:2317.12889
[360]	validation_0-mae:2316.89164
[361]	validation_0-mae:2316.37709
[362]	validation_0-mae:2316.13636
[363]	validation_0-mae:2315.67060
[364]	validation_0-mae:2315.94003
[365]	validation_0-mae:2315.64416
[366]	validation_0-mae:2315.82584
[367]	validation_0-mae:2316.26583
[368]	validation_0-mae:2315.70192
[369]	validation_0-mae:2314.17558
[370]	validation_0-mae:2313.11015
[371]	validation_0-mae:2311.95354
[372]	validation_0-mae:2311.16361
[373]	validation_0-mae:2310.34406
[374]	validation_0-mae:2309.56604
[375]	validation_0-mae:2307.77699
[376]	validation_0-mae:2308.52665
[377]	validation_0-mae:2306.58893
[378]	validation_0-mae:2306.48045
[379]	validation_0-mae:2306.51024
[380]	validation_0-mae:2306.69378
[381]	validation_0-mae:2307.14119
[382]	validation_0-mae:2306.38078
[383]	validation_0-mae:2305.50813
[384]	validation_0-mae:2305.05947
[385]	validation_0-mae:2305.49335
[386]	validation_0-mae:2305.25738
[387]	validation_0-mae:2304.27245
[388]	validation_0-mae:2304.66422
[389]	validation_0-mae:2304.53678
[390]	validation_0-mae:2303.60204
[391]	validation_0-mae:2303.47341
[392]	validation_0-mae:2303.43600
[393]	validation_0-mae:2302.93239
[394]	validation_0-mae:2301.85572
[395]	validation_0-mae:2299.35180
[396]	validation_0-mae:2299.43932
[397]	validation_0-mae:2299.28714
[398]	validation_0-mae:2299.61085
[399]	validation_0-mae:2299.61107
[400]	validation_0-mae:2299.42202
[401]	validation_0-mae:2299.68377
[402]	validation_0-mae:2299.69781
[403]	validation_0-mae:2299.04170
[404]	validation_0-mae:2298.87702
[405]	validation_0-mae:2298.45398
[406]	validation_0-mae:2298.73752
[407]	validation_0-mae:2298.76316
[408]	validation_0-mae:2298.79633
[409]	validation_0-mae:2298.12144
[410]	validation_0-mae:2298.63963
[411]	validation_0-mae:2298.87879
[412]	validation_0-mae:2299.47705
[413]	validation_0-mae:2299.16602
[414]	validation_0-mae:2299.24504
[415]	validation_0-mae:2299.71824
[416]	validation_0-mae:2299.99939
[417]	validation_0-mae:2300.16021
[418]	validation_0-mae:2298.24679
[419]	validation_0-mae:2298.88038
[420]	validation_0-mae:2297.86668
[421]	validation_0-mae:2297.29992
[422]	validation_0-mae:2297.62044
[423]	validation_0-mae:2297.34652
[424]	validation_0-mae:2297.04020
[425]	validation_0-mae:2295.86325
[426]	validation_0-mae:2294.22245
[427]	validation_0-mae:2293.80295
[428]	validation_0-mae:2293.60791
[429]	validation_0-mae:2292.25505
[430]	validation_0-mae:2290.95337
[431]	validation_0-mae:2291.04098
[432]	validation_0-mae:2290.63054
[433]	validation_0-mae:2290.25751
[434]	validation_0-mae:2289.92712
[435]	validation_0-mae:2289.35652
[436]	validation_0-mae:2289.28135
[437]	validation_0-mae:2289.32452
[438]	validation_0-mae:2289.07742
[439]	validation_0-mae:2288.50341
[440]	validation_0-mae:2288.78763
[441]	validation_0-mae:2288.12201
[442]	validation_0-mae:2287.99749
[443]	validation_0-mae:2287.28313
[444]	validation_0-mae:2286.34146
[445]	validation_0-mae:2286.59871
[446]	validation_0-mae:2285.70200
[447]	validation_0-mae:2286.14931
[448]	validation_0-mae:2285.60712
[449]	validation_0-mae:2284.71733
[450]	validation_0-mae:2284.53707
[451]	validation_0-mae:2284.80414
[452]	validation_0-mae:2284.60530
[453]	validation_0-mae:2283.68183
[454]	validation_0-mae:2283.85547
[455]	validation_0-mae:2283.38580
[456]	validation_0-mae:2283.37230
[457]	validation_0-mae:2282.78439
[458]	validation_0-mae:2283.36064
[459]	validation_0-mae:2283.40862
[460]	validation_0-mae:2282.71643
[461]	validation_0-mae:2283.41463
[462]	validation_0-mae:2283.74433
[463]	validation_0-mae:2283.00926
[464]	validation_0-mae:2282.45081
[465]	validation_0-mae:2283.03184
[466]	validation_0-mae:2283.30019
[467]	validation_0-mae:2283.69650
[468]	validation_0-mae:2284.02275
[469]	validation_0-mae:2284.26840
[470]	validation_0-mae:2284.24270
[471]	validation_0-mae:2284.76527
[472]	validation_0-mae:2282.24263
[473]	validation_0-mae:2281.15006
[474]	validation_0-mae:2281.03599
[475]	validation_0-mae:2281.51289
[476]	validation_0-mae:2279.16240
[477]	validation_0-mae:2278.37286
[478]	validation_0-mae:2278.80842
[479]	validation_0-mae:2278.52215
[480]	validation_0-mae:2278.40871
[481]	validation_0-mae:2277.34748
[482]	validation_0-mae:2277.76224
[483]	validation_0-mae:2277.78398
[484]	validation_0-mae:2277.32324
[485]	validation_0-mae:2277.03999
[486]	validation_0-mae:2275.56884
[487]	validation_0-mae:2275.85836
[488]	validation_0-mae:2275.90809
[489]	validation_0-mae:2273.28537
[490]	validation_0-mae:2273.20195
[491]	validation_0-mae:2271.77894
[492]	validation_0-mae:2272.00908
[493]	validation_0-mae:2271.05655
[494]	validation_0-mae:2269.56940
[495]	validation_0-mae:2269.28211
[496]	validation_0-mae:2268.76942
[497]	validation_0-mae:2268.96894
[498]	validation_0-mae:2268.80847
[499]	validation_0-mae:2268.06116
[500]	validation_0-mae:2267.67551
[501]	validation_0-mae:2267.18453
[502]	validation_0-mae:2266.87484
[503]	validation_0-mae:2266.93110
[504]	validation_0-mae:2265.86198
[505]	validation_0-mae:2265.22112
[506]	validation_0-mae:2264.96369
[507]	validation_0-mae:2264.13137
[508]	validation_0-mae:2263.53649
[509]	validation_0-mae:2262.81563
[510]	validation_0-mae:2263.00963
[511]	validation_0-mae:2263.23594
[512]	validation_0-mae:2263.25694
[513]	validation_0-mae:2263.39756
[514]	validation_0-mae:2263.58264
[515]	validation_0-mae:2263.35062
[516]	validation_0-mae:2263.14129
[517]	validation_0-mae:2262.17099
[518]	validation_0-mae:2261.92217
[519]	validation_0-mae:2261.60467
[520]	validation_0-mae:2261.56050
[521]	validation_0-mae:2261.22414
[522]	validation_0-mae:2260.90355
[523]	validation_0-mae:2260.82470
[524]	validation_0-mae:2261.15032
[525]	validation_0-mae:2259.85518
[526]	validation_0-mae:2259.19151
[527]	validation_0-mae:2258.86102
[528]	validation_0-mae:2258.09108
[529]	validation_0-mae:2258.40264
[530]	validation_0-mae:2258.17204
[531]	validation_0-mae:2257.81709
[532]	validation_0-mae:2257.79083
[533]	validation_0-mae:2258.11426
[534]	validation_0-mae:2258.45622
[535]	validation_0-mae:2258.18517
[536]	validation_0-mae:2258.13581
[537]	validation_0-mae:2257.27728
[538]	validation_0-mae:2257.28769
[539]	validation_0-mae:2257.29494
[540]	validation_0-mae:2257.14460
[541]	validation_0-mae:2257.45647
[542]	validation_0-mae:2257.35639
[543]	validation_0-mae:2257.18476
[544]	validation_0-mae:2256.89579
[545]	validation_0-mae:2257.03826
[546]	validation_0-mae:2257.16621
[547]	validation_0-mae:2257.19142
[548]	validation_0-mae:2256.04464
[549]	validation_0-mae:2256.13861
[550]	validation_0-mae:2256.13663
[551]	validation_0-mae:2256.44898
[552]	validation_0-mae:2256.71641
[553]	validation_0-mae:2255.59315
[554]	validation_0-mae:2255.43747
[555]	validation_0-mae:2254.80771
[556]	validation_0-mae:2253.99832
[557]	validation_0-mae:2254.09169
[558]	validation_0-mae:2252.55066
[559]	validation_0-mae:2251.65559
[560]	validation_0-mae:2250.87560
[561]	validation_0-mae:2250.86920
[562]	validation_0-mae:2251.04255
[563]	validation_0-mae:2251.17655
[564]	validation_0-mae:2249.87385
[565]	validation_0-mae:2249.07216
[566]	validation_0-mae:2249.01439
[567]	validation_0-mae:2248.75013
[568]	validation_0-mae:2247.76399
[569]	validation_0-mae:2247.82150
[570]	validation_0-mae:2248.21602
[571]	validation_0-mae:2247.31636
[572]	validation_0-mae:2246.80137
[573]	validation_0-mae:2246.80278
[574]	validation_0-mae:2246.69510
[575]	validation_0-mae:2246.63035
[576]	validation_0-mae:2246.12074
[577]	validation_0-mae:2245.55977
[578]	validation_0-mae:2245.61773
[579]	validation_0-mae:2245.92849
[580]	validation_0-mae:2245.94719
[581]	validation_0-mae:2245.83512
[582]	validation_0-mae:2244.83482
[583]	validation_0-mae:2245.04582
[584]	validation_0-mae:2245.41431
[585]	validation_0-mae:2245.48649
[586]	validation_0-mae:2244.70278
[587]	validation_0-mae:2244.85448
[588]	validation_0-mae:2244.71083
[589]	validation_0-mae:2244.88612
[590]	validation_0-mae:2244.76744
[591]	validation_0-mae:2244.76046
[592]	validation_0-mae:2244.75620
[593]	validation_0-mae:2244.57679
[594]	validation_0-mae:2244.59897
[595]	validation_0-mae:2244.88409
[596]	validation_0-mae:2244.51426
[597]	validation_0-mae:2244.32220
[598]	validation_0-mae:2243.47156
[599]	validation_0-mae:2242.32990
[600]	validation_0-mae:2242.74667
[601]	validation_0-mae:2242.26248
[602]	validation_0-mae:2242.26072
[603]	validation_0-mae:2241.97747
[604]	validation_0-mae:2242.50010

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[15]	validation_0-mae:6712.99805
[16]	validation_0-mae:6467.38237
[17]	validation_0-mae:6284.25148
[18]	validation_0-mae:6101.98555
[19]	validation_0-mae:5941.93764
[20]	validation_0-mae:5745.23384
[21]	validation_0-mae:5599.37969
[22]	validation_0-mae:5430.32095
[23]	validation_0-mae:5296.39215
[24]	validation_0-mae:5151.69350
[25]	validation_0-mae:5042.55191
[26]	validation_0-mae:4913.21680
[27]	validation_0-mae:4812.24514
[28]	validation_0-mae:4690.95920
[29]	validation_0-mae:4581.96085
[30]	validation_0-mae:4484.52733
[31]	validation_0-mae:4382.78810
[32]	validation_0-mae:4292.38959
[33]	validation_0-mae:4199.79051
[34]	validation_0-mae:4131.84390
[35]	validation_0-mae:4051.30123
[36]	validation_0-mae:3972.03570
[37]	validation_0-mae:3908.65597
[38]	validation_0-mae:3837.51908
[39]	validation_0-mae:3766.19950
[40]	validation_0-mae:3709.30294
[41]	validation_0-mae:3656.11839
[42]	validation_0-mae:3608.79415
[43]	validation_0-mae:3563.86329
[44]	validation_0-mae:3514.67977
[45]	validation_0-mae:3477.26433
[46]	validation_0-mae:3436.42977
[47]	validation_0-mae:3385.48198
[48]	validation_0-mae:3352.26081
[49]	validation_0-mae:3325.64382
[50]	validation_0-mae:3279.23566
[51]	validation_0-mae:3242.27675
[52]	validation_0-mae:3217.05314
[53]	validation_0-mae:3190.71418
[54]	validation_0-mae:3165.80173
[55]	validation_0-mae:3140.02504
[56]	validation_0-mae:3115.81318
[57]	validation_0-mae:3094.71243
[58]	validation_0-mae:3057.10136
[59]	validation_0-mae:3026.15229
[60]	validation_0-mae:3005.97183
[61]	validation_0-mae:2978.08051
[62]	validation_0-mae:2956.83739
[63]	validation_0-mae:2929.51546
[64]	validation_0-mae:2911.22682
[65]	validation_0-mae:2889.37572
[66]	validation_0-mae:2874.32763
[67]	validation_0-mae:2857.29628
[68]	validation_0-mae:2843.04785
[69]	validation_0-mae:2828.74258
[70]	validation_0-mae:2805.63136
[71]	validation_0-mae:2795.11909
[72]	validation_0-mae:2775.74548
[73]	validation_0-mae:2763.86300
[74]	validation_0-mae:2752.04748
[75]	validation_0-mae:2728.57824
[76]	validation_0-mae:2718.04366
[77]	validation_0-mae:2706.49290
[78]	validation_0-mae:2694.37765
[79]	validation_0-mae:2685.75440
[80]	validation_0-mae:2675.78442
[81]	validation_0-mae:2661.88218
[82]	validation_0-mae:2648.87184
[83]	validation_0-mae:2641.27204
[84]	validation_0-mae:2637.57773
[85]	validation_0-mae:2629.18211
[86]	validation_0-mae:2619.92283
[87]	validation_0-mae:2609.26869
[88]	validation_0-mae:2594.82666
[89]	validation_0-mae:2586.08923
[90]	validation_0-mae:2581.32403
[91]	validation_0-mae:2571.69364
[92]	validation_0-mae:2566.07908
[93]	validation_0-mae:2561.54335
[94]	validation_0-mae:2544.26499
[95]	validation_0-mae:2536.82911
[96]	validation_0-mae:2523.50809
[97]	validation_0-mae:2513.31864
[98]	validation_0-mae:2506.02246
[99]	validation_0-mae:2500.20716
[100]	validation_0-mae:2499.19157
[101]	validation_0-mae:2491.94303
[102]	validation_0-mae:2486.35685
[103]	validation_0-mae:2479.37785
[104]	validation_0-mae:2473.31255
[105]	validation_0-mae:2467.25042
[106]	validation_0-mae:2464.32435
[107]	validation_0-mae:2456.51799
[108]	validation_0-mae:2454.43764
[109]	validation_0-mae:2447.22880
[110]	validation_0-mae:2445.13857
[111]	validation_0-mae:2442.38315
[112]	validation_0-mae:2433.57883
[113]	validation_0-mae:2428.77196
[114]	validation_0-mae:2425.44973
[115]	validation_0-mae:2423.02107
[116]	validation_0-mae:2419.59258
[117]	validation_0-mae:2415.22432
[118]	validation_0-mae:2413.06683
[119]	validation_0-mae:2410.07750
[120]	validation_0-mae:2408.49818
[121]	validation_0-mae:2398.56984
[122]	validation_0-mae:2396.85102
[123]	validation_0-mae:2390.87954
[124]	validation_0-mae:2385.97778
[125]	validation_0-mae:2384.52670
[126]	validation_0-mae:2383.06636
[127]	validation_0-mae:2379.08333
[128]	validation_0-mae:2374.27070
[129]	validation_0-mae:2373.72615
[130]	validation_0-mae:2368.96462
[131]	validation_0-mae:2366.76911
[132]	validation_0-mae:2366.04064
[133]	validation_0-mae:2363.24960
[134]	validation_0-mae:2358.77656
[135]	validation_0-mae:2355.13238
[136]	validation_0-mae:2349.22935
[137]	validation_0-mae:2346.46148
[138]	validation_0-mae:2345.69702
[139]	validation_0-mae:2343.78880
[140]	validation_0-mae:2339.08216
[141]	validation_0-mae:2337.61922
[142]	validation_0-mae:2333.35133
[143]	validation_0-mae:2332.34250
[144]	validation_0-mae:2330.75864
[145]	validation_0-mae:2329.28012
[146]	validation_0-mae:2327.63102
[147]	validation_0-mae:2323.10910
[148]	validation_0-mae:2319.14318
[149]	validation_0-mae:2317.63098
[150]	validation_0-mae:2314.30235
[151]	validation_0-mae:2311.90082
[152]	validation_0-mae:2312.18194
[153]	validation_0-mae:2310.25559
[154]	validation_0-mae:2307.60212
[155]	validation_0-mae:2305.99522
[156]	validation_0-mae:2304.39474
[157]	validation_0-mae:2305.09430
[158]	validation_0-mae:2302.69423
[159]	validation_0-mae:2298.70230
[160]	validation_0-mae:2296.33616
[161]	validation_0-mae:2294.51357
[162]	validation_0-mae:2294.35065
[163]	validation_0-mae:2292.19716
[164]	validation_0-mae:2292.29971
[165]	validation_0-mae:2292.10666
[166]	validation_0-mae:2291.73096
[167]	validation_0-mae:2289.86767
[168]	validation_0-mae:2287.48569
[169]	validation_0-mae:2285.46422
[170]	validation_0-mae:2285.33199
[171]	validation_0-mae:2283.10433
[172]	validation_0-mae:2282.31189
[173]	validation_0-mae:2281.65139
[174]	validation_0-mae:2278.80872
[175]	validation_0-mae:2277.31169
[176]	validation_0-mae:2276.02574
[177]	validation_0-mae:2276.07855
[178]	validation_0-mae:2273.82523
[179]	validation_0-mae:2269.75686
[180]	validation_0-mae:2269.46828
[181]	validation_0-mae:2267.89497
[182]	validation_0-mae:2266.16926
[183]	validation_0-mae:2266.89731
[184]	validation_0-mae:2263.50647
[185]	validation_0-mae:2263.42737
[186]	validation_0-mae:2262.14463
[187]	validation_0-mae:2262.12597
[188]	validation_0-mae:2261.52910
[189]	validation_0-mae:2259.73603
[190]	validation_0-mae:2260.23830
[191]	validation_0-mae:2259.80020
[192]	validation_0-mae:2259.02190
[193]	validation_0-mae:2256.47028
[194]	validation_0-mae:2256.02920
[195]	validation_0-mae:2254.54699
[196]	validation_0-mae:2255.23769
[197]	validation_0-mae:2254.91420
[198]	validation_0-mae:2255.59183
[199]	validation_0-mae:2255.57534
[200]	validation_0-mae:2254.83213
[201]	validation_0-mae:2253.35908
[202]	validation_0-mae:2253.64514
[203]	validation_0-mae:2251.41772
[204]	validation_0-mae:2250.23669
[205]	validation_0-mae:2249.15179
[206]	validation_0-mae:2248.00396
[207]	validation_0-mae:2248.42291
[208]	validation_0-mae:2247.17116
[209]	validation_0-mae:2246.64682
[210]	validation_0-mae:2245.97355
[211]	validation_0-mae:2245.20934
[212]	validation_0-mae:2245.68864
[213]	validation_0-mae:2245.31875
[214]	validation_0-mae:2243.67014
[215]	validation_0-mae:2243.37993
[216]	validation_0-mae:2242.28513
[217]	validation_0-mae:2241.38106
[218]	validation_0-mae:2241.89586
[219]	validation_0-mae:2241.10777
[220]	validation_0-mae:2240.68483
[221]	validation_0-mae:2241.22647
[222]	validation_0-mae:2241.79888
[223]	validation_0-mae:2240.44481
[224]	validation_0-mae:2240.83841
[225]	validation_0-mae:2239.71331
[226]	validation_0-mae:2237.99808
[227]	validation_0-mae:2236.90898
[228]	validation_0-mae:2235.03603
[229]	validation_0-mae:2234.79219
[230]	validation_0-mae:2235.11790
[231]	validation_0-mae:2234.44258
[232]	validation_0-mae:2233.59433
[233]	validation_0-mae:2230.18125
[234]	validation_0-mae:2228.66731
[235]	validation_0-mae:2228.03399
[236]	validation_0-mae:2227.91087
[237]	validation_0-mae:2227.14948
[238]	validation_0-mae:2226.39937
[239]	validation_0-mae:2225.14373
[240]	validation_0-mae:2224.52025
[241]	validation_0-mae:2223.53063
[242]	validation_0-mae:2221.96632
[243]	validation_0-mae:2219.69413
[244]	validation_0-mae:2219.53405
[245]	validation_0-mae:2218.70500
[246]	validation_0-mae:2219.55568
[247]	validation_0-mae:2219.33730
[248]	validation_0-mae:2217.74745
[249]	validation_0-mae:2216.52444
[250]	validation_0-mae:2216.75219
[251]	validation_0-mae:2216.10889
[252]	validation_0-mae:2215.61588
[253]	validation_0-mae:2214.39930
[254]	validation_0-mae:2212.77677
[255]	validation_0-mae:2213.34623
[256]	validation_0-mae:2213.67621
[257]	validation_0-mae:2214.30664
[258]	validation_0-mae:2213.50610
[259]	validation_0-mae:2213.49164
[260]	validation_0-mae:2213.24083
[261]	validation_0-mae:2213.70886
[262]	validation_0-mae:2213.65213
[263]	validation_0-mae:2214.17399
[264]	validation_0-mae:2214.69153
[265]	validation_0-mae:2215.00390
[266]	validation_0-mae:2214.64805
[267]	validation_0-mae:2213.37058
[268]	validation_0-mae:2212.14593
[269]	validation_0-mae:2212.30768
[270]	validation_0-mae:2211.56110
[271]	validation_0-mae:2211.62404
[272]	validation_0-mae:2212.64409
[273]	validation_0-mae:2212.64809
[274]	validation_0-mae:2212.15394
[275]	validation_0-mae:2211.59939
[276]	validation_0-mae:2211.15157
[277]	validation_0-mae:2209.89580
[278]	validation_0-mae:2209.82776
[279]	validation_0-mae:2209.22955
[280]	validation_0-mae:2209.03309
[281]	validation_0-mae:2209.67711
[282]	validation_0-mae:2209.39206
[283]	validation_0-mae:2209.51837
[284]	validation_0-mae:2209.26384
[285]	validation_0-mae:2208.87281
[286]	validation_0-mae:2205.29349
[287]	validation_0-mae:2205.28441
[288]	validation_0-mae:2205.42052
[289]	validation_0-mae:2202.40144
[290]	validation_0-mae:2201.85363
[291]	validation_0-mae:2201.83139
[292]	validation_0-mae:2200.18903
[293]	validation_0-mae:2199.91002
[294]	validation_0-mae:2199.54736
[295]	validation_0-mae:2197.70858
[296]	validation_0-mae:2197.70538
[297]	validation_0-mae:2197.13031
[298]	validation_0-mae:2197.73159
[299]	validation_0-mae:2196.81628
[300]	validation_0-mae:2196.73396
[301]	validation_0-mae:2194.30311
[302]	validation_0-mae:2191.88858
[303]	validation_0-mae:2192.57090
[304]	validation_0-mae:2191.19231
[305]	validation_0-mae:2190.64105
[306]	validation_0-mae:2190.45714
[307]	validation_0-mae:2190.37076
[308]	validation_0-mae:2190.00082
[309]	validation_0-mae:2189.17986
[310]	validation_0-mae:2189.41086
[311]	validation_0-mae:2189.14275
[312]	validation_0-mae:2189.41338
[313]	validation_0-mae:2187.00172
[314]	validation_0-mae:2187.24315
[315]	validation_0-mae:2187.53815
[316]	validation_0-mae:2187.98945
[317]	validation_0-mae:2187.71439
[318]	validation_0-mae:2188.02222
[319]	validation_0-mae:2188.10644
[320]	validation_0-mae:2185.40618
[321]	validation_0-mae:2183.90007
[322]	validation_0-mae:2183.89625
[323]	validation_0-mae:2183.87462
[324]	validation_0-mae:2183.52605
[325]	validation_0-mae:2182.61335
[326]	validation_0-mae:2182.22775
[327]	validation_0-mae:2182.06548
[328]	validation_0-mae:2181.89777
[329]	validation_0-mae:2180.96412
[330]	validation_0-mae:2181.29804
[331]	validation_0-mae:2179.25367
[332]	validation_0-mae:2179.44997
[333]	validation_0-mae:2179.32329
[334]	validation_0-mae:2179.20902
[335]	validation_0-mae:2179.62455
[336]	validation_0-mae:2178.60458
[337]	validation_0-mae:2177.70693
[338]	validation_0-mae:2178.23580
[339]	validation_0-mae:2175.86591
[340]	validation_0-mae:2176.30890
[341]	validation_0-mae:2176.23383
[342]	validation_0-mae:2175.60475
[343]	validation_0-mae:2176.45669
[344]	validation_0-mae:2176.17466
[345]	validation_0-mae:2176.12384
[346]	validation_0-mae:2175.86429
[347]	validation_0-mae:2175.55737
[348]	validation_0-mae:2175.62116
[349]	validation_0-mae:2175.44780
[350]	validation_0-mae:2175.35966
[351]	validation_0-mae:2175.40325
[352]	validation_0-mae:2175.75252
[353]	validation_0-mae:2175.63524
[354]	validation_0-mae:2175.23722
[355]	validation_0-mae:2174.45150
[356]	validation_0-mae:2174.84170
[357]	validation_0-mae:2174.46206
[358]	validation_0-mae:2173.40445
[359]	validation_0-mae:2173.13929
[360]	validation_0-mae:2172.59642
[361]	validation_0-mae:2172.66142
[362]	validation_0-mae:2172.83475
[363]	validation_0-mae:2173.80878
[364]	validation_0-mae:2174.62679
[365]	validation_0-mae:2174.40083
[366]	validation_0-mae:2173.62818
[367]	validation_0-mae:2173.53811
[368]	validation_0-mae:2173.14857
[369]	validation_0-mae:2172.28451
[370]	validation_0-mae:2172.74804
[371]	validation_0-mae:2171.94241
[372]	validation_0-mae:2171.92394
[373]	validation_0-mae:2171.88271
[374]	validation_0-mae:2171.80059
[375]	validation_0-mae:2171.48010
[376]	validation_0-mae:2171.22860
[377]	validation_0-mae:2171.15168
[378]	validation_0-mae:2169.98415
[379]	validation_0-mae:2169.88372
[380]	validation_0-mae:2169.58822
[381]	validation_0-mae:2169.76866
[382]	validation_0-mae:2169.09316
[383]	validation_0-mae:2168.12913
[384]	validation_0-mae:2166.83065
[385]	validation_0-mae:2166.07754
[386]	validation_0-mae:2166.79022
[387]	validation_0-mae:2167.19221
[388]	validation_0-mae:2166.71636
[389]	validation_0-mae:2166.88070
[390]	validation_0-mae:2167.38282
[391]	validation_0-mae:2167.38169
[392]	validation_0-mae:2167.09712
[393]	validation_0-mae:2166.39728
[394]	validation_0-mae:2166.29661
[395]	validation_0-mae:2165.59871
[396]	validation_0-mae:2165.04477
[397]	validation_0-mae:2165.28354
[398]	validation_0-mae:2165.10857
[399]	validation_0-mae:2165.43816
[400]	validation_0-mae:2165.27357
[401]	validation_0-mae:2165.37831
[402]	validation_0-mae:2166.28516
[403]	validation_0-mae:2166.42197
[404]	validation_0-mae:2165.41613
[405]	validation_0-mae:2164.86238
[406]	validation_0-mae:2163.48986
[407]	validation_0-mae:2162.72259
[408]	validation_0-mae:2161.93678
[409]	validation_0-mae:2162.31333
[410]	validation_0-mae:2162.52390
[411]	validation_0-mae:2162.26661
[412]	validation_0-mae:2161.17442
[413]	validation_0-mae:2161.30248
[414]	validation_0-mae:2161.22532
[415]	validation_0-mae:2161.15013
[416]	validation_0-mae:2160.83277
[417]	validation_0-mae:2161.02810
[418]	validation_0-mae:2160.84160
[419]	validation_0-mae:2160.87766
[420]	validation_0-mae:2161.34858
[421]	validation_0-mae:2161.39672
[422]	validation_0-mae:2161.38188
[423]	validation_0-mae:2160.98890
[424]	validation_0-mae:2159.98112
[425]	validation_0-mae:2160.42581
[426]	validation_0-mae:2159.47635
[427]	validation_0-mae:2159.57698
[428]	validation_0-mae:2159.49333
[429]	validation_0-mae:2159.67612
[430]	validation_0-mae:2160.12018
[431]	validation_0-mae:2160.56666
[432]	validation_0-mae:2160.42228
[433]	validation_0-mae:2160.93036
[434]	validation_0-mae:2161.17123
[435]	validation_0-mae:2161.00140
[436]	validation_0-mae:2161.14873
[437]	validation_0-mae:2159.95759
[438]	validation_0-mae:2158.74059
[439]	validation_0-mae:2158.63304
[440]	validation_0-mae:2157.73381
[441]	validation_0-mae:2157.90850
[442]	validation_0-mae:2157.70645
[443]	validation_0-mae:2157.79730
[444]	validation_0-mae:2158.01538
[445]	validation_0-mae:2158.12580
[446]	validation_0-mae:2157.84005
[447]	validation_0-mae:2157.75179
[448]	validation_0-mae:2158.05547
[449]	validation_0-mae:2158.13969
[450]	validation_0-mae:2157.64232
[451]	validation_0-mae:2157.36995
[452]	validation_0-mae:2158.13555
[453]	validation_0-mae:2157.34033
[454]	validation_0-mae:2157.42915
[455]	validation_0-mae:2157.86932
[456]	validation_0-mae:2158.20398
[457]	validation_0-mae:2157.56533
[458]	validation_0-mae:2156.87053
[459]	validation_0-mae:2156.89757
[460]	validation_0-mae:2155.54828
[461]	validation_0-mae:2155.57978
[462]	validation_0-mae:2155.65501
[463]	validation_0-mae:2154.37892
[464]	validation_0-mae:2153.70693
[465]	validation_0-mae:2153.40584
[466]	validation_0-mae:2153.51637
[467]	validation_0-mae:2153.92533
[468]	validation_0-mae:2154.42985
[469]	validation_0-mae:2155.13357
[470]	validation_0-mae:2154.31775
[471]	validation_0-mae:2154.08918
[472]	validation_0-mae:2152.91522
[473]	validation_0-mae:2153.14805
[474]	validation_0-mae:2153.40391
[475]	validation_0-mae:2153.30070
[476]	validation_0-mae:2153.54171
[477]	validation_0-mae:2152.83647
[478]	validation_0-mae:2152.26747
[479]	validation_0-mae:2152.32437
[480]	validation_0-mae:2152.32830
[481]	validation_0-mae:2152.64363
[482]	validation_0-mae:2153.01829
[483]	validation_0-mae:2152.91720
[484]	validation_0-mae:2152.88262
[485]	validation_0-mae:2152.59353
[486]	validation_0-mae:2152.27487
[487]	validation_0-mae:2152.24128
[488]	validation_0-mae:2151.90797
[489]	validation_0-mae:2152.12722
[490]	validation_0-mae:2150.79060
[491]	validation_0-mae:2149.64576
[492]	validation_0-mae:2147.89002
[493]	validation_0-mae:2147.80028
[494]	validation_0-mae:2147.33431
[495]	validation_0-mae:2147.32574
[496]	validation_0-mae:2147.71841
[497]	validation_0-mae:2147.71137
[498]	validation_0-mae:2147.50934
[499]	validation_0-mae:2147.30801
[500]	validation_0-mae:2147.28289
[501]	validation_0-mae:2147.47612
[502]	validation_0-mae:2144.97324
[503]	validation_0-mae:2144.86537
[504]	validation_0-mae:2144.90978
[505]	validation_0-mae:2145.03803
[506]	validation_0-mae:2145.26362
[507]	validation_0-mae:2145.12778
[508]	validation_0-mae:2143.56800
[509]	validation_0-mae:2143.73364
[510]	validation_0-mae:2142.55817
[511]	validation_0-mae:2142.65305
[512]	validation_0-mae:2142.34007
[513]	validation_0-mae:2141.91182
[514]	validation_0-mae:2141.89258
[515]	validation_0-mae:2141.53151
[516]	validation_0-mae:2141.71500
[517]	validation_0-mae:2142.36655
[518]	validation_0-mae:2142.57239
[519]	validation_0-mae:2143.05223
[520]	validation_0-mae:2143.26998
[521]	validation_0-mae:2143.30450
[522]	validation_0-mae:2143.64373
[523]	validation_0-mae:2142.63139
[524]	validation_0-mae:2142.42458
[525]	validation_0-mae:2142.43743
[526]	validation_0-mae:2139.99722
[527]	validation_0-mae:2138.57915
[528]	validation_0-mae:2138.59827
[529]	validation_0-mae:2138.70591
[530]	validation_0-mae:2138.24676
[531]	validation_0-mae:2138.86518
[532]	validation_0-mae:2138.59780
[533]	validation_0-mae:2137.19400
[534]	validation_0-mae:2137.29420
[535]	validation_0-mae:2137.76568
[536]	validation_0-mae:2138.18255
[537]	validation_0-mae:2138.32622
[538]	validation_0-mae:2137.55719
[539]	validation_0-mae:2137.55372
[540]	validation_0-mae:2137.88418
[541]	validation_0-mae:2137.79793
[542]	validation_0-mae:2138.17529
[543]	validation_0-mae:2138.07607
[544]	validation_0-mae:2138.47635
[545]	validation_0-mae:2138.20812
[546]	validation_0-mae:2138.19944
[547]	validation_0-mae:2137.99284
[548]	validation_0-mae:2137.84423
[549]	validation_0-mae:2137.80862
[550]	validation_0-mae:2137.97670
[551]	validation_0-mae:2137.02600
[552]	validation_0-mae:2137.19655
[553]	validation_0-mae:2137.76011
[554]	validation_0-mae:2137.65055
[555]	validation_0-mae:2137.76541
[556]	validation_0-mae:2137.40679
[557]	validation_0-mae:2137.51587
[558]	validation_0-mae:2137.01023
[559]	validation_0-mae:2137.28779
[560]	validation_0-mae:2136.76874
[561]	validation_0-mae:2136.78736
[562]	validation_0-mae:2136.77516
[563]	validation_0-mae:2136.83395
[564]	validation_0-mae:2135.90243
[565]	validation_0-mae:2135.88314
[566]	validation_0-mae:2135.70505
[567]	validation_0-mae:2135.31665
[568]	validation_0-mae:2135.46769
[569]	validation_0-mae:2135.62343
[570]	validation_0-mae:2135.78129
[571]	validation_0-mae:2135.34390
[572]	validation_0-mae:2135.63394
[573]	validation_0-mae:2135.67554
[574]	validation_0-mae:2135.46182
[575]	validation_0-mae:2135.53737
[576]	validation_0-mae:2135.30980
[577]	validation_0-mae:2134.59002
[578]	validation_0-mae:2134.25252
[579]	validation_0-mae:2134.00231
[580]	validation_0-mae:2132.23893
[581]	validation_0-mae:2131.37372
[582]	validation_0-mae:2131.48972
[583]	validation_0-mae:2131.67548
[584]	validation_0-mae:2131.68482
[585]	validation_0-mae:2132.07866
[586]	validation_0-mae:2132.32216
[587]	validation_0-mae:2132.01752
[588]	validation_0-mae:2132.52672
[589]	validation_0-mae:2131.98467
[590]	validation_0-mae:2132.08306
[591]	validation_0-mae:2132.03270
[592]	validation_0-mae:2132.23961
[593]	validation_0-mae:2132.39360
[594]	validation_0-mae:2132.71668
[595]	validation_0-mae:2132.70758
[596]	validation_0-mae:2130.60646
[597]	validation_0-mae:2130.95198
[598]	validation_0-mae:2131.01914
[599]	validation_0-mae:2131.05225
[600]	validation_0-mae:2130.96120
[601]	validation_0-mae:2131.36470
[602]	validation_0-mae:2131.04482
[603]	validation_0-mae:2130.92377
[604]	validation_0-mae:2131.41109

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[18]	validation_0-mae:8117.45588
[19]	validation_0-mae:8044.26042
[20]	validation_0-mae:7977.24480
[21]	validation_0-mae:7914.30694
[22]	validation_0-mae:7855.18005
[23]	validation_0-mae:7815.95529
[24]	validation_0-mae:7779.30568
[25]	validation_0-mae:7729.07769
[26]	validation_0-mae:7684.04715
[27]	validation_0-mae:7647.85202
[28]	validation_0-mae:7611.84332
[29]	validation_0-mae:7575.89015
[30]	validation_0-mae:7555.23661
[31]	validation_0-mae:7509.85922
[32]	validation_0-mae:7469.55183
[33]	validation_0-mae:7408.99314
[34]	validation_0-mae:7364.02767
[35]	validation_0-mae:7334.12244
[36]	validation_0-mae:7302.19768
[37]	validation_0-mae:7236.15706
[38]	validation_0-mae:7193.07661
[39]	validation_0-mae:7186.05973
[40]	validation_0-mae:7157.55904
[41]	validation_0-mae:7109.65042
[42]	validation_0-mae:7087.76878
[43]	validation_0-mae:7064.89532
[44]	validation_0-mae:7002.37323
[45]	validation_0-mae:6985.96476
[46]	validation_0-mae:6970.32815
[47]	validation_0-mae:6941.73622
[48]	validation_0-mae:6904.25279
[49]	validation_0-mae:6888.95594
[50]	validation_0-mae:6885.84011
[51]	validation_0-mae:6868.22354
[52]	validation_0-mae:6860.64778
[0]	validation_0-mae:12528.08025
[1]	validation_0-mae:11851.90073
[2]	validation_0-mae:11250.31009
[3]	validation_0-mae:10677.86004
[4]	validation_0-mae:10177.21553
[5]	validation_0-mae:9735.39885
[6]	validation_0-mae:9312.77769
[7]	validation_0-mae:8926.36306
[8]	validation_0-mae:8568.57168
[9]	validation_0-mae:8232.18091
[10]	validation_0-mae:7921.94023
[11]	validation_0-mae:7636.60631
[12]	validation_0-mae:7378.24157
[13]	validation_0-mae:7108.46736
[14]	validation_0-mae:6862.83240

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[15]	validation_0-mae:6647.34861
[16]	validation_0-mae:6397.25706
[17]	validation_0-mae:6197.00899
[18]	validation_0-mae:6017.80885
[19]	validation_0-mae:5827.65981
[20]	validation_0-mae:5647.02833
[21]	validation_0-mae:5491.78994
[22]	validation_0-mae:5337.05382
[23]	validation_0-mae:5197.45080
[24]	validation_0-mae:5050.98668
[25]	validation_0-mae:4922.31915
[26]	validation_0-mae:4806.82859
[27]	validation_0-mae:4702.80817
[28]	validation_0-mae:4580.69157
[29]	validation_0-mae:4480.27185
[30]	validation_0-mae:4368.13061
[31]	validation_0-mae:4294.70268
[32]	validation_0-mae:4201.12906
[33]	validation_0-mae:4113.46106
[34]	validation_0-mae:4019.91011
[35]	validation_0-mae:3942.07295
[36]	validation_0-mae:3871.14386
[37]	validation_0-mae:3801.28309
[38]	validation_0-mae:3735.87854
[39]	validation_0-mae:3681.30681
[40]	validation_0-mae:3626.75232
[41]	validation_0-mae:3586.11055
[42]	validation_0-mae:3539.15478
[43]	validation_0-mae:3496.87651
[44]	validation_0-mae:3453.75867
[45]	validation_0-mae:3416.28243
[46]	validation_0-mae:3379.02435
[47]	validation_0-mae:3341.47237
[48]	validation_0-mae:3289.00609
[49]	validation_0-mae:3260.38499
[50]	validation_0-mae:3231.22384
[51]	validation_0-mae:3191.17303
[52]	validation_0-mae:3168.07095
[53]	validation_0-mae:3142.85369
[54]	validation_0-mae:3110.10071
[55]	validation_0-mae:3088.15463
[56]	validation_0-mae:3067.27109
[57]	validation_0-mae:3029.65670
[58]	validation_0-mae:3011.45976
[59]	validation_0-mae:2994.68332
[60]	validation_0-mae:2975.09985
[61]	validation_0-mae:2941.44636
[62]	validation_0-mae:2923.41951
[63]	validation_0-mae:2911.30250
[64]	validation_0-mae:2884.88765
[65]	validation_0-mae:2862.22334
[66]	validation_0-mae:2849.50317
[67]	validation_0-mae:2833.64504
[68]	validation_0-mae:2821.29210
[69]	validation_0-mae:2806.31964
[70]	validation_0-mae:2790.37870
[71]	validation_0-mae:2779.29184
[72]	validation_0-mae:2764.91669
[73]	validation_0-mae:2754.81309
[74]	validation_0-mae:2742.02494
[75]	validation_0-mae:2716.77838
[76]	validation_0-mae:2703.94867
[77]	validation_0-mae:2683.23010
[78]	validation_0-mae:2669.19981
[79]	validation_0-mae:2660.91593
[80]	validation_0-mae:2651.55450
[81]	validation_0-mae:2646.63299
[82]	validation_0-mae:2633.96203
[83]	validation_0-mae:2616.83946
[84]	validation_0-mae:2604.67470
[85]	validation_0-mae:2588.92207
[86]	validation_0-mae:2583.17073
[87]	validation_0-mae:2575.81688
[88]	validation_0-mae:2565.87904
[89]	validation_0-mae:2556.34791
[90]	validation_0-mae:2549.74548
[91]	validation_0-mae:2542.86377
[92]	validation_0-mae:2526.72712
[93]	validation_0-mae:2521.48887
[94]	validation_0-mae:2517.01152
[95]	validation_0-mae:2508.68053
[96]	validation_0-mae:2503.62393
[97]	validation_0-mae:2497.17143
[98]	validation_0-mae:2490.69273
[99]	validation_0-mae:2481.73771
[100]	validation_0-mae:2476.25270
[101]	validation_0-mae:2470.40841
[102]	validation_0-mae:2459.02680
[103]	validation_0-mae:2450.09200
[104]	validation_0-mae:2443.10688
[105]	validation_0-mae:2442.63701
[106]	validation_0-mae:2439.66010
[107]	validation_0-mae:2433.76691
[108]	validation_0-mae:2428.60900
[109]	validation_0-mae:2422.49490
[110]	validation_0-mae:2418.37212
[111]	validation_0-mae:2411.12616
[112]	validation_0-mae:2408.77228
[113]	validation_0-mae:2404.93568
[114]	validation_0-mae:2400.45694
[115]	validation_0-mae:2393.24861
[116]	validation_0-mae:2388.47693
[117]	validation_0-mae:2386.66628
[118]	validation_0-mae:2383.97172
[119]	validation_0-mae:2379.24446
[120]	validation_0-mae:2375.66831
[121]	validation_0-mae:2370.17581
[122]	validation_0-mae:2361.85277
[123]	validation_0-mae:2357.53934
[124]	validation_0-mae:2356.30701
[125]	validation_0-mae:2352.05652
[126]	validation_0-mae:2351.05167
[127]	validation_0-mae:2349.35357
[128]	validation_0-mae:2340.66774
[129]	validation_0-mae:2337.94087
[130]	validation_0-mae:2335.19835
[131]	validation_0-mae:2333.59114
[132]	validation_0-mae:2330.19538
[133]	validation_0-mae:2323.61265
[134]	validation_0-mae:2320.32587
[135]	validation_0-mae:2316.28313
[136]	validation_0-mae:2312.21948
[137]	validation_0-mae:2310.13255
[138]	validation_0-mae:2310.84347
[139]	validation_0-mae:2307.89830
[140]	validation_0-mae:2304.77555
[141]	validation_0-mae:2303.11483
[142]	validation_0-mae:2300.05430
[143]	validation_0-mae:2299.70316
[144]	validation_0-mae:2298.88716
[145]	validation_0-mae:2299.33741
[146]	validation_0-mae:2298.95515
[147]	validation_0-mae:2295.85620
[148]	validation_0-mae:2292.11696
[149]	validation_0-mae:2288.92365
[150]	validation_0-mae:2286.87171
[151]	validation_0-mae:2281.15629
[152]	validation_0-mae:2280.64600
[153]	validation_0-mae:2278.77313
[154]	validation_0-mae:2274.21527
[155]	validation_0-mae:2270.72730
[156]	validation_0-mae:2267.94505
[157]	validation_0-mae:2265.79268
[158]	validation_0-mae:2265.15534
[159]	validation_0-mae:2262.54800
[160]	validation_0-mae:2262.19948
[161]	validation_0-mae:2260.82689
[162]	validation_0-mae:2259.36182
[163]	validation_0-mae:2254.97516
[164]	validation_0-mae:2252.01260
[165]	validation_0-mae:2252.73320
[166]	validation_0-mae:2250.68291
[167]	validation_0-mae:2250.85630
[168]	validation_0-mae:2250.90386
[169]	validation_0-mae:2249.42422
[170]	validation_0-mae:2247.43585
[171]	validation_0-mae:2247.80995
[172]	validation_0-mae:2246.71766
[173]	validation_0-mae:2244.80209
[174]	validation_0-mae:2242.58109
[175]	validation_0-mae:2240.07930
[176]	validation_0-mae:2239.01490
[177]	validation_0-mae:2238.75875
[178]	validation_0-mae:2237.88044
[179]	validation_0-mae:2234.95584
[180]	validation_0-mae:2234.39251
[181]	validation_0-mae:2231.88578
[182]	validation_0-mae:2231.65411
[183]	validation_0-mae:2230.65856
[184]	validation_0-mae:2229.43033
[185]	validation_0-mae:2228.11274
[186]	validation_0-mae:2227.51421
[187]	validation_0-mae:2226.58758
[188]	validation_0-mae:2223.65284
[189]	validation_0-mae:2223.42403
[190]	validation_0-mae:2224.05418
[191]	validation_0-mae:2223.55817
[192]	validation_0-mae:2223.98086
[193]	validation_0-mae:2223.99274
[194]	validation_0-mae:2222.18182
[195]	validation_0-mae:2221.61179
[196]	validation_0-mae:2221.56862
[197]	validation_0-mae:2223.29504
[198]	validation_0-mae:2222.70270
[199]	validation_0-mae:2221.54014
[200]	validation_0-mae:2220.34866
[201]	validation_0-mae:2220.56427
[202]	validation_0-mae:2220.18588
[203]	validation_0-mae:2219.42687
[204]	validation_0-mae:2217.85486
[205]	validation_0-mae:2217.14502
[206]	validation_0-mae:2216.57822
[207]	validation_0-mae:2215.43794
[208]	validation_0-mae:2215.24205
[209]	validation_0-mae:2212.71650
[210]	validation_0-mae:2212.41041
[211]	validation_0-mae:2211.20431
[212]	validation_0-mae:2209.49992
[213]	validation_0-mae:2206.47626
[214]	validation_0-mae:2206.75089
[215]	validation_0-mae:2207.16678
[216]	validation_0-mae:2205.59626
[217]	validation_0-mae:2205.62996
[218]	validation_0-mae:2204.64837
[219]	validation_0-mae:2202.79646
[220]	validation_0-mae:2201.76691
[221]	validation_0-mae:2200.42821
[222]	validation_0-mae:2199.10580
[223]	validation_0-mae:2198.36545
[224]	validation_0-mae:2196.38129
[225]	validation_0-mae:2196.29924
[226]	validation_0-mae:2195.95482
[227]	validation_0-mae:2196.00653
[228]	validation_0-mae:2193.51991
[229]	validation_0-mae:2193.43617
[230]	validation_0-mae:2193.43933
[231]	validation_0-mae:2193.19178
[232]	validation_0-mae:2192.10977
[233]	validation_0-mae:2192.16829
[234]	validation_0-mae:2190.33392
[235]	validation_0-mae:2189.76240
[236]	validation_0-mae:2189.89855
[237]	validation_0-mae:2189.41766
[238]	validation_0-mae:2188.83344
[239]	validation_0-mae:2187.89236
[240]	validation_0-mae:2187.72196
[241]	validation_0-mae:2187.12369
[242]	validation_0-mae:2187.48915
[243]	validation_0-mae:2187.57847
[244]	validation_0-mae:2186.90204
[245]	validation_0-mae:2185.72009
[246]	validation_0-mae:2185.50475
[247]	validation_0-mae:2185.12116
[248]	validation_0-mae:2185.45693
[249]	validation_0-mae:2184.63452
[250]	validation_0-mae:2183.75298
[251]	validation_0-mae:2184.12908
[252]	validation_0-mae:2183.88284
[253]	validation_0-mae:2183.30559
[254]	validation_0-mae:2181.59304
[255]	validation_0-mae:2183.09428
[256]	validation_0-mae:2181.35645
[257]	validation_0-mae:2180.05911
[258]	validation_0-mae:2180.20093
[259]	validation_0-mae:2179.38439
[260]	validation_0-mae:2179.26720
[261]	validation_0-mae:2178.73716
[262]	validation_0-mae:2179.51927
[263]	validation_0-mae:2179.40022
[264]	validation_0-mae:2179.38937
[265]	validation_0-mae:2179.67323
[266]	validation_0-mae:2179.34311
[267]	validation_0-mae:2178.95892
[268]	validation_0-mae:2178.46546
[269]	validation_0-mae:2179.07853
[270]	validation_0-mae:2179.36840
[271]	validation_0-mae:2178.78598
[272]	validation_0-mae:2178.78614
[273]	validation_0-mae:2178.93272
[274]	validation_0-mae:2178.70931
[275]	validation_0-mae:2177.65048
[276]	validation_0-mae:2177.96088
[277]	validation_0-mae:2179.64984
[278]	validation_0-mae:2178.51230
[279]	validation_0-mae:2178.21013
[280]	validation_0-mae:2177.48412
[281]	validation_0-mae:2177.41211
[282]	validation_0-mae:2177.42784
[283]	validation_0-mae:2177.79907
[284]	validation_0-mae:2177.72511
[285]	validation_0-mae:2178.48751
[286]	validation_0-mae:2178.42431
[287]	validation_0-mae:2177.84834
[288]	validation_0-mae:2178.21413
[289]	validation_0-mae:2178.34495
[290]	validation_0-mae:2176.95536
[291]	validation_0-mae:2176.58734
[292]	validation_0-mae:2176.40243
[293]	validation_0-mae:2175.03910
[294]	validation_0-mae:2175.19621
[295]	validation_0-mae:2175.84405
[296]	validation_0-mae:2175.93937
[297]	validation_0-mae:2175.49548
[298]	validation_0-mae:2174.53321
[299]	validation_0-mae:2173.40906
[300]	validation_0-mae:2173.46025
[301]	validation_0-mae:2173.72597
[302]	validation_0-mae:2173.88378
[303]	validation_0-mae:2172.16314
[304]	validation_0-mae:2169.64958
[305]	validation_0-mae:2169.51029
[306]	validation_0-mae:2169.15245
[307]	validation_0-mae:2169.93858
[308]	validation_0-mae:2170.14027
[309]	validation_0-mae:2170.35376
[310]	validation_0-mae:2170.64210
[311]	validation_0-mae:2170.60504
[312]	validation_0-mae:2170.84077
[313]	validation_0-mae:2171.62690
[314]	validation_0-mae:2170.57588
[315]	validation_0-mae:2170.12195
[316]	validation_0-mae:2170.41624
[317]	validation_0-mae:2171.04575
[318]	validation_0-mae:2171.32998
[319]	validation_0-mae:2171.04648
[320]	validation_0-mae:2170.41765
[321]	validation_0-mae:2170.72393
[322]	validation_0-mae:2170.88729
[323]	validation_0-mae:2169.94988
[324]	validation_0-mae:2168.57004
[325]	validation_0-mae:2167.56820
[326]	validation_0-mae:2167.65045
[327]	validation_0-mae:2168.11019
[328]	validation_0-mae:2168.14205
[329]	validation_0-mae:2168.47354
[330]	validation_0-mae:2168.51732
[331]	validation_0-mae:2167.51914
[332]	validation_0-mae:2165.94364
[333]	validation_0-mae:2165.34087
[334]	validation_0-mae:2164.87367
[335]	validation_0-mae:2163.16699
[336]	validation_0-mae:2163.17617
[337]	validation_0-mae:2162.96103
[338]	validation_0-mae:2162.44021
[339]	validation_0-mae:2162.56372
[340]	validation_0-mae:2162.21135
[341]	validation_0-mae:2160.29658
[342]	validation_0-mae:2159.84682
[343]	validation_0-mae:2158.99018
[344]	validation_0-mae:2158.88850
[345]	validation_0-mae:2158.94085
[346]	validation_0-mae:2158.86421
[347]	validation_0-mae:2158.78101
[348]	validation_0-mae:2158.52421
[349]	validation_0-mae:2157.85151
[350]	validation_0-mae:2157.45483
[351]	validation_0-mae:2157.03215
[352]	validation_0-mae:2157.02638
[353]	validation_0-mae:2157.13283
[354]	validation_0-mae:2156.99552
[355]	validation_0-mae:2156.44960
[356]	validation_0-mae:2154.28597
[357]	validation_0-mae:2154.00018
[358]	validation_0-mae:2153.26560
[359]	validation_0-mae:2153.64498
[360]	validation_0-mae:2154.30900
[361]	validation_0-mae:2153.73799
[362]	validation_0-mae:2153.67702
[363]	validation_0-mae:2152.85133
[364]	validation_0-mae:2152.53843
[365]	validation_0-mae:2151.34257
[366]	validation_0-mae:2150.70347
[367]	validation_0-mae:2150.13443
[368]	validation_0-mae:2148.58824
[369]	validation_0-mae:2147.52619
[370]	validation_0-mae:2147.04742
[371]	validation_0-mae:2146.77093
[372]	validation_0-mae:2146.65765
[373]	validation_0-mae:2146.89248
[374]	validation_0-mae:2146.23720
[375]	validation_0-mae:2146.59895
[376]	validation_0-mae:2146.30292
[377]	validation_0-mae:2146.34464
[378]	validation_0-mae:2146.81780
[379]	validation_0-mae:2147.07381
[380]	validation_0-mae:2144.87584
[381]	validation_0-mae:2144.96877
[382]	validation_0-mae:2144.18092
[383]	validation_0-mae:2143.14403
[384]	validation_0-mae:2142.66036
[385]	validation_0-mae:2142.11741
[386]	validation_0-mae:2141.74535
[387]	validation_0-mae:2141.78615
[388]	validation_0-mae:2142.00734
[389]	validation_0-mae:2141.79500
[390]	validation_0-mae:2142.25211
[391]	validation_0-mae:2142.11319
[392]	validation_0-mae:2141.36986
[393]	validation_0-mae:2141.19837
[394]	validation_0-mae:2141.28137
[395]	validation_0-mae:2141.11439
[396]	validation_0-mae:2141.56137
[397]	validation_0-mae:2141.84644
[398]	validation_0-mae:2140.72113
[399]	validation_0-mae:2139.57525
[400]	validation_0-mae:2139.96735
[401]	validation_0-mae:2140.09062
[402]	validation_0-mae:2137.98310
[403]	validation_0-mae:2137.74217
[404]	validation_0-mae:2138.06833
[405]	validation_0-mae:2137.19655
[406]	validation_0-mae:2137.18803
[407]	validation_0-mae:2136.97038
[408]	validation_0-mae:2137.06538
[409]	validation_0-mae:2137.64060
[410]	validation_0-mae:2137.09006
[411]	validation_0-mae:2136.96071
[412]	validation_0-mae:2136.87187
[413]	validation_0-mae:2137.02953
[414]	validation_0-mae:2136.73234
[415]	validation_0-mae:2136.78961
[416]	validation_0-mae:2136.62095
[417]	validation_0-mae:2136.43473
[418]	validation_0-mae:2136.49838
[419]	validation_0-mae:2135.41746
[420]	validation_0-mae:2134.61206
[421]	validation_0-mae:2134.23822
[422]	validation_0-mae:2133.91607
[423]	validation_0-mae:2134.18762
[424]	validation_0-mae:2133.83137
[425]	validation_0-mae:2134.07817
[426]	validation_0-mae:2134.31045
[427]	validation_0-mae:2134.06469
[428]	validation_0-mae:2133.29178
[429]	validation_0-mae:2132.30596
[430]	validation_0-mae:2131.41786
[431]	validation_0-mae:2129.82074
[432]	validation_0-mae:2128.90808
[433]	validation_0-mae:2128.44907
[434]	validation_0-mae:2128.71152
[435]	validation_0-mae:2128.81198
[436]	validation_0-mae:2128.05444
[437]	validation_0-mae:2127.80303
[438]	validation_0-mae:2127.77398
[439]	validation_0-mae:2128.12009
[440]	validation_0-mae:2126.56632
[441]	validation_0-mae:2126.39096
[442]	validation_0-mae:2124.81951
[443]	validation_0-mae:2124.96958
[444]	validation_0-mae:2125.44576
[445]	validation_0-mae:2125.30193
[446]	validation_0-mae:2124.53844
[447]	validation_0-mae:2124.01094
[448]	validation_0-mae:2124.40453
[449]	validation_0-mae:2124.38305
[450]	validation_0-mae:2124.48800
[451]	validation_0-mae:2124.80735
[452]	validation_0-mae:2124.99266
[453]	validation_0-mae:2124.91697
[454]	validation_0-mae:2124.43712
[455]	validation_0-mae:2124.58844
[456]	validation_0-mae:2124.02395
[457]	validation_0-mae:2124.14183
[458]	validation_0-mae:2124.51576
[459]	validation_0-mae:2124.35758
[460]	validation_0-mae:2124.17388
[461]	validation_0-mae:2122.91519
[462]	validation_0-mae:2123.48607
[463]	validation_0-mae:2123.49392
[464]	validation_0-mae:2123.94754
[465]	validation_0-mae:2124.22731
[466]	validation_0-mae:2124.51718
[467]	validation_0-mae:2124.65065
[468]	validation_0-mae:2124.48717
[469]	validation_0-mae:2124.99646
[470]	validation_0-mae:2124.82988
[471]	validation_0-mae:2125.24533
[472]	validation_0-mae:2125.34762
[473]	validation_0-mae:2125.41979
[474]	validation_0-mae:2124.77026
[475]	validation_0-mae:2125.10824
[476]	validation_0-mae:2125.62065
[477]	validation_0-mae:2125.30490
[478]	validation_0-mae:2125.21679
[479]	validation_0-mae:2125.47418
[480]	validation_0-mae:2125.13852
[481]	validation_0-mae:2125.35146
[482]	validation_0-mae:2125.38803
[483]	validation_0-mae:2124.39565
[484]	validation_0-mae:2124.32278
[485]	validation_0-mae:2123.65915
[486]	validation_0-mae:2123.31784
[487]	validation_0-mae:2123.69210
[488]	validation_0-mae:2123.00574
[489]	validation_0-mae:2122.21320
[490]	validation_0-mae:2122.00429
[491]	validation_0-mae:2122.11591
[492]	validation_0-mae:2121.35632
[493]	validation_0-mae:2121.15841
[494]	validation_0-mae:2121.28287
[495]	validation_0-mae:2121.22236
[496]	validation_0-mae:2121.42873
[497]	validation_0-mae:2121.48118
[498]	validation_0-mae:2121.57220
[499]	validation_0-mae:2120.62137
[500]	validation_0-mae:2120.18786
[501]	validation_0-mae:2120.22522
[502]	validation_0-mae:2120.36211
[503]	validation_0-mae:2120.12248
[504]	validation_0-mae:2119.55177
[505]	validation_0-mae:2119.47061
[506]	validation_0-mae:2118.61868
[507]	validation_0-mae:2118.86056
[508]	validation_0-mae:2118.48936
[509]	validation_0-mae:2118.62209
[510]	validation_0-mae:2118.60288
[511]	validation_0-mae:2118.46968
[512]	validation_0-mae:2118.32940
[513]	validation_0-mae:2117.98422
[514]	validation_0-mae:2117.64732
[515]	validation_0-mae:2117.19327
[516]	validation_0-mae:2117.10012
[517]	validation_0-mae:2116.44207
[518]	validation_0-mae:2116.15889
[519]	validation_0-mae:2115.22991
[520]	validation_0-mae:2115.05838
[521]	validation_0-mae:2114.68890
[522]	validation_0-mae:2114.56008
[523]	validation_0-mae:2114.95032
[524]	validation_0-mae:2114.98021
[525]	validation_0-mae:2114.78794
[526]	validation_0-mae:2113.02597
[527]	validation_0-mae:2113.14091
[528]	validation_0-mae:2113.08470
[529]	validation_0-mae:2113.47093
[530]	validation_0-mae:2112.33818
[531]	validation_0-mae:2112.32869
[532]	validation_0-mae:2111.46474
[533]	validation_0-mae:2111.71471
[534]	validation_0-mae:2111.48847
[535]	validation_0-mae:2111.29634
[536]	validation_0-mae:2111.52068
[537]	validation_0-mae:2111.98558
[538]	validation_0-mae:2112.15394
[539]	validation_0-mae:2112.66059
[540]	validation_0-mae:2112.54195
[541]	validation_0-mae:2112.52573
[542]	validation_0-mae:2111.49914
[543]	validation_0-mae:2111.59506
[544]	validation_0-mae:2110.80546
[545]	validation_0-mae:2109.61877
[546]	validation_0-mae:2109.67205
[547]	validation_0-mae:2110.21189
[548]	validation_0-mae:2109.62813
[549]	validation_0-mae:2109.60848
[550]	validation_0-mae:2109.53481
[551]	validation_0-mae:2109.05210
[552]	validation_0-mae:2108.84391
[553]	validation_0-mae:2109.13348
[554]	validation_0-mae:2108.52965
[555]	validation_0-mae:2108.26217
[556]	validation_0-mae:2108.48541
[557]	validation_0-mae:2108.57029
[558]	validation_0-mae:2108.69078
[559]	validation_0-mae:2108.77266
[560]	validation_0-mae:2108.95727
[561]	validation_0-mae:2108.74705
[562]	validation_0-mae:2107.70438
[563]	validation_0-mae:2107.36991
[564]	validation_0-mae:2107.47972
[565]	validation_0-mae:2107.61231
[566]	validation_0-mae:2107.06931
[567]	validation_0-mae:2107.05186
[568]	validation_0-mae:2107.41832
[569]	validation_0-mae:2106.83158
[570]	validation_0-mae:2106.61439
[571]	validation_0-mae:2106.90887
[572]	validation_0-mae:2106.84171
[573]	validation_0-mae:2105.84228
[574]	validation_0-mae:2105.66199
[575]	validation_0-mae:2105.87672
[576]	validation_0-mae:2105.86116
[577]	validation_0-mae:2105.48681
[578]	validation_0-mae:2105.50340
[579]	validation_0-mae:2105.64718
[580]	validation_0-mae:2105.35517
[581]	validation_0-mae:2104.51377
[582]	validation_0-mae:2103.90046
[583]	validation_0-mae:2104.10030
[584]	validation_0-mae:2103.81360
[585]	validation_0-mae:2104.31436
[586]	validation_0-mae:2104.23442
[587]	validation_0-mae:2103.68482
[588]	validation_0-mae:2103.12076
[589]	validation_0-mae:2103.48635
[590]	validation_0-mae:2103.77550
[591]	validation_0-mae:2103.36839
[592]	validation_0-mae:2103.37950
[593]	validation_0-mae:2102.44429
[594]	validation_0-mae:2102.29531
[595]	validation_0-mae:2102.69053
[596]	validation_0-mae:2102.35809
[597]	validation_0-mae:2101.98557
[598]	validation_0-mae:2102.12377
[599]	validation_0-mae:2101.86459
[600]	validation_0-mae:2101.22178
[601]	validation_0-mae:2101.38561
[602]	validation_0-mae:2101.24966
[603]	validation_0-mae:2101.22255
[604]	validation_0-mae:2101.40571

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[19]	validation_0-mae:7202.65310
[20]	validation_0-mae:7089.38014
[21]	validation_0-mae:7015.09702
[22]	validation_0-mae:6935.36895
[23]	validation_0-mae:6845.78127
[24]	validation_0-mae:6766.45109
[25]	validation_0-mae:6713.10340
[26]	validation_0-mae:6647.14807
[27]	validation_0-mae:6580.05759
[28]	validation_0-mae:6510.61530
[29]	validation_0-mae:6462.60196
[30]	validation_0-mae:6368.77895
[31]	validation_0-mae:6304.46533
[32]	validation_0-mae:6249.99494
[33]	validation_0-mae:6212.02055
[34]	validation_0-mae:6149.52715
[35]	validation_0-mae:6103.91364
[36]	validation_0-mae:6021.01010
[37]	validation_0-mae:5971.01907
[38]	validation_0-mae:5925.51443
[39]	validation_0-mae:5893.31534
[40]	validation_0-mae:5865.48399
[41]	validation_0-mae:5824.37848
[42]	validation_0-mae:5786.95826
[43]	validation_0-mae:5746.35322
[44]	validation_0-mae:5710.40923
[45]	validation_0-mae:5666.33018
[46]	validation_0-mae:5641.81591
[47]	validation_0-mae:5608.02684
[48]	validation_0-mae:5573.03762
[49]	validation_0-mae:5549.19727
[50]	validation_0-mae:5521.47250
[51]	validation_0-mae:5492.44256
[52]	validation_0-mae:5468.30163
[53]	validation_0-mae:5440.46497
[54]	validation_0-mae:5415.13395
[55]	validation_0-mae:5398.38374
[56]	validation_0-mae:5379.02027
[57]	validation_0-mae:5313.20778
[58]	validation_0-mae:5292.14483
[59]	validation_0-mae:5237.80582
[60]	validation_0-mae:5212.45876
[61]	validation_0-mae:5192.49356
[62]	validation_0-mae:5170.43785
[63]	validation_0-mae:5143.38203
[64]	validation_0-mae:5124.60354
[65]	validation_0-mae:5108.91534
[66]	validation_0-mae:5093.29347
[67]	validation_0-mae:5053.18516
[68]	validation_0-mae:5046.48077
[69]	validation_0-mae:5034.12552
[70]	validation_0-mae:5005.89166
[71]	validation_0-mae:4990.07013
[72]	validation_0-mae:4977.65588
[73]	validation_0-mae:4956.07584
[74]	validation_0-mae:4941.90411
[75]	validation_0-mae:4929.59553
[76]	validation_0-mae:4913.90077
[77]	validation_0-mae:4902.42313
[78]	validation_0-mae:4895.20396
[79]	validation_0-mae:4884.59642
[80]	validation_0-mae:4879.46652
[81]	validation_0-mae:4866.47928
[82]	validation_0-mae:4855.92475
[83]	validation_0-mae:4851.68625
[84]	validation_0-mae:4846.23635
[85]	validation_0-mae:4840.25446
[86]	validation_0-mae:4825.89552
[87]	validation_0-mae:4817.70995
[88]	validation_0-mae:4808.70524
[89]	validation_0-mae:4798.57131
[90]	validation_0-mae:4787.68756
[91]	validation_0-mae:4777.23795
[92]	validation_0-mae:4772.43304
[93]	validation_0-mae:4763.45624
[94]	validation_0-mae:4756.42395
[95]	validation_0-mae:4751.73883
[96]	validation_0-mae:4746.52794
[97]	validation_0-mae:4741.54525
[98]	validation_0-mae:4738.04801
[99]	validation_0-mae:4732.11295
[100]	validation_0-mae:4725.34897
[101]	validation_0-mae:4711.28152
[102]	validation_0-mae:4707.48228
[103]	validation_0-mae:4701.43564
[104]	validation_0-mae:4697.15615
[105]	validation_0-mae:4698.21237
[106]	validation_0-mae:4689.55425
[107]	validation_0-mae:4686.23134
[108]	validation_0-mae:4681.84428
[109]	validation_0-mae:4672.07123
[110]	validation_0-mae:4670.58373
[111]	validation_0-mae:4666.80900
[112]	validation_0-mae:4664.16346
[113]	validation_0-mae:4660.76752
[114]	validation_0-mae:4659.22942
[115]	validation_0-mae:4654.93150
[116]	validation_0-mae:4652.62778
[117]	validation_0-mae:4648.72341
[118]	validation_0-mae:4644.98551
[119]	validation_0-mae:4642.41096
[120]	validation_0-mae:4639.56339
[121]	validation_0-mae:4638.42943
[122]	validation_0-mae:4636.91087
[123]	validation_0-mae:4636.50500
[124]	validation_0-mae:4637.84234
[125]	validation_0-mae:4636.00012
[126]	validation_0-mae:4631.72038
[127]	validation_0-mae:4630.32771
[128]	validation_0-mae:4628.07606
[129]	validation_0-mae:4625.73481
[130]	validation_0-mae:4624.51726
[131]	validation_0-mae:4623.10717
[132]	validation_0-mae:4621.43297
[133]	validation_0-mae:4619.61601
[134]	validation_0-mae:4616.49625
[135]	validation_0-mae:4610.70010
[136]	validation_0-mae:4607.39647
[137]	validation_0-mae:4605.67409
[138]	validation_0-mae:4605.29246
[139]	validation_0-mae:4602.03378
[140]	validation_0-mae:4601.24715
[141]	validation_0-mae:4599.74333
[142]	validation_0-mae:4598.83737
[143]	validation_0-mae:4596.68618
[144]	validation_0-mae:4596.28191
[145]	validation_0-mae:4591.67556
[146]	validation_0-mae:4590.03463
[147]	validation_0-mae:4587.61228
[148]	validation_0-mae:4588.82868
[149]	validation_0-mae:4589.58800
[150]	validation_0-mae:4588.76780
[151]	validation_0-mae:4587.89344
[152]	validation_0-mae:4583.53435
[153]	validation_0-mae:4582.12125
[154]	validation_0-mae:4580.15012
[155]	validation_0-mae:4577.25774
[156]	validation_0-mae:4575.68896
[157]	validation_0-mae:4574.08790
[158]	validation_0-mae:4575.47864
[159]	validation_0-mae:4578.68563
[160]	validation_0-mae:4578.51912
[161]	validation_0-mae:4577.03834
[162]	validation_0-mae:4577.26751
[163]	validation_0-mae:4578.58299
[164]	validation_0-mae:4577.41231
[165]	validation_0-mae:4576.62308
[166]	validation_0-mae:4572.99729
[167]	validation_0-mae:4570.95985
[168]	validation_0-mae:4571.70497
[169]	validation_0-mae:4569.52895
[170]	validation_0-mae:4569.69352
[171]	validation_0-mae:4567.02408
[172]	validation_0-mae:4566.19097
[0]	validation_0-mae:12374.85816
[1]	validation_0-mae:11591.83233
[2]	validation_0-mae:10907.68903
[3]	validation_0-mae:10298.39162
[4]	validation_0-mae:9776.99161
[5]	validation_0-mae:9315.08961
[6]	validation_0-mae:8918.06113
[7]	validation_0-mae:8575.59140
[8]	validation_0-mae:8254.74039
[9]	validation_0-mae:7955.57373
[10]	validation_0-mae:7695.79605
[11]	validation_0-mae:7451.96907

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[12]	validation_0-mae:7256.51367
[13]	validation_0-mae:7067.85043
[14]	validation_0-mae:6905.85947
[15]	validation_0-mae:6749.88288
[16]	validation_0-mae:6611.27573
[17]	validation_0-mae:6495.39128
[18]	validation_0-mae:6383.54912
[19]	validation_0-mae:6282.03722
[20]	validation_0-mae:6172.16208
[21]	validation_0-mae:6089.43632
[22]	validation_0-mae:5975.64346
[23]	validation_0-mae:5876.35595
[24]	validation_0-mae:5789.64180
[25]	validation_0-mae:5701.33159
[26]	validation_0-mae:5626.98871
[27]	validation_0-mae:5527.98082
[28]	validation_0-mae:5442.49772
[29]	validation_0-mae:5348.72614
[30]	validation_0-mae:5293.84142
[31]	validation_0-mae:5213.38111
[32]	validation_0-mae:5095.50844
[33]	validation_0-mae:5046.68474
[34]	validation_0-mae:4995.01512
[35]	validation_0-mae:4929.21149
[36]	validation_0-mae:4876.51326
[37]	validation_0-mae:4818.75459
[38]	validation_0-mae:4731.71983
[39]	validation_0-mae:4676.37541
[40]	validation_0-mae:4634.73383
[41]	validation_0-mae:4593.16848
[42]	validation_0-mae:4529.30577
[43]	validation_0-mae:4458.51143
[44]	validation_0-mae:4416.38010
[45]	validation_0-mae:4379.05053
[46]	validation_0-mae:4313.43638
[47]	validation_0-mae:4272.95526
[48]	validation_0-mae:4243.13140
[49]	validation_0-mae:4215.46521
[50]	validation_0-mae:4186.67306
[51]	validation_0-mae:4137.77389
[52]	validation_0-mae:4113.24769
[53]	validation_0-mae:4090.71266
[54]	validation_0-mae:4041.71589
[55]	validation_0-mae:4014.08074
[56]	validation_0-mae:3984.76327
[57]	validation_0-mae:3968.74027
[58]	validation_0-mae:3922.94380
[59]	validation_0-mae:3885.92703
[60]	validation_0-mae:3873.97298
[61]	validation_0-mae:3858.52619
[62]	validation_0-mae:3828.50578
[63]	validation_0-mae:3807.20454
[64]	validation_0-mae:3787.90112
[65]	validation_0-mae:3768.77471
[66]	validation_0-mae:3751.88157
[67]	validation_0-mae:3731.82626
[68]	validation_0-mae:3719.24518
[69]	validation_0-mae:3698.52837
[70]	validation_0-mae:3680.51231
[71]	validation_0-mae:3667.64008
[72]	validation_0-mae:3654.65203
[73]	validation_0-mae:3643.54727
[74]	validation_0-mae:3632.78072
[75]	validation_0-mae:3613.66936
[76]	validation_0-mae:3595.02353
[77]	validation_0-mae:3583.23387
[78]	validation_0-mae:3569.55213
[79]	validation_0-mae:3554.82198
[80]	validation_0-mae:3552.03846
[81]	validation_0-mae:3542.43509
[82]	validation_0-mae:3529.90660
[83]	validation_0-mae:3525.25509
[84]	validation_0-mae:3512.24659
[85]	validation_0-mae:3506.45520
[86]	validation_0-mae:3499.24926
[87]	validation_0-mae:3485.69808
[88]	validation_0-mae:3475.91708
[89]	validation_0-mae:3470.40366
[90]	validation_0-mae:3461.09686
[91]	validation_0-mae:3454.66525
[92]	validation_0-mae:3448.35188
[93]	validation_0-mae:3441.32160
[94]	validation_0-mae:3435.11429
[95]	validation_0-mae:3427.76098
[96]	validation_0-mae:3424.56795
[97]	validation_0-mae:3416.81853
[98]	validation_0-mae:3411.29313
[99]	validation_0-mae:3402.90621
[100]	validation_0-mae:3397.93786
[101]	validation_0-mae:3382.41555
[102]	validation_0-mae:3376.15327
[103]	validation_0-mae:3363.65460
[104]	validation_0-mae:3359.07608
[105]	validation_0-mae:3347.37689
[106]	validation_0-mae:3339.98686
[107]	validation_0-mae:3332.65567
[108]	validation_0-mae:3323.76736
[109]	validation_0-mae:3317.85662
[110]	validation_0-mae:3313.56196
[111]	validation_0-mae:3305.21991
[112]	validation_0-mae:3301.16778
[113]	validation_0-mae:3296.78240
[114]	validation_0-mae:3292.71192
[115]	validation_0-mae:3285.51975
[116]	validation_0-mae:3280.07533
[117]	validation_0-mae:3278.23237
[118]	validation_0-mae:3274.28323
[119]	validation_0-mae:3272.23095
[120]	validation_0-mae:3268.98978
[121]	validation_0-mae:3267.06511
[122]	validation_0-mae:3264.87803
[123]	validation_0-mae:3262.06603
[124]	validation_0-mae:3258.96853
[125]	validation_0-mae:3255.53056
[126]	validation_0-mae:3253.54308
[127]	validation_0-mae:3251.05414
[128]	validation_0-mae:3248.41468
[129]	validation_0-mae:3246.54602
[130]	validation_0-mae:3244.49565
[131]	validation_0-mae:3243.25233
[132]	validation_0-mae:3240.31765
[133]	validation_0-mae:3239.88478
[134]	validation_0-mae:3235.89392
[135]	validation_0-mae:3233.75128
[136]	validation_0-mae:3229.20409
[137]	validation_0-mae:3227.43883
[138]	validation_0-mae:3225.88068
[139]	validation_0-mae:3223.43457
[140]	validation_0-mae:3222.87954
[141]	validation_0-mae:3219.16393
[142]	validation_0-mae:3214.67349
[143]	validation_0-mae:3214.02143
[144]	validation_0-mae:3210.85600
[145]	validation_0-mae:3207.10605
[146]	validation_0-mae:3205.37541
[147]	validation_0-mae:3203.70779
[148]	validation_0-mae:3202.20082
[149]	validation_0-mae:3199.99544
[150]	validation_0-mae:3197.74633
[151]	validation_0-mae:3195.33516
[152]	validation_0-mae:3191.77782
[153]	validation_0-mae:3190.85185
[154]	validation_0-mae:3187.82364
[155]	validation_0-mae:3185.29255
[156]	validation_0-mae:3181.59213
[157]	validation_0-mae:3179.47952
[158]	validation_0-mae:3177.63666
[159]	validation_0-mae:3177.48524
[160]	validation_0-mae:3174.90213
[161]	validation_0-mae:3174.68609
[162]	validation_0-mae:3174.77334
[163]	validation_0-mae:3172.82977
[164]	validation_0-mae:3172.30043
[165]	validation_0-mae:3171.41201
[166]	validation_0-mae:3170.01921
[167]	validation_0-mae:3170.48170
[168]	validation_0-mae:3167.48085
[169]	validation_0-mae:3165.85668
[170]	validation_0-mae:3162.17395
[171]	validation_0-mae:3160.47921
[172]	validation_0-mae:3159.51561
[173]	validation_0-mae:3160.86384
[174]	validation_0-mae:3158.36954
[175]	validation_0-mae:3157.29982
[176]	validation_0-mae:3156.44346
[177]	validation_0-mae:3155.93147
[178]	validation_0-mae:3153.48383
[179]	validation_0-mae:3152.91991
[180]	validation_0-mae:3153.16892
[181]	validation_0-mae:3152.30585
[182]	validation_0-mae:3151.11917
[183]	validation_0-mae:3150.30523
[184]	validation_0-mae:3146.23097
[185]	validation_0-mae:3143.83909
[186]	validation_0-mae:3143.71084
[187]	validation_0-mae:3143.23992
[188]	validation_0-mae:3142.09978
[189]	validation_0-mae:3139.91869
[190]	validation_0-mae:3139.10063
[191]	validation_0-mae:3139.02417
[192]	validation_0-mae:3137.96699
[193]	validation_0-mae:3137.13158
[194]	validation_0-mae:3135.27270
[195]	validation_0-mae:3134.36999
[196]	validation_0-mae:3133.99526
[197]	validation_0-mae:3131.66451
[198]	validation_0-mae:3130.39742
[199]	validation_0-mae:3130.44087
[200]	validation_0-mae:3130.37127
[201]	validation_0-mae:3129.25385
[202]	validation_0-mae:3129.48137
[203]	validation_0-mae:3128.89448
[204]	validation_0-mae:3127.04573
[205]	validation_0-mae:3125.20070
[206]	validation_0-mae:3124.11377
[207]	validation_0-mae:3123.41506
[208]	validation_0-mae:3123.52985
[209]	validation_0-mae:3122.43052
[210]	validation_0-mae:3122.73680
[211]	validation_0-mae:3121.74756
[212]	validation_0-mae:3122.08069
[213]	validation_0-mae:3122.07395
[214]	validation_0-mae:3120.90070
[215]	validation_0-mae:3118.77854
[216]	validation_0-mae:3118.32746
[217]	validation_0-mae:3117.38091
[218]	validation_0-mae:3117.04629
[219]	validation_0-mae:3116.57244
[220]	validation_0-mae:3115.19005
[221]	validation_0-mae:3115.11152
[222]	validation_0-mae:3113.39458
[223]	validation_0-mae:3113.50765
[224]	validation_0-mae:3113.96141
[225]	validation_0-mae:3112.66786
[226]	validation_0-mae:3111.47248
[227]	validation_0-mae:3110.86075
[228]	validation_0-mae:3110.39074
[229]	validation_0-mae:3110.21526
[230]	validation_0-mae:3110.00420
[231]	validation_0-mae:3108.45971
[232]	validation_0-mae:3108.65017
[233]	validation_0-mae:3107.50513
[234]	validation_0-mae:3106.49165
[235]	validation_0-mae:3104.09425
[236]	validation_0-mae:3103.30057
[237]	validation_0-mae:3102.91960
[238]	validation_0-mae:3102.67887
[239]	validation_0-mae:3101.24792
[240]	validation_0-mae:3100.86715
[241]	validation_0-mae:3099.85971
[242]	validation_0-mae:3098.60114
[243]	validation_0-mae:3097.15629
[244]	validation_0-mae:3095.81070
[245]	validation_0-mae:3094.46190
[246]	validation_0-mae:3093.96781
[247]	validation_0-mae:3092.53526
[248]	validation_0-mae:3093.05700
[249]	validation_0-mae:3092.12949
[250]	validation_0-mae:3092.02294
[251]	validation_0-mae:3090.02605
[252]	validation_0-mae:3088.76454
[253]	validation_0-mae:3088.20327
[254]	validation_0-mae:3086.95321
[255]	validation_0-mae:3087.47052
[256]	validation_0-mae:3087.22060
[257]	validation_0-mae:3086.54378
[258]	validation_0-mae:3085.63183
[259]	validation_0-mae:3085.35958
[260]	validation_0-mae:3085.37187
[261]	validation_0-mae:3086.27588
[262]	validation_0-mae:3084.37160
[263]	validation_0-mae:3084.39263
[264]	validation_0-mae:3084.78353
[265]	validation_0-mae:3084.95276
[266]	validation_0-mae:3085.55937
[267]	validation_0-mae:3085.12128
[268]	validation_0-mae:3085.63913
[269]	validation_0-mae:3086.09819
[270]	validation_0-mae:3086.25915
[271]	validation_0-mae:3087.65387
[272]	validation_0-mae:3088.04976
[273]	validation_0-mae:3087.29081
[274]	validation_0-mae:3086.05016
[275]	validation_0-mae:3086.47481
[276]	validation_0-mae:3085.71793
[277]	validation_0-mae:3084.78588
[278]	validation_0-mae:3084.41685
[279]	validation_0-mae:3085.58817
[280]	validation_0-mae:3084.65500
[281]	validation_0-mae:3083.79231
[282]	validation_0-mae:3082.11202
[283]	validation_0-mae:3081.57999
[284]	validation_0-mae:3081.52304
[285]	validation_0-mae:3081.35740
[286]	validation_0-mae:3083.60903
[287]	validation_0-mae:3085.03504
[288]	validation_0-mae:3084.40475
[289]	validation_0-mae:3085.39013
[290]	validation_0-mae:3084.92641
[291]	validation_0-mae:3084.11034
[292]	validation_0-mae:3084.31783
[293]	validation_0-mae:3083.42462
[294]	validation_0-mae:3083.72285
[295]	validation_0-mae:3082.74302
[296]	validation_0-mae:3082.67653
[297]	validation_0-mae:3082.46004
[298]	validation_0-mae:3082.31897
[299]	validation_0-mae:3081.40874
[300]	validation_0-mae:3081.56715
[301]	validation_0-mae:3082.14211
[302]	validation_0-mae:3082.60541
[303]	validation_0-mae:3083.44004
[304]	validation_0-mae:3083.41665
[305]	validation_0-mae:3084.05032
[306]	validation_0-mae:3083.37364
[307]	validation_0-mae:3083.32409
[308]	validation_0-mae:3083.19797
[309]	validation_0-mae:3082.92592
[310]	validation_0-mae:3083.26694
[311]	validation_0-mae:3083.05295
[312]	validation_0-mae:3083.72920
[313]	validation_0-mae:3084.33806
[314]	validation_0-mae:3082.78403
[315]	validation_0-mae:3082.36216
[316]	validation_0-mae:3082.16133
[317]	validation_0-mae:3081.56392
[318]	validation_0-mae:3081.49907
[319]	validation_0-mae:3081.98944
[320]	validation_0-mae:3082.27402
[321]	validation_0-mae:3081.82507
[322]	validation_0-mae:3081.33086
[323]	validation_0-mae:3082.75851
[324]	validation_0-mae:3082.77297
[325]	validation_0-mae:3081.31797
[326]	validation_0-mae:3080.04215
[327]	validation_0-mae:3078.64559
[328]	validation_0-mae:3077.10590
[329]	validation_0-mae:3076.75692
[330]	validation_0-mae:3076.71243
[331]	validation_0-mae:3076.09985
[332]	validation_0-mae:3075.92928
[333]	validation_0-mae:3075.77774
[334]	validation_0-mae:3075.69901
[335]	validation_0-mae:3075.65132
[336]	validation_0-mae:3075.70639
[337]	validation_0-mae:3075.83227
[338]	validation_0-mae:3075.69051
[339]	validation_0-mae:3074.80875
[340]	validation_0-mae:3074.90027
[341]	validation_0-mae:3076.21655
[342]	validation_0-mae:3075.49885
[343]	validation_0-mae:3074.52265
[344]	validation_0-mae:3075.40898
[345]	validation_0-mae:3075.61450
[346]	validation_0-mae:3076.05014
[347]	validation_0-mae:3076.14945
[348]	validation_0-mae:3075.30036
[349]	validation_0-mae:3074.92830
[350]	validation_0-mae:3074.87120
[351]	validation_0-mae:3075.56913
[352]	validation_0-mae:3075.62436
[353]	validation_0-mae:3075.65699
[354]	validation_0-mae:3075.60636
[355]	validation_0-mae:3075.36491
[356]	validation_0-mae:3075.61084
[357]	validation_0-mae:3075.86469
[358]	validation_0-mae:3074.65175
[359]	validation_0-mae:3074.16909
[360]	validation_0-mae:3074.37867
[361]	validation_0-mae:3073.99278
[362]	validation_0-mae:3073.70043
[363]	validation_0-mae:3073.55999
[364]	validation_0-mae:3073.65721
[365]	validation_0-mae:3073.64783
[366]	validation_0-mae:3072.21089
[367]	validation_0-mae:3072.54889
[368]	validation_0-mae:3071.97380
[369]	validation_0-mae:3072.23794
[370]	validation_0-mae:3071.30490
[371]	validation_0-mae:3071.26216
[372]	validation_0-mae:3071.16150
[373]	validation_0-mae:3070.94107
[374]	validation_0-mae:3070.86584
[375]	validation_0-mae:3069.84106
[376]	validation_0-mae:3070.28425
[377]	validation_0-mae:3071.14515
[378]	validation_0-mae:3071.24015
[379]	validation_0-mae:3071.94446
[380]	validation_0-mae:3070.92504
[381]	validation_0-mae:3070.86720
[382]	validation_0-mae:3070.69290
[383]	validation_0-mae:3069.92195
[384]	validation_0-mae:3069.72449
[385]	validation_0-mae:3069.50151
[386]	validation_0-mae:3069.38646
[387]	validation_0-mae:3069.48205
[388]	validation_0-mae:3068.97427
[389]	validation_0-mae:3068.51690
[390]	validation_0-mae:3069.10830
[391]	validation_0-mae:3068.24747
[392]	validation_0-mae:3068.96405
[393]	validation_0-mae:3069.59893
[394]	validation_0-mae:3069.48977
[395]	validation_0-mae:3069.20745
[396]	validation_0-mae:3069.65435
[397]	validation_0-mae:3070.49476
[398]	validation_0-mae:3070.19017
[399]	validation_0-mae:3070.25947
[400]	validation_0-mae:3069.80985
[401]	validation_0-mae:3069.87260
[402]	validation_0-mae:3070.25776
[403]	validation_0-mae:3069.86533
[404]	validation_0-mae:3068.89964
[405]	validation_0-mae:3068.36153
[406]	validation_0-mae:3067.90909
[407]	validation_0-mae:3067.78155
[408]	validation_0-mae:3067.41779
[409]	validation_0-mae:3066.53337
[410]	validation_0-mae:3066.53863
[411]	validation_0-mae:3067.22625
[412]	validation_0-mae:3066.94991
[413]	validation_0-mae:3068.06387
[414]	validation_0-mae:3068.27522
[415]	validation_0-mae:3067.87337
[416]	validation_0-mae:3067.12039
[417]	validation_0-mae:3067.56317
[418]	validation_0-mae:3068.16900
[419]	validation_0-mae:3067.51663
[420]	validation_0-mae:3067.71035
[421]	validation_0-mae:3067.32456
[422]	validation_0-mae:3066.42927
[423]	validation_0-mae:3066.81544
[424]	validation_0-mae:3066.41124
[425]	validation_0-mae:3065.95398
[426]	validation_0-mae:3065.60808
[427]	validation_0-mae:3066.38996
[428]	validation_0-mae:3066.92852
[429]	validation_0-mae:3066.45149
[430]	validation_0-mae:3065.88178
[431]	validation_0-mae:3064.42285
[432]	validation_0-mae:3063.99899
[433]	validation_0-mae:3064.52418
[434]	validation_0-mae:3064.10374
[435]	validation_0-mae:3064.03377
[436]	validation_0-mae:3063.63520
[437]	validation_0-mae:3064.04175
[438]	validation_0-mae:3063.76485
[439]	validation_0-mae:3063.86511
[440]	validation_0-mae:3064.03198
[441]	validation_0-mae:3063.60014
[442]	validation_0-mae:3064.01475
[443]	validation_0-mae:3063.99850
[444]	validation_0-mae:3063.95795
[445]	validation_0-mae:3064.71813
[446]	validation_0-mae:3066.13902
[447]	validation_0-mae:3066.03329
[448]	validation_0-mae:3066.64366
[449]	validation_0-mae:3066.24667
[450]	validation_0-mae:3066.75496
[451]	validation_0-mae:3066.56808
[452]	validation_0-mae:3067.04101
[453]	validation_0-mae:3066.07700
[454]	validation_0-mae:3066.16323
[455]	validation_0-mae:3065.72439
[456]	validation_0-mae:3065.58642
[457]	validation_0-mae:3065.65546
[458]	validation_0-mae:3064.89361
[459]	validation_0-mae:3064.79123
[460]	validation_0-mae:3065.30504
[461]	validation_0-mae:3064.85108
[462]	validation_0-mae:3064.48423
[463]	validation_0-mae:3064.63567
[464]	validation_0-mae:3065.18367
[465]	validation_0-mae:3064.97664
[466]	validation_0-mae:3064.35214
[467]	validation_0-mae:3064.19102
[468]	validation_0-mae:3064.15473
[469]	validation_0-mae:3064.62736
[470]	validation_0-mae:3064.63959
[471]	validation_0-mae:3064.28415
[472]	validation_0-mae:3064.44883
[473]	validation_0-mae:3063.81644
[474]	validation_0-mae:3064.05724
[475]	validation_0-mae:3064.16684
[476]	validation_0-mae:3064.31792
[477]	validation_0-mae:3064.06359
[478]	validation_0-mae:3063.69628
[479]	validation_0-mae:3063.54405
[480]	validation_0-mae:3063.72997
[481]	validation_0-mae:3063.44351
[482]	validation_0-mae:3063.58485
[483]	validation_0-mae:3063.61298
[484]	validation_0-mae:3062.29432
[485]	validation_0-mae:3061.43944
[486]	validation_0-mae:3061.54102
[487]	validation_0-mae:3061.55060
[488]	validation_0-mae:3061.43137
[489]	validation_0-mae:3061.98893
[490]	validation_0-mae:3062.13435
[491]	validation_0-mae:3062.44208
[492]	validation_0-mae:3063.27511
[493]	validation_0-mae:3063.37920
[494]	validation_0-mae:3063.76815
[495]	validation_0-mae:3063.82898
[496]	validation_0-mae:3063.46778
[497]	validation_0-mae:3063.73967
[498]	validation_0-mae:3064.03437
[499]	validation_0-mae:3064.59068
[500]	validation_0-mae:3064.70932
[501]	validation_0-mae:3065.08910
[502]	validation_0-mae:3064.58288
[503]	validation_0-mae:3064.33288
[504]	validation_0-mae:3064.63763
[505]	validation_0-mae:3064.69512
[506]	validation_0-mae:3064.01639
[507]	validation_0-mae:3064.76144
[508]	validation_0-mae:3063.82925
[509]	validation_0-mae:3063.91459
[510]	validation_0-mae:3064.15348
[511]	validation_0-mae:3063.45299
[512]	validation_0-mae:3063.39376
[513]	validation_0-mae:3063.33190
[514]	validation_0-mae:3063.58788
[515]	validation_0-mae:3063.58824
[516]	validation_0-mae:3063.80482
[517]	validation_0-mae:3063.39888
[518]	validation_0-mae:3063.27348
[519]	validation_0-mae:3063.58644
[520]	validation_0-mae:3063.77841
[521]	validation_0-mae:3063.45170
[522]	validation_0-mae:3063.06408
[523]	validation_0-mae:3062.98219
[524]	validation_0-mae:3062.61201
[525]	validation_0-mae:3062.20381
[526]	validation_0-mae:3062.58519
[527]	validation_0-mae:3061.65135
[528]	validation_0-mae:3061.66039
[529]	validation_0-mae:3061.83179
[530]	validation_0-mae:3061.62990
[531]	validation_0-mae:3061.98456
[532]	validation_0-mae:3061.55619
[533]	validation_0-mae:3060.86274
[534]	validation_0-mae:3061.32638
[535]	validation_0-mae:3061.05371
[536]	validation_0-mae:3060.83426
[537]	validation_0-mae:3060.74627
[538]	validation_0-mae:3060.53402
[539]	validation_0-mae:3060.24011
[540]	validation_0-mae:3059.94719
[541]	validation_0-mae:3059.81413
[542]	validation_0-mae:3060.01001
[543]	validation_0-mae:3059.83516
[544]	validation_0-mae:3059.64388
[545]	validation_0-mae:3059.69670
[546]	validation_0-mae:3059.89809
[547]	validation_0-mae:3060.89429
[548]	validation_0-mae:3060.98883
[549]	validation_0-mae:3060.78937
[550]	validation_0-mae:3060.43888
[551]	validation_0-mae:3060.48470
[552]	validation_0-mae:3060.09406
[553]	validation_0-mae:3059.76392
[554]	validation_0-mae:3059.62819
[555]	validation_0-mae:3060.83475
[556]	validation_0-mae:3060.40609
[557]	validation_0-mae:3059.98709
[558]	validation_0-mae:3059.43435
[559]	validation_0-mae:3060.04265
[560]	validation_0-mae:3059.68065
[561]	validation_0-mae:3060.06302
[562]	validation_0-mae:3060.58871
[563]	validation_0-mae:3060.58544
[564]	validation_0-mae:3060.41934
[565]	validation_0-mae:3060.27102
[566]	validation_0-mae:3060.25948
[567]	validation_0-mae:3060.09139
[568]	validation_0-mae:3059.85599
[569]	validation_0-mae:3060.53317
[570]	validation_0-mae:3060.85226
[571]	validation_0-mae:3060.94966
[572]	validation_0-mae:3061.35667
[573]	validation_0-mae:3060.99447
[574]	validation_0-mae:3061.33414
[575]	validation_0-mae:3061.54123
[576]	validation_0-mae:3061.42158
[577]	validation_0-mae:3061.47986
[578]	validation_0-mae:3061.33159
[579]	validation_0-mae:3061.72317
[580]	validation_0-mae:3061.89854
[581]	validation_0-mae:3062.18392
[582]	validation_0-mae:3062.21629
[583]	validation_0-mae:3062.44689
[584]	validation_0-mae:3062.35244
[585]	validation_0-mae:3062.06003
[586]	validation_0-mae:3062.02408
[587]	validation_0-mae:3062.35569
[588]	validation_0-mae:3062.21382
[589]	validation_0-mae:3061.90604
[590]	validation_0-mae:3062.20168
[591]	validation_0-mae:3062.62350
[592]	validation_0-mae:3062.70056
[593]	validation_0-mae:3062.73891
[594]	validation_0-mae:3062.84376
[595]	validation_0-mae:3062.78207
[596]	validation_0-mae:3063.55225
[597]	validation_0-mae:3063.88895
[598]	validation_0-mae:3064.51467
[599]	validation_0-mae:3065.07704
[600]	validation_0-mae:3065.02385
[601]	validation_0-mae:3064.93142

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[0]	validation_0-mae:12544.22193
[1]	validation_0-mae:11891.64668
[2]	validation_0-mae:11310.95820
[3]	validation_0-mae:10759.94329
[4]	validation_0-mae:10270.05395
[5]	validation_0-mae:9818.97453
[6]	validation_0-mae:9421.72120
[7]	validation_0-mae:9046.95163
[8]	validation_0-mae:8681.38641
[9]	validation_0-mae:8360.80058
[10]	validation_0-mae:8067.64071
[11]	validation_0-mae:7781.71205

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[12]	validation_0-mae:7516.52753
[13]	validation_0-mae:7256.15138
[14]	validation_0-mae:7036.98430
[15]	validation_0-mae:6808.93410
[16]	validation_0-mae:6595.76557
[17]	validation_0-mae:6401.98496
[18]	validation_0-mae:6227.08126
[19]	validation_0-mae:6055.18035
[20]	validation_0-mae:5862.10325
[21]	validation_0-mae:5720.52489
[22]	validation_0-mae:5569.99204
[23]	validation_0-mae:5420.13011
[24]	validation_0-mae:5273.22039
[25]	validation_0-mae:5143.08748
[26]	validation_0-mae:5037.55435
[27]	validation_0-mae:4925.74650
[28]	validation_0-mae:4819.41724
[29]	validation_0-mae:4720.46470
[30]	validation_0-mae:4610.23914
[31]	validation_0-mae:4515.31270
[32]	validation_0-mae:4442.92759
[33]	validation_0-mae:4345.47103
[34]	validation_0-mae:4273.93392
[35]	validation_0-mae:4214.83307
[36]	validation_0-mae:4139.43779
[37]	validation_0-mae:4051.33247
[38]	validation_0-mae:3994.37783
[39]	validation_0-mae:3930.45739
[40]	validation_0-mae:3883.68322
[41]	validation_0-mae:3827.17144
[42]	validation_0-mae:3769.89622
[43]	validation_0-mae:3718.06030
[44]	validation_0-mae:3677.10689
[45]	validation_0-mae:3631.56094
[46]	validation_0-mae:3575.95014
[47]	validation_0-mae:3540.11407
[48]	validation_0-mae:3499.07490
[49]	validation_0-mae:3462.92735
[50]	validation_0-mae:3427.78442
[51]	validation_0-mae:3396.21268
[52]	validation_0-mae:3366.81751
[53]	validation_0-mae:3338.29489
[54]	validation_0-mae:3305.77487
[55]	validation_0-mae:3270.58282
[56]	validation_0-mae:3239.73648
[57]	validation_0-mae:3216.71865
[58]	validation_0-mae:3189.43513
[59]	validation_0-mae:3168.13749
[60]	validation_0-mae:3142.56920
[61]	validation_0-mae:3124.07531
[62]	validation_0-mae:3105.96713
[63]	validation_0-mae:3088.77561
[64]	validation_0-mae:3061.35492
[65]	validation_0-mae:3027.49587
[66]	validation_0-mae:3008.16148
[67]	validation_0-mae:2995.47097
[68]	validation_0-mae:2985.91585
[69]	validation_0-mae:2969.29124
[70]	validation_0-mae:2957.44137
[71]	validation_0-mae:2947.90340
[72]	validation_0-mae:2935.90539
[73]	validation_0-mae:2926.99954
[74]	validation_0-mae:2913.97454
[75]	validation_0-mae:2887.76344
[76]	validation_0-mae:2862.04829
[77]	validation_0-mae:2846.51081
[78]	validation_0-mae:2835.40331
[79]	validation_0-mae:2824.40321
[80]	validation_0-mae:2815.50997
[81]	validation_0-mae:2801.54980
[82]	validation_0-mae:2785.93369
[83]	validation_0-mae:2775.79375
[84]	validation_0-mae:2763.45813
[85]	validation_0-mae:2755.03394
[86]	validation_0-mae:2745.99625
[87]	validation_0-mae:2741.49500
[88]	validation_0-mae:2729.40215
[89]	validation_0-mae:2715.29309
[90]	validation_0-mae:2699.73767
[91]	validation_0-mae:2693.98884
[92]	validation_0-mae:2684.19278
[93]	validation_0-mae:2669.50062
[94]	validation_0-mae:2662.70034
[95]	validation_0-mae:2656.45039
[96]	validation_0-mae:2639.16402
[97]	validation_0-mae:2627.14706
[98]	validation_0-mae:2614.28136
[99]	validation_0-mae:2610.27656
[100]	validation_0-mae:2600.61299
[101]	validation_0-mae:2593.17442
[102]	validation_0-mae:2591.57593
[103]	validation_0-mae:2579.42334
[104]	validation_0-mae:2574.69137
[105]	validation_0-mae:2568.66323
[106]	validation_0-mae:2559.31687
[107]	validation_0-mae:2553.67047
[108]	validation_0-mae:2550.67779
[109]	validation_0-mae:2544.88768
[110]	validation_0-mae:2540.83490
[111]	validation_0-mae:2536.48212
[112]	validation_0-mae:2531.12190
[113]	validation_0-mae:2524.86599
[114]	validation_0-mae:2511.78085
[115]	validation_0-mae:2502.01444
[116]	validation_0-mae:2496.47728
[117]	validation_0-mae:2486.94272
[118]	validation_0-mae:2479.38669
[119]	validation_0-mae:2475.18709
[120]	validation_0-mae:2462.83614
[121]	validation_0-mae:2453.21764
[122]	validation_0-mae:2447.00155
[123]	validation_0-mae:2437.46908
[124]	validation_0-mae:2435.11172
[125]	validation_0-mae:2432.68833
[126]	validation_0-mae:2423.99286
[127]	validation_0-mae:2420.74801
[128]	validation_0-mae:2418.48660
[129]	validation_0-mae:2417.30352
[130]	validation_0-mae:2413.01711
[131]	validation_0-mae:2411.13744
[132]	validation_0-mae:2408.79349
[133]	validation_0-mae:2405.27980
[134]	validation_0-mae:2398.96907
[135]	validation_0-mae:2392.85464
[136]	validation_0-mae:2387.34619
[137]	validation_0-mae:2384.34351
[138]	validation_0-mae:2376.15073
[139]	validation_0-mae:2372.21286
[140]	validation_0-mae:2367.66326
[141]	validation_0-mae:2363.30424
[142]	validation_0-mae:2358.45821
[143]	validation_0-mae:2355.09915
[144]	validation_0-mae:2350.16316
[145]	validation_0-mae:2350.53226
[146]	validation_0-mae:2345.24143
[147]	validation_0-mae:2341.58171
[148]	validation_0-mae:2338.12803
[149]	validation_0-mae:2335.90213
[150]	validation_0-mae:2334.26908
[151]	validation_0-mae:2332.59729
[152]	validation_0-mae:2331.13884
[153]	validation_0-mae:2329.55594
[154]	validation_0-mae:2326.93110
[155]	validation_0-mae:2323.84524
[156]	validation_0-mae:2321.35041
[157]	validation_0-mae:2317.98126
[158]	validation_0-mae:2312.76471
[159]	validation_0-mae:2309.25407
[160]	validation_0-mae:2306.36156
[161]	validation_0-mae:2305.35037
[162]	validation_0-mae:2301.82020
[163]	validation_0-mae:2300.65496
[164]	validation_0-mae:2297.95326
[165]	validation_0-mae:2298.10963
[166]	validation_0-mae:2293.31429
[167]	validation_0-mae:2291.67415
[168]	validation_0-mae:2292.22894
[169]	validation_0-mae:2290.01639
[170]	validation_0-mae:2290.41667
[171]	validation_0-mae:2287.63408
[172]	validation_0-mae:2285.23453
[173]	validation_0-mae:2283.77375
[174]	validation_0-mae:2281.08470
[175]	validation_0-mae:2280.70243
[176]	validation_0-mae:2277.50967
[177]	validation_0-mae:2277.29288
[178]	validation_0-mae:2274.42032
[179]	validation_0-mae:2272.44354
[180]	validation_0-mae:2268.16227
[181]	validation_0-mae:2265.56188
[182]	validation_0-mae:2264.24759
[183]	validation_0-mae:2262.65055
[184]	validation_0-mae:2262.28890
[185]	validation_0-mae:2262.58796
[186]	validation_0-mae:2261.42657
[187]	validation_0-mae:2260.92959
[188]	validation_0-mae:2260.24673
[189]	validation_0-mae:2259.85780
[190]	validation_0-mae:2255.44343
[191]	validation_0-mae:2254.73538
[192]	validation_0-mae:2252.68850
[193]	validation_0-mae:2254.52203
[194]	validation_0-mae:2253.06087
[195]	validation_0-mae:2250.68699
[196]	validation_0-mae:2248.94959
[197]	validation_0-mae:2247.84090
[198]	validation_0-mae:2248.29857
[199]	validation_0-mae:2245.69422
[200]	validation_0-mae:2244.95545
[201]	validation_0-mae:2241.91503
[202]	validation_0-mae:2240.30377
[203]	validation_0-mae:2238.90028
[204]	validation_0-mae:2238.04095
[205]	validation_0-mae:2235.38051
[206]	validation_0-mae:2234.41425
[207]	validation_0-mae:2233.35256
[208]	validation_0-mae:2233.00539
[209]	validation_0-mae:2232.05876
[210]	validation_0-mae:2232.01634
[211]	validation_0-mae:2231.25530
[212]	validation_0-mae:2228.88443
[213]	validation_0-mae:2228.90590
[214]	validation_0-mae:2227.40481
[215]	validation_0-mae:2226.50137
[216]	validation_0-mae:2226.89286
[217]	validation_0-mae:2226.96369
[218]	validation_0-mae:2225.10495
[219]	validation_0-mae:2224.76322
[220]	validation_0-mae:2224.48134
[221]	validation_0-mae:2223.08417
[222]	validation_0-mae:2220.58839
[223]	validation_0-mae:2219.90272
[224]	validation_0-mae:2218.97175
[225]	validation_0-mae:2217.73331
[226]	validation_0-mae:2216.89648
[227]	validation_0-mae:2215.37888
[228]	validation_0-mae:2214.68469
[229]	validation_0-mae:2213.56018
[230]	validation_0-mae:2215.01225
[231]	validation_0-mae:2212.28610
[232]	validation_0-mae:2212.60498
[233]	validation_0-mae:2212.07517
[234]	validation_0-mae:2212.50118
[235]	validation_0-mae:2212.51779
[236]	validation_0-mae:2210.21354
[237]	validation_0-mae:2210.50139
[238]	validation_0-mae:2210.34890
[239]	validation_0-mae:2210.97750
[240]	validation_0-mae:2210.16385
[241]	validation_0-mae:2209.60697
[242]	validation_0-mae:2209.34082
[243]	validation_0-mae:2208.76629
[244]	validation_0-mae:2209.44232
[245]	validation_0-mae:2209.66363
[246]	validation_0-mae:2209.45655
[247]	validation_0-mae:2209.38385
[248]	validation_0-mae:2208.41935
[249]	validation_0-mae:2207.96316
[250]	validation_0-mae:2207.37161
[251]	validation_0-mae:2206.37272
[252]	validation_0-mae:2206.29124
[253]	validation_0-mae:2207.07552
[254]	validation_0-mae:2207.31856
[255]	validation_0-mae:2205.91847
[256]	validation_0-mae:2205.83047
[257]	validation_0-mae:2206.26604
[258]	validation_0-mae:2205.26111
[259]	validation_0-mae:2204.01902
[260]	validation_0-mae:2204.88265
[261]	validation_0-mae:2204.50120
[262]	validation_0-mae:2202.55378
[263]	validation_0-mae:2201.43080
[264]	validation_0-mae:2201.66049
[265]	validation_0-mae:2200.98739
[266]	validation_0-mae:2201.19072
[267]	validation_0-mae:2201.96786
[268]	validation_0-mae:2200.97311
[269]	validation_0-mae:2201.95818
[270]	validation_0-mae:2201.83565
[271]	validation_0-mae:2200.51360
[272]	validation_0-mae:2201.73776
[273]	validation_0-mae:2201.85752
[274]	validation_0-mae:2199.65001
[275]	validation_0-mae:2199.64834
[276]	validation_0-mae:2200.19520
[277]	validation_0-mae:2198.98436
[278]	validation_0-mae:2198.95096
[279]	validation_0-mae:2197.58465
[280]	validation_0-mae:2197.44237
[281]	validation_0-mae:2197.94815
[282]	validation_0-mae:2196.26696
[283]	validation_0-mae:2196.45519
[284]	validation_0-mae:2196.62708
[285]	validation_0-mae:2195.12597
[286]	validation_0-mae:2194.78852
[287]	validation_0-mae:2195.26097
[288]	validation_0-mae:2196.11181
[289]	validation_0-mae:2195.43675
[290]	validation_0-mae:2193.71383
[291]	validation_0-mae:2192.59609
[292]	validation_0-mae:2192.67280
[293]	validation_0-mae:2192.47444
[294]	validation_0-mae:2193.17780
[295]	validation_0-mae:2192.95758
[296]	validation_0-mae:2193.26014
[297]	validation_0-mae:2192.23155
[298]	validation_0-mae:2192.48495
[299]	validation_0-mae:2191.55654
[300]	validation_0-mae:2192.54740
[301]	validation_0-mae:2192.84817
[302]	validation_0-mae:2192.84926
[303]	validation_0-mae:2191.37605
[304]	validation_0-mae:2191.99789
[305]	validation_0-mae:2192.12519
[306]	validation_0-mae:2193.40911
[307]	validation_0-mae:2192.83943
[308]	validation_0-mae:2192.19475
[309]	validation_0-mae:2191.65302
[310]	validation_0-mae:2190.62658
[311]	validation_0-mae:2190.06445
[312]	validation_0-mae:2189.30678
[313]	validation_0-mae:2190.32744
[314]	validation_0-mae:2190.91304
[315]	validation_0-mae:2191.14358
[316]	validation_0-mae:2191.35679
[317]	validation_0-mae:2191.75712
[318]	validation_0-mae:2191.28620
[319]	validation_0-mae:2191.68292
[320]	validation_0-mae:2189.92183
[321]	validation_0-mae:2190.30394
[322]	validation_0-mae:2189.73387
[323]	validation_0-mae:2189.44135
[324]	validation_0-mae:2189.41904
[325]	validation_0-mae:2189.39112
[326]	validation_0-mae:2189.74808
[327]	validation_0-mae:2189.85402
[328]	validation_0-mae:2189.78771
[329]	validation_0-mae:2188.94118
[330]	validation_0-mae:2187.79863
[331]	validation_0-mae:2187.73720
[332]	validation_0-mae:2185.13606
[333]	validation_0-mae:2185.23421
[334]	validation_0-mae:2184.72057
[335]	validation_0-mae:2184.02909
[336]	validation_0-mae:2183.80634
[337]	validation_0-mae:2183.72714
[338]	validation_0-mae:2183.34032
[339]	validation_0-mae:2183.39598
[340]	validation_0-mae:2182.77882
[341]	validation_0-mae:2182.59898
[342]	validation_0-mae:2181.37388
[343]	validation_0-mae:2180.81461
[344]	validation_0-mae:2181.02523
[345]	validation_0-mae:2181.11757
[346]	validation_0-mae:2181.88147
[347]	validation_0-mae:2181.86778
[348]	validation_0-mae:2181.58347
[349]	validation_0-mae:2180.02479
[350]	validation_0-mae:2179.87171
[351]	validation_0-mae:2180.07791
[352]	validation_0-mae:2179.63254
[353]	validation_0-mae:2178.42816
[354]	validation_0-mae:2178.14145
[355]	validation_0-mae:2178.25037
[356]	validation_0-mae:2176.81532
[357]	validation_0-mae:2176.02816
[358]	validation_0-mae:2175.71237
[359]	validation_0-mae:2175.31455
[360]	validation_0-mae:2174.72356
[361]	validation_0-mae:2175.34462
[362]	validation_0-mae:2174.04773
[363]	validation_0-mae:2174.05731
[364]	validation_0-mae:2171.93581
[365]	validation_0-mae:2170.79512
[366]	validation_0-mae:2169.74716
[367]	validation_0-mae:2170.09476
[368]	validation_0-mae:2170.35095
[369]	validation_0-mae:2170.31272
[370]	validation_0-mae:2169.66810
[371]	validation_0-mae:2169.30034
[372]	validation_0-mae:2169.41263
[373]	validation_0-mae:2169.00477
[374]	validation_0-mae:2168.76594
[375]	validation_0-mae:2169.03077
[376]	validation_0-mae:2169.20214
[377]	validation_0-mae:2169.68403
[378]	validation_0-mae:2169.32246
[379]	validation_0-mae:2168.87577
[380]	validation_0-mae:2168.48964
[381]	validation_0-mae:2168.32800
[382]	validation_0-mae:2168.35345
[383]	validation_0-mae:2168.84081
[384]	validation_0-mae:2168.28057
[385]	validation_0-mae:2167.15972
[386]	validation_0-mae:2166.73766
[387]	validation_0-mae:2166.78563
[388]	validation_0-mae:2164.80968
[389]	validation_0-mae:2165.14404
[390]	validation_0-mae:2163.94395
[391]	validation_0-mae:2163.60966
[392]	validation_0-mae:2163.16222
[393]	validation_0-mae:2163.46775
[394]	validation_0-mae:2163.52675
[395]	validation_0-mae:2163.71791
[396]	validation_0-mae:2161.83139
[397]	validation_0-mae:2161.69160
[398]	validation_0-mae:2159.06474
[399]	validation_0-mae:2159.64458
[400]	validation_0-mae:2159.00934
[401]	validation_0-mae:2157.89631
[402]	validation_0-mae:2158.15869
[403]	validation_0-mae:2158.27769
[404]	validation_0-mae:2158.50829
[405]	validation_0-mae:2156.41304
[406]	validation_0-mae:2156.35731
[407]	validation_0-mae:2155.33668
[408]	validation_0-mae:2155.66149
[409]	validation_0-mae:2155.58086
[410]	validation_0-mae:2156.14191
[411]	validation_0-mae:2155.72009
[412]	validation_0-mae:2155.05461
[413]	validation_0-mae:2155.46416
[414]	validation_0-mae:2155.55876
[415]	validation_0-mae:2154.67477
[416]	validation_0-mae:2154.93504
[417]	validation_0-mae:2154.74156
[418]	validation_0-mae:2154.85511
[419]	validation_0-mae:2154.05844
[420]	validation_0-mae:2153.68954
[421]	validation_0-mae:2152.74948
[422]	validation_0-mae:2152.59762
[423]	validation_0-mae:2153.14045
[424]	validation_0-mae:2151.94442
[425]	validation_0-mae:2151.76249
[426]	validation_0-mae:2151.45172
[427]	validation_0-mae:2151.00347
[428]	validation_0-mae:2150.59104
[429]	validation_0-mae:2150.79645
[430]	validation_0-mae:2148.97209
[431]	validation_0-mae:2149.02700
[432]	validation_0-mae:2148.37266
[433]	validation_0-mae:2148.16257
[434]	validation_0-mae:2147.52409
[435]	validation_0-mae:2147.31971
[436]	validation_0-mae:2147.46520
[437]	validation_0-mae:2147.85678
[438]	validation_0-mae:2148.41542
[439]	validation_0-mae:2147.27105
[440]	validation_0-mae:2147.17123
[441]	validation_0-mae:2147.54033
[442]	validation_0-mae:2147.11235
[443]	validation_0-mae:2146.21009
[444]	validation_0-mae:2144.71399
[445]	validation_0-mae:2144.25215
[446]	validation_0-mae:2144.34153
[447]	validation_0-mae:2143.18114
[448]	validation_0-mae:2143.15580
[449]	validation_0-mae:2143.28764
[450]	validation_0-mae:2143.39311
[451]	validation_0-mae:2142.50770
[452]	validation_0-mae:2142.06516
[453]	validation_0-mae:2140.92545
[454]	validation_0-mae:2139.77792
[455]	validation_0-mae:2139.71612
[456]	validation_0-mae:2139.62417
[457]	validation_0-mae:2140.40851
[458]	validation_0-mae:2140.60601
[459]	validation_0-mae:2140.08797
[460]	validation_0-mae:2140.29956
[461]	validation_0-mae:2139.42992
[462]	validation_0-mae:2139.40282
[463]	validation_0-mae:2139.75250
[464]	validation_0-mae:2138.60960
[465]	validation_0-mae:2138.41658
[466]	validation_0-mae:2138.04481
[467]	validation_0-mae:2138.21780
[468]	validation_0-mae:2138.58788
[469]	validation_0-mae:2138.52856
[470]	validation_0-mae:2137.55082
[471]	validation_0-mae:2137.10139
[472]	validation_0-mae:2136.47152
[473]	validation_0-mae:2135.58391
[474]	validation_0-mae:2134.42486
[475]	validation_0-mae:2133.75349
[476]	validation_0-mae:2133.06467
[477]	validation_0-mae:2133.39200
[478]	validation_0-mae:2133.42869
[479]	validation_0-mae:2132.48391
[480]	validation_0-mae:2132.29046
[481]	validation_0-mae:2132.16442
[482]	validation_0-mae:2131.74710
[483]	validation_0-mae:2130.28811
[484]	validation_0-mae:2130.54077
[485]	validation_0-mae:2130.57927
[486]	validation_0-mae:2129.89654
[487]	validation_0-mae:2129.92650
[488]	validation_0-mae:2129.81186
[489]	validation_0-mae:2130.17066
[490]	validation_0-mae:2130.58160
[491]	validation_0-mae:2131.26360
[492]	validation_0-mae:2131.47199
[493]	validation_0-mae:2131.41362
[494]	validation_0-mae:2132.04296
[495]	validation_0-mae:2131.90405
[496]	validation_0-mae:2132.96344
[497]	validation_0-mae:2133.12953
[498]	validation_0-mae:2133.16362
[499]	validation_0-mae:2133.49850
[500]	validation_0-mae:2134.53350
[501]	validation_0-mae:2134.79153
[502]	validation_0-mae:2134.92760
[503]	validation_0-mae:2134.31931
[504]	validation_0-mae:2134.52982
[505]	validation_0-mae:2134.42009
[506]	validation_0-mae:2134.24922
[507]	validation_0-mae:2134.30626
[508]	validation_0-mae:2133.62661
[509]	validation_0-mae:2133.57205
[510]	validation_0-mae:2133.80363
[511]	validation_0-mae:2133.55148
[512]	validation_0-mae:2133.45427
[513]	validation_0-mae:2133.45427
[514]	validation_0-mae:2133.33410
[515]	validation_0-mae:2133.18965
[516]	validation_0-mae:2133.04543
[517]	validation_0-mae:2133.08096
[518]	validation_0-mae:2131.77584
[519]	validation_0-mae:2131.95198
[520]	validation_0-mae:2131.91941
[521]	validation_0-mae:2131.27622
[522]	validation_0-mae:2131.34632
[523]	validation_0-mae:2131.28883
[524]	validation_0-mae:2131.05708
[525]	validation_0-mae:2131.33294
[526]	validation_0-mae:2131.56591
[527]	validation_0-mae:2131.76419
[528]	validation_0-mae:2132.09115
[529]	validation_0-mae:2131.81835
[530]	validation_0-mae:2131.75788
[531]	validation_0-mae:2131.64362
[532]	validation_0-mae:2131.79779
[533]	validation_0-mae:2132.09184
[534]	validation_0-mae:2131.83902
[535]	validation_0-mae:2131.74217
[536]	validation_0-mae:2131.59257
[537]	validation_0-mae:2132.23980
[538]	validation_0-mae:2132.36867
[539]	validation_0-mae:2132.69763
[540]	validation_0-mae:2132.51649
[541]	validation_0-mae:2132.57707
[542]	validation_0-mae:2132.55700
[543]	validation_0-mae:2132.93819
[544]	validation_0-mae:2131.79730
[545]	validation_0-mae:2132.04058
[546]	validation_0-mae:2132.30103
[547]	validation_0-mae:2132.00595
[548]	validation_0-mae:2131.64917
[549]	validation_0-mae:2131.83201
[550]	validation_0-mae:2131.81629
[551]	validation_0-mae:2131.75378
[552]	validation_0-mae:2132.03490
[553]	validation_0-mae:2132.73173
[554]	validation_0-mae:2132.89454
[555]	validation_0-mae:2133.45958
[556]	validation_0-mae:2133.86268
[557]	validation_0-mae:2133.96673
[558]	validation_0-mae:2133.78227
[559]	validation_0-mae:2133.16426
[560]	validation_0-mae:2133.03823
[561]	validation_0-mae:2133.21816
[562]	validation_0-mae:2134.01135
[563]	validation_0-mae:2133.54222
[564]	validation_0-mae:2133.77454
[565]	validation_0-mae:2133.79091
[566]	validation_0-mae:2133.64402
[567]	validation_0-mae:2133.62071
[568]	validation_0-mae:2134.32294
[569]	validation_0-mae:2134.33085
[570]	validation_0-mae:2134.40984
[571]	validation_0-mae:2134.81653
[572]	validation_0-mae:2134.92191
[573]	validation_0-mae:2134.44154
[574]	validation_0-mae:2134.73056
[575]	validation_0-mae:2134.63956
[576]	validation_0-mae:2134.86305
[577]	validation_0-mae:2134.59402
[578]	validation_0-mae:2134.66250
[579]	validation_0-mae:2134.95995
[580]	validation_0-mae:2135.10820
[581]	validation_0-mae:2134.79511
[582]	validation_0-mae:2135.42787
[583]	validation_0-mae:2134.04988
[584]	validation_0-mae:2134.31484
[585]	validation_0-mae:2134.18872
[586]	validation_0-mae:2133.67934
[587]	validation_0-mae:2133.13402
[588]	validation_0-mae:2133.36664
[589]	validation_0-mae:2133.13479
[590]	validation_0-mae:2133.60888
[591]	validation_0-mae:2133.86183
[592]	validation_0-mae:2133.91873
[593]	validation_0-mae:2134.70328
[594]	validation_0-mae:2133.56252
[595]	validation_0-mae:2133.52771
[596]	validation_0-mae:2133.22159
[597]	validation_0-mae:2133.64936
[598]	validation_0-mae:2133.38819
[599]	validation_0-mae:2133.01126
[600]	validation_0-mae:2132.73795
[601]	validation_0-mae:2132.95451

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[16]	validation_0-mae:6974.71820
[17]	validation_0-mae:6853.45134
[18]	validation_0-mae:6727.29041
[19]	validation_0-mae:6619.70439
[20]	validation_0-mae:6509.30442
[21]	validation_0-mae:6422.31393
[22]	validation_0-mae:6335.40166
[23]	validation_0-mae:6247.67925
[24]	validation_0-mae:6176.72846
[25]	validation_0-mae:6111.97955
[26]	validation_0-mae:6001.34260
[27]	validation_0-mae:5926.85159
[28]	validation_0-mae:5853.22757
[29]	validation_0-mae:5774.18810
[30]	validation_0-mae:5710.10414
[31]	validation_0-mae:5635.62632
[32]	validation_0-mae:5579.51669
[33]	validation_0-mae:5483.59565
[34]	validation_0-mae:5382.95174
[35]	validation_0-mae:5337.72365
[36]	validation_0-mae:5253.00237
[37]	validation_0-mae:5205.89036
[38]	validation_0-mae:5118.57587
[39]	validation_0-mae:5068.67605
[40]	validation_0-mae:4998.43308
[41]	validation_0-mae:4940.33598
[42]	validation_0-mae:4864.31073
[43]	validation_0-mae:4805.88220
[44]	validation_0-mae:4762.91480
[45]	validation_0-mae:4676.02962
[46]	validation_0-mae:4624.81548
[47]	validation_0-mae:4597.78218
[48]	validation_0-mae:4546.71645
[49]	validation_0-mae:4506.92807
[50]	validation_0-mae:4440.25965
[51]	validation_0-mae:4409.69505
[52]	validation_0-mae:4353.13608
[53]	validation_0-mae:4310.48096
[54]	validation_0-mae:4275.21159
[55]	validation_0-mae:4258.17026
[56]	validation_0-mae:4225.81567
[57]	validation_0-mae:4202.25936
[58]	validation_0-mae:4179.51389
[59]	validation_0-mae:4156.85537
[60]	validation_0-mae:4128.96568
[61]	validation_0-mae:4106.64059
[62]	validation_0-mae:4066.15163
[63]	validation_0-mae:4052.37428
[64]	validation_0-mae:4030.38958
[65]	validation_0-mae:3997.46744
[66]	validation_0-mae:3973.81579
[67]	validation_0-mae:3962.12113
[68]	validation_0-mae:3940.37342
[69]	validation_0-mae:3920.20894
[70]	validation_0-mae:3904.29713
[71]	validation_0-mae:3885.63987
[72]	validation_0-mae:3871.67198
[73]	validation_0-mae:3855.51910
[74]	validation_0-mae:3840.33691
[75]	validation_0-mae:3824.59555
[76]	validation_0-mae:3809.81329
[77]	validation_0-mae:3793.24710
[78]	validation_0-mae:3784.45153
[79]	validation_0-mae:3771.18854
[80]	validation_0-mae:3761.14155
[81]	validation_0-mae:3753.55845
[82]	validation_0-mae:3740.56398
[83]	validation_0-mae:3729.70226
[84]	validation_0-mae:3723.55171
[85]	validation_0-mae:3716.77634
[86]	validation_0-mae:3698.43213
[87]	validation_0-mae:3692.10058
[88]	validation_0-mae:3684.95036
[89]	validation_0-mae:3676.15161
[90]	validation_0-mae:3668.96695
[91]	validation_0-mae:3650.12104
[92]	validation_0-mae:3643.89338
[93]	validation_0-mae:3637.20362
[94]	validation_0-mae:3630.73792
[95]	validation_0-mae:3622.96809
[96]	validation_0-mae:3617.71686
[97]	validation_0-mae:3601.64452
[98]	validation_0-mae:3600.05364
[99]	validation_0-mae:3589.74835
[100]	validation_0-mae:3574.51336
[101]	validation_0-mae:3565.36946
[102]	validation_0-mae:3559.89451
[103]	validation_0-mae:3544.20326
[104]	validation_0-mae:3537.04639
[105]	validation_0-mae:3517.79075
[106]	validation_0-mae:3510.76268
[107]	validation_0-mae:3505.85053
[108]	validation_0-mae:3501.27605
[109]	validation_0-mae:3489.48621
[110]	validation_0-mae:3482.88259
[111]	validation_0-mae:3480.27007
[112]	validation_0-mae:3469.10486
[113]	validation_0-mae:3466.67093
[114]	validation_0-mae:3459.59592
[115]	validation_0-mae:3450.28030
[116]	validation_0-mae:3436.98710
[117]	validation_0-mae:3431.78492
[118]	validation_0-mae:3419.91270
[119]	validation_0-mae:3411.36733
[120]	validation_0-mae:3404.14269
[121]	validation_0-mae:3397.32735
[122]	validation_0-mae:3395.03126
[123]	validation_0-mae:3388.53919
[124]	validation_0-mae:3376.25319
[125]	validation_0-mae:3373.42663
[126]	validation_0-mae:3369.89393
[127]	validation_0-mae:3365.26395
[128]	validation_0-mae:3359.70586
[129]	validation_0-mae:3356.21126
[130]	validation_0-mae:3352.75613
[131]	validation_0-mae:3348.94363
[132]	validation_0-mae:3346.95646
[133]	validation_0-mae:3341.37989
[134]	validation_0-mae:3335.80033
[135]	validation_0-mae:3326.68807
[136]	validation_0-mae:3325.14744
[137]	validation_0-mae:3315.11533
[138]	validation_0-mae:3308.99884
[139]	validation_0-mae:3303.44216
[140]	validation_0-mae:3298.57847
[141]	validation_0-mae:3294.13760
[142]	validation_0-mae:3289.93527
[143]	validation_0-mae:3288.24299
[144]	validation_0-mae:3286.18432
[145]	validation_0-mae:3280.04219
[146]	validation_0-mae:3277.95940
[147]	validation_0-mae:3274.81824
[148]	validation_0-mae:3273.64776
[149]	validation_0-mae:3272.62807
[150]	validation_0-mae:3263.05862
[151]	validation_0-mae:3260.26424
[152]	validation_0-mae:3259.40666
[153]	validation_0-mae:3253.20928
[154]	validation_0-mae:3247.10716
[155]	validation_0-mae:3241.42431
[156]	validation_0-mae:3234.32902
[157]	validation_0-mae:3230.44856
[158]	validation_0-mae:3230.07535
[159]	validation_0-mae:3226.37672
[160]	validation_0-mae:3221.27358
[161]	validation_0-mae:3220.33072
[162]	validation_0-mae:3219.12989
[163]	validation_0-mae:3211.22932
[164]	validation_0-mae:3210.26553
[165]	validation_0-mae:3207.24092
[166]	validation_0-mae:3201.58849
[167]	validation_0-mae:3199.73732
[168]	validation_0-mae:3198.31389
[169]	validation_0-mae:3196.57882
[170]	validation_0-mae:3193.52577
[171]	validation_0-mae:3191.03807
[172]	validation_0-mae:3185.48095
[173]	validation_0-mae:3185.52733
[174]	validation_0-mae:3180.98574
[175]	validation_0-mae:3178.60116
[176]	validation_0-mae:3176.33942
[177]	validation_0-mae:3174.28104
[178]	validation_0-mae:3170.88687
[179]	validation_0-mae:3169.11663
[180]	validation_0-mae:3167.81679
[181]	validation_0-mae:3164.25341
[182]	validation_0-mae:3159.34210
[183]	validation_0-mae:3154.82439
[184]	validation_0-mae:3151.06220
[185]	validation_0-mae:3148.82158
[186]	validation_0-mae:3144.50536
[187]	validation_0-mae:3143.26928
[188]	validation_0-mae:3140.91346
[189]	validation_0-mae:3137.61819
[190]	validation_0-mae:3137.72226
[191]	validation_0-mae:3134.79642
[192]	validation_0-mae:3129.34225
[193]	validation_0-mae:3130.10814
[194]	validation_0-mae:3129.60264
[195]	validation_0-mae:3129.78877
[196]	validation_0-mae:3128.84384
[197]	validation_0-mae:3126.83761
[198]	validation_0-mae:3122.76157
[199]	validation_0-mae:3120.25836
[200]	validation_0-mae:3119.76030
[201]	validation_0-mae:3116.96208
[202]	validation_0-mae:3114.50106
[203]	validation_0-mae:3113.35299
[204]	validation_0-mae:3113.54577
[205]	validation_0-mae:3111.78545
[206]	validation_0-mae:3109.30007
[207]	validation_0-mae:3110.60051
[208]	validation_0-mae:3108.17260
[209]	validation_0-mae:3107.04739
[210]	validation_0-mae:3107.82364
[211]	validation_0-mae:3107.40258
[212]	validation_0-mae:3108.07949
[213]	validation_0-mae:3105.98420
[214]	validation_0-mae:3104.25786
[215]	validation_0-mae:3102.44031
[216]	validation_0-mae:3101.78885
[217]	validation_0-mae:3099.95752
[218]	validation_0-mae:3099.05859
[219]	validation_0-mae:3095.46785
[220]	validation_0-mae:3095.21800
[221]	validation_0-mae:3092.53628
[222]	validation_0-mae:3090.87672
[223]	validation_0-mae:3087.65844
[224]	validation_0-mae:3087.88365
[225]	validation_0-mae:3084.21793
[226]	validation_0-mae:3082.41182
[227]	validation_0-mae:3080.71405
[228]	validation_0-mae:3079.59683
[229]	validation_0-mae:3076.68061
[230]	validation_0-mae:3071.74913
[231]	validation_0-mae:3069.45289
[232]	validation_0-mae:3068.96531
[233]	validation_0-mae:3069.44339
[234]	validation_0-mae:3066.06510
[235]	validation_0-mae:3064.48043
[236]	validation_0-mae:3060.51390
[237]	validation_0-mae:3059.60156
[238]	validation_0-mae:3060.58824
[239]	validation_0-mae:3059.57580
[240]	validation_0-mae:3058.19074
[241]	validation_0-mae:3056.55820
[242]	validation_0-mae:3056.02567
[243]	validation_0-mae:3053.98507
[244]	validation_0-mae:3053.67985
[245]	validation_0-mae:3052.25465
[246]	validation_0-mae:3052.17163
[247]	validation_0-mae:3049.54644
[248]	validation_0-mae:3046.16153
[249]	validation_0-mae:3045.07254
[250]	validation_0-mae:3043.09357
[251]	validation_0-mae:3042.33429
[252]	validation_0-mae:3039.84714
[253]	validation_0-mae:3038.05488
[254]	validation_0-mae:3037.77750
[255]	validation_0-mae:3036.16539
[256]	validation_0-mae:3035.74470
[257]	validation_0-mae:3036.03512
[258]	validation_0-mae:3035.90862
[259]	validation_0-mae:3034.18501
[260]	validation_0-mae:3034.53810
[261]	validation_0-mae:3032.88391
[262]	validation_0-mae:3033.64088
[263]	validation_0-mae:3032.04630
[264]	validation_0-mae:3030.36427
[265]	validation_0-mae:3029.23871
[266]	validation_0-mae:3028.54163
[267]	validation_0-mae:3026.91130
[268]	validation_0-mae:3025.59000
[269]	validation_0-mae:3026.07965
[270]	validation_0-mae:3026.11325
[271]	validation_0-mae:3027.30364
[272]	validation_0-mae:3025.75131
[273]	validation_0-mae:3026.30563
[274]	validation_0-mae:3024.74752
[275]	validation_0-mae:3021.99010
[276]	validation_0-mae:3020.44558
[277]	validation_0-mae:3019.16414
[278]	validation_0-mae:3019.97185
[279]	validation_0-mae:3018.07578
[280]	validation_0-mae:3017.55800
[281]	validation_0-mae:3017.35159
[282]	validation_0-mae:3016.33960
[283]	validation_0-mae:3016.78997
[284]	validation_0-mae:3015.72630
[285]	validation_0-mae:3015.32667
[286]	validation_0-mae:3015.33715
[287]	validation_0-mae:3014.58761
[288]	validation_0-mae:3012.46066
[289]	validation_0-mae:3010.12431
[290]	validation_0-mae:3008.71975
[291]	validation_0-mae:3008.49688
[292]	validation_0-mae:3006.92572
[293]	validation_0-mae:3006.61644
[294]	validation_0-mae:3006.46264
[295]	validation_0-mae:3006.39724
[296]	validation_0-mae:3006.19464
[297]	validation_0-mae:3005.27908
[298]	validation_0-mae:3004.16923
[299]	validation_0-mae:3004.04294
[300]	validation_0-mae:3003.51731
[301]	validation_0-mae:3001.30551
[302]	validation_0-mae:3001.35024
[303]	validation_0-mae:3000.74830
[304]	validation_0-mae:3000.56797
[305]	validation_0-mae:2999.74946
[306]	validation_0-mae:2999.32933
[307]	validation_0-mae:2999.13390
[308]	validation_0-mae:2998.97324
[309]	validation_0-mae:2995.93794
[310]	validation_0-mae:2995.26317
[311]	validation_0-mae:2995.09406
[312]	validation_0-mae:2994.42600
[313]	validation_0-mae:2993.25526
[314]	validation_0-mae:2993.25357
[315]	validation_0-mae:2992.54027
[316]	validation_0-mae:2992.39951
[317]	validation_0-mae:2991.55055
[318]	validation_0-mae:2991.07637
[319]	validation_0-mae:2991.18763
[320]	validation_0-mae:2988.78165
[321]	validation_0-mae:2987.89521
[322]	validation_0-mae:2988.43979
[323]	validation_0-mae:2987.50311
[324]	validation_0-mae:2986.35019
[325]	validation_0-mae:2986.23188
[326]	validation_0-mae:2985.67989
[327]	validation_0-mae:2984.54751
[328]	validation_0-mae:2984.58046
[329]	validation_0-mae:2984.67433
[330]	validation_0-mae:2983.27601
[331]	validation_0-mae:2982.96989
[332]	validation_0-mae:2981.68807
[333]	validation_0-mae:2981.39801
[334]	validation_0-mae:2977.77836
[335]	validation_0-mae:2978.23649
[336]	validation_0-mae:2978.06671
[337]	validation_0-mae:2975.93194
[338]	validation_0-mae:2974.11062
[339]	validation_0-mae:2973.71371
[340]	validation_0-mae:2973.75899
[341]	validation_0-mae:2973.50083
[342]	validation_0-mae:2973.00634
[343]	validation_0-mae:2972.56625
[344]	validation_0-mae:2971.61428
[345]	validation_0-mae:2971.46363
[346]	validation_0-mae:2971.48625
[347]	validation_0-mae:2971.36656
[348]	validation_0-mae:2971.25132
[349]	validation_0-mae:2972.52500
[350]	validation_0-mae:2972.10727
[351]	validation_0-mae:2971.36988
[352]	validation_0-mae:2971.09574
[353]	validation_0-mae:2972.55990
[354]	validation_0-mae:2972.20041
[355]	validation_0-mae:2972.21614
[356]	validation_0-mae:2971.43081
[357]	validation_0-mae:2971.48443
[358]	validation_0-mae:2970.65804
[359]	validation_0-mae:2970.42231
[360]	validation_0-mae:2970.96323
[361]	validation_0-mae:2970.24960
[362]	validation_0-mae:2970.08942
[363]	validation_0-mae:2967.87350
[364]	validation_0-mae:2967.01356
[365]	validation_0-mae:2965.96605
[366]	validation_0-mae:2965.68686
[367]	validation_0-mae:2966.19575
[368]	validation_0-mae:2966.24241
[369]	validation_0-mae:2965.28536
[370]	validation_0-mae:2965.30160
[371]	validation_0-mae:2965.01059
[372]	validation_0-mae:2965.68423
[373]	validation_0-mae:2966.11770
[374]	validation_0-mae:2965.82918
[375]	validation_0-mae:2965.33947
[376]	validation_0-mae:2965.42308
[377]	validation_0-mae:2963.80047
[378]	validation_0-mae:2963.32707
[379]	validation_0-mae:2962.08340
[380]	validation_0-mae:2963.26185
[381]	validation_0-mae:2962.29438
[382]	validation_0-mae:2961.91451
[383]	validation_0-mae:2961.24782
[384]	validation_0-mae:2961.54508
[385]	validation_0-mae:2961.41524
[386]	validation_0-mae:2961.28039
[387]	validation_0-mae:2962.24542
[388]	validation_0-mae:2962.09544
[389]	validation_0-mae:2961.71247
[390]	validation_0-mae:2961.72225
[391]	validation_0-mae:2962.02051
[392]	validation_0-mae:2961.76327
[393]	validation_0-mae:2960.76076
[394]	validation_0-mae:2960.88934
[395]	validation_0-mae:2961.74421
[396]	validation_0-mae:2960.79608
[397]	validation_0-mae:2960.27891
[398]	validation_0-mae:2960.00865
[399]	validation_0-mae:2958.78516
[400]	validation_0-mae:2958.65321
[401]	validation_0-mae:2959.29959
[402]	validation_0-mae:2959.84958
[403]	validation_0-mae:2959.42904
[404]	validation_0-mae:2959.51969
[405]	validation_0-mae:2958.80278
[406]	validation_0-mae:2958.99802
[407]	validation_0-mae:2959.26064
[408]	validation_0-mae:2959.52673
[409]	validation_0-mae:2958.62114
[410]	validation_0-mae:2957.64630
[411]	validation_0-mae:2957.42598
[412]	validation_0-mae:2957.81242
[413]	validation_0-mae:2957.11486
[414]	validation_0-mae:2958.06910
[415]	validation_0-mae:2957.47357
[416]	validation_0-mae:2958.31212
[417]	validation_0-mae:2957.46594
[418]	validation_0-mae:2957.39462
[419]	validation_0-mae:2957.96716
[420]	validation_0-mae:2957.63245
[421]	validation_0-mae:2956.43628
[422]	validation_0-mae:2956.09187
[423]	validation_0-mae:2955.39045
[424]	validation_0-mae:2954.90774
[425]	validation_0-mae:2954.28321
[426]	validation_0-mae:2954.22242
[427]	validation_0-mae:2953.34426
[428]	validation_0-mae:2952.72397
[429]	validation_0-mae:2952.42007
[430]	validation_0-mae:2952.65266
[431]	validation_0-mae:2952.24835
[432]	validation_0-mae:2951.57892
[433]	validation_0-mae:2949.91598
[434]	validation_0-mae:2949.78357
[435]	validation_0-mae:2949.96907
[436]	validation_0-mae:2948.82807
[437]	validation_0-mae:2949.28507
[438]	validation_0-mae:2949.68366
[439]	validation_0-mae:2950.34366
[440]	validation_0-mae:2950.02323
[441]	validation_0-mae:2950.26764
[442]	validation_0-mae:2949.54810
[443]	validation_0-mae:2949.75256
[444]	validation_0-mae:2949.97433
[445]	validation_0-mae:2949.76934
[446]	validation_0-mae:2950.36823
[447]	validation_0-mae:2949.65318
[448]	validation_0-mae:2949.61817
[449]	validation_0-mae:2949.21201
[450]	validation_0-mae:2949.44197
[451]	validation_0-mae:2949.42304
[452]	validation_0-mae:2949.47194
[453]	validation_0-mae:2949.28946
[454]	validation_0-mae:2950.66605
[455]	validation_0-mae:2951.61899
[456]	validation_0-mae:2951.53133
[457]	validation_0-mae:2951.80267
[458]	validation_0-mae:2951.41694
[459]	validation_0-mae:2951.64814
[460]	validation_0-mae:2951.97880
[461]	validation_0-mae:2952.92638
[462]	validation_0-mae:2953.29868
[463]	validation_0-mae:2953.24816
[464]	validation_0-mae:2953.39504
[465]	validation_0-mae:2953.65497
[466]	validation_0-mae:2953.74827
[467]	validation_0-mae:2954.00351
[468]	validation_0-mae:2953.51506
[469]	validation_0-mae:2953.24428
[470]	validation_0-mae:2952.87867
[471]	validation_0-mae:2952.75565
[472]	validation_0-mae:2952.60214
[473]	validation_0-mae:2952.27766
[474]	validation_0-mae:2953.11524
[475]	validation_0-mae:2952.86056
[476]	validation_0-mae:2952.75703
[477]	validation_0-mae:2952.45824
[478]	validation_0-mae:2952.81033
[479]	validation_0-mae:2953.25111
[480]	validation_0-mae:2954.07627
[481]	validation_0-mae:2953.68069
[482]	validation_0-mae:2953.32027
[483]	validation_0-mae:2953.20929
[484]	validation_0-mae:2952.73728
[485]	validation_0-mae:2953.10309
[486]	validation_0-mae:2953.20532
[487]	validation_0-mae:2953.88177
[488]	validation_0-mae:2954.49033
[489]	validation_0-mae:2954.20958
[490]	validation_0-mae:2954.16593
[491]	validation_0-mae:2953.87187
[492]	validation_0-mae:2953.69578
[493]	validation_0-mae:2954.47630
[494]	validation_0-mae:2955.10013
[495]	validation_0-mae:2955.09752
[496]	validation_0-mae:2954.79950
[497]	validation_0-mae:2955.21250
[498]	validation_0-mae:2954.20611
[499]	validation_0-mae:2953.34628
[500]	validation_0-mae:2953.39241
[501]	validation_0-mae:2954.76007
[502]	validation_0-mae:2954.59856
[503]	validation_0-mae:2954.16231
[504]	validation_0-mae:2953.95958
[505]	validation_0-mae:2953.79215
[506]	validation_0-mae:2953.97367
[507]	validation_0-mae:2954.21209
[508]	validation_0-mae:2954.31216
[509]	validation_0-mae:2954.47629
[510]	validation_0-mae:2954.50558
[511]	validation_0-mae:2954.82040
[512]	validation_0-mae:2955.02470
[513]	validation_0-mae:2953.84533
[514]	validation_0-mae:2954.69866
[515]	validation_0-mae:2955.30749
[516]	validation_0-mae:2955.24554
[517]	validation_0-mae:2955.13926
[518]	validation_0-mae:2955.00080
[519]	validation_0-mae:2955.31994
[520]	validation_0-mae:2954.50993
[521]	validation_0-mae:2954.67027
[522]	validation_0-mae:2954.24490
[523]	validation_0-mae:2954.91367
[524]	validation_0-mae:2954.23528
[525]	validation_0-mae:2954.90584
[526]	validation_0-mae:2953.92830
[527]	validation_0-mae:2954.87324
[528]	validation_0-mae:2954.77993
[529]	validation_0-mae:2954.80257
[530]	validation_0-mae:2954.40339
[531]	validation_0-mae:2953.42530
[532]	validation_0-mae:2953.73732
[533]	validation_0-mae:2953.82754
[534]	validation_0-mae:2953.71402
[535]	validation_0-mae:2953.42330
[536]	validation_0-mae:2953.61573
[537]	validation_0-mae:2953.62330
[538]	validation_0-mae:2953.51322
[539]	validation_0-mae:2953.63349
[540]	validation_0-mae:2953.48308
[541]	validation_0-mae:2954.11834
[542]	validation_0-mae:2953.68221
[543]	validation_0-mae:2954.30233
[544]	validation_0-mae:2953.97561
[545]	validation_0-mae:2953.08991
[546]	validation_0-mae:2952.88072
[547]	validation_0-mae:2953.11790
[548]	validation_0-mae:2952.55173
[549]	validation_0-mae:2952.17646
[550]	validation_0-mae:2952.07858
[551]	validation_0-mae:2952.23004
[552]	validation_0-mae:2951.25599
[553]	validation_0-mae:2950.99210
[554]	validation_0-mae:2951.48966
[555]	validation_0-mae:2951.38689
[556]	validation_0-mae:2950.96779
[557]	validation_0-mae:2950.78260
[558]	validation_0-mae:2951.23397
[559]	validation_0-mae:2951.38816
[560]	validation_0-mae:2952.02870
[561]	validation_0-mae:2951.57425
[562]	validation_0-mae:2952.25376
[563]	validation_0-mae:2952.06687
[564]	validation_0-mae:2952.35945
[565]	validation_0-mae:2953.67448
[566]	validation_0-mae:2953.89914
[567]	validation_0-mae:2954.36049
[568]	validation_0-mae:2953.72522
[569]	validation_0-mae:2953.99432
[570]	validation_0-mae:2954.31152
[571]	validation_0-mae:2954.42868
[572]	validation_0-mae:2954.36295
[573]	validation_0-mae:2954.52524
[574]	validation_0-mae:2954.49015
[575]	validation_0-mae:2954.65858
[576]	validation_0-mae:2954.72363
[577]	validation_0-mae:2954.70901
[578]	validation_0-mae:2954.84059
[579]	validation_0-mae:2955.20420
[580]	validation_0-mae:2955.91151
[581]	validation_0-mae:2955.72813
[582]	validation_0-mae:2955.78327
[583]	validation_0-mae:2955.05661
[584]	validation_0-mae:2955.04233
[585]	validation_0-mae:2954.21893
[586]	validation_0-mae:2953.24094
[587]	validation_0-mae:2953.77389
[588]	validation_0-mae:2953.99330
[589]	validation_0-mae:2953.45421
[590]	validation_0-mae:2953.26435
[591]	validation_0-mae:2952.60676
[592]	validation_0-mae:2951.83015
[593]	validation_0-mae:2952.22498
[594]	validation_0-mae:2951.44299
[595]	validation_0-mae:2951.41514
[596]	validation_0-mae:2952.11658
[597]	validation_0-mae:2952.27721
[598]	validation_0-mae:2952.80178
[599]	validation_0-mae:2952.96551
[600]	validation_0-mae:2952.93007
[601]	validation_0-mae:2953.11324
[602]	validation_0-mae:2953.23799
[603]	validation_0-mae:2952.28657
[604]	validation_0-mae:2951.25703
[605]	validation_0-mae:2951.08904

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[17]	validation_0-mae:6603.79071
[18]	validation_0-mae:6431.67401
[19]	validation_0-mae:6261.58211
[20]	validation_0-mae:6077.47466
[21]	validation_0-mae:5938.15098
[22]	validation_0-mae:5780.31107
[23]	validation_0-mae:5637.82226
[24]	validation_0-mae:5493.55458
[25]	validation_0-mae:5369.57689
[26]	validation_0-mae:5246.90480
[27]	validation_0-mae:5127.57220
[28]	validation_0-mae:5012.72365
[29]	validation_0-mae:4907.95497
[30]	validation_0-mae:4805.20916
[31]	validation_0-mae:4710.60913
[32]	validation_0-mae:4600.92654
[33]	validation_0-mae:4516.75504
[34]	validation_0-mae:4432.42863
[35]	validation_0-mae:4341.63610
[36]	validation_0-mae:4257.34523
[37]	validation_0-mae:4186.93159
[38]	validation_0-mae:4130.41055
[39]	validation_0-mae:4059.44175
[40]	validation_0-mae:3988.90194
[41]	validation_0-mae:3936.62615
[42]	validation_0-mae:3876.47836
[43]	validation_0-mae:3823.74978
[44]	validation_0-mae:3771.20968
[45]	validation_0-mae:3720.35689
[46]	validation_0-mae:3680.43260
[47]	validation_0-mae:3621.37075
[48]	validation_0-mae:3586.59179
[49]	validation_0-mae:3543.41951
[50]	validation_0-mae:3505.14418
[51]	validation_0-mae:3464.97587
[52]	validation_0-mae:3433.05185
[53]	validation_0-mae:3393.57176
[54]	validation_0-mae:3359.63264
[55]	validation_0-mae:3334.88609
[56]	validation_0-mae:3304.94282
[57]	validation_0-mae:3278.35574
[58]	validation_0-mae:3252.14073
[59]	validation_0-mae:3227.69513
[60]	validation_0-mae:3199.68120
[61]	validation_0-mae:3177.68330
[62]	validation_0-mae:3155.65673
[63]	validation_0-mae:3124.43177
[64]	validation_0-mae:3101.82782
[65]	validation_0-mae:3083.62305
[66]	validation_0-mae:3064.61059
[67]	validation_0-mae:3039.39686
[68]	validation_0-mae:3024.46060
[69]	validation_0-mae:3010.68139
[70]	validation_0-mae:2987.32452
[71]	validation_0-mae:2974.34300
[72]	validation_0-mae:2961.60715
[73]	validation_0-mae:2948.22955
[74]	validation_0-mae:2937.78350
[75]	validation_0-mae:2924.59975
[76]	validation_0-mae:2914.73668
[77]	validation_0-mae:2900.87306
[78]	validation_0-mae:2889.37647
[79]	validation_0-mae:2866.11114
[80]	validation_0-mae:2855.34553
[81]	validation_0-mae:2842.11330
[82]	validation_0-mae:2832.90454
[83]	validation_0-mae:2823.45028
[84]	validation_0-mae:2805.51539
[85]	validation_0-mae:2794.88387
[86]	validation_0-mae:2781.49171
[87]	validation_0-mae:2771.62234
[88]	validation_0-mae:2752.55431
[89]	validation_0-mae:2742.74732
[90]	validation_0-mae:2738.90528
[91]	validation_0-mae:2731.77167
[92]	validation_0-mae:2718.53360
[93]	validation_0-mae:2705.22312
[94]	validation_0-mae:2699.71018
[95]	validation_0-mae:2693.15950
[96]	validation_0-mae:2687.09615
[97]	validation_0-mae:2680.28414
[98]	validation_0-mae:2663.93401
[99]	validation_0-mae:2656.74086
[100]	validation_0-mae:2641.56639
[101]	validation_0-mae:2630.28197
[102]	validation_0-mae:2621.71505
[103]	validation_0-mae:2609.60356
[104]	validation_0-mae:2604.26558
[105]	validation_0-mae:2598.60358
[106]	validation_0-mae:2589.04342
[107]	validation_0-mae:2579.39440
[108]	validation_0-mae:2575.42540
[109]	validation_0-mae:2560.38585
[110]	validation_0-mae:2551.75367
[111]	validation_0-mae:2547.49178
[112]	validation_0-mae:2541.66842
[113]	validation_0-mae:2536.91055
[114]	validation_0-mae:2529.30097
[115]	validation_0-mae:2528.68792
[116]	validation_0-mae:2523.60301
[117]	validation_0-mae:2512.39811
[118]	validation_0-mae:2507.39381
[119]	validation_0-mae:2501.22286
[120]	validation_0-mae:2493.49728
[121]	validation_0-mae:2486.56497
[122]	validation_0-mae:2482.60495
[123]	validation_0-mae:2475.05682
[124]	validation_0-mae:2468.59420
[125]	validation_0-mae:2465.38533
[126]	validation_0-mae:2459.96113
[127]	validation_0-mae:2452.33677
[128]	validation_0-mae:2447.77336
[129]	validation_0-mae:2444.60000
[130]	validation_0-mae:2439.02329
[131]	validation_0-mae:2435.94264
[132]	validation_0-mae:2428.81525
[133]	validation_0-mae:2424.61266
[134]	validation_0-mae:2420.40412
[135]	validation_0-mae:2417.44445
[136]	validation_0-mae:2413.60392
[137]	validation_0-mae:2407.94476
[138]	validation_0-mae:2401.32055
[139]	validation_0-mae:2398.92371
[140]	validation_0-mae:2395.12869
[141]	validation_0-mae:2391.86667
[142]	validation_0-mae:2389.54011
[143]	validation_0-mae:2386.89438
[144]	validation_0-mae:2385.73288
[145]	validation_0-mae:2382.83334
[146]	validation_0-mae:2381.03648
[147]	validation_0-mae:2376.45686
[148]	validation_0-mae:2372.39945
[149]	validation_0-mae:2369.17123
[150]	validation_0-mae:2366.17961
[151]	validation_0-mae:2363.40160
[152]	validation_0-mae:2360.08440
[153]	validation_0-mae:2356.33024
[154]	validation_0-mae:2354.05084
[155]	validation_0-mae:2352.30435
[156]	validation_0-mae:2349.84076
[157]	validation_0-mae:2347.44382
[158]	validation_0-mae:2345.47157
[159]	validation_0-mae:2340.08991
[160]	validation_0-mae:2336.90093
[161]	validation_0-mae:2335.15338
[162]	validation_0-mae:2331.87833
[163]	validation_0-mae:2329.54862
[164]	validation_0-mae:2327.17706
[165]	validation_0-mae:2324.79859
[166]	validation_0-mae:2322.24275
[167]	validation_0-mae:2320.11407
[168]	validation_0-mae:2317.35445
[169]	validation_0-mae:2312.80777
[170]	validation_0-mae:2309.29275
[171]	validation_0-mae:2306.77425
[172]	validation_0-mae:2305.04084
[173]	validation_0-mae:2303.88415
[174]	validation_0-mae:2301.84430
[175]	validation_0-mae:2300.93618
[176]	validation_0-mae:2300.10593
[177]	validation_0-mae:2298.29789
[178]	validation_0-mae:2294.71706
[179]	validation_0-mae:2295.18197
[180]	validation_0-mae:2293.67205
[181]	validation_0-mae:2292.84211
[182]	validation_0-mae:2293.93861
[183]	validation_0-mae:2293.43833
[184]	validation_0-mae:2290.84485
[185]	validation_0-mae:2287.28088
[186]	validation_0-mae:2284.07304
[187]	validation_0-mae:2281.69415
[188]	validation_0-mae:2282.18275
[189]	validation_0-mae:2278.56694
[190]	validation_0-mae:2278.95117
[191]	validation_0-mae:2275.92648
[192]	validation_0-mae:2276.74351
[193]	validation_0-mae:2275.02228
[194]	validation_0-mae:2272.55359
[195]	validation_0-mae:2271.10980
[196]	validation_0-mae:2269.72567
[197]	validation_0-mae:2267.06601
[198]	validation_0-mae:2263.58926
[199]	validation_0-mae:2262.50650
[200]	validation_0-mae:2262.65837
[201]	validation_0-mae:2260.67033
[202]	validation_0-mae:2258.29368
[203]	validation_0-mae:2256.30148
[204]	validation_0-mae:2255.14858
[205]	validation_0-mae:2254.59452
[206]	validation_0-mae:2252.14711
[207]	validation_0-mae:2252.06477
[208]	validation_0-mae:2250.33490
[209]	validation_0-mae:2248.85489
[210]	validation_0-mae:2249.11315
[211]	validation_0-mae:2247.19507
[212]	validation_0-mae:2245.94473
[213]	validation_0-mae:2244.50542
[214]	validation_0-mae:2244.75753
[215]	validation_0-mae:2241.26499
[216]	validation_0-mae:2237.70024
[217]	validation_0-mae:2238.09929
[218]	validation_0-mae:2236.36470
[219]	validation_0-mae:2235.64820
[220]	validation_0-mae:2233.53076
[221]	validation_0-mae:2232.21596
[222]	validation_0-mae:2230.61346
[223]	validation_0-mae:2231.66303
[224]	validation_0-mae:2230.95640
[225]	validation_0-mae:2230.37090
[226]	validation_0-mae:2230.47770
[227]	validation_0-mae:2229.30184
[228]	validation_0-mae:2228.62923
[229]	validation_0-mae:2228.53809
[230]	validation_0-mae:2228.50244
[231]	validation_0-mae:2226.80082
[232]	validation_0-mae:2226.06249
[233]	validation_0-mae:2226.11472
[234]	validation_0-mae:2225.01132
[235]	validation_0-mae:2224.82376
[236]	validation_0-mae:2225.18534
[237]	validation_0-mae:2224.39809
[238]	validation_0-mae:2222.70000
[239]	validation_0-mae:2220.74319
[240]	validation_0-mae:2220.60897
[241]	validation_0-mae:2220.52062
[242]	validation_0-mae:2220.33803
[243]	validation_0-mae:2220.87492
[244]	validation_0-mae:2218.20096
[245]	validation_0-mae:2217.03784
[246]	validation_0-mae:2215.01463
[247]	validation_0-mae:2215.56818
[248]	validation_0-mae:2215.23565
[249]	validation_0-mae:2214.16025
[250]	validation_0-mae:2214.17030
[251]	validation_0-mae:2213.15195
[252]	validation_0-mae:2212.02208
[253]	validation_0-mae:2212.60035
[254]	validation_0-mae:2212.46826
[255]	validation_0-mae:2212.25279
[256]	validation_0-mae:2209.61318
[257]	validation_0-mae:2210.80513
[258]	validation_0-mae:2210.46497
[259]	validation_0-mae:2209.09202
[260]	validation_0-mae:2209.02499
[261]	validation_0-mae:2208.62485
[262]	validation_0-mae:2208.06284
[263]	validation_0-mae:2206.80184
[264]	validation_0-mae:2206.19140
[265]	validation_0-mae:2205.86772
[266]	validation_0-mae:2205.45437
[267]	validation_0-mae:2204.71555
[268]	validation_0-mae:2203.61401
[269]	validation_0-mae:2203.30662
[270]	validation_0-mae:2202.10019
[271]	validation_0-mae:2202.05987
[272]	validation_0-mae:2201.77799
[273]	validation_0-mae:2200.35193
[274]	validation_0-mae:2200.33636
[275]	validation_0-mae:2199.77734
[276]	validation_0-mae:2198.44940
[277]	validation_0-mae:2197.61339
[278]	validation_0-mae:2196.17586
[279]	validation_0-mae:2196.14965
[280]	validation_0-mae:2197.16803
[281]	validation_0-mae:2197.38016
[282]	validation_0-mae:2196.66390
[283]	validation_0-mae:2195.34176
[284]	validation_0-mae:2195.50081
[285]	validation_0-mae:2194.99759
[286]	validation_0-mae:2194.74534
[287]	validation_0-mae:2194.19219
[288]	validation_0-mae:2194.26990
[289]	validation_0-mae:2193.95713
[290]	validation_0-mae:2193.36412
[291]	validation_0-mae:2192.59328
[292]	validation_0-mae:2191.37547
[293]	validation_0-mae:2190.67954
[294]	validation_0-mae:2189.26518
[295]	validation_0-mae:2189.62797
[296]	validation_0-mae:2189.34863
[297]	validation_0-mae:2190.34491
[298]	validation_0-mae:2190.74239
[299]	validation_0-mae:2190.25444
[300]	validation_0-mae:2189.77277
[301]	validation_0-mae:2190.15214
[302]	validation_0-mae:2189.36445
[303]	validation_0-mae:2189.52835
[304]	validation_0-mae:2189.52550
[305]	validation_0-mae:2190.61506
[306]	validation_0-mae:2190.05787
[307]	validation_0-mae:2189.23432
[308]	validation_0-mae:2188.86319
[309]	validation_0-mae:2188.32191
[310]	validation_0-mae:2188.53880
[311]	validation_0-mae:2187.76024
[312]	validation_0-mae:2188.17442
[313]	validation_0-mae:2187.51584
[314]	validation_0-mae:2186.26809
[315]	validation_0-mae:2185.77946
[316]	validation_0-mae:2186.63324
[317]	validation_0-mae:2187.10550
[318]	validation_0-mae:2186.70062
[319]	validation_0-mae:2185.94337
[320]	validation_0-mae:2184.94483
[321]	validation_0-mae:2184.87805
[322]	validation_0-mae:2184.87030
[323]	validation_0-mae:2184.29712
[324]	validation_0-mae:2184.13120
[325]	validation_0-mae:2184.74379
[326]	validation_0-mae:2182.64372
[327]	validation_0-mae:2182.15381
[328]	validation_0-mae:2182.89477
[329]	validation_0-mae:2181.82205
[330]	validation_0-mae:2181.31732
[331]	validation_0-mae:2180.28833
[332]	validation_0-mae:2179.33926
[333]	validation_0-mae:2179.01420
[334]	validation_0-mae:2179.20025
[335]	validation_0-mae:2179.55880
[336]	validation_0-mae:2179.28183
[337]	validation_0-mae:2179.53546
[338]	validation_0-mae:2179.31364
[339]	validation_0-mae:2178.29060
[340]	validation_0-mae:2178.14272
[341]	validation_0-mae:2178.26885
[342]	validation_0-mae:2178.59201
[343]	validation_0-mae:2178.44051
[344]	validation_0-mae:2178.86871
[345]	validation_0-mae:2179.14883
[346]	validation_0-mae:2179.21440
[347]	validation_0-mae:2178.57161
[348]	validation_0-mae:2178.74471
[349]	validation_0-mae:2178.16997
[350]	validation_0-mae:2178.29965
[351]	validation_0-mae:2176.94607
[352]	validation_0-mae:2176.47241
[353]	validation_0-mae:2177.21546
[354]	validation_0-mae:2177.24848
[355]	validation_0-mae:2177.71119
[356]	validation_0-mae:2177.42927
[357]	validation_0-mae:2177.12554
[358]	validation_0-mae:2176.68313
[359]	validation_0-mae:2177.29853
[360]	validation_0-mae:2176.52771
[361]	validation_0-mae:2176.08086
[362]	validation_0-mae:2176.52242
[363]	validation_0-mae:2175.69132
[364]	validation_0-mae:2176.02088
[365]	validation_0-mae:2176.04971
[366]	validation_0-mae:2176.48216
[367]	validation_0-mae:2176.54816
[368]	validation_0-mae:2176.36213
[369]	validation_0-mae:2175.55504
[370]	validation_0-mae:2175.15751
[371]	validation_0-mae:2175.27899
[372]	validation_0-mae:2175.17896
[373]	validation_0-mae:2175.32497
[374]	validation_0-mae:2175.26947
[375]	validation_0-mae:2175.36842
[376]	validation_0-mae:2175.53953
[377]	validation_0-mae:2174.64163
[378]	validation_0-mae:2174.55502
[379]	validation_0-mae:2172.80151
[380]	validation_0-mae:2172.80006
[381]	validation_0-mae:2172.65337
[382]	validation_0-mae:2173.17170
[383]	validation_0-mae:2172.42077
[384]	validation_0-mae:2172.17998
[385]	validation_0-mae:2170.96133
[386]	validation_0-mae:2170.90519
[387]	validation_0-mae:2170.77980
[388]	validation_0-mae:2170.68258
[389]	validation_0-mae:2169.43128
[390]	validation_0-mae:2169.11471
[391]	validation_0-mae:2168.96747
[392]	validation_0-mae:2169.00783
[393]	validation_0-mae:2168.95379
[394]	validation_0-mae:2169.07419
[395]	validation_0-mae:2168.93448
[396]	validation_0-mae:2168.61305
[397]	validation_0-mae:2168.59388
[398]	validation_0-mae:2168.44574
[399]	validation_0-mae:2169.15647
[400]	validation_0-mae:2169.85697
[401]	validation_0-mae:2169.91758
[402]	validation_0-mae:2168.72124
[403]	validation_0-mae:2168.63975
[404]	validation_0-mae:2169.40630
[405]	validation_0-mae:2169.22756
[406]	validation_0-mae:2169.42327
[407]	validation_0-mae:2168.12975
[408]	validation_0-mae:2166.75119
[409]	validation_0-mae:2167.63358
[410]	validation_0-mae:2167.94203
[411]	validation_0-mae:2167.77068
[412]	validation_0-mae:2166.07808
[413]	validation_0-mae:2166.53046
[414]	validation_0-mae:2166.79728
[415]	validation_0-mae:2166.25062
[416]	validation_0-mae:2166.26713
[417]	validation_0-mae:2165.84294
[418]	validation_0-mae:2164.86400
[419]	validation_0-mae:2164.07327
[420]	validation_0-mae:2164.35944
[421]	validation_0-mae:2163.53013
[422]	validation_0-mae:2162.87257
[423]	validation_0-mae:2161.56179
[424]	validation_0-mae:2161.48964
[425]	validation_0-mae:2161.84801
[426]	validation_0-mae:2161.18408
[427]	validation_0-mae:2160.86608
[428]	validation_0-mae:2160.90716
[429]	validation_0-mae:2161.18686
[430]	validation_0-mae:2161.43102
[431]	validation_0-mae:2161.18375
[432]	validation_0-mae:2161.31904
[433]	validation_0-mae:2161.39562
[434]	validation_0-mae:2160.44425
[435]	validation_0-mae:2160.00570
[436]	validation_0-mae:2159.09424
[437]	validation_0-mae:2157.66507
[438]	validation_0-mae:2157.26626
[439]	validation_0-mae:2157.21909
[440]	validation_0-mae:2156.57975
[441]	validation_0-mae:2154.71672
[442]	validation_0-mae:2154.52574
[443]	validation_0-mae:2154.52245
[444]	validation_0-mae:2154.34999
[445]	validation_0-mae:2153.98436
[446]	validation_0-mae:2152.97329
[447]	validation_0-mae:2152.53989
[448]	validation_0-mae:2151.38548
[449]	validation_0-mae:2151.06084
[450]	validation_0-mae:2151.00876
[451]	validation_0-mae:2150.96522
[452]	validation_0-mae:2150.73098
[453]	validation_0-mae:2150.77860
[454]	validation_0-mae:2150.79595
[455]	validation_0-mae:2150.69567
[456]	validation_0-mae:2151.19035
[457]	validation_0-mae:2151.16632
[458]	validation_0-mae:2150.38246
[459]	validation_0-mae:2149.44798
[460]	validation_0-mae:2149.19866
[461]	validation_0-mae:2149.46384
[462]	validation_0-mae:2149.23407
[463]	validation_0-mae:2149.39113
[464]	validation_0-mae:2148.88375
[465]	validation_0-mae:2148.72361
[466]	validation_0-mae:2148.71178
[467]	validation_0-mae:2148.46618
[468]	validation_0-mae:2148.34037
[469]	validation_0-mae:2146.12611
[470]	validation_0-mae:2145.77387
[471]	validation_0-mae:2145.61544
[472]	validation_0-mae:2145.19243
[473]	validation_0-mae:2144.45872
[474]	validation_0-mae:2142.74683
[475]	validation_0-mae:2142.34346
[476]	validation_0-mae:2141.76106
[477]	validation_0-mae:2141.64282
[478]	validation_0-mae:2139.84325
[479]	validation_0-mae:2140.24552
[480]	validation_0-mae:2138.66414
[481]	validation_0-mae:2138.57264
[482]	validation_0-mae:2138.38258
[483]	validation_0-mae:2137.72364
[484]	validation_0-mae:2137.90165
[485]	validation_0-mae:2138.85035
[486]	validation_0-mae:2138.40731
[487]	validation_0-mae:2138.08577
[488]	validation_0-mae:2138.12733
[489]	validation_0-mae:2137.80689
[490]	validation_0-mae:2138.00943
[491]	validation_0-mae:2138.37336
[492]	validation_0-mae:2138.11297
[493]	validation_0-mae:2138.14638
[494]	validation_0-mae:2138.31012
[495]	validation_0-mae:2137.73369
[496]	validation_0-mae:2137.31039
[497]	validation_0-mae:2137.49541
[498]	validation_0-mae:2137.51267
[499]	validation_0-mae:2137.40408
[500]	validation_0-mae:2137.62667
[501]	validation_0-mae:2137.85422
[502]	validation_0-mae:2137.90969
[503]	validation_0-mae:2136.75459
[504]	validation_0-mae:2136.54109
[505]	validation_0-mae:2136.88880
[506]	validation_0-mae:2137.05662
[507]	validation_0-mae:2137.14288
[508]	validation_0-mae:2136.94486
[509]	validation_0-mae:2136.50932
[510]	validation_0-mae:2136.46101
[511]	validation_0-mae:2135.82209
[512]	validation_0-mae:2135.88059
[513]	validation_0-mae:2135.93082
[514]	validation_0-mae:2136.15622
[515]	validation_0-mae:2135.81749
[516]	validation_0-mae:2134.72191
[517]	validation_0-mae:2134.23262
[518]	validation_0-mae:2134.25562
[519]	validation_0-mae:2134.41014
[520]	validation_0-mae:2134.25646
[521]	validation_0-mae:2134.27631
[522]	validation_0-mae:2134.18971
[523]	validation_0-mae:2134.80445
[524]	validation_0-mae:2134.53999
[525]	validation_0-mae:2134.52800
[526]	validation_0-mae:2134.36463
[527]	validation_0-mae:2134.38358
[528]	validation_0-mae:2134.01608
[529]	validation_0-mae:2133.30913
[530]	validation_0-mae:2131.93127
[531]	validation_0-mae:2131.57134
[532]	validation_0-mae:2131.76989
[533]	validation_0-mae:2132.51654
[534]	validation_0-mae:2131.41807
[535]	validation_0-mae:2131.47878
[536]	validation_0-mae:2130.08930
[537]	validation_0-mae:2129.93648
[538]	validation_0-mae:2130.06885
[539]	validation_0-mae:2129.28229
[540]	validation_0-mae:2126.84381
[541]	validation_0-mae:2126.49205
[542]	validation_0-mae:2126.65062
[543]	validation_0-mae:2126.61494
[544]	validation_0-mae:2126.39726
[545]	validation_0-mae:2126.63256
[546]	validation_0-mae:2125.07047
[547]	validation_0-mae:2124.79462
[548]	validation_0-mae:2124.69002
[549]	validation_0-mae:2124.09200
[550]	validation_0-mae:2124.14852
[551]	validation_0-mae:2124.45510
[552]	validation_0-mae:2124.53274
[553]	validation_0-mae:2123.96335
[554]	validation_0-mae:2123.97582
[555]	validation_0-mae:2123.47631
[556]	validation_0-mae:2123.15758
[557]	validation_0-mae:2122.41689
[558]	validation_0-mae:2122.44986
[559]	validation_0-mae:2122.45468
[560]	validation_0-mae:2122.44281
[561]	validation_0-mae:2122.83616
[562]	validation_0-mae:2123.53655
[563]	validation_0-mae:2122.81090
[564]	validation_0-mae:2121.73857
[565]	validation_0-mae:2121.83366
[566]	validation_0-mae:2122.36922
[567]	validation_0-mae:2121.97023
[568]	validation_0-mae:2121.90464
[569]	validation_0-mae:2122.32239
[570]	validation_0-mae:2122.65326
[571]	validation_0-mae:2122.63364
[572]	validation_0-mae:2122.34295
[573]	validation_0-mae:2122.07818
[574]	validation_0-mae:2121.69421
[575]	validation_0-mae:2121.74580
[576]	validation_0-mae:2120.76643
[577]	validation_0-mae:2120.53649
[578]	validation_0-mae:2120.63825
[579]	validation_0-mae:2120.76867
[580]	validation_0-mae:2121.08676
[581]	validation_0-mae:2120.94966
[582]	validation_0-mae:2120.60640
[583]	validation_0-mae:2120.61419
[584]	validation_0-mae:2120.16892
[585]	validation_0-mae:2119.87515
[586]	validation_0-mae:2120.23817
[587]	validation_0-mae:2119.92850
[588]	validation_0-mae:2120.08264
[589]	validation_0-mae:2119.92354
[590]	validation_0-mae:2120.04605
[591]	validation_0-mae:2120.22526
[592]	validation_0-mae:2119.38660
[593]	validation_0-mae:2119.25805
[594]	validation_0-mae:2119.02628
[595]	validation_0-mae:2119.06922
[596]	validation_0-mae:2119.50190
[597]	validation_0-mae:2119.05347
[598]	validation_0-mae:2118.76369
[599]	validation_0-mae:2118.74150
[600]	validation_0-mae:2118.82789
[601]	validation_0-mae:2118.85134
[602]	validation_0-mae:2119.21697
[603]	validation_0-mae:2118.60885
[604]	validation_0-mae:2118.82551
[605]	validation_0-mae:2118.21920
[606]	validation_0-mae:2117.97294

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[0]	validation_0-mae:12717.00158
[1]	validation_0-mae:12203.24432
[2]	validation_0-mae:11717.91930
[3]	validation_0-mae:11266.76446
[4]	validation_0-mae:10864.79500
[5]	validation_0-mae:10468.53176
[6]	validation_0-mae:10114.87609
[7]	validation_0-mae:9804.64830
[8]	validation_0-mae:9489.64834
[9]	validation_0-mae:9200.26267
[10]	validation_0-mae:8929.74419
[0]	validation_0-mae:12803.38419
[1]	validation_0-mae:12354.93724
[2]	validation_0-mae:11932.54399
[3]	validation_0-mae:11536.53160
[4]	validation_0-mae:11167.95810
[5]	validation_0-mae:10818.63217
[6]	validation_0-mae:10486.31717
[7]	validation_0-mae:10177.24125
[8]	validation_0-mae:9896.32195

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[9]	validation_0-mae:9617.68490
[10]	validation_0-mae:9363.27191
[0]	validation_0-mae:12441.88880
[1]	validation_0-mae:11727.16609
[2]	validation_0-mae:11070.75607

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[3]	validation_0-mae:10499.88550
[4]	validation_0-mae:10001.49123
[5]	validation_0-mae:9570.40334
[6]	validation_0-mae:9174.97870
[7]	validation_0-mae:8844.78017
[8]	validation_0-mae:8556.64659
[9]	validation_0-mae:8286.83778
[10]	validation_0-mae:8033.57874
[11]	validation_0-mae:7806.45892
[12]	validation_0-mae:7610.57915
[13]	validation_0-mae:7434.41336
[14]	validation_0-mae:7282.40516
[15]	validation_0-mae:7148.44626
[16]	validation_0-mae:7054.26424
[17]	validation_0-mae:6934.78453
[18]	validation_0-mae:6847.49794
[0]	validation_0-mae:12672.78710
[1]	validation_0-mae:12139.06480
[2]	validation_0-mae:11650.92614
[3]	validation_0-mae:11219.49019
[4]	validation_0-mae:10841.80907
[5]	validation_0-mae:10517.25774
[6]	validation_0-mae:10231.22088
[7]	validation_0-mae:9979.99116
[8]	validation_0-mae:9751.41132
[9]	validation_0-mae:9559.85095
[10]	validation_0-mae:9382.97414

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[0]	validation_0-mae:12850.24799
[1]	validation_0-mae:12445.67251
[2]	validation_0-mae:12071.93308
[3]	validation_0-mae:11708.46168
[4]	validation_0-mae:11367.36640
[5]	validation_0-mae:11053.53826

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[6]	validation_0-mae:10750.44673
[7]	validation_0-mae:10473.70279
[8]	validation_0-mae:10211.14463
[9]	validation_0-mae:9960.82621
[10]	validation_0-mae:9724.13142
[0]	validation_0-mae:12401.68751
[1]	validation_0-mae:11656.28290
[2]	validation_0-mae:10977.17621
[3]	validation_0-mae:10386.11958
[4]	validation_0-mae:9888.33428
[5]	validation_0-mae:9448.02512
[6]	validation_0-mae:9070.54275
[7]	validation_0-mae:8740.87853
[8]	validation_0-mae:8422.46942
[9]	validation_0-mae:8138.63365
[10]	validation_0-mae:7899.52621

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[11]	validation_0-mae:7688.79504
[12]	validation_0-mae:7487.40804
[13]	validation_0-mae:7320.58107
[14]	validation_0-mae:7184.66386
[15]	validation_0-mae:7047.46921
[16]	validation_0-mae:6911.81326
[17]	validation_0-mae:6821.55098
[18]	validation_0-mae:6718.55481
[19]	validation_0-mae:6650.69034
[20]	validation_0-mae:6538.69792
[21]	validation_0-mae:6452.25683
[0]	validation_0-mae:12491.91801
[1]	validation_0-mae:11792.56791
[2]	validation_0-mae:11174.55136
[3]	validation_0-mae:10590.94751
[4]	validation_0-mae:10084.47647
[5]	validation_0-mae:9624.31470
[6]	validation_0-mae:9220.31748
[7]	validation_0-mae:8837.26943
[8]	validation_0-mae:8463.06264
[9]	validation_0-mae:8134.31160
[10]	validation_0-mae:7823.57181
[11]	validation_0-mae:7533.87985

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[12]	validation_0-mae:7268.62135
[13]	validation_0-mae:7003.82215
[14]	validation_0-mae:6789.63541
[15]	validation_0-mae:6573.51919
[16]	validation_0-mae:6328.46188
[17]	validation_0-mae:6132.32304
[18]	validation_0-mae:5924.20597
[19]	validation_0-mae:5731.08963
[20]	validation_0-mae:5545.26735
[21]	validation_0-mae:5404.71066
[22]	validation_0-mae:5274.58033
[23]	validation_0-mae:5139.37875
[24]	validation_0-mae:5001.39864
[25]	validation_0-mae:4865.61854
[26]	validation_0-mae:4736.99454
[27]	validation_0-mae:4620.61116
[28]	validation_0-mae:4520.95300
[29]	validation_0-mae:4437.74531
[30]	validation_0-mae:4323.88635
[31]	validation_0-mae:4231.68447
[32]	validation_0-mae:4158.70016
[33]	validation_0-mae:4068.11626
[34]	validation_0-mae:3985.44990
[35]	validation_0-mae:3922.12500
[36]	validation_0-mae:3843.64062
[37]	validation_0-mae:3768.96382
[38]	validation_0-mae:3719.17514
[39]	validation_0-mae:3656.09473
[40]	validation_0-mae:3609.47319
[41]	validation_0-mae:3558.55940
[42]	validation_0-mae:3494.23846
[43]	validation_0-mae:3443.21722
[44]	validation_0-mae:3394.73045
[45]	validation_0-mae:3351.59834
[46]	validation_0-mae:3311.95717
[47]	validation_0-mae:3281.07669
[48]	validation_0-mae:3246.86090
[49]	validation_0-mae:3205.05203
[50]	validation_0-mae:3186.29934
[51]	validation_0-mae:3159.58949
[52]	validation_0-mae:3126.22598
[53]	validation_0-mae:3103.10999
[54]	validation_0-mae:3082.06135
[55]	validation_0-mae:3052.75390
[56]	validation_0-mae:3021.07800
[57]	validation_0-mae:3005.00249
[58]	validation_0-mae:2987.34351
[59]	validation_0-mae:2965.20332
[60]	validation_0-mae:2949.94689
[61]	validation_0-mae:2933.29465
[62]	validation_0-mae:2906.01964
[63]	validation_0-mae:2889.13144
[64]	validation_0-mae:2877.06231
[65]	validation_0-mae:2866.96996
[66]	validation_0-mae:2846.04697
[67]	validation_0-mae:2824.54110
[68]	validation_0-mae:2807.41473
[69]	validation_0-mae:2800.99543
[70]	validation_0-mae:2786.34977
[71]	validation_0-mae:2773.57233
[72]	validation_0-mae:2753.58042
[73]	validation_0-mae:2746.20686
[74]	validation_0-mae:2732.79294
[75]	validation_0-mae:2716.25786
[76]	validation_0-mae:2702.10932
[77]	validation_0-mae:2691.44593
[78]	validation_0-mae:2683.15787
[79]	validation_0-mae:2676.60161
[80]	validation_0-mae:2669.51346
[81]	validation_0-mae:2656.68887
[82]	validation_0-mae:2648.90626
[83]	validation_0-mae:2641.02847
[84]	validation_0-mae:2632.75286
[85]	validation_0-mae:2620.35218
[86]	validation_0-mae:2614.91300
[87]	validation_0-mae:2610.35597
[88]	validation_0-mae:2604.99821
[89]	validation_0-mae:2589.49647
[90]	validation_0-mae:2578.34803
[91]	validation_0-mae:2572.82789
[92]	validation_0-mae:2556.35686
[93]	validation_0-mae:2550.15616
[94]	validation_0-mae:2541.13678
[95]	validation_0-mae:2538.03764
[96]	validation_0-mae:2526.98989
[97]	validation_0-mae:2520.01721
[98]	validation_0-mae:2508.48366
[99]	validation_0-mae:2503.38164
[100]	validation_0-mae:2494.07513
[101]	validation_0-mae:2490.09585
[102]	validation_0-mae:2480.30465
[103]	validation_0-mae:2474.20131
[104]	validation_0-mae:2462.16202
[105]	validation_0-mae:2458.04493
[106]	validation_0-mae:2447.79420
[107]	validation_0-mae:2444.58698
[108]	validation_0-mae:2442.91754
[109]	validation_0-mae:2439.27793
[110]	validation_0-mae:2434.68137
[111]	validation_0-mae:2433.73330
[112]	validation_0-mae:2429.02155
[113]	validation_0-mae:2426.68246
[114]	validation_0-mae:2419.90739
[115]	validation_0-mae:2411.09972
[116]	validation_0-mae:2408.10279
[117]	validation_0-mae:2403.72894
[118]	validation_0-mae:2398.72735
[119]	validation_0-mae:2396.58817
[120]	validation_0-mae:2393.55057
[121]	validation_0-mae:2389.31349
[122]	validation_0-mae:2386.24487
[123]	validation_0-mae:2381.14067
[124]	validation_0-mae:2378.16043
[125]	validation_0-mae:2373.24920
[126]	validation_0-mae:2369.79097
[127]	validation_0-mae:2369.74461
[128]	validation_0-mae:2362.42574
[129]	validation_0-mae:2352.20916
[130]	validation_0-mae:2349.94604
[131]	validation_0-mae:2345.00688
[132]	validation_0-mae:2340.99575
[133]	validation_0-mae:2337.62139
[134]	validation_0-mae:2334.81297
[135]	validation_0-mae:2333.84699
[136]	validation_0-mae:2331.99117
[137]	validation_0-mae:2328.08629
[138]	validation_0-mae:2324.01146
[139]	validation_0-mae:2324.21949
[140]	validation_0-mae:2322.63606
[141]	validation_0-mae:2320.64306
[142]	validation_0-mae:2317.49662
[143]	validation_0-mae:2316.76675
[144]	validation_0-mae:2312.96626
[145]	validation_0-mae:2312.38679
[146]	validation_0-mae:2309.44344
[147]	validation_0-mae:2304.69941
[148]	validation_0-mae:2302.42143
[149]	validation_0-mae:2299.93839
[150]	validation_0-mae:2296.48440
[151]	validation_0-mae:2292.81464
[152]	validation_0-mae:2290.92185
[153]	validation_0-mae:2287.77663
[154]	validation_0-mae:2288.08288
[155]	validation_0-mae:2285.87732
[156]	validation_0-mae:2284.79437
[157]	validation_0-mae:2280.82183
[158]	validation_0-mae:2279.61048
[159]	validation_0-mae:2279.60611
[160]	validation_0-mae:2276.45449
[161]	validation_0-mae:2275.30483
[162]	validation_0-mae:2272.37677
[163]	validation_0-mae:2273.01272
[164]	validation_0-mae:2270.99153
[165]	validation_0-mae:2269.45963
[166]	validation_0-mae:2265.61792
[167]	validation_0-mae:2265.08152
[168]	validation_0-mae:2263.57283
[169]	validation_0-mae:2262.31405
[170]	validation_0-mae:2262.07764
[171]	validation_0-mae:2261.22772
[172]	validation_0-mae:2260.29659
[173]	validation_0-mae:2258.27893
[174]	validation_0-mae:2257.64199
[175]	validation_0-mae:2254.95148
[176]	validation_0-mae:2254.82395
[177]	validation_0-mae:2253.44441
[178]	validation_0-mae:2253.29487
[179]	validation_0-mae:2252.55948
[180]	validation_0-mae:2251.02228
[181]	validation_0-mae:2250.44355
[182]	validation_0-mae:2248.91381
[183]	validation_0-mae:2247.03716
[184]	validation_0-mae:2245.92820
[185]	validation_0-mae:2243.66024
[186]	validation_0-mae:2241.90965
[187]	validation_0-mae:2242.55469
[188]	validation_0-mae:2242.11706
[189]	validation_0-mae:2241.58299
[190]	validation_0-mae:2240.48284
[191]	validation_0-mae:2237.99802
[192]	validation_0-mae:2236.34109
[193]	validation_0-mae:2235.60280
[194]	validation_0-mae:2235.20284
[195]	validation_0-mae:2234.20485
[196]	validation_0-mae:2233.42530
[197]	validation_0-mae:2233.64371
[198]	validation_0-mae:2232.63740
[199]	validation_0-mae:2228.39345
[200]	validation_0-mae:2225.11586
[201]	validation_0-mae:2224.43033
[202]	validation_0-mae:2223.12624
[203]	validation_0-mae:2223.07819
[204]	validation_0-mae:2221.99845
[205]	validation_0-mae:2222.38039
[206]	validation_0-mae:2221.50506
[207]	validation_0-mae:2221.97745
[208]	validation_0-mae:2220.77493
[209]	validation_0-mae:2220.12546
[210]	validation_0-mae:2220.00663
[211]	validation_0-mae:2220.63288
[212]	validation_0-mae:2220.68434
[213]	validation_0-mae:2220.38232
[214]	validation_0-mae:2217.38353
[215]	validation_0-mae:2213.23786
[216]	validation_0-mae:2212.62011
[217]	validation_0-mae:2211.40685
[218]	validation_0-mae:2209.04943
[219]	validation_0-mae:2205.72321
[220]	validation_0-mae:2205.92788
[221]	validation_0-mae:2205.39585
[222]	validation_0-mae:2203.68778
[223]	validation_0-mae:2203.07289
[224]	validation_0-mae:2203.38140
[225]	validation_0-mae:2203.01466
[226]	validation_0-mae:2202.33937
[227]	validation_0-mae:2202.39019
[228]	validation_0-mae:2199.29378
[229]	validation_0-mae:2198.59545
[230]	validation_0-mae:2198.81623
[231]	validation_0-mae:2199.29449
[232]	validation_0-mae:2198.91518
[233]	validation_0-mae:2199.41215
[234]	validation_0-mae:2198.75281
[235]	validation_0-mae:2198.81452
[236]	validation_0-mae:2199.84481
[237]	validation_0-mae:2200.09801
[238]	validation_0-mae:2199.21506
[239]	validation_0-mae:2197.77318
[240]	validation_0-mae:2196.81493
[241]	validation_0-mae:2196.41178
[242]	validation_0-mae:2195.42111
[243]	validation_0-mae:2195.47930
[244]	validation_0-mae:2194.06648
[245]	validation_0-mae:2193.04277
[246]	validation_0-mae:2192.10861
[247]	validation_0-mae:2191.61364
[248]	validation_0-mae:2191.63160
[249]	validation_0-mae:2191.19484
[250]	validation_0-mae:2189.73140
[251]	validation_0-mae:2189.12528
[252]	validation_0-mae:2188.93746
[253]	validation_0-mae:2188.16857
[254]	validation_0-mae:2186.54771
[255]	validation_0-mae:2186.12731
[256]	validation_0-mae:2184.32880
[257]	validation_0-mae:2184.56727
[258]	validation_0-mae:2183.00749
[259]	validation_0-mae:2182.42010
[260]	validation_0-mae:2182.84405
[261]	validation_0-mae:2182.74789
[262]	validation_0-mae:2183.32818
[263]	validation_0-mae:2183.63645
[264]	validation_0-mae:2184.23596
[265]	validation_0-mae:2184.45940
[266]	validation_0-mae:2184.00891
[267]	validation_0-mae:2184.04484
[268]	validation_0-mae:2183.29151
[269]	validation_0-mae:2183.55574
[270]	validation_0-mae:2182.91785
[271]	validation_0-mae:2182.63942
[272]	validation_0-mae:2182.70407
[273]	validation_0-mae:2182.83369
[274]	validation_0-mae:2182.43765
[275]	validation_0-mae:2181.62656
[276]	validation_0-mae:2182.51806
[277]	validation_0-mae:2182.92720
[278]	validation_0-mae:2182.20172
[279]	validation_0-mae:2181.33881
[280]	validation_0-mae:2181.83835
[281]	validation_0-mae:2181.78433
[282]	validation_0-mae:2181.62177
[283]	validation_0-mae:2181.27780
[284]	validation_0-mae:2181.30990
[285]	validation_0-mae:2181.28047
[286]	validation_0-mae:2181.70617
[287]	validation_0-mae:2181.85192
[288]	validation_0-mae:2182.14264
[289]	validation_0-mae:2182.20755
[290]	validation_0-mae:2182.28755
[291]	validation_0-mae:2181.83351
[292]	validation_0-mae:2182.17949
[293]	validation_0-mae:2181.78576
[294]	validation_0-mae:2182.20896
[295]	validation_0-mae:2182.13537
[296]	validation_0-mae:2182.63439
[297]	validation_0-mae:2183.05515
[298]	validation_0-mae:2183.41839
[299]	validation_0-mae:2182.77118
[300]	validation_0-mae:2181.91110
[301]	validation_0-mae:2182.52117
[302]	validation_0-mae:2182.24818
[303]	validation_0-mae:2182.78829
[304]	validation_0-mae:2183.21232
[305]	validation_0-mae:2183.61580
[306]	validation_0-mae:2182.97245
[307]	validation_0-mae:2182.86314
[308]	validation_0-mae:2182.48303
[309]	validation_0-mae:2180.30384
[310]	validation_0-mae:2181.12961
[311]	validation_0-mae:2180.89651
[312]	validation_0-mae:2180.25082
[313]	validation_0-mae:2180.20964
[314]	validation_0-mae:2180.23635
[315]	validation_0-mae:2178.84547
[316]	validation_0-mae:2178.91960
[317]	validation_0-mae:2178.22644
[318]	validation_0-mae:2177.63420
[319]	validation_0-mae:2177.65223
[320]	validation_0-mae:2177.81197
[321]	validation_0-mae:2177.51174
[322]	validation_0-mae:2177.89644
[323]	validation_0-mae:2175.63715
[324]	validation_0-mae:2174.77241
[325]	validation_0-mae:2175.24744
[326]	validation_0-mae:2174.58623
[327]	validation_0-mae:2174.18431
[328]	validation_0-mae:2172.98966
[329]	validation_0-mae:2170.92059
[330]	validation_0-mae:2171.53156
[331]	validation_0-mae:2170.94442
[332]	validation_0-mae:2170.31773
[333]	validation_0-mae:2170.30059
[334]	validation_0-mae:2169.82821
[335]	validation_0-mae:2167.83253
[336]	validation_0-mae:2167.21221
[337]	validation_0-mae:2166.77338
[338]	validation_0-mae:2166.82103
[339]	validation_0-mae:2167.60918
[340]	validation_0-mae:2167.45578
[341]	validation_0-mae:2166.87749
[342]	validation_0-mae:2166.08901
[343]	validation_0-mae:2165.97883
[344]	validation_0-mae:2166.26211
[345]	validation_0-mae:2165.11357
[346]	validation_0-mae:2164.46491
[347]	validation_0-mae:2164.47922
[348]	validation_0-mae:2164.80057
[349]	validation_0-mae:2164.98304
[350]	validation_0-mae:2164.80523
[351]	validation_0-mae:2165.52700
[352]	validation_0-mae:2163.73830
[353]	validation_0-mae:2163.13896
[354]	validation_0-mae:2163.45984
[355]	validation_0-mae:2163.43778
[356]	validation_0-mae:2163.06126
[357]	validation_0-mae:2162.81099
[358]	validation_0-mae:2162.22377
[359]	validation_0-mae:2161.40250
[360]	validation_0-mae:2160.59432
[361]	validation_0-mae:2159.34978
[362]	validation_0-mae:2159.12637
[363]	validation_0-mae:2159.57761
[364]	validation_0-mae:2159.84387
[365]	validation_0-mae:2160.80971
[366]	validation_0-mae:2160.07961
[367]	validation_0-mae:2159.37875
[368]	validation_0-mae:2158.49246
[369]	validation_0-mae:2158.96851
[370]	validation_0-mae:2158.47260
[371]	validation_0-mae:2157.89204
[372]	validation_0-mae:2156.99636
[373]	validation_0-mae:2157.05227
[374]	validation_0-mae:2156.49781
[375]	validation_0-mae:2156.46124
[376]	validation_0-mae:2156.59066
[377]	validation_0-mae:2156.66625
[378]	validation_0-mae:2157.11200
[379]	validation_0-mae:2157.45106
[380]	validation_0-mae:2157.44775
[381]	validation_0-mae:2157.36158
[382]	validation_0-mae:2157.06142
[383]	validation_0-mae:2156.35405
[384]	validation_0-mae:2155.63482
[385]	validation_0-mae:2154.66604
[386]	validation_0-mae:2153.73426
[387]	validation_0-mae:2152.93892
[388]	validation_0-mae:2152.54976
[389]	validation_0-mae:2151.20202
[390]	validation_0-mae:2151.31812
[391]	validation_0-mae:2151.07242
[392]	validation_0-mae:2151.78340
[393]	validation_0-mae:2150.67427
[394]	validation_0-mae:2151.40855
[395]	validation_0-mae:2150.83199
[396]	validation_0-mae:2150.94002
[397]	validation_0-mae:2151.62262
[398]	validation_0-mae:2152.11596
[399]	validation_0-mae:2151.78145
[400]	validation_0-mae:2152.39065
[401]	validation_0-mae:2153.16190
[402]	validation_0-mae:2152.71603
[403]	validation_0-mae:2152.50974
[404]	validation_0-mae:2151.44073
[405]	validation_0-mae:2150.78101
[406]	validation_0-mae:2150.50068
[407]	validation_0-mae:2150.56667
[408]	validation_0-mae:2150.61871
[409]	validation_0-mae:2149.62129
[410]	validation_0-mae:2148.67233
[411]	validation_0-mae:2148.74027
[412]	validation_0-mae:2147.44579
[413]	validation_0-mae:2147.51259
[414]	validation_0-mae:2147.71727
[415]	validation_0-mae:2147.23115
[416]	validation_0-mae:2146.85682
[417]	validation_0-mae:2146.66055
[418]	validation_0-mae:2146.32164
[419]	validation_0-mae:2146.52196
[420]	validation_0-mae:2146.48898
[421]	validation_0-mae:2146.15949
[422]	validation_0-mae:2146.12300
[423]	validation_0-mae:2143.71093
[424]	validation_0-mae:2143.58684
[425]	validation_0-mae:2143.59768
[426]	validation_0-mae:2144.01091
[427]	validation_0-mae:2143.42113
[428]	validation_0-mae:2142.69413
[429]	validation_0-mae:2141.53367
[430]	validation_0-mae:2142.01193
[431]	validation_0-mae:2142.56735
[432]	validation_0-mae:2141.79131
[433]	validation_0-mae:2140.63552
[434]	validation_0-mae:2140.44171
[435]	validation_0-mae:2140.82849
[436]	validation_0-mae:2140.81014
[437]	validation_0-mae:2141.54391
[438]	validation_0-mae:2141.44753
[439]	validation_0-mae:2140.86214
[440]	validation_0-mae:2141.50949
[441]	validation_0-mae:2140.55599
[442]	validation_0-mae:2139.79873
[443]	validation_0-mae:2139.33596
[444]	validation_0-mae:2139.02636
[445]	validation_0-mae:2137.17831
[446]	validation_0-mae:2137.94239
[447]	validation_0-mae:2137.57556
[448]	validation_0-mae:2137.94058
[449]	validation_0-mae:2138.11390
[450]	validation_0-mae:2137.11278
[451]	validation_0-mae:2137.89382
[452]	validation_0-mae:2138.16728
[453]	validation_0-mae:2138.71995
[454]	validation_0-mae:2138.51395
[455]	validation_0-mae:2137.68238
[456]	validation_0-mae:2137.89034
[457]	validation_0-mae:2137.59129
[458]	validation_0-mae:2138.21171
[459]	validation_0-mae:2138.48220
[460]	validation_0-mae:2137.94466
[461]	validation_0-mae:2138.15084
[462]	validation_0-mae:2138.15196
[463]	validation_0-mae:2137.84781
[464]	validation_0-mae:2138.06882
[465]	validation_0-mae:2137.08664
[466]	validation_0-mae:2137.44397
[467]	validation_0-mae:2137.08258
[468]	validation_0-mae:2137.08591
[469]	validation_0-mae:2136.63088
[470]	validation_0-mae:2137.10074
[471]	validation_0-mae:2136.78628
[472]	validation_0-mae:2136.44992
[473]	validation_0-mae:2136.05049
[474]	validation_0-mae:2135.53179
[475]	validation_0-mae:2135.49238
[476]	validation_0-mae:2135.62318
[477]	validation_0-mae:2134.78302
[478]	validation_0-mae:2135.27245
[479]	validation_0-mae:2135.02499
[0]	validation_0-mae:12557.34004
[1]	validation_0-mae:11920.34909
[2]	validation_0-mae:11360.75777
[3]	validation_0-mae:10824.85658
[4]	validation_0-mae:10352.15230
[5]	validation_0-mae:9941.32052
[6]	validation_0-mae:9556.99113
[7]	validation_0-mae:9206.67887
[8]	validation_0-mae:8893.96546
[9]	validation_0-mae:8596.16448
[10]	validation_0-mae:8343.85561
[11]	validation_0-mae:8095.08018
[12]	validation_0-mae:7874.14546
[13]	validation_0-mae:7667.05660
[14]	validation_0-mae:7480.93029

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[0]	validation_0-mae:12670.64047
[1]	validation_0-mae:12110.28970
[2]	validation_0-mae:11591.45301
[3]	validation_0-mae:11107.78796
[4]	validation_0-mae:10678.94904
[5]	validation_0-mae:10260.96831
[6]	validation_0-mae:9887.33858
[7]	validation_0-mae:9558.76363
[8]	validation_0-mae:9226.44071
[9]	validation_0-mae:8920.49947
[0]	validation_0-mae:12779.09350
[1]	validation_0-mae:12311.65087
[2]	validation_0-mae:11879.63227
[3]	validation_0-mae:11469.75264
[4]	validation_0-mae:11090.10889
[5]	validation_0-mae:10734.10347
[6]	validation_0-mae:10414.44387
[7]	validation_0-mae:10119.59172
[8]	validation_0-mae:9861.35515
[9]	validation_0-mae:9600.25872

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[0]	validation_0-mae:12544.97161
[1]	validation_0-mae:11872.53101
[2]	validation_0-mae:11283.19666
[3]	validation_0-mae:10760.64984
[4]	validation_0-mae:10287.45054
[5]	validation_0-mae:9846.43900
[6]	validation_0-mae:9448.80664
[7]	validation_0-mae:9087.68066
[8]	validation_0-mae:8750.02326
[9]	validation_0-mae:8463.83837
[10]	validation_0-mae:8171.92999
[11]	validation_0-mae:7871.60433
[12]	validation_0-mae:7600.06339
[13]	validation_0-mae:7373.41037
[14]	validation_0-mae:7135.27584
[15]	validation_0-mae:6955.20120
[16]	validation_0-mae:6762.97309
[17]	validation_0-mae:6547.42603
[18]	validation_0-mae:6395.17048
[19]	validation_0-mae:6256.61357
[20]	validation_0-mae:6081.18344
[21]	validation_0-mae:5929.30241
[22]	validation_0-mae:5788.01311
[23]	validation_0-mae:5657.40730
[24]	validation_0-mae:5521.20252
[25]	validation_0-mae:5392.47645
[26]	validation_0-mae:5266.31797
[27]	validation_0-mae:5179.33216
[28]	validation_0-mae:5060.99257
[29]	validation_0-mae:4932.15704
[30]	validation_0-mae:4850.74970
[31]	validation_0-mae:4781.56116
[32]	validation_0-mae:4683.25429
[33]	validation_0-mae:4576.43037
[34]	validation_0-mae:4512.89302
[35]	validation_0-mae:4459.45859
[36]	validation_0-mae:4385.02390
[37]	validation_0-mae:4308.85734
[38]	validation_0-mae:4247.47542
[39]	validation_0-mae:4182.44093
[40]	validation_0-mae:4130.95209
[41]	validation_0-mae:4077.41262
[42]	validation_0-mae:4029.08805
[43]	validation_0-mae:3987.69592
[44]	validation_0-mae:3940.61444
[45]	validation_0-mae:3872.23164
[46]	validation_0-mae:3831.72331
[47]	validation_0-mae:3789.11959
[48]	validation_0-mae:3742.31506
[49]	validation_0-mae:3710.51162
[50]	validation_0-mae:3672.31802
[51]	validation_0-mae:3630.95137
[52]	validation_0-mae:3591.67128
[53]	validation_0-mae:3569.21514
[54]	validation_0-mae:3552.46320
[55]	validation_0-mae:3520.18951
[56]	validation_0-mae:3495.60015
[57]	validation_0-mae:3470.70797
[58]	validation_0-mae:3447.55248
[59]	validation_0-mae:3422.03786
[60]	validation_0-mae:3401.49716
[61]	validation_0-mae:3375.62412
[62]	validation_0-mae:3355.67729
[63]	validation_0-mae:3330.48999
[64]	validation_0-mae:3317.57467
[65]	validation_0-mae:3299.67371
[66]	validation_0-mae:3282.88942
[67]	validation_0-mae:3257.68877
[68]	validation_0-mae:3235.05996
[69]	validation_0-mae:3224.83341
[70]	validation_0-mae:3197.04581
[71]	validation_0-mae:3182.84336
[72]	validation_0-mae:3175.38959
[73]	validation_0-mae:3158.30644
[74]	validation_0-mae:3145.58557
[75]	validation_0-mae:3133.58967
[76]	validation_0-mae:3121.22884
[77]	validation_0-mae:3100.47819
[78]	validation_0-mae:3083.16105
[79]	validation_0-mae:3073.12847
[80]	validation_0-mae:3052.71925
[81]	validation_0-mae:3044.43102
[82]	validation_0-mae:3036.85502
[83]	validation_0-mae:3021.18608
[84]	validation_0-mae:3012.61541
[85]	validation_0-mae:2998.61182
[86]	validation_0-mae:2984.43546
[87]	validation_0-mae:2979.55317
[88]	validation_0-mae:2968.51833
[89]	validation_0-mae:2959.60798
[90]	validation_0-mae:2948.57791
[91]	validation_0-mae:2943.88175
[92]	validation_0-mae:2937.05775
[93]	validation_0-mae:2925.31954
[94]	validation_0-mae:2915.62355
[95]	validation_0-mae:2905.26486
[96]	validation_0-mae:2897.04090
[97]	validation_0-mae:2890.71131
[98]	validation_0-mae:2873.42793
[99]	validation_0-mae:2863.80152
[100]	validation_0-mae:2855.71369
[101]	validation_0-mae:2850.01330
[102]	validation_0-mae:2832.77005
[103]	validation_0-mae:2828.45215
[104]	validation_0-mae:2822.15730
[105]	validation_0-mae:2816.38594
[106]	validation_0-mae:2804.95297
[107]	validation_0-mae:2800.89153
[108]	validation_0-mae:2794.02639
[109]	validation_0-mae:2791.97518
[110]	validation_0-mae:2780.56554
[111]	validation_0-mae:2772.52869
[112]	validation_0-mae:2763.86757
[113]	validation_0-mae:2758.04795
[114]	validation_0-mae:2745.61370
[115]	validation_0-mae:2736.67620
[116]	validation_0-mae:2732.22691
[117]	validation_0-mae:2724.34341
[118]	validation_0-mae:2719.56290
[119]	validation_0-mae:2713.17331
[120]	validation_0-mae:2710.04499
[121]	validation_0-mae:2707.24341
[122]	validation_0-mae:2701.47471
[123]	validation_0-mae:2694.83122
[124]	validation_0-mae:2689.10903
[125]	validation_0-mae:2686.24157
[126]	validation_0-mae:2682.12233
[127]	validation_0-mae:2676.37870
[128]	validation_0-mae:2670.68419
[129]	validation_0-mae:2664.54841
[130]	validation_0-mae:2659.88633
[131]	validation_0-mae:2656.14649
[132]	validation_0-mae:2650.53101
[133]	validation_0-mae:2648.07697
[134]	validation_0-mae:2642.51269
[135]	validation_0-mae:2636.07466
[136]	validation_0-mae:2632.54342
[137]	validation_0-mae:2630.72508
[138]	validation_0-mae:2629.10837
[139]	validation_0-mae:2623.93042
[140]	validation_0-mae:2621.08611
[141]	validation_0-mae:2619.40347
[142]	validation_0-mae:2616.77275
[143]	validation_0-mae:2611.79316
[144]	validation_0-mae:2606.41864
[145]	validation_0-mae:2602.48687
[146]	validation_0-mae:2598.42944
[147]	validation_0-mae:2591.82665
[148]	validation_0-mae:2587.86934
[149]	validation_0-mae:2582.07695
[150]	validation_0-mae:2578.66643
[151]	validation_0-mae:2576.72094
[152]	validation_0-mae:2571.80157
[153]	validation_0-mae:2568.17940
[154]	validation_0-mae:2567.40608
[155]	validation_0-mae:2557.82989
[156]	validation_0-mae:2554.30991
[157]	validation_0-mae:2551.61845
[158]	validation_0-mae:2548.86176
[159]	validation_0-mae:2547.77896
[160]	validation_0-mae:2541.74011
[161]	validation_0-mae:2539.00096
[162]	validation_0-mae:2534.35022
[163]	validation_0-mae:2532.00297
[164]	validation_0-mae:2529.94364
[165]	validation_0-mae:2521.75066
[166]	validation_0-mae:2519.32111
[167]	validation_0-mae:2517.59248
[168]	validation_0-mae:2514.45821
[169]	validation_0-mae:2512.60340
[170]	validation_0-mae:2510.68356
[171]	validation_0-mae:2507.65488
[172]	validation_0-mae:2501.65414
[173]	validation_0-mae:2502.49197
[174]	validation_0-mae:2501.61232
[175]	validation_0-mae:2497.28777
[176]	validation_0-mae:2495.72735
[177]	validation_0-mae:2495.75676
[178]	validation_0-mae:2488.65568
[179]	validation_0-mae:2483.01751
[180]	validation_0-mae:2481.42564
[181]	validation_0-mae:2479.22570
[182]	validation_0-mae:2476.07954
[183]	validation_0-mae:2474.62975
[184]	validation_0-mae:2473.13436
[185]	validation_0-mae:2471.16760
[186]	validation_0-mae:2468.79670
[187]	validation_0-mae:2464.63064
[188]	validation_0-mae:2464.16271
[189]	validation_0-mae:2461.51548
[190]	validation_0-mae:2459.68470
[191]	validation_0-mae:2459.31287
[192]	validation_0-mae:2458.05777
[193]	validation_0-mae:2454.30021
[194]	validation_0-mae:2449.58567
[195]	validation_0-mae:2446.90066
[196]	validation_0-mae:2445.80596
[197]	validation_0-mae:2443.51765
[198]	validation_0-mae:2441.24423
[199]	validation_0-mae:2440.15584
[200]	validation_0-mae:2438.61561
[201]	validation_0-mae:2435.24953
[202]	validation_0-mae:2431.55957
[203]	validation_0-mae:2429.68517
[204]	validation_0-mae:2428.72385
[205]	validation_0-mae:2427.62877
[206]	validation_0-mae:2427.57579
[207]	validation_0-mae:2424.53794
[208]	validation_0-mae:2424.67706
[209]	validation_0-mae:2423.02539
[210]	validation_0-mae:2421.28543
[211]	validation_0-mae:2419.28893
[212]	validation_0-mae:2417.52072
[213]	validation_0-mae:2416.74873
[214]	validation_0-mae:2416.13123
[215]	validation_0-mae:2413.87553
[216]	validation_0-mae:2414.57977
[217]	validation_0-mae:2413.16720
[218]	validation_0-mae:2412.94710
[219]	validation_0-mae:2413.86491
[220]	validation_0-mae:2412.23095
[221]	validation_0-mae:2412.32634
[222]	validation_0-mae:2412.83230
[223]	validation_0-mae:2412.12215
[224]	validation_0-mae:2411.11624
[225]	validation_0-mae:2409.78929
[226]	validation_0-mae:2409.78993
[227]	validation_0-mae:2409.09381
[228]	validation_0-mae:2407.53181
[229]	validation_0-mae:2405.71974
[230]	validation_0-mae:2404.56318
[231]	validation_0-mae:2400.92349
[232]	validation_0-mae:2398.54956
[233]	validation_0-mae:2395.80198
[234]	validation_0-mae:2393.71085
[235]	validation_0-mae:2391.24954
[236]	validation_0-mae:2390.72645
[237]	validation_0-mae:2390.01316
[238]	validation_0-mae:2388.93404
[239]	validation_0-mae:2388.72593
[240]	validation_0-mae:2386.88812
[241]	validation_0-mae:2385.78086
[242]	validation_0-mae:2384.94020
[243]	validation_0-mae:2383.40425
[244]	validation_0-mae:2384.06667
[245]	validation_0-mae:2382.54442
[246]	validation_0-mae:2381.63807
[247]	validation_0-mae:2380.66903
[248]	validation_0-mae:2379.76668
[249]	validation_0-mae:2376.52282
[250]	validation_0-mae:2373.73015
[251]	validation_0-mae:2373.15312
[252]	validation_0-mae:2373.27281
[253]	validation_0-mae:2372.28240
[254]	validation_0-mae:2373.31489
[255]	validation_0-mae:2373.19178
[256]	validation_0-mae:2370.28527
[257]	validation_0-mae:2370.37788
[258]	validation_0-mae:2370.58098
[259]	validation_0-mae:2368.89868
[260]	validation_0-mae:2369.34319
[261]	validation_0-mae:2369.61885
[262]	validation_0-mae:2365.37674
[263]	validation_0-mae:2364.23162
[264]	validation_0-mae:2362.34342
[265]	validation_0-mae:2361.95440
[266]	validation_0-mae:2359.78964
[267]	validation_0-mae:2358.41574
[268]	validation_0-mae:2357.12588
[269]	validation_0-mae:2354.76815
[270]	validation_0-mae:2353.35611
[271]	validation_0-mae:2353.47476
[272]	validation_0-mae:2353.02233
[273]	validation_0-mae:2352.46781
[274]	validation_0-mae:2351.36323
[275]	validation_0-mae:2349.03538
[276]	validation_0-mae:2348.88510
[277]	validation_0-mae:2348.87222
[278]	validation_0-mae:2347.19134
[279]	validation_0-mae:2347.20520
[280]	validation_0-mae:2346.75507
[281]	validation_0-mae:2345.07515
[282]	validation_0-mae:2344.54571
[283]	validation_0-mae:2344.63505
[284]	validation_0-mae:2344.23576
[285]	validation_0-mae:2342.02264
[286]	validation_0-mae:2341.88039
[287]	validation_0-mae:2342.24228
[288]	validation_0-mae:2339.67635
[289]	validation_0-mae:2338.84625
[290]	validation_0-mae:2339.02922
[291]	validation_0-mae:2338.24100
[292]	validation_0-mae:2336.63413
[293]	validation_0-mae:2337.13638
[294]	validation_0-mae:2335.88778
[295]	validation_0-mae:2334.81621
[296]	validation_0-mae:2333.62426
[297]	validation_0-mae:2333.03489
[298]	validation_0-mae:2332.50972
[299]	validation_0-mae:2332.15839
[300]	validation_0-mae:2332.03419
[301]	validation_0-mae:2330.43829
[302]	validation_0-mae:2330.36837
[303]	validation_0-mae:2329.36628
[304]	validation_0-mae:2329.53794
[305]	validation_0-mae:2329.66530
[306]	validation_0-mae:2329.53539
[307]	validation_0-mae:2328.73025
[308]	validation_0-mae:2328.84536
[309]	validation_0-mae:2329.98717
[310]	validation_0-mae:2330.00026
[311]	validation_0-mae:2328.49494
[312]	validation_0-mae:2327.61572
[313]	validation_0-mae:2327.20842
[314]	validation_0-mae:2327.49334
[315]	validation_0-mae:2326.22338
[316]	validation_0-mae:2326.31266
[317]	validation_0-mae:2324.55297
[318]	validation_0-mae:2323.81886
[319]	validation_0-mae:2323.68786
[320]	validation_0-mae:2322.98665
[321]	validation_0-mae:2321.63656
[322]	validation_0-mae:2321.35793
[323]	validation_0-mae:2320.74234
[324]	validation_0-mae:2320.86749
[325]	validation_0-mae:2318.12758
[326]	validation_0-mae:2318.28921
[327]	validation_0-mae:2318.56761
[328]	validation_0-mae:2318.96719
[329]	validation_0-mae:2317.88585
[330]	validation_0-mae:2317.46308
[331]	validation_0-mae:2316.13402
[332]	validation_0-mae:2315.74438
[333]	validation_0-mae:2315.78069
[334]	validation_0-mae:2316.37000
[335]	validation_0-mae:2314.74632
[336]	validation_0-mae:2314.25656
[337]	validation_0-mae:2314.29330
[338]	validation_0-mae:2314.25078
[339]	validation_0-mae:2314.15470
[340]	validation_0-mae:2314.52751
[341]	validation_0-mae:2313.97397
[342]	validation_0-mae:2314.30096
[343]	validation_0-mae:2314.34817
[344]	validation_0-mae:2314.30230
[345]	validation_0-mae:2313.69970
[346]	validation_0-mae:2312.78051
[347]	validation_0-mae:2311.95695
[348]	validation_0-mae:2311.54038
[349]	validation_0-mae:2311.10364
[350]	validation_0-mae:2309.99947
[351]	validation_0-mae:2309.93692
[352]	validation_0-mae:2308.59834
[353]	validation_0-mae:2308.45466
[354]	validation_0-mae:2307.74258
[355]	validation_0-mae:2307.95080
[356]	validation_0-mae:2308.32250
[357]	validation_0-mae:2308.23026
[358]	validation_0-mae:2308.36208
[359]	validation_0-mae:2306.40306
[360]	validation_0-mae:2305.66331
[361]	validation_0-mae:2303.98351
[362]	validation_0-mae:2303.22695
[363]	validation_0-mae:2302.40675
[364]	validation_0-mae:2302.14791
[365]	validation_0-mae:2302.04399
[366]	validation_0-mae:2302.42041
[367]	validation_0-mae:2302.22999
[368]	validation_0-mae:2302.00167
[369]	validation_0-mae:2300.93852
[370]	validation_0-mae:2300.98002
[371]	validation_0-mae:2300.97060
[372]	validation_0-mae:2300.89223
[373]	validation_0-mae:2300.09555
[374]	validation_0-mae:2299.68361
[375]	validation_0-mae:2299.43210
[376]	validation_0-mae:2299.10387
[377]	validation_0-mae:2299.67570
[378]	validation_0-mae:2299.56692
[379]	validation_0-mae:2299.61462
[380]	validation_0-mae:2298.31927
[381]	validation_0-mae:2296.76084
[382]	validation_0-mae:2297.71443
[383]	validation_0-mae:2297.92720
[384]	validation_0-mae:2298.54359
[385]	validation_0-mae:2298.43208
[386]	validation_0-mae:2298.40658
[387]	validation_0-mae:2297.86486
[388]	validation_0-mae:2297.99158
[389]	validation_0-mae:2296.23197
[390]	validation_0-mae:2295.10620
[391]	validation_0-mae:2295.72578
[392]	validation_0-mae:2296.65194
[393]	validation_0-mae:2294.54708
[394]	validation_0-mae:2294.46187
[395]	validation_0-mae:2294.62291
[396]	validation_0-mae:2294.03907
[397]	validation_0-mae:2294.76129
[398]	validation_0-mae:2295.38373
[399]	validation_0-mae:2295.86735
[400]	validation_0-mae:2293.94847
[401]	validation_0-mae:2292.96186
[402]	validation_0-mae:2292.60919
[403]	validation_0-mae:2292.70989
[404]	validation_0-mae:2292.24072
[405]	validation_0-mae:2291.95572
[406]	validation_0-mae:2291.19684
[407]	validation_0-mae:2291.49304
[408]	validation_0-mae:2291.69305
[409]	validation_0-mae:2292.41235
[410]	validation_0-mae:2292.21975
[411]	validation_0-mae:2291.90609
[412]	validation_0-mae:2292.03665
[413]	validation_0-mae:2291.65178
[414]	validation_0-mae:2291.46276
[415]	validation_0-mae:2290.87736
[416]	validation_0-mae:2289.88485
[417]	validation_0-mae:2289.64349
[418]	validation_0-mae:2290.16944
[419]	validation_0-mae:2289.54336
[420]	validation_0-mae:2289.32439
[421]	validation_0-mae:2289.46645
[422]	validation_0-mae:2289.45821
[423]	validation_0-mae:2287.89656
[424]	validation_0-mae:2288.14684
[425]	validation_0-mae:2288.05729
[426]	validation_0-mae:2287.69897
[427]	validation_0-mae:2287.11231
[428]	validation_0-mae:2286.63681
[429]	validation_0-mae:2286.83640
[430]	validation_0-mae:2285.35684
[431]	validation_0-mae:2285.02945
[432]	validation_0-mae:2285.08255
[433]	validation_0-mae:2285.68333
[434]	validation_0-mae:2286.15209
[435]	validation_0-mae:2286.19121
[436]	validation_0-mae:2285.09969
[437]	validation_0-mae:2284.76948
[438]	validation_0-mae:2285.12386
[439]	validation_0-mae:2285.72917
[440]	validation_0-mae:2285.19066
[441]	validation_0-mae:2284.92995
[442]	validation_0-mae:2285.23190
[443]	validation_0-mae:2285.17238
[444]	validation_0-mae:2285.19560
[445]	validation_0-mae:2285.31787
[446]	validation_0-mae:2284.17593
[447]	validation_0-mae:2284.41767
[448]	validation_0-mae:2284.74441
[449]	validation_0-mae:2283.90261
[450]	validation_0-mae:2283.00851
[451]	validation_0-mae:2283.00278
[452]	validation_0-mae:2283.34341
[453]	validation_0-mae:2283.14927
[454]	validation_0-mae:2282.76591
[455]	validation_0-mae:2283.57485
[456]	validation_0-mae:2283.06497
[457]	validation_0-mae:2283.23939
[458]	validation_0-mae:2282.07149
[459]	validation_0-mae:2281.88099
[460]	validation_0-mae:2281.87396
[461]	validation_0-mae:2281.72019
[462]	validation_0-mae:2281.50400
[463]	validation_0-mae:2281.53101
[464]	validation_0-mae:2280.80112
[465]	validation_0-mae:2281.15295
[466]	validation_0-mae:2281.20696
[467]	validation_0-mae:2280.43921
[468]	validation_0-mae:2280.04162
[469]	validation_0-mae:2280.42421
[470]	validation_0-mae:2280.68243
[471]	validation_0-mae:2280.71369
[472]	validation_0-mae:2280.84849
[473]	validation_0-mae:2281.20488
[474]	validation_0-mae:2279.29059
[475]	validation_0-mae:2278.73742
[476]	validation_0-mae:2278.93590
[477]	validation_0-mae:2278.88309
[478]	validation_0-mae:2279.52545
[479]	validation_0-mae:2277.42466
[480]	validation_0-mae:2277.85293
[481]	validation_0-mae:2276.59177
[482]	validation_0-mae:2276.22144
[483]	validation_0-mae:2275.91769
[484]	validation_0-mae:2273.93315
[485]	validation_0-mae:2273.91850
[486]	validation_0-mae:2273.11000
[487]	validation_0-mae:2273.24220
[488]	validation_0-mae:2271.98743
[489]	validation_0-mae:2272.36962
[490]	validation_0-mae:2270.91736
[491]	validation_0-mae:2270.58742
[492]	validation_0-mae:2270.16931
[493]	validation_0-mae:2270.08583
[494]	validation_0-mae:2270.42987
[495]	validation_0-mae:2269.43923
[496]	validation_0-mae:2270.15339
[497]	validation_0-mae:2270.41473
[498]	validation_0-mae:2271.51253
[499]	validation_0-mae:2271.16868
[500]	validation_0-mae:2269.35954
[501]	validation_0-mae:2268.31044
[502]	validation_0-mae:2268.53975
[503]	validation_0-mae:2268.70474
[504]	validation_0-mae:2268.98130
[505]	validation_0-mae:2268.42861
[506]	validation_0-mae:2269.51527
[507]	validation_0-mae:2269.04613
[508]	validation_0-mae:2269.60251
[509]	validation_0-mae:2269.68190
[510]	validation_0-mae:2270.06625
[511]	validation_0-mae:2269.87248
[512]	validation_0-mae:2269.26923
[513]	validation_0-mae:2268.92813
[514]	validation_0-mae:2268.69486
[515]	validation_0-mae:2268.25521
[516]	validation_0-mae:2267.65502
[517]	validation_0-mae:2267.09016
[518]	validation_0-mae:2267.21304
[519]	validation_0-mae:2266.60351
[520]	validation_0-mae:2265.87278
[521]	validation_0-mae:2266.11749
[522]	validation_0-mae:2266.76525
[523]	validation_0-mae:2267.33635
[524]	validation_0-mae:2266.71008
[525]	validation_0-mae:2266.35356
[526]	validation_0-mae:2264.77368
[527]	validation_0-mae:2264.80715
[528]	validation_0-mae:2264.76008
[529]	validation_0-mae:2264.00104
[530]	validation_0-mae:2264.43378
[531]	validation_0-mae:2264.45379
[532]	validation_0-mae:2264.02855
[533]	validation_0-mae:2263.89836
[534]	validation_0-mae:2264.57822
[535]	validation_0-mae:2263.92114
[536]	validation_0-mae:2263.91947
[537]	validation_0-mae:2263.73538
[538]	validation_0-mae:2263.47931
[539]	validation_0-mae:2263.38724
[540]	validation_0-mae:2263.33148
[541]	validation_0-mae:2262.80986
[542]	validation_0-mae:2262.51216
[543]	validation_0-mae:2262.27701
[544]	validation_0-mae:2262.57334
[545]	validation_0-mae:2261.77112
[546]	validation_0-mae:2261.29563
[547]	validation_0-mae:2260.98990
[548]	validation_0-mae:2261.51392
[549]	validation_0-mae:2261.56038
[550]	validation_0-mae:2261.49631
[551]	validation_0-mae:2260.97283
[552]	validation_0-mae:2261.14375
[553]	validation_0-mae:2261.55095
[554]	validation_0-mae:2261.86836
[555]	validation_0-mae:2262.29117
[556]	validation_0-mae:2262.97307
[557]	validation_0-mae:2262.85043
[558]	validation_0-mae:2262.91198
[559]	validation_0-mae:2262.87202
[560]	validation_0-mae:2263.23126
[561]	validation_0-mae:2263.30706
[562]	validation_0-mae:2263.07907
[563]	validation_0-mae:2262.58938
[564]	validation_0-mae:2262.31284
[565]	validation_0-mae:2261.17342
[566]	validation_0-mae:2261.19747
[567]	validation_0-mae:2260.84607
[568]	validation_0-mae:2260.85860
[569]	validation_0-mae:2261.24323
[570]	validation_0-mae:2259.61004
[571]	validation_0-mae:2260.28957
[572]	validation_0-mae:2260.82980
[573]	validation_0-mae:2260.03445
[574]	validation_0-mae:2259.65382
[575]	validation_0-mae:2259.68863
[576]	validation_0-mae:2260.48322
[577]	validation_0-mae:2261.29913
[578]	validation_0-mae:2260.30395
[579]	validation_0-mae:2260.01050
[580]	validation_0-mae:2260.40682
[581]	validation_0-mae:2261.28558
[582]	validation_0-mae:2260.28065
[583]	validation_0-mae:2260.83823
[584]	validation_0-mae:2261.11699
[585]	validation_0-mae:2261.11203
[586]	validation_0-mae:2259.69173
[587]	validation_0-mae:2260.78477
[588]	validation_0-mae:2261.01071
[589]	validation_0-mae:2261.37673
[0]	validation_0-mae:12915.02037

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[0]	validation_0-mae:12672.78501
[1]	validation_0-mae:12120.12523
[2]	validation_0-mae:11629.84727
[3]	validation_0-mae:11195.43394
[4]	validation_0-mae:10819.54713
[5]	validation_0-mae:10495.83994
[6]	validation_0-mae:10215.08696
[7]	validation_0-mae:9955.72075
[8]	validation_0-mae:9733.05599
[9]	validation_0-mae:9532.82951
[10]	validation_0-mae:9363.37952
[0]	validation_0-mae:12828.41101
[1]	validation_0-mae:12399.70939
[2]	validation_0-mae:12012.31387
[3]	validation_0-mae:11652.19159
[4]	validation_0-mae:11321.69672
[5]	validation_0-mae:11005.03867
[6]	validation_0-mae:10716.10227
[7]	validation_0-mae:10452.83792
[8]	validation_0-mae:10193.46245
[9]	validation_0-mae:9968.57192
[10]	validation_0-mae:9763.19494
[0]	validation_0-mae:12555.02607
[1]	validation_0-mae:11896.71371
[2]	validation_0-mae:11308.73012
[3]	validation_0-mae:10764.67849
[4]	validation_0-mae:10272.08483
[5]	validation_0-mae:9837.52057
[6]	validation_0-mae:9435.51788
[7]	validation_0-mae:9058.97347
[8]	validation_0-mae:8723.60871

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[9]	validation_0-mae:8411.84960
[10]	validation_0-mae:8136.17139
[11]	validation_0-mae:7835.50230
[12]	validation_0-mae:7581.87868
[13]	validation_0-mae:7316.57377
[14]	validation_0-mae:7089.18343
[15]	validation_0-mae:6833.32514
[16]	validation_0-mae:6653.00148
[17]	validation_0-mae:6451.88454
[18]	validation_0-mae:6277.82235
[19]	validation_0-mae:6092.57055
[20]	validation_0-mae:5927.10032
[21]	validation_0-mae:5764.75434
[22]	validation_0-mae:5628.51212
[23]	validation_0-mae:5488.78407
[24]	validation_0-mae:5343.82145
[25]	validation_0-mae:5216.07186
[26]	validation_0-mae:5085.46781
[27]	validation_0-mae:4961.31759
[28]	validation_0-mae:4845.02404
[29]	validation_0-mae:4744.44452
[30]	validation_0-mae:4640.68682
[31]	validation_0-mae:4559.91259
[32]	validation_0-mae:4461.15486
[33]	validation_0-mae:4372.06628
[34]	validation_0-mae:4284.73797
[35]	validation_0-mae:4227.59090
[36]	validation_0-mae:4151.87489
[37]	validation_0-mae:4084.33851
[38]	validation_0-mae:4020.90042
[39]	validation_0-mae:3954.97200
[40]	validation_0-mae:3902.96555
[41]	validation_0-mae:3840.96720
[42]	validation_0-mae:3783.01459
[43]	validation_0-mae:3731.54001
[44]	validation_0-mae:3689.08605
[45]	validation_0-mae:3619.99583
[46]	validation_0-mae:3574.19921
[47]	validation_0-mae:3534.19452
[48]	validation_0-mae:3503.44926
[49]	validation_0-mae:3467.56185
[50]	validation_0-mae:3431.06642
[51]	validation_0-mae:3404.22641
[52]	validation_0-mae:3371.17838
[53]	validation_0-mae:3327.65172
[54]	validation_0-mae:3302.11727
[55]	validation_0-mae:3274.99582
[56]	validation_0-mae:3241.51460
[57]	validation_0-mae:3199.99914
[58]	validation_0-mae:3177.36590
[59]	validation_0-mae:3152.94285
[60]	validation_0-mae:3125.90001
[61]	validation_0-mae:3108.86298
[62]	validation_0-mae:3090.64212
[63]	validation_0-mae:3070.35039
[64]	validation_0-mae:3048.65736
[65]	validation_0-mae:3030.91319
[66]	validation_0-mae:3010.86584
[67]	validation_0-mae:2989.68241
[68]	validation_0-mae:2961.03415
[69]	validation_0-mae:2950.22720
[70]	validation_0-mae:2932.35595
[71]	validation_0-mae:2918.53242
[72]	validation_0-mae:2893.28056
[73]	validation_0-mae:2877.88124
[74]	validation_0-mae:2862.57898
[75]	validation_0-mae:2851.11267
[76]	validation_0-mae:2846.45079
[77]	validation_0-mae:2825.87180
[78]	validation_0-mae:2812.99747
[79]	validation_0-mae:2803.46842
[80]	validation_0-mae:2797.17164
[81]	validation_0-mae:2788.50159
[82]	validation_0-mae:2779.90089
[83]	validation_0-mae:2759.70852
[84]	validation_0-mae:2745.15109
[85]	validation_0-mae:2733.23648
[86]	validation_0-mae:2721.06214
[87]	validation_0-mae:2712.71489
[88]	validation_0-mae:2704.82274
[89]	validation_0-mae:2692.81333
[90]	validation_0-mae:2689.44403
[91]	validation_0-mae:2682.74201
[92]	validation_0-mae:2676.16649
[93]	validation_0-mae:2667.23095
[94]	validation_0-mae:2662.66530
[95]	validation_0-mae:2651.48497
[96]	validation_0-mae:2642.65643
[97]	validation_0-mae:2630.21856
[98]	validation_0-mae:2625.29049
[99]	validation_0-mae:2622.30427
[100]	validation_0-mae:2617.20528
[101]	validation_0-mae:2611.13147
[102]	validation_0-mae:2604.47859
[103]	validation_0-mae:2600.25375
[104]	validation_0-mae:2595.43216
[105]	validation_0-mae:2584.74583
[106]	validation_0-mae:2581.85553
[107]	validation_0-mae:2573.93603
[108]	validation_0-mae:2567.59698
[109]	validation_0-mae:2559.37639
[110]	validation_0-mae:2552.52105
[111]	validation_0-mae:2544.36555
[112]	validation_0-mae:2536.21849
[113]	validation_0-mae:2534.36131
[114]	validation_0-mae:2526.96782
[115]	validation_0-mae:2521.29323
[116]	validation_0-mae:2516.76847
[117]	validation_0-mae:2508.07869
[118]	validation_0-mae:2501.25219
[119]	validation_0-mae:2495.37582
[120]	validation_0-mae:2488.69189
[121]	validation_0-mae:2481.36455
[122]	validation_0-mae:2474.77123
[123]	validation_0-mae:2469.85346
[124]	validation_0-mae:2467.85740
[125]	validation_0-mae:2463.17075
[126]	validation_0-mae:2456.11808
[127]	validation_0-mae:2452.71590
[128]	validation_0-mae:2446.44008
[129]	validation_0-mae:2441.26652
[130]	validation_0-mae:2435.75647
[131]	validation_0-mae:2430.90277
[132]	validation_0-mae:2427.42456
[133]	validation_0-mae:2424.65744
[134]	validation_0-mae:2425.02584
[135]	validation_0-mae:2422.61339
[136]	validation_0-mae:2418.30491
[137]	validation_0-mae:2413.46816
[138]	validation_0-mae:2412.60502
[139]	validation_0-mae:2409.93906
[140]	validation_0-mae:2407.26234
[141]	validation_0-mae:2402.56393
[142]	validation_0-mae:2398.77902
[143]	validation_0-mae:2397.66601
[144]	validation_0-mae:2396.64635
[145]	validation_0-mae:2393.79136
[146]	validation_0-mae:2394.23421
[147]	validation_0-mae:2391.64711
[148]	validation_0-mae:2387.05406
[149]	validation_0-mae:2385.22730
[150]	validation_0-mae:2384.72267
[151]	validation_0-mae:2381.88467
[152]	validation_0-mae:2379.56951
[153]	validation_0-mae:2376.86098
[154]	validation_0-mae:2376.11396
[155]	validation_0-mae:2372.66984
[156]	validation_0-mae:2373.10644
[157]	validation_0-mae:2368.77718
[158]	validation_0-mae:2366.12203
[159]	validation_0-mae:2363.78627
[160]	validation_0-mae:2358.58254
[161]	validation_0-mae:2354.24299
[162]	validation_0-mae:2353.46299
[163]	validation_0-mae:2351.81862
[164]	validation_0-mae:2352.64390
[165]	validation_0-mae:2349.13280
[166]	validation_0-mae:2347.45839
[167]	validation_0-mae:2344.57061
[168]	validation_0-mae:2340.48442
[169]	validation_0-mae:2338.55808
[170]	validation_0-mae:2335.17886
[171]	validation_0-mae:2333.44862
[172]	validation_0-mae:2332.57662
[173]	validation_0-mae:2329.91941
[174]	validation_0-mae:2326.34637
[175]	validation_0-mae:2325.94894
[176]	validation_0-mae:2324.61180
[177]	validation_0-mae:2319.32861
[178]	validation_0-mae:2318.25172
[179]	validation_0-mae:2316.55697
[180]	validation_0-mae:2312.63865
[181]	validation_0-mae:2310.75404
[182]	validation_0-mae:2308.57711
[183]	validation_0-mae:2308.30133
[184]	validation_0-mae:2306.85205
[185]	validation_0-mae:2306.62676
[186]	validation_0-mae:2306.46157
[187]	validation_0-mae:2305.42546
[188]	validation_0-mae:2302.33052
[189]	validation_0-mae:2301.60787
[190]	validation_0-mae:2298.73368
[191]	validation_0-mae:2297.15778
[192]	validation_0-mae:2295.76694
[193]	validation_0-mae:2295.91864
[194]	validation_0-mae:2295.67156
[195]	validation_0-mae:2294.24106
[196]	validation_0-mae:2292.67811
[197]	validation_0-mae:2291.92498
[198]	validation_0-mae:2288.31779
[199]	validation_0-mae:2287.10249
[200]	validation_0-mae:2286.12800
[201]	validation_0-mae:2284.80786
[202]	validation_0-mae:2283.87853
[203]	validation_0-mae:2281.94153
[204]	validation_0-mae:2281.03186
[205]	validation_0-mae:2281.83652
[206]	validation_0-mae:2282.86291
[207]	validation_0-mae:2281.85947
[208]	validation_0-mae:2280.42535
[209]	validation_0-mae:2278.71506
[210]	validation_0-mae:2278.13244
[211]	validation_0-mae:2278.44413
[212]	validation_0-mae:2277.46026
[213]	validation_0-mae:2275.52508
[214]	validation_0-mae:2274.66262
[215]	validation_0-mae:2273.44983
[216]	validation_0-mae:2270.66563
[217]	validation_0-mae:2269.94051
[218]	validation_0-mae:2268.49168
[219]	validation_0-mae:2266.21266
[220]	validation_0-mae:2266.83614
[221]	validation_0-mae:2265.71648
[222]	validation_0-mae:2263.88810
[223]	validation_0-mae:2262.65455
[224]	validation_0-mae:2262.42863
[225]	validation_0-mae:2261.96359
[226]	validation_0-mae:2260.67328
[227]	validation_0-mae:2259.58753
[228]	validation_0-mae:2258.56026
[229]	validation_0-mae:2257.61924
[230]	validation_0-mae:2257.43373
[231]	validation_0-mae:2256.59435
[232]	validation_0-mae:2255.02232
[233]	validation_0-mae:2254.36244
[234]	validation_0-mae:2254.18175
[235]	validation_0-mae:2254.20313
[236]	validation_0-mae:2253.86382
[237]	validation_0-mae:2253.36384
[238]	validation_0-mae:2253.67867
[239]	validation_0-mae:2253.55573
[240]	validation_0-mae:2252.76047
[241]	validation_0-mae:2252.31534
[242]	validation_0-mae:2251.41790
[243]	validation_0-mae:2250.38060
[244]	validation_0-mae:2249.95405
[245]	validation_0-mae:2248.88637
[246]	validation_0-mae:2247.77308
[247]	validation_0-mae:2247.67996
[248]	validation_0-mae:2245.95472
[249]	validation_0-mae:2245.81203
[250]	validation_0-mae:2245.76815
[251]	validation_0-mae:2242.55643
[252]	validation_0-mae:2242.06387
[253]	validation_0-mae:2240.72316
[254]	validation_0-mae:2239.38682
[255]	validation_0-mae:2237.60454
[256]	validation_0-mae:2235.80254
[257]	validation_0-mae:2235.68131
[258]	validation_0-mae:2234.95078
[259]	validation_0-mae:2235.35900
[260]	validation_0-mae:2233.86903
[261]	validation_0-mae:2233.29011
[262]	validation_0-mae:2230.03607
[263]	validation_0-mae:2229.69409
[264]	validation_0-mae:2229.43748
[265]	validation_0-mae:2229.49239
[266]	validation_0-mae:2229.47344
[267]	validation_0-mae:2229.31379
[268]	validation_0-mae:2229.23734
[269]	validation_0-mae:2229.36655
[270]	validation_0-mae:2229.60060
[271]	validation_0-mae:2228.23471
[272]	validation_0-mae:2228.66308
[273]	validation_0-mae:2228.93955
[274]	validation_0-mae:2228.02307
[275]	validation_0-mae:2226.44673
[276]	validation_0-mae:2223.60508
[277]	validation_0-mae:2223.78544
[278]	validation_0-mae:2221.76461
[279]	validation_0-mae:2221.06889
[280]	validation_0-mae:2220.12834
[281]	validation_0-mae:2220.23947
[282]	validation_0-mae:2218.88120
[283]	validation_0-mae:2218.35344
[284]	validation_0-mae:2218.12216
[285]	validation_0-mae:2217.63981
[286]	validation_0-mae:2217.43189
[287]	validation_0-mae:2216.68616
[288]	validation_0-mae:2216.26602
[289]	validation_0-mae:2215.98679
[290]	validation_0-mae:2215.60380
[291]	validation_0-mae:2214.35803
[292]	validation_0-mae:2212.95767
[293]	validation_0-mae:2212.87270
[294]	validation_0-mae:2212.44647
[295]	validation_0-mae:2211.54374
[296]	validation_0-mae:2211.27474
[297]	validation_0-mae:2210.13681
[298]	validation_0-mae:2208.73216
[299]	validation_0-mae:2207.62083
[300]	validation_0-mae:2208.05159
[301]	validation_0-mae:2207.38831
[302]	validation_0-mae:2206.45385
[303]	validation_0-mae:2205.48100
[304]	validation_0-mae:2205.16223
[305]	validation_0-mae:2204.72361
[306]	validation_0-mae:2204.94181
[307]	validation_0-mae:2204.73778
[308]	validation_0-mae:2205.18606
[309]	validation_0-mae:2204.90553
[310]	validation_0-mae:2204.47357
[311]	validation_0-mae:2203.56299
[312]	validation_0-mae:2204.49018
[313]	validation_0-mae:2205.83670
[314]	validation_0-mae:2205.66887
[315]	validation_0-mae:2203.25995
[316]	validation_0-mae:2202.35827
[317]	validation_0-mae:2202.41619
[318]	validation_0-mae:2202.10011
[319]	validation_0-mae:2202.08672
[320]	validation_0-mae:2202.22567
[321]	validation_0-mae:2203.17985
[322]	validation_0-mae:2202.70445
[323]	validation_0-mae:2202.82363
[324]	validation_0-mae:2203.09432
[325]	validation_0-mae:2202.58158
[326]	validation_0-mae:2203.16806
[327]	validation_0-mae:2203.04005
[328]	validation_0-mae:2202.93076
[329]	validation_0-mae:2202.43753
[330]	validation_0-mae:2203.10916
[331]	validation_0-mae:2202.10063
[332]	validation_0-mae:2201.19324
[333]	validation_0-mae:2200.88521
[334]	validation_0-mae:2200.28044
[335]	validation_0-mae:2200.76489
[336]	validation_0-mae:2200.04652
[337]	validation_0-mae:2200.24181
[338]	validation_0-mae:2198.92631
[339]	validation_0-mae:2198.96113
[340]	validation_0-mae:2198.66206
[341]	validation_0-mae:2198.61941
[342]	validation_0-mae:2199.42424
[343]	validation_0-mae:2197.99973
[344]	validation_0-mae:2196.93264
[345]	validation_0-mae:2197.17983
[346]	validation_0-mae:2196.38351
[347]	validation_0-mae:2196.37553
[348]	validation_0-mae:2196.82474
[349]	validation_0-mae:2196.92337
[350]	validation_0-mae:2196.56978
[351]	validation_0-mae:2196.29973
[352]	validation_0-mae:2196.43079
[353]	validation_0-mae:2196.92382
[354]	validation_0-mae:2197.36875
[355]	validation_0-mae:2196.95722
[356]	validation_0-mae:2196.75631
[357]	validation_0-mae:2196.43589
[358]	validation_0-mae:2197.22270
[359]	validation_0-mae:2198.08715
[360]	validation_0-mae:2197.94700
[361]	validation_0-mae:2198.33118
[362]	validation_0-mae:2197.41982
[363]	validation_0-mae:2196.73086
[364]	validation_0-mae:2196.86549
[365]	validation_0-mae:2196.51905
[366]	validation_0-mae:2197.06001
[367]	validation_0-mae:2194.37076
[368]	validation_0-mae:2194.47909
[369]	validation_0-mae:2194.65779
[370]	validation_0-mae:2193.37451
[371]	validation_0-mae:2191.46601
[372]	validation_0-mae:2191.10652
[373]	validation_0-mae:2190.80605
[374]	validation_0-mae:2189.30922
[375]	validation_0-mae:2189.61162
[376]	validation_0-mae:2190.05821
[377]	validation_0-mae:2189.46565
[378]	validation_0-mae:2189.79487
[379]	validation_0-mae:2189.90912
[380]	validation_0-mae:2190.48823
[381]	validation_0-mae:2190.67636
[382]	validation_0-mae:2190.06217
[383]	validation_0-mae:2190.00044
[384]	validation_0-mae:2189.29179
[385]	validation_0-mae:2188.99493
[386]	validation_0-mae:2188.29717
[387]	validation_0-mae:2187.97290
[388]	validation_0-mae:2186.72800
[389]	validation_0-mae:2186.94232
[390]	validation_0-mae:2186.54890
[391]	validation_0-mae:2185.73275
[392]	validation_0-mae:2185.14899
[393]	validation_0-mae:2185.22849
[394]	validation_0-mae:2184.06569
[395]	validation_0-mae:2182.46115
[396]	validation_0-mae:2180.39028
[397]	validation_0-mae:2180.32048
[398]	validation_0-mae:2178.90615
[399]	validation_0-mae:2179.01393
[400]	validation_0-mae:2178.14037
[401]	validation_0-mae:2177.97187
[402]	validation_0-mae:2177.69801
[403]	validation_0-mae:2177.22176
[404]	validation_0-mae:2177.23394
[405]	validation_0-mae:2176.14519
[406]	validation_0-mae:2175.41632
[407]	validation_0-mae:2175.63119
[408]	validation_0-mae:2175.83195
[409]	validation_0-mae:2176.24103
[410]	validation_0-mae:2176.63820
[411]	validation_0-mae:2176.00044
[412]	validation_0-mae:2176.93924
[413]	validation_0-mae:2175.45627
[414]	validation_0-mae:2174.70394
[415]	validation_0-mae:2172.41664
[416]	validation_0-mae:2171.42921
[417]	validation_0-mae:2171.84664
[418]	validation_0-mae:2171.35857
[419]	validation_0-mae:2168.80213
[420]	validation_0-mae:2168.31955
[421]	validation_0-mae:2168.58364
[422]	validation_0-mae:2167.99318
[423]	validation_0-mae:2167.01873
[424]	validation_0-mae:2165.66461
[425]	validation_0-mae:2165.73609
[426]	validation_0-mae:2166.47904
[427]	validation_0-mae:2165.91813
[428]	validation_0-mae:2165.52565
[429]	validation_0-mae:2165.28659
[430]	validation_0-mae:2164.78274
[431]	validation_0-mae:2164.75439
[432]	validation_0-mae:2164.28216
[433]	validation_0-mae:2162.38030
[434]	validation_0-mae:2161.12576
[435]	validation_0-mae:2160.52789
[436]	validation_0-mae:2160.16691
[437]	validation_0-mae:2160.26791
[438]	validation_0-mae:2160.28342
[439]	validation_0-mae:2159.36964
[440]	validation_0-mae:2159.61213
[441]	validation_0-mae:2158.19697
[442]	validation_0-mae:2157.76731
[443]	validation_0-mae:2157.56282
[444]	validation_0-mae:2157.15579
[445]	validation_0-mae:2157.64104
[446]	validation_0-mae:2156.90273
[447]	validation_0-mae:2156.31791
[448]	validation_0-mae:2156.28139
[449]	validation_0-mae:2156.12894
[450]	validation_0-mae:2156.66313
[451]	validation_0-mae:2156.84436
[452]	validation_0-mae:2156.43577
[453]	validation_0-mae:2154.21494
[454]	validation_0-mae:2154.59217
[455]	validation_0-mae:2154.02500
[456]	validation_0-mae:2153.08060
[457]	validation_0-mae:2151.88729
[458]	validation_0-mae:2150.75047
[459]	validation_0-mae:2151.75598
[460]	validation_0-mae:2151.58305
[461]	validation_0-mae:2150.27795
[462]	validation_0-mae:2150.21395
[463]	validation_0-mae:2150.50269
[464]	validation_0-mae:2149.99369
[465]	validation_0-mae:2149.58593
[466]	validation_0-mae:2149.49644
[467]	validation_0-mae:2149.72784
[468]	validation_0-mae:2150.10103
[469]	validation_0-mae:2150.13633
[470]	validation_0-mae:2150.27111
[471]	validation_0-mae:2150.25705
[472]	validation_0-mae:2149.98227
[473]	validation_0-mae:2149.62594
[474]	validation_0-mae:2149.73545
[475]	validation_0-mae:2150.18283
[476]	validation_0-mae:2150.41158
[477]	validation_0-mae:2150.04707
[478]	validation_0-mae:2149.66410
[479]	validation_0-mae:2149.71411
[480]	validation_0-mae:2149.50652
[481]	validation_0-mae:2149.44454
[482]	validation_0-mae:2149.64536
[483]	validation_0-mae:2147.73054
[484]	validation_0-mae:2148.10104
[485]	validation_0-mae:2148.23091
[486]	validation_0-mae:2147.79919
[487]	validation_0-mae:2147.43463
[488]	validation_0-mae:2147.35919
[489]	validation_0-mae:2147.25824
[490]	validation_0-mae:2147.12703
[491]	validation_0-mae:2146.62417
[492]	validation_0-mae:2146.65600
[493]	validation_0-mae:2147.10136
[494]	validation_0-mae:2146.50662
[495]	validation_0-mae:2145.61889
[496]	validation_0-mae:2145.86825
[497]	validation_0-mae:2145.32565
[498]	validation_0-mae:2144.99062
[499]	validation_0-mae:2145.12415
[500]	validation_0-mae:2144.75392
[501]	validation_0-mae:2144.14700
[502]	validation_0-mae:2144.21010
[503]	validation_0-mae:2143.02706
[504]	validation_0-mae:2142.75624
[505]	validation_0-mae:2142.73787
[506]	validation_0-mae:2142.67313
[507]	validation_0-mae:2142.21707
[508]	validation_0-mae:2142.13980
[509]	validation_0-mae:2141.51383
[510]	validation_0-mae:2141.80451
[511]	validation_0-mae:2141.10276
[512]	validation_0-mae:2140.12049
[513]	validation_0-mae:2138.84585
[514]	validation_0-mae:2138.51596
[515]	validation_0-mae:2138.25165
[516]	validation_0-mae:2138.25328
[517]	validation_0-mae:2137.86504
[518]	validation_0-mae:2137.64627
[519]	validation_0-mae:2137.38856
[520]	validation_0-mae:2137.42002
[521]	validation_0-mae:2137.77328
[522]	validation_0-mae:2137.16810
[523]	validation_0-mae:2137.24157
[524]	validation_0-mae:2137.11656
[525]	validation_0-mae:2137.26771
[526]	validation_0-mae:2137.69597
[527]	validation_0-mae:2137.86524
[528]	validation_0-mae:2137.61978
[529]	validation_0-mae:2137.20894
[530]	validation_0-mae:2136.23094
[531]	validation_0-mae:2136.62312
[532]	validation_0-mae:2136.65103
[533]	validation_0-mae:2136.22687
[534]	validation_0-mae:2136.15715
[535]	validation_0-mae:2136.03549
[536]	validation_0-mae:2135.69072
[537]	validation_0-mae:2135.81337
[538]	validation_0-mae:2135.81690
[539]	validation_0-mae:2136.04855
[540]	validation_0-mae:2136.09809
[541]	validation_0-mae:2135.91410
[542]	validation_0-mae:2135.00232
[543]	validation_0-mae:2135.49588
[544]	validation_0-mae:2135.76174
[545]	validation_0-mae:2136.27825
[546]	validation_0-mae:2136.13723
[547]	validation_0-mae:2135.94117
[548]	validation_0-mae:2136.54570
[549]	validation_0-mae:2136.56714
[550]	validation_0-mae:2136.32862
[551]	validation_0-mae:2136.51780
[552]	validation_0-mae:2136.69955
[553]	validation_0-mae:2135.54113
[554]	validation_0-mae:2135.81505
[555]	validation_0-mae:2135.65911
[556]	validation_0-mae:2134.58952
[557]	validation_0-mae:2134.74482
[558]	validation_0-mae:2133.93018
[559]	validation_0-mae:2133.96638
[560]	validation_0-mae:2133.22068
[561]	validation_0-mae:2133.24257
[562]	validation_0-mae:2132.75707
[563]	validation_0-mae:2132.72701
[564]	validation_0-mae:2132.90654
[565]	validation_0-mae:2132.75231
[566]	validation_0-mae:2132.33635
[567]	validation_0-mae:2132.18637
[568]	validation_0-mae:2131.97909
[569]	validation_0-mae:2131.73725
[570]	validation_0-mae:2132.02265
[571]	validation_0-mae:2132.21835
[572]	validation_0-mae:2132.65821
[573]	validation_0-mae:2132.54478
[574]	validation_0-mae:2132.37467
[575]	validation_0-mae:2132.25945
[576]	validation_0-mae:2131.80060
[577]	validation_0-mae:2132.06557
[578]	validation_0-mae:2132.51065
[579]	validation_0-mae:2132.31544
[580]	validation_0-mae:2131.89405
[581]	validation_0-mae:2132.09573
[582]	validation_0-mae:2132.35092
[583]	validation_0-mae:2131.72719
[584]	validation_0-mae:2132.44204
[585]	validation_0-mae:2133.00095
[586]	validation_0-mae:2132.08404
[587]	validation_0-mae:2132.04452
[588]	validation_0-mae:2131.81198
[589]	validation_0-mae:2131.96097
[590]	validation_0-mae:2132.09491
[591]	validation_0-mae:2131.83970
[592]	validation_0-mae:2131.60678
[593]	validation_0-mae:2131.48898
[594]	validation_0-mae:2130.89125
[595]	validation_0-mae:2130.98349
[596]	validation_0-mae:2131.37672
[597]	validation_0-mae:2131.48530
[598]	validation_0-mae:2130.44804

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[42]	validation_0-mae:3773.07064
[43]	validation_0-mae:3714.78650
[44]	validation_0-mae:3663.89928
[45]	validation_0-mae:3618.48705
[46]	validation_0-mae:3581.96210
[47]	validation_0-mae:3531.60636
[48]	validation_0-mae:3490.49871
[49]	validation_0-mae:3452.32462
[50]	validation_0-mae:3416.39099
[51]	validation_0-mae:3383.71990
[52]	validation_0-mae:3348.41084
[53]	validation_0-mae:3319.42885
[54]	validation_0-mae:3282.99339
[55]	validation_0-mae:3257.55880
[56]	validation_0-mae:3231.13793
[57]	validation_0-mae:3210.16301
[58]	validation_0-mae:3177.15357
[59]	validation_0-mae:3155.83439
[60]	validation_0-mae:3124.29379
[61]	validation_0-mae:3100.55010
[62]	validation_0-mae:3082.79820
[63]	validation_0-mae:3065.74061
[64]	validation_0-mae:3051.34667
[65]	validation_0-mae:3038.66485
[66]	validation_0-mae:3021.75634
[67]	validation_0-mae:2993.62158
[68]	validation_0-mae:2980.28451
[69]	validation_0-mae:2966.66263
[70]	validation_0-mae:2941.57084
[71]	validation_0-mae:2932.58608
[72]	validation_0-mae:2920.04167
[73]	validation_0-mae:2902.38046
[74]	validation_0-mae:2882.15457
[75]	validation_0-mae:2867.47045
[76]	validation_0-mae:2853.15261
[77]	validation_0-mae:2837.94939
[78]	validation_0-mae:2831.34480
[79]	validation_0-mae:2820.09305
[80]	validation_0-mae:2803.80060
[81]	validation_0-mae:2785.16687
[82]	validation_0-mae:2774.39278
[83]	validation_0-mae:2767.30835
[84]	validation_0-mae:2757.78616
[85]	validation_0-mae:2746.03997
[86]	validation_0-mae:2737.33067
[87]	validation_0-mae:2731.49875
[88]	validation_0-mae:2722.01605
[89]	validation_0-mae:2711.33361
[90]	validation_0-mae:2700.47101
[91]	validation_0-mae:2691.32398
[92]	validation_0-mae:2685.26132
[93]	validation_0-mae:2671.45580
[94]	validation_0-mae:2661.43435
[95]	validation_0-mae:2655.90843
[96]	validation_0-mae:2642.28589
[97]	validation_0-mae:2635.99022
[98]	validation_0-mae:2627.48415
[99]	validation_0-mae:2620.93040
[100]	validation_0-mae:2606.30621
[101]	validation_0-mae:2599.16814
[102]	validation_0-mae:2589.23162
[103]	validation_0-mae:2582.46190
[104]	validation_0-mae:2580.46720
[105]	validation_0-mae:2566.60719
[106]	validation_0-mae:2560.80037
[107]	validation_0-mae:2556.18409
[108]	validation_0-mae:2552.93730
[109]	validation_0-mae:2545.35810
[110]	validation_0-mae:2534.70130
[111]	validation_0-mae:2527.58390
[112]	validation_0-mae:2522.56958
[113]	validation_0-mae:2517.40346
[114]	validation_0-mae:2511.21602
[115]	validation_0-mae:2502.45582
[116]	validation_0-mae:2496.12553
[117]	validation_0-mae:2490.62511
[118]	validation_0-mae:2489.71747
[119]	validation_0-mae:2482.80443
[120]	validation_0-mae:2478.54311
[121]	validation_0-mae:2475.47279
[122]	validation_0-mae:2465.05384
[123]	validation_0-mae:2462.63335
[124]	validation_0-mae:2458.18581
[125]	validation_0-mae:2457.61613
[126]	validation_0-mae:2454.37735
[127]	validation_0-mae:2447.58875
[128]	validation_0-mae:2444.05930
[129]	validation_0-mae:2441.32640
[130]	validation_0-mae:2439.34933
[131]	validation_0-mae:2431.25274
[132]	validation_0-mae:2424.87203
[133]	validation_0-mae:2420.48361
[134]	validation_0-mae:2416.14877
[135]	validation_0-mae:2410.02270
[136]	validation_0-mae:2406.88445
[137]	validation_0-mae:2404.22995
[138]	validation_0-mae:2401.80647
[139]	validation_0-mae:2398.73550
[140]	validation_0-mae:2395.48562
[141]	validation_0-mae:2389.16171
[142]	validation_0-mae:2381.89020
[143]	validation_0-mae:2379.03757
[144]	validation_0-mae:2374.46191
[145]	validation_0-mae:2371.38632
[146]	validation_0-mae:2368.63573
[147]	validation_0-mae:2364.45337
[148]	validation_0-mae:2363.49719
[149]	validation_0-mae:2360.93121
[150]	validation_0-mae:2359.16072
[151]	validation_0-mae:2357.74089
[152]	validation_0-mae:2354.16719
[153]	validation_0-mae:2353.43387
[154]	validation_0-mae:2350.51880
[155]	validation_0-mae:2349.12770
[156]	validation_0-mae:2347.67408
[157]	validation_0-mae:2346.03937
[158]	validation_0-mae:2346.32014
[159]	validation_0-mae:2344.69351
[160]	validation_0-mae:2344.29935
[161]	validation_0-mae:2343.22386
[162]	validation_0-mae:2339.39948
[163]	validation_0-mae:2335.79734
[164]	validation_0-mae:2335.95912
[165]	validation_0-mae:2335.74484
[166]	validation_0-mae:2331.21097
[167]	validation_0-mae:2329.98227
[168]	validation_0-mae:2329.23118
[169]	validation_0-mae:2328.88903
[170]	validation_0-mae:2324.57960
[171]	validation_0-mae:2324.00456
[172]	validation_0-mae:2323.11986
[173]	validation_0-mae:2321.01670
[174]	validation_0-mae:2319.95341
[175]	validation_0-mae:2320.20505
[176]	validation_0-mae:2319.71183
[177]	validation_0-mae:2316.14358
[178]	validation_0-mae:2314.96013
[179]	validation_0-mae:2311.45984
[180]	validation_0-mae:2311.24709
[181]	validation_0-mae:2308.35977
[182]	validation_0-mae:2307.87626
[183]	validation_0-mae:2305.38187
[184]	validation_0-mae:2304.01059
[185]	validation_0-mae:2302.58639
[186]	validation_0-mae:2300.24134
[187]	validation_0-mae:2298.49965
[188]	validation_0-mae:2297.49460
[189]	validation_0-mae:2294.27347
[190]	validation_0-mae:2293.78374
[191]	validation_0-mae:2292.55230
[192]	validation_0-mae:2291.32330
[193]	validation_0-mae:2292.15455
[194]	validation_0-mae:2290.11081
[195]	validation_0-mae:2286.92455
[196]	validation_0-mae:2285.96700
[197]	validation_0-mae:2286.01259
[198]	validation_0-mae:2281.89318
[199]	validation_0-mae:2282.39816
[200]	validation_0-mae:2280.47734
[201]	validation_0-mae:2279.34515
[202]	validation_0-mae:2277.21448
[203]	validation_0-mae:2276.05777
[204]	validation_0-mae:2276.86379
[205]	validation_0-mae:2275.75396
[206]	validation_0-mae:2274.29183
[207]	validation_0-mae:2273.27095
[208]	validation_0-mae:2271.03328
[209]	validation_0-mae:2271.35248
[210]	validation_0-mae:2272.59916
[211]	validation_0-mae:2271.86961
[212]	validation_0-mae:2270.30694
[213]	validation_0-mae:2270.18490
[214]	validation_0-mae:2267.97858
[215]	validation_0-mae:2265.37834
[216]	validation_0-mae:2263.25397
[217]	validation_0-mae:2262.11869
[218]	validation_0-mae:2261.60443
[219]	validation_0-mae:2261.63364
[220]	validation_0-mae:2259.97031
[221]	validation_0-mae:2260.16093
[222]	validation_0-mae:2259.73021
[223]	validation_0-mae:2259.27837
[224]	validation_0-mae:2257.88209
[225]	validation_0-mae:2255.86905
[226]	validation_0-mae:2255.57491
[227]	validation_0-mae:2255.03649
[228]	validation_0-mae:2252.29357
[229]	validation_0-mae:2250.37231
[230]	validation_0-mae:2246.99301
[231]	validation_0-mae:2245.83281
[232]	validation_0-mae:2244.39037
[233]	validation_0-mae:2243.83351
[234]	validation_0-mae:2243.25712
[235]	validation_0-mae:2241.68753
[236]	validation_0-mae:2241.64097
[237]	validation_0-mae:2239.24913
[238]	validation_0-mae:2239.09996
[239]	validation_0-mae:2237.09285
[240]	validation_0-mae:2237.58506
[241]	validation_0-mae:2236.66003
[242]	validation_0-mae:2236.49737
[243]	validation_0-mae:2234.62739
[244]	validation_0-mae:2235.32993
[245]	validation_0-mae:2234.40358
[246]	validation_0-mae:2233.27985
[247]	validation_0-mae:2232.82391
[248]	validation_0-mae:2232.59139
[249]	validation_0-mae:2233.10000
[250]	validation_0-mae:2230.99192
[251]	validation_0-mae:2229.92801
[252]	validation_0-mae:2230.48541
[253]	validation_0-mae:2229.32924
[254]	validation_0-mae:2228.41791
[255]	validation_0-mae:2225.75905
[256]	validation_0-mae:2225.56884
[257]	validation_0-mae:2225.90123
[258]	validation_0-mae:2225.02381
[259]	validation_0-mae:2224.96614
[260]	validation_0-mae:2225.08492
[261]	validation_0-mae:2224.94472
[262]	validation_0-mae:2224.91398
[263]	validation_0-mae:2225.19205
[264]	validation_0-mae:2225.17331
[265]	validation_0-mae:2225.68955
[266]	validation_0-mae:2225.81192
[267]	validation_0-mae:2225.41209
[268]	validation_0-mae:2225.00317
[269]	validation_0-mae:2225.05734
[270]	validation_0-mae:2224.79315
[271]	validation_0-mae:2224.80373
[272]	validation_0-mae:2225.28019
[273]	validation_0-mae:2225.36715
[274]	validation_0-mae:2224.00959
[275]	validation_0-mae:2223.82386
[276]	validation_0-mae:2222.32343
[277]	validation_0-mae:2222.77345
[278]	validation_0-mae:2221.48361
[279]	validation_0-mae:2221.63165
[280]	validation_0-mae:2221.31317
[281]	validation_0-mae:2220.73396
[282]	validation_0-mae:2219.12584
[283]	validation_0-mae:2219.21357
[284]	validation_0-mae:2219.17664
[285]	validation_0-mae:2218.73516
[286]	validation_0-mae:2218.70672
[287]	validation_0-mae:2217.83041
[288]	validation_0-mae:2218.34334
[289]	validation_0-mae:2218.53516
[290]	validation_0-mae:2217.86557
[291]	validation_0-mae:2218.31211
[292]	validation_0-mae:2216.14434
[293]	validation_0-mae:2215.91052
[294]	validation_0-mae:2214.73615
[295]	validation_0-mae:2214.27775
[296]	validation_0-mae:2214.24917
[297]	validation_0-mae:2214.43557
[298]	validation_0-mae:2214.00735
[299]	validation_0-mae:2214.16958
[300]	validation_0-mae:2212.56077
[301]	validation_0-mae:2212.69167
[302]	validation_0-mae:2212.63868
[303]	validation_0-mae:2213.71052
[304]	validation_0-mae:2213.75541
[305]	validation_0-mae:2214.23020
[306]	validation_0-mae:2213.09103
[307]	validation_0-mae:2212.60712
[308]	validation_0-mae:2212.25953
[309]	validation_0-mae:2210.91822
[310]	validation_0-mae:2211.10873
[311]	validation_0-mae:2211.55309
[312]	validation_0-mae:2211.13300
[313]	validation_0-mae:2209.07013
[314]	validation_0-mae:2208.70919
[315]	validation_0-mae:2209.43935
[316]	validation_0-mae:2209.22603
[317]	validation_0-mae:2208.71728
[318]	validation_0-mae:2207.74537
[319]	validation_0-mae:2207.33463
[320]	validation_0-mae:2207.23066
[321]	validation_0-mae:2206.68317
[322]	validation_0-mae:2205.92118
[323]	validation_0-mae:2205.98592
[324]	validation_0-mae:2205.87018
[325]	validation_0-mae:2206.53885
[326]	validation_0-mae:2206.16454
[327]	validation_0-mae:2205.08809
[328]	validation_0-mae:2203.23193
[329]	validation_0-mae:2203.15912
[330]	validation_0-mae:2202.18764
[331]	validation_0-mae:2201.83463
[332]	validation_0-mae:2202.64101
[333]	validation_0-mae:2201.26696
[334]	validation_0-mae:2200.70906
[335]	validation_0-mae:2200.27202
[336]	validation_0-mae:2199.60696
[337]	validation_0-mae:2199.20764
[338]	validation_0-mae:2200.05675
[339]	validation_0-mae:2199.28679
[340]	validation_0-mae:2198.07051
[341]	validation_0-mae:2197.98083
[342]	validation_0-mae:2197.77839
[343]	validation_0-mae:2196.68639
[344]	validation_0-mae:2195.67513
[345]	validation_0-mae:2196.09854
[346]	validation_0-mae:2195.43639
[347]	validation_0-mae:2193.67300
[348]	validation_0-mae:2193.53070
[349]	validation_0-mae:2193.34613
[350]	validation_0-mae:2193.32996
[351]	validation_0-mae:2193.13385
[352]	validation_0-mae:2193.57595
[353]	validation_0-mae:2193.77308
[354]	validation_0-mae:2193.50696
[355]	validation_0-mae:2192.28281
[356]	validation_0-mae:2192.51200
[357]	validation_0-mae:2192.42647
[358]	validation_0-mae:2192.24459
[359]	validation_0-mae:2192.33826
[360]	validation_0-mae:2192.58316
[361]	validation_0-mae:2192.84301
[362]	validation_0-mae:2192.99213
[363]	validation_0-mae:2192.94899
[364]	validation_0-mae:2192.80345
[365]	validation_0-mae:2191.78473
[366]	validation_0-mae:2191.72281
[367]	validation_0-mae:2192.65669
[368]	validation_0-mae:2192.72755
[369]	validation_0-mae:2191.96084
[370]	validation_0-mae:2189.80912
[371]	validation_0-mae:2190.54512
[372]	validation_0-mae:2190.51490
[373]	validation_0-mae:2188.76166
[374]	validation_0-mae:2188.15815
[375]	validation_0-mae:2186.21223
[376]	validation_0-mae:2185.72973
[377]	validation_0-mae:2185.07359
[378]	validation_0-mae:2185.15379
[379]	validation_0-mae:2184.39217
[380]	validation_0-mae:2184.79536
[381]	validation_0-mae:2184.51490
[382]	validation_0-mae:2184.33570
[383]	validation_0-mae:2183.04419
[384]	validation_0-mae:2182.73259
[385]	validation_0-mae:2182.50922
[386]	validation_0-mae:2182.80078
[387]	validation_0-mae:2182.40053
[388]	validation_0-mae:2182.87688
[389]	validation_0-mae:2183.12205
[390]	validation_0-mae:2183.01944
[391]	validation_0-mae:2183.27485
[392]	validation_0-mae:2180.93843
[393]	validation_0-mae:2179.91363
[394]	validation_0-mae:2179.64569
[395]	validation_0-mae:2179.29867
[396]	validation_0-mae:2179.83798
[397]	validation_0-mae:2179.99320
[398]	validation_0-mae:2179.58833
[399]	validation_0-mae:2179.42432
[400]	validation_0-mae:2180.16985
[401]	validation_0-mae:2180.70399
[402]	validation_0-mae:2179.72608
[403]	validation_0-mae:2179.47033
[404]	validation_0-mae:2179.20629
[405]	validation_0-mae:2178.70727
[406]	validation_0-mae:2178.40321
[407]	validation_0-mae:2176.39367
[408]	validation_0-mae:2175.89503
[409]	validation_0-mae:2175.62148
[410]	validation_0-mae:2175.10772
[411]	validation_0-mae:2174.97515
[412]	validation_0-mae:2173.49229
[413]	validation_0-mae:2173.00152
[414]	validation_0-mae:2172.57970
[415]	validation_0-mae:2172.17917
[416]	validation_0-mae:2171.15407
[417]	validation_0-mae:2170.16115
[418]	validation_0-mae:2169.95025
[419]	validation_0-mae:2170.91968
[420]	validation_0-mae:2168.61862
[421]	validation_0-mae:2168.27945
[422]	validation_0-mae:2167.67478
[423]	validation_0-mae:2167.54524
[424]	validation_0-mae:2167.74046
[425]	validation_0-mae:2167.57969
[426]	validation_0-mae:2166.64203
[427]	validation_0-mae:2165.96792
[428]	validation_0-mae:2165.79136
[429]	validation_0-mae:2164.82043
[430]	validation_0-mae:2164.17616
[431]	validation_0-mae:2162.88633
[432]	validation_0-mae:2162.71486
[433]	validation_0-mae:2162.22707
[434]	validation_0-mae:2162.46967
[435]	validation_0-mae:2163.14534
[436]	validation_0-mae:2162.69965
[437]	validation_0-mae:2162.54880
[438]	validation_0-mae:2162.30110
[439]	validation_0-mae:2162.36146
[440]	validation_0-mae:2162.67799
[441]	validation_0-mae:2162.34351
[442]	validation_0-mae:2161.80187
[443]	validation_0-mae:2161.11766
[444]	validation_0-mae:2161.31065
[445]	validation_0-mae:2160.80503
[446]	validation_0-mae:2160.67262
[447]	validation_0-mae:2160.29314
[448]	validation_0-mae:2160.70060
[449]	validation_0-mae:2160.63786
[450]	validation_0-mae:2160.30140
[451]	validation_0-mae:2159.12635
[452]	validation_0-mae:2159.58417
[453]	validation_0-mae:2159.97360
[454]	validation_0-mae:2160.47228
[455]	validation_0-mae:2160.52806
[456]	validation_0-mae:2160.98079
[457]	validation_0-mae:2159.48925
[458]	validation_0-mae:2159.85997
[459]	validation_0-mae:2160.07050
[460]	validation_0-mae:2159.93317
[461]	validation_0-mae:2159.66847
[462]	validation_0-mae:2159.03563
[463]	validation_0-mae:2158.98191
[464]	validation_0-mae:2158.83090
[465]	validation_0-mae:2158.74201
[466]	validation_0-mae:2158.05084
[467]	validation_0-mae:2157.85841
[468]	validation_0-mae:2157.92971
[469]	validation_0-mae:2157.85362
[470]	validation_0-mae:2157.12773
[471]	validation_0-mae:2157.16462
[472]	validation_0-mae:2157.31581
[473]	validation_0-mae:2157.28488
[474]	validation_0-mae:2156.94432
[475]	validation_0-mae:2156.41798
[476]	validation_0-mae:2155.48552
[477]	validation_0-mae:2155.27278
[478]	validation_0-mae:2154.75941
[479]	validation_0-mae:2154.44376
[480]	validation_0-mae:2154.21033
[481]	validation_0-mae:2154.28373
[482]	validation_0-mae:2154.29272
[483]	validation_0-mae:2154.57507
[484]	validation_0-mae:2154.95133
[485]	validation_0-mae:2155.18084
[486]	validation_0-mae:2154.74786
[487]	validation_0-mae:2154.78018
[488]	validation_0-mae:2154.46184
[489]	validation_0-mae:2153.61840
[490]	validation_0-mae:2153.22480
[491]	validation_0-mae:2152.35674
[492]	validation_0-mae:2150.77790
[493]	validation_0-mae:2151.01016
[494]	validation_0-mae:2150.72401
[495]	validation_0-mae:2150.48979
[496]	validation_0-mae:2150.36677
[497]	validation_0-mae:2150.51887
[498]	validation_0-mae:2151.03376
[499]	validation_0-mae:2150.14733
[500]	validation_0-mae:2149.90157
[501]	validation_0-mae:2149.99171
[502]	validation_0-mae:2150.17789
[503]	validation_0-mae:2149.51674
[504]	validation_0-mae:2149.78810
[505]	validation_0-mae:2149.26931
[506]	validation_0-mae:2149.21898
[507]	validation_0-mae:2149.42437
[508]	validation_0-mae:2149.14834
[509]	validation_0-mae:2149.08948
[510]	validation_0-mae:2149.36728
[511]	validation_0-mae:2149.52180
[512]	validation_0-mae:2149.85705
[513]	validation_0-mae:2149.65959
[514]	validation_0-mae:2149.61372
[515]	validation_0-mae:2149.31488
[516]	validation_0-mae:2149.69261
[517]	validation_0-mae:2149.48259
[518]	validation_0-mae:2149.38867
[519]	validation_0-mae:2149.33109
[520]	validation_0-mae:2149.27394
[521]	validation_0-mae:2149.22928
[522]	validation_0-mae:2149.30384
[523]	validation_0-mae:2149.43347
[524]	validation_0-mae:2149.37686
[525]	validation_0-mae:2149.61412
[526]	validation_0-mae:2149.58116
[527]	validation_0-mae:2149.67237
[528]	validation_0-mae:2149.59607
[529]	validation_0-mae:2149.26031
[530]	validation_0-mae:2149.03819
[531]	validation_0-mae:2147.99803
[532]	validation_0-mae:2148.53752
[533]	validation_0-mae:2148.61329
[534]	validation_0-mae:2148.94502
[535]	validation_0-mae:2149.36341
[536]	validation_0-mae:2149.06935
[537]	validation_0-mae:2149.61973
[538]	validation_0-mae:2149.24916
[539]	validation_0-mae:2148.95441
[540]	validation_0-mae:2148.46060
[541]	validation_0-mae:2148.43877
[542]	validation_0-mae:2148.44487
[543]	validation_0-mae:2148.14736
[544]	validation_0-mae:2147.20584
[545]	validation_0-mae:2147.13094
[546]	validation_0-mae:2146.76877
[547]	validation_0-mae:2146.52979
[548]	validation_0-mae:2145.97293
[549]	validation_0-mae:2145.87567
[550]	validation_0-mae:2145.70688
[551]	validation_0-mae:2146.44171
[552]	validation_0-mae:2145.53221
[553]	validation_0-mae:2146.28014
[554]	validation_0-mae:2145.49253
[555]	validation_0-mae:2144.87147
[556]	validation_0-mae:2145.16981
[557]	validation_0-mae:2145.84833
[558]	validation_0-mae:2145.64762
[559]	validation_0-mae:2145.26835
[560]	validation_0-mae:2145.92927
[561]	validation_0-mae:2146.18134
[562]	validation_0-mae:2146.20618
[563]	validation_0-mae:2146.46543
[564]	validation_0-mae:2145.59851
[565]	validation_0-mae:2145.78965
[566]	validation_0-mae:2145.75631
[567]	validation_0-mae:2145.83591
[568]	validation_0-mae:2145.96664
[569]	validation_0-mae:2146.04065
[570]	validation_0-mae:2145.78262
[571]	validation_0-mae:2145.50658
[572]	validation_0-mae:2145.56094
[573]	validation_0-mae:2145.74802
[574]	validation_0-mae:2145.33964
[575]	validation_0-mae:2145.38746
[576]	validation_0-mae:2145.20539
[577]	validation_0-mae:2144.63991
[578]	validation_0-mae:2144.31712
[579]	validation_0-mae:2143.93037
[580]	validation_0-mae:2143.81062
[581]	validation_0-mae:2143.15650
[582]	validation_0-mae:2143.54654
[583]	validation_0-mae:2143.54163
[584]	validation_0-mae:2143.49275
[585]	validation_0-mae:2143.62450
[586]	validation_0-mae:2143.46704
[587]	validation_0-mae:2143.34301
[588]	validation_0-mae:2143.42853
[589]	validation_0-mae:2143.41093
[590]	validation_0-mae:2142.82117
[591]	validation_0-mae:2142.42020
[592]	validation_0-mae:2142.52066
[593]	validation_0-mae:2141.95169
[594]	validation_0-mae:2140.39730
[595]	validation_0-mae:2140.40098
[596]	validation_0-mae:2140.48803
[597]	validation_0-mae:2139.83723
[598]	validation_0-mae:2139.46328
[599]	validation_0-mae:2139.75767
[600]	validation_0-mae:2139.71113
[601]	validation_0-mae:2139.28076
[602]	validation_0-mae:2139.14718
[603]	validation_0-mae:2138.80330
[604]	validation_0-mae:2138.79396
[605]	validation_0-mae:2138.48679
[606]	validation_0-mae:2138.86742
[607]	validation_0-mae:2138.75789
[608]	validation_0-mae:2138.83412
[609]	validation_0-mae:2138.92783
[610]	validation_0-mae:2138.94462
[611]	validation_0-mae:2137.57558
[612]	validation_0-mae:2138.06196
[613]	validation_0-mae:2138.35534
[614]	validation_0-mae:2137.80679
[615]	validation_0-mae:2138.07320
[616]	validation_0-mae:2138.24160
[617]	validation_0-mae:2137.83860
[618]	validation_0-mae:2138.15827
[619]	validation_0-mae:2138.45248
[620]	validation_0-mae:2137.88420
[621]	validation_0-mae:2137.28908
[622]	validation_0-mae:2136.68758
[623]	validation_0-mae:2135.46758
[624]	validation_0-mae:2133.88620
[625]	validation_0-mae:2132.71001
[626]	validation_0-mae:2132.26288
[627]	validation_0-mae:2132.61636
[628]	validation_0-mae:2132.05359
[629]	validation_0-mae:2132.33459
[630]	validation_0-mae:2131.61316

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[3]	validation_0-mae:10776.24949
[4]	validation_0-mae:10299.88112
[5]	validation_0-mae:9855.50019
[6]	validation_0-mae:9447.19855
[7]	validation_0-mae:9083.12926
[8]	validation_0-mae:8763.59662
[9]	validation_0-mae:8456.30164
[10]	validation_0-mae:8164.75459
[11]	validation_0-mae:7890.19119
[12]	validation_0-mae:7638.02941
[13]	validation_0-mae:7368.35670
[14]	validation_0-mae:7181.77039
[15]	validation_0-mae:6955.47335
[16]	validation_0-mae:6758.98711
[17]	validation_0-mae:6547.84365
[18]	validation_0-mae:6388.68477
[19]	validation_0-mae:6194.21041
[20]	validation_0-mae:6053.91358
[21]	validation_0-mae:5882.92559
[22]	validation_0-mae:5754.50541
[23]	validation_0-mae:5609.49712
[24]	validation_0-mae:5446.30027
[25]	validation_0-mae:5321.76505
[26]	validation_0-mae:5181.95588
[27]	validation_0-mae:5047.80207
[28]	validation_0-mae:4944.38025
[29]	validation_0-mae:4847.58647
[30]	validation_0-mae:4740.06257
[31]	validation_0-mae:4665.88341
[32]	validation_0-mae:4561.58366
[33]	validation_0-mae:4477.90306
[34]	validation_0-mae:4390.63787
[35]	validation_0-mae:4309.08525
[36]	validation_0-mae:4248.36704
[37]	validation_0-mae:4172.11124
[38]	validation_0-mae:4098.07749
[39]	validation_0-mae:4047.81003
[40]	validation_0-mae:3981.80172
[41]	validation_0-mae:3931.47840
[42]	validation_0-mae:3875.83377
[43]	validation_0-mae:3829.32400
[44]	validation_0-mae:3781.99443
[45]	validation_0-mae:3713.86603
[46]	validation_0-mae:3672.28031
[47]	validation_0-mae:3633.20194
[48]	validation_0-mae:3584.27004
[49]	validation_0-mae:3554.22685
[50]	validation_0-mae:3515.54507
[51]	validation_0-mae:3482.02522
[52]	validation_0-mae:3447.31271
[53]	validation_0-mae:3421.07961
[54]	validation_0-mae:3378.43624
[55]	validation_0-mae:3353.98693
[56]	validation_0-mae:3331.90773
[57]	validation_0-mae:3316.15482
[58]	validation_0-mae:3293.47588
[59]	validation_0-mae:3271.19961
[60]	validation_0-mae:3247.12852
[61]	validation_0-mae:3226.37872
[62]	validation_0-mae:3191.29094
[63]	validation_0-mae:3175.64268
[64]	validation_0-mae:3152.99668
[65]	validation_0-mae:3131.12303
[66]	validation_0-mae:3118.74145
[67]	validation_0-mae:3101.47813
[68]	validation_0-mae:3069.31334
[69]	validation_0-mae:3049.61564
[70]	validation_0-mae:3039.63284
[71]	validation_0-mae:3026.26876
[72]	validation_0-mae:3011.05323
[73]	validation_0-mae:3001.79545
[74]	validation_0-mae:2986.07604
[75]	validation_0-mae:2977.27658
[76]	validation_0-mae:2968.61235
[77]	validation_0-mae:2956.47024
[78]	validation_0-mae:2934.53894
[79]	validation_0-mae:2919.43063
[80]	validation_0-mae:2908.41128
[81]	validation_0-mae:2890.14375
[82]	validation_0-mae:2869.81837
[83]	validation_0-mae:2860.54789
[84]	validation_0-mae:2852.73394
[85]	validation_0-mae:2843.56408
[86]	validation_0-mae:2833.97083
[87]	validation_0-mae:2827.08733
[88]	validation_0-mae:2808.02388
[89]	validation_0-mae:2800.20779
[90]	validation_0-mae:2789.91370
[91]	validation_0-mae:2777.64204
[92]	validation_0-mae:2756.15518
[93]	validation_0-mae:2748.97644
[94]	validation_0-mae:2737.81395
[95]	validation_0-mae:2731.77717
[96]	validation_0-mae:2725.77152
[97]	validation_0-mae:2718.42522
[98]	validation_0-mae:2704.97045
[99]	validation_0-mae:2692.21782
[100]	validation_0-mae:2689.29328
[101]	validation_0-mae:2686.78873
[102]	validation_0-mae:2683.19422
[103]	validation_0-mae:2671.46570
[104]	validation_0-mae:2655.39987
[105]	validation_0-mae:2645.51967
[106]	validation_0-mae:2638.39905
[107]	validation_0-mae:2628.81319
[108]	validation_0-mae:2623.14309
[109]	validation_0-mae:2617.37101
[110]	validation_0-mae:2608.45753
[111]	validation_0-mae:2600.03993
[112]	validation_0-mae:2594.64598
[113]	validation_0-mae:2588.19271
[114]	validation_0-mae:2580.26642
[115]	validation_0-mae:2573.49273
[116]	validation_0-mae:2568.72432
[117]	validation_0-mae:2565.32272
[118]	validation_0-mae:2560.29411
[119]	validation_0-mae:2554.32933
[120]	validation_0-mae:2546.66238
[121]	validation_0-mae:2542.34750
[122]	validation_0-mae:2536.72299
[123]	validation_0-mae:2531.23034
[124]	validation_0-mae:2524.69410
[125]	validation_0-mae:2521.79335
[126]	validation_0-mae:2517.47989
[127]	validation_0-mae:2510.21642
[128]	validation_0-mae:2504.36280
[129]	validation_0-mae:2496.99716
[130]	validation_0-mae:2490.67502
[131]	validation_0-mae:2483.47969
[132]	validation_0-mae:2480.68927
[133]	validation_0-mae:2475.55139
[134]	validation_0-mae:2471.66943
[135]	validation_0-mae:2468.80123
[136]	validation_0-mae:2464.80620
[137]	validation_0-mae:2460.52150
[138]	validation_0-mae:2458.74723
[139]	validation_0-mae:2455.34090
[140]	validation_0-mae:2450.59892
[141]	validation_0-mae:2446.55383
[142]	validation_0-mae:2442.63736
[143]	validation_0-mae:2436.87787
[144]	validation_0-mae:2434.66426
[145]	validation_0-mae:2431.57196
[146]	validation_0-mae:2427.65233
[147]	validation_0-mae:2426.34987
[148]	validation_0-mae:2425.89143
[149]	validation_0-mae:2423.70777
[150]	validation_0-mae:2418.10736
[151]	validation_0-mae:2414.86548
[152]	validation_0-mae:2413.66871
[153]	validation_0-mae:2411.65855
[154]	validation_0-mae:2409.26887
[155]	validation_0-mae:2407.72373
[156]	validation_0-mae:2404.39155
[157]	validation_0-mae:2401.23074
[158]	validation_0-mae:2400.14286
[159]	validation_0-mae:2396.82899
[160]	validation_0-mae:2394.89487
[161]	validation_0-mae:2389.08928
[162]	validation_0-mae:2389.06788
[163]	validation_0-mae:2387.30542
[164]	validation_0-mae:2387.13942
[165]	validation_0-mae:2385.55924
[166]	validation_0-mae:2383.65115
[167]	validation_0-mae:2381.49417
[168]	validation_0-mae:2378.24406
[169]	validation_0-mae:2375.00621
[170]	validation_0-mae:2375.26093
[171]	validation_0-mae:2370.91324
[172]	validation_0-mae:2371.21509
[173]	validation_0-mae:2371.05734
[174]	validation_0-mae:2370.36272
[175]	validation_0-mae:2366.63190
[176]	validation_0-mae:2365.95806
[177]	validation_0-mae:2365.40121
[178]	validation_0-mae:2361.99266
[179]	validation_0-mae:2358.97340
[180]	validation_0-mae:2357.63933
[181]	validation_0-mae:2356.64910
[182]	validation_0-mae:2354.51446
[183]	validation_0-mae:2350.04249
[184]	validation_0-mae:2347.49155
[185]	validation_0-mae:2344.19688
[186]	validation_0-mae:2345.51925
[187]	validation_0-mae:2344.13053
[188]	validation_0-mae:2341.13534
[189]	validation_0-mae:2340.21333
[190]	validation_0-mae:2338.63029
[191]	validation_0-mae:2337.01541
[192]	validation_0-mae:2335.93261
[193]	validation_0-mae:2332.82294
[194]	validation_0-mae:2332.36339
[195]	validation_0-mae:2332.32189
[196]	validation_0-mae:2328.07530
[197]	validation_0-mae:2325.77662
[198]	validation_0-mae:2323.87802
[199]	validation_0-mae:2322.42734
[200]	validation_0-mae:2322.27329
[201]	validation_0-mae:2321.95519
[202]	validation_0-mae:2322.62923
[203]	validation_0-mae:2319.06288
[204]	validation_0-mae:2316.94928
[205]	validation_0-mae:2316.54914
[206]	validation_0-mae:2315.69214
[207]	validation_0-mae:2315.17051
[208]	validation_0-mae:2315.22828
[209]	validation_0-mae:2315.01766
[210]	validation_0-mae:2313.59634
[211]	validation_0-mae:2314.17844
[212]	validation_0-mae:2313.37332
[213]	validation_0-mae:2313.65840
[214]	validation_0-mae:2311.86438
[215]	validation_0-mae:2309.33224
[216]	validation_0-mae:2310.05061
[217]	validation_0-mae:2309.75908
[218]	validation_0-mae:2306.77390
[219]	validation_0-mae:2307.02201
[220]	validation_0-mae:2305.88962
[221]	validation_0-mae:2305.70408
[222]	validation_0-mae:2306.17672
[223]	validation_0-mae:2306.17019
[224]	validation_0-mae:2304.85089
[225]	validation_0-mae:2304.00616
[226]	validation_0-mae:2303.93606
[227]	validation_0-mae:2303.51664
[228]	validation_0-mae:2303.61074
[229]	validation_0-mae:2302.30118
[230]	validation_0-mae:2301.32521
[231]	validation_0-mae:2300.36733
[232]	validation_0-mae:2300.55465
[233]	validation_0-mae:2300.66317
[234]	validation_0-mae:2300.69058
[235]	validation_0-mae:2299.56303
[236]	validation_0-mae:2298.90472
[237]	validation_0-mae:2297.55660
[238]	validation_0-mae:2296.12833
[239]	validation_0-mae:2295.69339
[240]	validation_0-mae:2295.54167
[241]	validation_0-mae:2294.00887
[242]	validation_0-mae:2293.53401
[243]	validation_0-mae:2291.12489
[244]	validation_0-mae:2290.69614
[245]	validation_0-mae:2290.89472
[246]	validation_0-mae:2290.46698
[247]	validation_0-mae:2289.22612
[248]	validation_0-mae:2288.72670
[249]	validation_0-mae:2286.95702
[250]	validation_0-mae:2286.05172
[251]	validation_0-mae:2285.61298
[252]	validation_0-mae:2285.75501
[253]	validation_0-mae:2285.48147
[254]	validation_0-mae:2285.77324
[255]	validation_0-mae:2285.44777
[256]	validation_0-mae:2284.45210
[257]	validation_0-mae:2284.82999
[258]	validation_0-mae:2284.90187
[259]	validation_0-mae:2284.54979
[260]	validation_0-mae:2282.99467
[261]	validation_0-mae:2282.53316
[262]	validation_0-mae:2282.00894
[263]	validation_0-mae:2281.59328
[264]	validation_0-mae:2281.92895
[265]	validation_0-mae:2281.29161
[266]	validation_0-mae:2280.70536
[267]	validation_0-mae:2281.90653
[268]	validation_0-mae:2279.24668
[269]	validation_0-mae:2279.86113
[270]	validation_0-mae:2279.25664
[271]	validation_0-mae:2277.91472
[272]	validation_0-mae:2275.95853
[273]	validation_0-mae:2275.97670
[274]	validation_0-mae:2275.91962
[275]	validation_0-mae:2276.03230
[276]	validation_0-mae:2275.21914
[277]	validation_0-mae:2274.67338
[278]	validation_0-mae:2272.52559
[279]	validation_0-mae:2271.97565
[280]	validation_0-mae:2270.22253
[281]	validation_0-mae:2268.64007
[282]	validation_0-mae:2268.77781
[283]	validation_0-mae:2268.01730
[284]	validation_0-mae:2267.73220
[285]	validation_0-mae:2266.24696
[286]	validation_0-mae:2266.40496
[287]	validation_0-mae:2265.35733
[288]	validation_0-mae:2263.47467
[289]	validation_0-mae:2262.82062
[290]	validation_0-mae:2261.18336
[291]	validation_0-mae:2261.20161
[292]	validation_0-mae:2261.19573
[293]	validation_0-mae:2260.97689
[294]	validation_0-mae:2261.21712
[295]	validation_0-mae:2261.64708
[296]	validation_0-mae:2261.76671
[297]	validation_0-mae:2261.23423
[298]	validation_0-mae:2259.97315
[299]	validation_0-mae:2259.23061
[300]	validation_0-mae:2259.16194
[301]	validation_0-mae:2259.51438
[302]	validation_0-mae:2258.77943
[303]	validation_0-mae:2259.17080
[304]	validation_0-mae:2259.08104
[305]	validation_0-mae:2257.40049
[306]	validation_0-mae:2257.40194
[307]	validation_0-mae:2257.86974
[308]	validation_0-mae:2255.95186
[309]	validation_0-mae:2254.77542
[310]	validation_0-mae:2253.43998
[311]	validation_0-mae:2252.50827
[312]	validation_0-mae:2252.59797
[313]	validation_0-mae:2253.07765
[314]	validation_0-mae:2251.56566
[315]	validation_0-mae:2251.17215
[316]	validation_0-mae:2250.33931
[317]	validation_0-mae:2250.37990
[318]	validation_0-mae:2249.47806
[319]	validation_0-mae:2246.49204
[320]	validation_0-mae:2245.79661
[321]	validation_0-mae:2244.68520
[322]	validation_0-mae:2244.28171
[323]	validation_0-mae:2244.62404
[324]	validation_0-mae:2244.25073
[325]	validation_0-mae:2244.00579
[326]	validation_0-mae:2243.92897
[327]	validation_0-mae:2243.80697
[328]	validation_0-mae:2243.60239
[329]	validation_0-mae:2242.62110
[330]	validation_0-mae:2242.91130
[331]	validation_0-mae:2240.16620
[332]	validation_0-mae:2235.98547
[333]	validation_0-mae:2232.94812
[334]	validation_0-mae:2233.64538
[335]	validation_0-mae:2233.37050
[336]	validation_0-mae:2232.84096
[337]	validation_0-mae:2233.24040
[338]	validation_0-mae:2233.02172
[339]	validation_0-mae:2233.15064
[340]	validation_0-mae:2232.23896
[341]	validation_0-mae:2232.20906
[342]	validation_0-mae:2231.78868
[343]	validation_0-mae:2231.41449
[344]	validation_0-mae:2231.37549
[345]	validation_0-mae:2231.35694
[346]	validation_0-mae:2232.30402
[347]	validation_0-mae:2232.32967
[348]	validation_0-mae:2232.75783
[349]	validation_0-mae:2232.68865
[350]	validation_0-mae:2231.55032
[351]	validation_0-mae:2230.33924
[352]	validation_0-mae:2230.53825
[353]	validation_0-mae:2231.49485
[354]	validation_0-mae:2231.10462
[355]	validation_0-mae:2231.35861
[356]	validation_0-mae:2232.13375
[357]	validation_0-mae:2231.55315
[358]	validation_0-mae:2231.35504
[359]	validation_0-mae:2231.00720
[360]	validation_0-mae:2229.33234
[361]	validation_0-mae:2229.28280
[362]	validation_0-mae:2228.05213
[363]	validation_0-mae:2227.95928
[364]	validation_0-mae:2228.04271
[365]	validation_0-mae:2227.85814
[366]	validation_0-mae:2228.01611
[367]	validation_0-mae:2226.60384
[368]	validation_0-mae:2226.73361
[369]	validation_0-mae:2225.64178
[370]	validation_0-mae:2225.74776
[371]	validation_0-mae:2225.34999
[372]	validation_0-mae:2224.80788
[373]	validation_0-mae:2224.96233
[374]	validation_0-mae:2224.87653
[375]	validation_0-mae:2224.82484
[376]	validation_0-mae:2224.74751
[377]	validation_0-mae:2224.92850
[378]	validation_0-mae:2224.44789
[379]	validation_0-mae:2223.54689
[380]	validation_0-mae:2223.11473
[381]	validation_0-mae:2223.52243
[382]	validation_0-mae:2223.42653
[383]	validation_0-mae:2224.34721
[384]	validation_0-mae:2224.23276
[385]	validation_0-mae:2224.18344
[386]	validation_0-mae:2222.93615
[387]	validation_0-mae:2222.42105
[388]	validation_0-mae:2222.18201
[389]	validation_0-mae:2222.52844
[390]	validation_0-mae:2221.45308
[391]	validation_0-mae:2220.76303
[392]	validation_0-mae:2220.32800
[393]	validation_0-mae:2220.27981
[394]	validation_0-mae:2219.89097
[395]	validation_0-mae:2219.64728
[396]	validation_0-mae:2219.82609
[397]	validation_0-mae:2220.35415
[398]	validation_0-mae:2219.47567
[399]	validation_0-mae:2218.87543
[400]	validation_0-mae:2219.19990
[401]	validation_0-mae:2219.35041
[402]	validation_0-mae:2219.55349
[403]	validation_0-mae:2219.52455
[404]	validation_0-mae:2219.76045
[405]	validation_0-mae:2220.70734
[406]	validation_0-mae:2219.70603
[407]	validation_0-mae:2219.56934
[408]	validation_0-mae:2218.17292
[409]	validation_0-mae:2218.61945
[410]	validation_0-mae:2217.34599
[411]	validation_0-mae:2216.60412
[412]	validation_0-mae:2215.33648
[413]	validation_0-mae:2215.09688
[414]	validation_0-mae:2214.60992
[415]	validation_0-mae:2214.38539
[416]	validation_0-mae:2214.06586
[417]	validation_0-mae:2214.19158
[418]	validation_0-mae:2214.11140
[419]	validation_0-mae:2213.29496
[420]	validation_0-mae:2213.06818
[421]	validation_0-mae:2213.70836
[422]	validation_0-mae:2213.62206
[423]	validation_0-mae:2213.23223
[424]	validation_0-mae:2212.37328
[425]	validation_0-mae:2212.40072
[426]	validation_0-mae:2213.08003
[427]	validation_0-mae:2213.15618
[428]	validation_0-mae:2212.44217
[429]	validation_0-mae:2212.79984
[430]	validation_0-mae:2213.27554
[431]	validation_0-mae:2213.78003
[432]	validation_0-mae:2213.53056
[433]	validation_0-mae:2213.04589
[434]	validation_0-mae:2212.43060
[435]	validation_0-mae:2212.20364
[436]	validation_0-mae:2212.16671
[437]	validation_0-mae:2212.07198
[438]	validation_0-mae:2212.70082
[439]	validation_0-mae:2212.60929
[440]	validation_0-mae:2212.24620
[441]	validation_0-mae:2211.95373
[442]	validation_0-mae:2211.48333
[443]	validation_0-mae:2211.51885
[444]	validation_0-mae:2211.29489
[445]	validation_0-mae:2212.11001
[446]	validation_0-mae:2213.45482
[447]	validation_0-mae:2212.52393
[448]	validation_0-mae:2212.78329
[449]	validation_0-mae:2213.27938
[450]	validation_0-mae:2213.54355
[451]	validation_0-mae:2212.98073
[452]	validation_0-mae:2212.64694
[453]	validation_0-mae:2212.85981
[454]	validation_0-mae:2212.71282
[455]	validation_0-mae:2212.28134
[456]	validation_0-mae:2212.16302
[457]	validation_0-mae:2212.30198
[458]	validation_0-mae:2212.91836
[459]	validation_0-mae:2212.77238
[460]	validation_0-mae:2212.29127
[461]	validation_0-mae:2211.91774
[462]	validation_0-mae:2211.97255
[463]	validation_0-mae:2211.78420
[464]	validation_0-mae:2211.93223
[465]	validation_0-mae:2211.94105
[466]	validation_0-mae:2212.00678
[467]	validation_0-mae:2210.79727
[468]	validation_0-mae:2209.69603
[469]	validation_0-mae:2209.56815
[470]	validation_0-mae:2209.40084
[471]	validation_0-mae:2209.59251
[472]	validation_0-mae:2209.56730
[473]	validation_0-mae:2207.82450
[474]	validation_0-mae:2205.55727
[475]	validation_0-mae:2206.21030
[476]	validation_0-mae:2206.06776
[477]	validation_0-mae:2206.00192
[478]	validation_0-mae:2206.06648
[479]	validation_0-mae:2205.42170
[480]	validation_0-mae:2204.56129
[481]	validation_0-mae:2204.00357
[482]	validation_0-mae:2202.87192
[483]	validation_0-mae:2201.84140
[484]	validation_0-mae:2201.64430
[485]	validation_0-mae:2202.25101
[486]	validation_0-mae:2201.55320
[487]	validation_0-mae:2201.11168
[488]	validation_0-mae:2200.66513
[489]	validation_0-mae:2201.18239
[490]	validation_0-mae:2201.53847
[491]	validation_0-mae:2202.45484
[492]	validation_0-mae:2203.50466
[493]	validation_0-mae:2203.36850
[494]	validation_0-mae:2203.20070
[495]	validation_0-mae:2202.89090
[496]	validation_0-mae:2203.22367
[497]	validation_0-mae:2203.58099
[498]	validation_0-mae:2203.20843
[499]	validation_0-mae:2203.55300
[500]	validation_0-mae:2202.61856
[501]	validation_0-mae:2202.78944
[502]	validation_0-mae:2203.16339
[503]	validation_0-mae:2203.44343
[504]	validation_0-mae:2203.04045
[505]	validation_0-mae:2203.21950
[506]	validation_0-mae:2203.93316
[507]	validation_0-mae:2204.20364
[508]	validation_0-mae:2202.47977
[509]	validation_0-mae:2202.12567
[510]	validation_0-mae:2201.36955
[511]	validation_0-mae:2201.39852
[512]	validation_0-mae:2201.91266
[513]	validation_0-mae:2201.49421
[514]	validation_0-mae:2201.78644
[515]	validation_0-mae:2201.78651
[516]	validation_0-mae:2202.44874
[517]	validation_0-mae:2202.23953
[518]	validation_0-mae:2202.27036
[519]	validation_0-mae:2202.07591
[520]	validation_0-mae:2202.66208
[521]	validation_0-mae:2202.29283
[522]	validation_0-mae:2201.48287
[523]	validation_0-mae:2199.86412
[524]	validation_0-mae:2199.58894
[525]	validation_0-mae:2199.02859
[526]	validation_0-mae:2199.73252
[527]	validation_0-mae:2199.64877
[528]	validation_0-mae:2199.35566
[529]	validation_0-mae:2199.00254
[530]	validation_0-mae:2198.74427
[531]	validation_0-mae:2198.75515
[532]	validation_0-mae:2198.99395
[533]	validation_0-mae:2199.10940
[534]	validation_0-mae:2198.77541
[535]	validation_0-mae:2198.45506
[536]	validation_0-mae:2199.33076
[537]	validation_0-mae:2199.08460
[538]	validation_0-mae:2198.00249
[539]	validation_0-mae:2197.88455
[540]	validation_0-mae:2198.19249
[541]	validation_0-mae:2197.90747
[542]	validation_0-mae:2198.74253
[543]	validation_0-mae:2198.48559
[544]	validation_0-mae:2198.68317
[545]	validation_0-mae:2198.68607
[546]	validation_0-mae:2198.71036
[547]	validation_0-mae:2199.07730
[548]	validation_0-mae:2198.43268
[549]	validation_0-mae:2199.04934
[550]	validation_0-mae:2199.38347
[551]	validation_0-mae:2199.34060
[552]	validation_0-mae:2199.23966
[553]	validation_0-mae:2199.15108
[554]	validation_0-mae:2199.25776
[555]	validation_0-mae:2199.37797
[556]	validation_0-mae:2199.33967
[557]	validation_0-mae:2199.89738
[558]	validation_0-mae:2199.50960
[559]	validation_0-mae:2198.97857
[560]	validation_0-mae:2198.58441
[561]	validation_0-mae:2198.46939
[562]	validation_0-mae:2198.39292
[563]	validation_0-mae:2198.41691
[564]	validation_0-mae:2198.14116
[565]	validation_0-mae:2198.08223
[566]	validation_0-mae:2197.21477
[567]	validation_0-mae:2197.11832
[568]	validation_0-mae:2196.83935
[569]	validation_0-mae:2196.53189
[570]	validation_0-mae:2197.35288
[571]	validation_0-mae:2197.95519
[572]	validation_0-mae:2197.78089
[573]	validation_0-mae:2197.14523
[574]	validation_0-mae:2196.91585
[575]	validation_0-mae:2196.00338
[576]	validation_0-mae:2196.12288
[577]	validation_0-mae:2196.18370
[578]	validation_0-mae:2196.09906
[579]	validation_0-mae:2196.21359
[580]	validation_0-mae:2196.36091
[581]	validation_0-mae:2195.75353
[582]	validation_0-mae:2195.91204
[583]	validation_0-mae:2195.38654
[584]	validation_0-mae:2195.36690
[585]	validation_0-mae:2195.43380
[586]	validation_0-mae:2194.86604
[587]	validation_0-mae:2194.63105
[588]	validation_0-mae:2194.84573
[589]	validation_0-mae:2194.15781
[590]	validation_0-mae:2193.62317
[591]	validation_0-mae:2193.94359
[592]	validation_0-mae:2193.40171
[593]	validation_0-mae:2193.04831

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[0]	validation_0-mae:12552.77351
[1]	validation_0-mae:11895.11814
[2]	validation_0-mae:11310.59175
[3]	validation_0-mae:10761.48142
[4]	validation_0-mae:10274.19314
[5]	validation_0-mae:9834.20243
[6]	validation_0-mae:9418.21333
[7]	validation_0-mae:9038.62737
[8]	validation_0-mae:8683.86625
[9]	validation_0-mae:8366.02262
[10]	validation_0-mae:8060.71809
[11]	validation_0-mae:7798.18901
[12]	validation_0-mae:7541.11746
[13]	validation_0-mae:7304.11450
[14]	validation_0-mae:7069.35444
[15]	validation_0-mae:6847.72683
[16]	validation_0-mae:6655.71686
[17]	validation_0-mae:6471.52090
[18]	validation_0-mae:6261.99787
[19]	validation_0-mae:6107.99327
[20]	validation_0-mae:5932.63759
[21]	validation_0-mae:5790.85916
[22]	validation_0-mae:5649.47369
[23]	validation_0-mae:5489.06636
[24]	validation_0-mae:5377.18227
[25]	validation_0-mae:5237.64671
[26]	validation_0-mae:5111.54773
[27]	validation_0-mae:4997.44000
[28]	validation_0-mae:4893.27472
[29]	validation_0-mae:4798.64878
[30]	validation_0-mae:4694.04938
[31]	validation_0-mae:4581.43620
[32]	validation_0-mae:4498.17211
[33]	validation_0-mae:4397.31922
[34]	validation_0-mae:4323.72484
[35]	validation_0-mae:4246.91041
[36]	validation_0-mae:4175.37078
[37]	validation_0-mae:4095.61594
[38]	validation_0-mae:4014.29038
[39]	validation_0-mae:3960.55027
[40]	validation_0-mae:3904.24751

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[41]	validation_0-mae:3850.93836
[42]	validation_0-mae:3786.71367
[43]	validation_0-mae:3749.32110
[44]	validation_0-mae:3692.49110
[45]	validation_0-mae:3645.87055
[46]	validation_0-mae:3609.02668
[47]	validation_0-mae:3559.64769
[48]	validation_0-mae:3523.83736
[49]	validation_0-mae:3482.73489
[50]	validation_0-mae:3440.66221
[51]	validation_0-mae:3394.04326
[52]	validation_0-mae:3359.44567
[53]	validation_0-mae:3332.50932
[54]	validation_0-mae:3303.91231
[55]	validation_0-mae:3271.08364
[56]	validation_0-mae:3234.95150
[57]	validation_0-mae:3207.27549
[58]	validation_0-mae:3194.05603
[59]	validation_0-mae:3173.18377
[60]	validation_0-mae:3148.66732
[61]	validation_0-mae:3129.35156
[62]	validation_0-mae:3112.87301
[63]	validation_0-mae:3093.15119
[64]	validation_0-mae:3072.52730
[65]	validation_0-mae:3037.57184
[66]	validation_0-mae:3024.66695
[67]	validation_0-mae:3008.21240
[68]	validation_0-mae:2989.64707
[69]	validation_0-mae:2967.20382
[70]	validation_0-mae:2954.65722
[71]	validation_0-mae:2924.38751
[72]	validation_0-mae:2913.04551
[73]	validation_0-mae:2900.49548
[74]	validation_0-mae:2888.09454
[75]	validation_0-mae:2881.41362
[76]	validation_0-mae:2872.90341
[77]	validation_0-mae:2862.29088
[78]	validation_0-mae:2847.40065
[79]	validation_0-mae:2837.45971
[80]	validation_0-mae:2829.51581
[81]	validation_0-mae:2809.43377
[82]	validation_0-mae:2791.01603
[83]	validation_0-mae:2776.37105
[84]	validation_0-mae:2768.94328
[85]	validation_0-mae:2757.47037
[86]	validation_0-mae:2745.98218
[87]	validation_0-mae:2740.25670
[88]	validation_0-mae:2731.70120
[89]	validation_0-mae:2723.13668
[90]	validation_0-mae:2713.99187
[91]	validation_0-mae:2706.14626
[92]	validation_0-mae:2691.79367
[93]	validation_0-mae:2682.47861
[94]	validation_0-mae:2676.71031
[95]	validation_0-mae:2662.27135
[96]	validation_0-mae:2653.68875
[97]	validation_0-mae:2650.41753
[98]	validation_0-mae:2641.84108
[99]	validation_0-mae:2639.13103
[100]	validation_0-mae:2626.65164
[101]	validation_0-mae:2614.48031
[102]	validation_0-mae:2609.24438
[103]	validation_0-mae:2601.94186
[104]	validation_0-mae:2595.05311
[105]	validation_0-mae:2590.24154
[106]	validation_0-mae:2579.95026
[107]	validation_0-mae:2573.61726
[108]	validation_0-mae:2569.73286
[109]	validation_0-mae:2562.02437
[110]	validation_0-mae:2552.07027
[111]	validation_0-mae:2542.77735
[112]	validation_0-mae:2538.66349
[113]	validation_0-mae:2532.82939
[114]	validation_0-mae:2525.45193
[115]	validation_0-mae:2522.08395
[116]	validation_0-mae:2517.65604
[117]	validation_0-mae:2512.06383
[118]	validation_0-mae:2506.26671
[119]	validation_0-mae:2498.91610
[120]	validation_0-mae:2493.58595
[121]	validation_0-mae:2487.47434
[122]	validation_0-mae:2481.58945
[123]	validation_0-mae:2476.18352
[124]	validation_0-mae:2470.46944
[125]	validation_0-mae:2464.78561
[126]	validation_0-mae:2458.05605
[127]	validation_0-mae:2454.05540
[128]	validation_0-mae:2445.62381
[129]	validation_0-mae:2442.25010
[130]	validation_0-mae:2432.56847
[131]	validation_0-mae:2428.78351
[132]	validation_0-mae:2424.60428
[133]	validation_0-mae:2420.73786
[134]	validation_0-mae:2416.44962
[135]	validation_0-mae:2416.26142
[136]	validation_0-mae:2413.36574
[137]	validation_0-mae:2411.32180
[138]	validation_0-mae:2404.57473
[139]	validation_0-mae:2402.72817
[140]	validation_0-mae:2399.77762
[141]	validation_0-mae:2393.67807
[142]	validation_0-mae:2387.96577
[143]	validation_0-mae:2385.07445
[144]	validation_0-mae:2383.00922
[145]	validation_0-mae:2380.15274
[146]	validation_0-mae:2378.88542
[147]	validation_0-mae:2375.93929
[148]	validation_0-mae:2374.34695
[149]	validation_0-mae:2371.17876
[150]	validation_0-mae:2366.12851
[151]	validation_0-mae:2361.98468
[152]	validation_0-mae:2358.69727
[153]	validation_0-mae:2358.03312
[154]	validation_0-mae:2355.01928
[155]	validation_0-mae:2354.50258
[156]	validation_0-mae:2352.91274
[157]	validation_0-mae:2349.18650
[158]	validation_0-mae:2345.09372
[159]	validation_0-mae:2339.25152
[160]	validation_0-mae:2336.94711
[161]	validation_0-mae:2333.34317
[162]	validation_0-mae:2329.44417
[163]	validation_0-mae:2326.54839
[164]	validation_0-mae:2326.46529
[165]	validation_0-mae:2320.55503
[166]	validation_0-mae:2320.16761
[167]	validation_0-mae:2318.97163
[168]	validation_0-mae:2316.82233
[169]	validation_0-mae:2316.57493
[170]	validation_0-mae:2312.27589
[171]	validation_0-mae:2307.57405
[172]	validation_0-mae:2303.23163
[173]	validation_0-mae:2300.45145
[174]	validation_0-mae:2296.53819
[175]	validation_0-mae:2294.24741
[176]	validation_0-mae:2292.66784
[177]	validation_0-mae:2290.65107
[178]	validation_0-mae:2287.94065
[179]	validation_0-mae:2284.31663
[180]	validation_0-mae:2282.60032
[181]	validation_0-mae:2275.93504
[182]	validation_0-mae:2274.30487
[183]	validation_0-mae:2272.93637
[184]	validation_0-mae:2270.11879
[185]	validation_0-mae:2269.26236
[186]	validation_0-mae:2268.55219
[187]	validation_0-mae:2266.63434
[188]	validation_0-mae:2265.69975
[189]	validation_0-mae:2264.86215
[190]	validation_0-mae:2261.64651
[191]	validation_0-mae:2260.24075
[192]	validation_0-mae:2258.43409
[193]	validation_0-mae:2255.77590
[194]	validation_0-mae:2254.18137
[195]	validation_0-mae:2251.85874
[196]	validation_0-mae:2249.14709
[197]	validation_0-mae:2248.79778
[198]	validation_0-mae:2247.22885
[199]	validation_0-mae:2247.39804
[200]	validation_0-mae:2244.86300
[201]	validation_0-mae:2244.71252
[202]	validation_0-mae:2243.34408
[203]	validation_0-mae:2242.84788
[204]	validation_0-mae:2242.01874
[205]	validation_0-mae:2241.07915
[206]	validation_0-mae:2238.73775
[207]	validation_0-mae:2238.62710
[208]	validation_0-mae:2237.61023
[209]	validation_0-mae:2235.27291
[210]	validation_0-mae:2233.28332
[211]	validation_0-mae:2231.96058
[212]	validation_0-mae:2230.44185
[213]	validation_0-mae:2230.32505
[214]	validation_0-mae:2229.50381
[215]	validation_0-mae:2228.04914
[216]	validation_0-mae:2228.31759
[217]	validation_0-mae:2227.49865
[218]	validation_0-mae:2227.38659
[219]	validation_0-mae:2226.97603
[220]	validation_0-mae:2226.43792
[221]	validation_0-mae:2226.60711
[222]	validation_0-mae:2225.57665
[223]	validation_0-mae:2225.59629
[224]	validation_0-mae:2224.33680
[225]	validation_0-mae:2222.86903
[226]	validation_0-mae:2221.88251
[227]	validation_0-mae:2220.84350
[228]	validation_0-mae:2219.99269
[229]	validation_0-mae:2219.55001
[230]	validation_0-mae:2219.19350
[231]	validation_0-mae:2218.29856
[232]	validation_0-mae:2219.72332
[233]	validation_0-mae:2219.47527
[234]	validation_0-mae:2220.42645
[235]	validation_0-mae:2220.16352
[236]	validation_0-mae:2216.99194
[237]	validation_0-mae:2215.52409
[238]	validation_0-mae:2213.41554
[239]	validation_0-mae:2213.61734
[240]	validation_0-mae:2212.88275
[241]	validation_0-mae:2211.02895
[242]	validation_0-mae:2209.85974
[243]	validation_0-mae:2208.05489
[244]	validation_0-mae:2207.75419
[245]	validation_0-mae:2207.60844
[246]	validation_0-mae:2207.93744
[247]	validation_0-mae:2208.07058
[248]	validation_0-mae:2207.50458
[249]	validation_0-mae:2205.73889
[250]	validation_0-mae:2206.98300
[251]	validation_0-mae:2205.96568
[252]	validation_0-mae:2206.22886
[253]	validation_0-mae:2205.39249
[254]	validation_0-mae:2205.63143
[255]	validation_0-mae:2205.77923
[256]	validation_0-mae:2206.33298
[257]	validation_0-mae:2205.26082
[258]	validation_0-mae:2205.61055
[259]	validation_0-mae:2204.83801
[260]	validation_0-mae:2202.89463
[261]	validation_0-mae:2201.71686
[262]	validation_0-mae:2199.98397
[263]	validation_0-mae:2200.52696
[264]	validation_0-mae:2199.56365
[265]	validation_0-mae:2199.49772
[266]	validation_0-mae:2198.17364
[267]	validation_0-mae:2195.23073
[268]	validation_0-mae:2194.40067
[269]	validation_0-mae:2194.29762
[270]	validation_0-mae:2193.11522
[271]	validation_0-mae:2192.23291
[272]	validation_0-mae:2192.66331
[273]	validation_0-mae:2191.84366
[274]	validation_0-mae:2192.49844
[275]	validation_0-mae:2192.21544
[276]	validation_0-mae:2190.56343
[277]	validation_0-mae:2188.92889
[278]	validation_0-mae:2188.81520
[279]	validation_0-mae:2188.47535
[280]	validation_0-mae:2187.84090
[281]	validation_0-mae:2185.58052
[282]	validation_0-mae:2185.77867
[283]	validation_0-mae:2185.09351
[284]	validation_0-mae:2184.05101
[285]	validation_0-mae:2184.09399
[286]	validation_0-mae:2183.27486
[287]	validation_0-mae:2183.36917
[288]	validation_0-mae:2184.32674
[289]	validation_0-mae:2183.56881
[290]	validation_0-mae:2183.55933
[291]	validation_0-mae:2183.24721
[292]	validation_0-mae:2184.22098
[293]	validation_0-mae:2183.76021
[294]	validation_0-mae:2183.14416
[295]	validation_0-mae:2182.36560
[296]	validation_0-mae:2180.95330
[297]	validation_0-mae:2179.76267
[298]	validation_0-mae:2178.33087
[299]	validation_0-mae:2177.53648
[300]	validation_0-mae:2176.75152
[301]	validation_0-mae:2177.73542
[302]	validation_0-mae:2177.66604
[303]	validation_0-mae:2177.58413
[304]	validation_0-mae:2177.34799
[305]	validation_0-mae:2177.48125
[306]	validation_0-mae:2177.07046
[307]	validation_0-mae:2176.62861
[308]	validation_0-mae:2176.46347
[309]	validation_0-mae:2176.33739
[310]	validation_0-mae:2175.31818
[311]	validation_0-mae:2175.42138
[312]	validation_0-mae:2174.75461
[313]	validation_0-mae:2173.99568
[314]	validation_0-mae:2173.60538
[315]	validation_0-mae:2172.80097
[316]	validation_0-mae:2172.23529
[317]	validation_0-mae:2169.92056
[318]	validation_0-mae:2169.05666
[319]	validation_0-mae:2170.36549
[320]	validation_0-mae:2169.56904
[321]	validation_0-mae:2169.14802
[322]	validation_0-mae:2168.73314
[323]	validation_0-mae:2168.72102
[324]	validation_0-mae:2168.46117
[325]	validation_0-mae:2167.03648
[326]	validation_0-mae:2166.64966
[327]	validation_0-mae:2166.42476
[328]	validation_0-mae:2165.21030
[329]	validation_0-mae:2164.00027
[330]	validation_0-mae:2164.27266
[331]	validation_0-mae:2163.63185
[332]	validation_0-mae:2162.94643
[333]	validation_0-mae:2162.27297
[334]	validation_0-mae:2161.83736
[335]	validation_0-mae:2162.89736
[336]	validation_0-mae:2162.11910
[337]	validation_0-mae:2161.39110
[338]	validation_0-mae:2161.87634
[339]	validation_0-mae:2161.92450
[340]	validation_0-mae:2161.54981
[341]	validation_0-mae:2162.04503
[342]	validation_0-mae:2161.88217
[343]	validation_0-mae:2162.73936
[344]	validation_0-mae:2161.20379
[345]	validation_0-mae:2161.10949
[346]	validation_0-mae:2160.58818
[347]	validation_0-mae:2160.26902
[348]	validation_0-mae:2159.35026
[349]	validation_0-mae:2159.45112
[350]	validation_0-mae:2158.50859
[351]	validation_0-mae:2156.90000
[352]	validation_0-mae:2156.95631
[353]	validation_0-mae:2156.41843
[354]	validation_0-mae:2156.28474
[355]	validation_0-mae:2156.15213
[356]	validation_0-mae:2155.71642
[357]	validation_0-mae:2155.04914
[358]	validation_0-mae:2153.01287
[359]	validation_0-mae:2153.06458
[360]	validation_0-mae:2151.75809
[361]	validation_0-mae:2151.90715
[362]	validation_0-mae:2152.89681
[363]	validation_0-mae:2152.53583
[364]	validation_0-mae:2151.75736
[365]	validation_0-mae:2152.16979
[366]	validation_0-mae:2151.57825
[367]	validation_0-mae:2151.64814
[368]	validation_0-mae:2151.49897
[369]	validation_0-mae:2149.13160
[370]	validation_0-mae:2149.41940
[371]	validation_0-mae:2149.64277
[372]	validation_0-mae:2149.52572
[373]	validation_0-mae:2149.92410
[374]	validation_0-mae:2150.52070
[375]	validation_0-mae:2148.48970
[376]	validation_0-mae:2148.17523
[377]	validation_0-mae:2147.74563
[378]	validation_0-mae:2147.08733
[379]	validation_0-mae:2146.92767
[380]	validation_0-mae:2147.10229
[381]	validation_0-mae:2146.97666
[382]	validation_0-mae:2147.31726
[383]	validation_0-mae:2146.56607
[384]	validation_0-mae:2145.23321
[385]	validation_0-mae:2145.26535
[386]	validation_0-mae:2144.91095
[387]	validation_0-mae:2144.72610
[388]	validation_0-mae:2144.44363
[389]	validation_0-mae:2144.51059
[390]	validation_0-mae:2142.90616
[391]	validation_0-mae:2142.57611
[392]	validation_0-mae:2142.28876
[393]	validation_0-mae:2141.68224
[394]	validation_0-mae:2142.93972
[395]	validation_0-mae:2142.02594
[396]	validation_0-mae:2142.27580
[397]	validation_0-mae:2142.01073
[398]	validation_0-mae:2141.85013
[399]	validation_0-mae:2140.79042
[400]	validation_0-mae:2140.63291
[401]	validation_0-mae:2140.32909
[402]	validation_0-mae:2140.22159
[403]	validation_0-mae:2140.19961
[404]	validation_0-mae:2139.91251
[405]	validation_0-mae:2139.28236
[406]	validation_0-mae:2139.39532
[407]	validation_0-mae:2139.14339
[408]	validation_0-mae:2139.27909
[409]	validation_0-mae:2139.23052
[410]	validation_0-mae:2139.07485
[411]	validation_0-mae:2139.42432
[412]	validation_0-mae:2139.70640
[413]	validation_0-mae:2139.14515
[414]	validation_0-mae:2137.94539
[415]	validation_0-mae:2137.76662
[416]	validation_0-mae:2137.71301
[417]	validation_0-mae:2138.61664
[418]	validation_0-mae:2138.60783
[419]	validation_0-mae:2138.75740
[420]	validation_0-mae:2138.64350
[421]	validation_0-mae:2138.83917
[422]	validation_0-mae:2138.63320
[423]	validation_0-mae:2139.38488
[424]	validation_0-mae:2138.96450
[425]	validation_0-mae:2139.18116
[426]	validation_0-mae:2139.25891
[427]	validation_0-mae:2138.99053
[428]	validation_0-mae:2138.50256
[429]	validation_0-mae:2138.25741
[430]	validation_0-mae:2138.47027
[431]	validation_0-mae:2137.91779
[432]	validation_0-mae:2137.91640
[433]	validation_0-mae:2137.62535
[434]	validation_0-mae:2137.73018
[435]	validation_0-mae:2137.57108
[436]	validation_0-mae:2137.74790
[437]	validation_0-mae:2137.09590
[438]	validation_0-mae:2137.64854
[439]	validation_0-mae:2137.51684
[440]	validation_0-mae:2137.36925
[441]	validation_0-mae:2137.07379
[442]	validation_0-mae:2137.08735
[443]	validation_0-mae:2136.86653
[444]	validation_0-mae:2136.72175
[445]	validation_0-mae:2136.37906
[446]	validation_0-mae:2136.08136
[447]	validation_0-mae:2135.39130
[448]	validation_0-mae:2134.55733
[449]	validation_0-mae:2134.59663
[450]	validation_0-mae:2134.53518
[451]	validation_0-mae:2134.62904
[452]	validation_0-mae:2135.02510
[453]	validation_0-mae:2135.25202
[454]	validation_0-mae:2135.65020
[455]	validation_0-mae:2134.52448
[456]	validation_0-mae:2133.23458
[457]	validation_0-mae:2132.80396
[458]	validation_0-mae:2131.67712
[459]	validation_0-mae:2131.58628
[460]	validation_0-mae:2129.97998
[461]	validation_0-mae:2129.76770
[462]	validation_0-mae:2129.32659
[463]	validation_0-mae:2129.25462
[464]	validation_0-mae:2128.96677
[465]	validation_0-mae:2128.92608
[466]	validation_0-mae:2128.69818
[467]	validation_0-mae:2128.14112
[468]	validation_0-mae:2127.53546
[469]	validation_0-mae:2127.87871
[470]	validation_0-mae:2127.81920
[471]	validation_0-mae:2128.26173
[472]	validation_0-mae:2129.01230
[473]	validation_0-mae:2129.21525
[474]	validation_0-mae:2129.45946
[475]	validation_0-mae:2129.34842
[476]	validation_0-mae:2129.36502
[477]	validation_0-mae:2129.20054
[478]	validation_0-mae:2129.64352
[479]	validation_0-mae:2129.75065
[480]	validation_0-mae:2129.46016
[481]	validation_0-mae:2129.29142
[482]	validation_0-mae:2129.11607
[483]	validation_0-mae:2129.22650
[484]	validation_0-mae:2128.96026
[485]	validation_0-mae:2129.74704
[486]	validation_0-mae:2129.82256
[487]	validation_0-mae:2129.37709
[488]	validation_0-mae:2128.93239
[489]	validation_0-mae:2128.98108
[490]	validation_0-mae:2129.60460
[491]	validation_0-mae:2129.37877
[492]	validation_0-mae:2129.30010
[493]	validation_0-mae:2129.12665
[494]	validation_0-mae:2129.01836
[495]	validation_0-mae:2128.86196
[496]	validation_0-mae:2127.94071
[497]	validation_0-mae:2128.30865
[498]	validation_0-mae:2128.44576
[499]	validation_0-mae:2128.35008
[500]	validation_0-mae:2128.31438
[501]	validation_0-mae:2128.35586
[502]	validation_0-mae:2128.63721
[503]	validation_0-mae:2128.62923
[504]	validation_0-mae:2128.68487
[505]	validation_0-mae:2128.71875
[506]	validation_0-mae:2128.64916
[507]	validation_0-mae:2128.29377
[508]	validation_0-mae:2128.29325
[509]	validation_0-mae:2128.61177
[510]	validation_0-mae:2127.66673
[511]	validation_0-mae:2127.79955
[512]	validation_0-mae:2128.08394
[513]	validation_0-mae:2127.15720
[514]	validation_0-mae:2126.54525
[515]	validation_0-mae:2125.45457
[516]	validation_0-mae:2125.17269
[517]	validation_0-mae:2124.14286
[518]	validation_0-mae:2123.86758
[519]	validation_0-mae:2124.22948
[520]	validation_0-mae:2124.66225
[521]	validation_0-mae:2124.58015
[522]	validation_0-mae:2124.23855
[523]	validation_0-mae:2124.94189
[524]	validation_0-mae:2124.83578
[525]	validation_0-mae:2125.20379
[526]	validation_0-mae:2124.49736
[527]	validation_0-mae:2123.92440
[528]	validation_0-mae:2124.20353
[529]	validation_0-mae:2124.18195
[530]	validation_0-mae:2124.12696
[531]	validation_0-mae:2123.18992
[532]	validation_0-mae:2122.75988
[533]	validation_0-mae:2123.08288
[534]	validation_0-mae:2123.34686
[535]	validation_0-mae:2123.17589
[536]	validation_0-mae:2123.08738
[537]	validation_0-mae:2122.86093
[538]	validation_0-mae:2122.58170
[539]	validation_0-mae:2122.25364
[540]	validation_0-mae:2122.62092
[541]	validation_0-mae:2121.98934
[542]	validation_0-mae:2122.06861
[543]	validation_0-mae:2122.91993
[544]	validation_0-mae:2122.90838
[545]	validation_0-mae:2122.69378
[546]	validation_0-mae:2122.58171
[547]	validation_0-mae:2122.35344
[548]	validation_0-mae:2121.72388
[549]	validation_0-mae:2120.42531
[550]	validation_0-mae:2120.38002
[551]	validation_0-mae:2120.18919
[552]	validation_0-mae:2120.32869
[553]	validation_0-mae:2120.22842
[554]	validation_0-mae:2118.91767
[555]	validation_0-mae:2118.66514
[556]	validation_0-mae:2118.73236
[557]	validation_0-mae:2119.04088
[558]	validation_0-mae:2119.02188
[559]	validation_0-mae:2119.07622
[560]	validation_0-mae:2119.27529
[561]	validation_0-mae:2119.27642
[562]	validation_0-mae:2117.64620
[563]	validation_0-mae:2117.34011
[564]	validation_0-mae:2117.38069
[565]	validation_0-mae:2116.82271
[566]	validation_0-mae:2116.64370
[567]	validation_0-mae:2116.89671
[568]	validation_0-mae:2116.81910
[569]	validation_0-mae:2116.73102
[570]	validation_0-mae:2115.91329
[571]	validation_0-mae:2115.96890
[572]	validation_0-mae:2115.02774
[573]	validation_0-mae:2114.33714
[574]	validation_0-mae:2114.61653
[575]	validation_0-mae:2114.87428
[576]	validation_0-mae:2115.13544
[577]	validation_0-mae:2115.11028
[578]	validation_0-mae:2114.35312
[579]	validation_0-mae:2114.63416
[580]	validation_0-mae:2114.49650
[581]	validation_0-mae:2113.14098
[582]	validation_0-mae:2113.18892
[583]	validation_0-mae:2113.60588
[584]	validation_0-mae:2112.15033
[585]	validation_0-mae:2112.25500
[586]	validation_0-mae:2111.11672
[587]	validation_0-mae:2110.35333
[588]	validation_0-mae:2110.52793
[589]	validation_0-mae:2110.76728
[590]	validation_0-mae:2111.19583
[591]	validation_0-mae:2110.80897
[592]	validation_0-mae:2110.14161
[593]	validation_0-mae:2109.81557
[594]	validation_0-mae:2110.04115
[595]	validation_0-mae:2110.00093
[596]	validation_0-mae:2109.98644
[597]	validation_0-mae:2110.54983
[598]	validation_0-mae:2110.32310
[599]	validation_0-mae:2110.24644
[600]	validation_0-mae:2110.81088
[601]	validation_0-mae:2111.33427
[602]	validation_0-mae:2110.62337
[603]	validation_0-mae:2110.70365
[604]	validation_0-mae:2110.76039
[605]	validation_0-mae:2110.33630
[606]	validation_0-mae:2110.43504
[607]	validation_0-mae:2110.12780
[608]	validation_0-mae:2110.17743
[609]	validation_0-mae:2110.28623
[610]	validation_0-mae:2109.75586
[611]	validation_0-mae:2110.16416
[612]	validation_0-mae:2110.59083
[613]	validation_0-mae:2110.57539
[614]	validation_0-mae:2110.65924
[615]	validation_0-mae:2109.71287
[616]	validation_0-mae:2108.97175
[617]	validation_0-mae:2109.04858
[618]	validation_0-mae:2109.28476
[619]	validation_0-mae:2108.83202
[620]	validation_0-mae:2107.98288
[621]	validation_0-mae:2108.06966
[622]	validation_0-mae:2107.27202
[623]	validation_0-mae:2106.45317
[624]	validation_0-mae:2106.38420
[625]	validation_0-mae:2105.13206
[626]	validation_0-mae:2104.90273
[627]	validation_0-mae:2104.75606
[628]	validation_0-mae:2104.22401
[629]	validation_0-mae:2103.21123

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[0]	validation_0-mae:12663.42005
[1]	validation_0-mae:12098.68404
[2]	validation_0-mae:11583.11585
[3]	validation_0-mae:11106.07500
[4]	validation_0-mae:10662.88197
[5]	validation_0-mae:10259.90821
[6]	validation_0-mae:9907.75313
[7]	validation_0-mae:9561.22724
[8]	validation_0-mae:9261.13973
[9]	validation_0-mae:8937.37056

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[0]	validation_0-mae:12688.67091
[1]	validation_0-mae:12151.61486
[2]	validation_0-mae:11668.51342
[3]	validation_0-mae:11250.20452
[4]	validation_0-mae:10873.43438
[5]	validation_0-mae:10523.10397
[6]	validation_0-mae:10202.17804
[7]	validation_0-mae:9937.72471
[8]	validation_0-mae:9662.22310
[9]	validation_0-mae:9435.09238
[10]	validation_0-mae:9213.26800
[0]	validation_0-mae:12522.38445
[1]	validation_0-mae:11834.26438
[2]	validation_0-mae:11235.68559
[3]	validation_0-mae:10669.95507
[4]	validation_0-mae:10176.45918
[5]	validation_0-mae:9706.73053
[6]	validation_0-mae:9296.96752
[7]	validation_0-mae:8938.12096
[8]	validation_0-mae:8605.77105
[9]	validation_0-mae:8277.52287
[10]	validation_0-mae:8005.12466
[11]	validation_0-mae:7721.32183
[12]	validation_0-mae:7432.31731
[13]	validation_0-mae:7163.97864
[14]	validation_0-mae:6945.90135
[15]	validation_0-mae:6736.06687
[16]	validation_0-mae:6538.09750
[17]	validation_0-mae:6351.70144
[18]	validation_0-mae:6138.44166
[19]	validation_0-mae:5984.31654
[20]	validation_0-mae:5805.57619
[21]	validation_0-mae:5652.03806
[22]	validation_0-mae:5487.69677
[23]	validation_0-mae:5354.15169
[24]	validation_0-mae:5209.19583
[25]	validation_0-mae:5092.09930
[26]	validation_0-mae:4976.39783
[27]	validation_0-mae:4863.41956
[28]	validation_0-mae:4745.51029
[29]	validation_0-mae:4648.88005
[30]	validation_0-mae:4543.84919
[31]	validation_0-mae:4446.68552
[32]	validation_0-mae:4345.31295
[33]	validation_0-mae:4258.86120
[34]	validation_0-mae:4175.38414
[35]	validation_0-mae:4110.37956
[36]	validation_0-mae:4032.05437
[37]	validation_0-mae:3964.62928
[38]	validation_0-mae:3883.50403
[39]	validation_0-mae:3822.22310
[40]	validation_0-mae:3758.60090
[41]	validation_0-mae:3704.55592
[42]	validation_0-mae:3654.87671
[43]	validation_0-mae:3612.99085
[44]	validation_0-mae:3572.89811
[45]	validation_0-mae:3530.63931

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[46]	validation_0-mae:3490.00041
[47]	validation_0-mae:3449.29496
[48]	validation_0-mae:3409.14732
[49]	validation_0-mae:3372.35144
[50]	validation_0-mae:3344.48950
[51]	validation_0-mae:3321.43947
[52]	validation_0-mae:3290.22841
[53]	validation_0-mae:3264.02107
[54]	validation_0-mae:3226.55045
[55]	validation_0-mae:3206.23606
[56]	validation_0-mae:3168.94818
[57]	validation_0-mae:3138.78661
[58]	validation_0-mae:3115.55420
[59]	validation_0-mae:3101.66902
[60]	validation_0-mae:3051.19893
[61]	validation_0-mae:3023.30189
[62]	validation_0-mae:3004.89932
[63]	validation_0-mae:2985.51000
[64]	validation_0-mae:2968.51418
[65]	validation_0-mae:2948.25870
[66]	validation_0-mae:2930.66623
[67]	validation_0-mae:2913.21352
[68]	validation_0-mae:2896.33623
[69]	validation_0-mae:2884.43474
[70]	validation_0-mae:2870.49344
[71]	validation_0-mae:2860.32683
[72]	validation_0-mae:2852.11070
[73]	validation_0-mae:2839.63358
[74]	validation_0-mae:2829.91960
[75]	validation_0-mae:2808.71914
[76]	validation_0-mae:2798.19412
[77]	validation_0-mae:2783.17325
[78]	validation_0-mae:2775.12527
[79]	validation_0-mae:2765.40202
[80]	validation_0-mae:2747.86561
[81]	validation_0-mae:2732.05335
[82]	validation_0-mae:2724.75200
[83]	validation_0-mae:2718.85441
[84]	validation_0-mae:2702.27721
[85]	validation_0-mae:2699.03731
[86]	validation_0-mae:2687.45669
[87]	validation_0-mae:2680.41712
[88]	validation_0-mae:2670.76660
[89]	validation_0-mae:2665.37164
[90]	validation_0-mae:2650.73520
[91]	validation_0-mae:2643.75963
[92]	validation_0-mae:2634.08423
[93]	validation_0-mae:2631.58618
[94]	validation_0-mae:2624.17691
[95]	validation_0-mae:2613.65125
[96]	validation_0-mae:2606.61172
[97]	validation_0-mae:2592.75810
[98]	validation_0-mae:2584.81729
[99]	validation_0-mae:2574.44737
[100]	validation_0-mae:2569.43076
[101]	validation_0-mae:2563.50104
[102]	validation_0-mae:2558.77488
[103]	validation_0-mae:2550.65558
[104]	validation_0-mae:2542.52721
[105]	validation_0-mae:2530.20883
[106]	validation_0-mae:2523.11853
[107]	validation_0-mae:2518.46780
[108]	validation_0-mae:2514.14970
[109]	validation_0-mae:2505.32086
[110]	validation_0-mae:2499.64411
[111]	validation_0-mae:2493.51695
[112]	validation_0-mae:2487.42619
[113]	validation_0-mae:2482.46387
[114]	validation_0-mae:2470.35822
[115]	validation_0-mae:2467.40565
[116]	validation_0-mae:2460.82574
[117]	validation_0-mae:2455.22606
[118]	validation_0-mae:2449.20633
[119]	validation_0-mae:2446.82522
[120]	validation_0-mae:2443.74081
[121]	validation_0-mae:2440.57599
[122]	validation_0-mae:2435.45716
[123]	validation_0-mae:2430.26425
[124]	validation_0-mae:2427.18209
[125]	validation_0-mae:2416.50778
[126]	validation_0-mae:2414.52156
[127]	validation_0-mae:2409.74241
[128]	validation_0-mae:2405.35066
[129]	validation_0-mae:2402.32056
[130]	validation_0-mae:2400.20497
[131]	validation_0-mae:2396.75174
[132]	validation_0-mae:2391.84518
[133]	validation_0-mae:2390.25856
[134]	validation_0-mae:2386.65416
[135]	validation_0-mae:2385.23925
[136]	validation_0-mae:2380.70833
[137]	validation_0-mae:2376.88388
[138]	validation_0-mae:2373.69929
[139]	validation_0-mae:2370.46657
[140]	validation_0-mae:2367.15497
[141]	validation_0-mae:2364.97072
[142]	validation_0-mae:2362.65599
[143]	validation_0-mae:2359.74731
[144]	validation_0-mae:2356.92949
[145]	validation_0-mae:2356.37114
[146]	validation_0-mae:2354.15812
[147]	validation_0-mae:2347.82443
[148]	validation_0-mae:2346.72971
[149]	validation_0-mae:2342.39765
[150]	validation_0-mae:2339.97098
[151]	validation_0-mae:2338.83796
[152]	validation_0-mae:2336.66035
[153]	validation_0-mae:2332.95553
[154]	validation_0-mae:2332.61028
[155]	validation_0-mae:2331.68531
[156]	validation_0-mae:2328.18587
[157]	validation_0-mae:2324.90268
[158]	validation_0-mae:2322.93791
[159]	validation_0-mae:2316.99826
[160]	validation_0-mae:2314.25813
[161]	validation_0-mae:2312.42497
[162]	validation_0-mae:2311.54594
[163]	validation_0-mae:2310.63575
[164]	validation_0-mae:2309.03253
[165]	validation_0-mae:2305.99270
[166]	validation_0-mae:2302.17464
[167]	validation_0-mae:2298.26025
[168]	validation_0-mae:2293.69825
[169]	validation_0-mae:2294.53099
[170]	validation_0-mae:2293.43494
[171]	validation_0-mae:2291.33890
[172]	validation_0-mae:2286.79971
[173]	validation_0-mae:2285.14323
[174]	validation_0-mae:2285.30898
[175]	validation_0-mae:2280.18541
[176]	validation_0-mae:2279.47211
[177]	validation_0-mae:2277.78061
[178]	validation_0-mae:2277.47623
[179]	validation_0-mae:2275.64002
[180]	validation_0-mae:2272.26673
[181]	validation_0-mae:2272.37961
[182]	validation_0-mae:2272.16376
[183]	validation_0-mae:2269.21734
[184]	validation_0-mae:2267.32694
[185]	validation_0-mae:2266.74338
[186]	validation_0-mae:2265.06733
[187]	validation_0-mae:2264.63348
[188]	validation_0-mae:2265.03481
[189]	validation_0-mae:2263.94469
[190]	validation_0-mae:2263.93628
[191]	validation_0-mae:2262.15854
[192]	validation_0-mae:2262.58674
[193]	validation_0-mae:2261.51503
[194]	validation_0-mae:2260.08372
[195]	validation_0-mae:2257.92413
[196]	validation_0-mae:2258.43516
[197]	validation_0-mae:2256.31175
[198]	validation_0-mae:2255.26744
[199]	validation_0-mae:2254.59726
[200]	validation_0-mae:2254.09347
[201]	validation_0-mae:2253.07586
[202]	validation_0-mae:2252.39309
[203]	validation_0-mae:2251.52070
[204]	validation_0-mae:2250.78755
[205]	validation_0-mae:2249.94135
[206]	validation_0-mae:2249.17654
[207]	validation_0-mae:2248.17076
[208]	validation_0-mae:2248.51013
[209]	validation_0-mae:2246.42764
[210]	validation_0-mae:2245.76338
[211]	validation_0-mae:2243.70125
[212]	validation_0-mae:2242.27713
[213]	validation_0-mae:2242.44716
[214]	validation_0-mae:2242.65079
[215]	validation_0-mae:2242.50169
[216]	validation_0-mae:2242.29375
[217]	validation_0-mae:2241.29820
[218]	validation_0-mae:2241.86163
[219]	validation_0-mae:2241.37453
[220]	validation_0-mae:2240.90501
[221]	validation_0-mae:2239.70505
[222]	validation_0-mae:2238.71757
[223]	validation_0-mae:2238.97550
[224]	validation_0-mae:2238.12535
[225]	validation_0-mae:2237.29046
[226]	validation_0-mae:2235.80370
[227]	validation_0-mae:2235.46364
[228]	validation_0-mae:2234.84159
[229]	validation_0-mae:2234.56721
[230]	validation_0-mae:2233.48813
[231]	validation_0-mae:2232.06083
[232]	validation_0-mae:2230.94579
[233]	validation_0-mae:2231.60561
[234]	validation_0-mae:2230.89019
[235]	validation_0-mae:2231.88862
[236]	validation_0-mae:2229.59816
[237]	validation_0-mae:2228.41352
[238]	validation_0-mae:2228.31882
[239]	validation_0-mae:2228.13591
[240]	validation_0-mae:2226.73730
[241]	validation_0-mae:2225.51886
[242]	validation_0-mae:2224.80133
[243]	validation_0-mae:2223.65882
[244]	validation_0-mae:2223.29116
[245]	validation_0-mae:2223.03751
[246]	validation_0-mae:2220.17808
[247]	validation_0-mae:2219.71571
[248]	validation_0-mae:2219.84454
[249]	validation_0-mae:2219.45196
[250]	validation_0-mae:2217.49772
[251]	validation_0-mae:2218.13646
[252]	validation_0-mae:2217.78137
[253]	validation_0-mae:2217.11984
[254]	validation_0-mae:2214.99198
[255]	validation_0-mae:2214.14578
[256]	validation_0-mae:2213.40705
[257]	validation_0-mae:2212.39060
[258]	validation_0-mae:2212.53013
[259]	validation_0-mae:2211.53689
[260]	validation_0-mae:2210.10065
[261]	validation_0-mae:2209.92452
[262]	validation_0-mae:2205.74869
[263]	validation_0-mae:2205.25914
[264]	validation_0-mae:2203.80365
[265]	validation_0-mae:2202.59819
[266]	validation_0-mae:2202.04473
[267]	validation_0-mae:2200.82065
[268]	validation_0-mae:2200.93417
[269]	validation_0-mae:2200.22538
[270]	validation_0-mae:2199.87772
[271]	validation_0-mae:2199.16022
[272]	validation_0-mae:2198.77010
[273]	validation_0-mae:2196.20786
[274]	validation_0-mae:2195.82880
[275]	validation_0-mae:2196.68397
[276]	validation_0-mae:2196.01748
[277]	validation_0-mae:2195.19693
[278]	validation_0-mae:2194.88146
[279]	validation_0-mae:2194.37672
[280]	validation_0-mae:2193.88203
[281]	validation_0-mae:2192.51989
[282]	validation_0-mae:2192.42913
[283]	validation_0-mae:2192.07141
[284]	validation_0-mae:2192.23747
[285]	validation_0-mae:2191.84830
[286]	validation_0-mae:2192.42240
[287]	validation_0-mae:2191.88201
[288]	validation_0-mae:2190.43433
[289]	validation_0-mae:2189.33457
[290]	validation_0-mae:2187.87878
[291]	validation_0-mae:2187.31692
[292]	validation_0-mae:2186.44005
[293]	validation_0-mae:2186.84589
[294]	validation_0-mae:2186.92098
[295]	validation_0-mae:2186.61254
[296]	validation_0-mae:2187.26025
[297]	validation_0-mae:2187.90368
[298]	validation_0-mae:2187.36765
[299]	validation_0-mae:2186.30849
[300]	validation_0-mae:2186.48720
[301]	validation_0-mae:2186.38882
[302]	validation_0-mae:2185.89640
[303]	validation_0-mae:2186.38141
[304]	validation_0-mae:2186.21234
[305]	validation_0-mae:2186.29417
[306]	validation_0-mae:2185.93501
[307]	validation_0-mae:2185.28817
[308]	validation_0-mae:2185.55501
[309]	validation_0-mae:2185.40976
[310]	validation_0-mae:2184.45380
[311]	validation_0-mae:2184.83079
[312]	validation_0-mae:2185.09972
[313]	validation_0-mae:2184.84295
[314]	validation_0-mae:2182.01633
[315]	validation_0-mae:2180.33810
[316]	validation_0-mae:2179.74549
[317]	validation_0-mae:2179.40619
[318]	validation_0-mae:2179.18508
[319]	validation_0-mae:2180.09330
[320]	validation_0-mae:2177.59034
[321]	validation_0-mae:2176.44870
[322]	validation_0-mae:2174.76988
[323]	validation_0-mae:2174.37651
[324]	validation_0-mae:2174.05409
[325]	validation_0-mae:2173.89351
[326]	validation_0-mae:2173.83052
[327]	validation_0-mae:2173.01693
[328]	validation_0-mae:2171.11728
[329]	validation_0-mae:2170.83677
[330]	validation_0-mae:2170.11901
[331]	validation_0-mae:2167.46346
[332]	validation_0-mae:2167.45937
[333]	validation_0-mae:2166.31701
[334]	validation_0-mae:2166.01579
[335]	validation_0-mae:2166.19955
[336]	validation_0-mae:2166.16216
[337]	validation_0-mae:2165.86959
[338]	validation_0-mae:2165.54959
[339]	validation_0-mae:2164.85528
[340]	validation_0-mae:2164.50515
[341]	validation_0-mae:2164.64843
[342]	validation_0-mae:2163.24132
[343]	validation_0-mae:2162.88487
[344]	validation_0-mae:2162.98307
[345]	validation_0-mae:2161.92511
[346]	validation_0-mae:2161.48865
[347]	validation_0-mae:2161.42284
[348]	validation_0-mae:2161.21312
[349]	validation_0-mae:2160.60626
[350]	validation_0-mae:2160.21824
[351]	validation_0-mae:2159.77437
[352]	validation_0-mae:2159.08661
[353]	validation_0-mae:2157.46951
[354]	validation_0-mae:2157.21162
[355]	validation_0-mae:2156.31448
[356]	validation_0-mae:2155.66876
[357]	validation_0-mae:2155.29600
[358]	validation_0-mae:2154.22870
[359]	validation_0-mae:2153.96549
[360]	validation_0-mae:2154.17674
[361]	validation_0-mae:2153.73427
[362]	validation_0-mae:2154.08200
[363]	validation_0-mae:2154.13502
[364]	validation_0-mae:2152.88101
[365]	validation_0-mae:2152.65764
[366]	validation_0-mae:2152.04788
[367]	validation_0-mae:2152.58794
[368]	validation_0-mae:2152.52360
[369]	validation_0-mae:2152.21940
[370]	validation_0-mae:2152.07103
[371]	validation_0-mae:2151.16645
[372]	validation_0-mae:2150.21511
[373]	validation_0-mae:2150.92700
[374]	validation_0-mae:2151.44332
[375]	validation_0-mae:2151.83040
[376]	validation_0-mae:2152.61625
[377]	validation_0-mae:2150.49195
[378]	validation_0-mae:2149.88836
[379]	validation_0-mae:2149.52606
[380]	validation_0-mae:2150.03841
[381]	validation_0-mae:2149.21673
[382]	validation_0-mae:2149.15444
[383]	validation_0-mae:2149.35917
[384]	validation_0-mae:2149.00736
[385]	validation_0-mae:2148.16466
[386]	validation_0-mae:2148.26106
[387]	validation_0-mae:2147.13861
[388]	validation_0-mae:2147.35048
[389]	validation_0-mae:2146.85603
[390]	validation_0-mae:2146.66807
[391]	validation_0-mae:2146.21703
[392]	validation_0-mae:2145.55354
[393]	validation_0-mae:2144.59216
[394]	validation_0-mae:2144.16563
[395]	validation_0-mae:2144.42801
[396]	validation_0-mae:2143.16426
[397]	validation_0-mae:2143.02730
[398]	validation_0-mae:2143.04483
[399]	validation_0-mae:2141.60543
[400]	validation_0-mae:2140.76106
[401]	validation_0-mae:2139.84918
[402]	validation_0-mae:2140.17780
[403]	validation_0-mae:2140.21023
[404]	validation_0-mae:2140.17041
[405]	validation_0-mae:2140.38740
[406]	validation_0-mae:2138.70365
[407]	validation_0-mae:2137.60286
[408]	validation_0-mae:2137.32702
[409]	validation_0-mae:2135.90133
[410]	validation_0-mae:2135.89034
[411]	validation_0-mae:2136.23206
[412]	validation_0-mae:2135.85028
[413]	validation_0-mae:2135.81382
[414]	validation_0-mae:2134.99585
[415]	validation_0-mae:2135.47092
[416]	validation_0-mae:2135.43301
[417]	validation_0-mae:2134.25861
[418]	validation_0-mae:2133.41859
[419]	validation_0-mae:2133.17615
[420]	validation_0-mae:2132.76959
[421]	validation_0-mae:2132.82948
[422]	validation_0-mae:2133.08591
[423]	validation_0-mae:2132.88360
[424]	validation_0-mae:2130.59641
[425]	validation_0-mae:2129.37347
[426]	validation_0-mae:2128.88294
[427]	validation_0-mae:2126.74121
[428]	validation_0-mae:2125.48407
[429]	validation_0-mae:2125.42715
[430]	validation_0-mae:2124.86603
[431]	validation_0-mae:2124.11710
[432]	validation_0-mae:2123.45955
[433]	validation_0-mae:2123.42656
[434]	validation_0-mae:2121.90638
[435]	validation_0-mae:2121.56796
[436]	validation_0-mae:2121.94483
[437]	validation_0-mae:2122.33303
[438]	validation_0-mae:2122.19189
[439]	validation_0-mae:2121.46860
[440]	validation_0-mae:2121.48491
[441]	validation_0-mae:2121.32318
[442]	validation_0-mae:2120.86168
[443]	validation_0-mae:2119.79221
[444]	validation_0-mae:2119.72645
[445]	validation_0-mae:2119.92170
[446]	validation_0-mae:2119.56353
[447]	validation_0-mae:2119.58162
[448]	validation_0-mae:2119.61935
[449]	validation_0-mae:2119.62055
[450]	validation_0-mae:2119.60771
[451]	validation_0-mae:2119.95988
[452]	validation_0-mae:2119.84949
[453]	validation_0-mae:2119.93858
[454]	validation_0-mae:2119.80644
[455]	validation_0-mae:2119.82967
[456]	validation_0-mae:2119.97414
[457]	validation_0-mae:2120.41154
[458]	validation_0-mae:2120.27351
[459]	validation_0-mae:2120.40413
[460]	validation_0-mae:2119.96089
[461]	validation_0-mae:2119.59568
[462]	validation_0-mae:2119.40248
[463]	validation_0-mae:2118.86210
[464]	validation_0-mae:2118.29492
[465]	validation_0-mae:2117.82562
[466]	validation_0-mae:2117.58782
[467]	validation_0-mae:2116.56763
[468]	validation_0-mae:2115.55917
[469]	validation_0-mae:2115.14596
[470]	validation_0-mae:2115.16439
[471]	validation_0-mae:2114.97234
[472]	validation_0-mae:2114.79686
[473]	validation_0-mae:2114.75605
[474]	validation_0-mae:2114.94277
[475]	validation_0-mae:2115.47654
[476]	validation_0-mae:2115.37155
[477]	validation_0-mae:2115.14590
[478]	validation_0-mae:2114.80253
[479]	validation_0-mae:2114.69944
[480]	validation_0-mae:2114.70840
[481]	validation_0-mae:2114.25385
[482]	validation_0-mae:2114.21516
[483]	validation_0-mae:2114.51213
[484]	validation_0-mae:2113.80718
[485]	validation_0-mae:2113.44702
[486]	validation_0-mae:2113.54566
[487]	validation_0-mae:2112.71571
[488]	validation_0-mae:2112.90051
[489]	validation_0-mae:2112.70668
[490]	validation_0-mae:2112.30325
[491]	validation_0-mae:2111.96718
[492]	validation_0-mae:2111.91711
[493]	validation_0-mae:2112.44982
[494]	validation_0-mae:2112.76313
[495]	validation_0-mae:2113.36544
[496]	validation_0-mae:2113.11735
[497]	validation_0-mae:2113.21228
[498]	validation_0-mae:2113.48134
[499]	validation_0-mae:2113.35637
[500]	validation_0-mae:2113.68409
[501]	validation_0-mae:2113.72221
[502]	validation_0-mae:2113.81055
[503]	validation_0-mae:2113.26577
[504]	validation_0-mae:2113.49954
[505]	validation_0-mae:2113.92857
[506]	validation_0-mae:2113.96023
[507]	validation_0-mae:2114.41047
[508]	validation_0-mae:2114.19402
[509]	validation_0-mae:2113.91913
[510]	validation_0-mae:2113.51019
[511]	validation_0-mae:2113.39656
[512]	validation_0-mae:2113.30818
[513]	validation_0-mae:2113.33282
[514]	validation_0-mae:2113.26684
[515]	validation_0-mae:2112.08448
[516]	validation_0-mae:2110.42623
[517]	validation_0-mae:2110.60180
[518]	validation_0-mae:2110.08054
[519]	validation_0-mae:2109.99316
[520]	validation_0-mae:2108.47805
[521]	validation_0-mae:2108.00166
[522]	validation_0-mae:2106.97546
[523]	validation_0-mae:2107.34308
[524]	validation_0-mae:2106.30738
[525]	validation_0-mae:2106.09201
[526]	validation_0-mae:2106.09294
[527]	validation_0-mae:2105.03653
[528]	validation_0-mae:2104.92293
[529]	validation_0-mae:2105.38799
[530]	validation_0-mae:2105.42547
[531]	validation_0-mae:2104.71567
[532]	validation_0-mae:2103.89522
[533]	validation_0-mae:2102.87620
[534]	validation_0-mae:2102.80943
[535]	validation_0-mae:2102.79640
[536]	validation_0-mae:2102.11700
[537]	validation_0-mae:2102.09263
[538]	validation_0-mae:2101.48376
[539]	validation_0-mae:2100.18778
[540]	validation_0-mae:2099.82401
[541]	validation_0-mae:2099.21111
[542]	validation_0-mae:2099.32571
[543]	validation_0-mae:2099.29477
[544]	validation_0-mae:2099.24145
[545]	validation_0-mae:2098.76550
[546]	validation_0-mae:2098.61527
[547]	validation_0-mae:2098.40048
[548]	validation_0-mae:2097.60700
[549]	validation_0-mae:2097.13395
[550]	validation_0-mae:2096.65190
[551]	validation_0-mae:2096.89265
[552]	validation_0-mae:2096.89050
[553]	validation_0-mae:2096.91935
[554]	validation_0-mae:2096.97465
[555]	validation_0-mae:2097.14884
[556]	validation_0-mae:2097.41022
[557]	validation_0-mae:2097.30492
[558]	validation_0-mae:2097.38530
[559]	validation_0-mae:2097.40560
[560]	validation_0-mae:2097.29459
[561]	validation_0-mae:2097.15899
[562]	validation_0-mae:2097.38046
[563]	validation_0-mae:2096.33470
[564]	validation_0-mae:2096.48850
[565]	validation_0-mae:2096.06441
[566]	validation_0-mae:2096.31509
[567]	validation_0-mae:2096.74593
[568]	validation_0-mae:2097.03557
[569]	validation_0-mae:2096.87993
[570]	validation_0-mae:2096.77864
[571]	validation_0-mae:2096.84595
[572]	validation_0-mae:2097.14213
[573]	validation_0-mae:2097.10793
[574]	validation_0-mae:2097.05203
[575]	validation_0-mae:2097.69626
[576]	validation_0-mae:2097.81587
[577]	validation_0-mae:2097.23532
[578]	validation_0-mae:2097.45801
[579]	validation_0-mae:2096.84769
[580]	validation_0-mae:2097.31391
[581]	validation_0-mae:2097.32340
[582]	validation_0-mae:2097.57902
[583]	validation_0-mae:2097.61683
[584]	validation_0-mae:2097.02266
[585]	validation_0-mae:2097.12740
[586]	validation_0-mae:2097.03268
[587]	validation_0-mae:2097.18132
[588]	validation_0-mae:2097.40175
[589]	validation_0-mae:2097.50532
[590]	validation_0-mae:2097.34248
[591]	validation_0-mae:2096.96794
[592]	validation_0-mae:2096.71310
[593]	validation_0-mae:2096.26745
[594]	validation_0-mae:2096.32899
[595]	validation_0-mae:2096.64823
[596]	validation_0-mae:2096.24016
[597]	validation_0-mae:2096.25831
[598]	validation_0-mae:2096.10065
[599]	validation_0-mae:2096.15016
[600]	validation_0-mae:2096.39555
[601]	validation_0-mae:2095.82315
[602]	validation_0-mae:2096.02348
[603]	validation_0-mae:2095.80045
[604]	validation_0-mae:2095.96780
[605]	validation_0-mae:2095.74738
[606]	validation_0-mae:2095.92627
[607]	validation_0-mae:2095.67034
[608]	validation_0-mae:2095.89943
[609]	validation_0-mae:2095.82542
[610]	validation_0-mae:2096.12790
[611]	validation_0-mae:2096.17640
[612]	validation_0-mae:2095.99891
[613]	validation_0-mae:2095.77045
[614]	validation_0-mae:2095.69980
[615]	validation_0-mae:2096.26895
[616]	validation_0-mae:2096.50101
[617]	validation_0-mae:2095.89879
[618]	validation_0-mae:2095.81294
[619]	validation_0-mae:2095.86653
[620]	validation_0-mae:2095.68455
[621]	validation_0-mae:2095.68069
[622]	validation_0-mae:2095.87761
[623]	validation_0-mae:2095.36636
[624]	validation_0-mae:2095.25131
[625]	validation_0-mae:2095.71139
[626]	validation_0-mae:2095.69753
[627]	validation_0-mae:2095.60011
[628]	validation_0-mae:2096.15319
[629]	validation_0-mae:2096.59816
[630]	validation_0-mae:2096.26598
[631]	validation_0-mae:2095.44026
[632]	validation_0-mae:2094.66355
[633]	validation_0-mae:2094.85851
[634]	validation_0-mae:2094.97768

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[44]	validation_0-mae:3508.95878
[45]	validation_0-mae:3438.59653
[46]	validation_0-mae:3403.50943
[47]	validation_0-mae:3377.46188
[48]	validation_0-mae:3337.75148
[49]	validation_0-mae:3312.16118
[50]	validation_0-mae:3279.19970
[51]	validation_0-mae:3251.55700
[52]	validation_0-mae:3223.98588
[53]	validation_0-mae:3190.12257
[54]	validation_0-mae:3164.37571
[55]	validation_0-mae:3144.61987
[56]	validation_0-mae:3120.67465
[57]	validation_0-mae:3088.43847
[58]	validation_0-mae:3067.80872
[59]	validation_0-mae:3034.87905
[60]	validation_0-mae:3020.68062
[61]	validation_0-mae:2996.99143
[62]	validation_0-mae:2980.27353
[63]	validation_0-mae:2968.74894
[64]	validation_0-mae:2957.39641
[65]	validation_0-mae:2947.04014
[66]	validation_0-mae:2939.42629
[67]	validation_0-mae:2916.42993
[68]	validation_0-mae:2904.95753
[69]	validation_0-mae:2892.97474
[70]	validation_0-mae:2870.41967
[71]	validation_0-mae:2860.23562
[72]	validation_0-mae:2847.64174
[73]	validation_0-mae:2825.21412
[74]	validation_0-mae:2818.20947
[75]	validation_0-mae:2800.06283
[76]	validation_0-mae:2784.14133
[77]	validation_0-mae:2769.00517
[78]	validation_0-mae:2763.09470
[79]	validation_0-mae:2750.16599
[80]	validation_0-mae:2744.54210
[81]	validation_0-mae:2735.86137
[82]	validation_0-mae:2732.63401
[83]	validation_0-mae:2723.56101
[84]	validation_0-mae:2707.17871
[85]	validation_0-mae:2700.12461
[86]	validation_0-mae:2693.11120
[87]	validation_0-mae:2682.88586
[88]	validation_0-mae:2677.38380
[89]	validation_0-mae:2670.62709
[90]	validation_0-mae:2664.15318
[91]	validation_0-mae:2655.82874
[92]	validation_0-mae:2646.37181
[93]	validation_0-mae:2632.57212
[94]	validation_0-mae:2627.77001
[95]	validation_0-mae:2611.64928
[96]	validation_0-mae:2606.01851
[97]	validation_0-mae:2599.43911
[98]	validation_0-mae:2594.51800
[99]	validation_0-mae:2588.57523
[100]	validation_0-mae:2577.71516
[101]	validation_0-mae:2572.17081
[102]	validation_0-mae:2560.92306
[103]	validation_0-mae:2552.50980
[104]	validation_0-mae:2544.67097
[105]	validation_0-mae:2537.13025
[106]	validation_0-mae:2530.02950
[107]	validation_0-mae:2519.54848
[108]	validation_0-mae:2515.18314
[109]	validation_0-mae:2510.45046
[110]	validation_0-mae:2504.07196
[111]	validation_0-mae:2497.72570
[112]	validation_0-mae:2491.72423
[113]	validation_0-mae:2484.86734
[114]	validation_0-mae:2479.63321
[115]	validation_0-mae:2474.11972
[116]	validation_0-mae:2470.02247
[117]	validation_0-mae:2465.61361
[118]	validation_0-mae:2461.92658
[119]	validation_0-mae:2457.37807
[120]	validation_0-mae:2450.95572
[121]	validation_0-mae:2447.66003
[122]	validation_0-mae:2442.27875
[123]	validation_0-mae:2438.68141
[124]	validation_0-mae:2433.91635
[125]	validation_0-mae:2431.61478
[126]	validation_0-mae:2426.54045
[127]	validation_0-mae:2422.33599
[128]	validation_0-mae:2418.50430
[129]	validation_0-mae:2416.36436
[130]	validation_0-mae:2415.52541
[131]	validation_0-mae:2413.19855
[132]	validation_0-mae:2407.58265
[133]	validation_0-mae:2402.64717
[134]	validation_0-mae:2392.75055
[135]	validation_0-mae:2390.17777
[136]	validation_0-mae:2387.14466
[137]	validation_0-mae:2384.56588
[138]	validation_0-mae:2378.38122
[139]	validation_0-mae:2379.50027
[140]	validation_0-mae:2376.44831
[141]	validation_0-mae:2371.61958
[142]	validation_0-mae:2365.45190
[143]	validation_0-mae:2365.33520
[144]	validation_0-mae:2362.98717
[145]	validation_0-mae:2360.50788
[146]	validation_0-mae:2357.96542
[147]	validation_0-mae:2353.25334
[148]	validation_0-mae:2351.28178
[149]	validation_0-mae:2351.16649
[150]	validation_0-mae:2347.99498
[151]	validation_0-mae:2347.23396
[152]	validation_0-mae:2346.99812
[153]	validation_0-mae:2344.88002
[154]	validation_0-mae:2344.85166
[155]	validation_0-mae:2341.82840
[156]	validation_0-mae:2340.55902
[157]	validation_0-mae:2340.52945
[158]	validation_0-mae:2337.30104
[159]	validation_0-mae:2336.45600
[160]	validation_0-mae:2335.98343
[161]	validation_0-mae:2335.24130
[162]	validation_0-mae:2333.39102
[163]	validation_0-mae:2330.74677
[164]	validation_0-mae:2329.73380
[165]	validation_0-mae:2327.20996
[166]	validation_0-mae:2326.04258
[167]	validation_0-mae:2323.32435
[168]	validation_0-mae:2320.79823
[169]	validation_0-mae:2317.66602
[170]	validation_0-mae:2315.64033
[171]	validation_0-mae:2314.25913
[172]	validation_0-mae:2311.85529
[173]	validation_0-mae:2311.67522
[174]	validation_0-mae:2311.92188
[175]	validation_0-mae:2311.71920
[176]	validation_0-mae:2310.87037
[177]	validation_0-mae:2311.83599
[178]	validation_0-mae:2311.24521
[179]	validation_0-mae:2310.27598
[180]	validation_0-mae:2310.21495
[181]	validation_0-mae:2310.01960
[182]	validation_0-mae:2307.92521
[183]	validation_0-mae:2304.56326
[184]	validation_0-mae:2303.07402
[185]	validation_0-mae:2302.02492
[186]	validation_0-mae:2300.16524
[187]	validation_0-mae:2298.10042
[188]	validation_0-mae:2296.88287
[189]	validation_0-mae:2295.19357
[190]	validation_0-mae:2292.40363
[191]	validation_0-mae:2291.13267
[192]	validation_0-mae:2291.56318
[193]	validation_0-mae:2291.38987
[194]	validation_0-mae:2290.80037
[195]	validation_0-mae:2289.84020
[196]	validation_0-mae:2289.43118
[197]	validation_0-mae:2288.01399
[198]	validation_0-mae:2287.58097
[199]	validation_0-mae:2286.25295
[200]	validation_0-mae:2285.60296
[201]	validation_0-mae:2284.89313
[202]	validation_0-mae:2283.53441
[203]	validation_0-mae:2282.97281
[204]	validation_0-mae:2282.61214
[205]	validation_0-mae:2280.39399
[206]	validation_0-mae:2279.21430
[207]	validation_0-mae:2278.53375
[208]	validation_0-mae:2276.23490
[209]	validation_0-mae:2274.47091
[210]	validation_0-mae:2273.78635
[211]	validation_0-mae:2273.56015
[212]	validation_0-mae:2273.96026
[213]	validation_0-mae:2273.42319
[214]	validation_0-mae:2270.60438
[215]	validation_0-mae:2269.10207
[216]	validation_0-mae:2269.53006
[217]	validation_0-mae:2268.45509
[218]	validation_0-mae:2267.65638
[219]	validation_0-mae:2265.57326
[220]	validation_0-mae:2263.43642
[221]	validation_0-mae:2262.81734
[222]	validation_0-mae:2262.70234
[223]	validation_0-mae:2261.21290
[224]	validation_0-mae:2261.48296
[225]	validation_0-mae:2260.07524
[226]	validation_0-mae:2260.59902
[227]	validation_0-mae:2259.79167
[228]	validation_0-mae:2258.34053
[229]	validation_0-mae:2258.63621
[230]	validation_0-mae:2257.38861
[231]	validation_0-mae:2255.89654
[232]	validation_0-mae:2256.23316
[233]	validation_0-mae:2256.08946
[234]	validation_0-mae:2253.59854
[235]	validation_0-mae:2252.84483
[236]	validation_0-mae:2249.92043
[237]	validation_0-mae:2248.74623
[238]	validation_0-mae:2247.38664
[239]	validation_0-mae:2247.21272
[240]	validation_0-mae:2246.94646
[241]	validation_0-mae:2246.15745
[242]	validation_0-mae:2246.79194
[243]	validation_0-mae:2246.26404
[244]	validation_0-mae:2245.73805
[245]	validation_0-mae:2245.63298
[246]	validation_0-mae:2244.50896
[247]	validation_0-mae:2243.22145
[248]	validation_0-mae:2243.17753
[249]	validation_0-mae:2241.89337
[250]	validation_0-mae:2240.69764
[251]	validation_0-mae:2240.66142
[252]	validation_0-mae:2237.92100
[253]	validation_0-mae:2236.89457
[254]	validation_0-mae:2236.44213
[255]	validation_0-mae:2235.94809
[256]	validation_0-mae:2234.46838
[257]	validation_0-mae:2233.86453
[258]	validation_0-mae:2233.91433
[259]	validation_0-mae:2233.42964
[260]	validation_0-mae:2232.17415
[261]	validation_0-mae:2231.36868
[262]	validation_0-mae:2230.95395
[263]	validation_0-mae:2230.96888
[264]	validation_0-mae:2231.06997
[265]	validation_0-mae:2229.82624
[266]	validation_0-mae:2229.38810
[267]	validation_0-mae:2228.63140
[268]	validation_0-mae:2227.67550
[269]	validation_0-mae:2227.80861
[270]	validation_0-mae:2226.80236
[271]	validation_0-mae:2225.90080
[272]	validation_0-mae:2226.12957
[273]	validation_0-mae:2225.96036
[274]	validation_0-mae:2224.90392
[275]	validation_0-mae:2224.44246
[276]	validation_0-mae:2223.42582
[277]	validation_0-mae:2223.36089
[278]	validation_0-mae:2222.86860
[279]	validation_0-mae:2219.67166
[280]	validation_0-mae:2221.40912
[281]	validation_0-mae:2221.53082
[282]	validation_0-mae:2222.50281
[283]	validation_0-mae:2220.33038
[284]	validation_0-mae:2219.94102
[285]	validation_0-mae:2219.73742
[286]	validation_0-mae:2219.12954
[287]	validation_0-mae:2218.78907
[288]	validation_0-mae:2218.60772
[289]	validation_0-mae:2218.74422
[290]	validation_0-mae:2218.24465
[291]	validation_0-mae:2216.37634
[292]	validation_0-mae:2216.25450
[293]	validation_0-mae:2216.42928
[294]	validation_0-mae:2215.94901
[295]	validation_0-mae:2216.83591
[296]	validation_0-mae:2215.56331
[297]	validation_0-mae:2215.03214
[298]	validation_0-mae:2213.97532
[299]	validation_0-mae:2213.68256
[300]	validation_0-mae:2212.49241
[301]	validation_0-mae:2212.08380
[302]	validation_0-mae:2211.82623
[303]	validation_0-mae:2211.84184
[304]	validation_0-mae:2210.00592
[305]	validation_0-mae:2209.29216
[306]	validation_0-mae:2208.90308
[307]	validation_0-mae:2208.53708
[308]	validation_0-mae:2206.20175
[309]	validation_0-mae:2204.68296
[310]	validation_0-mae:2204.14854
[311]	validation_0-mae:2204.12761
[312]	validation_0-mae:2203.46111
[313]	validation_0-mae:2202.76862
[314]	validation_0-mae:2201.83597
[315]	validation_0-mae:2200.94115
[316]	validation_0-mae:2200.65027
[317]	validation_0-mae:2199.82899
[318]	validation_0-mae:2199.34248
[319]	validation_0-mae:2199.13634
[320]	validation_0-mae:2199.59448
[321]	validation_0-mae:2199.23044
[322]	validation_0-mae:2199.86926
[323]	validation_0-mae:2199.09830
[324]	validation_0-mae:2198.78985
[325]	validation_0-mae:2198.51530
[326]	validation_0-mae:2197.71212
[327]	validation_0-mae:2197.54613
[328]	validation_0-mae:2198.67110
[329]	validation_0-mae:2198.69361
[330]	validation_0-mae:2198.55811
[331]	validation_0-mae:2198.39606
[332]	validation_0-mae:2197.35477
[333]	validation_0-mae:2195.64403
[334]	validation_0-mae:2193.98204
[335]	validation_0-mae:2194.39888
[336]	validation_0-mae:2194.71805
[337]	validation_0-mae:2194.09620
[338]	validation_0-mae:2193.97678
[339]	validation_0-mae:2193.01308
[340]	validation_0-mae:2192.63941
[341]	validation_0-mae:2192.23056
[342]	validation_0-mae:2189.46459
[343]	validation_0-mae:2188.90086
[344]	validation_0-mae:2189.88055
[345]	validation_0-mae:2188.52585
[346]	validation_0-mae:2189.15920
[347]	validation_0-mae:2189.33576
[348]	validation_0-mae:2188.46964
[349]	validation_0-mae:2189.25429
[350]	validation_0-mae:2188.17126
[351]	validation_0-mae:2185.65725
[352]	validation_0-mae:2185.26175
[353]	validation_0-mae:2185.70348
[354]	validation_0-mae:2183.81503
[355]	validation_0-mae:2184.07368
[356]	validation_0-mae:2184.44838
[357]	validation_0-mae:2183.13409
[358]	validation_0-mae:2183.54772
[359]	validation_0-mae:2184.47876
[360]	validation_0-mae:2184.51547
[361]	validation_0-mae:2183.85160
[362]	validation_0-mae:2182.77254
[363]	validation_0-mae:2183.40623
[364]	validation_0-mae:2182.96684
[365]	validation_0-mae:2183.18501
[366]	validation_0-mae:2183.10901
[367]	validation_0-mae:2183.39797
[368]	validation_0-mae:2182.90550
[369]	validation_0-mae:2182.29685
[370]	validation_0-mae:2182.47321
[371]	validation_0-mae:2182.39250
[372]	validation_0-mae:2181.33966
[373]	validation_0-mae:2180.24356
[374]	validation_0-mae:2178.87361
[375]	validation_0-mae:2178.12895
[376]	validation_0-mae:2177.85965
[377]	validation_0-mae:2177.82949
[378]	validation_0-mae:2177.64501
[379]	validation_0-mae:2177.57367
[380]	validation_0-mae:2177.80918
[381]	validation_0-mae:2178.26112
[382]	validation_0-mae:2178.50060
[383]	validation_0-mae:2177.83670
[384]	validation_0-mae:2177.60987
[385]	validation_0-mae:2177.12970
[386]	validation_0-mae:2177.16311
[387]	validation_0-mae:2176.15426
[388]	validation_0-mae:2176.32981
[389]	validation_0-mae:2176.38043
[390]	validation_0-mae:2175.81096
[391]	validation_0-mae:2175.74239
[392]	validation_0-mae:2176.60273
[393]	validation_0-mae:2175.75835
[394]	validation_0-mae:2175.01152
[395]	validation_0-mae:2172.81349
[396]	validation_0-mae:2171.68584
[397]	validation_0-mae:2171.74871
[398]	validation_0-mae:2171.30621
[399]	validation_0-mae:2169.70881
[400]	validation_0-mae:2168.97524
[401]	validation_0-mae:2168.10517
[402]	validation_0-mae:2166.63263
[403]	validation_0-mae:2167.29552
[404]	validation_0-mae:2167.29525
[405]	validation_0-mae:2167.29038
[406]	validation_0-mae:2166.83070
[407]	validation_0-mae:2167.18884
[408]	validation_0-mae:2166.06138
[409]	validation_0-mae:2165.03164
[410]	validation_0-mae:2164.43756
[411]	validation_0-mae:2164.03281
[412]	validation_0-mae:2164.53885
[413]	validation_0-mae:2164.09005
[414]	validation_0-mae:2164.04900
[415]	validation_0-mae:2163.32535
[416]	validation_0-mae:2162.95729
[417]	validation_0-mae:2162.86739
[418]	validation_0-mae:2163.32641
[419]	validation_0-mae:2163.37562
[420]	validation_0-mae:2162.90688
[421]	validation_0-mae:2162.54851
[422]	validation_0-mae:2162.33604
[423]	validation_0-mae:2162.47832
[424]	validation_0-mae:2162.65248
[425]	validation_0-mae:2162.16309
[426]	validation_0-mae:2161.97412
[427]	validation_0-mae:2161.74411
[428]	validation_0-mae:2161.30477
[429]	validation_0-mae:2161.30935
[430]	validation_0-mae:2160.99892
[431]	validation_0-mae:2161.48895
[432]	validation_0-mae:2161.07944
[433]	validation_0-mae:2160.54087
[434]	validation_0-mae:2160.47284
[435]	validation_0-mae:2160.65291
[436]	validation_0-mae:2161.49734
[437]	validation_0-mae:2161.57396
[438]	validation_0-mae:2161.34038
[439]	validation_0-mae:2161.86156
[440]	validation_0-mae:2162.24391
[441]	validation_0-mae:2161.95986
[442]	validation_0-mae:2161.22855
[443]	validation_0-mae:2161.44372
[444]	validation_0-mae:2161.25672
[445]	validation_0-mae:2161.23977
[446]	validation_0-mae:2160.65917
[447]	validation_0-mae:2160.08725
[448]	validation_0-mae:2160.02749
[449]	validation_0-mae:2160.31637
[450]	validation_0-mae:2159.70402
[451]	validation_0-mae:2159.62020
[452]	validation_0-mae:2159.79207
[453]	validation_0-mae:2158.95365
[454]	validation_0-mae:2159.28408
[455]	validation_0-mae:2159.49211
[456]	validation_0-mae:2159.09877
[457]	validation_0-mae:2159.22385
[458]	validation_0-mae:2158.80807
[459]	validation_0-mae:2158.90894
[460]	validation_0-mae:2159.37938
[461]	validation_0-mae:2159.57300
[462]	validation_0-mae:2160.00232
[463]	validation_0-mae:2159.74972
[464]	validation_0-mae:2159.07815
[465]	validation_0-mae:2159.72617
[466]	validation_0-mae:2160.24115
[467]	validation_0-mae:2160.36720
[468]	validation_0-mae:2160.57142
[469]	validation_0-mae:2160.74262
[470]	validation_0-mae:2160.33981
[471]	validation_0-mae:2160.99291
[472]	validation_0-mae:2160.41336
[473]	validation_0-mae:2160.13346
[474]	validation_0-mae:2159.83278
[475]	validation_0-mae:2160.14107
[476]	validation_0-mae:2160.75285
[477]	validation_0-mae:2160.90503
[478]	validation_0-mae:2161.00015
[479]	validation_0-mae:2159.74153
[480]	validation_0-mae:2159.28243
[481]	validation_0-mae:2159.30947
[482]	validation_0-mae:2159.70573
[483]	validation_0-mae:2159.46346
[484]	validation_0-mae:2159.90189
[485]	validation_0-mae:2159.76441
[486]	validation_0-mae:2159.75012
[487]	validation_0-mae:2159.66073
[488]	validation_0-mae:2159.79129
[489]	validation_0-mae:2159.09445
[490]	validation_0-mae:2158.35126
[491]	validation_0-mae:2158.38999
[492]	validation_0-mae:2157.91641
[493]	validation_0-mae:2158.13452
[494]	validation_0-mae:2159.16786
[495]	validation_0-mae:2159.15616
[496]	validation_0-mae:2159.01105
[497]	validation_0-mae:2159.21507
[498]	validation_0-mae:2159.34211
[499]	validation_0-mae:2159.76015
[500]	validation_0-mae:2158.32351
[501]	validation_0-mae:2157.85351
[502]	validation_0-mae:2158.91866
[503]	validation_0-mae:2158.95394
[504]	validation_0-mae:2158.00320
[505]	validation_0-mae:2156.38536
[506]	validation_0-mae:2153.78431
[507]	validation_0-mae:2153.34191
[508]	validation_0-mae:2152.14250
[509]	validation_0-mae:2151.93176
[510]	validation_0-mae:2151.21662
[511]	validation_0-mae:2150.54165
[512]	validation_0-mae:2150.35347
[513]	validation_0-mae:2150.06378
[514]	validation_0-mae:2149.56262
[515]	validation_0-mae:2148.76856
[516]	validation_0-mae:2148.87947
[517]	validation_0-mae:2148.72642
[518]	validation_0-mae:2148.98769
[519]	validation_0-mae:2149.20511
[520]	validation_0-mae:2149.49602
[521]	validation_0-mae:2149.55545
[522]	validation_0-mae:2149.28403
[523]	validation_0-mae:2148.17837
[524]	validation_0-mae:2148.12106
[525]	validation_0-mae:2148.38111
[526]	validation_0-mae:2146.79390
[527]	validation_0-mae:2146.64341
[528]	validation_0-mae:2146.92882
[529]	validation_0-mae:2146.40582
[530]	validation_0-mae:2146.73956
[531]	validation_0-mae:2145.43674
[532]	validation_0-mae:2144.82883
[533]	validation_0-mae:2144.17904
[534]	validation_0-mae:2144.25408
[535]	validation_0-mae:2144.53529
[536]	validation_0-mae:2144.35449
[537]	validation_0-mae:2144.15555
[538]	validation_0-mae:2144.62361
[539]	validation_0-mae:2144.02835
[540]	validation_0-mae:2144.20556
[541]	validation_0-mae:2143.63914
[542]	validation_0-mae:2143.05886
[543]	validation_0-mae:2142.55454
[544]	validation_0-mae:2142.33682
[545]	validation_0-mae:2142.13546
[546]	validation_0-mae:2141.76474
[547]	validation_0-mae:2141.48519
[548]	validation_0-mae:2141.59519
[549]	validation_0-mae:2141.86235
[550]	validation_0-mae:2141.69473
[551]	validation_0-mae:2142.12481
[552]	validation_0-mae:2141.59788
[553]	validation_0-mae:2141.67953
[554]	validation_0-mae:2141.87085
[555]	validation_0-mae:2141.30225
[556]	validation_0-mae:2141.10342
[557]	validation_0-mae:2140.92777
[558]	validation_0-mae:2141.18331
[559]	validation_0-mae:2140.28012
[560]	validation_0-mae:2139.90714
[561]	validation_0-mae:2139.78152
[562]	validation_0-mae:2140.01585
[563]	validation_0-mae:2140.39894
[564]	validation_0-mae:2141.09225
[565]	validation_0-mae:2140.43563
[566]	validation_0-mae:2140.49746
[567]	validation_0-mae:2141.21591
[568]	validation_0-mae:2141.37988
[569]	validation_0-mae:2141.82759
[570]	validation_0-mae:2142.11336
[571]	validation_0-mae:2141.77074
[572]	validation_0-mae:2141.46106
[573]	validation_0-mae:2141.83468
[574]	validation_0-mae:2141.37807
[575]	validation_0-mae:2140.80969
[576]	validation_0-mae:2141.10005
[577]	validation_0-mae:2140.74069
[578]	validation_0-mae:2140.88952
[579]	validation_0-mae:2141.02261
[580]	validation_0-mae:2141.25558
[581]	validation_0-mae:2141.52391
[582]	validation_0-mae:2141.23205
[583]	validation_0-mae:2141.40843
[584]	validation_0-mae:2141.69293
[585]	validation_0-mae:2141.56194
[586]	validation_0-mae:2141.31619
[587]	validation_0-mae:2140.73329
[588]	validation_0-mae:2140.06398
[589]	validation_0-mae:2138.05509
[590]	validation_0-mae:2138.01531
[591]	validation_0-mae:2137.65866
[592]	validation_0-mae:2137.62386
[593]	validation_0-mae:2137.22386
[594]	validation_0-mae:2137.20391
[595]	validation_0-mae:2137.39143
[596]	validation_0-mae:2137.30181
[597]	validation_0-mae:2137.04378
[598]	validation_0-mae:2136.35532
[599]	validation_0-mae:2136.53679
[600]	validation_0-mae:2136.37116
[601]	validation_0-mae:2136.32143
[602]	validation_0-mae:2136.78773
[603]	validation_0-mae:2136.80772
[604]	validation_0-mae:2137.45246
[605]	validation_0-mae:2136.72859
[606]	validation_0-mae:2136.65587
[607]	validation_0-mae:2136.69034
[608]	validation_0-mae:2136.85983
[609]	validation_0-mae:2137.08530
[610]	validation_0-mae:2136.93171
[611]	validation_0-mae:2137.01469
[612]	validation_0-mae:2137.23760
[613]	validation_0-mae:2136.97656
[614]	validation_0-mae:2136.99402
[615]	validation_0-mae:2137.04588
[616]	validation_0-mae:2137.24735
[617]	validation_0-mae:2137.30917
[618]	validation_0-mae:2137.51797
[619]	validation_0-mae:2137.27901
[620]	validation_0-mae:2137.12896
[621]	validation_0-mae:2137.36819
[622]	validation_0-mae:2137.26504
[623]	validation_0-mae:2137.38295
[624]	validation_0-mae:2137.33406
[625]	validation_0-mae:2136.83152
[626]	validation_0-mae:2136.54436
[627]	validation_0-mae:2136.78836
[628]	validation_0-mae:2136.56613
[629]	validation_0-mae:2136.57612
[630]	validation_0-mae:2137.04269
[631]	validation_0-mae:2137.03067
[632]	validation_0-mae:2137.33123

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[2]	validation_0-mae:11309.78276
[3]	validation_0-mae:10759.02634
[4]	validation_0-mae:10279.65729
[5]	validation_0-mae:9856.22164
[6]	validation_0-mae:9472.59214
[7]	validation_0-mae:9125.98909
[8]	validation_0-mae:8816.48726
[9]	validation_0-mae:8527.47689
[0]	validation_0-mae:12570.26966
[1]	validation_0-mae:11933.38500
[2]	validation_0-mae:11346.18219
[3]	validation_0-mae:10791.86398
[4]	validation_0-mae:10302.43065
[5]	validation_0-mae:9858.40027
[6]	validation_0-mae:9430.39364
[7]	validation_0-mae:9021.68944
[8]	validation_0-mae:8680.67336
[9]	validation_0-mae:8353.76555
[10]	validation_0-mae:8034.05184
[11]	validation_0-mae:7750.60587
[12]	validation_0-mae:7477.39490
[13]	validation_0-mae:7218.10087
[14]	validation_0-mae:6978.03484
[15]	validation_0-mae:6759.55575
[16]	validation_0-mae:6542.50062
[17]	validation_0-mae:6339.41056
[18]	validation_0-mae:6142.97386
[19]	validation_0-mae:5955.81461
[20]	validation_0-mae:5790.68696
[21]	validation_0-mae:5635.31822
[22]	validation_0-mae:5477.29850
[23]	validation_0-mae:5324.30722
[24]	validation_0-mae:5187.41116
[25]	validation_0-mae:5042.34012
[26]	validation_0-mae:4912.56396
[27]	validation_0-mae:4786.15970
[28]	validation_0-mae:4677.44852
[29]	validation_0-mae:4564.82455
[30]	validation_0-mae:4459.86450
[31]	validation_0-mae:4368.17341
[32]	validation_0-mae:4286.76084

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[33]	validation_0-mae:4202.78365
[34]	validation_0-mae:4120.36797
[35]	validation_0-mae:4047.25867
[36]	validation_0-mae:3965.56328
[37]	validation_0-mae:3894.84592
[38]	validation_0-mae:3826.96267
[39]	validation_0-mae:3759.87326
[40]	validation_0-mae:3709.08071
[41]	validation_0-mae:3644.90843
[42]	validation_0-mae:3601.38407
[43]	validation_0-mae:3543.00802
[44]	validation_0-mae:3500.83185
[45]	validation_0-mae:3457.77127
[46]	validation_0-mae:3412.47905
[47]	validation_0-mae:3375.95482
[48]	validation_0-mae:3329.87802
[49]	validation_0-mae:3295.83673
[50]	validation_0-mae:3261.34681
[51]	validation_0-mae:3226.75014
[52]	validation_0-mae:3201.25063
[53]	validation_0-mae:3174.25398
[54]	validation_0-mae:3150.50873
[55]	validation_0-mae:3121.31550
[56]	validation_0-mae:3099.46419
[57]	validation_0-mae:3068.52462
[58]	validation_0-mae:3039.83844
[59]	validation_0-mae:3014.35737
[60]	validation_0-mae:2997.81381
[61]	validation_0-mae:2979.90684
[62]	validation_0-mae:2946.56052
[63]	validation_0-mae:2918.17671
[64]	validation_0-mae:2889.85327
[65]	validation_0-mae:2874.92745
[66]	validation_0-mae:2860.98609
[67]	validation_0-mae:2841.02910
[68]	validation_0-mae:2822.51750
[69]	validation_0-mae:2808.04794
[70]	validation_0-mae:2788.24213
[71]	validation_0-mae:2772.39764
[72]	validation_0-mae:2756.18040
[73]	validation_0-mae:2741.53717
[74]	validation_0-mae:2723.62546
[75]	validation_0-mae:2710.62171
[76]	validation_0-mae:2696.32285
[77]	validation_0-mae:2683.30740
[78]	validation_0-mae:2674.37373
[79]	validation_0-mae:2665.91297
[80]	validation_0-mae:2658.14339
[81]	validation_0-mae:2643.67656
[82]	validation_0-mae:2634.05724
[83]	validation_0-mae:2624.55013
[84]	validation_0-mae:2615.96310
[85]	validation_0-mae:2599.26384
[86]	validation_0-mae:2585.68163
[87]	validation_0-mae:2578.72454
[88]	validation_0-mae:2572.65197
[89]	validation_0-mae:2561.24224
[90]	validation_0-mae:2554.06369
[91]	validation_0-mae:2546.82781
[92]	validation_0-mae:2537.96745
[93]	validation_0-mae:2530.54500
[94]	validation_0-mae:2524.72060
[95]	validation_0-mae:2514.50858
[96]	validation_0-mae:2508.65203
[97]	validation_0-mae:2497.47005
[98]	validation_0-mae:2488.22128
[99]	validation_0-mae:2478.84183
[100]	validation_0-mae:2468.48741
[101]	validation_0-mae:2463.43885
[102]	validation_0-mae:2458.20344
[103]	validation_0-mae:2450.51512
[104]	validation_0-mae:2448.88177
[105]	validation_0-mae:2444.57810
[106]	validation_0-mae:2440.35697
[107]	validation_0-mae:2436.36406
[108]	validation_0-mae:2431.74287
[109]	validation_0-mae:2428.07032
[110]	validation_0-mae:2422.63079
[111]	validation_0-mae:2416.95038
[112]	validation_0-mae:2413.41227
[113]	validation_0-mae:2409.53275
[114]	validation_0-mae:2405.70502
[115]	validation_0-mae:2400.47825
[116]	validation_0-mae:2397.09574
[117]	validation_0-mae:2393.68097
[118]	validation_0-mae:2390.12744
[119]	validation_0-mae:2378.24032
[120]	validation_0-mae:2373.65709
[121]	validation_0-mae:2371.33144
[122]	validation_0-mae:2367.48869
[123]	validation_0-mae:2363.69995
[124]	validation_0-mae:2361.04354
[125]	validation_0-mae:2358.05414
[126]	validation_0-mae:2354.88402
[127]	validation_0-mae:2354.94130
[128]	validation_0-mae:2352.56115
[129]	validation_0-mae:2345.01318
[130]	validation_0-mae:2341.73117
[131]	validation_0-mae:2338.84394
[132]	validation_0-mae:2336.61174
[133]	validation_0-mae:2333.77510
[134]	validation_0-mae:2329.61335
[135]	validation_0-mae:2329.19383
[136]	validation_0-mae:2326.12125
[137]	validation_0-mae:2320.69252
[138]	validation_0-mae:2318.60674
[139]	validation_0-mae:2316.71652
[140]	validation_0-mae:2315.49901
[141]	validation_0-mae:2313.92758
[142]	validation_0-mae:2310.46935
[143]	validation_0-mae:2308.54426
[144]	validation_0-mae:2305.51827
[145]	validation_0-mae:2303.13488
[146]	validation_0-mae:2297.85355
[147]	validation_0-mae:2294.84730
[148]	validation_0-mae:2293.78411
[149]	validation_0-mae:2288.58277
[150]	validation_0-mae:2286.21104
[151]	validation_0-mae:2283.82971
[152]	validation_0-mae:2281.70711
[153]	validation_0-mae:2279.41718
[154]	validation_0-mae:2278.77160
[155]	validation_0-mae:2277.54676
[156]	validation_0-mae:2276.16004
[157]	validation_0-mae:2274.05854
[158]	validation_0-mae:2271.27086
[159]	validation_0-mae:2270.50703
[160]	validation_0-mae:2267.09967
[161]	validation_0-mae:2265.19779
[162]	validation_0-mae:2262.97965
[163]	validation_0-mae:2257.97856
[164]	validation_0-mae:2258.36806
[165]	validation_0-mae:2254.93362
[166]	validation_0-mae:2253.13342
[167]	validation_0-mae:2250.60052
[168]	validation_0-mae:2245.46539
[169]	validation_0-mae:2243.82231
[170]	validation_0-mae:2243.00623
[171]	validation_0-mae:2241.90355
[172]	validation_0-mae:2241.54881
[173]	validation_0-mae:2240.53173
[174]	validation_0-mae:2236.37223
[175]	validation_0-mae:2234.84246
[176]	validation_0-mae:2233.13362
[177]	validation_0-mae:2230.14994
[178]	validation_0-mae:2230.22131
[179]	validation_0-mae:2227.66457
[180]	validation_0-mae:2226.96331
[181]	validation_0-mae:2226.86201
[182]	validation_0-mae:2226.81279
[183]	validation_0-mae:2225.01993
[184]	validation_0-mae:2223.52796
[185]	validation_0-mae:2223.39141
[186]	validation_0-mae:2223.67958
[187]	validation_0-mae:2223.23429
[188]	validation_0-mae:2222.20123
[189]	validation_0-mae:2220.12434
[190]	validation_0-mae:2219.45300
[191]	validation_0-mae:2218.45517
[192]	validation_0-mae:2216.38795
[193]	validation_0-mae:2214.47326
[194]	validation_0-mae:2213.02067
[195]	validation_0-mae:2212.44533
[196]	validation_0-mae:2210.53950
[197]	validation_0-mae:2209.49047
[198]	validation_0-mae:2209.94682
[199]	validation_0-mae:2208.91373
[200]	validation_0-mae:2207.70404
[201]	validation_0-mae:2206.34110
[202]	validation_0-mae:2205.61685
[203]	validation_0-mae:2205.63465
[204]	validation_0-mae:2205.29740
[205]	validation_0-mae:2204.92998
[206]	validation_0-mae:2203.84754
[207]	validation_0-mae:2202.98293
[208]	validation_0-mae:2201.94403
[209]	validation_0-mae:2199.52250
[210]	validation_0-mae:2199.66156
[211]	validation_0-mae:2199.50130
[212]	validation_0-mae:2198.73921
[213]	validation_0-mae:2198.63471
[214]	validation_0-mae:2196.76046
[215]	validation_0-mae:2196.85790
[216]	validation_0-mae:2196.96997
[217]	validation_0-mae:2194.83146
[218]	validation_0-mae:2195.48705
[219]	validation_0-mae:2194.44706
[220]	validation_0-mae:2195.11702
[221]	validation_0-mae:2195.36002
[222]	validation_0-mae:2194.93495
[223]	validation_0-mae:2193.63445
[224]	validation_0-mae:2194.13031
[225]	validation_0-mae:2193.38343
[226]	validation_0-mae:2192.57269
[227]	validation_0-mae:2191.96101
[228]	validation_0-mae:2190.73347
[229]	validation_0-mae:2190.86179
[230]	validation_0-mae:2189.07962
[231]	validation_0-mae:2188.07352
[232]	validation_0-mae:2186.46284
[233]	validation_0-mae:2185.18222
[234]	validation_0-mae:2185.15528
[235]	validation_0-mae:2185.57581
[236]	validation_0-mae:2185.75698
[237]	validation_0-mae:2186.05124
[238]	validation_0-mae:2186.71068
[239]	validation_0-mae:2186.98976
[240]	validation_0-mae:2186.04934
[241]	validation_0-mae:2186.05916
[242]	validation_0-mae:2186.77302
[243]	validation_0-mae:2186.73904
[244]	validation_0-mae:2185.36727
[245]	validation_0-mae:2185.60361
[246]	validation_0-mae:2185.26179
[247]	validation_0-mae:2184.40344
[248]	validation_0-mae:2184.82645
[249]	validation_0-mae:2185.49709
[250]	validation_0-mae:2184.60353
[251]	validation_0-mae:2185.13232
[252]	validation_0-mae:2185.83471
[253]	validation_0-mae:2185.89005
[254]	validation_0-mae:2186.23046
[255]	validation_0-mae:2186.32636
[256]	validation_0-mae:2185.67243
[257]	validation_0-mae:2184.07043
[258]	validation_0-mae:2184.20502
[259]	validation_0-mae:2182.22805
[260]	validation_0-mae:2182.17133
[261]	validation_0-mae:2182.14771
[262]	validation_0-mae:2182.35226
[263]	validation_0-mae:2180.79372
[264]	validation_0-mae:2180.39018
[265]	validation_0-mae:2180.51244
[266]	validation_0-mae:2179.81753
[267]	validation_0-mae:2180.15984
[268]	validation_0-mae:2179.92558
[269]	validation_0-mae:2179.89599
[270]	validation_0-mae:2178.70569
[271]	validation_0-mae:2178.96918
[272]	validation_0-mae:2178.65835
[273]	validation_0-mae:2178.05236
[274]	validation_0-mae:2177.51780
[275]	validation_0-mae:2177.48934
[276]	validation_0-mae:2176.75445
[277]	validation_0-mae:2176.78502
[278]	validation_0-mae:2177.69359
[279]	validation_0-mae:2177.23712
[280]	validation_0-mae:2176.56766
[281]	validation_0-mae:2176.75646
[282]	validation_0-mae:2176.94302
[283]	validation_0-mae:2175.62543
[284]	validation_0-mae:2176.20354
[285]	validation_0-mae:2176.99861
[286]	validation_0-mae:2176.05002
[287]	validation_0-mae:2176.20848
[288]	validation_0-mae:2176.59097
[289]	validation_0-mae:2176.74466
[290]	validation_0-mae:2175.02518
[291]	validation_0-mae:2173.23418
[292]	validation_0-mae:2173.16730
[293]	validation_0-mae:2173.59958
[294]	validation_0-mae:2172.91332
[295]	validation_0-mae:2172.87217
[296]	validation_0-mae:2171.52727
[297]	validation_0-mae:2170.84226
[298]	validation_0-mae:2170.95952
[299]	validation_0-mae:2169.29757
[300]	validation_0-mae:2168.02451
[301]	validation_0-mae:2166.84547
[302]	validation_0-mae:2166.69965
[303]	validation_0-mae:2166.01693
[304]	validation_0-mae:2165.26105
[305]	validation_0-mae:2165.21625
[306]	validation_0-mae:2164.34985
[307]	validation_0-mae:2162.93269
[308]	validation_0-mae:2163.07943
[309]	validation_0-mae:2163.10611
[310]	validation_0-mae:2162.09241
[311]	validation_0-mae:2162.44237
[312]	validation_0-mae:2160.98895
[313]	validation_0-mae:2161.49865
[314]	validation_0-mae:2161.52862
[315]	validation_0-mae:2161.82097
[316]	validation_0-mae:2161.59291
[317]	validation_0-mae:2159.13364
[318]	validation_0-mae:2158.87081
[319]	validation_0-mae:2158.97581
[320]	validation_0-mae:2158.49083
[321]	validation_0-mae:2158.86965
[322]	validation_0-mae:2158.71322
[323]	validation_0-mae:2158.58528
[324]	validation_0-mae:2159.08619
[325]	validation_0-mae:2159.52370
[326]	validation_0-mae:2159.54167
[327]	validation_0-mae:2158.65691
[328]	validation_0-mae:2157.85579
[329]	validation_0-mae:2156.25292
[330]	validation_0-mae:2155.10846
[331]	validation_0-mae:2154.81310
[332]	validation_0-mae:2154.26682
[333]	validation_0-mae:2154.05695
[334]	validation_0-mae:2153.77662
[335]	validation_0-mae:2154.43056
[336]	validation_0-mae:2154.06889
[337]	validation_0-mae:2153.96348
[338]	validation_0-mae:2153.25674
[339]	validation_0-mae:2152.96432
[340]	validation_0-mae:2152.97932
[341]	validation_0-mae:2153.25121
[342]	validation_0-mae:2153.13797
[343]	validation_0-mae:2153.15643
[344]	validation_0-mae:2153.44921
[345]	validation_0-mae:2153.56803
[346]	validation_0-mae:2153.12262
[347]	validation_0-mae:2153.07747
[348]	validation_0-mae:2152.97061
[349]	validation_0-mae:2152.91171
[350]	validation_0-mae:2153.37490
[351]	validation_0-mae:2153.83977
[352]	validation_0-mae:2154.65547
[353]	validation_0-mae:2154.96270
[354]	validation_0-mae:2154.31609
[355]	validation_0-mae:2153.62199
[356]	validation_0-mae:2153.56169
[357]	validation_0-mae:2152.78632
[358]	validation_0-mae:2152.83698
[359]	validation_0-mae:2152.82284
[360]	validation_0-mae:2151.10719
[361]	validation_0-mae:2151.53065
[362]	validation_0-mae:2150.80269
[363]	validation_0-mae:2151.55000
[364]	validation_0-mae:2150.83654
[365]	validation_0-mae:2151.66865
[366]	validation_0-mae:2151.86843
[367]	validation_0-mae:2151.80277
[368]	validation_0-mae:2152.04728
[369]	validation_0-mae:2150.55878
[370]	validation_0-mae:2149.62245
[371]	validation_0-mae:2149.96534
[372]	validation_0-mae:2149.40900
[373]	validation_0-mae:2150.20512
[374]	validation_0-mae:2149.87146
[375]	validation_0-mae:2150.86784
[376]	validation_0-mae:2149.98573
[377]	validation_0-mae:2149.58879
[378]	validation_0-mae:2148.94074
[379]	validation_0-mae:2149.25067
[380]	validation_0-mae:2149.33906
[381]	validation_0-mae:2148.80245
[382]	validation_0-mae:2148.09645
[383]	validation_0-mae:2148.43792
[384]	validation_0-mae:2147.73596
[385]	validation_0-mae:2147.76275
[386]	validation_0-mae:2147.95020
[387]	validation_0-mae:2147.99079
[388]	validation_0-mae:2148.11696
[389]	validation_0-mae:2148.18983
[390]	validation_0-mae:2148.22585
[391]	validation_0-mae:2148.56539
[392]	validation_0-mae:2148.85985
[393]	validation_0-mae:2148.62652
[394]	validation_0-mae:2148.19293
[395]	validation_0-mae:2147.38729
[396]	validation_0-mae:2147.88403
[397]	validation_0-mae:2148.11493
[398]	validation_0-mae:2148.08081
[399]	validation_0-mae:2148.08967
[400]	validation_0-mae:2147.92279
[401]	validation_0-mae:2148.14095
[402]	validation_0-mae:2148.31323
[403]	validation_0-mae:2146.65315
[404]	validation_0-mae:2145.75459
[405]	validation_0-mae:2145.33264
[406]	validation_0-mae:2145.47607
[407]	validation_0-mae:2145.23041
[408]	validation_0-mae:2144.73987
[409]	validation_0-mae:2144.90238
[410]	validation_0-mae:2144.42305
[411]	validation_0-mae:2143.88656
[412]	validation_0-mae:2143.98864
[413]	validation_0-mae:2143.15498
[414]	validation_0-mae:2143.02098
[415]	validation_0-mae:2143.08407
[416]	validation_0-mae:2142.50825
[417]	validation_0-mae:2142.29923
[418]	validation_0-mae:2142.70210
[419]	validation_0-mae:2142.42162
[420]	validation_0-mae:2141.89231
[421]	validation_0-mae:2141.98393
[422]	validation_0-mae:2141.83309
[423]	validation_0-mae:2141.66352
[424]	validation_0-mae:2141.63113
[425]	validation_0-mae:2141.62767
[426]	validation_0-mae:2141.25218
[427]	validation_0-mae:2141.30025
[428]	validation_0-mae:2141.47564
[429]	validation_0-mae:2141.49818
[430]	validation_0-mae:2140.13461
[431]	validation_0-mae:2140.22566
[432]	validation_0-mae:2140.57410
[433]	validation_0-mae:2140.66982
[434]	validation_0-mae:2140.87296
[435]	validation_0-mae:2141.02653
[436]	validation_0-mae:2141.41389
[437]	validation_0-mae:2140.50127
[438]	validation_0-mae:2140.17104
[439]	validation_0-mae:2140.31919
[440]	validation_0-mae:2140.57849
[441]	validation_0-mae:2140.50681
[442]	validation_0-mae:2139.68854
[443]	validation_0-mae:2139.90930
[444]	validation_0-mae:2139.70857
[445]	validation_0-mae:2139.84257
[446]	validation_0-mae:2140.01764
[447]	validation_0-mae:2140.02646
[448]	validation_0-mae:2139.33126
[449]	validation_0-mae:2139.54903
[450]	validation_0-mae:2139.53162
[451]	validation_0-mae:2139.67203
[452]	validation_0-mae:2139.92382
[453]	validation_0-mae:2140.54049
[454]	validation_0-mae:2140.32026
[455]	validation_0-mae:2140.31142
[456]	validation_0-mae:2140.12969
[457]	validation_0-mae:2138.45980
[458]	validation_0-mae:2138.00559
[459]	validation_0-mae:2138.26053
[460]	validation_0-mae:2137.10096
[461]	validation_0-mae:2137.01364
[462]	validation_0-mae:2137.19414
[463]	validation_0-mae:2137.08056
[464]	validation_0-mae:2135.89485
[465]	validation_0-mae:2135.80660
[466]	validation_0-mae:2135.70316
[467]	validation_0-mae:2135.20522
[468]	validation_0-mae:2135.53161
[469]	validation_0-mae:2135.57056
[470]	validation_0-mae:2135.54825
[471]	validation_0-mae:2135.79062
[472]	validation_0-mae:2135.79194
[473]	validation_0-mae:2135.04433
[474]	validation_0-mae:2134.37714
[475]	validation_0-mae:2134.33008
[476]	validation_0-mae:2132.08409
[477]	validation_0-mae:2132.65223
[478]	validation_0-mae:2132.97454
[479]	validation_0-mae:2132.27435
[480]	validation_0-mae:2131.75033
[481]	validation_0-mae:2132.03924
[482]	validation_0-mae:2131.63845
[483]	validation_0-mae:2131.76427
[484]	validation_0-mae:2131.55209
[485]	validation_0-mae:2131.24210
[486]	validation_0-mae:2131.74978
[487]	validation_0-mae:2131.51631
[488]	validation_0-mae:2131.54722
[489]	validation_0-mae:2131.73933
[490]	validation_0-mae:2131.98701
[491]	validation_0-mae:2131.85880
[492]	validation_0-mae:2132.10249
[493]	validation_0-mae:2132.09584
[494]	validation_0-mae:2132.04851
[495]	validation_0-mae:2132.08640
[496]	validation_0-mae:2131.96625
[497]	validation_0-mae:2132.14933
[498]	validation_0-mae:2131.62010
[499]	validation_0-mae:2131.72519
[500]	validation_0-mae:2130.44580
[501]	validation_0-mae:2130.27446
[502]	validation_0-mae:2130.16164
[503]	validation_0-mae:2130.15613
[504]	validation_0-mae:2130.07667
[505]	validation_0-mae:2129.94697
[506]	validation_0-mae:2129.91979
[507]	validation_0-mae:2129.95944
[508]	validation_0-mae:2130.03137
[509]	validation_0-mae:2129.41861
[510]	validation_0-mae:2129.03889
[511]	validation_0-mae:2129.11725
[512]	validation_0-mae:2129.04850
[513]	validation_0-mae:2129.26759
[514]	validation_0-mae:2129.45829
[515]	validation_0-mae:2129.36043
[516]	validation_0-mae:2129.51201
[517]	validation_0-mae:2129.13016
[518]	validation_0-mae:2129.44644
[519]	validation_0-mae:2129.24039
[520]	validation_0-mae:2129.36163
[521]	validation_0-mae:2129.15470
[522]	validation_0-mae:2129.26506
[523]	validation_0-mae:2127.50916
[524]	validation_0-mae:2127.10090
[525]	validation_0-mae:2126.84104
[526]	validation_0-mae:2127.48014
[527]	validation_0-mae:2127.40139
[528]	validation_0-mae:2127.32136
[529]	validation_0-mae:2126.57751
[530]	validation_0-mae:2126.30032
[531]	validation_0-mae:2126.40374
[532]	validation_0-mae:2126.59942
[533]	validation_0-mae:2126.14008
[534]	validation_0-mae:2126.29425
[535]	validation_0-mae:2126.49440
[536]	validation_0-mae:2126.64414
[537]	validation_0-mae:2126.81317
[538]	validation_0-mae:2126.73506
[539]	validation_0-mae:2126.67570
[540]	validation_0-mae:2126.42585
[541]	validation_0-mae:2126.31289
[542]	validation_0-mae:2126.75841
[543]	validation_0-mae:2126.75081
[544]	validation_0-mae:2126.50774
[545]	validation_0-mae:2126.36779
[546]	validation_0-mae:2126.46736
[547]	validation_0-mae:2125.81624
[548]	validation_0-mae:2126.22444
[549]	validation_0-mae:2125.99520
[550]	validation_0-mae:2126.13069
[551]	validation_0-mae:2126.02592
[552]	validation_0-mae:2125.94246
[553]	validation_0-mae:2125.83735
[554]	validation_0-mae:2125.53923
[555]	validation_0-mae:2125.49671
[556]	validation_0-mae:2125.58066
[557]	validation_0-mae:2125.24317
[558]	validation_0-mae:2125.24570
[559]	validation_0-mae:2124.66108
[560]	validation_0-mae:2125.12587
[561]	validation_0-mae:2124.97461
[562]	validation_0-mae:2125.32891
[563]	validation_0-mae:2124.95992
[564]	validation_0-mae:2124.57514
[565]	validation_0-mae:2124.35568
[566]	validation_0-mae:2124.32646
[567]	validation_0-mae:2124.12367
[568]	validation_0-mae:2124.07362
[569]	validation_0-mae:2123.76884
[570]	validation_0-mae:2124.46393
[571]	validation_0-mae:2124.53924
[572]	validation_0-mae:2124.44484
[573]	validation_0-mae:2124.52551
[574]	validation_0-mae:2124.45554
[575]	validation_0-mae:2124.39385
[576]	validation_0-mae:2124.38529
[577]	validation_0-mae:2124.62295
[578]	validation_0-mae:2124.71556
[579]	validation_0-mae:2124.16973
[580]	validation_0-mae:2124.29957
[581]	validation_0-mae:2124.43616
[582]	validation_0-mae:2124.67536
[583]	validation_0-mae:2125.09461
[584]	validation_0-mae:2125.04980
[585]	validation_0-mae:2125.09443
[586]	validation_0-mae:2124.99065
[587]	validation_0-mae:2124.87047
[588]	validation_0-mae:2124.56640
[589]	validation_0-mae:2124.64156
[590]	validation_0-mae:2124.42994
[591]	validation_0-mae:2124.31476
[592]	validation_0-mae:2124.11559
[593]	validation_0-mae:2124.34505
[594]	validation_0-mae:2124.17751
[595]	validation_0-mae:2124.34484
[596]	validation_0-mae:2124.00330
[597]	validation_0-mae:2124.05329
[598]	validation_0-mae:2123.83695
[599]	validation_0-mae:2123.93139
[600]	validation_0-mae:2123.72766
[601]	validation_0-mae:2123.71678
[602]	validation_0-mae:2124.05279
[603]	validation_0-mae:2123.51459
[604]	validation_0-mae:2123.26447
[605]	validation_0-mae:2123.12719
[606]	validation_0-mae:2122.75163
[607]	validation_0-mae:2122.80019
[608]	validation_0-mae:2122.06051
[609]	validation_0-mae:2122.00463
[610]	validation_0-mae:2121.58144
[611]	validation_0-mae:2121.17255
[612]	validation_0-mae:2120.78734
[613]	validation_0-mae:2120.88655
[614]	validation_0-mae:2120.64825
[615]	validation_0-mae:2120.24460
[616]	validation_0-mae:2119.87495
[617]	validation_0-mae:2119.60285
[618]	validation_0-mae:2119.29368
[619]	validation_0-mae:2118.79277
[620]	validation_0-mae:2118.80559
[621]	validation_0-mae:2118.56826
[622]	validation_0-mae:2118.42717

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[9]	validation_0-mae:9233.08833
[10]	validation_0-mae:9068.74511
[0]	validation_0-mae:12665.21059
[1]	validation_0-mae:12108.74698
[2]	validation_0-mae:11602.77507
[3]	validation_0-mae:11142.12106
[4]	validation_0-mae:10708.06661
[5]	validation_0-mae:10338.37141
[6]	validation_0-mae:9995.98873
[7]	validation_0-mae:9674.24797
[8]	validation_0-mae:9389.09225
[9]	validation_0-mae:9126.71493
[10]	validation_0-mae:8889.63023
[0]	validation_0-mae:12712.24410
[1]	validation_0-mae:12188.65952
[2]	validation_0-mae:11709.28155
[3]	validation_0-mae:11253.98481
[4]	validation_0-mae:10845.45200

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[5]	validation_0-mae:10463.94181
[6]	validation_0-mae:10125.03102
[7]	validation_0-mae:9814.53769
[8]	validation_0-mae:9528.03129
[9]	validation_0-mae:9252.22900
[0]	validation_0-mae:12769.97497
[1]	validation_0-mae:12297.01869
[2]	validation_0-mae:11867.28473
[3]	validation_0-mae:11449.47199
[4]	validation_0-mae:11075.90336
[5]	validation_0-mae:10724.96143
[6]	validation_0-mae:10395.19629
[7]	validation_0-mae:10096.88048
[8]	validation_0-mae:9809.74099
[9]	validation_0-mae:9547.37220
[10]	validation_0-mae:9314.72046

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[0]	validation_0-mae:12551.29234
[1]	validation_0-mae:11896.10749
[2]	validation_0-mae:11291.68264
[3]	validation_0-mae:10716.42276
[4]	validation_0-mae:10215.24095
[5]	validation_0-mae:9755.32182
[6]	validation_0-mae:9329.06607
[7]	validation_0-mae:8927.05732
[8]	validation_0-mae:8582.09431
[9]	validation_0-mae:8244.72353
[10]	validation_0-mae:7941.17946
[11]	validation_0-mae:7646.94230
[12]	validation_0-mae:7370.34567
[13]	validation_0-mae:7118.96434
[14]	validation_0-mae:6886.81086
[15]	validation_0-mae:6661.03471
[16]	validation_0-mae:6440.50208
[17]	validation_0-mae:6245.70343
[18]	validation_0-mae:6040.53621
[19]	validation_0-mae:5853.48638
[20]	validation_0-mae:5679.38987
[21]	validation_0-mae:5520.33682
[22]	validation_0-mae:5358.95911
[23]	validation_0-mae:5219.43984
[24]	validation_0-mae:5071.21809
[25]	validation_0-mae:4930.92994
[26]	validation_0-mae:4800.46410
[27]	validation_0-mae:4671.80678
[28]	validation_0-mae:4567.34312
[29]	validation_0-mae:4457.87689
[30]	validation_0-mae:4366.04655
[31]	validation_0-mae:4266.61801
[32]	validation_0-mae:4174.91211
[33]	validation_0-mae:4093.68933
[34]	validation_0-mae:4010.16642
[35]	validation_0-mae:3934.46175
[36]	validation_0-mae:3857.76119
[37]	validation_0-mae:3806.05558
[38]	validation_0-mae:3743.79496
[39]	validation_0-mae:3681.94419
[40]	validation_0-mae:3617.33616
[41]	validation_0-mae:3572.65666
[42]	validation_0-mae:3520.72732
[43]	validation_0-mae:3472.13746
[44]	validation_0-mae:3411.76301
[45]	validation_0-mae:3365.65122
[46]	validation_0-mae:3320.67991
[47]	validation_0-mae:3264.04405
[48]	validation_0-mae:3231.57556
[49]	validation_0-mae:3196.38356
[50]	validation_0-mae:3165.10741
[51]	validation_0-mae:3126.82309
[52]	validation_0-mae:3100.18270
[53]	validation_0-mae:3073.75035
[54]	validation_0-mae:3046.82418
[55]	validation_0-mae:3025.94710
[56]	validation_0-mae:2995.09308
[57]	validation_0-mae:2974.40910
[58]	validation_0-mae:2946.62788
[59]	validation_0-mae:2922.14737
[60]	validation_0-mae:2891.57897
[61]	validation_0-mae:2876.36489
[62]	validation_0-mae:2852.55413
[63]	validation_0-mae:2833.73838
[64]	validation_0-mae:2818.22555
[65]	validation_0-mae:2800.06028
[66]	validation_0-mae:2778.77213
[67]	validation_0-mae:2761.86663
[68]	validation_0-mae:2748.90528
[69]	validation_0-mae:2732.61006
[70]	validation_0-mae:2723.43116
[71]	validation_0-mae:2710.72361
[72]	validation_0-mae:2699.55413
[73]	validation_0-mae:2682.21197
[74]	validation_0-mae:2671.85859
[75]	validation_0-mae:2660.35421
[76]	validation_0-mae:2648.34918
[77]	validation_0-mae:2639.03288
[78]	validation_0-mae:2632.60002
[79]	validation_0-mae:2618.96528
[80]	validation_0-mae:2605.01379
[81]	validation_0-mae:2598.07894
[82]	validation_0-mae:2581.55413
[83]	validation_0-mae:2574.29042
[84]	validation_0-mae:2560.11846
[85]	validation_0-mae:2553.38213
[86]	validation_0-mae:2547.01599
[87]	validation_0-mae:2537.12564
[88]	validation_0-mae:2528.07626
[89]	validation_0-mae:2519.62937
[90]	validation_0-mae:2516.22007
[91]	validation_0-mae:2510.92808
[92]	validation_0-mae:2505.11945
[93]	validation_0-mae:2494.16190
[94]	validation_0-mae:2488.94237
[95]	validation_0-mae:2479.63706
[96]	validation_0-mae:2468.09830
[97]	validation_0-mae:2462.87343
[98]	validation_0-mae:2457.43774
[99]	validation_0-mae:2449.21279
[100]	validation_0-mae:2442.70353
[101]	validation_0-mae:2439.20540
[102]	validation_0-mae:2434.83927
[103]	validation_0-mae:2426.39788
[104]	validation_0-mae:2420.46326
[105]	validation_0-mae:2416.39907
[106]	validation_0-mae:2409.99163
[107]	validation_0-mae:2405.15232
[108]	validation_0-mae:2400.24211
[109]	validation_0-mae:2396.29852
[110]	validation_0-mae:2393.35841
[111]	validation_0-mae:2390.47180
[112]	validation_0-mae:2385.48641
[113]	validation_0-mae:2382.74716
[114]	validation_0-mae:2377.92346
[115]	validation_0-mae:2373.08835
[116]	validation_0-mae:2368.39041
[117]	validation_0-mae:2365.33962
[118]	validation_0-mae:2361.44894
[119]	validation_0-mae:2358.42835
[120]	validation_0-mae:2353.57141
[121]	validation_0-mae:2350.42586
[122]	validation_0-mae:2346.95490
[123]	validation_0-mae:2346.31936
[124]	validation_0-mae:2342.02527
[125]	validation_0-mae:2339.52456
[126]	validation_0-mae:2336.15276
[127]	validation_0-mae:2329.68400
[128]	validation_0-mae:2327.10796
[129]	validation_0-mae:2324.47382
[130]	validation_0-mae:2321.22392
[131]	validation_0-mae:2316.31839
[132]	validation_0-mae:2313.06204
[133]	validation_0-mae:2311.25540
[134]	validation_0-mae:2306.05424
[135]	validation_0-mae:2304.88260
[136]	validation_0-mae:2301.56553
[137]	validation_0-mae:2298.22639
[138]	validation_0-mae:2296.30509
[139]	validation_0-mae:2292.28319
[140]	validation_0-mae:2288.96857
[141]	validation_0-mae:2283.74267
[142]	validation_0-mae:2280.17306
[143]	validation_0-mae:2277.03456
[144]	validation_0-mae:2274.43890
[145]	validation_0-mae:2270.92194
[146]	validation_0-mae:2268.61388
[147]	validation_0-mae:2267.57350
[148]	validation_0-mae:2265.58305
[149]	validation_0-mae:2265.14004
[150]	validation_0-mae:2261.17491
[151]	validation_0-mae:2260.20203
[152]	validation_0-mae:2259.60106
[153]	validation_0-mae:2256.35264
[154]	validation_0-mae:2255.07819
[155]	validation_0-mae:2254.58261
[156]	validation_0-mae:2253.44706
[157]	validation_0-mae:2253.52005
[158]	validation_0-mae:2253.20963
[159]	validation_0-mae:2251.33498
[160]	validation_0-mae:2249.42301
[161]	validation_0-mae:2246.59912
[162]	validation_0-mae:2245.07068
[163]	validation_0-mae:2244.44797
[164]	validation_0-mae:2244.12617
[165]	validation_0-mae:2241.54660
[166]	validation_0-mae:2238.17075
[167]	validation_0-mae:2237.09282
[168]	validation_0-mae:2235.80679
[169]	validation_0-mae:2232.67386
[170]	validation_0-mae:2231.96738
[171]	validation_0-mae:2230.52633
[172]	validation_0-mae:2230.43636
[173]	validation_0-mae:2229.64456
[174]	validation_0-mae:2227.96889
[175]	validation_0-mae:2226.73728
[176]	validation_0-mae:2224.91260
[177]	validation_0-mae:2223.00342
[178]	validation_0-mae:2221.08036
[179]	validation_0-mae:2219.72609
[180]	validation_0-mae:2217.42267
[181]	validation_0-mae:2215.88419
[182]	validation_0-mae:2214.83010
[183]	validation_0-mae:2213.08752
[184]	validation_0-mae:2211.54945
[185]	validation_0-mae:2209.87468
[186]	validation_0-mae:2206.64325
[187]	validation_0-mae:2206.12631
[188]	validation_0-mae:2203.70815
[189]	validation_0-mae:2201.69388
[190]	validation_0-mae:2201.73883
[191]	validation_0-mae:2200.57532
[192]	validation_0-mae:2199.60164
[193]	validation_0-mae:2197.59032
[194]	validation_0-mae:2195.88379
[195]	validation_0-mae:2194.72728
[196]	validation_0-mae:2193.56617
[197]	validation_0-mae:2192.82628
[198]	validation_0-mae:2192.00246
[199]	validation_0-mae:2190.64429
[200]	validation_0-mae:2189.21585
[201]	validation_0-mae:2189.50927
[202]	validation_0-mae:2188.65262
[203]	validation_0-mae:2187.16715
[204]	validation_0-mae:2184.89245
[205]	validation_0-mae:2183.67253
[206]	validation_0-mae:2181.47295
[207]	validation_0-mae:2180.55491
[208]	validation_0-mae:2178.41481
[209]	validation_0-mae:2177.80808
[210]	validation_0-mae:2176.50184
[211]	validation_0-mae:2176.33233
[212]	validation_0-mae:2176.52090
[213]	validation_0-mae:2175.06905
[214]	validation_0-mae:2173.82068
[215]	validation_0-mae:2173.37513
[216]	validation_0-mae:2170.43680
[217]	validation_0-mae:2170.15566
[218]	validation_0-mae:2168.80460
[219]	validation_0-mae:2168.79977
[220]	validation_0-mae:2168.53937
[221]	validation_0-mae:2168.40102
[222]	validation_0-mae:2166.84848
[223]	validation_0-mae:2164.67571
[224]	validation_0-mae:2163.53901
[225]	validation_0-mae:2161.91849
[226]	validation_0-mae:2161.11432
[227]	validation_0-mae:2161.14163
[228]	validation_0-mae:2159.55957
[229]	validation_0-mae:2159.64143
[230]	validation_0-mae:2159.16652
[231]	validation_0-mae:2157.74895
[232]	validation_0-mae:2156.66013
[233]	validation_0-mae:2157.54394
[234]	validation_0-mae:2156.12905
[235]	validation_0-mae:2156.35036
[236]	validation_0-mae:2156.00770
[237]	validation_0-mae:2156.44960
[238]	validation_0-mae:2156.71738
[239]	validation_0-mae:2155.55335
[240]	validation_0-mae:2155.73482
[241]	validation_0-mae:2155.30765
[242]	validation_0-mae:2154.55421
[243]	validation_0-mae:2154.41457
[244]	validation_0-mae:2154.31514
[245]	validation_0-mae:2154.76993
[246]	validation_0-mae:2154.48568
[247]	validation_0-mae:2153.23770
[248]	validation_0-mae:2152.61639
[249]	validation_0-mae:2152.25725
[250]	validation_0-mae:2150.85405
[251]	validation_0-mae:2150.91825
[252]	validation_0-mae:2150.44855
[253]	validation_0-mae:2150.37558
[254]	validation_0-mae:2149.75994
[255]	validation_0-mae:2149.74784
[256]	validation_0-mae:2148.41555
[257]	validation_0-mae:2147.58310
[258]	validation_0-mae:2147.29348
[259]	validation_0-mae:2147.52699
[260]	validation_0-mae:2148.05554
[261]	validation_0-mae:2148.38049
[262]	validation_0-mae:2147.57970
[263]	validation_0-mae:2145.85473
[264]	validation_0-mae:2145.94905
[265]	validation_0-mae:2145.86086
[266]	validation_0-mae:2145.64147
[267]	validation_0-mae:2145.21615
[268]	validation_0-mae:2144.96938
[269]	validation_0-mae:2144.90383
[270]	validation_0-mae:2145.06497
[271]	validation_0-mae:2145.76742
[272]	validation_0-mae:2145.15684
[273]	validation_0-mae:2144.00568
[274]	validation_0-mae:2144.35491
[275]	validation_0-mae:2143.48237
[276]	validation_0-mae:2143.49476
[277]	validation_0-mae:2143.36731
[278]	validation_0-mae:2143.03027
[279]	validation_0-mae:2143.00234
[280]	validation_0-mae:2142.96242
[281]	validation_0-mae:2141.89674
[282]	validation_0-mae:2141.28972
[283]	validation_0-mae:2141.05543
[284]	validation_0-mae:2139.95991
[285]	validation_0-mae:2139.90339
[286]	validation_0-mae:2140.24670
[287]	validation_0-mae:2139.69513
[288]	validation_0-mae:2139.77903
[289]	validation_0-mae:2139.61531
[290]	validation_0-mae:2139.88972
[291]	validation_0-mae:2139.10282
[292]	validation_0-mae:2139.36985
[293]	validation_0-mae:2139.00408
[294]	validation_0-mae:2139.24542
[295]	validation_0-mae:2138.98042
[296]	validation_0-mae:2138.44544
[297]	validation_0-mae:2138.04978
[298]	validation_0-mae:2138.11100
[299]	validation_0-mae:2138.32974
[300]	validation_0-mae:2137.42007
[301]	validation_0-mae:2137.41874
[302]	validation_0-mae:2137.97162
[303]	validation_0-mae:2137.05600
[304]	validation_0-mae:2136.43808
[305]	validation_0-mae:2136.20391
[306]	validation_0-mae:2135.74262
[307]	validation_0-mae:2135.75412
[308]	validation_0-mae:2135.81825
[309]	validation_0-mae:2135.88001
[310]	validation_0-mae:2135.96715
[311]	validation_0-mae:2135.46027
[312]	validation_0-mae:2135.16301
[313]	validation_0-mae:2134.80731
[314]	validation_0-mae:2133.75751
[315]	validation_0-mae:2133.75865
[316]	validation_0-mae:2133.74561
[317]	validation_0-mae:2132.53952
[318]	validation_0-mae:2132.40627
[319]	validation_0-mae:2131.81434
[320]	validation_0-mae:2132.08777
[321]	validation_0-mae:2132.35867
[322]	validation_0-mae:2132.11671
[323]	validation_0-mae:2132.46106
[324]	validation_0-mae:2131.21191
[325]	validation_0-mae:2131.19782
[326]	validation_0-mae:2131.77243
[327]	validation_0-mae:2131.56734
[328]	validation_0-mae:2131.33851
[329]	validation_0-mae:2130.96882
[330]	validation_0-mae:2131.10244
[331]	validation_0-mae:2131.25381
[332]	validation_0-mae:2131.21536
[333]	validation_0-mae:2130.24347
[334]	validation_0-mae:2130.54185
[335]	validation_0-mae:2130.40801
[336]	validation_0-mae:2130.30684
[337]	validation_0-mae:2130.51678
[338]	validation_0-mae:2130.31220
[339]	validation_0-mae:2129.45598
[340]	validation_0-mae:2129.53069
[341]	validation_0-mae:2129.50085
[342]	validation_0-mae:2129.74779
[343]	validation_0-mae:2128.80123
[344]	validation_0-mae:2128.26367
[345]	validation_0-mae:2127.75239
[346]	validation_0-mae:2127.20573
[347]	validation_0-mae:2126.91278
[348]	validation_0-mae:2127.39989
[349]	validation_0-mae:2126.98562
[350]	validation_0-mae:2127.29421
[351]	validation_0-mae:2126.17823
[352]	validation_0-mae:2126.34403
[353]	validation_0-mae:2127.15958
[354]	validation_0-mae:2127.38328
[355]	validation_0-mae:2127.40505
[356]	validation_0-mae:2126.72678
[357]	validation_0-mae:2126.03694
[358]	validation_0-mae:2125.82928
[359]	validation_0-mae:2125.35994
[360]	validation_0-mae:2125.73582
[361]	validation_0-mae:2126.13544
[362]	validation_0-mae:2125.42769
[363]	validation_0-mae:2126.16108
[364]	validation_0-mae:2126.15053
[365]	validation_0-mae:2126.50936
[366]	validation_0-mae:2126.59719
[367]	validation_0-mae:2127.05852
[368]	validation_0-mae:2127.08944
[369]	validation_0-mae:2125.58638
[370]	validation_0-mae:2125.75359
[371]	validation_0-mae:2125.94613
[372]	validation_0-mae:2125.99231
[373]	validation_0-mae:2125.58508
[374]	validation_0-mae:2125.56341
[375]	validation_0-mae:2125.79362
[376]	validation_0-mae:2126.10860
[377]	validation_0-mae:2126.75550
[378]	validation_0-mae:2126.73355
[379]	validation_0-mae:2127.23623
[380]	validation_0-mae:2127.30637
[381]	validation_0-mae:2127.91111
[382]	validation_0-mae:2128.21145
[383]	validation_0-mae:2128.41084
[384]	validation_0-mae:2127.66146
[385]	validation_0-mae:2127.58938
[386]	validation_0-mae:2127.87869
[387]	validation_0-mae:2128.20102
[388]	validation_0-mae:2127.68269
[389]	validation_0-mae:2127.48685
[390]	validation_0-mae:2127.30212
[391]	validation_0-mae:2127.51709
[392]	validation_0-mae:2127.71872
[393]	validation_0-mae:2127.67320
[394]	validation_0-mae:2127.72411
[395]	validation_0-mae:2127.87577
[396]	validation_0-mae:2127.89048
[397]	validation_0-mae:2127.85869
[398]	validation_0-mae:2126.76179
[399]	validation_0-mae:2126.30278
[400]	validation_0-mae:2126.62640
[401]	validation_0-mae:2126.23754
[402]	validation_0-mae:2126.50571
[403]	validation_0-mae:2126.82567
[404]	validation_0-mae:2126.79333
[405]	validation_0-mae:2125.56242
[406]	validation_0-mae:2125.98884
[407]	validation_0-mae:2125.85142
[408]	validation_0-mae:2125.87981
[409]	validation_0-mae:2126.18678
[410]	validation_0-mae:2126.19383
[411]	validation_0-mae:2126.70447
[412]	validation_0-mae:2126.61323
[413]	validation_0-mae:2126.14022
[414]	validation_0-mae:2125.38907
[415]	validation_0-mae:2125.11638
[416]	validation_0-mae:2124.82988
[417]	validation_0-mae:2124.86873
[418]	validation_0-mae:2124.47833
[419]	validation_0-mae:2124.09861
[420]	validation_0-mae:2124.16944
[421]	validation_0-mae:2123.77086
[422]	validation_0-mae:2124.33226
[423]	validation_0-mae:2123.54523
[424]	validation_0-mae:2123.45052
[425]	validation_0-mae:2123.29968
[426]	validation_0-mae:2123.47190
[427]	validation_0-mae:2123.29283
[428]	validation_0-mae:2122.57729
[429]	validation_0-mae:2122.52719
[430]	validation_0-mae:2122.34068
[431]	validation_0-mae:2122.29632
[432]	validation_0-mae:2122.06656
[433]	validation_0-mae:2122.52029
[434]	validation_0-mae:2122.67300
[435]	validation_0-mae:2122.74930
[436]	validation_0-mae:2123.00154
[437]	validation_0-mae:2122.73525
[438]	validation_0-mae:2123.11169
[439]	validation_0-mae:2122.50258
[440]	validation_0-mae:2122.97007
[441]	validation_0-mae:2123.52971
[442]	validation_0-mae:2123.81832
[443]	validation_0-mae:2124.16404
[444]	validation_0-mae:2124.46832
[445]	validation_0-mae:2124.49225
[446]	validation_0-mae:2124.65606
[447]	validation_0-mae:2124.77917
[448]	validation_0-mae:2124.94589
[449]	validation_0-mae:2124.73132
[450]	validation_0-mae:2123.74553
[451]	validation_0-mae:2123.63585
[452]	validation_0-mae:2123.20936
[453]	validation_0-mae:2123.16277
[454]	validation_0-mae:2122.90541
[455]	validation_0-mae:2123.07669
[456]	validation_0-mae:2122.73659
[457]	validation_0-mae:2123.05834
[458]	validation_0-mae:2123.24026
[459]	validation_0-mae:2123.15194
[460]	validation_0-mae:2122.94808
[461]	validation_0-mae:2122.94033
[462]	validation_0-mae:2123.07164
[463]	validation_0-mae:2123.01757
[464]	validation_0-mae:2123.28589
[465]	validation_0-mae:2122.91601
[466]	validation_0-mae:2123.01921
[467]	validation_0-mae:2123.22770
[468]	validation_0-mae:2123.00769
[469]	validation_0-mae:2123.01431
[470]	validation_0-mae:2123.61740
[471]	validation_0-mae:2123.66692
[472]	validation_0-mae:2122.58409
[473]	validation_0-mae:2123.18510
[474]	validation_0-mae:2122.63307
[475]	validation_0-mae:2123.21377
[476]	validation_0-mae:2123.30074
[477]	validation_0-mae:2123.20017
[478]	validation_0-mae:2122.87265
[479]	validation_0-mae:2122.06349
[480]	validation_0-mae:2122.62131
[481]	validation_0-mae:2122.53773
[482]	validation_0-mae:2122.56180
[483]	validation_0-mae:2122.32094
[484]	validation_0-mae:2122.39734
[485]	validation_0-mae:2121.85794
[486]	validation_0-mae:2121.69230
[487]	validation_0-mae:2120.40493
[488]	validation_0-mae:2120.40869
[489]	validation_0-mae:2119.70315
[490]	validation_0-mae:2119.76196
[491]	validation_0-mae:2119.26025
[492]	validation_0-mae:2118.07360
[493]	validation_0-mae:2118.71752
[494]	validation_0-mae:2116.88801
[495]	validation_0-mae:2116.55684
[496]	validation_0-mae:2116.97092
[497]	validation_0-mae:2117.08937
[498]	validation_0-mae:2116.90399
[499]	validation_0-mae:2116.88681
[500]	validation_0-mae:2116.38553
[501]	validation_0-mae:2116.56424
[502]	validation_0-mae:2116.83036
[503]	validation_0-mae:2117.12394
[504]	validation_0-mae:2117.35109
[505]	validation_0-mae:2115.68497
[506]	validation_0-mae:2116.12154
[507]	validation_0-mae:2116.29687
[508]	validation_0-mae:2116.25613
[509]	validation_0-mae:2116.26215
[510]	validation_0-mae:2116.41339
[511]	validation_0-mae:2116.42629
[512]	validation_0-mae:2116.46941
[513]	validation_0-mae:2116.44245
[514]	validation_0-mae:2116.45299
[515]	validation_0-mae:2116.20005
[516]	validation_0-mae:2116.26338
[517]	validation_0-mae:2115.14736
[518]	validation_0-mae:2115.44953
[519]	validation_0-mae:2115.49313
[520]	validation_0-mae:2115.05639
[521]	validation_0-mae:2114.72514
[522]	validation_0-mae:2115.11470
[523]	validation_0-mae:2115.06401
[524]	validation_0-mae:2115.15943
[525]	validation_0-mae:2115.03660
[526]	validation_0-mae:2115.24570
[527]	validation_0-mae:2114.48971
[528]	validation_0-mae:2114.40754
[529]	validation_0-mae:2114.44956
[530]	validation_0-mae:2114.08780
[531]	validation_0-mae:2114.08718
[532]	validation_0-mae:2114.05852
[533]	validation_0-mae:2114.20954
[534]	validation_0-mae:2114.22903
[535]	validation_0-mae:2114.17227
[536]	validation_0-mae:2114.18902
[537]	validation_0-mae:2114.51208
[538]	validation_0-mae:2114.51930
[539]	validation_0-mae:2114.46943
[540]	validation_0-mae:2114.18100
[541]	validation_0-mae:2112.48742
[542]	validation_0-mae:2112.28980
[543]	validation_0-mae:2112.01875
[544]	validation_0-mae:2111.77949
[545]	validation_0-mae:2111.31527
[546]	validation_0-mae:2110.82264
[547]	validation_0-mae:2109.15644
[548]	validation_0-mae:2109.04086
[549]	validation_0-mae:2108.80972
[550]	validation_0-mae:2108.02627
[551]	validation_0-mae:2108.21139
[552]	validation_0-mae:2108.24402
[553]	validation_0-mae:2108.27213
[554]	validation_0-mae:2108.34351
[555]	validation_0-mae:2108.41216
[556]	validation_0-mae:2108.48759
[557]	validation_0-mae:2108.07244
[558]	validation_0-mae:2108.26525
[559]	validation_0-mae:2108.05617
[560]	validation_0-mae:2108.15195
[561]	validation_0-mae:2108.32127
[562]	validation_0-mae:2107.84402
[563]	validation_0-mae:2108.40973
[564]	validation_0-mae:2108.77819
[565]	validation_0-mae:2108.35177
[566]	validation_0-mae:2108.63817
[567]	validation_0-mae:2108.05768
[568]	validation_0-mae:2107.89314
[569]	validation_0-mae:2108.09147
[570]	validation_0-mae:2108.94792
[571]	validation_0-mae:2109.38420
[572]	validation_0-mae:2109.52823
[573]	validation_0-mae:2109.54620
[574]	validation_0-mae:2109.26397
[575]	validation_0-mae:2109.32993
[576]	validation_0-mae:2108.84053
[577]	validation_0-mae:2108.70259
[578]	validation_0-mae:2108.62128
[579]	validation_0-mae:2107.68027
[580]	validation_0-mae:2107.20501
[581]	validation_0-mae:2106.54222
[582]	validation_0-mae:2106.28264
[583]	validation_0-mae:2106.42080
[584]	validation_0-mae:2106.75178
[585]	validation_0-mae:2106.47031
[586]	validation_0-mae:2106.96129
[587]	validation_0-mae:2107.47904
[588]	validation_0-mae:2107.30041
[589]	validation_0-mae:2107.19055
[590]	validation_0-mae:2106.19926

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[42]	validation_0-mae:3433.34689
[43]	validation_0-mae:3395.01877
[44]	validation_0-mae:3351.30950
[45]	validation_0-mae:3315.61659
[46]	validation_0-mae:3280.89632
[47]	validation_0-mae:3235.79927
[48]	validation_0-mae:3197.29845
[49]	validation_0-mae:3165.90766
[50]	validation_0-mae:3138.91774
[51]	validation_0-mae:3110.66327
[52]	validation_0-mae:3071.03687
[53]	validation_0-mae:3029.21834
[54]	validation_0-mae:3005.92989
[55]	validation_0-mae:2984.25084
[56]	validation_0-mae:2962.97947
[57]	validation_0-mae:2931.54864
[58]	validation_0-mae:2913.40248
[59]	validation_0-mae:2893.94585
[60]	validation_0-mae:2867.58091
[61]	validation_0-mae:2851.35451
[62]	validation_0-mae:2831.99267
[63]	validation_0-mae:2820.42329
[64]	validation_0-mae:2806.41362
[65]	validation_0-mae:2788.01728
[66]	validation_0-mae:2773.93151
[67]	validation_0-mae:2758.58991
[68]	validation_0-mae:2747.27097
[69]	validation_0-mae:2725.45599
[70]	validation_0-mae:2706.42460
[71]	validation_0-mae:2695.56994
[72]	validation_0-mae:2684.42761
[73]	validation_0-mae:2672.54320
[74]	validation_0-mae:2664.17304
[75]	validation_0-mae:2654.90397
[76]	validation_0-mae:2636.95820
[77]	validation_0-mae:2623.80159
[78]	validation_0-mae:2611.57505
[79]	validation_0-mae:2604.78967
[80]	validation_0-mae:2592.86346
[81]	validation_0-mae:2580.95490
[82]	validation_0-mae:2571.34106
[83]	validation_0-mae:2566.91403
[84]	validation_0-mae:2557.63698
[85]	validation_0-mae:2544.90648
[86]	validation_0-mae:2533.01338
[87]	validation_0-mae:2524.92810
[88]	validation_0-mae:2515.48000
[89]	validation_0-mae:2510.20811
[90]	validation_0-mae:2502.93579
[91]	validation_0-mae:2494.19370
[92]	validation_0-mae:2491.58441
[93]	validation_0-mae:2488.57052
[94]	validation_0-mae:2483.74380
[95]	validation_0-mae:2476.99899
[96]	validation_0-mae:2470.47903
[97]	validation_0-mae:2462.98320
[98]	validation_0-mae:2453.50158
[99]	validation_0-mae:2451.77271
[100]	validation_0-mae:2448.69322
[101]	validation_0-mae:2443.01903
[102]	validation_0-mae:2438.06928
[103]	validation_0-mae:2430.36669
[104]	validation_0-mae:2425.92369
[105]	validation_0-mae:2420.09904
[106]	validation_0-mae:2418.82638
[107]	validation_0-mae:2412.44765
[108]	validation_0-mae:2409.10713
[109]	validation_0-mae:2408.04410
[110]	validation_0-mae:2399.72646
[111]	validation_0-mae:2396.91590
[112]	validation_0-mae:2395.30662
[113]	validation_0-mae:2385.58686
[114]	validation_0-mae:2379.37790
[115]	validation_0-mae:2373.38500
[116]	validation_0-mae:2372.17794
[117]	validation_0-mae:2365.78880
[118]	validation_0-mae:2361.21831
[119]	validation_0-mae:2354.77099
[120]	validation_0-mae:2351.83003
[121]	validation_0-mae:2346.70075
[122]	validation_0-mae:2345.89854
[123]	validation_0-mae:2342.41025
[124]	validation_0-mae:2339.82685
[125]	validation_0-mae:2337.45870
[126]	validation_0-mae:2330.70130
[127]	validation_0-mae:2328.87544
[128]	validation_0-mae:2326.04504
[129]	validation_0-mae:2323.41564
[130]	validation_0-mae:2320.25419
[131]	validation_0-mae:2318.76866
[132]	validation_0-mae:2314.79182
[133]	validation_0-mae:2312.99643
[134]	validation_0-mae:2308.78407
[135]	validation_0-mae:2307.52135
[136]	validation_0-mae:2304.03123
[137]	validation_0-mae:2303.15878
[138]	validation_0-mae:2301.25689
[139]	validation_0-mae:2299.73165
[140]	validation_0-mae:2299.21057
[141]	validation_0-mae:2296.50365
[142]	validation_0-mae:2293.68260
[143]	validation_0-mae:2293.49714
[144]	validation_0-mae:2290.16268
[145]	validation_0-mae:2287.08112
[146]	validation_0-mae:2285.08625
[147]	validation_0-mae:2282.21584
[148]	validation_0-mae:2279.22328
[149]	validation_0-mae:2277.00248
[150]	validation_0-mae:2276.58001
[151]	validation_0-mae:2275.17406
[152]	validation_0-mae:2273.89568
[153]	validation_0-mae:2273.77062
[154]	validation_0-mae:2273.49833
[155]	validation_0-mae:2271.62362
[156]	validation_0-mae:2270.29694
[157]	validation_0-mae:2270.00957
[158]	validation_0-mae:2268.59733
[159]	validation_0-mae:2267.59482
[160]	validation_0-mae:2266.93537
[161]	validation_0-mae:2264.68839
[162]	validation_0-mae:2264.06664
[163]	validation_0-mae:2264.62567
[164]	validation_0-mae:2263.75673
[165]	validation_0-mae:2263.02148
[166]	validation_0-mae:2261.99470
[167]	validation_0-mae:2262.34198
[168]	validation_0-mae:2260.93005
[169]	validation_0-mae:2260.57350
[170]	validation_0-mae:2260.10394
[171]	validation_0-mae:2255.22719
[172]	validation_0-mae:2254.34598
[173]	validation_0-mae:2253.97520
[174]	validation_0-mae:2251.93965
[175]	validation_0-mae:2252.09615
[176]	validation_0-mae:2251.71358
[177]	validation_0-mae:2249.91643
[178]	validation_0-mae:2248.35478
[179]	validation_0-mae:2249.19900
[180]	validation_0-mae:2248.77546
[181]	validation_0-mae:2247.89561
[182]	validation_0-mae:2246.88554
[183]	validation_0-mae:2246.04296
[184]	validation_0-mae:2247.35223
[185]	validation_0-mae:2246.95402
[186]	validation_0-mae:2246.36929
[187]	validation_0-mae:2246.76704
[188]	validation_0-mae:2245.52455
[189]	validation_0-mae:2245.31546
[190]	validation_0-mae:2243.10092
[191]	validation_0-mae:2241.19111
[192]	validation_0-mae:2240.78921
[193]	validation_0-mae:2240.80625
[194]	validation_0-mae:2239.78361
[195]	validation_0-mae:2240.21449
[196]	validation_0-mae:2239.73212
[197]	validation_0-mae:2239.37171
[198]	validation_0-mae:2238.83137
[199]	validation_0-mae:2239.22705
[200]	validation_0-mae:2238.09881
[201]	validation_0-mae:2237.31116
[202]	validation_0-mae:2235.81109
[203]	validation_0-mae:2235.78032
[204]	validation_0-mae:2234.53920
[205]	validation_0-mae:2234.23280
[206]	validation_0-mae:2235.05250
[207]	validation_0-mae:2236.13000
[208]	validation_0-mae:2235.86142
[209]	validation_0-mae:2236.19954
[210]	validation_0-mae:2234.10432
[211]	validation_0-mae:2234.03095
[212]	validation_0-mae:2233.90469
[213]	validation_0-mae:2232.03450
[214]	validation_0-mae:2231.79471
[215]	validation_0-mae:2232.39584
[216]	validation_0-mae:2231.95383
[217]	validation_0-mae:2232.05629
[218]	validation_0-mae:2230.90165
[219]	validation_0-mae:2230.76542
[220]	validation_0-mae:2230.12074
[221]	validation_0-mae:2228.97969
[222]	validation_0-mae:2229.48898
[223]	validation_0-mae:2230.30282
[224]	validation_0-mae:2229.49866
[225]	validation_0-mae:2229.65149
[226]	validation_0-mae:2229.90821
[227]	validation_0-mae:2228.98802
[228]	validation_0-mae:2227.85667
[229]	validation_0-mae:2226.18677
[230]	validation_0-mae:2226.58240
[231]	validation_0-mae:2225.05017
[232]	validation_0-mae:2224.53072
[233]	validation_0-mae:2225.66213
[234]	validation_0-mae:2226.11552
[235]	validation_0-mae:2225.99780
[236]	validation_0-mae:2224.99001
[237]	validation_0-mae:2223.39213
[238]	validation_0-mae:2223.21228
[239]	validation_0-mae:2222.09708
[240]	validation_0-mae:2221.85049
[241]	validation_0-mae:2221.15063
[242]	validation_0-mae:2220.19966
[243]	validation_0-mae:2219.65095
[244]	validation_0-mae:2217.87355
[245]	validation_0-mae:2218.00494
[246]	validation_0-mae:2218.33474
[247]	validation_0-mae:2217.28028
[248]	validation_0-mae:2215.88926
[249]	validation_0-mae:2215.09024
[250]	validation_0-mae:2213.95196
[251]	validation_0-mae:2213.58772
[252]	validation_0-mae:2212.30934
[253]	validation_0-mae:2212.86511
[254]	validation_0-mae:2212.64003
[255]	validation_0-mae:2211.95150
[256]	validation_0-mae:2211.13632
[257]	validation_0-mae:2210.95436
[258]	validation_0-mae:2210.62620
[259]	validation_0-mae:2210.89543
[260]	validation_0-mae:2210.82673
[261]	validation_0-mae:2209.28590
[262]	validation_0-mae:2209.65102
[263]	validation_0-mae:2209.35763
[264]	validation_0-mae:2209.11847
[265]	validation_0-mae:2209.46243
[266]	validation_0-mae:2209.94863
[267]	validation_0-mae:2209.46683
[268]	validation_0-mae:2209.39350
[269]	validation_0-mae:2209.76489
[270]	validation_0-mae:2208.58736
[271]	validation_0-mae:2208.54087
[272]	validation_0-mae:2207.93469
[273]	validation_0-mae:2208.06791
[274]	validation_0-mae:2208.52411
[275]	validation_0-mae:2208.50656
[276]	validation_0-mae:2208.37301
[277]	validation_0-mae:2208.55044
[278]	validation_0-mae:2209.11525
[279]	validation_0-mae:2209.28742
[280]	validation_0-mae:2207.02523
[281]	validation_0-mae:2207.66172
[282]	validation_0-mae:2207.48583
[283]	validation_0-mae:2207.58604
[284]	validation_0-mae:2207.39329
[285]	validation_0-mae:2206.78988
[286]	validation_0-mae:2206.93977
[287]	validation_0-mae:2205.71743
[288]	validation_0-mae:2205.34440
[289]	validation_0-mae:2205.21156
[290]	validation_0-mae:2204.00841
[291]	validation_0-mae:2204.03650
[292]	validation_0-mae:2203.61841
[293]	validation_0-mae:2202.90275
[294]	validation_0-mae:2201.81947
[295]	validation_0-mae:2201.72933
[296]	validation_0-mae:2201.65655
[297]	validation_0-mae:2201.78540
[298]	validation_0-mae:2202.09537
[299]	validation_0-mae:2200.66322
[300]	validation_0-mae:2200.10117
[301]	validation_0-mae:2199.42008
[302]	validation_0-mae:2198.34699
[303]	validation_0-mae:2198.91156
[304]	validation_0-mae:2198.41107
[305]	validation_0-mae:2198.39345
[306]	validation_0-mae:2198.62414
[307]	validation_0-mae:2197.48949
[308]	validation_0-mae:2198.37522
[309]	validation_0-mae:2198.20927
[310]	validation_0-mae:2198.19212
[311]	validation_0-mae:2198.10543
[312]	validation_0-mae:2197.49876
[313]	validation_0-mae:2198.11953
[314]	validation_0-mae:2198.46394
[315]	validation_0-mae:2198.99150
[316]	validation_0-mae:2199.27890
[317]	validation_0-mae:2199.28478
[318]	validation_0-mae:2199.33658
[319]	validation_0-mae:2199.05668
[320]	validation_0-mae:2199.11986
[321]	validation_0-mae:2199.24808
[322]	validation_0-mae:2199.17766
[323]	validation_0-mae:2199.34971
[324]	validation_0-mae:2199.42411
[325]	validation_0-mae:2198.71397
[326]	validation_0-mae:2197.94563
[327]	validation_0-mae:2197.19014
[328]	validation_0-mae:2196.92296
[329]	validation_0-mae:2197.45739
[330]	validation_0-mae:2196.94107
[331]	validation_0-mae:2195.85584
[332]	validation_0-mae:2194.99170
[333]	validation_0-mae:2195.44940
[334]	validation_0-mae:2194.02024
[335]	validation_0-mae:2193.00606
[336]	validation_0-mae:2192.27854
[337]	validation_0-mae:2191.18053
[338]	validation_0-mae:2189.31120
[339]	validation_0-mae:2188.33741
[340]	validation_0-mae:2187.27863
[341]	validation_0-mae:2187.51252
[342]	validation_0-mae:2187.17117
[343]	validation_0-mae:2186.99508
[344]	validation_0-mae:2187.18754
[345]	validation_0-mae:2188.14330
[346]	validation_0-mae:2187.48875
[347]	validation_0-mae:2187.80426
[348]	validation_0-mae:2187.64934
[349]	validation_0-mae:2187.65141
[350]	validation_0-mae:2186.87142
[351]	validation_0-mae:2187.66167
[352]	validation_0-mae:2187.65380
[353]	validation_0-mae:2188.00458
[354]	validation_0-mae:2187.42990
[355]	validation_0-mae:2187.90696
[356]	validation_0-mae:2187.67173
[357]	validation_0-mae:2187.86094
[358]	validation_0-mae:2187.32340
[359]	validation_0-mae:2187.31102
[360]	validation_0-mae:2187.34645
[361]	validation_0-mae:2187.71237
[362]	validation_0-mae:2187.31819
[363]	validation_0-mae:2187.64247
[364]	validation_0-mae:2187.12591
[365]	validation_0-mae:2187.40924
[366]	validation_0-mae:2187.54162
[367]	validation_0-mae:2187.11414
[368]	validation_0-mae:2187.55271
[369]	validation_0-mae:2187.25098
[370]	validation_0-mae:2187.28077
[371]	validation_0-mae:2187.54007
[372]	validation_0-mae:2187.87051
[373]	validation_0-mae:2187.81408
[374]	validation_0-mae:2187.70608
[375]	validation_0-mae:2187.54721
[376]	validation_0-mae:2187.77859
[377]	validation_0-mae:2186.78440
[378]	validation_0-mae:2186.14726
[379]	validation_0-mae:2185.21312
[380]	validation_0-mae:2185.36933
[381]	validation_0-mae:2185.12169
[382]	validation_0-mae:2185.32334
[383]	validation_0-mae:2185.97429
[384]	validation_0-mae:2185.88683
[385]	validation_0-mae:2185.77690
[386]	validation_0-mae:2184.80575
[387]	validation_0-mae:2184.88632
[388]	validation_0-mae:2184.72653
[389]	validation_0-mae:2184.59527
[390]	validation_0-mae:2184.66230
[391]	validation_0-mae:2184.92810
[392]	validation_0-mae:2185.05454
[393]	validation_0-mae:2185.71141
[394]	validation_0-mae:2185.75309
[395]	validation_0-mae:2185.69072
[396]	validation_0-mae:2185.91706
[397]	validation_0-mae:2186.02727
[398]	validation_0-mae:2186.20309
[399]	validation_0-mae:2186.09343
[400]	validation_0-mae:2186.01238
[401]	validation_0-mae:2185.89282
[402]	validation_0-mae:2186.26865
[403]	validation_0-mae:2186.45714
[404]	validation_0-mae:2186.51109
[405]	validation_0-mae:2186.56528
[406]	validation_0-mae:2187.21719
[407]	validation_0-mae:2187.35179
[408]	validation_0-mae:2187.32523
[409]	validation_0-mae:2187.68520
[410]	validation_0-mae:2188.08184
[411]	validation_0-mae:2187.90610
[412]	validation_0-mae:2187.92162
[413]	validation_0-mae:2187.54931
[414]	validation_0-mae:2186.66102
[415]	validation_0-mae:2186.06173
[416]	validation_0-mae:2186.34640
[417]	validation_0-mae:2186.57255
[418]	validation_0-mae:2186.46718
[419]	validation_0-mae:2186.42532
[420]	validation_0-mae:2186.11835
[421]	validation_0-mae:2185.81261
[422]	validation_0-mae:2185.84234
[423]	validation_0-mae:2185.49534
[424]	validation_0-mae:2185.40470
[425]	validation_0-mae:2185.31458
[426]	validation_0-mae:2185.45252
[427]	validation_0-mae:2185.85742
[428]	validation_0-mae:2185.50347
[429]	validation_0-mae:2185.47373
[430]	validation_0-mae:2185.25592
[431]	validation_0-mae:2184.75660
[432]	validation_0-mae:2185.01693
[433]	validation_0-mae:2185.00361
[434]	validation_0-mae:2185.72253
[435]	validation_0-mae:2185.90193
[436]	validation_0-mae:2186.31817
[437]	validation_0-mae:2186.21083
[438]	validation_0-mae:2187.03977
[439]	validation_0-mae:2187.04540
[440]	validation_0-mae:2187.01393
[441]	validation_0-mae:2186.97761
[442]	validation_0-mae:2186.95364
[443]	validation_0-mae:2187.96529
[444]	validation_0-mae:2187.91488
[445]	validation_0-mae:2188.31775
[446]	validation_0-mae:2187.74939
[447]	validation_0-mae:2188.24938
[448]	validation_0-mae:2188.34676
[449]	validation_0-mae:2188.47511
[450]	validation_0-mae:2188.91889
[451]	validation_0-mae:2188.92708
[452]	validation_0-mae:2188.38935
[453]	validation_0-mae:2188.18028
[454]	validation_0-mae:2188.76423
[455]	validation_0-mae:2188.49878
[456]	validation_0-mae:2188.48954
[457]	validation_0-mae:2188.30557
[458]	validation_0-mae:2188.26102
[459]	validation_0-mae:2188.20197
[460]	validation_0-mae:2188.47436
[461]	validation_0-mae:2188.41029
[462]	validation_0-mae:2188.64540
[463]	validation_0-mae:2188.77144
[464]	validation_0-mae:2189.33427
[465]	validation_0-mae:2188.00826
[466]	validation_0-mae:2187.93242
[467]	validation_0-mae:2188.00786
[468]	validation_0-mae:2188.03409
[469]	validation_0-mae:2186.97428
[470]	validation_0-mae:2187.09873
[471]	validation_0-mae:2186.60666
[472]	validation_0-mae:2186.19095
[473]	validation_0-mae:2185.39863
[474]	validation_0-mae:2185.51128
[475]	validation_0-mae:2184.59797
[476]	validation_0-mae:2184.40339
[477]	validation_0-mae:2183.92953
[478]	validation_0-mae:2183.94841
[479]	validation_0-mae:2184.22530
[480]	validation_0-mae:2184.87817
[481]	validation_0-mae:2185.06324
[482]	validation_0-mae:2184.03100
[483]	validation_0-mae:2183.73700
[484]	validation_0-mae:2183.70087
[485]	validation_0-mae:2183.93202
[486]	validation_0-mae:2182.65241
[487]	validation_0-mae:2182.41190
[488]	validation_0-mae:2182.30835
[489]	validation_0-mae:2181.81467
[490]	validation_0-mae:2181.17485
[491]	validation_0-mae:2181.04797
[492]	validation_0-mae:2181.79676
[493]	validation_0-mae:2181.95196
[494]	validation_0-mae:2181.88656
[495]	validation_0-mae:2182.49381
[496]	validation_0-mae:2182.47316
[497]	validation_0-mae:2181.98836
[498]	validation_0-mae:2181.72653
[499]	validation_0-mae:2181.80035
[500]	validation_0-mae:2181.95288
[501]	validation_0-mae:2182.12552
[502]	validation_0-mae:2182.18587
[503]	validation_0-mae:2182.03241
[504]	validation_0-mae:2181.79493
[505]	validation_0-mae:2181.91857
[506]	validation_0-mae:2182.31165
[507]	validation_0-mae:2181.89444
[508]	validation_0-mae:2181.69855
[509]	validation_0-mae:2181.74819
[510]	validation_0-mae:2181.85753
[511]	validation_0-mae:2182.06855
[512]	validation_0-mae:2181.91238
[513]	validation_0-mae:2182.02556
[514]	validation_0-mae:2182.10141
[515]	validation_0-mae:2182.45606
[516]	validation_0-mae:2182.49317
[517]	validation_0-mae:2182.52577
[518]	validation_0-mae:2182.52687
[519]	validation_0-mae:2182.67072
[520]	validation_0-mae:2182.86718
[521]	validation_0-mae:2182.63455
[522]	validation_0-mae:2181.51056
[523]	validation_0-mae:2181.44411
[524]	validation_0-mae:2180.63341
[525]	validation_0-mae:2180.46962
[526]	validation_0-mae:2180.37553
[527]	validation_0-mae:2180.21642
[528]	validation_0-mae:2179.89037
[529]	validation_0-mae:2179.56276
[530]	validation_0-mae:2178.68240
[531]	validation_0-mae:2178.47500
[532]	validation_0-mae:2177.67248
[533]	validation_0-mae:2177.77464
[534]	validation_0-mae:2177.61284
[535]	validation_0-mae:2177.02419
[536]	validation_0-mae:2176.70187
[537]	validation_0-mae:2176.29623
[538]	validation_0-mae:2175.59827
[539]	validation_0-mae:2175.27469
[540]	validation_0-mae:2174.14176
[541]	validation_0-mae:2173.37781
[542]	validation_0-mae:2172.53423
[543]	validation_0-mae:2171.69138
[544]	validation_0-mae:2171.36132
[545]	validation_0-mae:2170.79350
[546]	validation_0-mae:2170.68811
[547]	validation_0-mae:2169.82451
[548]	validation_0-mae:2169.52451
[549]	validation_0-mae:2168.75778
[550]	validation_0-mae:2168.07825
[551]	validation_0-mae:2167.94878
[552]	validation_0-mae:2167.40409
[553]	validation_0-mae:2167.59962
[554]	validation_0-mae:2167.76740
[555]	validation_0-mae:2167.62366
[556]	validation_0-mae:2167.81016
[557]	validation_0-mae:2167.85834
[558]	validation_0-mae:2167.96710
[559]	validation_0-mae:2167.94693
[560]	validation_0-mae:2167.67710
[561]	validation_0-mae:2167.45782
[562]	validation_0-mae:2167.31763
[563]	validation_0-mae:2167.57144
[564]	validation_0-mae:2167.30140
[565]	validation_0-mae:2166.63412
[566]	validation_0-mae:2166.39317
[567]	validation_0-mae:2166.40423
[568]	validation_0-mae:2166.56595
[569]	validation_0-mae:2166.60510
[570]	validation_0-mae:2166.59133
[571]	validation_0-mae:2166.65720
[572]	validation_0-mae:2166.84124
[573]	validation_0-mae:2165.74490
[574]	validation_0-mae:2165.52829
[575]	validation_0-mae:2165.59651
[576]	validation_0-mae:2165.68541
[577]	validation_0-mae:2165.68713
[578]	validation_0-mae:2165.28262
[579]	validation_0-mae:2165.73099
[580]	validation_0-mae:2165.26941
[581]	validation_0-mae:2165.20167
[582]	validation_0-mae:2165.25889
[583]	validation_0-mae:2165.16060
[584]	validation_0-mae:2165.70113
[585]	validation_0-mae:2165.79848
[586]	validation_0-mae:2165.88567
[587]	validation_0-mae:2166.27563
[588]	validation_0-mae:2165.75896
[589]	validation_0-mae:2165.70367
[590]	validation_0-mae:2165.70226
[591]	validation_0-mae:2165.90593
[592]	validation_0-mae:2165.70355
[0]	validation_0-mae:12570.73825
[1]	validation_0-mae:11936.76510
[2]	validation_0-mae:11348.97185
[3]	validation_0-mae:10783.12193
[4]	validation_0-mae:10275.79002
[5]	validation_0-mae:9823.41427
[6]	validation_0-mae:9376.18991
[7]	validation_0-mae:8989.40867
[8]	validation_0-mae:8631.26084
[9]	validation_0-mae:8298.50228
[10]	validation_0-mae:7998.43753
[11]	validation_0-mae:7718.83881
[12]	validation_0-mae:7448.81478
[13]	validation_0-mae:7186.85413
[14]	validation_0-mae:6960.00059
[15]	validation_0-mae:6731.89364
[16]	validation_0-mae:6512.89414
[17]	validation_0-mae:6313.27091
[18]	validation_0-mae:6129.65466
[19]	validation_0-mae:5942.03467
[20]	validation_0-mae:5768.53855
[21]	validation_0-mae:5604.32108
[22]	validation_0-mae:5452.60486
[23]	validation_0-mae:5321.48932
[24]	validation_0-mae:5172.06309
[25]	validation_0-mae:5046.12785
[26]	validation_0-mae:4909.11361
[27]	validation_0-mae:4795.68157
[28]	validation_0-mae:4683.48700
[29]	validation_0-mae:4574.92593
[30]	validation_0-mae:4468.87368
[31]	validation_0-mae:4372.11160
[32]	validation_0-mae:4276.22802
[33]	validation_0-mae:4210.22972
[34]	validation_0-mae:4120.87241
[35]	validation_0-mae:4043.85910
[36]	validation_0-mae:3968.73280
[37]	validation_0-mae:3917.50835
[38]	validation_0-mae:3841.96513
[39]	validation_0-mae:3772.11311

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[41]	validation_0-mae:3654.07680
[42]	validation_0-mae:3600.41771
[43]	validation_0-mae:3548.57624
[44]	validation_0-mae:3492.83493
[45]	validation_0-mae:3445.37279
[46]	validation_0-mae:3402.37911
[47]	validation_0-mae:3361.92912
[48]	validation_0-mae:3319.11300
[49]	validation_0-mae:3281.51602
[50]	validation_0-mae:3247.40454
[51]	validation_0-mae:3219.18558
[52]	validation_0-mae:3189.26758
[53]	validation_0-mae:3157.99367
[54]	validation_0-mae:3133.81245
[55]	validation_0-mae:3107.71186
[56]	validation_0-mae:3086.29314
[57]	validation_0-mae:3064.08280
[58]	validation_0-mae:3038.91139
[59]	validation_0-mae:3017.52285
[60]	validation_0-mae:2981.87707
[61]	validation_0-mae:2967.58578
[62]	validation_0-mae:2951.88802
[63]	validation_0-mae:2935.06273
[64]	validation_0-mae:2905.78294
[65]	validation_0-mae:2893.08194
[66]	validation_0-mae:2879.75430
[67]	validation_0-mae:2855.64868
[68]	validation_0-mae:2831.94457
[69]	validation_0-mae:2807.09784
[70]	validation_0-mae:2791.95186
[71]	validation_0-mae:2777.62399
[72]	validation_0-mae:2769.12382
[73]	validation_0-mae:2756.84552
[74]	validation_0-mae:2743.21100
[75]	validation_0-mae:2715.32510
[76]	validation_0-mae:2707.51037
[77]	validation_0-mae:2688.69432
[78]	validation_0-mae:2666.89831
[79]	validation_0-mae:2658.24989
[80]	validation_0-mae:2651.46912
[81]	validation_0-mae:2641.76757
[82]	validation_0-mae:2638.35714
[83]	validation_0-mae:2627.85454
[84]	validation_0-mae:2620.72291
[85]	validation_0-mae:2611.84796
[86]	validation_0-mae:2604.63656
[87]	validation_0-mae:2590.01159
[88]	validation_0-mae:2587.97497
[89]	validation_0-mae:2582.78761
[90]	validation_0-mae:2569.24613
[91]	validation_0-mae:2565.24816
[92]	validation_0-mae:2553.72989
[93]	validation_0-mae:2549.21699
[94]	validation_0-mae:2541.04073
[95]	validation_0-mae:2536.17950
[96]	validation_0-mae:2527.36440
[97]	validation_0-mae:2518.56026
[98]	validation_0-mae:2513.71910
[99]	validation_0-mae:2506.77912
[100]	validation_0-mae:2497.65943
[101]	validation_0-mae:2492.70330
[102]	validation_0-mae:2487.48671
[103]	validation_0-mae:2485.66101
[104]	validation_0-mae:2479.18554
[105]	validation_0-mae:2474.21227
[106]	validation_0-mae:2463.42183
[107]	validation_0-mae:2453.28019
[108]	validation_0-mae:2451.52443
[109]	validation_0-mae:2443.49388
[110]	validation_0-mae:2438.49355
[111]	validation_0-mae:2426.82153
[112]	validation_0-mae:2422.14809
[113]	validation_0-mae:2417.67986
[114]	validation_0-mae:2413.62708
[115]	validation_0-mae:2411.26725
[116]	validation_0-mae:2407.12737
[117]	validation_0-mae:2399.87554
[118]	validation_0-mae:2392.68104
[119]	validation_0-mae:2389.81357
[120]	validation_0-mae:2385.04643
[121]	validation_0-mae:2377.22150
[122]	validation_0-mae:2374.99569
[123]	validation_0-mae:2370.98321
[124]	validation_0-mae:2368.36020
[125]	validation_0-mae:2363.83482
[126]	validation_0-mae:2356.80281
[127]	validation_0-mae:2356.53901
[128]	validation_0-mae:2352.39748
[129]	validation_0-mae:2349.15716
[130]	validation_0-mae:2344.65256
[131]	validation_0-mae:2342.82210
[132]	validation_0-mae:2340.06510
[133]	validation_0-mae:2333.38600
[134]	validation_0-mae:2330.60863
[135]	validation_0-mae:2329.57484
[136]	validation_0-mae:2327.84579
[137]	validation_0-mae:2324.20861
[138]	validation_0-mae:2319.29064
[139]	validation_0-mae:2317.45275
[140]	validation_0-mae:2316.07638
[141]	validation_0-mae:2314.87928
[142]	validation_0-mae:2312.29686
[143]	validation_0-mae:2312.04576
[144]	validation_0-mae:2310.68494
[145]	validation_0-mae:2308.40881
[146]	validation_0-mae:2304.15909
[147]	validation_0-mae:2300.46791
[148]	validation_0-mae:2298.80556
[149]	validation_0-mae:2296.47136
[150]	validation_0-mae:2294.51754
[151]	validation_0-mae:2292.93605
[152]	validation_0-mae:2291.71372
[153]	validation_0-mae:2289.57880
[154]	validation_0-mae:2287.65437
[155]	validation_0-mae:2287.86616
[156]	validation_0-mae:2286.85598
[157]	validation_0-mae:2284.22549
[158]	validation_0-mae:2279.28993
[159]	validation_0-mae:2275.40837
[160]	validation_0-mae:2274.55297
[161]	validation_0-mae:2273.30376
[162]	validation_0-mae:2272.47765
[163]	validation_0-mae:2269.51325
[164]	validation_0-mae:2268.91612
[165]	validation_0-mae:2266.84305
[166]	validation_0-mae:2264.03756
[167]	validation_0-mae:2260.67533
[168]	validation_0-mae:2258.44215
[169]	validation_0-mae:2257.08448
[170]	validation_0-mae:2254.02070
[171]	validation_0-mae:2253.03884
[172]	validation_0-mae:2249.43139
[173]	validation_0-mae:2247.22488
[174]	validation_0-mae:2246.73795
[175]	validation_0-mae:2245.50132
[176]	validation_0-mae:2243.72299
[177]	validation_0-mae:2240.29201
[178]	validation_0-mae:2240.28616
[179]	validation_0-mae:2239.48718
[180]	validation_0-mae:2239.45621
[181]	validation_0-mae:2238.18147
[182]	validation_0-mae:2236.62437
[183]	validation_0-mae:2237.00108
[184]	validation_0-mae:2237.11485
[185]	validation_0-mae:2235.94703
[186]	validation_0-mae:2235.87460
[187]	validation_0-mae:2234.68327
[188]	validation_0-mae:2231.89999
[189]	validation_0-mae:2231.17388
[190]	validation_0-mae:2228.37129
[191]	validation_0-mae:2229.01759
[192]	validation_0-mae:2227.63150
[193]	validation_0-mae:2225.65902
[194]	validation_0-mae:2225.18707
[195]	validation_0-mae:2224.42898
[196]	validation_0-mae:2223.00703
[197]	validation_0-mae:2223.33525
[198]	validation_0-mae:2223.57437
[199]	validation_0-mae:2222.39838
[200]	validation_0-mae:2223.60108
[201]	validation_0-mae:2224.06622
[202]	validation_0-mae:2224.26904
[203]	validation_0-mae:2222.67298
[204]	validation_0-mae:2220.00798
[205]	validation_0-mae:2219.30983
[206]	validation_0-mae:2217.72854
[207]	validation_0-mae:2217.03134
[208]	validation_0-mae:2217.28537
[209]	validation_0-mae:2217.64995
[210]	validation_0-mae:2216.59197
[211]	validation_0-mae:2216.29810
[212]	validation_0-mae:2215.44907
[213]	validation_0-mae:2214.20334
[214]	validation_0-mae:2214.55716
[215]	validation_0-mae:2215.19621
[216]	validation_0-mae:2215.42887
[217]	validation_0-mae:2214.67825
[218]	validation_0-mae:2213.17488
[219]	validation_0-mae:2212.56846
[220]	validation_0-mae:2212.30886
[221]	validation_0-mae:2211.99328
[222]	validation_0-mae:2211.25840
[223]	validation_0-mae:2209.04887
[224]	validation_0-mae:2208.95107
[225]	validation_0-mae:2207.23175
[226]	validation_0-mae:2206.95828
[227]	validation_0-mae:2205.87004
[228]	validation_0-mae:2206.07031
[229]	validation_0-mae:2205.91538
[230]	validation_0-mae:2205.24419
[231]	validation_0-mae:2204.34308
[232]	validation_0-mae:2201.57379
[233]	validation_0-mae:2200.11801
[234]	validation_0-mae:2200.19848
[235]	validation_0-mae:2199.86574
[236]	validation_0-mae:2199.56615
[237]	validation_0-mae:2199.36705
[238]	validation_0-mae:2198.16572
[239]	validation_0-mae:2197.80836
[240]	validation_0-mae:2197.95167
[241]	validation_0-mae:2197.40398
[242]	validation_0-mae:2198.47000
[243]	validation_0-mae:2198.38376
[244]	validation_0-mae:2196.02619
[245]	validation_0-mae:2195.27966
[246]	validation_0-mae:2195.39985
[247]	validation_0-mae:2194.34209
[248]	validation_0-mae:2194.14237
[249]	validation_0-mae:2194.89352
[250]	validation_0-mae:2195.32143
[251]	validation_0-mae:2194.60303
[252]	validation_0-mae:2194.13304
[253]	validation_0-mae:2194.31163
[254]	validation_0-mae:2192.79281
[255]	validation_0-mae:2191.29927
[256]	validation_0-mae:2190.74269
[257]	validation_0-mae:2189.08058
[258]	validation_0-mae:2187.72800
[259]	validation_0-mae:2186.64438
[260]	validation_0-mae:2185.63060
[261]	validation_0-mae:2185.59154
[262]	validation_0-mae:2186.37511
[263]	validation_0-mae:2186.59884
[264]	validation_0-mae:2186.17224
[265]	validation_0-mae:2186.27320
[266]	validation_0-mae:2186.48072
[267]	validation_0-mae:2185.79048
[268]	validation_0-mae:2185.66764
[269]	validation_0-mae:2185.39981
[270]	validation_0-mae:2185.84124
[271]	validation_0-mae:2185.62682
[272]	validation_0-mae:2184.53485
[273]	validation_0-mae:2186.18901
[274]	validation_0-mae:2185.99993
[275]	validation_0-mae:2185.59423
[276]	validation_0-mae:2185.66392
[277]	validation_0-mae:2185.27469
[278]	validation_0-mae:2185.29412
[279]	validation_0-mae:2184.95126
[280]	validation_0-mae:2185.12789
[281]	validation_0-mae:2185.06112
[282]	validation_0-mae:2185.22047
[283]	validation_0-mae:2185.51508
[284]	validation_0-mae:2185.23671
[285]	validation_0-mae:2185.59856
[286]	validation_0-mae:2185.04284
[287]	validation_0-mae:2185.29326
[288]	validation_0-mae:2185.12620
[289]	validation_0-mae:2185.43625
[290]	validation_0-mae:2185.41272
[291]	validation_0-mae:2184.64196
[292]	validation_0-mae:2184.77462
[293]	validation_0-mae:2184.78404
[294]	validation_0-mae:2184.72776
[295]	validation_0-mae:2183.98310
[296]	validation_0-mae:2183.05034
[297]	validation_0-mae:2182.34937
[298]	validation_0-mae:2182.13364
[299]	validation_0-mae:2182.43164
[300]	validation_0-mae:2181.87430
[301]	validation_0-mae:2181.46312
[302]	validation_0-mae:2181.97667
[303]	validation_0-mae:2181.16400
[304]	validation_0-mae:2181.24801
[305]	validation_0-mae:2180.42604
[306]	validation_0-mae:2179.87997
[307]	validation_0-mae:2178.61566
[308]	validation_0-mae:2177.21631
[309]	validation_0-mae:2177.04284
[310]	validation_0-mae:2175.63203
[311]	validation_0-mae:2175.27211
[312]	validation_0-mae:2175.46484
[313]	validation_0-mae:2173.88638
[314]	validation_0-mae:2172.47794
[315]	validation_0-mae:2172.72823
[316]	validation_0-mae:2172.61699
[317]	validation_0-mae:2171.53760
[318]	validation_0-mae:2171.05810
[319]	validation_0-mae:2171.52284
[320]	validation_0-mae:2172.00629
[321]	validation_0-mae:2172.07185
[322]	validation_0-mae:2171.67031
[323]	validation_0-mae:2172.13386
[324]	validation_0-mae:2172.04048
[325]	validation_0-mae:2172.50289
[326]	validation_0-mae:2172.47471
[327]	validation_0-mae:2171.72172
[328]	validation_0-mae:2171.21285
[329]	validation_0-mae:2170.34966
[330]	validation_0-mae:2170.35060
[331]	validation_0-mae:2168.61224
[332]	validation_0-mae:2167.75035
[333]	validation_0-mae:2167.90257
[334]	validation_0-mae:2168.00859
[335]	validation_0-mae:2168.09954
[336]	validation_0-mae:2168.25284
[337]	validation_0-mae:2168.06549
[338]	validation_0-mae:2167.88941
[339]	validation_0-mae:2167.82964
[340]	validation_0-mae:2167.83762
[341]	validation_0-mae:2167.56993
[342]	validation_0-mae:2167.60311
[343]	validation_0-mae:2168.16529
[344]	validation_0-mae:2168.62885
[345]	validation_0-mae:2167.49489
[346]	validation_0-mae:2165.32565
[347]	validation_0-mae:2165.71029
[348]	validation_0-mae:2165.80357
[349]	validation_0-mae:2165.87745
[350]	validation_0-mae:2165.80728
[351]	validation_0-mae:2166.21148
[352]	validation_0-mae:2166.41970
[353]	validation_0-mae:2164.21564
[354]	validation_0-mae:2163.83007
[355]	validation_0-mae:2163.95945
[356]	validation_0-mae:2163.16805
[357]	validation_0-mae:2162.30554
[358]	validation_0-mae:2161.75945
[359]	validation_0-mae:2160.93490
[360]	validation_0-mae:2161.66985
[361]	validation_0-mae:2161.33388
[362]	validation_0-mae:2160.11354
[363]	validation_0-mae:2159.88363
[364]	validation_0-mae:2159.76501
[365]	validation_0-mae:2159.76986
[366]	validation_0-mae:2159.83272
[367]	validation_0-mae:2159.94115
[368]	validation_0-mae:2159.94509
[369]	validation_0-mae:2159.97202
[370]	validation_0-mae:2160.03769
[371]	validation_0-mae:2159.38756
[372]	validation_0-mae:2159.45216
[373]	validation_0-mae:2159.27396
[374]	validation_0-mae:2159.20167
[375]	validation_0-mae:2158.32118
[376]	validation_0-mae:2158.85012
[377]	validation_0-mae:2157.59456
[378]	validation_0-mae:2157.79909
[379]	validation_0-mae:2158.03491
[380]	validation_0-mae:2158.02952
[381]	validation_0-mae:2157.69206
[382]	validation_0-mae:2156.79070
[383]	validation_0-mae:2156.64436
[384]	validation_0-mae:2156.78552
[385]	validation_0-mae:2156.78660
[386]	validation_0-mae:2156.70576
[387]	validation_0-mae:2156.99795
[388]	validation_0-mae:2156.57176
[389]	validation_0-mae:2156.76083
[390]	validation_0-mae:2155.49335
[391]	validation_0-mae:2154.37912
[392]	validation_0-mae:2155.14918
[393]	validation_0-mae:2153.30173
[394]	validation_0-mae:2153.85251
[395]	validation_0-mae:2153.45901
[396]	validation_0-mae:2153.32505
[397]	validation_0-mae:2153.34521
[398]	validation_0-mae:2153.36844
[399]	validation_0-mae:2152.67516
[400]	validation_0-mae:2152.43691
[401]	validation_0-mae:2151.10071
[402]	validation_0-mae:2150.95898
[403]	validation_0-mae:2150.89807
[404]	validation_0-mae:2150.43871
[405]	validation_0-mae:2150.54086
[406]	validation_0-mae:2150.85922
[407]	validation_0-mae:2150.72038
[408]	validation_0-mae:2150.41212
[409]	validation_0-mae:2149.69578
[410]	validation_0-mae:2149.88843
[411]	validation_0-mae:2149.92626
[412]	validation_0-mae:2149.85336
[413]	validation_0-mae:2149.31265
[414]	validation_0-mae:2149.63581
[415]	validation_0-mae:2150.04222
[416]	validation_0-mae:2150.06392
[417]	validation_0-mae:2150.31360
[418]	validation_0-mae:2150.06520
[419]	validation_0-mae:2150.22500
[420]	validation_0-mae:2149.86439
[421]	validation_0-mae:2149.77778
[422]	validation_0-mae:2148.50018
[423]	validation_0-mae:2148.26991
[424]	validation_0-mae:2148.34446
[425]	validation_0-mae:2146.52491
[426]	validation_0-mae:2146.54903
[427]	validation_0-mae:2146.41410
[428]	validation_0-mae:2146.57978
[429]	validation_0-mae:2146.33510
[430]	validation_0-mae:2146.21898
[431]	validation_0-mae:2146.72047
[432]	validation_0-mae:2147.23630
[433]	validation_0-mae:2146.62163
[434]	validation_0-mae:2146.79130
[435]	validation_0-mae:2145.16672
[436]	validation_0-mae:2144.93713
[437]	validation_0-mae:2145.40652
[438]	validation_0-mae:2145.47339
[439]	validation_0-mae:2145.74103
[440]	validation_0-mae:2145.82839
[441]	validation_0-mae:2145.91069
[442]	validation_0-mae:2145.62628
[443]	validation_0-mae:2144.93062
[444]	validation_0-mae:2145.22836
[445]	validation_0-mae:2145.18620
[446]	validation_0-mae:2144.29562
[447]	validation_0-mae:2144.47326
[448]	validation_0-mae:2144.34193
[449]	validation_0-mae:2144.44433
[450]	validation_0-mae:2144.17235
[451]	validation_0-mae:2144.44789
[452]	validation_0-mae:2144.65831
[453]	validation_0-mae:2144.65799
[454]	validation_0-mae:2144.74955
[455]	validation_0-mae:2144.94837
[456]	validation_0-mae:2144.63242
[457]	validation_0-mae:2144.19733
[458]	validation_0-mae:2144.06522
[459]	validation_0-mae:2142.99702
[460]	validation_0-mae:2143.14648
[461]	validation_0-mae:2142.06300
[462]	validation_0-mae:2141.49331
[463]	validation_0-mae:2141.54848
[464]	validation_0-mae:2141.84282
[465]	validation_0-mae:2139.96431
[466]	validation_0-mae:2139.48267
[467]	validation_0-mae:2139.71745
[468]	validation_0-mae:2139.92710
[469]	validation_0-mae:2139.86856
[470]	validation_0-mae:2140.31864
[471]	validation_0-mae:2140.22078
[472]	validation_0-mae:2140.72615
[473]	validation_0-mae:2140.68529
[474]	validation_0-mae:2140.59461
[475]	validation_0-mae:2139.27893
[476]	validation_0-mae:2139.53364
[477]	validation_0-mae:2139.62596
[478]	validation_0-mae:2139.38364
[479]	validation_0-mae:2139.65426
[480]	validation_0-mae:2139.71398
[481]	validation_0-mae:2139.62259
[482]	validation_0-mae:2139.52507
[483]	validation_0-mae:2139.39086
[484]	validation_0-mae:2139.09333
[485]	validation_0-mae:2139.08983
[486]	validation_0-mae:2139.06359
[487]	validation_0-mae:2138.66837
[488]	validation_0-mae:2138.24181
[489]	validation_0-mae:2138.65448
[490]	validation_0-mae:2138.41491
[491]	validation_0-mae:2137.82586
[492]	validation_0-mae:2137.39349
[493]	validation_0-mae:2137.06234
[494]	validation_0-mae:2136.57932
[495]	validation_0-mae:2136.65248
[496]	validation_0-mae:2136.44995
[497]	validation_0-mae:2136.14422
[498]	validation_0-mae:2136.30399
[499]	validation_0-mae:2136.29649
[500]	validation_0-mae:2135.89010
[501]	validation_0-mae:2134.75662
[502]	validation_0-mae:2133.90088
[503]	validation_0-mae:2134.02575
[504]	validation_0-mae:2134.23565
[505]	validation_0-mae:2134.35484
[506]	validation_0-mae:2134.32975
[507]	validation_0-mae:2132.99159
[508]	validation_0-mae:2133.03585
[509]	validation_0-mae:2132.79199
[510]	validation_0-mae:2132.92077
[511]	validation_0-mae:2132.84616
[512]	validation_0-mae:2132.55212
[513]	validation_0-mae:2132.47084
[514]	validation_0-mae:2131.75207
[515]	validation_0-mae:2131.28280
[516]	validation_0-mae:2131.56972
[517]	validation_0-mae:2131.57609
[518]	validation_0-mae:2131.59733
[519]	validation_0-mae:2130.51520
[520]	validation_0-mae:2129.79405
[521]	validation_0-mae:2130.13153
[522]	validation_0-mae:2129.53760
[523]	validation_0-mae:2129.07831
[524]	validation_0-mae:2128.49311
[525]	validation_0-mae:2127.67948
[526]	validation_0-mae:2126.91982
[527]	validation_0-mae:2126.87843
[528]	validation_0-mae:2126.80545
[529]	validation_0-mae:2126.69520
[530]	validation_0-mae:2126.55999
[531]	validation_0-mae:2126.40565
[532]	validation_0-mae:2125.63442
[533]	validation_0-mae:2125.82356
[534]	validation_0-mae:2125.63715
[535]	validation_0-mae:2125.56943
[536]	validation_0-mae:2125.07154
[537]	validation_0-mae:2125.21709
[538]	validation_0-mae:2124.12471
[539]	validation_0-mae:2123.45917
[540]	validation_0-mae:2123.48720
[541]	validation_0-mae:2123.18764
[542]	validation_0-mae:2123.02168
[543]	validation_0-mae:2123.30178
[544]	validation_0-mae:2123.51712
[545]	validation_0-mae:2122.86493
[546]	validation_0-mae:2123.16903
[547]	validation_0-mae:2122.85604
[548]	validation_0-mae:2122.64511
[549]	validation_0-mae:2122.70158
[550]	validation_0-mae:2123.10026
[551]	validation_0-mae:2122.46219
[552]	validation_0-mae:2122.46548
[553]	validation_0-mae:2122.59799
[554]	validation_0-mae:2122.93626
[555]	validation_0-mae:2122.55690
[556]	validation_0-mae:2122.74197
[557]	validation_0-mae:2122.85128
[558]	validation_0-mae:2122.86135
[559]	validation_0-mae:2122.63396
[560]	validation_0-mae:2122.83385
[561]	validation_0-mae:2123.42138
[562]	validation_0-mae:2123.49102
[563]	validation_0-mae:2123.30628
[564]	validation_0-mae:2123.27488
[565]	validation_0-mae:2123.57102
[566]	validation_0-mae:2123.60425
[567]	validation_0-mae:2123.42023
[568]	validation_0-mae:2123.83879
[569]	validation_0-mae:2123.82830
[570]	validation_0-mae:2124.26889
[571]	validation_0-mae:2124.16053
[572]	validation_0-mae:2123.73548
[573]	validation_0-mae:2124.04235
[574]	validation_0-mae:2123.68839
[575]	validation_0-mae:2123.45149
[576]	validation_0-mae:2123.37107
[577]	validation_0-mae:2122.81909
[578]	validation_0-mae:2122.86810
[579]	validation_0-mae:2122.98894
[580]	validation_0-mae:2123.09536
[581]	validation_0-mae:2123.18449
[582]	validation_0-mae:2123.08344
[583]	validation_0-mae:2123.20351
[584]	validation_0-mae:2123.24568
[585]	validation_0-mae:2122.79292
[586]	validation_0-mae:2122.86075
[587]	validation_0-mae:2122.92231
[588]	validation_0-mae:2122.17029
[589]	validation_0-mae:2122.28385
[590]	validation_0-mae:2122.02662
[591]	validation_0-mae:2121.99154
[592]	validation_0-mae:2122.23306
[593]	validation_0-mae:2122.27864
[594]	validation_0-mae:2122.58353
[595]	validation_0-mae:2122.69679
[596]	validation_0-mae:2122.68956
[597]	validation_0-mae:2122.66444
[598]	validation_0-mae:2122.55153
[599]	validation_0-mae:2121.90271
[600]	validation_0-mae:2121.87073
[601]	validation_0-mae:2121.87424
[602]	validation_0-mae:2122.04761
[603]	validation_0-mae:2122.22004
[604]	validation_0-mae:2121.46966
[605]	validation_0-mae:2121.33315
[606]	validation_0-mae:2121.48901
[607]	validation_0-mae:2121.38770
[608]	validation_0-mae:2121.24535
[609]	validation_0-mae:2121.18840
[610]	validation_0-mae:2120.56870
[611]	validation_0-mae:2120.88297
[612]	validation_0-mae:2120.58328
[613]	validation_0-mae:2120.71056
[614]	validation_0-mae:2120.58816
[615]	validation_0-mae:2120.01402
[616]	validation_0-mae:2119.90805
[617]	validation_0-mae:2120.13204
[618]	validation_0-mae:2120.14470
[619]	validation_0-mae:2119.85863
[620]	validation_0-mae:2120.09930
[621]	validation_0-mae:2120.24663
[622]	validation_0-mae:2120.42756
[623]	validation_0-mae:2120.43264
[624]	validation_0-mae:2120.31385
[625]	validation_0-mae:2120.39033
[626]	validation_0-mae:2120.31496
[627]	validation_0-mae:2120.38087
[628]	validation_0-mae:2119.91869
[629]	validation_0-mae:2120.11078

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[48]	validation_0-mae:3503.76299
[49]	validation_0-mae:3470.13633
[50]	validation_0-mae:3433.22111
[51]	validation_0-mae:3400.27228
[52]	validation_0-mae:3369.77052
[53]	validation_0-mae:3332.33016
[54]	validation_0-mae:3307.73885
[55]	validation_0-mae:3281.30264
[56]	validation_0-mae:3262.17006
[57]	validation_0-mae:3235.00500
[58]	validation_0-mae:3196.91923
[59]	validation_0-mae:3178.24537
[60]	validation_0-mae:3161.06438
[61]	validation_0-mae:3138.62618
[62]	validation_0-mae:3119.86669
[63]	validation_0-mae:3090.46887
[64]	validation_0-mae:3068.16809
[65]	validation_0-mae:3052.13661
[66]	validation_0-mae:3040.65216
[67]	validation_0-mae:3016.92901
[68]	validation_0-mae:3001.20485
[69]	validation_0-mae:2981.90016
[70]	validation_0-mae:2967.32706
[71]	validation_0-mae:2955.41291
[72]	validation_0-mae:2945.02510
[73]	validation_0-mae:2919.62225
[74]	validation_0-mae:2909.44169
[75]	validation_0-mae:2900.00977
[76]	validation_0-mae:2891.42291
[77]	validation_0-mae:2870.04206
[78]	validation_0-mae:2860.31122
[79]	validation_0-mae:2847.46298
[80]	validation_0-mae:2837.89226
[81]	validation_0-mae:2830.38733
[82]	validation_0-mae:2814.00053
[83]	validation_0-mae:2797.14435
[84]	validation_0-mae:2787.35275
[85]	validation_0-mae:2778.32414
[86]	validation_0-mae:2759.17278
[87]	validation_0-mae:2738.57550
[88]	validation_0-mae:2728.96489
[89]	validation_0-mae:2721.84301
[90]	validation_0-mae:2712.32431
[91]	validation_0-mae:2704.21739
[92]	validation_0-mae:2690.45550
[93]	validation_0-mae:2683.16334
[94]	validation_0-mae:2676.99289
[95]	validation_0-mae:2664.33944
[96]	validation_0-mae:2656.06725
[97]	validation_0-mae:2648.35743
[98]	validation_0-mae:2637.73209
[99]	validation_0-mae:2632.22671
[100]	validation_0-mae:2629.96776
[101]	validation_0-mae:2626.27697
[102]	validation_0-mae:2620.85362
[103]	validation_0-mae:2605.92996
[104]	validation_0-mae:2597.35757
[105]	validation_0-mae:2585.95885
[106]	validation_0-mae:2582.96558
[107]	validation_0-mae:2576.17464
[108]	validation_0-mae:2565.40047
[109]	validation_0-mae:2559.32270
[110]	validation_0-mae:2551.02984
[111]	validation_0-mae:2540.89908
[112]	validation_0-mae:2534.05442
[113]	validation_0-mae:2525.15476
[114]	validation_0-mae:2520.87578
[115]	validation_0-mae:2516.47621
[116]	validation_0-mae:2502.93808
[117]	validation_0-mae:2497.27993
[118]	validation_0-mae:2493.78942
[119]	validation_0-mae:2487.03659
[120]	validation_0-mae:2481.80777
[121]	validation_0-mae:2476.76380
[122]	validation_0-mae:2468.93968
[123]	validation_0-mae:2464.76164
[124]	validation_0-mae:2456.51008
[125]	validation_0-mae:2451.53779
[126]	validation_0-mae:2444.81699
[127]	validation_0-mae:2441.93033
[128]	validation_0-mae:2435.30178
[129]	validation_0-mae:2432.08118
[130]	validation_0-mae:2428.67147
[131]	validation_0-mae:2424.44827
[132]	validation_0-mae:2421.83587
[133]	validation_0-mae:2418.41152
[134]	validation_0-mae:2414.31748
[135]	validation_0-mae:2411.36217
[136]	validation_0-mae:2408.86303
[137]	validation_0-mae:2404.06539
[138]	validation_0-mae:2398.74480
[139]	validation_0-mae:2396.70942
[140]	validation_0-mae:2392.28043
[141]	validation_0-mae:2388.62672
[142]	validation_0-mae:2385.18566
[143]	validation_0-mae:2378.70313
[144]	validation_0-mae:2375.80824
[145]	validation_0-mae:2372.51883
[146]	validation_0-mae:2369.75935
[147]	validation_0-mae:2367.73567
[148]	validation_0-mae:2365.71884
[149]	validation_0-mae:2364.96704
[150]	validation_0-mae:2359.86769
[151]	validation_0-mae:2356.38329
[152]	validation_0-mae:2349.06609
[153]	validation_0-mae:2345.45295
[154]	validation_0-mae:2341.42914
[155]	validation_0-mae:2336.46461
[156]	validation_0-mae:2333.14597
[157]	validation_0-mae:2330.15906
[158]	validation_0-mae:2324.38663
[159]	validation_0-mae:2320.82853
[160]	validation_0-mae:2317.52511
[161]	validation_0-mae:2315.56007
[162]	validation_0-mae:2313.70979
[163]	validation_0-mae:2307.53613
[164]	validation_0-mae:2304.96421
[165]	validation_0-mae:2302.87691
[166]	validation_0-mae:2300.71554
[167]	validation_0-mae:2299.09896
[168]	validation_0-mae:2298.07609
[169]	validation_0-mae:2295.27266
[170]	validation_0-mae:2293.41431
[171]	validation_0-mae:2291.92535
[172]	validation_0-mae:2289.99421
[173]	validation_0-mae:2288.49667
[174]	validation_0-mae:2285.69680
[175]	validation_0-mae:2282.35222
[176]	validation_0-mae:2280.40850
[177]	validation_0-mae:2278.13331
[178]	validation_0-mae:2276.42351
[179]	validation_0-mae:2275.33585
[180]	validation_0-mae:2272.14230
[181]	validation_0-mae:2267.74875
[182]	validation_0-mae:2265.42243
[183]	validation_0-mae:2263.42978
[184]	validation_0-mae:2262.34668
[185]	validation_0-mae:2261.20052
[186]	validation_0-mae:2259.13528
[187]	validation_0-mae:2255.92248
[188]	validation_0-mae:2253.11201
[189]	validation_0-mae:2251.86192
[190]	validation_0-mae:2246.53080
[191]	validation_0-mae:2245.65425
[192]	validation_0-mae:2243.79920
[193]	validation_0-mae:2244.24258
[194]	validation_0-mae:2243.10700
[195]	validation_0-mae:2240.85351
[196]	validation_0-mae:2238.34993
[197]	validation_0-mae:2237.64471
[198]	validation_0-mae:2237.14395
[199]	validation_0-mae:2235.72986
[200]	validation_0-mae:2234.86142
[201]	validation_0-mae:2234.37152
[202]	validation_0-mae:2232.77114
[203]	validation_0-mae:2229.60731
[204]	validation_0-mae:2226.92301
[205]	validation_0-mae:2226.69740
[206]	validation_0-mae:2227.68856
[207]	validation_0-mae:2227.67082
[208]	validation_0-mae:2225.71059
[209]	validation_0-mae:2224.07860
[210]	validation_0-mae:2223.35299
[211]	validation_0-mae:2223.10234
[212]	validation_0-mae:2222.04766
[213]	validation_0-mae:2220.29694
[214]	validation_0-mae:2220.52558
[215]	validation_0-mae:2218.39257
[216]	validation_0-mae:2216.53419
[217]	validation_0-mae:2216.34861
[218]	validation_0-mae:2216.10545
[219]	validation_0-mae:2213.98609
[220]	validation_0-mae:2213.13357
[221]	validation_0-mae:2214.04179
[222]	validation_0-mae:2214.65713
[223]	validation_0-mae:2214.22775
[224]	validation_0-mae:2214.42180
[225]	validation_0-mae:2214.13740
[226]	validation_0-mae:2214.55623
[227]	validation_0-mae:2213.31947
[228]	validation_0-mae:2210.84644
[229]	validation_0-mae:2211.63301
[230]	validation_0-mae:2211.34275
[231]	validation_0-mae:2211.64190
[232]	validation_0-mae:2211.33986
[233]	validation_0-mae:2211.22415
[234]	validation_0-mae:2210.74571
[235]	validation_0-mae:2211.03182
[236]	validation_0-mae:2210.67646
[237]	validation_0-mae:2210.31352
[238]	validation_0-mae:2209.01351
[239]	validation_0-mae:2209.30858
[240]	validation_0-mae:2208.64446
[241]	validation_0-mae:2207.29539
[242]	validation_0-mae:2206.98145
[243]	validation_0-mae:2205.32798
[244]	validation_0-mae:2203.66308
[245]	validation_0-mae:2200.93065
[246]	validation_0-mae:2198.86370
[247]	validation_0-mae:2196.98102
[248]	validation_0-mae:2195.90603
[249]	validation_0-mae:2194.52217
[250]	validation_0-mae:2193.74373
[251]	validation_0-mae:2191.24179
[252]	validation_0-mae:2191.41438
[253]	validation_0-mae:2188.69643
[254]	validation_0-mae:2187.93247
[255]	validation_0-mae:2188.04198
[256]	validation_0-mae:2187.49571
[257]	validation_0-mae:2186.39427
[258]	validation_0-mae:2186.59298
[259]	validation_0-mae:2185.60650
[260]	validation_0-mae:2186.05237
[261]	validation_0-mae:2185.93489
[262]	validation_0-mae:2184.87556
[263]	validation_0-mae:2183.43798
[264]	validation_0-mae:2183.83019
[265]	validation_0-mae:2183.17824
[266]	validation_0-mae:2183.34129
[267]	validation_0-mae:2182.85051
[268]	validation_0-mae:2182.20309
[269]	validation_0-mae:2180.60419
[270]	validation_0-mae:2180.12034
[271]	validation_0-mae:2180.18189
[272]	validation_0-mae:2177.66091
[273]	validation_0-mae:2177.11918
[274]	validation_0-mae:2175.55145
[275]	validation_0-mae:2173.25861
[276]	validation_0-mae:2173.62917
[277]	validation_0-mae:2174.08832
[278]	validation_0-mae:2174.09867
[279]	validation_0-mae:2174.22656
[280]	validation_0-mae:2174.35938
[281]	validation_0-mae:2170.81341
[282]	validation_0-mae:2169.18374
[283]	validation_0-mae:2167.03567
[284]	validation_0-mae:2166.52859
[285]	validation_0-mae:2166.51158
[286]	validation_0-mae:2165.56842
[287]	validation_0-mae:2163.35989
[288]	validation_0-mae:2161.12440
[289]	validation_0-mae:2158.70986
[290]	validation_0-mae:2159.29549
[291]	validation_0-mae:2159.09216
[292]	validation_0-mae:2158.24056
[293]	validation_0-mae:2157.41445
[294]	validation_0-mae:2157.25026
[295]	validation_0-mae:2157.93115
[296]	validation_0-mae:2157.55176
[297]	validation_0-mae:2157.81564
[298]	validation_0-mae:2156.53248
[299]	validation_0-mae:2154.83375
[300]	validation_0-mae:2155.06198
[301]	validation_0-mae:2154.38961
[302]	validation_0-mae:2154.06273
[303]	validation_0-mae:2153.20848
[304]	validation_0-mae:2153.35133
[305]	validation_0-mae:2152.58805
[306]	validation_0-mae:2152.85703
[307]	validation_0-mae:2151.21688
[308]	validation_0-mae:2150.31570
[309]	validation_0-mae:2149.84990
[310]	validation_0-mae:2148.09756
[311]	validation_0-mae:2148.16672
[312]	validation_0-mae:2148.18532
[313]	validation_0-mae:2147.96863
[314]	validation_0-mae:2146.56876
[315]	validation_0-mae:2145.45286
[316]	validation_0-mae:2145.26897
[317]	validation_0-mae:2144.82942
[318]	validation_0-mae:2145.46038
[319]	validation_0-mae:2145.47313
[320]	validation_0-mae:2145.94251
[321]	validation_0-mae:2143.81459
[322]	validation_0-mae:2142.28847
[323]	validation_0-mae:2140.52235
[324]	validation_0-mae:2140.42912
[325]	validation_0-mae:2140.68206
[326]	validation_0-mae:2140.25648
[327]	validation_0-mae:2139.65005
[328]	validation_0-mae:2139.47825
[329]	validation_0-mae:2139.88651
[330]	validation_0-mae:2138.85026
[331]	validation_0-mae:2138.87646
[332]	validation_0-mae:2138.58289
[333]	validation_0-mae:2139.06599
[334]	validation_0-mae:2139.06077
[335]	validation_0-mae:2138.97697
[336]	validation_0-mae:2139.21013
[337]	validation_0-mae:2139.30396
[338]	validation_0-mae:2139.03701
[339]	validation_0-mae:2138.23153
[340]	validation_0-mae:2138.36512
[341]	validation_0-mae:2138.42609
[342]	validation_0-mae:2138.67536
[343]	validation_0-mae:2138.95761
[344]	validation_0-mae:2139.40905
[345]	validation_0-mae:2139.32972
[346]	validation_0-mae:2139.64219
[347]	validation_0-mae:2139.82048
[348]	validation_0-mae:2139.23279
[349]	validation_0-mae:2139.33934
[350]	validation_0-mae:2139.37604
[351]	validation_0-mae:2138.97878
[352]	validation_0-mae:2138.58656
[353]	validation_0-mae:2138.89293
[354]	validation_0-mae:2138.20085
[355]	validation_0-mae:2137.47198
[356]	validation_0-mae:2137.56610
[357]	validation_0-mae:2137.95262
[358]	validation_0-mae:2137.56268
[359]	validation_0-mae:2137.73959
[360]	validation_0-mae:2137.58590
[361]	validation_0-mae:2137.22688
[362]	validation_0-mae:2137.29992
[363]	validation_0-mae:2137.32943
[364]	validation_0-mae:2138.12733
[365]	validation_0-mae:2137.71787
[366]	validation_0-mae:2137.76184
[367]	validation_0-mae:2137.65927
[368]	validation_0-mae:2137.98071
[369]	validation_0-mae:2137.82104
[370]	validation_0-mae:2137.86061
[371]	validation_0-mae:2137.77681
[372]	validation_0-mae:2138.05567
[373]	validation_0-mae:2137.93522
[374]	validation_0-mae:2138.50755
[375]	validation_0-mae:2138.43924
[376]	validation_0-mae:2138.21071
[377]	validation_0-mae:2138.28662
[378]	validation_0-mae:2138.31302
[379]	validation_0-mae:2138.17555
[380]	validation_0-mae:2136.98128
[381]	validation_0-mae:2136.73866
[382]	validation_0-mae:2136.91699
[383]	validation_0-mae:2136.96447
[384]	validation_0-mae:2135.86475
[385]	validation_0-mae:2136.07695
[386]	validation_0-mae:2135.14161
[387]	validation_0-mae:2134.28700
[388]	validation_0-mae:2134.06971
[389]	validation_0-mae:2133.06936
[390]	validation_0-mae:2133.06746
[391]	validation_0-mae:2133.36211
[392]	validation_0-mae:2133.31282
[393]	validation_0-mae:2133.50407
[394]	validation_0-mae:2133.62906
[395]	validation_0-mae:2133.22535
[396]	validation_0-mae:2132.94216
[397]	validation_0-mae:2132.15136
[398]	validation_0-mae:2132.09280
[399]	validation_0-mae:2131.98659
[400]	validation_0-mae:2132.10350
[401]	validation_0-mae:2132.43502
[402]	validation_0-mae:2132.44417
[403]	validation_0-mae:2132.44970
[404]	validation_0-mae:2132.47622
[405]	validation_0-mae:2132.81643
[406]	validation_0-mae:2133.29121
[407]	validation_0-mae:2130.67305
[408]	validation_0-mae:2131.58937
[409]	validation_0-mae:2131.55921
[410]	validation_0-mae:2130.77107
[411]	validation_0-mae:2130.02531
[412]	validation_0-mae:2129.87950
[413]	validation_0-mae:2129.55391
[414]	validation_0-mae:2130.31825
[415]	validation_0-mae:2129.66501
[416]	validation_0-mae:2129.99329
[417]	validation_0-mae:2128.99834
[418]	validation_0-mae:2129.10048
[419]	validation_0-mae:2128.60686
[420]	validation_0-mae:2127.86835
[421]	validation_0-mae:2127.39419
[422]	validation_0-mae:2126.36349
[423]	validation_0-mae:2126.07357
[424]	validation_0-mae:2125.23568
[425]	validation_0-mae:2125.26537
[426]	validation_0-mae:2125.19111
[427]	validation_0-mae:2125.27180
[428]	validation_0-mae:2125.08195
[429]	validation_0-mae:2125.21254
[430]	validation_0-mae:2125.64632
[431]	validation_0-mae:2125.06784
[432]	validation_0-mae:2125.08638
[433]	validation_0-mae:2124.71045
[434]	validation_0-mae:2124.42961
[435]	validation_0-mae:2124.53398
[436]	validation_0-mae:2124.06649
[437]	validation_0-mae:2123.89579
[438]	validation_0-mae:2123.72699
[439]	validation_0-mae:2122.80083
[440]	validation_0-mae:2123.06703
[441]	validation_0-mae:2123.09752
[442]	validation_0-mae:2123.10666
[443]	validation_0-mae:2123.37365
[444]	validation_0-mae:2123.13141
[445]	validation_0-mae:2122.63955
[446]	validation_0-mae:2122.34773
[447]	validation_0-mae:2122.03737
[448]	validation_0-mae:2121.00354
[449]	validation_0-mae:2121.24968
[450]	validation_0-mae:2121.55313
[451]	validation_0-mae:2121.19793
[452]	validation_0-mae:2120.87122
[453]	validation_0-mae:2120.56352
[454]	validation_0-mae:2120.11708
[455]	validation_0-mae:2119.92446
[456]	validation_0-mae:2118.82402
[457]	validation_0-mae:2118.23471
[458]	validation_0-mae:2118.31812
[459]	validation_0-mae:2117.96876
[460]	validation_0-mae:2118.14245
[461]	validation_0-mae:2117.49527
[462]	validation_0-mae:2117.28089
[463]	validation_0-mae:2116.66330
[464]	validation_0-mae:2117.10853
[465]	validation_0-mae:2116.16094
[466]	validation_0-mae:2115.30438
[467]	validation_0-mae:2115.27546
[468]	validation_0-mae:2114.74159
[469]	validation_0-mae:2114.12813
[470]	validation_0-mae:2114.42262
[471]	validation_0-mae:2114.42015
[472]	validation_0-mae:2113.95905
[473]	validation_0-mae:2114.09876
[474]	validation_0-mae:2111.97542
[475]	validation_0-mae:2111.50637
[476]	validation_0-mae:2111.74824
[477]	validation_0-mae:2111.54502
[478]	validation_0-mae:2111.59427
[479]	validation_0-mae:2111.61645
[480]	validation_0-mae:2111.90159
[481]	validation_0-mae:2111.67633
[482]	validation_0-mae:2110.49283
[483]	validation_0-mae:2110.76767
[484]	validation_0-mae:2109.67440
[485]	validation_0-mae:2109.22401
[486]	validation_0-mae:2108.80519
[487]	validation_0-mae:2107.78476
[488]	validation_0-mae:2107.52609
[489]	validation_0-mae:2107.50023
[490]	validation_0-mae:2107.58294
[491]	validation_0-mae:2108.36639
[492]	validation_0-mae:2108.19373
[493]	validation_0-mae:2106.77513
[494]	validation_0-mae:2107.22467
[495]	validation_0-mae:2107.18894
[496]	validation_0-mae:2106.26914
[497]	validation_0-mae:2106.57148
[498]	validation_0-mae:2106.24135
[499]	validation_0-mae:2105.91853
[500]	validation_0-mae:2105.79965
[501]	validation_0-mae:2106.32259
[502]	validation_0-mae:2106.23019
[503]	validation_0-mae:2105.94030
[504]	validation_0-mae:2106.06264
[505]	validation_0-mae:2105.86445
[506]	validation_0-mae:2104.16138
[507]	validation_0-mae:2104.17267
[508]	validation_0-mae:2104.14844
[509]	validation_0-mae:2104.60769
[510]	validation_0-mae:2104.90253
[511]	validation_0-mae:2104.77953
[512]	validation_0-mae:2104.52322
[513]	validation_0-mae:2104.47277
[514]	validation_0-mae:2104.44706
[515]	validation_0-mae:2104.72692
[516]	validation_0-mae:2104.60705
[517]	validation_0-mae:2104.73263
[518]	validation_0-mae:2103.26962
[519]	validation_0-mae:2103.34069
[520]	validation_0-mae:2103.21327
[521]	validation_0-mae:2103.17971
[522]	validation_0-mae:2103.63331
[523]	validation_0-mae:2103.24680
[524]	validation_0-mae:2102.43001
[525]	validation_0-mae:2102.29093
[526]	validation_0-mae:2101.28719
[527]	validation_0-mae:2101.32402
[528]	validation_0-mae:2101.49365
[529]	validation_0-mae:2101.53023
[530]	validation_0-mae:2101.58994
[531]	validation_0-mae:2101.81049
[532]	validation_0-mae:2102.07423
[533]	validation_0-mae:2101.77322
[534]	validation_0-mae:2102.17391
[535]	validation_0-mae:2099.66093
[536]	validation_0-mae:2099.29260
[537]	validation_0-mae:2099.47395
[538]	validation_0-mae:2099.32489
[539]	validation_0-mae:2098.48761
[540]	validation_0-mae:2098.48471
[541]	validation_0-mae:2098.81850
[542]	validation_0-mae:2098.45454
[543]	validation_0-mae:2098.09825
[544]	validation_0-mae:2097.97519
[545]	validation_0-mae:2097.72104
[546]	validation_0-mae:2097.15455
[547]	validation_0-mae:2096.58642
[548]	validation_0-mae:2096.15704
[549]	validation_0-mae:2096.47822
[550]	validation_0-mae:2096.19234
[551]	validation_0-mae:2095.74551
[552]	validation_0-mae:2094.83160
[553]	validation_0-mae:2094.64803
[554]	validation_0-mae:2093.98026
[555]	validation_0-mae:2093.41253
[556]	validation_0-mae:2093.02594
[557]	validation_0-mae:2093.16880
[558]	validation_0-mae:2092.31865
[559]	validation_0-mae:2092.40835
[560]	validation_0-mae:2091.25378
[561]	validation_0-mae:2091.43657
[562]	validation_0-mae:2091.48559
[563]	validation_0-mae:2090.92472
[564]	validation_0-mae:2090.82985
[565]	validation_0-mae:2090.55152
[566]	validation_0-mae:2090.45946
[567]	validation_0-mae:2090.14029
[568]	validation_0-mae:2090.25376
[569]	validation_0-mae:2090.35428
[570]	validation_0-mae:2090.43057
[571]	validation_0-mae:2091.00558
[572]	validation_0-mae:2091.09980
[573]	validation_0-mae:2090.16528
[574]	validation_0-mae:2090.19545
[575]	validation_0-mae:2089.02045
[576]	validation_0-mae:2088.78502
[577]	validation_0-mae:2087.55733
[578]	validation_0-mae:2085.75855
[579]	validation_0-mae:2086.07452
[580]	validation_0-mae:2085.06275
[581]	validation_0-mae:2084.91894
[582]	validation_0-mae:2084.96958
[583]	validation_0-mae:2084.65318
[584]	validation_0-mae:2083.11067
[585]	validation_0-mae:2082.86434
[586]	validation_0-mae:2082.38431
[587]	validation_0-mae:2082.96597
[588]	validation_0-mae:2082.89171
[589]	validation_0-mae:2082.31104
[590]	validation_0-mae:2082.53859
[591]	validation_0-mae:2082.21969
[592]	validation_0-mae:2081.68890
[593]	validation_0-mae:2081.59536
[594]	validation_0-mae:2081.24728
[595]	validation_0-mae:2081.04288
[596]	validation_0-mae:2080.70380
[597]	validation_0-mae:2080.73069
[598]	validation_0-mae:2080.44728
[599]	validation_0-mae:2080.44455
[600]	validation_0-mae:2079.76259
[601]	validation_0-mae:2079.53587
[602]	validation_0-mae:2078.60535
[603]	validation_0-mae:2078.35124
[604]	validation_0-mae:2078.01416
[605]	validation_0-mae:2078.12237
[606]	validation_0-mae:2078.53077
[607]	validation_0-mae:2078.47462
[608]	validation_0-mae:2078.50507
[609]	validation_0-mae:2078.48317
[610]	validation_0-mae:2078.49466
[611]	validation_0-mae:2078.72769
[612]	validation_0-mae:2079.24148
[613]	validation_0-mae:2079.52835
[614]	validation_0-mae:2079.43166
[615]	validation_0-mae:2079.29607
[616]	validation_0-mae:2079.57324
[617]	validation_0-mae:2079.24856
[618]	validation_0-mae:2079.35986
[619]	validation_0-mae:2079.52692
[620]	validation_0-mae:2079.56061
[621]	validation_0-mae:2078.47667
[622]	validation_0-mae:2077.67906
[623]	validation_0-mae:2077.91739
[624]	validation_0-mae:2077.81624
[625]	validation_0-mae:2078.12453
[626]	validation_0-mae:2078.46614
[627]	validation_0-mae:2078.31840
[628]	validation_0-mae:2078.71858
[629]	validation_0-mae:2079.13548
[630]	validation_0-mae:2078.53288
[631]	validation_0-mae:2078.15989
[632]	validation_0-mae:2077.68260
[633]	validation_0-mae:2077.10597
[634]	validation_0-mae:2077.50955
[635]	validation_0-mae:2077.13055
[636]	validation_0-mae:2077.11024

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[56]	validation_0-mae:3184.78510
[57]	validation_0-mae:3151.91325
[58]	validation_0-mae:3104.44875
[59]	validation_0-mae:3081.77537
[60]	validation_0-mae:3066.06580
[61]	validation_0-mae:3048.31676
[62]	validation_0-mae:3038.01948
[63]	validation_0-mae:3009.83831
[64]	validation_0-mae:2994.61334
[65]	validation_0-mae:2970.55856
[66]	validation_0-mae:2950.29140
[67]	validation_0-mae:2929.61332
[68]	validation_0-mae:2913.88924
[69]	validation_0-mae:2901.08959
[70]	validation_0-mae:2884.88641
[71]	validation_0-mae:2871.63241
[72]	validation_0-mae:2857.85595
[73]	validation_0-mae:2845.43129
[74]	validation_0-mae:2834.36791
[75]	validation_0-mae:2823.86044
[76]	validation_0-mae:2800.57614
[77]	validation_0-mae:2792.35732
[78]	validation_0-mae:2780.42989
[79]	validation_0-mae:2762.86722
[80]	validation_0-mae:2757.12195
[81]	validation_0-mae:2740.28562
[82]	validation_0-mae:2732.60556
[83]	validation_0-mae:2726.24490
[84]	validation_0-mae:2719.53328
[85]	validation_0-mae:2710.78393
[86]	validation_0-mae:2703.01305
[87]	validation_0-mae:2691.45118
[88]	validation_0-mae:2678.82734
[89]	validation_0-mae:2671.01553
[90]	validation_0-mae:2662.77716
[91]	validation_0-mae:2651.23854
[92]	validation_0-mae:2642.75847
[93]	validation_0-mae:2634.10504
[94]	validation_0-mae:2617.75043
[95]	validation_0-mae:2608.53110
[96]	validation_0-mae:2600.66304
[97]	validation_0-mae:2593.45235
[98]	validation_0-mae:2588.52147
[99]	validation_0-mae:2575.14719
[100]	validation_0-mae:2570.84006
[101]	validation_0-mae:2562.53615
[102]	validation_0-mae:2557.44650
[103]	validation_0-mae:2544.73430
[104]	validation_0-mae:2540.53819
[105]	validation_0-mae:2531.43187
[106]	validation_0-mae:2523.12309
[107]	validation_0-mae:2515.50680
[108]	validation_0-mae:2506.83713
[109]	validation_0-mae:2501.43920
[110]	validation_0-mae:2496.20194
[111]	validation_0-mae:2491.54583
[112]	validation_0-mae:2485.12405
[113]	validation_0-mae:2478.93155
[114]	validation_0-mae:2473.22313
[115]	validation_0-mae:2470.45794
[116]	validation_0-mae:2463.89958
[117]	validation_0-mae:2460.02013
[118]	validation_0-mae:2455.46456
[119]	validation_0-mae:2450.25156
[120]	validation_0-mae:2445.01636
[121]	validation_0-mae:2440.70869
[122]	validation_0-mae:2436.52841
[123]	validation_0-mae:2431.75371
[124]	validation_0-mae:2430.86199
[125]	validation_0-mae:2426.16317
[126]	validation_0-mae:2421.60861
[127]	validation_0-mae:2417.80112
[128]	validation_0-mae:2412.77214
[129]	validation_0-mae:2410.59929
[130]	validation_0-mae:2406.53705
[131]	validation_0-mae:2405.42487
[132]	validation_0-mae:2400.24784
[133]	validation_0-mae:2397.71732
[134]	validation_0-mae:2395.63955
[135]	validation_0-mae:2389.40096
[136]	validation_0-mae:2384.71216
[137]	validation_0-mae:2382.50336
[138]	validation_0-mae:2377.05807
[139]	validation_0-mae:2375.24388
[140]	validation_0-mae:2371.80182
[141]	validation_0-mae:2368.75845
[142]	validation_0-mae:2367.17012
[143]	validation_0-mae:2366.09858
[144]	validation_0-mae:2362.64322
[145]	validation_0-mae:2359.41395
[146]	validation_0-mae:2354.37090
[147]	validation_0-mae:2347.31435
[148]	validation_0-mae:2346.46995
[149]	validation_0-mae:2344.17014
[150]	validation_0-mae:2342.87116
[151]	validation_0-mae:2342.81327
[152]	validation_0-mae:2342.83077
[153]	validation_0-mae:2339.47075
[154]	validation_0-mae:2336.29613
[155]	validation_0-mae:2332.71324
[156]	validation_0-mae:2330.73415
[157]	validation_0-mae:2331.32217
[158]	validation_0-mae:2328.69834
[159]	validation_0-mae:2321.87103
[160]	validation_0-mae:2319.40359
[161]	validation_0-mae:2318.50479
[162]	validation_0-mae:2317.19364
[163]	validation_0-mae:2315.16031
[164]	validation_0-mae:2313.17768
[165]	validation_0-mae:2312.45101
[166]	validation_0-mae:2309.49407
[167]	validation_0-mae:2304.97676
[168]	validation_0-mae:2303.49362
[169]	validation_0-mae:2299.84755
[170]	validation_0-mae:2300.28901
[171]	validation_0-mae:2296.28539
[172]	validation_0-mae:2294.44902
[173]	validation_0-mae:2294.87787
[174]	validation_0-mae:2294.62724
[175]	validation_0-mae:2295.58098
[176]	validation_0-mae:2292.58188
[177]	validation_0-mae:2290.90752
[178]	validation_0-mae:2289.91242
[179]	validation_0-mae:2287.99943
[180]	validation_0-mae:2288.01205
[181]	validation_0-mae:2288.63443
[182]	validation_0-mae:2288.54733
[183]	validation_0-mae:2288.07983
[184]	validation_0-mae:2288.92649
[185]	validation_0-mae:2284.36588
[186]	validation_0-mae:2279.96343
[187]	validation_0-mae:2274.87563
[188]	validation_0-mae:2273.87007
[189]	validation_0-mae:2271.78476
[190]	validation_0-mae:2272.18779
[191]	validation_0-mae:2269.26904
[192]	validation_0-mae:2267.60468
[193]	validation_0-mae:2265.69871
[194]	validation_0-mae:2265.07916
[195]	validation_0-mae:2265.16306
[196]	validation_0-mae:2262.69408
[197]	validation_0-mae:2261.26724
[198]	validation_0-mae:2260.44290
[199]	validation_0-mae:2256.78223
[200]	validation_0-mae:2256.37040
[201]	validation_0-mae:2256.69897
[202]	validation_0-mae:2256.19484
[203]	validation_0-mae:2255.74600
[204]	validation_0-mae:2254.59133
[205]	validation_0-mae:2252.46720
[206]	validation_0-mae:2251.33921
[207]	validation_0-mae:2249.08763
[208]	validation_0-mae:2248.91258
[209]	validation_0-mae:2249.18501
[210]	validation_0-mae:2247.98622
[211]	validation_0-mae:2248.22918
[212]	validation_0-mae:2246.38637
[213]	validation_0-mae:2245.33332
[214]	validation_0-mae:2244.74004
[215]	validation_0-mae:2244.78111
[216]	validation_0-mae:2244.00433
[217]	validation_0-mae:2244.10595
[218]	validation_0-mae:2242.48081
[219]	validation_0-mae:2241.99761
[220]	validation_0-mae:2241.35466
[221]	validation_0-mae:2241.23408
[222]	validation_0-mae:2240.09892
[223]	validation_0-mae:2241.27196
[224]	validation_0-mae:2238.25876
[225]	validation_0-mae:2236.57798
[226]	validation_0-mae:2237.96770
[227]	validation_0-mae:2237.43627
[228]	validation_0-mae:2238.06693
[229]	validation_0-mae:2236.54626
[230]	validation_0-mae:2235.65920
[231]	validation_0-mae:2235.17951
[232]	validation_0-mae:2233.84250
[233]	validation_0-mae:2234.24289
[234]	validation_0-mae:2235.00060
[235]	validation_0-mae:2234.22131
[236]	validation_0-mae:2231.91590
[237]	validation_0-mae:2231.50294
[238]	validation_0-mae:2232.32329
[239]	validation_0-mae:2228.93405
[240]	validation_0-mae:2229.02596
[241]	validation_0-mae:2229.68714
[242]	validation_0-mae:2227.32304
[243]	validation_0-mae:2226.31944
[244]	validation_0-mae:2226.53145
[245]	validation_0-mae:2226.19689
[246]	validation_0-mae:2225.89890
[247]	validation_0-mae:2224.89186
[248]	validation_0-mae:2224.77765
[249]	validation_0-mae:2225.09083
[250]	validation_0-mae:2225.00142
[251]	validation_0-mae:2224.40286
[252]	validation_0-mae:2223.16613
[253]	validation_0-mae:2223.01181
[254]	validation_0-mae:2223.44579
[255]	validation_0-mae:2222.42241
[256]	validation_0-mae:2221.30955
[257]	validation_0-mae:2221.58273
[258]	validation_0-mae:2220.56887
[259]	validation_0-mae:2220.71139
[260]	validation_0-mae:2220.08198
[261]	validation_0-mae:2219.20498
[262]	validation_0-mae:2218.72071
[263]	validation_0-mae:2218.97294
[264]	validation_0-mae:2217.47995
[265]	validation_0-mae:2216.18288
[266]	validation_0-mae:2215.60615
[267]	validation_0-mae:2216.06901
[268]	validation_0-mae:2214.39971
[269]	validation_0-mae:2215.29416
[270]	validation_0-mae:2215.10723
[271]	validation_0-mae:2214.13451
[272]	validation_0-mae:2214.41944
[273]	validation_0-mae:2213.05890
[274]	validation_0-mae:2213.67792
[275]	validation_0-mae:2213.07746
[276]	validation_0-mae:2213.31229
[277]	validation_0-mae:2212.61741
[278]	validation_0-mae:2210.78466
[279]	validation_0-mae:2208.75111
[280]	validation_0-mae:2207.20523
[281]	validation_0-mae:2205.41416
[282]	validation_0-mae:2205.37805
[283]	validation_0-mae:2204.98295
[284]	validation_0-mae:2204.45035
[285]	validation_0-mae:2203.17980
[286]	validation_0-mae:2202.52086
[287]	validation_0-mae:2202.78275
[288]	validation_0-mae:2202.89177
[289]	validation_0-mae:2201.49582
[290]	validation_0-mae:2201.89156
[291]	validation_0-mae:2200.73524
[292]	validation_0-mae:2200.84897
[293]	validation_0-mae:2200.21658
[294]	validation_0-mae:2199.31473
[295]	validation_0-mae:2198.99461
[296]	validation_0-mae:2198.31239
[297]	validation_0-mae:2198.53836
[298]	validation_0-mae:2197.58397
[299]	validation_0-mae:2198.18456
[300]	validation_0-mae:2196.83646
[301]	validation_0-mae:2196.73124
[302]	validation_0-mae:2195.94906
[303]	validation_0-mae:2195.67094
[304]	validation_0-mae:2195.62409
[305]	validation_0-mae:2194.65529
[306]	validation_0-mae:2194.95139
[307]	validation_0-mae:2194.77924
[308]	validation_0-mae:2194.38916
[309]	validation_0-mae:2194.57774
[310]	validation_0-mae:2192.40842
[311]	validation_0-mae:2192.67281
[312]	validation_0-mae:2191.25876
[313]	validation_0-mae:2190.40569
[314]	validation_0-mae:2190.72003
[315]	validation_0-mae:2191.27984
[316]	validation_0-mae:2191.51104
[317]	validation_0-mae:2190.82635
[318]	validation_0-mae:2190.44979
[319]	validation_0-mae:2190.42107
[320]	validation_0-mae:2189.53627
[321]	validation_0-mae:2189.52029
[322]	validation_0-mae:2189.25451
[323]	validation_0-mae:2188.35864
[324]	validation_0-mae:2187.86389
[325]	validation_0-mae:2187.52543
[326]	validation_0-mae:2187.22659
[327]	validation_0-mae:2186.65645
[328]	validation_0-mae:2185.17886
[329]	validation_0-mae:2184.80883
[330]	validation_0-mae:2183.83851
[331]	validation_0-mae:2183.49136
[332]	validation_0-mae:2181.91820
[333]	validation_0-mae:2180.81068
[334]	validation_0-mae:2180.89836
[335]	validation_0-mae:2180.32946
[336]	validation_0-mae:2179.37016
[337]	validation_0-mae:2179.68866
[338]	validation_0-mae:2179.93402
[339]	validation_0-mae:2180.08641
[340]	validation_0-mae:2179.28568
[341]	validation_0-mae:2178.75896
[342]	validation_0-mae:2178.40954
[343]	validation_0-mae:2178.30447
[344]	validation_0-mae:2177.55776
[345]	validation_0-mae:2177.64725
[346]	validation_0-mae:2176.53472
[347]	validation_0-mae:2176.51873
[348]	validation_0-mae:2176.49245
[349]	validation_0-mae:2175.73597
[350]	validation_0-mae:2175.77917
[351]	validation_0-mae:2175.56658
[352]	validation_0-mae:2175.05311
[353]	validation_0-mae:2174.34586
[354]	validation_0-mae:2173.79183
[355]	validation_0-mae:2173.29704
[356]	validation_0-mae:2173.42361
[357]	validation_0-mae:2173.47500
[358]	validation_0-mae:2173.75389
[359]	validation_0-mae:2173.46501
[360]	validation_0-mae:2173.10488
[361]	validation_0-mae:2173.20828
[362]	validation_0-mae:2174.16949
[363]	validation_0-mae:2173.94363
[364]	validation_0-mae:2173.30203
[365]	validation_0-mae:2172.12815
[366]	validation_0-mae:2171.47125
[367]	validation_0-mae:2170.39156
[368]	validation_0-mae:2170.84474
[369]	validation_0-mae:2171.36279
[370]	validation_0-mae:2170.91047
[371]	validation_0-mae:2170.73918
[372]	validation_0-mae:2171.00958
[373]	validation_0-mae:2169.43621
[374]	validation_0-mae:2169.03314
[375]	validation_0-mae:2169.19718
[376]	validation_0-mae:2169.37284
[377]	validation_0-mae:2169.83136
[378]	validation_0-mae:2168.14771
[379]	validation_0-mae:2168.19549
[380]	validation_0-mae:2168.09514
[381]	validation_0-mae:2165.23235
[382]	validation_0-mae:2164.55420
[383]	validation_0-mae:2164.58581
[384]	validation_0-mae:2164.19098
[385]	validation_0-mae:2164.21298
[386]	validation_0-mae:2164.18100
[387]	validation_0-mae:2163.23246
[388]	validation_0-mae:2163.22215
[389]	validation_0-mae:2162.02095
[390]	validation_0-mae:2161.10912
[391]	validation_0-mae:2161.21127
[392]	validation_0-mae:2159.59104
[393]	validation_0-mae:2159.99152
[394]	validation_0-mae:2160.28328
[395]	validation_0-mae:2159.98918
[396]	validation_0-mae:2160.35563
[397]	validation_0-mae:2160.31275
[398]	validation_0-mae:2160.90069
[399]	validation_0-mae:2160.72285
[400]	validation_0-mae:2160.54622
[401]	validation_0-mae:2160.82260
[402]	validation_0-mae:2160.60349
[403]	validation_0-mae:2160.11732
[404]	validation_0-mae:2159.62531
[405]	validation_0-mae:2158.06045
[406]	validation_0-mae:2157.26590
[407]	validation_0-mae:2157.82417
[408]	validation_0-mae:2158.64040
[409]	validation_0-mae:2158.48580
[410]	validation_0-mae:2156.15167
[411]	validation_0-mae:2155.49324
[412]	validation_0-mae:2155.43296
[413]	validation_0-mae:2155.28649
[414]	validation_0-mae:2154.98589
[415]	validation_0-mae:2154.50838
[416]	validation_0-mae:2154.83121
[417]	validation_0-mae:2154.58775
[418]	validation_0-mae:2154.68414
[419]	validation_0-mae:2154.44254
[420]	validation_0-mae:2152.94731
[421]	validation_0-mae:2153.10234
[422]	validation_0-mae:2152.41748
[423]	validation_0-mae:2152.46007
[424]	validation_0-mae:2152.43320
[425]	validation_0-mae:2151.96715
[426]	validation_0-mae:2151.97635
[427]	validation_0-mae:2152.11141
[428]	validation_0-mae:2151.78832
[429]	validation_0-mae:2152.07107
[430]	validation_0-mae:2151.75146
[431]	validation_0-mae:2151.62896
[432]	validation_0-mae:2151.55406
[433]	validation_0-mae:2151.82349
[434]	validation_0-mae:2152.13823
[435]	validation_0-mae:2152.00805
[436]	validation_0-mae:2152.29119
[437]	validation_0-mae:2152.71386
[438]	validation_0-mae:2152.44957
[439]	validation_0-mae:2151.90313
[440]	validation_0-mae:2150.35350
[441]	validation_0-mae:2149.68690
[442]	validation_0-mae:2150.12616
[443]	validation_0-mae:2150.18354
[444]	validation_0-mae:2149.69478
[445]	validation_0-mae:2149.36657
[446]	validation_0-mae:2149.61993
[447]	validation_0-mae:2148.76319
[448]	validation_0-mae:2149.39449
[449]	validation_0-mae:2148.59144
[450]	validation_0-mae:2148.11614
[451]	validation_0-mae:2148.31243
[452]	validation_0-mae:2147.28007
[453]	validation_0-mae:2147.74411
[454]	validation_0-mae:2147.40586
[455]	validation_0-mae:2146.98015
[456]	validation_0-mae:2146.72030
[457]	validation_0-mae:2146.18225
[458]	validation_0-mae:2144.86499
[459]	validation_0-mae:2144.07145
[460]	validation_0-mae:2144.22016
[461]	validation_0-mae:2144.28117
[462]	validation_0-mae:2144.04932
[463]	validation_0-mae:2143.73679
[464]	validation_0-mae:2144.07804
[465]	validation_0-mae:2143.53994
[466]	validation_0-mae:2143.90744
[467]	validation_0-mae:2144.37506
[468]	validation_0-mae:2144.51554
[469]	validation_0-mae:2144.13425
[470]	validation_0-mae:2140.41297
[471]	validation_0-mae:2140.22445
[472]	validation_0-mae:2140.07363
[473]	validation_0-mae:2140.61983
[474]	validation_0-mae:2140.75076
[475]	validation_0-mae:2140.66797
[476]	validation_0-mae:2139.65000
[477]	validation_0-mae:2139.02439
[478]	validation_0-mae:2139.46908
[479]	validation_0-mae:2139.08593
[480]	validation_0-mae:2137.38740
[481]	validation_0-mae:2137.59170
[482]	validation_0-mae:2136.64365
[483]	validation_0-mae:2136.32047
[484]	validation_0-mae:2136.58742
[485]	validation_0-mae:2135.82693
[486]	validation_0-mae:2135.75992
[487]	validation_0-mae:2134.66917
[488]	validation_0-mae:2134.31460
[489]	validation_0-mae:2133.95330
[490]	validation_0-mae:2132.51113
[491]	validation_0-mae:2131.01441
[492]	validation_0-mae:2129.81982
[493]	validation_0-mae:2129.21145
[494]	validation_0-mae:2128.55550
[495]	validation_0-mae:2128.28473
[496]	validation_0-mae:2127.48532
[497]	validation_0-mae:2127.59249
[498]	validation_0-mae:2127.03214
[499]	validation_0-mae:2127.13362
[500]	validation_0-mae:2125.65807
[501]	validation_0-mae:2125.55153
[502]	validation_0-mae:2125.60641
[503]	validation_0-mae:2126.10216
[504]	validation_0-mae:2126.21745
[505]	validation_0-mae:2126.58237
[506]	validation_0-mae:2126.81466
[507]	validation_0-mae:2126.83635
[508]	validation_0-mae:2126.35903
[509]	validation_0-mae:2126.03072
[510]	validation_0-mae:2125.83192
[511]	validation_0-mae:2125.15966
[512]	validation_0-mae:2125.07300
[513]	validation_0-mae:2124.05498
[514]	validation_0-mae:2124.35029
[515]	validation_0-mae:2124.08711
[516]	validation_0-mae:2122.91278
[517]	validation_0-mae:2122.66614
[518]	validation_0-mae:2122.64484
[519]	validation_0-mae:2122.10304
[520]	validation_0-mae:2122.01507
[521]	validation_0-mae:2122.35718
[522]	validation_0-mae:2121.15931
[523]	validation_0-mae:2121.41065
[524]	validation_0-mae:2121.49957
[525]	validation_0-mae:2121.36766
[526]	validation_0-mae:2121.67878
[527]	validation_0-mae:2121.63955
[528]	validation_0-mae:2121.77647
[529]	validation_0-mae:2121.48001
[530]	validation_0-mae:2120.83926
[531]	validation_0-mae:2119.73957
[532]	validation_0-mae:2119.25904
[533]	validation_0-mae:2118.84811
[534]	validation_0-mae:2118.31842
[535]	validation_0-mae:2118.69537
[536]	validation_0-mae:2119.04217
[537]	validation_0-mae:2118.89587
[538]	validation_0-mae:2118.99584
[539]	validation_0-mae:2119.45985
[540]	validation_0-mae:2119.30163
[541]	validation_0-mae:2119.90614
[542]	validation_0-mae:2119.52232
[543]	validation_0-mae:2119.35507
[544]	validation_0-mae:2119.28206
[545]	validation_0-mae:2119.29380
[546]	validation_0-mae:2118.42070
[547]	validation_0-mae:2119.11190
[548]	validation_0-mae:2119.52319
[549]	validation_0-mae:2119.56205
[550]	validation_0-mae:2119.04181
[551]	validation_0-mae:2120.20891
[552]	validation_0-mae:2120.25402
[553]	validation_0-mae:2120.10398
[554]	validation_0-mae:2120.49480
[555]	validation_0-mae:2120.19230
[556]	validation_0-mae:2120.58981
[557]	validation_0-mae:2119.88916
[558]	validation_0-mae:2119.49516
[559]	validation_0-mae:2119.65780
[560]	validation_0-mae:2119.79245
[561]	validation_0-mae:2119.10244
[562]	validation_0-mae:2119.40577
[563]	validation_0-mae:2118.83958
[564]	validation_0-mae:2118.73155
[565]	validation_0-mae:2117.91273
[566]	validation_0-mae:2117.89403
[567]	validation_0-mae:2117.64464
[568]	validation_0-mae:2117.28595
[569]	validation_0-mae:2116.95102
[570]	validation_0-mae:2116.30718
[571]	validation_0-mae:2116.25441
[0]	validation_0-mae:12536.72292
[1]	validation_0-mae:11876.60312
[2]	validation_0-mae:11291.82747
[3]	validation_0-mae:10770.95094
[4]	validation_0-mae:10327.42438
[5]	validation_0-mae:9928.21715
[6]	validation_0-mae:9555.01511
[7]	validation_0-mae:9189.63463
[8]	validation_0-mae:8885.00885
[9]	validation_0-mae:8614.46819
[10]	validation_0-mae:8352.50377
[0]	validation_0-mae:12632.14369
[1]	validation_0-mae:12049.03626
[2]	validation_0-mae:11511.42590
[3]	validation_0-mae:11014.95413
[4]	validation_0-mae:10574.98193

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[5]	validation_0-mae:10157.92407
[6]	validation_0-mae:9764.56565
[7]	validation_0-mae:9425.35944
[8]	validation_0-mae:9100.21091
[9]	validation_0-mae:8784.95639
[0]	validation_0-mae:12350.28464
[1]	validation_0-mae:11560.39865
[2]	validation_0-mae:10829.65319
[3]	validation_0-mae:10160.43717
[4]	validation_0-mae:9567.90630
[5]	validation_0-mae:9050.55358
[6]	validation_0-mae:8612.39691
[7]	validation_0-mae:8203.81752
[8]	validation_0-mae:7826.11772
[9]	validation_0-mae:7484.92497
[10]	validation_0-mae:7140.02459
[11]	validation_0-mae:6841.29792
[12]	validation_0-mae:6597.19986
[13]	validation_0-mae:6336.46519
[14]	validation_0-mae:6082.71525
[15]	validation_0-mae:5847.41002
[16]	validation_0-mae:5632.59642
[17]	validation_0-mae:5440.20306
[18]	validation_0-mae:5266.74461
[19]	validation_0-mae:5076.46299
[20]	validation_0-mae:4923.03320
[21]	validation_0-mae:4754.09445
[22]	validation_0-mae:4610.56278
[23]	validation_0-mae:4481.26054
[24]	validation_0-mae:4348.74248
[25]	validation_0-mae:4241.41817
[26]	validation_0-mae:4127.13360
[27]	validation_0-mae:4033.05821
[28]	validation_0-mae:3928.64988
[29]	validation_0-mae:3845.55287
[30]	validation_0-mae:3772.44481
[31]	validation_0-mae:3700.77732
[32]	validation_0-mae:3627.61094
[33]	validation_0-mae:3567.25126
[34]	validation_0-mae:3504.78663
[35]	validation_0-mae:3456.35935
[36]	validation_0-mae:3400.21910
[37]	validation_0-mae:3358.23580
[38]	validation_0-mae:3293.40710
[39]	validation_0-mae:3255.24208
[40]	validation_0-mae:3209.18603
[41]	validation_0-mae:3170.99849
[42]	validation_0-mae:3143.45046

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[43]	validation_0-mae:3098.11278
[44]	validation_0-mae:3064.95790
[45]	validation_0-mae:3037.14071
[46]	validation_0-mae:3007.16737
[47]	validation_0-mae:2971.52126
[48]	validation_0-mae:2947.94863
[49]	validation_0-mae:2924.00819
[50]	validation_0-mae:2900.39951
[51]	validation_0-mae:2880.17647
[52]	validation_0-mae:2863.77329
[53]	validation_0-mae:2843.82246
[54]	validation_0-mae:2824.24144
[55]	validation_0-mae:2807.08370
[56]	validation_0-mae:2788.12609
[57]	validation_0-mae:2760.96304
[58]	validation_0-mae:2746.46877
[59]	validation_0-mae:2732.12122
[60]	validation_0-mae:2714.35864
[61]	validation_0-mae:2699.34519
[62]	validation_0-mae:2687.61778
[63]	validation_0-mae:2674.58755
[64]	validation_0-mae:2657.43378
[65]	validation_0-mae:2644.86440
[66]	validation_0-mae:2628.04258
[67]	validation_0-mae:2617.77300
[68]	validation_0-mae:2601.64413
[69]	validation_0-mae:2589.31339
[70]	validation_0-mae:2575.39252
[71]	validation_0-mae:2564.35924
[72]	validation_0-mae:2551.85687
[73]	validation_0-mae:2540.52789
[74]	validation_0-mae:2531.53967
[75]	validation_0-mae:2525.34156
[76]	validation_0-mae:2514.07252
[77]	validation_0-mae:2508.78760
[78]	validation_0-mae:2499.56759
[79]	validation_0-mae:2494.75252
[80]	validation_0-mae:2490.04885
[81]	validation_0-mae:2484.96865
[82]	validation_0-mae:2479.26310
[83]	validation_0-mae:2468.63328
[84]	validation_0-mae:2459.79160
[85]	validation_0-mae:2456.38856
[86]	validation_0-mae:2447.70536
[87]	validation_0-mae:2437.56728
[88]	validation_0-mae:2434.47693
[89]	validation_0-mae:2431.60037
[90]	validation_0-mae:2424.71258
[91]	validation_0-mae:2405.67970
[92]	validation_0-mae:2399.30212
[93]	validation_0-mae:2392.37897
[94]	validation_0-mae:2389.18995
[95]	validation_0-mae:2383.73225
[96]	validation_0-mae:2373.82733
[97]	validation_0-mae:2371.20500
[98]	validation_0-mae:2362.72539
[99]	validation_0-mae:2360.03179
[100]	validation_0-mae:2353.42910
[101]	validation_0-mae:2352.05757
[102]	validation_0-mae:2345.42536
[103]	validation_0-mae:2343.75965
[104]	validation_0-mae:2341.58343
[105]	validation_0-mae:2336.57884
[106]	validation_0-mae:2326.06632
[107]	validation_0-mae:2324.01635
[108]	validation_0-mae:2321.43589
[109]	validation_0-mae:2318.32628
[110]	validation_0-mae:2311.06688
[111]	validation_0-mae:2308.98724
[112]	validation_0-mae:2306.56204
[113]	validation_0-mae:2304.25280
[114]	validation_0-mae:2297.20800
[115]	validation_0-mae:2294.32835
[116]	validation_0-mae:2292.15416
[117]	validation_0-mae:2287.98024
[118]	validation_0-mae:2286.47878
[119]	validation_0-mae:2285.35723
[120]	validation_0-mae:2281.54703
[121]	validation_0-mae:2277.58862
[122]	validation_0-mae:2277.83220
[123]	validation_0-mae:2273.82393
[124]	validation_0-mae:2272.89592
[125]	validation_0-mae:2267.08937
[126]	validation_0-mae:2267.11120
[127]	validation_0-mae:2266.47474
[128]	validation_0-mae:2264.45534
[129]	validation_0-mae:2262.46164
[130]	validation_0-mae:2257.90315
[131]	validation_0-mae:2256.98264
[132]	validation_0-mae:2256.17105
[133]	validation_0-mae:2254.11870
[134]	validation_0-mae:2252.80715
[135]	validation_0-mae:2252.57300
[136]	validation_0-mae:2251.17591
[137]	validation_0-mae:2251.54152
[138]	validation_0-mae:2249.96068
[139]	validation_0-mae:2245.67913
[140]	validation_0-mae:2243.69446
[141]	validation_0-mae:2241.72175
[142]	validation_0-mae:2239.45156
[143]	validation_0-mae:2239.50914
[144]	validation_0-mae:2238.24042
[145]	validation_0-mae:2235.39257
[146]	validation_0-mae:2234.19611
[147]	validation_0-mae:2233.27044
[148]	validation_0-mae:2232.86682
[149]	validation_0-mae:2231.38143
[150]	validation_0-mae:2228.74803
[151]	validation_0-mae:2227.82149
[152]	validation_0-mae:2227.27868
[153]	validation_0-mae:2224.83774
[154]	validation_0-mae:2224.24217
[155]	validation_0-mae:2224.76553
[156]	validation_0-mae:2224.47940
[157]	validation_0-mae:2220.83294
[158]	validation_0-mae:2221.77683
[159]	validation_0-mae:2222.51529
[160]	validation_0-mae:2220.99113
[161]	validation_0-mae:2218.03946
[162]	validation_0-mae:2217.48589
[163]	validation_0-mae:2217.70823
[164]	validation_0-mae:2216.81023
[165]	validation_0-mae:2215.61421
[166]	validation_0-mae:2215.73400
[167]	validation_0-mae:2214.06746
[168]	validation_0-mae:2213.89968
[169]	validation_0-mae:2214.23397
[170]	validation_0-mae:2211.10888
[171]	validation_0-mae:2210.14528
[172]	validation_0-mae:2210.70745
[173]	validation_0-mae:2211.09264
[174]	validation_0-mae:2209.53036
[175]	validation_0-mae:2209.50019
[176]	validation_0-mae:2208.37355
[177]	validation_0-mae:2207.04683
[178]	validation_0-mae:2207.26963
[179]	validation_0-mae:2206.53715
[180]	validation_0-mae:2205.20243
[181]	validation_0-mae:2204.87847
[182]	validation_0-mae:2204.82074
[183]	validation_0-mae:2203.58220
[184]	validation_0-mae:2201.96914
[185]	validation_0-mae:2203.05690
[186]	validation_0-mae:2202.03483
[187]	validation_0-mae:2200.41742
[188]	validation_0-mae:2200.17244
[189]	validation_0-mae:2200.29477
[190]	validation_0-mae:2197.97814
[191]	validation_0-mae:2196.87831
[192]	validation_0-mae:2196.95972
[193]	validation_0-mae:2194.75170
[194]	validation_0-mae:2193.31170
[195]	validation_0-mae:2193.52175
[196]	validation_0-mae:2193.88554
[197]	validation_0-mae:2193.17616
[198]	validation_0-mae:2192.52514
[199]	validation_0-mae:2192.74133
[200]	validation_0-mae:2189.65575
[201]	validation_0-mae:2189.31674
[202]	validation_0-mae:2190.32777
[203]	validation_0-mae:2190.78980
[204]	validation_0-mae:2188.74630
[205]	validation_0-mae:2187.80758
[206]	validation_0-mae:2187.75194
[207]	validation_0-mae:2187.60827
[208]	validation_0-mae:2187.69816
[209]	validation_0-mae:2188.40091
[210]	validation_0-mae:2186.98623
[211]	validation_0-mae:2186.40591
[212]	validation_0-mae:2186.18472
[213]	validation_0-mae:2187.17557
[214]	validation_0-mae:2186.85088
[215]	validation_0-mae:2185.60044
[216]	validation_0-mae:2185.34348
[217]	validation_0-mae:2184.91383
[218]	validation_0-mae:2184.61740
[219]	validation_0-mae:2184.61225
[220]	validation_0-mae:2182.56570
[221]	validation_0-mae:2181.17111
[222]	validation_0-mae:2180.76460
[223]	validation_0-mae:2180.37886
[224]	validation_0-mae:2180.02074
[225]	validation_0-mae:2180.42407
[226]	validation_0-mae:2178.48845
[227]	validation_0-mae:2178.75676
[228]	validation_0-mae:2177.34041
[229]	validation_0-mae:2176.54968
[230]	validation_0-mae:2174.93592
[231]	validation_0-mae:2174.98568
[232]	validation_0-mae:2174.12353
[233]	validation_0-mae:2172.13163
[234]	validation_0-mae:2171.72055
[235]	validation_0-mae:2171.26737
[236]	validation_0-mae:2170.59299
[237]	validation_0-mae:2172.09392
[238]	validation_0-mae:2172.98455
[239]	validation_0-mae:2171.77298
[240]	validation_0-mae:2170.08513
[241]	validation_0-mae:2170.55679
[242]	validation_0-mae:2170.69921
[243]	validation_0-mae:2170.97692
[244]	validation_0-mae:2170.09796
[245]	validation_0-mae:2170.34983
[246]	validation_0-mae:2170.76084
[247]	validation_0-mae:2171.20955
[248]	validation_0-mae:2167.88869
[249]	validation_0-mae:2168.19289
[250]	validation_0-mae:2167.91990
[251]	validation_0-mae:2168.36142
[252]	validation_0-mae:2167.70819
[253]	validation_0-mae:2166.96925
[254]	validation_0-mae:2166.26118
[255]	validation_0-mae:2165.46459
[256]	validation_0-mae:2165.98893
[257]	validation_0-mae:2166.65338
[258]	validation_0-mae:2166.93741
[259]	validation_0-mae:2166.29787
[260]	validation_0-mae:2165.84157
[261]	validation_0-mae:2165.72242
[262]	validation_0-mae:2165.60656
[263]	validation_0-mae:2165.14148
[264]	validation_0-mae:2165.34062
[265]	validation_0-mae:2165.11966
[266]	validation_0-mae:2165.70537
[267]	validation_0-mae:2166.41738
[268]	validation_0-mae:2166.17078
[269]	validation_0-mae:2165.03594
[270]	validation_0-mae:2163.45330
[271]	validation_0-mae:2162.27502
[272]	validation_0-mae:2161.33564
[273]	validation_0-mae:2161.97214
[274]	validation_0-mae:2162.65423
[275]	validation_0-mae:2163.06119
[276]	validation_0-mae:2163.92519
[277]	validation_0-mae:2164.32637
[278]	validation_0-mae:2164.25686
[279]	validation_0-mae:2164.14405
[280]	validation_0-mae:2164.62790
[281]	validation_0-mae:2163.30146
[282]	validation_0-mae:2163.71948
[283]	validation_0-mae:2163.55076
[284]	validation_0-mae:2163.72556
[285]	validation_0-mae:2161.47979
[286]	validation_0-mae:2160.69115
[287]	validation_0-mae:2158.74809
[288]	validation_0-mae:2156.22263
[289]	validation_0-mae:2155.37418
[290]	validation_0-mae:2153.64298
[291]	validation_0-mae:2152.71898
[292]	validation_0-mae:2152.80421
[293]	validation_0-mae:2153.05973
[294]	validation_0-mae:2152.99879
[295]	validation_0-mae:2153.31613
[296]	validation_0-mae:2153.79716
[297]	validation_0-mae:2153.72284
[298]	validation_0-mae:2153.06311
[299]	validation_0-mae:2152.76808
[300]	validation_0-mae:2152.82673
[301]	validation_0-mae:2152.75959
[302]	validation_0-mae:2153.24819
[303]	validation_0-mae:2152.99382
[304]	validation_0-mae:2153.10641
[305]	validation_0-mae:2153.52585
[306]	validation_0-mae:2153.02072
[307]	validation_0-mae:2153.78141
[308]	validation_0-mae:2152.83903
[309]	validation_0-mae:2153.33850
[310]	validation_0-mae:2154.17503
[311]	validation_0-mae:2153.92127
[312]	validation_0-mae:2152.87649
[313]	validation_0-mae:2152.83175
[314]	validation_0-mae:2152.26704
[315]	validation_0-mae:2152.29469
[316]	validation_0-mae:2150.59840
[317]	validation_0-mae:2151.02563
[318]	validation_0-mae:2150.98456
[319]	validation_0-mae:2152.19057
[320]	validation_0-mae:2151.75909
[321]	validation_0-mae:2149.54017
[322]	validation_0-mae:2149.05748
[323]	validation_0-mae:2148.92007
[324]	validation_0-mae:2147.56648
[325]	validation_0-mae:2147.68210
[326]	validation_0-mae:2147.50558
[327]	validation_0-mae:2147.80022
[328]	validation_0-mae:2146.55741
[329]	validation_0-mae:2146.81191
[330]	validation_0-mae:2146.11385
[331]	validation_0-mae:2145.32845
[332]	validation_0-mae:2145.02939
[333]	validation_0-mae:2145.14933
[334]	validation_0-mae:2145.37784
[335]	validation_0-mae:2145.62807
[336]	validation_0-mae:2144.87097
[337]	validation_0-mae:2144.18871
[338]	validation_0-mae:2144.07260
[339]	validation_0-mae:2142.06769
[340]	validation_0-mae:2142.01031
[341]	validation_0-mae:2141.61644
[342]	validation_0-mae:2140.87992
[343]	validation_0-mae:2140.81590
[344]	validation_0-mae:2141.40973
[345]	validation_0-mae:2141.82806
[346]	validation_0-mae:2142.02040
[347]	validation_0-mae:2140.81007
[348]	validation_0-mae:2140.63804
[349]	validation_0-mae:2140.63302
[350]	validation_0-mae:2140.33311
[351]	validation_0-mae:2140.75582
[352]	validation_0-mae:2141.54389
[353]	validation_0-mae:2141.02698
[354]	validation_0-mae:2140.99020
[355]	validation_0-mae:2140.93592
[356]	validation_0-mae:2140.81530
[357]	validation_0-mae:2141.03837
[358]	validation_0-mae:2140.67040
[359]	validation_0-mae:2140.04184
[360]	validation_0-mae:2139.49783
[361]	validation_0-mae:2139.19465
[362]	validation_0-mae:2139.40178
[363]	validation_0-mae:2139.04709
[364]	validation_0-mae:2138.68788
[365]	validation_0-mae:2136.39035
[366]	validation_0-mae:2135.20024
[367]	validation_0-mae:2134.87373
[368]	validation_0-mae:2135.13433
[369]	validation_0-mae:2135.48668
[370]	validation_0-mae:2135.02516
[371]	validation_0-mae:2135.19598
[372]	validation_0-mae:2133.53102
[373]	validation_0-mae:2133.31296
[374]	validation_0-mae:2132.93246
[375]	validation_0-mae:2132.41701
[376]	validation_0-mae:2132.32696
[377]	validation_0-mae:2131.90978
[378]	validation_0-mae:2131.47827
[379]	validation_0-mae:2131.95882
[380]	validation_0-mae:2130.81672
[381]	validation_0-mae:2130.96774
[382]	validation_0-mae:2130.91117
[383]	validation_0-mae:2130.99421
[384]	validation_0-mae:2130.88469
[385]	validation_0-mae:2130.62380
[386]	validation_0-mae:2130.38879
[387]	validation_0-mae:2130.31698
[388]	validation_0-mae:2130.22613
[389]	validation_0-mae:2128.22041
[390]	validation_0-mae:2128.37345
[391]	validation_0-mae:2128.32239
[392]	validation_0-mae:2127.64484
[393]	validation_0-mae:2126.73291
[394]	validation_0-mae:2126.23878
[395]	validation_0-mae:2125.11008
[396]	validation_0-mae:2124.73533
[397]	validation_0-mae:2125.22456
[398]	validation_0-mae:2125.42073
[399]	validation_0-mae:2125.47273
[400]	validation_0-mae:2125.30359
[401]	validation_0-mae:2125.42457
[402]	validation_0-mae:2125.61822
[403]	validation_0-mae:2125.71398
[404]	validation_0-mae:2125.77775
[405]	validation_0-mae:2125.41489
[406]	validation_0-mae:2125.54471
[407]	validation_0-mae:2125.56130
[408]	validation_0-mae:2124.63454
[409]	validation_0-mae:2125.07665
[410]	validation_0-mae:2125.17789
[411]	validation_0-mae:2125.55809
[412]	validation_0-mae:2125.32471
[413]	validation_0-mae:2125.27138
[414]	validation_0-mae:2125.57756
[415]	validation_0-mae:2125.50619
[416]	validation_0-mae:2123.78877
[417]	validation_0-mae:2123.40342
[418]	validation_0-mae:2122.86280
[419]	validation_0-mae:2122.35530
[420]	validation_0-mae:2122.43008
[421]	validation_0-mae:2122.64289
[422]	validation_0-mae:2122.56059
[423]	validation_0-mae:2121.60366
[424]	validation_0-mae:2121.78780
[425]	validation_0-mae:2121.86944
[426]	validation_0-mae:2121.87683
[427]	validation_0-mae:2121.59150
[428]	validation_0-mae:2122.06215
[429]	validation_0-mae:2122.11482
[430]	validation_0-mae:2121.92370
[431]	validation_0-mae:2121.80347
[432]	validation_0-mae:2122.43338
[433]	validation_0-mae:2121.70707
[434]	validation_0-mae:2121.64872
[435]	validation_0-mae:2121.69702
[436]	validation_0-mae:2121.89236
[437]	validation_0-mae:2122.47534
[438]	validation_0-mae:2122.21524
[439]	validation_0-mae:2122.09339
[440]	validation_0-mae:2122.24683
[441]	validation_0-mae:2122.57384
[442]	validation_0-mae:2122.73658
[443]	validation_0-mae:2122.79436
[444]	validation_0-mae:2122.69557
[445]	validation_0-mae:2122.76384
[446]	validation_0-mae:2122.67379
[447]	validation_0-mae:2122.17769
[448]	validation_0-mae:2122.30722
[449]	validation_0-mae:2121.41007
[450]	validation_0-mae:2120.82314
[451]	validation_0-mae:2120.20355
[452]	validation_0-mae:2118.48865
[453]	validation_0-mae:2118.42333
[454]	validation_0-mae:2118.30796
[455]	validation_0-mae:2118.20810
[456]	validation_0-mae:2116.83987
[457]	validation_0-mae:2116.17521
[458]	validation_0-mae:2116.32146
[459]	validation_0-mae:2116.12208
[460]	validation_0-mae:2115.96800
[461]	validation_0-mae:2116.11172
[462]	validation_0-mae:2115.50359
[463]	validation_0-mae:2115.58290
[464]	validation_0-mae:2114.04849
[465]	validation_0-mae:2113.29948
[466]	validation_0-mae:2111.73950
[467]	validation_0-mae:2111.43102
[468]	validation_0-mae:2111.90544
[469]	validation_0-mae:2111.91277
[470]	validation_0-mae:2111.47782
[471]	validation_0-mae:2111.59802
[472]	validation_0-mae:2111.57590
[473]	validation_0-mae:2111.66102
[474]	validation_0-mae:2111.59839
[475]	validation_0-mae:2111.57930
[476]	validation_0-mae:2111.61571
[477]	validation_0-mae:2111.61418
[478]	validation_0-mae:2111.65539
[479]	validation_0-mae:2112.17348
[480]	validation_0-mae:2112.03628
[481]	validation_0-mae:2112.15937
[482]	validation_0-mae:2111.07356
[483]	validation_0-mae:2111.22989
[484]	validation_0-mae:2110.48868
[485]	validation_0-mae:2110.18034
[486]	validation_0-mae:2110.24652
[487]	validation_0-mae:2110.55512
[488]	validation_0-mae:2110.42404
[489]	validation_0-mae:2110.74707
[490]	validation_0-mae:2110.62591
[491]	validation_0-mae:2110.77935
[492]	validation_0-mae:2110.58029
[493]	validation_0-mae:2109.76373
[494]	validation_0-mae:2109.92382
[495]	validation_0-mae:2110.15026
[496]	validation_0-mae:2109.60041
[497]	validation_0-mae:2109.60648
[498]	validation_0-mae:2109.73770
[499]	validation_0-mae:2109.76525
[500]	validation_0-mae:2109.72329
[501]	validation_0-mae:2109.74980
[502]	validation_0-mae:2109.82899
[503]	validation_0-mae:2110.15642
[504]	validation_0-mae:2110.16817
[505]	validation_0-mae:2109.46100
[506]	validation_0-mae:2109.19593
[507]	validation_0-mae:2109.27353
[508]	validation_0-mae:2109.39622
[509]	validation_0-mae:2108.98738
[510]	validation_0-mae:2108.94928
[511]	validation_0-mae:2109.00138
[512]	validation_0-mae:2108.93329
[513]	validation_0-mae:2108.97800
[514]	validation_0-mae:2108.87171
[515]	validation_0-mae:2108.68747
[516]	validation_0-mae:2108.51369
[517]	validation_0-mae:2108.76561
[518]	validation_0-mae:2108.75989
[519]	validation_0-mae:2107.88072
[520]	validation_0-mae:2107.95622
[521]	validation_0-mae:2107.77496
[522]	validation_0-mae:2107.39073
[523]	validation_0-mae:2107.64399
[524]	validation_0-mae:2108.14442
[525]	validation_0-mae:2108.06533
[526]	validation_0-mae:2107.37467
[527]	validation_0-mae:2106.86239
[528]	validation_0-mae:2107.22486
[529]	validation_0-mae:2107.19273
[530]	validation_0-mae:2107.11338
[531]	validation_0-mae:2107.52536
[532]	validation_0-mae:2107.40010
[533]	validation_0-mae:2107.27221
[534]	validation_0-mae:2107.10417
[535]	validation_0-mae:2107.05648
[536]	validation_0-mae:2106.67080
[537]	validation_0-mae:2106.32705
[538]	validation_0-mae:2106.27579
[539]	validation_0-mae:2106.04721
[540]	validation_0-mae:2106.28747
[541]	validation_0-mae:2105.48562
[542]	validation_0-mae:2105.89873
[543]	validation_0-mae:2106.18953
[544]	validation_0-mae:2106.24549
[545]	validation_0-mae:2106.58241
[546]	validation_0-mae:2106.19709
[547]	validation_0-mae:2106.36854
[548]	validation_0-mae:2106.53570
[549]	validation_0-mae:2106.24788
[550]	validation_0-mae:2105.35999
[551]	validation_0-mae:2105.80327
[552]	validation_0-mae:2104.76793
[553]	validation_0-mae:2105.03935
[554]	validation_0-mae:2104.45528
[555]	validation_0-mae:2104.84094
[556]	validation_0-mae:2104.92949
[557]	validation_0-mae:2105.16950
[558]	validation_0-mae:2105.20619
[559]	validation_0-mae:2105.20966
[560]	validation_0-mae:2104.86636
[561]	validation_0-mae:2105.00900
[562]	validation_0-mae:2105.21274
[563]	validation_0-mae:2105.03663
[564]	validation_0-mae:2104.86039
[565]	validation_0-mae:2104.90768
[566]	validation_0-mae:2104.85718
[567]	validation_0-mae:2104.49139
[568]	validation_0-mae:2104.76344
[569]	validation_0-mae:2104.59920
[570]	validation_0-mae:2104.12569
[571]	validation_0-mae:2103.88226
[572]	validation_0-mae:2103.84043
[573]	validation_0-mae:2103.52386
[574]	validation_0-mae:2103.59565
[575]	validation_0-mae:2103.09023
[576]	validation_0-mae:2103.02573
[577]	validation_0-mae:2103.19939
[578]	validation_0-mae:2103.18597
[579]	validation_0-mae:2102.92907
[580]	validation_0-mae:2102.81207
[581]	validation_0-mae:2102.33300
[582]	validation_0-mae:2102.33673
[583]	validation_0-mae:2102.56955
[584]	validation_0-mae:2102.04090
[585]	validation_0-mae:2102.15001
[586]	validation_0-mae:2102.44427
[587]	validation_0-mae:2102.37813
[588]	validation_0-mae:2102.01179
[589]	validation_0-mae:2101.48019
[590]	validation_0-mae:2101.02976
[591]	validation_0-mae:2100.87769
[592]	validation_0-mae:2100.56268
[593]	validation_0-mae:2099.67630
[594]	validation_0-mae:2099.64353
[595]	validation_0-mae:2099.72998
[596]	validation_0-mae:2099.30139
[597]	validation_0-mae:2097.98927
[598]	validation_0-mae:2096.86914
[599]	validation_0-mae:2096.19095
[600]	validation_0-mae:2096.26658
[601]	validation_0-mae:2095.37190
[602]	validation_0-mae:2095.45092
[603]	validation_0-mae:2095.27145
[604]	validation_0-mae:2095.54744
[605]	validation_0-mae:2095.59169
[606]	validation_0-mae:2095.76772
[607]	validation_0-mae:2095.80429
[608]	validation_0-mae:2095.86166
[609]	validation_0-mae:2095.85783
[610]	validation_0-mae:2095.86524
[611]	validation_0-mae:2095.93939
[612]	validation_0-mae:2095.92211
[613]	validation_0-mae:2095.70384
[614]	validation_0-mae:2095.74589
[615]	validation_0-mae:2095.65530
[616]	validation_0-mae:2095.67802
[617]	validation_0-mae:2095.28461
[618]	validation_0-mae:2094.84334
[619]	validation_0-mae:2094.53981
[620]	validation_0-mae:2093.90936
[621]	validation_0-mae:2093.43729
[622]	validation_0-mae:2092.61330
[623]	validation_0-mae:2091.85861
[624]	validation_0-mae:2091.95754
[625]	validation_0-mae:2092.04916
[626]	validation_0-mae:2091.78375
[627]	validation_0-mae:2091.75564
[628]	validation_0-mae:2091.76997
[629]	validation_0-mae:2091.86520
[630]	validation_0-mae:2091.66168
[631]	validation_0-mae:2091.74759

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[53]	validation_0-mae:3103.38340
[54]	validation_0-mae:3081.46192
[55]	validation_0-mae:3063.35785
[56]	validation_0-mae:3042.05116
[57]	validation_0-mae:3026.83329
[58]	validation_0-mae:2999.85596
[59]	validation_0-mae:2984.72871
[60]	validation_0-mae:2952.81969
[61]	validation_0-mae:2938.31686
[62]	validation_0-mae:2926.61067
[63]	validation_0-mae:2910.31268
[64]	validation_0-mae:2895.96025
[65]	validation_0-mae:2888.79657
[66]	validation_0-mae:2879.15894
[67]	validation_0-mae:2867.00421
[68]	validation_0-mae:2855.52471
[69]	validation_0-mae:2829.05108
[70]	validation_0-mae:2812.19092
[71]	validation_0-mae:2796.22921
[72]	validation_0-mae:2774.79347
[73]	validation_0-mae:2765.71846
[74]	validation_0-mae:2755.25278
[75]	validation_0-mae:2746.33096
[76]	validation_0-mae:2730.05685
[77]	validation_0-mae:2727.60384
[78]	validation_0-mae:2719.61426
[79]	validation_0-mae:2706.61010
[80]	validation_0-mae:2693.26986
[81]	validation_0-mae:2686.46275
[82]	validation_0-mae:2673.57618
[83]	validation_0-mae:2660.84163
[84]	validation_0-mae:2654.00823
[85]	validation_0-mae:2648.65245
[86]	validation_0-mae:2635.76636
[87]	validation_0-mae:2628.98656
[88]	validation_0-mae:2620.13724
[89]	validation_0-mae:2611.24990
[90]	validation_0-mae:2605.34617
[91]	validation_0-mae:2592.00842
[92]	validation_0-mae:2584.82178
[93]	validation_0-mae:2577.66582
[94]	validation_0-mae:2572.59334
[95]	validation_0-mae:2564.16626
[96]	validation_0-mae:2556.94012
[97]	validation_0-mae:2548.48323
[98]	validation_0-mae:2538.94138
[99]	validation_0-mae:2532.33346
[100]	validation_0-mae:2523.23989
[101]	validation_0-mae:2514.95933
[102]	validation_0-mae:2505.42111
[103]	validation_0-mae:2498.34218
[104]	validation_0-mae:2494.29970
[105]	validation_0-mae:2489.66628
[106]	validation_0-mae:2480.73736
[107]	validation_0-mae:2476.88662
[108]	validation_0-mae:2466.06820
[109]	validation_0-mae:2459.68017
[110]	validation_0-mae:2456.64535
[111]	validation_0-mae:2452.98010
[112]	validation_0-mae:2446.82170
[113]	validation_0-mae:2442.42512
[114]	validation_0-mae:2437.27621
[115]	validation_0-mae:2427.99380
[116]	validation_0-mae:2423.73222
[117]	validation_0-mae:2416.83811
[118]	validation_0-mae:2413.99940
[119]	validation_0-mae:2410.30278
[120]	validation_0-mae:2404.94970
[121]	validation_0-mae:2402.55783
[122]	validation_0-mae:2395.37728
[123]	validation_0-mae:2389.73430
[124]	validation_0-mae:2388.41665
[125]	validation_0-mae:2385.59414
[126]	validation_0-mae:2381.50508
[127]	validation_0-mae:2378.99346
[128]	validation_0-mae:2375.19157
[129]	validation_0-mae:2374.83027
[130]	validation_0-mae:2368.36353
[131]	validation_0-mae:2365.07734
[132]	validation_0-mae:2361.90510
[133]	validation_0-mae:2359.90780
[134]	validation_0-mae:2357.92724
[135]	validation_0-mae:2355.51113
[136]	validation_0-mae:2352.68729
[137]	validation_0-mae:2347.07169
[138]	validation_0-mae:2343.91646
[139]	validation_0-mae:2343.51282
[140]	validation_0-mae:2341.41320
[141]	validation_0-mae:2340.53480
[142]	validation_0-mae:2337.40236
[143]	validation_0-mae:2332.22252
[144]	validation_0-mae:2330.32875
[145]	validation_0-mae:2329.45420
[146]	validation_0-mae:2328.34279
[147]	validation_0-mae:2327.25473
[148]	validation_0-mae:2326.56477
[149]	validation_0-mae:2322.52666
[150]	validation_0-mae:2323.41372
[151]	validation_0-mae:2321.62275
[152]	validation_0-mae:2317.41855
[153]	validation_0-mae:2319.11633
[154]	validation_0-mae:2316.65079
[155]	validation_0-mae:2312.80618
[156]	validation_0-mae:2312.97592
[157]	validation_0-mae:2308.44365
[158]	validation_0-mae:2307.30737
[159]	validation_0-mae:2306.44418
[160]	validation_0-mae:2305.48715
[161]	validation_0-mae:2301.81517
[162]	validation_0-mae:2300.31594
[163]	validation_0-mae:2299.69600
[164]	validation_0-mae:2298.43083
[165]	validation_0-mae:2298.12963
[166]	validation_0-mae:2295.48334
[167]	validation_0-mae:2290.95030
[168]	validation_0-mae:2289.58986
[169]	validation_0-mae:2287.81571
[170]	validation_0-mae:2285.57643
[171]	validation_0-mae:2284.45532
[172]	validation_0-mae:2283.08623
[173]	validation_0-mae:2280.33353
[174]	validation_0-mae:2277.51850
[175]	validation_0-mae:2275.58960
[176]	validation_0-mae:2274.74036
[177]	validation_0-mae:2276.36621
[178]	validation_0-mae:2275.79457
[179]	validation_0-mae:2274.79914
[180]	validation_0-mae:2274.73940
[181]	validation_0-mae:2272.16450
[182]	validation_0-mae:2271.09562
[183]	validation_0-mae:2269.66252
[184]	validation_0-mae:2270.16558
[185]	validation_0-mae:2271.56144
[186]	validation_0-mae:2270.89160
[187]	validation_0-mae:2270.01873
[188]	validation_0-mae:2270.49326
[189]	validation_0-mae:2269.11183
[190]	validation_0-mae:2268.46661
[191]	validation_0-mae:2269.14722
[192]	validation_0-mae:2269.07847
[193]	validation_0-mae:2268.53486
[194]	validation_0-mae:2268.57654
[195]	validation_0-mae:2267.95706
[196]	validation_0-mae:2268.40157
[197]	validation_0-mae:2267.31571
[198]	validation_0-mae:2263.60458
[199]	validation_0-mae:2263.73943
[200]	validation_0-mae:2263.75031
[201]	validation_0-mae:2260.67984
[202]	validation_0-mae:2259.69083
[203]	validation_0-mae:2257.41217
[204]	validation_0-mae:2256.14626
[205]	validation_0-mae:2254.46181
[206]	validation_0-mae:2252.83956
[207]	validation_0-mae:2252.35496
[208]	validation_0-mae:2252.26831
[209]	validation_0-mae:2252.36183
[210]	validation_0-mae:2251.61305
[211]	validation_0-mae:2250.77928
[212]	validation_0-mae:2250.55625
[213]	validation_0-mae:2250.40968
[214]	validation_0-mae:2249.94924
[215]	validation_0-mae:2249.43668
[216]	validation_0-mae:2248.87746
[217]	validation_0-mae:2248.40924
[218]	validation_0-mae:2247.92715
[219]	validation_0-mae:2247.67214
[220]	validation_0-mae:2248.45723
[221]	validation_0-mae:2246.89891
[222]	validation_0-mae:2246.25110
[223]	validation_0-mae:2245.85693
[224]	validation_0-mae:2244.67017
[225]	validation_0-mae:2244.93294
[226]	validation_0-mae:2244.08039
[227]	validation_0-mae:2244.90779
[228]	validation_0-mae:2244.38974
[229]	validation_0-mae:2244.74085
[230]	validation_0-mae:2244.37155
[231]	validation_0-mae:2242.60421
[232]	validation_0-mae:2240.87944
[233]	validation_0-mae:2241.62570
[234]	validation_0-mae:2241.05381
[235]	validation_0-mae:2240.14749
[236]	validation_0-mae:2241.14936
[237]	validation_0-mae:2241.41594
[238]	validation_0-mae:2241.10286
[239]	validation_0-mae:2240.11787
[240]	validation_0-mae:2239.97686
[241]	validation_0-mae:2238.83072
[242]	validation_0-mae:2239.51763
[243]	validation_0-mae:2239.08095
[244]	validation_0-mae:2238.14761
[245]	validation_0-mae:2236.92872
[246]	validation_0-mae:2236.47177
[247]	validation_0-mae:2235.67801
[248]	validation_0-mae:2236.23422
[249]	validation_0-mae:2235.82870
[250]	validation_0-mae:2234.22367
[251]	validation_0-mae:2233.36440
[252]	validation_0-mae:2232.66454
[253]	validation_0-mae:2233.00719
[254]	validation_0-mae:2232.73570
[255]	validation_0-mae:2233.83755
[256]	validation_0-mae:2231.47239
[257]	validation_0-mae:2231.01813
[258]	validation_0-mae:2229.73348
[259]	validation_0-mae:2228.20835
[260]	validation_0-mae:2227.42643
[261]	validation_0-mae:2227.30206
[262]	validation_0-mae:2227.01672
[263]	validation_0-mae:2227.21358
[264]	validation_0-mae:2227.04073
[265]	validation_0-mae:2226.06743
[266]	validation_0-mae:2225.72505
[267]	validation_0-mae:2225.68820
[268]	validation_0-mae:2225.02935
[269]	validation_0-mae:2225.50488
[270]	validation_0-mae:2224.42627
[271]	validation_0-mae:2224.38143
[272]	validation_0-mae:2223.87523
[273]	validation_0-mae:2223.05694
[274]	validation_0-mae:2223.10958
[275]	validation_0-mae:2223.52586
[276]	validation_0-mae:2222.44771
[277]	validation_0-mae:2220.44332
[278]	validation_0-mae:2219.56945
[279]	validation_0-mae:2217.88269
[280]	validation_0-mae:2216.45260
[281]	validation_0-mae:2215.36167
[282]	validation_0-mae:2214.90687
[283]	validation_0-mae:2214.94324
[284]	validation_0-mae:2214.69731
[285]	validation_0-mae:2215.17579
[286]	validation_0-mae:2214.67337
[287]	validation_0-mae:2214.58593
[288]	validation_0-mae:2215.19709
[289]	validation_0-mae:2214.53520
[290]	validation_0-mae:2214.52249
[291]	validation_0-mae:2211.97600
[292]	validation_0-mae:2209.65790
[293]	validation_0-mae:2209.68195
[294]	validation_0-mae:2209.71089
[295]	validation_0-mae:2209.52027
[296]	validation_0-mae:2208.73095
[297]	validation_0-mae:2209.15309
[298]	validation_0-mae:2209.27608
[0]	validation_0-mae:12407.34805
[1]	validation_0-mae:11639.43295
[2]	validation_0-mae:10958.50605
[3]	validation_0-mae:10368.69551
[4]	validation_0-mae:9850.34910
[5]	validation_0-mae:9386.05450
[6]	validation_0-mae:8980.51928
[7]	validation_0-mae:8629.21521
[8]	validation_0-mae:8312.25940
[9]	validation_0-mae:8024.98768
[10]	validation_0-mae:7753.75620
[11]	validation_0-mae:7502.03834
[12]	validation_0-mae:7281.19677
[13]	validation_0-mae:7108.02791
[14]	validation_0-mae:6950.33373
[15]	validation_0-mae:6795.88534
[16]	validation_0-mae:6650.87374
[17]	validation_0-mae:6529.74347

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[0]	validation_0-mae:12414.22606
[1]	validation_0-mae:11657.60115
[2]	validation_0-mae:10981.99888
[3]	validation_0-mae:10334.03061
[4]	validation_0-mae:9774.38899
[5]	validation_0-mae:9251.96072
[6]	validation_0-mae:8790.25406
[7]	validation_0-mae:8383.07927
[8]	validation_0-mae:7998.80780
[9]	validation_0-mae:7640.78989
[10]	validation_0-mae:7325.96295
[11]	validation_0-mae:7031.80758
[12]	validation_0-mae:6753.65453
[13]	validation_0-mae:6470.95688
[14]	validation_0-mae:6214.35220
[15]	validation_0-mae:5977.42675
[16]	validation_0-mae:5771.89894
[17]	validation_0-mae:5548.42623
[18]	validation_0-mae:5373.75618
[19]	validation_0-mae:5202.74264
[20]	validation_0-mae:5034.94175
[21]	validation_0-mae:4882.47906
[22]	validation_0-mae:4748.49615
[23]	validation_0-mae:4606.17086
[24]	validation_0-mae:4479.44929
[25]	validation_0-mae:4359.53810
[26]	validation_0-mae:4262.83843
[27]	validation_0-mae:4142.22556
[28]	validation_0-mae:4038.15325
[29]	validation_0-mae:3957.42546
[30]	validation_0-mae:3863.13513
[31]	validation_0-mae:3789.93177
[32]	validation_0-mae:3706.51035
[33]	validation_0-mae:3634.68627
[34]	validation_0-mae:3569.59210
[35]	validation_0-mae:3499.63117
[36]	validation_0-mae:3443.99147
[37]	validation_0-mae:3388.58852
[38]	validation_0-mae:3340.09553
[39]	validation_0-mae:3279.58756
[40]	validation_0-mae:3230.33810
[41]	validation_0-mae:3187.03844
[42]	validation_0-mae:3152.55968
[43]	validation_0-mae:3119.05501
[44]	validation_0-mae:3086.59277
[45]	validation_0-mae:3056.36783
[46]	validation_0-mae:3022.13594
[47]	validation_0-mae:2982.70004
[48]	validation_0-mae:2960.05629
[49]	validation_0-mae:2932.39710
[50]	validation_0-mae:2910.56506
[51]	validation_0-mae:2884.63793
[52]	validation_0-mae:2865.12558
[53]	validation_0-mae:2838.24914
[54]	validation_0-mae:2824.71189
[55]	validation_0-mae:2808.71033
[56]	validation_0-mae:2781.94954
[57]	validation_0-mae:2757.73025
[58]	validation_0-mae:2739.84707
[59]	validation_0-mae:2725.86577
[60]	validation_0-mae:2705.68758
[61]	validation_0-mae:2682.43383
[62]	validation_0-mae:2668.92819
[63]	validation_0-mae:2657.81954
[64]	validation_0-mae:2647.64857
[65]	validation_0-mae:2637.89566
[66]	validation_0-mae:2620.16657
[67]	validation_0-mae:2608.84606
[68]	validation_0-mae:2598.92464
[69]	validation_0-mae:2577.95174
[70]	validation_0-mae:2570.07511
[71]	validation_0-mae:2563.47208
[72]	validation_0-mae:2556.71357
[73]	validation_0-mae:2547.19464
[74]	validation_0-mae:2535.09758
[75]	validation_0-mae:2522.49552
[76]	validation_0-mae:2511.94140
[77]	validation_0-mae:2506.12966
[78]	validation_0-mae:2488.13476
[79]	validation_0-mae:2474.09470
[80]	validation_0-mae:2466.71621
[81]	validation_0-mae:2461.81139
[82]	validation_0-mae:2455.56879
[83]	validation_0-mae:2448.57835
[84]	validation_0-mae:2435.09115
[85]	validation_0-mae:2429.31167
[86]	validation_0-mae:2422.92115
[87]	validation_0-mae:2416.61440
[88]	validation_0-mae:2410.44273
[89]	validation_0-mae:2400.10250
[90]	validation_0-mae:2393.93348
[91]	validation_0-mae:2391.19980
[92]	validation_0-mae:2381.05954
[93]	validation_0-mae:2376.74662
[94]	validation_0-mae:2365.70616
[95]	validation_0-mae:2359.27360
[96]	validation_0-mae:2350.39314
[97]	validation_0-mae:2346.14047
[98]	validation_0-mae:2344.52762
[99]	validation_0-mae:2338.07326
[100]	validation_0-mae:2331.00080
[101]	validation_0-mae:2329.09177
[102]	validation_0-mae:2324.29774
[103]	validation_0-mae:2317.60890
[104]	validation_0-mae:2314.68870
[105]	validation_0-mae:2310.64747
[106]	validation_0-mae:2311.33519
[107]	validation_0-mae:2304.82139
[108]	validation_0-mae:2302.96399
[109]	validation_0-mae:2299.71177
[110]	validation_0-mae:2295.81805
[111]	validation_0-mae:2294.14886
[112]	validation_0-mae:2289.46864
[113]	validation_0-mae:2287.31548
[114]	validation_0-mae:2283.78094
[115]	validation_0-mae:2281.70591
[116]	validation_0-mae:2279.35477
[117]	validation_0-mae:2272.59275
[118]	validation_0-mae:2268.17178
[119]	validation_0-mae:2266.47554
[120]	validation_0-mae:2263.23689
[121]	validation_0-mae:2261.57057
[122]	validation_0-mae:2257.75200
[123]	validation_0-mae:2256.35221
[124]	validation_0-mae:2253.90525
[125]	validation_0-mae:2253.49995
[126]	validation_0-mae:2251.91316
[127]	validation_0-mae:2253.15083
[128]	validation_0-mae:2249.77804
[129]	validation_0-mae:2249.22210
[130]	validation_0-mae:2248.27469
[131]	validation_0-mae:2248.38114
[132]	validation_0-mae:2246.07044
[133]	validation_0-mae:2245.15816
[134]	validation_0-mae:2243.31546
[135]	validation_0-mae:2241.32157
[136]	validation_0-mae:2237.50575
[137]	validation_0-mae:2235.70481
[138]	validation_0-mae:2233.65151
[139]	validation_0-mae:2231.63402
[140]	validation_0-mae:2227.96607
[141]	validation_0-mae:2228.26549
[142]	validation_0-mae:2227.60441
[143]	validation_0-mae:2226.62426
[144]	validation_0-mae:2223.48033
[145]	validation_0-mae:2222.66927
[146]	validation_0-mae:2220.51678
[147]	validation_0-mae:2217.51065
[148]	validation_0-mae:2216.11867
[149]	validation_0-mae:2214.48624
[150]	validation_0-mae:2214.66979
[151]	validation_0-mae:2214.42515
[152]	validation_0-mae:2214.30793
[153]	validation_0-mae:2212.47647
[154]	validation_0-mae:2210.74965
[155]	validation_0-mae:2210.80827
[156]	validation_0-mae:2210.49060
[157]	validation_0-mae:2208.28988
[158]	validation_0-mae:2207.06337
[159]	validation_0-mae:2206.06913
[160]	validation_0-mae:2205.42838
[161]	validation_0-mae:2206.01016
[162]	validation_0-mae:2206.52160
[163]	validation_0-mae:2206.53222
[164]	validation_0-mae:2205.45417
[165]	validation_0-mae:2205.15980
[166]	validation_0-mae:2204.70272
[167]	validation_0-mae:2204.29033
[168]	validation_0-mae:2204.42612
[169]	validation_0-mae:2204.28081
[170]	validation_0-mae:2204.36204
[171]	validation_0-mae:2203.97579
[172]	validation_0-mae:2202.79755
[173]	validation_0-mae:2203.69376
[174]	validation_0-mae:2204.59587
[175]	validation_0-mae:2204.58603
[176]	validation_0-mae:2203.32841
[177]	validation_0-mae:2201.11431
[178]	validation_0-mae:2202.58434
[179]	validation_0-mae:2201.71427
[180]	validation_0-mae:2198.49032
[181]	validation_0-mae:2197.86936
[182]	validation_0-mae:2197.41277
[183]	validation_0-mae:2195.58898
[184]	validation_0-mae:2196.55155
[185]	validation_0-mae:2194.40577
[186]	validation_0-mae:2194.59115
[187]	validation_0-mae:2194.61730
[188]	validation_0-mae:2193.98283
[189]	validation_0-mae:2192.40034
[190]	validation_0-mae:2192.05962
[191]	validation_0-mae:2193.20195
[192]	validation_0-mae:2192.92436
[193]	validation_0-mae:2193.08484
[194]	validation_0-mae:2190.68577
[195]	validation_0-mae:2190.20424
[196]	validation_0-mae:2190.54299
[197]	validation_0-mae:2190.71937
[198]	validation_0-mae:2190.33288
[199]	validation_0-mae:2189.92872
[200]	validation_0-mae:2189.57803
[201]	validation_0-mae:2190.09305
[202]	validation_0-mae:2188.68536
[203]	validation_0-mae:2188.38679
[204]	validation_0-mae:2188.62835
[205]	validation_0-mae:2187.50808
[206]	validation_0-mae:2185.23474
[207]	validation_0-mae:2186.58626
[208]	validation_0-mae:2186.32196
[209]	validation_0-mae:2184.52942
[210]	validation_0-mae:2184.04751
[211]	validation_0-mae:2183.89678
[212]	validation_0-mae:2183.44986
[213]	validation_0-mae:2182.12844
[214]	validation_0-mae:2180.93870
[215]	validation_0-mae:2181.59638
[216]	validation_0-mae:2178.68835
[217]	validation_0-mae:2178.27642
[218]	validation_0-mae:2176.72432
[219]	validation_0-mae:2175.51167
[220]	validation_0-mae:2174.14368
[221]	validation_0-mae:2175.66883
[222]	validation_0-mae:2176.59084
[223]	validation_0-mae:2177.20652
[224]	validation_0-mae:2176.32065
[225]	validation_0-mae:2174.64088
[226]	validation_0-mae:2174.91834
[227]	validation_0-mae:2174.82905
[228]	validation_0-mae:2174.48699
[229]	validation_0-mae:2174.19934
[230]	validation_0-mae:2171.51224
[231]	validation_0-mae:2171.42057
[232]	validation_0-mae:2170.87900
[233]	validation_0-mae:2170.40197
[234]	validation_0-mae:2170.04383
[235]	validation_0-mae:2168.13464
[236]	validation_0-mae:2167.95890
[237]	validation_0-mae:2166.15794
[238]	validation_0-mae:2166.76960
[239]	validation_0-mae:2166.23747
[240]	validation_0-mae:2166.10139
[241]	validation_0-mae:2166.25699
[242]	validation_0-mae:2165.70873
[243]	validation_0-mae:2164.62984
[244]	validation_0-mae:2163.86200
[245]	validation_0-mae:2163.07165
[246]	validation_0-mae:2163.01817
[247]	validation_0-mae:2162.70392
[248]	validation_0-mae:2162.54240
[249]	validation_0-mae:2163.12533
[250]	validation_0-mae:2163.50186
[251]	validation_0-mae:2163.62702
[252]	validation_0-mae:2163.34927
[253]	validation_0-mae:2162.84682
[254]	validation_0-mae:2163.17856
[255]	validation_0-mae:2163.81362
[256]	validation_0-mae:2164.09822
[257]	validation_0-mae:2164.04536
[258]	validation_0-mae:2163.67512
[259]	validation_0-mae:2163.41307
[260]	validation_0-mae:2163.51301
[261]	validation_0-mae:2164.40055
[262]	validation_0-mae:2164.21503
[263]	validation_0-mae:2163.99690
[264]	validation_0-mae:2164.59944
[265]	validation_0-mae:2164.53586
[266]	validation_0-mae:2163.17065
[267]	validation_0-mae:2162.11699
[268]	validation_0-mae:2162.09030
[269]	validation_0-mae:2162.06883
[270]	validation_0-mae:2162.40701
[271]	validation_0-mae:2161.26375
[272]	validation_0-mae:2160.57495
[273]	validation_0-mae:2159.15709
[274]	validation_0-mae:2157.77532
[275]	validation_0-mae:2158.01949
[276]	validation_0-mae:2157.86923
[277]	validation_0-mae:2157.30921
[278]	validation_0-mae:2157.19112
[279]	validation_0-mae:2155.84359
[280]	validation_0-mae:2154.84669
[281]	validation_0-mae:2155.00326
[282]	validation_0-mae:2154.06304
[283]	validation_0-mae:2154.10987
[284]	validation_0-mae:2153.43134
[285]	validation_0-mae:2152.59335
[286]	validation_0-mae:2152.77419
[287]	validation_0-mae:2153.34479
[288]	validation_0-mae:2153.00721
[289]	validation_0-mae:2152.13208
[290]	validation_0-mae:2153.24396
[291]	validation_0-mae:2153.23603
[292]	validation_0-mae:2154.18642
[293]	validation_0-mae:2154.09202
[294]	validation_0-mae:2152.80572
[295]	validation_0-mae:2151.41813
[296]	validation_0-mae:2150.78312
[297]	validation_0-mae:2150.71847
[298]	validation_0-mae:2149.63639
[299]	validation_0-mae:2149.22732
[300]	validation_0-mae:2149.54240
[301]	validation_0-mae:2149.64761
[302]	validation_0-mae:2149.62310
[303]	validation_0-mae:2149.79959
[304]	validation_0-mae:2147.78427
[305]	validation_0-mae:2147.68039
[306]	validation_0-mae:2147.38206
[307]	validation_0-mae:2147.07683
[308]	validation_0-mae:2145.41350
[309]	validation_0-mae:2143.91762
[310]	validation_0-mae:2143.90694
[311]	validation_0-mae:2143.85365
[312]	validation_0-mae:2144.54569
[313]	validation_0-mae:2142.95096
[314]	validation_0-mae:2141.39897
[315]	validation_0-mae:2141.75032
[316]	validation_0-mae:2140.91673
[317]	validation_0-mae:2139.55511
[318]	validation_0-mae:2139.28380
[319]	validation_0-mae:2138.28913
[320]	validation_0-mae:2138.27234
[321]	validation_0-mae:2138.07217
[322]	validation_0-mae:2137.43849
[323]	validation_0-mae:2137.09131
[324]	validation_0-mae:2136.09763
[325]	validation_0-mae:2136.07330
[326]	validation_0-mae:2135.88189
[327]	validation_0-mae:2135.55584
[328]	validation_0-mae:2134.64990
[329]	validation_0-mae:2134.64081
[330]	validation_0-mae:2133.22883
[331]	validation_0-mae:2133.47752
[332]	validation_0-mae:2132.83169
[333]	validation_0-mae:2132.62086
[334]	validation_0-mae:2132.33764
[335]	validation_0-mae:2132.39312
[336]	validation_0-mae:2132.39237
[337]	validation_0-mae:2131.33321
[338]	validation_0-mae:2130.06423
[339]	validation_0-mae:2128.49501
[340]	validation_0-mae:2128.84683
[341]	validation_0-mae:2127.84213
[342]	validation_0-mae:2126.48839
[343]	validation_0-mae:2126.44012
[344]	validation_0-mae:2126.69708
[345]	validation_0-mae:2126.85030
[346]	validation_0-mae:2126.80611
[347]	validation_0-mae:2127.07025
[348]	validation_0-mae:2127.17737
[349]	validation_0-mae:2126.39701
[350]	validation_0-mae:2125.44124
[351]	validation_0-mae:2125.89567
[352]	validation_0-mae:2125.73389
[353]	validation_0-mae:2125.20243
[354]	validation_0-mae:2125.06995
[355]	validation_0-mae:2125.51641
[356]	validation_0-mae:2125.49925
[357]	validation_0-mae:2124.94156
[358]	validation_0-mae:2123.53626
[359]	validation_0-mae:2123.57936
[360]	validation_0-mae:2123.23820
[361]	validation_0-mae:2123.60462
[362]	validation_0-mae:2123.50299
[363]	validation_0-mae:2123.35106
[364]	validation_0-mae:2123.63969
[365]	validation_0-mae:2122.41794
[366]	validation_0-mae:2121.91957
[367]	validation_0-mae:2121.28624
[368]	validation_0-mae:2121.58355
[369]	validation_0-mae:2121.64507
[370]	validation_0-mae:2121.65671
[371]	validation_0-mae:2121.21914
[372]	validation_0-mae:2120.67413
[373]	validation_0-mae:2120.63067
[374]	validation_0-mae:2121.08452
[375]	validation_0-mae:2121.17846
[376]	validation_0-mae:2121.33423
[377]	validation_0-mae:2121.17172
[378]	validation_0-mae:2121.55164
[379]	validation_0-mae:2121.75542
[380]	validation_0-mae:2120.72641
[381]	validation_0-mae:2121.34756
[382]	validation_0-mae:2120.10387
[383]	validation_0-mae:2119.04258
[384]	validation_0-mae:2119.27136
[385]	validation_0-mae:2119.86806
[386]	validation_0-mae:2119.22706
[387]	validation_0-mae:2119.56931
[388]	validation_0-mae:2120.00792
[389]	validation_0-mae:2120.42268
[390]	validation_0-mae:2120.28073
[391]	validation_0-mae:2119.45301
[392]	validation_0-mae:2119.36317
[393]	validation_0-mae:2119.38014
[394]	validation_0-mae:2119.75538
[395]	validation_0-mae:2119.78078
[396]	validation_0-mae:2119.86630
[397]	validation_0-mae:2120.25385
[398]	validation_0-mae:2119.14403
[399]	validation_0-mae:2118.65947
[400]	validation_0-mae:2118.06397
[401]	validation_0-mae:2117.97280
[402]	validation_0-mae:2118.42064
[403]	validation_0-mae:2118.39222
[404]	validation_0-mae:2118.72171
[405]	validation_0-mae:2118.60363
[406]	validation_0-mae:2119.11032
[407]	validation_0-mae:2118.60984
[408]	validation_0-mae:2118.87720
[409]	validation_0-mae:2117.88573
[410]	validation_0-mae:2117.90363
[411]	validation_0-mae:2117.66675
[412]	validation_0-mae:2117.05763
[413]	validation_0-mae:2116.82686
[414]	validation_0-mae:2116.59855
[415]	validation_0-mae:2116.62510
[416]	validation_0-mae:2116.60241
[417]	validation_0-mae:2116.99153
[418]	validation_0-mae:2116.99368
[419]	validation_0-mae:2117.08309
[420]	validation_0-mae:2117.07247
[421]	validation_0-mae:2117.69431
[422]	validation_0-mae:2117.71619
[423]	validation_0-mae:2117.90154
[424]	validation_0-mae:2118.09134
[425]	validation_0-mae:2117.36747
[426]	validation_0-mae:2117.24516
[427]	validation_0-mae:2116.87096
[428]	validation_0-mae:2117.09148
[429]	validation_0-mae:2117.38209
[430]	validation_0-mae:2117.57744
[431]	validation_0-mae:2117.85553
[432]	validation_0-mae:2116.68894
[433]	validation_0-mae:2116.44260
[434]	validation_0-mae:2116.54425
[435]	validation_0-mae:2117.04129
[436]	validation_0-mae:2115.34970
[437]	validation_0-mae:2114.94521
[438]	validation_0-mae:2115.07857
[439]	validation_0-mae:2114.95765
[440]	validation_0-mae:2115.27788
[441]	validation_0-mae:2114.63045
[442]	validation_0-mae:2114.38458
[443]	validation_0-mae:2114.71871
[444]	validation_0-mae:2114.90704
[445]	validation_0-mae:2114.68658
[446]	validation_0-mae:2114.29316
[447]	validation_0-mae:2114.42105
[448]	validation_0-mae:2113.61533
[449]	validation_0-mae:2113.36259
[450]	validation_0-mae:2112.85139
[451]	validation_0-mae:2112.74907
[452]	validation_0-mae:2112.88601
[453]	validation_0-mae:2113.03378
[454]	validation_0-mae:2113.07201
[455]	validation_0-mae:2113.22183
[456]	validation_0-mae:2113.24841
[457]	validation_0-mae:2113.08780
[458]	validation_0-mae:2112.91475
[459]	validation_0-mae:2112.67641
[460]	validation_0-mae:2112.56019
[461]	validation_0-mae:2111.99387
[462]	validation_0-mae:2111.23912
[463]	validation_0-mae:2111.09110
[464]	validation_0-mae:2110.97858
[465]	validation_0-mae:2110.73512
[466]	validation_0-mae:2111.10942
[467]	validation_0-mae:2111.46883
[468]	validation_0-mae:2111.84326
[469]	validation_0-mae:2111.87241
[470]	validation_0-mae:2111.41042
[471]	validation_0-mae:2111.14846
[472]	validation_0-mae:2110.80442
[473]	validation_0-mae:2110.31357
[474]	validation_0-mae:2110.42025
[475]	validation_0-mae:2110.41054
[476]	validation_0-mae:2110.71676
[477]	validation_0-mae:2110.75603
[478]	validation_0-mae:2109.71194
[479]	validation_0-mae:2109.71258
[480]	validation_0-mae:2109.91878
[481]	validation_0-mae:2109.80789
[482]	validation_0-mae:2109.88330
[483]	validation_0-mae:2110.01217
[484]	validation_0-mae:2109.39528
[485]	validation_0-mae:2108.93465
[486]	validation_0-mae:2109.01016
[487]	validation_0-mae:2108.57079
[488]	validation_0-mae:2109.15338
[489]	validation_0-mae:2109.37758
[490]	validation_0-mae:2109.25970
[491]	validation_0-mae:2109.56827
[492]	validation_0-mae:2109.41712
[493]	validation_0-mae:2109.60144
[494]	validation_0-mae:2109.58585
[495]	validation_0-mae:2109.74081
[496]	validation_0-mae:2109.28068
[497]	validation_0-mae:2109.00793
[498]	validation_0-mae:2108.97226
[499]	validation_0-mae:2108.45201
[500]	validation_0-mae:2108.74375
[501]	validation_0-mae:2108.40837
[502]	validation_0-mae:2108.49908
[503]	validation_0-mae:2107.72254
[504]	validation_0-mae:2107.52959
[505]	validation_0-mae:2107.42972
[506]	validation_0-mae:2107.37932
[507]	validation_0-mae:2107.26909
[508]	validation_0-mae:2106.99563
[509]	validation_0-mae:2106.72025
[510]	validation_0-mae:2106.65407
[511]	validation_0-mae:2105.44195
[512]	validation_0-mae:2105.54611
[513]	validation_0-mae:2105.90529
[514]	validation_0-mae:2105.35334
[515]	validation_0-mae:2105.59092
[516]	validation_0-mae:2105.32106
[517]	validation_0-mae:2105.48934
[518]	validation_0-mae:2105.55561
[519]	validation_0-mae:2105.87818
[520]	validation_0-mae:2105.86578
[521]	validation_0-mae:2105.59182
[522]	validation_0-mae:2105.76647
[523]	validation_0-mae:2105.19451
[524]	validation_0-mae:2104.86548
[525]	validation_0-mae:2105.41980
[526]	validation_0-mae:2105.08859
[527]	validation_0-mae:2105.59933
[528]	validation_0-mae:2105.62835
[529]	validation_0-mae:2105.03737
[530]	validation_0-mae:2104.93757
[531]	validation_0-mae:2104.78967
[532]	validation_0-mae:2105.10667
[533]	validation_0-mae:2104.86878
[534]	validation_0-mae:2105.90036
[535]	validation_0-mae:2106.02791
[536]	validation_0-mae:2105.86763
[537]	validation_0-mae:2105.23790
[538]	validation_0-mae:2105.47118
[539]	validation_0-mae:2104.84761
[540]	validation_0-mae:2104.89083
[541]	validation_0-mae:2104.57297
[542]	validation_0-mae:2104.83089
[543]	validation_0-mae:2104.96396
[544]	validation_0-mae:2104.53225
[545]	validation_0-mae:2104.47169
[546]	validation_0-mae:2104.41703
[547]	validation_0-mae:2104.37989
[548]	validation_0-mae:2104.07975
[549]	validation_0-mae:2104.36836
[550]	validation_0-mae:2103.19481
[551]	validation_0-mae:2103.11121
[552]	validation_0-mae:2102.97747
[553]	validation_0-mae:2103.01406
[554]	validation_0-mae:2102.92601
[555]	validation_0-mae:2103.26489
[556]	validation_0-mae:2103.21806
[557]	validation_0-mae:2102.32744
[558]	validation_0-mae:2102.30188
[559]	validation_0-mae:2102.25607
[560]	validation_0-mae:2102.27176
[561]	validation_0-mae:2102.36260
[562]	validation_0-mae:2102.17620
[563]	validation_0-mae:2102.29178
[564]	validation_0-mae:2102.28255
[565]	validation_0-mae:2102.12691
[566]	validation_0-mae:2102.08237
[567]	validation_0-mae:2102.16326
[568]	validation_0-mae:2102.43520
[569]	validation_0-mae:2102.70352
[570]	validation_0-mae:2102.81588
[571]	validation_0-mae:2102.68945
[572]	validation_0-mae:2101.70107
[573]	validation_0-mae:2101.59983
[574]	validation_0-mae:2101.69138
[575]	validation_0-mae:2101.62481
[576]	validation_0-mae:2101.17438
[577]	validation_0-mae:2101.03940
[578]	validation_0-mae:2101.14947
[579]	validation_0-mae:2101.32318
[580]	validation_0-mae:2100.95902
[581]	validation_0-mae:2101.13031
[582]	validation_0-mae:2100.83929
[583]	validation_0-mae:2101.07235
[584]	validation_0-mae:2100.81052
[585]	validation_0-mae:2100.76426
[586]	validation_0-mae:2100.74116
[587]	validation_0-mae:2100.33446
[588]	validation_0-mae:2100.23207
[589]	validation_0-mae:2099.83038
[590]	validation_0-mae:2099.81713

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[41]	validation_0-mae:3226.34563
[42]	validation_0-mae:3181.58614
[43]	validation_0-mae:3143.99276
[44]	validation_0-mae:3112.65509
[45]	validation_0-mae:3084.89922
[46]	validation_0-mae:3048.10718
[47]	validation_0-mae:3016.78215
[48]	validation_0-mae:2988.90780
[49]	validation_0-mae:2954.34609
[50]	validation_0-mae:2929.77684
[51]	validation_0-mae:2908.00937
[52]	validation_0-mae:2874.76441
[53]	validation_0-mae:2855.07869
[54]	validation_0-mae:2831.77699
[55]	validation_0-mae:2806.29939
[56]	validation_0-mae:2772.93831
[57]	validation_0-mae:2747.70749
[58]	validation_0-mae:2733.84575
[59]	validation_0-mae:2711.18565
[60]	validation_0-mae:2701.13499
[61]	validation_0-mae:2688.16324
[62]	validation_0-mae:2673.97705
[63]	validation_0-mae:2664.87006
[64]	validation_0-mae:2654.14810
[65]	validation_0-mae:2637.79588
[66]	validation_0-mae:2626.50073
[67]	validation_0-mae:2615.01679
[68]	validation_0-mae:2599.48376
[69]	validation_0-mae:2588.28645
[70]	validation_0-mae:2578.23534
[71]	validation_0-mae:2564.28840
[72]	validation_0-mae:2558.92486
[73]	validation_0-mae:2550.68656
[74]	validation_0-mae:2537.78048
[75]	validation_0-mae:2529.73937
[76]	validation_0-mae:2522.03864
[77]	validation_0-mae:2515.95902
[78]	validation_0-mae:2504.91313
[79]	validation_0-mae:2496.34075
[80]	validation_0-mae:2490.42934
[81]	validation_0-mae:2483.33942
[82]	validation_0-mae:2471.11573
[83]	validation_0-mae:2464.05164
[84]	validation_0-mae:2460.00014
[85]	validation_0-mae:2457.90941
[86]	validation_0-mae:2451.29098
[87]	validation_0-mae:2441.72081
[88]	validation_0-mae:2437.42413
[89]	validation_0-mae:2433.97365
[90]	validation_0-mae:2429.20862
[91]	validation_0-mae:2421.41286
[92]	validation_0-mae:2415.43046
[93]	validation_0-mae:2410.23401
[94]	validation_0-mae:2406.03984
[95]	validation_0-mae:2400.92674
[96]	validation_0-mae:2396.37827
[97]	validation_0-mae:2390.11902
[98]	validation_0-mae:2384.82697
[99]	validation_0-mae:2378.65074
[100]	validation_0-mae:2375.88280
[101]	validation_0-mae:2370.59549
[102]	validation_0-mae:2368.76622
[103]	validation_0-mae:2363.87110
[104]	validation_0-mae:2359.30527
[105]	validation_0-mae:2357.07018
[106]	validation_0-mae:2352.53894
[107]	validation_0-mae:2347.41834
[108]	validation_0-mae:2344.35382
[109]	validation_0-mae:2338.10782
[110]	validation_0-mae:2335.04439
[111]	validation_0-mae:2334.41238
[112]	validation_0-mae:2331.17005
[113]	validation_0-mae:2325.52415
[114]	validation_0-mae:2320.37175
[115]	validation_0-mae:2313.27920
[116]	validation_0-mae:2309.80068
[117]	validation_0-mae:2303.05581
[118]	validation_0-mae:2303.35017
[119]	validation_0-mae:2297.58217
[120]	validation_0-mae:2295.67871
[121]	validation_0-mae:2292.59291
[122]	validation_0-mae:2291.82008
[123]	validation_0-mae:2289.84396
[124]	validation_0-mae:2289.32285
[125]	validation_0-mae:2288.31109
[126]	validation_0-mae:2285.54425
[127]	validation_0-mae:2282.10916
[128]	validation_0-mae:2278.53327
[129]	validation_0-mae:2272.79704
[130]	validation_0-mae:2271.86379
[131]	validation_0-mae:2270.80429
[132]	validation_0-mae:2265.08600
[133]	validation_0-mae:2265.41816
[134]	validation_0-mae:2264.35129
[135]	validation_0-mae:2263.92167
[136]	validation_0-mae:2263.66461
[137]	validation_0-mae:2262.14403
[138]	validation_0-mae:2259.98980
[139]	validation_0-mae:2256.15087
[140]	validation_0-mae:2254.31349
[141]	validation_0-mae:2252.76218
[142]	validation_0-mae:2252.40362
[143]	validation_0-mae:2252.07209
[144]	validation_0-mae:2248.47171
[145]	validation_0-mae:2246.32182
[146]	validation_0-mae:2242.58215
[147]	validation_0-mae:2241.42962
[148]	validation_0-mae:2241.89477
[149]	validation_0-mae:2240.26642
[150]	validation_0-mae:2239.99604
[151]	validation_0-mae:2236.40029
[152]	validation_0-mae:2232.36580
[153]	validation_0-mae:2231.86771
[154]	validation_0-mae:2231.53145
[155]	validation_0-mae:2229.75563
[156]	validation_0-mae:2227.16143
[157]	validation_0-mae:2225.99667
[158]	validation_0-mae:2223.38918
[159]	validation_0-mae:2221.12205
[160]	validation_0-mae:2219.70188
[161]	validation_0-mae:2218.76224
[162]	validation_0-mae:2219.18300
[163]	validation_0-mae:2217.86845
[164]	validation_0-mae:2216.94023
[165]	validation_0-mae:2215.34501
[166]	validation_0-mae:2213.76665
[167]	validation_0-mae:2213.27687
[168]	validation_0-mae:2211.11210
[169]	validation_0-mae:2207.80013
[170]	validation_0-mae:2207.20635
[171]	validation_0-mae:2208.06327
[172]	validation_0-mae:2208.27413
[173]	validation_0-mae:2206.40183
[174]	validation_0-mae:2206.15134
[175]	validation_0-mae:2205.73762
[176]	validation_0-mae:2206.07125
[177]	validation_0-mae:2204.09486
[178]	validation_0-mae:2202.67323
[179]	validation_0-mae:2202.61418
[180]	validation_0-mae:2202.18547
[181]	validation_0-mae:2199.41053
[182]	validation_0-mae:2198.41679
[183]	validation_0-mae:2197.39497
[184]	validation_0-mae:2197.22919
[185]	validation_0-mae:2196.39794
[186]	validation_0-mae:2193.63793
[187]	validation_0-mae:2192.75012
[188]	validation_0-mae:2192.84415
[189]	validation_0-mae:2192.03411
[190]	validation_0-mae:2190.20842
[191]	validation_0-mae:2189.82982
[192]	validation_0-mae:2188.18533
[193]	validation_0-mae:2188.20705
[194]	validation_0-mae:2185.86790
[195]	validation_0-mae:2184.67753
[196]	validation_0-mae:2184.17125
[197]	validation_0-mae:2182.99781
[198]	validation_0-mae:2182.92412
[199]	validation_0-mae:2181.07327
[200]	validation_0-mae:2181.10828
[201]	validation_0-mae:2180.95264
[202]	validation_0-mae:2179.15858
[203]	validation_0-mae:2178.55026
[204]	validation_0-mae:2178.42513
[205]	validation_0-mae:2177.80613
[206]	validation_0-mae:2177.87292
[207]	validation_0-mae:2175.50665
[208]	validation_0-mae:2175.08112
[209]	validation_0-mae:2173.79933
[210]	validation_0-mae:2172.77850
[211]	validation_0-mae:2171.67003
[212]	validation_0-mae:2170.26046
[213]	validation_0-mae:2169.35673
[214]	validation_0-mae:2169.57350
[215]	validation_0-mae:2168.89705
[216]	validation_0-mae:2168.48976
[217]	validation_0-mae:2167.38669
[218]	validation_0-mae:2166.30244
[219]	validation_0-mae:2165.43347
[220]	validation_0-mae:2163.89785
[221]	validation_0-mae:2163.12442
[222]	validation_0-mae:2164.37114
[223]	validation_0-mae:2163.91275
[224]	validation_0-mae:2164.70635
[225]	validation_0-mae:2163.77529
[226]	validation_0-mae:2164.13981
[227]	validation_0-mae:2162.91712
[228]	validation_0-mae:2162.95441
[229]	validation_0-mae:2164.58487
[230]	validation_0-mae:2163.23342
[231]	validation_0-mae:2162.32212
[232]	validation_0-mae:2162.17853
[233]	validation_0-mae:2161.34991
[234]	validation_0-mae:2161.49467
[235]	validation_0-mae:2160.86529
[236]	validation_0-mae:2159.05831
[237]	validation_0-mae:2158.16717
[238]	validation_0-mae:2156.89001
[239]	validation_0-mae:2156.95376
[240]	validation_0-mae:2157.34332
[241]	validation_0-mae:2157.44170
[242]	validation_0-mae:2157.05885
[243]	validation_0-mae:2156.85071
[244]	validation_0-mae:2156.85531
[245]	validation_0-mae:2156.59721
[246]	validation_0-mae:2156.49415
[247]	validation_0-mae:2153.19251
[248]	validation_0-mae:2152.00260
[249]	validation_0-mae:2150.69022
[250]	validation_0-mae:2151.47932
[251]	validation_0-mae:2150.99614
[252]	validation_0-mae:2150.28088
[253]	validation_0-mae:2151.10422
[254]	validation_0-mae:2151.44683
[255]	validation_0-mae:2152.29077
[256]	validation_0-mae:2153.38445
[257]	validation_0-mae:2154.12994
[258]	validation_0-mae:2152.84910
[259]	validation_0-mae:2153.18899
[260]	validation_0-mae:2153.12431
[261]	validation_0-mae:2150.85317
[262]	validation_0-mae:2150.03776
[263]	validation_0-mae:2149.54273
[264]	validation_0-mae:2148.99522
[265]	validation_0-mae:2147.98189
[266]	validation_0-mae:2145.89560
[267]	validation_0-mae:2145.94077
[268]	validation_0-mae:2145.20574
[269]	validation_0-mae:2143.86079
[270]	validation_0-mae:2143.86690
[271]	validation_0-mae:2143.15200
[272]	validation_0-mae:2142.46988
[273]	validation_0-mae:2141.34439
[274]	validation_0-mae:2141.32730
[275]	validation_0-mae:2140.60197
[276]	validation_0-mae:2140.30142
[277]	validation_0-mae:2139.21839
[278]	validation_0-mae:2139.06370
[279]	validation_0-mae:2137.65607
[280]	validation_0-mae:2137.57998
[281]	validation_0-mae:2137.36892
[282]	validation_0-mae:2137.43862
[283]	validation_0-mae:2137.02527
[284]	validation_0-mae:2136.71244
[285]	validation_0-mae:2136.23622
[286]	validation_0-mae:2136.20889
[287]	validation_0-mae:2135.36569
[288]	validation_0-mae:2135.63104
[289]	validation_0-mae:2135.01972
[290]	validation_0-mae:2135.25734
[291]	validation_0-mae:2135.04776
[292]	validation_0-mae:2134.71954
[293]	validation_0-mae:2134.72443
[294]	validation_0-mae:2133.49857
[295]	validation_0-mae:2132.59678
[296]	validation_0-mae:2132.58880
[297]	validation_0-mae:2131.18294
[298]	validation_0-mae:2130.02572
[299]	validation_0-mae:2131.05057
[300]	validation_0-mae:2129.17481
[301]	validation_0-mae:2128.95195
[302]	validation_0-mae:2127.86847
[303]	validation_0-mae:2127.88302
[304]	validation_0-mae:2127.21271
[305]	validation_0-mae:2127.64626
[306]	validation_0-mae:2128.44941
[307]	validation_0-mae:2128.05432
[308]	validation_0-mae:2128.49706
[309]	validation_0-mae:2128.13260
[310]	validation_0-mae:2128.05750
[311]	validation_0-mae:2126.40538
[312]	validation_0-mae:2126.98624
[313]	validation_0-mae:2126.67415
[314]	validation_0-mae:2126.74272
[315]	validation_0-mae:2125.60562
[316]	validation_0-mae:2124.22566
[317]	validation_0-mae:2124.82695
[318]	validation_0-mae:2123.83832
[319]	validation_0-mae:2123.52083
[320]	validation_0-mae:2122.58614
[321]	validation_0-mae:2121.88436
[322]	validation_0-mae:2121.65417
[323]	validation_0-mae:2122.04592
[324]	validation_0-mae:2121.98026
[325]	validation_0-mae:2121.82710
[326]	validation_0-mae:2121.69394
[327]	validation_0-mae:2121.70862
[328]	validation_0-mae:2121.69508
[329]	validation_0-mae:2121.33892
[330]	validation_0-mae:2121.06544
[331]	validation_0-mae:2120.59927
[332]	validation_0-mae:2120.38539
[333]	validation_0-mae:2120.44097
[334]	validation_0-mae:2120.61903
[335]	validation_0-mae:2120.65271
[336]	validation_0-mae:2120.49667
[337]	validation_0-mae:2120.37937
[338]	validation_0-mae:2119.42762
[339]	validation_0-mae:2118.50549
[340]	validation_0-mae:2118.40572
[341]	validation_0-mae:2117.79758
[342]	validation_0-mae:2117.60874
[343]	validation_0-mae:2114.79510
[344]	validation_0-mae:2113.24310
[345]	validation_0-mae:2112.99234
[346]	validation_0-mae:2112.75558
[347]	validation_0-mae:2112.51550
[348]	validation_0-mae:2112.33231
[349]	validation_0-mae:2111.29185
[350]	validation_0-mae:2110.08476
[351]	validation_0-mae:2110.85352
[352]	validation_0-mae:2110.57000
[353]	validation_0-mae:2110.23424
[354]	validation_0-mae:2109.63914
[355]	validation_0-mae:2109.01709
[356]	validation_0-mae:2108.73728
[357]	validation_0-mae:2107.23199
[358]	validation_0-mae:2107.68943
[359]	validation_0-mae:2107.74129
[360]	validation_0-mae:2107.64451
[361]	validation_0-mae:2107.83511
[362]	validation_0-mae:2107.67701
[363]	validation_0-mae:2107.68879
[364]	validation_0-mae:2108.15871
[365]	validation_0-mae:2108.52701
[366]	validation_0-mae:2108.34134
[367]	validation_0-mae:2108.55929
[368]	validation_0-mae:2108.05136
[369]	validation_0-mae:2107.65441
[370]	validation_0-mae:2107.68347
[371]	validation_0-mae:2107.70220
[372]	validation_0-mae:2107.35025
[373]	validation_0-mae:2106.92385
[374]	validation_0-mae:2106.94746
[375]	validation_0-mae:2106.89800
[376]	validation_0-mae:2105.64455
[377]	validation_0-mae:2104.24271
[378]	validation_0-mae:2103.19579
[379]	validation_0-mae:2101.75671
[380]	validation_0-mae:2102.01854
[381]	validation_0-mae:2102.28149
[382]	validation_0-mae:2101.23791
[383]	validation_0-mae:2101.19683
[384]	validation_0-mae:2101.65652
[385]	validation_0-mae:2101.56306
[386]	validation_0-mae:2100.08049
[387]	validation_0-mae:2099.71725
[388]	validation_0-mae:2100.07191
[389]	validation_0-mae:2100.02811
[390]	validation_0-mae:2099.11150
[391]	validation_0-mae:2098.87040
[392]	validation_0-mae:2098.79558
[393]	validation_0-mae:2098.57177
[394]	validation_0-mae:2098.57514
[395]	validation_0-mae:2098.18939
[396]	validation_0-mae:2097.97819
[397]	validation_0-mae:2098.34506
[398]	validation_0-mae:2098.48143
[399]	validation_0-mae:2098.64306
[400]	validation_0-mae:2097.55432
[401]	validation_0-mae:2097.23074
[402]	validation_0-mae:2097.07854
[403]	validation_0-mae:2097.09392
[404]	validation_0-mae:2096.89206
[405]	validation_0-mae:2096.77157
[406]	validation_0-mae:2097.04407
[407]	validation_0-mae:2096.72824
[408]	validation_0-mae:2096.65123
[409]	validation_0-mae:2096.01317
[410]	validation_0-mae:2096.30245
[411]	validation_0-mae:2096.38513
[412]	validation_0-mae:2096.13250
[413]	validation_0-mae:2096.65502
[414]	validation_0-mae:2097.06479
[415]	validation_0-mae:2097.39222
[416]	validation_0-mae:2097.23339
[417]	validation_0-mae:2097.52011
[418]	validation_0-mae:2097.26656
[419]	validation_0-mae:2097.49214
[420]	validation_0-mae:2096.81847
[421]	validation_0-mae:2096.50932
[422]	validation_0-mae:2096.79629
[423]	validation_0-mae:2095.80664
[424]	validation_0-mae:2096.18481
[425]	validation_0-mae:2096.12416
[426]	validation_0-mae:2096.61589
[427]	validation_0-mae:2096.98789
[428]	validation_0-mae:2096.02389
[429]	validation_0-mae:2095.68510
[430]	validation_0-mae:2095.73779
[431]	validation_0-mae:2095.00870
[432]	validation_0-mae:2094.80910
[433]	validation_0-mae:2094.97150
[434]	validation_0-mae:2095.04578
[435]	validation_0-mae:2095.61841
[436]	validation_0-mae:2095.76947
[437]	validation_0-mae:2096.02636
[438]	validation_0-mae:2095.13527
[439]	validation_0-mae:2095.07167
[440]	validation_0-mae:2095.28582
[441]	validation_0-mae:2095.33847
[442]	validation_0-mae:2095.30076
[443]	validation_0-mae:2095.64474
[444]	validation_0-mae:2095.90115
[445]	validation_0-mae:2095.62078
[446]	validation_0-mae:2095.19075
[447]	validation_0-mae:2095.29650
[448]	validation_0-mae:2095.34754
[449]	validation_0-mae:2095.48076
[450]	validation_0-mae:2095.56147
[451]	validation_0-mae:2095.67184
[452]	validation_0-mae:2096.03457
[453]	validation_0-mae:2095.94665
[454]	validation_0-mae:2095.58339
[455]	validation_0-mae:2095.69081
[456]	validation_0-mae:2095.44669
[457]	validation_0-mae:2095.49622
[458]	validation_0-mae:2095.25342
[459]	validation_0-mae:2094.58587
[460]	validation_0-mae:2094.63381
[461]	validation_0-mae:2095.32299
[462]	validation_0-mae:2095.15187
[463]	validation_0-mae:2095.06823
[464]	validation_0-mae:2094.16134
[465]	validation_0-mae:2093.66477
[466]	validation_0-mae:2093.86819
[467]	validation_0-mae:2093.62164
[468]	validation_0-mae:2093.73205
[469]	validation_0-mae:2093.93046
[470]	validation_0-mae:2093.72572
[471]	validation_0-mae:2093.88235
[472]	validation_0-mae:2094.37068
[473]	validation_0-mae:2094.26386
[474]	validation_0-mae:2094.32124
[475]	validation_0-mae:2094.61509
[476]	validation_0-mae:2094.25906
[477]	validation_0-mae:2094.62729
[478]	validation_0-mae:2094.65381
[479]	validation_0-mae:2094.62639
[480]	validation_0-mae:2093.80812
[481]	validation_0-mae:2093.85717
[482]	validation_0-mae:2094.28269
[483]	validation_0-mae:2094.08602
[484]	validation_0-mae:2094.26808
[485]	validation_0-mae:2094.48246
[486]	validation_0-mae:2094.33127
[487]	validation_0-mae:2094.35900
[488]	validation_0-mae:2094.33971
[489]	validation_0-mae:2093.92508
[490]	validation_0-mae:2094.27133
[491]	validation_0-mae:2092.92260
[492]	validation_0-mae:2092.89640
[493]	validation_0-mae:2093.19980
[494]	validation_0-mae:2092.26221
[495]	validation_0-mae:2091.76019
[496]	validation_0-mae:2091.79143
[497]	validation_0-mae:2091.74562
[498]	validation_0-mae:2091.11107
[499]	validation_0-mae:2090.85206
[500]	validation_0-mae:2090.47002
[501]	validation_0-mae:2090.75665
[502]	validation_0-mae:2090.79396
[503]	validation_0-mae:2090.45479
[504]	validation_0-mae:2090.49757
[505]	validation_0-mae:2091.09157
[506]	validation_0-mae:2090.61719
[507]	validation_0-mae:2090.51710
[508]	validation_0-mae:2090.25377
[509]	validation_0-mae:2089.27603
[510]	validation_0-mae:2089.38197
[511]	validation_0-mae:2089.41705
[512]	validation_0-mae:2089.17973
[513]	validation_0-mae:2089.23712
[514]	validation_0-mae:2089.26638
[515]	validation_0-mae:2088.28822
[516]	validation_0-mae:2088.63030
[517]	validation_0-mae:2088.70126
[518]	validation_0-mae:2088.83267
[519]	validation_0-mae:2089.39938
[520]	validation_0-mae:2089.44025
[521]	validation_0-mae:2089.18055
[522]	validation_0-mae:2089.63626
[523]	validation_0-mae:2089.63335
[524]	validation_0-mae:2089.39088
[525]	validation_0-mae:2089.29259
[526]	validation_0-mae:2088.94833
[527]	validation_0-mae:2088.83047
[528]	validation_0-mae:2088.53258
[529]	validation_0-mae:2088.92009
[530]	validation_0-mae:2088.56333
[531]	validation_0-mae:2088.60560
[532]	validation_0-mae:2088.46113
[533]	validation_0-mae:2088.21116
[534]	validation_0-mae:2088.58166
[535]	validation_0-mae:2088.40853
[536]	validation_0-mae:2088.93228
[537]	validation_0-mae:2089.08869
[538]	validation_0-mae:2089.00635
[539]	validation_0-mae:2089.66260
[540]	validation_0-mae:2089.58053
[541]	validation_0-mae:2089.81168
[542]	validation_0-mae:2089.08157
[543]	validation_0-mae:2088.97970
[544]	validation_0-mae:2089.19579
[545]	validation_0-mae:2088.86755
[546]	validation_0-mae:2088.90089
[547]	validation_0-mae:2089.20842
[548]	validation_0-mae:2089.54331
[549]	validation_0-mae:2089.64297
[550]	validation_0-mae:2089.99718
[551]	validation_0-mae:2090.27045
[552]	validation_0-mae:2089.91110
[553]	validation_0-mae:2090.16619
[554]	validation_0-mae:2090.40432
[555]	validation_0-mae:2090.40814
[556]	validation_0-mae:2089.42636
[557]	validation_0-mae:2089.59638
[558]	validation_0-mae:2089.57695
[559]	validation_0-mae:2089.22855
[560]	validation_0-mae:2089.28974
[561]	validation_0-mae:2089.51703
[562]	validation_0-mae:2089.70691
[563]	validation_0-mae:2087.88494
[564]	validation_0-mae:2087.52518
[565]	validation_0-mae:2087.75317
[566]	validation_0-mae:2087.42697
[567]	validation_0-mae:2087.66261
[568]	validation_0-mae:2087.84115
[569]	validation_0-mae:2087.76928
[570]	validation_0-mae:2087.86869
[571]	validation_0-mae:2087.57482
[572]	validation_0-mae:2087.60844
[573]	validation_0-mae:2087.74515
[574]	validation_0-mae:2087.91133
[575]	validation_0-mae:2088.05030
[576]	validation_0-mae:2088.30851
[577]	validation_0-mae:2087.92637
[578]	validation_0-mae:2088.34343
[579]	validation_0-mae:2088.03702
[580]	validation_0-mae:2088.16213
[581]	validation_0-mae:2088.32955
[582]	validation_0-mae:2088.52314
[583]	validation_0-mae:2088.85723
[584]	validation_0-mae:2089.34553
[585]	validation_0-mae:2089.39229
[586]	validation_0-mae:2087.49309
[587]	validation_0-mae:2087.49036
[588]	validation_0-mae:2087.50860
[589]	validation_0-mae:2085.99829
[590]	validation_0-mae:2086.55465
[591]	validation_0-mae:2086.39651
[592]	validation_0-mae:2086.95476
[593]	validation_0-mae:2086.89098
[594]	validation_0-mae:2086.85242
[595]	validation_0-mae:2087.41913
[596]	validation_0-mae:2087.89783
[597]	validation_0-mae:2088.03316
[598]	validation_0-mae:2088.36193
[599]	validation_0-mae:2088.50350
[600]	validation_0-mae:2088.64368
[601]	validation_0-mae:2087.98627
[602]	validation_0-mae:2087.74441
[603]	validation_0-mae:2087.71721
[604]	validation_0-mae:2087.84115
[605]	validation_0-mae:2087.96197
[606]	validation_0-mae:2087.84948
[607]	validation_0-mae:2087.70731
[608]	validation_0-mae:2087.52832
[609]	validation_0-mae:2087.59746
[610]	validation_0-mae:2087.56901
[611]	validation_0-mae:2087.65202
[612]	validation_0-mae:2087.91097
[613]	validation_0-mae:2087.75531
[614]	validation_0-mae:2087.60870
[615]	validation_0-mae:2087.69928
[616]	validation_0-mae:2087.52403
[617]	validation_0-mae:2087.60881
[618]	validation_0-mae:2087.72518
[619]	validation_0-mae:2087.77130
[620]	validation_0-mae:2087.40299
[621]	validation_0-mae:2087.57569
[622]	validation_0-mae:2087.59373
[0]	validation_0-mae:12443.47730
[1]	validation_0-mae:11717.98035
[2]	validation_0-mae:11063.76394
[3]	validation_0-mae:10492.62453
[4]	validation_0-mae:9980.80920
[5]	validation_0-mae:9533.64376
[6]	validation_0-mae:9138.36700
[7]	validation_0-mae:8788.46124

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[7]	validation_0-mae:8731.29158
[8]	validation_0-mae:8385.23965
[9]	validation_0-mae:8104.59357
[10]	validation_0-mae:7839.77024
[11]	validation_0-mae:7590.68906
[12]	validation_0-mae:7387.00101
[13]	validation_0-mae:7206.59350
[14]	validation_0-mae:7024.08829
[15]	validation_0-mae:6869.30582
[0]	validation_0-mae:12406.78773
[1]	validation_0-mae:11642.14056
[2]	validation_0-mae:10953.54534
[3]	validation_0-mae:10346.99745
[4]	validation_0-mae:9806.39816
[5]	validation_0-mae:9310.12420
[6]	validation_0-mae:8861.29043
[7]	validation_0-mae:8451.90421
[8]	validation_0-mae:8109.49366
[9]	validation_0-mae:7750.19142
[10]	validation_0-mae:7465.82096
[11]	validation_0-mae:7163.30551
[12]	validation_0-mae:6897.66583
[13]	validation_0-mae:6656.56763
[14]	validation_0-mae:6415.60420
[15]	validation_0-mae:6183.92170
[16]	validation_0-mae:5963.20052
[17]	validation_0-mae:5786.87300
[18]	validation_0-mae:5627.59423
[19]	validation_0-mae:5456.05197
[20]	validation_0-mae:5290.17097
[21]	validation_0-mae:5152.34898
[22]	validation_0-mae:5011.72270
[23]	validation_0-mae:4887.86893
[24]	validation_0-mae:4737.02127
[25]	validation_0-mae:4608.90338
[26]	validation_0-mae:4472.67402
[27]	validation_0-mae:4367.20268
[28]	validation_0-mae:4257.89751
[29]	validation_0-mae:4178.97913
[30]	validation_0-mae:4093.78964
[31]	validation_0-mae:4008.40558
[32]	validation_0-mae:3941.24494
[33]	validation_0-mae:3872.36630
[34]	validation_0-mae:3804.74107
[35]	validation_0-mae:3731.94421
[36]	validation_0-mae:3683.22157
[37]	validation_0-mae:3630.12340
[38]	validation_0-mae:3575.60596
[39]	validation_0-mae:3527.60615
[40]	validation_0-mae:3475.57073
[41]	validation_0-mae:3437.00575
[42]	validation_0-mae:3395.31086

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[43]	validation_0-mae:3358.78440
[44]	validation_0-mae:3322.44184
[45]	validation_0-mae:3289.19657
[46]	validation_0-mae:3247.64969
[47]	validation_0-mae:3223.75731
[48]	validation_0-mae:3193.50492
[49]	validation_0-mae:3163.28358
[50]	validation_0-mae:3136.07263
[51]	validation_0-mae:3084.82477
[52]	validation_0-mae:3060.79993
[53]	validation_0-mae:3038.01723
[54]	validation_0-mae:3021.97981
[55]	validation_0-mae:3002.13795
[56]	validation_0-mae:2978.11481
[57]	validation_0-mae:2960.98099
[58]	validation_0-mae:2943.73662
[59]	validation_0-mae:2929.67234
[60]	validation_0-mae:2898.50997
[61]	validation_0-mae:2879.28453
[62]	validation_0-mae:2869.51074
[63]	validation_0-mae:2853.11481
[64]	validation_0-mae:2834.86159
[65]	validation_0-mae:2823.22577
[66]	validation_0-mae:2810.64515
[67]	validation_0-mae:2784.44891
[68]	validation_0-mae:2771.59078
[69]	validation_0-mae:2763.25843
[70]	validation_0-mae:2752.61389
[71]	validation_0-mae:2744.55382
[72]	validation_0-mae:2735.40381
[73]	validation_0-mae:2728.72698
[74]	validation_0-mae:2710.13019
[75]	validation_0-mae:2695.63572
[76]	validation_0-mae:2685.91256
[77]	validation_0-mae:2679.78534
[78]	validation_0-mae:2671.20927
[79]	validation_0-mae:2650.07595
[80]	validation_0-mae:2643.01344
[81]	validation_0-mae:2624.15567
[82]	validation_0-mae:2621.70265
[83]	validation_0-mae:2612.21814
[84]	validation_0-mae:2601.17377
[85]	validation_0-mae:2593.23315
[86]	validation_0-mae:2588.82219
[87]	validation_0-mae:2581.83194
[88]	validation_0-mae:2575.40724
[89]	validation_0-mae:2559.68763
[90]	validation_0-mae:2548.74255
[91]	validation_0-mae:2541.36854
[92]	validation_0-mae:2537.48116
[93]	validation_0-mae:2530.09573
[94]	validation_0-mae:2524.69473
[95]	validation_0-mae:2515.32322
[96]	validation_0-mae:2511.72579
[97]	validation_0-mae:2504.51392
[98]	validation_0-mae:2499.45723
[99]	validation_0-mae:2495.83270
[100]	validation_0-mae:2490.15307
[101]	validation_0-mae:2480.77673
[102]	validation_0-mae:2475.91864
[103]	validation_0-mae:2468.66184
[104]	validation_0-mae:2465.46414
[105]	validation_0-mae:2460.14274
[106]	validation_0-mae:2457.95156
[107]	validation_0-mae:2448.12199
[108]	validation_0-mae:2442.39617
[109]	validation_0-mae:2440.93146
[110]	validation_0-mae:2435.56177
[111]	validation_0-mae:2432.37736
[112]	validation_0-mae:2427.01136
[113]	validation_0-mae:2426.25835
[114]	validation_0-mae:2424.28213
[115]	validation_0-mae:2416.89825
[116]	validation_0-mae:2414.28733
[117]	validation_0-mae:2411.67960
[118]	validation_0-mae:2408.93436
[119]	validation_0-mae:2404.30367
[120]	validation_0-mae:2401.16809
[121]	validation_0-mae:2400.60175
[122]	validation_0-mae:2394.47024
[123]	validation_0-mae:2388.95787
[124]	validation_0-mae:2386.59183
[125]	validation_0-mae:2379.88853
[126]	validation_0-mae:2379.19442
[127]	validation_0-mae:2377.54952
[128]	validation_0-mae:2374.26848
[129]	validation_0-mae:2365.11946
[130]	validation_0-mae:2362.98292
[131]	validation_0-mae:2359.90270
[132]	validation_0-mae:2357.27494
[133]	validation_0-mae:2350.85927
[134]	validation_0-mae:2350.41036
[135]	validation_0-mae:2347.15070
[136]	validation_0-mae:2344.89464
[137]	validation_0-mae:2339.87902
[138]	validation_0-mae:2334.86849
[139]	validation_0-mae:2333.01751
[140]	validation_0-mae:2329.38029
[141]	validation_0-mae:2327.69625
[142]	validation_0-mae:2324.79722
[143]	validation_0-mae:2320.82538
[144]	validation_0-mae:2320.05720
[145]	validation_0-mae:2317.50489
[146]	validation_0-mae:2318.13053
[147]	validation_0-mae:2315.02096
[148]	validation_0-mae:2314.21093
[149]	validation_0-mae:2313.27749
[150]	validation_0-mae:2305.40811
[151]	validation_0-mae:2301.35099
[152]	validation_0-mae:2301.27066
[153]	validation_0-mae:2300.76220
[154]	validation_0-mae:2299.29746
[155]	validation_0-mae:2293.81793
[156]	validation_0-mae:2290.38736
[157]	validation_0-mae:2285.83132
[158]	validation_0-mae:2286.23654
[159]	validation_0-mae:2285.39339
[160]	validation_0-mae:2283.22382
[161]	validation_0-mae:2282.46823
[162]	validation_0-mae:2280.13262
[163]	validation_0-mae:2278.22489
[164]	validation_0-mae:2277.41245
[165]	validation_0-mae:2277.97214
[166]	validation_0-mae:2276.39679
[167]	validation_0-mae:2275.78886
[168]	validation_0-mae:2273.83845
[169]	validation_0-mae:2273.26712
[170]	validation_0-mae:2271.78314
[171]	validation_0-mae:2269.06930
[172]	validation_0-mae:2266.98804
[173]	validation_0-mae:2264.70186
[174]	validation_0-mae:2264.69197
[175]	validation_0-mae:2264.39852
[176]	validation_0-mae:2262.84377
[177]	validation_0-mae:2261.87477
[178]	validation_0-mae:2261.71187
[179]	validation_0-mae:2261.19971
[180]	validation_0-mae:2256.45654
[181]	validation_0-mae:2255.42107
[182]	validation_0-mae:2250.98118
[183]	validation_0-mae:2249.03194
[184]	validation_0-mae:2247.77652
[185]	validation_0-mae:2245.33282
[186]	validation_0-mae:2245.05119
[187]	validation_0-mae:2243.30001
[188]	validation_0-mae:2243.39833
[189]	validation_0-mae:2242.12231
[190]	validation_0-mae:2241.87944
[191]	validation_0-mae:2240.22165
[192]	validation_0-mae:2240.23042
[193]	validation_0-mae:2240.31127
[194]	validation_0-mae:2240.20632
[195]	validation_0-mae:2238.74239
[196]	validation_0-mae:2237.79611
[197]	validation_0-mae:2235.29623
[198]	validation_0-mae:2233.47059
[199]	validation_0-mae:2233.54131
[200]	validation_0-mae:2231.76379
[201]	validation_0-mae:2231.00599
[202]	validation_0-mae:2228.74426
[203]	validation_0-mae:2227.70435
[204]	validation_0-mae:2228.58086
[205]	validation_0-mae:2228.08062
[206]	validation_0-mae:2228.29073
[207]	validation_0-mae:2228.21846
[208]	validation_0-mae:2226.68011
[209]	validation_0-mae:2226.45899
[210]	validation_0-mae:2224.81254
[211]	validation_0-mae:2224.14815
[212]	validation_0-mae:2223.36649
[213]	validation_0-mae:2222.88552
[214]	validation_0-mae:2222.57853
[215]	validation_0-mae:2221.76279
[216]	validation_0-mae:2221.51975
[217]	validation_0-mae:2220.09208
[218]	validation_0-mae:2220.11356
[219]	validation_0-mae:2218.18331
[220]	validation_0-mae:2218.88766
[221]	validation_0-mae:2219.16293
[222]	validation_0-mae:2218.66493
[223]	validation_0-mae:2218.80047
[224]	validation_0-mae:2218.71082
[225]	validation_0-mae:2217.82935
[226]	validation_0-mae:2218.13367
[227]	validation_0-mae:2217.44545
[228]	validation_0-mae:2216.78784
[229]	validation_0-mae:2216.40442
[230]	validation_0-mae:2215.76881
[231]	validation_0-mae:2214.43416
[232]	validation_0-mae:2214.23158
[233]	validation_0-mae:2213.52361
[234]	validation_0-mae:2212.66273
[235]	validation_0-mae:2213.18646
[236]	validation_0-mae:2213.76150
[237]	validation_0-mae:2212.20047
[238]	validation_0-mae:2213.57515
[239]	validation_0-mae:2213.46849
[240]	validation_0-mae:2212.33278
[241]	validation_0-mae:2211.29518
[242]	validation_0-mae:2210.53776
[243]	validation_0-mae:2211.60544
[244]	validation_0-mae:2211.53039
[245]	validation_0-mae:2211.66771
[246]	validation_0-mae:2210.87592
[247]	validation_0-mae:2209.21117
[248]	validation_0-mae:2207.47569
[249]	validation_0-mae:2208.29650
[250]	validation_0-mae:2208.77640
[251]	validation_0-mae:2208.59446
[252]	validation_0-mae:2207.89386
[253]	validation_0-mae:2207.11251
[254]	validation_0-mae:2206.88303
[255]	validation_0-mae:2206.92721
[256]	validation_0-mae:2207.33496
[257]	validation_0-mae:2207.95610
[258]	validation_0-mae:2208.06570
[259]	validation_0-mae:2208.91593
[260]	validation_0-mae:2208.86433
[261]	validation_0-mae:2208.55137
[262]	validation_0-mae:2208.05668
[263]	validation_0-mae:2207.98748
[264]	validation_0-mae:2207.34738
[265]	validation_0-mae:2206.65680
[266]	validation_0-mae:2207.03832
[267]	validation_0-mae:2205.78330
[268]	validation_0-mae:2204.76234
[269]	validation_0-mae:2204.47924
[270]	validation_0-mae:2203.14007
[271]	validation_0-mae:2201.55250
[272]	validation_0-mae:2199.39998
[273]	validation_0-mae:2198.92163
[274]	validation_0-mae:2199.76132
[275]	validation_0-mae:2200.01801
[276]	validation_0-mae:2199.33334
[277]	validation_0-mae:2199.93469
[278]	validation_0-mae:2198.94674
[279]	validation_0-mae:2199.42113
[280]	validation_0-mae:2199.28224
[281]	validation_0-mae:2199.72011
[282]	validation_0-mae:2199.54849
[283]	validation_0-mae:2199.66678
[284]	validation_0-mae:2199.35885
[285]	validation_0-mae:2199.19897
[286]	validation_0-mae:2198.34069
[287]	validation_0-mae:2198.69321
[288]	validation_0-mae:2198.88588
[289]	validation_0-mae:2198.89367
[290]	validation_0-mae:2198.52087
[291]	validation_0-mae:2198.33199
[292]	validation_0-mae:2198.48297
[293]	validation_0-mae:2198.46086
[294]	validation_0-mae:2197.83317
[295]	validation_0-mae:2197.88973
[296]	validation_0-mae:2196.70451
[297]	validation_0-mae:2195.88330
[298]	validation_0-mae:2196.12847
[299]	validation_0-mae:2194.67376
[300]	validation_0-mae:2193.97374
[301]	validation_0-mae:2194.22950
[302]	validation_0-mae:2194.78054
[303]	validation_0-mae:2194.17636
[304]	validation_0-mae:2194.55804
[305]	validation_0-mae:2194.46706
[306]	validation_0-mae:2192.66530
[307]	validation_0-mae:2192.77292
[308]	validation_0-mae:2192.46062
[309]	validation_0-mae:2192.42746
[310]	validation_0-mae:2192.06427
[311]	validation_0-mae:2192.23883
[312]	validation_0-mae:2190.44238
[313]	validation_0-mae:2188.38205
[314]	validation_0-mae:2186.13030
[315]	validation_0-mae:2185.67264
[316]	validation_0-mae:2184.85091
[317]	validation_0-mae:2184.00153
[318]	validation_0-mae:2183.55989
[319]	validation_0-mae:2184.00389
[320]	validation_0-mae:2183.50293
[321]	validation_0-mae:2183.20873
[322]	validation_0-mae:2183.18848
[323]	validation_0-mae:2182.55407
[324]	validation_0-mae:2180.94948
[325]	validation_0-mae:2179.76355
[326]	validation_0-mae:2179.55626
[327]	validation_0-mae:2179.38575
[328]	validation_0-mae:2179.08278
[329]	validation_0-mae:2178.87414
[330]	validation_0-mae:2179.09800
[331]	validation_0-mae:2177.30198
[332]	validation_0-mae:2176.33232
[333]	validation_0-mae:2176.82932
[334]	validation_0-mae:2176.43068
[335]	validation_0-mae:2176.08593
[336]	validation_0-mae:2176.44317
[337]	validation_0-mae:2176.48088
[338]	validation_0-mae:2173.83524
[339]	validation_0-mae:2172.91880
[340]	validation_0-mae:2173.24650
[341]	validation_0-mae:2173.25423
[342]	validation_0-mae:2173.65966
[343]	validation_0-mae:2173.53384
[344]	validation_0-mae:2173.45576
[345]	validation_0-mae:2172.33715
[346]	validation_0-mae:2172.06214
[347]	validation_0-mae:2171.13278
[348]	validation_0-mae:2170.99880
[349]	validation_0-mae:2170.77231
[350]	validation_0-mae:2171.29091
[351]	validation_0-mae:2168.87314
[352]	validation_0-mae:2169.28920
[353]	validation_0-mae:2165.77724
[354]	validation_0-mae:2165.29368
[355]	validation_0-mae:2165.65333
[356]	validation_0-mae:2165.06161
[357]	validation_0-mae:2165.11959
[358]	validation_0-mae:2165.08425
[359]	validation_0-mae:2164.72056
[360]	validation_0-mae:2164.84366
[361]	validation_0-mae:2164.64798
[362]	validation_0-mae:2164.78355
[363]	validation_0-mae:2165.38698
[364]	validation_0-mae:2165.39129
[365]	validation_0-mae:2163.82181
[366]	validation_0-mae:2163.99740
[367]	validation_0-mae:2163.51822
[368]	validation_0-mae:2163.22588
[369]	validation_0-mae:2163.24882
[370]	validation_0-mae:2163.28700
[371]	validation_0-mae:2163.42747
[372]	validation_0-mae:2163.28597
[373]	validation_0-mae:2163.41290
[374]	validation_0-mae:2160.84193
[375]	validation_0-mae:2160.30515
[376]	validation_0-mae:2159.40910
[377]	validation_0-mae:2159.58801
[378]	validation_0-mae:2160.09160
[379]	validation_0-mae:2161.11998
[380]	validation_0-mae:2161.30114
[381]	validation_0-mae:2161.34209
[382]	validation_0-mae:2161.28536
[383]	validation_0-mae:2161.23886
[384]	validation_0-mae:2161.50890
[385]	validation_0-mae:2162.11297
[386]	validation_0-mae:2160.88030
[387]	validation_0-mae:2161.57666
[388]	validation_0-mae:2161.34917
[389]	validation_0-mae:2161.98511
[390]	validation_0-mae:2160.61202
[391]	validation_0-mae:2161.85428
[392]	validation_0-mae:2160.55348
[393]	validation_0-mae:2160.50387
[394]	validation_0-mae:2160.32359
[395]	validation_0-mae:2160.33664
[396]	validation_0-mae:2160.64331
[397]	validation_0-mae:2160.98662
[398]	validation_0-mae:2160.46445
[399]	validation_0-mae:2159.95794
[400]	validation_0-mae:2160.00169
[401]	validation_0-mae:2160.51817
[402]	validation_0-mae:2160.01742
[403]	validation_0-mae:2159.01918
[404]	validation_0-mae:2158.96848
[405]	validation_0-mae:2159.06429
[406]	validation_0-mae:2157.63415
[407]	validation_0-mae:2157.53594
[408]	validation_0-mae:2157.40717
[409]	validation_0-mae:2158.10507
[410]	validation_0-mae:2157.98896
[411]	validation_0-mae:2158.30140
[412]	validation_0-mae:2157.94179
[413]	validation_0-mae:2158.15953
[414]	validation_0-mae:2158.43635
[415]	validation_0-mae:2158.49198
[416]	validation_0-mae:2157.09181
[417]	validation_0-mae:2156.77946
[418]	validation_0-mae:2157.41972
[419]	validation_0-mae:2157.54945
[420]	validation_0-mae:2156.47201
[421]	validation_0-mae:2156.76384
[422]	validation_0-mae:2155.55374
[423]	validation_0-mae:2155.64889
[424]	validation_0-mae:2155.43386
[425]	validation_0-mae:2155.51881
[426]	validation_0-mae:2155.80266
[427]	validation_0-mae:2155.37357
[428]	validation_0-mae:2155.82904
[429]	validation_0-mae:2154.57697
[430]	validation_0-mae:2154.28609
[431]	validation_0-mae:2154.33465
[432]	validation_0-mae:2152.17369
[433]	validation_0-mae:2151.94213
[434]	validation_0-mae:2152.20102
[435]	validation_0-mae:2151.65690
[436]	validation_0-mae:2151.59889
[437]	validation_0-mae:2150.07119
[438]	validation_0-mae:2150.45343
[439]	validation_0-mae:2150.89685
[440]	validation_0-mae:2150.56457
[441]	validation_0-mae:2150.98680
[442]	validation_0-mae:2151.23362
[443]	validation_0-mae:2151.35266
[444]	validation_0-mae:2151.80092
[445]	validation_0-mae:2150.91087
[446]	validation_0-mae:2151.18098
[447]	validation_0-mae:2150.99869
[448]	validation_0-mae:2151.26303
[449]	validation_0-mae:2152.14773
[450]	validation_0-mae:2151.74519
[451]	validation_0-mae:2152.02138
[452]	validation_0-mae:2152.60844
[453]	validation_0-mae:2150.72366
[454]	validation_0-mae:2150.78343
[455]	validation_0-mae:2151.08081
[456]	validation_0-mae:2150.91974
[457]	validation_0-mae:2149.33456
[458]	validation_0-mae:2149.43509
[459]	validation_0-mae:2147.59270
[460]	validation_0-mae:2147.05791
[461]	validation_0-mae:2146.62542
[462]	validation_0-mae:2144.41244
[463]	validation_0-mae:2144.31166
[464]	validation_0-mae:2144.41326
[465]	validation_0-mae:2143.91418
[466]	validation_0-mae:2144.04484
[467]	validation_0-mae:2142.18011
[468]	validation_0-mae:2142.43929
[469]	validation_0-mae:2143.01088
[470]	validation_0-mae:2142.67143
[471]	validation_0-mae:2142.21200
[472]	validation_0-mae:2141.54856
[473]	validation_0-mae:2140.79285
[474]	validation_0-mae:2140.51503
[475]	validation_0-mae:2139.83944
[476]	validation_0-mae:2139.59566
[477]	validation_0-mae:2139.54833
[478]	validation_0-mae:2139.81023
[479]	validation_0-mae:2139.62631
[480]	validation_0-mae:2139.36087
[481]	validation_0-mae:2139.16626
[482]	validation_0-mae:2138.99098
[483]	validation_0-mae:2139.00633
[484]	validation_0-mae:2139.02813
[485]	validation_0-mae:2138.72898
[486]	validation_0-mae:2139.11616
[487]	validation_0-mae:2138.31951
[488]	validation_0-mae:2135.73124
[489]	validation_0-mae:2135.02965
[0]	validation_0-mae:12456.33144
[1]	validation_0-mae:11727.13726
[2]	validation_0-mae:11066.34837
[3]	validation_0-mae:10445.06083
[4]	validation_0-mae:9899.64948
[5]	validation_0-mae:9399.26412
[6]	validation_0-mae:8941.64422
[7]	validation_0-mae:8527.18987
[8]	validation_0-mae:8159.39572
[9]	validation_0-mae:7815.03241
[10]	validation_0-mae:7501.15531
[11]	validation_0-mae:7186.96983
[12]	validation_0-mae:6919.46774
[13]	validation_0-mae:6669.02581
[14]	validation_0-mae:6435.11031
[15]	validation_0-mae:6211.91952
[16]	validation_0-mae:5986.11341
[17]	validation_0-mae:5783.48698
[18]	validation_0-mae:5584.05786
[19]	validation_0-mae:5387.82828
[20]	validation_0-mae:5235.90287
[21]	validation_0-mae:5070.55861
[22]	validation_0-mae:4926.00633
[23]	validation_0-mae:4790.52635
[24]	validation_0-mae:4664.52734
[25]	validation_0-mae:4548.62447
[26]	validation_0-mae:4453.81298
[27]	validation_0-mae:4346.00305
[28]	validation_0-mae:4232.48704
[29]	validation_0-mae:4134.80292
[30]	validation_0-mae:4056.82557
[31]	validation_0-mae:3980.93071
[32]	validation_0-mae:3904.82054
[33]	validation_0-mae:3824.86300
[34]	validation_0-mae:3766.37514
[35]	validation_0-mae:3711.13177
[36]	validation_0-mae:3644.57485
[37]	validation_0-mae:3581.75243
[38]	validation_0-mae:3529.25054
[39]	validation_0-mae:3473.44486
[40]	validation_0-mae:3428.26460

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[41]	validation_0-mae:3384.47418
[42]	validation_0-mae:3347.13479
[43]	validation_0-mae:3305.30528
[44]	validation_0-mae:3271.51100
[45]	validation_0-mae:3228.55735
[46]	validation_0-mae:3194.28748
[47]	validation_0-mae:3167.91021
[48]	validation_0-mae:3140.23098
[49]	validation_0-mae:3109.34877
[50]	validation_0-mae:3088.99877
[51]	validation_0-mae:3065.25460
[52]	validation_0-mae:3024.84450
[53]	validation_0-mae:3008.51430
[54]	validation_0-mae:2976.03682
[55]	validation_0-mae:2955.84145
[56]	validation_0-mae:2923.45366
[57]	validation_0-mae:2909.38903
[58]	validation_0-mae:2894.74303
[59]	validation_0-mae:2878.50777
[60]	validation_0-mae:2852.62284
[61]	validation_0-mae:2841.43389
[62]	validation_0-mae:2824.31096
[63]	validation_0-mae:2809.29351
[64]	validation_0-mae:2793.26537
[65]	validation_0-mae:2774.37354
[66]	validation_0-mae:2762.57754
[67]	validation_0-mae:2751.55449
[68]	validation_0-mae:2741.28804
[69]	validation_0-mae:2735.20411
[70]	validation_0-mae:2722.63811
[71]	validation_0-mae:2709.26245
[72]	validation_0-mae:2693.57362
[73]	validation_0-mae:2688.50649
[74]	validation_0-mae:2679.78576
[75]	validation_0-mae:2668.07755
[76]	validation_0-mae:2651.18237
[77]	validation_0-mae:2643.01486
[78]	validation_0-mae:2626.88321
[79]	validation_0-mae:2618.94293
[80]	validation_0-mae:2602.87835
[81]	validation_0-mae:2596.51870
[82]	validation_0-mae:2588.92539
[83]	validation_0-mae:2579.07572
[84]	validation_0-mae:2574.03960
[85]	validation_0-mae:2557.50641
[86]	validation_0-mae:2548.08756
[87]	validation_0-mae:2541.84545
[88]	validation_0-mae:2536.37945
[89]	validation_0-mae:2527.03321
[90]	validation_0-mae:2517.13930
[91]	validation_0-mae:2507.29993
[92]	validation_0-mae:2496.02826
[93]	validation_0-mae:2490.66395
[94]	validation_0-mae:2487.47058
[95]	validation_0-mae:2479.37787
[96]	validation_0-mae:2475.95683
[97]	validation_0-mae:2463.47181
[98]	validation_0-mae:2454.37737
[99]	validation_0-mae:2448.10837
[100]	validation_0-mae:2444.93927
[101]	validation_0-mae:2442.01529
[102]	validation_0-mae:2437.57188
[103]	validation_0-mae:2434.81028
[104]	validation_0-mae:2429.69724
[105]	validation_0-mae:2424.03675
[106]	validation_0-mae:2417.68654
[107]	validation_0-mae:2412.43694
[108]	validation_0-mae:2405.41525
[109]	validation_0-mae:2403.27298
[110]	validation_0-mae:2396.74112
[111]	validation_0-mae:2392.71135
[112]	validation_0-mae:2386.48175
[113]	validation_0-mae:2381.78246
[114]	validation_0-mae:2377.08315
[115]	validation_0-mae:2372.78407
[116]	validation_0-mae:2368.09862
[117]	validation_0-mae:2364.27408
[118]	validation_0-mae:2359.33885
[119]	validation_0-mae:2353.60010
[120]	validation_0-mae:2351.19604
[121]	validation_0-mae:2347.91369
[122]	validation_0-mae:2344.99485
[123]	validation_0-mae:2341.99053
[124]	validation_0-mae:2337.82053
[125]	validation_0-mae:2337.33265
[126]	validation_0-mae:2332.92939
[127]	validation_0-mae:2331.83321
[128]	validation_0-mae:2330.48509
[129]	validation_0-mae:2327.17153
[130]	validation_0-mae:2325.22772
[131]	validation_0-mae:2323.88356
[132]	validation_0-mae:2320.16682
[133]	validation_0-mae:2319.19439
[134]	validation_0-mae:2317.80796
[135]	validation_0-mae:2316.43262
[136]	validation_0-mae:2312.97400
[137]	validation_0-mae:2311.93695
[138]	validation_0-mae:2310.54159
[139]	validation_0-mae:2306.40497
[140]	validation_0-mae:2302.41653
[141]	validation_0-mae:2301.94988
[142]	validation_0-mae:2298.01578
[143]	validation_0-mae:2295.80419
[144]	validation_0-mae:2296.09330
[145]	validation_0-mae:2293.68393
[146]	validation_0-mae:2292.88663
[147]	validation_0-mae:2291.42124
[148]	validation_0-mae:2287.66927
[149]	validation_0-mae:2287.15821
[150]	validation_0-mae:2284.33216
[151]	validation_0-mae:2282.69800
[152]	validation_0-mae:2282.28900
[153]	validation_0-mae:2279.55245
[154]	validation_0-mae:2278.02447
[155]	validation_0-mae:2276.42302
[156]	validation_0-mae:2274.49234
[157]	validation_0-mae:2272.55555
[158]	validation_0-mae:2269.27320
[159]	validation_0-mae:2268.13059
[160]	validation_0-mae:2265.82175
[161]	validation_0-mae:2265.69488
[162]	validation_0-mae:2263.71546
[163]	validation_0-mae:2262.87349
[164]	validation_0-mae:2261.89660
[165]	validation_0-mae:2260.35991
[166]	validation_0-mae:2258.28601
[167]	validation_0-mae:2257.73344
[168]	validation_0-mae:2256.75670
[169]	validation_0-mae:2256.46369
[170]	validation_0-mae:2257.11084
[171]	validation_0-mae:2256.48904
[172]	validation_0-mae:2256.63181
[173]	validation_0-mae:2256.06225
[174]	validation_0-mae:2255.96053
[175]	validation_0-mae:2255.78836
[176]	validation_0-mae:2255.76190
[177]	validation_0-mae:2255.13088
[178]	validation_0-mae:2252.30116
[179]	validation_0-mae:2251.79256
[180]	validation_0-mae:2250.10237
[181]	validation_0-mae:2250.71232
[182]	validation_0-mae:2250.46430
[183]	validation_0-mae:2250.22628
[184]	validation_0-mae:2250.22662
[185]	validation_0-mae:2247.67870
[186]	validation_0-mae:2248.14882
[187]	validation_0-mae:2246.82659
[188]	validation_0-mae:2246.36308
[189]	validation_0-mae:2244.71600
[190]	validation_0-mae:2243.88831
[191]	validation_0-mae:2243.37202
[192]	validation_0-mae:2242.67307
[193]	validation_0-mae:2241.27477
[194]	validation_0-mae:2240.44810
[195]	validation_0-mae:2237.95453
[196]	validation_0-mae:2237.60445
[197]	validation_0-mae:2237.18391
[198]	validation_0-mae:2235.99392
[199]	validation_0-mae:2236.50239
[200]	validation_0-mae:2234.30385
[201]	validation_0-mae:2233.34363
[202]	validation_0-mae:2233.50770
[203]	validation_0-mae:2233.33704
[204]	validation_0-mae:2232.56539
[205]	validation_0-mae:2232.43219
[206]	validation_0-mae:2231.34459
[207]	validation_0-mae:2230.68015
[208]	validation_0-mae:2230.06893
[209]	validation_0-mae:2229.12021
[210]	validation_0-mae:2228.66472
[211]	validation_0-mae:2228.16389
[212]	validation_0-mae:2228.09940
[213]	validation_0-mae:2227.64441
[214]	validation_0-mae:2227.05253
[215]	validation_0-mae:2226.88641
[216]	validation_0-mae:2226.67514
[217]	validation_0-mae:2226.50583
[218]	validation_0-mae:2225.72284
[219]	validation_0-mae:2224.99681
[220]	validation_0-mae:2223.92573
[221]	validation_0-mae:2223.97616
[222]	validation_0-mae:2223.69789
[223]	validation_0-mae:2222.56146
[224]	validation_0-mae:2222.22686
[225]	validation_0-mae:2222.47137
[226]	validation_0-mae:2221.09546
[227]	validation_0-mae:2219.85741
[228]	validation_0-mae:2219.53922
[229]	validation_0-mae:2219.43033
[230]	validation_0-mae:2219.31414
[231]	validation_0-mae:2219.08012
[232]	validation_0-mae:2219.07220
[233]	validation_0-mae:2218.84091
[234]	validation_0-mae:2218.82635
[235]	validation_0-mae:2218.60687
[236]	validation_0-mae:2218.19076
[237]	validation_0-mae:2217.89279
[238]	validation_0-mae:2217.02155
[239]	validation_0-mae:2217.41755
[240]	validation_0-mae:2217.54067
[241]	validation_0-mae:2215.61059
[242]	validation_0-mae:2213.20062
[243]	validation_0-mae:2211.20255
[244]	validation_0-mae:2211.24066
[245]	validation_0-mae:2211.22880
[246]	validation_0-mae:2207.96307
[247]	validation_0-mae:2207.59534
[248]	validation_0-mae:2207.48491
[249]	validation_0-mae:2207.49027
[250]	validation_0-mae:2206.81223
[251]	validation_0-mae:2206.37403
[252]	validation_0-mae:2205.89295
[253]	validation_0-mae:2205.29542
[254]	validation_0-mae:2205.67291
[255]	validation_0-mae:2205.91533
[256]	validation_0-mae:2205.76864
[257]	validation_0-mae:2205.77696
[258]	validation_0-mae:2205.51987
[259]	validation_0-mae:2204.91141
[260]	validation_0-mae:2204.59908
[261]	validation_0-mae:2204.21350
[262]	validation_0-mae:2204.54463
[263]	validation_0-mae:2205.02348
[264]	validation_0-mae:2205.22067
[265]	validation_0-mae:2204.90119
[266]	validation_0-mae:2205.21637
[267]	validation_0-mae:2204.81787
[268]	validation_0-mae:2203.27147
[269]	validation_0-mae:2202.74231
[270]	validation_0-mae:2203.36139
[271]	validation_0-mae:2202.72318
[272]	validation_0-mae:2202.53645
[273]	validation_0-mae:2202.45092
[274]	validation_0-mae:2201.26745
[275]	validation_0-mae:2200.55952
[276]	validation_0-mae:2200.24463
[277]	validation_0-mae:2200.04152
[278]	validation_0-mae:2199.54539
[279]	validation_0-mae:2200.05075
[280]	validation_0-mae:2199.19330
[281]	validation_0-mae:2197.74723
[282]	validation_0-mae:2198.23426
[283]	validation_0-mae:2196.99339
[284]	validation_0-mae:2196.58576
[285]	validation_0-mae:2194.06304
[286]	validation_0-mae:2194.25321
[287]	validation_0-mae:2194.06130
[288]	validation_0-mae:2192.77036
[289]	validation_0-mae:2192.33479
[290]	validation_0-mae:2192.35824
[291]	validation_0-mae:2190.91590
[292]	validation_0-mae:2190.99722
[293]	validation_0-mae:2189.08050
[294]	validation_0-mae:2187.62951
[295]	validation_0-mae:2186.37327
[296]	validation_0-mae:2183.80717
[297]	validation_0-mae:2183.63253
[298]	validation_0-mae:2183.51312
[299]	validation_0-mae:2183.53862
[300]	validation_0-mae:2183.44618
[301]	validation_0-mae:2184.81402
[302]	validation_0-mae:2184.72098
[303]	validation_0-mae:2184.92914
[304]	validation_0-mae:2184.67270
[305]	validation_0-mae:2184.67642
[306]	validation_0-mae:2183.38942
[307]	validation_0-mae:2183.10475
[308]	validation_0-mae:2183.69706
[309]	validation_0-mae:2183.14606
[310]	validation_0-mae:2182.21265
[311]	validation_0-mae:2181.47884
[312]	validation_0-mae:2179.93155
[313]	validation_0-mae:2179.26328
[314]	validation_0-mae:2179.18682
[315]	validation_0-mae:2177.74759
[316]	validation_0-mae:2177.65568
[317]	validation_0-mae:2176.28271
[318]	validation_0-mae:2176.05537
[319]	validation_0-mae:2175.39385
[320]	validation_0-mae:2174.28593
[321]	validation_0-mae:2174.13607
[322]	validation_0-mae:2174.84338
[323]	validation_0-mae:2173.55148
[324]	validation_0-mae:2173.29394
[325]	validation_0-mae:2174.12259
[326]	validation_0-mae:2173.98062
[327]	validation_0-mae:2174.74930
[328]	validation_0-mae:2174.97537
[329]	validation_0-mae:2172.96721
[330]	validation_0-mae:2173.26191
[331]	validation_0-mae:2173.22953
[332]	validation_0-mae:2173.10326
[333]	validation_0-mae:2173.78131
[334]	validation_0-mae:2172.98984
[335]	validation_0-mae:2171.27859
[336]	validation_0-mae:2171.22389
[337]	validation_0-mae:2170.15981
[338]	validation_0-mae:2169.10237
[339]	validation_0-mae:2168.46229
[340]	validation_0-mae:2166.37425
[341]	validation_0-mae:2164.47669
[342]	validation_0-mae:2163.04153
[343]	validation_0-mae:2163.10704
[344]	validation_0-mae:2163.63292
[345]	validation_0-mae:2164.57810
[346]	validation_0-mae:2163.90430
[347]	validation_0-mae:2164.31893
[348]	validation_0-mae:2164.44112
[349]	validation_0-mae:2164.52941
[350]	validation_0-mae:2165.53960
[351]	validation_0-mae:2166.14704
[352]	validation_0-mae:2165.96114
[353]	validation_0-mae:2166.48730
[354]	validation_0-mae:2167.02121
[355]	validation_0-mae:2166.63824
[356]	validation_0-mae:2165.93365
[357]	validation_0-mae:2165.79792
[358]	validation_0-mae:2165.27719
[359]	validation_0-mae:2165.50630
[360]	validation_0-mae:2166.09678
[361]	validation_0-mae:2165.69170
[362]	validation_0-mae:2166.30977
[363]	validation_0-mae:2165.86701
[364]	validation_0-mae:2166.41069
[365]	validation_0-mae:2166.96065
[366]	validation_0-mae:2165.78038
[367]	validation_0-mae:2165.24283
[368]	validation_0-mae:2164.47824
[369]	validation_0-mae:2164.89714
[370]	validation_0-mae:2165.20208
[371]	validation_0-mae:2165.20124
[372]	validation_0-mae:2164.19023
[373]	validation_0-mae:2164.85147
[374]	validation_0-mae:2165.86407
[375]	validation_0-mae:2165.29972
[376]	validation_0-mae:2164.33446
[377]	validation_0-mae:2164.43313
[378]	validation_0-mae:2164.21297
[379]	validation_0-mae:2164.34487
[380]	validation_0-mae:2163.68452
[381]	validation_0-mae:2164.33751
[382]	validation_0-mae:2164.30767
[383]	validation_0-mae:2164.59069
[384]	validation_0-mae:2163.98319
[385]	validation_0-mae:2164.11528
[386]	validation_0-mae:2163.55205
[387]	validation_0-mae:2163.67619
[388]	validation_0-mae:2163.62987
[389]	validation_0-mae:2163.98311
[390]	validation_0-mae:2163.35919
[391]	validation_0-mae:2163.02300
[392]	validation_0-mae:2161.56737
[393]	validation_0-mae:2161.10432
[394]	validation_0-mae:2159.97036
[395]	validation_0-mae:2159.95401
[396]	validation_0-mae:2159.82494
[397]	validation_0-mae:2159.70859
[398]	validation_0-mae:2159.33588
[399]	validation_0-mae:2158.73027
[400]	validation_0-mae:2157.97177
[401]	validation_0-mae:2157.94775
[402]	validation_0-mae:2157.67920
[403]	validation_0-mae:2157.06036
[404]	validation_0-mae:2156.94005
[405]	validation_0-mae:2157.02880
[406]	validation_0-mae:2156.42292
[407]	validation_0-mae:2156.70397
[408]	validation_0-mae:2156.77047
[409]	validation_0-mae:2156.21407
[410]	validation_0-mae:2155.68347
[411]	validation_0-mae:2156.07033
[412]	validation_0-mae:2155.02894
[413]	validation_0-mae:2154.99829
[414]	validation_0-mae:2154.84907
[415]	validation_0-mae:2155.14647
[416]	validation_0-mae:2155.46787
[417]	validation_0-mae:2155.88537
[418]	validation_0-mae:2155.60441
[419]	validation_0-mae:2155.65507
[420]	validation_0-mae:2155.67009
[421]	validation_0-mae:2154.98797
[422]	validation_0-mae:2154.62834
[423]	validation_0-mae:2154.67867
[424]	validation_0-mae:2154.55876
[425]	validation_0-mae:2154.36806
[426]	validation_0-mae:2154.43487
[427]	validation_0-mae:2154.14891
[428]	validation_0-mae:2154.05238
[429]	validation_0-mae:2154.06637
[430]	validation_0-mae:2154.20441
[431]	validation_0-mae:2154.27497
[432]	validation_0-mae:2154.31964
[433]	validation_0-mae:2154.08109
[434]	validation_0-mae:2154.27682
[435]	validation_0-mae:2154.29763
[436]	validation_0-mae:2154.67918
[437]	validation_0-mae:2154.09804
[438]	validation_0-mae:2153.01127
[439]	validation_0-mae:2152.62834
[440]	validation_0-mae:2152.18687
[441]	validation_0-mae:2152.73305
[442]	validation_0-mae:2152.49187
[443]	validation_0-mae:2152.63130
[444]	validation_0-mae:2152.62708
[445]	validation_0-mae:2152.63167
[446]	validation_0-mae:2151.70572
[447]	validation_0-mae:2151.83093
[448]	validation_0-mae:2152.24883
[449]	validation_0-mae:2152.37494
[450]	validation_0-mae:2151.75597
[451]	validation_0-mae:2151.91528
[452]	validation_0-mae:2151.69910
[453]	validation_0-mae:2151.47399
[454]	validation_0-mae:2151.27099
[455]	validation_0-mae:2151.89344
[456]	validation_0-mae:2151.33110
[457]	validation_0-mae:2151.31927
[458]	validation_0-mae:2150.80867
[0]	validation_0-mae:12426.06706
[1]	validation_0-mae:11665.11935
[2]	validation_0-mae:10990.90896
[3]	validation_0-mae:10356.00524
[4]	validation_0-mae:9791.52983
[5]	validation_0-mae:9277.56854
[6]	validation_0-mae:8817.81786
[7]	validation_0-mae:8401.55219
[8]	validation_0-mae:8024.16953
[9]	validation_0-mae:7691.64621
[10]	validation_0-mae:7349.19728
[11]	validation_0-mae:7047.05832
[12]	validation_0-mae:6778.53745
[13]	validation_0-mae:6511.27048
[14]	validation_0-mae:6289.28353
[15]	validation_0-mae:6070.32379
[16]	validation_0-mae:5846.61758
[17]	validation_0-mae:5640.95449
[18]	validation_0-mae:5466.58480
[19]	validation_0-mae:5278.05094
[20]	validation_0-mae:5101.18290
[21]	validation_0-mae:4956.36582
[22]	validation_0-mae:4815.74282
[23]	validation_0-mae:4666.53171
[24]	validation_0-mae:4542.89148
[25]	validation_0-mae:4418.84949

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[26]	validation_0-mae:4303.22701
[27]	validation_0-mae:4198.95433
[28]	validation_0-mae:4101.27527
[29]	validation_0-mae:4027.35161
[30]	validation_0-mae:3934.79543
[31]	validation_0-mae:3849.37876
[32]	validation_0-mae:3792.76721
[33]	validation_0-mae:3720.06508
[34]	validation_0-mae:3658.80049
[35]	validation_0-mae:3600.51236
[36]	validation_0-mae:3541.72702
[37]	validation_0-mae:3495.49523
[38]	validation_0-mae:3440.82312
[39]	validation_0-mae:3399.46940
[40]	validation_0-mae:3359.21670
[41]	validation_0-mae:3316.19849
[42]	validation_0-mae:3274.84049
[43]	validation_0-mae:3242.78282
[44]	validation_0-mae:3207.11805
[45]	validation_0-mae:3163.37852
[46]	validation_0-mae:3132.63187
[47]	validation_0-mae:3092.41103
[48]	validation_0-mae:3062.50492
[49]	validation_0-mae:3026.23215
[50]	validation_0-mae:2986.01842
[51]	validation_0-mae:2962.20569
[52]	validation_0-mae:2939.81538
[53]	validation_0-mae:2905.30603
[54]	validation_0-mae:2889.56526
[55]	validation_0-mae:2873.01975
[56]	validation_0-mae:2847.49250
[57]	validation_0-mae:2829.71724
[58]	validation_0-mae:2818.03430
[59]	validation_0-mae:2794.63427
[60]	validation_0-mae:2782.15363
[61]	validation_0-mae:2768.08425
[62]	validation_0-mae:2750.07608
[63]	validation_0-mae:2735.40554
[64]	validation_0-mae:2721.02993
[65]	validation_0-mae:2711.80112
[66]	validation_0-mae:2698.91592
[67]	validation_0-mae:2687.67603
[68]	validation_0-mae:2674.45151
[69]	validation_0-mae:2657.37527
[70]	validation_0-mae:2647.97848
[71]	validation_0-mae:2634.95701
[72]	validation_0-mae:2627.13270
[73]	validation_0-mae:2608.90273
[74]	validation_0-mae:2592.97495
[75]	validation_0-mae:2583.35197
[76]	validation_0-mae:2571.77858
[77]	validation_0-mae:2563.52275
[78]	validation_0-mae:2557.73744
[79]	validation_0-mae:2548.99419
[80]	validation_0-mae:2540.28155
[81]	validation_0-mae:2532.02332
[82]	validation_0-mae:2519.44621
[83]	validation_0-mae:2514.55756
[84]	validation_0-mae:2504.96309
[85]	validation_0-mae:2497.52462
[86]	validation_0-mae:2489.48808
[87]	validation_0-mae:2484.91411
[88]	validation_0-mae:2478.54185
[89]	validation_0-mae:2474.40664
[90]	validation_0-mae:2470.59660
[91]	validation_0-mae:2466.45280
[92]	validation_0-mae:2458.92268
[93]	validation_0-mae:2449.69404
[94]	validation_0-mae:2443.50139
[95]	validation_0-mae:2432.79054
[96]	validation_0-mae:2426.69028
[97]	validation_0-mae:2420.16625
[98]	validation_0-mae:2415.78773
[99]	validation_0-mae:2411.11305
[100]	validation_0-mae:2409.15321
[101]	validation_0-mae:2403.08574
[102]	validation_0-mae:2397.76669
[103]	validation_0-mae:2392.86038
[104]	validation_0-mae:2390.83634
[105]	validation_0-mae:2386.11081
[106]	validation_0-mae:2381.75683
[107]	validation_0-mae:2375.42567
[108]	validation_0-mae:2371.82397
[109]	validation_0-mae:2366.94214
[110]	validation_0-mae:2361.99354
[111]	validation_0-mae:2359.00667
[112]	validation_0-mae:2355.92135
[113]	validation_0-mae:2352.85370
[114]	validation_0-mae:2350.02121
[115]	validation_0-mae:2347.48212
[116]	validation_0-mae:2345.27428
[117]	validation_0-mae:2341.08790
[118]	validation_0-mae:2339.89616
[119]	validation_0-mae:2339.51143
[120]	validation_0-mae:2332.42455
[121]	validation_0-mae:2330.75971
[122]	validation_0-mae:2326.30853
[123]	validation_0-mae:2322.98014
[124]	validation_0-mae:2319.04430
[125]	validation_0-mae:2314.04501
[126]	validation_0-mae:2312.08180
[127]	validation_0-mae:2307.04805
[128]	validation_0-mae:2305.34261
[129]	validation_0-mae:2303.88622
[130]	validation_0-mae:2302.15367
[131]	validation_0-mae:2300.17040
[132]	validation_0-mae:2297.28746
[133]	validation_0-mae:2294.56422
[134]	validation_0-mae:2289.25912
[135]	validation_0-mae:2286.19746
[136]	validation_0-mae:2282.75971
[137]	validation_0-mae:2281.28343
[138]	validation_0-mae:2278.89271
[139]	validation_0-mae:2277.98628
[140]	validation_0-mae:2273.92396
[141]	validation_0-mae:2271.31881
[142]	validation_0-mae:2268.70810
[143]	validation_0-mae:2266.43280
[144]	validation_0-mae:2262.06226
[145]	validation_0-mae:2260.84869
[146]	validation_0-mae:2260.76317
[147]	validation_0-mae:2259.61538
[148]	validation_0-mae:2258.27569
[149]	validation_0-mae:2256.67997
[150]	validation_0-mae:2254.76874
[151]	validation_0-mae:2251.30007
[152]	validation_0-mae:2249.64359
[153]	validation_0-mae:2248.68972
[154]	validation_0-mae:2246.62513
[155]	validation_0-mae:2244.07279
[156]	validation_0-mae:2241.81952
[157]	validation_0-mae:2240.77922
[158]	validation_0-mae:2236.18403
[159]	validation_0-mae:2236.19226
[160]	validation_0-mae:2233.41466
[161]	validation_0-mae:2229.48115
[162]	validation_0-mae:2229.41405
[163]	validation_0-mae:2227.14867
[164]	validation_0-mae:2223.90483
[165]	validation_0-mae:2222.12665
[166]	validation_0-mae:2220.52086
[167]	validation_0-mae:2217.60702
[168]	validation_0-mae:2215.95614
[169]	validation_0-mae:2213.85205
[170]	validation_0-mae:2213.44370
[171]	validation_0-mae:2213.77624
[172]	validation_0-mae:2212.10382
[173]	validation_0-mae:2212.13086
[174]	validation_0-mae:2207.45992
[175]	validation_0-mae:2206.93375
[176]	validation_0-mae:2206.10552
[177]	validation_0-mae:2203.38626
[178]	validation_0-mae:2201.84945
[179]	validation_0-mae:2200.42819
[180]	validation_0-mae:2200.86565
[181]	validation_0-mae:2199.53810
[182]	validation_0-mae:2199.64821
[183]	validation_0-mae:2199.71818
[184]	validation_0-mae:2198.46408
[185]	validation_0-mae:2198.78259
[186]	validation_0-mae:2196.80393
[187]	validation_0-mae:2196.16108
[188]	validation_0-mae:2195.78170
[189]	validation_0-mae:2193.89251
[190]	validation_0-mae:2193.61918
[191]	validation_0-mae:2194.09379
[192]	validation_0-mae:2193.67445
[193]	validation_0-mae:2190.41672
[194]	validation_0-mae:2192.09046
[195]	validation_0-mae:2191.71071
[196]	validation_0-mae:2191.75045
[197]	validation_0-mae:2191.16988
[198]	validation_0-mae:2190.80580
[199]	validation_0-mae:2190.38372
[200]	validation_0-mae:2188.49974
[201]	validation_0-mae:2187.71593
[202]	validation_0-mae:2185.79169
[203]	validation_0-mae:2184.68155
[204]	validation_0-mae:2184.16086
[205]	validation_0-mae:2184.27139
[206]	validation_0-mae:2182.03268
[207]	validation_0-mae:2180.61359
[208]	validation_0-mae:2180.25007
[209]	validation_0-mae:2178.90263
[210]	validation_0-mae:2178.74474
[211]	validation_0-mae:2179.19857
[212]	validation_0-mae:2178.04120
[213]	validation_0-mae:2177.68841
[214]	validation_0-mae:2177.46199
[215]	validation_0-mae:2177.58302
[216]	validation_0-mae:2177.65967
[217]	validation_0-mae:2177.51704
[218]	validation_0-mae:2177.17570
[219]	validation_0-mae:2176.54571
[220]	validation_0-mae:2176.31517
[221]	validation_0-mae:2176.73690
[222]	validation_0-mae:2175.49711
[223]	validation_0-mae:2175.00054
[224]	validation_0-mae:2173.47140
[225]	validation_0-mae:2172.76932
[226]	validation_0-mae:2173.08624
[227]	validation_0-mae:2171.75951
[228]	validation_0-mae:2171.77988
[229]	validation_0-mae:2167.68041
[230]	validation_0-mae:2167.29266
[231]	validation_0-mae:2166.67972
[232]	validation_0-mae:2165.82654
[233]	validation_0-mae:2165.93847
[234]	validation_0-mae:2165.18845
[235]	validation_0-mae:2165.27505
[236]	validation_0-mae:2166.82564
[237]	validation_0-mae:2166.40736
[238]	validation_0-mae:2165.74101
[239]	validation_0-mae:2164.72177
[240]	validation_0-mae:2164.40739
[241]	validation_0-mae:2164.37875
[242]	validation_0-mae:2164.62439
[243]	validation_0-mae:2164.55874
[244]	validation_0-mae:2163.19760
[245]	validation_0-mae:2162.57400
[246]	validation_0-mae:2162.48365
[247]	validation_0-mae:2161.57330
[248]	validation_0-mae:2159.31719
[249]	validation_0-mae:2158.39055
[250]	validation_0-mae:2157.60668
[251]	validation_0-mae:2157.13400
[252]	validation_0-mae:2157.26693
[253]	validation_0-mae:2156.91790
[254]	validation_0-mae:2157.44876
[255]	validation_0-mae:2157.09921
[256]	validation_0-mae:2157.34945
[257]	validation_0-mae:2157.31504
[258]	validation_0-mae:2157.49577
[259]	validation_0-mae:2157.39388
[260]	validation_0-mae:2157.72626
[261]	validation_0-mae:2157.51139
[262]	validation_0-mae:2157.48034
[263]	validation_0-mae:2157.21686
[264]	validation_0-mae:2155.60837
[265]	validation_0-mae:2155.12472
[266]	validation_0-mae:2154.74691
[267]	validation_0-mae:2154.96991
[268]	validation_0-mae:2154.77789
[269]	validation_0-mae:2154.16153
[270]	validation_0-mae:2152.22427
[271]	validation_0-mae:2152.18688
[272]	validation_0-mae:2151.90108
[273]	validation_0-mae:2151.52292
[274]	validation_0-mae:2151.58225
[275]	validation_0-mae:2149.72633
[276]	validation_0-mae:2150.13564
[277]	validation_0-mae:2149.08625
[278]	validation_0-mae:2149.83348
[279]	validation_0-mae:2149.64413
[280]	validation_0-mae:2148.48688
[281]	validation_0-mae:2147.66647
[282]	validation_0-mae:2147.37151
[283]	validation_0-mae:2147.48925
[284]	validation_0-mae:2147.52551
[285]	validation_0-mae:2147.00869
[286]	validation_0-mae:2146.04419
[287]	validation_0-mae:2144.50099
[288]	validation_0-mae:2144.65986
[289]	validation_0-mae:2144.89872
[290]	validation_0-mae:2145.24861
[291]	validation_0-mae:2144.90844
[292]	validation_0-mae:2144.07475
[293]	validation_0-mae:2144.65741
[294]	validation_0-mae:2144.78337
[295]	validation_0-mae:2145.06704
[296]	validation_0-mae:2144.13221
[297]	validation_0-mae:2144.50575
[298]	validation_0-mae:2144.82676
[299]	validation_0-mae:2144.56749
[300]	validation_0-mae:2143.98360
[301]	validation_0-mae:2143.46748
[302]	validation_0-mae:2144.09571
[303]	validation_0-mae:2143.91532
[304]	validation_0-mae:2143.56565
[305]	validation_0-mae:2143.67591
[306]	validation_0-mae:2143.98585
[307]	validation_0-mae:2144.44576
[308]	validation_0-mae:2144.10832
[309]	validation_0-mae:2143.98052
[310]	validation_0-mae:2143.81212
[311]	validation_0-mae:2144.13079
[312]	validation_0-mae:2144.70085
[313]	validation_0-mae:2144.10233
[314]	validation_0-mae:2143.81783
[315]	validation_0-mae:2143.95421
[316]	validation_0-mae:2144.62404
[317]	validation_0-mae:2144.90155
[318]	validation_0-mae:2145.23357
[319]	validation_0-mae:2142.57637
[320]	validation_0-mae:2142.41297
[321]	validation_0-mae:2142.58144
[322]	validation_0-mae:2141.24705
[323]	validation_0-mae:2141.31579
[324]	validation_0-mae:2140.77158
[325]	validation_0-mae:2137.90647
[326]	validation_0-mae:2137.69625
[327]	validation_0-mae:2137.73278
[328]	validation_0-mae:2137.79645
[329]	validation_0-mae:2137.11988
[330]	validation_0-mae:2135.65443
[331]	validation_0-mae:2133.36096
[332]	validation_0-mae:2133.43398
[333]	validation_0-mae:2133.17842
[334]	validation_0-mae:2133.16937
[335]	validation_0-mae:2133.10809
[336]	validation_0-mae:2133.30109
[337]	validation_0-mae:2132.91331
[338]	validation_0-mae:2131.57257
[339]	validation_0-mae:2131.76179
[340]	validation_0-mae:2131.01819
[341]	validation_0-mae:2131.00374
[342]	validation_0-mae:2130.33021
[343]	validation_0-mae:2128.70884
[344]	validation_0-mae:2128.63821
[345]	validation_0-mae:2128.77306
[346]	validation_0-mae:2129.14803
[347]	validation_0-mae:2129.14585
[348]	validation_0-mae:2128.83431
[349]	validation_0-mae:2127.80159
[350]	validation_0-mae:2126.86325
[351]	validation_0-mae:2126.81277
[352]	validation_0-mae:2127.35952
[353]	validation_0-mae:2126.82371
[354]	validation_0-mae:2126.94146
[355]	validation_0-mae:2126.97719
[356]	validation_0-mae:2126.94259
[357]	validation_0-mae:2126.81490
[358]	validation_0-mae:2126.48942
[359]	validation_0-mae:2126.89593
[360]	validation_0-mae:2127.21950
[361]	validation_0-mae:2126.98085
[362]	validation_0-mae:2126.52230
[363]	validation_0-mae:2126.37040
[364]	validation_0-mae:2125.94102
[365]	validation_0-mae:2126.22906
[366]	validation_0-mae:2126.03559
[367]	validation_0-mae:2126.32867
[368]	validation_0-mae:2125.91611
[369]	validation_0-mae:2125.10903
[370]	validation_0-mae:2123.92894
[371]	validation_0-mae:2123.72807
[372]	validation_0-mae:2123.71047
[373]	validation_0-mae:2122.90405
[374]	validation_0-mae:2123.41269
[375]	validation_0-mae:2123.28849
[376]	validation_0-mae:2122.41952
[377]	validation_0-mae:2122.76246
[378]	validation_0-mae:2122.75830
[379]	validation_0-mae:2122.39850
[380]	validation_0-mae:2122.15975
[381]	validation_0-mae:2121.46076
[382]	validation_0-mae:2121.55821
[383]	validation_0-mae:2120.74090
[384]	validation_0-mae:2119.59511
[385]	validation_0-mae:2119.25224
[386]	validation_0-mae:2119.46524
[387]	validation_0-mae:2118.57046
[388]	validation_0-mae:2117.92728
[389]	validation_0-mae:2117.41645
[390]	validation_0-mae:2117.06046
[391]	validation_0-mae:2116.93944
[392]	validation_0-mae:2116.11228
[393]	validation_0-mae:2115.69150
[394]	validation_0-mae:2115.75938
[395]	validation_0-mae:2114.87109
[396]	validation_0-mae:2114.79465
[397]	validation_0-mae:2114.80586
[398]	validation_0-mae:2115.37949
[399]	validation_0-mae:2114.25090
[400]	validation_0-mae:2114.31103
[401]	validation_0-mae:2114.31762
[402]	validation_0-mae:2113.48661
[403]	validation_0-mae:2113.03982
[404]	validation_0-mae:2112.56425
[405]	validation_0-mae:2112.39569
[406]	validation_0-mae:2112.52417
[407]	validation_0-mae:2111.75591
[408]	validation_0-mae:2111.80898
[409]	validation_0-mae:2112.01233
[410]	validation_0-mae:2111.80095
[411]	validation_0-mae:2111.11146
[412]	validation_0-mae:2111.76855
[413]	validation_0-mae:2110.55935
[414]	validation_0-mae:2110.47960
[415]	validation_0-mae:2109.87436
[416]	validation_0-mae:2110.03750
[417]	validation_0-mae:2109.51795
[418]	validation_0-mae:2109.13397
[419]	validation_0-mae:2109.47005
[420]	validation_0-mae:2109.84248
[421]	validation_0-mae:2109.43730
[422]	validation_0-mae:2109.53972
[423]	validation_0-mae:2108.75937
[424]	validation_0-mae:2107.89401
[425]	validation_0-mae:2107.72896
[426]	validation_0-mae:2105.87399
[427]	validation_0-mae:2105.74959
[428]	validation_0-mae:2104.83685
[429]	validation_0-mae:2104.90110
[430]	validation_0-mae:2104.43482
[431]	validation_0-mae:2104.21665
[432]	validation_0-mae:2103.98920
[433]	validation_0-mae:2103.91294
[434]	validation_0-mae:2103.87811
[435]	validation_0-mae:2103.86905
[436]	validation_0-mae:2103.21200
[437]	validation_0-mae:2103.71958
[438]	validation_0-mae:2103.91637
[439]	validation_0-mae:2103.30818
[440]	validation_0-mae:2103.67029
[441]	validation_0-mae:2103.45307
[442]	validation_0-mae:2103.16727
[443]	validation_0-mae:2103.27890
[444]	validation_0-mae:2103.27752
[445]	validation_0-mae:2102.68836
[446]	validation_0-mae:2102.41928
[447]	validation_0-mae:2102.48536
[448]	validation_0-mae:2102.15702
[449]	validation_0-mae:2102.93579
[450]	validation_0-mae:2102.32377
[451]	validation_0-mae:2102.38131
[452]	validation_0-mae:2101.52461
[453]	validation_0-mae:2102.14138
[454]	validation_0-mae:2101.03184
[455]	validation_0-mae:2101.14060
[456]	validation_0-mae:2101.25675
[457]	validation_0-mae:2099.79423
[458]	validation_0-mae:2098.69654
[459]	validation_0-mae:2098.89243
[460]	validation_0-mae:2098.99106
[461]	validation_0-mae:2099.22041
[462]	validation_0-mae:2098.99039
[463]	validation_0-mae:2098.92529
[464]	validation_0-mae:2098.75119
[465]	validation_0-mae:2098.69029
[466]	validation_0-mae:2098.31711
[467]	validation_0-mae:2097.82714
[468]	validation_0-mae:2097.73801
[469]	validation_0-mae:2097.84940
[470]	validation_0-mae:2097.79773
[471]	validation_0-mae:2097.22198
[472]	validation_0-mae:2097.11189
[473]	validation_0-mae:2096.72977
[474]	validation_0-mae:2096.69322
[475]	validation_0-mae:2096.33074
[476]	validation_0-mae:2096.63999
[477]	validation_0-mae:2096.70506
[478]	validation_0-mae:2096.57436
[479]	validation_0-mae:2096.39504
[480]	validation_0-mae:2096.46839
[481]	validation_0-mae:2096.35181
[482]	validation_0-mae:2095.92021
[483]	validation_0-mae:2095.97544
[484]	validation_0-mae:2095.82649
[485]	validation_0-mae:2095.98204
[486]	validation_0-mae:2096.16177
[487]	validation_0-mae:2096.41861
[488]	validation_0-mae:2096.09056
[489]	validation_0-mae:2096.15124
[490]	validation_0-mae:2095.87387
[491]	validation_0-mae:2095.39097
[492]	validation_0-mae:2095.12029
[493]	validation_0-mae:2094.96881
[494]	validation_0-mae:2095.13719
[495]	validation_0-mae:2095.14354
[496]	validation_0-mae:2095.54799
[497]	validation_0-mae:2095.51919
[498]	validation_0-mae:2095.35200
[499]	validation_0-mae:2095.19035
[500]	validation_0-mae:2095.07729
[501]	validation_0-mae:2095.10805
[502]	validation_0-mae:2094.88986
[503]	validation_0-mae:2094.90831
[504]	validation_0-mae:2094.89755
[505]	validation_0-mae:2094.86894
[506]	validation_0-mae:2094.51208
[507]	validation_0-mae:2094.66738
[508]	validation_0-mae:2094.68877
[509]	validation_0-mae:2095.03819
[510]	validation_0-mae:2094.73167
[511]	validation_0-mae:2094.73697
[512]	validation_0-mae:2094.72842
[513]	validation_0-mae:2095.37125
[514]	validation_0-mae:2095.58345
[515]	validation_0-mae:2095.99743
[516]	validation_0-mae:2095.24097
[517]	validation_0-mae:2093.90686
[518]	validation_0-mae:2094.15548
[519]	validation_0-mae:2094.45835
[520]	validation_0-mae:2094.49688
[521]	validation_0-mae:2094.55719
[522]	validation_0-mae:2093.99006
[523]	validation_0-mae:2093.61712
[524]	validation_0-mae:2093.67026
[525]	validation_0-mae:2092.66121
[526]	validation_0-mae:2092.40392
[527]	validation_0-mae:2092.58136
[528]	validation_0-mae:2092.37094
[529]	validation_0-mae:2092.49479
[530]	validation_0-mae:2092.59146
[531]	validation_0-mae:2092.52451
[532]	validation_0-mae:2092.42612
[533]	validation_0-mae:2092.63084
[534]	validation_0-mae:2092.53060
[535]	validation_0-mae:2092.61064
[536]	validation_0-mae:2092.27763
[537]	validation_0-mae:2092.15855
[538]	validation_0-mae:2092.66595
[539]	validation_0-mae:2092.57969
[540]	validation_0-mae:2092.67055
[541]	validation_0-mae:2092.61972
[542]	validation_0-mae:2092.38856
[543]	validation_0-mae:2092.23368
[544]	validation_0-mae:2092.35415
[545]	validation_0-mae:2092.20282
[546]	validation_0-mae:2092.30110
[547]	validation_0-mae:2092.35568
[548]	validation_0-mae:2092.41893
[549]	validation_0-mae:2091.79306
[550]	validation_0-mae:2091.81660
[551]	validation_0-mae:2091.53147
[552]	validation_0-mae:2091.55704
[553]	validation_0-mae:2091.71824
[554]	validation_0-mae:2091.40628
[555]	validation_0-mae:2091.40102
[556]	validation_0-mae:2091.29507
[557]	validation_0-mae:2090.88021
[558]	validation_0-mae:2090.49552
[559]	validation_0-mae:2091.01009
[560]	validation_0-mae:2090.96149
[561]	validation_0-mae:2090.81743
[562]	validation_0-mae:2091.02583
[563]	validation_0-mae:2090.95993
[564]	validation_0-mae:2090.92047
[565]	validation_0-mae:2091.07144
[566]	validation_0-mae:2090.92121
[567]	validation_0-mae:2090.29118
[568]	validation_0-mae:2090.05017
[569]	validation_0-mae:2090.31613
[570]	validation_0-mae:2089.73743
[571]	validation_0-mae:2089.09259
[572]	validation_0-mae:2089.13694
[573]	validation_0-mae:2088.61996
[574]	validation_0-mae:2088.55044
[575]	validation_0-mae:2088.58814
[576]	validation_0-mae:2088.52528
[577]	validation_0-mae:2088.32792
[578]	validation_0-mae:2088.46864
[579]	validation_0-mae:2088.43800
[580]	validation_0-mae:2088.63054
[581]	validation_0-mae:2088.86722
[582]	validation_0-mae:2089.04169
[0]	validation_0-mae:12480.18442
[1]	validation_0-mae:11784.53364
[2]	validation_0-mae:11196.83347
[3]	validation_0-mae:10713.03314
[4]	validation_0-mae:10286.01287
[5]	validation_0-mae:9934.86774
[6]	validation_0-mae:9623.12994
[7]	validation_0-mae:9361.47239
[8]	validation_0-mae:9152.71015
[9]	validation_0-mae:8977.32241
[0]	validation_0-mae:12392.60423

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[1]	validation_0-mae:11608.07682
[2]	validation_0-mae:10897.57857
[3]	validation_0-mae:10248.51371
[4]	validation_0-mae:9670.39583
[5]	validation_0-mae:9150.16833
[6]	validation_0-mae:8699.88035
[7]	validation_0-mae:8281.20428
[8]	validation_0-mae:7894.07380
[9]	validation_0-mae:7500.28553
[10]	validation_0-mae:7194.59519
[11]	validation_0-mae:6877.15996
[12]	validation_0-mae:6598.17336
[13]	validation_0-mae:6348.79378
[14]	validation_0-mae:6096.40469
[15]	validation_0-mae:5850.94931
[16]	validation_0-mae:5659.67689
[17]	validation_0-mae:5472.82994
[18]	validation_0-mae:5271.32993
[19]	validation_0-mae:5114.96819
[20]	validation_0-mae:4961.08437
[21]	validation_0-mae:4785.78382
[22]	validation_0-mae:4644.77955
[23]	validation_0-mae:4531.14596
[24]	validation_0-mae:4403.63886
[25]	validation_0-mae:4294.50471
[26]	validation_0-mae:4189.93522
[27]	validation_0-mae:4082.03465
[28]	validation_0-mae:3995.79044
[29]	validation_0-mae:3902.41875
[30]	validation_0-mae:3811.44232
[31]	validation_0-mae:3726.26141
[32]	validation_0-mae:3650.63922
[33]	validation_0-mae:3580.60589
[34]	validation_0-mae:3523.00688
[35]	validation_0-mae:3464.60842
[36]	validation_0-mae:3409.90971
[37]	validation_0-mae:3361.01077
[38]	validation_0-mae:3317.36966
[39]	validation_0-mae:3263.73433
[40]	validation_0-mae:3220.59168
[41]	validation_0-mae:3186.69785
[42]	validation_0-mae:3151.88879
[43]	validation_0-mae:3116.84848
[44]	validation_0-mae:3084.87658
[45]	validation_0-mae:3057.81123
[46]	validation_0-mae:3033.52389
[47]	validation_0-mae:3002.63972
[48]	validation_0-mae:2979.67162
[49]	validation_0-mae:2959.98651
[50]	validation_0-mae:2937.06898
[51]	validation_0-mae:2910.20687
[52]	validation_0-mae:2893.71623
[53]	validation_0-mae:2876.22553
[54]	validation_0-mae:2855.60346
[55]	validation_0-mae:2837.99025
[56]	validation_0-mae:2823.16506
[57]	validation_0-mae:2781.43588
[58]	validation_0-mae:2767.69486
[59]	validation_0-mae:2757.37165
[60]	validation_0-mae:2746.64288
[61]	validation_0-mae:2718.10926
[62]	validation_0-mae:2705.32547
[63]	validation_0-mae:2695.29317
[64]	validation_0-mae:2686.42400
[65]	validation_0-mae:2677.96711
[66]	validation_0-mae:2651.81742
[67]	validation_0-mae:2644.52124
[68]	validation_0-mae:2638.57212
[69]	validation_0-mae:2623.01225
[70]	validation_0-mae:2604.28237
[71]	validation_0-mae:2596.20874
[72]	validation_0-mae:2580.21848
[73]	validation_0-mae:2570.92410
[74]	validation_0-mae:2561.54330
[75]	validation_0-mae:2552.19498
[76]	validation_0-mae:2537.93351
[77]	validation_0-mae:2525.30821
[78]	validation_0-mae:2512.28150
[79]	validation_0-mae:2505.98090
[80]	validation_0-mae:2501.17219
[81]	validation_0-mae:2492.71383
[82]	validation_0-mae:2484.74770
[83]	validation_0-mae:2474.95317
[84]	validation_0-mae:2467.85892
[85]	validation_0-mae:2461.89882
[86]	validation_0-mae:2454.02778
[87]	validation_0-mae:2451.02687
[88]	validation_0-mae:2441.41559
[89]	validation_0-mae:2435.90128
[90]	validation_0-mae:2429.06878
[91]	validation_0-mae:2425.90773
[92]	validation_0-mae:2419.52455
[93]	validation_0-mae:2411.58074
[94]	validation_0-mae:2404.08616
[95]	validation_0-mae:2397.70546
[96]	validation_0-mae:2385.74856
[97]	validation_0-mae:2383.02527
[98]	validation_0-mae:2380.47090
[99]	validation_0-mae:2376.31009
[100]	validation_0-mae:2374.28401
[101]	validation_0-mae:2369.95524
[102]	validation_0-mae:2362.82912
[103]	validation_0-mae:2362.42275
[104]	validation_0-mae:2355.33473
[105]	validation_0-mae:2352.87517
[106]	validation_0-mae:2349.48269
[107]	validation_0-mae:2345.92565
[108]	validation_0-mae:2342.65210
[109]	validation_0-mae:2339.53164
[110]	validation_0-mae:2336.93280
[111]	validation_0-mae:2333.34488
[112]	validation_0-mae:2327.34087
[113]	validation_0-mae:2324.55111
[114]	validation_0-mae:2319.54943
[115]	validation_0-mae:2316.43677
[116]	validation_0-mae:2309.40657
[117]	validation_0-mae:2308.21594
[118]	validation_0-mae:2309.01744
[119]	validation_0-mae:2307.86175
[120]	validation_0-mae:2306.99886
[121]	validation_0-mae:2307.25717
[122]	validation_0-mae:2307.97460
[123]	validation_0-mae:2302.82480
[124]	validation_0-mae:2302.61086
[125]	validation_0-mae:2299.41209
[126]	validation_0-mae:2298.93615
[127]	validation_0-mae:2298.38596
[128]	validation_0-mae:2296.73934
[129]	validation_0-mae:2295.35135
[130]	validation_0-mae:2290.17476
[131]	validation_0-mae:2287.42661
[132]	validation_0-mae:2283.54794
[133]	validation_0-mae:2283.15836
[134]	validation_0-mae:2279.87974
[135]	validation_0-mae:2275.16887
[136]	validation_0-mae:2271.94493
[137]	validation_0-mae:2271.01314
[138]	validation_0-mae:2269.43139
[139]	validation_0-mae:2267.22406
[140]	validation_0-mae:2266.00695
[141]	validation_0-mae:2264.72253
[142]	validation_0-mae:2262.45282
[143]	validation_0-mae:2261.93045
[144]	validation_0-mae:2259.88159
[145]	validation_0-mae:2258.10050
[146]	validation_0-mae:2258.21754
[147]	validation_0-mae:2256.81263
[148]	validation_0-mae:2255.49169
[149]	validation_0-mae:2254.93577
[150]	validation_0-mae:2252.52698
[151]	validation_0-mae:2253.99235
[152]	validation_0-mae:2253.95045
[153]	validation_0-mae:2253.06732
[154]	validation_0-mae:2251.02577
[155]	validation_0-mae:2249.00590
[156]	validation_0-mae:2249.05965
[157]	validation_0-mae:2249.60673
[158]	validation_0-mae:2248.08136
[159]	validation_0-mae:2246.78667
[160]	validation_0-mae:2246.57414
[161]	validation_0-mae:2245.56658
[162]	validation_0-mae:2245.32277
[163]	validation_0-mae:2243.46611
[164]	validation_0-mae:2243.19417
[165]	validation_0-mae:2242.66628
[166]	validation_0-mae:2242.23773
[167]	validation_0-mae:2241.39015
[168]	validation_0-mae:2240.13255
[169]	validation_0-mae:2238.93623
[170]	validation_0-mae:2237.61202
[171]	validation_0-mae:2237.48502
[172]	validation_0-mae:2236.68196
[173]	validation_0-mae:2234.37109
[174]	validation_0-mae:2232.39560
[175]	validation_0-mae:2231.27192
[176]	validation_0-mae:2230.01630
[177]	validation_0-mae:2230.29425
[178]	validation_0-mae:2229.72144
[179]	validation_0-mae:2228.11129
[180]	validation_0-mae:2227.73285
[181]	validation_0-mae:2225.28940
[182]	validation_0-mae:2223.49381
[183]	validation_0-mae:2222.73413
[184]	validation_0-mae:2221.48440
[185]	validation_0-mae:2221.29451
[186]	validation_0-mae:2221.72275
[187]	validation_0-mae:2222.01268
[188]	validation_0-mae:2221.02322
[189]	validation_0-mae:2220.94264
[190]	validation_0-mae:2220.64449
[191]	validation_0-mae:2221.73890
[192]	validation_0-mae:2221.61120
[193]	validation_0-mae:2219.20259
[194]	validation_0-mae:2219.67619
[195]	validation_0-mae:2218.79874
[196]	validation_0-mae:2214.55597
[197]	validation_0-mae:2214.67346
[198]	validation_0-mae:2212.55994
[199]	validation_0-mae:2211.95657
[200]	validation_0-mae:2210.84868
[201]	validation_0-mae:2207.58904
[202]	validation_0-mae:2207.24739
[203]	validation_0-mae:2204.67931
[204]	validation_0-mae:2204.75195
[205]	validation_0-mae:2205.12302
[206]	validation_0-mae:2205.74178
[207]	validation_0-mae:2204.45062
[208]	validation_0-mae:2204.17382
[209]	validation_0-mae:2202.34812
[210]	validation_0-mae:2203.46001
[211]	validation_0-mae:2201.62215
[212]	validation_0-mae:2198.89211
[213]	validation_0-mae:2197.52198
[214]	validation_0-mae:2197.41611
[215]	validation_0-mae:2198.24376
[216]	validation_0-mae:2197.75432
[217]	validation_0-mae:2198.02958
[218]	validation_0-mae:2198.72304
[219]	validation_0-mae:2197.77007
[220]	validation_0-mae:2198.23894
[221]	validation_0-mae:2198.28535
[222]	validation_0-mae:2195.27466
[223]	validation_0-mae:2195.53328
[224]	validation_0-mae:2194.17237
[225]	validation_0-mae:2193.51762
[226]	validation_0-mae:2193.28471
[227]	validation_0-mae:2193.54780
[228]	validation_0-mae:2193.42205
[229]	validation_0-mae:2193.21119
[230]	validation_0-mae:2194.18817
[231]	validation_0-mae:2194.16912
[232]	validation_0-mae:2193.90578
[233]	validation_0-mae:2193.78659
[234]	validation_0-mae:2193.75824
[235]	validation_0-mae:2193.80621
[236]	validation_0-mae:2193.64494
[237]	validation_0-mae:2193.57306
[238]	validation_0-mae:2193.22100
[239]	validation_0-mae:2192.70952
[240]	validation_0-mae:2194.27544
[241]	validation_0-mae:2193.02776
[242]	validation_0-mae:2193.24865
[243]	validation_0-mae:2193.11714
[244]	validation_0-mae:2191.77614
[245]	validation_0-mae:2191.37947
[246]	validation_0-mae:2190.51571
[247]	validation_0-mae:2189.76710
[248]	validation_0-mae:2188.39221
[249]	validation_0-mae:2188.97265
[250]	validation_0-mae:2189.69383
[251]	validation_0-mae:2188.49222
[252]	validation_0-mae:2188.22736
[253]	validation_0-mae:2188.82044
[254]	validation_0-mae:2188.89133
[255]	validation_0-mae:2188.70955
[256]	validation_0-mae:2189.46854
[257]	validation_0-mae:2187.71469
[258]	validation_0-mae:2187.43828
[259]	validation_0-mae:2186.92395
[260]	validation_0-mae:2186.44750
[261]	validation_0-mae:2185.80282
[262]	validation_0-mae:2185.95080
[263]	validation_0-mae:2185.72522
[264]	validation_0-mae:2183.04904
[265]	validation_0-mae:2183.47424
[266]	validation_0-mae:2182.75422
[267]	validation_0-mae:2182.39318
[268]	validation_0-mae:2183.09475
[269]	validation_0-mae:2183.15597
[270]	validation_0-mae:2183.42125
[271]	validation_0-mae:2182.86209
[272]	validation_0-mae:2183.31534
[273]	validation_0-mae:2183.22599
[274]	validation_0-mae:2183.53969
[275]	validation_0-mae:2183.45210
[276]	validation_0-mae:2183.49880
[277]	validation_0-mae:2183.86477
[278]	validation_0-mae:2183.49032
[279]	validation_0-mae:2183.66459
[280]	validation_0-mae:2183.04261
[281]	validation_0-mae:2182.34680
[282]	validation_0-mae:2182.32387
[283]	validation_0-mae:2182.51468
[284]	validation_0-mae:2182.88367
[285]	validation_0-mae:2183.09045
[286]	validation_0-mae:2183.08533
[287]	validation_0-mae:2183.06997
[288]	validation_0-mae:2182.60960
[289]	validation_0-mae:2182.77132
[290]	validation_0-mae:2182.37529
[291]	validation_0-mae:2181.88473
[292]	validation_0-mae:2181.45472
[293]	validation_0-mae:2181.74964
[294]	validation_0-mae:2181.65797
[295]	validation_0-mae:2179.96654
[296]	validation_0-mae:2179.01715
[297]	validation_0-mae:2178.81360
[298]	validation_0-mae:2177.61975
[299]	validation_0-mae:2176.17352
[300]	validation_0-mae:2175.38825
[301]	validation_0-mae:2173.96750
[302]	validation_0-mae:2174.56221
[303]	validation_0-mae:2174.51563
[304]	validation_0-mae:2173.82934
[305]	validation_0-mae:2173.73767
[306]	validation_0-mae:2173.83603
[307]	validation_0-mae:2173.50396
[308]	validation_0-mae:2172.06212
[309]	validation_0-mae:2171.75470
[310]	validation_0-mae:2171.60313
[311]	validation_0-mae:2171.60757
[312]	validation_0-mae:2171.53968
[313]	validation_0-mae:2170.98447
[314]	validation_0-mae:2170.97639
[315]	validation_0-mae:2171.09013
[316]	validation_0-mae:2170.80604
[317]	validation_0-mae:2170.80875
[318]	validation_0-mae:2169.46751
[319]	validation_0-mae:2169.24326
[320]	validation_0-mae:2168.01017
[321]	validation_0-mae:2167.89415
[322]	validation_0-mae:2167.11263
[323]	validation_0-mae:2166.80927
[324]	validation_0-mae:2166.37204
[325]	validation_0-mae:2167.48656
[326]	validation_0-mae:2166.32509
[327]	validation_0-mae:2165.10178
[328]	validation_0-mae:2164.30870
[329]	validation_0-mae:2164.90796
[330]	validation_0-mae:2165.12028
[331]	validation_0-mae:2165.26159
[332]	validation_0-mae:2163.06637
[333]	validation_0-mae:2162.93421
[334]	validation_0-mae:2162.61584
[335]	validation_0-mae:2161.57433
[336]	validation_0-mae:2161.59889
[337]	validation_0-mae:2161.70355
[338]	validation_0-mae:2161.85366
[339]	validation_0-mae:2161.60060
[340]	validation_0-mae:2161.40058
[341]	validation_0-mae:2161.02075
[342]	validation_0-mae:2160.85674
[343]	validation_0-mae:2160.65893
[344]	validation_0-mae:2160.58878
[345]	validation_0-mae:2159.93261
[346]	validation_0-mae:2158.83104
[347]	validation_0-mae:2157.63960
[348]	validation_0-mae:2157.37333
[349]	validation_0-mae:2157.19711
[350]	validation_0-mae:2157.01025
[351]	validation_0-mae:2156.72512
[352]	validation_0-mae:2157.12357
[353]	validation_0-mae:2155.86278
[354]	validation_0-mae:2155.60678
[355]	validation_0-mae:2154.84294
[356]	validation_0-mae:2154.84547
[357]	validation_0-mae:2154.67841
[358]	validation_0-mae:2154.80106
[359]	validation_0-mae:2154.52893
[360]	validation_0-mae:2154.86229
[361]	validation_0-mae:2155.08491
[362]	validation_0-mae:2155.38751
[363]	validation_0-mae:2154.98878
[364]	validation_0-mae:2154.89406
[365]	validation_0-mae:2154.10940
[366]	validation_0-mae:2152.46708
[367]	validation_0-mae:2152.19001
[368]	validation_0-mae:2152.03911
[369]	validation_0-mae:2152.17317
[370]	validation_0-mae:2152.59530
[371]	validation_0-mae:2152.78236
[372]	validation_0-mae:2152.62923
[373]	validation_0-mae:2152.50959
[374]	validation_0-mae:2152.39674
[375]	validation_0-mae:2151.60120
[376]	validation_0-mae:2151.84759
[377]	validation_0-mae:2151.97772
[378]	validation_0-mae:2152.15267
[379]	validation_0-mae:2152.10723
[380]	validation_0-mae:2150.95669
[381]	validation_0-mae:2151.06841
[382]	validation_0-mae:2150.57917
[383]	validation_0-mae:2150.95848
[384]	validation_0-mae:2151.20583
[385]	validation_0-mae:2151.12768
[386]	validation_0-mae:2151.02138
[387]	validation_0-mae:2151.38299
[388]	validation_0-mae:2151.46713
[389]	validation_0-mae:2151.68727
[390]	validation_0-mae:2151.40722
[391]	validation_0-mae:2151.04877
[392]	validation_0-mae:2150.97926
[393]	validation_0-mae:2149.75698
[394]	validation_0-mae:2149.63282
[395]	validation_0-mae:2150.35420
[396]	validation_0-mae:2149.79281
[397]	validation_0-mae:2148.23833
[398]	validation_0-mae:2147.95261
[399]	validation_0-mae:2147.70986
[400]	validation_0-mae:2146.73895
[401]	validation_0-mae:2146.49377
[402]	validation_0-mae:2145.94979
[403]	validation_0-mae:2145.41360
[404]	validation_0-mae:2144.11216
[405]	validation_0-mae:2143.78999
[406]	validation_0-mae:2142.10782
[407]	validation_0-mae:2142.54729
[408]	validation_0-mae:2141.54875
[409]	validation_0-mae:2141.31962
[410]	validation_0-mae:2141.96177
[411]	validation_0-mae:2142.14202
[412]	validation_0-mae:2141.91031
[413]	validation_0-mae:2140.15270
[414]	validation_0-mae:2140.25357
[415]	validation_0-mae:2140.26308
[416]	validation_0-mae:2140.24547
[417]	validation_0-mae:2139.77383
[418]	validation_0-mae:2139.93222
[419]	validation_0-mae:2140.02096
[420]	validation_0-mae:2140.41746
[421]	validation_0-mae:2140.74735
[422]	validation_0-mae:2139.51986
[423]	validation_0-mae:2139.88560
[424]	validation_0-mae:2139.18597
[425]	validation_0-mae:2139.13818
[426]	validation_0-mae:2139.20617
[427]	validation_0-mae:2139.30565
[428]	validation_0-mae:2139.04433
[429]	validation_0-mae:2138.84408
[430]	validation_0-mae:2139.31010
[431]	validation_0-mae:2139.44329
[432]	validation_0-mae:2138.99381
[433]	validation_0-mae:2139.22595
[434]	validation_0-mae:2139.10157
[435]	validation_0-mae:2138.23797
[436]	validation_0-mae:2138.18489
[437]	validation_0-mae:2138.36541
[438]	validation_0-mae:2138.62861
[439]	validation_0-mae:2138.81174
[440]	validation_0-mae:2138.46186
[441]	validation_0-mae:2137.09550
[442]	validation_0-mae:2137.12538
[443]	validation_0-mae:2136.65050
[444]	validation_0-mae:2136.71955
[445]	validation_0-mae:2137.07221
[446]	validation_0-mae:2136.76970
[447]	validation_0-mae:2136.79747
[448]	validation_0-mae:2136.98113
[449]	validation_0-mae:2135.70979
[450]	validation_0-mae:2136.01473
[451]	validation_0-mae:2136.25722
[452]	validation_0-mae:2135.04649
[453]	validation_0-mae:2135.15908
[454]	validation_0-mae:2135.10013
[455]	validation_0-mae:2134.74297
[456]	validation_0-mae:2134.60991
[457]	validation_0-mae:2134.61895
[458]	validation_0-mae:2134.69209
[459]	validation_0-mae:2134.58271
[460]	validation_0-mae:2134.53504
[461]	validation_0-mae:2135.23104
[462]	validation_0-mae:2135.47747
[463]	validation_0-mae:2134.96186
[464]	validation_0-mae:2134.83214
[465]	validation_0-mae:2133.52361
[466]	validation_0-mae:2133.31650
[467]	validation_0-mae:2131.50440
[468]	validation_0-mae:2131.65293
[469]	validation_0-mae:2131.56634
[470]	validation_0-mae:2130.94248
[471]	validation_0-mae:2131.01720
[472]	validation_0-mae:2131.27083
[473]	validation_0-mae:2131.36870
[474]	validation_0-mae:2131.33640
[475]	validation_0-mae:2131.56478
[476]	validation_0-mae:2131.19421
[477]	validation_0-mae:2131.48327
[478]	validation_0-mae:2131.52420
[479]	validation_0-mae:2131.62864
[480]	validation_0-mae:2131.77896
[481]	validation_0-mae:2131.61819
[482]	validation_0-mae:2131.73235
[483]	validation_0-mae:2131.33284
[484]	validation_0-mae:2131.17817
[485]	validation_0-mae:2130.70051
[486]	validation_0-mae:2130.43198
[487]	validation_0-mae:2130.66671
[488]	validation_0-mae:2130.85435
[489]	validation_0-mae:2130.37507
[490]	validation_0-mae:2130.59188
[491]	validation_0-mae:2129.82217
[492]	validation_0-mae:2129.30360
[493]	validation_0-mae:2129.54273
[494]	validation_0-mae:2129.48520
[495]	validation_0-mae:2129.36524
[496]	validation_0-mae:2129.50673
[497]	validation_0-mae:2129.54454
[498]	validation_0-mae:2129.16056
[499]	validation_0-mae:2128.97876
[500]	validation_0-mae:2128.78599
[0]	validation_0-mae:12490.90904
[1]	validation_0-mae:11783.28500
[2]	validation_0-mae:11140.58489
[3]	validation_0-mae:10525.97355
[4]	validation_0-mae:9986.25008
[5]	validation_0-mae:9496.11046
[6]	validation_0-mae:9048.97522
[7]	validation_0-mae:8637.18510
[8]	validation_0-mae:8251.08516
[9]	validation_0-mae:7909.27006
[10]	validation_0-mae:7605.01960
[11]	validation_0-mae:7332.11403
[12]	validation_0-mae:7045.40288
[13]	validation_0-mae:6780.05061
[14]	validation_0-mae:6545.14933
[15]	validation_0-mae:6326.48052
[16]	validation_0-mae:6111.04957
[17]	validation_0-mae:5911.31087
[18]	validation_0-mae:5722.42036
[19]	validation_0-mae:5545.15306
[20]	validation_0-mae:5387.58766
[21]	validation_0-mae:5211.49343
[22]	validation_0-mae:5059.18391
[23]	validation_0-mae:4910.74139
[24]	validation_0-mae:4788.38208
[25]	validation_0-mae:4661.74210
[26]	validation_0-mae:4543.67948
[27]	validation_0-mae:4436.62232
[28]	validation_0-mae:4329.73724
[29]	validation_0-mae:4224.66670
[30]	validation_0-mae:4136.91830
[31]	validation_0-mae:4049.15366
[32]	validation_0-mae:3968.90205
[33]	validation_0-mae:3881.87486
[34]	validation_0-mae:3818.12241
[35]	validation_0-mae:3743.72412
[36]	validation_0-mae:3668.67716
[37]	validation_0-mae:3608.08090
[38]	validation_0-mae:3545.91900
[39]	validation_0-mae:3499.12039
[40]	validation_0-mae:3446.15373
[41]	validation_0-mae:3400.11084
[42]	validation_0-mae:3361.14430
[43]	validation_0-mae:3316.17415

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[44]	validation_0-mae:3281.85202
[45]	validation_0-mae:3240.55061
[46]	validation_0-mae:3189.45932
[47]	validation_0-mae:3160.65131
[48]	validation_0-mae:3127.89191
[49]	validation_0-mae:3093.40803
[50]	validation_0-mae:3066.93371
[51]	validation_0-mae:3033.58931
[52]	validation_0-mae:3006.82421
[53]	validation_0-mae:2988.67459
[54]	validation_0-mae:2944.83524
[55]	validation_0-mae:2918.55558
[56]	validation_0-mae:2900.15348
[57]	validation_0-mae:2881.05297
[58]	validation_0-mae:2856.03718
[59]	validation_0-mae:2833.03542
[60]	validation_0-mae:2814.02022
[61]	validation_0-mae:2799.74743
[62]	validation_0-mae:2783.77291
[63]	validation_0-mae:2770.33419
[64]	validation_0-mae:2755.57900
[65]	validation_0-mae:2738.79849
[66]	validation_0-mae:2732.09527
[67]	validation_0-mae:2710.37662
[68]	validation_0-mae:2692.85640
[69]	validation_0-mae:2680.24853
[70]	validation_0-mae:2668.68790
[71]	validation_0-mae:2658.78911
[72]	validation_0-mae:2647.77916
[73]	validation_0-mae:2642.64908
[74]	validation_0-mae:2633.01664
[75]	validation_0-mae:2622.93004
[76]	validation_0-mae:2608.24970
[77]	validation_0-mae:2603.20197
[78]	validation_0-mae:2593.25783
[79]	validation_0-mae:2584.43621
[80]	validation_0-mae:2575.29917
[81]	validation_0-mae:2569.20598
[82]	validation_0-mae:2559.30509
[83]	validation_0-mae:2546.96877
[84]	validation_0-mae:2534.81982
[85]	validation_0-mae:2528.71638
[86]	validation_0-mae:2519.11301
[87]	validation_0-mae:2514.43446
[88]	validation_0-mae:2509.41950
[89]	validation_0-mae:2505.06741
[90]	validation_0-mae:2498.27756
[91]	validation_0-mae:2491.65179
[92]	validation_0-mae:2481.85904
[93]	validation_0-mae:2475.84600
[94]	validation_0-mae:2470.39744
[95]	validation_0-mae:2462.18214
[96]	validation_0-mae:2456.43869
[97]	validation_0-mae:2451.56970
[98]	validation_0-mae:2445.80072
[99]	validation_0-mae:2439.66823
[100]	validation_0-mae:2432.59654
[101]	validation_0-mae:2426.87818
[102]	validation_0-mae:2423.88169
[103]	validation_0-mae:2420.30264
[104]	validation_0-mae:2413.75872
[105]	validation_0-mae:2409.91339
[106]	validation_0-mae:2405.20904
[107]	validation_0-mae:2400.64680
[108]	validation_0-mae:2395.45234
[109]	validation_0-mae:2389.16410
[110]	validation_0-mae:2383.78905
[111]	validation_0-mae:2380.59294
[112]	validation_0-mae:2373.97996
[113]	validation_0-mae:2370.25347
[114]	validation_0-mae:2365.87774
[115]	validation_0-mae:2358.93051
[116]	validation_0-mae:2356.79156
[117]	validation_0-mae:2353.21433
[118]	validation_0-mae:2346.85851
[119]	validation_0-mae:2345.87369
[120]	validation_0-mae:2343.21511
[121]	validation_0-mae:2340.33076
[122]	validation_0-mae:2336.33688
[123]	validation_0-mae:2334.87864
[124]	validation_0-mae:2331.69208
[125]	validation_0-mae:2325.60834
[126]	validation_0-mae:2320.13217
[127]	validation_0-mae:2315.05682
[128]	validation_0-mae:2311.18549
[129]	validation_0-mae:2308.75078
[130]	validation_0-mae:2305.78687
[131]	validation_0-mae:2304.23374
[132]	validation_0-mae:2301.24170
[133]	validation_0-mae:2299.41246
[134]	validation_0-mae:2298.93211
[135]	validation_0-mae:2297.01622
[136]	validation_0-mae:2293.45090
[137]	validation_0-mae:2292.80867
[138]	validation_0-mae:2287.67884
[139]	validation_0-mae:2285.68025
[140]	validation_0-mae:2285.28076
[141]	validation_0-mae:2281.05286
[142]	validation_0-mae:2279.45823
[143]	validation_0-mae:2278.72854
[144]	validation_0-mae:2274.21511
[145]	validation_0-mae:2271.19662
[146]	validation_0-mae:2266.58423
[147]	validation_0-mae:2262.99667
[148]	validation_0-mae:2262.99469
[149]	validation_0-mae:2259.53819
[150]	validation_0-mae:2258.03710
[151]	validation_0-mae:2254.59704
[152]	validation_0-mae:2252.13822
[153]	validation_0-mae:2251.62713
[154]	validation_0-mae:2251.06512
[155]	validation_0-mae:2247.29070
[156]	validation_0-mae:2243.62814
[157]	validation_0-mae:2242.61648
[158]	validation_0-mae:2239.69425
[159]	validation_0-mae:2237.17826
[160]	validation_0-mae:2236.66084
[161]	validation_0-mae:2234.75183
[162]	validation_0-mae:2234.43698
[163]	validation_0-mae:2232.25414
[164]	validation_0-mae:2229.60112
[165]	validation_0-mae:2229.23995
[166]	validation_0-mae:2226.31210
[167]	validation_0-mae:2225.87867
[168]	validation_0-mae:2225.25827
[169]	validation_0-mae:2223.14617
[170]	validation_0-mae:2222.72443
[171]	validation_0-mae:2220.29478
[172]	validation_0-mae:2219.81194
[173]	validation_0-mae:2220.06163
[174]	validation_0-mae:2217.68834
[175]	validation_0-mae:2217.76935
[176]	validation_0-mae:2217.10477
[177]	validation_0-mae:2214.40229
[178]	validation_0-mae:2213.67577
[179]	validation_0-mae:2212.30813
[180]	validation_0-mae:2210.95520
[181]	validation_0-mae:2210.76925
[182]	validation_0-mae:2208.86036
[183]	validation_0-mae:2208.25362
[184]	validation_0-mae:2207.24953
[185]	validation_0-mae:2206.04494
[186]	validation_0-mae:2204.61301
[187]	validation_0-mae:2201.74213
[188]	validation_0-mae:2200.02951
[189]	validation_0-mae:2197.96108
[190]	validation_0-mae:2197.45600
[191]	validation_0-mae:2197.49339
[192]	validation_0-mae:2196.39833
[193]	validation_0-mae:2196.46209
[194]	validation_0-mae:2196.62951
[195]	validation_0-mae:2194.52021
[196]	validation_0-mae:2192.13795
[197]	validation_0-mae:2191.72088
[198]	validation_0-mae:2189.09290
[199]	validation_0-mae:2188.86077
[200]	validation_0-mae:2188.61005
[201]	validation_0-mae:2187.29102
[202]	validation_0-mae:2186.16380
[203]	validation_0-mae:2186.14024
[204]	validation_0-mae:2185.00051
[205]	validation_0-mae:2184.58037
[206]	validation_0-mae:2182.61109
[207]	validation_0-mae:2182.58850
[208]	validation_0-mae:2182.13351
[209]	validation_0-mae:2181.58754
[210]	validation_0-mae:2181.28415
[211]	validation_0-mae:2181.06709
[212]	validation_0-mae:2181.16296
[213]	validation_0-mae:2182.15410
[214]	validation_0-mae:2181.53936
[215]	validation_0-mae:2181.66520
[216]	validation_0-mae:2182.17812
[217]	validation_0-mae:2181.97298
[218]	validation_0-mae:2181.99932
[219]	validation_0-mae:2182.17939
[220]	validation_0-mae:2182.08708
[221]	validation_0-mae:2181.01546
[222]	validation_0-mae:2179.89198
[223]	validation_0-mae:2180.45369
[224]	validation_0-mae:2178.29993
[225]	validation_0-mae:2179.02758
[226]	validation_0-mae:2179.39370
[227]	validation_0-mae:2178.36053
[228]	validation_0-mae:2177.32071
[229]	validation_0-mae:2177.29460
[230]	validation_0-mae:2177.57743
[231]	validation_0-mae:2178.00225
[232]	validation_0-mae:2178.59921
[233]	validation_0-mae:2178.67260
[234]	validation_0-mae:2179.11769
[235]	validation_0-mae:2179.02346
[236]	validation_0-mae:2179.17270
[237]	validation_0-mae:2179.43275
[238]	validation_0-mae:2178.85731
[239]	validation_0-mae:2179.46577
[240]	validation_0-mae:2178.70770
[241]	validation_0-mae:2179.38227
[242]	validation_0-mae:2179.75069
[243]	validation_0-mae:2179.43634
[244]	validation_0-mae:2177.66459
[245]	validation_0-mae:2178.19560
[246]	validation_0-mae:2177.29669
[247]	validation_0-mae:2177.09222
[248]	validation_0-mae:2176.83365
[249]	validation_0-mae:2176.93027
[250]	validation_0-mae:2175.85344
[251]	validation_0-mae:2175.74835
[252]	validation_0-mae:2172.98017
[253]	validation_0-mae:2172.94844
[254]	validation_0-mae:2171.81010
[255]	validation_0-mae:2171.82879
[256]	validation_0-mae:2171.41062
[257]	validation_0-mae:2171.54409
[258]	validation_0-mae:2170.76310
[259]	validation_0-mae:2171.16413
[260]	validation_0-mae:2170.67319
[261]	validation_0-mae:2170.82051
[262]	validation_0-mae:2171.10034
[263]	validation_0-mae:2172.18825
[264]	validation_0-mae:2171.53296
[265]	validation_0-mae:2171.43863
[266]	validation_0-mae:2171.34135
[267]	validation_0-mae:2172.09491
[268]	validation_0-mae:2170.28314
[269]	validation_0-mae:2170.98705
[270]	validation_0-mae:2170.09624
[271]	validation_0-mae:2169.61894
[272]	validation_0-mae:2168.69987
[273]	validation_0-mae:2168.34956
[274]	validation_0-mae:2167.64538
[275]	validation_0-mae:2166.01874
[276]	validation_0-mae:2166.53818
[277]	validation_0-mae:2166.48779
[278]	validation_0-mae:2166.12401
[279]	validation_0-mae:2166.27114
[280]	validation_0-mae:2167.33183
[281]	validation_0-mae:2166.57138
[282]	validation_0-mae:2166.14679
[283]	validation_0-mae:2165.49391
[284]	validation_0-mae:2165.50304
[285]	validation_0-mae:2165.40899
[286]	validation_0-mae:2165.44285
[287]	validation_0-mae:2166.17655
[288]	validation_0-mae:2166.11405
[289]	validation_0-mae:2166.50540
[290]	validation_0-mae:2166.48235
[291]	validation_0-mae:2164.85071
[292]	validation_0-mae:2165.29864
[293]	validation_0-mae:2164.88868
[294]	validation_0-mae:2164.81003
[295]	validation_0-mae:2164.57411
[296]	validation_0-mae:2164.14434
[297]	validation_0-mae:2163.13596
[298]	validation_0-mae:2162.52967
[299]	validation_0-mae:2162.62757
[300]	validation_0-mae:2162.58861
[301]	validation_0-mae:2161.07992
[302]	validation_0-mae:2160.56701
[303]	validation_0-mae:2160.01092
[304]	validation_0-mae:2160.10915
[305]	validation_0-mae:2159.87116
[306]	validation_0-mae:2159.27513
[307]	validation_0-mae:2158.39868
[308]	validation_0-mae:2157.03826
[309]	validation_0-mae:2157.45649
[310]	validation_0-mae:2157.08646
[311]	validation_0-mae:2156.45113
[312]	validation_0-mae:2156.31053
[313]	validation_0-mae:2155.93302
[314]	validation_0-mae:2155.40101
[315]	validation_0-mae:2156.13628
[316]	validation_0-mae:2156.43942
[317]	validation_0-mae:2156.29666
[318]	validation_0-mae:2156.32019
[319]	validation_0-mae:2155.31940
[320]	validation_0-mae:2154.81173
[321]	validation_0-mae:2154.69562
[322]	validation_0-mae:2154.32671
[323]	validation_0-mae:2154.26237
[324]	validation_0-mae:2153.86673
[325]	validation_0-mae:2153.69763
[326]	validation_0-mae:2153.71996
[327]	validation_0-mae:2154.02109
[328]	validation_0-mae:2153.45332
[329]	validation_0-mae:2151.91480
[330]	validation_0-mae:2151.90823
[331]	validation_0-mae:2151.31407
[332]	validation_0-mae:2150.77004
[333]	validation_0-mae:2150.90990
[334]	validation_0-mae:2150.94550
[335]	validation_0-mae:2150.92038
[336]	validation_0-mae:2150.95579
[337]	validation_0-mae:2149.98118
[338]	validation_0-mae:2150.60946
[339]	validation_0-mae:2150.96033
[340]	validation_0-mae:2149.76684
[341]	validation_0-mae:2150.10500
[342]	validation_0-mae:2150.21544
[343]	validation_0-mae:2150.38821
[344]	validation_0-mae:2148.97082
[345]	validation_0-mae:2149.28364
[346]	validation_0-mae:2149.25118
[347]	validation_0-mae:2149.05753
[348]	validation_0-mae:2149.28926
[349]	validation_0-mae:2150.03278
[350]	validation_0-mae:2149.44774
[351]	validation_0-mae:2148.15162
[352]	validation_0-mae:2147.47695
[353]	validation_0-mae:2147.78872
[354]	validation_0-mae:2147.67444
[355]	validation_0-mae:2147.48345
[356]	validation_0-mae:2147.65287
[357]	validation_0-mae:2147.42474
[358]	validation_0-mae:2146.49996
[359]	validation_0-mae:2146.63336
[360]	validation_0-mae:2146.61466
[361]	validation_0-mae:2146.54128
[362]	validation_0-mae:2145.97212
[363]	validation_0-mae:2144.78336
[364]	validation_0-mae:2144.42251
[365]	validation_0-mae:2143.65750
[366]	validation_0-mae:2144.00209
[367]	validation_0-mae:2144.04492
[368]	validation_0-mae:2144.70543
[369]	validation_0-mae:2144.23356
[370]	validation_0-mae:2144.13479
[371]	validation_0-mae:2144.26320
[372]	validation_0-mae:2143.77081
[373]	validation_0-mae:2143.94649
[374]	validation_0-mae:2143.90818
[375]	validation_0-mae:2143.95374
[376]	validation_0-mae:2143.04391
[377]	validation_0-mae:2143.39085
[378]	validation_0-mae:2142.24986
[379]	validation_0-mae:2142.28301
[380]	validation_0-mae:2142.33908
[381]	validation_0-mae:2143.06818
[382]	validation_0-mae:2142.84088
[383]	validation_0-mae:2141.13983
[384]	validation_0-mae:2141.02264
[385]	validation_0-mae:2141.90425
[386]	validation_0-mae:2141.58337
[387]	validation_0-mae:2142.57421
[388]	validation_0-mae:2142.40246
[389]	validation_0-mae:2142.37026
[390]	validation_0-mae:2142.18057
[391]	validation_0-mae:2143.20995
[392]	validation_0-mae:2143.03051
[393]	validation_0-mae:2143.81599
[394]	validation_0-mae:2144.57512
[395]	validation_0-mae:2144.92741
[396]	validation_0-mae:2144.89244
[397]	validation_0-mae:2144.71061
[398]	validation_0-mae:2144.59531
[399]	validation_0-mae:2144.75114
[400]	validation_0-mae:2144.13477
[401]	validation_0-mae:2143.88041
[402]	validation_0-mae:2143.33771
[403]	validation_0-mae:2143.24608
[404]	validation_0-mae:2143.56613
[405]	validation_0-mae:2144.24817
[406]	validation_0-mae:2143.98912
[407]	validation_0-mae:2144.04929
[408]	validation_0-mae:2143.20929
[409]	validation_0-mae:2143.09087
[410]	validation_0-mae:2142.97683
[411]	validation_0-mae:2143.13022
[412]	validation_0-mae:2142.99517
[413]	validation_0-mae:2143.01698
[414]	validation_0-mae:2143.01757
[415]	validation_0-mae:2143.31750
[416]	validation_0-mae:2143.30722
[417]	validation_0-mae:2143.19413
[418]	validation_0-mae:2143.93484
[419]	validation_0-mae:2143.89884
[420]	validation_0-mae:2142.25669
[421]	validation_0-mae:2142.24525
[422]	validation_0-mae:2141.72480
[423]	validation_0-mae:2141.83621
[424]	validation_0-mae:2141.29364
[425]	validation_0-mae:2141.24079
[426]	validation_0-mae:2141.48877
[427]	validation_0-mae:2141.39526
[428]	validation_0-mae:2141.36466
[429]	validation_0-mae:2141.39911
[430]	validation_0-mae:2141.72261
[431]	validation_0-mae:2140.89055
[432]	validation_0-mae:2140.70374
[433]	validation_0-mae:2141.04574
[434]	validation_0-mae:2140.87109
[435]	validation_0-mae:2141.19452
[436]	validation_0-mae:2141.01370
[437]	validation_0-mae:2141.28482
[438]	validation_0-mae:2140.50019
[439]	validation_0-mae:2140.15141
[440]	validation_0-mae:2140.30870
[441]	validation_0-mae:2140.33000
[442]	validation_0-mae:2140.25881
[443]	validation_0-mae:2139.71641
[444]	validation_0-mae:2139.42368
[445]	validation_0-mae:2139.37894
[446]	validation_0-mae:2139.23634
[447]	validation_0-mae:2138.35135
[448]	validation_0-mae:2138.23690
[449]	validation_0-mae:2137.59010
[450]	validation_0-mae:2137.88060
[451]	validation_0-mae:2137.91111
[452]	validation_0-mae:2136.81917
[453]	validation_0-mae:2136.81996
[454]	validation_0-mae:2137.24521
[455]	validation_0-mae:2137.54247
[456]	validation_0-mae:2137.37632
[457]	validation_0-mae:2137.60126
[458]	validation_0-mae:2137.62463
[459]	validation_0-mae:2137.58587
[460]	validation_0-mae:2137.89830
[461]	validation_0-mae:2137.20557
[462]	validation_0-mae:2137.25034
[463]	validation_0-mae:2137.07031
[464]	validation_0-mae:2137.18522
[465]	validation_0-mae:2137.33730
[466]	validation_0-mae:2137.38599
[467]	validation_0-mae:2137.52343
[468]	validation_0-mae:2137.96137
[469]	validation_0-mae:2137.83235
[470]	validation_0-mae:2138.29536
[471]	validation_0-mae:2138.18659
[472]	validation_0-mae:2138.41370
[473]	validation_0-mae:2138.10854
[474]	validation_0-mae:2137.00445
[475]	validation_0-mae:2136.79055
[476]	validation_0-mae:2136.48610
[477]	validation_0-mae:2135.75731
[478]	validation_0-mae:2135.55953
[479]	validation_0-mae:2135.59684
[480]	validation_0-mae:2135.26478
[481]	validation_0-mae:2135.36358
[482]	validation_0-mae:2135.71853
[483]	validation_0-mae:2135.45057
[484]	validation_0-mae:2135.18952
[485]	validation_0-mae:2134.91231
[486]	validation_0-mae:2135.24546
[487]	validation_0-mae:2135.53623
[488]	validation_0-mae:2135.73484
[489]	validation_0-mae:2135.90936
[490]	validation_0-mae:2136.08959
[491]	validation_0-mae:2135.92661
[492]	validation_0-mae:2135.69567
[493]	validation_0-mae:2135.36673
[494]	validation_0-mae:2135.67450
[495]	validation_0-mae:2135.63522
[496]	validation_0-mae:2135.80573
[497]	validation_0-mae:2135.91026
[498]	validation_0-mae:2135.80677
[499]	validation_0-mae:2135.65148
[500]	validation_0-mae:2135.60886
[501]	validation_0-mae:2135.12205
[502]	validation_0-mae:2135.40145
[503]	validation_0-mae:2135.43889
[504]	validation_0-mae:2135.61623
[505]	validation_0-mae:2135.58266
[506]	validation_0-mae:2135.89114
[507]	validation_0-mae:2135.96485
[508]	validation_0-mae:2135.71552
[509]	validation_0-mae:2135.42074
[510]	validation_0-mae:2135.44001
[511]	validation_0-mae:2135.31716
[512]	validation_0-mae:2135.15636
[513]	validation_0-mae:2134.83211
[514]	validation_0-mae:2134.76967
[515]	validation_0-mae:2134.50505
[516]	validation_0-mae:2134.47499
[517]	validation_0-mae:2133.65744
[518]	validation_0-mae:2133.80217
[519]	validation_0-mae:2133.02088
[520]	validation_0-mae:2132.78221
[521]	validation_0-mae:2132.33008
[522]	validation_0-mae:2132.48670
[523]	validation_0-mae:2131.44610
[524]	validation_0-mae:2131.17722
[525]	validation_0-mae:2130.85294
[526]	validation_0-mae:2130.92503
[527]	validation_0-mae:2130.62481
[528]	validation_0-mae:2130.65098
[529]	validation_0-mae:2130.27410
[530]	validation_0-mae:2130.05489
[531]	validation_0-mae:2130.22772
[532]	validation_0-mae:2129.80512
[533]	validation_0-mae:2130.07926
[534]	validation_0-mae:2129.79895
[535]	validation_0-mae:2129.79018
[536]	validation_0-mae:2129.89852
[537]	validation_0-mae:2130.07429
[538]	validation_0-mae:2130.36477
[539]	validation_0-mae:2130.47693
[540]	validation_0-mae:2130.58965
[541]	validation_0-mae:2130.33826
[542]	validation_0-mae:2130.39914
[543]	validation_0-mae:2130.44190
[544]	validation_0-mae:2130.36012
[545]	validation_0-mae:2130.44020
[546]	validation_0-mae:2130.17207
[547]	validation_0-mae:2130.28293
[548]	validation_0-mae:2130.32264
[549]	validation_0-mae:2130.50942
[550]	validation_0-mae:2130.76498
[551]	validation_0-mae:2130.70670
[552]	validation_0-mae:2130.77084
[553]	validation_0-mae:2130.84871
[554]	validation_0-mae:2130.88804
[555]	validation_0-mae:2130.23694
[556]	validation_0-mae:2130.15593
[557]	validation_0-mae:2129.95114
[558]	validation_0-mae:2129.63750
[559]	validation_0-mae:2129.58826
[0]	validation_0-mae:12444.00342
[1]	validation_0-mae:11717.36705
[2]	validation_0-mae:11061.57073
[3]	validation_0-mae:10488.82638
[4]	validation_0-mae:9978.82174
[5]	validation_0-mae:9530.61659
[6]	validation_0-mae:9145.92138
[7]	validation_0-mae:8798.70940
[8]	validation_0-mae:8485.80304
[9]	validation_0-mae:8191.02693
[10]	validation_0-mae:7916.98882
[11]	validation_0-mae:7677.17772

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[0]	validation_0-mae:12481.50481
[1]	validation_0-mae:11781.36126
[2]	validation_0-mae:11156.93777
[3]	validation_0-mae:10579.25314
[4]	validation_0-mae:10058.70871
[5]	validation_0-mae:9591.07515
[6]	validation_0-mae:9182.00269
[7]	validation_0-mae:8781.63452
[8]	validation_0-mae:8435.00713
[9]	validation_0-mae:8102.66391
[10]	validation_0-mae:7792.61742
[11]	validation_0-mae:7511.16868
[12]	validation_0-mae:7242.79875
[13]	validation_0-mae:7007.60908
[14]	validation_0-mae:6761.46649
[15]	validation_0-mae:6525.66905
[16]	validation_0-mae:6319.07284
[17]	validation_0-mae:6118.18257
[18]	validation_0-mae:5934.20577
[19]	validation_0-mae:5757.20255
[20]	validation_0-mae:5583.05288
[21]	validation_0-mae:5446.25457
[22]	validation_0-mae:5313.30765
[23]	validation_0-mae:5176.47572
[24]	validation_0-mae:5037.02900
[25]	validation_0-mae:4887.45465
[26]	validation_0-mae:4778.28561
[27]	validation_0-mae:4664.02479
[28]	validation_0-mae:4571.30042
[29]	validation_0-mae:4467.32785
[30]	validation_0-mae:4388.14613
[31]	validation_0-mae:4289.42631
[32]	validation_0-mae:4217.03993
[33]	validation_0-mae:4124.69157
[34]	validation_0-mae:4058.27335
[35]	validation_0-mae:3988.37384
[36]	validation_0-mae:3932.62070
[37]	validation_0-mae:3860.83653
[38]	validation_0-mae:3798.08473
[39]	validation_0-mae:3761.27671
[40]	validation_0-mae:3711.59865
[41]	validation_0-mae:3660.72306
[42]	validation_0-mae:3609.36459
[43]	validation_0-mae:3565.50238
[44]	validation_0-mae:3520.41489
[45]	validation_0-mae:3479.68329
[46]	validation_0-mae:3435.06508
[47]	validation_0-mae:3396.38931
[48]	validation_0-mae:3356.97453
[49]	validation_0-mae:3321.48670
[50]	validation_0-mae:3281.23174
[51]	validation_0-mae:3237.59421
[52]	validation_0-mae:3205.23932
[53]	validation_0-mae:3175.71587
[54]	validation_0-mae:3151.70800
[55]	validation_0-mae:3130.65766
[56]	validation_0-mae:3103.29737
[57]	validation_0-mae:3084.64364
[58]	validation_0-mae:3068.55222
[59]	validation_0-mae:3049.53775
[60]	validation_0-mae:3023.01808
[61]	validation_0-mae:3008.27012
[62]	validation_0-mae:2983.43039
[63]	validation_0-mae:2972.21472
[64]	validation_0-mae:2958.80564
[65]	validation_0-mae:2945.75816
[66]	validation_0-mae:2932.32608
[67]	validation_0-mae:2921.29502
[68]	validation_0-mae:2906.04523
[69]	validation_0-mae:2884.98417
[70]	validation_0-mae:2870.82950
[71]	validation_0-mae:2858.67315
[72]	validation_0-mae:2834.40142
[73]	validation_0-mae:2814.03881
[74]	validation_0-mae:2804.28939
[75]	validation_0-mae:2787.70117
[76]	validation_0-mae:2766.58348
[77]	validation_0-mae:2754.77967
[78]	validation_0-mae:2747.81220
[79]	validation_0-mae:2738.80186
[80]	validation_0-mae:2723.75880
[81]	validation_0-mae:2719.69192
[82]	validation_0-mae:2709.43488
[83]	validation_0-mae:2705.88215
[84]	validation_0-mae:2691.30032
[85]	validation_0-mae:2682.32150
[86]	validation_0-mae:2676.91630
[87]	validation_0-mae:2667.91188
[88]	validation_0-mae:2653.43863
[89]	validation_0-mae:2642.60089
[90]	validation_0-mae:2630.36481
[91]	validation_0-mae:2621.23766
[92]	validation_0-mae:2617.29395
[93]	validation_0-mae:2612.81103
[94]	validation_0-mae:2603.75254
[95]	validation_0-mae:2594.72893
[96]	validation_0-mae:2585.64184
[97]	validation_0-mae:2572.56965
[98]	validation_0-mae:2565.37717
[99]	validation_0-mae:2557.84690
[100]	validation_0-mae:2552.64899
[101]	validation_0-mae:2545.35016
[102]	validation_0-mae:2538.32125
[103]	validation_0-mae:2532.85541
[104]	validation_0-mae:2525.07796
[105]	validation_0-mae:2516.70084
[106]	validation_0-mae:2509.81207
[107]	validation_0-mae:2504.05279
[108]	validation_0-mae:2498.75211
[109]	validation_0-mae:2490.47443
[110]	validation_0-mae:2487.34897
[111]	validation_0-mae:2484.56379
[112]	validation_0-mae:2480.74549
[113]	validation_0-mae:2475.99763
[114]	validation_0-mae:2469.65186
[115]	validation_0-mae:2467.93238
[116]	validation_0-mae:2463.99386
[117]	validation_0-mae:2459.38393
[118]	validation_0-mae:2451.63924
[119]	validation_0-mae:2448.45823
[120]	validation_0-mae:2443.76656
[121]	validation_0-mae:2441.09875
[122]	validation_0-mae:2437.74019
[123]	validation_0-mae:2433.55646
[124]	validation_0-mae:2431.97232
[125]	validation_0-mae:2427.68118
[126]	validation_0-mae:2422.51060
[127]	validation_0-mae:2417.48828
[128]	validation_0-mae:2411.37620
[129]	validation_0-mae:2406.43708
[130]	validation_0-mae:2404.32467
[131]	validation_0-mae:2400.56233
[132]	validation_0-mae:2393.67816
[133]	validation_0-mae:2392.65056
[134]	validation_0-mae:2391.58984
[135]	validation_0-mae:2387.38484
[136]	validation_0-mae:2383.13795
[137]	validation_0-mae:2378.15719
[138]	validation_0-mae:2374.36894
[139]	validation_0-mae:2370.58237
[140]	validation_0-mae:2364.67648
[141]	validation_0-mae:2362.71777
[142]	validation_0-mae:2360.58979
[143]	validation_0-mae:2359.59818
[144]	validation_0-mae:2358.73646
[145]	validation_0-mae:2356.51929
[146]	validation_0-mae:2354.00196
[147]	validation_0-mae:2352.48826
[148]	validation_0-mae:2349.00693
[149]	validation_0-mae:2347.32637
[150]	validation_0-mae:2344.18425
[151]	validation_0-mae:2341.49119
[152]	validation_0-mae:2338.65701
[153]	validation_0-mae:2338.38070
[154]	validation_0-mae:2337.28447
[155]	validation_0-mae:2336.00683
[156]	validation_0-mae:2334.69884
[0]	validation_0-mae:12538.54858
[1]	validation_0-mae:11862.57872
[2]	validation_0-mae:11264.46323
[3]	validation_0-mae:10706.12317
[4]	validation_0-mae:10209.31940
[5]	validation_0-mae:9745.18937
[6]	validation_0-mae:9345.11853
[7]	validation_0-mae:8973.50285
[8]	validation_0-mae:8653.34657
[9]	validation_0-mae:8366.12707
[10]	validation_0-mae:8107.09270
[0]	validation_0-mae:12463.42867

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[1]	validation_0-mae:11748.25187
[2]	validation_0-mae:11087.98941
[3]	validation_0-mae:10476.43834
[4]	validation_0-mae:9939.72502
[5]	validation_0-mae:9459.83513
[6]	validation_0-mae:8991.83997
[7]	validation_0-mae:8574.77888
[8]	validation_0-mae:8184.16847
[9]	validation_0-mae:7843.80002
[10]	validation_0-mae:7531.16875
[11]	validation_0-mae:7225.83722
[12]	validation_0-mae:6966.65606
[13]	validation_0-mae:6712.04716
[14]	validation_0-mae:6462.39972
[15]	validation_0-mae:6223.92896
[16]	validation_0-mae:6019.82373
[17]	validation_0-mae:5804.60262
[18]	validation_0-mae:5614.69194
[19]	validation_0-mae:5444.46902
[20]	validation_0-mae:5271.73582
[21]	validation_0-mae:5104.59601
[22]	validation_0-mae:4949.83112
[23]	validation_0-mae:4809.08195
[24]	validation_0-mae:4678.54766
[25]	validation_0-mae:4556.49963
[26]	validation_0-mae:4437.90108
[27]	validation_0-mae:4334.77184
[28]	validation_0-mae:4218.76300
[29]	validation_0-mae:4110.07756
[30]	validation_0-mae:4018.01268
[31]	validation_0-mae:3930.03011
[32]	validation_0-mae:3844.01578
[33]	validation_0-mae:3762.89695
[34]	validation_0-mae:3691.98783
[35]	validation_0-mae:3622.90847
[36]	validation_0-mae:3561.54601
[37]	validation_0-mae:3508.60155
[38]	validation_0-mae:3457.00862
[39]	validation_0-mae:3401.85576
[40]	validation_0-mae:3336.74816
[41]	validation_0-mae:3294.06403
[42]	validation_0-mae:3243.97986
[43]	validation_0-mae:3204.70459
[44]	validation_0-mae:3169.78003
[45]	validation_0-mae:3136.90246
[46]	validation_0-mae:3087.55095
[47]	validation_0-mae:3053.47191
[48]	validation_0-mae:3022.81237
[49]	validation_0-mae:2996.69481
[50]	validation_0-mae:2962.08045
[51]	validation_0-mae:2936.53795
[52]	validation_0-mae:2916.08171
[53]	validation_0-mae:2886.79385
[54]	validation_0-mae:2866.90009
[55]	validation_0-mae:2845.65933
[56]	validation_0-mae:2829.78793
[57]	validation_0-mae:2807.91736
[58]	validation_0-mae:2784.87134
[59]	validation_0-mae:2762.34977
[60]	validation_0-mae:2738.98291
[61]	validation_0-mae:2723.77430
[62]	validation_0-mae:2706.08003
[63]	validation_0-mae:2682.85562
[64]	validation_0-mae:2667.95121
[65]	validation_0-mae:2645.63110
[66]	validation_0-mae:2634.48553
[67]	validation_0-mae:2626.22532
[68]	validation_0-mae:2615.21350
[69]	validation_0-mae:2600.76226
[70]	validation_0-mae:2575.59353
[71]	validation_0-mae:2566.70826
[72]	validation_0-mae:2551.53829
[73]	validation_0-mae:2539.49348
[74]	validation_0-mae:2523.52820
[75]	validation_0-mae:2517.30378
[76]	validation_0-mae:2509.62473
[77]	validation_0-mae:2501.31881
[78]	validation_0-mae:2487.45097
[79]	validation_0-mae:2471.40197
[80]	validation_0-mae:2465.11754
[81]	validation_0-mae:2453.97205
[82]	validation_0-mae:2449.42484
[83]	validation_0-mae:2441.19846
[84]	validation_0-mae:2430.86739
[85]	validation_0-mae:2422.34535
[86]	validation_0-mae:2418.53315
[87]	validation_0-mae:2412.24589
[88]	validation_0-mae:2405.40919
[89]	validation_0-mae:2397.92369
[90]	validation_0-mae:2389.45058
[91]	validation_0-mae:2383.24290
[92]	validation_0-mae:2377.87179
[93]	validation_0-mae:2370.30984
[94]	validation_0-mae:2363.21268
[95]	validation_0-mae:2358.73962
[96]	validation_0-mae:2350.59939
[97]	validation_0-mae:2348.97292
[98]	validation_0-mae:2343.12868
[99]	validation_0-mae:2332.46196
[100]	validation_0-mae:2326.32779
[101]	validation_0-mae:2323.26997
[102]	validation_0-mae:2315.51903
[103]	validation_0-mae:2310.32420
[104]	validation_0-mae:2306.73097
[105]	validation_0-mae:2303.16695
[106]	validation_0-mae:2296.57005
[107]	validation_0-mae:2295.25030
[108]	validation_0-mae:2290.61394
[109]	validation_0-mae:2288.43207
[110]	validation_0-mae:2284.46860
[111]	validation_0-mae:2280.14820
[112]	validation_0-mae:2276.03174
[113]	validation_0-mae:2268.82290
[114]	validation_0-mae:2264.24880
[115]	validation_0-mae:2264.21535
[116]	validation_0-mae:2258.89924
[117]	validation_0-mae:2253.97457
[118]	validation_0-mae:2250.85329
[119]	validation_0-mae:2248.79378
[120]	validation_0-mae:2245.60913
[121]	validation_0-mae:2245.99155
[122]	validation_0-mae:2240.04182
[123]	validation_0-mae:2237.36099
[124]	validation_0-mae:2233.33309
[125]	validation_0-mae:2230.06767
[126]	validation_0-mae:2228.80139
[127]	validation_0-mae:2227.45520
[128]	validation_0-mae:2226.26337
[129]	validation_0-mae:2225.87022
[130]	validation_0-mae:2225.71395
[131]	validation_0-mae:2224.51648
[132]	validation_0-mae:2222.43427
[133]	validation_0-mae:2221.54395
[134]	validation_0-mae:2218.61714
[135]	validation_0-mae:2216.53853
[136]	validation_0-mae:2214.68214
[137]	validation_0-mae:2213.20643
[138]	validation_0-mae:2212.15437
[139]	validation_0-mae:2209.03051
[140]	validation_0-mae:2206.51274
[141]	validation_0-mae:2205.54272
[142]	validation_0-mae:2201.96533
[143]	validation_0-mae:2201.51147
[144]	validation_0-mae:2197.63896
[145]	validation_0-mae:2195.90371
[146]	validation_0-mae:2194.84479
[147]	validation_0-mae:2191.63617
[148]	validation_0-mae:2191.45026
[149]	validation_0-mae:2189.41872
[150]	validation_0-mae:2188.16163
[151]	validation_0-mae:2187.63682
[152]	validation_0-mae:2184.53828
[153]	validation_0-mae:2183.30916
[154]	validation_0-mae:2182.66168
[155]	validation_0-mae:2183.52678
[156]	validation_0-mae:2182.67798
[157]	validation_0-mae:2183.65638
[158]	validation_0-mae:2181.87104
[159]	validation_0-mae:2180.23337
[160]	validation_0-mae:2180.03039
[161]	validation_0-mae:2178.52570
[162]	validation_0-mae:2178.78594
[163]	validation_0-mae:2178.66452
[164]	validation_0-mae:2177.71131
[165]	validation_0-mae:2176.21652
[166]	validation_0-mae:2176.71198
[167]	validation_0-mae:2177.07528
[168]	validation_0-mae:2176.14980
[169]	validation_0-mae:2177.38191
[170]	validation_0-mae:2175.53547
[171]	validation_0-mae:2176.69308
[172]	validation_0-mae:2176.01523
[173]	validation_0-mae:2175.44255
[174]	validation_0-mae:2173.49766
[175]	validation_0-mae:2173.15191
[176]	validation_0-mae:2172.37872
[177]	validation_0-mae:2170.91645
[178]	validation_0-mae:2170.57574
[179]	validation_0-mae:2169.20053
[180]	validation_0-mae:2168.66670
[181]	validation_0-mae:2165.85431
[182]	validation_0-mae:2165.03199
[183]	validation_0-mae:2162.38010
[184]	validation_0-mae:2162.87893
[185]	validation_0-mae:2163.03004
[186]	validation_0-mae:2162.89787
[187]	validation_0-mae:2162.15007
[188]	validation_0-mae:2161.43248
[189]	validation_0-mae:2159.09916
[190]	validation_0-mae:2155.95494
[191]	validation_0-mae:2157.48758
[192]	validation_0-mae:2157.68103
[193]	validation_0-mae:2156.73838
[194]	validation_0-mae:2156.15187
[195]	validation_0-mae:2155.66580
[196]	validation_0-mae:2153.29260
[197]	validation_0-mae:2150.32465
[198]	validation_0-mae:2148.43852
[199]	validation_0-mae:2149.25361
[200]	validation_0-mae:2148.70921
[201]	validation_0-mae:2148.63356
[202]	validation_0-mae:2147.73195
[203]	validation_0-mae:2147.46494
[204]	validation_0-mae:2147.87947
[205]	validation_0-mae:2148.52129
[206]	validation_0-mae:2148.03877
[207]	validation_0-mae:2146.83972
[208]	validation_0-mae:2145.71103
[209]	validation_0-mae:2144.42802
[210]	validation_0-mae:2145.64972
[211]	validation_0-mae:2144.41811
[212]	validation_0-mae:2141.54408
[213]	validation_0-mae:2140.16873
[214]	validation_0-mae:2139.69662
[215]	validation_0-mae:2139.40548
[216]	validation_0-mae:2139.86248
[217]	validation_0-mae:2139.25133
[218]	validation_0-mae:2137.29998
[219]	validation_0-mae:2137.88882
[220]	validation_0-mae:2135.65579
[221]	validation_0-mae:2134.83991
[222]	validation_0-mae:2133.40229
[223]	validation_0-mae:2131.94737
[224]	validation_0-mae:2131.34318
[225]	validation_0-mae:2130.66915
[226]	validation_0-mae:2130.52544
[227]	validation_0-mae:2129.04630
[228]	validation_0-mae:2129.21369
[229]	validation_0-mae:2129.25398
[230]	validation_0-mae:2129.11641
[231]	validation_0-mae:2129.40492
[232]	validation_0-mae:2128.72850
[233]	validation_0-mae:2128.34677
[234]	validation_0-mae:2129.19612
[235]	validation_0-mae:2129.94494
[236]	validation_0-mae:2130.53331
[237]	validation_0-mae:2129.67416
[238]	validation_0-mae:2128.03805
[239]	validation_0-mae:2128.21756
[240]	validation_0-mae:2127.05921
[241]	validation_0-mae:2126.38721
[242]	validation_0-mae:2126.00779
[243]	validation_0-mae:2123.75443
[244]	validation_0-mae:2122.32527
[245]	validation_0-mae:2121.19249
[246]	validation_0-mae:2119.90467
[247]	validation_0-mae:2120.00954
[248]	validation_0-mae:2119.91130
[249]	validation_0-mae:2119.54634
[250]	validation_0-mae:2118.30703
[251]	validation_0-mae:2118.24198
[252]	validation_0-mae:2116.57983
[253]	validation_0-mae:2116.00450
[254]	validation_0-mae:2116.19901
[255]	validation_0-mae:2115.46283
[256]	validation_0-mae:2115.90009
[257]	validation_0-mae:2114.71724
[258]	validation_0-mae:2114.54879
[259]	validation_0-mae:2113.08326
[260]	validation_0-mae:2111.26537
[261]	validation_0-mae:2109.56281
[262]	validation_0-mae:2109.81602
[263]	validation_0-mae:2108.93755
[264]	validation_0-mae:2108.23287
[265]	validation_0-mae:2107.47737
[266]	validation_0-mae:2105.33375
[267]	validation_0-mae:2104.90573
[268]	validation_0-mae:2104.39494
[269]	validation_0-mae:2104.68998
[270]	validation_0-mae:2104.83042
[271]	validation_0-mae:2104.76506
[272]	validation_0-mae:2104.52498
[273]	validation_0-mae:2103.40237
[274]	validation_0-mae:2103.58850
[275]	validation_0-mae:2103.70112
[276]	validation_0-mae:2103.73498
[277]	validation_0-mae:2104.31081
[278]	validation_0-mae:2105.03335
[279]	validation_0-mae:2104.46340
[280]	validation_0-mae:2104.33049
[281]	validation_0-mae:2104.80634
[282]	validation_0-mae:2104.86249
[283]	validation_0-mae:2104.84082
[284]	validation_0-mae:2104.02613
[285]	validation_0-mae:2103.58957
[286]	validation_0-mae:2103.55193
[287]	validation_0-mae:2103.01355
[288]	validation_0-mae:2103.30425
[289]	validation_0-mae:2102.99259
[290]	validation_0-mae:2103.00770
[291]	validation_0-mae:2103.11734
[292]	validation_0-mae:2103.04494
[293]	validation_0-mae:2103.34376
[294]	validation_0-mae:2103.48234
[295]	validation_0-mae:2104.16103
[296]	validation_0-mae:2102.90882
[297]	validation_0-mae:2102.86908
[298]	validation_0-mae:2102.56272
[299]	validation_0-mae:2102.39387
[300]	validation_0-mae:2102.09461
[301]	validation_0-mae:2102.34102
[302]	validation_0-mae:2102.72471
[303]	validation_0-mae:2102.25570
[304]	validation_0-mae:2102.78355
[305]	validation_0-mae:2103.39723
[306]	validation_0-mae:2102.40761
[307]	validation_0-mae:2102.62695
[308]	validation_0-mae:2102.70414
[309]	validation_0-mae:2102.74166
[310]	validation_0-mae:2102.54346
[311]	validation_0-mae:2102.34204
[312]	validation_0-mae:2101.94696
[313]	validation_0-mae:2101.71368
[314]	validation_0-mae:2101.32625
[315]	validation_0-mae:2101.60930
[316]	validation_0-mae:2101.05982
[317]	validation_0-mae:2100.37716
[318]	validation_0-mae:2100.13828
[319]	validation_0-mae:2100.12675
[320]	validation_0-mae:2098.29804
[321]	validation_0-mae:2098.74546
[322]	validation_0-mae:2098.66838
[323]	validation_0-mae:2098.82532
[324]	validation_0-mae:2098.75158
[325]	validation_0-mae:2098.54643
[326]	validation_0-mae:2097.02961
[327]	validation_0-mae:2096.30376
[328]	validation_0-mae:2096.00287
[329]	validation_0-mae:2096.21505
[330]	validation_0-mae:2096.14876
[331]	validation_0-mae:2095.43412
[332]	validation_0-mae:2095.46681
[333]	validation_0-mae:2094.81267
[334]	validation_0-mae:2094.17988
[335]	validation_0-mae:2094.30353
[336]	validation_0-mae:2093.41946
[337]	validation_0-mae:2094.13938
[338]	validation_0-mae:2094.54407
[339]	validation_0-mae:2094.34085
[340]	validation_0-mae:2094.38621
[341]	validation_0-mae:2094.23441
[342]	validation_0-mae:2093.71090
[343]	validation_0-mae:2094.43958
[344]	validation_0-mae:2094.00170
[345]	validation_0-mae:2093.68532
[346]	validation_0-mae:2092.53588
[347]	validation_0-mae:2092.36719
[348]	validation_0-mae:2092.23736
[349]	validation_0-mae:2092.69782
[350]	validation_0-mae:2092.87137
[351]	validation_0-mae:2092.56043
[352]	validation_0-mae:2092.52083
[353]	validation_0-mae:2092.58116
[354]	validation_0-mae:2092.17488
[355]	validation_0-mae:2091.95671
[356]	validation_0-mae:2091.91257
[357]	validation_0-mae:2091.85850
[358]	validation_0-mae:2092.00028
[359]	validation_0-mae:2091.95938
[360]	validation_0-mae:2091.74569
[361]	validation_0-mae:2091.68855
[362]	validation_0-mae:2091.74091
[363]	validation_0-mae:2091.05102
[364]	validation_0-mae:2091.02520
[365]	validation_0-mae:2091.08952
[366]	validation_0-mae:2091.13206
[367]	validation_0-mae:2091.80556
[368]	validation_0-mae:2092.47396
[369]	validation_0-mae:2091.88461
[370]	validation_0-mae:2092.03525
[371]	validation_0-mae:2090.14940
[372]	validation_0-mae:2090.12079
[373]	validation_0-mae:2090.26820
[374]	validation_0-mae:2090.33739
[375]	validation_0-mae:2090.72156
[376]	validation_0-mae:2091.02242
[377]	validation_0-mae:2090.53823
[378]	validation_0-mae:2089.37616
[379]	validation_0-mae:2088.92134
[380]	validation_0-mae:2088.95549
[381]	validation_0-mae:2088.73103
[382]	validation_0-mae:2088.75530
[383]	validation_0-mae:2089.10731
[384]	validation_0-mae:2089.17497
[385]	validation_0-mae:2089.13977
[386]	validation_0-mae:2089.57541
[387]	validation_0-mae:2088.50452
[388]	validation_0-mae:2088.59020
[389]	validation_0-mae:2088.93276
[390]	validation_0-mae:2088.80509
[391]	validation_0-mae:2088.72593
[392]	validation_0-mae:2088.38498
[393]	validation_0-mae:2088.65421
[394]	validation_0-mae:2088.92113
[395]	validation_0-mae:2088.48686
[396]	validation_0-mae:2088.08215
[397]	validation_0-mae:2087.45861
[398]	validation_0-mae:2087.46620
[399]	validation_0-mae:2087.44577
[400]	validation_0-mae:2087.89432
[401]	validation_0-mae:2087.94833
[402]	validation_0-mae:2087.68591
[403]	validation_0-mae:2087.89393
[404]	validation_0-mae:2088.01019
[405]	validation_0-mae:2088.24567
[406]	validation_0-mae:2088.19739
[407]	validation_0-mae:2087.98012
[408]	validation_0-mae:2088.29955
[409]	validation_0-mae:2088.44495
[410]	validation_0-mae:2088.77990
[411]	validation_0-mae:2089.06004
[412]	validation_0-mae:2088.99505
[413]	validation_0-mae:2088.85554
[414]	validation_0-mae:2088.37803
[415]	validation_0-mae:2087.83395
[416]	validation_0-mae:2088.06419
[417]	validation_0-mae:2088.43074
[418]	validation_0-mae:2088.49804
[419]	validation_0-mae:2088.40255
[420]	validation_0-mae:2088.19002
[421]	validation_0-mae:2087.93167
[422]	validation_0-mae:2087.91254
[423]	validation_0-mae:2087.54635
[424]	validation_0-mae:2086.79960
[425]	validation_0-mae:2085.69118
[426]	validation_0-mae:2085.82921
[427]	validation_0-mae:2085.55290
[428]	validation_0-mae:2085.37827
[429]	validation_0-mae:2084.44330
[430]	validation_0-mae:2084.67235
[431]	validation_0-mae:2084.84733
[432]	validation_0-mae:2084.61191
[433]	validation_0-mae:2084.96073
[434]	validation_0-mae:2085.00220
[435]	validation_0-mae:2084.48567
[436]	validation_0-mae:2084.91209
[437]	validation_0-mae:2084.83498
[438]	validation_0-mae:2085.27443
[439]	validation_0-mae:2085.51998
[440]	validation_0-mae:2085.70239
[441]	validation_0-mae:2085.61277
[442]	validation_0-mae:2085.30921
[443]	validation_0-mae:2084.88851
[444]	validation_0-mae:2084.91959
[445]	validation_0-mae:2084.58406
[446]	validation_0-mae:2084.30014
[447]	validation_0-mae:2083.39816
[448]	validation_0-mae:2083.59403
[449]	validation_0-mae:2083.73320
[450]	validation_0-mae:2083.65852
[451]	validation_0-mae:2083.92147
[452]	validation_0-mae:2084.26498
[453]	validation_0-mae:2083.74960
[454]	validation_0-mae:2083.71935
[455]	validation_0-mae:2084.03000
[456]	validation_0-mae:2083.97823
[457]	validation_0-mae:2084.01726
[458]	validation_0-mae:2084.20337
[459]	validation_0-mae:2084.16968
[460]	validation_0-mae:2084.33871
[461]	validation_0-mae:2084.35694
[462]	validation_0-mae:2084.20210
[463]	validation_0-mae:2084.18253
[464]	validation_0-mae:2083.99861
[465]	validation_0-mae:2084.00059
[466]	validation_0-mae:2083.08444
[467]	validation_0-mae:2082.56642
[468]	validation_0-mae:2082.26652
[469]	validation_0-mae:2082.24794
[470]	validation_0-mae:2082.12600
[471]	validation_0-mae:2081.97427
[472]	validation_0-mae:2081.70566
[473]	validation_0-mae:2081.56318
[474]	validation_0-mae:2081.68364
[475]	validation_0-mae:2082.02458
[476]	validation_0-mae:2082.29723
[477]	validation_0-mae:2082.90737
[478]	validation_0-mae:2082.98852
[479]	validation_0-mae:2082.95527
[480]	validation_0-mae:2082.96579
[481]	validation_0-mae:2083.42634
[482]	validation_0-mae:2083.86825
[483]	validation_0-mae:2083.99680
[484]	validation_0-mae:2084.12051
[485]	validation_0-mae:2084.34766
[486]	validation_0-mae:2083.94198
[487]	validation_0-mae:2084.17590
[488]	validation_0-mae:2084.22575
[489]	validation_0-mae:2083.90078
[490]	validation_0-mae:2084.27962
[491]	validation_0-mae:2084.20475
[492]	validation_0-mae:2084.45529
[493]	validation_0-mae:2084.58834
[494]	validation_0-mae:2084.54454
[495]	validation_0-mae:2084.89371
[496]	validation_0-mae:2085.22257
[497]	validation_0-mae:2084.80733
[498]	validation_0-mae:2084.42832
[499]	validation_0-mae:2083.97286
[500]	validation_0-mae:2084.04708
[501]	validation_0-mae:2084.03305
[502]	validation_0-mae:2084.19928
[503]	validation_0-mae:2084.17640
[504]	validation_0-mae:2084.06612
[505]	validation_0-mae:2084.17588
[506]	validation_0-mae:2084.15173
[507]	validation_0-mae:2084.20639
[508]	validation_0-mae:2083.97218
[509]	validation_0-mae:2084.04714
[510]	validation_0-mae:2083.92109
[511]	validation_0-mae:2083.97915
[512]	validation_0-mae:2083.98575
[513]	validation_0-mae:2084.06690
[514]	validation_0-mae:2084.58590
[515]	validation_0-mae:2084.58464
[516]	validation_0-mae:2083.65804
[517]	validation_0-mae:2083.56662
[518]	validation_0-mae:2083.57700
[519]	validation_0-mae:2083.58942
[520]	validation_0-mae:2083.72873
[521]	validation_0-mae:2083.11772
[522]	validation_0-mae:2082.70101
[523]	validation_0-mae:2082.57838
[524]	validation_0-mae:2082.64624
[525]	validation_0-mae:2082.55352
[526]	validation_0-mae:2082.69756
[527]	validation_0-mae:2082.62689
[528]	validation_0-mae:2081.85004
[529]	validation_0-mae:2081.81514
[530]	validation_0-mae:2081.61749
[531]	validation_0-mae:2081.34768
[532]	validation_0-mae:2081.40435
[533]	validation_0-mae:2081.49452
[534]	validation_0-mae:2081.18543
[535]	validation_0-mae:2081.08385
[536]	validation_0-mae:2080.97883
[537]	validation_0-mae:2081.12287
[538]	validation_0-mae:2081.01697
[539]	validation_0-mae:2080.58954
[540]	validation_0-mae:2080.57630
[541]	validation_0-mae:2079.86825
[542]	validation_0-mae:2080.01767
[543]	validation_0-mae:2079.74234
[544]	validation_0-mae:2079.60726
[545]	validation_0-mae:2079.70039
[546]	validation_0-mae:2079.88621
[547]	validation_0-mae:2079.95838
[548]	validation_0-mae:2080.03683
[549]	validation_0-mae:2080.06403
[550]	validation_0-mae:2079.43851
[551]	validation_0-mae:2079.48276
[552]	validation_0-mae:2079.50079
[553]	validation_0-mae:2079.55338
[554]	validation_0-mae:2079.75963
[555]	validation_0-mae:2079.78405
[556]	validation_0-mae:2079.48300
[557]	validation_0-mae:2079.23842
[558]	validation_0-mae:2078.94205
[559]	validation_0-mae:2078.86509
[560]	validation_0-mae:2078.94624
[561]	validation_0-mae:2078.76270
[562]	validation_0-mae:2078.78841
[563]	validation_0-mae:2078.40718
[564]	validation_0-mae:2078.54018
[565]	validation_0-mae:2078.63162
[566]	validation_0-mae:2078.81553
[567]	validation_0-mae:2078.51086
[568]	validation_0-mae:2078.49888
[569]	validation_0-mae:2078.46148
[570]	validation_0-mae:2078.35943
[571]	validation_0-mae:2078.16883
[572]	validation_0-mae:2078.35719
[573]	validation_0-mae:2078.25429
[574]	validation_0-mae:2078.54569
[575]	validation_0-mae:2078.32095
[576]	validation_0-mae:2078.17387
[577]	validation_0-mae:2078.26374
[578]	validation_0-mae:2078.32948
[579]	validation_0-mae:2078.45091
[580]	validation_0-mae:2078.38809
[581]	validation_0-mae:2077.78102
[582]	validation_0-mae:2077.46839
[583]	validation_0-mae:2077.23439
[584]	validation_0-mae:2077.24526
[585]	validation_0-mae:2077.16425
[586]	validation_0-mae:2076.66956
[587]	validation_0-mae:2076.57114
[588]	validation_0-mae:2076.60657
[589]	validation_0-mae:2076.28431
[590]	validation_0-mae:2076.60517
[591]	validation_0-mae:2076.55208

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[39]	validation_0-mae:3384.20937
[40]	validation_0-mae:3340.16509
[41]	validation_0-mae:3288.70504
[42]	validation_0-mae:3250.91226
[43]	validation_0-mae:3214.61538
[44]	validation_0-mae:3178.68305
[45]	validation_0-mae:3141.48184
[46]	validation_0-mae:3107.38083
[47]	validation_0-mae:3081.01423
[48]	validation_0-mae:3051.86180
[49]	validation_0-mae:3029.59982
[50]	validation_0-mae:2994.05257
[51]	validation_0-mae:2952.89665
[52]	validation_0-mae:2922.52687
[53]	validation_0-mae:2900.86770
[54]	validation_0-mae:2881.25586
[55]	validation_0-mae:2854.69751
[56]	validation_0-mae:2834.26213
[57]	validation_0-mae:2807.92582
[58]	validation_0-mae:2789.37066
[59]	validation_0-mae:2770.29352
[60]	validation_0-mae:2756.39640
[61]	validation_0-mae:2731.20027
[62]	validation_0-mae:2717.72726
[63]	validation_0-mae:2707.22819
[64]	validation_0-mae:2696.48497
[65]	validation_0-mae:2685.65081
[66]	validation_0-mae:2670.23134
[67]	validation_0-mae:2654.95547
[68]	validation_0-mae:2639.48391
[69]	validation_0-mae:2628.31940
[70]	validation_0-mae:2609.22462
[71]	validation_0-mae:2589.03768
[72]	validation_0-mae:2574.90498
[73]	validation_0-mae:2567.62390
[74]	validation_0-mae:2549.31540
[75]	validation_0-mae:2535.39428
[76]	validation_0-mae:2527.96433
[77]	validation_0-mae:2521.08667
[78]	validation_0-mae:2509.67311
[79]	validation_0-mae:2499.60996
[80]	validation_0-mae:2494.80905
[81]	validation_0-mae:2482.32285
[82]	validation_0-mae:2476.35610
[83]	validation_0-mae:2469.70195
[84]	validation_0-mae:2460.75541
[85]	validation_0-mae:2456.20656
[86]	validation_0-mae:2451.15322
[87]	validation_0-mae:2443.59159
[88]	validation_0-mae:2438.76541
[89]	validation_0-mae:2430.04621
[90]	validation_0-mae:2423.94385
[91]	validation_0-mae:2415.88916
[92]	validation_0-mae:2407.87319
[93]	validation_0-mae:2397.85264
[94]	validation_0-mae:2394.46517
[95]	validation_0-mae:2390.05523
[96]	validation_0-mae:2384.42727
[97]	validation_0-mae:2375.26983
[98]	validation_0-mae:2370.47724
[99]	validation_0-mae:2363.75546
[100]	validation_0-mae:2360.05734
[101]	validation_0-mae:2358.92152
[102]	validation_0-mae:2351.82127
[103]	validation_0-mae:2345.56649
[104]	validation_0-mae:2338.42729
[105]	validation_0-mae:2331.24537
[106]	validation_0-mae:2323.11180
[107]	validation_0-mae:2317.16016
[108]	validation_0-mae:2312.72354
[109]	validation_0-mae:2309.64060
[110]	validation_0-mae:2307.23376
[111]	validation_0-mae:2303.68894
[112]	validation_0-mae:2297.66648
[113]	validation_0-mae:2294.82016
[114]	validation_0-mae:2290.47454
[115]	validation_0-mae:2287.00883
[116]	validation_0-mae:2283.80470
[117]	validation_0-mae:2278.87451
[118]	validation_0-mae:2279.02714
[119]	validation_0-mae:2276.57824
[120]	validation_0-mae:2274.84985
[121]	validation_0-mae:2272.57183
[122]	validation_0-mae:2268.35741
[123]	validation_0-mae:2266.92192
[124]	validation_0-mae:2266.02214
[125]	validation_0-mae:2264.30789
[126]	validation_0-mae:2261.44080
[127]	validation_0-mae:2255.22190
[128]	validation_0-mae:2253.54548
[129]	validation_0-mae:2252.05639
[130]	validation_0-mae:2248.39417
[131]	validation_0-mae:2248.42147
[132]	validation_0-mae:2247.18554
[133]	validation_0-mae:2246.78159
[134]	validation_0-mae:2245.90674
[135]	validation_0-mae:2244.64315
[136]	validation_0-mae:2240.72492
[137]	validation_0-mae:2237.38924
[138]	validation_0-mae:2234.55495
[139]	validation_0-mae:2234.47020
[140]	validation_0-mae:2231.65845
[141]	validation_0-mae:2231.89426
[142]	validation_0-mae:2231.26389
[143]	validation_0-mae:2227.75238
[144]	validation_0-mae:2226.39637
[145]	validation_0-mae:2222.55273
[146]	validation_0-mae:2222.06046
[147]	validation_0-mae:2222.17228
[148]	validation_0-mae:2221.03472
[149]	validation_0-mae:2221.65936
[150]	validation_0-mae:2221.42561
[151]	validation_0-mae:2219.63165
[152]	validation_0-mae:2216.26709
[153]	validation_0-mae:2212.77424
[154]	validation_0-mae:2209.94747
[155]	validation_0-mae:2206.69136
[156]	validation_0-mae:2205.06597
[157]	validation_0-mae:2204.65624
[158]	validation_0-mae:2203.96876
[159]	validation_0-mae:2200.17191
[160]	validation_0-mae:2200.11680
[161]	validation_0-mae:2199.24540
[162]	validation_0-mae:2195.14497
[163]	validation_0-mae:2193.32469
[164]	validation_0-mae:2192.01008
[165]	validation_0-mae:2191.40690
[166]	validation_0-mae:2190.91814
[167]	validation_0-mae:2190.17716
[168]	validation_0-mae:2188.25723
[169]	validation_0-mae:2188.58326
[170]	validation_0-mae:2187.81127
[171]	validation_0-mae:2186.39078
[172]	validation_0-mae:2185.62270
[173]	validation_0-mae:2185.79429
[174]	validation_0-mae:2183.48328
[175]	validation_0-mae:2182.74334
[176]	validation_0-mae:2181.24327
[177]	validation_0-mae:2178.77173
[178]	validation_0-mae:2177.91213
[179]	validation_0-mae:2177.47819
[180]	validation_0-mae:2175.31164
[181]	validation_0-mae:2175.07137
[182]	validation_0-mae:2174.20162
[183]	validation_0-mae:2170.87947
[184]	validation_0-mae:2170.08873
[185]	validation_0-mae:2167.48494
[186]	validation_0-mae:2166.86242
[187]	validation_0-mae:2166.06636
[188]	validation_0-mae:2164.81891
[189]	validation_0-mae:2164.14284
[190]	validation_0-mae:2164.10031
[191]	validation_0-mae:2163.04707
[192]	validation_0-mae:2162.69534
[193]	validation_0-mae:2162.42443
[194]	validation_0-mae:2162.37046
[195]	validation_0-mae:2162.53051
[196]	validation_0-mae:2160.85974
[197]	validation_0-mae:2160.94838
[198]	validation_0-mae:2157.95966
[199]	validation_0-mae:2157.56843
[200]	validation_0-mae:2157.41412
[201]	validation_0-mae:2155.69750
[202]	validation_0-mae:2156.36221
[203]	validation_0-mae:2155.70546
[204]	validation_0-mae:2156.39638
[205]	validation_0-mae:2154.79433
[206]	validation_0-mae:2154.90045
[207]	validation_0-mae:2154.41669
[208]	validation_0-mae:2155.06122
[209]	validation_0-mae:2154.47815
[210]	validation_0-mae:2152.46153
[211]	validation_0-mae:2152.04728
[212]	validation_0-mae:2150.06957
[213]	validation_0-mae:2150.08597
[214]	validation_0-mae:2149.38308
[215]	validation_0-mae:2147.90718
[216]	validation_0-mae:2148.80110
[217]	validation_0-mae:2148.16150
[218]	validation_0-mae:2146.29946
[219]	validation_0-mae:2146.28680
[220]	validation_0-mae:2145.76406
[221]	validation_0-mae:2146.15303
[222]	validation_0-mae:2145.97177
[223]	validation_0-mae:2145.73446
[224]	validation_0-mae:2144.39984
[225]	validation_0-mae:2144.51280
[226]	validation_0-mae:2143.95992
[227]	validation_0-mae:2141.92011
[228]	validation_0-mae:2141.81260
[229]	validation_0-mae:2140.72227
[230]	validation_0-mae:2139.48225
[231]	validation_0-mae:2136.84904
[232]	validation_0-mae:2136.85073
[233]	validation_0-mae:2135.55655
[234]	validation_0-mae:2133.89650
[235]	validation_0-mae:2134.08529
[236]	validation_0-mae:2134.06995
[237]	validation_0-mae:2133.37809
[238]	validation_0-mae:2133.76270
[239]	validation_0-mae:2133.08351
[240]	validation_0-mae:2132.99381
[241]	validation_0-mae:2132.97498
[242]	validation_0-mae:2132.72984
[243]	validation_0-mae:2133.65506
[244]	validation_0-mae:2132.84459
[245]	validation_0-mae:2131.68279
[246]	validation_0-mae:2132.31939
[247]	validation_0-mae:2130.55223
[248]	validation_0-mae:2129.47949
[249]	validation_0-mae:2129.29234
[250]	validation_0-mae:2128.73927
[251]	validation_0-mae:2129.06209
[252]	validation_0-mae:2129.02595
[253]	validation_0-mae:2128.69946
[254]	validation_0-mae:2127.71300
[255]	validation_0-mae:2128.22822
[256]	validation_0-mae:2128.21326
[257]	validation_0-mae:2128.41412
[258]	validation_0-mae:2128.32873
[259]	validation_0-mae:2129.50600
[260]	validation_0-mae:2129.01970
[261]	validation_0-mae:2129.43162
[262]	validation_0-mae:2129.79447
[263]	validation_0-mae:2130.03852
[264]	validation_0-mae:2129.54215
[265]	validation_0-mae:2129.44148
[266]	validation_0-mae:2128.97730
[267]	validation_0-mae:2128.46591
[268]	validation_0-mae:2128.81295
[269]	validation_0-mae:2128.21927
[270]	validation_0-mae:2128.61752
[271]	validation_0-mae:2128.66619
[272]	validation_0-mae:2127.92355
[273]	validation_0-mae:2128.05762
[274]	validation_0-mae:2126.99564
[275]	validation_0-mae:2126.96465
[276]	validation_0-mae:2126.54164
[277]	validation_0-mae:2125.72520
[278]	validation_0-mae:2126.14837
[279]	validation_0-mae:2125.44712
[280]	validation_0-mae:2124.19754
[281]	validation_0-mae:2124.38713
[282]	validation_0-mae:2123.26856
[283]	validation_0-mae:2122.45409
[284]	validation_0-mae:2122.31576
[285]	validation_0-mae:2121.71633
[286]	validation_0-mae:2122.18169
[287]	validation_0-mae:2121.73332
[288]	validation_0-mae:2121.38383
[289]	validation_0-mae:2119.88388
[290]	validation_0-mae:2119.31866
[291]	validation_0-mae:2119.74715
[292]	validation_0-mae:2118.72247
[293]	validation_0-mae:2117.81780
[294]	validation_0-mae:2118.12270
[295]	validation_0-mae:2116.72539
[296]	validation_0-mae:2115.93723
[297]	validation_0-mae:2115.70934
[298]	validation_0-mae:2116.01459
[299]	validation_0-mae:2115.63754
[300]	validation_0-mae:2114.17633
[301]	validation_0-mae:2113.57717
[302]	validation_0-mae:2113.13907
[303]	validation_0-mae:2113.22698
[304]	validation_0-mae:2113.17422
[305]	validation_0-mae:2113.16181
[306]	validation_0-mae:2112.84944
[307]	validation_0-mae:2112.41556
[308]	validation_0-mae:2112.20323
[309]	validation_0-mae:2111.38669
[310]	validation_0-mae:2110.96904
[311]	validation_0-mae:2110.73734
[312]	validation_0-mae:2110.53453
[313]	validation_0-mae:2110.51351
[314]	validation_0-mae:2110.48465
[315]	validation_0-mae:2110.35430
[316]	validation_0-mae:2110.07846
[317]	validation_0-mae:2110.21586
[318]	validation_0-mae:2109.39398
[319]	validation_0-mae:2108.79218
[320]	validation_0-mae:2108.72087
[321]	validation_0-mae:2108.48905
[322]	validation_0-mae:2108.42644
[323]	validation_0-mae:2107.28681
[324]	validation_0-mae:2107.30375
[325]	validation_0-mae:2107.00343
[326]	validation_0-mae:2106.52309
[327]	validation_0-mae:2107.41237
[328]	validation_0-mae:2106.20356
[329]	validation_0-mae:2105.63584
[330]	validation_0-mae:2105.77738
[331]	validation_0-mae:2105.63428
[332]	validation_0-mae:2105.39876
[333]	validation_0-mae:2104.28874
[334]	validation_0-mae:2103.85440
[335]	validation_0-mae:2102.91156
[336]	validation_0-mae:2101.74340
[337]	validation_0-mae:2101.48026
[338]	validation_0-mae:2101.80626
[339]	validation_0-mae:2101.64493
[340]	validation_0-mae:2101.59825
[341]	validation_0-mae:2102.13659
[342]	validation_0-mae:2101.77829
[343]	validation_0-mae:2102.25388
[344]	validation_0-mae:2102.14131
[345]	validation_0-mae:2101.75307
[346]	validation_0-mae:2101.43314
[347]	validation_0-mae:2100.34063
[348]	validation_0-mae:2100.51556
[349]	validation_0-mae:2100.66843
[350]	validation_0-mae:2100.28837
[351]	validation_0-mae:2099.58904
[352]	validation_0-mae:2099.35865
[353]	validation_0-mae:2099.03130
[354]	validation_0-mae:2098.25879
[355]	validation_0-mae:2098.22789
[356]	validation_0-mae:2097.59088
[357]	validation_0-mae:2096.92009
[358]	validation_0-mae:2095.45255
[359]	validation_0-mae:2095.20767
[360]	validation_0-mae:2095.13696
[361]	validation_0-mae:2094.82256
[362]	validation_0-mae:2094.35991
[363]	validation_0-mae:2094.01849
[364]	validation_0-mae:2093.82196
[365]	validation_0-mae:2093.59738
[366]	validation_0-mae:2093.73014
[367]	validation_0-mae:2093.95679
[368]	validation_0-mae:2093.59979
[369]	validation_0-mae:2093.66597
[370]	validation_0-mae:2093.78592
[371]	validation_0-mae:2093.94461
[372]	validation_0-mae:2093.85220
[373]	validation_0-mae:2093.55462
[374]	validation_0-mae:2093.63446
[375]	validation_0-mae:2092.71934
[376]	validation_0-mae:2093.08447
[377]	validation_0-mae:2093.16575
[378]	validation_0-mae:2092.87045
[379]	validation_0-mae:2093.03629
[380]	validation_0-mae:2093.36576
[381]	validation_0-mae:2093.59176
[382]	validation_0-mae:2093.65336
[383]	validation_0-mae:2092.97920
[384]	validation_0-mae:2092.54433
[385]	validation_0-mae:2091.03264
[386]	validation_0-mae:2091.26095
[387]	validation_0-mae:2091.17837
[388]	validation_0-mae:2090.20362
[389]	validation_0-mae:2089.63189
[390]	validation_0-mae:2088.83720
[391]	validation_0-mae:2088.92472
[392]	validation_0-mae:2088.23371
[393]	validation_0-mae:2088.73758
[394]	validation_0-mae:2088.74267
[395]	validation_0-mae:2088.55584
[396]	validation_0-mae:2088.19926
[397]	validation_0-mae:2088.51021
[398]	validation_0-mae:2088.76098
[399]	validation_0-mae:2088.75111
[400]	validation_0-mae:2089.06660
[401]	validation_0-mae:2089.31581
[402]	validation_0-mae:2089.54111
[403]	validation_0-mae:2089.13429
[404]	validation_0-mae:2089.41313
[405]	validation_0-mae:2089.56236
[406]	validation_0-mae:2089.52394
[407]	validation_0-mae:2088.60426
[408]	validation_0-mae:2088.51040
[409]	validation_0-mae:2087.62083
[410]	validation_0-mae:2087.63168
[411]	validation_0-mae:2087.89099
[412]	validation_0-mae:2088.24743
[413]	validation_0-mae:2087.79665
[414]	validation_0-mae:2087.68046
[415]	validation_0-mae:2087.73233
[416]	validation_0-mae:2087.44362
[417]	validation_0-mae:2087.59517
[418]	validation_0-mae:2087.13427
[419]	validation_0-mae:2086.63617
[420]	validation_0-mae:2086.23523
[421]	validation_0-mae:2086.12538
[422]	validation_0-mae:2086.25201
[423]	validation_0-mae:2086.35289
[424]	validation_0-mae:2086.70443
[425]	validation_0-mae:2086.74952
[426]	validation_0-mae:2086.66386
[427]	validation_0-mae:2086.32975
[428]	validation_0-mae:2085.86918
[429]	validation_0-mae:2086.03279
[430]	validation_0-mae:2086.04078
[431]	validation_0-mae:2086.19982
[432]	validation_0-mae:2086.01394
[433]	validation_0-mae:2086.01661
[434]	validation_0-mae:2085.37240
[435]	validation_0-mae:2085.16394
[436]	validation_0-mae:2085.05495
[437]	validation_0-mae:2085.01098
[438]	validation_0-mae:2084.57706
[439]	validation_0-mae:2083.87683
[440]	validation_0-mae:2083.35920
[441]	validation_0-mae:2082.58444
[442]	validation_0-mae:2083.03275
[443]	validation_0-mae:2083.17876
[444]	validation_0-mae:2083.00271
[445]	validation_0-mae:2082.76843
[446]	validation_0-mae:2082.63246
[447]	validation_0-mae:2082.70258
[448]	validation_0-mae:2082.61351
[449]	validation_0-mae:2081.91119
[450]	validation_0-mae:2082.00386
[451]	validation_0-mae:2082.47272
[452]	validation_0-mae:2082.56641
[453]	validation_0-mae:2082.06147
[454]	validation_0-mae:2082.34045
[455]	validation_0-mae:2082.55993
[456]	validation_0-mae:2082.15897
[457]	validation_0-mae:2082.02109
[458]	validation_0-mae:2082.33476
[459]	validation_0-mae:2082.52418
[460]	validation_0-mae:2082.66619
[461]	validation_0-mae:2082.51236
[462]	validation_0-mae:2081.85478
[463]	validation_0-mae:2081.98332
[464]	validation_0-mae:2081.97873
[465]	validation_0-mae:2081.94153
[466]	validation_0-mae:2082.39827
[467]	validation_0-mae:2082.71007
[468]	validation_0-mae:2082.63281
[469]	validation_0-mae:2082.93887
[470]	validation_0-mae:2082.97936
[471]	validation_0-mae:2083.13411
[472]	validation_0-mae:2083.19440
[473]	validation_0-mae:2083.06095
[474]	validation_0-mae:2083.05798
[475]	validation_0-mae:2082.71430
[476]	validation_0-mae:2082.22957
[477]	validation_0-mae:2082.35895
[478]	validation_0-mae:2082.21497
[479]	validation_0-mae:2082.04783
[480]	validation_0-mae:2081.81805
[481]	validation_0-mae:2081.87074
[482]	validation_0-mae:2081.64347
[483]	validation_0-mae:2082.06619
[484]	validation_0-mae:2082.12882
[485]	validation_0-mae:2082.33690
[486]	validation_0-mae:2082.54033
[487]	validation_0-mae:2082.72074
[488]	validation_0-mae:2082.32499
[489]	validation_0-mae:2082.32787
[490]	validation_0-mae:2082.13279
[491]	validation_0-mae:2082.31835
[492]	validation_0-mae:2082.41416
[493]	validation_0-mae:2082.59389
[494]	validation_0-mae:2082.35192
[495]	validation_0-mae:2082.32113
[496]	validation_0-mae:2082.52257
[497]	validation_0-mae:2083.08398
[498]	validation_0-mae:2082.79046
[499]	validation_0-mae:2081.73813
[500]	validation_0-mae:2081.68195
[501]	validation_0-mae:2081.83787
[502]	validation_0-mae:2080.78605
[503]	validation_0-mae:2080.20220
[504]	validation_0-mae:2080.23888
[505]	validation_0-mae:2080.35329
[506]	validation_0-mae:2078.88497
[507]	validation_0-mae:2079.10531
[508]	validation_0-mae:2078.86180
[509]	validation_0-mae:2078.82892
[510]	validation_0-mae:2077.88275
[511]	validation_0-mae:2077.49503
[512]	validation_0-mae:2077.03558
[513]	validation_0-mae:2076.75228
[514]	validation_0-mae:2075.73526
[515]	validation_0-mae:2074.89193
[516]	validation_0-mae:2074.78450
[517]	validation_0-mae:2074.88525
[518]	validation_0-mae:2074.71522
[519]	validation_0-mae:2073.91749
[520]	validation_0-mae:2073.39959
[521]	validation_0-mae:2073.22118
[522]	validation_0-mae:2072.56232
[523]	validation_0-mae:2072.57802
[524]	validation_0-mae:2072.20938
[0]	validation_0-mae:12503.55836
[1]	validation_0-mae:11805.22170
[2]	validation_0-mae:11170.16334
[3]	validation_0-mae:10593.62015
[4]	validation_0-mae:10067.17102
[5]	validation_0-mae:9602.65235
[6]	validation_0-mae:9186.44514
[7]	validation_0-mae:8817.45342
[8]	validation_0-mae:8506.17645
[9]	validation_0-mae:8222.53657
[10]	validation_0-mae:7951.77729
[11]	validation_0-mae:7696.96029
[0]	validation_0-mae:12948.14161

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[1]	validation_0-mae:12609.44574
[2]	validation_0-mae:12299.95171
[3]	validation_0-mae:11992.08735
[4]	validation_0-mae:11705.56445
[5]	validation_0-mae:11423.95069
[6]	validation_0-mae:11153.15363
[7]	validation_0-mae:10900.60125
[8]	validation_0-mae:10650.00010
[9]	validation_0-mae:10401.13062
[0]	validation_0-mae:12456.44505
[1]	validation_0-mae:11723.16596
[2]	validation_0-mae:11052.94776
[3]	validation_0-mae:10429.87735
[4]	validation_0-mae:9877.83994
[5]	validation_0-mae:9375.97026
[6]	validation_0-mae:8918.71971
[7]	validation_0-mae:8510.25636
[8]	validation_0-mae:8136.62316
[9]	validation_0-mae:7792.22255
[10]	validation_0-mae:7479.34657
[11]	validation_0-mae:7180.06027
[12]	validation_0-mae:6892.19063
[13]	validation_0-mae:6632.42440
[14]	validation_0-mae:6383.59568
[15]	validation_0-mae:6150.94282
[16]	validation_0-mae:5938.18599
[17]	validation_0-mae:5741.89580
[18]	validation_0-mae:5558.48156
[19]	validation_0-mae:5378.89807
[20]	validation_0-mae:5200.91393
[21]	validation_0-mae:5034.91127
[22]	validation_0-mae:4901.91865
[23]	validation_0-mae:4760.77770
[24]	validation_0-mae:4628.66817
[25]	validation_0-mae:4511.15030
[26]	validation_0-mae:4414.30652
[27]	validation_0-mae:4310.12704
[28]	validation_0-mae:4213.95097
[29]	validation_0-mae:4125.85328
[30]	validation_0-mae:4018.65663
[31]	validation_0-mae:3932.11181
[32]	validation_0-mae:3842.81543
[33]	validation_0-mae:3765.32148
[34]	validation_0-mae:3688.61772
[35]	validation_0-mae:3626.80389
[36]	validation_0-mae:3568.96569
[37]	validation_0-mae:3494.98565

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[38]	validation_0-mae:3438.25466
[39]	validation_0-mae:3391.93346
[40]	validation_0-mae:3349.25822
[41]	validation_0-mae:3307.83846
[42]	validation_0-mae:3264.90412
[43]	validation_0-mae:3227.25072
[44]	validation_0-mae:3193.26809
[45]	validation_0-mae:3154.05056
[46]	validation_0-mae:3129.36591
[47]	validation_0-mae:3094.48291
[48]	validation_0-mae:3053.31062
[49]	validation_0-mae:3030.59809
[50]	validation_0-mae:3005.04063
[51]	validation_0-mae:2980.61773
[52]	validation_0-mae:2955.27507
[53]	validation_0-mae:2931.93113
[54]	validation_0-mae:2887.38420
[55]	validation_0-mae:2869.77871
[56]	validation_0-mae:2839.53968
[57]	validation_0-mae:2818.29862
[58]	validation_0-mae:2797.33465
[59]	validation_0-mae:2777.81899
[60]	validation_0-mae:2765.21696
[61]	validation_0-mae:2744.23800
[62]	validation_0-mae:2734.31137
[63]	validation_0-mae:2718.02062
[64]	validation_0-mae:2692.41316
[65]	validation_0-mae:2682.24303
[66]	validation_0-mae:2668.98599
[67]	validation_0-mae:2652.67683
[68]	validation_0-mae:2642.88256
[69]	validation_0-mae:2632.90166
[70]	validation_0-mae:2623.57089
[71]	validation_0-mae:2612.17098
[72]	validation_0-mae:2603.94320
[73]	validation_0-mae:2588.42315
[74]	validation_0-mae:2576.97825
[75]	validation_0-mae:2568.98880
[76]	validation_0-mae:2561.97424
[77]	validation_0-mae:2552.71371
[78]	validation_0-mae:2546.02902
[79]	validation_0-mae:2538.32993
[80]	validation_0-mae:2522.30976
[81]	validation_0-mae:2516.90691
[82]	validation_0-mae:2507.82100
[83]	validation_0-mae:2499.21245
[84]	validation_0-mae:2489.66306
[85]	validation_0-mae:2478.09313
[86]	validation_0-mae:2470.72778
[87]	validation_0-mae:2466.99523
[88]	validation_0-mae:2461.95044
[89]	validation_0-mae:2450.10399
[90]	validation_0-mae:2440.92875
[91]	validation_0-mae:2434.05928
[92]	validation_0-mae:2425.09121
[93]	validation_0-mae:2423.23803
[94]	validation_0-mae:2417.83568
[95]	validation_0-mae:2411.61394
[96]	validation_0-mae:2406.43047
[97]	validation_0-mae:2397.59322
[98]	validation_0-mae:2392.49552
[99]	validation_0-mae:2385.42115
[100]	validation_0-mae:2379.55461
[101]	validation_0-mae:2375.24163
[102]	validation_0-mae:2373.24121
[103]	validation_0-mae:2367.12113
[104]	validation_0-mae:2359.12339
[105]	validation_0-mae:2353.82969
[106]	validation_0-mae:2345.37097
[107]	validation_0-mae:2341.79886
[108]	validation_0-mae:2337.72485
[109]	validation_0-mae:2330.06173
[110]	validation_0-mae:2326.78377
[111]	validation_0-mae:2321.77460
[112]	validation_0-mae:2317.37977
[113]	validation_0-mae:2311.75340
[114]	validation_0-mae:2306.24583
[115]	validation_0-mae:2302.30429
[116]	validation_0-mae:2300.38044
[117]	validation_0-mae:2299.13530
[118]	validation_0-mae:2296.53814
[119]	validation_0-mae:2295.44392
[120]	validation_0-mae:2290.97410
[121]	validation_0-mae:2287.53122
[122]	validation_0-mae:2284.88738
[123]	validation_0-mae:2283.12115
[124]	validation_0-mae:2277.23507
[125]	validation_0-mae:2275.14052
[126]	validation_0-mae:2271.06537
[127]	validation_0-mae:2269.62394
[128]	validation_0-mae:2266.87220
[129]	validation_0-mae:2263.84543
[130]	validation_0-mae:2259.66763
[131]	validation_0-mae:2258.11932
[132]	validation_0-mae:2257.65018
[133]	validation_0-mae:2255.01717
[134]	validation_0-mae:2250.90616
[135]	validation_0-mae:2249.99756
[136]	validation_0-mae:2246.69535
[137]	validation_0-mae:2245.07546
[138]	validation_0-mae:2243.84062
[139]	validation_0-mae:2242.03092
[140]	validation_0-mae:2237.97166
[141]	validation_0-mae:2235.23348
[142]	validation_0-mae:2233.72172
[143]	validation_0-mae:2231.53216
[144]	validation_0-mae:2227.07578
[145]	validation_0-mae:2226.78737
[146]	validation_0-mae:2225.54133
[147]	validation_0-mae:2225.21448
[148]	validation_0-mae:2223.45571
[149]	validation_0-mae:2221.26660
[150]	validation_0-mae:2220.24543
[151]	validation_0-mae:2218.36303
[152]	validation_0-mae:2216.10653
[153]	validation_0-mae:2212.96308
[154]	validation_0-mae:2210.49560
[155]	validation_0-mae:2209.69150
[156]	validation_0-mae:2208.76832
[157]	validation_0-mae:2206.20240
[158]	validation_0-mae:2204.42407
[159]	validation_0-mae:2204.62444
[160]	validation_0-mae:2202.69362
[161]	validation_0-mae:2202.16886
[162]	validation_0-mae:2200.34257
[163]	validation_0-mae:2198.84159
[164]	validation_0-mae:2197.97231
[165]	validation_0-mae:2196.50973
[166]	validation_0-mae:2194.45166
[167]	validation_0-mae:2193.50221
[168]	validation_0-mae:2192.05333
[169]	validation_0-mae:2192.30497
[170]	validation_0-mae:2191.69739
[171]	validation_0-mae:2189.81836
[172]	validation_0-mae:2187.51565
[173]	validation_0-mae:2186.61784
[174]	validation_0-mae:2186.41622
[175]	validation_0-mae:2185.09885
[176]	validation_0-mae:2183.81960
[177]	validation_0-mae:2183.65818
[178]	validation_0-mae:2182.48100
[179]	validation_0-mae:2181.32294
[180]	validation_0-mae:2180.02113
[181]	validation_0-mae:2178.69156
[182]	validation_0-mae:2179.00138
[183]	validation_0-mae:2176.69644
[184]	validation_0-mae:2175.01175
[185]	validation_0-mae:2172.97247
[186]	validation_0-mae:2172.55508
[187]	validation_0-mae:2171.77505
[188]	validation_0-mae:2169.86711
[189]	validation_0-mae:2169.07128
[190]	validation_0-mae:2168.13161
[191]	validation_0-mae:2166.96122
[192]	validation_0-mae:2166.15948
[193]	validation_0-mae:2164.90995
[194]	validation_0-mae:2163.48004
[195]	validation_0-mae:2162.79105
[196]	validation_0-mae:2161.64524
[197]	validation_0-mae:2161.65261
[198]	validation_0-mae:2162.48502
[199]	validation_0-mae:2162.48739
[200]	validation_0-mae:2161.96425
[201]	validation_0-mae:2161.75815
[202]	validation_0-mae:2159.94714
[203]	validation_0-mae:2159.81605
[204]	validation_0-mae:2159.49300
[205]	validation_0-mae:2159.93206
[206]	validation_0-mae:2159.31222
[207]	validation_0-mae:2157.59103
[208]	validation_0-mae:2157.04939
[209]	validation_0-mae:2156.91218
[210]	validation_0-mae:2155.61677
[211]	validation_0-mae:2153.86844
[212]	validation_0-mae:2154.59572
[213]	validation_0-mae:2153.67656
[214]	validation_0-mae:2150.74474
[215]	validation_0-mae:2149.84695
[216]	validation_0-mae:2149.14547
[217]	validation_0-mae:2148.95440
[218]	validation_0-mae:2147.75116
[219]	validation_0-mae:2144.99909
[220]	validation_0-mae:2143.55040
[221]	validation_0-mae:2142.38735
[222]	validation_0-mae:2141.12254
[223]	validation_0-mae:2141.03155
[224]	validation_0-mae:2141.04996
[225]	validation_0-mae:2141.21955
[226]	validation_0-mae:2141.06902
[227]	validation_0-mae:2141.08760
[228]	validation_0-mae:2140.97102
[229]	validation_0-mae:2141.53503
[230]	validation_0-mae:2141.15737
[231]	validation_0-mae:2141.48826
[232]	validation_0-mae:2141.35866
[233]	validation_0-mae:2141.58525
[234]	validation_0-mae:2140.99409
[235]	validation_0-mae:2140.81598
[236]	validation_0-mae:2138.44299
[237]	validation_0-mae:2137.45839
[238]	validation_0-mae:2135.02277
[239]	validation_0-mae:2134.50257
[240]	validation_0-mae:2134.18531
[241]	validation_0-mae:2132.39190
[242]	validation_0-mae:2132.26666
[243]	validation_0-mae:2132.62096
[244]	validation_0-mae:2132.69618
[245]	validation_0-mae:2132.43691
[246]	validation_0-mae:2132.49489
[247]	validation_0-mae:2129.12748
[248]	validation_0-mae:2129.59394
[249]	validation_0-mae:2128.78661
[250]	validation_0-mae:2128.40004
[251]	validation_0-mae:2128.78815
[252]	validation_0-mae:2129.56616
[253]	validation_0-mae:2129.33418
[254]	validation_0-mae:2129.22409
[255]	validation_0-mae:2129.20659
[256]	validation_0-mae:2128.93371
[257]	validation_0-mae:2128.26702
[258]	validation_0-mae:2127.62392
[259]	validation_0-mae:2127.48914
[260]	validation_0-mae:2127.43478
[261]	validation_0-mae:2127.03043
[262]	validation_0-mae:2126.81815
[263]	validation_0-mae:2125.96642
[264]	validation_0-mae:2125.70494
[265]	validation_0-mae:2125.30795
[266]	validation_0-mae:2125.78436
[267]	validation_0-mae:2126.04160
[268]	validation_0-mae:2125.27556
[269]	validation_0-mae:2125.15104
[270]	validation_0-mae:2124.53592
[271]	validation_0-mae:2122.76636
[272]	validation_0-mae:2122.52700
[273]	validation_0-mae:2122.70591
[274]	validation_0-mae:2121.56520
[275]	validation_0-mae:2121.63338
[276]	validation_0-mae:2121.79024
[277]	validation_0-mae:2121.42058
[278]	validation_0-mae:2121.88774
[279]	validation_0-mae:2121.26915
[280]	validation_0-mae:2121.14126
[281]	validation_0-mae:2119.63460
[282]	validation_0-mae:2119.43666
[283]	validation_0-mae:2118.46746
[284]	validation_0-mae:2118.40188
[285]	validation_0-mae:2119.06872
[286]	validation_0-mae:2119.02143
[287]	validation_0-mae:2118.80475
[288]	validation_0-mae:2118.75009
[289]	validation_0-mae:2118.28403
[290]	validation_0-mae:2118.51506
[291]	validation_0-mae:2118.15722
[292]	validation_0-mae:2117.25343
[293]	validation_0-mae:2117.32593
[294]	validation_0-mae:2117.15905
[295]	validation_0-mae:2116.50011
[296]	validation_0-mae:2116.39197
[297]	validation_0-mae:2115.98207
[298]	validation_0-mae:2115.62475
[299]	validation_0-mae:2115.73679
[300]	validation_0-mae:2115.29995
[301]	validation_0-mae:2115.40660
[302]	validation_0-mae:2115.33076
[303]	validation_0-mae:2115.35834
[304]	validation_0-mae:2115.18805
[305]	validation_0-mae:2114.85994
[306]	validation_0-mae:2114.59391
[307]	validation_0-mae:2114.19458
[308]	validation_0-mae:2114.44748
[309]	validation_0-mae:2113.89638
[310]	validation_0-mae:2113.84537
[311]	validation_0-mae:2114.28632
[312]	validation_0-mae:2114.28927
[313]	validation_0-mae:2114.70878
[314]	validation_0-mae:2115.14430
[315]	validation_0-mae:2114.31314
[316]	validation_0-mae:2114.97598
[317]	validation_0-mae:2114.46197
[318]	validation_0-mae:2114.52414
[319]	validation_0-mae:2114.36434
[320]	validation_0-mae:2114.71327
[321]	validation_0-mae:2114.96324
[322]	validation_0-mae:2115.36668
[323]	validation_0-mae:2115.22114
[324]	validation_0-mae:2114.42215
[325]	validation_0-mae:2113.82439
[326]	validation_0-mae:2112.14478
[327]	validation_0-mae:2111.41434
[328]	validation_0-mae:2111.40013
[329]	validation_0-mae:2111.36400
[330]	validation_0-mae:2110.52276
[331]	validation_0-mae:2110.08863
[332]	validation_0-mae:2109.87822
[333]	validation_0-mae:2109.17718
[334]	validation_0-mae:2109.32773
[335]	validation_0-mae:2109.74361
[336]	validation_0-mae:2109.88834
[337]	validation_0-mae:2110.34412
[338]	validation_0-mae:2110.70803
[339]	validation_0-mae:2110.06923
[340]	validation_0-mae:2109.65275
[341]	validation_0-mae:2109.31047
[342]	validation_0-mae:2109.61382
[343]	validation_0-mae:2109.85418
[344]	validation_0-mae:2109.69898
[345]	validation_0-mae:2109.83423
[346]	validation_0-mae:2110.03976
[347]	validation_0-mae:2110.37900
[348]	validation_0-mae:2110.42679
[349]	validation_0-mae:2110.56125
[350]	validation_0-mae:2110.40454
[351]	validation_0-mae:2110.34639
[352]	validation_0-mae:2109.75128
[353]	validation_0-mae:2108.61874
[354]	validation_0-mae:2108.12873
[355]	validation_0-mae:2108.12282
[356]	validation_0-mae:2108.09665
[357]	validation_0-mae:2108.07099
[358]	validation_0-mae:2107.99786
[359]	validation_0-mae:2107.49342
[360]	validation_0-mae:2106.90134
[361]	validation_0-mae:2106.70735
[362]	validation_0-mae:2106.35769
[363]	validation_0-mae:2106.30819
[364]	validation_0-mae:2106.14752
[365]	validation_0-mae:2106.29610
[0]	validation_0-mae:12598.22813
[1]	validation_0-mae:11979.95548
[2]	validation_0-mae:11461.42432
[3]	validation_0-mae:11000.04792
[4]	validation_0-mae:10616.26840
[5]	validation_0-mae:10275.88951
[6]	validation_0-mae:9983.19341
[7]	validation_0-mae:9712.51717
[8]	validation_0-mae:9485.02379
[9]	validation_0-mae:9292.00025
[10]	validation_0-mae:9127.88051

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[0]	validation_0-mae:12378.24496
[1]	validation_0-mae:11593.07625
[2]	validation_0-mae:10875.96653
[3]	validation_0-mae:10248.53104
[4]	validation_0-mae:9684.74120
[5]	validation_0-mae:9190.99377
[6]	validation_0-mae:8778.48904
[7]	validation_0-mae:8423.53717
[8]	validation_0-mae:8110.93410
[9]	validation_0-mae:7815.91833
[10]	validation_0-mae:7534.09525
[11]	validation_0-mae:7295.74088
[12]	validation_0-mae:7095.51091
[13]	validation_0-mae:6917.77023
[14]	validation_0-mae:6752.31356
[15]	validation_0-mae:6606.73602
[16]	validation_0-mae:6490.77996
[0]	validation_0-mae:12425.81907
[1]	validation_0-mae:11669.75477
[2]	validation_0-mae:10992.98553
[3]	validation_0-mae:10350.44527
[4]	validation_0-mae:9791.64947
[5]	validation_0-mae:9295.27692
[6]	validation_0-mae:8832.22111
[7]	validation_0-mae:8419.68906
[8]	validation_0-mae:8041.79441
[9]	validation_0-mae:7699.13166
[10]	validation_0-mae:7375.35825
[11]	validation_0-mae:7071.15174
[12]	validation_0-mae:6796.30897
[13]	validation_0-mae:6536.98224
[14]	validation_0-mae:6263.77474
[15]	validation_0-mae:6040.79316
[16]	validation_0-mae:5823.13586
[17]	validation_0-mae:5640.36771
[18]	validation_0-mae:5467.30096
[19]	validation_0-mae:5262.33896
[20]	validation_0-mae:5109.86203
[21]	validation_0-mae:4938.22203
[22]	validation_0-mae:4798.11898
[23]	validation_0-mae:4656.55372
[24]	validation_0-mae:4544.22494
[25]	validation_0-mae:4415.07002
[26]	validation_0-mae:4315.15303
[27]	validation_0-mae:4210.83181
[28]	validation_0-mae:4111.04581
[29]	validation_0-mae:4010.88195
[30]	validation_0-mae:3908.14140
[31]	validation_0-mae:3834.80512
[32]	validation_0-mae:3750.91638
[33]	validation_0-mae:3682.74794
[34]	validation_0-mae:3610.51971
[35]	validation_0-mae:3550.00119
[36]	validation_0-mae:3484.18885
[37]	validation_0-mae:3428.78933
[38]	validation_0-mae:3375.72066

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[39]	validation_0-mae:3328.54950
[40]	validation_0-mae:3279.48435
[41]	validation_0-mae:3241.55669
[42]	validation_0-mae:3204.01428
[43]	validation_0-mae:3160.92168
[44]	validation_0-mae:3120.94329
[45]	validation_0-mae:3092.27959
[46]	validation_0-mae:3048.48674
[47]	validation_0-mae:3019.86496
[48]	validation_0-mae:2988.17169
[49]	validation_0-mae:2968.63538
[50]	validation_0-mae:2938.18449
[51]	validation_0-mae:2914.59440
[52]	validation_0-mae:2892.07691
[53]	validation_0-mae:2874.58866
[54]	validation_0-mae:2858.27115
[55]	validation_0-mae:2842.66266
[56]	validation_0-mae:2823.45859
[57]	validation_0-mae:2797.72379
[58]	validation_0-mae:2780.36332
[59]	validation_0-mae:2764.35528
[60]	validation_0-mae:2740.78970
[61]	validation_0-mae:2727.37549
[62]	validation_0-mae:2715.03659
[63]	validation_0-mae:2698.83076
[64]	validation_0-mae:2684.12409
[65]	validation_0-mae:2665.59673
[66]	validation_0-mae:2659.38077
[67]	validation_0-mae:2648.49867
[68]	validation_0-mae:2632.11868
[69]	validation_0-mae:2619.79109
[70]	validation_0-mae:2610.58427
[71]	validation_0-mae:2602.52386
[72]	validation_0-mae:2587.65851
[73]	validation_0-mae:2577.20687
[74]	validation_0-mae:2569.06801
[75]	validation_0-mae:2562.18794
[76]	validation_0-mae:2547.37982
[77]	validation_0-mae:2537.77049
[78]	validation_0-mae:2529.98883
[79]	validation_0-mae:2522.31023
[80]	validation_0-mae:2514.93192
[81]	validation_0-mae:2511.11325
[82]	validation_0-mae:2502.21657
[83]	validation_0-mae:2494.34247
[84]	validation_0-mae:2480.01765
[85]	validation_0-mae:2472.50818
[86]	validation_0-mae:2467.45044
[87]	validation_0-mae:2460.17585
[88]	validation_0-mae:2451.82577
[89]	validation_0-mae:2447.16682
[90]	validation_0-mae:2440.94107
[91]	validation_0-mae:2432.16178
[92]	validation_0-mae:2426.96821
[93]	validation_0-mae:2423.51368
[94]	validation_0-mae:2418.11587
[95]	validation_0-mae:2409.69009
[96]	validation_0-mae:2403.74910
[97]	validation_0-mae:2399.92893
[98]	validation_0-mae:2397.18507
[99]	validation_0-mae:2388.14538
[100]	validation_0-mae:2381.64512
[101]	validation_0-mae:2374.95991
[102]	validation_0-mae:2372.13354
[103]	validation_0-mae:2369.07073
[104]	validation_0-mae:2364.20918
[105]	validation_0-mae:2360.31646
[106]	validation_0-mae:2353.98706
[107]	validation_0-mae:2348.39996
[108]	validation_0-mae:2345.07391
[109]	validation_0-mae:2341.61744
[110]	validation_0-mae:2341.17718
[111]	validation_0-mae:2338.42419
[112]	validation_0-mae:2337.21787
[113]	validation_0-mae:2332.98127
[114]	validation_0-mae:2333.10011
[115]	validation_0-mae:2328.08927
[116]	validation_0-mae:2325.95176
[117]	validation_0-mae:2321.16655
[118]	validation_0-mae:2317.19126
[119]	validation_0-mae:2314.54419
[120]	validation_0-mae:2311.74953
[121]	validation_0-mae:2305.76553
[122]	validation_0-mae:2303.50225
[123]	validation_0-mae:2301.76247
[124]	validation_0-mae:2298.96941
[125]	validation_0-mae:2293.43768
[126]	validation_0-mae:2287.31563
[127]	validation_0-mae:2282.75106
[128]	validation_0-mae:2281.56516
[129]	validation_0-mae:2280.69171
[130]	validation_0-mae:2277.96131
[131]	validation_0-mae:2276.39322
[132]	validation_0-mae:2274.41999
[133]	validation_0-mae:2271.69253
[134]	validation_0-mae:2270.49835
[135]	validation_0-mae:2267.15280
[136]	validation_0-mae:2265.85970
[137]	validation_0-mae:2263.63775
[138]	validation_0-mae:2261.50380
[139]	validation_0-mae:2261.17560
[140]	validation_0-mae:2259.88529
[141]	validation_0-mae:2260.21596
[142]	validation_0-mae:2256.33840
[143]	validation_0-mae:2255.71097
[144]	validation_0-mae:2253.55788
[145]	validation_0-mae:2251.48658
[146]	validation_0-mae:2250.70285
[147]	validation_0-mae:2249.37656
[148]	validation_0-mae:2247.99766
[149]	validation_0-mae:2247.67715
[150]	validation_0-mae:2247.78160
[151]	validation_0-mae:2248.34064
[152]	validation_0-mae:2248.06034
[153]	validation_0-mae:2246.97579
[154]	validation_0-mae:2244.34638
[155]	validation_0-mae:2242.96914
[156]	validation_0-mae:2240.30209
[157]	validation_0-mae:2238.52692
[158]	validation_0-mae:2238.36170
[159]	validation_0-mae:2234.31374
[160]	validation_0-mae:2230.31842
[161]	validation_0-mae:2227.99504
[162]	validation_0-mae:2223.36037
[163]	validation_0-mae:2221.76916
[164]	validation_0-mae:2220.66460
[165]	validation_0-mae:2219.56262
[166]	validation_0-mae:2219.46965
[167]	validation_0-mae:2216.64835
[168]	validation_0-mae:2215.61307
[169]	validation_0-mae:2212.58762
[170]	validation_0-mae:2211.37844
[171]	validation_0-mae:2210.66336
[172]	validation_0-mae:2210.24184
[173]	validation_0-mae:2207.66032
[174]	validation_0-mae:2206.59712
[175]	validation_0-mae:2206.37816
[176]	validation_0-mae:2204.57058
[177]	validation_0-mae:2203.32997
[178]	validation_0-mae:2201.69642
[179]	validation_0-mae:2201.99882
[180]	validation_0-mae:2200.63734
[181]	validation_0-mae:2201.41148
[182]	validation_0-mae:2200.24888
[183]	validation_0-mae:2199.57435
[184]	validation_0-mae:2199.00846
[185]	validation_0-mae:2198.65493
[186]	validation_0-mae:2198.59878
[187]	validation_0-mae:2198.44723
[188]	validation_0-mae:2198.37228
[189]	validation_0-mae:2197.32482
[190]	validation_0-mae:2196.86203
[191]	validation_0-mae:2196.31471
[192]	validation_0-mae:2197.04942
[193]	validation_0-mae:2196.19588
[194]	validation_0-mae:2195.82755
[195]	validation_0-mae:2193.75606
[196]	validation_0-mae:2191.40756
[197]	validation_0-mae:2189.93758
[198]	validation_0-mae:2190.13826
[199]	validation_0-mae:2191.09226
[200]	validation_0-mae:2189.52218
[201]	validation_0-mae:2188.62846
[202]	validation_0-mae:2187.75690
[203]	validation_0-mae:2187.10846
[204]	validation_0-mae:2187.18664
[205]	validation_0-mae:2187.13357
[206]	validation_0-mae:2187.41815
[207]	validation_0-mae:2187.94155
[208]	validation_0-mae:2188.88015
[209]	validation_0-mae:2187.75889
[210]	validation_0-mae:2186.94603
[211]	validation_0-mae:2187.04872
[212]	validation_0-mae:2186.77953
[213]	validation_0-mae:2186.70012
[214]	validation_0-mae:2186.97255
[215]	validation_0-mae:2186.83996
[216]	validation_0-mae:2186.10497
[217]	validation_0-mae:2184.77737
[218]	validation_0-mae:2185.07618
[219]	validation_0-mae:2186.10328
[220]	validation_0-mae:2185.51552
[221]	validation_0-mae:2184.98278
[222]	validation_0-mae:2185.17745
[223]	validation_0-mae:2184.91058
[224]	validation_0-mae:2185.07790
[225]	validation_0-mae:2183.24917
[226]	validation_0-mae:2183.63572
[227]	validation_0-mae:2181.36413
[228]	validation_0-mae:2182.08232
[229]	validation_0-mae:2180.95869
[230]	validation_0-mae:2180.85483
[231]	validation_0-mae:2179.79616
[232]	validation_0-mae:2179.66846
[233]	validation_0-mae:2178.03573
[234]	validation_0-mae:2178.42282
[235]	validation_0-mae:2177.98840
[236]	validation_0-mae:2176.75096
[237]	validation_0-mae:2176.28820
[238]	validation_0-mae:2176.03308
[239]	validation_0-mae:2176.18006
[240]	validation_0-mae:2176.30226
[241]	validation_0-mae:2177.01941
[242]	validation_0-mae:2176.94712
[243]	validation_0-mae:2174.49209
[244]	validation_0-mae:2174.62114
[245]	validation_0-mae:2173.99696
[246]	validation_0-mae:2173.87587
[247]	validation_0-mae:2172.45677
[248]	validation_0-mae:2172.80620
[249]	validation_0-mae:2172.84051
[250]	validation_0-mae:2171.82473
[251]	validation_0-mae:2170.55323
[252]	validation_0-mae:2169.25689
[253]	validation_0-mae:2169.13857
[254]	validation_0-mae:2168.96281
[255]	validation_0-mae:2169.07933
[256]	validation_0-mae:2168.23485
[257]	validation_0-mae:2169.13956
[258]	validation_0-mae:2168.58883
[259]	validation_0-mae:2168.50440
[260]	validation_0-mae:2169.05403
[261]	validation_0-mae:2169.06994
[262]	validation_0-mae:2169.01665
[263]	validation_0-mae:2168.24915
[264]	validation_0-mae:2169.29177
[265]	validation_0-mae:2168.06892
[266]	validation_0-mae:2167.87787
[267]	validation_0-mae:2167.70468
[268]	validation_0-mae:2167.57001
[269]	validation_0-mae:2166.28430
[270]	validation_0-mae:2164.62655
[271]	validation_0-mae:2164.89541
[272]	validation_0-mae:2164.20840
[273]	validation_0-mae:2164.30110
[274]	validation_0-mae:2164.00432
[275]	validation_0-mae:2164.46888
[276]	validation_0-mae:2164.45074
[277]	validation_0-mae:2163.62321
[278]	validation_0-mae:2163.76382
[279]	validation_0-mae:2163.87370
[280]	validation_0-mae:2163.14459
[281]	validation_0-mae:2162.50423
[282]	validation_0-mae:2162.18399
[283]	validation_0-mae:2162.44113
[284]	validation_0-mae:2161.56272
[285]	validation_0-mae:2161.85401
[286]	validation_0-mae:2162.62236
[287]	validation_0-mae:2162.42973
[288]	validation_0-mae:2162.49891
[289]	validation_0-mae:2162.58045
[290]	validation_0-mae:2162.49585
[291]	validation_0-mae:2162.29895
[292]	validation_0-mae:2161.80991
[293]	validation_0-mae:2162.42957
[294]	validation_0-mae:2162.35020
[295]	validation_0-mae:2162.88569
[296]	validation_0-mae:2162.60722
[297]	validation_0-mae:2161.39633
[298]	validation_0-mae:2160.17359
[299]	validation_0-mae:2160.49264
[300]	validation_0-mae:2160.60968
[301]	validation_0-mae:2160.37997
[302]	validation_0-mae:2159.78932
[303]	validation_0-mae:2159.32486
[304]	validation_0-mae:2158.99192
[305]	validation_0-mae:2159.18352
[306]	validation_0-mae:2159.04090
[307]	validation_0-mae:2158.97431
[308]	validation_0-mae:2158.27788
[309]	validation_0-mae:2158.20128
[310]	validation_0-mae:2157.99658
[311]	validation_0-mae:2156.79329
[312]	validation_0-mae:2156.91517
[313]	validation_0-mae:2156.28524
[314]	validation_0-mae:2155.95084
[315]	validation_0-mae:2155.06286
[316]	validation_0-mae:2153.74668
[317]	validation_0-mae:2153.56415
[318]	validation_0-mae:2152.14354
[319]	validation_0-mae:2150.91078
[320]	validation_0-mae:2150.74363
[321]	validation_0-mae:2148.91976
[322]	validation_0-mae:2148.80073
[323]	validation_0-mae:2146.46700
[324]	validation_0-mae:2146.24034
[325]	validation_0-mae:2144.71686
[326]	validation_0-mae:2143.80409
[327]	validation_0-mae:2143.55938
[328]	validation_0-mae:2143.46659
[329]	validation_0-mae:2144.43424
[330]	validation_0-mae:2143.94282
[331]	validation_0-mae:2143.11366
[332]	validation_0-mae:2141.91384
[333]	validation_0-mae:2142.16613
[334]	validation_0-mae:2142.61717
[335]	validation_0-mae:2142.45749
[336]	validation_0-mae:2141.80389
[337]	validation_0-mae:2141.31583
[338]	validation_0-mae:2141.26409
[339]	validation_0-mae:2141.29286
[340]	validation_0-mae:2141.19041
[341]	validation_0-mae:2141.50064
[342]	validation_0-mae:2140.84673
[343]	validation_0-mae:2140.70046
[344]	validation_0-mae:2139.55204
[345]	validation_0-mae:2139.20776
[346]	validation_0-mae:2138.47259
[347]	validation_0-mae:2138.76773
[348]	validation_0-mae:2137.40552
[349]	validation_0-mae:2137.33105
[350]	validation_0-mae:2136.82407
[351]	validation_0-mae:2136.75197
[352]	validation_0-mae:2136.85313
[353]	validation_0-mae:2136.19450
[354]	validation_0-mae:2135.56960
[355]	validation_0-mae:2135.69149
[356]	validation_0-mae:2135.30362
[357]	validation_0-mae:2135.57439
[358]	validation_0-mae:2134.28325
[359]	validation_0-mae:2134.35847
[360]	validation_0-mae:2133.69165
[361]	validation_0-mae:2134.11014
[362]	validation_0-mae:2133.85853
[363]	validation_0-mae:2134.21405
[364]	validation_0-mae:2135.15437
[365]	validation_0-mae:2134.97352
[366]	validation_0-mae:2134.75587
[367]	validation_0-mae:2134.64056
[368]	validation_0-mae:2134.16780
[369]	validation_0-mae:2134.74581
[370]	validation_0-mae:2134.90059
[371]	validation_0-mae:2135.14679
[372]	validation_0-mae:2134.60847
[373]	validation_0-mae:2135.41015
[374]	validation_0-mae:2134.91083
[375]	validation_0-mae:2134.66771
[376]	validation_0-mae:2133.98793
[377]	validation_0-mae:2134.25444
[378]	validation_0-mae:2133.72021
[379]	validation_0-mae:2133.61399
[380]	validation_0-mae:2133.91141
[381]	validation_0-mae:2134.12050
[382]	validation_0-mae:2133.08560
[383]	validation_0-mae:2132.74512
[384]	validation_0-mae:2133.11995
[385]	validation_0-mae:2133.46556
[386]	validation_0-mae:2133.74327
[387]	validation_0-mae:2134.30152
[388]	validation_0-mae:2134.17392
[389]	validation_0-mae:2134.35740
[390]	validation_0-mae:2134.33749
[391]	validation_0-mae:2134.40762
[392]	validation_0-mae:2134.72261
[393]	validation_0-mae:2134.73407
[394]	validation_0-mae:2134.77872
[395]	validation_0-mae:2134.48193
[396]	validation_0-mae:2133.98418
[397]	validation_0-mae:2133.78682
[398]	validation_0-mae:2133.66529
[399]	validation_0-mae:2132.65921
[400]	validation_0-mae:2131.88192
[401]	validation_0-mae:2132.60203
[402]	validation_0-mae:2132.23198
[403]	validation_0-mae:2131.86312
[404]	validation_0-mae:2130.73002
[405]	validation_0-mae:2130.30213
[406]	validation_0-mae:2129.48812
[407]	validation_0-mae:2129.51246
[408]	validation_0-mae:2129.24241
[409]	validation_0-mae:2129.44698
[410]	validation_0-mae:2129.59667
[411]	validation_0-mae:2129.66663
[412]	validation_0-mae:2129.15496
[413]	validation_0-mae:2129.33534
[414]	validation_0-mae:2129.92004
[415]	validation_0-mae:2130.19962
[416]	validation_0-mae:2129.98382
[417]	validation_0-mae:2130.24880
[418]	validation_0-mae:2130.17362
[419]	validation_0-mae:2129.85685
[420]	validation_0-mae:2129.60621
[421]	validation_0-mae:2128.82870
[422]	validation_0-mae:2128.95234
[423]	validation_0-mae:2128.57080
[424]	validation_0-mae:2128.96880
[425]	validation_0-mae:2128.85594
[426]	validation_0-mae:2129.19565
[427]	validation_0-mae:2129.22945
[428]	validation_0-mae:2129.45103
[429]	validation_0-mae:2129.37436
[430]	validation_0-mae:2129.21407
[431]	validation_0-mae:2129.67093
[432]	validation_0-mae:2129.46933
[433]	validation_0-mae:2128.47947
[434]	validation_0-mae:2128.80826
[435]	validation_0-mae:2129.06681
[436]	validation_0-mae:2128.91457
[437]	validation_0-mae:2129.12296
[438]	validation_0-mae:2127.93111
[439]	validation_0-mae:2127.47515
[440]	validation_0-mae:2127.49845
[441]	validation_0-mae:2127.24194
[442]	validation_0-mae:2127.78960
[443]	validation_0-mae:2128.09941
[444]	validation_0-mae:2128.20513
[445]	validation_0-mae:2128.27348
[446]	validation_0-mae:2128.51575
[447]	validation_0-mae:2128.21485
[448]	validation_0-mae:2128.30804
[449]	validation_0-mae:2128.55704
[450]	validation_0-mae:2128.92725
[451]	validation_0-mae:2129.18671
[452]	validation_0-mae:2128.75271
[453]	validation_0-mae:2128.17264
[454]	validation_0-mae:2128.08887
[455]	validation_0-mae:2127.44500
[456]	validation_0-mae:2127.11816
[457]	validation_0-mae:2127.14222
[458]	validation_0-mae:2127.35521
[459]	validation_0-mae:2127.24756
[460]	validation_0-mae:2127.21399
[461]	validation_0-mae:2126.96994
[462]	validation_0-mae:2126.62940
[463]	validation_0-mae:2126.48862
[464]	validation_0-mae:2126.59194
[465]	validation_0-mae:2126.75436
[466]	validation_0-mae:2127.14414
[467]	validation_0-mae:2127.34177
[468]	validation_0-mae:2127.24488
[469]	validation_0-mae:2127.12748
[470]	validation_0-mae:2127.24107
[471]	validation_0-mae:2127.32834
[472]	validation_0-mae:2127.15301
[473]	validation_0-mae:2127.15295
[474]	validation_0-mae:2127.13817
[475]	validation_0-mae:2127.04372
[476]	validation_0-mae:2126.86674
[477]	validation_0-mae:2125.22701
[478]	validation_0-mae:2125.04464
[479]	validation_0-mae:2124.81367
[480]	validation_0-mae:2124.76695
[481]	validation_0-mae:2124.07925
[482]	validation_0-mae:2124.03059
[483]	validation_0-mae:2123.87256
[484]	validation_0-mae:2123.59846
[485]	validation_0-mae:2123.17403
[486]	validation_0-mae:2122.84682
[487]	validation_0-mae:2122.72918
[488]	validation_0-mae:2122.33272
[489]	validation_0-mae:2122.32921
[490]	validation_0-mae:2122.58036
[491]	validation_0-mae:2122.54600
[492]	validation_0-mae:2123.10590
[493]	validation_0-mae:2123.44799
[494]	validation_0-mae:2123.34048
[495]	validation_0-mae:2123.28161
[496]	validation_0-mae:2123.19788
[497]	validation_0-mae:2122.94753
[498]	validation_0-mae:2122.99591
[499]	validation_0-mae:2122.90580
[500]	validation_0-mae:2122.92944
[501]	validation_0-mae:2122.55496
[502]	validation_0-mae:2122.83223
[503]	validation_0-mae:2123.01176
[504]	validation_0-mae:2123.05590
[505]	validation_0-mae:2123.06027
[506]	validation_0-mae:2123.37996
[507]	validation_0-mae:2123.19167
[508]	validation_0-mae:2122.89704
[509]	validation_0-mae:2122.94699
[510]	validation_0-mae:2122.93593
[511]	validation_0-mae:2123.39590
[512]	validation_0-mae:2123.40431
[513]	validation_0-mae:2123.57557
[514]	validation_0-mae:2123.80955
[515]	validation_0-mae:2123.65372
[516]	validation_0-mae:2123.91461
[517]	validation_0-mae:2124.05691
[518]	validation_0-mae:2123.94380
[519]	validation_0-mae:2124.25604
[520]	validation_0-mae:2124.25911
[521]	validation_0-mae:2124.31329
[522]	validation_0-mae:2124.31376
[523]	validation_0-mae:2124.27567
[524]	validation_0-mae:2124.41287
[525]	validation_0-mae:2124.34960
[526]	validation_0-mae:2123.75810
[527]	validation_0-mae:2123.45649
[528]	validation_0-mae:2123.81948
[529]	validation_0-mae:2123.62925
[530]	validation_0-mae:2122.48832
[531]	validation_0-mae:2122.35395
[532]	validation_0-mae:2122.27614
[533]	validation_0-mae:2122.29252
[534]	validation_0-mae:2122.35618
[535]	validation_0-mae:2122.58481
[536]	validation_0-mae:2122.74011
[537]	validation_0-mae:2122.79027
[538]	validation_0-mae:2122.22843
[539]	validation_0-mae:2122.19165
[540]	validation_0-mae:2121.65228
[541]	validation_0-mae:2121.67876
[542]	validation_0-mae:2121.58157
[543]	validation_0-mae:2121.28619
[544]	validation_0-mae:2120.80923
[545]	validation_0-mae:2120.43521
[546]	validation_0-mae:2120.52009
[547]	validation_0-mae:2120.13877
[548]	validation_0-mae:2119.61193
[549]	validation_0-mae:2118.99952
[550]	validation_0-mae:2119.04286
[551]	validation_0-mae:2119.11199
[552]	validation_0-mae:2119.13359
[553]	validation_0-mae:2118.97095
[554]	validation_0-mae:2118.96263
[555]	validation_0-mae:2118.49334
[556]	validation_0-mae:2118.17028
[557]	validation_0-mae:2117.62788
[558]	validation_0-mae:2117.64601
[559]	validation_0-mae:2117.51773
[560]	validation_0-mae:2117.78437
[561]	validation_0-mae:2117.86844
[562]	validation_0-mae:2118.00828
[563]	validation_0-mae:2117.93697
[564]	validation_0-mae:2118.14762
[565]	validation_0-mae:2118.18866
[566]	validation_0-mae:2117.21770
[567]	validation_0-mae:2116.85960
[568]	validation_0-mae:2117.21100
[569]	validation_0-mae:2117.32507
[570]	validation_0-mae:2116.94879
[571]	validation_0-mae:2116.96752
[572]	validation_0-mae:2116.80961
[573]	validation_0-mae:2116.83905
[574]	validation_0-mae:2116.92597
[575]	validation_0-mae:2116.54895
[576]	validation_0-mae:2116.13327
[577]	validation_0-mae:2116.11046
[578]	validation_0-mae:2115.50314
[579]	validation_0-mae:2115.13543
[580]	validation_0-mae:2115.29653
[581]	validation_0-mae:2115.19767
[582]	validation_0-mae:2115.21815
[583]	validation_0-mae:2114.77349
[584]	validation_0-mae:2114.51348
[585]	validation_0-mae:2114.61335
[586]	validation_0-mae:2114.52617
[587]	validation_0-mae:2114.58951
[588]	validation_0-mae:2114.72248
[589]	validation_0-mae:2114.72609
[590]	validation_0-mae:2114.75623
[591]	validation_0-mae:2115.20479
[592]	validation_0-mae:2114.93533
[593]	validation_0-mae:2114.68136
[594]	validation_0-mae:2114.98792
[595]	validation_0-mae:2115.29543
[596]	validation_0-mae:2115.52663
[597]	validation_0-mae:2115.11937
[598]	validation_0-mae:2114.90522
[599]	validation_0-mae:2114.84110
[600]	validation_0-mae:2114.89433
[601]	validation_0-mae:2114.83797
[602]	validation_0-mae:2114.91654
[603]	validation_0-mae:2115.11419
[604]	validation_0-mae:2115.18651
[605]	validation_0-mae:2115.14540
[606]	validation_0-mae:2115.21302
[607]	validation_0-mae:2115.02878
[608]	validation_0-mae:2115.21614
[609]	validation_0-mae:2115.34638
[610]	validation_0-mae:2115.52854
[611]	validation_0-mae:2115.55845
[612]	validation_0-mae:2115.21000
[613]	validation_0-mae:2115.14223
[614]	validation_0-mae:2115.08831
[615]	validation_0-mae:2115.21572
[616]	validation_0-mae:2115.04306
[617]	validation_0-mae:2115.34264
[618]	validation_0-mae:2115.34303
[619]	validation_0-mae:2115.28122
[620]	validation_0-mae:2114.96794
[621]	validation_0-mae:2115.01771
[622]	validation_0-mae:2114.87519
[623]	validation_0-mae:2114.95505
[624]	validation_0-mae:2114.89751
[625]	validation_0-mae:2115.22361
[626]	validation_0-mae:2115.19166
[627]	validation_0-mae:2115.31033
[628]	validation_0-mae:2115.34699

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[38]	validation_0-mae:3338.97438
[39]	validation_0-mae:3296.64378
[40]	validation_0-mae:3253.83316
[41]	validation_0-mae:3208.19389
[42]	validation_0-mae:3178.50577
[43]	validation_0-mae:3148.38893
[44]	validation_0-mae:3114.20312
[45]	validation_0-mae:3055.83771
[46]	validation_0-mae:3029.76459
[47]	validation_0-mae:3004.88468
[48]	validation_0-mae:2986.05475
[49]	validation_0-mae:2959.41022
[50]	validation_0-mae:2943.58107
[51]	validation_0-mae:2920.94806
[52]	validation_0-mae:2896.79572
[53]	validation_0-mae:2868.20069
[54]	validation_0-mae:2851.87552
[55]	validation_0-mae:2827.87650
[56]	validation_0-mae:2810.95744
[57]	validation_0-mae:2789.44298
[58]	validation_0-mae:2775.00740
[59]	validation_0-mae:2759.53957
[60]	validation_0-mae:2747.28142
[61]	validation_0-mae:2727.80014
[62]	validation_0-mae:2700.86708
[63]	validation_0-mae:2688.19242
[64]	validation_0-mae:2678.94060
[65]	validation_0-mae:2667.51505
[66]	validation_0-mae:2647.65938
[67]	validation_0-mae:2628.92499
[68]	validation_0-mae:2620.84307
[69]	validation_0-mae:2615.01659
[70]	validation_0-mae:2601.06155
[71]	validation_0-mae:2594.30863
[72]	validation_0-mae:2578.62472
[73]	validation_0-mae:2572.38197
[74]	validation_0-mae:2560.64388
[75]	validation_0-mae:2554.26850
[76]	validation_0-mae:2540.60247
[77]	validation_0-mae:2531.39465
[78]	validation_0-mae:2522.94801
[79]	validation_0-mae:2508.38937
[80]	validation_0-mae:2503.53369
[81]	validation_0-mae:2493.65883
[82]	validation_0-mae:2485.12986
[83]	validation_0-mae:2477.51893
[84]	validation_0-mae:2464.83890
[85]	validation_0-mae:2455.86644
[86]	validation_0-mae:2450.30328
[87]	validation_0-mae:2444.53898
[88]	validation_0-mae:2435.69303
[89]	validation_0-mae:2433.56752
[90]	validation_0-mae:2426.62415
[91]	validation_0-mae:2419.02195
[92]	validation_0-mae:2411.13943
[93]	validation_0-mae:2405.62964
[94]	validation_0-mae:2400.26411
[95]	validation_0-mae:2395.66689
[96]	validation_0-mae:2392.96751
[97]	validation_0-mae:2386.57814
[98]	validation_0-mae:2382.32240
[99]	validation_0-mae:2370.50467
[100]	validation_0-mae:2366.79267
[101]	validation_0-mae:2364.16097
[102]	validation_0-mae:2359.90910
[103]	validation_0-mae:2355.76704
[104]	validation_0-mae:2351.47209
[105]	validation_0-mae:2344.71412
[106]	validation_0-mae:2339.77619
[107]	validation_0-mae:2337.07025
[108]	validation_0-mae:2333.64778
[109]	validation_0-mae:2329.69160
[110]	validation_0-mae:2326.03171
[111]	validation_0-mae:2323.48350
[112]	validation_0-mae:2320.08013
[113]	validation_0-mae:2317.54390
[114]	validation_0-mae:2312.35048
[115]	validation_0-mae:2310.47709
[116]	validation_0-mae:2307.10576
[117]	validation_0-mae:2305.80390
[118]	validation_0-mae:2301.58657
[119]	validation_0-mae:2297.08648
[120]	validation_0-mae:2294.17379
[121]	validation_0-mae:2293.62622
[122]	validation_0-mae:2293.59799
[123]	validation_0-mae:2290.53151
[124]	validation_0-mae:2290.13977
[125]	validation_0-mae:2288.43029
[126]	validation_0-mae:2286.24152
[127]	validation_0-mae:2284.09008
[128]	validation_0-mae:2280.76591
[129]	validation_0-mae:2275.93048
[130]	validation_0-mae:2273.35100
[131]	validation_0-mae:2271.57619
[132]	validation_0-mae:2268.83697
[133]	validation_0-mae:2267.80645
[134]	validation_0-mae:2265.36361
[135]	validation_0-mae:2263.82251
[136]	validation_0-mae:2263.51627
[137]	validation_0-mae:2262.44157
[138]	validation_0-mae:2262.37085
[139]	validation_0-mae:2261.35579
[140]	validation_0-mae:2260.87278
[141]	validation_0-mae:2258.46462
[142]	validation_0-mae:2255.76211
[143]	validation_0-mae:2252.95613
[144]	validation_0-mae:2252.32227
[145]	validation_0-mae:2252.53674
[146]	validation_0-mae:2251.31277
[147]	validation_0-mae:2251.38849
[148]	validation_0-mae:2249.17287
[149]	validation_0-mae:2245.42434
[150]	validation_0-mae:2245.31375
[151]	validation_0-mae:2243.99554
[152]	validation_0-mae:2244.88432
[153]	validation_0-mae:2243.56619
[154]	validation_0-mae:2243.28653
[155]	validation_0-mae:2242.23001
[156]	validation_0-mae:2242.17152
[157]	validation_0-mae:2240.66380
[158]	validation_0-mae:2236.23874
[159]	validation_0-mae:2234.82360
[160]	validation_0-mae:2233.89325
[161]	validation_0-mae:2232.21919
[162]	validation_0-mae:2230.55346
[163]	validation_0-mae:2229.15873
[164]	validation_0-mae:2228.01916
[165]	validation_0-mae:2225.67033
[166]	validation_0-mae:2225.44430
[167]	validation_0-mae:2222.31611
[168]	validation_0-mae:2222.40105
[169]	validation_0-mae:2222.39526
[170]	validation_0-mae:2221.89575
[171]	validation_0-mae:2220.82854
[172]	validation_0-mae:2219.65668
[173]	validation_0-mae:2219.14691
[174]	validation_0-mae:2218.21024
[175]	validation_0-mae:2218.38339
[176]	validation_0-mae:2218.46076
[177]	validation_0-mae:2215.60328
[178]	validation_0-mae:2214.02988
[179]	validation_0-mae:2213.82989
[180]	validation_0-mae:2213.39015
[181]	validation_0-mae:2212.63547
[182]	validation_0-mae:2211.95146
[183]	validation_0-mae:2209.26427
[184]	validation_0-mae:2209.95601
[185]	validation_0-mae:2207.93442
[186]	validation_0-mae:2207.80864
[187]	validation_0-mae:2205.78282
[188]	validation_0-mae:2205.76107
[189]	validation_0-mae:2204.66714
[190]	validation_0-mae:2202.39860
[191]	validation_0-mae:2201.07699
[192]	validation_0-mae:2199.88080
[193]	validation_0-mae:2198.88904
[194]	validation_0-mae:2199.60923
[195]	validation_0-mae:2199.15879
[196]	validation_0-mae:2198.99500
[197]	validation_0-mae:2198.38766
[198]	validation_0-mae:2197.96874
[199]	validation_0-mae:2197.45088
[200]	validation_0-mae:2197.53215
[201]	validation_0-mae:2197.74349
[202]	validation_0-mae:2196.68912
[203]	validation_0-mae:2195.37049
[204]	validation_0-mae:2194.46251
[205]	validation_0-mae:2195.25239
[206]	validation_0-mae:2194.36483
[207]	validation_0-mae:2192.85302
[208]	validation_0-mae:2192.31375
[209]	validation_0-mae:2192.39640
[210]	validation_0-mae:2191.67403
[211]	validation_0-mae:2190.00377
[212]	validation_0-mae:2189.60280
[213]	validation_0-mae:2189.72786
[214]	validation_0-mae:2189.04969
[215]	validation_0-mae:2188.48022
[216]	validation_0-mae:2188.67274
[217]	validation_0-mae:2186.53888
[218]	validation_0-mae:2185.17845
[219]	validation_0-mae:2185.13102
[220]	validation_0-mae:2184.17351
[221]	validation_0-mae:2182.84562
[222]	validation_0-mae:2181.54970
[223]	validation_0-mae:2180.37763
[224]	validation_0-mae:2178.18585
[225]	validation_0-mae:2177.64560
[226]	validation_0-mae:2177.59541
[227]	validation_0-mae:2176.84227
[228]	validation_0-mae:2177.31560
[229]	validation_0-mae:2177.14570
[230]	validation_0-mae:2176.58770
[231]	validation_0-mae:2175.09690
[232]	validation_0-mae:2174.96554
[233]	validation_0-mae:2174.72223
[234]	validation_0-mae:2173.37026
[235]	validation_0-mae:2173.47102
[236]	validation_0-mae:2173.38465
[237]	validation_0-mae:2172.72180
[238]	validation_0-mae:2171.89670
[239]	validation_0-mae:2173.00786
[240]	validation_0-mae:2172.86496
[241]	validation_0-mae:2172.55476
[242]	validation_0-mae:2172.05365
[243]	validation_0-mae:2171.39120
[244]	validation_0-mae:2170.83610
[245]	validation_0-mae:2169.80891
[246]	validation_0-mae:2167.79389
[247]	validation_0-mae:2168.24757
[248]	validation_0-mae:2167.04258
[249]	validation_0-mae:2165.98456
[250]	validation_0-mae:2166.38676
[251]	validation_0-mae:2163.64548
[252]	validation_0-mae:2164.16566
[253]	validation_0-mae:2164.30166
[254]	validation_0-mae:2162.86482
[255]	validation_0-mae:2161.86038
[256]	validation_0-mae:2161.64299
[257]	validation_0-mae:2162.17575
[258]	validation_0-mae:2161.39009
[259]	validation_0-mae:2161.27325
[260]	validation_0-mae:2160.17202
[261]	validation_0-mae:2159.66241
[262]	validation_0-mae:2160.24780
[263]	validation_0-mae:2160.40492
[264]	validation_0-mae:2160.79770
[265]	validation_0-mae:2160.34873
[266]	validation_0-mae:2160.91275
[267]	validation_0-mae:2159.43147
[268]	validation_0-mae:2159.11872
[269]	validation_0-mae:2158.45798
[270]	validation_0-mae:2157.35332
[271]	validation_0-mae:2155.86399
[272]	validation_0-mae:2155.14004
[273]	validation_0-mae:2155.22105
[274]	validation_0-mae:2153.14965
[275]	validation_0-mae:2152.44180
[276]	validation_0-mae:2151.78642
[277]	validation_0-mae:2151.99310
[278]	validation_0-mae:2151.94398
[279]	validation_0-mae:2151.10560
[280]	validation_0-mae:2150.93361
[281]	validation_0-mae:2151.57666
[282]	validation_0-mae:2151.76980
[283]	validation_0-mae:2151.37167
[284]	validation_0-mae:2151.13917
[285]	validation_0-mae:2150.55452
[286]	validation_0-mae:2150.16964
[287]	validation_0-mae:2149.93624
[288]	validation_0-mae:2149.62746
[289]	validation_0-mae:2149.57957
[290]	validation_0-mae:2149.27544
[291]	validation_0-mae:2149.13090
[292]	validation_0-mae:2148.65049
[293]	validation_0-mae:2147.95979
[294]	validation_0-mae:2148.39058
[295]	validation_0-mae:2147.71818
[296]	validation_0-mae:2148.47848
[297]	validation_0-mae:2147.84009
[298]	validation_0-mae:2147.03855
[299]	validation_0-mae:2146.73525
[300]	validation_0-mae:2147.23860
[301]	validation_0-mae:2147.48448
[302]	validation_0-mae:2147.76001
[303]	validation_0-mae:2147.80613
[304]	validation_0-mae:2147.78423
[305]	validation_0-mae:2147.73853
[306]	validation_0-mae:2146.80070
[307]	validation_0-mae:2146.35474
[308]	validation_0-mae:2145.44434
[309]	validation_0-mae:2145.00423
[310]	validation_0-mae:2144.67446
[311]	validation_0-mae:2144.78961
[312]	validation_0-mae:2144.85791
[313]	validation_0-mae:2145.09408
[314]	validation_0-mae:2143.80820
[315]	validation_0-mae:2142.93060
[316]	validation_0-mae:2142.57172
[317]	validation_0-mae:2142.98720
[318]	validation_0-mae:2142.22905
[319]	validation_0-mae:2141.89319
[320]	validation_0-mae:2141.16315
[321]	validation_0-mae:2140.13381
[322]	validation_0-mae:2139.66283
[323]	validation_0-mae:2138.46100
[324]	validation_0-mae:2137.64023
[325]	validation_0-mae:2136.78231
[326]	validation_0-mae:2136.18003
[327]	validation_0-mae:2136.11759
[328]	validation_0-mae:2134.56428
[329]	validation_0-mae:2134.68243
[330]	validation_0-mae:2134.33740
[331]	validation_0-mae:2133.62857
[332]	validation_0-mae:2132.88095
[333]	validation_0-mae:2133.27051
[334]	validation_0-mae:2133.20763
[335]	validation_0-mae:2131.94065
[336]	validation_0-mae:2131.55752
[337]	validation_0-mae:2131.92251
[338]	validation_0-mae:2131.26337
[339]	validation_0-mae:2131.21600
[340]	validation_0-mae:2131.47671
[341]	validation_0-mae:2131.04607
[342]	validation_0-mae:2130.11720
[343]	validation_0-mae:2129.72512
[344]	validation_0-mae:2129.61179
[345]	validation_0-mae:2130.00932
[346]	validation_0-mae:2129.58004
[347]	validation_0-mae:2128.93463
[348]	validation_0-mae:2129.23643
[349]	validation_0-mae:2128.59430
[350]	validation_0-mae:2128.88665
[351]	validation_0-mae:2128.34084
[352]	validation_0-mae:2127.96147
[353]	validation_0-mae:2128.02704
[354]	validation_0-mae:2127.63976
[355]	validation_0-mae:2127.57619
[356]	validation_0-mae:2128.02229
[357]	validation_0-mae:2128.43796
[358]	validation_0-mae:2128.79018
[359]	validation_0-mae:2129.14965
[360]	validation_0-mae:2129.39261
[361]	validation_0-mae:2129.15484
[362]	validation_0-mae:2127.04296
[363]	validation_0-mae:2127.20739
[364]	validation_0-mae:2128.49981
[365]	validation_0-mae:2128.00211
[366]	validation_0-mae:2128.46571
[367]	validation_0-mae:2127.53982
[368]	validation_0-mae:2126.93981
[369]	validation_0-mae:2125.59756
[370]	validation_0-mae:2126.25149
[371]	validation_0-mae:2125.94792
[372]	validation_0-mae:2123.90093
[373]	validation_0-mae:2123.74613
[374]	validation_0-mae:2123.21454
[375]	validation_0-mae:2123.09218
[376]	validation_0-mae:2122.98461
[377]	validation_0-mae:2122.87895
[378]	validation_0-mae:2122.70977
[379]	validation_0-mae:2122.35348
[380]	validation_0-mae:2122.73977
[381]	validation_0-mae:2122.57771
[382]	validation_0-mae:2122.02546
[383]	validation_0-mae:2121.46498
[384]	validation_0-mae:2120.66821
[385]	validation_0-mae:2120.41653
[386]	validation_0-mae:2120.03014
[387]	validation_0-mae:2119.48331
[388]	validation_0-mae:2119.83106
[389]	validation_0-mae:2118.99960
[390]	validation_0-mae:2118.56215
[391]	validation_0-mae:2118.45978
[392]	validation_0-mae:2117.86367
[393]	validation_0-mae:2117.94175
[394]	validation_0-mae:2117.65900
[395]	validation_0-mae:2117.51292
[396]	validation_0-mae:2117.31819
[397]	validation_0-mae:2117.07944
[398]	validation_0-mae:2116.97338
[399]	validation_0-mae:2116.08827
[400]	validation_0-mae:2115.71749
[401]	validation_0-mae:2115.35006
[402]	validation_0-mae:2115.20262
[403]	validation_0-mae:2114.79166
[404]	validation_0-mae:2114.05119
[405]	validation_0-mae:2114.20565
[406]	validation_0-mae:2114.07258
[407]	validation_0-mae:2113.96366
[408]	validation_0-mae:2114.08123
[409]	validation_0-mae:2114.26776
[410]	validation_0-mae:2114.45535
[411]	validation_0-mae:2114.16709
[412]	validation_0-mae:2113.99019
[413]	validation_0-mae:2114.10701
[414]	validation_0-mae:2113.56716
[415]	validation_0-mae:2113.68471
[416]	validation_0-mae:2113.65969
[417]	validation_0-mae:2113.76435
[418]	validation_0-mae:2113.92334
[419]	validation_0-mae:2113.90868
[420]	validation_0-mae:2114.31641
[421]	validation_0-mae:2114.64709
[422]	validation_0-mae:2113.89637
[423]	validation_0-mae:2113.77530
[424]	validation_0-mae:2114.31212
[425]	validation_0-mae:2114.50509
[426]	validation_0-mae:2114.84952
[427]	validation_0-mae:2114.69022
[428]	validation_0-mae:2114.19201
[429]	validation_0-mae:2113.78757
[430]	validation_0-mae:2112.70172
[431]	validation_0-mae:2112.62043
[432]	validation_0-mae:2110.97984
[433]	validation_0-mae:2110.76706
[434]	validation_0-mae:2110.70417
[435]	validation_0-mae:2110.91661
[436]	validation_0-mae:2110.84477
[437]	validation_0-mae:2110.60890
[438]	validation_0-mae:2109.30011
[439]	validation_0-mae:2108.22089
[440]	validation_0-mae:2106.94683
[441]	validation_0-mae:2106.72552
[442]	validation_0-mae:2106.03696
[443]	validation_0-mae:2106.35016
[444]	validation_0-mae:2106.45400
[445]	validation_0-mae:2106.48661
[446]	validation_0-mae:2105.33833
[447]	validation_0-mae:2104.94365
[448]	validation_0-mae:2104.62527
[449]	validation_0-mae:2103.77376
[450]	validation_0-mae:2103.70090
[451]	validation_0-mae:2103.59882
[452]	validation_0-mae:2103.61324
[453]	validation_0-mae:2103.35159
[454]	validation_0-mae:2102.86257
[455]	validation_0-mae:2102.24235
[456]	validation_0-mae:2102.02552
[457]	validation_0-mae:2101.94722
[458]	validation_0-mae:2101.81662
[459]	validation_0-mae:2101.46695
[460]	validation_0-mae:2101.14734
[461]	validation_0-mae:2101.16770
[462]	validation_0-mae:2101.00493
[463]	validation_0-mae:2100.90412
[464]	validation_0-mae:2101.11800
[465]	validation_0-mae:2101.13992
[466]	validation_0-mae:2101.03457
[467]	validation_0-mae:2101.03582
[468]	validation_0-mae:2100.67025
[469]	validation_0-mae:2100.27701
[470]	validation_0-mae:2100.42292
[471]	validation_0-mae:2100.06223
[472]	validation_0-mae:2099.90712
[473]	validation_0-mae:2099.88116
[474]	validation_0-mae:2099.47069
[475]	validation_0-mae:2098.71450
[476]	validation_0-mae:2098.43196
[477]	validation_0-mae:2098.14212
[478]	validation_0-mae:2097.11246
[479]	validation_0-mae:2096.48136
[480]	validation_0-mae:2096.40714
[481]	validation_0-mae:2096.63715
[482]	validation_0-mae:2096.55242
[483]	validation_0-mae:2096.73093
[484]	validation_0-mae:2096.30447
[485]	validation_0-mae:2096.19045
[486]	validation_0-mae:2096.18651
[487]	validation_0-mae:2096.12060
[488]	validation_0-mae:2095.99955
[489]	validation_0-mae:2095.52810
[490]	validation_0-mae:2095.51678
[491]	validation_0-mae:2095.41514
[492]	validation_0-mae:2095.52899
[493]	validation_0-mae:2095.49195
[494]	validation_0-mae:2095.67492
[495]	validation_0-mae:2095.48270
[496]	validation_0-mae:2094.73031
[497]	validation_0-mae:2094.52006
[498]	validation_0-mae:2094.50294
[499]	validation_0-mae:2094.56989
[500]	validation_0-mae:2094.30438
[501]	validation_0-mae:2094.54799
[502]	validation_0-mae:2094.58190
[503]	validation_0-mae:2094.82654
[504]	validation_0-mae:2094.68651
[505]	validation_0-mae:2094.76634
[506]	validation_0-mae:2094.77013
[507]	validation_0-mae:2094.84348
[508]	validation_0-mae:2094.87039
[509]	validation_0-mae:2094.51085
[510]	validation_0-mae:2094.22597
[511]	validation_0-mae:2093.79015
[512]	validation_0-mae:2094.03369
[513]	validation_0-mae:2093.60853
[514]	validation_0-mae:2093.68473
[515]	validation_0-mae:2093.86695
[516]	validation_0-mae:2093.99724
[517]	validation_0-mae:2094.02488
[518]	validation_0-mae:2093.45149
[519]	validation_0-mae:2093.49242
[520]	validation_0-mae:2093.07014
[521]	validation_0-mae:2092.69510
[522]	validation_0-mae:2092.72735
[523]	validation_0-mae:2092.44736
[524]	validation_0-mae:2092.43781
[525]	validation_0-mae:2092.38648
[526]	validation_0-mae:2092.16810
[527]	validation_0-mae:2092.50334
[528]	validation_0-mae:2092.71261
[529]	validation_0-mae:2092.30152
[530]	validation_0-mae:2092.32462
[531]	validation_0-mae:2092.10828
[532]	validation_0-mae:2092.14796
[533]	validation_0-mae:2091.28359
[534]	validation_0-mae:2090.98958
[535]	validation_0-mae:2090.78247
[536]	validation_0-mae:2090.41494
[537]	validation_0-mae:2090.54372
[538]	validation_0-mae:2090.33268
[539]	validation_0-mae:2090.57431
[540]	validation_0-mae:2090.41999
[541]	validation_0-mae:2090.79599
[542]	validation_0-mae:2090.98633
[543]	validation_0-mae:2090.39789
[544]	validation_0-mae:2090.51705
[545]	validation_0-mae:2090.11353
[546]	validation_0-mae:2090.37780
[547]	validation_0-mae:2090.53269
[548]	validation_0-mae:2090.54442
[549]	validation_0-mae:2090.71356
[550]	validation_0-mae:2090.46341
[551]	validation_0-mae:2089.74466
[552]	validation_0-mae:2089.10993
[553]	validation_0-mae:2088.92602
[554]	validation_0-mae:2089.07982
[555]	validation_0-mae:2088.67068
[556]	validation_0-mae:2088.36193
[557]	validation_0-mae:2088.39230
[558]	validation_0-mae:2088.40981
[559]	validation_0-mae:2088.65528
[560]	validation_0-mae:2088.67927
[561]	validation_0-mae:2088.94976
[562]	validation_0-mae:2088.57528
[563]	validation_0-mae:2087.60789
[564]	validation_0-mae:2088.11432
[565]	validation_0-mae:2087.93302
[566]	validation_0-mae:2087.91752
[567]	validation_0-mae:2087.30129
[568]	validation_0-mae:2087.22424
[569]	validation_0-mae:2087.04021
[570]	validation_0-mae:2086.82275
[571]	validation_0-mae:2086.51080
[572]	validation_0-mae:2086.71945
[573]	validation_0-mae:2086.45677
[574]	validation_0-mae:2086.20540
[575]	validation_0-mae:2086.47106
[576]	validation_0-mae:2086.79775
[577]	validation_0-mae:2087.15475
[578]	validation_0-mae:2087.06529
[579]	validation_0-mae:2087.25676
[580]	validation_0-mae:2087.31764
[0]	validation_0-mae:12400.88769
[1]	validation_0-mae:11625.08209
[2]	validation_0-mae:10911.94788
[3]	validation_0-mae:10272.64459
[4]	validation_0-mae:9693.80387
[5]	validation_0-mae:9181.78387
[6]	validation_0-mae:8727.18825
[7]	validation_0-mae:8291.04329
[8]	validation_0-mae:7913.17785
[9]	validation_0-mae:7565.88521
[10]	validation_0-mae:7223.29118
[11]	validation_0-mae:6918.95170
[12]	validation_0-mae:6631.54014
[13]	validation_0-mae:6351.25581
[14]	validation_0-mae:6082.37861
[15]	validation_0-mae:5873.62118
[16]	validation_0-mae:5669.17492
[17]	validation_0-mae:5464.59033
[18]	validation_0-mae:5260.00072
[19]	validation_0-mae:5107.67267
[20]	validation_0-mae:4940.18107
[21]	validation_0-mae:4784.36679
[22]	validation_0-mae:4656.18683
[23]	validation_0-mae:4513.35994
[24]	validation_0-mae:4383.17513
[25]	validation_0-mae:4261.19288
[26]	validation_0-mae:4161.01045
[27]	validation_0-mae:4071.90964
[28]	validation_0-mae:3983.96801
[29]	validation_0-mae:3891.72622
[30]	validation_0-mae:3805.55228
[31]	validation_0-mae:3737.96462
[32]	validation_0-mae:3670.29026
[33]	validation_0-mae:3601.01590
[34]	validation_0-mae:3543.09422
[35]	validation_0-mae:3486.06020
[36]	validation_0-mae:3432.89882
[37]	validation_0-mae:3382.63906

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[38]	validation_0-mae:3342.98674
[39]	validation_0-mae:3304.10653
[40]	validation_0-mae:3264.85620
[41]	validation_0-mae:3226.70760
[42]	validation_0-mae:3195.57203
[43]	validation_0-mae:3149.87115
[44]	validation_0-mae:3116.98926
[45]	validation_0-mae:3095.20731
[46]	validation_0-mae:3051.53457
[47]	validation_0-mae:3024.83257
[48]	validation_0-mae:2999.98647
[49]	validation_0-mae:2975.10799
[50]	validation_0-mae:2958.57718
[51]	validation_0-mae:2923.66949
[52]	validation_0-mae:2888.36762
[53]	validation_0-mae:2850.99302
[54]	validation_0-mae:2831.26547
[55]	validation_0-mae:2813.26085
[56]	validation_0-mae:2789.99048
[57]	validation_0-mae:2770.41360
[58]	validation_0-mae:2755.03445
[59]	validation_0-mae:2743.30239
[60]	validation_0-mae:2728.47493
[61]	validation_0-mae:2708.41682
[62]	validation_0-mae:2699.93064
[63]	validation_0-mae:2677.42113
[64]	validation_0-mae:2669.84376
[65]	validation_0-mae:2654.39941
[66]	validation_0-mae:2642.33944
[67]	validation_0-mae:2620.46694
[68]	validation_0-mae:2611.78314
[69]	validation_0-mae:2600.58976
[70]	validation_0-mae:2592.80125
[71]	validation_0-mae:2580.42445
[72]	validation_0-mae:2561.30247
[73]	validation_0-mae:2556.91657
[74]	validation_0-mae:2542.19745
[75]	validation_0-mae:2534.60757
[76]	validation_0-mae:2524.51132
[77]	validation_0-mae:2517.71565
[78]	validation_0-mae:2509.02656
[79]	validation_0-mae:2503.87646
[80]	validation_0-mae:2486.97516
[81]	validation_0-mae:2478.70851
[82]	validation_0-mae:2474.92231
[83]	validation_0-mae:2466.44532
[84]	validation_0-mae:2461.16728
[85]	validation_0-mae:2450.86547
[86]	validation_0-mae:2447.43061
[87]	validation_0-mae:2434.17026
[88]	validation_0-mae:2428.58687
[89]	validation_0-mae:2424.68943
[90]	validation_0-mae:2416.52878
[91]	validation_0-mae:2410.61771
[92]	validation_0-mae:2402.25076
[93]	validation_0-mae:2399.76917
[94]	validation_0-mae:2391.94736
[95]	validation_0-mae:2389.17411
[96]	validation_0-mae:2387.56185
[97]	validation_0-mae:2382.09021
[98]	validation_0-mae:2377.20121
[99]	validation_0-mae:2376.50024
[100]	validation_0-mae:2371.70227
[101]	validation_0-mae:2368.32975
[102]	validation_0-mae:2361.61443
[103]	validation_0-mae:2354.85033
[104]	validation_0-mae:2352.20569
[105]	validation_0-mae:2348.51587
[106]	validation_0-mae:2345.57414
[107]	validation_0-mae:2344.08460
[108]	validation_0-mae:2339.83919
[109]	validation_0-mae:2336.43874
[110]	validation_0-mae:2332.75276
[111]	validation_0-mae:2330.39306
[112]	validation_0-mae:2328.78373
[113]	validation_0-mae:2325.32934
[114]	validation_0-mae:2323.20759
[115]	validation_0-mae:2317.77248
[116]	validation_0-mae:2313.52374
[117]	validation_0-mae:2312.04320
[118]	validation_0-mae:2308.86594
[119]	validation_0-mae:2304.23032
[120]	validation_0-mae:2302.50854
[121]	validation_0-mae:2301.39353
[122]	validation_0-mae:2296.75261
[123]	validation_0-mae:2296.17480
[124]	validation_0-mae:2291.78304
[125]	validation_0-mae:2288.24848
[126]	validation_0-mae:2288.91499
[127]	validation_0-mae:2284.91041
[128]	validation_0-mae:2281.42135
[129]	validation_0-mae:2281.26008
[130]	validation_0-mae:2279.71938
[131]	validation_0-mae:2275.44872
[132]	validation_0-mae:2273.44882
[133]	validation_0-mae:2269.08234
[134]	validation_0-mae:2265.76227
[135]	validation_0-mae:2263.54274
[136]	validation_0-mae:2262.79855
[137]	validation_0-mae:2261.40035
[138]	validation_0-mae:2262.26875
[139]	validation_0-mae:2261.06795
[140]	validation_0-mae:2262.90064
[141]	validation_0-mae:2262.91262
[142]	validation_0-mae:2261.42263
[143]	validation_0-mae:2257.78716
[144]	validation_0-mae:2256.55676
[145]	validation_0-mae:2254.62962
[146]	validation_0-mae:2254.22247
[147]	validation_0-mae:2250.72038
[148]	validation_0-mae:2250.57218
[149]	validation_0-mae:2250.22428
[150]	validation_0-mae:2248.42929
[151]	validation_0-mae:2245.17280
[152]	validation_0-mae:2245.07168
[153]	validation_0-mae:2243.05492
[154]	validation_0-mae:2241.54561
[155]	validation_0-mae:2239.38624
[156]	validation_0-mae:2236.45903
[157]	validation_0-mae:2235.51338
[158]	validation_0-mae:2236.07149
[159]	validation_0-mae:2234.06509
[160]	validation_0-mae:2231.83889
[161]	validation_0-mae:2230.24819
[162]	validation_0-mae:2230.21848
[163]	validation_0-mae:2229.40338
[164]	validation_0-mae:2230.08288
[165]	validation_0-mae:2229.82027
[166]	validation_0-mae:2229.36715
[167]	validation_0-mae:2228.40712
[168]	validation_0-mae:2226.36615
[169]	validation_0-mae:2227.98994
[170]	validation_0-mae:2226.87644
[171]	validation_0-mae:2226.36126
[172]	validation_0-mae:2226.32460
[173]	validation_0-mae:2227.32257
[174]	validation_0-mae:2225.13678
[175]	validation_0-mae:2223.74408
[176]	validation_0-mae:2220.62600
[177]	validation_0-mae:2220.24732
[178]	validation_0-mae:2219.76840
[179]	validation_0-mae:2217.80461
[180]	validation_0-mae:2217.58907
[181]	validation_0-mae:2216.33250
[182]	validation_0-mae:2216.45244
[183]	validation_0-mae:2215.96609
[184]	validation_0-mae:2215.73132
[185]	validation_0-mae:2215.55509
[186]	validation_0-mae:2214.47409
[187]	validation_0-mae:2213.52289
[188]	validation_0-mae:2213.54454
[189]	validation_0-mae:2211.67435
[190]	validation_0-mae:2211.16909
[191]	validation_0-mae:2210.70550
[192]	validation_0-mae:2209.52502
[193]	validation_0-mae:2207.99331
[194]	validation_0-mae:2207.38858
[195]	validation_0-mae:2205.46316
[196]	validation_0-mae:2204.57116
[197]	validation_0-mae:2204.60199
[198]	validation_0-mae:2202.74880
[199]	validation_0-mae:2202.73554
[200]	validation_0-mae:2202.06938
[201]	validation_0-mae:2201.27256
[202]	validation_0-mae:2200.84257
[203]	validation_0-mae:2200.88969
[204]	validation_0-mae:2200.69474
[205]	validation_0-mae:2200.61672
[206]	validation_0-mae:2198.74680
[207]	validation_0-mae:2198.58252
[208]	validation_0-mae:2198.86212
[209]	validation_0-mae:2199.16670
[210]	validation_0-mae:2198.96010
[211]	validation_0-mae:2198.26623
[212]	validation_0-mae:2198.37520
[213]	validation_0-mae:2198.74798
[214]	validation_0-mae:2198.12477
[215]	validation_0-mae:2197.48702
[216]	validation_0-mae:2196.96873
[217]	validation_0-mae:2197.18088
[218]	validation_0-mae:2197.37837
[219]	validation_0-mae:2197.42707
[220]	validation_0-mae:2196.69176
[221]	validation_0-mae:2197.12560
[222]	validation_0-mae:2195.93460
[223]	validation_0-mae:2195.78935
[224]	validation_0-mae:2195.58635
[225]	validation_0-mae:2194.62006
[226]	validation_0-mae:2194.53599
[227]	validation_0-mae:2195.17762
[228]	validation_0-mae:2194.78535
[229]	validation_0-mae:2195.20637
[230]	validation_0-mae:2195.54374
[231]	validation_0-mae:2193.25181
[232]	validation_0-mae:2193.24244
[233]	validation_0-mae:2193.36564
[234]	validation_0-mae:2192.98611
[235]	validation_0-mae:2192.15654
[236]	validation_0-mae:2191.97445
[237]	validation_0-mae:2191.84825
[238]	validation_0-mae:2191.68255
[239]	validation_0-mae:2191.85301
[240]	validation_0-mae:2191.10990
[241]	validation_0-mae:2190.33266
[242]	validation_0-mae:2189.33669
[243]	validation_0-mae:2189.19606
[244]	validation_0-mae:2189.00049
[245]	validation_0-mae:2189.36759
[246]	validation_0-mae:2189.44895
[247]	validation_0-mae:2188.38149
[248]	validation_0-mae:2187.67077
[249]	validation_0-mae:2187.59064
[250]	validation_0-mae:2187.65708
[251]	validation_0-mae:2187.50120
[252]	validation_0-mae:2187.16981
[253]	validation_0-mae:2186.09296
[254]	validation_0-mae:2186.59932
[255]	validation_0-mae:2185.31257
[256]	validation_0-mae:2185.61537
[257]	validation_0-mae:2186.31008
[258]	validation_0-mae:2187.30307
[259]	validation_0-mae:2187.37060
[260]	validation_0-mae:2185.75139
[261]	validation_0-mae:2185.70991
[262]	validation_0-mae:2186.12557
[263]	validation_0-mae:2186.25177
[264]	validation_0-mae:2185.61932
[265]	validation_0-mae:2184.18861
[266]	validation_0-mae:2182.94155
[267]	validation_0-mae:2182.71205
[268]	validation_0-mae:2180.58119
[269]	validation_0-mae:2179.80677
[270]	validation_0-mae:2179.49137
[271]	validation_0-mae:2179.66513
[272]	validation_0-mae:2179.09998
[273]	validation_0-mae:2177.78668
[274]	validation_0-mae:2176.95829
[275]	validation_0-mae:2175.19015
[276]	validation_0-mae:2174.19011
[277]	validation_0-mae:2174.66364
[278]	validation_0-mae:2174.64672
[279]	validation_0-mae:2173.50492
[280]	validation_0-mae:2173.54345
[281]	validation_0-mae:2174.36075
[282]	validation_0-mae:2174.22349
[283]	validation_0-mae:2174.17247
[284]	validation_0-mae:2173.98545
[285]	validation_0-mae:2173.95707
[286]	validation_0-mae:2174.31269
[287]	validation_0-mae:2174.01440
[288]	validation_0-mae:2173.71460
[289]	validation_0-mae:2173.41710
[290]	validation_0-mae:2173.51534
[291]	validation_0-mae:2174.42376
[292]	validation_0-mae:2174.22040
[293]	validation_0-mae:2172.15961
[294]	validation_0-mae:2172.11192
[295]	validation_0-mae:2170.75648
[296]	validation_0-mae:2170.29878
[297]	validation_0-mae:2170.13687
[298]	validation_0-mae:2168.65487
[299]	validation_0-mae:2168.71310
[300]	validation_0-mae:2169.08054
[301]	validation_0-mae:2169.15111
[302]	validation_0-mae:2168.93439
[303]	validation_0-mae:2169.98873
[304]	validation_0-mae:2169.85837
[305]	validation_0-mae:2169.92084
[306]	validation_0-mae:2168.53190
[307]	validation_0-mae:2167.16613
[308]	validation_0-mae:2167.67138
[309]	validation_0-mae:2167.44258
[310]	validation_0-mae:2166.89757
[311]	validation_0-mae:2166.28317
[312]	validation_0-mae:2166.50355
[313]	validation_0-mae:2166.89629
[314]	validation_0-mae:2165.59646
[315]	validation_0-mae:2165.56512
[316]	validation_0-mae:2165.52622
[317]	validation_0-mae:2165.84112
[318]	validation_0-mae:2165.47854
[319]	validation_0-mae:2165.46227
[320]	validation_0-mae:2165.46786
[321]	validation_0-mae:2165.24526
[322]	validation_0-mae:2165.04316
[323]	validation_0-mae:2164.61475
[324]	validation_0-mae:2164.64150
[325]	validation_0-mae:2163.98370
[326]	validation_0-mae:2162.97049
[327]	validation_0-mae:2162.56287
[328]	validation_0-mae:2163.00024
[329]	validation_0-mae:2162.03017
[330]	validation_0-mae:2161.82219
[331]	validation_0-mae:2162.16711
[332]	validation_0-mae:2161.53976
[333]	validation_0-mae:2161.28833
[334]	validation_0-mae:2160.91934
[335]	validation_0-mae:2159.43734
[336]	validation_0-mae:2159.71081
[337]	validation_0-mae:2158.27152
[338]	validation_0-mae:2158.03349
[339]	validation_0-mae:2157.23276
[340]	validation_0-mae:2157.02603
[341]	validation_0-mae:2156.42115
[342]	validation_0-mae:2156.58652
[343]	validation_0-mae:2156.39512
[344]	validation_0-mae:2156.34089
[345]	validation_0-mae:2156.40550
[346]	validation_0-mae:2156.68661
[347]	validation_0-mae:2156.70896
[348]	validation_0-mae:2156.76362
[349]	validation_0-mae:2156.13580
[350]	validation_0-mae:2156.06484
[351]	validation_0-mae:2155.27272
[352]	validation_0-mae:2155.09484
[353]	validation_0-mae:2155.06032
[354]	validation_0-mae:2154.52237
[355]	validation_0-mae:2154.38876
[356]	validation_0-mae:2153.46357
[357]	validation_0-mae:2154.00083
[358]	validation_0-mae:2153.75931
[359]	validation_0-mae:2154.55122
[360]	validation_0-mae:2154.55604
[361]	validation_0-mae:2154.67568
[362]	validation_0-mae:2155.26655
[363]	validation_0-mae:2155.96090
[364]	validation_0-mae:2155.73813
[365]	validation_0-mae:2155.60908
[366]	validation_0-mae:2155.45907
[367]	validation_0-mae:2156.09495
[368]	validation_0-mae:2155.23831
[369]	validation_0-mae:2155.31423
[370]	validation_0-mae:2156.19071
[371]	validation_0-mae:2157.13117
[372]	validation_0-mae:2156.42057
[373]	validation_0-mae:2156.08559
[374]	validation_0-mae:2155.98102
[375]	validation_0-mae:2155.65939
[376]	validation_0-mae:2155.55882
[377]	validation_0-mae:2156.28303
[378]	validation_0-mae:2156.75291
[379]	validation_0-mae:2156.99063
[380]	validation_0-mae:2156.83551
[381]	validation_0-mae:2156.88209
[382]	validation_0-mae:2156.37724
[383]	validation_0-mae:2156.55195
[384]	validation_0-mae:2157.07387
[385]	validation_0-mae:2157.23016
[386]	validation_0-mae:2157.28623
[387]	validation_0-mae:2157.31495
[388]	validation_0-mae:2157.30365
[389]	validation_0-mae:2157.58152
[390]	validation_0-mae:2157.87170
[391]	validation_0-mae:2157.39346
[392]	validation_0-mae:2156.98888
[393]	validation_0-mae:2157.09346
[394]	validation_0-mae:2157.03610
[395]	validation_0-mae:2157.46059
[396]	validation_0-mae:2158.34335
[397]	validation_0-mae:2158.31909
[398]	validation_0-mae:2158.37865
[399]	validation_0-mae:2158.41093
[400]	validation_0-mae:2158.33347
[401]	validation_0-mae:2158.21226
[402]	validation_0-mae:2158.20296
[403]	validation_0-mae:2158.10048
[404]	validation_0-mae:2158.09390
[405]	validation_0-mae:2157.92184
[406]	validation_0-mae:2157.82330
[407]	validation_0-mae:2157.83642
[408]	validation_0-mae:2156.63776
[409]	validation_0-mae:2156.29072
[410]	validation_0-mae:2154.92692
[411]	validation_0-mae:2153.86663
[412]	validation_0-mae:2153.71882
[413]	validation_0-mae:2153.75606
[414]	validation_0-mae:2153.36837
[415]	validation_0-mae:2152.89197
[416]	validation_0-mae:2152.86156
[417]	validation_0-mae:2152.52315
[418]	validation_0-mae:2152.30699
[419]	validation_0-mae:2152.16373
[420]	validation_0-mae:2152.53666
[421]	validation_0-mae:2151.96760
[422]	validation_0-mae:2151.71372
[423]	validation_0-mae:2151.87188
[424]	validation_0-mae:2151.78093
[425]	validation_0-mae:2151.97625
[426]	validation_0-mae:2151.72405
[0]	validation_0-mae:12531.15693
[1]	validation_0-mae:11855.59049
[2]	validation_0-mae:11245.20094
[3]	validation_0-mae:10683.07310
[4]	validation_0-mae:10176.74112
[5]	validation_0-mae:9711.10456
[6]	validation_0-mae:9303.50993
[7]	validation_0-mae:8923.65569
[8]	validation_0-mae:8593.16004
[9]	validation_0-mae:8304.98069
[10]	validation_0-mae:8043.61788

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[0]	validation_0-mae:12457.95550
[1]	validation_0-mae:11739.17211
[2]	validation_0-mae:11075.87573
[3]	validation_0-mae:10471.46249
[4]	validation_0-mae:9937.54908
[5]	validation_0-mae:9447.04079
[6]	validation_0-mae:9004.86406
[7]	validation_0-mae:8589.86030
[8]	validation_0-mae:8194.93653
[9]	validation_0-mae:7864.12163
[10]	validation_0-mae:7548.46312
[11]	validation_0-mae:7249.00232
[12]	validation_0-mae:6960.98601
[13]	validation_0-mae:6715.62553
[14]	validation_0-mae:6473.30935
[15]	validation_0-mae:6247.74670
[16]	validation_0-mae:6006.74089
[17]	validation_0-mae:5803.74316
[18]	validation_0-mae:5610.62942
[19]	validation_0-mae:5442.03972
[20]	validation_0-mae:5260.47223
[21]	validation_0-mae:5105.50715
[22]	validation_0-mae:4957.96130
[23]	validation_0-mae:4818.31601
[24]	validation_0-mae:4683.11947
[25]	validation_0-mae:4554.86456
[26]	validation_0-mae:4443.31565
[27]	validation_0-mae:4336.54649
[28]	validation_0-mae:4230.77271
[29]	validation_0-mae:4136.40507
[30]	validation_0-mae:4046.30130
[31]	validation_0-mae:3958.39366
[32]	validation_0-mae:3881.24634
[33]	validation_0-mae:3801.88078
[34]	validation_0-mae:3740.18025
[35]	validation_0-mae:3675.11995
[36]	validation_0-mae:3616.73343
[37]	validation_0-mae:3550.06625
[38]	validation_0-mae:3497.50953
[39]	validation_0-mae:3431.24611
[40]	validation_0-mae:3377.04970
[41]	validation_0-mae:3327.20657
[42]	validation_0-mae:3281.68571
[43]	validation_0-mae:3241.42424
[44]	validation_0-mae:3207.22111
[45]	validation_0-mae:3171.00938
[46]	validation_0-mae:3136.73884
[47]	validation_0-mae:3103.72435
[48]	validation_0-mae:3061.33228
[49]	validation_0-mae:3035.61981
[50]	validation_0-mae:3000.01997
[51]	validation_0-mae:2976.77588
[52]	validation_0-mae:2950.65368
[53]	validation_0-mae:2929.45412
[54]	validation_0-mae:2908.34665
[55]	validation_0-mae:2876.92330
[56]	validation_0-mae:2858.14189
[57]	validation_0-mae:2830.89612
[58]	validation_0-mae:2814.85579
[59]	validation_0-mae:2797.07671
[60]	validation_0-mae:2782.17945
[61]	validation_0-mae:2769.66224
[62]	validation_0-mae:2753.05663
[63]	validation_0-mae:2740.90099
[64]	validation_0-mae:2718.08319
[65]	validation_0-mae:2703.40674
[66]	validation_0-mae:2696.17384
[67]	validation_0-mae:2682.33902
[68]	validation_0-mae:2672.92025
[69]	validation_0-mae:2655.73187
[70]	validation_0-mae:2643.61683
[71]	validation_0-mae:2630.29958
[72]	validation_0-mae:2622.54088
[73]	validation_0-mae:2612.89796
[74]	validation_0-mae:2604.89111
[75]	validation_0-mae:2594.91366
[76]	validation_0-mae:2585.38203
[77]	validation_0-mae:2570.63226
[78]	validation_0-mae:2557.44377
[79]	validation_0-mae:2550.87708
[80]	validation_0-mae:2535.11860
[81]	validation_0-mae:2524.63812
[82]	validation_0-mae:2517.02666
[83]	validation_0-mae:2508.20012
[84]	validation_0-mae:2495.63949
[85]	validation_0-mae:2491.05935
[86]	validation_0-mae:2484.85352
[87]	validation_0-mae:2475.17830
[88]	validation_0-mae:2469.24859
[89]	validation_0-mae:2459.78220
[90]	validation_0-mae:2456.78088
[91]	validation_0-mae:2451.47548
[92]	validation_0-mae:2442.18082
[93]	validation_0-mae:2438.32105
[94]	validation_0-mae:2427.66706
[95]	validation_0-mae:2420.01681
[96]	validation_0-mae:2412.04018
[97]	validation_0-mae:2406.09999
[98]	validation_0-mae:2398.63110
[99]	validation_0-mae:2392.07547
[100]	validation_0-mae:2386.68039
[101]	validation_0-mae:2383.39829
[102]	validation_0-mae:2380.56227
[103]	validation_0-mae:2373.04361
[104]	validation_0-mae:2364.63783
[105]	validation_0-mae:2360.31901
[106]	validation_0-mae:2356.56126
[107]	validation_0-mae:2353.61962
[108]	validation_0-mae:2351.24730
[109]	validation_0-mae:2342.30786
[110]	validation_0-mae:2335.06320
[111]	validation_0-mae:2329.06071
[112]	validation_0-mae:2325.44731
[113]	validation_0-mae:2323.41189
[114]	validation_0-mae:2317.50264
[115]	validation_0-mae:2314.54661
[116]	validation_0-mae:2311.58306
[117]	validation_0-mae:2308.60107
[118]	validation_0-mae:2303.83387
[119]	validation_0-mae:2302.61808
[120]	validation_0-mae:2300.42375
[121]	validation_0-mae:2296.71024
[122]	validation_0-mae:2294.75295
[123]	validation_0-mae:2294.34861
[124]	validation_0-mae:2289.76629
[125]	validation_0-mae:2285.12394
[126]	validation_0-mae:2282.26978
[127]	validation_0-mae:2281.81813
[128]	validation_0-mae:2281.41083
[129]	validation_0-mae:2280.91723
[130]	validation_0-mae:2275.75190
[131]	validation_0-mae:2273.36702
[132]	validation_0-mae:2269.70934
[133]	validation_0-mae:2267.32215
[134]	validation_0-mae:2264.53316
[135]	validation_0-mae:2262.69395
[136]	validation_0-mae:2256.64190
[137]	validation_0-mae:2257.43286
[138]	validation_0-mae:2255.52179
[139]	validation_0-mae:2254.19011
[140]	validation_0-mae:2254.52847
[141]	validation_0-mae:2252.29484
[142]	validation_0-mae:2251.13035
[143]	validation_0-mae:2248.08973
[144]	validation_0-mae:2246.11471
[145]	validation_0-mae:2244.69620
[146]	validation_0-mae:2243.86527
[147]	validation_0-mae:2244.39970
[148]	validation_0-mae:2242.79481
[149]	validation_0-mae:2241.85772
[150]	validation_0-mae:2241.81914
[151]	validation_0-mae:2237.61033
[152]	validation_0-mae:2236.63916
[153]	validation_0-mae:2237.07053
[154]	validation_0-mae:2234.86321
[155]	validation_0-mae:2235.11096
[156]	validation_0-mae:2231.49325
[157]	validation_0-mae:2229.17143
[158]	validation_0-mae:2228.52290
[159]	validation_0-mae:2226.99600
[160]	validation_0-mae:2225.76941
[161]	validation_0-mae:2223.79548
[162]	validation_0-mae:2219.29716
[163]	validation_0-mae:2218.36117
[164]	validation_0-mae:2216.86279
[165]	validation_0-mae:2216.66983
[166]	validation_0-mae:2214.85313
[167]	validation_0-mae:2213.24830
[168]	validation_0-mae:2213.23347
[169]	validation_0-mae:2214.29915
[170]	validation_0-mae:2210.80271
[171]	validation_0-mae:2210.01787
[172]	validation_0-mae:2207.60682
[173]	validation_0-mae:2207.41449
[174]	validation_0-mae:2204.78128
[175]	validation_0-mae:2202.67204
[176]	validation_0-mae:2202.38029
[177]	validation_0-mae:2200.81546
[178]	validation_0-mae:2200.57967
[179]	validation_0-mae:2199.10266
[180]	validation_0-mae:2198.87926
[181]	validation_0-mae:2197.31036
[182]	validation_0-mae:2197.72803
[183]	validation_0-mae:2198.13243
[184]	validation_0-mae:2199.29089
[185]	validation_0-mae:2197.16621
[186]	validation_0-mae:2196.90530
[187]	validation_0-mae:2197.01519
[188]	validation_0-mae:2195.44130
[189]	validation_0-mae:2194.97257
[190]	validation_0-mae:2193.92037
[191]	validation_0-mae:2193.31389
[192]	validation_0-mae:2193.28881
[193]	validation_0-mae:2191.77989
[194]	validation_0-mae:2191.65152
[195]	validation_0-mae:2190.73389
[196]	validation_0-mae:2189.73015
[197]	validation_0-mae:2186.88431
[198]	validation_0-mae:2187.07998
[199]	validation_0-mae:2187.97184
[200]	validation_0-mae:2186.02519
[201]	validation_0-mae:2186.05472
[202]	validation_0-mae:2185.66098
[203]	validation_0-mae:2186.17364
[204]	validation_0-mae:2186.26384
[205]	validation_0-mae:2186.20840
[206]	validation_0-mae:2185.76779
[207]	validation_0-mae:2185.65762
[208]	validation_0-mae:2185.74121
[209]	validation_0-mae:2185.88702
[210]	validation_0-mae:2184.84241
[211]	validation_0-mae:2184.60765
[212]	validation_0-mae:2184.68967
[213]	validation_0-mae:2183.42437
[214]	validation_0-mae:2183.22479
[215]	validation_0-mae:2182.30997
[216]	validation_0-mae:2182.62991
[217]	validation_0-mae:2180.95888
[218]	validation_0-mae:2181.11716
[219]	validation_0-mae:2180.56866
[220]	validation_0-mae:2179.97289
[221]	validation_0-mae:2179.02636
[222]	validation_0-mae:2178.59526
[223]	validation_0-mae:2177.48542
[224]	validation_0-mae:2177.41280
[225]	validation_0-mae:2177.15305
[226]	validation_0-mae:2176.91054
[227]	validation_0-mae:2176.54844
[228]	validation_0-mae:2176.49228
[229]	validation_0-mae:2177.96783
[230]	validation_0-mae:2178.01665
[231]	validation_0-mae:2176.79952
[232]	validation_0-mae:2176.41628
[233]	validation_0-mae:2176.58385
[234]	validation_0-mae:2176.47924
[235]	validation_0-mae:2175.45184
[236]	validation_0-mae:2174.93647
[237]	validation_0-mae:2175.55851
[238]	validation_0-mae:2175.26224
[239]	validation_0-mae:2174.56602
[240]	validation_0-mae:2173.29681
[241]	validation_0-mae:2171.10855
[242]	validation_0-mae:2170.15979
[243]	validation_0-mae:2170.02977
[244]	validation_0-mae:2168.59233
[245]	validation_0-mae:2167.52271
[246]	validation_0-mae:2166.26007
[247]	validation_0-mae:2166.00615
[248]	validation_0-mae:2165.93270
[249]	validation_0-mae:2165.93097
[250]	validation_0-mae:2165.84348
[251]	validation_0-mae:2165.69229
[252]	validation_0-mae:2166.37057
[253]	validation_0-mae:2165.02064
[254]	validation_0-mae:2165.06395
[255]	validation_0-mae:2163.98109
[256]	validation_0-mae:2164.34098
[257]	validation_0-mae:2163.12902
[258]	validation_0-mae:2162.14497
[259]	validation_0-mae:2162.12694
[260]	validation_0-mae:2159.58691
[261]	validation_0-mae:2159.43184
[262]	validation_0-mae:2160.33052
[263]	validation_0-mae:2159.34005
[264]	validation_0-mae:2160.09903
[265]	validation_0-mae:2160.57459
[266]	validation_0-mae:2159.40266
[267]	validation_0-mae:2159.74765
[268]	validation_0-mae:2158.93971
[269]	validation_0-mae:2158.46705
[270]	validation_0-mae:2159.27018
[271]	validation_0-mae:2158.46055
[272]	validation_0-mae:2158.28084
[273]	validation_0-mae:2157.88777
[274]	validation_0-mae:2158.47084
[275]	validation_0-mae:2158.41498
[276]	validation_0-mae:2158.20673
[277]	validation_0-mae:2157.88320
[278]	validation_0-mae:2157.29779
[279]	validation_0-mae:2156.47593
[280]	validation_0-mae:2156.03567
[281]	validation_0-mae:2155.34773
[282]	validation_0-mae:2155.51309
[283]	validation_0-mae:2155.74307
[284]	validation_0-mae:2155.48755
[285]	validation_0-mae:2155.37780
[286]	validation_0-mae:2155.61549
[287]	validation_0-mae:2154.91695
[288]	validation_0-mae:2153.85041
[289]	validation_0-mae:2153.54642
[290]	validation_0-mae:2152.48493
[291]	validation_0-mae:2154.01077
[292]	validation_0-mae:2153.00972
[293]	validation_0-mae:2151.88133
[294]	validation_0-mae:2151.38479
[295]	validation_0-mae:2152.44033
[296]	validation_0-mae:2152.85919
[297]	validation_0-mae:2152.40355
[298]	validation_0-mae:2149.81244
[299]	validation_0-mae:2149.67239
[300]	validation_0-mae:2149.43795
[301]	validation_0-mae:2147.55265
[302]	validation_0-mae:2146.69798
[303]	validation_0-mae:2145.83522
[304]	validation_0-mae:2145.85471
[305]	validation_0-mae:2145.07549
[306]	validation_0-mae:2144.31121
[307]	validation_0-mae:2144.12265
[308]	validation_0-mae:2144.00462
[309]	validation_0-mae:2143.52410
[310]	validation_0-mae:2143.03010
[311]	validation_0-mae:2142.61372
[312]	validation_0-mae:2142.26312
[313]	validation_0-mae:2142.53442
[314]	validation_0-mae:2143.06200
[315]	validation_0-mae:2143.43212
[316]	validation_0-mae:2142.85687
[317]	validation_0-mae:2142.77735
[318]	validation_0-mae:2142.46164
[319]	validation_0-mae:2142.36716
[320]	validation_0-mae:2142.11857
[321]	validation_0-mae:2141.85936
[322]	validation_0-mae:2142.06901
[323]	validation_0-mae:2142.02386
[324]	validation_0-mae:2141.93470
[325]	validation_0-mae:2141.84604
[326]	validation_0-mae:2141.73944
[327]	validation_0-mae:2141.55789
[328]	validation_0-mae:2141.51766
[329]	validation_0-mae:2141.59801
[330]	validation_0-mae:2140.28875
[331]	validation_0-mae:2140.33109
[332]	validation_0-mae:2138.26897
[333]	validation_0-mae:2137.89036
[334]	validation_0-mae:2135.93483
[335]	validation_0-mae:2136.46375
[336]	validation_0-mae:2136.29722
[337]	validation_0-mae:2136.33406
[338]	validation_0-mae:2136.42210
[339]	validation_0-mae:2137.24384
[340]	validation_0-mae:2135.94118
[341]	validation_0-mae:2135.30244
[342]	validation_0-mae:2134.86173
[343]	validation_0-mae:2134.43676
[344]	validation_0-mae:2134.45784
[345]	validation_0-mae:2132.56040
[346]	validation_0-mae:2132.34246
[347]	validation_0-mae:2132.37797
[348]	validation_0-mae:2131.51508
[349]	validation_0-mae:2131.97103
[350]	validation_0-mae:2131.62859
[351]	validation_0-mae:2131.09668
[352]	validation_0-mae:2130.64681
[353]	validation_0-mae:2130.68391
[354]	validation_0-mae:2130.48685
[355]	validation_0-mae:2131.00756
[356]	validation_0-mae:2130.96549
[357]	validation_0-mae:2130.93233
[358]	validation_0-mae:2130.16457
[359]	validation_0-mae:2130.41300
[360]	validation_0-mae:2130.22129
[361]	validation_0-mae:2130.63359
[362]	validation_0-mae:2130.71303
[363]	validation_0-mae:2130.66837
[364]	validation_0-mae:2130.31077
[365]	validation_0-mae:2129.47806
[366]	validation_0-mae:2129.63542
[367]	validation_0-mae:2129.09746
[368]	validation_0-mae:2128.42427
[369]	validation_0-mae:2128.61146
[370]	validation_0-mae:2128.61390
[371]	validation_0-mae:2128.11194
[372]	validation_0-mae:2127.15698
[373]	validation_0-mae:2127.01278
[374]	validation_0-mae:2127.05609
[375]	validation_0-mae:2126.57041
[376]	validation_0-mae:2125.87248
[377]	validation_0-mae:2126.14973
[378]	validation_0-mae:2125.66391
[379]	validation_0-mae:2125.30360
[380]	validation_0-mae:2125.52661
[381]	validation_0-mae:2124.71398
[382]	validation_0-mae:2124.54569
[383]	validation_0-mae:2124.92722
[384]	validation_0-mae:2124.98029
[385]	validation_0-mae:2124.99793
[386]	validation_0-mae:2124.84107
[387]	validation_0-mae:2124.33757
[388]	validation_0-mae:2124.89386
[389]	validation_0-mae:2125.23557
[390]	validation_0-mae:2125.51487
[391]	validation_0-mae:2125.52261
[392]	validation_0-mae:2125.70642
[393]	validation_0-mae:2125.88215
[394]	validation_0-mae:2125.66658
[395]	validation_0-mae:2125.17687
[396]	validation_0-mae:2125.32602
[397]	validation_0-mae:2125.13553
[398]	validation_0-mae:2123.59835
[399]	validation_0-mae:2123.82227
[400]	validation_0-mae:2124.33549
[401]	validation_0-mae:2124.13992
[402]	validation_0-mae:2124.15022
[403]	validation_0-mae:2122.82682
[404]	validation_0-mae:2123.12528
[405]	validation_0-mae:2123.63223
[406]	validation_0-mae:2122.64679
[407]	validation_0-mae:2121.79743
[408]	validation_0-mae:2120.62043
[409]	validation_0-mae:2120.16905
[410]	validation_0-mae:2119.53105
[411]	validation_0-mae:2119.00745
[412]	validation_0-mae:2118.18657
[413]	validation_0-mae:2117.78348
[414]	validation_0-mae:2117.38097
[415]	validation_0-mae:2118.02227
[416]	validation_0-mae:2118.11356
[417]	validation_0-mae:2118.04444
[418]	validation_0-mae:2117.58608
[419]	validation_0-mae:2117.54017
[420]	validation_0-mae:2117.46519
[421]	validation_0-mae:2117.42538
[422]	validation_0-mae:2116.38671
[423]	validation_0-mae:2115.25633
[424]	validation_0-mae:2114.98903
[425]	validation_0-mae:2113.84928
[426]	validation_0-mae:2114.03382
[427]	validation_0-mae:2114.05856
[428]	validation_0-mae:2114.49382
[429]	validation_0-mae:2114.37887
[430]	validation_0-mae:2114.63136
[431]	validation_0-mae:2114.93283
[432]	validation_0-mae:2115.02263
[433]	validation_0-mae:2115.05438
[434]	validation_0-mae:2115.29846
[435]	validation_0-mae:2115.27195
[436]	validation_0-mae:2115.31470
[437]	validation_0-mae:2115.37810
[438]	validation_0-mae:2115.81136
[439]	validation_0-mae:2115.83636
[440]	validation_0-mae:2115.95905
[441]	validation_0-mae:2115.89835
[442]	validation_0-mae:2115.92924
[443]	validation_0-mae:2116.05955
[444]	validation_0-mae:2116.07908
[445]	validation_0-mae:2116.17290
[446]	validation_0-mae:2116.35754
[447]	validation_0-mae:2116.30362
[448]	validation_0-mae:2116.10112
[449]	validation_0-mae:2116.00522
[450]	validation_0-mae:2116.37542
[451]	validation_0-mae:2116.14695
[452]	validation_0-mae:2116.12950
[453]	validation_0-mae:2116.17928
[454]	validation_0-mae:2116.38567
[455]	validation_0-mae:2116.76027
[456]	validation_0-mae:2115.84642
[457]	validation_0-mae:2116.06225
[458]	validation_0-mae:2115.54802
[459]	validation_0-mae:2115.71682
[460]	validation_0-mae:2116.08044
[461]	validation_0-mae:2116.43671
[462]	validation_0-mae:2115.64385
[463]	validation_0-mae:2115.91734
[464]	validation_0-mae:2116.03870
[465]	validation_0-mae:2115.66741
[466]	validation_0-mae:2115.06064
[467]	validation_0-mae:2115.73372
[468]	validation_0-mae:2115.85439
[469]	validation_0-mae:2116.07555
[470]	validation_0-mae:2115.22769
[471]	validation_0-mae:2114.62857
[472]	validation_0-mae:2115.09259
[473]	validation_0-mae:2114.45687
[474]	validation_0-mae:2114.10214
[475]	validation_0-mae:2113.53983
[476]	validation_0-mae:2113.28836
[477]	validation_0-mae:2113.27993
[478]	validation_0-mae:2113.48650
[479]	validation_0-mae:2113.81871
[480]	validation_0-mae:2114.04594
[481]	validation_0-mae:2113.24590
[482]	validation_0-mae:2112.96036
[483]	validation_0-mae:2112.52969
[484]	validation_0-mae:2112.54413
[485]	validation_0-mae:2113.36778
[486]	validation_0-mae:2113.99744
[487]	validation_0-mae:2113.76189
[488]	validation_0-mae:2113.27885
[489]	validation_0-mae:2113.26082
[490]	validation_0-mae:2113.33355
[491]	validation_0-mae:2112.87633
[492]	validation_0-mae:2112.72479
[493]	validation_0-mae:2112.79300
[494]	validation_0-mae:2112.04707
[495]	validation_0-mae:2111.86849
[496]	validation_0-mae:2111.05630
[497]	validation_0-mae:2110.47302
[498]	validation_0-mae:2110.01810
[499]	validation_0-mae:2109.49797
[500]	validation_0-mae:2108.92935
[501]	validation_0-mae:2108.62896
[502]	validation_0-mae:2108.33577
[503]	validation_0-mae:2107.65447
[504]	validation_0-mae:2107.46120
[505]	validation_0-mae:2107.65515
[506]	validation_0-mae:2107.64809
[507]	validation_0-mae:2107.57754
[508]	validation_0-mae:2107.39174
[509]	validation_0-mae:2107.08845
[510]	validation_0-mae:2106.99396
[511]	validation_0-mae:2107.20644
[512]	validation_0-mae:2107.03496
[513]	validation_0-mae:2106.94388
[514]	validation_0-mae:2106.73164
[515]	validation_0-mae:2107.21113
[516]	validation_0-mae:2106.59314
[517]	validation_0-mae:2106.68294
[518]	validation_0-mae:2106.11999
[519]	validation_0-mae:2105.80575
[520]	validation_0-mae:2105.77252
[521]	validation_0-mae:2105.94759
[522]	validation_0-mae:2105.19356
[523]	validation_0-mae:2105.04753
[524]	validation_0-mae:2104.83414
[525]	validation_0-mae:2104.72443
[526]	validation_0-mae:2104.64977
[527]	validation_0-mae:2104.33399
[528]	validation_0-mae:2104.42975
[529]	validation_0-mae:2104.12696
[530]	validation_0-mae:2104.20136
[531]	validation_0-mae:2103.81282
[532]	validation_0-mae:2103.69810
[533]	validation_0-mae:2103.72971
[534]	validation_0-mae:2103.07056
[535]	validation_0-mae:2102.97490
[536]	validation_0-mae:2102.87188
[537]	validation_0-mae:2102.40358
[538]	validation_0-mae:2102.42444
[539]	validation_0-mae:2102.24702
[540]	validation_0-mae:2102.34133
[541]	validation_0-mae:2101.99203
[542]	validation_0-mae:2101.69871
[543]	validation_0-mae:2101.73100
[0]	validation_0-mae:12553.01050
[1]	validation_0-mae:11894.56639
[2]	validation_0-mae:11299.61477
[3]	validation_0-mae:10748.30487
[4]	validation_0-mae:10247.89280
[5]	validation_0-mae:9789.13495
[6]	validation_0-mae:9384.56832
[7]	validation_0-mae:9022.59446
[8]	validation_0-mae:8691.59694
[9]	validation_0-mae:8398.72637
[10]	validation_0-mae:8125.04994

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[0]	validation_0-mae:13134.65958
[1]	validation_0-mae:12974.12933
[2]	validation_0-mae:12815.45688
[3]	validation_0-mae:12663.96164
[4]	validation_0-mae:12514.04325
[5]	validation_0-mae:12366.95797
[6]	validation_0-mae:12223.81095
[7]	validation_0-mae:12083.01759
[8]	validation_0-mae:11944.94504
[9]	validation_0-mae:11813.23186
[0]	validation_0-mae:12568.69411
[1]	validation_0-mae:11941.67059
[2]	validation_0-mae:11401.41318
[3]	validation_0-mae:10931.73879
[4]	validation_0-mae:10546.42886
[5]	validation_0-mae:10214.85105
[6]	validation_0-mae:9920.81192
[7]	validation_0-mae:9664.79963
[8]	validation_0-mae:9445.33944
[9]	validation_0-mae:9249.23602
[10]	validation_0-mae:9087.74166
[0]	validation_0-mae:13262.35500

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[1]	validation_0-mae:13226.36127
[2]	validation_0-mae:13190.51354
[3]	validation_0-mae:13154.76400
[4]	validation_0-mae:13119.01446
[5]	validation_0-mae:13083.53878
[6]	validation_0-mae:13048.06302
[7]	validation_0-mae:13012.99109
[8]	validation_0-mae:12978.07690
[9]	validation_0-mae:12943.52037
[10]	validation_0-mae:12909.04184
[0]	validation_0-mae:12616.20241
[1]	validation_0-mae:12028.54356
[2]	validation_0-mae:11510.68529
[3]	validation_0-mae:11061.15848
[4]	validation_0-mae:10666.53084
[5]	validation_0-mae:10335.65468
[6]	validation_0-mae:10037.58358
[7]	validation_0-mae:9778.97881
[8]	validation_0-mae:9554.07717
[9]	validation_0-mae:9357.53145
[10]	validation_0-mae:9186.66601
[0]	validation_0-mae:12427.17934
[1]	validation_0-mae:11684.67463
[2]	validation_0-mae:11016.49141

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[3]	validation_0-mae:10376.62555
[4]	validation_0-mae:9826.83641
[5]	validation_0-mae:9309.39605
[6]	validation_0-mae:8847.52729
[7]	validation_0-mae:8431.35793
[8]	validation_0-mae:8048.30118
[9]	validation_0-mae:7686.85630
[10]	validation_0-mae:7384.27487
[11]	validation_0-mae:7078.95484
[12]	validation_0-mae:6801.23347
[13]	validation_0-mae:6526.16254
[14]	validation_0-mae:6284.98513
[15]	validation_0-mae:6050.06036
[16]	validation_0-mae:5835.04934
[17]	validation_0-mae:5643.45984
[18]	validation_0-mae:5453.54674
[19]	validation_0-mae:5285.38287
[20]	validation_0-mae:5106.79499
[21]	validation_0-mae:4937.36533
[22]	validation_0-mae:4778.18648
[23]	validation_0-mae:4649.42495
[24]	validation_0-mae:4521.37104
[25]	validation_0-mae:4397.46224
[26]	validation_0-mae:4288.09574
[27]	validation_0-mae:4194.54289
[28]	validation_0-mae:4097.03886
[29]	validation_0-mae:4001.64626
[30]	validation_0-mae:3931.37075
[31]	validation_0-mae:3847.50976
[32]	validation_0-mae:3765.44043
[33]	validation_0-mae:3692.58652
[34]	validation_0-mae:3633.05018
[35]	validation_0-mae:3578.58403
[36]	validation_0-mae:3513.53970
[37]	validation_0-mae:3463.74698
[38]	validation_0-mae:3416.62501
[39]	validation_0-mae:3372.61272
[40]	validation_0-mae:3328.73619
[41]	validation_0-mae:3282.87135
[42]	validation_0-mae:3241.54630
[43]	validation_0-mae:3205.21791
[44]	validation_0-mae:3166.75006
[45]	validation_0-mae:3136.61166
[46]	validation_0-mae:3103.28684
[47]	validation_0-mae:3072.34967
[48]	validation_0-mae:3042.04571
[49]	validation_0-mae:3016.92525
[50]	validation_0-mae:2995.92850
[51]	validation_0-mae:2970.07999
[52]	validation_0-mae:2953.24391
[53]	validation_0-mae:2933.64657
[54]	validation_0-mae:2909.75222
[55]	validation_0-mae:2892.17403
[56]	validation_0-mae:2878.95464
[57]	validation_0-mae:2861.87563
[58]	validation_0-mae:2849.68233
[59]	validation_0-mae:2831.07072
[60]	validation_0-mae:2809.13612
[61]	validation_0-mae:2797.19716
[62]	validation_0-mae:2784.26461
[63]	validation_0-mae:2769.81024
[64]	validation_0-mae:2760.90389
[65]	validation_0-mae:2743.30607
[66]	validation_0-mae:2734.89905
[67]	validation_0-mae:2725.42810
[68]	validation_0-mae:2709.60939
[69]	validation_0-mae:2700.95528
[70]	validation_0-mae:2689.50853
[71]	validation_0-mae:2681.56016
[72]	validation_0-mae:2673.69407
[73]	validation_0-mae:2665.00574
[74]	validation_0-mae:2646.18561
[75]	validation_0-mae:2633.38348
[76]	validation_0-mae:2615.03651
[77]	validation_0-mae:2611.71890
[78]	validation_0-mae:2604.02562
[79]	validation_0-mae:2594.84269
[80]	validation_0-mae:2583.61498
[81]	validation_0-mae:2578.56105
[82]	validation_0-mae:2571.16605
[83]	validation_0-mae:2561.30517
[84]	validation_0-mae:2557.72983
[85]	validation_0-mae:2547.18104
[86]	validation_0-mae:2543.33408
[87]	validation_0-mae:2537.92469
[88]	validation_0-mae:2531.50064
[89]	validation_0-mae:2522.12033
[90]	validation_0-mae:2518.83709
[91]	validation_0-mae:2512.34574
[92]	validation_0-mae:2509.43485
[93]	validation_0-mae:2502.33566
[94]	validation_0-mae:2492.53691
[95]	validation_0-mae:2487.37144
[96]	validation_0-mae:2481.85214
[97]	validation_0-mae:2476.25112
[98]	validation_0-mae:2469.27909
[99]	validation_0-mae:2465.68378
[100]	validation_0-mae:2462.24761
[101]	validation_0-mae:2458.82589
[102]	validation_0-mae:2456.85799
[103]	validation_0-mae:2448.13071
[104]	validation_0-mae:2441.38030
[105]	validation_0-mae:2439.15459
[106]	validation_0-mae:2436.61997
[107]	validation_0-mae:2433.93718
[108]	validation_0-mae:2430.40647
[109]	validation_0-mae:2425.51079
[110]	validation_0-mae:2416.57430
[111]	validation_0-mae:2412.54921
[112]	validation_0-mae:2411.18533
[113]	validation_0-mae:2408.27459
[114]	validation_0-mae:2401.17413
[115]	validation_0-mae:2398.00601
[116]	validation_0-mae:2392.97245
[117]	validation_0-mae:2390.90150
[118]	validation_0-mae:2388.45745
[119]	validation_0-mae:2388.45743
[120]	validation_0-mae:2386.11812
[121]	validation_0-mae:2384.64980
[122]	validation_0-mae:2382.03438
[123]	validation_0-mae:2378.48916
[124]	validation_0-mae:2373.99101
[125]	validation_0-mae:2371.42761
[126]	validation_0-mae:2369.95512
[127]	validation_0-mae:2366.04395
[128]	validation_0-mae:2366.10187
[129]	validation_0-mae:2364.55788
[130]	validation_0-mae:2360.52756
[131]	validation_0-mae:2357.97280
[132]	validation_0-mae:2356.54156
[133]	validation_0-mae:2356.28841
[134]	validation_0-mae:2351.23709
[135]	validation_0-mae:2348.45657
[136]	validation_0-mae:2346.58692
[137]	validation_0-mae:2339.68472
[138]	validation_0-mae:2334.65388
[139]	validation_0-mae:2334.20415
[140]	validation_0-mae:2333.30508
[141]	validation_0-mae:2332.72214
[142]	validation_0-mae:2332.73308
[143]	validation_0-mae:2331.96744
[144]	validation_0-mae:2332.18716
[145]	validation_0-mae:2329.64038
[146]	validation_0-mae:2327.14427
[147]	validation_0-mae:2325.41396
[148]	validation_0-mae:2323.36852
[149]	validation_0-mae:2322.59111
[150]	validation_0-mae:2321.82858
[151]	validation_0-mae:2317.24740
[152]	validation_0-mae:2315.32173
[153]	validation_0-mae:2312.96858
[154]	validation_0-mae:2310.53646
[155]	validation_0-mae:2309.46396
[156]	validation_0-mae:2307.84889
[157]	validation_0-mae:2306.27221
[158]	validation_0-mae:2304.29904
[159]	validation_0-mae:2301.23014
[160]	validation_0-mae:2300.29772
[161]	validation_0-mae:2298.63538
[162]	validation_0-mae:2297.07163
[163]	validation_0-mae:2296.92828
[164]	validation_0-mae:2296.88112
[165]	validation_0-mae:2293.92162
[166]	validation_0-mae:2292.87531
[167]	validation_0-mae:2289.10062
[168]	validation_0-mae:2284.01645
[169]	validation_0-mae:2279.64894
[170]	validation_0-mae:2278.39244
[171]	validation_0-mae:2278.73591
[172]	validation_0-mae:2276.85162
[173]	validation_0-mae:2276.01920
[174]	validation_0-mae:2274.47844
[175]	validation_0-mae:2274.82062
[176]	validation_0-mae:2275.13801
[177]	validation_0-mae:2272.58868
[178]	validation_0-mae:2271.97888
[179]	validation_0-mae:2270.43302
[180]	validation_0-mae:2269.56513
[0]	validation_0-mae:12421.60089
[1]	validation_0-mae:11670.28857
[2]	validation_0-mae:10997.36072
[3]	validation_0-mae:10353.00284
[4]	validation_0-mae:9796.50275
[5]	validation_0-mae:9277.91148
[6]	validation_0-mae:8815.53652
[7]	validation_0-mae:8406.58800
[8]	validation_0-mae:8020.22913
[9]	validation_0-mae:7696.60331
[10]	validation_0-mae:7372.86294
[11]	validation_0-mae:7095.66634
[12]	validation_0-mae:6810.50801
[13]	validation_0-mae:6543.05221
[14]	validation_0-mae:6280.90981
[15]	validation_0-mae:6031.64094
[16]	validation_0-mae:5815.27272
[17]	validation_0-mae:5632.42556
[18]	validation_0-mae:5445.18257
[19]	validation_0-mae:5274.32058
[20]	validation_0-mae:5087.73950
[21]	validation_0-mae:4926.46648
[22]	validation_0-mae:4773.85251
[23]	validation_0-mae:4645.56501
[24]	validation_0-mae:4516.46504
[25]	validation_0-mae:4401.15663
[26]	validation_0-mae:4291.65388
[27]	validation_0-mae:4197.00272
[28]	validation_0-mae:4099.23700
[29]	validation_0-mae:4003.71765
[30]	validation_0-mae:3920.88107
[31]	validation_0-mae:3844.97656
[32]	validation_0-mae:3776.51538
[33]	validation_0-mae:3699.97381
[34]	validation_0-mae:3631.27315
[35]	validation_0-mae:3571.01144
[36]	validation_0-mae:3507.68541
[37]	validation_0-mae:3457.75597
[38]	validation_0-mae:3407.40257
[39]	validation_0-mae:3359.01914
[40]	validation_0-mae:3312.81664
[41]	validation_0-mae:3265.31915
[42]	validation_0-mae:3220.32355
[43]	validation_0-mae:3178.77595

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[44]	validation_0-mae:3142.54363
[45]	validation_0-mae:3110.47481
[46]	validation_0-mae:3075.02947
[47]	validation_0-mae:3031.36843
[48]	validation_0-mae:3002.10506
[49]	validation_0-mae:2982.79363
[50]	validation_0-mae:2962.81378
[51]	validation_0-mae:2931.17266
[52]	validation_0-mae:2912.19915
[53]	validation_0-mae:2890.58413
[54]	validation_0-mae:2863.57039
[55]	validation_0-mae:2831.88063
[56]	validation_0-mae:2811.49395
[57]	validation_0-mae:2796.08699
[58]	validation_0-mae:2777.77872
[59]	validation_0-mae:2763.18460
[60]	validation_0-mae:2748.22934
[61]	validation_0-mae:2735.72720
[62]	validation_0-mae:2709.60068
[63]	validation_0-mae:2698.78942
[64]	validation_0-mae:2682.25433
[65]	validation_0-mae:2671.61662
[66]	validation_0-mae:2655.31096
[67]	validation_0-mae:2643.23808
[68]	validation_0-mae:2635.60600
[69]	validation_0-mae:2625.19278
[70]	validation_0-mae:2615.05660
[71]	validation_0-mae:2601.39288
[72]	validation_0-mae:2594.78010
[73]	validation_0-mae:2581.36625
[74]	validation_0-mae:2561.67128
[75]	validation_0-mae:2550.79768
[76]	validation_0-mae:2543.03075
[77]	validation_0-mae:2537.11025
[78]	validation_0-mae:2525.02598
[79]	validation_0-mae:2517.55829
[80]	validation_0-mae:2512.27363
[81]	validation_0-mae:2506.63136
[82]	validation_0-mae:2502.31453
[83]	validation_0-mae:2496.19233
[84]	validation_0-mae:2484.07407
[85]	validation_0-mae:2476.96781
[86]	validation_0-mae:2468.24666
[87]	validation_0-mae:2455.68765
[88]	validation_0-mae:2445.10771
[89]	validation_0-mae:2439.60620
[90]	validation_0-mae:2437.32973
[91]	validation_0-mae:2430.05624
[92]	validation_0-mae:2417.16319
[93]	validation_0-mae:2409.21630
[94]	validation_0-mae:2405.65574
[95]	validation_0-mae:2397.63157
[96]	validation_0-mae:2392.27300
[97]	validation_0-mae:2387.90748
[98]	validation_0-mae:2380.07733
[99]	validation_0-mae:2374.72431
[100]	validation_0-mae:2368.38370
[101]	validation_0-mae:2361.54898
[102]	validation_0-mae:2358.40558
[103]	validation_0-mae:2351.84206
[104]	validation_0-mae:2344.85535
[105]	validation_0-mae:2339.04796
[106]	validation_0-mae:2329.99819
[107]	validation_0-mae:2324.45141
[108]	validation_0-mae:2321.69320
[109]	validation_0-mae:2318.16996
[110]	validation_0-mae:2316.21530
[111]	validation_0-mae:2313.26095
[112]	validation_0-mae:2311.63211
[113]	validation_0-mae:2307.82599
[114]	validation_0-mae:2302.97753
[115]	validation_0-mae:2296.21495
[116]	validation_0-mae:2293.58396
[117]	validation_0-mae:2292.19243
[118]	validation_0-mae:2286.74496
[119]	validation_0-mae:2282.75087
[120]	validation_0-mae:2282.80501
[121]	validation_0-mae:2281.85109
[122]	validation_0-mae:2276.91295
[123]	validation_0-mae:2271.92453
[124]	validation_0-mae:2269.07239
[125]	validation_0-mae:2265.58312
[126]	validation_0-mae:2260.84564
[127]	validation_0-mae:2260.49373
[128]	validation_0-mae:2259.35942
[129]	validation_0-mae:2255.47155
[130]	validation_0-mae:2255.10663
[131]	validation_0-mae:2253.39837
[132]	validation_0-mae:2253.02787
[133]	validation_0-mae:2250.96974
[134]	validation_0-mae:2246.12813
[135]	validation_0-mae:2245.31549
[136]	validation_0-mae:2245.36571
[137]	validation_0-mae:2240.76100
[138]	validation_0-mae:2238.29153
[139]	validation_0-mae:2236.42390
[140]	validation_0-mae:2233.89795
[141]	validation_0-mae:2232.74720
[142]	validation_0-mae:2232.34599
[143]	validation_0-mae:2229.49607
[144]	validation_0-mae:2225.67067
[145]	validation_0-mae:2225.71252
[146]	validation_0-mae:2222.69832
[147]	validation_0-mae:2222.51261
[148]	validation_0-mae:2219.40578
[149]	validation_0-mae:2214.97251
[150]	validation_0-mae:2213.64919
[151]	validation_0-mae:2212.52039
[152]	validation_0-mae:2211.07809
[153]	validation_0-mae:2207.71215
[154]	validation_0-mae:2206.72224
[155]	validation_0-mae:2206.57042
[156]	validation_0-mae:2204.81570
[157]	validation_0-mae:2203.85684
[158]	validation_0-mae:2202.36555
[159]	validation_0-mae:2200.48860
[160]	validation_0-mae:2198.76196
[161]	validation_0-mae:2198.87560
[162]	validation_0-mae:2195.87145
[163]	validation_0-mae:2195.30329
[164]	validation_0-mae:2194.97528
[165]	validation_0-mae:2190.68069
[166]	validation_0-mae:2190.01118
[167]	validation_0-mae:2189.02952
[168]	validation_0-mae:2190.21805
[169]	validation_0-mae:2189.44490
[170]	validation_0-mae:2188.58455
[171]	validation_0-mae:2185.71285
[172]	validation_0-mae:2186.14452
[173]	validation_0-mae:2184.66740
[174]	validation_0-mae:2184.37452
[175]	validation_0-mae:2183.51420
[176]	validation_0-mae:2181.72727
[177]	validation_0-mae:2181.21769
[178]	validation_0-mae:2180.51541
[179]	validation_0-mae:2178.87322
[180]	validation_0-mae:2178.12561
[181]	validation_0-mae:2176.68052
[182]	validation_0-mae:2177.17376
[183]	validation_0-mae:2176.43479
[184]	validation_0-mae:2176.29906
[185]	validation_0-mae:2175.71074
[186]	validation_0-mae:2174.93688
[187]	validation_0-mae:2174.89516
[188]	validation_0-mae:2173.60557
[189]	validation_0-mae:2172.89196
[190]	validation_0-mae:2170.64316
[191]	validation_0-mae:2171.51338
[192]	validation_0-mae:2169.27474
[193]	validation_0-mae:2169.29877
[194]	validation_0-mae:2165.78810
[195]	validation_0-mae:2162.10940
[196]	validation_0-mae:2160.88617
[197]	validation_0-mae:2160.40254
[198]	validation_0-mae:2158.19735
[199]	validation_0-mae:2156.77884
[200]	validation_0-mae:2155.85338
[201]	validation_0-mae:2154.29575
[202]	validation_0-mae:2152.37689
[203]	validation_0-mae:2149.09673
[204]	validation_0-mae:2147.57557
[205]	validation_0-mae:2146.86595
[206]	validation_0-mae:2145.56097
[207]	validation_0-mae:2142.88868
[208]	validation_0-mae:2143.81461
[209]	validation_0-mae:2143.34252
[210]	validation_0-mae:2142.97976
[211]	validation_0-mae:2143.88774
[212]	validation_0-mae:2143.63984
[213]	validation_0-mae:2143.63533
[214]	validation_0-mae:2143.42195
[215]	validation_0-mae:2142.96487
[216]	validation_0-mae:2142.21572
[217]	validation_0-mae:2140.98104
[218]	validation_0-mae:2138.98007
[219]	validation_0-mae:2137.12217
[220]	validation_0-mae:2135.80043
[221]	validation_0-mae:2135.32902
[222]	validation_0-mae:2132.94765
[223]	validation_0-mae:2132.30164
[224]	validation_0-mae:2132.76178
[225]	validation_0-mae:2133.05208
[226]	validation_0-mae:2133.38923
[227]	validation_0-mae:2133.09426
[228]	validation_0-mae:2131.91664
[229]	validation_0-mae:2131.90842
[230]	validation_0-mae:2131.82284
[231]	validation_0-mae:2130.11880
[232]	validation_0-mae:2127.07839
[233]	validation_0-mae:2126.44893
[234]	validation_0-mae:2125.05781
[235]	validation_0-mae:2125.01589
[236]	validation_0-mae:2124.70319
[237]	validation_0-mae:2123.83057
[238]	validation_0-mae:2122.88266
[239]	validation_0-mae:2122.95200
[240]	validation_0-mae:2121.68563
[241]	validation_0-mae:2121.63112
[242]	validation_0-mae:2121.48561
[243]	validation_0-mae:2120.90274
[244]	validation_0-mae:2121.04210
[245]	validation_0-mae:2121.13618
[246]	validation_0-mae:2121.56643
[247]	validation_0-mae:2120.87150
[248]	validation_0-mae:2120.60218
[249]	validation_0-mae:2120.95555
[250]	validation_0-mae:2121.56867
[251]	validation_0-mae:2121.78508
[252]	validation_0-mae:2122.00788
[253]	validation_0-mae:2121.69293
[254]	validation_0-mae:2121.40127
[255]	validation_0-mae:2121.63477
[256]	validation_0-mae:2120.84127
[257]	validation_0-mae:2120.17007
[258]	validation_0-mae:2120.02543
[259]	validation_0-mae:2120.53915
[260]	validation_0-mae:2118.40132
[261]	validation_0-mae:2117.73356
[262]	validation_0-mae:2117.74175
[263]	validation_0-mae:2116.36103
[264]	validation_0-mae:2116.09562
[265]	validation_0-mae:2116.01117
[266]	validation_0-mae:2116.17984
[267]	validation_0-mae:2115.73403
[268]	validation_0-mae:2115.69618
[269]	validation_0-mae:2116.24919
[270]	validation_0-mae:2116.50002
[271]	validation_0-mae:2114.70594
[272]	validation_0-mae:2114.47771
[273]	validation_0-mae:2114.93629
[274]	validation_0-mae:2114.27773
[275]	validation_0-mae:2115.09744
[276]	validation_0-mae:2114.57846
[277]	validation_0-mae:2114.42549
[278]	validation_0-mae:2114.50914
[279]	validation_0-mae:2114.05855
[280]	validation_0-mae:2114.41716
[281]	validation_0-mae:2114.09599
[282]	validation_0-mae:2114.20594
[283]	validation_0-mae:2114.05081
[284]	validation_0-mae:2113.90690
[285]	validation_0-mae:2112.74669
[286]	validation_0-mae:2112.63617
[287]	validation_0-mae:2112.49797
[288]	validation_0-mae:2112.54039
[289]	validation_0-mae:2113.10328
[290]	validation_0-mae:2113.44925
[291]	validation_0-mae:2112.53647
[292]	validation_0-mae:2112.39363
[293]	validation_0-mae:2111.92845
[294]	validation_0-mae:2109.70593
[295]	validation_0-mae:2109.44180
[296]	validation_0-mae:2109.10858
[297]	validation_0-mae:2107.93075
[298]	validation_0-mae:2107.96894
[299]	validation_0-mae:2105.57917
[300]	validation_0-mae:2105.02757
[301]	validation_0-mae:2104.71059
[302]	validation_0-mae:2103.23535
[303]	validation_0-mae:2102.97009
[304]	validation_0-mae:2103.20733
[305]	validation_0-mae:2102.87710
[306]	validation_0-mae:2101.39574
[307]	validation_0-mae:2100.90805
[308]	validation_0-mae:2101.30203
[309]	validation_0-mae:2101.59513
[310]	validation_0-mae:2101.69004
[311]	validation_0-mae:2101.92682
[312]	validation_0-mae:2101.30885
[313]	validation_0-mae:2100.10033
[314]	validation_0-mae:2099.96780
[315]	validation_0-mae:2099.20204
[316]	validation_0-mae:2098.98269
[317]	validation_0-mae:2099.02282
[318]	validation_0-mae:2098.80240
[319]	validation_0-mae:2099.40218
[320]	validation_0-mae:2100.16633
[321]	validation_0-mae:2100.27454
[322]	validation_0-mae:2099.32788
[323]	validation_0-mae:2099.05524
[324]	validation_0-mae:2098.48125
[325]	validation_0-mae:2098.33430
[326]	validation_0-mae:2097.82459
[327]	validation_0-mae:2097.77695
[328]	validation_0-mae:2097.74933
[329]	validation_0-mae:2097.42330
[330]	validation_0-mae:2096.76798
[331]	validation_0-mae:2096.03772
[332]	validation_0-mae:2095.62168
[333]	validation_0-mae:2094.92583
[334]	validation_0-mae:2095.00149
[335]	validation_0-mae:2094.44321
[336]	validation_0-mae:2094.73044
[337]	validation_0-mae:2095.10225
[338]	validation_0-mae:2095.09523
[339]	validation_0-mae:2095.57658
[340]	validation_0-mae:2095.37626
[341]	validation_0-mae:2095.09361
[342]	validation_0-mae:2095.37325
[343]	validation_0-mae:2095.51569
[344]	validation_0-mae:2095.51557
[345]	validation_0-mae:2095.59860
[346]	validation_0-mae:2095.38126
[347]	validation_0-mae:2095.61012
[348]	validation_0-mae:2095.07261
[349]	validation_0-mae:2095.21938
[350]	validation_0-mae:2093.95405
[351]	validation_0-mae:2092.37276
[352]	validation_0-mae:2090.85631
[353]	validation_0-mae:2089.86035
[354]	validation_0-mae:2090.72162
[355]	validation_0-mae:2090.16168
[356]	validation_0-mae:2089.28378
[357]	validation_0-mae:2088.12886
[358]	validation_0-mae:2087.98025
[359]	validation_0-mae:2087.65166
[360]	validation_0-mae:2086.55940
[361]	validation_0-mae:2086.60452
[362]	validation_0-mae:2086.65389
[363]	validation_0-mae:2085.94958
[364]	validation_0-mae:2084.26610
[365]	validation_0-mae:2082.86955
[366]	validation_0-mae:2082.35246
[367]	validation_0-mae:2082.66047
[368]	validation_0-mae:2082.42066
[369]	validation_0-mae:2080.96256
[370]	validation_0-mae:2081.27479
[371]	validation_0-mae:2081.39440
[372]	validation_0-mae:2081.41121
[373]	validation_0-mae:2082.13003
[374]	validation_0-mae:2081.61745
[375]	validation_0-mae:2081.94584
[376]	validation_0-mae:2082.22914
[377]	validation_0-mae:2080.78279
[378]	validation_0-mae:2079.77168
[379]	validation_0-mae:2079.74934
[380]	validation_0-mae:2079.41553
[381]	validation_0-mae:2079.14454
[382]	validation_0-mae:2079.38018
[383]	validation_0-mae:2079.61632
[384]	validation_0-mae:2078.59097
[385]	validation_0-mae:2078.39239
[386]	validation_0-mae:2078.67268
[387]	validation_0-mae:2079.12622
[388]	validation_0-mae:2078.74133
[389]	validation_0-mae:2079.19146
[390]	validation_0-mae:2079.39509
[391]	validation_0-mae:2079.61550
[392]	validation_0-mae:2079.47583
[393]	validation_0-mae:2078.87893
[394]	validation_0-mae:2078.64079
[395]	validation_0-mae:2078.64381
[396]	validation_0-mae:2078.46399
[397]	validation_0-mae:2078.02340
[398]	validation_0-mae:2078.06859
[399]	validation_0-mae:2077.52387
[400]	validation_0-mae:2077.37794
[401]	validation_0-mae:2075.30124
[402]	validation_0-mae:2074.76360
[403]	validation_0-mae:2074.49166
[404]	validation_0-mae:2074.14506
[405]	validation_0-mae:2074.42238
[406]	validation_0-mae:2074.34113
[407]	validation_0-mae:2074.31733
[408]	validation_0-mae:2074.62729
[409]	validation_0-mae:2074.92465
[410]	validation_0-mae:2074.94139
[411]	validation_0-mae:2074.67859
[412]	validation_0-mae:2074.73152
[413]	validation_0-mae:2074.90434
[414]	validation_0-mae:2075.12667
[415]	validation_0-mae:2074.59444
[416]	validation_0-mae:2074.20791
[417]	validation_0-mae:2074.66911
[418]	validation_0-mae:2074.92664
[419]	validation_0-mae:2074.87513
[420]	validation_0-mae:2074.78428
[421]	validation_0-mae:2074.55315
[422]	validation_0-mae:2074.60160
[423]	validation_0-mae:2074.60044
[424]	validation_0-mae:2074.59666
[425]	validation_0-mae:2074.44972
[426]	validation_0-mae:2072.69491
[427]	validation_0-mae:2072.57147
[428]	validation_0-mae:2072.57338
[429]	validation_0-mae:2072.83462
[430]	validation_0-mae:2072.07250
[431]	validation_0-mae:2072.08851
[432]	validation_0-mae:2071.71369
[433]	validation_0-mae:2071.75259
[434]	validation_0-mae:2071.99076
[435]	validation_0-mae:2072.11659
[436]	validation_0-mae:2072.86202
[437]	validation_0-mae:2073.65566
[438]	validation_0-mae:2073.38829
[439]	validation_0-mae:2073.61215
[440]	validation_0-mae:2073.12140
[441]	validation_0-mae:2073.26623
[442]	validation_0-mae:2072.30103
[443]	validation_0-mae:2072.32169
[444]	validation_0-mae:2072.33919
[445]	validation_0-mae:2071.84366
[446]	validation_0-mae:2072.15764
[447]	validation_0-mae:2071.80566
[448]	validation_0-mae:2071.73515
[449]	validation_0-mae:2071.66104
[450]	validation_0-mae:2071.67495
[451]	validation_0-mae:2071.80929
[452]	validation_0-mae:2071.88799
[453]	validation_0-mae:2072.11973
[454]	validation_0-mae:2072.33887
[455]	validation_0-mae:2072.28467
[456]	validation_0-mae:2072.21724
[457]	validation_0-mae:2071.75830
[458]	validation_0-mae:2071.80920
[459]	validation_0-mae:2071.56002
[460]	validation_0-mae:2071.76979
[461]	validation_0-mae:2071.12643
[462]	validation_0-mae:2071.08845
[463]	validation_0-mae:2071.35806
[464]	validation_0-mae:2070.78675
[465]	validation_0-mae:2070.70357
[466]	validation_0-mae:2070.02392
[467]	validation_0-mae:2069.19363
[468]	validation_0-mae:2068.92964
[469]	validation_0-mae:2068.01420
[470]	validation_0-mae:2068.25756
[471]	validation_0-mae:2067.76774
[472]	validation_0-mae:2067.90503
[473]	validation_0-mae:2067.74243
[474]	validation_0-mae:2067.48950
[475]	validation_0-mae:2067.00762
[476]	validation_0-mae:2067.09738
[477]	validation_0-mae:2067.01637
[478]	validation_0-mae:2067.12165
[479]	validation_0-mae:2067.20298
[480]	validation_0-mae:2066.65240
[481]	validation_0-mae:2066.15172
[482]	validation_0-mae:2065.27388
[483]	validation_0-mae:2063.39372
[484]	validation_0-mae:2062.95681
[485]	validation_0-mae:2062.89906
[486]	validation_0-mae:2062.53117
[487]	validation_0-mae:2061.41241
[488]	validation_0-mae:2061.14539
[489]	validation_0-mae:2061.48755
[490]	validation_0-mae:2061.33070
[491]	validation_0-mae:2061.18401
[492]	validation_0-mae:2060.92101
[493]	validation_0-mae:2060.90672
[494]	validation_0-mae:2060.89517
[495]	validation_0-mae:2060.76482
[496]	validation_0-mae:2060.43782
[497]	validation_0-mae:2059.92539
[498]	validation_0-mae:2060.17471
[499]	validation_0-mae:2060.74762
[500]	validation_0-mae:2060.81396
[501]	validation_0-mae:2060.86355
[502]	validation_0-mae:2061.07379
[503]	validation_0-mae:2061.02197
[504]	validation_0-mae:2061.16471
[505]	validation_0-mae:2061.31641
[506]	validation_0-mae:2061.12358
[507]	validation_0-mae:2061.22732
[508]	validation_0-mae:2061.11396
[509]	validation_0-mae:2060.94607
[510]	validation_0-mae:2060.91816
[511]	validation_0-mae:2060.93787
[512]	validation_0-mae:2060.92343
[513]	validation_0-mae:2060.99676
[514]	validation_0-mae:2060.90437
[515]	validation_0-mae:2060.69740
[516]	validation_0-mae:2060.65154
[517]	validation_0-mae:2060.45436
[518]	validation_0-mae:2060.29199
[519]	validation_0-mae:2060.76864
[520]	validation_0-mae:2060.74750
[521]	validation_0-mae:2060.82437
[522]	validation_0-mae:2060.95747
[523]	validation_0-mae:2060.91834
[524]	validation_0-mae:2061.04917
[525]	validation_0-mae:2060.69943
[526]	validation_0-mae:2060.40100
[527]	validation_0-mae:2060.36078
[528]	validation_0-mae:2059.50806
[529]	validation_0-mae:2059.02993
[530]	validation_0-mae:2058.53292
[531]	validation_0-mae:2058.26717
[532]	validation_0-mae:2058.16565
[533]	validation_0-mae:2058.32007
[534]	validation_0-mae:2058.44213
[535]	validation_0-mae:2058.55818
[536]	validation_0-mae:2058.61473
[537]	validation_0-mae:2059.11495
[538]	validation_0-mae:2059.10503
[539]	validation_0-mae:2059.32360
[540]	validation_0-mae:2059.33695
[541]	validation_0-mae:2058.92870
[542]	validation_0-mae:2059.04732
[543]	validation_0-mae:2058.69133
[544]	validation_0-mae:2058.41844
[545]	validation_0-mae:2058.64064
[546]	validation_0-mae:2058.51435
[547]	validation_0-mae:2058.70387
[548]	validation_0-mae:2058.24886
[549]	validation_0-mae:2058.54097
[550]	validation_0-mae:2058.61937
[551]	validation_0-mae:2058.38336
[552]	validation_0-mae:2058.66294
[553]	validation_0-mae:2058.75667
[554]	validation_0-mae:2058.82945
[555]	validation_0-mae:2058.92320
[556]	validation_0-mae:2059.06750
[557]	validation_0-mae:2058.99821
[558]	validation_0-mae:2059.12932
[559]	validation_0-mae:2059.03259
[560]	validation_0-mae:2059.15868
[561]	validation_0-mae:2059.30101
[562]	validation_0-mae:2059.42034
[563]	validation_0-mae:2059.61418
[564]	validation_0-mae:2058.98724
[565]	validation_0-mae:2059.11198
[566]	validation_0-mae:2058.73061
[567]	validation_0-mae:2058.87879
[568]	validation_0-mae:2058.04090
[569]	validation_0-mae:2058.29766
[570]	validation_0-mae:2058.35040
[571]	validation_0-mae:2058.70064
[572]	validation_0-mae:2058.98721
[573]	validation_0-mae:2059.25381
[574]	validation_0-mae:2058.88440
[575]	validation_0-mae:2058.86571
[576]	validation_0-mae:2058.46544
[577]	validation_0-mae:2058.76859
[578]	validation_0-mae:2058.75294
[579]	validation_0-mae:2059.20128
[580]	validation_0-mae:2059.24326
[581]	validation_0-mae:2059.10455
[582]	validation_0-mae:2059.34380
[583]	validation_0-mae:2059.12460
[584]	validation_0-mae:2059.17545
[585]	validation_0-mae:2059.08612
[586]	validation_0-mae:2059.02611
[587]	validation_0-mae:2058.58635
[588]	validation_0-mae:2058.68708
[589]	validation_0-mae:2058.52736
[590]	validation_0-mae:2058.19837
[591]	validation_0-mae:2058.22706
[592]	validation_0-mae:2058.12415
[593]	validation_0-mae:2057.85243
[594]	validation_0-mae:2057.73884
[595]	validation_0-mae:2057.59406
[596]	validation_0-mae:2057.81692
[597]	validation_0-mae:2058.10872
[598]	validation_0-mae:2058.18251
[599]	validation_0-mae:2058.27069
[600]	validation_0-mae:2058.20800
[601]	validation_0-mae:2057.60010
[602]	validation_0-mae:2057.40721
[603]	validation_0-mae:2057.30251
[604]	validation_0-mae:2057.54958
[605]	validation_0-mae:2057.73148
[606]	validation_0-mae:2057.99840
[607]	validation_0-mae:2058.12070
[608]	validation_0-mae:2057.70740
[609]	validation_0-mae:2057.83080
[610]	validation_0-mae:2057.69138
[611]	validation_0-mae:2058.44128
[612]	validation_0-mae:2059.13955
[613]	validation_0-mae:2058.90571
[614]	validation_0-mae:2059.40979
[615]	validation_0-mae:2059.58085
[616]	validation_0-mae:2059.49268
[617]	validation_0-mae:2059.54028
[618]	validation_0-mae:2059.53769
[619]	validation_0-mae:2059.47055
[620]	validation_0-mae:2059.35276
[621]	validation_0-mae:2059.67780
[622]	validation_0-mae:2059.70871
[623]	validation_0-mae:2059.67384
[624]	validation_0-mae:2059.65405
[625]	validation_0-mae:2059.81985
[626]	validation_0-mae:2059.58295
[627]	validation_0-mae:2059.07929
[628]	validation_0-mae:2059.04321
[629]	validation_0-mae:2058.33828
[630]	validation_0-mae:2058.33079
[631]	validation_0-mae:2057.97373
[632]	validation_0-mae:2058.11484

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[38]	validation_0-mae:3257.04801
[39]	validation_0-mae:3219.25190
[40]	validation_0-mae:3177.90354
[41]	validation_0-mae:3138.28076
[42]	validation_0-mae:3107.88322
[43]	validation_0-mae:3076.11520
[44]	validation_0-mae:3048.62917
[45]	validation_0-mae:3021.31947
[46]	validation_0-mae:2979.85180
[47]	validation_0-mae:2952.07653
[48]	validation_0-mae:2928.47825
[49]	validation_0-mae:2882.55763
[50]	validation_0-mae:2859.53557
[51]	validation_0-mae:2840.76110
[52]	validation_0-mae:2809.13137
[53]	validation_0-mae:2783.33378
[54]	validation_0-mae:2767.98740
[55]	validation_0-mae:2748.75687
[56]	validation_0-mae:2729.98897
[57]	validation_0-mae:2714.49711
[58]	validation_0-mae:2686.38322
[59]	validation_0-mae:2668.30795
[60]	validation_0-mae:2657.66538
[61]	validation_0-mae:2651.12137
[62]	validation_0-mae:2636.02745
[63]	validation_0-mae:2611.58631
[64]	validation_0-mae:2599.36627
[65]	validation_0-mae:2588.95108
[66]	validation_0-mae:2573.78645
[67]	validation_0-mae:2563.42770
[68]	validation_0-mae:2552.89039
[69]	validation_0-mae:2542.01916
[70]	validation_0-mae:2524.32471
[71]	validation_0-mae:2516.95399
[72]	validation_0-mae:2502.28502
[73]	validation_0-mae:2489.88492
[74]	validation_0-mae:2485.71775
[75]	validation_0-mae:2476.31607
[76]	validation_0-mae:2468.62026
[77]	validation_0-mae:2462.37218
[78]	validation_0-mae:2455.54413
[79]	validation_0-mae:2451.41409
[80]	validation_0-mae:2441.71323
[81]	validation_0-mae:2436.40697
[82]	validation_0-mae:2428.61829
[83]	validation_0-mae:2422.78431
[84]	validation_0-mae:2419.49257
[85]	validation_0-mae:2413.88281
[86]	validation_0-mae:2408.32431
[87]	validation_0-mae:2402.97431
[88]	validation_0-mae:2396.50249
[89]	validation_0-mae:2393.46185
[90]	validation_0-mae:2383.94242
[91]	validation_0-mae:2377.64026
[92]	validation_0-mae:2373.14081
[93]	validation_0-mae:2369.91183
[94]	validation_0-mae:2365.23161
[95]	validation_0-mae:2363.97205
[96]	validation_0-mae:2355.30111
[97]	validation_0-mae:2349.78850
[98]	validation_0-mae:2348.14630
[99]	validation_0-mae:2342.88202
[100]	validation_0-mae:2341.04623
[101]	validation_0-mae:2335.07054
[102]	validation_0-mae:2327.50030
[103]	validation_0-mae:2325.28157
[104]	validation_0-mae:2320.34271
[105]	validation_0-mae:2317.99604
[106]	validation_0-mae:2313.72205
[107]	validation_0-mae:2311.15153
[108]	validation_0-mae:2308.86779
[109]	validation_0-mae:2305.15286
[110]	validation_0-mae:2302.64233
[111]	validation_0-mae:2299.10465
[112]	validation_0-mae:2293.37251
[113]	validation_0-mae:2292.16363
[114]	validation_0-mae:2291.18969
[115]	validation_0-mae:2286.85187
[116]	validation_0-mae:2285.53104
[117]	validation_0-mae:2283.69390
[118]	validation_0-mae:2281.98279
[119]	validation_0-mae:2281.18393
[120]	validation_0-mae:2279.00233
[121]	validation_0-mae:2278.58748
[122]	validation_0-mae:2278.44633
[123]	validation_0-mae:2276.82819
[124]	validation_0-mae:2275.10865
[125]	validation_0-mae:2273.89233
[126]	validation_0-mae:2271.83975
[127]	validation_0-mae:2264.91580
[128]	validation_0-mae:2265.26292
[129]	validation_0-mae:2264.81551
[130]	validation_0-mae:2263.22295
[131]	validation_0-mae:2261.48999
[132]	validation_0-mae:2260.56970
[133]	validation_0-mae:2256.77560
[134]	validation_0-mae:2255.90323
[135]	validation_0-mae:2255.47012
[136]	validation_0-mae:2252.17597
[137]	validation_0-mae:2252.13753
[138]	validation_0-mae:2252.54970
[139]	validation_0-mae:2251.90874
[140]	validation_0-mae:2249.68046
[141]	validation_0-mae:2249.40508
[142]	validation_0-mae:2248.20586
[143]	validation_0-mae:2248.11789
[144]	validation_0-mae:2246.58921
[145]	validation_0-mae:2243.22930
[146]	validation_0-mae:2241.57898
[147]	validation_0-mae:2239.52418
[148]	validation_0-mae:2238.86663
[149]	validation_0-mae:2237.65419
[150]	validation_0-mae:2236.19636
[151]	validation_0-mae:2232.11004
[152]	validation_0-mae:2229.90203
[153]	validation_0-mae:2229.55592
[154]	validation_0-mae:2229.88051
[155]	validation_0-mae:2229.20668
[156]	validation_0-mae:2228.55270
[157]	validation_0-mae:2227.84418
[158]	validation_0-mae:2227.93202
[159]	validation_0-mae:2227.56694
[160]	validation_0-mae:2226.42993
[161]	validation_0-mae:2223.08087
[162]	validation_0-mae:2222.53725
[163]	validation_0-mae:2222.20472
[164]	validation_0-mae:2221.88871
[165]	validation_0-mae:2222.41778
[166]	validation_0-mae:2221.35797
[167]	validation_0-mae:2221.49485
[168]	validation_0-mae:2220.64063
[169]	validation_0-mae:2221.50245
[170]	validation_0-mae:2222.33723
[171]	validation_0-mae:2220.20393
[172]	validation_0-mae:2220.81707
[173]	validation_0-mae:2221.30759
[174]	validation_0-mae:2220.12100
[175]	validation_0-mae:2220.73537
[176]	validation_0-mae:2220.64518
[177]	validation_0-mae:2220.11235
[178]	validation_0-mae:2216.13699
[179]	validation_0-mae:2213.32034
[180]	validation_0-mae:2211.57805
[181]	validation_0-mae:2211.50136
[182]	validation_0-mae:2210.77713
[183]	validation_0-mae:2211.28827
[184]	validation_0-mae:2212.00495
[185]	validation_0-mae:2211.94234
[186]	validation_0-mae:2211.58188
[187]	validation_0-mae:2212.31890
[188]	validation_0-mae:2211.04223
[189]	validation_0-mae:2210.56999
[190]	validation_0-mae:2208.58902
[191]	validation_0-mae:2206.97382
[192]	validation_0-mae:2206.21866
[193]	validation_0-mae:2206.80043
[194]	validation_0-mae:2204.62705
[195]	validation_0-mae:2202.29382
[196]	validation_0-mae:2202.15311
[197]	validation_0-mae:2203.03140
[198]	validation_0-mae:2200.26311
[199]	validation_0-mae:2201.03239
[200]	validation_0-mae:2199.58488
[201]	validation_0-mae:2198.48173
[202]	validation_0-mae:2199.01327
[203]	validation_0-mae:2199.00915
[204]	validation_0-mae:2198.88884
[205]	validation_0-mae:2197.54765
[206]	validation_0-mae:2198.13351
[207]	validation_0-mae:2198.17715
[208]	validation_0-mae:2198.21362
[209]	validation_0-mae:2198.12341
[210]	validation_0-mae:2196.85254
[211]	validation_0-mae:2196.70497
[212]	validation_0-mae:2196.16084
[213]	validation_0-mae:2195.68485
[214]	validation_0-mae:2194.11018
[215]	validation_0-mae:2194.74438
[216]	validation_0-mae:2194.82961
[217]	validation_0-mae:2194.25924
[218]	validation_0-mae:2192.42339
[219]	validation_0-mae:2191.48738
[220]	validation_0-mae:2190.35024
[221]	validation_0-mae:2190.18543
[222]	validation_0-mae:2190.46744
[223]	validation_0-mae:2189.37299
[224]	validation_0-mae:2188.72915
[225]	validation_0-mae:2187.49443
[226]	validation_0-mae:2187.09688
[227]	validation_0-mae:2186.25963
[228]	validation_0-mae:2185.39455
[229]	validation_0-mae:2185.18104
[230]	validation_0-mae:2183.69337
[231]	validation_0-mae:2182.51866
[232]	validation_0-mae:2180.51469
[233]	validation_0-mae:2180.94074
[234]	validation_0-mae:2178.74439
[235]	validation_0-mae:2178.70013
[236]	validation_0-mae:2177.95102
[237]	validation_0-mae:2178.02403
[238]	validation_0-mae:2177.60713
[239]	validation_0-mae:2175.71301
[240]	validation_0-mae:2175.20185
[241]	validation_0-mae:2172.52728
[242]	validation_0-mae:2171.92274
[243]	validation_0-mae:2170.41680
[244]	validation_0-mae:2169.95610
[245]	validation_0-mae:2170.14488
[246]	validation_0-mae:2170.38833
[247]	validation_0-mae:2170.02470
[248]	validation_0-mae:2167.53803
[249]	validation_0-mae:2167.27077
[250]	validation_0-mae:2167.76242
[251]	validation_0-mae:2167.69882
[252]	validation_0-mae:2167.97002
[253]	validation_0-mae:2167.75585
[254]	validation_0-mae:2168.44137
[255]	validation_0-mae:2168.38831
[256]	validation_0-mae:2167.89576
[257]	validation_0-mae:2168.50455
[258]	validation_0-mae:2169.62597
[259]	validation_0-mae:2169.05514
[260]	validation_0-mae:2168.56336
[261]	validation_0-mae:2168.12696
[262]	validation_0-mae:2168.37862
[263]	validation_0-mae:2168.18600
[264]	validation_0-mae:2167.57133
[265]	validation_0-mae:2167.75705
[266]	validation_0-mae:2167.50031
[267]	validation_0-mae:2165.59467
[268]	validation_0-mae:2164.41162
[269]	validation_0-mae:2164.15430
[270]	validation_0-mae:2163.02585
[271]	validation_0-mae:2162.64589
[272]	validation_0-mae:2162.48909
[273]	validation_0-mae:2160.14395
[274]	validation_0-mae:2158.87268
[275]	validation_0-mae:2159.38976
[276]	validation_0-mae:2159.99717
[277]	validation_0-mae:2160.73336
[278]	validation_0-mae:2160.59875
[279]	validation_0-mae:2158.92960
[280]	validation_0-mae:2159.36846
[281]	validation_0-mae:2159.49641
[282]	validation_0-mae:2159.38502
[283]	validation_0-mae:2159.70462
[284]	validation_0-mae:2159.25918
[285]	validation_0-mae:2159.40497
[286]	validation_0-mae:2158.99720
[287]	validation_0-mae:2158.62057
[288]	validation_0-mae:2158.79395
[289]	validation_0-mae:2158.85649
[290]	validation_0-mae:2158.94065
[291]	validation_0-mae:2158.78900
[292]	validation_0-mae:2159.43685
[293]	validation_0-mae:2158.64828
[294]	validation_0-mae:2158.42830
[295]	validation_0-mae:2158.74359
[296]	validation_0-mae:2158.36156
[297]	validation_0-mae:2157.60363
[298]	validation_0-mae:2157.94342
[299]	validation_0-mae:2158.91409
[300]	validation_0-mae:2158.79351
[301]	validation_0-mae:2159.53304
[302]	validation_0-mae:2159.73164
[303]	validation_0-mae:2158.43671
[304]	validation_0-mae:2156.60436
[305]	validation_0-mae:2156.57857
[306]	validation_0-mae:2156.11264
[307]	validation_0-mae:2155.03622
[308]	validation_0-mae:2154.12638
[309]	validation_0-mae:2154.37764
[310]	validation_0-mae:2153.83367
[311]	validation_0-mae:2154.72081
[312]	validation_0-mae:2154.39949
[313]	validation_0-mae:2154.44274
[314]	validation_0-mae:2153.10963
[315]	validation_0-mae:2153.20094
[316]	validation_0-mae:2153.22130
[317]	validation_0-mae:2153.68294
[318]	validation_0-mae:2152.15567
[319]	validation_0-mae:2151.95734
[320]	validation_0-mae:2152.40057
[321]	validation_0-mae:2152.36377
[322]	validation_0-mae:2152.92293
[323]	validation_0-mae:2152.11803
[324]	validation_0-mae:2152.30601
[325]	validation_0-mae:2152.47849
[326]	validation_0-mae:2152.73646
[327]	validation_0-mae:2150.49244
[328]	validation_0-mae:2149.39113
[329]	validation_0-mae:2148.32481
[330]	validation_0-mae:2147.72271
[331]	validation_0-mae:2146.26941
[332]	validation_0-mae:2146.02870
[333]	validation_0-mae:2144.67002
[334]	validation_0-mae:2144.50698
[335]	validation_0-mae:2144.09253
[336]	validation_0-mae:2142.83498
[337]	validation_0-mae:2142.81227
[338]	validation_0-mae:2142.24086
[339]	validation_0-mae:2141.96413
[340]	validation_0-mae:2142.40788
[341]	validation_0-mae:2141.43987
[342]	validation_0-mae:2140.93954
[343]	validation_0-mae:2141.13073
[344]	validation_0-mae:2141.21742
[345]	validation_0-mae:2141.54180
[346]	validation_0-mae:2140.24170
[347]	validation_0-mae:2139.75561
[348]	validation_0-mae:2137.93317
[349]	validation_0-mae:2137.10376
[350]	validation_0-mae:2136.57355
[351]	validation_0-mae:2136.01365
[352]	validation_0-mae:2136.46809
[353]	validation_0-mae:2136.85808
[354]	validation_0-mae:2137.36900
[355]	validation_0-mae:2138.21386
[356]	validation_0-mae:2137.77714
[357]	validation_0-mae:2138.03273
[358]	validation_0-mae:2137.67452
[359]	validation_0-mae:2138.07931
[360]	validation_0-mae:2138.46070
[361]	validation_0-mae:2138.44055
[362]	validation_0-mae:2138.86635
[363]	validation_0-mae:2138.72187
[364]	validation_0-mae:2139.16767
[365]	validation_0-mae:2139.24873
[366]	validation_0-mae:2139.27659
[367]	validation_0-mae:2139.93581
[368]	validation_0-mae:2140.29412
[369]	validation_0-mae:2139.41853
[370]	validation_0-mae:2138.59896
[371]	validation_0-mae:2137.84822
[372]	validation_0-mae:2137.35345
[373]	validation_0-mae:2137.67925
[374]	validation_0-mae:2137.49799
[375]	validation_0-mae:2136.98919
[376]	validation_0-mae:2137.61982
[377]	validation_0-mae:2136.81397
[378]	validation_0-mae:2137.03077
[379]	validation_0-mae:2137.07563
[380]	validation_0-mae:2137.00498
[381]	validation_0-mae:2136.21830
[382]	validation_0-mae:2136.11999
[383]	validation_0-mae:2136.32262
[384]	validation_0-mae:2136.25923
[385]	validation_0-mae:2136.41148
[386]	validation_0-mae:2136.34921
[387]	validation_0-mae:2135.94298
[388]	validation_0-mae:2135.66722
[389]	validation_0-mae:2134.75421
[390]	validation_0-mae:2134.32882
[391]	validation_0-mae:2134.32268
[392]	validation_0-mae:2134.48172
[393]	validation_0-mae:2134.48944
[394]	validation_0-mae:2134.79289
[395]	validation_0-mae:2134.73567
[396]	validation_0-mae:2134.97903
[397]	validation_0-mae:2135.11998
[398]	validation_0-mae:2135.06971
[399]	validation_0-mae:2135.32555
[400]	validation_0-mae:2134.66917
[401]	validation_0-mae:2134.59542
[402]	validation_0-mae:2133.32974
[403]	validation_0-mae:2133.01591
[404]	validation_0-mae:2132.54377
[405]	validation_0-mae:2132.27548
[406]	validation_0-mae:2132.05849
[407]	validation_0-mae:2132.20522
[408]	validation_0-mae:2132.36294
[409]	validation_0-mae:2132.31628
[410]	validation_0-mae:2131.71490
[411]	validation_0-mae:2130.22367
[412]	validation_0-mae:2130.20341
[413]	validation_0-mae:2130.45167
[414]	validation_0-mae:2131.04975
[415]	validation_0-mae:2131.13331
[416]	validation_0-mae:2131.30709
[417]	validation_0-mae:2130.96957
[418]	validation_0-mae:2130.40586
[419]	validation_0-mae:2130.48392
[420]	validation_0-mae:2130.96589
[421]	validation_0-mae:2130.91094
[422]	validation_0-mae:2130.45507
[423]	validation_0-mae:2130.34944
[424]	validation_0-mae:2129.22252
[425]	validation_0-mae:2128.50250
[426]	validation_0-mae:2129.05541
[427]	validation_0-mae:2129.18904
[428]	validation_0-mae:2129.48655
[429]	validation_0-mae:2128.27024
[430]	validation_0-mae:2128.19095
[431]	validation_0-mae:2128.25779
[432]	validation_0-mae:2128.30214
[433]	validation_0-mae:2128.72855
[434]	validation_0-mae:2128.55937
[435]	validation_0-mae:2128.51391
[436]	validation_0-mae:2128.34935
[437]	validation_0-mae:2128.01878
[438]	validation_0-mae:2127.55862
[439]	validation_0-mae:2127.24522
[440]	validation_0-mae:2127.66263
[441]	validation_0-mae:2127.87090
[442]	validation_0-mae:2127.37452
[443]	validation_0-mae:2127.96862
[444]	validation_0-mae:2127.83854
[445]	validation_0-mae:2127.53621
[446]	validation_0-mae:2127.07804
[447]	validation_0-mae:2126.78604
[448]	validation_0-mae:2126.73047
[449]	validation_0-mae:2126.86173
[450]	validation_0-mae:2126.75307
[451]	validation_0-mae:2127.06236
[452]	validation_0-mae:2127.12128
[453]	validation_0-mae:2126.62240
[454]	validation_0-mae:2126.33965
[455]	validation_0-mae:2126.16573
[456]	validation_0-mae:2126.85302
[457]	validation_0-mae:2127.24138
[458]	validation_0-mae:2127.54647
[459]	validation_0-mae:2127.91832
[460]	validation_0-mae:2127.93826
[461]	validation_0-mae:2127.81333
[462]	validation_0-mae:2127.74865
[463]	validation_0-mae:2127.56039
[464]	validation_0-mae:2128.09919
[465]	validation_0-mae:2128.45300
[466]	validation_0-mae:2128.59034
[467]	validation_0-mae:2128.38770
[468]	validation_0-mae:2127.99617
[469]	validation_0-mae:2127.70468
[470]	validation_0-mae:2127.76416
[471]	validation_0-mae:2127.81981
[472]	validation_0-mae:2127.52886
[473]	validation_0-mae:2127.61319
[474]	validation_0-mae:2127.40360
[475]	validation_0-mae:2127.38634
[476]	validation_0-mae:2126.27120
[477]	validation_0-mae:2126.21085
[478]	validation_0-mae:2126.22717
[479]	validation_0-mae:2126.24306
[480]	validation_0-mae:2126.27833
[481]	validation_0-mae:2126.15198
[482]	validation_0-mae:2126.37113
[483]	validation_0-mae:2126.27298
[484]	validation_0-mae:2126.27762
[485]	validation_0-mae:2126.67241
[486]	validation_0-mae:2126.73207
[487]	validation_0-mae:2126.82159
[488]	validation_0-mae:2126.92356
[489]	validation_0-mae:2125.71905
[490]	validation_0-mae:2125.71316
[491]	validation_0-mae:2125.76474
[492]	validation_0-mae:2125.95866
[493]	validation_0-mae:2126.09446
[494]	validation_0-mae:2125.73401
[495]	validation_0-mae:2125.27412
[496]	validation_0-mae:2125.74429
[497]	validation_0-mae:2125.77364
[498]	validation_0-mae:2125.85639
[499]	validation_0-mae:2125.74053
[500]	validation_0-mae:2125.51207
[501]	validation_0-mae:2125.24116
[502]	validation_0-mae:2125.17735
[503]	validation_0-mae:2125.38188
[504]	validation_0-mae:2125.80456
[505]	validation_0-mae:2126.04230
[506]	validation_0-mae:2125.30105
[507]	validation_0-mae:2124.10582
[508]	validation_0-mae:2123.50943
[509]	validation_0-mae:2123.71089
[510]	validation_0-mae:2123.81443
[511]	validation_0-mae:2123.84078
[512]	validation_0-mae:2123.93176
[513]	validation_0-mae:2123.65041
[514]	validation_0-mae:2123.84465
[515]	validation_0-mae:2123.77272
[516]	validation_0-mae:2123.93866
[517]	validation_0-mae:2124.08236
[518]	validation_0-mae:2124.12297
[519]	validation_0-mae:2124.04567
[520]	validation_0-mae:2123.84316
[521]	validation_0-mae:2123.95560
[522]	validation_0-mae:2124.17885
[523]	validation_0-mae:2123.89334
[524]	validation_0-mae:2123.79067
[525]	validation_0-mae:2123.00070
[526]	validation_0-mae:2122.94831
[527]	validation_0-mae:2122.59717
[528]	validation_0-mae:2122.36802
[529]	validation_0-mae:2122.45409
[530]	validation_0-mae:2122.48710
[531]	validation_0-mae:2122.26945
[532]	validation_0-mae:2121.94682
[533]	validation_0-mae:2121.95622
[534]	validation_0-mae:2122.26227
[535]	validation_0-mae:2122.09597
[536]	validation_0-mae:2122.18538
[537]	validation_0-mae:2122.33568
[538]	validation_0-mae:2122.50074
[539]	validation_0-mae:2122.25469
[540]	validation_0-mae:2122.50879
[541]	validation_0-mae:2122.35337
[542]	validation_0-mae:2122.49629
[543]	validation_0-mae:2122.26983
[544]	validation_0-mae:2122.52073
[545]	validation_0-mae:2123.30668
[546]	validation_0-mae:2123.51445
[547]	validation_0-mae:2123.50197
[548]	validation_0-mae:2123.60642
[549]	validation_0-mae:2123.65465
[550]	validation_0-mae:2123.80440
[551]	validation_0-mae:2124.12398
[552]	validation_0-mae:2124.13757
[553]	validation_0-mae:2124.12850
[554]	validation_0-mae:2123.91643
[555]	validation_0-mae:2123.60971
[556]	validation_0-mae:2123.74297
[557]	validation_0-mae:2124.01040
[558]	validation_0-mae:2124.09122
[559]	validation_0-mae:2123.34418
[560]	validation_0-mae:2123.44185
[561]	validation_0-mae:2123.37187
[562]	validation_0-mae:2122.99762
[563]	validation_0-mae:2122.32233
[564]	validation_0-mae:2121.92600
[565]	validation_0-mae:2122.06119
[566]	validation_0-mae:2122.05763
[567]	validation_0-mae:2122.09755
[568]	validation_0-mae:2121.61661
[569]	validation_0-mae:2121.72252
[570]	validation_0-mae:2121.65615
[571]	validation_0-mae:2121.26052
[572]	validation_0-mae:2121.47478
[573]	validation_0-mae:2121.35699
[574]	validation_0-mae:2121.47679
[575]	validation_0-mae:2121.44798
[576]	validation_0-mae:2121.42199
[577]	validation_0-mae:2121.51715
[578]	validation_0-mae:2121.12661
[0]	validation_0-mae:12347.98008
[1]	validation_0-mae:11538.16143
[2]	validation_0-mae:10807.72352
[3]	validation_0-mae:10169.49149
[4]	validation_0-mae:9612.83830
[5]	validation_0-mae:9125.61371
[6]	validation_0-mae:8694.77106
[7]	validation_0-mae:8326.40084
[8]	validation_0-mae:7992.35165
[9]	validation_0-mae:7706.82799
[10]	validation_0-mae:7444.48669
[11]	validation_0-mae:7224.65687
[12]	validation_0-mae:7012.33630
[13]	validation_0-mae:6800.39596
[14]	validation_0-mae:6639.52601
[15]	validation_0-mae:6504.65318
[16]	validation_0-mae:6383.02916
[17]	validation_0-mae:6271.38973

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[0]	validation_0-mae:12381.72510
[1]	validation_0-mae:11598.23823
[2]	validation_0-mae:10883.85927
[3]	validation_0-mae:10234.22414
[4]	validation_0-mae:9665.60850
[5]	validation_0-mae:9135.50689
[6]	validation_0-mae:8665.04098
[7]	validation_0-mae:8263.39115
[8]	validation_0-mae:7871.09752
[9]	validation_0-mae:7528.65037
[10]	validation_0-mae:7204.29080
[11]	validation_0-mae:6909.11893
[12]	validation_0-mae:6614.42508
[13]	validation_0-mae:6335.79248
[14]	validation_0-mae:6091.23982
[15]	validation_0-mae:5866.92315
[16]	validation_0-mae:5651.44450
[17]	validation_0-mae:5449.36334
[18]	validation_0-mae:5280.73797
[19]	validation_0-mae:5100.36786
[20]	validation_0-mae:4924.70702
[21]	validation_0-mae:4775.67306
[22]	validation_0-mae:4642.22140
[23]	validation_0-mae:4519.01982
[24]	validation_0-mae:4403.32795
[25]	validation_0-mae:4279.91338
[26]	validation_0-mae:4162.00588
[27]	validation_0-mae:4060.02327
[28]	validation_0-mae:3959.50772
[29]	validation_0-mae:3871.39496
[30]	validation_0-mae:3790.90379
[31]	validation_0-mae:3714.24007
[32]	validation_0-mae:3633.86929
[33]	validation_0-mae:3573.09804
[34]	validation_0-mae:3509.10011
[35]	validation_0-mae:3451.84523
[36]	validation_0-mae:3393.94456
[37]	validation_0-mae:3344.03196
[38]	validation_0-mae:3284.22481
[39]	validation_0-mae:3240.84985
[40]	validation_0-mae:3202.00579
[41]	validation_0-mae:3163.92865
[42]	validation_0-mae:3126.02553
[43]	validation_0-mae:3088.63683
[44]	validation_0-mae:3060.12857
[45]	validation_0-mae:3007.46393
[46]	validation_0-mae:2977.88425
[47]	validation_0-mae:2936.11843
[48]	validation_0-mae:2916.76392
[49]	validation_0-mae:2895.17485
[50]	validation_0-mae:2876.64888
[51]	validation_0-mae:2848.51718
[52]	validation_0-mae:2830.74555
[53]	validation_0-mae:2814.72780
[54]	validation_0-mae:2797.78134
[55]	validation_0-mae:2776.78648
[56]	validation_0-mae:2762.22866
[57]	validation_0-mae:2747.17578
[58]	validation_0-mae:2732.14288
[59]	validation_0-mae:2696.79124
[60]	validation_0-mae:2678.00607
[61]	validation_0-mae:2663.38961
[62]	validation_0-mae:2653.59350
[63]	validation_0-mae:2641.89765
[64]	validation_0-mae:2618.88760
[65]	validation_0-mae:2596.25031
[66]	validation_0-mae:2588.16576
[67]	validation_0-mae:2571.72619
[68]	validation_0-mae:2563.13671
[69]	validation_0-mae:2550.02091
[70]	validation_0-mae:2541.21589
[71]	validation_0-mae:2536.51457
[72]	validation_0-mae:2525.74304
[73]	validation_0-mae:2515.13448
[74]	validation_0-mae:2505.33183
[75]	validation_0-mae:2495.88661
[76]	validation_0-mae:2488.45571
[77]	validation_0-mae:2476.49853
[78]	validation_0-mae:2469.58436
[79]	validation_0-mae:2459.04089
[80]	validation_0-mae:2446.57721
[81]	validation_0-mae:2434.70063
[82]	validation_0-mae:2428.73155
[83]	validation_0-mae:2419.12776
[84]	validation_0-mae:2407.67069
[85]	validation_0-mae:2402.81152
[86]	validation_0-mae:2397.44024
[87]	validation_0-mae:2386.02318
[88]	validation_0-mae:2374.65282
[89]	validation_0-mae:2367.27480
[90]	validation_0-mae:2364.79541
[91]	validation_0-mae:2358.15458
[92]	validation_0-mae:2353.53488
[93]	validation_0-mae:2346.83219
[94]	validation_0-mae:2337.34963
[95]	validation_0-mae:2328.71805
[96]	validation_0-mae:2321.95774
[97]	validation_0-mae:2319.29289
[98]	validation_0-mae:2314.84132
[99]	validation_0-mae:2312.38774
[100]	validation_0-mae:2306.72174
[101]	validation_0-mae:2306.61183
[102]	validation_0-mae:2301.64136
[103]	validation_0-mae:2297.01460
[104]	validation_0-mae:2292.46550
[105]	validation_0-mae:2288.43906
[106]	validation_0-mae:2279.43390
[107]	validation_0-mae:2276.97271
[108]	validation_0-mae:2272.51626
[109]	validation_0-mae:2265.39522
[110]	validation_0-mae:2262.72488
[111]	validation_0-mae:2260.75900
[112]	validation_0-mae:2260.23732
[113]	validation_0-mae:2256.80174
[114]	validation_0-mae:2255.94638
[115]	validation_0-mae:2252.82236
[116]	validation_0-mae:2251.35067
[117]	validation_0-mae:2248.70716
[118]	validation_0-mae:2245.40049
[119]	validation_0-mae:2243.83017
[120]	validation_0-mae:2241.56969
[121]	validation_0-mae:2239.55635
[122]	validation_0-mae:2236.39083
[123]	validation_0-mae:2233.89307
[124]	validation_0-mae:2228.47556
[125]	validation_0-mae:2228.64616
[126]	validation_0-mae:2226.80316
[127]	validation_0-mae:2223.82584
[128]	validation_0-mae:2219.67321
[129]	validation_0-mae:2218.38101
[130]	validation_0-mae:2218.73868
[131]	validation_0-mae:2216.20006
[132]	validation_0-mae:2214.36632
[133]	validation_0-mae:2214.99916
[134]	validation_0-mae:2211.78078
[135]	validation_0-mae:2210.06815
[136]	validation_0-mae:2210.44607
[137]	validation_0-mae:2207.64190
[138]	validation_0-mae:2203.81273
[139]	validation_0-mae:2199.53391
[140]	validation_0-mae:2198.90272
[141]	validation_0-mae:2197.52342
[142]	validation_0-mae:2196.22358
[143]	validation_0-mae:2196.90762
[144]	validation_0-mae:2194.80627
[145]	validation_0-mae:2193.61920
[146]	validation_0-mae:2190.42386
[147]	validation_0-mae:2189.76663
[148]	validation_0-mae:2189.81232
[149]	validation_0-mae:2188.77252
[150]	validation_0-mae:2187.61398
[151]	validation_0-mae:2187.05109
[152]	validation_0-mae:2187.22239
[153]	validation_0-mae:2184.67708
[154]	validation_0-mae:2183.98492
[155]	validation_0-mae:2182.79328
[156]	validation_0-mae:2181.23211
[157]	validation_0-mae:2181.57684
[158]	validation_0-mae:2180.40735
[159]	validation_0-mae:2179.88187
[160]	validation_0-mae:2179.61971
[161]	validation_0-mae:2178.41163
[162]	validation_0-mae:2177.96504
[163]	validation_0-mae:2177.53665
[164]	validation_0-mae:2176.95422
[165]	validation_0-mae:2176.26152
[166]	validation_0-mae:2176.71826
[167]	validation_0-mae:2175.43512
[168]	validation_0-mae:2174.02499
[169]	validation_0-mae:2172.11056
[170]	validation_0-mae:2170.53121
[171]	validation_0-mae:2167.99856
[172]	validation_0-mae:2165.38588
[173]	validation_0-mae:2163.08704
[174]	validation_0-mae:2161.08842
[175]	validation_0-mae:2161.69949
[176]	validation_0-mae:2160.47832
[177]	validation_0-mae:2158.34475
[178]	validation_0-mae:2158.07509
[179]	validation_0-mae:2155.36766
[180]	validation_0-mae:2156.40733
[181]	validation_0-mae:2155.41345
[182]	validation_0-mae:2155.86843
[183]	validation_0-mae:2155.66438
[184]	validation_0-mae:2156.19554
[185]	validation_0-mae:2155.86047
[186]	validation_0-mae:2155.31487
[187]	validation_0-mae:2154.74291
[188]	validation_0-mae:2153.39766
[189]	validation_0-mae:2153.62653
[190]	validation_0-mae:2153.93808
[191]	validation_0-mae:2154.07528
[192]	validation_0-mae:2154.23161
[193]	validation_0-mae:2154.40162
[194]	validation_0-mae:2154.23838
[195]	validation_0-mae:2154.19169
[196]	validation_0-mae:2152.71830
[197]	validation_0-mae:2152.70617
[198]	validation_0-mae:2152.99441
[199]	validation_0-mae:2152.36740
[200]	validation_0-mae:2149.06902
[201]	validation_0-mae:2147.22450
[202]	validation_0-mae:2147.79360
[203]	validation_0-mae:2148.10715
[204]	validation_0-mae:2149.05154
[205]	validation_0-mae:2149.00905
[206]	validation_0-mae:2146.43459
[207]	validation_0-mae:2147.03619
[208]	validation_0-mae:2147.11716
[209]	validation_0-mae:2147.54233
[210]	validation_0-mae:2147.70631
[211]	validation_0-mae:2146.70736
[212]	validation_0-mae:2147.49237
[213]	validation_0-mae:2149.29757
[214]	validation_0-mae:2147.57598
[215]	validation_0-mae:2144.77881
[216]	validation_0-mae:2145.96520
[217]	validation_0-mae:2145.94038
[218]	validation_0-mae:2143.18960
[219]	validation_0-mae:2139.58469
[220]	validation_0-mae:2140.16187
[221]	validation_0-mae:2141.10097
[222]	validation_0-mae:2141.82598
[223]	validation_0-mae:2138.91322
[224]	validation_0-mae:2137.69021
[225]	validation_0-mae:2135.69830
[226]	validation_0-mae:2135.36940
[227]	validation_0-mae:2134.86742
[228]	validation_0-mae:2134.05261
[229]	validation_0-mae:2134.02140
[230]	validation_0-mae:2135.10078
[231]	validation_0-mae:2134.15528
[232]	validation_0-mae:2134.25595
[233]	validation_0-mae:2133.97403
[234]	validation_0-mae:2133.46453
[235]	validation_0-mae:2131.44181
[236]	validation_0-mae:2131.44149
[237]	validation_0-mae:2131.72522
[238]	validation_0-mae:2132.21527
[239]	validation_0-mae:2131.18992
[240]	validation_0-mae:2131.92652
[241]	validation_0-mae:2132.45191
[242]	validation_0-mae:2130.28841
[243]	validation_0-mae:2129.84698
[244]	validation_0-mae:2128.65197
[245]	validation_0-mae:2128.54506
[246]	validation_0-mae:2128.30141
[247]	validation_0-mae:2128.09300
[248]	validation_0-mae:2127.64597
[249]	validation_0-mae:2126.65390
[250]	validation_0-mae:2126.46744
[251]	validation_0-mae:2127.30075
[252]	validation_0-mae:2126.81080
[253]	validation_0-mae:2125.20690
[254]	validation_0-mae:2124.47374
[255]	validation_0-mae:2123.87948
[256]	validation_0-mae:2124.10601
[257]	validation_0-mae:2123.55473
[258]	validation_0-mae:2122.58581
[259]	validation_0-mae:2121.93687
[260]	validation_0-mae:2120.65615
[261]	validation_0-mae:2120.17308
[262]	validation_0-mae:2120.35350
[263]	validation_0-mae:2120.71906
[264]	validation_0-mae:2119.56840
[265]	validation_0-mae:2117.61159
[266]	validation_0-mae:2116.29079
[267]	validation_0-mae:2115.06023
[268]	validation_0-mae:2115.89474
[269]	validation_0-mae:2115.08296
[270]	validation_0-mae:2114.56070
[271]	validation_0-mae:2114.51871
[272]	validation_0-mae:2114.13533
[273]	validation_0-mae:2114.36551
[274]	validation_0-mae:2114.64911
[275]	validation_0-mae:2115.50731
[276]	validation_0-mae:2115.92543
[277]	validation_0-mae:2114.61178
[278]	validation_0-mae:2114.90230
[279]	validation_0-mae:2115.19954
[280]	validation_0-mae:2114.69220
[281]	validation_0-mae:2114.99543
[282]	validation_0-mae:2114.25045
[283]	validation_0-mae:2114.36976
[284]	validation_0-mae:2113.27375
[285]	validation_0-mae:2113.30433
[286]	validation_0-mae:2113.61890
[287]	validation_0-mae:2113.73263
[288]	validation_0-mae:2113.40366
[289]	validation_0-mae:2114.01545
[290]	validation_0-mae:2113.12212
[291]	validation_0-mae:2112.43022
[292]	validation_0-mae:2112.12639
[293]	validation_0-mae:2112.14514
[294]	validation_0-mae:2110.94590
[295]	validation_0-mae:2110.64565
[296]	validation_0-mae:2110.91891
[297]	validation_0-mae:2111.02006
[298]	validation_0-mae:2111.44998
[299]	validation_0-mae:2110.82856
[300]	validation_0-mae:2110.62185
[301]	validation_0-mae:2110.71596
[302]	validation_0-mae:2109.37834
[303]	validation_0-mae:2108.50273
[304]	validation_0-mae:2108.32071
[305]	validation_0-mae:2108.39501
[306]	validation_0-mae:2108.20465
[307]	validation_0-mae:2107.78886
[308]	validation_0-mae:2107.10676
[309]	validation_0-mae:2107.04598
[310]	validation_0-mae:2107.04609
[311]	validation_0-mae:2107.24773
[312]	validation_0-mae:2107.21110
[313]	validation_0-mae:2106.62652
[314]	validation_0-mae:2105.09486
[315]	validation_0-mae:2105.71846
[316]	validation_0-mae:2105.56456
[317]	validation_0-mae:2105.06097
[318]	validation_0-mae:2104.91385
[319]	validation_0-mae:2104.09939
[320]	validation_0-mae:2102.16781
[321]	validation_0-mae:2102.36011
[322]	validation_0-mae:2102.27789
[323]	validation_0-mae:2101.92174
[324]	validation_0-mae:2101.95179
[325]	validation_0-mae:2102.15838
[326]	validation_0-mae:2102.10561
[327]	validation_0-mae:2102.04434
[328]	validation_0-mae:2100.53054
[329]	validation_0-mae:2100.79560
[330]	validation_0-mae:2101.08110
[331]	validation_0-mae:2099.78182
[332]	validation_0-mae:2098.96633
[333]	validation_0-mae:2098.77591
[334]	validation_0-mae:2098.27243
[335]	validation_0-mae:2098.62735
[336]	validation_0-mae:2098.47542
[337]	validation_0-mae:2098.76559
[338]	validation_0-mae:2098.44102
[339]	validation_0-mae:2098.38306
[340]	validation_0-mae:2097.67159
[341]	validation_0-mae:2098.17291
[342]	validation_0-mae:2098.47435
[343]	validation_0-mae:2098.09770
[344]	validation_0-mae:2097.96850
[345]	validation_0-mae:2096.70150
[346]	validation_0-mae:2095.15080
[347]	validation_0-mae:2093.73794
[348]	validation_0-mae:2093.75195
[349]	validation_0-mae:2093.61976
[350]	validation_0-mae:2094.06421
[351]	validation_0-mae:2092.96477
[352]	validation_0-mae:2093.03268
[353]	validation_0-mae:2092.73699
[354]	validation_0-mae:2092.48117
[355]	validation_0-mae:2091.94231
[356]	validation_0-mae:2090.66297
[357]	validation_0-mae:2090.20016
[358]	validation_0-mae:2090.34196
[359]	validation_0-mae:2090.41840
[360]	validation_0-mae:2090.14444
[361]	validation_0-mae:2090.05402
[362]	validation_0-mae:2089.53762
[363]	validation_0-mae:2089.41368
[364]	validation_0-mae:2088.86677
[365]	validation_0-mae:2089.21745
[366]	validation_0-mae:2089.40311
[367]	validation_0-mae:2089.53107
[368]	validation_0-mae:2089.78083
[369]	validation_0-mae:2089.59413
[370]	validation_0-mae:2089.87558
[371]	validation_0-mae:2088.99140
[372]	validation_0-mae:2089.41065
[373]	validation_0-mae:2089.37481
[374]	validation_0-mae:2089.16436
[375]	validation_0-mae:2088.32033
[376]	validation_0-mae:2087.66652
[377]	validation_0-mae:2087.90998
[378]	validation_0-mae:2086.55578
[379]	validation_0-mae:2086.72145
[380]	validation_0-mae:2087.03312
[381]	validation_0-mae:2086.64952
[382]	validation_0-mae:2086.91655
[383]	validation_0-mae:2087.03521
[384]	validation_0-mae:2087.45314
[385]	validation_0-mae:2087.19203
[386]	validation_0-mae:2086.88963
[387]	validation_0-mae:2086.66444
[388]	validation_0-mae:2086.75446
[389]	validation_0-mae:2086.65889
[390]	validation_0-mae:2086.84707
[391]	validation_0-mae:2087.14676
[392]	validation_0-mae:2087.28536
[393]	validation_0-mae:2086.76726
[394]	validation_0-mae:2086.37269
[395]	validation_0-mae:2086.44489
[396]	validation_0-mae:2086.88973
[397]	validation_0-mae:2086.83841
[398]	validation_0-mae:2085.97951
[399]	validation_0-mae:2086.17293
[400]	validation_0-mae:2086.05737
[401]	validation_0-mae:2086.58968
[402]	validation_0-mae:2087.35460
[403]	validation_0-mae:2085.44057
[404]	validation_0-mae:2085.62971
[405]	validation_0-mae:2085.75841
[406]	validation_0-mae:2085.83459
[407]	validation_0-mae:2085.86854
[408]	validation_0-mae:2086.04991
[409]	validation_0-mae:2085.85755
[410]	validation_0-mae:2085.33405
[411]	validation_0-mae:2085.65473
[412]	validation_0-mae:2085.81877
[413]	validation_0-mae:2084.55535
[414]	validation_0-mae:2084.43607
[415]	validation_0-mae:2084.48786
[416]	validation_0-mae:2083.90148
[417]	validation_0-mae:2084.03876
[418]	validation_0-mae:2083.93926
[419]	validation_0-mae:2084.16856
[420]	validation_0-mae:2083.35002
[421]	validation_0-mae:2083.75760
[422]	validation_0-mae:2083.24855
[423]	validation_0-mae:2083.29234
[424]	validation_0-mae:2083.17587
[425]	validation_0-mae:2082.98254
[426]	validation_0-mae:2083.44240
[427]	validation_0-mae:2083.58277
[428]	validation_0-mae:2083.84691
[429]	validation_0-mae:2083.41035
[430]	validation_0-mae:2083.40892
[431]	validation_0-mae:2083.86614
[432]	validation_0-mae:2083.42545
[433]	validation_0-mae:2083.75382
[434]	validation_0-mae:2083.71185
[435]	validation_0-mae:2083.84189
[436]	validation_0-mae:2084.05086
[437]	validation_0-mae:2084.29766
[438]	validation_0-mae:2084.12915
[439]	validation_0-mae:2084.53657
[440]	validation_0-mae:2084.74793
[441]	validation_0-mae:2085.05945
[442]	validation_0-mae:2085.16158
[443]	validation_0-mae:2085.20882
[444]	validation_0-mae:2085.46474
[445]	validation_0-mae:2085.59640
[446]	validation_0-mae:2085.39665
[447]	validation_0-mae:2085.27701
[448]	validation_0-mae:2085.34633
[449]	validation_0-mae:2085.28936
[450]	validation_0-mae:2085.15321
[451]	validation_0-mae:2084.89870
[452]	validation_0-mae:2085.12235
[453]	validation_0-mae:2084.28229
[454]	validation_0-mae:2083.23560
[455]	validation_0-mae:2082.29543
[456]	validation_0-mae:2082.54251
[457]	validation_0-mae:2082.83039
[458]	validation_0-mae:2082.48317
[459]	validation_0-mae:2082.37516
[460]	validation_0-mae:2081.95344
[461]	validation_0-mae:2081.44134
[462]	validation_0-mae:2081.24718
[463]	validation_0-mae:2080.64721
[464]	validation_0-mae:2080.69558
[465]	validation_0-mae:2080.91171
[466]	validation_0-mae:2080.70998
[467]	validation_0-mae:2080.81063
[468]	validation_0-mae:2080.46511
[469]	validation_0-mae:2080.80922
[470]	validation_0-mae:2080.36979
[471]	validation_0-mae:2080.57531
[472]	validation_0-mae:2080.93958
[473]	validation_0-mae:2081.01557
[474]	validation_0-mae:2081.40394
[475]	validation_0-mae:2081.08142
[476]	validation_0-mae:2081.38349
[477]	validation_0-mae:2081.46769
[478]	validation_0-mae:2080.75789
[479]	validation_0-mae:2080.48573
[480]	validation_0-mae:2080.66245
[481]	validation_0-mae:2080.67481
[482]	validation_0-mae:2080.30669
[483]	validation_0-mae:2080.44390
[484]	validation_0-mae:2079.65740
[485]	validation_0-mae:2079.79360
[486]	validation_0-mae:2079.50125
[487]	validation_0-mae:2079.07564
[488]	validation_0-mae:2079.23850
[489]	validation_0-mae:2078.94846
[490]	validation_0-mae:2079.01328
[491]	validation_0-mae:2078.63039
[492]	validation_0-mae:2078.93143
[493]	validation_0-mae:2078.94504
[494]	validation_0-mae:2078.75280
[495]	validation_0-mae:2078.85517
[496]	validation_0-mae:2078.87038
[497]	validation_0-mae:2079.08617
[498]	validation_0-mae:2079.00149
[499]	validation_0-mae:2079.17549
[500]	validation_0-mae:2079.13227
[501]	validation_0-mae:2078.79498
[502]	validation_0-mae:2078.79113
[503]	validation_0-mae:2078.34614
[504]	validation_0-mae:2078.03050
[505]	validation_0-mae:2078.11453
[506]	validation_0-mae:2078.12729
[507]	validation_0-mae:2078.26256
[508]	validation_0-mae:2078.15021
[509]	validation_0-mae:2077.60960
[510]	validation_0-mae:2077.98136
[511]	validation_0-mae:2077.93487
[512]	validation_0-mae:2077.97457
[513]	validation_0-mae:2077.99232
[514]	validation_0-mae:2077.90187
[515]	validation_0-mae:2077.66986
[516]	validation_0-mae:2077.70746
[517]	validation_0-mae:2077.58756
[518]	validation_0-mae:2077.67916
[519]	validation_0-mae:2077.91309
[520]	validation_0-mae:2077.97982
[521]	validation_0-mae:2077.88840
[522]	validation_0-mae:2077.91981
[523]	validation_0-mae:2077.91979
[524]	validation_0-mae:2077.49724
[525]	validation_0-mae:2077.20377
[526]	validation_0-mae:2077.02664
[527]	validation_0-mae:2076.53855
[528]	validation_0-mae:2076.40330
[529]	validation_0-mae:2075.93631
[530]	validation_0-mae:2076.00147
[531]	validation_0-mae:2075.61095
[532]	validation_0-mae:2075.19862
[533]	validation_0-mae:2075.25936
[534]	validation_0-mae:2074.71338
[535]	validation_0-mae:2074.72807
[536]	validation_0-mae:2074.66994
[537]	validation_0-mae:2074.52115
[538]	validation_0-mae:2074.70513
[539]	validation_0-mae:2074.82509
[540]	validation_0-mae:2074.82839
[541]	validation_0-mae:2074.95760
[542]	validation_0-mae:2075.04991
[543]	validation_0-mae:2075.00419
[544]	validation_0-mae:2075.00741
[545]	validation_0-mae:2074.71203
[546]	validation_0-mae:2074.53405
[547]	validation_0-mae:2074.35366
[548]	validation_0-mae:2073.75969
[549]	validation_0-mae:2073.58146
[550]	validation_0-mae:2073.67242
[551]	validation_0-mae:2073.71627
[552]	validation_0-mae:2073.75165
[553]	validation_0-mae:2073.72565
[554]	validation_0-mae:2073.63351
[555]	validation_0-mae:2074.06845
[556]	validation_0-mae:2073.97464
[557]	validation_0-mae:2073.88815
[558]	validation_0-mae:2073.81860
[559]	validation_0-mae:2073.00594
[560]	validation_0-mae:2072.98851
[561]	validation_0-mae:2072.83025
[562]	validation_0-mae:2072.56297
[563]	validation_0-mae:2072.42139
[564]	validation_0-mae:2072.54484
[565]	validation_0-mae:2072.80393
[566]	validation_0-mae:2072.68490
[567]	validation_0-mae:2072.69512
[568]	validation_0-mae:2072.67405
[569]	validation_0-mae:2072.52602
[570]	validation_0-mae:2072.53801
[571]	validation_0-mae:2072.37042
[572]	validation_0-mae:2072.24820
[573]	validation_0-mae:2071.98045
[574]	validation_0-mae:2071.84915
[575]	validation_0-mae:2071.83170
[576]	validation_0-mae:2072.03094
[577]	validation_0-mae:2072.11095
[578]	validation_0-mae:2071.91560
[579]	validation_0-mae:2071.66283
[580]	validation_0-mae:2071.31439
[581]	validation_0-mae:2071.19422
[582]	validation_0-mae:2071.17292
[583]	validation_0-mae:2071.28758
[584]	validation_0-mae:2071.56187
[585]	validation_0-mae:2071.60769
[586]	validation_0-mae:2071.39290
[587]	validation_0-mae:2070.48692
[588]	validation_0-mae:2069.65080
[589]	validation_0-mae:2069.41579
[590]	validation_0-mae:2069.46204

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[0]	validation_0-mae:12400.63307
[1]	validation_0-mae:11626.31315
[2]	validation_0-mae:10947.68097
[3]	validation_0-mae:10342.54878
[4]	validation_0-mae:9798.40707
[5]	validation_0-mae:9356.72658
[6]	validation_0-mae:8959.23786
[7]	validation_0-mae:8598.93912
[8]	validation_0-mae:8278.46187
[9]	validation_0-mae:7981.09714
[10]	validation_0-mae:7712.22026
[11]	validation_0-mae:7493.81448
[12]	validation_0-mae:7279.95965
[13]	validation_0-mae:7093.46522
[0]	validation_0-mae:12351.78149
[1]	validation_0-mae:11564.87874
[2]	validation_0-mae:10833.39642
[3]	validation_0-mae:10147.78842
[4]	validation_0-mae:9564.08091
[5]	validation_0-mae:9050.89932
[6]	validation_0-mae:8580.79568
[7]	validation_0-mae:8158.62306
[8]	validation_0-mae:7769.81663
[9]	validation_0-mae:7421.42337
[10]	validation_0-mae:7102.65452
[11]	validation_0-mae:6777.88894
[12]	validation_0-mae:6488.20688
[13]	validation_0-mae:6222.79525
[14]	validation_0-mae:6001.88755
[15]	validation_0-mae:5776.56809
[16]	validation_0-mae:5546.90328
[17]	validation_0-mae:5376.46904
[18]	validation_0-mae:5201.77324
[19]	validation_0-mae:5025.47637
[20]	validation_0-mae:4886.72680
[21]	validation_0-mae:4744.25501
[22]	validation_0-mae:4600.15371
[23]	validation_0-mae:4459.96410
[24]	validation_0-mae:4347.58288
[25]	validation_0-mae:4231.29295
[26]	validation_0-mae:4142.13831
[27]	validation_0-mae:4030.77140
[28]	validation_0-mae:3934.97536
[29]	validation_0-mae:3837.43196
[30]	validation_0-mae:3753.27057
[31]	validation_0-mae:3674.14699
[32]	validation_0-mae:3606.31666
[33]	validation_0-mae:3540.25985
[34]	validation_0-mae:3478.75951
[35]	validation_0-mae:3421.14788
[36]	validation_0-mae:3359.88482

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[37]	validation_0-mae:3311.11294
[38]	validation_0-mae:3266.37856
[39]	validation_0-mae:3227.32162
[40]	validation_0-mae:3188.83258
[41]	validation_0-mae:3145.12306
[42]	validation_0-mae:3101.95709
[43]	validation_0-mae:3066.22404
[44]	validation_0-mae:3037.05121
[45]	validation_0-mae:2994.59309
[46]	validation_0-mae:2961.95256
[47]	validation_0-mae:2931.47024
[48]	validation_0-mae:2900.00476
[49]	validation_0-mae:2880.05311
[50]	validation_0-mae:2858.82317
[51]	validation_0-mae:2841.74202
[52]	validation_0-mae:2816.01198
[53]	validation_0-mae:2797.89384
[54]	validation_0-mae:2780.24754
[55]	validation_0-mae:2761.12841
[56]	validation_0-mae:2741.44047
[57]	validation_0-mae:2726.31504
[58]	validation_0-mae:2714.89549
[59]	validation_0-mae:2703.00554
[60]	validation_0-mae:2679.19822
[61]	validation_0-mae:2666.25904
[62]	validation_0-mae:2653.94830
[63]	validation_0-mae:2639.21641
[64]	validation_0-mae:2633.10279
[65]	validation_0-mae:2622.87883
[66]	validation_0-mae:2615.13295
[67]	validation_0-mae:2598.74984
[68]	validation_0-mae:2594.12657
[69]	validation_0-mae:2585.20369
[70]	validation_0-mae:2572.99414
[71]	validation_0-mae:2559.05160
[72]	validation_0-mae:2554.60720
[73]	validation_0-mae:2544.55941
[74]	validation_0-mae:2539.95842
[75]	validation_0-mae:2531.90514
[76]	validation_0-mae:2522.73581
[77]	validation_0-mae:2512.58387
[78]	validation_0-mae:2499.96900
[79]	validation_0-mae:2493.60570
[80]	validation_0-mae:2485.82968
[81]	validation_0-mae:2478.12323
[82]	validation_0-mae:2469.33016
[83]	validation_0-mae:2458.77545
[84]	validation_0-mae:2452.75136
[85]	validation_0-mae:2443.39770
[86]	validation_0-mae:2436.18288
[87]	validation_0-mae:2425.98224
[88]	validation_0-mae:2418.19539
[89]	validation_0-mae:2414.42417
[90]	validation_0-mae:2411.12935
[91]	validation_0-mae:2407.60890
[92]	validation_0-mae:2402.97973
[93]	validation_0-mae:2401.72541
[94]	validation_0-mae:2396.94013
[95]	validation_0-mae:2391.00282
[96]	validation_0-mae:2389.75325
[97]	validation_0-mae:2386.43534
[98]	validation_0-mae:2384.66199
[99]	validation_0-mae:2382.08558
[100]	validation_0-mae:2382.01219
[101]	validation_0-mae:2379.43606
[102]	validation_0-mae:2373.52565
[103]	validation_0-mae:2369.43260
[104]	validation_0-mae:2368.78632
[105]	validation_0-mae:2368.21192
[106]	validation_0-mae:2364.79905
[107]	validation_0-mae:2361.37310
[108]	validation_0-mae:2357.94255
[109]	validation_0-mae:2352.74482
[110]	validation_0-mae:2349.99604
[111]	validation_0-mae:2347.31362
[112]	validation_0-mae:2342.70130
[113]	validation_0-mae:2340.69018
[114]	validation_0-mae:2338.48078
[115]	validation_0-mae:2335.64669
[116]	validation_0-mae:2331.83856
[117]	validation_0-mae:2330.05530
[118]	validation_0-mae:2323.45479
[119]	validation_0-mae:2321.22762
[120]	validation_0-mae:2318.46317
[121]	validation_0-mae:2313.69195
[122]	validation_0-mae:2310.56855
[123]	validation_0-mae:2308.40500
[124]	validation_0-mae:2305.64096
[125]	validation_0-mae:2302.90218
[126]	validation_0-mae:2303.12527
[127]	validation_0-mae:2299.85609
[128]	validation_0-mae:2297.13732
[129]	validation_0-mae:2294.88336
[130]	validation_0-mae:2291.22860
[131]	validation_0-mae:2291.32747
[132]	validation_0-mae:2291.25960
[133]	validation_0-mae:2289.68466
[134]	validation_0-mae:2284.28929
[135]	validation_0-mae:2282.80284
[136]	validation_0-mae:2281.92156
[137]	validation_0-mae:2281.84973
[138]	validation_0-mae:2281.70164
[139]	validation_0-mae:2278.22058
[140]	validation_0-mae:2276.66946
[141]	validation_0-mae:2274.47604
[142]	validation_0-mae:2271.95744
[143]	validation_0-mae:2271.44102
[144]	validation_0-mae:2270.76285
[145]	validation_0-mae:2271.78743
[146]	validation_0-mae:2270.00511
[147]	validation_0-mae:2265.23907
[148]	validation_0-mae:2263.07298
[149]	validation_0-mae:2260.19427
[150]	validation_0-mae:2257.98497
[151]	validation_0-mae:2256.20607
[152]	validation_0-mae:2255.66855
[153]	validation_0-mae:2255.33139
[154]	validation_0-mae:2254.60759
[155]	validation_0-mae:2255.27346
[156]	validation_0-mae:2252.40090
[157]	validation_0-mae:2250.98095
[158]	validation_0-mae:2250.60109
[159]	validation_0-mae:2250.01820
[160]	validation_0-mae:2250.66692
[161]	validation_0-mae:2249.03231
[162]	validation_0-mae:2245.70032
[163]	validation_0-mae:2246.47053
[164]	validation_0-mae:2244.40900
[165]	validation_0-mae:2244.79683
[166]	validation_0-mae:2244.94208
[167]	validation_0-mae:2243.99235
[168]	validation_0-mae:2243.22143
[169]	validation_0-mae:2243.03647
[170]	validation_0-mae:2240.89006
[171]	validation_0-mae:2241.86053
[172]	validation_0-mae:2243.07319
[173]	validation_0-mae:2240.49425
[174]	validation_0-mae:2239.11280
[175]	validation_0-mae:2238.37004
[176]	validation_0-mae:2237.97237
[177]	validation_0-mae:2237.72233
[178]	validation_0-mae:2238.04984
[179]	validation_0-mae:2236.38949
[180]	validation_0-mae:2235.97077
[181]	validation_0-mae:2235.65156
[182]	validation_0-mae:2234.75415
[183]	validation_0-mae:2234.97886
[184]	validation_0-mae:2233.53393
[185]	validation_0-mae:2233.80720
[186]	validation_0-mae:2231.45227
[187]	validation_0-mae:2230.88799
[188]	validation_0-mae:2229.06346
[189]	validation_0-mae:2230.54793
[190]	validation_0-mae:2228.18928
[191]	validation_0-mae:2229.08028
[192]	validation_0-mae:2227.84845
[193]	validation_0-mae:2227.81985
[194]	validation_0-mae:2226.90686
[195]	validation_0-mae:2225.67231
[196]	validation_0-mae:2226.02224
[197]	validation_0-mae:2225.57106
[198]	validation_0-mae:2225.64279
[199]	validation_0-mae:2225.00593
[200]	validation_0-mae:2224.88119
[201]	validation_0-mae:2223.42033
[202]	validation_0-mae:2222.01727
[203]	validation_0-mae:2221.55411
[204]	validation_0-mae:2218.17012
[205]	validation_0-mae:2217.59383
[206]	validation_0-mae:2217.31152
[207]	validation_0-mae:2216.29186
[208]	validation_0-mae:2216.57800
[209]	validation_0-mae:2215.90422
[210]	validation_0-mae:2214.29309
[211]	validation_0-mae:2212.30839
[212]	validation_0-mae:2212.40794
[213]	validation_0-mae:2211.51728
[214]	validation_0-mae:2210.17144
[215]	validation_0-mae:2208.35130
[216]	validation_0-mae:2207.92627
[217]	validation_0-mae:2207.74327
[218]	validation_0-mae:2207.04731
[219]	validation_0-mae:2205.84049
[220]	validation_0-mae:2206.13962
[221]	validation_0-mae:2206.05637
[222]	validation_0-mae:2204.64310
[223]	validation_0-mae:2202.65018
[224]	validation_0-mae:2202.35633
[225]	validation_0-mae:2200.98478
[226]	validation_0-mae:2200.56439
[227]	validation_0-mae:2200.01773
[228]	validation_0-mae:2199.84834
[229]	validation_0-mae:2200.05360
[230]	validation_0-mae:2200.25781
[231]	validation_0-mae:2198.55819
[232]	validation_0-mae:2196.58811
[233]	validation_0-mae:2196.24556
[234]	validation_0-mae:2196.62186
[235]	validation_0-mae:2196.31917
[236]	validation_0-mae:2195.20712
[237]	validation_0-mae:2194.54633
[238]	validation_0-mae:2194.18610
[239]	validation_0-mae:2194.28934
[240]	validation_0-mae:2193.60787
[241]	validation_0-mae:2190.90377
[242]	validation_0-mae:2190.35861
[243]	validation_0-mae:2188.54906
[244]	validation_0-mae:2188.34570
[245]	validation_0-mae:2187.29663
[246]	validation_0-mae:2185.20691
[247]	validation_0-mae:2184.48453
[248]	validation_0-mae:2184.18956
[249]	validation_0-mae:2184.05084
[250]	validation_0-mae:2183.44799
[251]	validation_0-mae:2182.34378
[252]	validation_0-mae:2181.99318
[253]	validation_0-mae:2181.74094
[254]	validation_0-mae:2181.21410
[255]	validation_0-mae:2180.73606
[256]	validation_0-mae:2180.39472
[257]	validation_0-mae:2179.03707
[258]	validation_0-mae:2179.20254
[259]	validation_0-mae:2177.55285
[260]	validation_0-mae:2177.23909
[261]	validation_0-mae:2177.78369
[262]	validation_0-mae:2177.73854
[263]	validation_0-mae:2177.64288
[264]	validation_0-mae:2177.92531
[265]	validation_0-mae:2177.14371
[266]	validation_0-mae:2176.62271
[267]	validation_0-mae:2176.49358
[268]	validation_0-mae:2176.43288
[269]	validation_0-mae:2176.12726
[270]	validation_0-mae:2176.75283
[271]	validation_0-mae:2176.62246
[272]	validation_0-mae:2176.31524
[273]	validation_0-mae:2175.50754
[274]	validation_0-mae:2174.56077
[275]	validation_0-mae:2174.60760
[276]	validation_0-mae:2174.45198
[277]	validation_0-mae:2174.14341
[278]	validation_0-mae:2174.40158
[279]	validation_0-mae:2174.87976
[280]	validation_0-mae:2174.60834
[281]	validation_0-mae:2174.56698
[282]	validation_0-mae:2174.77982
[283]	validation_0-mae:2174.54848
[284]	validation_0-mae:2174.81690
[285]	validation_0-mae:2174.97392
[286]	validation_0-mae:2174.61654
[287]	validation_0-mae:2174.39901
[288]	validation_0-mae:2174.47686
[289]	validation_0-mae:2174.44290
[290]	validation_0-mae:2173.99962
[291]	validation_0-mae:2174.24709
[292]	validation_0-mae:2172.54665
[293]	validation_0-mae:2172.75370
[294]	validation_0-mae:2172.74133
[295]	validation_0-mae:2172.87179
[296]	validation_0-mae:2173.06492
[297]	validation_0-mae:2173.00713
[298]	validation_0-mae:2172.84741
[299]	validation_0-mae:2172.19601
[300]	validation_0-mae:2170.95484
[301]	validation_0-mae:2170.47241
[302]	validation_0-mae:2170.90749
[303]	validation_0-mae:2169.41948
[304]	validation_0-mae:2169.10976
[305]	validation_0-mae:2168.60862
[306]	validation_0-mae:2169.19486
[307]	validation_0-mae:2168.85416
[308]	validation_0-mae:2167.41987
[309]	validation_0-mae:2167.04915
[310]	validation_0-mae:2167.25207
[311]	validation_0-mae:2166.67972
[312]	validation_0-mae:2166.56555
[313]	validation_0-mae:2164.70660
[314]	validation_0-mae:2165.04075
[315]	validation_0-mae:2164.75723
[316]	validation_0-mae:2164.64371
[317]	validation_0-mae:2165.09072
[318]	validation_0-mae:2164.57636
[319]	validation_0-mae:2164.56108
[320]	validation_0-mae:2163.67047
[321]	validation_0-mae:2163.04935
[322]	validation_0-mae:2161.54337
[323]	validation_0-mae:2160.83109
[324]	validation_0-mae:2160.65700
[325]	validation_0-mae:2160.03367
[326]	validation_0-mae:2160.19846
[327]	validation_0-mae:2159.64759
[328]	validation_0-mae:2159.52450
[329]	validation_0-mae:2160.06174
[330]	validation_0-mae:2160.48716
[331]	validation_0-mae:2160.81037
[332]	validation_0-mae:2160.42823
[333]	validation_0-mae:2160.44613
[334]	validation_0-mae:2160.35146
[335]	validation_0-mae:2160.25727
[336]	validation_0-mae:2159.85963
[337]	validation_0-mae:2159.92631
[338]	validation_0-mae:2159.10713
[339]	validation_0-mae:2159.54399
[340]	validation_0-mae:2159.99525
[341]	validation_0-mae:2160.40582
[342]	validation_0-mae:2159.97003
[343]	validation_0-mae:2160.36549
[344]	validation_0-mae:2160.39325
[345]	validation_0-mae:2160.09293
[346]	validation_0-mae:2160.28736
[347]	validation_0-mae:2160.33601
[348]	validation_0-mae:2160.45326
[349]	validation_0-mae:2160.49582
[350]	validation_0-mae:2160.27420
[351]	validation_0-mae:2159.72797
[352]	validation_0-mae:2159.10512
[353]	validation_0-mae:2158.61774
[354]	validation_0-mae:2158.64659
[355]	validation_0-mae:2158.93824
[356]	validation_0-mae:2158.78863
[357]	validation_0-mae:2158.60414
[358]	validation_0-mae:2158.56437
[0]	validation_0-mae:12415.07986
[1]	validation_0-mae:11658.20371
[2]	validation_0-mae:10983.79214
[3]	validation_0-mae:10349.87468
[4]	validation_0-mae:9801.25815
[5]	validation_0-mae:9277.25658
[6]	validation_0-mae:8830.22440
[7]	validation_0-mae:8411.15049
[8]	validation_0-mae:8015.53971
[9]	validation_0-mae:7663.93696
[10]	validation_0-mae:7361.99242
[11]	validation_0-mae:7067.84357
[12]	validation_0-mae:6784.13784
[13]	validation_0-mae:6500.90095
[14]	validation_0-mae:6270.50341
[15]	validation_0-mae:6056.66396
[16]	validation_0-mae:5845.31444
[17]	validation_0-mae:5645.29565
[18]	validation_0-mae:5437.80345
[19]	validation_0-mae:5270.90616
[20]	validation_0-mae:5113.90031
[21]	validation_0-mae:4947.18142
[22]	validation_0-mae:4814.44668
[23]	validation_0-mae:4670.00436
[24]	validation_0-mae:4540.37874
[25]	validation_0-mae:4438.00615
[26]	validation_0-mae:4325.53241
[27]	validation_0-mae:4206.96503
[28]	validation_0-mae:4108.74882
[29]	validation_0-mae:4011.57858
[30]	validation_0-mae:3916.62630
[31]	validation_0-mae:3833.09135
[32]	validation_0-mae:3746.71263
[33]	validation_0-mae:3681.91520
[34]	validation_0-mae:3611.68097
[35]	validation_0-mae:3549.95473
[36]	validation_0-mae:3491.38796
[37]	validation_0-mae:3432.61398
[38]	validation_0-mae:3379.34655
[39]	validation_0-mae:3330.35102
[40]	validation_0-mae:3291.02328
[41]	validation_0-mae:3250.78039
[42]	validation_0-mae:3215.48111

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[43]	validation_0-mae:3182.26745
[44]	validation_0-mae:3149.64443
[45]	validation_0-mae:3098.74796
[46]	validation_0-mae:3070.06687
[47]	validation_0-mae:3027.96240
[48]	validation_0-mae:3006.16670
[49]	validation_0-mae:2979.54802
[50]	validation_0-mae:2961.67490
[51]	validation_0-mae:2926.27275
[52]	validation_0-mae:2901.93916
[53]	validation_0-mae:2881.69169
[54]	validation_0-mae:2869.20168
[55]	validation_0-mae:2850.31326
[56]	validation_0-mae:2833.59520
[57]	validation_0-mae:2808.75119
[58]	validation_0-mae:2794.37402
[59]	validation_0-mae:2764.05508
[60]	validation_0-mae:2747.23531
[61]	validation_0-mae:2730.54373
[62]	validation_0-mae:2715.04206
[63]	validation_0-mae:2703.77679
[64]	validation_0-mae:2691.67882
[65]	validation_0-mae:2681.25500
[66]	validation_0-mae:2669.46935
[67]	validation_0-mae:2645.66611
[68]	validation_0-mae:2626.28280
[69]	validation_0-mae:2610.92615
[70]	validation_0-mae:2603.83201
[71]	validation_0-mae:2594.23877
[72]	validation_0-mae:2585.59231
[73]	validation_0-mae:2569.57284
[74]	validation_0-mae:2553.70468
[75]	validation_0-mae:2543.32659
[76]	validation_0-mae:2539.45593
[77]	validation_0-mae:2532.62562
[78]	validation_0-mae:2524.21737
[79]	validation_0-mae:2518.33815
[80]	validation_0-mae:2507.21420
[81]	validation_0-mae:2503.89581
[82]	validation_0-mae:2497.69363
[83]	validation_0-mae:2491.60919
[84]	validation_0-mae:2482.80004
[85]	validation_0-mae:2474.94078
[86]	validation_0-mae:2466.42624
[87]	validation_0-mae:2459.03068
[88]	validation_0-mae:2451.82332
[89]	validation_0-mae:2443.96973
[90]	validation_0-mae:2435.45065
[91]	validation_0-mae:2430.57764
[92]	validation_0-mae:2425.60727
[93]	validation_0-mae:2413.43514
[94]	validation_0-mae:2405.84187
[95]	validation_0-mae:2399.95097
[96]	validation_0-mae:2396.29548
[97]	validation_0-mae:2388.33118
[98]	validation_0-mae:2377.47132
[99]	validation_0-mae:2374.17653
[100]	validation_0-mae:2371.45005
[101]	validation_0-mae:2362.64483
[102]	validation_0-mae:2354.49077
[103]	validation_0-mae:2349.03839
[104]	validation_0-mae:2346.53603
[105]	validation_0-mae:2338.53071
[106]	validation_0-mae:2333.59324
[107]	validation_0-mae:2332.08831
[108]	validation_0-mae:2327.77878
[109]	validation_0-mae:2323.30200
[110]	validation_0-mae:2320.74932
[111]	validation_0-mae:2318.51065
[112]	validation_0-mae:2312.38455
[113]	validation_0-mae:2310.16118
[114]	validation_0-mae:2307.71073
[115]	validation_0-mae:2302.61153
[116]	validation_0-mae:2297.30845
[117]	validation_0-mae:2296.61297
[118]	validation_0-mae:2292.95279
[119]	validation_0-mae:2288.96123
[120]	validation_0-mae:2288.46026
[121]	validation_0-mae:2285.38883
[122]	validation_0-mae:2285.54670
[123]	validation_0-mae:2284.34885
[124]	validation_0-mae:2280.42390
[125]	validation_0-mae:2277.47472
[126]	validation_0-mae:2272.89872
[127]	validation_0-mae:2269.37343
[128]	validation_0-mae:2266.29142
[129]	validation_0-mae:2261.52001
[130]	validation_0-mae:2258.47118
[131]	validation_0-mae:2256.94930
[132]	validation_0-mae:2255.56883
[133]	validation_0-mae:2253.05192
[134]	validation_0-mae:2250.19454
[135]	validation_0-mae:2246.40022
[136]	validation_0-mae:2246.00357
[137]	validation_0-mae:2242.31888
[138]	validation_0-mae:2243.01572
[139]	validation_0-mae:2242.19674
[140]	validation_0-mae:2241.27751
[141]	validation_0-mae:2238.14674
[142]	validation_0-mae:2235.24259
[143]	validation_0-mae:2234.38531
[144]	validation_0-mae:2234.58247
[145]	validation_0-mae:2232.50486
[146]	validation_0-mae:2228.80836
[147]	validation_0-mae:2226.52586
[148]	validation_0-mae:2226.00526
[149]	validation_0-mae:2224.20172
[150]	validation_0-mae:2223.26485
[151]	validation_0-mae:2219.75775
[152]	validation_0-mae:2220.85876
[153]	validation_0-mae:2221.71315
[154]	validation_0-mae:2216.81417
[155]	validation_0-mae:2214.05799
[156]	validation_0-mae:2215.25673
[157]	validation_0-mae:2210.66259
[158]	validation_0-mae:2209.89822
[159]	validation_0-mae:2210.89390
[160]	validation_0-mae:2210.95797
[161]	validation_0-mae:2209.64680
[162]	validation_0-mae:2207.11927
[163]	validation_0-mae:2205.08663
[164]	validation_0-mae:2204.48106
[165]	validation_0-mae:2201.32897
[166]	validation_0-mae:2202.39603
[167]	validation_0-mae:2202.19961
[168]	validation_0-mae:2202.40184
[169]	validation_0-mae:2199.07756
[170]	validation_0-mae:2196.78886
[171]	validation_0-mae:2193.75758
[172]	validation_0-mae:2190.38603
[173]	validation_0-mae:2189.91240
[174]	validation_0-mae:2190.05375
[175]	validation_0-mae:2187.04853
[176]	validation_0-mae:2185.76438
[177]	validation_0-mae:2184.43421
[178]	validation_0-mae:2182.44617
[179]	validation_0-mae:2180.71843
[180]	validation_0-mae:2178.13276
[181]	validation_0-mae:2175.41404
[182]	validation_0-mae:2175.78749
[183]	validation_0-mae:2175.41764
[184]	validation_0-mae:2175.82564
[185]	validation_0-mae:2175.21996
[186]	validation_0-mae:2175.74893
[187]	validation_0-mae:2174.61566
[188]	validation_0-mae:2174.87927
[189]	validation_0-mae:2173.52953
[190]	validation_0-mae:2172.08512
[191]	validation_0-mae:2169.98109
[192]	validation_0-mae:2167.44039
[193]	validation_0-mae:2166.91372
[194]	validation_0-mae:2165.68811
[195]	validation_0-mae:2163.83745
[196]	validation_0-mae:2162.21197
[197]	validation_0-mae:2161.13528
[198]	validation_0-mae:2160.75819
[199]	validation_0-mae:2158.75016
[200]	validation_0-mae:2157.80940
[201]	validation_0-mae:2157.54421
[202]	validation_0-mae:2158.56050
[203]	validation_0-mae:2158.30238
[204]	validation_0-mae:2155.19628
[205]	validation_0-mae:2155.10613
[206]	validation_0-mae:2152.95776
[207]	validation_0-mae:2151.71140
[208]	validation_0-mae:2151.04783
[209]	validation_0-mae:2150.89400
[210]	validation_0-mae:2150.13881
[211]	validation_0-mae:2149.21366
[212]	validation_0-mae:2147.47345
[213]	validation_0-mae:2145.72902
[214]	validation_0-mae:2145.91673
[215]	validation_0-mae:2144.70490
[216]	validation_0-mae:2142.76584
[217]	validation_0-mae:2140.99371
[218]	validation_0-mae:2139.92683
[219]	validation_0-mae:2139.78680
[220]	validation_0-mae:2138.35144
[221]	validation_0-mae:2138.38043
[222]	validation_0-mae:2137.88756
[223]	validation_0-mae:2137.38704
[224]	validation_0-mae:2136.71065
[225]	validation_0-mae:2133.99249
[226]	validation_0-mae:2131.41640
[227]	validation_0-mae:2130.00672
[228]	validation_0-mae:2128.33601
[229]	validation_0-mae:2128.99416
[230]	validation_0-mae:2128.35218
[231]	validation_0-mae:2128.28391
[232]	validation_0-mae:2128.15347
[233]	validation_0-mae:2128.75876
[234]	validation_0-mae:2127.49510
[235]	validation_0-mae:2126.21472
[236]	validation_0-mae:2126.29846
[237]	validation_0-mae:2127.02098
[238]	validation_0-mae:2127.44772
[239]	validation_0-mae:2125.94589
[240]	validation_0-mae:2126.04847
[241]	validation_0-mae:2124.25692
[242]	validation_0-mae:2123.18964
[243]	validation_0-mae:2121.07055
[244]	validation_0-mae:2120.02560
[245]	validation_0-mae:2120.08805
[246]	validation_0-mae:2117.54599
[247]	validation_0-mae:2116.74906
[248]	validation_0-mae:2115.38301
[249]	validation_0-mae:2112.68141
[250]	validation_0-mae:2112.46205
[251]	validation_0-mae:2111.68099
[252]	validation_0-mae:2111.30029
[253]	validation_0-mae:2110.92434
[254]	validation_0-mae:2109.69287
[255]	validation_0-mae:2108.73712
[256]	validation_0-mae:2108.66654
[257]	validation_0-mae:2106.99724
[258]	validation_0-mae:2106.50186
[259]	validation_0-mae:2106.66508
[260]	validation_0-mae:2105.65630
[261]	validation_0-mae:2102.80561
[262]	validation_0-mae:2102.59457
[263]	validation_0-mae:2103.58629
[264]	validation_0-mae:2101.73488
[265]	validation_0-mae:2101.75315
[266]	validation_0-mae:2101.10698
[267]	validation_0-mae:2099.70259
[268]	validation_0-mae:2099.83115
[269]	validation_0-mae:2099.55689
[270]	validation_0-mae:2098.49886
[271]	validation_0-mae:2096.91128
[272]	validation_0-mae:2096.59726
[273]	validation_0-mae:2096.10493
[274]	validation_0-mae:2095.37157
[275]	validation_0-mae:2094.93814
[276]	validation_0-mae:2095.85393
[277]	validation_0-mae:2095.27204
[278]	validation_0-mae:2094.71478
[279]	validation_0-mae:2094.34076
[280]	validation_0-mae:2094.79206
[281]	validation_0-mae:2094.25295
[282]	validation_0-mae:2093.16173
[283]	validation_0-mae:2093.79561
[284]	validation_0-mae:2092.71166
[285]	validation_0-mae:2092.17764
[286]	validation_0-mae:2092.45725
[287]	validation_0-mae:2092.40654
[288]	validation_0-mae:2090.95339
[289]	validation_0-mae:2090.21977
[290]	validation_0-mae:2089.92794
[291]	validation_0-mae:2089.42172
[292]	validation_0-mae:2089.07466
[293]	validation_0-mae:2088.31450
[294]	validation_0-mae:2088.56013
[295]	validation_0-mae:2087.73008
[296]	validation_0-mae:2087.45150
[297]	validation_0-mae:2088.27998
[298]	validation_0-mae:2088.04280
[299]	validation_0-mae:2088.47283
[300]	validation_0-mae:2088.73637
[301]	validation_0-mae:2088.24451
[302]	validation_0-mae:2088.11539
[303]	validation_0-mae:2088.09585
[304]	validation_0-mae:2087.21387
[305]	validation_0-mae:2085.86614
[306]	validation_0-mae:2085.46912
[307]	validation_0-mae:2084.84810
[308]	validation_0-mae:2085.09145
[309]	validation_0-mae:2085.15262
[310]	validation_0-mae:2084.91157
[311]	validation_0-mae:2084.61822
[312]	validation_0-mae:2085.35732
[313]	validation_0-mae:2085.23119
[314]	validation_0-mae:2083.94668
[315]	validation_0-mae:2083.82034
[316]	validation_0-mae:2083.84372
[317]	validation_0-mae:2084.34425
[318]	validation_0-mae:2084.58112
[319]	validation_0-mae:2083.91765
[320]	validation_0-mae:2083.48544
[321]	validation_0-mae:2083.08172
[322]	validation_0-mae:2083.10724
[323]	validation_0-mae:2080.94772
[324]	validation_0-mae:2080.95963
[325]	validation_0-mae:2080.48201
[326]	validation_0-mae:2079.96005
[327]	validation_0-mae:2079.27209
[328]	validation_0-mae:2079.22251
[329]	validation_0-mae:2078.89433
[330]	validation_0-mae:2078.49021
[331]	validation_0-mae:2078.67375
[332]	validation_0-mae:2078.36556
[333]	validation_0-mae:2078.46111
[334]	validation_0-mae:2077.93419
[335]	validation_0-mae:2077.82656
[336]	validation_0-mae:2078.08056
[337]	validation_0-mae:2078.56124
[338]	validation_0-mae:2078.92709
[339]	validation_0-mae:2078.81230
[340]	validation_0-mae:2078.41405
[341]	validation_0-mae:2078.62118
[342]	validation_0-mae:2078.73026
[343]	validation_0-mae:2078.27661
[344]	validation_0-mae:2078.21365
[345]	validation_0-mae:2078.93738
[346]	validation_0-mae:2078.45447
[347]	validation_0-mae:2078.53583
[348]	validation_0-mae:2079.34499
[349]	validation_0-mae:2079.44469
[350]	validation_0-mae:2078.55384
[351]	validation_0-mae:2079.10241
[352]	validation_0-mae:2079.62290
[353]	validation_0-mae:2079.06120
[354]	validation_0-mae:2079.23685
[355]	validation_0-mae:2079.01000
[356]	validation_0-mae:2079.21949
[357]	validation_0-mae:2078.89215
[358]	validation_0-mae:2079.05054
[359]	validation_0-mae:2078.84292
[360]	validation_0-mae:2078.59093
[361]	validation_0-mae:2079.25562
[362]	validation_0-mae:2079.33542
[363]	validation_0-mae:2079.51580
[364]	validation_0-mae:2079.30308
[365]	validation_0-mae:2078.78357
[366]	validation_0-mae:2078.97120
[367]	validation_0-mae:2077.89737
[368]	validation_0-mae:2078.15015
[369]	validation_0-mae:2077.99622
[370]	validation_0-mae:2076.93381
[371]	validation_0-mae:2076.77817
[372]	validation_0-mae:2076.78285
[373]	validation_0-mae:2076.81862
[374]	validation_0-mae:2076.46509
[375]	validation_0-mae:2075.73626
[376]	validation_0-mae:2075.22766
[377]	validation_0-mae:2074.97326
[378]	validation_0-mae:2074.62195
[379]	validation_0-mae:2073.82856
[380]	validation_0-mae:2073.79675
[381]	validation_0-mae:2074.46826
[382]	validation_0-mae:2073.49194
[383]	validation_0-mae:2073.99592
[384]	validation_0-mae:2074.01682
[385]	validation_0-mae:2073.58862
[386]	validation_0-mae:2073.30677
[387]	validation_0-mae:2072.72657
[388]	validation_0-mae:2072.04316
[389]	validation_0-mae:2071.73662
[390]	validation_0-mae:2071.49672
[391]	validation_0-mae:2071.92755
[392]	validation_0-mae:2071.85683
[393]	validation_0-mae:2071.67261
[394]	validation_0-mae:2070.52102
[395]	validation_0-mae:2070.39562
[396]	validation_0-mae:2070.37321
[397]	validation_0-mae:2070.57596
[398]	validation_0-mae:2070.25986
[399]	validation_0-mae:2069.91943
[400]	validation_0-mae:2070.58409
[401]	validation_0-mae:2070.21248
[402]	validation_0-mae:2069.97394
[403]	validation_0-mae:2069.79572
[404]	validation_0-mae:2069.69528
[405]	validation_0-mae:2069.86545
[406]	validation_0-mae:2069.96619
[407]	validation_0-mae:2069.87677
[408]	validation_0-mae:2069.76909
[409]	validation_0-mae:2069.42402
[410]	validation_0-mae:2069.17645
[411]	validation_0-mae:2068.77358
[412]	validation_0-mae:2068.66456
[413]	validation_0-mae:2068.67518
[414]	validation_0-mae:2068.87812
[415]	validation_0-mae:2069.09425
[416]	validation_0-mae:2069.62730
[417]	validation_0-mae:2068.54063
[418]	validation_0-mae:2068.66740
[419]	validation_0-mae:2067.67074
[420]	validation_0-mae:2068.16625
[421]	validation_0-mae:2068.37333
[422]	validation_0-mae:2067.42588
[423]	validation_0-mae:2067.02621
[424]	validation_0-mae:2067.15956
[425]	validation_0-mae:2067.26510
[426]	validation_0-mae:2066.99252
[427]	validation_0-mae:2067.40927
[428]	validation_0-mae:2067.01243
[429]	validation_0-mae:2066.87742
[430]	validation_0-mae:2066.85399
[431]	validation_0-mae:2066.88047
[432]	validation_0-mae:2067.29813
[433]	validation_0-mae:2067.46698
[434]	validation_0-mae:2067.25038
[435]	validation_0-mae:2066.85962
[436]	validation_0-mae:2065.61328
[437]	validation_0-mae:2065.83435
[438]	validation_0-mae:2065.82618
[439]	validation_0-mae:2065.85026
[440]	validation_0-mae:2066.06191
[441]	validation_0-mae:2066.17068
[442]	validation_0-mae:2065.94393
[443]	validation_0-mae:2065.68940
[444]	validation_0-mae:2065.63071
[445]	validation_0-mae:2065.76066
[446]	validation_0-mae:2065.07554
[447]	validation_0-mae:2065.12269
[448]	validation_0-mae:2065.23038
[449]	validation_0-mae:2065.31568
[450]	validation_0-mae:2064.07261
[451]	validation_0-mae:2063.84011
[452]	validation_0-mae:2063.75024
[453]	validation_0-mae:2063.97252
[454]	validation_0-mae:2064.01170
[455]	validation_0-mae:2063.17275
[456]	validation_0-mae:2063.53299
[457]	validation_0-mae:2063.87091
[458]	validation_0-mae:2064.00719
[459]	validation_0-mae:2064.33410
[460]	validation_0-mae:2064.65359
[461]	validation_0-mae:2064.20846
[462]	validation_0-mae:2063.76466
[463]	validation_0-mae:2063.26320
[464]	validation_0-mae:2063.01575
[465]	validation_0-mae:2062.65654
[466]	validation_0-mae:2063.08981
[467]	validation_0-mae:2063.06816
[468]	validation_0-mae:2063.74791
[469]	validation_0-mae:2063.27652
[470]	validation_0-mae:2063.56259
[471]	validation_0-mae:2063.32763
[472]	validation_0-mae:2063.32979
[473]	validation_0-mae:2063.63835
[474]	validation_0-mae:2063.92957
[475]	validation_0-mae:2064.13599
[476]	validation_0-mae:2064.09419
[477]	validation_0-mae:2063.90179
[478]	validation_0-mae:2064.06830
[479]	validation_0-mae:2063.77508
[480]	validation_0-mae:2063.94287
[481]	validation_0-mae:2063.83316
[482]	validation_0-mae:2063.35228
[483]	validation_0-mae:2063.10972
[484]	validation_0-mae:2063.29061
[485]	validation_0-mae:2062.87261
[486]	validation_0-mae:2062.75813
[487]	validation_0-mae:2062.94097
[488]	validation_0-mae:2063.15750
[489]	validation_0-mae:2063.19776
[490]	validation_0-mae:2062.99345
[491]	validation_0-mae:2063.09256
[492]	validation_0-mae:2062.81030
[493]	validation_0-mae:2063.20157
[494]	validation_0-mae:2063.13836
[495]	validation_0-mae:2063.11789
[496]	validation_0-mae:2063.24931
[497]	validation_0-mae:2063.40166
[498]	validation_0-mae:2063.15529
[499]	validation_0-mae:2062.85697
[500]	validation_0-mae:2062.64873
[501]	validation_0-mae:2062.43394
[502]	validation_0-mae:2062.22171
[503]	validation_0-mae:2062.31361
[504]	validation_0-mae:2062.73476
[505]	validation_0-mae:2062.45816
[506]	validation_0-mae:2062.50856
[507]	validation_0-mae:2062.46377
[508]	validation_0-mae:2061.92445
[509]	validation_0-mae:2061.77745
[510]	validation_0-mae:2061.95679
[511]	validation_0-mae:2061.86485
[512]	validation_0-mae:2061.42292
[513]	validation_0-mae:2060.93012
[514]	validation_0-mae:2060.96039
[515]	validation_0-mae:2060.82570
[516]	validation_0-mae:2060.69054
[517]	validation_0-mae:2060.48613
[518]	validation_0-mae:2060.58840
[519]	validation_0-mae:2059.89817
[520]	validation_0-mae:2059.35800
[521]	validation_0-mae:2059.64683
[522]	validation_0-mae:2059.60053
[523]	validation_0-mae:2059.62256
[524]	validation_0-mae:2059.60219
[525]	validation_0-mae:2059.81776
[526]	validation_0-mae:2059.88044
[527]	validation_0-mae:2060.07482
[528]	validation_0-mae:2059.95984
[529]	validation_0-mae:2060.14674
[530]	validation_0-mae:2060.27551
[531]	validation_0-mae:2060.00485
[532]	validation_0-mae:2060.10970
[533]	validation_0-mae:2060.37420
[534]	validation_0-mae:2060.85507
[535]	validation_0-mae:2060.78931
[536]	validation_0-mae:2061.06876
[537]	validation_0-mae:2060.95069
[538]	validation_0-mae:2061.35845
[539]	validation_0-mae:2061.62885
[540]	validation_0-mae:2061.72796
[541]	validation_0-mae:2061.75761
[542]	validation_0-mae:2062.06953
[543]	validation_0-mae:2062.21539
[544]	validation_0-mae:2061.65037
[545]	validation_0-mae:2060.59835
[546]	validation_0-mae:2060.72001
[547]	validation_0-mae:2060.51973
[548]	validation_0-mae:2060.42165
[549]	validation_0-mae:2060.31400
[550]	validation_0-mae:2059.82653
[551]	validation_0-mae:2059.73671
[552]	validation_0-mae:2059.75815
[553]	validation_0-mae:2059.57893
[554]	validation_0-mae:2059.28207
[555]	validation_0-mae:2059.28704
[556]	validation_0-mae:2059.37997
[557]	validation_0-mae:2059.67919
[558]	validation_0-mae:2059.60804
[559]	validation_0-mae:2059.57286
[560]	validation_0-mae:2059.36927
[561]	validation_0-mae:2059.42631
[562]	validation_0-mae:2059.76616
[563]	validation_0-mae:2059.83447
[564]	validation_0-mae:2059.99995
[565]	validation_0-mae:2060.13082
[566]	validation_0-mae:2060.21504
[567]	validation_0-mae:2060.26499
[568]	validation_0-mae:2060.36174
[569]	validation_0-mae:2060.27938
[570]	validation_0-mae:2060.36828
[571]	validation_0-mae:2060.43546
[572]	validation_0-mae:2060.74025
[573]	validation_0-mae:2060.19835
[574]	validation_0-mae:2060.19056
[575]	validation_0-mae:2060.40171
[576]	validation_0-mae:2060.59694
[577]	validation_0-mae:2061.04688
[578]	validation_0-mae:2061.13914
[579]	validation_0-mae:2061.11533
[580]	validation_0-mae:2060.70285
[581]	validation_0-mae:2060.57237
[582]	validation_0-mae:2060.92449
[583]	validation_0-mae:2060.88586
[584]	validation_0-mae:2060.94627
[585]	validation_0-mae:2060.61279
[586]	validation_0-mae:2060.54308
[587]	validation_0-mae:2060.31638
[588]	validation_0-mae:2060.25775
[589]	validation_0-mae:2060.40753
[590]	validation_0-mae:2060.35022
[591]	validation_0-mae:2060.35397
[592]	validation_0-mae:2060.20552
[593]	validation_0-mae:2060.27122
[594]	validation_0-mae:2060.26533
[595]	validation_0-mae:2060.14685
[596]	validation_0-mae:2060.19842
[597]	validation_0-mae:2060.48052
[598]	validation_0-mae:2060.44088
[599]	validation_0-mae:2060.55276
[600]	validation_0-mae:2060.58299
[601]	validation_0-mae:2060.71751
[602]	validation_0-mae:2060.72616
[603]	validation_0-mae:2060.94539
[604]	validation_0-mae:2061.15593
[605]	validation_0-mae:2061.38657
[606]	validation_0-mae:2061.37440
[607]	validation_0-mae:2061.31982
[608]	validation_0-mae:2061.40132
[609]	validation_0-mae:2061.51064
[610]	validation_0-mae:2061.43513
[611]	validation_0-mae:2061.48105
[612]	validation_0-mae:2061.56689
[613]	validation_0-mae:2061.54147
[614]	validation_0-mae:2061.13226
[615]	validation_0-mae:2060.88954
[616]	validation_0-mae:2060.72059
[617]	validation_0-mae:2060.66245
[618]	validation_0-mae:2060.64482
[619]	validation_0-mae:2060.66971
[620]	validation_0-mae:2060.70159
[621]	validation_0-mae:2060.73753
[622]	validation_0-mae:2060.61373
[623]	validation_0-mae:2060.72866
[624]	validation_0-mae:2060.77383
[625]	validation_0-mae:2060.88738
[626]	validation_0-mae:2060.71905
[627]	validation_0-mae:2060.64891
[628]	validation_0-mae:2061.08681
[629]	validation_0-mae:2060.95006
[630]	validation_0-mae:2061.17396
[631]	validation_0-mae:2061.08534

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[43]	validation_0-mae:3273.18187
[44]	validation_0-mae:3233.26858
[45]	validation_0-mae:3200.75999
[46]	validation_0-mae:3163.00257
[47]	validation_0-mae:3124.01380
[48]	validation_0-mae:3090.99628
[49]	validation_0-mae:3066.45363
[50]	validation_0-mae:3031.36674
[51]	validation_0-mae:3003.29382
[52]	validation_0-mae:2977.24713
[53]	validation_0-mae:2955.04143
[54]	validation_0-mae:2930.22794
[55]	validation_0-mae:2894.52994
[56]	validation_0-mae:2874.16139
[57]	validation_0-mae:2850.51581
[58]	validation_0-mae:2837.16175
[59]	validation_0-mae:2819.83237
[60]	validation_0-mae:2804.16284
[61]	validation_0-mae:2791.32388
[62]	validation_0-mae:2778.45884
[63]	validation_0-mae:2768.11115
[64]	validation_0-mae:2749.84394
[65]	validation_0-mae:2729.98456
[66]	validation_0-mae:2703.74664
[67]	validation_0-mae:2695.29327
[68]	validation_0-mae:2684.82110
[69]	validation_0-mae:2674.48049
[70]	validation_0-mae:2665.10539
[71]	validation_0-mae:2649.89053
[72]	validation_0-mae:2633.36848
[73]	validation_0-mae:2615.72480
[74]	validation_0-mae:2607.62384
[75]	validation_0-mae:2597.35678
[76]	validation_0-mae:2591.90780
[77]	validation_0-mae:2577.59904
[78]	validation_0-mae:2559.85149
[79]	validation_0-mae:2549.97322
[80]	validation_0-mae:2539.17904
[81]	validation_0-mae:2531.03937
[82]	validation_0-mae:2520.80711
[83]	validation_0-mae:2507.09316
[84]	validation_0-mae:2500.17196
[85]	validation_0-mae:2496.18566
[86]	validation_0-mae:2489.22888
[87]	validation_0-mae:2479.89523
[88]	validation_0-mae:2464.20650
[89]	validation_0-mae:2459.39267
[90]	validation_0-mae:2451.21775
[91]	validation_0-mae:2437.05153
[92]	validation_0-mae:2423.12393
[93]	validation_0-mae:2417.55982
[94]	validation_0-mae:2406.18093
[95]	validation_0-mae:2399.50486
[96]	validation_0-mae:2393.34564
[97]	validation_0-mae:2384.19847
[98]	validation_0-mae:2377.83373
[99]	validation_0-mae:2371.15421
[100]	validation_0-mae:2364.41015
[101]	validation_0-mae:2359.80582
[102]	validation_0-mae:2356.43360
[103]	validation_0-mae:2351.21495
[104]	validation_0-mae:2348.22579
[105]	validation_0-mae:2333.90988
[106]	validation_0-mae:2330.09816
[107]	validation_0-mae:2324.81014
[108]	validation_0-mae:2319.50976
[109]	validation_0-mae:2316.78561
[110]	validation_0-mae:2315.11710
[111]	validation_0-mae:2312.17292
[112]	validation_0-mae:2311.06233
[113]	validation_0-mae:2308.34399
[114]	validation_0-mae:2303.08486
[115]	validation_0-mae:2299.22277
[116]	validation_0-mae:2292.58359
[117]	validation_0-mae:2289.80016
[118]	validation_0-mae:2286.13013
[119]	validation_0-mae:2283.91383
[120]	validation_0-mae:2279.45275
[121]	validation_0-mae:2275.86863
[122]	validation_0-mae:2271.43378
[123]	validation_0-mae:2268.13967
[124]	validation_0-mae:2266.90096
[125]	validation_0-mae:2264.83036
[126]	validation_0-mae:2263.95431
[127]	validation_0-mae:2264.06842
[128]	validation_0-mae:2258.20103
[129]	validation_0-mae:2256.78035
[130]	validation_0-mae:2256.00625
[131]	validation_0-mae:2252.54627
[132]	validation_0-mae:2252.27186
[133]	validation_0-mae:2249.55682
[134]	validation_0-mae:2247.00785
[135]	validation_0-mae:2244.78477
[136]	validation_0-mae:2242.72276
[137]	validation_0-mae:2241.27466
[138]	validation_0-mae:2241.31169
[139]	validation_0-mae:2239.61534
[140]	validation_0-mae:2235.67739
[141]	validation_0-mae:2235.08801
[142]	validation_0-mae:2234.55505
[143]	validation_0-mae:2233.40830
[144]	validation_0-mae:2229.34591
[145]	validation_0-mae:2228.42720
[146]	validation_0-mae:2223.66768
[147]	validation_0-mae:2222.32784
[148]	validation_0-mae:2218.47737
[149]	validation_0-mae:2216.94831
[150]	validation_0-mae:2212.95988
[151]	validation_0-mae:2212.89052
[152]	validation_0-mae:2212.32596
[153]	validation_0-mae:2211.70848
[154]	validation_0-mae:2207.32377
[155]	validation_0-mae:2207.19109
[156]	validation_0-mae:2204.97413
[157]	validation_0-mae:2201.36819
[158]	validation_0-mae:2200.52911
[159]	validation_0-mae:2197.84213
[160]	validation_0-mae:2197.74332
[161]	validation_0-mae:2195.86338
[162]	validation_0-mae:2195.15700
[163]	validation_0-mae:2195.25881
[164]	validation_0-mae:2194.53505
[165]	validation_0-mae:2194.11291
[166]	validation_0-mae:2193.79803
[167]	validation_0-mae:2191.05531
[168]	validation_0-mae:2190.05929
[169]	validation_0-mae:2189.40658
[170]	validation_0-mae:2186.99489
[171]	validation_0-mae:2185.10040
[172]	validation_0-mae:2184.58889
[173]	validation_0-mae:2184.52995
[174]	validation_0-mae:2184.89726
[175]	validation_0-mae:2185.93787
[176]	validation_0-mae:2186.26225
[177]	validation_0-mae:2185.54968
[178]	validation_0-mae:2184.44722
[179]	validation_0-mae:2183.06769
[180]	validation_0-mae:2181.99712
[181]	validation_0-mae:2179.47199
[182]	validation_0-mae:2179.35604
[183]	validation_0-mae:2176.55238
[184]	validation_0-mae:2173.88720
[185]	validation_0-mae:2173.69252
[186]	validation_0-mae:2173.01531
[187]	validation_0-mae:2171.41392
[188]	validation_0-mae:2171.50674
[189]	validation_0-mae:2167.95067
[190]	validation_0-mae:2165.26465
[191]	validation_0-mae:2164.58254
[192]	validation_0-mae:2163.66032
[193]	validation_0-mae:2163.66306
[194]	validation_0-mae:2162.21719
[195]	validation_0-mae:2163.01091
[196]	validation_0-mae:2162.36105
[197]	validation_0-mae:2161.74300
[198]	validation_0-mae:2161.24268
[199]	validation_0-mae:2160.48225
[200]	validation_0-mae:2159.45136
[201]	validation_0-mae:2158.61712
[202]	validation_0-mae:2159.24368
[203]	validation_0-mae:2157.53891
[204]	validation_0-mae:2158.04200
[205]	validation_0-mae:2158.23094
[206]	validation_0-mae:2158.19458
[207]	validation_0-mae:2157.57555
[208]	validation_0-mae:2157.99823
[209]	validation_0-mae:2157.26774
[210]	validation_0-mae:2156.84675
[211]	validation_0-mae:2156.38650
[212]	validation_0-mae:2155.98814
[213]	validation_0-mae:2156.01680
[214]	validation_0-mae:2154.87666
[215]	validation_0-mae:2155.12351
[216]	validation_0-mae:2154.13236
[217]	validation_0-mae:2153.93972
[218]	validation_0-mae:2153.26009
[219]	validation_0-mae:2152.72305
[220]	validation_0-mae:2152.57049
[221]	validation_0-mae:2152.44376
[222]	validation_0-mae:2153.27482
[223]	validation_0-mae:2152.72753
[224]	validation_0-mae:2151.26327
[225]	validation_0-mae:2150.33335
[226]	validation_0-mae:2149.89922
[227]	validation_0-mae:2149.78456
[228]	validation_0-mae:2149.03325
[229]	validation_0-mae:2148.77017
[230]	validation_0-mae:2148.91083
[231]	validation_0-mae:2148.87649
[232]	validation_0-mae:2148.89937
[233]	validation_0-mae:2148.49848
[234]	validation_0-mae:2148.63583
[235]	validation_0-mae:2148.16160
[236]	validation_0-mae:2147.85281
[237]	validation_0-mae:2148.36850
[238]	validation_0-mae:2148.15426
[239]	validation_0-mae:2148.85478
[240]	validation_0-mae:2149.15422
[241]	validation_0-mae:2148.92600
[242]	validation_0-mae:2148.28204
[243]	validation_0-mae:2147.93553
[244]	validation_0-mae:2148.46047
[245]	validation_0-mae:2148.33510
[246]	validation_0-mae:2148.36819
[247]	validation_0-mae:2146.56207
[248]	validation_0-mae:2147.63863
[249]	validation_0-mae:2147.43581
[250]	validation_0-mae:2147.10218
[251]	validation_0-mae:2146.66689
[252]	validation_0-mae:2145.41398
[253]	validation_0-mae:2145.70982
[254]	validation_0-mae:2144.20972
[255]	validation_0-mae:2144.04070
[256]	validation_0-mae:2143.03597
[257]	validation_0-mae:2143.27433
[258]	validation_0-mae:2143.18142
[259]	validation_0-mae:2141.10961
[260]	validation_0-mae:2140.97469
[261]	validation_0-mae:2141.19893
[262]	validation_0-mae:2141.43791
[263]	validation_0-mae:2141.00719
[264]	validation_0-mae:2142.16913
[265]	validation_0-mae:2141.62787
[266]	validation_0-mae:2141.74138
[267]	validation_0-mae:2141.07902
[268]	validation_0-mae:2140.75305
[269]	validation_0-mae:2139.42236
[270]	validation_0-mae:2138.72549
[271]	validation_0-mae:2136.37943
[272]	validation_0-mae:2136.27260
[273]	validation_0-mae:2135.75850
[274]	validation_0-mae:2135.86101
[275]	validation_0-mae:2135.30782
[276]	validation_0-mae:2134.76874
[277]	validation_0-mae:2133.61387
[278]	validation_0-mae:2133.69457
[279]	validation_0-mae:2133.65576
[280]	validation_0-mae:2133.17208
[281]	validation_0-mae:2133.83283
[282]	validation_0-mae:2133.98879
[283]	validation_0-mae:2134.18019
[284]	validation_0-mae:2133.27506
[285]	validation_0-mae:2133.65650
[286]	validation_0-mae:2133.33674
[287]	validation_0-mae:2134.03320
[288]	validation_0-mae:2134.65935
[289]	validation_0-mae:2134.23004
[290]	validation_0-mae:2134.89007
[291]	validation_0-mae:2134.68333
[292]	validation_0-mae:2134.18427
[293]	validation_0-mae:2133.38807
[294]	validation_0-mae:2133.34482
[295]	validation_0-mae:2132.86450
[296]	validation_0-mae:2133.26673
[297]	validation_0-mae:2133.65670
[298]	validation_0-mae:2133.28964
[299]	validation_0-mae:2133.37584
[300]	validation_0-mae:2133.92657
[301]	validation_0-mae:2134.38395
[302]	validation_0-mae:2135.15426
[303]	validation_0-mae:2135.23439
[304]	validation_0-mae:2134.66672
[305]	validation_0-mae:2134.85334
[306]	validation_0-mae:2134.22269
[307]	validation_0-mae:2134.79168
[308]	validation_0-mae:2134.61382
[309]	validation_0-mae:2134.31233
[310]	validation_0-mae:2133.68021
[311]	validation_0-mae:2133.25226
[312]	validation_0-mae:2133.49405
[313]	validation_0-mae:2133.50026
[314]	validation_0-mae:2133.37865
[315]	validation_0-mae:2132.37607
[316]	validation_0-mae:2132.98991
[317]	validation_0-mae:2132.52507
[318]	validation_0-mae:2133.37482
[319]	validation_0-mae:2133.24847
[320]	validation_0-mae:2133.72572
[321]	validation_0-mae:2133.76791
[322]	validation_0-mae:2133.52934
[323]	validation_0-mae:2133.84471
[324]	validation_0-mae:2133.68459
[325]	validation_0-mae:2133.56387
[326]	validation_0-mae:2132.96273
[327]	validation_0-mae:2131.35737
[328]	validation_0-mae:2130.68115
[329]	validation_0-mae:2130.25210
[330]	validation_0-mae:2128.91099
[331]	validation_0-mae:2129.52563
[332]	validation_0-mae:2128.69432
[333]	validation_0-mae:2128.52039
[334]	validation_0-mae:2128.58693
[335]	validation_0-mae:2128.64672
[336]	validation_0-mae:2128.56087
[337]	validation_0-mae:2128.72857
[338]	validation_0-mae:2129.13296
[339]	validation_0-mae:2127.14419
[340]	validation_0-mae:2127.36660
[341]	validation_0-mae:2126.93093
[342]	validation_0-mae:2126.73731
[343]	validation_0-mae:2126.23721
[344]	validation_0-mae:2126.14785
[345]	validation_0-mae:2125.44732
[346]	validation_0-mae:2125.40870
[347]	validation_0-mae:2123.23208
[348]	validation_0-mae:2123.67665
[349]	validation_0-mae:2123.42096
[350]	validation_0-mae:2122.44420
[351]	validation_0-mae:2120.26174
[352]	validation_0-mae:2120.24016
[353]	validation_0-mae:2120.28572
[354]	validation_0-mae:2119.29435
[355]	validation_0-mae:2117.00734
[356]	validation_0-mae:2116.94029
[357]	validation_0-mae:2116.68733
[358]	validation_0-mae:2116.80155
[359]	validation_0-mae:2116.47207
[360]	validation_0-mae:2115.89379
[361]	validation_0-mae:2115.98235
[362]	validation_0-mae:2114.53968
[363]	validation_0-mae:2112.55596
[364]	validation_0-mae:2112.10474
[365]	validation_0-mae:2111.79692
[366]	validation_0-mae:2111.60921
[367]	validation_0-mae:2111.25619
[368]	validation_0-mae:2110.77472
[369]	validation_0-mae:2110.28115
[370]	validation_0-mae:2110.00682
[371]	validation_0-mae:2110.45542
[372]	validation_0-mae:2110.13097
[373]	validation_0-mae:2109.99822
[374]	validation_0-mae:2108.84614
[375]	validation_0-mae:2109.43984
[376]	validation_0-mae:2109.45784
[377]	validation_0-mae:2109.26655
[378]	validation_0-mae:2109.23889
[379]	validation_0-mae:2108.28206
[380]	validation_0-mae:2108.12287
[381]	validation_0-mae:2107.60534
[382]	validation_0-mae:2107.01480
[383]	validation_0-mae:2107.06438
[384]	validation_0-mae:2106.68551
[385]	validation_0-mae:2106.55014
[386]	validation_0-mae:2106.52116
[387]	validation_0-mae:2106.44960
[388]	validation_0-mae:2106.62377
[389]	validation_0-mae:2105.92683
[390]	validation_0-mae:2106.75961
[391]	validation_0-mae:2105.72100
[392]	validation_0-mae:2105.90721
[393]	validation_0-mae:2105.65560
[394]	validation_0-mae:2105.71370
[395]	validation_0-mae:2105.27962
[396]	validation_0-mae:2105.29060
[397]	validation_0-mae:2105.13621
[398]	validation_0-mae:2104.42318
[399]	validation_0-mae:2103.35462
[400]	validation_0-mae:2102.94452
[401]	validation_0-mae:2104.10680
[402]	validation_0-mae:2103.68387
[403]	validation_0-mae:2103.82306
[404]	validation_0-mae:2103.33239
[405]	validation_0-mae:2103.57868
[406]	validation_0-mae:2103.77353
[407]	validation_0-mae:2103.81955
[408]	validation_0-mae:2103.70207
[409]	validation_0-mae:2103.70709
[410]	validation_0-mae:2103.80944
[411]	validation_0-mae:2103.44681
[412]	validation_0-mae:2102.63997
[413]	validation_0-mae:2102.41789
[414]	validation_0-mae:2102.74557
[415]	validation_0-mae:2102.85397
[416]	validation_0-mae:2101.61842
[417]	validation_0-mae:2100.77686
[418]	validation_0-mae:2099.64852
[419]	validation_0-mae:2099.05033
[420]	validation_0-mae:2098.53118
[421]	validation_0-mae:2097.92825
[422]	validation_0-mae:2097.55264
[423]	validation_0-mae:2097.51889
[424]	validation_0-mae:2097.14096
[425]	validation_0-mae:2096.89155
[426]	validation_0-mae:2096.93611
[427]	validation_0-mae:2096.20081
[428]	validation_0-mae:2095.87409
[429]	validation_0-mae:2095.52420
[430]	validation_0-mae:2095.45280
[431]	validation_0-mae:2095.67618
[432]	validation_0-mae:2095.66489
[433]	validation_0-mae:2095.72118
[434]	validation_0-mae:2095.24899
[435]	validation_0-mae:2095.48415
[436]	validation_0-mae:2095.44952
[437]	validation_0-mae:2095.47508
[438]	validation_0-mae:2095.80470
[439]	validation_0-mae:2095.59992
[440]	validation_0-mae:2095.59598
[441]	validation_0-mae:2094.94832
[442]	validation_0-mae:2094.09797
[443]	validation_0-mae:2093.97765
[444]	validation_0-mae:2094.54074
[445]	validation_0-mae:2093.28826
[446]	validation_0-mae:2092.88787
[447]	validation_0-mae:2091.91280
[448]	validation_0-mae:2092.02515
[449]	validation_0-mae:2091.44034
[450]	validation_0-mae:2092.10640
[451]	validation_0-mae:2091.91707
[452]	validation_0-mae:2091.34459
[453]	validation_0-mae:2091.14751
[454]	validation_0-mae:2091.45085
[455]	validation_0-mae:2090.99253
[456]	validation_0-mae:2090.69152
[457]	validation_0-mae:2089.82567
[458]	validation_0-mae:2089.59845
[459]	validation_0-mae:2089.88020
[460]	validation_0-mae:2089.31066
[461]	validation_0-mae:2089.84586
[462]	validation_0-mae:2090.04529
[463]	validation_0-mae:2090.19893
[464]	validation_0-mae:2090.20815
[465]	validation_0-mae:2090.58547
[466]	validation_0-mae:2090.69156
[467]	validation_0-mae:2090.72032
[468]	validation_0-mae:2090.08160
[469]	validation_0-mae:2089.49560
[470]	validation_0-mae:2089.27826
[471]	validation_0-mae:2089.71301
[472]	validation_0-mae:2089.97116
[473]	validation_0-mae:2088.82490
[474]	validation_0-mae:2088.08885
[475]	validation_0-mae:2088.62265
[476]	validation_0-mae:2088.72368
[477]	validation_0-mae:2088.42992
[478]	validation_0-mae:2087.15003
[479]	validation_0-mae:2087.68481
[480]	validation_0-mae:2087.73529
[481]	validation_0-mae:2087.85015
[482]	validation_0-mae:2087.79348
[483]	validation_0-mae:2087.72048
[484]	validation_0-mae:2087.75079
[485]	validation_0-mae:2087.61133
[486]	validation_0-mae:2087.25610
[487]	validation_0-mae:2087.40863
[488]	validation_0-mae:2086.98300
[489]	validation_0-mae:2087.56165
[490]	validation_0-mae:2087.63988
[491]	validation_0-mae:2087.26722
[492]	validation_0-mae:2087.06171
[493]	validation_0-mae:2086.78896
[494]	validation_0-mae:2086.47672
[495]	validation_0-mae:2086.70152
[496]	validation_0-mae:2086.37906
[497]	validation_0-mae:2086.13000
[498]	validation_0-mae:2086.35801
[499]	validation_0-mae:2086.26966
[500]	validation_0-mae:2086.08207
[501]	validation_0-mae:2085.86718
[502]	validation_0-mae:2085.40665
[503]	validation_0-mae:2085.33898
[504]	validation_0-mae:2085.36863
[505]	validation_0-mae:2085.55444
[506]	validation_0-mae:2085.30980
[507]	validation_0-mae:2085.41404
[508]	validation_0-mae:2085.84382
[509]	validation_0-mae:2085.83870
[510]	validation_0-mae:2085.04280
[511]	validation_0-mae:2084.09002
[512]	validation_0-mae:2083.35301
[513]	validation_0-mae:2083.14211
[514]	validation_0-mae:2082.75760
[515]	validation_0-mae:2083.04354
[516]	validation_0-mae:2083.01172
[517]	validation_0-mae:2082.99616
[518]	validation_0-mae:2083.37947
[519]	validation_0-mae:2083.08315
[520]	validation_0-mae:2082.83636
[521]	validation_0-mae:2082.94185
[522]	validation_0-mae:2083.18628
[523]	validation_0-mae:2083.44370
[524]	validation_0-mae:2083.78493
[525]	validation_0-mae:2083.99794
[526]	validation_0-mae:2084.43597
[527]	validation_0-mae:2083.86650
[528]	validation_0-mae:2083.48249
[529]	validation_0-mae:2083.21171
[530]	validation_0-mae:2083.27511
[531]	validation_0-mae:2083.69961
[532]	validation_0-mae:2084.18163
[533]	validation_0-mae:2083.58055
[534]	validation_0-mae:2083.40288
[535]	validation_0-mae:2083.71356
[536]	validation_0-mae:2084.12188
[537]	validation_0-mae:2083.85663
[538]	validation_0-mae:2083.86724
[539]	validation_0-mae:2084.12524
[540]	validation_0-mae:2083.29512
[541]	validation_0-mae:2083.44862
[542]	validation_0-mae:2083.09199
[543]	validation_0-mae:2082.86212
[544]	validation_0-mae:2082.81708
[545]	validation_0-mae:2082.92032
[546]	validation_0-mae:2082.68148
[547]	validation_0-mae:2082.53609
[548]	validation_0-mae:2082.43683
[549]	validation_0-mae:2081.96128
[550]	validation_0-mae:2082.13808
[551]	validation_0-mae:2081.69039
[552]	validation_0-mae:2081.75348
[553]	validation_0-mae:2081.50589
[554]	validation_0-mae:2081.51387
[555]	validation_0-mae:2081.50756
[556]	validation_0-mae:2081.92895
[557]	validation_0-mae:2082.29346
[558]	validation_0-mae:2082.28442
[559]	validation_0-mae:2082.11122
[560]	validation_0-mae:2081.93014
[561]	validation_0-mae:2082.47028
[562]	validation_0-mae:2082.79948
[563]	validation_0-mae:2082.80969
[564]	validation_0-mae:2082.88514
[565]	validation_0-mae:2082.83774
[566]	validation_0-mae:2082.81045
[567]	validation_0-mae:2082.65918
[568]	validation_0-mae:2083.00485
[569]	validation_0-mae:2082.93694
[570]	validation_0-mae:2082.80371
[571]	validation_0-mae:2082.96118
[572]	validation_0-mae:2083.01214
[573]	validation_0-mae:2083.28040
[574]	validation_0-mae:2082.97935
[575]	validation_0-mae:2082.99888
[576]	validation_0-mae:2083.23917
[577]	validation_0-mae:2083.60528
[578]	validation_0-mae:2083.39011
[579]	validation_0-mae:2083.51696
[580]	validation_0-mae:2082.85181
[581]	validation_0-mae:2082.78214
[582]	validation_0-mae:2082.13143
[583]	validation_0-mae:2082.25271
[584]	validation_0-mae:2082.49437
[585]	validation_0-mae:2082.59255
[586]	validation_0-mae:2082.17173
[587]	validation_0-mae:2082.16710
[588]	validation_0-mae:2081.91047
[589]	validation_0-mae:2081.10305
[590]	validation_0-mae:2081.13641
[591]	validation_0-mae:2080.69273
[592]	validation_0-mae:2080.39759
[593]	validation_0-mae:2080.36865
[594]	validation_0-mae:2080.11406
[595]	validation_0-mae:2080.20574
[596]	validation_0-mae:2080.50725
[597]	validation_0-mae:2080.15090
[598]	validation_0-mae:2079.84609
[599]	validation_0-mae:2079.84948
[600]	validation_0-mae:2079.85050
[601]	validation_0-mae:2079.77579
[602]	validation_0-mae:2079.31877
[603]	validation_0-mae:2079.27368
[604]	validation_0-mae:2079.19457
[605]	validation_0-mae:2078.79803
[606]	validation_0-mae:2078.77443
[607]	validation_0-mae:2078.42275
[608]	validation_0-mae:2078.44555
[609]	validation_0-mae:2078.47701
[610]	validation_0-mae:2078.57903
[611]	validation_0-mae:2078.32075
[612]	validation_0-mae:2078.10764
[613]	validation_0-mae:2078.02672
[614]	validation_0-mae:2077.81032
[615]	validation_0-mae:2077.29283
[616]	validation_0-mae:2077.19277
[617]	validation_0-mae:2077.17846
[618]	validation_0-mae:2076.86520
[619]	validation_0-mae:2076.10331
[620]	validation_0-mae:2076.10478
[621]	validation_0-mae:2076.07457
[622]	validation_0-mae:2076.20365
[623]	validation_0-mae:2076.51732
[624]	validation_0-mae:2076.48365
[625]	validation_0-mae:2076.50043
[626]	validation_0-mae:2075.90767
[627]	validation_0-mae:2075.75746
[628]	validation_0-mae:2075.32773
[629]	validation_0-mae:2075.29757
[630]	validation_0-mae:2074.17304
[631]	validation_0-mae:2074.21931

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[41]	validation_0-mae:3340.93109
[42]	validation_0-mae:3297.39451
[43]	validation_0-mae:3257.98328
[44]	validation_0-mae:3222.08097
[45]	validation_0-mae:3187.29162
[46]	validation_0-mae:3150.21387
[47]	validation_0-mae:3118.87747
[48]	validation_0-mae:3089.15946
[49]	validation_0-mae:3063.86982
[50]	validation_0-mae:3024.92448
[51]	validation_0-mae:2991.76130
[52]	validation_0-mae:2969.40998
[53]	validation_0-mae:2944.15308
[54]	validation_0-mae:2924.94500
[55]	validation_0-mae:2891.21501
[56]	validation_0-mae:2871.00956
[57]	validation_0-mae:2849.24894
[58]	validation_0-mae:2833.56332
[59]	validation_0-mae:2808.30312
[60]	validation_0-mae:2795.06950
[61]	validation_0-mae:2778.08940
[62]	validation_0-mae:2763.57923
[63]	validation_0-mae:2751.56869
[64]	validation_0-mae:2738.53745
[65]	validation_0-mae:2724.05510
[66]	validation_0-mae:2713.63047
[67]	validation_0-mae:2703.59044
[68]	validation_0-mae:2691.33631
[69]	validation_0-mae:2675.68292
[70]	validation_0-mae:2667.99276
[71]	validation_0-mae:2659.62240
[72]	validation_0-mae:2644.69898
[73]	validation_0-mae:2640.64763
[74]	validation_0-mae:2631.77108
[75]	validation_0-mae:2623.12339
[76]	validation_0-mae:2615.14651
[77]	validation_0-mae:2604.99000
[78]	validation_0-mae:2592.58775
[79]	validation_0-mae:2579.84950
[80]	validation_0-mae:2576.09945
[81]	validation_0-mae:2572.16776
[82]	validation_0-mae:2564.29021
[83]	validation_0-mae:2541.75887
[84]	validation_0-mae:2532.23229
[85]	validation_0-mae:2520.87119
[86]	validation_0-mae:2510.50216
[87]	validation_0-mae:2501.77808
[88]	validation_0-mae:2495.47499
[89]	validation_0-mae:2487.43966
[90]	validation_0-mae:2483.44840
[91]	validation_0-mae:2482.10496
[92]	validation_0-mae:2475.15658
[93]	validation_0-mae:2470.48612
[94]	validation_0-mae:2466.20628
[95]	validation_0-mae:2452.13097
[96]	validation_0-mae:2442.36132
[97]	validation_0-mae:2439.61460
[98]	validation_0-mae:2435.69088
[99]	validation_0-mae:2431.60188
[100]	validation_0-mae:2426.29268
[101]	validation_0-mae:2416.03455
[102]	validation_0-mae:2409.08405
[103]	validation_0-mae:2401.31877
[104]	validation_0-mae:2396.15885
[105]	validation_0-mae:2392.01062
[106]	validation_0-mae:2388.50686
[107]	validation_0-mae:2387.11092
[108]	validation_0-mae:2382.71235
[109]	validation_0-mae:2377.43388
[110]	validation_0-mae:2369.90614
[111]	validation_0-mae:2363.80077
[112]	validation_0-mae:2358.03076
[113]	validation_0-mae:2350.94711
[114]	validation_0-mae:2348.95090
[115]	validation_0-mae:2345.06202
[116]	validation_0-mae:2342.57984
[117]	validation_0-mae:2337.32020
[118]	validation_0-mae:2335.62475
[119]	validation_0-mae:2333.33056
[120]	validation_0-mae:2329.33079
[121]	validation_0-mae:2325.80807
[122]	validation_0-mae:2322.64655
[123]	validation_0-mae:2319.04655
[124]	validation_0-mae:2316.89048
[125]	validation_0-mae:2315.72812
[126]	validation_0-mae:2313.69134
[127]	validation_0-mae:2312.71153
[128]	validation_0-mae:2308.34674
[129]	validation_0-mae:2306.87648
[130]	validation_0-mae:2300.23329
[131]	validation_0-mae:2297.50898
[132]	validation_0-mae:2296.49067
[133]	validation_0-mae:2295.15063
[134]	validation_0-mae:2290.91058
[135]	validation_0-mae:2286.00210
[136]	validation_0-mae:2285.63879
[137]	validation_0-mae:2281.36341
[138]	validation_0-mae:2278.36975
[139]	validation_0-mae:2271.87593
[140]	validation_0-mae:2271.46318
[141]	validation_0-mae:2269.36737
[142]	validation_0-mae:2267.94785
[143]	validation_0-mae:2265.51450
[144]	validation_0-mae:2264.63171
[145]	validation_0-mae:2261.84712
[146]	validation_0-mae:2258.91575
[147]	validation_0-mae:2257.64971
[148]	validation_0-mae:2258.58587
[149]	validation_0-mae:2256.66596
[150]	validation_0-mae:2255.54146
[151]	validation_0-mae:2250.70915
[152]	validation_0-mae:2249.12381
[153]	validation_0-mae:2246.05728
[154]	validation_0-mae:2240.95856
[155]	validation_0-mae:2240.09510
[156]	validation_0-mae:2237.16903
[157]	validation_0-mae:2236.55185
[158]	validation_0-mae:2231.98363
[159]	validation_0-mae:2229.96308
[160]	validation_0-mae:2225.44036
[161]	validation_0-mae:2224.54385
[162]	validation_0-mae:2223.00076
[163]	validation_0-mae:2222.05396
[164]	validation_0-mae:2221.79811
[165]	validation_0-mae:2219.57372
[166]	validation_0-mae:2218.42202
[167]	validation_0-mae:2217.03604
[168]	validation_0-mae:2216.21457
[169]	validation_0-mae:2215.13799
[170]	validation_0-mae:2215.24056
[171]	validation_0-mae:2214.29153
[172]	validation_0-mae:2212.63935
[173]	validation_0-mae:2212.00723
[174]	validation_0-mae:2210.65474
[175]	validation_0-mae:2210.70373
[176]	validation_0-mae:2209.94708
[177]	validation_0-mae:2207.33752
[178]	validation_0-mae:2207.19648
[179]	validation_0-mae:2205.77589
[180]	validation_0-mae:2204.60276
[181]	validation_0-mae:2204.06233
[182]	validation_0-mae:2203.43099
[183]	validation_0-mae:2201.52084
[184]	validation_0-mae:2200.70041
[185]	validation_0-mae:2200.41000
[186]	validation_0-mae:2199.34420
[187]	validation_0-mae:2197.15548
[188]	validation_0-mae:2194.73535
[189]	validation_0-mae:2192.76232
[190]	validation_0-mae:2191.67687
[191]	validation_0-mae:2190.58839
[192]	validation_0-mae:2191.05300
[193]	validation_0-mae:2186.79315
[194]	validation_0-mae:2185.14176
[195]	validation_0-mae:2184.65477
[196]	validation_0-mae:2182.35890
[197]	validation_0-mae:2179.95032
[198]	validation_0-mae:2179.40468
[199]	validation_0-mae:2179.20377
[200]	validation_0-mae:2177.72322
[201]	validation_0-mae:2177.50833
[202]	validation_0-mae:2177.02865
[203]	validation_0-mae:2176.48811
[204]	validation_0-mae:2177.04694
[205]	validation_0-mae:2176.58779
[206]	validation_0-mae:2175.08696
[207]	validation_0-mae:2175.60799
[208]	validation_0-mae:2176.11279
[209]	validation_0-mae:2174.83066
[210]	validation_0-mae:2174.64930
[211]	validation_0-mae:2172.74425
[212]	validation_0-mae:2172.61637
[213]	validation_0-mae:2171.56126
[214]	validation_0-mae:2170.28914
[215]	validation_0-mae:2170.30856
[216]	validation_0-mae:2169.39577
[217]	validation_0-mae:2169.45451
[218]	validation_0-mae:2169.43217
[219]	validation_0-mae:2168.03784
[220]	validation_0-mae:2167.44867
[221]	validation_0-mae:2166.88625
[222]	validation_0-mae:2166.13690
[223]	validation_0-mae:2167.43806
[224]	validation_0-mae:2166.53478
[225]	validation_0-mae:2167.30038
[226]	validation_0-mae:2166.84941
[227]	validation_0-mae:2164.64272
[228]	validation_0-mae:2164.19461
[229]	validation_0-mae:2163.34524
[230]	validation_0-mae:2163.82764
[231]	validation_0-mae:2164.61167
[232]	validation_0-mae:2165.46216
[233]	validation_0-mae:2164.18575
[234]	validation_0-mae:2164.20273
[235]	validation_0-mae:2162.91390
[236]	validation_0-mae:2161.69800
[237]	validation_0-mae:2159.71209
[238]	validation_0-mae:2158.15618
[239]	validation_0-mae:2156.77161
[240]	validation_0-mae:2156.81493
[241]	validation_0-mae:2156.33206
[242]	validation_0-mae:2154.30297
[243]	validation_0-mae:2154.16440
[244]	validation_0-mae:2153.54032
[245]	validation_0-mae:2153.20149
[246]	validation_0-mae:2152.44783
[247]	validation_0-mae:2152.70933
[248]	validation_0-mae:2152.92176
[249]	validation_0-mae:2153.60321
[250]	validation_0-mae:2152.90475
[251]	validation_0-mae:2151.77825
[252]	validation_0-mae:2151.69269
[253]	validation_0-mae:2151.31783
[254]	validation_0-mae:2151.08608
[255]	validation_0-mae:2150.02619
[256]	validation_0-mae:2150.18357
[257]	validation_0-mae:2150.90783
[258]	validation_0-mae:2151.15080
[259]	validation_0-mae:2151.17703
[260]	validation_0-mae:2150.89573
[261]	validation_0-mae:2152.18133
[262]	validation_0-mae:2152.71461
[263]	validation_0-mae:2152.81121
[264]	validation_0-mae:2153.34859
[265]	validation_0-mae:2153.70822
[266]	validation_0-mae:2153.42532
[267]	validation_0-mae:2153.79135
[268]	validation_0-mae:2152.92844
[269]	validation_0-mae:2153.09824
[270]	validation_0-mae:2152.81469
[271]	validation_0-mae:2152.29320
[272]	validation_0-mae:2150.45050
[273]	validation_0-mae:2150.26079
[274]	validation_0-mae:2149.31471
[275]	validation_0-mae:2148.98260
[276]	validation_0-mae:2148.56268
[277]	validation_0-mae:2148.55645
[278]	validation_0-mae:2148.01880
[279]	validation_0-mae:2148.23271
[280]	validation_0-mae:2149.17291
[281]	validation_0-mae:2149.02528
[282]	validation_0-mae:2146.50842
[283]	validation_0-mae:2146.19463
[284]	validation_0-mae:2146.89750
[285]	validation_0-mae:2145.63183
[286]	validation_0-mae:2146.26405
[287]	validation_0-mae:2145.74741
[288]	validation_0-mae:2145.43788
[289]	validation_0-mae:2144.27177
[290]	validation_0-mae:2145.10274
[291]	validation_0-mae:2143.96024
[292]	validation_0-mae:2144.05795
[293]	validation_0-mae:2144.16304
[294]	validation_0-mae:2144.01310
[295]	validation_0-mae:2144.04664
[296]	validation_0-mae:2143.72165
[297]	validation_0-mae:2141.82372
[298]	validation_0-mae:2141.81860
[299]	validation_0-mae:2141.26071
[300]	validation_0-mae:2141.83901
[301]	validation_0-mae:2142.24787
[302]	validation_0-mae:2141.52884
[303]	validation_0-mae:2141.15309
[304]	validation_0-mae:2139.52081
[305]	validation_0-mae:2139.36574
[306]	validation_0-mae:2138.84182
[307]	validation_0-mae:2139.11440
[308]	validation_0-mae:2138.17347
[309]	validation_0-mae:2136.93653
[310]	validation_0-mae:2136.78868
[311]	validation_0-mae:2136.26216
[312]	validation_0-mae:2136.53137
[313]	validation_0-mae:2136.96451
[314]	validation_0-mae:2136.97833
[315]	validation_0-mae:2137.47048
[316]	validation_0-mae:2137.20277
[317]	validation_0-mae:2136.96575
[318]	validation_0-mae:2137.73681
[319]	validation_0-mae:2138.13052
[320]	validation_0-mae:2138.88460
[321]	validation_0-mae:2138.87892
[322]	validation_0-mae:2139.60420
[323]	validation_0-mae:2138.98947
[324]	validation_0-mae:2139.51712
[325]	validation_0-mae:2139.93005
[326]	validation_0-mae:2139.32128
[327]	validation_0-mae:2139.09060
[328]	validation_0-mae:2139.16231
[329]	validation_0-mae:2138.49746
[330]	validation_0-mae:2137.93689
[331]	validation_0-mae:2138.27516
[332]	validation_0-mae:2138.79021
[333]	validation_0-mae:2137.47950
[334]	validation_0-mae:2138.36077
[335]	validation_0-mae:2139.26335
[336]	validation_0-mae:2139.80063
[337]	validation_0-mae:2140.54921
[338]	validation_0-mae:2141.08004
[339]	validation_0-mae:2140.70044
[340]	validation_0-mae:2140.96762
[341]	validation_0-mae:2141.24699
[342]	validation_0-mae:2141.19412
[343]	validation_0-mae:2141.08807
[344]	validation_0-mae:2141.18164
[345]	validation_0-mae:2141.17161
[346]	validation_0-mae:2141.29607
[347]	validation_0-mae:2141.43105
[348]	validation_0-mae:2140.65704
[349]	validation_0-mae:2140.95881
[350]	validation_0-mae:2140.44959
[351]	validation_0-mae:2140.30003
[352]	validation_0-mae:2140.30807
[353]	validation_0-mae:2139.76971
[354]	validation_0-mae:2139.42782
[355]	validation_0-mae:2138.14289
[356]	validation_0-mae:2137.68482
[357]	validation_0-mae:2136.33447
[358]	validation_0-mae:2135.91433
[359]	validation_0-mae:2136.24775
[360]	validation_0-mae:2136.37777
[361]	validation_0-mae:2136.94561
[362]	validation_0-mae:2136.68612
[363]	validation_0-mae:2136.95432
[364]	validation_0-mae:2135.94633
[365]	validation_0-mae:2136.30289
[366]	validation_0-mae:2136.79165
[367]	validation_0-mae:2136.97032
[368]	validation_0-mae:2136.43159
[369]	validation_0-mae:2136.93084
[370]	validation_0-mae:2136.64089
[371]	validation_0-mae:2136.49702
[372]	validation_0-mae:2135.52705
[373]	validation_0-mae:2135.74050
[374]	validation_0-mae:2135.17428
[375]	validation_0-mae:2134.70474
[376]	validation_0-mae:2134.04344
[377]	validation_0-mae:2134.45872
[378]	validation_0-mae:2134.84458
[379]	validation_0-mae:2134.72419
[380]	validation_0-mae:2134.36145
[381]	validation_0-mae:2133.56346
[382]	validation_0-mae:2133.69639
[383]	validation_0-mae:2133.75361
[384]	validation_0-mae:2134.32513
[385]	validation_0-mae:2134.53613
[386]	validation_0-mae:2134.55853
[387]	validation_0-mae:2134.12161
[388]	validation_0-mae:2133.68027
[389]	validation_0-mae:2133.41758
[390]	validation_0-mae:2133.56898
[391]	validation_0-mae:2133.72215
[392]	validation_0-mae:2133.63679
[393]	validation_0-mae:2133.56447
[394]	validation_0-mae:2132.99346
[395]	validation_0-mae:2133.24591
[396]	validation_0-mae:2133.38021
[397]	validation_0-mae:2132.86474
[398]	validation_0-mae:2131.74481
[399]	validation_0-mae:2131.50139
[400]	validation_0-mae:2131.65246
[401]	validation_0-mae:2131.80798
[402]	validation_0-mae:2131.90863
[403]	validation_0-mae:2132.32596
[404]	validation_0-mae:2132.35727
[405]	validation_0-mae:2132.79535
[406]	validation_0-mae:2132.92015
[407]	validation_0-mae:2133.25717
[408]	validation_0-mae:2133.97684
[409]	validation_0-mae:2133.79032
[410]	validation_0-mae:2134.46251
[411]	validation_0-mae:2132.98759
[412]	validation_0-mae:2133.48452
[413]	validation_0-mae:2132.99564
[414]	validation_0-mae:2131.71501
[415]	validation_0-mae:2131.64436
[416]	validation_0-mae:2132.62075
[417]	validation_0-mae:2132.33041
[418]	validation_0-mae:2132.47580
[419]	validation_0-mae:2131.90185
[420]	validation_0-mae:2132.32020
[421]	validation_0-mae:2132.52524
[422]	validation_0-mae:2132.52460
[423]	validation_0-mae:2131.92365
[424]	validation_0-mae:2131.18266
[425]	validation_0-mae:2130.58340
[426]	validation_0-mae:2129.70322
[427]	validation_0-mae:2129.83362
[428]	validation_0-mae:2129.51207
[429]	validation_0-mae:2128.39635
[430]	validation_0-mae:2128.53250
[431]	validation_0-mae:2128.63699
[432]	validation_0-mae:2128.35884
[433]	validation_0-mae:2128.65228
[434]	validation_0-mae:2128.82354
[435]	validation_0-mae:2128.95747
[436]	validation_0-mae:2128.76406
[437]	validation_0-mae:2129.01678
[438]	validation_0-mae:2128.84493
[439]	validation_0-mae:2128.78810
[440]	validation_0-mae:2129.24443
[441]	validation_0-mae:2129.12959
[442]	validation_0-mae:2128.93125
[443]	validation_0-mae:2129.14853
[444]	validation_0-mae:2128.72667
[445]	validation_0-mae:2128.96304
[446]	validation_0-mae:2129.20859
[447]	validation_0-mae:2128.82096
[448]	validation_0-mae:2129.10508
[449]	validation_0-mae:2128.93659
[450]	validation_0-mae:2129.08341
[451]	validation_0-mae:2129.27052
[452]	validation_0-mae:2129.37303
[453]	validation_0-mae:2129.24790
[454]	validation_0-mae:2128.82816
[455]	validation_0-mae:2128.92664
[456]	validation_0-mae:2128.43854
[457]	validation_0-mae:2127.54871
[458]	validation_0-mae:2127.60814
[459]	validation_0-mae:2127.87895
[460]	validation_0-mae:2128.08987
[461]	validation_0-mae:2127.81399
[462]	validation_0-mae:2127.60636
[463]	validation_0-mae:2127.83952
[464]	validation_0-mae:2128.04251
[465]	validation_0-mae:2127.49243
[466]	validation_0-mae:2127.05055
[467]	validation_0-mae:2126.67920
[468]	validation_0-mae:2126.10277
[469]	validation_0-mae:2125.94997
[470]	validation_0-mae:2126.18216
[471]	validation_0-mae:2125.98758
[472]	validation_0-mae:2124.87938
[473]	validation_0-mae:2124.88847
[474]	validation_0-mae:2124.98207
[475]	validation_0-mae:2125.33271
[476]	validation_0-mae:2125.26961
[477]	validation_0-mae:2125.41098
[478]	validation_0-mae:2125.44498
[479]	validation_0-mae:2125.23585
[480]	validation_0-mae:2124.67842
[481]	validation_0-mae:2125.10010
[482]	validation_0-mae:2124.81232
[483]	validation_0-mae:2124.48547
[484]	validation_0-mae:2124.70928
[485]	validation_0-mae:2124.33998
[486]	validation_0-mae:2123.95199
[487]	validation_0-mae:2123.86460
[488]	validation_0-mae:2123.93876
[489]	validation_0-mae:2124.25492
[490]	validation_0-mae:2123.51063
[491]	validation_0-mae:2123.57810
[492]	validation_0-mae:2123.58368
[493]	validation_0-mae:2123.79278
[494]	validation_0-mae:2123.87067
[495]	validation_0-mae:2123.63668
[496]	validation_0-mae:2123.72117
[497]	validation_0-mae:2123.52020
[498]	validation_0-mae:2123.02592
[499]	validation_0-mae:2123.11968
[500]	validation_0-mae:2123.31441
[501]	validation_0-mae:2123.50892
[502]	validation_0-mae:2123.64481
[503]	validation_0-mae:2123.81662
[504]	validation_0-mae:2123.18988
[505]	validation_0-mae:2123.44289
[506]	validation_0-mae:2122.88770
[507]	validation_0-mae:2123.11170
[508]	validation_0-mae:2123.61489
[509]	validation_0-mae:2124.22407
[510]	validation_0-mae:2123.97334
[511]	validation_0-mae:2122.87986
[512]	validation_0-mae:2122.26448
[513]	validation_0-mae:2121.55444
[514]	validation_0-mae:2120.91970
[515]	validation_0-mae:2120.58385
[516]	validation_0-mae:2120.14875
[517]	validation_0-mae:2119.47069
[518]	validation_0-mae:2119.08141
[519]	validation_0-mae:2118.95143
[520]	validation_0-mae:2118.44740
[521]	validation_0-mae:2118.54278
[522]	validation_0-mae:2118.16692
[523]	validation_0-mae:2117.77235
[524]	validation_0-mae:2117.86437
[525]	validation_0-mae:2118.01532
[526]	validation_0-mae:2118.19306
[527]	validation_0-mae:2117.85972
[528]	validation_0-mae:2117.67646
[529]	validation_0-mae:2117.64820
[530]	validation_0-mae:2117.73907
[531]	validation_0-mae:2118.14888
[532]	validation_0-mae:2117.88418
[533]	validation_0-mae:2117.27585
[534]	validation_0-mae:2117.43367
[535]	validation_0-mae:2117.34853
[536]	validation_0-mae:2117.46656
[537]	validation_0-mae:2117.76243
[538]	validation_0-mae:2117.55147
[539]	validation_0-mae:2117.29343
[540]	validation_0-mae:2116.69611
[541]	validation_0-mae:2116.97942
[542]	validation_0-mae:2116.33524
[543]	validation_0-mae:2116.22135
[544]	validation_0-mae:2116.54247
[545]	validation_0-mae:2116.91855
[546]	validation_0-mae:2116.68446
[547]	validation_0-mae:2116.71493
[548]	validation_0-mae:2116.63998
[549]	validation_0-mae:2117.02359
[550]	validation_0-mae:2117.14544
[551]	validation_0-mae:2117.27203
[552]	validation_0-mae:2117.01169
[553]	validation_0-mae:2117.19752
[554]	validation_0-mae:2117.16315
[555]	validation_0-mae:2117.33080
[556]	validation_0-mae:2117.41114
[557]	validation_0-mae:2117.45987
[558]	validation_0-mae:2117.20676
[559]	validation_0-mae:2117.10127
[560]	validation_0-mae:2117.35355
[561]	validation_0-mae:2117.29535
[562]	validation_0-mae:2117.19804
[563]	validation_0-mae:2117.35712
[564]	validation_0-mae:2117.76522
[565]	validation_0-mae:2117.89362
[566]	validation_0-mae:2117.75906
[567]	validation_0-mae:2117.79129
[568]	validation_0-mae:2117.83893
[569]	validation_0-mae:2118.19753
[570]	validation_0-mae:2118.25133
[571]	validation_0-mae:2118.32087
[572]	validation_0-mae:2118.26947
[573]	validation_0-mae:2118.35597
[574]	validation_0-mae:2118.30011
[575]	validation_0-mae:2117.60305
[576]	validation_0-mae:2117.32077
[577]	validation_0-mae:2117.36121
[578]	validation_0-mae:2116.70142
[579]	validation_0-mae:2116.88847
[580]	validation_0-mae:2116.99821
[581]	validation_0-mae:2116.95721
[582]	validation_0-mae:2117.21431
[583]	validation_0-mae:2116.87188
[584]	validation_0-mae:2116.75664
[585]	validation_0-mae:2116.75680
[586]	validation_0-mae:2117.04349
[587]	validation_0-mae:2116.63677
[588]	validation_0-mae:2116.94760
[589]	validation_0-mae:2116.87097
[590]	validation_0-mae:2117.14920
[591]	validation_0-mae:2117.22699
[592]	validation_0-mae:2117.41884
[593]	validation_0-mae:2117.57300
[594]	validation_0-mae:2117.36007
[595]	validation_0-mae:2117.48971
[596]	validation_0-mae:2118.04678
[597]	validation_0-mae:2117.85698
[598]	validation_0-mae:2117.96439
[599]	validation_0-mae:2117.58485
[600]	validation_0-mae:2117.35693
[601]	validation_0-mae:2117.63876
[602]	validation_0-mae:2117.42607
[603]	validation_0-mae:2117.22910
[604]	validation_0-mae:2117.27605
[605]	validation_0-mae:2117.30914
[606]	validation_0-mae:2117.28911
[607]	validation_0-mae:2117.45385
[608]	validation_0-mae:2117.59937
[609]	validation_0-mae:2117.64068
[610]	validation_0-mae:2117.56235
[611]	validation_0-mae:2116.60602
[612]	validation_0-mae:2116.60338
[613]	validation_0-mae:2116.78887
[614]	validation_0-mae:2116.69087
[615]	validation_0-mae:2116.66422
[616]	validation_0-mae:2116.37403
[617]	validation_0-mae:2115.37173
[618]	validation_0-mae:2114.84387
[619]	validation_0-mae:2114.79454
[620]	validation_0-mae:2114.52076
[621]	validation_0-mae:2114.31320
[622]	validation_0-mae:2114.10826
[623]	validation_0-mae:2113.94353
[624]	validation_0-mae:2113.47604
[625]	validation_0-mae:2113.98745
[626]	validation_0-mae:2113.89521
[627]	validation_0-mae:2113.86185
[628]	validation_0-mae:2113.80030
[629]	validation_0-mae:2114.05371

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[0]	validation_0-mae:12379.92127
[1]	validation_0-mae:11607.29159
[2]	validation_0-mae:10892.41293
[3]	validation_0-mae:10228.93013
[4]	validation_0-mae:9669.40800
[5]	validation_0-mae:9151.76433
[6]	validation_0-mae:8691.14438
[7]	validation_0-mae:8286.87936
[8]	validation_0-mae:7917.96445
[9]	validation_0-mae:7564.42720
[10]	validation_0-mae:7238.95452
[11]	validation_0-mae:6935.88571
[12]	validation_0-mae:6649.27562
[13]	validation_0-mae:6367.51543
[14]	validation_0-mae:6144.11199
[15]	validation_0-mae:5899.43356
[16]	validation_0-mae:5645.63415
[17]	validation_0-mae:5460.09410
[18]	validation_0-mae:5265.95060
[19]	validation_0-mae:5094.41151
[20]	validation_0-mae:4932.27790
[21]	validation_0-mae:4782.38499
[22]	validation_0-mae:4639.11601
[23]	validation_0-mae:4500.25070
[24]	validation_0-mae:4385.36687
[25]	validation_0-mae:4255.17427
[26]	validation_0-mae:4146.84886
[27]	validation_0-mae:4042.40547
[28]	validation_0-mae:3947.09769
[29]	validation_0-mae:3866.31397
[30]	validation_0-mae:3777.42368
[31]	validation_0-mae:3707.21243
[32]	validation_0-mae:3646.08359
[33]	validation_0-mae:3580.06513
[34]	validation_0-mae:3500.48111
[35]	validation_0-mae:3444.58059
[36]	validation_0-mae:3396.16276
[37]	validation_0-mae:3322.63248
[38]	validation_0-mae:3272.05580
[39]	validation_0-mae:3225.86356
[40]	validation_0-mae:3182.64534
[41]	validation_0-mae:3146.74335
[42]	validation_0-mae:3110.95863
[43]	validation_0-mae:3073.95045
[44]	validation_0-mae:3042.09304
[45]	validation_0-mae:3000.85467
[46]	validation_0-mae:2965.52984
[47]	validation_0-mae:2937.53961
[48]	validation_0-mae:2916.69082
[49]	validation_0-mae:2891.36016
[50]	validation_0-mae:2853.82896
[51]	validation_0-mae:2829.43026
[52]	validation_0-mae:2808.85934
[53]	validation_0-mae:2788.58838
[54]	validation_0-mae:2771.08025
[55]	validation_0-mae:2751.95431
[56]	validation_0-mae:2735.14140
[57]	validation_0-mae:2719.58111
[58]	validation_0-mae:2702.61407
[59]	validation_0-mae:2686.23069
[60]	validation_0-mae:2671.70263
[61]	validation_0-mae:2651.52917
[62]	validation_0-mae:2622.53901
[63]	validation_0-mae:2612.24014
[64]	validation_0-mae:2594.05181
[65]	validation_0-mae:2583.24268
[66]	validation_0-mae:2571.04721
[67]	validation_0-mae:2555.10614
[68]	validation_0-mae:2544.74017
[69]	validation_0-mae:2538.14826
[70]	validation_0-mae:2526.59086
[71]	validation_0-mae:2516.33613
[72]	validation_0-mae:2509.87748
[73]	validation_0-mae:2501.81077
[74]	validation_0-mae:2490.01049
[75]	validation_0-mae:2474.05621
[76]	validation_0-mae:2463.55191
[77]	validation_0-mae:2456.44720
[78]	validation_0-mae:2451.21345
[79]	validation_0-mae:2438.52524
[80]	validation_0-mae:2429.15040
[81]	validation_0-mae:2423.25563
[82]	validation_0-mae:2417.65785
[83]	validation_0-mae:2408.74513
[84]	validation_0-mae:2401.84030
[85]	validation_0-mae:2398.27893
[86]	validation_0-mae:2383.45816
[87]	validation_0-mae:2375.07365
[88]	validation_0-mae:2366.72722
[89]	validation_0-mae:2359.26365
[90]	validation_0-mae:2351.60217
[91]	validation_0-mae:2347.19721
[92]	validation_0-mae:2343.09757
[93]	validation_0-mae:2337.06087
[94]	validation_0-mae:2330.31910
[95]	validation_0-mae:2327.29601
[96]	validation_0-mae:2321.27932
[97]	validation_0-mae:2316.69860
[98]	validation_0-mae:2312.56445
[99]	validation_0-mae:2302.80454
[100]	validation_0-mae:2295.89501
[101]	validation_0-mae:2289.13628
[102]	validation_0-mae:2281.66206
[103]	validation_0-mae:2276.57848
[104]	validation_0-mae:2273.39618
[105]	validation_0-mae:2269.96694
[106]	validation_0-mae:2262.68116
[107]	validation_0-mae:2259.94254
[108]	validation_0-mae:2257.07357
[109]	validation_0-mae:2251.43065
[110]	validation_0-mae:2249.36842
[111]	validation_0-mae:2246.34067
[112]	validation_0-mae:2240.87881
[113]	validation_0-mae:2236.10161
[114]	validation_0-mae:2232.03180
[115]	validation_0-mae:2225.42958
[116]	validation_0-mae:2220.17378
[117]	validation_0-mae:2216.81211
[118]	validation_0-mae:2212.98914
[119]	validation_0-mae:2208.40017
[120]	validation_0-mae:2206.75277
[121]	validation_0-mae:2205.19534
[122]	validation_0-mae:2202.80447
[123]	validation_0-mae:2198.69935
[124]	validation_0-mae:2193.11832
[125]	validation_0-mae:2190.44938
[126]	validation_0-mae:2188.58629
[127]	validation_0-mae:2186.23926
[128]	validation_0-mae:2180.90826
[129]	validation_0-mae:2180.39931
[130]	validation_0-mae:2178.75938
[131]	validation_0-mae:2178.13524
[132]	validation_0-mae:2174.80905
[133]	validation_0-mae:2173.44005
[134]	validation_0-mae:2169.43334
[135]	validation_0-mae:2165.88943
[136]	validation_0-mae:2166.09847
[137]	validation_0-mae:2163.61944
[138]	validation_0-mae:2163.69063
[139]	validation_0-mae:2162.52100
[140]	validation_0-mae:2161.26530
[141]	validation_0-mae:2158.33293
[142]	validation_0-mae:2156.45850
[143]	validation_0-mae:2155.38134
[144]	validation_0-mae:2153.34297
[145]	validation_0-mae:2153.12403
[146]	validation_0-mae:2151.99711
[147]	validation_0-mae:2153.10093
[148]	validation_0-mae:2150.74407
[149]	validation_0-mae:2151.84804
[150]	validation_0-mae:2149.27259
[151]	validation_0-mae:2149.00930
[152]	validation_0-mae:2148.84740
[153]	validation_0-mae:2147.40037
[154]	validation_0-mae:2145.03936
[155]	validation_0-mae:2144.48703
[156]	validation_0-mae:2143.01854
[157]	validation_0-mae:2141.95827
[158]	validation_0-mae:2140.98522
[159]	validation_0-mae:2140.30899
[160]	validation_0-mae:2140.02893
[161]	validation_0-mae:2139.47628
[162]	validation_0-mae:2137.47205
[163]	validation_0-mae:2136.67056
[164]	validation_0-mae:2136.53329
[165]	validation_0-mae:2137.42093
[166]	validation_0-mae:2136.74084
[167]	validation_0-mae:2134.21909
[168]	validation_0-mae:2132.81902
[169]	validation_0-mae:2132.01676
[170]	validation_0-mae:2132.77199
[171]	validation_0-mae:2131.55763
[172]	validation_0-mae:2130.13825
[173]	validation_0-mae:2129.64658
[174]	validation_0-mae:2129.11949
[175]	validation_0-mae:2129.22589
[176]	validation_0-mae:2127.78367
[177]	validation_0-mae:2127.55179
[178]	validation_0-mae:2126.41212
[179]	validation_0-mae:2124.65823
[180]	validation_0-mae:2123.11306
[181]	validation_0-mae:2121.21038
[182]	validation_0-mae:2121.45692
[183]	validation_0-mae:2120.46245
[184]	validation_0-mae:2117.89683
[185]	validation_0-mae:2117.20058
[186]	validation_0-mae:2116.41430
[187]	validation_0-mae:2114.93045
[188]	validation_0-mae:2114.58023
[189]	validation_0-mae:2115.58182
[190]	validation_0-mae:2115.44174
[191]	validation_0-mae:2114.22500
[192]	validation_0-mae:2109.72476
[193]	validation_0-mae:2109.61965
[194]	validation_0-mae:2108.76795
[195]	validation_0-mae:2106.12907
[196]	validation_0-mae:2105.20677
[197]	validation_0-mae:2105.21448
[198]	validation_0-mae:2105.09358
[199]	validation_0-mae:2104.53991
[200]	validation_0-mae:2104.23561
[201]	validation_0-mae:2104.49935
[202]	validation_0-mae:2102.39201
[203]	validation_0-mae:2102.48701
[204]	validation_0-mae:2102.13122
[205]	validation_0-mae:2101.65710
[206]	validation_0-mae:2101.89793
[207]	validation_0-mae:2102.60269
[208]	validation_0-mae:2102.22633
[209]	validation_0-mae:2100.56458
[210]	validation_0-mae:2099.55058
[211]	validation_0-mae:2099.78092
[212]	validation_0-mae:2099.88569
[213]	validation_0-mae:2098.57993
[214]	validation_0-mae:2098.36579
[215]	validation_0-mae:2098.11830
[216]	validation_0-mae:2096.87229
[217]	validation_0-mae:2096.63501
[218]	validation_0-mae:2095.36206
[219]	validation_0-mae:2094.65867
[220]	validation_0-mae:2094.14278
[221]	validation_0-mae:2093.92973
[222]	validation_0-mae:2093.54595
[223]	validation_0-mae:2094.14788
[224]	validation_0-mae:2094.03394
[225]	validation_0-mae:2093.03729
[226]	validation_0-mae:2092.29023
[227]	validation_0-mae:2090.80302
[228]	validation_0-mae:2090.07637
[229]	validation_0-mae:2089.68275
[230]	validation_0-mae:2089.70540
[231]	validation_0-mae:2090.62753
[232]	validation_0-mae:2090.71019
[233]	validation_0-mae:2088.99631
[234]	validation_0-mae:2089.33149
[235]	validation_0-mae:2089.76342
[236]	validation_0-mae:2089.46959
[237]	validation_0-mae:2090.41853
[238]	validation_0-mae:2090.25166
[239]	validation_0-mae:2090.93007
[240]	validation_0-mae:2090.74812
[241]	validation_0-mae:2089.53736
[242]	validation_0-mae:2089.17415
[243]	validation_0-mae:2089.04538
[244]	validation_0-mae:2089.54227
[245]	validation_0-mae:2087.66107
[246]	validation_0-mae:2087.80792
[247]	validation_0-mae:2088.39841
[248]	validation_0-mae:2087.17270
[249]	validation_0-mae:2086.08849
[250]	validation_0-mae:2086.42315
[251]	validation_0-mae:2086.58837
[252]	validation_0-mae:2086.76131
[253]	validation_0-mae:2087.76700
[254]	validation_0-mae:2087.57470
[255]	validation_0-mae:2087.03272
[256]	validation_0-mae:2086.69849
[257]	validation_0-mae:2087.31489
[258]	validation_0-mae:2086.56656
[259]	validation_0-mae:2085.26822
[260]	validation_0-mae:2085.22777
[261]	validation_0-mae:2085.96809
[262]	validation_0-mae:2086.47092
[263]	validation_0-mae:2086.75727
[264]	validation_0-mae:2087.14649
[265]	validation_0-mae:2086.29033
[266]	validation_0-mae:2086.52031
[267]	validation_0-mae:2084.60724
[268]	validation_0-mae:2084.75465
[269]	validation_0-mae:2083.83087
[270]	validation_0-mae:2083.05771
[271]	validation_0-mae:2083.36239
[272]	validation_0-mae:2082.85975
[273]	validation_0-mae:2083.79154
[274]	validation_0-mae:2082.89077
[275]	validation_0-mae:2082.65913
[276]	validation_0-mae:2081.38142
[277]	validation_0-mae:2080.79890
[278]	validation_0-mae:2080.38606
[279]	validation_0-mae:2080.57568
[280]	validation_0-mae:2080.55303
[281]	validation_0-mae:2079.82280
[282]	validation_0-mae:2080.61120
[283]	validation_0-mae:2081.14291
[284]	validation_0-mae:2081.27431
[285]	validation_0-mae:2082.44210
[286]	validation_0-mae:2082.88240
[287]	validation_0-mae:2084.63037
[288]	validation_0-mae:2084.61617
[289]	validation_0-mae:2084.32665
[290]	validation_0-mae:2084.38563
[291]	validation_0-mae:2084.35203
[292]	validation_0-mae:2084.01387
[293]	validation_0-mae:2082.34252
[294]	validation_0-mae:2082.56767
[295]	validation_0-mae:2082.58211
[296]	validation_0-mae:2081.74391
[297]	validation_0-mae:2081.28657
[298]	validation_0-mae:2080.27562
[299]	validation_0-mae:2080.21665
[300]	validation_0-mae:2080.49010
[301]	validation_0-mae:2079.07881
[302]	validation_0-mae:2078.92561
[303]	validation_0-mae:2077.90569
[304]	validation_0-mae:2077.37907
[305]	validation_0-mae:2077.35553
[306]	validation_0-mae:2077.54071
[307]	validation_0-mae:2077.20108
[308]	validation_0-mae:2077.48461
[309]	validation_0-mae:2077.73678
[310]	validation_0-mae:2075.62159
[311]	validation_0-mae:2073.77647
[312]	validation_0-mae:2073.62227
[313]	validation_0-mae:2073.75548
[314]	validation_0-mae:2073.01818
[315]	validation_0-mae:2072.92139
[316]	validation_0-mae:2073.27842
[317]	validation_0-mae:2073.29024
[318]	validation_0-mae:2073.42914
[319]	validation_0-mae:2073.73629
[320]	validation_0-mae:2074.37866
[321]	validation_0-mae:2073.77178
[322]	validation_0-mae:2074.02185
[323]	validation_0-mae:2074.30749
[324]	validation_0-mae:2075.03162
[325]	validation_0-mae:2074.62498
[326]	validation_0-mae:2075.28455
[327]	validation_0-mae:2075.41985
[328]	validation_0-mae:2075.45430
[329]	validation_0-mae:2075.53889
[330]	validation_0-mae:2075.64620
[331]	validation_0-mae:2076.06037
[332]	validation_0-mae:2074.87291
[333]	validation_0-mae:2074.65428
[334]	validation_0-mae:2074.33116
[335]	validation_0-mae:2073.83170
[336]	validation_0-mae:2073.67477
[337]	validation_0-mae:2073.63520
[338]	validation_0-mae:2073.79295
[339]	validation_0-mae:2072.67293
[340]	validation_0-mae:2072.36843
[341]	validation_0-mae:2072.56364
[342]	validation_0-mae:2072.26771
[343]	validation_0-mae:2072.47038
[344]	validation_0-mae:2072.98084
[345]	validation_0-mae:2072.73583
[346]	validation_0-mae:2073.14539
[347]	validation_0-mae:2073.28337
[348]	validation_0-mae:2073.11559
[349]	validation_0-mae:2071.83172
[350]	validation_0-mae:2071.87577
[351]	validation_0-mae:2071.71205
[352]	validation_0-mae:2071.06153
[353]	validation_0-mae:2071.13290
[354]	validation_0-mae:2071.11897
[355]	validation_0-mae:2071.61560
[356]	validation_0-mae:2071.71766
[357]	validation_0-mae:2071.82368
[358]	validation_0-mae:2071.95913
[359]	validation_0-mae:2072.53251
[360]	validation_0-mae:2071.78218
[361]	validation_0-mae:2071.36206
[362]	validation_0-mae:2071.64165
[363]	validation_0-mae:2071.40044
[364]	validation_0-mae:2071.55624
[365]	validation_0-mae:2071.13953
[366]	validation_0-mae:2071.13873
[367]	validation_0-mae:2070.92242
[368]	validation_0-mae:2070.45232
[369]	validation_0-mae:2070.36350
[370]	validation_0-mae:2070.05020
[371]	validation_0-mae:2070.11481
[372]	validation_0-mae:2070.32342
[373]	validation_0-mae:2070.18829
[374]	validation_0-mae:2070.28449
[375]	validation_0-mae:2070.68711
[376]	validation_0-mae:2070.99897
[377]	validation_0-mae:2071.02028
[378]	validation_0-mae:2070.82532
[379]	validation_0-mae:2071.11093
[380]	validation_0-mae:2071.68398
[381]	validation_0-mae:2072.10801
[382]	validation_0-mae:2072.11884
[383]	validation_0-mae:2071.89704
[384]	validation_0-mae:2072.22469
[385]	validation_0-mae:2072.05169
[386]	validation_0-mae:2071.70664
[387]	validation_0-mae:2071.42134
[388]	validation_0-mae:2071.25887
[389]	validation_0-mae:2071.14023
[390]	validation_0-mae:2070.51321
[391]	validation_0-mae:2070.14819
[392]	validation_0-mae:2070.35629
[393]	validation_0-mae:2070.67089
[394]	validation_0-mae:2069.65662
[395]	validation_0-mae:2069.17970
[396]	validation_0-mae:2069.36334
[397]	validation_0-mae:2069.52795
[398]	validation_0-mae:2069.63029
[399]	validation_0-mae:2069.70647
[400]	validation_0-mae:2070.34058
[401]	validation_0-mae:2070.09340
[402]	validation_0-mae:2069.79047
[403]	validation_0-mae:2069.50849
[404]	validation_0-mae:2069.11360
[405]	validation_0-mae:2069.44243
[406]	validation_0-mae:2069.12092
[407]	validation_0-mae:2068.47944
[408]	validation_0-mae:2067.87772
[409]	validation_0-mae:2067.00944
[410]	validation_0-mae:2067.04386
[411]	validation_0-mae:2066.62041
[412]	validation_0-mae:2066.29019
[413]	validation_0-mae:2066.13308
[414]	validation_0-mae:2065.91197
[415]	validation_0-mae:2064.45109
[416]	validation_0-mae:2063.85254
[417]	validation_0-mae:2063.99707
[418]	validation_0-mae:2063.42934
[419]	validation_0-mae:2062.37852
[420]	validation_0-mae:2062.52077
[421]	validation_0-mae:2062.37675
[422]	validation_0-mae:2061.89626
[423]	validation_0-mae:2061.89459
[424]	validation_0-mae:2061.96059
[425]	validation_0-mae:2061.72161
[426]	validation_0-mae:2061.88725
[427]	validation_0-mae:2061.59612
[428]	validation_0-mae:2061.44388
[429]	validation_0-mae:2061.04737
[430]	validation_0-mae:2061.29838
[431]	validation_0-mae:2061.63551
[432]	validation_0-mae:2061.06110
[433]	validation_0-mae:2061.41266
[434]	validation_0-mae:2061.32767
[435]	validation_0-mae:2061.69091
[436]	validation_0-mae:2061.27226
[437]	validation_0-mae:2061.13951
[438]	validation_0-mae:2060.76223
[439]	validation_0-mae:2060.68778
[440]	validation_0-mae:2060.29814
[441]	validation_0-mae:2060.33848
[442]	validation_0-mae:2060.42783
[443]	validation_0-mae:2060.49367
[444]	validation_0-mae:2060.12951
[445]	validation_0-mae:2060.21282
[446]	validation_0-mae:2059.50143
[447]	validation_0-mae:2059.04932
[448]	validation_0-mae:2059.20492
[449]	validation_0-mae:2059.15419
[450]	validation_0-mae:2058.05875
[451]	validation_0-mae:2057.96460
[452]	validation_0-mae:2058.01797
[453]	validation_0-mae:2058.00872
[454]	validation_0-mae:2058.11944
[455]	validation_0-mae:2057.37043
[456]	validation_0-mae:2057.14535
[457]	validation_0-mae:2057.43164
[458]	validation_0-mae:2057.11774
[459]	validation_0-mae:2057.29073
[460]	validation_0-mae:2056.86688
[461]	validation_0-mae:2057.01329
[462]	validation_0-mae:2057.17906
[463]	validation_0-mae:2056.91478
[464]	validation_0-mae:2056.71716
[465]	validation_0-mae:2056.35831
[466]	validation_0-mae:2056.37680
[467]	validation_0-mae:2056.01145
[468]	validation_0-mae:2056.01432
[469]	validation_0-mae:2055.90202
[470]	validation_0-mae:2056.30520
[471]	validation_0-mae:2056.66143
[472]	validation_0-mae:2056.82907
[473]	validation_0-mae:2055.84396
[474]	validation_0-mae:2055.69119
[475]	validation_0-mae:2055.95772
[476]	validation_0-mae:2056.05793
[477]	validation_0-mae:2055.88627
[478]	validation_0-mae:2056.13548
[479]	validation_0-mae:2055.70371
[480]	validation_0-mae:2056.07680
[481]	validation_0-mae:2056.17012
[482]	validation_0-mae:2056.37256
[483]	validation_0-mae:2056.10891
[484]	validation_0-mae:2056.13263
[485]	validation_0-mae:2056.36443
[486]	validation_0-mae:2056.24124
[487]	validation_0-mae:2056.36052
[488]	validation_0-mae:2056.46633
[489]	validation_0-mae:2056.39714
[490]	validation_0-mae:2056.64360
[491]	validation_0-mae:2056.96501
[492]	validation_0-mae:2057.31137
[493]	validation_0-mae:2057.26880
[494]	validation_0-mae:2057.11091
[495]	validation_0-mae:2056.27320
[496]	validation_0-mae:2056.17576
[497]	validation_0-mae:2055.07393
[498]	validation_0-mae:2054.81942
[499]	validation_0-mae:2054.36173
[500]	validation_0-mae:2054.17226
[501]	validation_0-mae:2054.21095
[502]	validation_0-mae:2053.94394
[503]	validation_0-mae:2053.84421
[504]	validation_0-mae:2054.27069
[505]	validation_0-mae:2054.06435
[506]	validation_0-mae:2054.65597
[507]	validation_0-mae:2055.09512
[508]	validation_0-mae:2055.10048
[509]	validation_0-mae:2054.81980
[510]	validation_0-mae:2054.74735
[511]	validation_0-mae:2054.73462
[512]	validation_0-mae:2054.68236
[513]	validation_0-mae:2054.38921
[514]	validation_0-mae:2054.59875
[515]	validation_0-mae:2054.71891
[516]	validation_0-mae:2054.93413
[517]	validation_0-mae:2054.79282
[518]	validation_0-mae:2054.45987
[519]	validation_0-mae:2054.68363
[520]	validation_0-mae:2054.86212
[521]	validation_0-mae:2055.02605
[522]	validation_0-mae:2054.68531
[523]	validation_0-mae:2054.20943
[524]	validation_0-mae:2053.68501
[525]	validation_0-mae:2053.28881
[526]	validation_0-mae:2053.09721
[527]	validation_0-mae:2053.52248
[528]	validation_0-mae:2053.73387
[529]	validation_0-mae:2053.98167
[530]	validation_0-mae:2054.02113
[531]	validation_0-mae:2053.94417
[532]	validation_0-mae:2054.03267
[533]	validation_0-mae:2054.20826
[534]	validation_0-mae:2054.01806
[535]	validation_0-mae:2054.37360
[536]	validation_0-mae:2054.25200
[537]	validation_0-mae:2054.42688
[538]	validation_0-mae:2054.31581
[539]	validation_0-mae:2054.51412
[540]	validation_0-mae:2054.51647
[541]	validation_0-mae:2054.24511
[542]	validation_0-mae:2053.84247
[543]	validation_0-mae:2053.83481
[544]	validation_0-mae:2053.89869
[545]	validation_0-mae:2052.53121
[546]	validation_0-mae:2052.76097
[547]	validation_0-mae:2052.92992
[548]	validation_0-mae:2052.86086
[549]	validation_0-mae:2052.71147
[550]	validation_0-mae:2053.30245
[551]	validation_0-mae:2053.75563
[552]	validation_0-mae:2053.47861
[553]	validation_0-mae:2053.38819
[554]	validation_0-mae:2052.95296
[555]	validation_0-mae:2053.21984
[556]	validation_0-mae:2053.16460
[557]	validation_0-mae:2053.09944
[558]	validation_0-mae:2052.93169
[559]	validation_0-mae:2052.84485
[560]	validation_0-mae:2052.33533
[561]	validation_0-mae:2051.66703
[562]	validation_0-mae:2051.93556
[563]	validation_0-mae:2051.84526
[564]	validation_0-mae:2051.92276
[565]	validation_0-mae:2052.00938
[566]	validation_0-mae:2052.03994
[567]	validation_0-mae:2051.93509
[568]	validation_0-mae:2051.65834
[569]	validation_0-mae:2051.67773
[570]	validation_0-mae:2051.36220
[571]	validation_0-mae:2051.28331
[572]	validation_0-mae:2051.31468
[573]	validation_0-mae:2050.77462
[574]	validation_0-mae:2050.95725
[575]	validation_0-mae:2050.82268
[576]	validation_0-mae:2050.61063
[577]	validation_0-mae:2050.15127
[578]	validation_0-mae:2050.27015
[579]	validation_0-mae:2049.86457
[580]	validation_0-mae:2049.90662
[581]	validation_0-mae:2049.73687
[582]	validation_0-mae:2049.91929
[583]	validation_0-mae:2050.01618
[584]	validation_0-mae:2050.39844
[585]	validation_0-mae:2049.96836
[586]	validation_0-mae:2049.96962
[587]	validation_0-mae:2050.24818
[588]	validation_0-mae:2050.21934
[589]	validation_0-mae:2050.08039
[590]	validation_0-mae:2050.30694

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[41]	validation_0-mae:3474.60847
[42]	validation_0-mae:3422.70844
[43]	validation_0-mae:3378.28065
[44]	validation_0-mae:3344.12224
[45]	validation_0-mae:3304.34848
[46]	validation_0-mae:3275.70722
[47]	validation_0-mae:3240.05117
[48]	validation_0-mae:3210.46363
[49]	validation_0-mae:3173.02504
[50]	validation_0-mae:3130.46539
[51]	validation_0-mae:3104.83899
[52]	validation_0-mae:3080.79112
[53]	validation_0-mae:3059.06649
[54]	validation_0-mae:3026.47104
[55]	validation_0-mae:3001.80387
[56]	validation_0-mae:2981.97769
[57]	validation_0-mae:2956.11641
[58]	validation_0-mae:2933.10291
[59]	validation_0-mae:2918.07553
[60]	validation_0-mae:2897.63212
[61]	validation_0-mae:2883.47190
[62]	validation_0-mae:2868.83938
[63]	validation_0-mae:2851.17091
[64]	validation_0-mae:2838.07499
[65]	validation_0-mae:2814.11804
[66]	validation_0-mae:2805.75040
[67]	validation_0-mae:2793.52705
[68]	validation_0-mae:2773.55837
[69]	validation_0-mae:2761.91331
[70]	validation_0-mae:2740.06207
[71]	validation_0-mae:2725.68956
[72]	validation_0-mae:2716.64581
[73]	validation_0-mae:2703.77281
[74]	validation_0-mae:2690.92977
[75]	validation_0-mae:2684.25752
[76]	validation_0-mae:2676.55544
[77]	validation_0-mae:2661.91643
[78]	validation_0-mae:2644.78252
[79]	validation_0-mae:2639.32832
[80]	validation_0-mae:2631.08893
[81]	validation_0-mae:2622.68760
[82]	validation_0-mae:2613.34087
[83]	validation_0-mae:2603.75368
[84]	validation_0-mae:2600.65220
[85]	validation_0-mae:2592.12232
[86]	validation_0-mae:2578.39356
[87]	validation_0-mae:2566.07766
[88]	validation_0-mae:2559.53851
[89]	validation_0-mae:2551.01685
[90]	validation_0-mae:2547.76323
[91]	validation_0-mae:2539.67562
[92]	validation_0-mae:2531.79746
[93]	validation_0-mae:2525.23915
[94]	validation_0-mae:2517.98392
[95]	validation_0-mae:2509.41379
[96]	validation_0-mae:2505.70353
[97]	validation_0-mae:2497.13227
[98]	validation_0-mae:2490.96777
[99]	validation_0-mae:2483.51345
[100]	validation_0-mae:2480.26143
[101]	validation_0-mae:2474.89523
[102]	validation_0-mae:2470.03004
[103]	validation_0-mae:2466.25071
[104]	validation_0-mae:2459.41940
[105]	validation_0-mae:2452.01655
[106]	validation_0-mae:2444.40810
[107]	validation_0-mae:2439.77473
[108]	validation_0-mae:2433.79447
[109]	validation_0-mae:2430.87901
[110]	validation_0-mae:2425.41288
[111]	validation_0-mae:2422.85112
[112]	validation_0-mae:2418.74935
[113]	validation_0-mae:2410.23362
[114]	validation_0-mae:2409.16572
[115]	validation_0-mae:2407.45381
[116]	validation_0-mae:2402.84892
[117]	validation_0-mae:2399.78843
[0]	validation_0-mae:12379.88507
[1]	validation_0-mae:11607.23823
[2]	validation_0-mae:10892.34158
[3]	validation_0-mae:10228.84743
[4]	validation_0-mae:9669.31711
[5]	validation_0-mae:9151.66522
[6]	validation_0-mae:8691.04620
[7]	validation_0-mae:8286.78093
[8]	validation_0-mae:7917.86745
[9]	validation_0-mae:7564.33111
[10]	validation_0-mae:7238.86549
[11]	validation_0-mae:6935.79377
[12]	validation_0-mae:6649.18163
[13]	validation_0-mae:6367.42140
[14]	validation_0-mae:6144.02270
[15]	validation_0-mae:5899.34387
[16]	validation_0-mae:5645.54877
[17]	validation_0-mae:5460.01312
[18]	validation_0-mae:5265.86614
[19]	validation_0-mae:5094.33067
[20]	validation_0-mae:4932.19553
[21]	validation_0-mae:4782.30598
[22]	validation_0-mae:4639.04294
[23]	validation_0-mae:4500.17601
[24]	validation_0-mae:4385.29098
[25]	validation_0-mae:4255.09987
[26]	validation_0-mae:4146.78323
[27]	validation_0-mae:4042.34292
[28]	validation_0-mae:3947.03531
[29]	validation_0-mae:3866.25649
[30]	validation_0-mae:3777.37409
[31]	validation_0-mae:3707.16605
[32]	validation_0-mae:3646.04333
[33]	validation_0-mae:3580.02463
[34]	validation_0-mae:3500.44466
[35]	validation_0-mae:3444.54579
[36]	validation_0-mae:3396.13856
[37]	validation_0-mae:3322.61136
[38]	validation_0-mae:3272.03747
[39]	validation_0-mae:3225.84803
[40]	validation_0-mae:3182.63518

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[41]	validation_0-mae:3146.73500
[42]	validation_0-mae:3110.95417
[43]	validation_0-mae:3073.94715
[44]	validation_0-mae:3042.09030
[45]	validation_0-mae:3000.85494
[46]	validation_0-mae:2965.53242
[47]	validation_0-mae:2937.54393
[48]	validation_0-mae:2916.69726
[49]	validation_0-mae:2891.36848
[50]	validation_0-mae:2853.83916
[51]	validation_0-mae:2829.43932
[52]	validation_0-mae:2808.87266
[53]	validation_0-mae:2788.60161
[54]	validation_0-mae:2771.09345
[55]	validation_0-mae:2751.97075
[56]	validation_0-mae:2735.15992
[57]	validation_0-mae:2719.59659
[58]	validation_0-mae:2702.63134
[59]	validation_0-mae:2686.24661
[60]	validation_0-mae:2671.72083
[61]	validation_0-mae:2651.54761
[62]	validation_0-mae:2622.55744
[63]	validation_0-mae:2612.25940
[64]	validation_0-mae:2594.06937
[65]	validation_0-mae:2583.26031
[66]	validation_0-mae:2571.06600
[67]	validation_0-mae:2555.12548
[68]	validation_0-mae:2544.75788
[69]	validation_0-mae:2538.16661
[70]	validation_0-mae:2526.61057
[71]	validation_0-mae:2516.35812
[72]	validation_0-mae:2509.90005
[73]	validation_0-mae:2501.83455
[74]	validation_0-mae:2490.03421
[75]	validation_0-mae:2474.07954
[76]	validation_0-mae:2463.57592
[77]	validation_0-mae:2456.47277
[78]	validation_0-mae:2451.23879
[79]	validation_0-mae:2438.55267
[80]	validation_0-mae:2429.17811
[81]	validation_0-mae:2423.28335
[82]	validation_0-mae:2417.68598
[83]	validation_0-mae:2408.77256
[84]	validation_0-mae:2401.86786
[85]	validation_0-mae:2398.30622
[86]	validation_0-mae:2383.48612
[87]	validation_0-mae:2375.10103
[88]	validation_0-mae:2366.75451
[89]	validation_0-mae:2359.29196
[90]	validation_0-mae:2351.63121
[91]	validation_0-mae:2347.22534
[92]	validation_0-mae:2343.12544
[93]	validation_0-mae:2337.09036
[94]	validation_0-mae:2330.34858
[95]	validation_0-mae:2327.32509
[96]	validation_0-mae:2321.30851
[97]	validation_0-mae:2316.72766
[98]	validation_0-mae:2312.44185
[99]	validation_0-mae:2302.65818
[100]	validation_0-mae:2295.77414
[101]	validation_0-mae:2289.26175
[102]	validation_0-mae:2281.79136
[103]	validation_0-mae:2276.97373
[104]	validation_0-mae:2273.10126
[105]	validation_0-mae:2268.83498
[106]	validation_0-mae:2264.44720
[107]	validation_0-mae:2257.58143
[108]	validation_0-mae:2252.98628
[109]	validation_0-mae:2249.49662
[110]	validation_0-mae:2247.07908
[111]	validation_0-mae:2243.90571
[112]	validation_0-mae:2243.39924
[113]	validation_0-mae:2240.43276
[114]	validation_0-mae:2240.37653
[115]	validation_0-mae:2235.48874
[116]	validation_0-mae:2235.01799
[117]	validation_0-mae:2231.35759
[118]	validation_0-mae:2226.58490
[119]	validation_0-mae:2221.98125
[120]	validation_0-mae:2217.41002
[121]	validation_0-mae:2216.23103
[122]	validation_0-mae:2216.37879
[123]	validation_0-mae:2213.63566
[124]	validation_0-mae:2208.62549
[125]	validation_0-mae:2208.24220
[126]	validation_0-mae:2207.47257
[127]	validation_0-mae:2205.43869
[128]	validation_0-mae:2204.01382
[129]	validation_0-mae:2200.80811
[130]	validation_0-mae:2199.77166
[131]	validation_0-mae:2197.47558
[132]	validation_0-mae:2197.37524
[133]	validation_0-mae:2195.80791
[134]	validation_0-mae:2194.08897
[135]	validation_0-mae:2189.49516
[136]	validation_0-mae:2188.85185
[137]	validation_0-mae:2185.70696
[138]	validation_0-mae:2181.69551
[139]	validation_0-mae:2179.83938
[140]	validation_0-mae:2177.44187
[141]	validation_0-mae:2176.15506
[142]	validation_0-mae:2177.09241
[143]	validation_0-mae:2174.69993
[144]	validation_0-mae:2171.92876
[145]	validation_0-mae:2171.32621
[146]	validation_0-mae:2168.00671
[147]	validation_0-mae:2166.10319
[148]	validation_0-mae:2164.35636
[149]	validation_0-mae:2163.59491
[150]	validation_0-mae:2164.52425
[151]	validation_0-mae:2164.62225
[152]	validation_0-mae:2164.07739
[153]	validation_0-mae:2162.81828
[154]	validation_0-mae:2160.86396
[155]	validation_0-mae:2158.40249
[156]	validation_0-mae:2157.67101
[157]	validation_0-mae:2158.63954
[158]	validation_0-mae:2156.66260
[159]	validation_0-mae:2154.89927
[160]	validation_0-mae:2153.72106
[161]	validation_0-mae:2151.18599
[162]	validation_0-mae:2149.99562
[163]	validation_0-mae:2150.53761
[164]	validation_0-mae:2146.94105
[165]	validation_0-mae:2146.68176
[166]	validation_0-mae:2146.58717
[167]	validation_0-mae:2146.12318
[168]	validation_0-mae:2145.47459
[169]	validation_0-mae:2145.02649
[170]	validation_0-mae:2144.86807
[171]	validation_0-mae:2145.83349
[172]	validation_0-mae:2145.98329
[173]	validation_0-mae:2144.85428
[174]	validation_0-mae:2145.45275
[175]	validation_0-mae:2143.44118
[176]	validation_0-mae:2143.07226
[177]	validation_0-mae:2142.55965
[178]	validation_0-mae:2140.96176
[179]	validation_0-mae:2139.63917
[180]	validation_0-mae:2136.09826
[181]	validation_0-mae:2136.53518
[182]	validation_0-mae:2137.99889
[183]	validation_0-mae:2136.23957
[184]	validation_0-mae:2134.77953
[185]	validation_0-mae:2134.04251
[186]	validation_0-mae:2133.36615
[187]	validation_0-mae:2133.64865
[188]	validation_0-mae:2131.59643
[189]	validation_0-mae:2129.99313
[190]	validation_0-mae:2130.50055
[191]	validation_0-mae:2129.42294
[192]	validation_0-mae:2129.68783
[193]	validation_0-mae:2128.63936
[194]	validation_0-mae:2128.85110
[195]	validation_0-mae:2127.76054
[196]	validation_0-mae:2127.06828
[197]	validation_0-mae:2127.34316
[198]	validation_0-mae:2127.54965
[199]	validation_0-mae:2127.55280
[200]	validation_0-mae:2126.67068
[201]	validation_0-mae:2125.54809
[202]	validation_0-mae:2124.26638
[203]	validation_0-mae:2121.56390
[204]	validation_0-mae:2121.56857
[205]	validation_0-mae:2122.05146
[206]	validation_0-mae:2122.34992
[207]	validation_0-mae:2122.84363
[208]	validation_0-mae:2122.74538
[209]	validation_0-mae:2122.50513
[210]	validation_0-mae:2120.88231
[211]	validation_0-mae:2120.36415
[212]	validation_0-mae:2120.89317
[213]	validation_0-mae:2120.10962
[214]	validation_0-mae:2119.12779
[215]	validation_0-mae:2119.15828
[216]	validation_0-mae:2119.36903
[217]	validation_0-mae:2120.29350
[218]	validation_0-mae:2118.79324
[219]	validation_0-mae:2118.64051
[220]	validation_0-mae:2119.42032
[221]	validation_0-mae:2118.98881
[222]	validation_0-mae:2118.56334
[223]	validation_0-mae:2117.44020
[224]	validation_0-mae:2118.18326
[225]	validation_0-mae:2117.87567
[226]	validation_0-mae:2116.88379
[227]	validation_0-mae:2116.93016
[228]	validation_0-mae:2116.86758
[229]	validation_0-mae:2116.65641
[230]	validation_0-mae:2116.26215
[231]	validation_0-mae:2117.01979
[232]	validation_0-mae:2117.11917
[233]	validation_0-mae:2117.30847
[234]	validation_0-mae:2117.41698
[235]	validation_0-mae:2115.97801
[236]	validation_0-mae:2116.45191
[237]	validation_0-mae:2115.01799
[238]	validation_0-mae:2113.89983
[239]	validation_0-mae:2113.09396
[240]	validation_0-mae:2113.11474
[241]	validation_0-mae:2113.04910
[242]	validation_0-mae:2112.57897
[243]	validation_0-mae:2112.37420
[244]	validation_0-mae:2111.32985
[245]	validation_0-mae:2110.44596
[246]	validation_0-mae:2109.96139
[247]	validation_0-mae:2110.37620
[248]	validation_0-mae:2110.57437
[249]	validation_0-mae:2110.34743
[250]	validation_0-mae:2109.99121
[251]	validation_0-mae:2109.63822
[252]	validation_0-mae:2109.45742
[253]	validation_0-mae:2107.51063
[254]	validation_0-mae:2106.65301
[255]	validation_0-mae:2105.98390
[256]	validation_0-mae:2106.95849
[257]	validation_0-mae:2106.98180
[258]	validation_0-mae:2105.95564
[259]	validation_0-mae:2106.41164
[260]	validation_0-mae:2104.92734
[261]	validation_0-mae:2105.13073
[262]	validation_0-mae:2104.00498
[263]	validation_0-mae:2103.78255
[264]	validation_0-mae:2104.32496
[265]	validation_0-mae:2104.58924
[266]	validation_0-mae:2104.37093
[267]	validation_0-mae:2104.17205
[268]	validation_0-mae:2103.59278
[269]	validation_0-mae:2103.51271
[270]	validation_0-mae:2102.50701
[271]	validation_0-mae:2102.15170
[272]	validation_0-mae:2102.76935
[273]	validation_0-mae:2102.16804
[274]	validation_0-mae:2101.17794
[275]	validation_0-mae:2100.71813
[276]	validation_0-mae:2099.41921
[277]	validation_0-mae:2099.32552
[278]	validation_0-mae:2097.71772
[279]	validation_0-mae:2097.99754
[280]	validation_0-mae:2097.76232
[281]	validation_0-mae:2096.95801
[282]	validation_0-mae:2095.81650
[283]	validation_0-mae:2094.64557
[284]	validation_0-mae:2094.00195
[285]	validation_0-mae:2093.46558
[286]	validation_0-mae:2092.75352
[287]	validation_0-mae:2092.58340
[288]	validation_0-mae:2092.46294
[289]	validation_0-mae:2091.44340
[290]	validation_0-mae:2091.86180
[291]	validation_0-mae:2090.94759
[292]	validation_0-mae:2091.45017
[293]	validation_0-mae:2091.21486
[294]	validation_0-mae:2089.50011
[295]	validation_0-mae:2088.72509
[296]	validation_0-mae:2088.48449
[297]	validation_0-mae:2087.62214
[298]	validation_0-mae:2087.40101
[299]	validation_0-mae:2086.36112
[300]	validation_0-mae:2086.17117
[301]	validation_0-mae:2086.11074
[302]	validation_0-mae:2085.36136
[303]	validation_0-mae:2084.72397
[304]	validation_0-mae:2085.67158
[305]	validation_0-mae:2085.36218
[306]	validation_0-mae:2085.71644
[307]	validation_0-mae:2085.98418
[308]	validation_0-mae:2084.90031
[309]	validation_0-mae:2084.96980
[310]	validation_0-mae:2085.99450
[311]	validation_0-mae:2085.97040
[312]	validation_0-mae:2086.01265
[313]	validation_0-mae:2085.98774
[314]	validation_0-mae:2085.95438
[315]	validation_0-mae:2086.75452
[316]	validation_0-mae:2086.27596
[317]	validation_0-mae:2085.66230
[318]	validation_0-mae:2085.66998
[319]	validation_0-mae:2085.38126
[320]	validation_0-mae:2085.71032
[321]	validation_0-mae:2085.54744
[322]	validation_0-mae:2085.81860
[323]	validation_0-mae:2085.54147
[324]	validation_0-mae:2085.60457
[325]	validation_0-mae:2085.59829
[326]	validation_0-mae:2086.35814
[327]	validation_0-mae:2086.08234
[328]	validation_0-mae:2086.68242
[329]	validation_0-mae:2085.86433
[330]	validation_0-mae:2084.71382
[331]	validation_0-mae:2083.93481
[332]	validation_0-mae:2083.85295
[333]	validation_0-mae:2082.85798
[334]	validation_0-mae:2082.23451
[335]	validation_0-mae:2082.05298
[336]	validation_0-mae:2081.51314
[337]	validation_0-mae:2081.13922
[338]	validation_0-mae:2079.25288
[339]	validation_0-mae:2078.49682
[340]	validation_0-mae:2077.60109
[341]	validation_0-mae:2075.69963
[342]	validation_0-mae:2074.16902
[343]	validation_0-mae:2074.19701
[344]	validation_0-mae:2073.52291
[345]	validation_0-mae:2073.49535
[346]	validation_0-mae:2072.83644
[347]	validation_0-mae:2072.65271
[348]	validation_0-mae:2072.72936
[349]	validation_0-mae:2073.16851
[350]	validation_0-mae:2073.70858
[351]	validation_0-mae:2074.28986
[352]	validation_0-mae:2073.48072
[353]	validation_0-mae:2073.76784
[354]	validation_0-mae:2071.32867
[355]	validation_0-mae:2072.01496
[356]	validation_0-mae:2071.66239
[357]	validation_0-mae:2071.79849
[358]	validation_0-mae:2071.08489
[359]	validation_0-mae:2071.52148
[360]	validation_0-mae:2071.36876
[361]	validation_0-mae:2071.04123
[362]	validation_0-mae:2070.46291
[363]	validation_0-mae:2070.83949
[364]	validation_0-mae:2071.93522
[365]	validation_0-mae:2072.37341
[366]	validation_0-mae:2073.28845
[367]	validation_0-mae:2072.30848
[368]	validation_0-mae:2071.06648
[369]	validation_0-mae:2070.86041
[370]	validation_0-mae:2071.24837
[371]	validation_0-mae:2071.16036
[372]	validation_0-mae:2070.87799
[373]	validation_0-mae:2070.47048
[374]	validation_0-mae:2070.20965
[375]	validation_0-mae:2069.59580
[376]	validation_0-mae:2069.14156
[377]	validation_0-mae:2069.38064
[378]	validation_0-mae:2069.95686
[379]	validation_0-mae:2069.87741
[380]	validation_0-mae:2070.04670
[381]	validation_0-mae:2069.91265
[382]	validation_0-mae:2070.11914
[383]	validation_0-mae:2070.52801
[384]	validation_0-mae:2069.56786
[385]	validation_0-mae:2069.65500
[386]	validation_0-mae:2069.75606
[387]	validation_0-mae:2069.27990
[388]	validation_0-mae:2069.39148
[389]	validation_0-mae:2069.26870
[390]	validation_0-mae:2069.22310
[391]	validation_0-mae:2068.15486
[392]	validation_0-mae:2068.36549
[393]	validation_0-mae:2068.33948
[394]	validation_0-mae:2068.11280
[395]	validation_0-mae:2068.08175
[396]	validation_0-mae:2068.60834
[397]	validation_0-mae:2068.93158
[398]	validation_0-mae:2068.93782
[399]	validation_0-mae:2069.17034
[400]	validation_0-mae:2068.63765
[401]	validation_0-mae:2068.97503
[402]	validation_0-mae:2068.88462
[403]	validation_0-mae:2069.26120
[404]	validation_0-mae:2069.33797
[405]	validation_0-mae:2069.26947
[406]	validation_0-mae:2069.35891
[407]	validation_0-mae:2069.85949
[408]	validation_0-mae:2069.82272
[409]	validation_0-mae:2069.96573
[410]	validation_0-mae:2069.96126
[411]	validation_0-mae:2069.10247
[412]	validation_0-mae:2069.50438
[413]	validation_0-mae:2069.33787
[414]	validation_0-mae:2068.77200
[415]	validation_0-mae:2068.75322
[416]	validation_0-mae:2069.03461
[417]	validation_0-mae:2069.33780
[418]	validation_0-mae:2069.16542
[419]	validation_0-mae:2069.17015
[420]	validation_0-mae:2067.72948
[421]	validation_0-mae:2067.36776
[422]	validation_0-mae:2067.50464
[423]	validation_0-mae:2067.46674
[424]	validation_0-mae:2067.45178
[425]	validation_0-mae:2067.22167
[426]	validation_0-mae:2066.74389
[427]	validation_0-mae:2066.91690
[428]	validation_0-mae:2066.73933
[429]	validation_0-mae:2067.08971
[430]	validation_0-mae:2067.32974
[431]	validation_0-mae:2067.27794
[432]	validation_0-mae:2066.63547
[433]	validation_0-mae:2066.79123
[434]	validation_0-mae:2066.96309
[435]	validation_0-mae:2067.47484
[436]	validation_0-mae:2067.71498
[437]	validation_0-mae:2068.51145
[438]	validation_0-mae:2067.41959
[439]	validation_0-mae:2067.30742
[440]	validation_0-mae:2066.52624
[441]	validation_0-mae:2066.12173
[442]	validation_0-mae:2064.60410
[443]	validation_0-mae:2064.19918
[444]	validation_0-mae:2063.90291
[445]	validation_0-mae:2064.36937
[446]	validation_0-mae:2063.47238
[447]	validation_0-mae:2063.32274
[448]	validation_0-mae:2063.21322
[449]	validation_0-mae:2063.37325
[450]	validation_0-mae:2063.02513
[451]	validation_0-mae:2062.55368
[452]	validation_0-mae:2062.62858
[453]	validation_0-mae:2062.70200
[454]	validation_0-mae:2062.97491
[455]	validation_0-mae:2062.61938
[456]	validation_0-mae:2062.58024
[457]	validation_0-mae:2062.13482
[458]	validation_0-mae:2062.09398
[459]	validation_0-mae:2061.85274
[460]	validation_0-mae:2062.12132
[461]	validation_0-mae:2060.38531
[462]	validation_0-mae:2060.38919
[463]	validation_0-mae:2060.15971
[464]	validation_0-mae:2060.13788
[465]	validation_0-mae:2060.55796
[466]	validation_0-mae:2060.44627
[467]	validation_0-mae:2059.44842
[468]	validation_0-mae:2059.53837
[469]	validation_0-mae:2059.52569
[470]	validation_0-mae:2059.22517
[471]	validation_0-mae:2059.24991
[472]	validation_0-mae:2058.99175
[473]	validation_0-mae:2059.17045
[474]	validation_0-mae:2059.14266
[475]	validation_0-mae:2058.21783
[476]	validation_0-mae:2057.33976
[477]	validation_0-mae:2057.12779
[478]	validation_0-mae:2057.51746
[479]	validation_0-mae:2057.07556
[480]	validation_0-mae:2056.11037
[481]	validation_0-mae:2055.98128
[482]	validation_0-mae:2056.35515
[483]	validation_0-mae:2055.89293
[484]	validation_0-mae:2054.46793
[485]	validation_0-mae:2054.06712
[486]	validation_0-mae:2053.87610
[487]	validation_0-mae:2053.73544
[488]	validation_0-mae:2053.71828
[489]	validation_0-mae:2053.86013
[490]	validation_0-mae:2053.77311
[491]	validation_0-mae:2053.50108
[492]	validation_0-mae:2053.70740
[493]	validation_0-mae:2053.59030
[494]	validation_0-mae:2053.59573
[495]	validation_0-mae:2054.15458
[496]	validation_0-mae:2053.18272
[497]	validation_0-mae:2053.27582
[498]	validation_0-mae:2052.84980
[499]	validation_0-mae:2052.74003
[500]	validation_0-mae:2052.84440
[501]	validation_0-mae:2052.28814
[502]	validation_0-mae:2052.00911
[503]	validation_0-mae:2052.19783
[504]	validation_0-mae:2051.91651
[505]	validation_0-mae:2051.81539
[506]	validation_0-mae:2051.60218
[507]	validation_0-mae:2051.13518
[508]	validation_0-mae:2050.92822
[509]	validation_0-mae:2051.41658
[510]	validation_0-mae:2051.63168
[511]	validation_0-mae:2051.74130
[512]	validation_0-mae:2051.63396
[513]	validation_0-mae:2051.85897
[514]	validation_0-mae:2051.80945
[515]	validation_0-mae:2051.75064
[516]	validation_0-mae:2050.95570
[517]	validation_0-mae:2050.55527
[518]	validation_0-mae:2049.98684
[519]	validation_0-mae:2050.48049
[520]	validation_0-mae:2050.21464
[521]	validation_0-mae:2050.01530
[522]	validation_0-mae:2049.59631
[523]	validation_0-mae:2049.73421
[524]	validation_0-mae:2050.14490
[525]	validation_0-mae:2050.48687
[526]	validation_0-mae:2049.73233
[527]	validation_0-mae:2049.94902
[528]	validation_0-mae:2049.12247
[529]	validation_0-mae:2048.82684
[530]	validation_0-mae:2048.61722
[531]	validation_0-mae:2048.53497
[532]	validation_0-mae:2048.29406
[533]	validation_0-mae:2048.11609
[534]	validation_0-mae:2047.97881
[535]	validation_0-mae:2048.02488
[536]	validation_0-mae:2047.36352
[537]	validation_0-mae:2047.52994
[538]	validation_0-mae:2047.28174
[539]	validation_0-mae:2047.26881
[540]	validation_0-mae:2046.97875
[541]	validation_0-mae:2046.61201
[542]	validation_0-mae:2046.84200
[543]	validation_0-mae:2046.43551
[544]	validation_0-mae:2046.50083
[545]	validation_0-mae:2046.27753
[546]	validation_0-mae:2045.84200
[547]	validation_0-mae:2045.85223
[548]	validation_0-mae:2045.98824
[549]	validation_0-mae:2045.73220
[550]	validation_0-mae:2045.84888
[551]	validation_0-mae:2045.83320
[552]	validation_0-mae:2045.88792
[553]	validation_0-mae:2046.07787
[554]	validation_0-mae:2045.70157
[555]	validation_0-mae:2045.44873
[556]	validation_0-mae:2045.28017
[557]	validation_0-mae:2044.90980
[558]	validation_0-mae:2045.14354
[559]	validation_0-mae:2044.77838
[560]	validation_0-mae:2044.83075
[561]	validation_0-mae:2044.65826
[562]	validation_0-mae:2044.76644
[563]	validation_0-mae:2044.65122
[564]	validation_0-mae:2044.74677
[565]	validation_0-mae:2044.65429
[566]	validation_0-mae:2044.54403
[567]	validation_0-mae:2044.36192
[568]	validation_0-mae:2044.43601
[569]	validation_0-mae:2044.74632
[570]	validation_0-mae:2044.62221
[571]	validation_0-mae:2045.05222
[572]	validation_0-mae:2045.08224
[573]	validation_0-mae:2045.09266
[574]	validation_0-mae:2045.07392
[575]	validation_0-mae:2045.16579
[576]	validation_0-mae:2045.32917
[577]	validation_0-mae:2045.69170
[578]	validation_0-mae:2045.62402
[579]	validation_0-mae:2045.92915
[580]	validation_0-mae:2045.96138
[581]	validation_0-mae:2046.36222
[582]	validation_0-mae:2046.28596
[583]	validation_0-mae:2046.33100
[584]	validation_0-mae:2046.54993
[585]	validation_0-mae:2046.46657
[586]	validation_0-mae:2046.54527
[587]	validation_0-mae:2046.59698
[588]	validation_0-mae:2046.69044
[589]	validation_0-mae:2046.59734
[590]	validation_0-mae:2046.76438
[591]	validation_0-mae:2046.46369
[592]	validation_0-mae:2046.44042
[593]	validation_0-mae:2046.41314
[594]	validation_0-mae:2046.25585
[595]	validation_0-mae:2046.37353
[596]	validation_0-mae:2046.46304
[597]	validation_0-mae:2046.40980
[598]	validation_0-mae:2046.60357
[599]	validation_0-mae:2045.70582
[600]	validation_0-mae:2044.81300
[601]	validation_0-mae:2044.81833
[602]	validation_0-mae:2044.85481
[603]	validation_0-mae:2045.08143
[604]	validation_0-mae:2045.19377
[605]	validation_0-mae:2044.79270
[606]	validation_0-mae:2044.89778
[607]	validation_0-mae:2044.95255
[608]	validation_0-mae:2044.78023
[609]	validation_0-mae:2043.78970
[610]	validation_0-mae:2043.56763
[611]	validation_0-mae:2043.43699
[612]	validation_0-mae:2043.40847
[613]	validation_0-mae:2043.20442
[614]	validation_0-mae:2042.99267
[615]	validation_0-mae:2042.87239
[616]	validation_0-mae:2042.85598
[617]	validation_0-mae:2042.97920
[618]	validation_0-mae:2043.24008
[619]	validation_0-mae:2043.29188
[620]	validation_0-mae:2043.07798
[621]	validation_0-mae:2043.17118
[622]	validation_0-mae:2043.22689
[623]	validation_0-mae:2043.17792
[624]	validation_0-mae:2043.09407
[625]	validation_0-mae:2042.90981
[626]	validation_0-mae:2042.21299
[627]	validation_0-mae:2042.27236
[628]	validation_0-mae:2042.46282
[629]	validation_0-mae:2041.93265

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[41]	validation_0-mae:3172.12782
[42]	validation_0-mae:3139.12800
[43]	validation_0-mae:3104.58826
[44]	validation_0-mae:3075.30876
[45]	validation_0-mae:3046.17988
[46]	validation_0-mae:3001.78892
[47]	validation_0-mae:2955.18432
[48]	validation_0-mae:2923.29631
[49]	validation_0-mae:2897.69463
[50]	validation_0-mae:2867.25812
[51]	validation_0-mae:2845.63517
[52]	validation_0-mae:2821.29030
[53]	validation_0-mae:2801.21899
[54]	validation_0-mae:2780.28472
[55]	validation_0-mae:2767.29145
[56]	validation_0-mae:2751.44471
[57]	validation_0-mae:2738.69075
[58]	validation_0-mae:2720.36934
[59]	validation_0-mae:2709.34786
[60]	validation_0-mae:2686.19521
[61]	validation_0-mae:2666.60568
[62]	validation_0-mae:2637.16222
[63]	validation_0-mae:2623.69360
[64]	validation_0-mae:2607.37932
[65]	validation_0-mae:2598.15479
[66]	validation_0-mae:2585.82527
[67]	validation_0-mae:2573.77533
[68]	validation_0-mae:2562.23579
[69]	validation_0-mae:2544.43529
[70]	validation_0-mae:2535.78891
[71]	validation_0-mae:2524.92167
[72]	validation_0-mae:2507.62848
[73]	validation_0-mae:2500.53773
[74]	validation_0-mae:2494.04327
[75]	validation_0-mae:2485.33384
[76]	validation_0-mae:2468.85845
[77]	validation_0-mae:2457.52333
[78]	validation_0-mae:2451.30627
[79]	validation_0-mae:2446.30114
[80]	validation_0-mae:2437.15187
[81]	validation_0-mae:2434.07448
[82]	validation_0-mae:2423.94339
[83]	validation_0-mae:2419.36959
[84]	validation_0-mae:2408.36189
[85]	validation_0-mae:2400.71932
[86]	validation_0-mae:2391.72367
[87]	validation_0-mae:2387.94428
[88]	validation_0-mae:2381.98374
[89]	validation_0-mae:2374.95454
[90]	validation_0-mae:2364.63262
[91]	validation_0-mae:2359.67047
[92]	validation_0-mae:2353.63709
[93]	validation_0-mae:2347.03611
[94]	validation_0-mae:2340.00906
[95]	validation_0-mae:2335.13281
[96]	validation_0-mae:2329.24046
[97]	validation_0-mae:2327.22707
[98]	validation_0-mae:2320.56508
[99]	validation_0-mae:2317.96247
[100]	validation_0-mae:2314.65656
[101]	validation_0-mae:2308.82534
[102]	validation_0-mae:2303.67627
[103]	validation_0-mae:2297.54121
[104]	validation_0-mae:2294.93348
[105]	validation_0-mae:2292.64266
[106]	validation_0-mae:2289.03934
[107]	validation_0-mae:2284.11348
[108]	validation_0-mae:2280.72790
[109]	validation_0-mae:2278.04270
[110]	validation_0-mae:2274.67283
[111]	validation_0-mae:2274.71638
[112]	validation_0-mae:2270.89014
[113]	validation_0-mae:2269.48646
[114]	validation_0-mae:2267.41881
[115]	validation_0-mae:2264.82413
[116]	validation_0-mae:2261.92762
[117]	validation_0-mae:2260.56667
[118]	validation_0-mae:2259.96386
[119]	validation_0-mae:2255.72962
[120]	validation_0-mae:2252.48285
[121]	validation_0-mae:2249.17745
[122]	validation_0-mae:2247.59390
[123]	validation_0-mae:2243.68763
[124]	validation_0-mae:2239.16577
[125]	validation_0-mae:2240.46405
[126]	validation_0-mae:2235.64304
[127]	validation_0-mae:2233.00228
[128]	validation_0-mae:2232.20175
[129]	validation_0-mae:2231.12805
[130]	validation_0-mae:2228.56731
[131]	validation_0-mae:2226.47099
[132]	validation_0-mae:2225.64627
[133]	validation_0-mae:2221.67060
[134]	validation_0-mae:2220.27685
[135]	validation_0-mae:2220.31834
[136]	validation_0-mae:2216.63248
[137]	validation_0-mae:2216.20668
[138]	validation_0-mae:2212.23294
[139]	validation_0-mae:2208.36030
[140]	validation_0-mae:2207.73423
[141]	validation_0-mae:2201.73358
[142]	validation_0-mae:2200.57069
[143]	validation_0-mae:2199.17124
[144]	validation_0-mae:2194.20367
[145]	validation_0-mae:2191.97201
[146]	validation_0-mae:2189.96039
[147]	validation_0-mae:2186.63229
[148]	validation_0-mae:2185.97219
[149]	validation_0-mae:2184.30838
[150]	validation_0-mae:2182.06192
[151]	validation_0-mae:2179.91823
[152]	validation_0-mae:2178.85853
[153]	validation_0-mae:2178.90510
[154]	validation_0-mae:2178.05963
[155]	validation_0-mae:2176.53286
[156]	validation_0-mae:2177.01493
[157]	validation_0-mae:2175.68516
[158]	validation_0-mae:2172.11626
[159]	validation_0-mae:2172.56067
[160]	validation_0-mae:2171.47253
[161]	validation_0-mae:2171.50977
[162]	validation_0-mae:2169.48808
[163]	validation_0-mae:2168.21842
[164]	validation_0-mae:2166.91391
[165]	validation_0-mae:2166.00799
[166]	validation_0-mae:2166.26743
[167]	validation_0-mae:2163.44156
[168]	validation_0-mae:2163.58625
[169]	validation_0-mae:2160.88596
[170]	validation_0-mae:2156.91014
[171]	validation_0-mae:2155.35765
[172]	validation_0-mae:2154.28801
[173]	validation_0-mae:2151.02022
[174]	validation_0-mae:2151.53064
[175]	validation_0-mae:2150.21628
[176]	validation_0-mae:2148.37938
[177]	validation_0-mae:2145.65434
[178]	validation_0-mae:2145.53320
[179]	validation_0-mae:2144.32735
[180]	validation_0-mae:2144.81391
[181]	validation_0-mae:2144.67383
[182]	validation_0-mae:2143.31150
[183]	validation_0-mae:2142.34767
[184]	validation_0-mae:2141.34396
[185]	validation_0-mae:2140.69278
[186]	validation_0-mae:2137.90395
[187]	validation_0-mae:2138.33935
[188]	validation_0-mae:2139.68968
[189]	validation_0-mae:2138.43553
[190]	validation_0-mae:2137.61869
[191]	validation_0-mae:2137.90722
[192]	validation_0-mae:2138.98217
[193]	validation_0-mae:2138.02176
[194]	validation_0-mae:2135.53219
[195]	validation_0-mae:2135.77723
[196]	validation_0-mae:2134.04769
[197]	validation_0-mae:2133.94234
[198]	validation_0-mae:2134.33994
[199]	validation_0-mae:2135.16871
[200]	validation_0-mae:2135.83607
[201]	validation_0-mae:2133.98061
[202]	validation_0-mae:2133.49159
[203]	validation_0-mae:2134.13371
[204]	validation_0-mae:2133.24842
[205]	validation_0-mae:2133.10956
[206]	validation_0-mae:2132.10228
[207]	validation_0-mae:2132.17650
[208]	validation_0-mae:2129.12939
[209]	validation_0-mae:2128.47459
[210]	validation_0-mae:2127.24418
[211]	validation_0-mae:2127.11170
[212]	validation_0-mae:2127.67885
[213]	validation_0-mae:2127.30557
[214]	validation_0-mae:2127.05250
[215]	validation_0-mae:2127.28166
[216]	validation_0-mae:2127.02517
[217]	validation_0-mae:2124.87801
[218]	validation_0-mae:2124.19385
[219]	validation_0-mae:2125.02369
[220]	validation_0-mae:2126.59867
[221]	validation_0-mae:2125.97611
[222]	validation_0-mae:2126.30078
[223]	validation_0-mae:2123.73372
[224]	validation_0-mae:2123.08359
[225]	validation_0-mae:2123.47192
[226]	validation_0-mae:2123.07657
[227]	validation_0-mae:2123.01859
[228]	validation_0-mae:2123.02908
[229]	validation_0-mae:2120.43080
[230]	validation_0-mae:2120.53826
[231]	validation_0-mae:2117.38613
[232]	validation_0-mae:2117.71268
[233]	validation_0-mae:2117.58517
[234]	validation_0-mae:2118.39669
[235]	validation_0-mae:2117.55522
[236]	validation_0-mae:2117.64557
[237]	validation_0-mae:2117.59538
[238]	validation_0-mae:2117.40301
[239]	validation_0-mae:2117.04494
[240]	validation_0-mae:2116.79411
[241]	validation_0-mae:2116.69700
[242]	validation_0-mae:2117.40351
[243]	validation_0-mae:2117.09952
[244]	validation_0-mae:2116.68213
[245]	validation_0-mae:2116.04817
[246]	validation_0-mae:2114.94460
[247]	validation_0-mae:2115.25594
[248]	validation_0-mae:2115.98339
[249]	validation_0-mae:2114.48727
[250]	validation_0-mae:2115.00964
[251]	validation_0-mae:2114.09230
[252]	validation_0-mae:2113.27818
[253]	validation_0-mae:2113.25902
[254]	validation_0-mae:2112.54871
[255]	validation_0-mae:2112.60975
[256]	validation_0-mae:2112.17586
[257]	validation_0-mae:2111.77608
[258]	validation_0-mae:2111.28522
[259]	validation_0-mae:2111.15941
[260]	validation_0-mae:2111.57483
[261]	validation_0-mae:2111.73340
[262]	validation_0-mae:2109.88144
[263]	validation_0-mae:2108.11704
[264]	validation_0-mae:2108.16705
[265]	validation_0-mae:2107.71203
[266]	validation_0-mae:2107.10507
[267]	validation_0-mae:2107.08470
[268]	validation_0-mae:2106.77689
[269]	validation_0-mae:2106.37562
[270]	validation_0-mae:2105.86025
[271]	validation_0-mae:2105.79780
[272]	validation_0-mae:2106.00728
[273]	validation_0-mae:2106.19528
[274]	validation_0-mae:2106.12923
[275]	validation_0-mae:2106.24162
[276]	validation_0-mae:2105.96899
[277]	validation_0-mae:2106.28820
[278]	validation_0-mae:2106.86863
[279]	validation_0-mae:2107.31021
[280]	validation_0-mae:2107.15769
[281]	validation_0-mae:2107.76220
[282]	validation_0-mae:2107.79310
[283]	validation_0-mae:2108.26421
[284]	validation_0-mae:2108.67130
[285]	validation_0-mae:2108.04841
[286]	validation_0-mae:2108.24478
[287]	validation_0-mae:2107.75030
[288]	validation_0-mae:2106.69291
[289]	validation_0-mae:2107.01439
[290]	validation_0-mae:2107.70098
[291]	validation_0-mae:2107.54099
[292]	validation_0-mae:2106.39905
[293]	validation_0-mae:2105.89129
[294]	validation_0-mae:2105.78774
[295]	validation_0-mae:2105.47506
[296]	validation_0-mae:2105.36571
[297]	validation_0-mae:2105.64592
[298]	validation_0-mae:2106.00692
[299]	validation_0-mae:2106.02706
[300]	validation_0-mae:2105.92733
[301]	validation_0-mae:2106.48594
[302]	validation_0-mae:2106.26792
[303]	validation_0-mae:2106.91360
[304]	validation_0-mae:2106.23589
[305]	validation_0-mae:2106.70473
[306]	validation_0-mae:2106.77217
[307]	validation_0-mae:2106.84868
[308]	validation_0-mae:2106.98680
[309]	validation_0-mae:2107.07947
[310]	validation_0-mae:2107.40875
[311]	validation_0-mae:2107.77269
[312]	validation_0-mae:2108.42626
[313]	validation_0-mae:2109.69418
[314]	validation_0-mae:2109.89759
[315]	validation_0-mae:2110.98430
[316]	validation_0-mae:2110.87300
[317]	validation_0-mae:2110.57524
[318]	validation_0-mae:2110.69451
[319]	validation_0-mae:2109.76379
[320]	validation_0-mae:2108.40432
[321]	validation_0-mae:2108.38249
[322]	validation_0-mae:2107.59639
[323]	validation_0-mae:2106.86626
[324]	validation_0-mae:2106.98058
[325]	validation_0-mae:2106.23244
[326]	validation_0-mae:2105.73544
[327]	validation_0-mae:2105.62512
[328]	validation_0-mae:2105.88844
[329]	validation_0-mae:2104.61663
[330]	validation_0-mae:2105.35750
[331]	validation_0-mae:2105.10267
[332]	validation_0-mae:2104.94246
[333]	validation_0-mae:2104.05458
[334]	validation_0-mae:2104.63060
[335]	validation_0-mae:2103.79666
[336]	validation_0-mae:2102.85466
[337]	validation_0-mae:2103.01279
[338]	validation_0-mae:2101.81326
[339]	validation_0-mae:2101.77000
[340]	validation_0-mae:2101.50591
[341]	validation_0-mae:2101.80085
[342]	validation_0-mae:2102.00559
[343]	validation_0-mae:2100.91869
[344]	validation_0-mae:2098.75079
[345]	validation_0-mae:2098.01368
[346]	validation_0-mae:2098.12452
[347]	validation_0-mae:2097.75235
[348]	validation_0-mae:2098.22604
[349]	validation_0-mae:2098.33208
[350]	validation_0-mae:2098.01634
[351]	validation_0-mae:2098.05152
[352]	validation_0-mae:2098.12180
[353]	validation_0-mae:2098.46092
[354]	validation_0-mae:2097.31497
[355]	validation_0-mae:2097.12535
[356]	validation_0-mae:2096.13514
[357]	validation_0-mae:2096.91672
[358]	validation_0-mae:2096.44311
[359]	validation_0-mae:2096.39473
[360]	validation_0-mae:2096.22999
[361]	validation_0-mae:2095.98044
[362]	validation_0-mae:2096.11508
[363]	validation_0-mae:2095.71672
[364]	validation_0-mae:2094.96629
[365]	validation_0-mae:2095.16333
[366]	validation_0-mae:2094.75900
[367]	validation_0-mae:2094.84304
[368]	validation_0-mae:2094.86596
[369]	validation_0-mae:2094.77012
[370]	validation_0-mae:2094.65735
[371]	validation_0-mae:2094.40860
[372]	validation_0-mae:2094.60966
[373]	validation_0-mae:2093.83718
[374]	validation_0-mae:2093.83689
[375]	validation_0-mae:2093.71817
[376]	validation_0-mae:2093.91291
[377]	validation_0-mae:2093.82031
[378]	validation_0-mae:2094.44183
[379]	validation_0-mae:2094.59775
[380]	validation_0-mae:2094.82298
[381]	validation_0-mae:2095.57036
[382]	validation_0-mae:2095.23868
[383]	validation_0-mae:2095.06269
[384]	validation_0-mae:2095.01814
[385]	validation_0-mae:2093.99594
[386]	validation_0-mae:2093.27206
[387]	validation_0-mae:2093.28392
[388]	validation_0-mae:2093.17191
[389]	validation_0-mae:2092.22279
[390]	validation_0-mae:2092.38348
[391]	validation_0-mae:2092.77648
[392]	validation_0-mae:2092.71068
[393]	validation_0-mae:2092.02115
[394]	validation_0-mae:2092.25234
[395]	validation_0-mae:2092.74608
[396]	validation_0-mae:2092.98641
[397]	validation_0-mae:2093.84196
[398]	validation_0-mae:2094.47568
[399]	validation_0-mae:2094.68785
[400]	validation_0-mae:2094.61959
[401]	validation_0-mae:2094.64324
[402]	validation_0-mae:2093.22550
[403]	validation_0-mae:2094.29044
[404]	validation_0-mae:2094.94032
[405]	validation_0-mae:2095.16948
[406]	validation_0-mae:2094.22498
[407]	validation_0-mae:2094.61190
[408]	validation_0-mae:2094.81432
[409]	validation_0-mae:2094.63448
[410]	validation_0-mae:2094.70760
[411]	validation_0-mae:2094.47414
[412]	validation_0-mae:2094.45935
[413]	validation_0-mae:2094.39687
[414]	validation_0-mae:2094.17983
[415]	validation_0-mae:2094.14162
[416]	validation_0-mae:2094.50583
[417]	validation_0-mae:2094.62394
[418]	validation_0-mae:2094.70506
[419]	validation_0-mae:2095.02969
[420]	validation_0-mae:2095.14043
[421]	validation_0-mae:2095.16233
[422]	validation_0-mae:2095.16362
[423]	validation_0-mae:2094.66100
[424]	validation_0-mae:2094.56742
[425]	validation_0-mae:2094.85630
[426]	validation_0-mae:2095.04886
[427]	validation_0-mae:2095.09501
[428]	validation_0-mae:2095.28942
[429]	validation_0-mae:2095.11133
[430]	validation_0-mae:2094.90628
[431]	validation_0-mae:2094.95124
[432]	validation_0-mae:2094.94387
[433]	validation_0-mae:2095.10910
[434]	validation_0-mae:2095.65614
[435]	validation_0-mae:2095.13613
[436]	validation_0-mae:2095.35772
[437]	validation_0-mae:2095.05284
[438]	validation_0-mae:2095.11405
[439]	validation_0-mae:2095.59361
[440]	validation_0-mae:2095.76776
[441]	validation_0-mae:2095.76530
[442]	validation_0-mae:2095.39391
[443]	validation_0-mae:2095.46582
[444]	validation_0-mae:2095.67748
[445]	validation_0-mae:2096.06369
[446]	validation_0-mae:2096.22766
[447]	validation_0-mae:2096.05488
[448]	validation_0-mae:2096.08277
[449]	validation_0-mae:2096.49523
[450]	validation_0-mae:2095.86728
[451]	validation_0-mae:2095.86745
[452]	validation_0-mae:2096.40605
[453]	validation_0-mae:2096.43646
[454]	validation_0-mae:2095.90195
[455]	validation_0-mae:2095.64305
[456]	validation_0-mae:2096.33155
[457]	validation_0-mae:2096.25678
[458]	validation_0-mae:2095.85184
[459]	validation_0-mae:2096.30778
[460]	validation_0-mae:2096.35318
[461]	validation_0-mae:2096.17745
[462]	validation_0-mae:2096.39882
[463]	validation_0-mae:2096.19316
[464]	validation_0-mae:2095.42258
[465]	validation_0-mae:2094.58377
[466]	validation_0-mae:2094.29683
[467]	validation_0-mae:2093.91774
[468]	validation_0-mae:2093.23239
[469]	validation_0-mae:2092.80064
[470]	validation_0-mae:2092.67687
[471]	validation_0-mae:2092.00494
[472]	validation_0-mae:2091.94863
[473]	validation_0-mae:2091.57827
[474]	validation_0-mae:2091.52188
[475]	validation_0-mae:2091.66510
[476]	validation_0-mae:2090.80050
[477]	validation_0-mae:2091.08285
[478]	validation_0-mae:2091.27559
[479]	validation_0-mae:2091.48341
[480]	validation_0-mae:2090.74988
[481]	validation_0-mae:2090.71933
[482]	validation_0-mae:2090.61972
[483]	validation_0-mae:2090.91810
[484]	validation_0-mae:2090.85150
[485]	validation_0-mae:2090.62764
[486]	validation_0-mae:2090.16045
[487]	validation_0-mae:2089.99567
[488]	validation_0-mae:2090.36649
[489]	validation_0-mae:2090.66510
[490]	validation_0-mae:2090.53161
[491]	validation_0-mae:2090.42614
[492]	validation_0-mae:2090.26848
[493]	validation_0-mae:2089.60362
[494]	validation_0-mae:2090.02742
[495]	validation_0-mae:2089.58233
[496]	validation_0-mae:2089.06124
[497]	validation_0-mae:2088.81598
[498]	validation_0-mae:2088.47249
[499]	validation_0-mae:2088.49642
[500]	validation_0-mae:2088.52065
[501]	validation_0-mae:2088.62715
[502]	validation_0-mae:2088.83294
[503]	validation_0-mae:2088.04489
[504]	validation_0-mae:2088.53611
[505]	validation_0-mae:2088.53193
[506]	validation_0-mae:2088.73598
[507]	validation_0-mae:2089.05661
[508]	validation_0-mae:2088.96464
[509]	validation_0-mae:2089.05231
[510]	validation_0-mae:2089.59470
[511]	validation_0-mae:2089.45683
[512]	validation_0-mae:2089.48301
[513]	validation_0-mae:2089.49100
[514]	validation_0-mae:2089.45305
[515]	validation_0-mae:2089.11369
[516]	validation_0-mae:2089.34913
[517]	validation_0-mae:2089.44744
[518]	validation_0-mae:2089.58147
[519]	validation_0-mae:2090.11861
[520]	validation_0-mae:2090.22677
[521]	validation_0-mae:2090.73720
[522]	validation_0-mae:2090.62871
[523]	validation_0-mae:2090.22501
[524]	validation_0-mae:2090.05063
[525]	validation_0-mae:2090.66105
[526]	validation_0-mae:2090.48376
[527]	validation_0-mae:2090.60021
[528]	validation_0-mae:2090.99619
[529]	validation_0-mae:2090.68377
[530]	validation_0-mae:2090.63299
[531]	validation_0-mae:2090.65901
[532]	validation_0-mae:2090.63666
[533]	validation_0-mae:2090.58933
[534]	validation_0-mae:2090.58730
[535]	validation_0-mae:2091.13934
[536]	validation_0-mae:2091.28739
[537]	validation_0-mae:2090.48618
[538]	validation_0-mae:2091.01725
[539]	validation_0-mae:2090.88246
[540]	validation_0-mae:2089.40531
[541]	validation_0-mae:2088.60724
[542]	validation_0-mae:2088.59610
[543]	validation_0-mae:2088.51509
[544]	validation_0-mae:2088.68625
[545]	validation_0-mae:2088.81829
[546]	validation_0-mae:2088.81491
[547]	validation_0-mae:2088.74501
[548]	validation_0-mae:2088.45287
[549]	validation_0-mae:2087.99525
[550]	validation_0-mae:2088.19393
[551]	validation_0-mae:2088.07901
[552]	validation_0-mae:2087.81310
[553]	validation_0-mae:2088.17287
[554]	validation_0-mae:2087.91287
[555]	validation_0-mae:2087.70952
[556]	validation_0-mae:2087.80959
[557]	validation_0-mae:2087.93632
[558]	validation_0-mae:2087.85898
[559]	validation_0-mae:2087.69256
[560]	validation_0-mae:2087.66499
[561]	validation_0-mae:2087.67951
[562]	validation_0-mae:2087.67136
[563]	validation_0-mae:2087.29052
[564]	validation_0-mae:2087.12187
[565]	validation_0-mae:2087.08153
[566]	validation_0-mae:2086.91250
[567]	validation_0-mae:2086.96684
[568]	validation_0-mae:2086.73606
[569]	validation_0-mae:2086.25942
[570]	validation_0-mae:2085.56992
[571]	validation_0-mae:2085.57516
[572]	validation_0-mae:2085.63564
[573]	validation_0-mae:2085.89726
[574]	validation_0-mae:2085.61836
[575]	validation_0-mae:2085.29992
[576]	validation_0-mae:2085.38537
[577]	validation_0-mae:2085.59475
[578]	validation_0-mae:2085.65294
[579]	validation_0-mae:2086.06888
[580]	validation_0-mae:2086.11613
[581]	validation_0-mae:2085.81244
[582]	validation_0-mae:2085.96433
[583]	validation_0-mae:2085.97424
[584]	validation_0-mae:2085.64581
[585]	validation_0-mae:2085.72378
[586]	validation_0-mae:2085.53282
[587]	validation_0-mae:2085.57291
[588]	validation_0-mae:2085.25040
[589]	validation_0-mae:2085.05197
[590]	validation_0-mae:2084.90987
[591]	validation_0-mae:2085.10749
[592]	validation_0-mae:2085.10336
[593]	validation_0-mae:2084.91157
[594]	validation_0-mae:2084.94188
[595]	validation_0-mae:2085.04145
[596]	validation_0-mae:2084.99708
[597]	validation_0-mae:2085.14090
[598]	validation_0-mae:2085.33100
[599]	validation_0-mae:2085.42461
[600]	validation_0-mae:2085.53583
[601]	validation_0-mae:2085.26527
[602]	validation_0-mae:2085.01611
[603]	validation_0-mae:2084.82124
[604]	validation_0-mae:2084.59472
[605]	validation_0-mae:2084.70780
[606]	validation_0-mae:2084.47263
[607]	validation_0-mae:2084.69617
[608]	validation_0-mae:2084.70718
[609]	validation_0-mae:2084.75367
[610]	validation_0-mae:2084.76368
[611]	validation_0-mae:2084.93077
[612]	validation_0-mae:2084.76857
[613]	validation_0-mae:2084.66761
[614]	validation_0-mae:2084.41809
[615]	validation_0-mae:2084.51385
[616]	validation_0-mae:2084.68298
[617]	validation_0-mae:2084.58423
[618]	validation_0-mae:2084.39501
[619]	validation_0-mae:2084.70023
[620]	validation_0-mae:2084.55209
[621]	validation_0-mae:2084.56247
[622]	validation_0-mae:2084.18606
[623]	validation_0-mae:2083.95867
[624]	validation_0-mae:2083.92388
[625]	validation_0-mae:2084.11521
[626]	validation_0-mae:2083.91010
[627]	validation_0-mae:2083.46856
[628]	validation_0-mae:2083.38403
[629]	validation_0-mae:2083.20051

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[44]	validation_0-mae:3301.21997
[45]	validation_0-mae:3262.82769
[46]	validation_0-mae:3229.39875
[47]	validation_0-mae:3201.54736
[48]	validation_0-mae:3154.34768
[49]	validation_0-mae:3126.60276
[50]	validation_0-mae:3088.05059
[51]	validation_0-mae:3064.77711
[52]	validation_0-mae:3036.01879
[53]	validation_0-mae:3012.08736
[54]	validation_0-mae:2991.73254
[55]	validation_0-mae:2960.66053
[56]	validation_0-mae:2935.64830
[57]	validation_0-mae:2910.88833
[58]	validation_0-mae:2882.43669
[59]	validation_0-mae:2866.34203
[60]	validation_0-mae:2844.51299
[61]	validation_0-mae:2822.78574
[62]	validation_0-mae:2810.05465
[63]	validation_0-mae:2795.33489
[64]	validation_0-mae:2776.67904
[65]	validation_0-mae:2761.28837
[66]	validation_0-mae:2749.63108
[67]	validation_0-mae:2739.89235
[68]	validation_0-mae:2719.09411
[69]	validation_0-mae:2708.92139
[70]	validation_0-mae:2702.48438
[71]	validation_0-mae:2680.88923
[72]	validation_0-mae:2664.30584
[73]	validation_0-mae:2647.57457
[74]	validation_0-mae:2633.78672
[75]	validation_0-mae:2626.01155
[76]	validation_0-mae:2619.23616
[77]	validation_0-mae:2612.39364
[78]	validation_0-mae:2598.45459
[79]	validation_0-mae:2586.62194
[80]	validation_0-mae:2581.95493
[81]	validation_0-mae:2570.70234
[82]	validation_0-mae:2562.20275
[83]	validation_0-mae:2552.12102
[84]	validation_0-mae:2542.42674
[85]	validation_0-mae:2533.83195
[86]	validation_0-mae:2527.86434
[87]	validation_0-mae:2517.46660
[88]	validation_0-mae:2508.04043
[89]	validation_0-mae:2499.51976
[90]	validation_0-mae:2490.90799
[91]	validation_0-mae:2482.04369
[92]	validation_0-mae:2477.11256
[93]	validation_0-mae:2470.58507
[94]	validation_0-mae:2462.77854
[95]	validation_0-mae:2459.39870
[96]	validation_0-mae:2458.36608
[97]	validation_0-mae:2454.15463
[98]	validation_0-mae:2449.67496
[99]	validation_0-mae:2444.71551
[100]	validation_0-mae:2434.94335
[101]	validation_0-mae:2429.60231
[102]	validation_0-mae:2421.63692
[103]	validation_0-mae:2414.89103
[104]	validation_0-mae:2411.29313
[105]	validation_0-mae:2403.82360
[106]	validation_0-mae:2396.51688
[107]	validation_0-mae:2392.39245
[108]	validation_0-mae:2389.79949
[109]	validation_0-mae:2383.90818
[110]	validation_0-mae:2379.17477
[111]	validation_0-mae:2370.81307
[112]	validation_0-mae:2366.13029
[113]	validation_0-mae:2360.34910
[114]	validation_0-mae:2355.07386
[115]	validation_0-mae:2349.15238
[116]	validation_0-mae:2346.05684
[117]	validation_0-mae:2341.71428
[118]	validation_0-mae:2339.81371
[119]	validation_0-mae:2335.41576
[120]	validation_0-mae:2328.00521
[121]	validation_0-mae:2325.35769
[122]	validation_0-mae:2321.31244
[123]	validation_0-mae:2318.91800
[124]	validation_0-mae:2316.22283
[125]	validation_0-mae:2309.41443
[126]	validation_0-mae:2308.45746
[127]	validation_0-mae:2308.37370
[128]	validation_0-mae:2304.59693
[129]	validation_0-mae:2297.98013
[130]	validation_0-mae:2296.39178
[131]	validation_0-mae:2294.22500
[132]	validation_0-mae:2293.39153
[133]	validation_0-mae:2289.66287
[134]	validation_0-mae:2287.33323
[135]	validation_0-mae:2284.14672
[136]	validation_0-mae:2283.20432
[137]	validation_0-mae:2283.00367
[138]	validation_0-mae:2280.38652
[139]	validation_0-mae:2278.14903
[140]	validation_0-mae:2274.58987
[141]	validation_0-mae:2273.07669
[142]	validation_0-mae:2269.83370
[143]	validation_0-mae:2267.94213
[144]	validation_0-mae:2266.16720
[145]	validation_0-mae:2265.76357
[146]	validation_0-mae:2263.27768
[147]	validation_0-mae:2261.95054
[148]	validation_0-mae:2259.90210
[149]	validation_0-mae:2260.32618
[150]	validation_0-mae:2258.09629
[151]	validation_0-mae:2252.32695
[152]	validation_0-mae:2251.57943
[153]	validation_0-mae:2248.74908
[154]	validation_0-mae:2247.04145
[155]	validation_0-mae:2243.11255
[156]	validation_0-mae:2242.10448
[157]	validation_0-mae:2237.96216
[158]	validation_0-mae:2231.31105
[159]	validation_0-mae:2229.23565
[160]	validation_0-mae:2227.25263
[161]	validation_0-mae:2225.51016
[162]	validation_0-mae:2223.08072
[163]	validation_0-mae:2221.53334
[164]	validation_0-mae:2220.78993
[165]	validation_0-mae:2219.45372
[166]	validation_0-mae:2218.75557
[167]	validation_0-mae:2214.98257
[168]	validation_0-mae:2211.59553
[169]	validation_0-mae:2211.17145
[170]	validation_0-mae:2208.26338
[171]	validation_0-mae:2206.92652
[172]	validation_0-mae:2204.97790
[173]	validation_0-mae:2205.04027
[174]	validation_0-mae:2206.06386
[175]	validation_0-mae:2204.26638
[176]	validation_0-mae:2202.79473
[177]	validation_0-mae:2201.18008
[178]	validation_0-mae:2201.41569
[179]	validation_0-mae:2199.84880
[180]	validation_0-mae:2199.12646
[181]	validation_0-mae:2197.15988
[182]	validation_0-mae:2194.35652
[183]	validation_0-mae:2191.72035
[184]	validation_0-mae:2191.87862
[185]	validation_0-mae:2193.45229
[186]	validation_0-mae:2192.83648
[187]	validation_0-mae:2192.81307
[188]	validation_0-mae:2192.34145
[189]	validation_0-mae:2191.69594
[190]	validation_0-mae:2191.93945
[191]	validation_0-mae:2188.92257
[192]	validation_0-mae:2189.20229
[193]	validation_0-mae:2186.20367
[194]	validation_0-mae:2185.65666
[195]	validation_0-mae:2183.34080
[196]	validation_0-mae:2183.47825
[197]	validation_0-mae:2184.05427
[198]	validation_0-mae:2183.47226
[199]	validation_0-mae:2181.07497
[200]	validation_0-mae:2181.83307
[201]	validation_0-mae:2181.69750
[202]	validation_0-mae:2181.32372
[203]	validation_0-mae:2180.22750
[204]	validation_0-mae:2180.46413
[205]	validation_0-mae:2180.97503
[206]	validation_0-mae:2181.42210
[207]	validation_0-mae:2181.64963
[208]	validation_0-mae:2181.34258
[209]	validation_0-mae:2181.22211
[210]	validation_0-mae:2181.31607
[211]	validation_0-mae:2180.83212
[212]	validation_0-mae:2179.97570
[213]	validation_0-mae:2179.46220
[214]	validation_0-mae:2178.68175
[215]	validation_0-mae:2178.95878
[216]	validation_0-mae:2177.73923
[217]	validation_0-mae:2177.07482
[218]	validation_0-mae:2176.98621
[219]	validation_0-mae:2177.29211
[220]	validation_0-mae:2176.58511
[221]	validation_0-mae:2177.25067
[222]	validation_0-mae:2177.14540
[223]	validation_0-mae:2176.23426
[224]	validation_0-mae:2175.94669
[225]	validation_0-mae:2175.68036
[226]	validation_0-mae:2174.14200
[227]	validation_0-mae:2171.97165
[228]	validation_0-mae:2172.35640
[229]	validation_0-mae:2173.03414
[230]	validation_0-mae:2173.15353
[231]	validation_0-mae:2172.61076
[232]	validation_0-mae:2171.61055
[233]	validation_0-mae:2170.91351
[234]	validation_0-mae:2168.39302
[235]	validation_0-mae:2167.73769
[236]	validation_0-mae:2166.78900
[237]	validation_0-mae:2166.68133
[238]	validation_0-mae:2166.40379
[239]	validation_0-mae:2166.97310
[240]	validation_0-mae:2167.51501
[241]	validation_0-mae:2166.64065
[242]	validation_0-mae:2167.00131
[243]	validation_0-mae:2165.53742
[244]	validation_0-mae:2165.84030
[245]	validation_0-mae:2164.49605
[246]	validation_0-mae:2162.60297
[247]	validation_0-mae:2161.81603
[248]	validation_0-mae:2162.25746
[249]	validation_0-mae:2161.21635
[250]	validation_0-mae:2160.49430
[251]	validation_0-mae:2160.89405
[252]	validation_0-mae:2160.06461
[253]	validation_0-mae:2159.91967
[254]	validation_0-mae:2160.23500
[255]	validation_0-mae:2158.98046
[256]	validation_0-mae:2157.70023
[257]	validation_0-mae:2158.50684
[258]	validation_0-mae:2158.76234
[259]	validation_0-mae:2156.56700
[260]	validation_0-mae:2156.19522
[261]	validation_0-mae:2154.32565
[262]	validation_0-mae:2154.93810
[263]	validation_0-mae:2154.04813
[264]	validation_0-mae:2154.02622
[265]	validation_0-mae:2153.77047
[266]	validation_0-mae:2153.05589
[267]	validation_0-mae:2153.43656
[268]	validation_0-mae:2151.62546
[269]	validation_0-mae:2152.17031
[270]	validation_0-mae:2151.91221
[271]	validation_0-mae:2151.01601
[272]	validation_0-mae:2150.70684
[273]	validation_0-mae:2150.05906
[274]	validation_0-mae:2148.03963
[275]	validation_0-mae:2147.13254
[276]	validation_0-mae:2146.84681
[277]	validation_0-mae:2146.85401
[278]	validation_0-mae:2147.48538
[279]	validation_0-mae:2144.59763
[280]	validation_0-mae:2144.73911
[281]	validation_0-mae:2145.02029
[282]	validation_0-mae:2144.65968
[283]	validation_0-mae:2144.05434
[284]	validation_0-mae:2144.18368
[285]	validation_0-mae:2143.52032
[286]	validation_0-mae:2143.13361
[287]	validation_0-mae:2142.68469
[288]	validation_0-mae:2143.03578
[289]	validation_0-mae:2143.33146
[290]	validation_0-mae:2143.31234
[291]	validation_0-mae:2143.21031
[292]	validation_0-mae:2143.26881
[293]	validation_0-mae:2143.63372
[294]	validation_0-mae:2143.63165
[295]	validation_0-mae:2143.30429
[296]	validation_0-mae:2143.19483
[297]	validation_0-mae:2143.34518
[298]	validation_0-mae:2143.56331
[299]	validation_0-mae:2143.95730
[300]	validation_0-mae:2143.05566
[301]	validation_0-mae:2142.01363
[302]	validation_0-mae:2142.49879
[303]	validation_0-mae:2142.06584
[304]	validation_0-mae:2140.85616
[305]	validation_0-mae:2140.58281
[306]	validation_0-mae:2139.62511
[307]	validation_0-mae:2139.47414
[308]	validation_0-mae:2139.15235
[309]	validation_0-mae:2139.05543
[310]	validation_0-mae:2138.61092
[311]	validation_0-mae:2138.30378
[312]	validation_0-mae:2138.55276
[313]	validation_0-mae:2138.67483
[314]	validation_0-mae:2138.25168
[315]	validation_0-mae:2137.19851
[316]	validation_0-mae:2136.31571
[317]	validation_0-mae:2136.39173
[318]	validation_0-mae:2136.15377
[319]	validation_0-mae:2136.42705
[320]	validation_0-mae:2135.99967
[321]	validation_0-mae:2135.73518
[322]	validation_0-mae:2135.14724
[323]	validation_0-mae:2135.07361
[324]	validation_0-mae:2135.38114
[325]	validation_0-mae:2133.89944
[326]	validation_0-mae:2134.00006
[327]	validation_0-mae:2133.52067
[328]	validation_0-mae:2133.42795
[329]	validation_0-mae:2132.78842
[330]	validation_0-mae:2132.92564
[331]	validation_0-mae:2133.64249
[332]	validation_0-mae:2133.30851
[333]	validation_0-mae:2132.02386
[334]	validation_0-mae:2131.36285
[335]	validation_0-mae:2130.77634
[336]	validation_0-mae:2130.69328
[337]	validation_0-mae:2130.72947
[338]	validation_0-mae:2129.80091
[339]	validation_0-mae:2129.18494
[340]	validation_0-mae:2129.24380
[341]	validation_0-mae:2129.46933
[342]	validation_0-mae:2128.99672
[343]	validation_0-mae:2129.54006
[344]	validation_0-mae:2128.26226
[345]	validation_0-mae:2127.85921
[346]	validation_0-mae:2128.08718
[347]	validation_0-mae:2127.70642
[348]	validation_0-mae:2127.89744
[349]	validation_0-mae:2128.01779
[350]	validation_0-mae:2128.08738
[351]	validation_0-mae:2128.44818
[352]	validation_0-mae:2128.61047
[353]	validation_0-mae:2128.49098
[354]	validation_0-mae:2127.89340
[355]	validation_0-mae:2127.74979
[356]	validation_0-mae:2127.04383
[357]	validation_0-mae:2127.21131
[358]	validation_0-mae:2126.86001
[359]	validation_0-mae:2127.07971
[360]	validation_0-mae:2127.05664
[361]	validation_0-mae:2126.89153
[362]	validation_0-mae:2125.90718
[363]	validation_0-mae:2125.66721
[364]	validation_0-mae:2125.11728
[365]	validation_0-mae:2125.14873
[366]	validation_0-mae:2124.95192
[367]	validation_0-mae:2123.61607
[368]	validation_0-mae:2123.90392
[369]	validation_0-mae:2123.88530
[370]	validation_0-mae:2123.53077
[371]	validation_0-mae:2123.76244
[372]	validation_0-mae:2123.98074
[373]	validation_0-mae:2124.44599
[374]	validation_0-mae:2124.58016
[375]	validation_0-mae:2123.52924
[376]	validation_0-mae:2123.82977
[377]	validation_0-mae:2123.93124
[378]	validation_0-mae:2123.34883
[379]	validation_0-mae:2122.73786
[380]	validation_0-mae:2123.12868
[381]	validation_0-mae:2123.23156
[382]	validation_0-mae:2123.19184
[383]	validation_0-mae:2122.98362
[384]	validation_0-mae:2123.01652
[385]	validation_0-mae:2122.85118
[386]	validation_0-mae:2122.88455
[387]	validation_0-mae:2122.01027
[388]	validation_0-mae:2121.37020
[389]	validation_0-mae:2121.04546
[390]	validation_0-mae:2120.93087
[391]	validation_0-mae:2120.99780
[392]	validation_0-mae:2120.29697
[393]	validation_0-mae:2120.29528
[394]	validation_0-mae:2120.14591
[395]	validation_0-mae:2120.41512
[396]	validation_0-mae:2119.90038
[397]	validation_0-mae:2120.05576
[398]	validation_0-mae:2120.08369
[399]	validation_0-mae:2119.37556
[400]	validation_0-mae:2119.57186
[401]	validation_0-mae:2119.02574
[402]	validation_0-mae:2119.12988
[403]	validation_0-mae:2119.44384
[404]	validation_0-mae:2119.03445
[405]	validation_0-mae:2118.88079
[406]	validation_0-mae:2119.10051
[407]	validation_0-mae:2119.95840
[408]	validation_0-mae:2119.94823
[409]	validation_0-mae:2119.93345
[410]	validation_0-mae:2119.42195
[411]	validation_0-mae:2119.26833
[412]	validation_0-mae:2118.60277
[413]	validation_0-mae:2118.72796
[414]	validation_0-mae:2118.64144
[415]	validation_0-mae:2118.14099
[416]	validation_0-mae:2118.07962
[417]	validation_0-mae:2117.44849
[418]	validation_0-mae:2117.42082
[419]	validation_0-mae:2117.35460
[420]	validation_0-mae:2117.11917
[421]	validation_0-mae:2116.82477
[422]	validation_0-mae:2116.64564
[423]	validation_0-mae:2116.77277
[424]	validation_0-mae:2116.64907
[425]	validation_0-mae:2116.27050
[426]	validation_0-mae:2115.85715
[427]	validation_0-mae:2115.61195
[428]	validation_0-mae:2115.77271
[429]	validation_0-mae:2116.31562
[430]	validation_0-mae:2115.78733
[431]	validation_0-mae:2115.45876
[432]	validation_0-mae:2115.08681
[433]	validation_0-mae:2115.17606
[434]	validation_0-mae:2113.56637
[435]	validation_0-mae:2113.54611
[436]	validation_0-mae:2112.62566
[437]	validation_0-mae:2112.82407
[438]	validation_0-mae:2112.54628
[439]	validation_0-mae:2112.54936
[440]	validation_0-mae:2111.55003
[441]	validation_0-mae:2111.37077
[442]	validation_0-mae:2110.21760
[443]	validation_0-mae:2110.27821
[444]	validation_0-mae:2110.48518
[445]	validation_0-mae:2110.53431
[446]	validation_0-mae:2110.42632
[447]	validation_0-mae:2110.29849
[448]	validation_0-mae:2109.91043
[449]	validation_0-mae:2109.40749
[450]	validation_0-mae:2108.91312
[451]	validation_0-mae:2108.54503
[452]	validation_0-mae:2108.54245
[453]	validation_0-mae:2108.52562
[454]	validation_0-mae:2108.73245
[455]	validation_0-mae:2108.25778
[456]	validation_0-mae:2108.33560
[457]	validation_0-mae:2107.64373
[458]	validation_0-mae:2107.23150
[459]	validation_0-mae:2107.20233
[460]	validation_0-mae:2107.23393
[461]	validation_0-mae:2106.99214
[462]	validation_0-mae:2107.03123
[463]	validation_0-mae:2105.98137
[464]	validation_0-mae:2105.76933
[465]	validation_0-mae:2105.51029
[466]	validation_0-mae:2105.40851
[467]	validation_0-mae:2105.44503
[468]	validation_0-mae:2106.05224
[469]	validation_0-mae:2106.24284
[470]	validation_0-mae:2106.24989
[471]	validation_0-mae:2105.89255
[472]	validation_0-mae:2105.58407
[473]	validation_0-mae:2104.88876
[474]	validation_0-mae:2104.99065
[475]	validation_0-mae:2104.50610
[476]	validation_0-mae:2104.60218
[477]	validation_0-mae:2104.01374
[478]	validation_0-mae:2103.54862
[479]	validation_0-mae:2103.51322
[480]	validation_0-mae:2103.38323
[481]	validation_0-mae:2103.33053
[482]	validation_0-mae:2103.82702
[483]	validation_0-mae:2103.70424
[484]	validation_0-mae:2103.47675
[485]	validation_0-mae:2103.52663
[486]	validation_0-mae:2103.52454
[487]	validation_0-mae:2103.71586
[488]	validation_0-mae:2104.33243
[489]	validation_0-mae:2104.40600
[490]	validation_0-mae:2103.82652
[491]	validation_0-mae:2104.13258
[492]	validation_0-mae:2102.47746
[493]	validation_0-mae:2102.31809
[494]	validation_0-mae:2102.37613
[495]	validation_0-mae:2101.52563
[496]	validation_0-mae:2101.55905
[497]	validation_0-mae:2101.86168
[498]	validation_0-mae:2101.49501
[499]	validation_0-mae:2101.53348
[500]	validation_0-mae:2101.70534
[501]	validation_0-mae:2101.70590
[502]	validation_0-mae:2101.28337
[503]	validation_0-mae:2101.24370
[504]	validation_0-mae:2100.96382
[505]	validation_0-mae:2100.79190
[506]	validation_0-mae:2100.61728
[507]	validation_0-mae:2100.64252
[508]	validation_0-mae:2100.40068
[509]	validation_0-mae:2100.48449
[510]	validation_0-mae:2100.44834
[511]	validation_0-mae:2100.08152
[512]	validation_0-mae:2100.05235
[513]	validation_0-mae:2099.62943
[514]	validation_0-mae:2099.64022
[515]	validation_0-mae:2100.15931
[516]	validation_0-mae:2100.13671
[517]	validation_0-mae:2099.94066
[518]	validation_0-mae:2099.69072
[519]	validation_0-mae:2099.39678
[520]	validation_0-mae:2098.29219
[521]	validation_0-mae:2097.70091
[522]	validation_0-mae:2095.73877
[523]	validation_0-mae:2095.50486
[524]	validation_0-mae:2095.64064
[525]	validation_0-mae:2095.58432
[526]	validation_0-mae:2095.99214
[527]	validation_0-mae:2096.36840
[528]	validation_0-mae:2096.67409
[529]	validation_0-mae:2094.98956
[530]	validation_0-mae:2094.62579
[531]	validation_0-mae:2094.75195
[532]	validation_0-mae:2094.96725
[533]	validation_0-mae:2095.47891
[534]	validation_0-mae:2095.43108
[535]	validation_0-mae:2095.78423
[536]	validation_0-mae:2095.47701
[537]	validation_0-mae:2095.92985
[538]	validation_0-mae:2096.39458
[539]	validation_0-mae:2096.84714
[540]	validation_0-mae:2096.46314
[541]	validation_0-mae:2095.24306
[542]	validation_0-mae:2095.60504
[543]	validation_0-mae:2095.76161
[544]	validation_0-mae:2096.26340
[545]	validation_0-mae:2096.39512
[546]	validation_0-mae:2095.38133
[547]	validation_0-mae:2095.46606
[548]	validation_0-mae:2095.38921
[549]	validation_0-mae:2095.10209
[550]	validation_0-mae:2094.98827
[551]	validation_0-mae:2095.12584
[552]	validation_0-mae:2095.28718
[553]	validation_0-mae:2095.97140
[554]	validation_0-mae:2095.82818
[555]	validation_0-mae:2095.52556
[556]	validation_0-mae:2095.11607
[557]	validation_0-mae:2095.29101
[558]	validation_0-mae:2095.79405
[559]	validation_0-mae:2095.80463
[560]	validation_0-mae:2096.02200
[561]	validation_0-mae:2095.96491
[562]	validation_0-mae:2096.10114
[563]	validation_0-mae:2096.27257
[564]	validation_0-mae:2097.01472
[565]	validation_0-mae:2096.97613
[566]	validation_0-mae:2096.84391
[567]	validation_0-mae:2096.90255
[568]	validation_0-mae:2097.20883
[569]	validation_0-mae:2095.66539
[570]	validation_0-mae:2095.78969
[571]	validation_0-mae:2095.33882
[572]	validation_0-mae:2095.19654
[573]	validation_0-mae:2095.44187
[574]	validation_0-mae:2095.49135
[575]	validation_0-mae:2095.07654
[576]	validation_0-mae:2094.87316
[577]	validation_0-mae:2094.55753
[578]	validation_0-mae:2094.46235
[579]	validation_0-mae:2093.73141
[580]	validation_0-mae:2093.67710
[581]	validation_0-mae:2093.52759
[582]	validation_0-mae:2093.30130
[583]	validation_0-mae:2093.37610
[584]	validation_0-mae:2092.98936
[585]	validation_0-mae:2092.99165
[586]	validation_0-mae:2092.51807
[587]	validation_0-mae:2092.29193
[588]	validation_0-mae:2091.98731
[589]	validation_0-mae:2091.53807
[590]	validation_0-mae:2091.34474
[591]	validation_0-mae:2091.17971
[592]	validation_0-mae:2091.08489
[593]	validation_0-mae:2090.96707
[594]	validation_0-mae:2090.72959
[595]	validation_0-mae:2090.93634
[596]	validation_0-mae:2090.51759
[597]	validation_0-mae:2090.24731
[598]	validation_0-mae:2089.92847
[599]	validation_0-mae:2090.28916
[600]	validation_0-mae:2090.04913
[601]	validation_0-mae:2090.37485
[602]	validation_0-mae:2090.40847
[603]	validation_0-mae:2090.15861
[604]	validation_0-mae:2090.22044
[605]	validation_0-mae:2090.67436
[606]	validation_0-mae:2090.66327
[607]	validation_0-mae:2090.73993
[608]	validation_0-mae:2090.81549
[609]	validation_0-mae:2090.95031
[610]	validation_0-mae:2091.17814
[611]	validation_0-mae:2091.10594
[612]	validation_0-mae:2090.88755
[613]	validation_0-mae:2090.70188
[614]	validation_0-mae:2090.67594
[615]	validation_0-mae:2090.40246
[616]	validation_0-mae:2090.11118
[617]	validation_0-mae:2090.06549
[618]	validation_0-mae:2090.05909
[619]	validation_0-mae:2089.97591
[620]	validation_0-mae:2090.06411
[621]	validation_0-mae:2090.13149
[622]	validation_0-mae:2090.43386
[623]	validation_0-mae:2090.82268
[624]	validation_0-mae:2090.96587
[625]	validation_0-mae:2090.80876
[626]	validation_0-mae:2090.85788
[627]	validation_0-mae:2090.55592
[628]	validation_0-mae:2090.69037
[629]	validation_0-mae:2090.66175
[630]	validation_0-mae:2090.70311
[631]	validation_0-mae:2090.61661
[632]	validation_0-mae:2090.55663

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[1]	validation_0-mae:11709.51383
[2]	validation_0-mae:11033.06644
[3]	validation_0-mae:10412.01204
[4]	validation_0-mae:9869.08571
[5]	validation_0-mae:9373.39340
[6]	validation_0-mae:8946.00113
[7]	validation_0-mae:8555.39747
[8]	validation_0-mae:8173.46750
[9]	validation_0-mae:7836.02303
[10]	validation_0-mae:7503.76887
[11]	validation_0-mae:7229.82980
[12]	validation_0-mae:6955.92978
[13]	validation_0-mae:6713.10099
[14]	validation_0-mae:6455.65855
[15]	validation_0-mae:6238.69509
[16]	validation_0-mae:6044.20401
[17]	validation_0-mae:5824.73469
[18]	validation_0-mae:5641.75178
[19]	validation_0-mae:5445.72488
[20]	validation_0-mae:5283.45514
[21]	validation_0-mae:5119.24265
[22]	validation_0-mae:4981.65313
[23]	validation_0-mae:4850.00875
[24]	validation_0-mae:4718.82192
[25]	validation_0-mae:4596.55927
[26]	validation_0-mae:4480.59326
[27]	validation_0-mae:4367.43985
[28]	validation_0-mae:4259.98968
[29]	validation_0-mae:4175.06446
[30]	validation_0-mae:4083.81254
[31]	validation_0-mae:3978.07750
[32]	validation_0-mae:3908.76762
[33]	validation_0-mae:3823.48870
[34]	validation_0-mae:3745.46781
[35]	validation_0-mae:3676.50328
[36]	validation_0-mae:3622.00855
[37]	validation_0-mae:3567.40936
[38]	validation_0-mae:3503.33446
[39]	validation_0-mae:3446.54852
[40]	validation_0-mae:3399.36261
[41]	validation_0-mae:3353.08059
[42]	validation_0-mae:3294.88260
[43]	validation_0-mae:3256.97493
[44]	validation_0-mae:3215.48740
[45]	validation_0-mae:3181.60669
[46]	validation_0-mae:3148.43944
[47]	validation_0-mae:3122.36525
[48]	validation_0-mae:3077.51059
[49]	validation_0-mae:3041.01295
[50]	validation_0-mae:3014.28694
[51]	validation_0-mae:2990.97970
[52]	validation_0-mae:2961.13623
[53]	validation_0-mae:2938.39180
[54]	validation_0-mae:2910.49489
[55]	validation_0-mae:2890.66382
[56]	validation_0-mae:2877.30459
[57]	validation_0-mae:2855.05172
[58]	validation_0-mae:2833.06000
[59]	validation_0-mae:2822.21252
[60]	validation_0-mae:2809.89532
[61]	validation_0-mae:2794.77634
[62]	validation_0-mae:2771.40644
[63]	validation_0-mae:2762.88019
[64]	validation_0-mae:2750.78090
[65]	validation_0-mae:2729.49194
[66]	validation_0-mae:2712.36266
[67]	validation_0-mae:2698.21768
[68]	validation_0-mae:2684.44176
[69]	validation_0-mae:2671.69762
[70]	validation_0-mae:2659.36637
[71]	validation_0-mae:2650.54745
[72]	validation_0-mae:2643.31180
[73]	validation_0-mae:2628.73902
[74]	validation_0-mae:2618.07296
[75]	validation_0-mae:2606.13471
[76]	validation_0-mae:2599.61455
[77]	validation_0-mae:2590.48524
[78]	validation_0-mae:2583.10388
[79]	validation_0-mae:2568.78357
[80]	validation_0-mae:2563.19684
[81]	validation_0-mae:2554.86342
[82]	validation_0-mae:2546.91864
[83]	validation_0-mae:2539.22313
[84]	validation_0-mae:2534.28689
[85]	validation_0-mae:2527.72315
[86]	validation_0-mae:2516.95351
[87]	validation_0-mae:2502.55782
[88]	validation_0-mae:2494.69613
[89]	validation_0-mae:2487.44093
[90]	validation_0-mae:2481.06865
[91]	validation_0-mae:2477.78672
[92]	validation_0-mae:2471.51992
[93]	validation_0-mae:2463.90033
[94]	validation_0-mae:2460.34124
[95]	validation_0-mae:2452.91432
[96]	validation_0-mae:2446.23381
[97]	validation_0-mae:2441.12241
[98]	validation_0-mae:2435.22326
[99]	validation_0-mae:2429.54531
[100]	validation_0-mae:2423.28534
[101]	validation_0-mae:2420.33303
[102]	validation_0-mae:2414.25466
[103]	validation_0-mae:2411.16803
[104]	validation_0-mae:2406.15118
[105]	validation_0-mae:2402.87643
[106]	validation_0-mae:2396.03731
[107]	validation_0-mae:2387.21085
[108]	validation_0-mae:2383.62067
[109]	validation_0-mae:2376.26317
[110]	validation_0-mae:2373.72763
[111]	validation_0-mae:2367.99078
[112]	validation_0-mae:2363.47072
[113]	validation_0-mae:2362.22223
[114]	validation_0-mae:2360.88469
[115]	validation_0-mae:2354.50908
[116]	validation_0-mae:2348.28060
[117]	validation_0-mae:2343.74105
[118]	validation_0-mae:2336.02350
[119]	validation_0-mae:2329.55459
[120]	validation_0-mae:2327.08592
[121]	validation_0-mae:2325.66465
[122]	validation_0-mae:2326.08558
[123]	validation_0-mae:2323.19180
[124]	validation_0-mae:2320.19940
[125]	validation_0-mae:2318.02867
[126]	validation_0-mae:2317.10326
[127]	validation_0-mae:2315.14168
[128]	validation_0-mae:2314.37921
[129]	validation_0-mae:2309.06150
[130]	validation_0-mae:2308.38702
[131]	validation_0-mae:2307.33902
[132]	validation_0-mae:2306.13208
[133]	validation_0-mae:2302.25834
[134]	validation_0-mae:2301.18916
[135]	validation_0-mae:2296.19549
[136]	validation_0-mae:2290.43589
[137]	validation_0-mae:2290.20120
[138]	validation_0-mae:2288.99353
[139]	validation_0-mae:2285.30223
[140]	validation_0-mae:2286.09737
[141]	validation_0-mae:2286.93255
[142]	validation_0-mae:2285.04998
[143]	validation_0-mae:2282.65384
[144]	validation_0-mae:2281.04473
[145]	validation_0-mae:2279.36749
[146]	validation_0-mae:2278.57015
[147]	validation_0-mae:2280.19073
[148]	validation_0-mae:2280.57855
[149]	validation_0-mae:2278.61692
[150]	validation_0-mae:2276.65768
[151]	validation_0-mae:2276.01076
[152]	validation_0-mae:2275.64615
[153]	validation_0-mae:2274.73519
[154]	validation_0-mae:2271.02136
[155]	validation_0-mae:2270.37822
[156]	validation_0-mae:2270.42524
[157]	validation_0-mae:2270.27114
[158]	validation_0-mae:2266.95118
[159]	validation_0-mae:2265.84408
[160]	validation_0-mae:2264.91905
[161]	validation_0-mae:2261.98004
[162]	validation_0-mae:2258.14444
[0]	validation_0-mae:12546.67572
[1]	validation_0-mae:11907.49416
[2]	validation_0-mae:11356.03568
[3]	validation_0-mae:10889.11246
[4]	validation_0-mae:10483.79194
[5]	validation_0-mae:10145.78894
[6]	validation_0-mae:9851.09391
[7]	validation_0-mae:9596.25086
[8]	validation_0-mae:9370.04115
[9]	validation_0-mae:9178.45662
[0]	validation_0-mae:12531.28988
[1]	validation_0-mae:11851.25076
[2]	validation_0-mae:11237.36028
[3]	validation_0-mae:10660.87750
[4]	validation_0-mae:10153.18954

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[5]	validation_0-mae:9700.52080
[6]	validation_0-mae:9269.89894
[7]	validation_0-mae:8886.52138
[8]	validation_0-mae:8537.38343
[9]	validation_0-mae:8181.45089
[0]	validation_0-mae:12515.16119
[1]	validation_0-mae:11830.35393
[2]	validation_0-mae:11199.90106
[3]	validation_0-mae:10612.64312
[4]	validation_0-mae:10097.26990
[5]	validation_0-mae:9634.57615
[6]	validation_0-mae:9206.97278
[7]	validation_0-mae:8824.64842
[8]	validation_0-mae:8455.80961
[9]	validation_0-mae:8111.18539
[10]	validation_0-mae:7816.75363

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[0]	validation_0-mae:12463.63375
[1]	validation_0-mae:11733.01252
[2]	validation_0-mae:11067.00711
[3]	validation_0-mae:10444.62730
[4]	validation_0-mae:9910.77908
[5]	validation_0-mae:9403.24144
[6]	validation_0-mae:8973.92724
[7]	validation_0-mae:8572.85350
[8]	validation_0-mae:8241.22047
[9]	validation_0-mae:7887.36333
[10]	validation_0-mae:7550.95034
[11]	validation_0-mae:7238.80936
[12]	validation_0-mae:6973.75889
[13]	validation_0-mae:6724.23161
[14]	validation_0-mae:6485.72171
[15]	validation_0-mae:6258.96596
[16]	validation_0-mae:6038.49373
[17]	validation_0-mae:5851.16346
[18]	validation_0-mae:5647.85932
[19]	validation_0-mae:5462.78647
[20]	validation_0-mae:5308.81968
[21]	validation_0-mae:5174.69797
[22]	validation_0-mae:5030.86476
[23]	validation_0-mae:4890.53600
[24]	validation_0-mae:4765.43038
[25]	validation_0-mae:4649.65438
[26]	validation_0-mae:4546.50048
[27]	validation_0-mae:4434.53767
[28]	validation_0-mae:4321.88713
[29]	validation_0-mae:4226.06044
[30]	validation_0-mae:4129.71383
[31]	validation_0-mae:4036.80137
[32]	validation_0-mae:3964.57686
[33]	validation_0-mae:3872.86182
[34]	validation_0-mae:3791.52752
[35]	validation_0-mae:3732.27566
[36]	validation_0-mae:3649.75205
[37]	validation_0-mae:3585.81244
[38]	validation_0-mae:3532.48496
[39]	validation_0-mae:3480.11293
[40]	validation_0-mae:3428.18552
[41]	validation_0-mae:3379.46003
[42]	validation_0-mae:3342.94898
[43]	validation_0-mae:3300.47950
[44]	validation_0-mae:3261.93317
[45]	validation_0-mae:3232.46585
[46]	validation_0-mae:3204.45665
[47]	validation_0-mae:3157.57412
[48]	validation_0-mae:3128.36139
[49]	validation_0-mae:3103.12609
[50]	validation_0-mae:3069.32477
[51]	validation_0-mae:3047.19891
[52]	validation_0-mae:3015.94734
[53]	validation_0-mae:2994.89355
[54]	validation_0-mae:2972.76675
[55]	validation_0-mae:2938.31867
[56]	validation_0-mae:2920.80645
[57]	validation_0-mae:2906.37799
[58]	validation_0-mae:2889.72456
[59]	validation_0-mae:2871.90542
[60]	validation_0-mae:2862.71099
[61]	validation_0-mae:2850.24336
[62]	validation_0-mae:2821.02749
[63]	validation_0-mae:2808.16568
[64]	validation_0-mae:2797.95661
[65]	validation_0-mae:2787.00207
[66]	validation_0-mae:2756.19330
[67]	validation_0-mae:2745.36334
[68]	validation_0-mae:2725.87474
[69]	validation_0-mae:2709.05471
[70]	validation_0-mae:2699.59433
[71]	validation_0-mae:2689.69309
[72]	validation_0-mae:2674.19929
[73]	validation_0-mae:2664.50329
[74]	validation_0-mae:2656.08398
[75]	validation_0-mae:2643.75437
[76]	validation_0-mae:2629.27569
[77]	validation_0-mae:2620.21861
[78]	validation_0-mae:2607.61558
[79]	validation_0-mae:2600.47737
[80]	validation_0-mae:2592.25634
[81]	validation_0-mae:2576.47313
[82]	validation_0-mae:2566.27522
[83]	validation_0-mae:2562.96165
[84]	validation_0-mae:2555.03291
[85]	validation_0-mae:2543.54566
[86]	validation_0-mae:2538.65048
[87]	validation_0-mae:2531.59245
[88]	validation_0-mae:2515.53756
[89]	validation_0-mae:2507.06368
[90]	validation_0-mae:2495.57865
[91]	validation_0-mae:2489.61711
[92]	validation_0-mae:2479.98059
[93]	validation_0-mae:2471.85291
[94]	validation_0-mae:2467.66939
[95]	validation_0-mae:2460.78494
[96]	validation_0-mae:2457.38023
[97]	validation_0-mae:2450.90640
[98]	validation_0-mae:2443.85931
[99]	validation_0-mae:2440.30862
[100]	validation_0-mae:2435.50307
[101]	validation_0-mae:2430.40990
[102]	validation_0-mae:2425.75182
[103]	validation_0-mae:2419.30377
[104]	validation_0-mae:2413.88163
[105]	validation_0-mae:2408.52768
[106]	validation_0-mae:2403.24669
[107]	validation_0-mae:2399.13216
[108]	validation_0-mae:2387.43435
[109]	validation_0-mae:2381.39626
[110]	validation_0-mae:2375.00964
[111]	validation_0-mae:2374.04665
[112]	validation_0-mae:2370.66260
[113]	validation_0-mae:2369.37447
[114]	validation_0-mae:2367.80573
[115]	validation_0-mae:2364.81006
[116]	validation_0-mae:2358.87103
[117]	validation_0-mae:2355.63731
[118]	validation_0-mae:2350.60303
[119]	validation_0-mae:2348.49889
[120]	validation_0-mae:2345.36366
[121]	validation_0-mae:2340.60651
[122]	validation_0-mae:2334.99972
[123]	validation_0-mae:2331.70759
[124]	validation_0-mae:2327.10937
[125]	validation_0-mae:2324.65687
[126]	validation_0-mae:2320.85634
[127]	validation_0-mae:2318.77340
[128]	validation_0-mae:2313.43064
[129]	validation_0-mae:2311.14290
[130]	validation_0-mae:2307.68819
[131]	validation_0-mae:2304.92717
[132]	validation_0-mae:2302.61824
[133]	validation_0-mae:2298.27960
[134]	validation_0-mae:2298.15806
[135]	validation_0-mae:2297.33997
[136]	validation_0-mae:2295.29853
[137]	validation_0-mae:2292.17677
[138]	validation_0-mae:2289.42114
[139]	validation_0-mae:2287.79547
[140]	validation_0-mae:2286.25903
[141]	validation_0-mae:2285.75561
[142]	validation_0-mae:2285.64431
[143]	validation_0-mae:2285.48137
[144]	validation_0-mae:2284.46549
[145]	validation_0-mae:2283.63614
[146]	validation_0-mae:2283.07558
[147]	validation_0-mae:2279.48856
[148]	validation_0-mae:2276.26528
[149]	validation_0-mae:2271.77841
[150]	validation_0-mae:2271.68051
[151]	validation_0-mae:2269.59713
[152]	validation_0-mae:2270.06953
[153]	validation_0-mae:2269.22199
[154]	validation_0-mae:2267.95401
[155]	validation_0-mae:2264.93321
[156]	validation_0-mae:2264.84902
[157]	validation_0-mae:2265.05777
[158]	validation_0-mae:2265.19318
[159]	validation_0-mae:2264.31489
[160]	validation_0-mae:2262.76911
[161]	validation_0-mae:2261.50965
[162]	validation_0-mae:2261.68475
[0]	validation_0-mae:12452.44717
[1]	validation_0-mae:11733.80203
[2]	validation_0-mae:11084.80260
[3]	validation_0-mae:10513.85697
[4]	validation_0-mae:10013.80992
[5]	validation_0-mae:9563.33306
[6]	validation_0-mae:9176.00526
[7]	validation_0-mae:8835.00951
[8]	validation_0-mae:8515.83601
[9]	validation_0-mae:8229.73464

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[0]	validation_0-mae:12368.85577
[1]	validation_0-mae:11582.34891
[2]	validation_0-mae:10858.64031
[3]	validation_0-mae:10194.97434
[4]	validation_0-mae:9629.33997
[5]	validation_0-mae:9081.20823
[6]	validation_0-mae:8634.78512
[7]	validation_0-mae:8218.71236
[8]	validation_0-mae:7855.15042
[9]	validation_0-mae:7487.68474
[10]	validation_0-mae:7180.00116
[11]	validation_0-mae:6905.01237
[12]	validation_0-mae:6618.86254
[13]	validation_0-mae:6341.71074
[14]	validation_0-mae:6093.04896
[15]	validation_0-mae:5877.35296
[16]	validation_0-mae:5636.04014
[17]	validation_0-mae:5466.95584
[18]	validation_0-mae:5277.38914
[19]	validation_0-mae:5071.43596
[20]	validation_0-mae:4928.76937
[21]	validation_0-mae:4769.21328
[22]	validation_0-mae:4631.98327
[23]	validation_0-mae:4488.59111
[24]	validation_0-mae:4366.39824
[25]	validation_0-mae:4250.13437
[26]	validation_0-mae:4141.44365
[27]	validation_0-mae:4062.97898
[28]	validation_0-mae:3964.43163
[29]	validation_0-mae:3869.60472
[30]	validation_0-mae:3791.02374
[31]	validation_0-mae:3723.43187
[32]	validation_0-mae:3645.79437
[33]	validation_0-mae:3557.60900
[34]	validation_0-mae:3497.10479
[35]	validation_0-mae:3436.49077
[36]	validation_0-mae:3383.25303
[37]	validation_0-mae:3332.63705
[38]	validation_0-mae:3283.95679
[39]	validation_0-mae:3244.04342
[40]	validation_0-mae:3204.98354
[41]	validation_0-mae:3179.12985
[42]	validation_0-mae:3139.27695
[43]	validation_0-mae:3090.89846
[44]	validation_0-mae:3055.21322
[45]	validation_0-mae:3012.47024
[46]	validation_0-mae:2971.47328
[47]	validation_0-mae:2946.41690
[48]	validation_0-mae:2924.69670
[49]	validation_0-mae:2903.74714
[50]	validation_0-mae:2880.50977
[51]	validation_0-mae:2849.28410
[52]	validation_0-mae:2827.86879
[53]	validation_0-mae:2797.68263
[54]	validation_0-mae:2780.56075
[55]	validation_0-mae:2763.95488
[56]	validation_0-mae:2740.41374
[57]	validation_0-mae:2717.43124
[58]	validation_0-mae:2704.77153
[59]	validation_0-mae:2687.86293
[60]	validation_0-mae:2678.70307
[61]	validation_0-mae:2668.06794
[62]	validation_0-mae:2658.60664
[63]	validation_0-mae:2646.91868
[64]	validation_0-mae:2636.80346
[65]	validation_0-mae:2621.56240
[66]	validation_0-mae:2606.31195
[67]	validation_0-mae:2599.69588
[68]	validation_0-mae:2592.44515
[69]	validation_0-mae:2575.83599
[70]	validation_0-mae:2560.07375
[71]	validation_0-mae:2552.55926
[72]	validation_0-mae:2549.37104
[73]	validation_0-mae:2540.54104
[74]	validation_0-mae:2524.47847
[75]	validation_0-mae:2509.17598
[76]	validation_0-mae:2502.98855
[77]	validation_0-mae:2497.20881
[78]	validation_0-mae:2488.86713
[79]	validation_0-mae:2482.12073
[80]	validation_0-mae:2474.16616
[81]	validation_0-mae:2464.91887
[82]	validation_0-mae:2460.97563
[83]	validation_0-mae:2453.32131
[84]	validation_0-mae:2449.49294
[85]	validation_0-mae:2441.08759
[86]	validation_0-mae:2433.38396
[87]	validation_0-mae:2427.67283
[88]	validation_0-mae:2418.74422
[89]	validation_0-mae:2411.63574
[90]	validation_0-mae:2404.56429
[91]	validation_0-mae:2397.84353
[92]	validation_0-mae:2391.43184
[93]	validation_0-mae:2384.02866
[94]	validation_0-mae:2380.43963
[95]	validation_0-mae:2377.17625
[96]	validation_0-mae:2372.43895
[97]	validation_0-mae:2366.99090
[98]	validation_0-mae:2359.52126
[99]	validation_0-mae:2352.64420
[100]	validation_0-mae:2346.20216
[101]	validation_0-mae:2344.82673
[102]	validation_0-mae:2339.87237
[103]	validation_0-mae:2339.32117
[104]	validation_0-mae:2335.45924
[105]	validation_0-mae:2332.39890
[106]	validation_0-mae:2328.62087
[107]	validation_0-mae:2320.01624
[108]	validation_0-mae:2317.24025
[109]	validation_0-mae:2314.80502
[110]	validation_0-mae:2309.83112
[111]	validation_0-mae:2305.00320
[112]	validation_0-mae:2305.48310
[113]	validation_0-mae:2300.80308
[114]	validation_0-mae:2296.52004
[115]	validation_0-mae:2292.96539
[116]	validation_0-mae:2289.99253
[117]	validation_0-mae:2287.66407
[118]	validation_0-mae:2284.95424
[119]	validation_0-mae:2284.44082
[120]	validation_0-mae:2283.30738
[121]	validation_0-mae:2280.32583
[122]	validation_0-mae:2280.22091
[123]	validation_0-mae:2275.97816
[124]	validation_0-mae:2272.88755
[125]	validation_0-mae:2270.17418
[126]	validation_0-mae:2267.24231
[127]	validation_0-mae:2262.13092
[128]	validation_0-mae:2258.48296
[129]	validation_0-mae:2257.13174
[130]	validation_0-mae:2257.65983
[131]	validation_0-mae:2256.21453
[132]	validation_0-mae:2254.54790
[133]	validation_0-mae:2253.59375
[134]	validation_0-mae:2249.95983
[135]	validation_0-mae:2249.24474
[136]	validation_0-mae:2246.98495
[137]	validation_0-mae:2245.87403
[138]	validation_0-mae:2244.95791
[139]	validation_0-mae:2242.82618
[140]	validation_0-mae:2239.55759
[141]	validation_0-mae:2237.87920
[142]	validation_0-mae:2238.01680
[143]	validation_0-mae:2235.74898
[144]	validation_0-mae:2234.89043
[145]	validation_0-mae:2230.61519
[146]	validation_0-mae:2229.28566
[147]	validation_0-mae:2228.14483
[148]	validation_0-mae:2225.11946
[149]	validation_0-mae:2224.92150
[150]	validation_0-mae:2220.86646
[151]	validation_0-mae:2219.81882
[152]	validation_0-mae:2219.39796
[153]	validation_0-mae:2219.06726
[154]	validation_0-mae:2215.93959
[155]	validation_0-mae:2214.07229
[156]	validation_0-mae:2214.68500
[157]	validation_0-mae:2213.06657
[158]	validation_0-mae:2210.88582
[159]	validation_0-mae:2209.32765
[160]	validation_0-mae:2209.52686
[161]	validation_0-mae:2207.34378
[162]	validation_0-mae:2204.49409
[163]	validation_0-mae:2201.99694
[164]	validation_0-mae:2202.30445
[165]	validation_0-mae:2201.76345
[166]	validation_0-mae:2201.05017
[167]	validation_0-mae:2200.70943
[168]	validation_0-mae:2200.28606
[169]	validation_0-mae:2198.98069
[170]	validation_0-mae:2198.09876
[171]	validation_0-mae:2197.03149
[172]	validation_0-mae:2194.58153
[173]	validation_0-mae:2193.77520
[174]	validation_0-mae:2192.68161
[175]	validation_0-mae:2190.15224
[176]	validation_0-mae:2190.60884
[177]	validation_0-mae:2190.01410
[178]	validation_0-mae:2189.21207
[179]	validation_0-mae:2188.72184
[180]	validation_0-mae:2186.61986
[181]	validation_0-mae:2186.27412
[182]	validation_0-mae:2186.28254
[183]	validation_0-mae:2183.89571
[184]	validation_0-mae:2183.32861
[185]	validation_0-mae:2183.23955
[186]	validation_0-mae:2180.66118
[187]	validation_0-mae:2180.53899
[188]	validation_0-mae:2180.12481
[189]	validation_0-mae:2180.28474
[190]	validation_0-mae:2177.73910
[191]	validation_0-mae:2176.65899
[192]	validation_0-mae:2175.12322
[193]	validation_0-mae:2174.09380
[194]	validation_0-mae:2174.08133
[195]	validation_0-mae:2174.26214
[196]	validation_0-mae:2174.59189
[197]	validation_0-mae:2173.60231
[198]	validation_0-mae:2173.37878
[199]	validation_0-mae:2173.17152
[200]	validation_0-mae:2173.15471
[201]	validation_0-mae:2172.56695
[202]	validation_0-mae:2172.81499
[203]	validation_0-mae:2173.96622
[204]	validation_0-mae:2172.10630
[205]	validation_0-mae:2172.83722
[206]	validation_0-mae:2172.69565
[207]	validation_0-mae:2171.74290
[208]	validation_0-mae:2170.34321
[209]	validation_0-mae:2169.67174
[210]	validation_0-mae:2169.56869
[211]	validation_0-mae:2168.76954
[212]	validation_0-mae:2167.71186
[213]	validation_0-mae:2167.08025
[214]	validation_0-mae:2166.48559
[215]	validation_0-mae:2165.63746
[216]	validation_0-mae:2165.53826
[217]	validation_0-mae:2164.13502
[218]	validation_0-mae:2163.75516
[219]	validation_0-mae:2164.81897
[220]	validation_0-mae:2164.88724
[221]	validation_0-mae:2164.82178
[222]	validation_0-mae:2164.52305
[223]	validation_0-mae:2164.03724
[224]	validation_0-mae:2163.76429
[225]	validation_0-mae:2164.17312
[226]	validation_0-mae:2163.62359
[227]	validation_0-mae:2163.16345
[228]	validation_0-mae:2162.85320
[229]	validation_0-mae:2162.81721
[230]	validation_0-mae:2162.87777
[231]	validation_0-mae:2160.73212
[232]	validation_0-mae:2159.94570
[233]	validation_0-mae:2159.36971
[234]	validation_0-mae:2159.24698
[235]	validation_0-mae:2158.52224
[236]	validation_0-mae:2157.60272
[237]	validation_0-mae:2156.97656
[238]	validation_0-mae:2157.60421
[239]	validation_0-mae:2156.41274
[240]	validation_0-mae:2157.04199
[241]	validation_0-mae:2156.53556
[242]	validation_0-mae:2156.29546
[243]	validation_0-mae:2155.14279
[244]	validation_0-mae:2154.73827
[245]	validation_0-mae:2153.95730
[246]	validation_0-mae:2152.75906
[247]	validation_0-mae:2153.39084
[248]	validation_0-mae:2153.33133
[249]	validation_0-mae:2152.71850
[250]	validation_0-mae:2152.93641
[251]	validation_0-mae:2152.78361
[252]	validation_0-mae:2152.69951
[253]	validation_0-mae:2153.20692
[254]	validation_0-mae:2152.52782
[255]	validation_0-mae:2151.97203
[256]	validation_0-mae:2152.38129
[257]	validation_0-mae:2152.06812
[258]	validation_0-mae:2152.11356
[259]	validation_0-mae:2150.60522
[260]	validation_0-mae:2150.66762
[261]	validation_0-mae:2151.28594
[262]	validation_0-mae:2151.04129
[263]	validation_0-mae:2151.31120
[264]	validation_0-mae:2151.45584
[265]	validation_0-mae:2151.60773
[266]	validation_0-mae:2151.22642
[267]	validation_0-mae:2151.60428
[268]	validation_0-mae:2150.85239
[269]	validation_0-mae:2149.95250
[270]	validation_0-mae:2148.73051
[271]	validation_0-mae:2149.95069
[272]	validation_0-mae:2149.54896
[273]	validation_0-mae:2149.26122
[274]	validation_0-mae:2147.87251
[275]	validation_0-mae:2148.26943
[276]	validation_0-mae:2147.07423
[277]	validation_0-mae:2146.68613
[278]	validation_0-mae:2146.14098
[279]	validation_0-mae:2145.11060
[280]	validation_0-mae:2144.11785
[281]	validation_0-mae:2142.55909
[282]	validation_0-mae:2141.94956
[283]	validation_0-mae:2142.21145
[284]	validation_0-mae:2142.49483
[285]	validation_0-mae:2140.38315
[286]	validation_0-mae:2139.44204
[287]	validation_0-mae:2138.79975
[288]	validation_0-mae:2138.10467
[289]	validation_0-mae:2136.40072
[290]	validation_0-mae:2136.84155
[291]	validation_0-mae:2136.82680
[292]	validation_0-mae:2137.34918
[293]	validation_0-mae:2138.06148
[294]	validation_0-mae:2137.58957
[295]	validation_0-mae:2137.48060
[296]	validation_0-mae:2137.94461
[297]	validation_0-mae:2138.77237
[298]	validation_0-mae:2137.35319
[299]	validation_0-mae:2137.57460
[300]	validation_0-mae:2136.59454
[301]	validation_0-mae:2137.16520
[302]	validation_0-mae:2137.49315
[303]	validation_0-mae:2136.23696
[304]	validation_0-mae:2135.40549
[305]	validation_0-mae:2134.73655
[306]	validation_0-mae:2134.46653
[307]	validation_0-mae:2134.77390
[308]	validation_0-mae:2133.46546
[309]	validation_0-mae:2133.01985
[310]	validation_0-mae:2132.80892
[311]	validation_0-mae:2132.07317
[312]	validation_0-mae:2132.26672
[313]	validation_0-mae:2131.74095
[314]	validation_0-mae:2132.30143
[315]	validation_0-mae:2131.76449
[316]	validation_0-mae:2132.16277
[317]	validation_0-mae:2131.90296
[318]	validation_0-mae:2131.06949
[319]	validation_0-mae:2131.19479
[320]	validation_0-mae:2130.86742
[321]	validation_0-mae:2130.67959
[322]	validation_0-mae:2131.18899
[323]	validation_0-mae:2131.26133
[324]	validation_0-mae:2132.15592
[325]	validation_0-mae:2132.90492
[326]	validation_0-mae:2131.72108
[327]	validation_0-mae:2131.25520
[328]	validation_0-mae:2131.76373
[329]	validation_0-mae:2131.91988
[330]	validation_0-mae:2131.81606
[331]	validation_0-mae:2131.15368
[332]	validation_0-mae:2130.84419
[333]	validation_0-mae:2129.69003
[334]	validation_0-mae:2130.14553
[335]	validation_0-mae:2129.91403
[336]	validation_0-mae:2129.93961
[337]	validation_0-mae:2130.43490
[338]	validation_0-mae:2130.71462
[339]	validation_0-mae:2130.17982
[340]	validation_0-mae:2130.30224
[341]	validation_0-mae:2128.87525
[342]	validation_0-mae:2129.15497
[343]	validation_0-mae:2128.89167
[344]	validation_0-mae:2128.89294
[345]	validation_0-mae:2128.06150
[346]	validation_0-mae:2126.94045
[347]	validation_0-mae:2126.50873
[348]	validation_0-mae:2125.78471
[349]	validation_0-mae:2125.01116
[350]	validation_0-mae:2125.47023
[351]	validation_0-mae:2125.19053
[352]	validation_0-mae:2125.37212
[353]	validation_0-mae:2125.12161
[354]	validation_0-mae:2124.73878
[355]	validation_0-mae:2123.79305
[356]	validation_0-mae:2123.44597
[357]	validation_0-mae:2123.33146
[358]	validation_0-mae:2123.34802
[359]	validation_0-mae:2122.52222
[360]	validation_0-mae:2122.79403
[361]	validation_0-mae:2121.88339
[362]	validation_0-mae:2121.54112
[363]	validation_0-mae:2121.60978
[364]	validation_0-mae:2121.99957
[365]	validation_0-mae:2121.14124
[366]	validation_0-mae:2121.55058
[367]	validation_0-mae:2121.46428
[368]	validation_0-mae:2121.78849
[369]	validation_0-mae:2122.07183
[370]	validation_0-mae:2122.43964
[371]	validation_0-mae:2122.28465
[372]	validation_0-mae:2122.13008
[373]	validation_0-mae:2122.07176
[374]	validation_0-mae:2121.26473
[375]	validation_0-mae:2121.01451
[376]	validation_0-mae:2120.56896
[377]	validation_0-mae:2119.81204
[378]	validation_0-mae:2120.00722
[379]	validation_0-mae:2120.21941
[380]	validation_0-mae:2120.20055
[381]	validation_0-mae:2120.10319
[382]	validation_0-mae:2120.36109
[383]	validation_0-mae:2120.07179
[384]	validation_0-mae:2119.76386
[385]	validation_0-mae:2119.84277
[386]	validation_0-mae:2119.93550
[387]	validation_0-mae:2118.66673
[388]	validation_0-mae:2119.17595
[389]	validation_0-mae:2118.75985
[390]	validation_0-mae:2116.97389
[391]	validation_0-mae:2116.69161
[392]	validation_0-mae:2115.93920
[393]	validation_0-mae:2116.76761
[394]	validation_0-mae:2116.30445
[395]	validation_0-mae:2116.47662
[396]	validation_0-mae:2116.51781
[397]	validation_0-mae:2115.65276
[398]	validation_0-mae:2115.96419
[399]	validation_0-mae:2115.86971
[400]	validation_0-mae:2115.98400
[401]	validation_0-mae:2116.18133
[402]	validation_0-mae:2115.85454
[403]	validation_0-mae:2114.84073
[404]	validation_0-mae:2115.89111
[405]	validation_0-mae:2115.86117
[406]	validation_0-mae:2115.63983
[407]	validation_0-mae:2115.56337
[408]	validation_0-mae:2115.81752
[409]	validation_0-mae:2116.55515
[410]	validation_0-mae:2116.53594
[411]	validation_0-mae:2115.85326
[412]	validation_0-mae:2115.52730
[413]	validation_0-mae:2115.43561
[414]	validation_0-mae:2115.12984
[415]	validation_0-mae:2114.87295
[416]	validation_0-mae:2114.85600
[417]	validation_0-mae:2114.85119
[418]	validation_0-mae:2114.87172
[419]	validation_0-mae:2114.91373
[420]	validation_0-mae:2115.06025
[421]	validation_0-mae:2114.87455
[422]	validation_0-mae:2115.50049
[423]	validation_0-mae:2115.36982
[424]	validation_0-mae:2115.14008
[425]	validation_0-mae:2114.42878
[426]	validation_0-mae:2114.57076
[427]	validation_0-mae:2114.23897
[428]	validation_0-mae:2113.49267
[429]	validation_0-mae:2113.72341
[430]	validation_0-mae:2113.98017
[431]	validation_0-mae:2112.76836
[432]	validation_0-mae:2112.85674
[433]	validation_0-mae:2112.87646
[434]	validation_0-mae:2113.14540
[435]	validation_0-mae:2113.24741
[436]	validation_0-mae:2112.18419
[437]	validation_0-mae:2112.03438
[438]	validation_0-mae:2112.03245
[439]	validation_0-mae:2112.24935
[440]	validation_0-mae:2111.71956
[441]	validation_0-mae:2111.66095
[442]	validation_0-mae:2111.19506
[443]	validation_0-mae:2111.53963
[444]	validation_0-mae:2111.59804
[445]	validation_0-mae:2110.58219
[446]	validation_0-mae:2110.88691
[447]	validation_0-mae:2110.59556
[448]	validation_0-mae:2110.64946
[449]	validation_0-mae:2110.49464
[450]	validation_0-mae:2110.47950
[451]	validation_0-mae:2110.20717
[452]	validation_0-mae:2110.00206
[453]	validation_0-mae:2109.81490
[454]	validation_0-mae:2109.38762
[455]	validation_0-mae:2109.13030
[456]	validation_0-mae:2109.03142
[457]	validation_0-mae:2108.89808
[458]	validation_0-mae:2108.43645
[459]	validation_0-mae:2108.33944
[460]	validation_0-mae:2108.15320
[461]	validation_0-mae:2107.57914
[462]	validation_0-mae:2107.39182
[463]	validation_0-mae:2107.11950
[464]	validation_0-mae:2106.41260
[465]	validation_0-mae:2106.16231
[466]	validation_0-mae:2106.32756
[467]	validation_0-mae:2106.50627
[468]	validation_0-mae:2106.36308
[469]	validation_0-mae:2106.29943
[470]	validation_0-mae:2106.66182
[471]	validation_0-mae:2106.31530
[472]	validation_0-mae:2106.48233
[473]	validation_0-mae:2105.69666
[474]	validation_0-mae:2105.05491
[475]	validation_0-mae:2104.80511
[476]	validation_0-mae:2104.64746
[477]	validation_0-mae:2104.25932
[478]	validation_0-mae:2104.53781
[479]	validation_0-mae:2104.65582
[480]	validation_0-mae:2104.45871
[481]	validation_0-mae:2104.24014
[482]	validation_0-mae:2103.93160
[483]	validation_0-mae:2103.48890
[484]	validation_0-mae:2102.84309
[485]	validation_0-mae:2102.50455
[486]	validation_0-mae:2102.21734
[487]	validation_0-mae:2101.86943
[488]	validation_0-mae:2101.79795
[489]	validation_0-mae:2101.93793
[490]	validation_0-mae:2102.13015
[491]	validation_0-mae:2102.20600
[492]	validation_0-mae:2102.51206
[493]	validation_0-mae:2102.62526
[494]	validation_0-mae:2102.95197
[495]	validation_0-mae:2103.31660
[496]	validation_0-mae:2103.54725
[497]	validation_0-mae:2103.43747
[498]	validation_0-mae:2103.72173
[499]	validation_0-mae:2103.52157
[500]	validation_0-mae:2102.58764
[501]	validation_0-mae:2102.18415
[502]	validation_0-mae:2101.82035
[503]	validation_0-mae:2101.86271
[504]	validation_0-mae:2102.11350
[505]	validation_0-mae:2101.86752
[506]	validation_0-mae:2101.74517
[507]	validation_0-mae:2101.78149
[508]	validation_0-mae:2101.43240
[509]	validation_0-mae:2101.63182
[510]	validation_0-mae:2101.66435
[511]	validation_0-mae:2101.35966
[512]	validation_0-mae:2101.35979
[513]	validation_0-mae:2101.09836
[514]	validation_0-mae:2101.21032
[515]	validation_0-mae:2101.12268
[516]	validation_0-mae:2101.25996
[517]	validation_0-mae:2101.35514
[518]	validation_0-mae:2101.42923
[519]	validation_0-mae:2101.43439
[520]	validation_0-mae:2101.21464
[521]	validation_0-mae:2101.40889
[522]	validation_0-mae:2101.40628
[523]	validation_0-mae:2101.24392
[524]	validation_0-mae:2101.41630
[525]	validation_0-mae:2101.46235
[526]	validation_0-mae:2101.48520
[527]	validation_0-mae:2101.76693
[528]	validation_0-mae:2101.62390
[529]	validation_0-mae:2101.83391
[530]	validation_0-mae:2101.90054
[531]	validation_0-mae:2101.88231
[532]	validation_0-mae:2101.91357
[533]	validation_0-mae:2101.90156
[534]	validation_0-mae:2101.95267
[535]	validation_0-mae:2102.18969
[536]	validation_0-mae:2102.29585
[537]	validation_0-mae:2102.57604
[538]	validation_0-mae:2102.79724
[539]	validation_0-mae:2102.61898
[540]	validation_0-mae:2102.69434
[541]	validation_0-mae:2102.87950
[542]	validation_0-mae:2102.98351
[543]	validation_0-mae:2102.86628
[544]	validation_0-mae:2102.65611
[545]	validation_0-mae:2102.92904
[546]	validation_0-mae:2102.85952
[547]	validation_0-mae:2103.07445
[548]	validation_0-mae:2102.85966
[549]	validation_0-mae:2102.76291
[550]	validation_0-mae:2103.05589
[551]	validation_0-mae:2102.54948
[552]	validation_0-mae:2102.71469
[553]	validation_0-mae:2102.65048
[554]	validation_0-mae:2102.81673
[555]	validation_0-mae:2102.98023
[556]	validation_0-mae:2102.95141
[557]	validation_0-mae:2102.89801
[558]	validation_0-mae:2102.67828
[559]	validation_0-mae:2102.75596
[560]	validation_0-mae:2103.16369
[561]	validation_0-mae:2103.24942
[562]	validation_0-mae:2103.24755
[563]	validation_0-mae:2103.66837
[564]	validation_0-mae:2103.76680
[565]	validation_0-mae:2103.84896
[566]	validation_0-mae:2103.99494
[567]	validation_0-mae:2103.14972
[568]	validation_0-mae:2102.79010
[569]	validation_0-mae:2103.05932
[570]	validation_0-mae:2103.07600
[571]	validation_0-mae:2103.03716
[572]	validation_0-mae:2102.78554
[573]	validation_0-mae:2103.00617
[574]	validation_0-mae:2102.85709
[575]	validation_0-mae:2103.14639
[576]	validation_0-mae:2103.12335
[577]	validation_0-mae:2103.20756
[578]	validation_0-mae:2102.64897
[579]	validation_0-mae:2102.66439
[580]	validation_0-mae:2102.56109
[581]	validation_0-mae:2102.82927
[582]	validation_0-mae:2102.86297
[583]	validation_0-mae:2102.93152
[584]	validation_0-mae:2102.69643
[585]	validation_0-mae:2102.77064
[586]	validation_0-mae:2102.31727
[587]	validation_0-mae:2102.09006
[588]	validation_0-mae:2101.95930
[589]	validation_0-mae:2101.88679
[590]	validation_0-mae:2101.91053

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[0]	validation_0-mae:12520.48975
[1]	validation_0-mae:11838.90523
[2]	validation_0-mae:11234.31049
[3]	validation_0-mae:10671.98964
[4]	validation_0-mae:10175.51848
[5]	validation_0-mae:9735.32981
[6]	validation_0-mae:9334.34602
[7]	validation_0-mae:8994.52195
[8]	validation_0-mae:8686.10032
[9]	validation_0-mae:8400.00884
[0]	validation_0-mae:12476.46743
[1]	validation_0-mae:11772.47399
[2]	validation_0-mae:11124.41202
[3]	validation_0-mae:10523.40412
[4]	validation_0-mae:9990.08205
[5]	validation_0-mae:9517.02896
[6]	validation_0-mae:9077.49318
[7]	validation_0-mae:8671.88536
[8]	validation_0-mae:8297.89684
[9]	validation_0-mae:7957.24305
[10]	validation_0-mae:7631.97014
[11]	validation_0-mae:7332.66738
[12]	validation_0-mae:7072.67781
[13]	validation_0-mae:6806.78534
[14]	validation_0-mae:6559.51495
[15]	validation_0-mae:6306.54350
[16]	validation_0-mae:6107.33763
[17]	validation_0-mae:5892.47546
[18]	validation_0-mae:5694.52979
[19]	validation_0-mae:5510.94013
[20]	validation_0-mae:5328.21459
[21]	validation_0-mae:5172.25857
[22]	validation_0-mae:5029.40775
[23]	validation_0-mae:4887.28014
[24]	validation_0-mae:4750.86410
[25]	validation_0-mae:4629.66770
[26]	validation_0-mae:4506.96332
[27]	validation_0-mae:4404.97059
[28]	validation_0-mae:4296.63887
[29]	validation_0-mae:4180.94358
[30]	validation_0-mae:4081.14435
[31]	validation_0-mae:4009.12594
[32]	validation_0-mae:3929.46534
[33]	validation_0-mae:3850.03412
[34]	validation_0-mae:3785.62336
[35]	validation_0-mae:3717.95754
[36]	validation_0-mae:3665.04201
[37]	validation_0-mae:3605.52063
[38]	validation_0-mae:3556.11762
[39]	validation_0-mae:3496.34959

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[40]	validation_0-mae:3452.43211
[41]	validation_0-mae:3403.47295
[42]	validation_0-mae:3362.70611
[43]	validation_0-mae:3322.09357
[44]	validation_0-mae:3276.42841
[45]	validation_0-mae:3241.16151
[46]	validation_0-mae:3201.40922
[47]	validation_0-mae:3169.10058
[48]	validation_0-mae:3131.10939
[49]	validation_0-mae:3097.22141
[50]	validation_0-mae:3072.12770
[51]	validation_0-mae:3041.90107
[52]	validation_0-mae:3016.53738
[53]	validation_0-mae:2988.06067
[54]	validation_0-mae:2959.90583
[55]	validation_0-mae:2940.88126
[56]	validation_0-mae:2923.84526
[57]	validation_0-mae:2891.07449
[58]	validation_0-mae:2875.52398
[59]	validation_0-mae:2857.66667
[60]	validation_0-mae:2837.00752
[61]	validation_0-mae:2809.40836
[62]	validation_0-mae:2795.67831
[63]	validation_0-mae:2782.57919
[64]	validation_0-mae:2765.71211
[65]	validation_0-mae:2754.54566
[66]	validation_0-mae:2737.91069
[67]	validation_0-mae:2715.22991
[68]	validation_0-mae:2695.66592
[69]	validation_0-mae:2673.70644
[70]	validation_0-mae:2663.78067
[71]	validation_0-mae:2641.76846
[72]	validation_0-mae:2625.91200
[73]	validation_0-mae:2620.57093
[74]	validation_0-mae:2605.17094
[75]	validation_0-mae:2595.32710
[76]	validation_0-mae:2586.66418
[77]	validation_0-mae:2575.32327
[78]	validation_0-mae:2567.04451
[79]	validation_0-mae:2562.56944
[80]	validation_0-mae:2552.12109
[81]	validation_0-mae:2542.75822
[82]	validation_0-mae:2535.05535
[83]	validation_0-mae:2527.91235
[84]	validation_0-mae:2523.01187
[85]	validation_0-mae:2509.68860
[86]	validation_0-mae:2500.43714
[87]	validation_0-mae:2487.77930
[88]	validation_0-mae:2479.34336
[89]	validation_0-mae:2466.07399
[90]	validation_0-mae:2457.26956
[91]	validation_0-mae:2447.66480
[92]	validation_0-mae:2441.81059
[93]	validation_0-mae:2435.33052
[94]	validation_0-mae:2425.58380
[95]	validation_0-mae:2420.89380
[96]	validation_0-mae:2415.08561
[97]	validation_0-mae:2410.05561
[98]	validation_0-mae:2402.53315
[99]	validation_0-mae:2394.96712
[100]	validation_0-mae:2389.47393
[101]	validation_0-mae:2387.46821
[102]	validation_0-mae:2384.03754
[103]	validation_0-mae:2381.01035
[104]	validation_0-mae:2378.17881
[105]	validation_0-mae:2374.80789
[106]	validation_0-mae:2372.18258
[107]	validation_0-mae:2368.25219
[108]	validation_0-mae:2363.68811
[109]	validation_0-mae:2355.79352
[110]	validation_0-mae:2352.64860
[111]	validation_0-mae:2347.79639
[112]	validation_0-mae:2342.69715
[113]	validation_0-mae:2339.69752
[114]	validation_0-mae:2337.77319
[115]	validation_0-mae:2334.64009
[116]	validation_0-mae:2333.48204
[117]	validation_0-mae:2328.22613
[118]	validation_0-mae:2324.81446
[119]	validation_0-mae:2321.71728
[120]	validation_0-mae:2318.47806
[121]	validation_0-mae:2316.31110
[122]	validation_0-mae:2313.38155
[123]	validation_0-mae:2311.34006
[124]	validation_0-mae:2308.45105
[125]	validation_0-mae:2304.87974
[126]	validation_0-mae:2302.42957
[127]	validation_0-mae:2299.30232
[128]	validation_0-mae:2294.11267
[129]	validation_0-mae:2292.65318
[130]	validation_0-mae:2291.31941
[131]	validation_0-mae:2288.44135
[132]	validation_0-mae:2287.38608
[133]	validation_0-mae:2286.25093
[134]	validation_0-mae:2283.73548
[135]	validation_0-mae:2280.16330
[136]	validation_0-mae:2276.51080
[137]	validation_0-mae:2274.31210
[138]	validation_0-mae:2275.35498
[139]	validation_0-mae:2272.32033
[140]	validation_0-mae:2269.38244
[141]	validation_0-mae:2268.65295
[142]	validation_0-mae:2268.77676
[143]	validation_0-mae:2267.48873
[144]	validation_0-mae:2265.37164
[145]	validation_0-mae:2264.90063
[146]	validation_0-mae:2264.18409
[147]	validation_0-mae:2262.69497
[148]	validation_0-mae:2260.85770
[149]	validation_0-mae:2259.81556
[150]	validation_0-mae:2255.29790
[151]	validation_0-mae:2252.14694
[152]	validation_0-mae:2250.02765
[153]	validation_0-mae:2250.27118
[154]	validation_0-mae:2247.64027
[155]	validation_0-mae:2245.74662
[156]	validation_0-mae:2244.58599
[157]	validation_0-mae:2243.53541
[158]	validation_0-mae:2240.33907
[159]	validation_0-mae:2239.85818
[160]	validation_0-mae:2236.59650
[161]	validation_0-mae:2234.72691
[162]	validation_0-mae:2233.22313
[163]	validation_0-mae:2231.85900
[164]	validation_0-mae:2232.49417
[165]	validation_0-mae:2232.02405
[166]	validation_0-mae:2231.32230
[167]	validation_0-mae:2230.57889
[168]	validation_0-mae:2231.12728
[169]	validation_0-mae:2230.88954
[170]	validation_0-mae:2229.47721
[171]	validation_0-mae:2227.68046
[172]	validation_0-mae:2226.23169
[173]	validation_0-mae:2225.57453
[174]	validation_0-mae:2224.70912
[175]	validation_0-mae:2222.33138
[176]	validation_0-mae:2220.73164
[177]	validation_0-mae:2219.36953
[178]	validation_0-mae:2219.18253
[179]	validation_0-mae:2218.54633
[180]	validation_0-mae:2216.75137
[181]	validation_0-mae:2216.79247
[182]	validation_0-mae:2215.88264
[183]	validation_0-mae:2214.42152
[184]	validation_0-mae:2213.29995
[185]	validation_0-mae:2211.93373
[186]	validation_0-mae:2211.30282
[187]	validation_0-mae:2209.56075
[188]	validation_0-mae:2208.80527
[189]	validation_0-mae:2208.06896
[190]	validation_0-mae:2207.60166
[191]	validation_0-mae:2207.82897
[192]	validation_0-mae:2207.54392
[193]	validation_0-mae:2206.73350
[194]	validation_0-mae:2205.55642
[195]	validation_0-mae:2205.14048
[196]	validation_0-mae:2203.46296
[197]	validation_0-mae:2203.78138
[198]	validation_0-mae:2204.20860
[199]	validation_0-mae:2202.82988
[200]	validation_0-mae:2202.35403
[201]	validation_0-mae:2202.20050
[202]	validation_0-mae:2201.12081
[203]	validation_0-mae:2201.89516
[204]	validation_0-mae:2201.35873
[205]	validation_0-mae:2200.63353
[206]	validation_0-mae:2201.34075
[207]	validation_0-mae:2199.45824
[208]	validation_0-mae:2197.48074
[209]	validation_0-mae:2198.07543
[210]	validation_0-mae:2197.90930
[211]	validation_0-mae:2198.21243
[212]	validation_0-mae:2198.51172
[213]	validation_0-mae:2196.85426
[214]	validation_0-mae:2195.35393
[215]	validation_0-mae:2194.08988
[216]	validation_0-mae:2193.28098
[217]	validation_0-mae:2192.31680
[218]	validation_0-mae:2191.48854
[219]	validation_0-mae:2191.13938
[220]	validation_0-mae:2190.88933
[221]	validation_0-mae:2189.23503
[222]	validation_0-mae:2189.83079
[223]	validation_0-mae:2188.26514
[224]	validation_0-mae:2188.09234
[225]	validation_0-mae:2186.74847
[226]	validation_0-mae:2187.71364
[227]	validation_0-mae:2186.47234
[228]	validation_0-mae:2186.68846
[229]	validation_0-mae:2186.55980
[230]	validation_0-mae:2186.42743
[231]	validation_0-mae:2186.27886
[232]	validation_0-mae:2186.23473
[233]	validation_0-mae:2187.30729
[234]	validation_0-mae:2186.78540
[235]	validation_0-mae:2187.35373
[236]	validation_0-mae:2185.67253
[237]	validation_0-mae:2185.70050
[238]	validation_0-mae:2185.98103
[239]	validation_0-mae:2184.51780
[240]	validation_0-mae:2182.67490
[241]	validation_0-mae:2182.01060
[242]	validation_0-mae:2180.97624
[243]	validation_0-mae:2181.39700
[244]	validation_0-mae:2180.80672
[245]	validation_0-mae:2180.61792
[246]	validation_0-mae:2178.65313
[247]	validation_0-mae:2177.81483
[248]	validation_0-mae:2176.99161
[249]	validation_0-mae:2176.72518
[250]	validation_0-mae:2175.09785
[251]	validation_0-mae:2175.30916
[252]	validation_0-mae:2175.39792
[253]	validation_0-mae:2176.44150
[254]	validation_0-mae:2176.64699
[255]	validation_0-mae:2177.19563
[256]	validation_0-mae:2177.04002
[257]	validation_0-mae:2177.83172
[258]	validation_0-mae:2178.02839
[259]	validation_0-mae:2177.82187
[260]	validation_0-mae:2176.48737
[261]	validation_0-mae:2176.03762
[262]	validation_0-mae:2176.96550
[263]	validation_0-mae:2176.05115
[264]	validation_0-mae:2175.81116
[265]	validation_0-mae:2175.60253
[266]	validation_0-mae:2175.49660
[267]	validation_0-mae:2176.11172
[268]	validation_0-mae:2176.22125
[269]	validation_0-mae:2176.55507
[270]	validation_0-mae:2177.19939
[271]	validation_0-mae:2177.11736
[272]	validation_0-mae:2175.72221
[273]	validation_0-mae:2175.80075
[274]	validation_0-mae:2176.11261
[275]	validation_0-mae:2176.46612
[276]	validation_0-mae:2177.50277
[277]	validation_0-mae:2177.86962
[278]	validation_0-mae:2178.46058
[279]	validation_0-mae:2178.36078
[280]	validation_0-mae:2178.25540
[281]	validation_0-mae:2178.29035
[282]	validation_0-mae:2178.20784
[283]	validation_0-mae:2177.70506
[284]	validation_0-mae:2177.74193
[285]	validation_0-mae:2177.93051
[286]	validation_0-mae:2177.50399
[287]	validation_0-mae:2176.41328
[288]	validation_0-mae:2174.72297
[289]	validation_0-mae:2172.86547
[290]	validation_0-mae:2170.63751
[291]	validation_0-mae:2169.72689
[292]	validation_0-mae:2168.47275
[293]	validation_0-mae:2166.90298
[294]	validation_0-mae:2166.10881
[295]	validation_0-mae:2165.71732
[296]	validation_0-mae:2164.66840
[297]	validation_0-mae:2165.16121
[298]	validation_0-mae:2164.25346
[299]	validation_0-mae:2163.67654
[300]	validation_0-mae:2163.42663
[301]	validation_0-mae:2163.53775
[302]	validation_0-mae:2163.35047
[303]	validation_0-mae:2162.92356
[304]	validation_0-mae:2159.54975
[305]	validation_0-mae:2159.31728
[306]	validation_0-mae:2159.20332
[307]	validation_0-mae:2157.98300
[308]	validation_0-mae:2158.07226
[309]	validation_0-mae:2158.49620
[310]	validation_0-mae:2157.79558
[311]	validation_0-mae:2156.75716
[312]	validation_0-mae:2155.65861
[313]	validation_0-mae:2155.45364
[314]	validation_0-mae:2154.66545
[315]	validation_0-mae:2155.06087
[316]	validation_0-mae:2155.23832
[317]	validation_0-mae:2155.13624
[318]	validation_0-mae:2154.89926
[319]	validation_0-mae:2155.06267
[320]	validation_0-mae:2155.17338
[321]	validation_0-mae:2155.07100
[322]	validation_0-mae:2153.62560
[323]	validation_0-mae:2153.62315
[324]	validation_0-mae:2152.97466
[325]	validation_0-mae:2153.25367
[326]	validation_0-mae:2152.78175
[327]	validation_0-mae:2152.00058
[328]	validation_0-mae:2151.22115
[329]	validation_0-mae:2150.58669
[330]	validation_0-mae:2150.74478
[331]	validation_0-mae:2150.17870
[332]	validation_0-mae:2149.60618
[333]	validation_0-mae:2149.20751
[334]	validation_0-mae:2148.89093
[335]	validation_0-mae:2148.36946
[336]	validation_0-mae:2148.12724
[337]	validation_0-mae:2148.05210
[338]	validation_0-mae:2147.49008
[339]	validation_0-mae:2146.92909
[340]	validation_0-mae:2145.77862
[341]	validation_0-mae:2145.47582
[342]	validation_0-mae:2145.33123
[343]	validation_0-mae:2144.93905
[344]	validation_0-mae:2145.18088
[345]	validation_0-mae:2143.72027
[346]	validation_0-mae:2143.00048
[347]	validation_0-mae:2142.99515
[348]	validation_0-mae:2142.59592
[349]	validation_0-mae:2141.76344
[350]	validation_0-mae:2140.93860
[351]	validation_0-mae:2139.68817
[352]	validation_0-mae:2140.39698
[353]	validation_0-mae:2141.01104
[354]	validation_0-mae:2140.95587
[355]	validation_0-mae:2141.03164
[356]	validation_0-mae:2140.57405
[357]	validation_0-mae:2140.63561
[358]	validation_0-mae:2140.93167
[359]	validation_0-mae:2141.25079
[360]	validation_0-mae:2141.22801
[361]	validation_0-mae:2141.36653
[362]	validation_0-mae:2141.38079
[363]	validation_0-mae:2141.68066
[364]	validation_0-mae:2141.79257
[365]	validation_0-mae:2141.76003
[366]	validation_0-mae:2141.97717
[367]	validation_0-mae:2140.87965
[368]	validation_0-mae:2140.58670
[369]	validation_0-mae:2140.14185
[370]	validation_0-mae:2139.60675
[371]	validation_0-mae:2138.47078
[372]	validation_0-mae:2137.57477
[373]	validation_0-mae:2137.15871
[374]	validation_0-mae:2136.32043
[375]	validation_0-mae:2136.64336
[376]	validation_0-mae:2136.63239
[377]	validation_0-mae:2136.40650
[378]	validation_0-mae:2136.37046
[379]	validation_0-mae:2135.59772
[380]	validation_0-mae:2135.66410
[381]	validation_0-mae:2134.91968
[382]	validation_0-mae:2134.83886
[383]	validation_0-mae:2134.13306
[384]	validation_0-mae:2134.14676
[385]	validation_0-mae:2133.97533
[386]	validation_0-mae:2133.59521
[387]	validation_0-mae:2133.00789
[388]	validation_0-mae:2133.21627
[389]	validation_0-mae:2132.36558
[390]	validation_0-mae:2132.04817
[391]	validation_0-mae:2131.20884
[392]	validation_0-mae:2130.68050
[393]	validation_0-mae:2130.98169
[394]	validation_0-mae:2130.90783
[395]	validation_0-mae:2131.18583
[396]	validation_0-mae:2130.53742
[397]	validation_0-mae:2130.15315
[398]	validation_0-mae:2130.33974
[399]	validation_0-mae:2129.44894
[400]	validation_0-mae:2130.06108
[401]	validation_0-mae:2129.98864
[402]	validation_0-mae:2130.67678
[403]	validation_0-mae:2131.10073
[404]	validation_0-mae:2130.14337
[405]	validation_0-mae:2129.84110
[406]	validation_0-mae:2129.01640
[407]	validation_0-mae:2128.22734
[408]	validation_0-mae:2128.15403
[409]	validation_0-mae:2126.81979
[410]	validation_0-mae:2127.33235
[411]	validation_0-mae:2126.62648
[412]	validation_0-mae:2126.65318
[413]	validation_0-mae:2126.07617
[414]	validation_0-mae:2126.03610
[415]	validation_0-mae:2126.09929
[416]	validation_0-mae:2126.07707
[417]	validation_0-mae:2125.24239
[418]	validation_0-mae:2124.88201
[419]	validation_0-mae:2124.61815
[420]	validation_0-mae:2123.75152
[421]	validation_0-mae:2122.81525
[422]	validation_0-mae:2122.42072
[423]	validation_0-mae:2122.29479
[424]	validation_0-mae:2121.75499
[425]	validation_0-mae:2120.80142
[426]	validation_0-mae:2120.73899
[427]	validation_0-mae:2120.44424
[428]	validation_0-mae:2120.70553
[429]	validation_0-mae:2121.18488
[430]	validation_0-mae:2120.68370
[431]	validation_0-mae:2120.76779
[432]	validation_0-mae:2120.21059
[433]	validation_0-mae:2119.91711
[434]	validation_0-mae:2119.21391
[435]	validation_0-mae:2119.03403
[436]	validation_0-mae:2119.20125
[437]	validation_0-mae:2119.33485
[438]	validation_0-mae:2119.10107
[439]	validation_0-mae:2119.03403
[440]	validation_0-mae:2119.41106
[441]	validation_0-mae:2119.28742
[442]	validation_0-mae:2118.47302
[443]	validation_0-mae:2118.70060
[444]	validation_0-mae:2118.71985
[445]	validation_0-mae:2118.69749
[446]	validation_0-mae:2118.72196
[447]	validation_0-mae:2119.02959
[448]	validation_0-mae:2118.93485
[449]	validation_0-mae:2118.73685
[450]	validation_0-mae:2118.73832
[451]	validation_0-mae:2118.69741
[452]	validation_0-mae:2118.78111
[453]	validation_0-mae:2118.98963
[454]	validation_0-mae:2119.18626
[455]	validation_0-mae:2119.30459
[456]	validation_0-mae:2119.02955
[457]	validation_0-mae:2118.70345
[458]	validation_0-mae:2118.83556
[459]	validation_0-mae:2118.78910
[460]	validation_0-mae:2118.85645
[461]	validation_0-mae:2118.63810
[462]	validation_0-mae:2118.50555
[463]	validation_0-mae:2118.64760
[464]	validation_0-mae:2118.22774
[465]	validation_0-mae:2118.44872
[466]	validation_0-mae:2117.93052
[467]	validation_0-mae:2117.63169
[468]	validation_0-mae:2117.20934
[469]	validation_0-mae:2116.60483
[470]	validation_0-mae:2116.43076
[471]	validation_0-mae:2116.14047
[472]	validation_0-mae:2115.64917
[473]	validation_0-mae:2115.22290
[474]	validation_0-mae:2115.36060
[475]	validation_0-mae:2115.29357
[476]	validation_0-mae:2115.20568
[477]	validation_0-mae:2114.99305
[478]	validation_0-mae:2115.16877
[479]	validation_0-mae:2114.99008
[480]	validation_0-mae:2115.18371
[481]	validation_0-mae:2114.65685
[482]	validation_0-mae:2114.32034
[483]	validation_0-mae:2114.13333
[484]	validation_0-mae:2112.75534
[485]	validation_0-mae:2113.05254
[486]	validation_0-mae:2113.11113
[487]	validation_0-mae:2113.04115
[488]	validation_0-mae:2112.67486
[489]	validation_0-mae:2112.47570
[490]	validation_0-mae:2112.57076
[491]	validation_0-mae:2112.43719
[492]	validation_0-mae:2112.14739
[493]	validation_0-mae:2111.40607
[494]	validation_0-mae:2111.25233
[495]	validation_0-mae:2111.34660
[496]	validation_0-mae:2110.85195
[497]	validation_0-mae:2111.15692
[498]	validation_0-mae:2111.19678
[499]	validation_0-mae:2110.86398
[500]	validation_0-mae:2110.95781
[501]	validation_0-mae:2110.57595
[502]	validation_0-mae:2110.75667
[503]	validation_0-mae:2110.55512
[504]	validation_0-mae:2110.53890
[505]	validation_0-mae:2110.88873
[506]	validation_0-mae:2110.79792
[507]	validation_0-mae:2110.56056
[508]	validation_0-mae:2109.70242
[509]	validation_0-mae:2109.91007
[510]	validation_0-mae:2110.06584
[511]	validation_0-mae:2110.32781
[512]	validation_0-mae:2110.21456
[513]	validation_0-mae:2110.23419
[514]	validation_0-mae:2110.49385
[515]	validation_0-mae:2110.49540
[516]	validation_0-mae:2110.57084
[517]	validation_0-mae:2110.73251
[518]	validation_0-mae:2110.51265
[519]	validation_0-mae:2110.77287
[520]	validation_0-mae:2110.50863
[521]	validation_0-mae:2110.75357
[522]	validation_0-mae:2110.83774
[523]	validation_0-mae:2110.57322
[524]	validation_0-mae:2110.36138
[525]	validation_0-mae:2110.25863
[526]	validation_0-mae:2110.26841
[527]	validation_0-mae:2110.15248
[528]	validation_0-mae:2110.03314
[529]	validation_0-mae:2109.88690
[530]	validation_0-mae:2109.85803
[531]	validation_0-mae:2109.95217
[532]	validation_0-mae:2110.11003
[533]	validation_0-mae:2110.40491
[534]	validation_0-mae:2110.22523
[535]	validation_0-mae:2110.24854
[536]	validation_0-mae:2110.37758
[537]	validation_0-mae:2110.46306
[538]	validation_0-mae:2110.10112
[539]	validation_0-mae:2109.51598
[540]	validation_0-mae:2108.58383
[541]	validation_0-mae:2108.36113
[542]	validation_0-mae:2107.47821
[543]	validation_0-mae:2107.56373
[544]	validation_0-mae:2106.94605
[545]	validation_0-mae:2107.08566
[546]	validation_0-mae:2107.26498
[547]	validation_0-mae:2107.29660
[548]	validation_0-mae:2107.51575
[549]	validation_0-mae:2107.37157
[550]	validation_0-mae:2106.99849
[551]	validation_0-mae:2106.83931
[552]	validation_0-mae:2106.94813
[553]	validation_0-mae:2106.95749
[554]	validation_0-mae:2106.97949
[555]	validation_0-mae:2106.75673
[556]	validation_0-mae:2106.81284
[557]	validation_0-mae:2107.25583
[558]	validation_0-mae:2107.36503
[559]	validation_0-mae:2107.39729
[560]	validation_0-mae:2107.40113
[561]	validation_0-mae:2107.48631
[562]	validation_0-mae:2107.58393
[563]	validation_0-mae:2107.78716
[564]	validation_0-mae:2107.69060
[565]	validation_0-mae:2107.09394
[566]	validation_0-mae:2107.13485
[567]	validation_0-mae:2106.97902
[568]	validation_0-mae:2106.98989
[569]	validation_0-mae:2107.06767
[570]	validation_0-mae:2107.24690
[571]	validation_0-mae:2107.52429
[572]	validation_0-mae:2107.37893
[573]	validation_0-mae:2107.53347
[574]	validation_0-mae:2107.68120
[575]	validation_0-mae:2107.54207
[576]	validation_0-mae:2107.66757
[577]	validation_0-mae:2107.70463
[578]	validation_0-mae:2107.76403
[579]	validation_0-mae:2107.68832
[580]	validation_0-mae:2107.86575
[581]	validation_0-mae:2107.95018
[582]	validation_0-mae:2107.78114
[583]	validation_0-mae:2107.85197
[584]	validation_0-mae:2108.12529
[585]	validation_0-mae:2108.21463
[586]	validation_0-mae:2107.59051
[587]	validation_0-mae:2107.20280
[588]	validation_0-mae:2107.22833
[589]	validation_0-mae:2107.31298
[590]	validation_0-mae:2106.87202
[591]	validation_0-mae:2106.51155
[592]	validation_0-mae:2106.44315
[593]	validation_0-mae:2106.50074
[594]	validation_0-mae:2106.64713
[595]	validation_0-mae:2106.40075
[596]	validation_0-mae:2106.13863
[597]	validation_0-mae:2105.96439
[598]	validation_0-mae:2106.18860
[599]	validation_0-mae:2105.64156
[600]	validation_0-mae:2105.64146
[601]	validation_0-mae:2105.60847
[602]	validation_0-mae:2104.74861
[603]	validation_0-mae:2104.70202
[604]	validation_0-mae:2104.75455
[605]	validation_0-mae:2104.87687
[606]	validation_0-mae:2104.71736
[607]	validation_0-mae:2105.14394
[608]	validation_0-mae:2105.44436
[609]	validation_0-mae:2104.97402
[610]	validation_0-mae:2104.86725
[611]	validation_0-mae:2104.94155
[612]	validation_0-mae:2104.74465
[613]	validation_0-mae:2104.95449
[614]	validation_0-mae:2104.53124
[615]	validation_0-mae:2104.12630
[616]	validation_0-mae:2103.98887
[617]	validation_0-mae:2104.08099
[618]	validation_0-mae:2104.26569
[619]	validation_0-mae:2104.25013
[620]	validation_0-mae:2104.23759
[621]	validation_0-mae:2104.41082
[622]	validation_0-mae:2104.14077
[623]	validation_0-mae:2104.29059
[624]	validation_0-mae:2103.87282
[625]	validation_0-mae:2103.84234
[626]	validation_0-mae:2103.63886
[627]	validation_0-mae:2103.31001
[628]	validation_0-mae:2103.12043
[629]	validation_0-mae:2102.78978

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[0]	validation_0-mae:12338.10658
[1]	validation_0-mae:11538.84585
[2]	validation_0-mae:10800.51480
[3]	validation_0-mae:10129.17376
[4]	validation_0-mae:9535.70298
[5]	validation_0-mae:9019.92841
[6]	validation_0-mae:8578.06546
[7]	validation_0-mae:8150.62230
[8]	validation_0-mae:7794.23654
[9]	validation_0-mae:7452.13870
[10]	validation_0-mae:7132.22202
[11]	validation_0-mae:6814.01190
[12]	validation_0-mae:6519.92931
[13]	validation_0-mae:6259.18928
[14]	validation_0-mae:6009.24409
[15]	validation_0-mae:5781.85904
[16]	validation_0-mae:5561.12549
[17]	validation_0-mae:5344.61925
[18]	validation_0-mae:5160.80075
[19]	validation_0-mae:4979.98775
[20]	validation_0-mae:4825.26419
[21]	validation_0-mae:4679.87132
[22]	validation_0-mae:4543.87755
[23]	validation_0-mae:4429.66542
[24]	validation_0-mae:4309.22245
[25]	validation_0-mae:4194.15194
[26]	validation_0-mae:4093.79194
[27]	validation_0-mae:3998.58483
[28]	validation_0-mae:3913.41459
[29]	validation_0-mae:3818.96953
[30]	validation_0-mae:3735.86117
[31]	validation_0-mae:3651.54247
[32]	validation_0-mae:3584.59780
[33]	validation_0-mae:3525.30946
[34]	validation_0-mae:3451.74087
[35]	validation_0-mae:3395.91274
[36]	validation_0-mae:3331.03077
[37]	validation_0-mae:3279.33340
[38]	validation_0-mae:3236.16664
[39]	validation_0-mae:3179.95502
[40]	validation_0-mae:3144.12834
[41]	validation_0-mae:3110.87940
[42]	validation_0-mae:3062.13898
[43]	validation_0-mae:3034.88572
[44]	validation_0-mae:3005.40722
[45]	validation_0-mae:2967.17538
[46]	validation_0-mae:2945.74252
[47]	validation_0-mae:2918.98263
[48]	validation_0-mae:2899.39838
[49]	validation_0-mae:2868.82743
[50]	validation_0-mae:2854.99829
[51]	validation_0-mae:2840.74858
[52]	validation_0-mae:2823.65919
[53]	validation_0-mae:2807.24148
[54]	validation_0-mae:2785.83824
[55]	validation_0-mae:2776.39707
[56]	validation_0-mae:2759.82646
[57]	validation_0-mae:2741.03381
[58]	validation_0-mae:2726.00781
[59]	validation_0-mae:2704.48288
[60]	validation_0-mae:2694.73284
[61]	validation_0-mae:2682.16955
[62]	validation_0-mae:2669.86427
[63]	validation_0-mae:2641.18514
[64]	validation_0-mae:2631.30364
[65]	validation_0-mae:2620.56389
[66]	validation_0-mae:2607.47047
[67]	validation_0-mae:2601.90616
[68]	validation_0-mae:2597.29617
[69]	validation_0-mae:2587.59317
[70]	validation_0-mae:2576.09301
[71]	validation_0-mae:2571.03837
[72]	validation_0-mae:2556.54962
[73]	validation_0-mae:2549.15895
[74]	validation_0-mae:2540.29757
[75]	validation_0-mae:2531.85205
[76]	validation_0-mae:2523.20942
[77]	validation_0-mae:2514.78344
[78]	validation_0-mae:2512.05401
[79]	validation_0-mae:2500.90644
[80]	validation_0-mae:2492.54060
[81]	validation_0-mae:2482.59676
[82]	validation_0-mae:2473.99121
[83]	validation_0-mae:2467.39612
[84]	validation_0-mae:2461.45363
[85]	validation_0-mae:2456.73467
[86]	validation_0-mae:2450.10010
[87]	validation_0-mae:2443.57390
[88]	validation_0-mae:2441.81479
[89]	validation_0-mae:2435.01853
[90]	validation_0-mae:2429.67592
[91]	validation_0-mae:2425.18948
[92]	validation_0-mae:2419.56070
[93]	validation_0-mae:2411.72941
[94]	validation_0-mae:2406.58240
[95]	validation_0-mae:2401.89675
[96]	validation_0-mae:2398.82758
[97]	validation_0-mae:2393.52284
[98]	validation_0-mae:2388.24762
[99]	validation_0-mae:2383.36934
[100]	validation_0-mae:2380.96193
[101]	validation_0-mae:2376.82400
[102]	validation_0-mae:2367.33329
[103]	validation_0-mae:2361.69282
[104]	validation_0-mae:2356.35714
[105]	validation_0-mae:2351.93217
[106]	validation_0-mae:2345.84110
[107]	validation_0-mae:2340.02981
[108]	validation_0-mae:2337.62879
[109]	validation_0-mae:2332.12160
[110]	validation_0-mae:2328.57466
[111]	validation_0-mae:2323.45707
[112]	validation_0-mae:2317.66912
[113]	validation_0-mae:2316.99268
[114]	validation_0-mae:2313.87973
[115]	validation_0-mae:2312.32231
[116]	validation_0-mae:2309.46487
[117]	validation_0-mae:2305.62155
[118]	validation_0-mae:2302.35126
[119]	validation_0-mae:2296.87939
[120]	validation_0-mae:2296.19702
[121]	validation_0-mae:2292.98086
[122]	validation_0-mae:2291.25003
[123]	validation_0-mae:2287.42345
[124]	validation_0-mae:2287.52582
[125]	validation_0-mae:2286.17218
[126]	validation_0-mae:2285.27973
[127]	validation_0-mae:2283.67078
[128]	validation_0-mae:2279.97524
[129]	validation_0-mae:2280.83522
[130]	validation_0-mae:2277.85824
[131]	validation_0-mae:2276.85643
[132]	validation_0-mae:2277.66457
[133]	validation_0-mae:2277.80316
[134]	validation_0-mae:2275.11727
[135]	validation_0-mae:2271.60346
[136]	validation_0-mae:2270.79087
[137]	validation_0-mae:2272.25391
[138]	validation_0-mae:2270.73585
[139]	validation_0-mae:2268.76021
[140]	validation_0-mae:2266.65760
[141]	validation_0-mae:2263.86539
[142]	validation_0-mae:2264.14608
[143]	validation_0-mae:2261.60649
[144]	validation_0-mae:2257.75539
[145]	validation_0-mae:2258.76596
[146]	validation_0-mae:2255.86924
[147]	validation_0-mae:2256.17862
[148]	validation_0-mae:2255.73797
[149]	validation_0-mae:2253.27490
[150]	validation_0-mae:2255.03961
[151]	validation_0-mae:2253.16082
[152]	validation_0-mae:2252.48956
[153]	validation_0-mae:2251.24324
[154]	validation_0-mae:2251.85929
[155]	validation_0-mae:2250.02745
[156]	validation_0-mae:2249.05154
[157]	validation_0-mae:2248.24930
[158]	validation_0-mae:2249.11274
[159]	validation_0-mae:2245.82356
[160]	validation_0-mae:2243.66346
[161]	validation_0-mae:2240.24754
[162]	validation_0-mae:2238.23384
[163]	validation_0-mae:2235.12368
[164]	validation_0-mae:2234.76076
[165]	validation_0-mae:2233.79633
[166]	validation_0-mae:2231.27376
[167]	validation_0-mae:2231.42560
[168]	validation_0-mae:2231.97698
[169]	validation_0-mae:2229.63393
[170]	validation_0-mae:2229.20977
[171]	validation_0-mae:2226.72294
[172]	validation_0-mae:2226.97986
[173]	validation_0-mae:2226.95782
[174]	validation_0-mae:2229.70379
[175]	validation_0-mae:2230.28875
[176]	validation_0-mae:2230.74170
[177]	validation_0-mae:2230.36166
[178]	validation_0-mae:2230.58658
[179]	validation_0-mae:2228.43031
[180]	validation_0-mae:2228.71461
[181]	validation_0-mae:2228.62487
[182]	validation_0-mae:2227.94390
[183]	validation_0-mae:2226.70291
[0]	validation_0-mae:12361.63750
[1]	validation_0-mae:11579.25786
[2]	validation_0-mae:10854.89596
[3]	validation_0-mae:10182.55256
[4]	validation_0-mae:9594.85255
[5]	validation_0-mae:9083.29233
[6]	validation_0-mae:8635.70066
[7]	validation_0-mae:8233.17798
[8]	validation_0-mae:7854.17937
[9]	validation_0-mae:7494.44883
[10]	validation_0-mae:7146.96215
[11]	validation_0-mae:6831.89048
[12]	validation_0-mae:6558.46251
[13]	validation_0-mae:6288.07796
[14]	validation_0-mae:6024.89738
[15]	validation_0-mae:5797.70345
[16]	validation_0-mae:5554.75975
[17]	validation_0-mae:5385.16349
[18]	validation_0-mae:5185.76829
[19]	validation_0-mae:4992.49043
[20]	validation_0-mae:4823.95686
[21]	validation_0-mae:4686.20483
[22]	validation_0-mae:4548.29313
[23]	validation_0-mae:4426.81474
[24]	validation_0-mae:4299.66065
[25]	validation_0-mae:4193.07147
[26]	validation_0-mae:4082.91714
[27]	validation_0-mae:3993.55477
[28]	validation_0-mae:3900.42181
[29]	validation_0-mae:3800.19639
[30]	validation_0-mae:3720.75243
[31]	validation_0-mae:3642.58276
[32]	validation_0-mae:3577.22285

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[33]	validation_0-mae:3506.51611
[34]	validation_0-mae:3447.21328
[35]	validation_0-mae:3389.83369
[36]	validation_0-mae:3334.59675
[37]	validation_0-mae:3289.57883
[38]	validation_0-mae:3240.22176
[39]	validation_0-mae:3198.99788
[40]	validation_0-mae:3163.70327
[41]	validation_0-mae:3128.14292
[42]	validation_0-mae:3072.68416
[43]	validation_0-mae:3043.67500
[44]	validation_0-mae:3010.69119
[45]	validation_0-mae:2974.23258
[46]	validation_0-mae:2947.03849
[47]	validation_0-mae:2894.77444
[48]	validation_0-mae:2874.20105
[49]	validation_0-mae:2848.73420
[50]	validation_0-mae:2824.38124
[51]	validation_0-mae:2797.28996
[52]	validation_0-mae:2775.10479
[53]	validation_0-mae:2753.80451
[54]	validation_0-mae:2732.10024
[55]	validation_0-mae:2708.72488
[56]	validation_0-mae:2692.86077
[57]	validation_0-mae:2670.06281
[58]	validation_0-mae:2654.58414
[59]	validation_0-mae:2636.74399
[60]	validation_0-mae:2625.86120
[61]	validation_0-mae:2617.34759
[62]	validation_0-mae:2607.22778
[63]	validation_0-mae:2594.12985
[64]	validation_0-mae:2583.31012
[65]	validation_0-mae:2570.41417
[66]	validation_0-mae:2561.86499
[67]	validation_0-mae:2550.22382
[68]	validation_0-mae:2532.02566
[69]	validation_0-mae:2521.78418
[70]	validation_0-mae:2510.16757
[71]	validation_0-mae:2498.12554
[72]	validation_0-mae:2488.61195
[73]	validation_0-mae:2477.42937
[74]	validation_0-mae:2467.35971
[75]	validation_0-mae:2459.75373
[76]	validation_0-mae:2446.71069
[77]	validation_0-mae:2438.90761
[78]	validation_0-mae:2432.27683
[79]	validation_0-mae:2424.81571
[80]	validation_0-mae:2413.55465
[81]	validation_0-mae:2402.44214
[82]	validation_0-mae:2400.35522
[83]	validation_0-mae:2396.21813
[84]	validation_0-mae:2388.98066
[85]	validation_0-mae:2381.16494
[86]	validation_0-mae:2374.89981
[87]	validation_0-mae:2367.66208
[88]	validation_0-mae:2362.18988
[89]	validation_0-mae:2356.87547
[90]	validation_0-mae:2352.04844
[91]	validation_0-mae:2343.33002
[92]	validation_0-mae:2338.35918
[93]	validation_0-mae:2333.48389
[94]	validation_0-mae:2329.22006
[95]	validation_0-mae:2322.88494
[96]	validation_0-mae:2318.75784
[97]	validation_0-mae:2314.51359
[98]	validation_0-mae:2309.42319
[99]	validation_0-mae:2304.07761
[100]	validation_0-mae:2298.84205
[101]	validation_0-mae:2294.00427
[102]	validation_0-mae:2290.95259
[103]	validation_0-mae:2287.42835
[104]	validation_0-mae:2285.13178
[105]	validation_0-mae:2282.32489
[106]	validation_0-mae:2279.22400
[107]	validation_0-mae:2277.40617
[108]	validation_0-mae:2274.45222
[109]	validation_0-mae:2273.18807
[110]	validation_0-mae:2266.88610
[111]	validation_0-mae:2264.88145
[112]	validation_0-mae:2264.43981
[113]	validation_0-mae:2261.75601
[114]	validation_0-mae:2259.61277
[115]	validation_0-mae:2255.87276
[116]	validation_0-mae:2254.66675
[117]	validation_0-mae:2250.31839
[118]	validation_0-mae:2247.23816
[119]	validation_0-mae:2243.62020
[120]	validation_0-mae:2240.38453
[121]	validation_0-mae:2237.81182
[122]	validation_0-mae:2232.79047
[123]	validation_0-mae:2231.25100
[124]	validation_0-mae:2229.74943
[125]	validation_0-mae:2228.93002
[126]	validation_0-mae:2226.70411
[127]	validation_0-mae:2223.41036
[128]	validation_0-mae:2218.60231
[129]	validation_0-mae:2218.53615
[130]	validation_0-mae:2216.82851
[131]	validation_0-mae:2213.97139
[132]	validation_0-mae:2211.60424
[133]	validation_0-mae:2211.74756
[134]	validation_0-mae:2212.61831
[135]	validation_0-mae:2213.31380
[136]	validation_0-mae:2212.16553
[137]	validation_0-mae:2211.73285
[138]	validation_0-mae:2211.74579
[139]	validation_0-mae:2209.40981
[140]	validation_0-mae:2208.80123
[141]	validation_0-mae:2206.81552
[142]	validation_0-mae:2205.63527
[143]	validation_0-mae:2206.00790
[144]	validation_0-mae:2203.67589
[145]	validation_0-mae:2203.90232
[146]	validation_0-mae:2201.93932
[147]	validation_0-mae:2198.63567
[148]	validation_0-mae:2196.20659
[149]	validation_0-mae:2194.94750
[150]	validation_0-mae:2194.46003
[151]	validation_0-mae:2194.46319
[152]	validation_0-mae:2192.72862
[153]	validation_0-mae:2189.62571
[154]	validation_0-mae:2189.75562
[155]	validation_0-mae:2189.38790
[156]	validation_0-mae:2186.89160
[157]	validation_0-mae:2184.30018
[158]	validation_0-mae:2182.70931
[159]	validation_0-mae:2183.06161
[160]	validation_0-mae:2181.31295
[161]	validation_0-mae:2179.42807
[162]	validation_0-mae:2178.19451
[163]	validation_0-mae:2175.70553
[164]	validation_0-mae:2176.35804
[165]	validation_0-mae:2175.40968
[166]	validation_0-mae:2172.42127
[167]	validation_0-mae:2171.17564
[168]	validation_0-mae:2168.01490
[169]	validation_0-mae:2166.35595
[170]	validation_0-mae:2163.81670
[171]	validation_0-mae:2163.84261
[172]	validation_0-mae:2162.97333
[173]	validation_0-mae:2161.44595
[174]	validation_0-mae:2160.52146
[175]	validation_0-mae:2158.84992
[176]	validation_0-mae:2158.92663
[177]	validation_0-mae:2156.35080
[178]	validation_0-mae:2156.42438
[179]	validation_0-mae:2155.02364
[180]	validation_0-mae:2156.33932
[181]	validation_0-mae:2155.63594
[182]	validation_0-mae:2155.02224
[183]	validation_0-mae:2156.23463
[184]	validation_0-mae:2154.72763
[185]	validation_0-mae:2154.87386
[186]	validation_0-mae:2155.03131
[187]	validation_0-mae:2154.93060
[188]	validation_0-mae:2152.59323
[189]	validation_0-mae:2151.31560
[190]	validation_0-mae:2152.61932
[191]	validation_0-mae:2153.51886
[192]	validation_0-mae:2152.86995
[193]	validation_0-mae:2150.33744
[194]	validation_0-mae:2149.71278
[195]	validation_0-mae:2148.41259
[196]	validation_0-mae:2148.91533
[197]	validation_0-mae:2148.20894
[198]	validation_0-mae:2148.01725
[199]	validation_0-mae:2147.17920
[200]	validation_0-mae:2147.38472
[201]	validation_0-mae:2146.62408
[202]	validation_0-mae:2145.09206
[203]	validation_0-mae:2144.54405
[204]	validation_0-mae:2144.46299
[205]	validation_0-mae:2144.46748
[206]	validation_0-mae:2144.66893
[207]	validation_0-mae:2143.14623
[208]	validation_0-mae:2140.80914
[209]	validation_0-mae:2140.09077
[210]	validation_0-mae:2140.14184
[211]	validation_0-mae:2140.28914
[212]	validation_0-mae:2140.63086
[213]	validation_0-mae:2139.91406
[214]	validation_0-mae:2140.14117
[215]	validation_0-mae:2140.77283
[216]	validation_0-mae:2138.99861
[217]	validation_0-mae:2138.13700
[218]	validation_0-mae:2139.09743
[219]	validation_0-mae:2138.88295
[220]	validation_0-mae:2136.93939
[221]	validation_0-mae:2137.39285
[222]	validation_0-mae:2134.58168
[223]	validation_0-mae:2134.03054
[224]	validation_0-mae:2133.40560
[225]	validation_0-mae:2133.26166
[226]	validation_0-mae:2130.66348
[227]	validation_0-mae:2130.09540
[228]	validation_0-mae:2129.56955
[229]	validation_0-mae:2127.93273
[230]	validation_0-mae:2126.54665
[231]	validation_0-mae:2127.45394
[232]	validation_0-mae:2127.17115
[233]	validation_0-mae:2126.75573
[234]	validation_0-mae:2126.09561
[235]	validation_0-mae:2125.80196
[236]	validation_0-mae:2124.88064
[237]	validation_0-mae:2124.28761
[238]	validation_0-mae:2123.11432
[239]	validation_0-mae:2122.75900
[240]	validation_0-mae:2123.59134
[241]	validation_0-mae:2123.88363
[242]	validation_0-mae:2123.79557
[243]	validation_0-mae:2122.21894
[244]	validation_0-mae:2123.07392
[245]	validation_0-mae:2123.19847
[246]	validation_0-mae:2122.99844
[247]	validation_0-mae:2123.21566
[248]	validation_0-mae:2122.41796
[249]	validation_0-mae:2121.97802
[250]	validation_0-mae:2121.58980
[251]	validation_0-mae:2121.74516
[252]	validation_0-mae:2122.08357
[253]	validation_0-mae:2120.50801
[254]	validation_0-mae:2120.01607
[255]	validation_0-mae:2119.95628
[256]	validation_0-mae:2120.37520
[257]	validation_0-mae:2120.66323
[258]	validation_0-mae:2120.34675
[259]	validation_0-mae:2120.83059
[260]	validation_0-mae:2120.66735
[261]	validation_0-mae:2120.73833
[262]	validation_0-mae:2120.29037
[263]	validation_0-mae:2119.74539
[264]	validation_0-mae:2120.10732
[265]	validation_0-mae:2120.36890
[266]	validation_0-mae:2120.13024
[267]	validation_0-mae:2119.44412
[268]	validation_0-mae:2118.30649
[269]	validation_0-mae:2118.57589
[270]	validation_0-mae:2117.34375
[271]	validation_0-mae:2116.87823
[272]	validation_0-mae:2118.11371
[273]	validation_0-mae:2117.83235
[274]	validation_0-mae:2117.18311
[275]	validation_0-mae:2115.76337
[276]	validation_0-mae:2113.64187
[277]	validation_0-mae:2113.99701
[278]	validation_0-mae:2113.23279
[279]	validation_0-mae:2113.55096
[280]	validation_0-mae:2113.22591
[281]	validation_0-mae:2113.17612
[282]	validation_0-mae:2113.32620
[283]	validation_0-mae:2113.50246
[284]	validation_0-mae:2111.37371
[285]	validation_0-mae:2110.33471
[286]	validation_0-mae:2110.31073
[287]	validation_0-mae:2109.18671
[288]	validation_0-mae:2108.90874
[289]	validation_0-mae:2108.60517
[290]	validation_0-mae:2107.83756
[291]	validation_0-mae:2107.89926
[292]	validation_0-mae:2107.76722
[293]	validation_0-mae:2106.66002
[294]	validation_0-mae:2104.15431
[295]	validation_0-mae:2104.28928
[296]	validation_0-mae:2104.66189
[297]	validation_0-mae:2104.84884
[298]	validation_0-mae:2105.04951
[299]	validation_0-mae:2105.48806
[300]	validation_0-mae:2105.19462
[301]	validation_0-mae:2104.64356
[302]	validation_0-mae:2102.32805
[303]	validation_0-mae:2102.17604
[304]	validation_0-mae:2102.75235
[305]	validation_0-mae:2101.98778
[306]	validation_0-mae:2102.88401
[307]	validation_0-mae:2102.95240
[308]	validation_0-mae:2102.00029
[309]	validation_0-mae:2101.56332
[310]	validation_0-mae:2100.67591
[311]	validation_0-mae:2100.00892
[312]	validation_0-mae:2099.73544
[313]	validation_0-mae:2099.88158
[314]	validation_0-mae:2100.27716
[315]	validation_0-mae:2099.32010
[316]	validation_0-mae:2098.58046
[317]	validation_0-mae:2098.94563
[318]	validation_0-mae:2097.45830
[319]	validation_0-mae:2097.99431
[320]	validation_0-mae:2098.08526
[321]	validation_0-mae:2097.96905
[322]	validation_0-mae:2097.79204
[323]	validation_0-mae:2097.44719
[324]	validation_0-mae:2097.38074
[325]	validation_0-mae:2097.58273
[326]	validation_0-mae:2097.08093
[327]	validation_0-mae:2095.05596
[328]	validation_0-mae:2095.32737
[329]	validation_0-mae:2094.58207
[330]	validation_0-mae:2094.22808
[331]	validation_0-mae:2093.45196
[332]	validation_0-mae:2093.37749
[333]	validation_0-mae:2092.76797
[334]	validation_0-mae:2092.38728
[335]	validation_0-mae:2091.96765
[336]	validation_0-mae:2091.82139
[337]	validation_0-mae:2091.72857
[338]	validation_0-mae:2091.45393
[339]	validation_0-mae:2091.93927
[340]	validation_0-mae:2090.92297
[341]	validation_0-mae:2089.90892
[342]	validation_0-mae:2089.71397
[343]	validation_0-mae:2089.76239
[344]	validation_0-mae:2089.82830
[345]	validation_0-mae:2088.19440
[346]	validation_0-mae:2087.76440
[347]	validation_0-mae:2086.75988
[348]	validation_0-mae:2086.96020
[349]	validation_0-mae:2085.88953
[350]	validation_0-mae:2086.16778
[351]	validation_0-mae:2086.16013
[352]	validation_0-mae:2086.40188
[353]	validation_0-mae:2086.59949
[354]	validation_0-mae:2087.28573
[355]	validation_0-mae:2086.22776
[356]	validation_0-mae:2084.07082
[357]	validation_0-mae:2084.15631
[358]	validation_0-mae:2084.57728
[359]	validation_0-mae:2083.27636
[360]	validation_0-mae:2083.43335
[361]	validation_0-mae:2082.96339
[362]	validation_0-mae:2082.98773
[363]	validation_0-mae:2083.53844
[364]	validation_0-mae:2082.88386
[365]	validation_0-mae:2083.50142
[366]	validation_0-mae:2082.78450
[367]	validation_0-mae:2082.58909
[368]	validation_0-mae:2082.09721
[369]	validation_0-mae:2081.79514
[370]	validation_0-mae:2082.25486
[371]	validation_0-mae:2082.38658
[372]	validation_0-mae:2082.63746
[373]	validation_0-mae:2082.10045
[374]	validation_0-mae:2081.95107
[375]	validation_0-mae:2081.99840
[376]	validation_0-mae:2082.46219
[377]	validation_0-mae:2082.24712
[378]	validation_0-mae:2082.91781
[379]	validation_0-mae:2082.55906
[380]	validation_0-mae:2082.30941
[381]	validation_0-mae:2082.28628
[382]	validation_0-mae:2081.93258
[383]	validation_0-mae:2082.39043
[384]	validation_0-mae:2082.41995
[385]	validation_0-mae:2082.63730
[386]	validation_0-mae:2082.62783
[387]	validation_0-mae:2082.35021
[388]	validation_0-mae:2082.31406
[389]	validation_0-mae:2081.98416
[390]	validation_0-mae:2082.18108
[391]	validation_0-mae:2081.87357
[392]	validation_0-mae:2080.95144
[393]	validation_0-mae:2080.65224
[394]	validation_0-mae:2080.24779
[395]	validation_0-mae:2079.90745
[396]	validation_0-mae:2078.97160
[397]	validation_0-mae:2078.74063
[398]	validation_0-mae:2078.46111
[399]	validation_0-mae:2078.92319
[400]	validation_0-mae:2078.88666
[401]	validation_0-mae:2078.62797
[402]	validation_0-mae:2078.38754
[403]	validation_0-mae:2078.48200
[404]	validation_0-mae:2078.30978
[405]	validation_0-mae:2078.39117
[406]	validation_0-mae:2078.74386
[407]	validation_0-mae:2078.21085
[408]	validation_0-mae:2078.29293
[409]	validation_0-mae:2078.33017
[410]	validation_0-mae:2077.90517
[411]	validation_0-mae:2077.78128
[412]	validation_0-mae:2077.94577
[413]	validation_0-mae:2078.26151
[414]	validation_0-mae:2077.99421
[415]	validation_0-mae:2077.23490
[416]	validation_0-mae:2076.17286
[417]	validation_0-mae:2076.02863
[418]	validation_0-mae:2075.98928
[419]	validation_0-mae:2075.85013
[420]	validation_0-mae:2076.22750
[421]	validation_0-mae:2076.36264
[422]	validation_0-mae:2075.94611
[423]	validation_0-mae:2076.17988
[424]	validation_0-mae:2076.26443
[425]	validation_0-mae:2076.22484
[426]	validation_0-mae:2075.79493
[427]	validation_0-mae:2075.49958
[428]	validation_0-mae:2075.39874
[429]	validation_0-mae:2074.57577
[430]	validation_0-mae:2074.94425
[431]	validation_0-mae:2075.17956
[432]	validation_0-mae:2075.29825
[433]	validation_0-mae:2075.29507
[434]	validation_0-mae:2075.64761
[435]	validation_0-mae:2075.65770
[436]	validation_0-mae:2075.92275
[437]	validation_0-mae:2076.27697
[438]	validation_0-mae:2076.62439
[439]	validation_0-mae:2076.42491
[440]	validation_0-mae:2075.66653
[441]	validation_0-mae:2075.43380
[442]	validation_0-mae:2075.57382
[443]	validation_0-mae:2075.98313
[444]	validation_0-mae:2075.69011
[445]	validation_0-mae:2075.64300
[446]	validation_0-mae:2075.42142
[447]	validation_0-mae:2074.75289
[448]	validation_0-mae:2074.14019
[449]	validation_0-mae:2073.66518
[450]	validation_0-mae:2073.86191
[451]	validation_0-mae:2073.96315
[452]	validation_0-mae:2073.49936
[453]	validation_0-mae:2073.15533
[454]	validation_0-mae:2072.70814
[455]	validation_0-mae:2072.73955
[456]	validation_0-mae:2072.72555
[457]	validation_0-mae:2072.74348
[458]	validation_0-mae:2072.73215
[459]	validation_0-mae:2073.20530
[460]	validation_0-mae:2072.80585
[461]	validation_0-mae:2073.11114
[462]	validation_0-mae:2072.82065
[463]	validation_0-mae:2072.17597
[464]	validation_0-mae:2072.20100
[465]	validation_0-mae:2072.18787
[466]	validation_0-mae:2071.59066
[467]	validation_0-mae:2070.83600
[468]	validation_0-mae:2071.04619
[469]	validation_0-mae:2071.37153
[470]	validation_0-mae:2070.96571
[471]	validation_0-mae:2070.23108
[472]	validation_0-mae:2069.99491
[473]	validation_0-mae:2070.08935
[474]	validation_0-mae:2070.02279
[475]	validation_0-mae:2070.06229
[476]	validation_0-mae:2070.26828
[477]	validation_0-mae:2070.23991
[478]	validation_0-mae:2070.32207
[479]	validation_0-mae:2070.53246
[480]	validation_0-mae:2070.43722
[481]	validation_0-mae:2070.25189
[482]	validation_0-mae:2070.13616
[483]	validation_0-mae:2070.24744
[484]	validation_0-mae:2070.14320
[485]	validation_0-mae:2069.64911
[486]	validation_0-mae:2069.04275
[487]	validation_0-mae:2069.03762
[488]	validation_0-mae:2069.64505
[489]	validation_0-mae:2069.75032
[490]	validation_0-mae:2069.86814
[491]	validation_0-mae:2069.43732
[492]	validation_0-mae:2069.01797
[493]	validation_0-mae:2068.95893
[494]	validation_0-mae:2068.57840
[495]	validation_0-mae:2068.53359
[496]	validation_0-mae:2068.22395
[497]	validation_0-mae:2068.45368
[498]	validation_0-mae:2068.77549
[499]	validation_0-mae:2069.02934
[500]	validation_0-mae:2068.26278
[501]	validation_0-mae:2068.07200
[502]	validation_0-mae:2068.14239
[503]	validation_0-mae:2068.20622
[504]	validation_0-mae:2068.40104
[505]	validation_0-mae:2068.42887
[506]	validation_0-mae:2068.59489
[507]	validation_0-mae:2067.87592
[508]	validation_0-mae:2067.92411
[509]	validation_0-mae:2067.86852
[510]	validation_0-mae:2067.76629
[511]	validation_0-mae:2067.71388
[512]	validation_0-mae:2067.85450
[513]	validation_0-mae:2067.54886
[514]	validation_0-mae:2067.92320
[515]	validation_0-mae:2068.13470
[516]	validation_0-mae:2068.35302
[517]	validation_0-mae:2067.70258
[518]	validation_0-mae:2067.93387
[519]	validation_0-mae:2067.95960
[520]	validation_0-mae:2068.09767
[521]	validation_0-mae:2068.21212
[522]	validation_0-mae:2068.23240
[523]	validation_0-mae:2068.06487
[524]	validation_0-mae:2067.66371
[525]	validation_0-mae:2067.68116
[526]	validation_0-mae:2067.64924
[527]	validation_0-mae:2067.06395
[528]	validation_0-mae:2067.03115
[529]	validation_0-mae:2067.08377
[530]	validation_0-mae:2067.46882
[531]	validation_0-mae:2067.32793
[532]	validation_0-mae:2067.30819
[533]	validation_0-mae:2067.18088
[534]	validation_0-mae:2067.27231
[535]	validation_0-mae:2066.98295
[536]	validation_0-mae:2067.22672
[537]	validation_0-mae:2067.22738
[538]	validation_0-mae:2067.39456
[539]	validation_0-mae:2067.39490
[540]	validation_0-mae:2067.49755
[541]	validation_0-mae:2067.56852
[542]	validation_0-mae:2067.54242
[543]	validation_0-mae:2067.36464
[544]	validation_0-mae:2067.21041
[545]	validation_0-mae:2067.50474
[546]	validation_0-mae:2067.46984
[547]	validation_0-mae:2067.55234
[548]	validation_0-mae:2067.41393
[549]	validation_0-mae:2067.42542
[550]	validation_0-mae:2067.84457
[551]	validation_0-mae:2067.79568
[552]	validation_0-mae:2067.83856
[553]	validation_0-mae:2067.96047
[554]	validation_0-mae:2067.64797
[555]	validation_0-mae:2067.61517
[556]	validation_0-mae:2067.35108
[557]	validation_0-mae:2067.43719
[558]	validation_0-mae:2067.71528
[559]	validation_0-mae:2067.94808
[560]	validation_0-mae:2067.86263
[561]	validation_0-mae:2067.55049
[562]	validation_0-mae:2067.48013
[563]	validation_0-mae:2067.35982
[564]	validation_0-mae:2067.87835
[565]	validation_0-mae:2067.92538
[566]	validation_0-mae:2068.12044
[567]	validation_0-mae:2067.76465
[568]	validation_0-mae:2067.63577
[569]	validation_0-mae:2067.43514
[570]	validation_0-mae:2067.08526
[571]	validation_0-mae:2067.02215
[572]	validation_0-mae:2067.17549
[573]	validation_0-mae:2067.59434
[574]	validation_0-mae:2068.03932
[575]	validation_0-mae:2068.16592
[576]	validation_0-mae:2068.23819
[577]	validation_0-mae:2068.33266
[578]	validation_0-mae:2068.33313
[579]	validation_0-mae:2068.28317
[580]	validation_0-mae:2068.21404
[581]	validation_0-mae:2068.19582
[582]	validation_0-mae:2068.26972
[583]	validation_0-mae:2068.61553
[584]	validation_0-mae:2068.65508
[585]	validation_0-mae:2068.34712
[586]	validation_0-mae:2068.59349
[587]	validation_0-mae:2068.38597
[588]	validation_0-mae:2068.75558
[589]	validation_0-mae:2068.96082
[590]	validation_0-mae:2069.17644
[591]	validation_0-mae:2069.33349
[592]	validation_0-mae:2069.55048
[593]	validation_0-mae:2069.64196
[594]	validation_0-mae:2069.68069
[595]	validation_0-mae:2069.85907
[596]	validation_0-mae:2069.21864
[597]	validation_0-mae:2068.90944
[598]	validation_0-mae:2068.78888
[599]	validation_0-mae:2068.66742
[600]	validation_0-mae:2068.73354
[601]	validation_0-mae:2068.77853
[602]	validation_0-mae:2068.92745
[603]	validation_0-mae:2068.90538
[604]	validation_0-mae:2068.12902
[605]	validation_0-mae:2068.27877
[606]	validation_0-mae:2068.22721
[607]	validation_0-mae:2068.34292
[608]	validation_0-mae:2068.03486
[609]	validation_0-mae:2067.98948
[610]	validation_0-mae:2067.99701
[611]	validation_0-mae:2068.00898
[612]	validation_0-mae:2068.05727
[613]	validation_0-mae:2068.12683
[614]	validation_0-mae:2068.31374
[615]	validation_0-mae:2068.21849
[616]	validation_0-mae:2068.28947
[617]	validation_0-mae:2068.26420
[618]	validation_0-mae:2068.23968
[619]	validation_0-mae:2068.20064
[620]	validation_0-mae:2068.13244
[621]	validation_0-mae:2067.66779
[622]	validation_0-mae:2067.81639

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[39]	validation_0-mae:3221.98419
[40]	validation_0-mae:3181.45999
[41]	validation_0-mae:3144.79784
[42]	validation_0-mae:3092.54163
[43]	validation_0-mae:3061.81503
[44]	validation_0-mae:3018.90572
[45]	validation_0-mae:2984.87873
[46]	validation_0-mae:2957.98112
[47]	validation_0-mae:2937.01161
[48]	validation_0-mae:2912.51370
[49]	validation_0-mae:2880.47431
[50]	validation_0-mae:2862.25527
[51]	validation_0-mae:2836.07809
[52]	validation_0-mae:2820.57180
[53]	validation_0-mae:2804.90122
[54]	validation_0-mae:2783.57163
[55]	validation_0-mae:2753.22962
[56]	validation_0-mae:2742.57956
[57]	validation_0-mae:2729.11396
[58]	validation_0-mae:2718.18109
[59]	validation_0-mae:2694.49735
[60]	validation_0-mae:2680.05752
[61]	validation_0-mae:2666.60859
[62]	validation_0-mae:2656.40103
[63]	validation_0-mae:2642.79211
[64]	validation_0-mae:2636.41087
[65]	validation_0-mae:2615.28643
[66]	validation_0-mae:2593.47128
[67]	validation_0-mae:2584.10502
[68]	validation_0-mae:2574.67885
[69]	validation_0-mae:2567.39024
[70]	validation_0-mae:2562.83962
[71]	validation_0-mae:2550.63222
[72]	validation_0-mae:2544.53572
[73]	validation_0-mae:2533.37890
[74]	validation_0-mae:2521.06963
[75]	validation_0-mae:2516.04223
[76]	validation_0-mae:2508.78303
[77]	validation_0-mae:2496.16765
[78]	validation_0-mae:2486.68438
[79]	validation_0-mae:2478.60155
[80]	validation_0-mae:2471.76688
[81]	validation_0-mae:2462.71244
[82]	validation_0-mae:2454.79410
[83]	validation_0-mae:2447.93978
[84]	validation_0-mae:2443.89644
[85]	validation_0-mae:2430.81543
[86]	validation_0-mae:2429.04136
[87]	validation_0-mae:2422.31274
[88]	validation_0-mae:2414.85940
[89]	validation_0-mae:2407.62950
[90]	validation_0-mae:2402.42051
[91]	validation_0-mae:2398.49967
[92]	validation_0-mae:2394.94225
[93]	validation_0-mae:2391.25063
[94]	validation_0-mae:2385.49936
[95]	validation_0-mae:2380.65333
[96]	validation_0-mae:2377.51528
[97]	validation_0-mae:2365.59229
[98]	validation_0-mae:2360.26097
[99]	validation_0-mae:2354.77795
[100]	validation_0-mae:2350.52186
[101]	validation_0-mae:2340.55850
[102]	validation_0-mae:2334.21955
[103]	validation_0-mae:2330.80481
[104]	validation_0-mae:2327.31087
[105]	validation_0-mae:2324.51937
[106]	validation_0-mae:2319.89234
[107]	validation_0-mae:2313.01786
[108]	validation_0-mae:2307.50379
[109]	validation_0-mae:2304.27262
[110]	validation_0-mae:2298.56002
[111]	validation_0-mae:2298.03037
[112]	validation_0-mae:2298.81214
[113]	validation_0-mae:2295.91909
[114]	validation_0-mae:2292.53760
[115]	validation_0-mae:2289.24048
[116]	validation_0-mae:2287.26898
[117]	validation_0-mae:2287.81087
[118]	validation_0-mae:2284.07332
[119]	validation_0-mae:2279.61512
[120]	validation_0-mae:2276.54736
[121]	validation_0-mae:2275.55738
[122]	validation_0-mae:2273.48636
[123]	validation_0-mae:2267.72106
[124]	validation_0-mae:2266.74806
[125]	validation_0-mae:2264.07786
[126]	validation_0-mae:2264.43738
[127]	validation_0-mae:2261.19916
[128]	validation_0-mae:2258.30523
[129]	validation_0-mae:2255.69693
[130]	validation_0-mae:2251.50636
[131]	validation_0-mae:2247.33799
[132]	validation_0-mae:2242.28089
[133]	validation_0-mae:2241.24880
[134]	validation_0-mae:2240.36300
[135]	validation_0-mae:2241.29230
[136]	validation_0-mae:2235.97416
[137]	validation_0-mae:2234.99057
[138]	validation_0-mae:2234.12710
[139]	validation_0-mae:2232.71901
[140]	validation_0-mae:2231.61252
[141]	validation_0-mae:2229.98901
[142]	validation_0-mae:2228.40630
[143]	validation_0-mae:2227.15544
[144]	validation_0-mae:2225.58801
[145]	validation_0-mae:2222.10222
[146]	validation_0-mae:2220.54764
[147]	validation_0-mae:2219.01456
[148]	validation_0-mae:2217.07745
[149]	validation_0-mae:2214.26796
[150]	validation_0-mae:2214.04076
[151]	validation_0-mae:2213.57457
[152]	validation_0-mae:2210.75516
[153]	validation_0-mae:2210.27030
[154]	validation_0-mae:2209.28249
[155]	validation_0-mae:2205.82737
[156]	validation_0-mae:2204.91032
[157]	validation_0-mae:2206.14166
[158]	validation_0-mae:2202.14343
[159]	validation_0-mae:2202.05269
[160]	validation_0-mae:2202.61278
[161]	validation_0-mae:2201.55191
[162]	validation_0-mae:2200.61111
[163]	validation_0-mae:2200.46507
[164]	validation_0-mae:2198.84944
[165]	validation_0-mae:2197.45004
[166]	validation_0-mae:2197.10105
[167]	validation_0-mae:2194.83602
[168]	validation_0-mae:2195.62839
[169]	validation_0-mae:2194.60962
[170]	validation_0-mae:2195.55348
[171]	validation_0-mae:2196.44524
[172]	validation_0-mae:2194.63007
[173]	validation_0-mae:2193.81299
[174]	validation_0-mae:2193.39332
[175]	validation_0-mae:2193.20489
[176]	validation_0-mae:2191.66181
[177]	validation_0-mae:2191.42630
[178]	validation_0-mae:2188.40898
[179]	validation_0-mae:2187.52810
[180]	validation_0-mae:2187.64260
[181]	validation_0-mae:2186.72659
[182]	validation_0-mae:2186.05624
[183]	validation_0-mae:2186.21180
[184]	validation_0-mae:2185.82431
[185]	validation_0-mae:2185.86098
[186]	validation_0-mae:2184.88008
[187]	validation_0-mae:2184.73967
[188]	validation_0-mae:2185.49873
[189]	validation_0-mae:2185.69105
[190]	validation_0-mae:2185.56524
[191]	validation_0-mae:2184.94981
[192]	validation_0-mae:2185.27467
[193]	validation_0-mae:2185.13902
[194]	validation_0-mae:2184.78412
[195]	validation_0-mae:2185.16929
[196]	validation_0-mae:2184.92062
[197]	validation_0-mae:2183.23950
[198]	validation_0-mae:2183.08617
[199]	validation_0-mae:2183.54526
[200]	validation_0-mae:2182.78061
[201]	validation_0-mae:2183.00083
[202]	validation_0-mae:2182.68018
[203]	validation_0-mae:2182.54069
[204]	validation_0-mae:2183.85466
[205]	validation_0-mae:2183.69714
[206]	validation_0-mae:2182.92198
[207]	validation_0-mae:2179.94837
[208]	validation_0-mae:2177.26623
[209]	validation_0-mae:2176.10529
[210]	validation_0-mae:2177.04002
[211]	validation_0-mae:2176.76175
[212]	validation_0-mae:2175.57807
[213]	validation_0-mae:2175.14223
[214]	validation_0-mae:2173.52902
[215]	validation_0-mae:2173.42573
[216]	validation_0-mae:2172.67598
[217]	validation_0-mae:2172.77261
[218]	validation_0-mae:2172.77457
[219]	validation_0-mae:2173.16097
[220]	validation_0-mae:2173.21858
[221]	validation_0-mae:2172.56184
[222]	validation_0-mae:2171.98381
[223]	validation_0-mae:2171.60504
[224]	validation_0-mae:2171.28747
[225]	validation_0-mae:2171.54547
[226]	validation_0-mae:2172.01292
[227]	validation_0-mae:2172.41441
[228]	validation_0-mae:2172.74441
[229]	validation_0-mae:2172.32515
[230]	validation_0-mae:2171.87201
[231]	validation_0-mae:2171.96630
[232]	validation_0-mae:2172.47647
[233]	validation_0-mae:2171.58710
[234]	validation_0-mae:2172.45971
[235]	validation_0-mae:2172.62346
[236]	validation_0-mae:2172.80286
[237]	validation_0-mae:2172.88029
[238]	validation_0-mae:2173.34506
[239]	validation_0-mae:2172.44034
[240]	validation_0-mae:2172.54668
[241]	validation_0-mae:2171.87471
[242]	validation_0-mae:2169.79056
[243]	validation_0-mae:2171.65669
[244]	validation_0-mae:2171.12679
[245]	validation_0-mae:2169.56952
[246]	validation_0-mae:2168.94352
[247]	validation_0-mae:2169.46047
[248]	validation_0-mae:2169.72059
[249]	validation_0-mae:2169.04208
[250]	validation_0-mae:2168.79561
[251]	validation_0-mae:2167.08486
[252]	validation_0-mae:2167.17400
[253]	validation_0-mae:2166.19418
[254]	validation_0-mae:2166.10033
[255]	validation_0-mae:2166.23229
[256]	validation_0-mae:2165.98543
[257]	validation_0-mae:2165.70756
[258]	validation_0-mae:2166.62425
[259]	validation_0-mae:2167.94835
[260]	validation_0-mae:2167.28633
[261]	validation_0-mae:2165.66792
[262]	validation_0-mae:2165.33432
[263]	validation_0-mae:2164.24164
[264]	validation_0-mae:2165.01276
[265]	validation_0-mae:2164.32094
[266]	validation_0-mae:2164.81960
[267]	validation_0-mae:2164.93732
[268]	validation_0-mae:2164.58240
[269]	validation_0-mae:2162.07997
[270]	validation_0-mae:2162.50750
[271]	validation_0-mae:2162.25671
[272]	validation_0-mae:2162.04003
[273]	validation_0-mae:2160.06289
[274]	validation_0-mae:2159.75130
[275]	validation_0-mae:2160.28235
[276]	validation_0-mae:2160.56177
[277]	validation_0-mae:2160.51411
[278]	validation_0-mae:2160.09678
[279]	validation_0-mae:2160.33855
[280]	validation_0-mae:2159.84204
[281]	validation_0-mae:2159.55607
[282]	validation_0-mae:2159.96785
[283]	validation_0-mae:2159.82193
[284]	validation_0-mae:2158.83004
[285]	validation_0-mae:2159.16928
[286]	validation_0-mae:2159.32598
[287]	validation_0-mae:2159.23468
[288]	validation_0-mae:2159.15416
[289]	validation_0-mae:2159.12471
[290]	validation_0-mae:2159.34908
[291]	validation_0-mae:2159.42455
[292]	validation_0-mae:2159.85980
[293]	validation_0-mae:2158.75297
[294]	validation_0-mae:2158.61123
[295]	validation_0-mae:2156.89569
[296]	validation_0-mae:2156.67398
[297]	validation_0-mae:2154.07339
[298]	validation_0-mae:2154.04905
[299]	validation_0-mae:2153.79488
[300]	validation_0-mae:2153.41801
[301]	validation_0-mae:2153.37390
[302]	validation_0-mae:2153.60438
[303]	validation_0-mae:2153.72434
[304]	validation_0-mae:2153.05381
[305]	validation_0-mae:2154.13179
[306]	validation_0-mae:2153.17889
[307]	validation_0-mae:2153.64449
[308]	validation_0-mae:2153.33797
[309]	validation_0-mae:2153.89313
[310]	validation_0-mae:2152.83757
[311]	validation_0-mae:2153.02549
[312]	validation_0-mae:2152.91369
[313]	validation_0-mae:2151.92228
[314]	validation_0-mae:2151.17748
[315]	validation_0-mae:2151.13548
[316]	validation_0-mae:2151.54466
[317]	validation_0-mae:2151.07425
[318]	validation_0-mae:2150.96467
[319]	validation_0-mae:2151.61878
[320]	validation_0-mae:2150.38768
[321]	validation_0-mae:2150.31190
[322]	validation_0-mae:2150.37547
[323]	validation_0-mae:2149.74918
[324]	validation_0-mae:2149.77873
[325]	validation_0-mae:2148.93873
[326]	validation_0-mae:2147.54386
[327]	validation_0-mae:2147.77443
[328]	validation_0-mae:2147.88010
[329]	validation_0-mae:2147.35215
[330]	validation_0-mae:2147.20803
[331]	validation_0-mae:2146.74196
[332]	validation_0-mae:2145.87240
[333]	validation_0-mae:2146.79315
[334]	validation_0-mae:2146.56979
[335]	validation_0-mae:2146.74811
[336]	validation_0-mae:2146.41478
[337]	validation_0-mae:2145.60855
[338]	validation_0-mae:2145.63647
[339]	validation_0-mae:2145.06672
[340]	validation_0-mae:2145.07277
[341]	validation_0-mae:2145.51694
[342]	validation_0-mae:2143.62947
[343]	validation_0-mae:2143.93745
[344]	validation_0-mae:2143.55208
[345]	validation_0-mae:2142.97651
[346]	validation_0-mae:2142.90131
[347]	validation_0-mae:2142.69883
[348]	validation_0-mae:2142.44166
[349]	validation_0-mae:2142.66100
[350]	validation_0-mae:2142.19068
[351]	validation_0-mae:2142.48295
[352]	validation_0-mae:2142.72293
[353]	validation_0-mae:2142.35512
[354]	validation_0-mae:2142.76119
[355]	validation_0-mae:2143.85429
[356]	validation_0-mae:2143.39533
[357]	validation_0-mae:2143.58833
[358]	validation_0-mae:2143.24055
[359]	validation_0-mae:2143.67251
[360]	validation_0-mae:2143.13268
[361]	validation_0-mae:2143.61521
[362]	validation_0-mae:2143.21913
[363]	validation_0-mae:2142.91631
[364]	validation_0-mae:2142.70149
[365]	validation_0-mae:2141.58165
[366]	validation_0-mae:2141.26588
[367]	validation_0-mae:2141.23156
[368]	validation_0-mae:2141.30124
[369]	validation_0-mae:2141.10345
[370]	validation_0-mae:2141.47740
[371]	validation_0-mae:2141.47071
[372]	validation_0-mae:2141.45738
[373]	validation_0-mae:2141.09784
[374]	validation_0-mae:2140.12627
[375]	validation_0-mae:2140.08717
[376]	validation_0-mae:2139.95984
[377]	validation_0-mae:2140.13596
[378]	validation_0-mae:2139.64537
[379]	validation_0-mae:2138.06011
[380]	validation_0-mae:2136.81343
[381]	validation_0-mae:2137.14463
[382]	validation_0-mae:2136.28543
[383]	validation_0-mae:2135.77667
[384]	validation_0-mae:2135.86093
[385]	validation_0-mae:2135.77968
[386]	validation_0-mae:2134.86647
[387]	validation_0-mae:2134.01114
[388]	validation_0-mae:2132.77543
[389]	validation_0-mae:2132.27280
[390]	validation_0-mae:2131.54215
[391]	validation_0-mae:2131.78072
[392]	validation_0-mae:2131.31956
[393]	validation_0-mae:2131.62033
[394]	validation_0-mae:2132.01600
[395]	validation_0-mae:2131.45846
[396]	validation_0-mae:2130.99000
[397]	validation_0-mae:2130.49600
[398]	validation_0-mae:2130.22281
[399]	validation_0-mae:2130.28428
[400]	validation_0-mae:2130.20909
[401]	validation_0-mae:2129.22307
[402]	validation_0-mae:2128.78522
[403]	validation_0-mae:2128.51573
[404]	validation_0-mae:2127.90524
[405]	validation_0-mae:2127.78896
[406]	validation_0-mae:2126.98007
[407]	validation_0-mae:2127.32184
[408]	validation_0-mae:2127.42113
[409]	validation_0-mae:2127.58828
[410]	validation_0-mae:2127.01347
[411]	validation_0-mae:2126.99289
[412]	validation_0-mae:2127.53740
[413]	validation_0-mae:2127.89162
[414]	validation_0-mae:2128.06564
[415]	validation_0-mae:2128.26699
[416]	validation_0-mae:2128.15182
[417]	validation_0-mae:2128.09255
[418]	validation_0-mae:2127.68914
[419]	validation_0-mae:2127.70864
[420]	validation_0-mae:2128.33558
[421]	validation_0-mae:2128.51604
[422]	validation_0-mae:2128.40643
[423]	validation_0-mae:2128.54334
[424]	validation_0-mae:2128.56514
[425]	validation_0-mae:2128.32591
[426]	validation_0-mae:2128.58765
[427]	validation_0-mae:2128.21227
[428]	validation_0-mae:2128.21973
[429]	validation_0-mae:2127.95143
[430]	validation_0-mae:2127.31191
[431]	validation_0-mae:2127.38719
[432]	validation_0-mae:2127.54931
[433]	validation_0-mae:2127.20016
[434]	validation_0-mae:2127.34156
[435]	validation_0-mae:2127.39061
[436]	validation_0-mae:2127.45430
[437]	validation_0-mae:2126.37768
[438]	validation_0-mae:2126.23158
[439]	validation_0-mae:2126.21431
[440]	validation_0-mae:2124.76105
[441]	validation_0-mae:2124.46540
[442]	validation_0-mae:2124.11180
[443]	validation_0-mae:2124.36616
[444]	validation_0-mae:2124.50260
[445]	validation_0-mae:2124.12884
[446]	validation_0-mae:2124.23411
[447]	validation_0-mae:2124.31935
[448]	validation_0-mae:2124.29772
[449]	validation_0-mae:2123.81305
[450]	validation_0-mae:2124.05616
[451]	validation_0-mae:2123.31118
[452]	validation_0-mae:2122.09410
[453]	validation_0-mae:2122.29661
[454]	validation_0-mae:2121.56110
[455]	validation_0-mae:2121.50882
[456]	validation_0-mae:2121.14074
[457]	validation_0-mae:2121.09827
[458]	validation_0-mae:2121.93179
[459]	validation_0-mae:2122.17234
[460]	validation_0-mae:2122.11935
[461]	validation_0-mae:2122.43959
[462]	validation_0-mae:2122.56694
[463]	validation_0-mae:2122.54570
[464]	validation_0-mae:2122.26084
[465]	validation_0-mae:2121.87501
[466]	validation_0-mae:2122.20244
[467]	validation_0-mae:2122.68448
[468]	validation_0-mae:2122.48446
[469]	validation_0-mae:2122.44735
[470]	validation_0-mae:2122.47228
[471]	validation_0-mae:2121.87252
[472]	validation_0-mae:2121.85318
[473]	validation_0-mae:2121.49630
[474]	validation_0-mae:2121.83279
[475]	validation_0-mae:2122.05489
[476]	validation_0-mae:2121.62229
[477]	validation_0-mae:2121.28520
[478]	validation_0-mae:2121.11159
[479]	validation_0-mae:2121.31742
[480]	validation_0-mae:2120.90274
[481]	validation_0-mae:2121.10984
[482]	validation_0-mae:2121.18049
[483]	validation_0-mae:2121.06829
[484]	validation_0-mae:2121.08450
[485]	validation_0-mae:2120.63519
[486]	validation_0-mae:2121.55126
[487]	validation_0-mae:2121.95345
[488]	validation_0-mae:2122.21643
[489]	validation_0-mae:2122.18298
[490]	validation_0-mae:2123.02826
[491]	validation_0-mae:2123.25640
[492]	validation_0-mae:2123.27311
[493]	validation_0-mae:2122.81783
[494]	validation_0-mae:2122.46341
[495]	validation_0-mae:2121.64687
[496]	validation_0-mae:2121.73770
[497]	validation_0-mae:2121.69347
[498]	validation_0-mae:2121.50013
[499]	validation_0-mae:2121.66087
[500]	validation_0-mae:2121.67176
[501]	validation_0-mae:2120.88512
[502]	validation_0-mae:2120.45419
[503]	validation_0-mae:2120.63683
[504]	validation_0-mae:2120.07372
[505]	validation_0-mae:2120.70666
[506]	validation_0-mae:2121.17050
[507]	validation_0-mae:2120.92619
[508]	validation_0-mae:2120.77904
[509]	validation_0-mae:2121.11764
[510]	validation_0-mae:2121.61412
[511]	validation_0-mae:2121.69577
[512]	validation_0-mae:2122.48668
[513]	validation_0-mae:2122.90331
[514]	validation_0-mae:2122.53577
[515]	validation_0-mae:2122.35893
[516]	validation_0-mae:2122.38028
[517]	validation_0-mae:2122.87398
[518]	validation_0-mae:2123.04430
[519]	validation_0-mae:2123.20678
[520]	validation_0-mae:2123.16133
[521]	validation_0-mae:2123.46799
[0]	validation_0-mae:12406.90772
[1]	validation_0-mae:11636.77284
[2]	validation_0-mae:10960.41851
[3]	validation_0-mae:10356.76705
[4]	validation_0-mae:9809.98711
[5]	validation_0-mae:9332.85013
[6]	validation_0-mae:8927.58226
[7]	validation_0-mae:8554.20788
[8]	validation_0-mae:8242.06570
[9]	validation_0-mae:7942.78909
[10]	validation_0-mae:7687.54973

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[0]	validation_0-mae:12447.11442
[1]	validation_0-mae:11704.85046
[2]	validation_0-mae:11037.44936
[3]	validation_0-mae:10437.07241
[4]	validation_0-mae:9908.34261
[5]	validation_0-mae:9426.36803
[6]	validation_0-mae:9005.84596
[7]	validation_0-mae:8594.51887
[8]	validation_0-mae:8212.38334
[9]	validation_0-mae:7891.16604
[10]	validation_0-mae:7582.41041
[11]	validation_0-mae:7289.13779
[12]	validation_0-mae:7031.98478
[13]	validation_0-mae:6776.30486
[14]	validation_0-mae:6511.01790
[15]	validation_0-mae:6237.33660
[16]	validation_0-mae:6011.15101
[17]	validation_0-mae:5811.47236
[18]	validation_0-mae:5607.89500
[19]	validation_0-mae:5433.95237
[20]	validation_0-mae:5255.92884
[21]	validation_0-mae:5096.80715
[22]	validation_0-mae:4927.79731
[23]	validation_0-mae:4777.92105
[24]	validation_0-mae:4647.37428
[25]	validation_0-mae:4532.77085
[26]	validation_0-mae:4424.59636
[27]	validation_0-mae:4325.28035
[28]	validation_0-mae:4228.66063
[29]	validation_0-mae:4124.98481
[30]	validation_0-mae:4052.37829
[31]	validation_0-mae:3954.02577
[32]	validation_0-mae:3877.90142
[33]	validation_0-mae:3798.50784
[34]	validation_0-mae:3738.05700
[35]	validation_0-mae:3670.34307
[36]	validation_0-mae:3605.75595
[37]	validation_0-mae:3548.46336
[38]	validation_0-mae:3497.83226
[39]	validation_0-mae:3444.20774
[40]	validation_0-mae:3396.48955
[41]	validation_0-mae:3354.72374
[42]	validation_0-mae:3316.76582
[43]	validation_0-mae:3278.68903
[44]	validation_0-mae:3244.40072
[45]	validation_0-mae:3207.92105
[46]	validation_0-mae:3178.78776
[47]	validation_0-mae:3154.79989
[48]	validation_0-mae:3123.13534
[49]	validation_0-mae:3095.37747
[50]	validation_0-mae:3041.32230
[51]	validation_0-mae:3005.24951
[52]	validation_0-mae:2981.17788
[53]	validation_0-mae:2963.53263
[54]	validation_0-mae:2938.61188
[55]	validation_0-mae:2907.49331
[56]	validation_0-mae:2877.29502
[57]	validation_0-mae:2849.08606
[58]	validation_0-mae:2829.87347
[59]	validation_0-mae:2809.29587
[60]	validation_0-mae:2794.32294
[61]	validation_0-mae:2763.21001
[62]	validation_0-mae:2745.01884
[63]	validation_0-mae:2735.40053
[64]	validation_0-mae:2710.12153
[65]	validation_0-mae:2692.90004
[66]	validation_0-mae:2683.10518
[67]	validation_0-mae:2677.57463
[68]	validation_0-mae:2660.39298
[69]	validation_0-mae:2654.11700
[70]	validation_0-mae:2642.84409
[71]	validation_0-mae:2633.22500
[72]	validation_0-mae:2624.25948
[73]	validation_0-mae:2610.78821
[74]	validation_0-mae:2602.17402
[75]	validation_0-mae:2595.83558
[76]	validation_0-mae:2585.41487
[77]	validation_0-mae:2565.92160
[78]	validation_0-mae:2549.53341
[79]	validation_0-mae:2538.29133
[80]	validation_0-mae:2528.79507
[81]	validation_0-mae:2516.70055
[82]	validation_0-mae:2506.87754
[83]	validation_0-mae:2500.75294
[84]	validation_0-mae:2487.67090
[85]	validation_0-mae:2476.87099
[86]	validation_0-mae:2472.58298
[87]	validation_0-mae:2463.31591
[88]	validation_0-mae:2451.50512
[89]	validation_0-mae:2450.33560
[90]	validation_0-mae:2444.01362
[91]	validation_0-mae:2433.18626
[92]	validation_0-mae:2434.27518
[93]	validation_0-mae:2428.43148
[94]	validation_0-mae:2428.82650
[95]	validation_0-mae:2422.41219
[96]	validation_0-mae:2411.44524
[97]	validation_0-mae:2403.79268
[98]	validation_0-mae:2397.64905
[99]	validation_0-mae:2395.59989
[100]	validation_0-mae:2389.46827
[101]	validation_0-mae:2384.71619
[102]	validation_0-mae:2382.23857
[103]	validation_0-mae:2379.85835
[104]	validation_0-mae:2373.10644
[105]	validation_0-mae:2366.56183
[106]	validation_0-mae:2361.06502
[107]	validation_0-mae:2354.61308
[108]	validation_0-mae:2349.34946
[109]	validation_0-mae:2345.65685
[110]	validation_0-mae:2344.12884
[111]	validation_0-mae:2334.30115
[112]	validation_0-mae:2330.40870
[113]	validation_0-mae:2328.26328
[114]	validation_0-mae:2324.20523
[115]	validation_0-mae:2318.65242
[116]	validation_0-mae:2315.67689
[117]	validation_0-mae:2311.53625
[118]	validation_0-mae:2307.63743
[119]	validation_0-mae:2305.64181
[120]	validation_0-mae:2301.70689
[121]	validation_0-mae:2297.66341
[122]	validation_0-mae:2293.23015
[123]	validation_0-mae:2290.52243
[124]	validation_0-mae:2291.70362
[125]	validation_0-mae:2288.37010
[126]	validation_0-mae:2286.55846
[127]	validation_0-mae:2281.25786
[128]	validation_0-mae:2277.28254
[129]	validation_0-mae:2275.50705
[130]	validation_0-mae:2275.30342
[131]	validation_0-mae:2273.51228
[132]	validation_0-mae:2272.55713
[133]	validation_0-mae:2269.16878
[134]	validation_0-mae:2266.55520
[135]	validation_0-mae:2264.31708
[136]	validation_0-mae:2261.48073
[137]	validation_0-mae:2262.67502
[138]	validation_0-mae:2260.59145
[139]	validation_0-mae:2259.40945
[140]	validation_0-mae:2255.69636
[141]	validation_0-mae:2251.38382
[142]	validation_0-mae:2249.15700
[143]	validation_0-mae:2246.25280
[144]	validation_0-mae:2244.19724
[145]	validation_0-mae:2240.05658
[146]	validation_0-mae:2239.13471
[147]	validation_0-mae:2237.49353
[148]	validation_0-mae:2233.25439
[149]	validation_0-mae:2229.81731
[150]	validation_0-mae:2227.94346
[151]	validation_0-mae:2223.71163
[152]	validation_0-mae:2221.17449
[153]	validation_0-mae:2217.23580
[154]	validation_0-mae:2213.39266
[155]	validation_0-mae:2210.20436
[156]	validation_0-mae:2206.13683
[157]	validation_0-mae:2205.17260
[158]	validation_0-mae:2204.14550
[159]	validation_0-mae:2202.79517
[160]	validation_0-mae:2201.12014
[161]	validation_0-mae:2200.53165
[162]	validation_0-mae:2198.71235
[163]	validation_0-mae:2196.73875
[164]	validation_0-mae:2195.43523
[165]	validation_0-mae:2192.59711
[166]	validation_0-mae:2191.85634
[167]	validation_0-mae:2190.23758
[168]	validation_0-mae:2187.76386
[169]	validation_0-mae:2185.75438
[170]	validation_0-mae:2183.53124
[171]	validation_0-mae:2185.02283
[172]	validation_0-mae:2184.18676
[173]	validation_0-mae:2183.64168
[174]	validation_0-mae:2179.74097
[175]	validation_0-mae:2179.12545
[176]	validation_0-mae:2177.12754
[177]	validation_0-mae:2177.76994
[178]	validation_0-mae:2176.86381
[179]	validation_0-mae:2175.77252
[180]	validation_0-mae:2174.74584
[181]	validation_0-mae:2174.91794
[182]	validation_0-mae:2175.27598
[183]	validation_0-mae:2172.94848
[184]	validation_0-mae:2170.96622
[185]	validation_0-mae:2169.22277
[186]	validation_0-mae:2168.44024
[187]	validation_0-mae:2167.48090
[188]	validation_0-mae:2164.56911
[189]	validation_0-mae:2164.01375
[190]	validation_0-mae:2164.45027
[191]	validation_0-mae:2162.97536
[192]	validation_0-mae:2161.43513
[193]	validation_0-mae:2161.07065
[194]	validation_0-mae:2160.27653
[195]	validation_0-mae:2158.24082
[196]	validation_0-mae:2155.61108
[197]	validation_0-mae:2153.22852
[198]	validation_0-mae:2151.50267
[199]	validation_0-mae:2149.66488
[200]	validation_0-mae:2148.39819
[201]	validation_0-mae:2147.00327
[202]	validation_0-mae:2146.55080
[203]	validation_0-mae:2145.63254
[204]	validation_0-mae:2146.23680
[205]	validation_0-mae:2145.60849
[206]	validation_0-mae:2146.06556
[207]	validation_0-mae:2143.53425
[208]	validation_0-mae:2142.56121
[209]	validation_0-mae:2142.17216
[210]	validation_0-mae:2142.50339
[211]	validation_0-mae:2141.57880
[212]	validation_0-mae:2139.77699
[213]	validation_0-mae:2140.58457
[214]	validation_0-mae:2139.79996
[215]	validation_0-mae:2139.35068
[216]	validation_0-mae:2137.85356
[217]	validation_0-mae:2137.61775
[218]	validation_0-mae:2135.64595
[219]	validation_0-mae:2135.33364
[220]	validation_0-mae:2133.93334
[221]	validation_0-mae:2133.37390
[222]	validation_0-mae:2133.16617
[223]	validation_0-mae:2132.32235
[224]	validation_0-mae:2132.59879
[225]	validation_0-mae:2132.56420
[226]	validation_0-mae:2133.15997
[227]	validation_0-mae:2132.30823
[228]	validation_0-mae:2131.85949
[229]	validation_0-mae:2130.62879
[230]	validation_0-mae:2130.96008
[231]	validation_0-mae:2128.49602
[232]	validation_0-mae:2128.35871
[233]	validation_0-mae:2128.59215
[234]	validation_0-mae:2128.56055
[235]	validation_0-mae:2126.43049
[236]	validation_0-mae:2126.12069
[237]	validation_0-mae:2125.44812
[238]	validation_0-mae:2125.85124
[239]	validation_0-mae:2122.51000
[240]	validation_0-mae:2121.99005
[241]	validation_0-mae:2120.07173
[242]	validation_0-mae:2120.29579
[243]	validation_0-mae:2117.94429
[244]	validation_0-mae:2117.29129
[245]	validation_0-mae:2116.05952
[246]	validation_0-mae:2115.20177
[247]	validation_0-mae:2114.82610
[248]	validation_0-mae:2114.12591
[249]	validation_0-mae:2114.52460
[250]	validation_0-mae:2114.24782
[251]	validation_0-mae:2114.01708
[252]	validation_0-mae:2113.53096
[253]	validation_0-mae:2114.28803
[254]	validation_0-mae:2114.27864
[255]	validation_0-mae:2113.78420
[256]	validation_0-mae:2113.40202
[257]	validation_0-mae:2114.37305
[258]	validation_0-mae:2114.22611
[259]	validation_0-mae:2113.46222
[260]	validation_0-mae:2114.03862
[261]	validation_0-mae:2114.16811
[262]	validation_0-mae:2111.67920
[263]	validation_0-mae:2110.96287
[264]	validation_0-mae:2110.92615
[265]	validation_0-mae:2110.39094
[266]	validation_0-mae:2109.47196
[267]	validation_0-mae:2109.04999
[268]	validation_0-mae:2108.99392
[269]	validation_0-mae:2108.30517
[270]	validation_0-mae:2107.85937
[271]	validation_0-mae:2108.49514
[272]	validation_0-mae:2109.10704
[273]	validation_0-mae:2109.40335
[274]	validation_0-mae:2108.90111
[275]	validation_0-mae:2106.98083
[276]	validation_0-mae:2107.72184
[277]	validation_0-mae:2106.05447
[278]	validation_0-mae:2105.56889
[279]	validation_0-mae:2104.84634
[280]	validation_0-mae:2105.17889
[281]	validation_0-mae:2103.40281
[282]	validation_0-mae:2102.25074
[283]	validation_0-mae:2101.18016
[284]	validation_0-mae:2098.79285
[285]	validation_0-mae:2098.60914
[286]	validation_0-mae:2097.37136
[287]	validation_0-mae:2097.41300
[288]	validation_0-mae:2097.84763
[289]	validation_0-mae:2097.99214
[290]	validation_0-mae:2097.58639
[291]	validation_0-mae:2096.41854
[292]	validation_0-mae:2096.06598
[293]	validation_0-mae:2096.53471
[294]	validation_0-mae:2096.94877
[295]	validation_0-mae:2096.32222
[296]	validation_0-mae:2096.43456
[297]	validation_0-mae:2095.88652
[298]	validation_0-mae:2095.51307
[299]	validation_0-mae:2096.32667
[300]	validation_0-mae:2096.36456
[301]	validation_0-mae:2096.15310
[302]	validation_0-mae:2095.94743
[303]	validation_0-mae:2094.43100
[304]	validation_0-mae:2093.59277
[305]	validation_0-mae:2094.47398
[306]	validation_0-mae:2092.10311
[307]	validation_0-mae:2092.84172
[308]	validation_0-mae:2091.93237
[309]	validation_0-mae:2090.14702
[310]	validation_0-mae:2089.52140
[311]	validation_0-mae:2088.26006
[312]	validation_0-mae:2088.42396
[313]	validation_0-mae:2088.14844
[314]	validation_0-mae:2088.48688
[315]	validation_0-mae:2087.60677
[316]	validation_0-mae:2087.77251
[317]	validation_0-mae:2088.00862
[318]	validation_0-mae:2087.06389
[319]	validation_0-mae:2086.63140
[320]	validation_0-mae:2085.76774
[321]	validation_0-mae:2085.58621
[322]	validation_0-mae:2085.32849
[323]	validation_0-mae:2085.06072
[324]	validation_0-mae:2084.69676
[325]	validation_0-mae:2084.98111
[326]	validation_0-mae:2084.37945
[327]	validation_0-mae:2084.48236
[328]	validation_0-mae:2084.37700
[329]	validation_0-mae:2083.81687
[330]	validation_0-mae:2083.26652
[331]	validation_0-mae:2081.84861
[332]	validation_0-mae:2080.00015
[333]	validation_0-mae:2079.59148
[334]	validation_0-mae:2079.82562
[335]	validation_0-mae:2079.23074
[336]	validation_0-mae:2078.91503
[337]	validation_0-mae:2078.91140
[338]	validation_0-mae:2079.81806
[339]	validation_0-mae:2078.03651
[340]	validation_0-mae:2078.52706
[341]	validation_0-mae:2078.52191
[342]	validation_0-mae:2078.22273
[343]	validation_0-mae:2078.74024
[344]	validation_0-mae:2078.80793
[345]	validation_0-mae:2078.74743
[346]	validation_0-mae:2077.18714
[347]	validation_0-mae:2077.13075
[348]	validation_0-mae:2076.75643
[349]	validation_0-mae:2076.48317
[350]	validation_0-mae:2075.49900
[351]	validation_0-mae:2076.01647
[352]	validation_0-mae:2075.88568
[353]	validation_0-mae:2075.72244
[354]	validation_0-mae:2075.47666
[355]	validation_0-mae:2075.72795
[356]	validation_0-mae:2076.47685
[357]	validation_0-mae:2077.01503
[358]	validation_0-mae:2076.60876
[359]	validation_0-mae:2076.32838
[360]	validation_0-mae:2076.41887
[361]	validation_0-mae:2075.94227
[362]	validation_0-mae:2074.93200
[363]	validation_0-mae:2074.66727
[364]	validation_0-mae:2074.79962
[365]	validation_0-mae:2075.43446
[366]	validation_0-mae:2075.18844
[367]	validation_0-mae:2075.08868
[368]	validation_0-mae:2075.18480
[369]	validation_0-mae:2075.63945
[370]	validation_0-mae:2075.65084
[371]	validation_0-mae:2075.71707
[372]	validation_0-mae:2076.11125
[373]	validation_0-mae:2076.29955
[374]	validation_0-mae:2076.09079
[375]	validation_0-mae:2076.15740
[376]	validation_0-mae:2075.20898
[377]	validation_0-mae:2075.37562
[378]	validation_0-mae:2075.07030
[379]	validation_0-mae:2075.11367
[380]	validation_0-mae:2075.10957
[381]	validation_0-mae:2075.14974
[382]	validation_0-mae:2075.00397
[383]	validation_0-mae:2074.76409
[384]	validation_0-mae:2075.19469
[385]	validation_0-mae:2074.84038
[386]	validation_0-mae:2075.12704
[387]	validation_0-mae:2075.18310
[388]	validation_0-mae:2075.29417
[389]	validation_0-mae:2075.61652
[390]	validation_0-mae:2075.70935
[391]	validation_0-mae:2075.53306
[392]	validation_0-mae:2075.32715
[393]	validation_0-mae:2075.32043
[394]	validation_0-mae:2074.79470
[395]	validation_0-mae:2074.25774
[396]	validation_0-mae:2074.43824
[397]	validation_0-mae:2073.89293
[398]	validation_0-mae:2073.58711
[399]	validation_0-mae:2072.38758
[400]	validation_0-mae:2072.44253
[401]	validation_0-mae:2072.40576
[402]	validation_0-mae:2072.70064
[403]	validation_0-mae:2072.35785
[404]	validation_0-mae:2072.46926
[405]	validation_0-mae:2072.05527
[406]	validation_0-mae:2071.53265
[407]	validation_0-mae:2072.28401
[408]	validation_0-mae:2071.66645
[409]	validation_0-mae:2071.34108
[410]	validation_0-mae:2071.41826
[411]	validation_0-mae:2071.52739
[412]	validation_0-mae:2071.59549
[413]	validation_0-mae:2071.51556
[414]	validation_0-mae:2071.71472
[415]	validation_0-mae:2071.72306
[416]	validation_0-mae:2071.52573
[417]	validation_0-mae:2070.86572
[418]	validation_0-mae:2070.72752
[419]	validation_0-mae:2070.68359
[420]	validation_0-mae:2070.03778
[421]	validation_0-mae:2070.29196
[422]	validation_0-mae:2070.24025
[423]	validation_0-mae:2069.72955
[424]	validation_0-mae:2069.80765
[425]	validation_0-mae:2069.57695
[426]	validation_0-mae:2069.97643
[427]	validation_0-mae:2069.90104
[428]	validation_0-mae:2069.51156
[429]	validation_0-mae:2069.49231
[430]	validation_0-mae:2069.17725
[431]	validation_0-mae:2069.17092
[432]	validation_0-mae:2069.47899
[433]	validation_0-mae:2069.24175
[434]	validation_0-mae:2067.98611
[435]	validation_0-mae:2068.56673
[436]	validation_0-mae:2068.78164
[437]	validation_0-mae:2068.70174
[438]	validation_0-mae:2068.71406
[439]	validation_0-mae:2068.68422
[440]	validation_0-mae:2067.81666
[441]	validation_0-mae:2067.75341
[442]	validation_0-mae:2067.61487
[443]	validation_0-mae:2067.57663
[444]	validation_0-mae:2068.01637
[445]	validation_0-mae:2068.24827
[446]	validation_0-mae:2068.05935
[447]	validation_0-mae:2068.12702
[448]	validation_0-mae:2068.43124
[449]	validation_0-mae:2068.46174
[450]	validation_0-mae:2068.74578
[451]	validation_0-mae:2067.79742
[452]	validation_0-mae:2067.87434
[453]	validation_0-mae:2067.71234
[454]	validation_0-mae:2068.18904
[455]	validation_0-mae:2068.40049
[456]	validation_0-mae:2068.63858
[457]	validation_0-mae:2068.25789
[458]	validation_0-mae:2068.29356
[459]	validation_0-mae:2068.23795
[460]	validation_0-mae:2068.16382
[461]	validation_0-mae:2068.25107
[462]	validation_0-mae:2068.11103
[463]	validation_0-mae:2068.38911
[464]	validation_0-mae:2068.47310
[465]	validation_0-mae:2068.78754
[466]	validation_0-mae:2069.06893
[467]	validation_0-mae:2069.21671
[468]	validation_0-mae:2068.73086
[469]	validation_0-mae:2068.77180
[470]	validation_0-mae:2068.71018
[471]	validation_0-mae:2068.69502
[472]	validation_0-mae:2069.12498
[473]	validation_0-mae:2069.16486
[474]	validation_0-mae:2069.41636
[475]	validation_0-mae:2069.55469
[476]	validation_0-mae:2069.93319
[477]	validation_0-mae:2069.95338
[478]	validation_0-mae:2069.56171
[479]	validation_0-mae:2067.75686
[480]	validation_0-mae:2067.93496
[481]	validation_0-mae:2066.70447
[482]	validation_0-mae:2066.65958
[483]	validation_0-mae:2066.50603
[484]	validation_0-mae:2066.70890
[485]	validation_0-mae:2066.79881
[486]	validation_0-mae:2066.94524
[487]	validation_0-mae:2067.08666
[488]	validation_0-mae:2066.90307
[489]	validation_0-mae:2066.64828
[490]	validation_0-mae:2066.39334
[491]	validation_0-mae:2066.24838
[492]	validation_0-mae:2066.17200
[493]	validation_0-mae:2065.96385
[494]	validation_0-mae:2066.03704
[495]	validation_0-mae:2066.00595
[496]	validation_0-mae:2066.08600
[497]	validation_0-mae:2065.81508
[498]	validation_0-mae:2066.02560
[499]	validation_0-mae:2066.43235
[500]	validation_0-mae:2065.78666
[501]	validation_0-mae:2065.72757
[502]	validation_0-mae:2065.64425
[503]	validation_0-mae:2066.07817
[504]	validation_0-mae:2066.75640
[505]	validation_0-mae:2066.58395
[506]	validation_0-mae:2066.76047
[507]	validation_0-mae:2067.01644
[508]	validation_0-mae:2067.38131
[509]	validation_0-mae:2067.43503
[510]	validation_0-mae:2067.48735
[511]	validation_0-mae:2067.56324
[512]	validation_0-mae:2068.06517
[513]	validation_0-mae:2068.13956
[514]	validation_0-mae:2068.40039
[515]	validation_0-mae:2068.57337
[516]	validation_0-mae:2068.49726
[517]	validation_0-mae:2068.88606
[518]	validation_0-mae:2067.73105
[519]	validation_0-mae:2068.07912
[520]	validation_0-mae:2068.11670
[521]	validation_0-mae:2067.68280
[522]	validation_0-mae:2067.86316
[523]	validation_0-mae:2068.29940
[524]	validation_0-mae:2068.16028
[525]	validation_0-mae:2068.05993
[526]	validation_0-mae:2068.26851
[527]	validation_0-mae:2067.47410
[528]	validation_0-mae:2067.56501
[529]	validation_0-mae:2067.11404
[530]	validation_0-mae:2067.09238
[531]	validation_0-mae:2067.27282
[532]	validation_0-mae:2067.27621
[533]	validation_0-mae:2067.33955
[534]	validation_0-mae:2067.48344
[535]	validation_0-mae:2067.42454
[536]	validation_0-mae:2067.38690
[537]	validation_0-mae:2066.52477
[538]	validation_0-mae:2066.59977
[539]	validation_0-mae:2066.70523
[540]	validation_0-mae:2066.72310
[541]	validation_0-mae:2066.88112
[542]	validation_0-mae:2067.12223
[543]	validation_0-mae:2067.07021
[544]	validation_0-mae:2067.20246
[545]	validation_0-mae:2067.23498
[546]	validation_0-mae:2066.27000
[547]	validation_0-mae:2065.94001
[548]	validation_0-mae:2065.80515
[549]	validation_0-mae:2065.48507
[550]	validation_0-mae:2065.35814
[551]	validation_0-mae:2065.47208
[552]	validation_0-mae:2065.49891
[553]	validation_0-mae:2065.35388
[554]	validation_0-mae:2065.51467
[555]	validation_0-mae:2065.29502
[556]	validation_0-mae:2065.00954
[557]	validation_0-mae:2064.92982
[558]	validation_0-mae:2064.23770
[559]	validation_0-mae:2064.21247
[560]	validation_0-mae:2064.37113
[561]	validation_0-mae:2064.70407
[562]	validation_0-mae:2064.85494
[563]	validation_0-mae:2064.86409
[564]	validation_0-mae:2064.94462
[565]	validation_0-mae:2065.18117
[566]	validation_0-mae:2064.58069
[567]	validation_0-mae:2064.67149
[568]	validation_0-mae:2064.37572
[569]	validation_0-mae:2064.39362
[570]	validation_0-mae:2064.48218
[571]	validation_0-mae:2064.61882
[572]	validation_0-mae:2063.94827
[573]	validation_0-mae:2063.82038
[574]	validation_0-mae:2063.65674
[575]	validation_0-mae:2063.61920
[576]	validation_0-mae:2063.56943
[577]	validation_0-mae:2063.16653
[578]	validation_0-mae:2063.24922
[579]	validation_0-mae:2063.26515
[580]	validation_0-mae:2063.30221
[581]	validation_0-mae:2063.29112
[582]	validation_0-mae:2063.18431
[583]	validation_0-mae:2062.83410
[584]	validation_0-mae:2062.61949
[585]	validation_0-mae:2062.40883
[586]	validation_0-mae:2062.79824
[587]	validation_0-mae:2062.55619
[588]	validation_0-mae:2062.74511
[589]	validation_0-mae:2062.33767
[590]	validation_0-mae:2062.62023

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[41]	validation_0-mae:3267.95906
[42]	validation_0-mae:3215.94402
[43]	validation_0-mae:3161.50676
[44]	validation_0-mae:3125.15727
[45]	validation_0-mae:3097.80852
[46]	validation_0-mae:3064.52859
[47]	validation_0-mae:3036.66152
[48]	validation_0-mae:3014.10609
[49]	validation_0-mae:2994.44619
[50]	validation_0-mae:2958.39357
[51]	validation_0-mae:2937.23076
[52]	validation_0-mae:2915.41625
[53]	validation_0-mae:2903.34959
[54]	validation_0-mae:2885.41826
[55]	validation_0-mae:2852.46987
[56]	validation_0-mae:2837.00967
[57]	validation_0-mae:2821.98917
[58]	validation_0-mae:2797.18013
[59]	validation_0-mae:2781.31675
[60]	validation_0-mae:2749.22555
[61]	validation_0-mae:2735.56265
[62]	validation_0-mae:2725.25144
[63]	validation_0-mae:2718.97102
[64]	validation_0-mae:2695.35648
[65]	validation_0-mae:2690.51126
[66]	validation_0-mae:2678.20097
[67]	validation_0-mae:2667.41188
[68]	validation_0-mae:2654.81561
[69]	validation_0-mae:2637.74307
[70]	validation_0-mae:2623.16659
[71]	validation_0-mae:2614.99688
[72]	validation_0-mae:2602.01680
[73]	validation_0-mae:2586.11159
[74]	validation_0-mae:2576.60599
[75]	validation_0-mae:2567.66715
[76]	validation_0-mae:2554.86933
[77]	validation_0-mae:2546.02719
[78]	validation_0-mae:2542.17620
[79]	validation_0-mae:2530.47534
[80]	validation_0-mae:2527.31344
[81]	validation_0-mae:2519.17968
[82]	validation_0-mae:2512.87944
[83]	validation_0-mae:2507.45805
[84]	validation_0-mae:2506.67266
[85]	validation_0-mae:2497.62934
[86]	validation_0-mae:2484.27054
[87]	validation_0-mae:2474.80619
[88]	validation_0-mae:2469.23545
[89]	validation_0-mae:2460.48445
[90]	validation_0-mae:2455.55971
[91]	validation_0-mae:2452.04884
[92]	validation_0-mae:2444.69464
[93]	validation_0-mae:2440.58690
[94]	validation_0-mae:2431.45434
[95]	validation_0-mae:2429.18924
[96]	validation_0-mae:2422.50199
[97]	validation_0-mae:2412.90532
[98]	validation_0-mae:2409.83264
[99]	validation_0-mae:2402.38524
[100]	validation_0-mae:2399.12097
[101]	validation_0-mae:2392.25417
[102]	validation_0-mae:2386.91338
[103]	validation_0-mae:2386.01485
[104]	validation_0-mae:2382.69733
[105]	validation_0-mae:2373.91241
[106]	validation_0-mae:2365.21202
[107]	validation_0-mae:2363.10095
[108]	validation_0-mae:2358.20746
[109]	validation_0-mae:2356.48354
[110]	validation_0-mae:2350.98182
[111]	validation_0-mae:2348.31095
[112]	validation_0-mae:2347.27003
[113]	validation_0-mae:2340.18357
[114]	validation_0-mae:2338.37767
[115]	validation_0-mae:2331.28627
[116]	validation_0-mae:2327.37442
[117]	validation_0-mae:2325.13347
[118]	validation_0-mae:2323.16565
[119]	validation_0-mae:2316.03906
[120]	validation_0-mae:2312.44216
[121]	validation_0-mae:2309.45352
[122]	validation_0-mae:2308.52671
[123]	validation_0-mae:2308.85969
[124]	validation_0-mae:2304.96602
[125]	validation_0-mae:2303.08538
[126]	validation_0-mae:2297.92775
[127]	validation_0-mae:2295.09316
[128]	validation_0-mae:2290.66134
[129]	validation_0-mae:2288.78018
[130]	validation_0-mae:2284.55899
[131]	validation_0-mae:2281.19596
[132]	validation_0-mae:2279.93541
[133]	validation_0-mae:2279.53974
[134]	validation_0-mae:2278.43713
[135]	validation_0-mae:2275.43678
[136]	validation_0-mae:2275.33940
[137]	validation_0-mae:2272.69618
[138]	validation_0-mae:2273.18338
[139]	validation_0-mae:2271.70001
[140]	validation_0-mae:2268.40405
[141]	validation_0-mae:2268.76446
[142]	validation_0-mae:2266.11980
[143]	validation_0-mae:2262.94190
[144]	validation_0-mae:2261.64395
[145]	validation_0-mae:2260.39293
[146]	validation_0-mae:2258.68752
[147]	validation_0-mae:2256.23441
[148]	validation_0-mae:2255.81997
[149]	validation_0-mae:2253.00247
[150]	validation_0-mae:2252.00929
[151]	validation_0-mae:2251.79382
[152]	validation_0-mae:2250.74235
[153]	validation_0-mae:2248.54827
[154]	validation_0-mae:2246.18502
[155]	validation_0-mae:2243.51954
[156]	validation_0-mae:2240.07903
[157]	validation_0-mae:2238.99793
[158]	validation_0-mae:2236.32223
[159]	validation_0-mae:2233.22271
[160]	validation_0-mae:2233.13968
[161]	validation_0-mae:2233.83863
[162]	validation_0-mae:2233.01830
[163]	validation_0-mae:2230.31371
[164]	validation_0-mae:2227.73870
[165]	validation_0-mae:2225.33133
[166]	validation_0-mae:2224.90503
[167]	validation_0-mae:2224.65429
[168]	validation_0-mae:2222.24612
[169]	validation_0-mae:2223.11026
[170]	validation_0-mae:2219.60355
[171]	validation_0-mae:2219.62686
[172]	validation_0-mae:2217.25740
[173]	validation_0-mae:2215.91309
[174]	validation_0-mae:2212.84486
[175]	validation_0-mae:2210.93311
[176]	validation_0-mae:2210.01125
[177]	validation_0-mae:2210.80802
[178]	validation_0-mae:2209.36543
[179]	validation_0-mae:2207.32284
[180]	validation_0-mae:2206.16693
[181]	validation_0-mae:2204.21378
[182]	validation_0-mae:2204.50243
[183]	validation_0-mae:2201.89402
[184]	validation_0-mae:2201.27743
[185]	validation_0-mae:2202.50472
[186]	validation_0-mae:2201.76401
[187]	validation_0-mae:2197.13702
[188]	validation_0-mae:2196.43941
[189]	validation_0-mae:2196.18630
[190]	validation_0-mae:2195.70181
[191]	validation_0-mae:2195.21633
[192]	validation_0-mae:2193.60086
[193]	validation_0-mae:2193.31780
[194]	validation_0-mae:2192.77013
[195]	validation_0-mae:2192.92838
[196]	validation_0-mae:2192.01110
[197]	validation_0-mae:2190.07746
[198]	validation_0-mae:2189.83438
[199]	validation_0-mae:2189.78096
[200]	validation_0-mae:2189.00927
[201]	validation_0-mae:2187.92922
[202]	validation_0-mae:2184.67695
[203]	validation_0-mae:2185.55933
[204]	validation_0-mae:2186.36847
[205]	validation_0-mae:2186.23543
[206]	validation_0-mae:2185.80798
[207]	validation_0-mae:2184.30866
[208]	validation_0-mae:2185.33295
[209]	validation_0-mae:2182.73829
[210]	validation_0-mae:2181.51294
[211]	validation_0-mae:2181.49879
[212]	validation_0-mae:2181.07296
[213]	validation_0-mae:2181.21736
[214]	validation_0-mae:2181.14553
[215]	validation_0-mae:2180.54196
[216]	validation_0-mae:2180.46700
[217]	validation_0-mae:2180.74369
[218]	validation_0-mae:2179.89254
[219]	validation_0-mae:2177.95316
[220]	validation_0-mae:2177.73745
[221]	validation_0-mae:2177.64365
[222]	validation_0-mae:2177.16373
[223]	validation_0-mae:2176.38023
[224]	validation_0-mae:2176.61206
[225]	validation_0-mae:2176.14581
[226]	validation_0-mae:2176.17109
[227]	validation_0-mae:2175.35100
[228]	validation_0-mae:2176.29250
[229]	validation_0-mae:2175.00818
[230]	validation_0-mae:2172.91901
[231]	validation_0-mae:2173.85253
[232]	validation_0-mae:2173.57518
[233]	validation_0-mae:2174.59922
[234]	validation_0-mae:2174.63462
[235]	validation_0-mae:2174.45717
[236]	validation_0-mae:2173.16205
[237]	validation_0-mae:2171.45198
[238]	validation_0-mae:2172.42133
[239]	validation_0-mae:2172.83181
[240]	validation_0-mae:2174.08827
[241]	validation_0-mae:2172.66718
[242]	validation_0-mae:2171.31370
[243]	validation_0-mae:2170.59191
[244]	validation_0-mae:2172.01578
[245]	validation_0-mae:2170.11067
[246]	validation_0-mae:2168.36001
[247]	validation_0-mae:2168.35610
[248]	validation_0-mae:2168.05560
[249]	validation_0-mae:2167.88265
[250]	validation_0-mae:2167.15196
[251]	validation_0-mae:2166.61144
[252]	validation_0-mae:2166.10426
[253]	validation_0-mae:2166.38757
[254]	validation_0-mae:2163.98604
[255]	validation_0-mae:2163.23834
[256]	validation_0-mae:2162.82155
[257]	validation_0-mae:2162.09116
[258]	validation_0-mae:2161.44707
[259]	validation_0-mae:2161.60830
[260]	validation_0-mae:2160.88995
[261]	validation_0-mae:2160.22129
[262]	validation_0-mae:2160.25092
[263]	validation_0-mae:2158.44469
[264]	validation_0-mae:2158.52566
[265]	validation_0-mae:2157.13656
[266]	validation_0-mae:2157.22037
[267]	validation_0-mae:2156.60202
[268]	validation_0-mae:2155.20889
[269]	validation_0-mae:2154.10374
[270]	validation_0-mae:2154.63688
[271]	validation_0-mae:2154.92429
[272]	validation_0-mae:2154.23137
[273]	validation_0-mae:2153.34607
[274]	validation_0-mae:2151.85416
[275]	validation_0-mae:2151.54484
[276]	validation_0-mae:2150.13939
[277]	validation_0-mae:2149.07531
[278]	validation_0-mae:2148.64485
[279]	validation_0-mae:2149.28338
[280]	validation_0-mae:2149.04965
[281]	validation_0-mae:2147.98324
[282]	validation_0-mae:2147.50713
[283]	validation_0-mae:2145.89572
[284]	validation_0-mae:2145.48914
[285]	validation_0-mae:2146.05816
[286]	validation_0-mae:2146.30983
[287]	validation_0-mae:2146.31970
[288]	validation_0-mae:2145.22909
[289]	validation_0-mae:2144.91012
[290]	validation_0-mae:2144.81080
[291]	validation_0-mae:2145.25789
[292]	validation_0-mae:2145.08122
[293]	validation_0-mae:2144.80127
[294]	validation_0-mae:2144.93877
[295]	validation_0-mae:2143.54198
[296]	validation_0-mae:2143.97107
[297]	validation_0-mae:2143.59638
[298]	validation_0-mae:2143.77339
[299]	validation_0-mae:2143.29358
[300]	validation_0-mae:2143.35312
[301]	validation_0-mae:2141.88820
[302]	validation_0-mae:2140.83451
[303]	validation_0-mae:2139.86240
[304]	validation_0-mae:2139.34774
[305]	validation_0-mae:2139.64271
[306]	validation_0-mae:2138.62547
[307]	validation_0-mae:2137.94761
[308]	validation_0-mae:2138.15733
[309]	validation_0-mae:2138.83625
[310]	validation_0-mae:2138.30358
[311]	validation_0-mae:2138.41654
[312]	validation_0-mae:2137.66996
[313]	validation_0-mae:2138.29221
[314]	validation_0-mae:2136.83645
[315]	validation_0-mae:2135.21158
[316]	validation_0-mae:2133.71406
[317]	validation_0-mae:2132.94818
[318]	validation_0-mae:2132.54175
[319]	validation_0-mae:2132.16373
[320]	validation_0-mae:2132.02854
[321]	validation_0-mae:2132.33125
[322]	validation_0-mae:2132.61890
[323]	validation_0-mae:2132.33089
[324]	validation_0-mae:2131.19727
[325]	validation_0-mae:2131.12427
[326]	validation_0-mae:2130.68258
[327]	validation_0-mae:2130.35630
[328]	validation_0-mae:2130.82715
[329]	validation_0-mae:2130.90723
[330]	validation_0-mae:2130.76257
[331]	validation_0-mae:2130.69354
[332]	validation_0-mae:2131.26508
[333]	validation_0-mae:2131.10391
[334]	validation_0-mae:2129.23628
[335]	validation_0-mae:2129.52324
[336]	validation_0-mae:2129.80214
[337]	validation_0-mae:2130.43409
[338]	validation_0-mae:2130.71413
[339]	validation_0-mae:2130.19311
[340]	validation_0-mae:2130.89366
[341]	validation_0-mae:2130.36296
[342]	validation_0-mae:2130.69692
[343]	validation_0-mae:2130.69397
[344]	validation_0-mae:2129.35480
[345]	validation_0-mae:2129.16860
[346]	validation_0-mae:2129.67061
[347]	validation_0-mae:2126.92702
[348]	validation_0-mae:2126.95695
[349]	validation_0-mae:2125.10964
[350]	validation_0-mae:2124.60930
[351]	validation_0-mae:2122.34810
[352]	validation_0-mae:2121.82008
[353]	validation_0-mae:2121.37893
[354]	validation_0-mae:2121.13643
[355]	validation_0-mae:2121.05036
[356]	validation_0-mae:2121.41241
[357]	validation_0-mae:2121.26181
[358]	validation_0-mae:2121.55372
[359]	validation_0-mae:2120.07010
[360]	validation_0-mae:2119.90957
[361]	validation_0-mae:2119.44783
[362]	validation_0-mae:2119.67507
[363]	validation_0-mae:2119.55729
[364]	validation_0-mae:2119.51852
[365]	validation_0-mae:2119.74496
[366]	validation_0-mae:2119.69159
[367]	validation_0-mae:2118.92656
[368]	validation_0-mae:2118.62832
[369]	validation_0-mae:2119.40868
[370]	validation_0-mae:2118.28182
[371]	validation_0-mae:2118.29727
[372]	validation_0-mae:2118.44243
[373]	validation_0-mae:2117.50872
[374]	validation_0-mae:2116.56185
[375]	validation_0-mae:2116.72257
[376]	validation_0-mae:2116.67938
[377]	validation_0-mae:2116.50973
[378]	validation_0-mae:2116.32341
[379]	validation_0-mae:2116.38231
[380]	validation_0-mae:2115.43348
[381]	validation_0-mae:2115.85195
[382]	validation_0-mae:2115.63150
[383]	validation_0-mae:2115.19928
[384]	validation_0-mae:2114.97561
[385]	validation_0-mae:2114.08044
[386]	validation_0-mae:2114.61521
[387]	validation_0-mae:2113.81114
[388]	validation_0-mae:2111.57854
[389]	validation_0-mae:2111.12857
[390]	validation_0-mae:2110.79756
[391]	validation_0-mae:2110.28942
[392]	validation_0-mae:2109.77554
[393]	validation_0-mae:2109.09149
[394]	validation_0-mae:2108.36927
[395]	validation_0-mae:2107.61446
[396]	validation_0-mae:2107.04677
[397]	validation_0-mae:2106.75724
[398]	validation_0-mae:2105.79763
[399]	validation_0-mae:2105.73801
[400]	validation_0-mae:2104.80991
[401]	validation_0-mae:2105.10265
[402]	validation_0-mae:2104.39500
[403]	validation_0-mae:2104.50101
[404]	validation_0-mae:2103.65571
[405]	validation_0-mae:2103.52169
[406]	validation_0-mae:2103.92936
[407]	validation_0-mae:2103.69376
[408]	validation_0-mae:2103.92578
[409]	validation_0-mae:2103.68817
[410]	validation_0-mae:2103.77952
[411]	validation_0-mae:2103.80338
[412]	validation_0-mae:2103.86111
[413]	validation_0-mae:2103.66005
[414]	validation_0-mae:2104.14347
[415]	validation_0-mae:2103.88624
[416]	validation_0-mae:2103.68721
[417]	validation_0-mae:2103.81283
[418]	validation_0-mae:2104.27296
[419]	validation_0-mae:2104.46467
[420]	validation_0-mae:2105.15986
[421]	validation_0-mae:2105.12087
[422]	validation_0-mae:2105.33572
[423]	validation_0-mae:2105.35478
[424]	validation_0-mae:2104.96505
[425]	validation_0-mae:2105.46076
[426]	validation_0-mae:2105.78424
[427]	validation_0-mae:2106.29857
[428]	validation_0-mae:2106.61265
[429]	validation_0-mae:2106.51032
[430]	validation_0-mae:2106.95443
[431]	validation_0-mae:2106.08249
[432]	validation_0-mae:2105.67588
[433]	validation_0-mae:2105.73154
[434]	validation_0-mae:2104.79864
[435]	validation_0-mae:2104.61850
[436]	validation_0-mae:2104.56123
[437]	validation_0-mae:2104.83727
[438]	validation_0-mae:2105.06083
[439]	validation_0-mae:2104.91399
[440]	validation_0-mae:2105.14227
[441]	validation_0-mae:2105.52273
[442]	validation_0-mae:2105.90181
[443]	validation_0-mae:2106.27037
[444]	validation_0-mae:2106.39155
[445]	validation_0-mae:2106.19869
[446]	validation_0-mae:2106.89147
[447]	validation_0-mae:2107.14548
[448]	validation_0-mae:2107.06305
[449]	validation_0-mae:2107.14199
[450]	validation_0-mae:2106.79147
[451]	validation_0-mae:2107.06411
[452]	validation_0-mae:2107.46651
[453]	validation_0-mae:2107.37975
[454]	validation_0-mae:2106.90761
[455]	validation_0-mae:2106.47778
[456]	validation_0-mae:2105.90762
[457]	validation_0-mae:2107.42508
[458]	validation_0-mae:2107.13743
[459]	validation_0-mae:2107.38915
[460]	validation_0-mae:2107.65440
[461]	validation_0-mae:2107.51131
[462]	validation_0-mae:2107.13673
[463]	validation_0-mae:2105.54774
[464]	validation_0-mae:2105.66146
[465]	validation_0-mae:2105.35668
[466]	validation_0-mae:2104.90611
[467]	validation_0-mae:2104.72341
[468]	validation_0-mae:2105.00688
[469]	validation_0-mae:2104.66629
[470]	validation_0-mae:2104.47127
[471]	validation_0-mae:2103.63364
[472]	validation_0-mae:2103.54029
[473]	validation_0-mae:2103.48077
[474]	validation_0-mae:2103.62006
[475]	validation_0-mae:2103.70762
[476]	validation_0-mae:2103.68365
[477]	validation_0-mae:2103.89035
[478]	validation_0-mae:2103.10458
[479]	validation_0-mae:2102.84372
[480]	validation_0-mae:2102.30740
[481]	validation_0-mae:2102.09175
[482]	validation_0-mae:2101.94456
[483]	validation_0-mae:2101.93533
[484]	validation_0-mae:2102.00676
[485]	validation_0-mae:2102.19559
[486]	validation_0-mae:2102.33706
[487]	validation_0-mae:2102.09410
[488]	validation_0-mae:2102.26396
[489]	validation_0-mae:2101.97694
[490]	validation_0-mae:2101.89463
[491]	validation_0-mae:2102.00519
[492]	validation_0-mae:2102.26798
[493]	validation_0-mae:2101.91548
[494]	validation_0-mae:2101.28416
[495]	validation_0-mae:2101.46527
[496]	validation_0-mae:2101.48930
[497]	validation_0-mae:2100.92367
[498]	validation_0-mae:2100.69383
[499]	validation_0-mae:2100.22251
[500]	validation_0-mae:2100.23572
[501]	validation_0-mae:2099.92492
[502]	validation_0-mae:2100.03208
[503]	validation_0-mae:2100.34419
[504]	validation_0-mae:2100.48904
[505]	validation_0-mae:2099.94093
[506]	validation_0-mae:2100.02932
[507]	validation_0-mae:2099.42941
[508]	validation_0-mae:2099.15537
[509]	validation_0-mae:2099.19885
[510]	validation_0-mae:2099.00823
[511]	validation_0-mae:2099.22692
[512]	validation_0-mae:2099.13534
[513]	validation_0-mae:2099.03977
[514]	validation_0-mae:2099.05370
[515]	validation_0-mae:2098.22474
[516]	validation_0-mae:2098.44625
[517]	validation_0-mae:2098.10552
[518]	validation_0-mae:2097.95786
[519]	validation_0-mae:2097.10776
[520]	validation_0-mae:2097.14657
[521]	validation_0-mae:2097.15026
[522]	validation_0-mae:2097.10640
[523]	validation_0-mae:2097.17061
[524]	validation_0-mae:2097.52490
[525]	validation_0-mae:2097.65354
[526]	validation_0-mae:2097.76848
[527]	validation_0-mae:2097.67698
[528]	validation_0-mae:2097.47374
[529]	validation_0-mae:2097.20953
[530]	validation_0-mae:2097.17738
[531]	validation_0-mae:2097.22321
[532]	validation_0-mae:2097.28627
[533]	validation_0-mae:2097.55631
[534]	validation_0-mae:2097.04983
[535]	validation_0-mae:2097.01776
[536]	validation_0-mae:2097.26698
[537]	validation_0-mae:2097.06636
[538]	validation_0-mae:2097.79429
[539]	validation_0-mae:2097.43909
[540]	validation_0-mae:2096.93502
[541]	validation_0-mae:2097.00524
[542]	validation_0-mae:2097.11488
[543]	validation_0-mae:2096.74850
[544]	validation_0-mae:2096.63120
[545]	validation_0-mae:2095.59915
[546]	validation_0-mae:2095.71012
[547]	validation_0-mae:2096.00933
[548]	validation_0-mae:2096.09309
[549]	validation_0-mae:2096.40567
[550]	validation_0-mae:2096.10819
[551]	validation_0-mae:2096.45689
[552]	validation_0-mae:2096.37102
[553]	validation_0-mae:2095.76803
[554]	validation_0-mae:2095.62011
[555]	validation_0-mae:2095.29433
[556]	validation_0-mae:2094.94321
[557]	validation_0-mae:2095.14926
[558]	validation_0-mae:2094.43278
[559]	validation_0-mae:2094.30280
[560]	validation_0-mae:2093.96688
[561]	validation_0-mae:2093.55490
[562]	validation_0-mae:2092.69417
[563]	validation_0-mae:2092.75831
[564]	validation_0-mae:2092.72603
[565]	validation_0-mae:2092.59993
[566]	validation_0-mae:2092.82741
[567]	validation_0-mae:2092.98834
[568]	validation_0-mae:2093.29785
[569]	validation_0-mae:2093.41097
[570]	validation_0-mae:2093.46477
[571]	validation_0-mae:2093.02919
[572]	validation_0-mae:2092.63042
[573]	validation_0-mae:2092.16379
[574]	validation_0-mae:2092.29744
[575]	validation_0-mae:2092.16106
[576]	validation_0-mae:2092.08726
[577]	validation_0-mae:2092.07344
[578]	validation_0-mae:2092.33419
[579]	validation_0-mae:2092.02357
[580]	validation_0-mae:2092.42956
[581]	validation_0-mae:2092.09637
[582]	validation_0-mae:2092.20079
[583]	validation_0-mae:2091.82807
[584]	validation_0-mae:2092.09419
[585]	validation_0-mae:2091.83245
[586]	validation_0-mae:2091.87077
[587]	validation_0-mae:2091.80000
[588]	validation_0-mae:2091.96807
[589]	validation_0-mae:2092.01344
[590]	validation_0-mae:2092.10241
[591]	validation_0-mae:2091.64744
[592]	validation_0-mae:2091.55381
[593]	validation_0-mae:2091.65241
[594]	validation_0-mae:2091.58822
[595]	validation_0-mae:2092.05113
[596]	validation_0-mae:2092.05304
[597]	validation_0-mae:2091.87425
[598]	validation_0-mae:2091.65706
[599]	validation_0-mae:2091.69878
[600]	validation_0-mae:2091.56457
[601]	validation_0-mae:2091.86617
[602]	validation_0-mae:2091.35969
[603]	validation_0-mae:2091.39267
[604]	validation_0-mae:2091.79688
[605]	validation_0-mae:2091.72148
[606]	validation_0-mae:2091.34531
[607]	validation_0-mae:2091.54512
[608]	validation_0-mae:2091.35335
[609]	validation_0-mae:2091.32353
[610]	validation_0-mae:2091.15923
[611]	validation_0-mae:2091.11704
[612]	validation_0-mae:2090.94564
[613]	validation_0-mae:2090.89466
[614]	validation_0-mae:2091.27884
[615]	validation_0-mae:2091.30020
[616]	validation_0-mae:2091.20428
[617]	validation_0-mae:2091.49826
[618]	validation_0-mae:2091.80596
[619]	validation_0-mae:2091.96979
[620]	validation_0-mae:2092.17362
[621]	validation_0-mae:2092.37994
[622]	validation_0-mae:2092.58108
[623]	validation_0-mae:2092.45635
[624]	validation_0-mae:2091.83820
[625]	validation_0-mae:2092.05611
[626]	validation_0-mae:2091.52582
[627]	validation_0-mae:2091.48672
[628]	validation_0-mae:2091.66003
[629]	validation_0-mae:2091.95293

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[35]	validation_0-mae:3676.17273
[36]	validation_0-mae:3610.58896
[37]	validation_0-mae:3556.76540
[38]	validation_0-mae:3501.71503
[39]	validation_0-mae:3459.10640
[40]	validation_0-mae:3409.95946
[41]	validation_0-mae:3376.25761
[42]	validation_0-mae:3337.51034
[43]	validation_0-mae:3296.36147
[44]	validation_0-mae:3256.23124
[45]	validation_0-mae:3201.78225
[46]	validation_0-mae:3171.09521
[47]	validation_0-mae:3139.28237
[48]	validation_0-mae:3095.65557
[49]	validation_0-mae:3069.35435
[50]	validation_0-mae:3038.62627
[51]	validation_0-mae:3006.28285
[52]	validation_0-mae:2978.56045
[53]	validation_0-mae:2944.03999
[54]	validation_0-mae:2922.74147
[55]	validation_0-mae:2906.17561
[56]	validation_0-mae:2884.98307
[57]	validation_0-mae:2869.31549
[58]	validation_0-mae:2849.06608
[59]	validation_0-mae:2836.44796
[60]	validation_0-mae:2820.02934
[61]	validation_0-mae:2790.53968
[62]	validation_0-mae:2772.92655
[63]	validation_0-mae:2757.92643
[64]	validation_0-mae:2730.08804
[65]	validation_0-mae:2721.58139
[66]	validation_0-mae:2711.62604
[67]	validation_0-mae:2693.73997
[68]	validation_0-mae:2672.34938
[69]	validation_0-mae:2661.68904
[70]	validation_0-mae:2649.09579
[71]	validation_0-mae:2627.49227
[72]	validation_0-mae:2618.57299
[73]	validation_0-mae:2600.01696
[74]	validation_0-mae:2594.78065
[75]	validation_0-mae:2584.75546
[76]	validation_0-mae:2571.66914
[77]	validation_0-mae:2564.06061
[78]	validation_0-mae:2556.50250
[79]	validation_0-mae:2547.81917
[80]	validation_0-mae:2533.79746
[81]	validation_0-mae:2522.84575
[82]	validation_0-mae:2516.33761
[83]	validation_0-mae:2512.13219
[84]	validation_0-mae:2504.99531
[85]	validation_0-mae:2495.89639
[86]	validation_0-mae:2487.28571
[87]	validation_0-mae:2482.70575
[88]	validation_0-mae:2475.28491
[89]	validation_0-mae:2468.41347
[90]	validation_0-mae:2456.51382
[91]	validation_0-mae:2449.54587
[92]	validation_0-mae:2442.09722
[93]	validation_0-mae:2436.33360
[94]	validation_0-mae:2431.71508
[95]	validation_0-mae:2426.20119
[96]	validation_0-mae:2419.19487
[97]	validation_0-mae:2409.49278
[98]	validation_0-mae:2402.90756
[99]	validation_0-mae:2396.90809
[100]	validation_0-mae:2392.07154
[101]	validation_0-mae:2387.01570
[102]	validation_0-mae:2383.15255
[103]	validation_0-mae:2375.70325
[104]	validation_0-mae:2373.99948
[105]	validation_0-mae:2370.66375
[106]	validation_0-mae:2366.67483
[107]	validation_0-mae:2361.41585
[108]	validation_0-mae:2358.13881
[109]	validation_0-mae:2355.72491
[110]	validation_0-mae:2350.34396
[111]	validation_0-mae:2347.67397
[112]	validation_0-mae:2342.50478
[113]	validation_0-mae:2340.38575
[114]	validation_0-mae:2335.21074
[115]	validation_0-mae:2332.45949
[116]	validation_0-mae:2331.45013
[117]	validation_0-mae:2327.81946
[118]	validation_0-mae:2326.27595
[119]	validation_0-mae:2319.96564
[120]	validation_0-mae:2318.86429
[121]	validation_0-mae:2317.77279
[122]	validation_0-mae:2313.11805
[123]	validation_0-mae:2310.34979
[124]	validation_0-mae:2310.17861
[125]	validation_0-mae:2306.48293
[126]	validation_0-mae:2305.54854
[127]	validation_0-mae:2303.43653
[128]	validation_0-mae:2303.30246
[129]	validation_0-mae:2301.06647
[130]	validation_0-mae:2299.76527
[131]	validation_0-mae:2296.98748
[132]	validation_0-mae:2294.10364
[133]	validation_0-mae:2292.50558
[134]	validation_0-mae:2291.26463
[135]	validation_0-mae:2288.31276
[136]	validation_0-mae:2288.67294
[137]	validation_0-mae:2290.13991
[138]	validation_0-mae:2287.69931
[139]	validation_0-mae:2282.90173
[140]	validation_0-mae:2279.62826
[141]	validation_0-mae:2275.84605
[142]	validation_0-mae:2274.92745
[143]	validation_0-mae:2272.34200
[144]	validation_0-mae:2269.06800
[145]	validation_0-mae:2268.18549
[146]	validation_0-mae:2266.49694
[147]	validation_0-mae:2264.91668
[148]	validation_0-mae:2261.73265
[149]	validation_0-mae:2261.30330
[0]	validation_0-mae:12681.59393
[1]	validation_0-mae:12138.21878
[2]	validation_0-mae:11683.54638
[3]	validation_0-mae:11223.56766
[4]	validation_0-mae:10877.46578
[5]	validation_0-mae:10530.00453
[6]	validation_0-mae:10215.22050
[7]	validation_0-mae:9912.94126
[8]	validation_0-mae:9637.73450
[9]	validation_0-mae:9357.44124
[10]	validation_0-mae:9062.66224
[0]	validation_0-mae:12843.97603

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[1]	validation_0-mae:12429.47939
[2]	validation_0-mae:12031.28170
[3]	validation_0-mae:11658.59898
[4]	validation_0-mae:11295.80292
[5]	validation_0-mae:10954.17432
[6]	validation_0-mae:10640.29978
[7]	validation_0-mae:10328.31428
[8]	validation_0-mae:10030.72916
[9]	validation_0-mae:9764.55194
[0]	validation_0-mae:12463.75898
[1]	validation_0-mae:11740.68455
[2]	validation_0-mae:11088.88463
[3]	validation_0-mae:10466.15776
[4]	validation_0-mae:9928.33081
[5]	validation_0-mae:9433.35945
[6]	validation_0-mae:8989.16340
[7]	validation_0-mae:8555.95462
[8]	validation_0-mae:8161.55846
[9]	validation_0-mae:7821.63105
[10]	validation_0-mae:7518.80683
[11]	validation_0-mae:7239.91970
[12]	validation_0-mae:6973.87573
[13]	validation_0-mae:6706.83166
[14]	validation_0-mae:6455.67035
[15]	validation_0-mae:6233.82303
[16]	validation_0-mae:5998.12804
[17]	validation_0-mae:5793.67302
[18]	validation_0-mae:5595.22879
[19]	validation_0-mae:5431.44061
[20]	validation_0-mae:5253.86371
[21]	validation_0-mae:5091.15810
[22]	validation_0-mae:4934.03931
[23]	validation_0-mae:4793.76892
[24]	validation_0-mae:4664.91033
[25]	validation_0-mae:4555.95845
[26]	validation_0-mae:4443.78697
[27]	validation_0-mae:4341.30362
[28]	validation_0-mae:4239.57343
[29]	validation_0-mae:4150.65866
[30]	validation_0-mae:4067.82575
[31]	validation_0-mae:3974.19693
[32]	validation_0-mae:3899.96585
[33]	validation_0-mae:3812.00963
[34]	validation_0-mae:3740.19160
[35]	validation_0-mae:3666.39213

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[36]	validation_0-mae:3603.71363
[37]	validation_0-mae:3536.11584
[38]	validation_0-mae:3478.33485
[39]	validation_0-mae:3428.94832
[40]	validation_0-mae:3384.05602
[41]	validation_0-mae:3331.75426
[42]	validation_0-mae:3289.47193
[43]	validation_0-mae:3247.76722
[44]	validation_0-mae:3206.92925
[45]	validation_0-mae:3172.31888
[46]	validation_0-mae:3141.18893
[47]	validation_0-mae:3103.93382
[48]	validation_0-mae:3069.75010
[49]	validation_0-mae:3041.41128
[50]	validation_0-mae:3020.46174
[51]	validation_0-mae:2990.26437
[52]	validation_0-mae:2961.20774
[53]	validation_0-mae:2932.48662
[54]	validation_0-mae:2913.32821
[55]	validation_0-mae:2882.42628
[56]	validation_0-mae:2867.29588
[57]	validation_0-mae:2851.21094
[58]	validation_0-mae:2830.76998
[59]	validation_0-mae:2812.78553
[60]	validation_0-mae:2799.38882
[61]	validation_0-mae:2781.93088
[62]	validation_0-mae:2768.17350
[63]	validation_0-mae:2758.23419
[64]	validation_0-mae:2745.91281
[65]	validation_0-mae:2732.82915
[66]	validation_0-mae:2725.62067
[67]	validation_0-mae:2702.34647
[68]	validation_0-mae:2691.45993
[69]	validation_0-mae:2673.53699
[70]	validation_0-mae:2656.88700
[71]	validation_0-mae:2648.65784
[72]	validation_0-mae:2640.57948
[73]	validation_0-mae:2632.98840
[74]	validation_0-mae:2620.46899
[75]	validation_0-mae:2612.93332
[76]	validation_0-mae:2602.68968
[77]	validation_0-mae:2592.42190
[78]	validation_0-mae:2583.75506
[79]	validation_0-mae:2574.86479
[80]	validation_0-mae:2567.01765
[81]	validation_0-mae:2559.03341
[82]	validation_0-mae:2552.97692
[83]	validation_0-mae:2544.72256
[84]	validation_0-mae:2534.65379
[85]	validation_0-mae:2528.40343
[86]	validation_0-mae:2516.69629
[87]	validation_0-mae:2508.86153
[88]	validation_0-mae:2502.27702
[89]	validation_0-mae:2495.82514
[90]	validation_0-mae:2490.04887
[91]	validation_0-mae:2479.13009
[92]	validation_0-mae:2471.86278
[93]	validation_0-mae:2463.77663
[94]	validation_0-mae:2455.45225
[95]	validation_0-mae:2452.70250
[96]	validation_0-mae:2450.37502
[97]	validation_0-mae:2441.75581
[98]	validation_0-mae:2435.40635
[99]	validation_0-mae:2429.60623
[100]	validation_0-mae:2423.18603
[101]	validation_0-mae:2417.81903
[102]	validation_0-mae:2413.09666
[103]	validation_0-mae:2403.90989
[104]	validation_0-mae:2397.82276
[105]	validation_0-mae:2394.55247
[106]	validation_0-mae:2389.20919
[107]	validation_0-mae:2383.44724
[108]	validation_0-mae:2377.78237
[109]	validation_0-mae:2375.05184
[110]	validation_0-mae:2366.21260
[111]	validation_0-mae:2362.03479
[112]	validation_0-mae:2357.61053
[113]	validation_0-mae:2350.66014
[114]	validation_0-mae:2349.45248
[115]	validation_0-mae:2345.60009
[116]	validation_0-mae:2342.67593
[117]	validation_0-mae:2337.38540
[118]	validation_0-mae:2335.16954
[119]	validation_0-mae:2332.40513
[120]	validation_0-mae:2328.42674
[121]	validation_0-mae:2325.61881
[122]	validation_0-mae:2321.22876
[123]	validation_0-mae:2315.14562
[124]	validation_0-mae:2313.61105
[125]	validation_0-mae:2308.75301
[126]	validation_0-mae:2304.58877
[127]	validation_0-mae:2300.92849
[128]	validation_0-mae:2294.15262
[129]	validation_0-mae:2287.40921
[130]	validation_0-mae:2283.29099
[131]	validation_0-mae:2280.64496
[132]	validation_0-mae:2277.34528
[133]	validation_0-mae:2271.85423
[134]	validation_0-mae:2268.42874
[135]	validation_0-mae:2267.44222
[136]	validation_0-mae:2263.08651
[137]	validation_0-mae:2261.32902
[138]	validation_0-mae:2261.68444
[139]	validation_0-mae:2257.92765
[140]	validation_0-mae:2255.02296
[141]	validation_0-mae:2253.36978
[142]	validation_0-mae:2251.55713
[143]	validation_0-mae:2249.44771
[144]	validation_0-mae:2250.09241
[145]	validation_0-mae:2248.05142
[146]	validation_0-mae:2242.19558
[147]	validation_0-mae:2240.16000
[148]	validation_0-mae:2237.15084
[149]	validation_0-mae:2233.08454
[150]	validation_0-mae:2232.35749
[151]	validation_0-mae:2228.49185
[152]	validation_0-mae:2223.49743
[153]	validation_0-mae:2224.37850
[154]	validation_0-mae:2223.22190
[155]	validation_0-mae:2222.52166
[156]	validation_0-mae:2222.29458
[157]	validation_0-mae:2220.57316
[158]	validation_0-mae:2218.31075
[159]	validation_0-mae:2217.46785
[160]	validation_0-mae:2217.47243
[161]	validation_0-mae:2215.00521
[162]	validation_0-mae:2211.08614
[163]	validation_0-mae:2208.42278
[164]	validation_0-mae:2207.76046
[165]	validation_0-mae:2208.11263
[166]	validation_0-mae:2205.99500
[167]	validation_0-mae:2203.86435
[168]	validation_0-mae:2204.13847
[169]	validation_0-mae:2203.61135
[170]	validation_0-mae:2203.52384
[171]	validation_0-mae:2202.76787
[172]	validation_0-mae:2203.48529
[173]	validation_0-mae:2202.63813
[174]	validation_0-mae:2202.59774
[175]	validation_0-mae:2201.68180
[176]	validation_0-mae:2202.21431
[177]	validation_0-mae:2200.94277
[178]	validation_0-mae:2200.29038
[179]	validation_0-mae:2197.69494
[180]	validation_0-mae:2195.88983
[181]	validation_0-mae:2194.11744
[182]	validation_0-mae:2194.48257
[183]	validation_0-mae:2194.96511
[184]	validation_0-mae:2194.75786
[185]	validation_0-mae:2194.89346
[186]	validation_0-mae:2194.65665
[187]	validation_0-mae:2191.87219
[188]	validation_0-mae:2192.70729
[189]	validation_0-mae:2190.92661
[190]	validation_0-mae:2187.90761
[191]	validation_0-mae:2188.34980
[192]	validation_0-mae:2187.14467
[193]	validation_0-mae:2186.67576
[194]	validation_0-mae:2187.23938
[195]	validation_0-mae:2187.56410
[196]	validation_0-mae:2186.08743
[197]	validation_0-mae:2185.24196
[198]	validation_0-mae:2184.44752
[199]	validation_0-mae:2182.12262
[200]	validation_0-mae:2179.93751
[201]	validation_0-mae:2179.33487
[202]	validation_0-mae:2179.04670
[203]	validation_0-mae:2177.05099
[204]	validation_0-mae:2175.82032
[205]	validation_0-mae:2174.03196
[206]	validation_0-mae:2171.21505
[207]	validation_0-mae:2169.12161
[208]	validation_0-mae:2167.98006
[209]	validation_0-mae:2167.59402
[210]	validation_0-mae:2166.66327
[211]	validation_0-mae:2166.88444
[212]	validation_0-mae:2167.48069
[213]	validation_0-mae:2165.79704
[214]	validation_0-mae:2164.64439
[215]	validation_0-mae:2164.81514
[216]	validation_0-mae:2164.97989
[217]	validation_0-mae:2165.57471
[218]	validation_0-mae:2165.05518
[219]	validation_0-mae:2163.65845
[220]	validation_0-mae:2163.70296
[221]	validation_0-mae:2164.28861
[222]	validation_0-mae:2164.52125
[223]	validation_0-mae:2164.53836
[224]	validation_0-mae:2162.58962
[225]	validation_0-mae:2161.95424
[226]	validation_0-mae:2162.16190
[227]	validation_0-mae:2159.73118
[228]	validation_0-mae:2158.26282
[229]	validation_0-mae:2157.73906
[230]	validation_0-mae:2158.24347
[231]	validation_0-mae:2156.36766
[232]	validation_0-mae:2156.50445
[233]	validation_0-mae:2156.46294
[234]	validation_0-mae:2157.10675
[235]	validation_0-mae:2157.47604
[236]	validation_0-mae:2158.21125
[237]	validation_0-mae:2158.25906
[238]	validation_0-mae:2158.05423
[239]	validation_0-mae:2157.96059
[240]	validation_0-mae:2158.35335
[241]	validation_0-mae:2157.00955
[242]	validation_0-mae:2158.17095
[243]	validation_0-mae:2157.63809
[244]	validation_0-mae:2157.38925
[245]	validation_0-mae:2156.73080
[246]	validation_0-mae:2156.96006
[247]	validation_0-mae:2155.85625
[248]	validation_0-mae:2154.57215
[249]	validation_0-mae:2150.64550
[250]	validation_0-mae:2150.40348
[251]	validation_0-mae:2151.15300
[252]	validation_0-mae:2150.57903
[253]	validation_0-mae:2150.28909
[254]	validation_0-mae:2150.50777
[255]	validation_0-mae:2150.79906
[256]	validation_0-mae:2150.57379
[257]	validation_0-mae:2148.63278
[258]	validation_0-mae:2149.27518
[259]	validation_0-mae:2148.24621
[260]	validation_0-mae:2147.94919
[261]	validation_0-mae:2149.22547
[262]	validation_0-mae:2149.08198
[263]	validation_0-mae:2148.82029
[264]	validation_0-mae:2149.08251
[265]	validation_0-mae:2148.86605
[266]	validation_0-mae:2149.08353
[267]	validation_0-mae:2148.87395
[268]	validation_0-mae:2147.28918
[269]	validation_0-mae:2145.33057
[270]	validation_0-mae:2144.30600
[271]	validation_0-mae:2144.13631
[272]	validation_0-mae:2143.62263
[273]	validation_0-mae:2142.89060
[274]	validation_0-mae:2141.95594
[275]	validation_0-mae:2141.65782
[276]	validation_0-mae:2141.17455
[277]	validation_0-mae:2139.91116
[278]	validation_0-mae:2141.02615
[279]	validation_0-mae:2140.87014
[280]	validation_0-mae:2141.00773
[281]	validation_0-mae:2139.84618
[282]	validation_0-mae:2139.28718
[283]	validation_0-mae:2138.13904
[284]	validation_0-mae:2138.21608
[285]	validation_0-mae:2138.32938
[286]	validation_0-mae:2137.80762
[287]	validation_0-mae:2137.81667
[288]	validation_0-mae:2138.25510
[289]	validation_0-mae:2137.56488
[290]	validation_0-mae:2139.00396
[291]	validation_0-mae:2137.77667
[292]	validation_0-mae:2137.13780
[293]	validation_0-mae:2138.16042
[294]	validation_0-mae:2137.69255
[295]	validation_0-mae:2138.61497
[296]	validation_0-mae:2138.40526
[297]	validation_0-mae:2138.99606
[298]	validation_0-mae:2139.14138
[299]	validation_0-mae:2137.54500
[300]	validation_0-mae:2137.33233
[301]	validation_0-mae:2137.12989
[302]	validation_0-mae:2137.34683
[303]	validation_0-mae:2137.33147
[304]	validation_0-mae:2135.37743
[305]	validation_0-mae:2135.36094
[306]	validation_0-mae:2133.06556
[307]	validation_0-mae:2131.88008
[308]	validation_0-mae:2131.97005
[309]	validation_0-mae:2132.30610
[310]	validation_0-mae:2132.16513
[311]	validation_0-mae:2132.56346
[312]	validation_0-mae:2132.24093
[313]	validation_0-mae:2132.38626
[314]	validation_0-mae:2132.57955
[315]	validation_0-mae:2131.46478
[316]	validation_0-mae:2131.81487
[317]	validation_0-mae:2131.16484
[318]	validation_0-mae:2130.17973
[319]	validation_0-mae:2130.54423
[320]	validation_0-mae:2130.52955
[321]	validation_0-mae:2130.91899
[322]	validation_0-mae:2130.55727
[323]	validation_0-mae:2129.79256
[324]	validation_0-mae:2130.16156
[325]	validation_0-mae:2129.39102
[326]	validation_0-mae:2129.05962
[327]	validation_0-mae:2128.62700
[328]	validation_0-mae:2129.20868
[329]	validation_0-mae:2128.94697
[330]	validation_0-mae:2129.09027
[331]	validation_0-mae:2129.43728
[332]	validation_0-mae:2129.26272
[333]	validation_0-mae:2128.05663
[334]	validation_0-mae:2128.08168
[335]	validation_0-mae:2127.03121
[336]	validation_0-mae:2126.67719
[337]	validation_0-mae:2127.27614
[338]	validation_0-mae:2128.41672
[339]	validation_0-mae:2128.27914
[340]	validation_0-mae:2128.52646
[341]	validation_0-mae:2127.73956
[342]	validation_0-mae:2128.09130
[343]	validation_0-mae:2128.49294
[344]	validation_0-mae:2128.76105
[345]	validation_0-mae:2129.33506
[346]	validation_0-mae:2127.92922
[347]	validation_0-mae:2126.14198
[348]	validation_0-mae:2126.50759
[349]	validation_0-mae:2125.97523
[350]	validation_0-mae:2125.10617
[351]	validation_0-mae:2125.11638
[352]	validation_0-mae:2124.17105
[353]	validation_0-mae:2123.49918
[354]	validation_0-mae:2123.30202
[355]	validation_0-mae:2122.83728
[356]	validation_0-mae:2122.97150
[357]	validation_0-mae:2122.45998
[358]	validation_0-mae:2123.09679
[359]	validation_0-mae:2123.23127
[360]	validation_0-mae:2122.75903
[361]	validation_0-mae:2123.07477
[362]	validation_0-mae:2121.22301
[363]	validation_0-mae:2121.80325
[364]	validation_0-mae:2121.93692
[365]	validation_0-mae:2121.39507
[366]	validation_0-mae:2121.42797
[367]	validation_0-mae:2121.28905
[368]	validation_0-mae:2121.83976
[369]	validation_0-mae:2121.38467
[370]	validation_0-mae:2121.41937
[371]	validation_0-mae:2121.13772
[372]	validation_0-mae:2120.57299
[373]	validation_0-mae:2121.00267
[374]	validation_0-mae:2120.80672
[375]	validation_0-mae:2120.61352
[376]	validation_0-mae:2120.68041
[377]	validation_0-mae:2119.95676
[378]	validation_0-mae:2118.47723
[379]	validation_0-mae:2117.78758
[380]	validation_0-mae:2116.92816
[381]	validation_0-mae:2116.27702
[382]	validation_0-mae:2116.81891
[383]	validation_0-mae:2116.81386
[384]	validation_0-mae:2116.55825
[385]	validation_0-mae:2116.56818
[386]	validation_0-mae:2115.51331
[387]	validation_0-mae:2115.23313
[388]	validation_0-mae:2114.22063
[389]	validation_0-mae:2114.15784
[390]	validation_0-mae:2114.34071
[391]	validation_0-mae:2114.13766
[392]	validation_0-mae:2114.52034
[393]	validation_0-mae:2112.65052
[394]	validation_0-mae:2112.69392
[395]	validation_0-mae:2112.01734
[396]	validation_0-mae:2111.79891
[397]	validation_0-mae:2112.13172
[398]	validation_0-mae:2111.98522
[399]	validation_0-mae:2111.76623
[400]	validation_0-mae:2112.51767
[401]	validation_0-mae:2112.36346
[402]	validation_0-mae:2112.25762
[403]	validation_0-mae:2112.21225
[404]	validation_0-mae:2112.20925
[405]	validation_0-mae:2111.54488
[406]	validation_0-mae:2110.49460
[407]	validation_0-mae:2110.41471
[408]	validation_0-mae:2110.11026
[409]	validation_0-mae:2109.64470
[410]	validation_0-mae:2109.65071
[411]	validation_0-mae:2108.68044
[412]	validation_0-mae:2109.00327
[413]	validation_0-mae:2106.79841
[414]	validation_0-mae:2106.29300
[415]	validation_0-mae:2106.23524
[416]	validation_0-mae:2106.38929
[417]	validation_0-mae:2106.14503
[418]	validation_0-mae:2106.22930
[419]	validation_0-mae:2105.89531
[420]	validation_0-mae:2105.95053
[421]	validation_0-mae:2106.47296
[422]	validation_0-mae:2106.48769
[423]	validation_0-mae:2105.97205
[424]	validation_0-mae:2105.97246
[425]	validation_0-mae:2106.07070
[426]	validation_0-mae:2106.21748
[427]	validation_0-mae:2106.15842
[428]	validation_0-mae:2106.21815
[429]	validation_0-mae:2106.22999
[430]	validation_0-mae:2106.14024
[431]	validation_0-mae:2106.39323
[432]	validation_0-mae:2106.17583
[433]	validation_0-mae:2106.30143
[434]	validation_0-mae:2106.65364
[435]	validation_0-mae:2106.19966
[436]	validation_0-mae:2105.69705
[437]	validation_0-mae:2104.98246
[438]	validation_0-mae:2104.87787
[439]	validation_0-mae:2105.17863
[440]	validation_0-mae:2104.90859
[441]	validation_0-mae:2104.39102
[442]	validation_0-mae:2104.50030
[443]	validation_0-mae:2104.45856
[444]	validation_0-mae:2104.55881
[445]	validation_0-mae:2104.27991
[446]	validation_0-mae:2103.82836
[447]	validation_0-mae:2103.48061
[448]	validation_0-mae:2103.52351
[449]	validation_0-mae:2103.29019
[450]	validation_0-mae:2102.39211
[451]	validation_0-mae:2101.48646
[452]	validation_0-mae:2101.59457
[453]	validation_0-mae:2102.13631
[454]	validation_0-mae:2102.09563
[455]	validation_0-mae:2101.84787
[456]	validation_0-mae:2101.70151
[457]	validation_0-mae:2101.37458
[458]	validation_0-mae:2100.57916
[459]	validation_0-mae:2100.84696
[460]	validation_0-mae:2100.65891
[461]	validation_0-mae:2100.83606
[462]	validation_0-mae:2100.70250
[463]	validation_0-mae:2099.99056
[464]	validation_0-mae:2100.00211
[465]	validation_0-mae:2099.49335
[466]	validation_0-mae:2099.29296
[467]	validation_0-mae:2099.47441
[468]	validation_0-mae:2099.28469
[469]	validation_0-mae:2099.17801
[470]	validation_0-mae:2099.40793
[471]	validation_0-mae:2099.76447
[472]	validation_0-mae:2099.05003
[473]	validation_0-mae:2099.01636
[474]	validation_0-mae:2099.17130
[475]	validation_0-mae:2099.17998
[476]	validation_0-mae:2098.70010
[477]	validation_0-mae:2098.61149
[478]	validation_0-mae:2098.87409
[479]	validation_0-mae:2098.50352
[480]	validation_0-mae:2098.36178
[481]	validation_0-mae:2098.31036
[482]	validation_0-mae:2098.36738
[483]	validation_0-mae:2098.47375
[484]	validation_0-mae:2097.92701
[485]	validation_0-mae:2098.52641
[486]	validation_0-mae:2097.78663
[487]	validation_0-mae:2098.31189
[488]	validation_0-mae:2098.30727
[489]	validation_0-mae:2098.46654
[490]	validation_0-mae:2098.74596
[491]	validation_0-mae:2098.90443
[492]	validation_0-mae:2098.50824
[493]	validation_0-mae:2098.85724
[494]	validation_0-mae:2097.03887
[495]	validation_0-mae:2096.67114
[496]	validation_0-mae:2096.98133
[497]	validation_0-mae:2097.23692
[498]	validation_0-mae:2095.65972
[499]	validation_0-mae:2095.68710
[500]	validation_0-mae:2095.47437
[501]	validation_0-mae:2095.81497
[502]	validation_0-mae:2095.91510
[503]	validation_0-mae:2095.79634
[504]	validation_0-mae:2095.82483
[505]	validation_0-mae:2095.66827
[506]	validation_0-mae:2095.41457
[507]	validation_0-mae:2095.37779
[508]	validation_0-mae:2095.44872
[509]	validation_0-mae:2095.52542
[510]	validation_0-mae:2094.74309
[511]	validation_0-mae:2094.98118
[512]	validation_0-mae:2094.88008
[513]	validation_0-mae:2094.62697
[514]	validation_0-mae:2094.41583
[515]	validation_0-mae:2093.61818
[516]	validation_0-mae:2092.82916
[517]	validation_0-mae:2092.53616
[518]	validation_0-mae:2092.39995
[519]	validation_0-mae:2092.38723
[520]	validation_0-mae:2092.82210
[521]	validation_0-mae:2092.86667
[522]	validation_0-mae:2093.21451
[523]	validation_0-mae:2093.93227
[524]	validation_0-mae:2093.95125
[525]	validation_0-mae:2094.24936
[526]	validation_0-mae:2094.37823
[527]	validation_0-mae:2094.72259
[528]	validation_0-mae:2094.93316
[529]	validation_0-mae:2094.91792
[530]	validation_0-mae:2095.24913
[531]	validation_0-mae:2095.19117
[532]	validation_0-mae:2095.48575
[533]	validation_0-mae:2095.22492
[534]	validation_0-mae:2095.64502
[535]	validation_0-mae:2095.50176
[536]	validation_0-mae:2094.98761
[537]	validation_0-mae:2095.48279
[538]	validation_0-mae:2095.58480
[539]	validation_0-mae:2095.52804
[540]	validation_0-mae:2095.30230
[541]	validation_0-mae:2095.39903
[542]	validation_0-mae:2095.45127
[543]	validation_0-mae:2095.55333
[544]	validation_0-mae:2095.42918
[545]	validation_0-mae:2095.50826
[546]	validation_0-mae:2095.83132
[547]	validation_0-mae:2095.68880
[548]	validation_0-mae:2095.81388
[549]	validation_0-mae:2095.53837
[550]	validation_0-mae:2095.23926
[551]	validation_0-mae:2095.38180
[552]	validation_0-mae:2095.62069
[553]	validation_0-mae:2095.48601
[554]	validation_0-mae:2095.66269
[555]	validation_0-mae:2094.99367
[556]	validation_0-mae:2095.05940
[557]	validation_0-mae:2095.13759
[558]	validation_0-mae:2095.06511
[559]	validation_0-mae:2094.96902
[560]	validation_0-mae:2094.78687
[561]	validation_0-mae:2095.02324
[562]	validation_0-mae:2095.35671
[563]	validation_0-mae:2095.06131
[564]	validation_0-mae:2095.27720
[565]	validation_0-mae:2095.29295
[566]	validation_0-mae:2095.34916
[567]	validation_0-mae:2095.59390
[568]	validation_0-mae:2095.03308
[569]	validation_0-mae:2094.74668
[570]	validation_0-mae:2094.79524
[571]	validation_0-mae:2094.68450
[572]	validation_0-mae:2094.47143
[573]	validation_0-mae:2094.40414
[574]	validation_0-mae:2094.44297
[575]	validation_0-mae:2094.61960
[576]	validation_0-mae:2094.56594
[577]	validation_0-mae:2094.80113
[578]	validation_0-mae:2095.03339
[579]	validation_0-mae:2095.28576
[580]	validation_0-mae:2095.10048
[581]	validation_0-mae:2095.10561
[582]	validation_0-mae:2095.10147
[583]	validation_0-mae:2094.97560
[584]	validation_0-mae:2095.02537
[585]	validation_0-mae:2094.75210
[586]	validation_0-mae:2094.84653
[587]	validation_0-mae:2094.63226
[588]	validation_0-mae:2094.37546
[589]	validation_0-mae:2093.66553
[590]	validation_0-mae:2093.72503
[591]	validation_0-mae:2093.53889
[592]	validation_0-mae:2093.36743
[593]	validation_0-mae:2092.97853
[594]	validation_0-mae:2092.60736
[595]	validation_0-mae:2092.68969
[596]	validation_0-mae:2092.73166
[597]	validation_0-mae:2093.10686
[598]	validation_0-mae:2092.66632
[599]	validation_0-mae:2092.21104
[600]	validation_0-mae:2092.20890
[601]	validation_0-mae:2091.33892
[602]	validation_0-mae:2091.38770
[603]	validation_0-mae:2091.49045
[604]	validation_0-mae:2091.35363
[605]	validation_0-mae:2090.77371
[606]	validation_0-mae:2090.74680
[607]	validation_0-mae:2090.66773
[608]	validation_0-mae:2090.59672
[609]	validation_0-mae:2089.44635
[610]	validation_0-mae:2089.54246
[611]	validation_0-mae:2089.42942
[612]	validation_0-mae:2089.49321
[613]	validation_0-mae:2088.26489
[614]	validation_0-mae:2087.42562
[615]	validation_0-mae:2087.52486
[616]	validation_0-mae:2087.28926
[617]	validation_0-mae:2087.31092
[618]	validation_0-mae:2087.18349
[619]	validation_0-mae:2087.18822
[620]	validation_0-mae:2087.15988
[621]	validation_0-mae:2087.10584
[622]	validation_0-mae:2087.20310
[623]	validation_0-mae:2087.22137
[624]	validation_0-mae:2087.17666
[625]	validation_0-mae:2087.28291

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[0]	validation_0-mae:12444.57433
[1]	validation_0-mae:11709.62693
[2]	validation_0-mae:11025.51660
[3]	validation_0-mae:10407.72552
[4]	validation_0-mae:9869.01451
[5]	validation_0-mae:9367.37099
[6]	validation_0-mae:8924.20129
[7]	validation_0-mae:8518.33585
[8]	validation_0-mae:8135.53777
[9]	validation_0-mae:7805.15224
[10]	validation_0-mae:7475.20951
[11]	validation_0-mae:7199.33402
[12]	validation_0-mae:6929.09395
[13]	validation_0-mae:6666.63578
[14]	validation_0-mae:6430.96795
[15]	validation_0-mae:6212.47286
[16]	validation_0-mae:6002.28431
[17]	validation_0-mae:5783.64704
[18]	validation_0-mae:5583.05303
[19]	validation_0-mae:5423.33185
[20]	validation_0-mae:5256.62684
[21]	validation_0-mae:5107.00069
[22]	validation_0-mae:4954.05402
[23]	validation_0-mae:4831.62417
[24]	validation_0-mae:4707.81239
[25]	validation_0-mae:4579.99400
[26]	validation_0-mae:4460.66657
[27]	validation_0-mae:4374.76978
[28]	validation_0-mae:4269.98872
[29]	validation_0-mae:4177.17235
[30]	validation_0-mae:4089.11660
[31]	validation_0-mae:3991.87512
[32]	validation_0-mae:3899.72839
[33]	validation_0-mae:3820.83992
[34]	validation_0-mae:3755.02230
[35]	validation_0-mae:3682.43278
[36]	validation_0-mae:3618.29280
[37]	validation_0-mae:3562.19001
[38]	validation_0-mae:3503.48910
[39]	validation_0-mae:3458.98934
[40]	validation_0-mae:3416.30532
[41]	validation_0-mae:3372.20023
[42]	validation_0-mae:3321.70042
[43]	validation_0-mae:3282.69327
[44]	validation_0-mae:3240.19565
[45]	validation_0-mae:3202.64675
[46]	validation_0-mae:3160.11702
[47]	validation_0-mae:3119.30030
[48]	validation_0-mae:3086.63832
[49]	validation_0-mae:3061.41403
[50]	validation_0-mae:3023.63497
[51]	validation_0-mae:2997.49117
[52]	validation_0-mae:2972.12678
[53]	validation_0-mae:2949.15606
[54]	validation_0-mae:2915.55323
[55]	validation_0-mae:2895.94142
[56]	validation_0-mae:2877.19114
[57]	validation_0-mae:2859.23185
[58]	validation_0-mae:2840.95330
[59]	validation_0-mae:2827.35575
[60]	validation_0-mae:2812.40468
[61]	validation_0-mae:2790.65337
[62]	validation_0-mae:2778.80858
[63]	validation_0-mae:2767.96660
[64]	validation_0-mae:2747.57312
[65]	validation_0-mae:2734.67847
[66]	validation_0-mae:2713.95012
[67]	validation_0-mae:2703.24339
[68]	validation_0-mae:2696.92241
[69]	validation_0-mae:2680.37411
[70]	validation_0-mae:2669.05346
[71]	validation_0-mae:2656.81288
[72]	validation_0-mae:2643.05159
[73]	validation_0-mae:2636.97567
[74]	validation_0-mae:2622.58393
[75]	validation_0-mae:2615.96166
[76]	validation_0-mae:2605.65490
[77]	validation_0-mae:2593.51967
[78]	validation_0-mae:2580.43695
[79]	validation_0-mae:2571.79937
[80]	validation_0-mae:2567.66983
[81]	validation_0-mae:2562.20629
[82]	validation_0-mae:2555.66707
[83]	validation_0-mae:2538.83863
[84]	validation_0-mae:2527.36204
[85]	validation_0-mae:2516.99003
[86]	validation_0-mae:2511.95243
[87]	validation_0-mae:2502.32610
[88]	validation_0-mae:2498.86674
[89]	validation_0-mae:2488.90593
[90]	validation_0-mae:2481.43854
[91]	validation_0-mae:2475.04248
[92]	validation_0-mae:2470.09985
[93]	validation_0-mae:2462.67583
[94]	validation_0-mae:2454.55788
[95]	validation_0-mae:2446.71889
[96]	validation_0-mae:2439.34424
[97]	validation_0-mae:2430.87724
[98]	validation_0-mae:2426.62169
[99]	validation_0-mae:2423.57776
[100]	validation_0-mae:2416.47577
[101]	validation_0-mae:2409.24856
[102]	validation_0-mae:2403.67164
[103]	validation_0-mae:2396.16884
[104]	validation_0-mae:2391.13342
[105]	validation_0-mae:2389.76487
[106]	validation_0-mae:2385.67085
[107]	validation_0-mae:2382.73492
[108]	validation_0-mae:2377.59721
[109]	validation_0-mae:2371.60219
[110]	validation_0-mae:2366.92886
[111]	validation_0-mae:2358.15161
[112]	validation_0-mae:2351.66907
[113]	validation_0-mae:2349.12476
[114]	validation_0-mae:2343.87713
[115]	validation_0-mae:2342.51745
[116]	validation_0-mae:2338.01533
[117]	validation_0-mae:2332.65495
[118]	validation_0-mae:2329.28892
[119]	validation_0-mae:2325.26771
[120]	validation_0-mae:2323.57527
[121]	validation_0-mae:2322.72107
[122]	validation_0-mae:2320.32529
[123]	validation_0-mae:2317.63848
[124]	validation_0-mae:2313.86033
[125]	validation_0-mae:2309.98643
[126]	validation_0-mae:2309.09218
[127]	validation_0-mae:2303.27593
[128]	validation_0-mae:2301.43079
[129]	validation_0-mae:2300.09302
[130]	validation_0-mae:2298.74363
[131]	validation_0-mae:2297.34614
[132]	validation_0-mae:2291.61266
[133]	validation_0-mae:2290.86506
[134]	validation_0-mae:2288.63497
[135]	validation_0-mae:2285.95557
[136]	validation_0-mae:2283.02912
[137]	validation_0-mae:2282.17702
[138]	validation_0-mae:2278.56953
[139]	validation_0-mae:2277.18283
[140]	validation_0-mae:2275.52215
[141]	validation_0-mae:2269.48157
[142]	validation_0-mae:2266.77349
[143]	validation_0-mae:2264.92606
[144]	validation_0-mae:2262.75885
[145]	validation_0-mae:2260.99636
[146]	validation_0-mae:2258.45547
[147]	validation_0-mae:2255.98149
[148]	validation_0-mae:2253.18374
[149]	validation_0-mae:2250.01862
[150]	validation_0-mae:2247.50109
[151]	validation_0-mae:2247.53902
[152]	validation_0-mae:2247.45520
[153]	validation_0-mae:2244.69578
[154]	validation_0-mae:2244.45055
[155]	validation_0-mae:2242.43782
[156]	validation_0-mae:2241.47564
[157]	validation_0-mae:2240.03116
[158]	validation_0-mae:2237.46344
[159]	validation_0-mae:2234.92625
[160]	validation_0-mae:2232.43541
[161]	validation_0-mae:2230.82057
[162]	validation_0-mae:2228.89809
[163]	validation_0-mae:2229.21211
[164]	validation_0-mae:2226.74372
[165]	validation_0-mae:2225.17732
[166]	validation_0-mae:2223.90281
[167]	validation_0-mae:2220.54591
[168]	validation_0-mae:2220.18574
[169]	validation_0-mae:2218.50169
[170]	validation_0-mae:2218.21880
[171]	validation_0-mae:2216.38510
[172]	validation_0-mae:2215.93581
[173]	validation_0-mae:2214.16376
[174]	validation_0-mae:2214.28794
[175]	validation_0-mae:2212.76101
[176]	validation_0-mae:2211.29292
[177]	validation_0-mae:2210.68690
[178]	validation_0-mae:2208.15083
[179]	validation_0-mae:2206.83789
[180]	validation_0-mae:2207.22849
[181]	validation_0-mae:2207.31903
[182]	validation_0-mae:2203.91107
[183]	validation_0-mae:2200.44041
[184]	validation_0-mae:2198.84600
[185]	validation_0-mae:2198.14777
[186]	validation_0-mae:2196.85076
[187]	validation_0-mae:2195.83511
[188]	validation_0-mae:2195.63283
[189]	validation_0-mae:2195.84778
[190]	validation_0-mae:2195.57272
[191]	validation_0-mae:2192.61849
[192]	validation_0-mae:2191.24728
[193]	validation_0-mae:2189.71011
[194]	validation_0-mae:2188.73502
[195]	validation_0-mae:2187.02662
[196]	validation_0-mae:2186.30430
[197]	validation_0-mae:2187.33904
[198]	validation_0-mae:2187.90866
[199]	validation_0-mae:2186.12018
[200]	validation_0-mae:2185.10325
[201]	validation_0-mae:2184.51529
[202]	validation_0-mae:2184.35605
[203]	validation_0-mae:2184.16121
[204]	validation_0-mae:2184.06295
[205]	validation_0-mae:2185.52845
[206]	validation_0-mae:2184.11952
[207]	validation_0-mae:2183.65592
[208]	validation_0-mae:2183.06973
[209]	validation_0-mae:2182.31739
[210]	validation_0-mae:2181.25774
[211]	validation_0-mae:2179.53151
[212]	validation_0-mae:2179.26456
[213]	validation_0-mae:2178.78023
[214]	validation_0-mae:2177.48620
[215]	validation_0-mae:2176.58156
[216]	validation_0-mae:2176.43931
[217]	validation_0-mae:2175.71863
[218]	validation_0-mae:2174.93311
[219]	validation_0-mae:2174.42165
[220]	validation_0-mae:2173.51041
[221]	validation_0-mae:2173.36109
[222]	validation_0-mae:2172.00782
[223]	validation_0-mae:2172.60404
[224]	validation_0-mae:2172.76896
[225]	validation_0-mae:2172.64079
[226]	validation_0-mae:2171.57115
[227]	validation_0-mae:2171.17361
[228]	validation_0-mae:2170.46168
[229]	validation_0-mae:2169.10470
[230]	validation_0-mae:2167.85554
[231]	validation_0-mae:2167.09364
[232]	validation_0-mae:2166.84158
[233]	validation_0-mae:2166.96367
[234]	validation_0-mae:2166.32888
[235]	validation_0-mae:2165.86886
[236]	validation_0-mae:2165.46785
[237]	validation_0-mae:2164.99598
[238]	validation_0-mae:2164.70503
[239]	validation_0-mae:2165.09954
[240]	validation_0-mae:2163.88852
[241]	validation_0-mae:2164.00187
[242]	validation_0-mae:2162.32356
[243]	validation_0-mae:2162.06324
[244]	validation_0-mae:2162.25002
[245]	validation_0-mae:2162.53605
[246]	validation_0-mae:2161.56744
[247]	validation_0-mae:2160.68574
[248]	validation_0-mae:2160.56025
[249]	validation_0-mae:2160.31376
[250]	validation_0-mae:2159.73371
[251]	validation_0-mae:2159.29579
[252]	validation_0-mae:2159.43496
[253]	validation_0-mae:2158.88092
[254]	validation_0-mae:2159.30299
[255]	validation_0-mae:2159.10910
[256]	validation_0-mae:2159.32729
[257]	validation_0-mae:2157.57442
[258]	validation_0-mae:2157.46226
[259]	validation_0-mae:2155.96860
[260]	validation_0-mae:2155.53451
[261]	validation_0-mae:2155.97193
[262]	validation_0-mae:2155.00643
[263]	validation_0-mae:2155.48172
[264]	validation_0-mae:2155.48977
[265]	validation_0-mae:2156.00306
[266]	validation_0-mae:2155.96937
[267]	validation_0-mae:2155.94428
[268]	validation_0-mae:2154.68410
[269]	validation_0-mae:2155.32823
[270]	validation_0-mae:2155.51032
[271]	validation_0-mae:2154.64820
[272]	validation_0-mae:2154.82958
[273]	validation_0-mae:2154.74508
[274]	validation_0-mae:2154.64709
[275]	validation_0-mae:2154.69310
[276]	validation_0-mae:2154.96427
[277]	validation_0-mae:2155.04304
[278]	validation_0-mae:2155.55053
[279]	validation_0-mae:2156.53707
[280]	validation_0-mae:2156.52972
[281]	validation_0-mae:2156.07762
[282]	validation_0-mae:2155.69781
[283]	validation_0-mae:2154.39704
[284]	validation_0-mae:2153.74706
[285]	validation_0-mae:2154.05253
[286]	validation_0-mae:2154.22128
[287]	validation_0-mae:2154.16950
[288]	validation_0-mae:2153.74724
[289]	validation_0-mae:2154.05020
[290]	validation_0-mae:2154.03476
[291]	validation_0-mae:2153.54950
[292]	validation_0-mae:2153.67931
[293]	validation_0-mae:2153.23432
[294]	validation_0-mae:2152.33033
[295]	validation_0-mae:2152.45172
[296]	validation_0-mae:2152.12137
[297]	validation_0-mae:2152.09851
[298]	validation_0-mae:2150.72577
[299]	validation_0-mae:2150.41521
[300]	validation_0-mae:2150.50285
[301]	validation_0-mae:2149.77773
[302]	validation_0-mae:2149.78489
[303]	validation_0-mae:2149.90205
[304]	validation_0-mae:2149.85278
[305]	validation_0-mae:2149.78997
[306]	validation_0-mae:2149.41949
[307]	validation_0-mae:2149.60881
[308]	validation_0-mae:2149.32999
[309]	validation_0-mae:2149.38867
[310]	validation_0-mae:2149.74122
[311]	validation_0-mae:2150.79287
[312]	validation_0-mae:2150.71130
[313]	validation_0-mae:2150.69909
[314]	validation_0-mae:2150.92862
[315]	validation_0-mae:2150.30365
[316]	validation_0-mae:2150.65361
[317]	validation_0-mae:2150.68020
[318]	validation_0-mae:2150.05167
[319]	validation_0-mae:2150.64133
[320]	validation_0-mae:2150.07241
[321]	validation_0-mae:2150.02585
[322]	validation_0-mae:2150.19909
[323]	validation_0-mae:2150.28997
[324]	validation_0-mae:2151.13189
[325]	validation_0-mae:2149.07437
[326]	validation_0-mae:2149.76964
[327]	validation_0-mae:2148.41051
[328]	validation_0-mae:2147.85807
[329]	validation_0-mae:2147.82203
[330]	validation_0-mae:2147.51335
[331]	validation_0-mae:2147.37290
[332]	validation_0-mae:2147.53871
[333]	validation_0-mae:2147.87759
[334]	validation_0-mae:2147.72196
[335]	validation_0-mae:2147.85233
[336]	validation_0-mae:2147.56152
[337]	validation_0-mae:2147.06696
[338]	validation_0-mae:2147.05349
[339]	validation_0-mae:2146.72766
[340]	validation_0-mae:2146.90662
[0]	validation_0-mae:12471.11480
[1]	validation_0-mae:11758.25421
[2]	validation_0-mae:11110.90834
[3]	validation_0-mae:10510.25460
[4]	validation_0-mae:9979.92349
[5]	validation_0-mae:9495.20174
[6]	validation_0-mae:9046.05113
[7]	validation_0-mae:8619.68774
[8]	validation_0-mae:8231.41127
[9]	validation_0-mae:7896.26799
[10]	validation_0-mae:7593.17425
[11]	validation_0-mae:7302.39114
[12]	validation_0-mae:7037.12904
[13]	validation_0-mae:6782.59576

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[0]	validation_0-mae:12463.57112
[1]	validation_0-mae:11734.69332
[2]	validation_0-mae:11075.01852
[3]	validation_0-mae:10459.69261
[4]	validation_0-mae:9918.84029
[5]	validation_0-mae:9408.05526
[6]	validation_0-mae:8978.36559
[7]	validation_0-mae:8579.10341
[8]	validation_0-mae:8202.98690
[9]	validation_0-mae:7867.44808
[10]	validation_0-mae:7574.86085
[11]	validation_0-mae:7271.00724
[12]	validation_0-mae:6997.85014
[13]	validation_0-mae:6745.04986
[14]	validation_0-mae:6514.99498
[15]	validation_0-mae:6277.47021
[16]	validation_0-mae:6061.24857
[17]	validation_0-mae:5858.51418
[18]	validation_0-mae:5641.24941
[19]	validation_0-mae:5474.75248
[20]	validation_0-mae:5293.91495
[21]	validation_0-mae:5122.22284
[22]	validation_0-mae:4967.34836
[23]	validation_0-mae:4832.36656
[24]	validation_0-mae:4710.54641
[25]	validation_0-mae:4592.10075
[26]	validation_0-mae:4479.26589
[27]	validation_0-mae:4365.43322
[28]	validation_0-mae:4257.25860
[29]	validation_0-mae:4157.54355
[30]	validation_0-mae:4071.37128
[31]	validation_0-mae:3996.06862
[32]	validation_0-mae:3910.70380
[33]	validation_0-mae:3837.41909
[34]	validation_0-mae:3766.09742
[35]	validation_0-mae:3709.83389
[36]	validation_0-mae:3659.66605
[37]	validation_0-mae:3602.94533
[38]	validation_0-mae:3547.12146
[39]	validation_0-mae:3476.33689
[40]	validation_0-mae:3430.34653
[41]	validation_0-mae:3389.05289
[42]	validation_0-mae:3344.94353
[43]	validation_0-mae:3303.43495
[44]	validation_0-mae:3268.15843
[45]	validation_0-mae:3238.06598
[46]	validation_0-mae:3189.43178
[47]	validation_0-mae:3159.27873
[48]	validation_0-mae:3129.91370
[49]	validation_0-mae:3104.26267
[50]	validation_0-mae:3080.71675
[51]	validation_0-mae:3043.05173
[52]	validation_0-mae:3022.50046
[53]	validation_0-mae:3000.34722
[54]	validation_0-mae:2975.98109
[55]	validation_0-mae:2956.16018
[56]	validation_0-mae:2931.16751
[57]	validation_0-mae:2902.66675
[58]	validation_0-mae:2887.02671
[0]	validation_0-mae:12387.33212
[1]	validation_0-mae:11614.69098
[2]	validation_0-mae:10904.90538
[3]	validation_0-mae:10263.20312
[4]	validation_0-mae:9704.99801
[5]	validation_0-mae:9170.17528
[6]	validation_0-mae:8688.26440
[7]	validation_0-mae:8277.40415
[8]	validation_0-mae:7889.87689
[9]	validation_0-mae:7542.24778
[10]	validation_0-mae:7220.18789
[11]	validation_0-mae:6917.15466
[12]	validation_0-mae:6647.95151
[13]	validation_0-mae:6424.18168
[14]	validation_0-mae:6168.21533
[15]	validation_0-mae:5936.65275
[16]	validation_0-mae:5718.64942
[17]	validation_0-mae:5505.66483
[18]	validation_0-mae:5323.87446
[19]	validation_0-mae:5144.61254
[20]	validation_0-mae:4984.45679
[21]	validation_0-mae:4837.90859
[22]	validation_0-mae:4688.71384
[23]	validation_0-mae:4555.03213
[24]	validation_0-mae:4427.90237
[25]	validation_0-mae:4321.36870
[26]	validation_0-mae:4211.76735
[27]	validation_0-mae:4116.66928
[28]	validation_0-mae:4013.03795
[29]	validation_0-mae:3923.62265
[30]	validation_0-mae:3838.18262
[31]	validation_0-mae:3755.98410
[32]	validation_0-mae:3692.64860
[33]	validation_0-mae:3618.43321
[34]	validation_0-mae:3554.82359
[35]	validation_0-mae:3500.41387
[36]	validation_0-mae:3445.37215
[37]	validation_0-mae:3391.33569

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[38]	validation_0-mae:3344.49207
[39]	validation_0-mae:3303.33866
[40]	validation_0-mae:3241.79736
[41]	validation_0-mae:3197.81540
[42]	validation_0-mae:3136.16039
[43]	validation_0-mae:3102.26386
[44]	validation_0-mae:3070.22972
[45]	validation_0-mae:3021.67662
[46]	validation_0-mae:2992.62008
[47]	validation_0-mae:2963.10084
[48]	validation_0-mae:2933.56660
[49]	validation_0-mae:2909.86224
[50]	validation_0-mae:2877.49604
[51]	validation_0-mae:2840.33551
[52]	validation_0-mae:2821.86873
[53]	validation_0-mae:2804.21710
[54]	validation_0-mae:2785.27917
[55]	validation_0-mae:2769.18314
[56]	validation_0-mae:2753.09489
[57]	validation_0-mae:2729.20791
[58]	validation_0-mae:2714.11963
[59]	validation_0-mae:2701.82417
[60]	validation_0-mae:2675.91666
[61]	validation_0-mae:2663.90662
[62]	validation_0-mae:2651.19443
[63]	validation_0-mae:2637.18992
[64]	validation_0-mae:2625.70032
[65]	validation_0-mae:2618.18323
[66]	validation_0-mae:2605.89537
[67]	validation_0-mae:2585.09723
[68]	validation_0-mae:2574.51622
[69]	validation_0-mae:2566.63679
[70]	validation_0-mae:2555.25817
[71]	validation_0-mae:2538.37920
[72]	validation_0-mae:2526.12721
[73]	validation_0-mae:2512.16970
[74]	validation_0-mae:2505.61328
[75]	validation_0-mae:2494.98627
[76]	validation_0-mae:2489.40495
[77]	validation_0-mae:2476.93991
[78]	validation_0-mae:2468.00286
[79]	validation_0-mae:2460.88267
[80]	validation_0-mae:2451.59849
[81]	validation_0-mae:2442.84053
[82]	validation_0-mae:2431.89600
[83]	validation_0-mae:2427.53516
[84]	validation_0-mae:2422.33658
[85]	validation_0-mae:2415.36822
[86]	validation_0-mae:2407.93869
[87]	validation_0-mae:2400.43403
[88]	validation_0-mae:2392.03653
[89]	validation_0-mae:2389.00927
[90]	validation_0-mae:2382.52111
[91]	validation_0-mae:2380.41031
[92]	validation_0-mae:2375.71963
[93]	validation_0-mae:2371.89085
[94]	validation_0-mae:2365.65272
[95]	validation_0-mae:2363.68953
[96]	validation_0-mae:2359.03493
[97]	validation_0-mae:2352.23629
[98]	validation_0-mae:2349.08885
[99]	validation_0-mae:2343.72718
[100]	validation_0-mae:2341.16135
[101]	validation_0-mae:2336.17935
[102]	validation_0-mae:2333.58042
[103]	validation_0-mae:2328.14114
[104]	validation_0-mae:2319.99692
[105]	validation_0-mae:2316.00962
[106]	validation_0-mae:2313.72774
[107]	validation_0-mae:2308.75247
[108]	validation_0-mae:2305.98260
[109]	validation_0-mae:2301.33148
[110]	validation_0-mae:2298.77648
[111]	validation_0-mae:2294.34070
[112]	validation_0-mae:2290.18585
[113]	validation_0-mae:2287.00880
[114]	validation_0-mae:2285.56529
[115]	validation_0-mae:2280.70191
[116]	validation_0-mae:2279.22558
[117]	validation_0-mae:2277.61186
[118]	validation_0-mae:2275.28685
[119]	validation_0-mae:2274.52333
[120]	validation_0-mae:2270.34092
[121]	validation_0-mae:2268.60187
[122]	validation_0-mae:2264.76922
[123]	validation_0-mae:2263.03857
[124]	validation_0-mae:2263.44036
[125]	validation_0-mae:2262.75507
[126]	validation_0-mae:2261.17048
[127]	validation_0-mae:2256.61688
[128]	validation_0-mae:2253.09792
[129]	validation_0-mae:2252.75347
[130]	validation_0-mae:2250.03676
[131]	validation_0-mae:2247.85490
[132]	validation_0-mae:2247.01676
[133]	validation_0-mae:2246.35803
[134]	validation_0-mae:2242.16459
[135]	validation_0-mae:2241.26202
[136]	validation_0-mae:2241.34844
[137]	validation_0-mae:2241.35870
[138]	validation_0-mae:2242.17127
[139]	validation_0-mae:2241.73010
[140]	validation_0-mae:2240.07639
[141]	validation_0-mae:2239.84243
[142]	validation_0-mae:2234.72693
[143]	validation_0-mae:2232.65995
[144]	validation_0-mae:2230.25897
[145]	validation_0-mae:2228.18714
[146]	validation_0-mae:2228.08182
[147]	validation_0-mae:2226.87018
[148]	validation_0-mae:2226.89784
[149]	validation_0-mae:2224.61900
[150]	validation_0-mae:2222.69655
[151]	validation_0-mae:2216.83322
[152]	validation_0-mae:2217.39915
[153]	validation_0-mae:2212.44114
[154]	validation_0-mae:2212.86556
[155]	validation_0-mae:2211.84616
[156]	validation_0-mae:2211.83704
[157]	validation_0-mae:2213.53331
[158]	validation_0-mae:2213.65875
[159]	validation_0-mae:2212.67548
[160]	validation_0-mae:2212.60415
[161]	validation_0-mae:2212.20115
[162]	validation_0-mae:2210.83315
[163]	validation_0-mae:2209.96635
[164]	validation_0-mae:2208.52983
[165]	validation_0-mae:2206.74764
[166]	validation_0-mae:2205.97881
[167]	validation_0-mae:2204.64569
[168]	validation_0-mae:2205.56020
[169]	validation_0-mae:2205.84247
[170]	validation_0-mae:2204.88874
[171]	validation_0-mae:2206.20484
[172]	validation_0-mae:2204.54075
[173]	validation_0-mae:2205.41681
[174]	validation_0-mae:2205.78237
[175]	validation_0-mae:2205.21896
[176]	validation_0-mae:2202.45074
[177]	validation_0-mae:2202.79960
[178]	validation_0-mae:2200.96549
[179]	validation_0-mae:2201.10318
[180]	validation_0-mae:2200.67491
[181]	validation_0-mae:2201.16743
[182]	validation_0-mae:2198.72755
[183]	validation_0-mae:2198.95472
[184]	validation_0-mae:2199.22906
[185]	validation_0-mae:2199.19542
[186]	validation_0-mae:2198.32625
[187]	validation_0-mae:2194.66558
[188]	validation_0-mae:2194.55269
[189]	validation_0-mae:2192.59086
[190]	validation_0-mae:2192.51408
[191]	validation_0-mae:2192.52287
[192]	validation_0-mae:2192.71937
[193]	validation_0-mae:2192.31957
[194]	validation_0-mae:2190.62122
[195]	validation_0-mae:2189.97290
[196]	validation_0-mae:2189.39833
[197]	validation_0-mae:2189.67053
[198]	validation_0-mae:2189.82735
[199]	validation_0-mae:2190.28346
[200]	validation_0-mae:2189.08358
[201]	validation_0-mae:2189.37568
[202]	validation_0-mae:2189.70780
[203]	validation_0-mae:2190.52033
[204]	validation_0-mae:2189.47547
[205]	validation_0-mae:2189.08070
[206]	validation_0-mae:2188.59479
[207]	validation_0-mae:2188.37680
[208]	validation_0-mae:2187.68183
[209]	validation_0-mae:2186.41558
[210]	validation_0-mae:2186.30287
[211]	validation_0-mae:2185.28698
[212]	validation_0-mae:2186.75740
[213]	validation_0-mae:2186.48718
[214]	validation_0-mae:2185.84730
[215]	validation_0-mae:2185.73696
[216]	validation_0-mae:2184.85087
[217]	validation_0-mae:2184.89885
[218]	validation_0-mae:2182.61300
[219]	validation_0-mae:2180.57864
[220]	validation_0-mae:2178.93745
[221]	validation_0-mae:2177.53720
[222]	validation_0-mae:2177.09081
[223]	validation_0-mae:2175.42896
[224]	validation_0-mae:2172.92529
[225]	validation_0-mae:2173.21834
[226]	validation_0-mae:2171.87693
[227]	validation_0-mae:2170.81271
[228]	validation_0-mae:2171.14046
[229]	validation_0-mae:2169.50163
[230]	validation_0-mae:2168.21513
[231]	validation_0-mae:2167.10517
[232]	validation_0-mae:2166.02534
[233]	validation_0-mae:2165.94042
[234]	validation_0-mae:2163.20395
[235]	validation_0-mae:2163.32815
[236]	validation_0-mae:2163.09843
[237]	validation_0-mae:2162.04678
[238]	validation_0-mae:2161.45149
[239]	validation_0-mae:2161.31154
[240]	validation_0-mae:2159.82934
[241]	validation_0-mae:2160.02686
[242]	validation_0-mae:2159.53326
[243]	validation_0-mae:2159.17627
[244]	validation_0-mae:2159.08464
[245]	validation_0-mae:2159.56897
[246]	validation_0-mae:2159.04974
[247]	validation_0-mae:2157.81662
[248]	validation_0-mae:2157.82466
[249]	validation_0-mae:2157.30730
[250]	validation_0-mae:2156.23921
[251]	validation_0-mae:2155.53217
[252]	validation_0-mae:2154.73900
[253]	validation_0-mae:2154.89014
[254]	validation_0-mae:2153.85954
[255]	validation_0-mae:2153.74362
[256]	validation_0-mae:2154.06905
[257]	validation_0-mae:2153.05858
[258]	validation_0-mae:2153.23252
[259]	validation_0-mae:2153.22097
[260]	validation_0-mae:2152.36322
[261]	validation_0-mae:2151.65596
[262]	validation_0-mae:2151.02920
[263]	validation_0-mae:2149.04868
[264]	validation_0-mae:2148.98246
[265]	validation_0-mae:2146.56481
[266]	validation_0-mae:2146.33254
[267]	validation_0-mae:2145.55761
[268]	validation_0-mae:2145.85784
[269]	validation_0-mae:2145.55727
[270]	validation_0-mae:2143.81836
[271]	validation_0-mae:2143.47962
[272]	validation_0-mae:2143.83161
[273]	validation_0-mae:2141.58853
[274]	validation_0-mae:2141.71022
[275]	validation_0-mae:2139.64631
[276]	validation_0-mae:2139.86689
[277]	validation_0-mae:2139.49498
[278]	validation_0-mae:2138.16987
[279]	validation_0-mae:2137.51473
[280]	validation_0-mae:2136.65675
[281]	validation_0-mae:2136.17927
[282]	validation_0-mae:2136.31231
[283]	validation_0-mae:2136.78875
[284]	validation_0-mae:2137.49476
[285]	validation_0-mae:2137.76485
[286]	validation_0-mae:2138.08352
[287]	validation_0-mae:2137.16659
[288]	validation_0-mae:2135.26019
[289]	validation_0-mae:2135.17262
[290]	validation_0-mae:2135.13943
[291]	validation_0-mae:2135.54070
[292]	validation_0-mae:2135.65265
[293]	validation_0-mae:2136.37103
[294]	validation_0-mae:2134.74256
[295]	validation_0-mae:2133.98584
[296]	validation_0-mae:2131.16009
[297]	validation_0-mae:2131.09201
[298]	validation_0-mae:2130.80264
[299]	validation_0-mae:2128.79579
[300]	validation_0-mae:2128.36573
[301]	validation_0-mae:2128.43490
[302]	validation_0-mae:2127.87430
[303]	validation_0-mae:2128.27159
[304]	validation_0-mae:2128.46219
[305]	validation_0-mae:2128.62858
[306]	validation_0-mae:2128.54345
[307]	validation_0-mae:2128.23686
[308]	validation_0-mae:2127.40923
[309]	validation_0-mae:2127.54915
[310]	validation_0-mae:2126.97000
[311]	validation_0-mae:2126.88099
[312]	validation_0-mae:2124.75910
[313]	validation_0-mae:2125.23718
[314]	validation_0-mae:2124.53918
[315]	validation_0-mae:2124.17207
[316]	validation_0-mae:2122.80375
[317]	validation_0-mae:2122.32516
[318]	validation_0-mae:2122.19464
[319]	validation_0-mae:2121.55492
[320]	validation_0-mae:2121.75331
[321]	validation_0-mae:2121.89513
[322]	validation_0-mae:2121.93335
[323]	validation_0-mae:2121.53152
[324]	validation_0-mae:2121.19430
[325]	validation_0-mae:2121.51066
[326]	validation_0-mae:2120.75871
[327]	validation_0-mae:2119.58683
[328]	validation_0-mae:2119.62382
[329]	validation_0-mae:2119.89782
[330]	validation_0-mae:2119.72826
[331]	validation_0-mae:2119.45465
[332]	validation_0-mae:2119.32116
[333]	validation_0-mae:2120.14053
[334]	validation_0-mae:2120.06007
[335]	validation_0-mae:2120.04481
[336]	validation_0-mae:2120.11498
[337]	validation_0-mae:2118.80449
[338]	validation_0-mae:2118.37828
[339]	validation_0-mae:2117.79604
[340]	validation_0-mae:2118.03875
[341]	validation_0-mae:2118.10553
[342]	validation_0-mae:2117.74461
[343]	validation_0-mae:2117.84478
[344]	validation_0-mae:2117.12659
[345]	validation_0-mae:2116.98378
[346]	validation_0-mae:2117.11795
[347]	validation_0-mae:2116.87546
[348]	validation_0-mae:2116.97648
[349]	validation_0-mae:2116.38475
[350]	validation_0-mae:2115.45603
[351]	validation_0-mae:2115.52483
[352]	validation_0-mae:2115.65108
[353]	validation_0-mae:2114.95805
[354]	validation_0-mae:2114.85548
[355]	validation_0-mae:2114.07242
[356]	validation_0-mae:2114.09939
[357]	validation_0-mae:2113.93566
[358]	validation_0-mae:2113.80112
[359]	validation_0-mae:2113.82284
[360]	validation_0-mae:2113.59646
[361]	validation_0-mae:2112.31097
[362]	validation_0-mae:2112.27668
[363]	validation_0-mae:2111.58604
[364]	validation_0-mae:2111.43231
[365]	validation_0-mae:2111.56978
[366]	validation_0-mae:2111.70168
[367]	validation_0-mae:2112.05475
[368]	validation_0-mae:2111.47875
[369]	validation_0-mae:2110.49554
[370]	validation_0-mae:2110.19864
[371]	validation_0-mae:2109.87658
[372]	validation_0-mae:2110.20579
[373]	validation_0-mae:2109.97663
[374]	validation_0-mae:2110.30799
[375]	validation_0-mae:2110.14381
[376]	validation_0-mae:2109.82238
[377]	validation_0-mae:2109.64915
[378]	validation_0-mae:2109.77172
[379]	validation_0-mae:2110.16126
[380]	validation_0-mae:2109.97375
[381]	validation_0-mae:2109.37595
[382]	validation_0-mae:2109.19421
[383]	validation_0-mae:2109.84973
[384]	validation_0-mae:2109.61595
[385]	validation_0-mae:2109.40032
[386]	validation_0-mae:2109.03661
[387]	validation_0-mae:2108.78927
[388]	validation_0-mae:2108.40243
[389]	validation_0-mae:2108.35209
[390]	validation_0-mae:2107.88837
[391]	validation_0-mae:2107.37542
[392]	validation_0-mae:2107.18881
[393]	validation_0-mae:2106.80505
[394]	validation_0-mae:2106.71307
[395]	validation_0-mae:2106.06295
[396]	validation_0-mae:2106.27914
[397]	validation_0-mae:2106.20061
[398]	validation_0-mae:2105.54925
[399]	validation_0-mae:2105.58825
[400]	validation_0-mae:2105.62433
[401]	validation_0-mae:2105.21101
[402]	validation_0-mae:2104.92957
[403]	validation_0-mae:2103.22622
[404]	validation_0-mae:2103.74424
[405]	validation_0-mae:2102.76576
[406]	validation_0-mae:2102.45700
[407]	validation_0-mae:2101.79438
[408]	validation_0-mae:2101.01880
[409]	validation_0-mae:2101.61189
[410]	validation_0-mae:2100.71200
[411]	validation_0-mae:2100.50315
[412]	validation_0-mae:2100.04849
[413]	validation_0-mae:2099.94127
[414]	validation_0-mae:2099.44753
[415]	validation_0-mae:2100.03151
[416]	validation_0-mae:2099.72899
[417]	validation_0-mae:2099.85164
[418]	validation_0-mae:2099.53979
[419]	validation_0-mae:2098.89447
[420]	validation_0-mae:2098.63809
[421]	validation_0-mae:2098.67866
[422]	validation_0-mae:2097.66411
[423]	validation_0-mae:2096.84636
[424]	validation_0-mae:2097.00772
[425]	validation_0-mae:2096.77969
[426]	validation_0-mae:2096.33916
[427]	validation_0-mae:2096.26339
[428]	validation_0-mae:2095.14873
[429]	validation_0-mae:2095.10409
[430]	validation_0-mae:2095.47467
[431]	validation_0-mae:2094.56244
[432]	validation_0-mae:2094.43091
[433]	validation_0-mae:2094.52322
[434]	validation_0-mae:2094.60299
[435]	validation_0-mae:2095.09985
[436]	validation_0-mae:2095.21457
[437]	validation_0-mae:2095.12806
[438]	validation_0-mae:2095.23336
[439]	validation_0-mae:2094.71724
[440]	validation_0-mae:2094.40722
[441]	validation_0-mae:2095.10023
[442]	validation_0-mae:2095.09014
[443]	validation_0-mae:2095.40264
[444]	validation_0-mae:2094.71860
[445]	validation_0-mae:2093.59885
[446]	validation_0-mae:2093.43233
[447]	validation_0-mae:2093.50670
[448]	validation_0-mae:2093.50153
[449]	validation_0-mae:2093.93975
[450]	validation_0-mae:2094.21749
[451]	validation_0-mae:2093.95315
[452]	validation_0-mae:2093.43409
[453]	validation_0-mae:2093.50860
[454]	validation_0-mae:2093.49725
[455]	validation_0-mae:2093.46035
[456]	validation_0-mae:2093.70795
[457]	validation_0-mae:2093.88441
[458]	validation_0-mae:2093.95203
[459]	validation_0-mae:2094.30620
[460]	validation_0-mae:2094.37884
[461]	validation_0-mae:2094.51321
[462]	validation_0-mae:2094.44128
[463]	validation_0-mae:2094.82877
[464]	validation_0-mae:2094.84699
[465]	validation_0-mae:2095.25142
[466]	validation_0-mae:2095.05966
[467]	validation_0-mae:2095.45021
[468]	validation_0-mae:2095.59683
[469]	validation_0-mae:2095.63459
[470]	validation_0-mae:2095.64957
[471]	validation_0-mae:2095.10026
[472]	validation_0-mae:2095.26125
[473]	validation_0-mae:2095.27143
[474]	validation_0-mae:2094.88041
[475]	validation_0-mae:2094.97552
[476]	validation_0-mae:2094.71576
[477]	validation_0-mae:2094.79795
[478]	validation_0-mae:2094.49404
[479]	validation_0-mae:2094.02324
[480]	validation_0-mae:2093.84186
[481]	validation_0-mae:2093.77637
[482]	validation_0-mae:2093.72418
[483]	validation_0-mae:2093.71273
[484]	validation_0-mae:2092.78846
[485]	validation_0-mae:2091.75751
[486]	validation_0-mae:2090.46678
[487]	validation_0-mae:2090.78255
[488]	validation_0-mae:2090.64853
[489]	validation_0-mae:2091.12101
[490]	validation_0-mae:2090.86293
[491]	validation_0-mae:2090.68751
[492]	validation_0-mae:2090.22265
[493]	validation_0-mae:2089.46340
[494]	validation_0-mae:2088.49159
[495]	validation_0-mae:2087.96898
[496]	validation_0-mae:2087.80990
[497]	validation_0-mae:2087.92603
[498]	validation_0-mae:2087.98810
[499]	validation_0-mae:2088.11433
[500]	validation_0-mae:2087.17398
[501]	validation_0-mae:2087.12958
[502]	validation_0-mae:2087.13500
[503]	validation_0-mae:2086.95573
[504]	validation_0-mae:2087.03812
[505]	validation_0-mae:2086.38678
[506]	validation_0-mae:2086.39207
[507]	validation_0-mae:2086.50114
[508]	validation_0-mae:2086.39297
[509]	validation_0-mae:2086.49413
[510]	validation_0-mae:2086.28323
[511]	validation_0-mae:2086.52792
[512]	validation_0-mae:2086.18665
[513]	validation_0-mae:2086.06686
[514]	validation_0-mae:2086.13251
[515]	validation_0-mae:2085.65690
[516]	validation_0-mae:2085.72467
[517]	validation_0-mae:2086.04420
[518]	validation_0-mae:2084.93104
[519]	validation_0-mae:2084.66773
[520]	validation_0-mae:2084.83612
[521]	validation_0-mae:2084.92050
[522]	validation_0-mae:2084.87330
[523]	validation_0-mae:2085.10203
[524]	validation_0-mae:2085.56457
[525]	validation_0-mae:2086.00719
[526]	validation_0-mae:2086.45681
[527]	validation_0-mae:2086.60002
[528]	validation_0-mae:2086.52509
[529]	validation_0-mae:2086.15354
[530]	validation_0-mae:2085.96114
[531]	validation_0-mae:2086.09624
[532]	validation_0-mae:2086.12390
[533]	validation_0-mae:2085.91661
[534]	validation_0-mae:2085.53300
[535]	validation_0-mae:2085.03649
[536]	validation_0-mae:2085.21831
[537]	validation_0-mae:2085.57892
[538]	validation_0-mae:2085.54442
[539]	validation_0-mae:2085.84868
[540]	validation_0-mae:2085.81635
[541]	validation_0-mae:2086.13517
[542]	validation_0-mae:2086.14369
[543]	validation_0-mae:2086.38115
[544]	validation_0-mae:2086.20072
[545]	validation_0-mae:2086.58523
[546]	validation_0-mae:2086.64665
[547]	validation_0-mae:2086.88956
[548]	validation_0-mae:2086.65441
[549]	validation_0-mae:2086.73309
[550]	validation_0-mae:2086.84169
[551]	validation_0-mae:2086.61018
[552]	validation_0-mae:2086.51117
[553]	validation_0-mae:2086.31149
[554]	validation_0-mae:2086.30034
[555]	validation_0-mae:2086.03984
[556]	validation_0-mae:2086.15554
[557]	validation_0-mae:2086.21719
[558]	validation_0-mae:2086.02571
[559]	validation_0-mae:2085.71823
[560]	validation_0-mae:2086.01824
[561]	validation_0-mae:2085.92640
[562]	validation_0-mae:2086.21481
[563]	validation_0-mae:2086.04159
[564]	validation_0-mae:2086.07191
[565]	validation_0-mae:2086.33189
[566]	validation_0-mae:2086.26391
[567]	validation_0-mae:2086.09078
[568]	validation_0-mae:2086.29928
[569]	validation_0-mae:2086.04194
[570]	validation_0-mae:2085.95939
[571]	validation_0-mae:2085.82544
[572]	validation_0-mae:2086.10990
[573]	validation_0-mae:2086.08624
[574]	validation_0-mae:2085.47276
[575]	validation_0-mae:2084.80307
[576]	validation_0-mae:2084.34930
[577]	validation_0-mae:2084.64939
[578]	validation_0-mae:2084.71410
[579]	validation_0-mae:2084.82150
[580]	validation_0-mae:2085.01846
[581]	validation_0-mae:2084.96033
[582]	validation_0-mae:2084.81837
[583]	validation_0-mae:2084.86938
[584]	validation_0-mae:2084.78873
[585]	validation_0-mae:2084.57999
[586]	validation_0-mae:2084.81734
[587]	validation_0-mae:2084.92198
[588]	validation_0-mae:2084.64077
[589]	validation_0-mae:2084.92876
[590]	validation_0-mae:2085.18903
[591]	validation_0-mae:2084.67069
[592]	validation_0-mae:2084.75888
[593]	validation_0-mae:2084.80867
[594]	validation_0-mae:2084.81569
[595]	validation_0-mae:2084.76977
[596]	validation_0-mae:2085.00054
[597]	validation_0-mae:2084.73414
[598]	validation_0-mae:2084.98460
[599]	validation_0-mae:2085.05805
[600]	validation_0-mae:2084.94036
[601]	validation_0-mae:2085.24666
[602]	validation_0-mae:2085.31045
[603]	validation_0-mae:2085.38223
[604]	validation_0-mae:2085.40945
[605]	validation_0-mae:2085.44856
[606]	validation_0-mae:2085.63139
[607]	validation_0-mae:2085.71807
[608]	validation_0-mae:2085.77299
[609]	validation_0-mae:2085.97590
[610]	validation_0-mae:2086.07800
[611]	validation_0-mae:2086.38198
[612]	validation_0-mae:2086.37420
[613]	validation_0-mae:2086.40615
[614]	validation_0-mae:2086.25566
[615]	validation_0-mae:2086.02777
[616]	validation_0-mae:2086.08873
[617]	validation_0-mae:2085.76403
[618]	validation_0-mae:2085.57344
[619]	validation_0-mae:2085.56260
[620]	validation_0-mae:2085.52515
[621]	validation_0-mae:2085.70694
[622]	validation_0-mae:2084.81277
[623]	validation_0-mae:2084.80972
[624]	validation_0-mae:2084.97670
[625]	validation_0-mae:2084.90369
[626]	validation_0-mae:2085.04021
[627]	validation_0-mae:2085.07924

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[3]	validation_0-mae:10859.38132
[4]	validation_0-mae:10462.28241
[5]	validation_0-mae:10110.54371
[6]	validation_0-mae:9810.64156
[7]	validation_0-mae:9553.04782
[8]	validation_0-mae:9331.28807
[9]	validation_0-mae:9129.06096
[0]	validation_0-mae:12389.40528
[1]	validation_0-mae:11599.90271
[2]	validation_0-mae:10885.45845
[3]	validation_0-mae:10238.29249
[4]	validation_0-mae:9670.39078
[5]	validation_0-mae:9189.70625
[6]	validation_0-mae:8738.44210
[7]	validation_0-mae:8328.29158
[8]	validation_0-mae:7964.01478
[9]	validation_0-mae:7598.34368
[10]	validation_0-mae:7268.52801
[11]	validation_0-mae:7009.55700
[12]	validation_0-mae:6711.60394
[13]	validation_0-mae:6442.09532
[14]	validation_0-mae:6203.91334
[15]	validation_0-mae:5967.20728
[16]	validation_0-mae:5764.49203
[17]	validation_0-mae:5557.72905
[18]	validation_0-mae:5372.03395
[19]	validation_0-mae:5177.29641
[20]	validation_0-mae:5011.36106
[21]	validation_0-mae:4861.18545
[22]	validation_0-mae:4709.60644
[23]	validation_0-mae:4584.40508
[24]	validation_0-mae:4450.77730
[25]	validation_0-mae:4322.84687
[26]	validation_0-mae:4216.47577
[27]	validation_0-mae:4118.78309
[28]	validation_0-mae:4024.47848
[29]	validation_0-mae:3920.11758
[30]	validation_0-mae:3841.23030
[31]	validation_0-mae:3743.41787
[32]	validation_0-mae:3672.28396
[33]	validation_0-mae:3603.48284
[34]	validation_0-mae:3548.71415
[35]	validation_0-mae:3492.08632
[36]	validation_0-mae:3446.02200
[37]	validation_0-mae:3388.09419
[38]	validation_0-mae:3338.91637

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[39]	validation_0-mae:3266.20080
[40]	validation_0-mae:3229.00100
[41]	validation_0-mae:3194.30380
[42]	validation_0-mae:3159.45673
[43]	validation_0-mae:3128.39408
[44]	validation_0-mae:3084.02641
[45]	validation_0-mae:3036.56197
[46]	validation_0-mae:3004.65543
[47]	validation_0-mae:2985.58936
[48]	validation_0-mae:2958.05951
[49]	validation_0-mae:2931.60825
[50]	validation_0-mae:2913.18372
[51]	validation_0-mae:2886.82318
[52]	validation_0-mae:2871.90876
[53]	validation_0-mae:2853.32781
[54]	validation_0-mae:2827.02720
[55]	validation_0-mae:2811.54268
[56]	validation_0-mae:2794.52717
[57]	validation_0-mae:2776.25679
[58]	validation_0-mae:2760.53740
[59]	validation_0-mae:2731.23827
[60]	validation_0-mae:2709.54454
[61]	validation_0-mae:2697.23003
[62]	validation_0-mae:2678.02596
[63]	validation_0-mae:2661.49892
[64]	validation_0-mae:2646.72516
[65]	validation_0-mae:2638.73290
[66]	validation_0-mae:2627.70412
[67]	validation_0-mae:2608.66518
[68]	validation_0-mae:2588.51938
[69]	validation_0-mae:2574.24834
[70]	validation_0-mae:2568.58429
[71]	validation_0-mae:2560.78210
[72]	validation_0-mae:2552.18520
[73]	validation_0-mae:2537.50757
[74]	validation_0-mae:2527.60423
[75]	validation_0-mae:2517.18479
[76]	validation_0-mae:2510.31312
[77]	validation_0-mae:2501.55110
[78]	validation_0-mae:2495.12449
[79]	validation_0-mae:2490.38592
[80]	validation_0-mae:2473.19654
[81]	validation_0-mae:2462.90997
[82]	validation_0-mae:2457.13408
[83]	validation_0-mae:2448.14629
[84]	validation_0-mae:2444.04504
[85]	validation_0-mae:2438.82276
[86]	validation_0-mae:2434.71357
[87]	validation_0-mae:2430.51178
[88]	validation_0-mae:2418.78067
[89]	validation_0-mae:2415.36434
[90]	validation_0-mae:2407.03170
[91]	validation_0-mae:2400.91010
[92]	validation_0-mae:2393.15054
[93]	validation_0-mae:2386.97420
[94]	validation_0-mae:2380.48731
[95]	validation_0-mae:2379.45279
[96]	validation_0-mae:2375.01100
[97]	validation_0-mae:2371.60745
[98]	validation_0-mae:2366.75647
[99]	validation_0-mae:2359.14193
[100]	validation_0-mae:2355.71848
[101]	validation_0-mae:2352.32021
[102]	validation_0-mae:2345.39149
[103]	validation_0-mae:2340.77464
[104]	validation_0-mae:2337.42681
[105]	validation_0-mae:2334.63496
[106]	validation_0-mae:2330.62745
[107]	validation_0-mae:2324.11262
[108]	validation_0-mae:2321.55747
[109]	validation_0-mae:2318.41555
[110]	validation_0-mae:2313.86951
[111]	validation_0-mae:2311.33055
[112]	validation_0-mae:2311.09116
[113]	validation_0-mae:2308.85363
[114]	validation_0-mae:2302.95531
[115]	validation_0-mae:2300.42451
[116]	validation_0-mae:2299.68576
[117]	validation_0-mae:2293.91310
[118]	validation_0-mae:2292.48950
[119]	validation_0-mae:2287.67331
[120]	validation_0-mae:2284.87919
[121]	validation_0-mae:2281.66046
[122]	validation_0-mae:2280.83769
[123]	validation_0-mae:2278.75095
[124]	validation_0-mae:2277.07370
[125]	validation_0-mae:2271.16935
[126]	validation_0-mae:2268.70684
[127]	validation_0-mae:2269.32496
[128]	validation_0-mae:2265.05976
[129]	validation_0-mae:2264.88647
[130]	validation_0-mae:2263.16298
[131]	validation_0-mae:2263.92663
[132]	validation_0-mae:2256.78561
[133]	validation_0-mae:2257.25295
[134]	validation_0-mae:2257.02237
[135]	validation_0-mae:2255.90020
[136]	validation_0-mae:2254.52710
[137]	validation_0-mae:2253.57479
[138]	validation_0-mae:2252.06399
[139]	validation_0-mae:2249.86833
[140]	validation_0-mae:2245.04533
[141]	validation_0-mae:2244.10868
[142]	validation_0-mae:2241.57620
[143]	validation_0-mae:2241.58490
[144]	validation_0-mae:2239.85412
[145]	validation_0-mae:2236.08330
[146]	validation_0-mae:2236.12388
[147]	validation_0-mae:2236.44043
[148]	validation_0-mae:2234.67294
[149]	validation_0-mae:2235.16302
[150]	validation_0-mae:2231.13343
[151]	validation_0-mae:2230.93982
[152]	validation_0-mae:2230.87200
[153]	validation_0-mae:2228.57536
[154]	validation_0-mae:2228.70109
[155]	validation_0-mae:2226.30801
[156]	validation_0-mae:2223.28071
[157]	validation_0-mae:2223.59816
[158]	validation_0-mae:2223.46340
[159]	validation_0-mae:2222.46234
[160]	validation_0-mae:2220.14796
[161]	validation_0-mae:2220.35076
[162]	validation_0-mae:2219.06238
[163]	validation_0-mae:2215.38939
[164]	validation_0-mae:2215.44311
[165]	validation_0-mae:2214.26761
[166]	validation_0-mae:2213.88897
[167]	validation_0-mae:2212.08506
[168]	validation_0-mae:2210.70705
[169]	validation_0-mae:2210.09034
[170]	validation_0-mae:2209.95420
[171]	validation_0-mae:2209.33972
[172]	validation_0-mae:2209.94247
[173]	validation_0-mae:2209.70615
[174]	validation_0-mae:2209.37061
[175]	validation_0-mae:2209.80887
[176]	validation_0-mae:2209.72888
[177]	validation_0-mae:2209.02888
[178]	validation_0-mae:2208.55321
[179]	validation_0-mae:2208.24946
[180]	validation_0-mae:2209.69819
[181]	validation_0-mae:2207.96422
[182]	validation_0-mae:2207.07036
[183]	validation_0-mae:2204.59589
[184]	validation_0-mae:2203.60706
[185]	validation_0-mae:2203.15561
[186]	validation_0-mae:2201.10201
[187]	validation_0-mae:2199.64494
[188]	validation_0-mae:2199.39128
[189]	validation_0-mae:2199.70578
[190]	validation_0-mae:2200.33669
[191]	validation_0-mae:2200.01526
[192]	validation_0-mae:2199.35808
[193]	validation_0-mae:2198.15812
[194]	validation_0-mae:2197.94669
[195]	validation_0-mae:2198.28197
[196]	validation_0-mae:2196.10000
[197]	validation_0-mae:2194.61952
[198]	validation_0-mae:2194.47935
[199]	validation_0-mae:2193.93640
[200]	validation_0-mae:2193.19757
[201]	validation_0-mae:2193.57998
[202]	validation_0-mae:2192.62601
[203]	validation_0-mae:2192.54679
[204]	validation_0-mae:2192.33684
[205]	validation_0-mae:2191.25722
[206]	validation_0-mae:2190.30532
[207]	validation_0-mae:2190.00307
[208]	validation_0-mae:2188.76232
[209]	validation_0-mae:2186.85512
[210]	validation_0-mae:2185.89790
[211]	validation_0-mae:2187.43617
[212]	validation_0-mae:2187.79629
[213]	validation_0-mae:2187.16929
[214]	validation_0-mae:2187.39024
[215]	validation_0-mae:2187.71948
[216]	validation_0-mae:2187.95177
[217]	validation_0-mae:2186.62793
[218]	validation_0-mae:2186.74076
[219]	validation_0-mae:2186.16072
[220]	validation_0-mae:2185.65248
[221]	validation_0-mae:2184.78418
[222]	validation_0-mae:2184.52456
[223]	validation_0-mae:2183.89354
[224]	validation_0-mae:2184.07867
[225]	validation_0-mae:2182.55675
[226]	validation_0-mae:2183.50684
[227]	validation_0-mae:2184.24095
[228]	validation_0-mae:2182.47809
[229]	validation_0-mae:2181.89675
[230]	validation_0-mae:2181.70664
[231]	validation_0-mae:2182.04064
[232]	validation_0-mae:2182.23900
[233]	validation_0-mae:2180.53744
[234]	validation_0-mae:2179.48315
[235]	validation_0-mae:2178.87842
[236]	validation_0-mae:2178.92282
[237]	validation_0-mae:2178.68438
[238]	validation_0-mae:2177.61389
[239]	validation_0-mae:2177.62829
[240]	validation_0-mae:2178.44802
[241]	validation_0-mae:2178.66636
[242]	validation_0-mae:2177.47237
[243]	validation_0-mae:2177.18485
[244]	validation_0-mae:2176.46403
[245]	validation_0-mae:2177.12947
[246]	validation_0-mae:2176.87536
[247]	validation_0-mae:2175.95334
[248]	validation_0-mae:2176.45224
[249]	validation_0-mae:2176.38043
[0]	validation_0-mae:12446.02795
[1]	validation_0-mae:11701.16267
[2]	validation_0-mae:11043.31881
[3]	validation_0-mae:10440.59017
[4]	validation_0-mae:9909.31604
[5]	validation_0-mae:9427.18793
[6]	validation_0-mae:8992.40384
[7]	validation_0-mae:8600.52744
[8]	validation_0-mae:8235.44425
[9]	validation_0-mae:7880.52396
[10]	validation_0-mae:7558.10667
[11]	validation_0-mae:7262.70167
[12]	validation_0-mae:6996.11392
[13]	validation_0-mae:6737.90268
[14]	validation_0-mae:6488.88918
[15]	validation_0-mae:6257.72328
[16]	validation_0-mae:6036.26317
[17]	validation_0-mae:5828.73117
[18]	validation_0-mae:5620.78054
[19]	validation_0-mae:5438.76025
[20]	validation_0-mae:5276.90490
[21]	validation_0-mae:5105.41054
[22]	validation_0-mae:4960.56217
[23]	validation_0-mae:4832.44463
[24]	validation_0-mae:4700.51655
[25]	validation_0-mae:4593.42058
[26]	validation_0-mae:4467.01647
[27]	validation_0-mae:4360.30316
[28]	validation_0-mae:4244.44044
[29]	validation_0-mae:4150.20369
[30]	validation_0-mae:4059.55529
[31]	validation_0-mae:3965.86066
[32]	validation_0-mae:3869.98039
[33]	validation_0-mae:3810.33235
[34]	validation_0-mae:3730.06293
[35]	validation_0-mae:3680.04381
[36]	validation_0-mae:3611.07911
[37]	validation_0-mae:3556.14469
[38]	validation_0-mae:3499.75459
[39]	validation_0-mae:3435.95894

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[40]	validation_0-mae:3389.88733
[41]	validation_0-mae:3341.37022
[42]	validation_0-mae:3298.71488
[43]	validation_0-mae:3260.76476
[44]	validation_0-mae:3217.38614
[45]	validation_0-mae:3181.80603
[46]	validation_0-mae:3148.60980
[47]	validation_0-mae:3118.97059
[48]	validation_0-mae:3091.13861
[49]	validation_0-mae:3056.12744
[50]	validation_0-mae:3024.31521
[51]	validation_0-mae:2996.56699
[52]	validation_0-mae:2976.87836
[53]	validation_0-mae:2952.96086
[54]	validation_0-mae:2929.88772
[55]	validation_0-mae:2907.20476
[56]	validation_0-mae:2886.07371
[57]	validation_0-mae:2872.45271
[58]	validation_0-mae:2857.54748
[59]	validation_0-mae:2840.13068
[60]	validation_0-mae:2821.33101
[61]	validation_0-mae:2798.77077
[62]	validation_0-mae:2786.01831
[63]	validation_0-mae:2765.26875
[64]	validation_0-mae:2752.77095
[65]	validation_0-mae:2741.50122
[66]	validation_0-mae:2713.05277
[67]	validation_0-mae:2699.32494
[68]	validation_0-mae:2687.77026
[69]	validation_0-mae:2678.36739
[70]	validation_0-mae:2658.49803
[71]	validation_0-mae:2650.01293
[72]	validation_0-mae:2641.43812
[73]	validation_0-mae:2622.68719
[74]	validation_0-mae:2605.11185
[75]	validation_0-mae:2596.67150
[76]	validation_0-mae:2581.88184
[77]	validation_0-mae:2566.74322
[78]	validation_0-mae:2558.26674
[79]	validation_0-mae:2548.58578
[80]	validation_0-mae:2535.06073
[81]	validation_0-mae:2529.73298
[82]	validation_0-mae:2518.73024
[83]	validation_0-mae:2514.25224
[84]	validation_0-mae:2502.30547
[85]	validation_0-mae:2498.71579
[86]	validation_0-mae:2492.21881
[87]	validation_0-mae:2484.47857
[88]	validation_0-mae:2478.74645
[89]	validation_0-mae:2469.01422
[90]	validation_0-mae:2465.46598
[91]	validation_0-mae:2457.55063
[92]	validation_0-mae:2449.94271
[93]	validation_0-mae:2441.03715
[94]	validation_0-mae:2433.82285
[95]	validation_0-mae:2429.16709
[96]	validation_0-mae:2425.53676
[97]	validation_0-mae:2420.03003
[98]	validation_0-mae:2413.23386
[99]	validation_0-mae:2409.87804
[100]	validation_0-mae:2403.03771
[101]	validation_0-mae:2396.38623
[102]	validation_0-mae:2390.81518
[103]	validation_0-mae:2388.54904
[104]	validation_0-mae:2386.23510
[105]	validation_0-mae:2382.10633
[106]	validation_0-mae:2373.20305
[107]	validation_0-mae:2369.99290
[108]	validation_0-mae:2367.35240
[109]	validation_0-mae:2362.34529
[110]	validation_0-mae:2359.69000
[111]	validation_0-mae:2356.61860
[112]	validation_0-mae:2352.77405
[113]	validation_0-mae:2350.93328
[114]	validation_0-mae:2350.39605
[115]	validation_0-mae:2344.08663
[116]	validation_0-mae:2339.95561
[117]	validation_0-mae:2337.08558
[118]	validation_0-mae:2335.64235
[119]	validation_0-mae:2329.77650
[120]	validation_0-mae:2326.87148
[121]	validation_0-mae:2326.01180
[122]	validation_0-mae:2320.86511
[123]	validation_0-mae:2317.42721
[124]	validation_0-mae:2315.47632
[125]	validation_0-mae:2311.96444
[126]	validation_0-mae:2309.63186
[127]	validation_0-mae:2305.78495
[128]	validation_0-mae:2303.45406
[129]	validation_0-mae:2299.76950
[130]	validation_0-mae:2298.44860
[131]	validation_0-mae:2295.04152
[132]	validation_0-mae:2291.47717
[133]	validation_0-mae:2291.63773
[134]	validation_0-mae:2288.16310
[135]	validation_0-mae:2288.09475
[136]	validation_0-mae:2286.31312
[137]	validation_0-mae:2279.79432
[138]	validation_0-mae:2280.30668
[139]	validation_0-mae:2276.64054
[140]	validation_0-mae:2275.04450
[141]	validation_0-mae:2272.24078
[142]	validation_0-mae:2271.09880
[143]	validation_0-mae:2267.51578
[144]	validation_0-mae:2265.23771
[145]	validation_0-mae:2264.00887
[146]	validation_0-mae:2262.57577
[147]	validation_0-mae:2263.19238
[148]	validation_0-mae:2261.54339
[149]	validation_0-mae:2258.84052
[0]	validation_0-mae:12406.43175
[1]	validation_0-mae:11639.84216
[2]	validation_0-mae:10959.66034
[3]	validation_0-mae:10305.46369
[4]	validation_0-mae:9737.35507
[5]	validation_0-mae:9233.53426
[6]	validation_0-mae:8746.97245
[7]	validation_0-mae:8330.99794
[8]	validation_0-mae:7955.54241
[9]	validation_0-mae:7594.91930
[10]	validation_0-mae:7278.41124
[11]	validation_0-mae:6960.09548
[12]	validation_0-mae:6677.86691
[13]	validation_0-mae:6419.46305
[14]	validation_0-mae:6179.59176
[15]	validation_0-mae:5952.51446
[16]	validation_0-mae:5739.99201
[17]	validation_0-mae:5536.63379
[18]	validation_0-mae:5336.95083
[19]	validation_0-mae:5148.53871
[20]	validation_0-mae:4996.89691
[21]	validation_0-mae:4831.30298
[22]	validation_0-mae:4703.82674
[23]	validation_0-mae:4573.83832
[24]	validation_0-mae:4450.83265
[25]	validation_0-mae:4316.60989
[26]	validation_0-mae:4212.99473
[27]	validation_0-mae:4111.07046
[28]	validation_0-mae:4010.07690
[29]	validation_0-mae:3908.59966
[30]	validation_0-mae:3839.18392
[31]	validation_0-mae:3737.13005
[32]	validation_0-mae:3671.03833
[33]	validation_0-mae:3595.89822
[34]	validation_0-mae:3534.28002

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[35]	validation_0-mae:3462.84779
[36]	validation_0-mae:3405.96576
[37]	validation_0-mae:3363.56547
[38]	validation_0-mae:3315.17483
[39]	validation_0-mae:3279.28638
[40]	validation_0-mae:3233.30487
[41]	validation_0-mae:3188.98264
[42]	validation_0-mae:3157.04600
[43]	validation_0-mae:3119.04033
[44]	validation_0-mae:3080.31756
[45]	validation_0-mae:3052.90371
[46]	validation_0-mae:3016.61409
[47]	validation_0-mae:2990.87802
[48]	validation_0-mae:2952.95417
[49]	validation_0-mae:2919.92447
[50]	validation_0-mae:2898.59295
[51]	validation_0-mae:2878.73092
[52]	validation_0-mae:2862.07340
[53]	validation_0-mae:2840.75386
[54]	validation_0-mae:2818.37469
[55]	validation_0-mae:2801.72022
[56]	validation_0-mae:2786.27775
[57]	validation_0-mae:2762.25865
[58]	validation_0-mae:2747.00263
[59]	validation_0-mae:2731.44426
[60]	validation_0-mae:2717.04052
[61]	validation_0-mae:2702.18562
[62]	validation_0-mae:2690.54114
[63]	validation_0-mae:2680.34825
[64]	validation_0-mae:2670.81513
[65]	validation_0-mae:2647.53149
[66]	validation_0-mae:2623.30471
[67]	validation_0-mae:2602.39097
[68]	validation_0-mae:2589.89467
[69]	validation_0-mae:2580.34044
[70]	validation_0-mae:2575.64552
[71]	validation_0-mae:2561.65536
[72]	validation_0-mae:2555.49786
[73]	validation_0-mae:2541.56308
[74]	validation_0-mae:2529.15407
[75]	validation_0-mae:2519.08913
[76]	validation_0-mae:2510.40616
[77]	validation_0-mae:2500.70791
[78]	validation_0-mae:2491.97970
[79]	validation_0-mae:2484.67113
[80]	validation_0-mae:2482.33702
[81]	validation_0-mae:2479.40704
[82]	validation_0-mae:2470.34065
[83]	validation_0-mae:2465.98778
[84]	validation_0-mae:2456.40803
[85]	validation_0-mae:2447.89801
[86]	validation_0-mae:2439.00586
[87]	validation_0-mae:2434.00649
[88]	validation_0-mae:2428.48585
[89]	validation_0-mae:2418.64148
[90]	validation_0-mae:2414.53741
[91]	validation_0-mae:2408.64116
[92]	validation_0-mae:2402.74542
[93]	validation_0-mae:2395.53271
[94]	validation_0-mae:2388.52308
[95]	validation_0-mae:2382.21089
[96]	validation_0-mae:2379.68863
[97]	validation_0-mae:2373.69020
[98]	validation_0-mae:2372.56022
[99]	validation_0-mae:2366.69640
[100]	validation_0-mae:2360.44560
[101]	validation_0-mae:2358.47439
[102]	validation_0-mae:2346.55480
[103]	validation_0-mae:2340.88825
[104]	validation_0-mae:2335.86865
[105]	validation_0-mae:2327.39653
[106]	validation_0-mae:2325.99784
[107]	validation_0-mae:2324.41816
[108]	validation_0-mae:2321.68462
[109]	validation_0-mae:2318.19741
[110]	validation_0-mae:2317.48689
[111]	validation_0-mae:2313.42841
[112]	validation_0-mae:2310.80328
[113]	validation_0-mae:2304.67275
[114]	validation_0-mae:2296.05815
[115]	validation_0-mae:2293.59519
[116]	validation_0-mae:2290.64530
[117]	validation_0-mae:2284.31431
[118]	validation_0-mae:2280.68044
[119]	validation_0-mae:2278.18046
[120]	validation_0-mae:2276.32899
[121]	validation_0-mae:2275.94706
[122]	validation_0-mae:2275.08132
[123]	validation_0-mae:2272.95864
[124]	validation_0-mae:2268.52350
[125]	validation_0-mae:2266.92212
[126]	validation_0-mae:2267.02177
[127]	validation_0-mae:2260.43906
[128]	validation_0-mae:2257.41099
[129]	validation_0-mae:2255.55137
[130]	validation_0-mae:2252.67855
[131]	validation_0-mae:2248.25725
[132]	validation_0-mae:2247.54387
[133]	validation_0-mae:2245.36775
[134]	validation_0-mae:2243.03249
[135]	validation_0-mae:2243.22087
[136]	validation_0-mae:2239.87339
[137]	validation_0-mae:2239.10782
[138]	validation_0-mae:2235.59899
[139]	validation_0-mae:2232.42886
[140]	validation_0-mae:2231.48595
[141]	validation_0-mae:2227.39447
[142]	validation_0-mae:2223.98142
[143]	validation_0-mae:2221.05059
[144]	validation_0-mae:2221.60822
[145]	validation_0-mae:2220.34463
[146]	validation_0-mae:2215.27982
[147]	validation_0-mae:2215.32208
[148]	validation_0-mae:2215.27279
[149]	validation_0-mae:2214.78341
[150]	validation_0-mae:2212.47982
[151]	validation_0-mae:2211.98815
[152]	validation_0-mae:2209.71026
[153]	validation_0-mae:2209.98604
[154]	validation_0-mae:2208.42121
[155]	validation_0-mae:2208.20480
[156]	validation_0-mae:2206.49304
[157]	validation_0-mae:2205.14400
[158]	validation_0-mae:2205.06459
[159]	validation_0-mae:2202.83301
[160]	validation_0-mae:2199.54169
[161]	validation_0-mae:2198.25701
[162]	validation_0-mae:2197.10645
[163]	validation_0-mae:2196.85825
[164]	validation_0-mae:2193.76944
[165]	validation_0-mae:2190.57951
[166]	validation_0-mae:2191.19567
[167]	validation_0-mae:2189.20763
[168]	validation_0-mae:2188.88568
[169]	validation_0-mae:2185.40733
[170]	validation_0-mae:2185.85422
[171]	validation_0-mae:2186.52596
[172]	validation_0-mae:2185.41227
[173]	validation_0-mae:2185.85700
[174]	validation_0-mae:2184.62346
[175]	validation_0-mae:2182.99625
[176]	validation_0-mae:2180.68352
[177]	validation_0-mae:2180.47162
[178]	validation_0-mae:2180.39200
[179]	validation_0-mae:2179.88987
[180]	validation_0-mae:2179.98069
[181]	validation_0-mae:2180.75619
[182]	validation_0-mae:2179.70673
[183]	validation_0-mae:2178.72636
[184]	validation_0-mae:2179.02251
[185]	validation_0-mae:2177.90720
[186]	validation_0-mae:2177.87882
[187]	validation_0-mae:2177.62307
[188]	validation_0-mae:2176.38367
[189]	validation_0-mae:2176.57038
[190]	validation_0-mae:2176.86954
[191]	validation_0-mae:2175.65708
[192]	validation_0-mae:2176.09319
[193]	validation_0-mae:2175.64105
[194]	validation_0-mae:2174.63157
[195]	validation_0-mae:2175.09373
[196]	validation_0-mae:2175.07513
[197]	validation_0-mae:2175.14458
[198]	validation_0-mae:2174.15545
[199]	validation_0-mae:2173.52503
[200]	validation_0-mae:2172.82721
[201]	validation_0-mae:2171.84709
[202]	validation_0-mae:2171.88345
[203]	validation_0-mae:2171.37737
[204]	validation_0-mae:2171.35392
[205]	validation_0-mae:2168.97578
[206]	validation_0-mae:2167.10386
[207]	validation_0-mae:2165.02091
[208]	validation_0-mae:2165.50715
[209]	validation_0-mae:2165.74215
[210]	validation_0-mae:2166.12287
[211]	validation_0-mae:2165.88083
[212]	validation_0-mae:2165.35286
[213]	validation_0-mae:2164.93710
[214]	validation_0-mae:2163.17023
[215]	validation_0-mae:2163.43700
[216]	validation_0-mae:2162.33548
[217]	validation_0-mae:2161.24860
[218]	validation_0-mae:2161.24142
[219]	validation_0-mae:2161.66454
[220]	validation_0-mae:2160.75361
[221]	validation_0-mae:2159.91932
[222]	validation_0-mae:2159.77285
[223]	validation_0-mae:2159.71205
[224]	validation_0-mae:2157.45500
[225]	validation_0-mae:2156.39545
[226]	validation_0-mae:2154.80240
[227]	validation_0-mae:2154.51449
[228]	validation_0-mae:2152.73247
[229]	validation_0-mae:2150.64970
[230]	validation_0-mae:2150.85320
[231]	validation_0-mae:2150.17528
[232]	validation_0-mae:2147.53377
[233]	validation_0-mae:2145.76568
[234]	validation_0-mae:2146.18476
[235]	validation_0-mae:2146.39924
[236]	validation_0-mae:2145.07319
[237]	validation_0-mae:2144.67341
[238]	validation_0-mae:2144.46845
[239]	validation_0-mae:2144.38778
[240]	validation_0-mae:2145.13898
[241]	validation_0-mae:2145.61009
[242]	validation_0-mae:2145.11939
[243]	validation_0-mae:2145.06856
[244]	validation_0-mae:2143.58800
[245]	validation_0-mae:2143.06094
[246]	validation_0-mae:2142.45402
[247]	validation_0-mae:2142.23257
[248]	validation_0-mae:2141.31816
[249]	validation_0-mae:2139.03086
[250]	validation_0-mae:2136.92774
[251]	validation_0-mae:2137.62851
[252]	validation_0-mae:2137.49178
[253]	validation_0-mae:2137.41256
[254]	validation_0-mae:2137.09392
[255]	validation_0-mae:2136.78418
[256]	validation_0-mae:2135.42275
[257]	validation_0-mae:2134.85867
[258]	validation_0-mae:2134.95319
[259]	validation_0-mae:2135.56937
[260]	validation_0-mae:2135.54211
[261]	validation_0-mae:2135.64562
[262]	validation_0-mae:2136.15718
[263]	validation_0-mae:2136.64525
[264]	validation_0-mae:2136.95986
[265]	validation_0-mae:2136.49028
[266]	validation_0-mae:2136.57176
[267]	validation_0-mae:2136.52473
[268]	validation_0-mae:2135.76714
[269]	validation_0-mae:2135.74569
[270]	validation_0-mae:2135.75063
[271]	validation_0-mae:2134.93056
[272]	validation_0-mae:2135.55997
[273]	validation_0-mae:2134.71186
[274]	validation_0-mae:2132.58111
[275]	validation_0-mae:2131.66738
[276]	validation_0-mae:2131.88613
[277]	validation_0-mae:2131.09375
[278]	validation_0-mae:2130.91189
[279]	validation_0-mae:2130.14387
[280]	validation_0-mae:2130.49033
[281]	validation_0-mae:2130.08987
[282]	validation_0-mae:2129.92174
[283]	validation_0-mae:2130.72065
[284]	validation_0-mae:2130.74706
[285]	validation_0-mae:2129.78867
[286]	validation_0-mae:2129.59588
[287]	validation_0-mae:2129.45607
[288]	validation_0-mae:2129.29779
[289]	validation_0-mae:2128.87604
[290]	validation_0-mae:2129.08133
[291]	validation_0-mae:2129.27535
[292]	validation_0-mae:2129.00160
[293]	validation_0-mae:2128.61889
[294]	validation_0-mae:2128.48155
[295]	validation_0-mae:2128.73728
[296]	validation_0-mae:2128.47058
[297]	validation_0-mae:2128.21405
[298]	validation_0-mae:2128.12737
[299]	validation_0-mae:2128.10999
[300]	validation_0-mae:2127.87483
[301]	validation_0-mae:2128.02222
[302]	validation_0-mae:2127.82389
[303]	validation_0-mae:2127.58536
[304]	validation_0-mae:2128.02838
[305]	validation_0-mae:2128.57477
[306]	validation_0-mae:2128.85841
[307]	validation_0-mae:2128.53300
[308]	validation_0-mae:2128.16642
[309]	validation_0-mae:2128.37737
[310]	validation_0-mae:2128.66252
[311]	validation_0-mae:2128.08017
[312]	validation_0-mae:2128.16548
[313]	validation_0-mae:2128.14723
[314]	validation_0-mae:2128.68361
[315]	validation_0-mae:2128.60586
[316]	validation_0-mae:2128.30603
[317]	validation_0-mae:2128.52924
[318]	validation_0-mae:2128.29883
[319]	validation_0-mae:2127.99032
[320]	validation_0-mae:2127.44208
[321]	validation_0-mae:2128.11835
[322]	validation_0-mae:2127.35666
[323]	validation_0-mae:2127.12859
[324]	validation_0-mae:2127.31575
[325]	validation_0-mae:2127.61908
[326]	validation_0-mae:2127.60299
[327]	validation_0-mae:2127.56675
[328]	validation_0-mae:2127.20895
[329]	validation_0-mae:2125.70609
[330]	validation_0-mae:2125.35132
[331]	validation_0-mae:2125.37510
[332]	validation_0-mae:2125.42962
[333]	validation_0-mae:2125.86083
[334]	validation_0-mae:2126.24187
[335]	validation_0-mae:2126.39385
[336]	validation_0-mae:2126.16988
[337]	validation_0-mae:2125.90056
[338]	validation_0-mae:2125.92281
[339]	validation_0-mae:2126.25405
[340]	validation_0-mae:2125.91783
[341]	validation_0-mae:2125.59548
[342]	validation_0-mae:2126.15479
[343]	validation_0-mae:2125.88360
[344]	validation_0-mae:2125.33598
[345]	validation_0-mae:2124.43000
[346]	validation_0-mae:2124.51823
[347]	validation_0-mae:2124.63497
[348]	validation_0-mae:2124.75467
[349]	validation_0-mae:2125.35330
[350]	validation_0-mae:2125.00281
[351]	validation_0-mae:2125.51082
[352]	validation_0-mae:2125.76806
[353]	validation_0-mae:2125.97836
[354]	validation_0-mae:2124.99934
[355]	validation_0-mae:2125.03523
[356]	validation_0-mae:2125.07761
[357]	validation_0-mae:2125.51088
[358]	validation_0-mae:2124.89227
[359]	validation_0-mae:2124.95074
[360]	validation_0-mae:2125.23182
[361]	validation_0-mae:2125.54282
[362]	validation_0-mae:2125.23461
[363]	validation_0-mae:2124.88323
[364]	validation_0-mae:2123.58058
[365]	validation_0-mae:2123.66071
[366]	validation_0-mae:2122.82997
[367]	validation_0-mae:2123.17628
[368]	validation_0-mae:2123.11637
[369]	validation_0-mae:2123.12909
[370]	validation_0-mae:2123.41724
[371]	validation_0-mae:2123.65755
[372]	validation_0-mae:2122.90926
[373]	validation_0-mae:2123.45911
[374]	validation_0-mae:2123.69070
[375]	validation_0-mae:2122.82134
[376]	validation_0-mae:2123.40223
[377]	validation_0-mae:2122.92656
[378]	validation_0-mae:2122.58313
[379]	validation_0-mae:2122.76183
[380]	validation_0-mae:2122.27506
[381]	validation_0-mae:2122.89799
[382]	validation_0-mae:2123.28647
[383]	validation_0-mae:2123.60361
[384]	validation_0-mae:2123.39782
[385]	validation_0-mae:2123.81915
[386]	validation_0-mae:2124.25038
[387]	validation_0-mae:2123.79191
[388]	validation_0-mae:2123.92216
[389]	validation_0-mae:2124.22136
[390]	validation_0-mae:2124.54102
[391]	validation_0-mae:2124.42319
[392]	validation_0-mae:2124.65441
[393]	validation_0-mae:2124.59458
[394]	validation_0-mae:2124.80955
[395]	validation_0-mae:2124.49816
[396]	validation_0-mae:2124.25274
[397]	validation_0-mae:2124.15561
[398]	validation_0-mae:2123.93747
[399]	validation_0-mae:2124.31631
[400]	validation_0-mae:2124.21181
[401]	validation_0-mae:2124.47883
[402]	validation_0-mae:2125.12729
[403]	validation_0-mae:2124.84137
[404]	validation_0-mae:2124.67734
[405]	validation_0-mae:2125.03125
[406]	validation_0-mae:2125.13160
[407]	validation_0-mae:2125.24935
[408]	validation_0-mae:2123.90343
[409]	validation_0-mae:2124.32914
[410]	validation_0-mae:2124.85839
[411]	validation_0-mae:2124.62651
[412]	validation_0-mae:2124.21659
[413]	validation_0-mae:2124.15841
[414]	validation_0-mae:2124.07020
[415]	validation_0-mae:2124.18792
[416]	validation_0-mae:2124.17193
[417]	validation_0-mae:2124.34144
[418]	validation_0-mae:2124.31733
[419]	validation_0-mae:2124.74973
[420]	validation_0-mae:2124.63752
[421]	validation_0-mae:2125.09324
[422]	validation_0-mae:2124.95446
[423]	validation_0-mae:2124.66093
[424]	validation_0-mae:2124.21292
[425]	validation_0-mae:2124.07003
[426]	validation_0-mae:2124.22049
[427]	validation_0-mae:2124.26012
[428]	validation_0-mae:2123.96333
[429]	validation_0-mae:2123.32537
[430]	validation_0-mae:2123.63000
[431]	validation_0-mae:2123.52231
[432]	validation_0-mae:2122.27457
[433]	validation_0-mae:2122.78989
[434]	validation_0-mae:2121.96353
[435]	validation_0-mae:2121.76304
[436]	validation_0-mae:2121.52106
[437]	validation_0-mae:2121.79976
[438]	validation_0-mae:2121.77110
[439]	validation_0-mae:2121.64038
[440]	validation_0-mae:2121.35964
[441]	validation_0-mae:2121.52005
[442]	validation_0-mae:2121.13459
[443]	validation_0-mae:2121.07900
[444]	validation_0-mae:2121.11033
[445]	validation_0-mae:2120.76496
[446]	validation_0-mae:2120.62765
[447]	validation_0-mae:2120.42993
[448]	validation_0-mae:2120.54455
[449]	validation_0-mae:2120.37213
[450]	validation_0-mae:2120.52932
[451]	validation_0-mae:2121.07802
[452]	validation_0-mae:2120.47028
[453]	validation_0-mae:2120.44722
[454]	validation_0-mae:2119.85946
[455]	validation_0-mae:2119.52303
[456]	validation_0-mae:2119.57545
[457]	validation_0-mae:2119.20096
[458]	validation_0-mae:2119.42135
[459]	validation_0-mae:2118.45081
[460]	validation_0-mae:2118.29804
[461]	validation_0-mae:2117.62344
[462]	validation_0-mae:2116.65397
[463]	validation_0-mae:2116.59720
[464]	validation_0-mae:2116.08164
[465]	validation_0-mae:2116.37240
[466]	validation_0-mae:2116.24997
[467]	validation_0-mae:2115.95279
[468]	validation_0-mae:2116.03989
[469]	validation_0-mae:2115.34116
[470]	validation_0-mae:2115.58736
[471]	validation_0-mae:2115.11585
[472]	validation_0-mae:2114.89307
[473]	validation_0-mae:2114.81105
[474]	validation_0-mae:2115.06990
[475]	validation_0-mae:2113.87043
[476]	validation_0-mae:2113.80576
[477]	validation_0-mae:2113.57240
[478]	validation_0-mae:2113.54464
[479]	validation_0-mae:2112.45449
[480]	validation_0-mae:2112.60368
[481]	validation_0-mae:2112.88458
[482]	validation_0-mae:2113.15960
[483]	validation_0-mae:2113.07231
[484]	validation_0-mae:2112.85982
[485]	validation_0-mae:2112.71648
[486]	validation_0-mae:2112.93817
[487]	validation_0-mae:2112.11481
[488]	validation_0-mae:2112.24841
[489]	validation_0-mae:2112.05591
[490]	validation_0-mae:2111.91946
[491]	validation_0-mae:2111.10879
[492]	validation_0-mae:2111.29146
[493]	validation_0-mae:2111.44663
[494]	validation_0-mae:2110.59941
[495]	validation_0-mae:2110.58075
[496]	validation_0-mae:2110.65546
[497]	validation_0-mae:2110.31680
[498]	validation_0-mae:2110.10422
[499]	validation_0-mae:2110.71055
[500]	validation_0-mae:2110.66631
[501]	validation_0-mae:2110.55348
[502]	validation_0-mae:2110.37422
[503]	validation_0-mae:2110.51516
[504]	validation_0-mae:2109.96185
[505]	validation_0-mae:2109.85718
[506]	validation_0-mae:2110.04932
[507]	validation_0-mae:2110.15046
[508]	validation_0-mae:2110.29070
[509]	validation_0-mae:2109.97712
[510]	validation_0-mae:2110.05664
[511]	validation_0-mae:2110.29172
[512]	validation_0-mae:2110.35020
[513]	validation_0-mae:2109.31803
[514]	validation_0-mae:2109.54103
[515]	validation_0-mae:2109.69319
[516]	validation_0-mae:2110.06626
[517]	validation_0-mae:2110.18713
[518]	validation_0-mae:2109.16527
[519]	validation_0-mae:2109.69031
[520]	validation_0-mae:2109.27102
[521]	validation_0-mae:2109.31548
[522]	validation_0-mae:2109.00430
[523]	validation_0-mae:2109.20536
[524]	validation_0-mae:2109.33601
[525]	validation_0-mae:2109.42109
[526]	validation_0-mae:2109.46326
[527]	validation_0-mae:2109.70994
[528]	validation_0-mae:2109.65988
[529]	validation_0-mae:2110.06394
[530]	validation_0-mae:2109.60359
[531]	validation_0-mae:2109.60787
[532]	validation_0-mae:2109.82297
[533]	validation_0-mae:2109.80294
[534]	validation_0-mae:2110.10775
[535]	validation_0-mae:2110.18969
[536]	validation_0-mae:2110.14263
[537]	validation_0-mae:2109.56946
[538]	validation_0-mae:2109.46798
[539]	validation_0-mae:2109.61685
[540]	validation_0-mae:2109.90426
[541]	validation_0-mae:2109.62157
[542]	validation_0-mae:2109.57993
[543]	validation_0-mae:2109.61506
[544]	validation_0-mae:2109.23451
[545]	validation_0-mae:2108.96165
[546]	validation_0-mae:2109.19918
[547]	validation_0-mae:2108.50418
[548]	validation_0-mae:2108.58393
[549]	validation_0-mae:2108.49559
[550]	validation_0-mae:2108.75581
[551]	validation_0-mae:2108.58029
[552]	validation_0-mae:2108.96524
[553]	validation_0-mae:2108.49874
[554]	validation_0-mae:2108.86567
[0]	validation_0-mae:12459.02466
[1]	validation_0-mae:11736.69915
[2]	validation_0-mae:11088.39268
[3]	validation_0-mae:10465.74429
[4]	validation_0-mae:9930.92359
[5]	validation_0-mae:9428.77118
[6]	validation_0-mae:8985.03843
[7]	validation_0-mae:8576.92484
[8]	validation_0-mae:8208.46655
[9]	validation_0-mae:7867.88280
[10]	validation_0-mae:7569.79717
[11]	validation_0-mae:7270.29612
[12]	validation_0-mae:6992.06396
[13]	validation_0-mae:6703.93385
[14]	validation_0-mae:6456.39626
[15]	validation_0-mae:6236.12841
[16]	validation_0-mae:6012.98205
[17]	validation_0-mae:5815.20274
[18]	validation_0-mae:5598.07562
[19]	validation_0-mae:5428.88418
[20]	validation_0-mae:5268.89229
[21]	validation_0-mae:5123.15318
[22]	validation_0-mae:4959.73792
[23]	validation_0-mae:4804.89837
[24]	validation_0-mae:4677.58607
[25]	validation_0-mae:4550.04687
[26]	validation_0-mae:4431.30259
[27]	validation_0-mae:4319.98288
[28]	validation_0-mae:4216.28354
[29]	validation_0-mae:4125.18157
[30]	validation_0-mae:4046.52284
[31]	validation_0-mae:3964.29123
[32]	validation_0-mae:3886.18225
[33]	validation_0-mae:3803.85353
[34]	validation_0-mae:3735.39183
[35]	validation_0-mae:3656.44182
[36]	validation_0-mae:3589.62515
[37]	validation_0-mae:3525.83346
[38]	validation_0-mae:3468.13262
[39]	validation_0-mae:3420.52155
[40]	validation_0-mae:3370.66505

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[41]	validation_0-mae:3331.50752
[42]	validation_0-mae:3285.76632
[43]	validation_0-mae:3238.04608
[44]	validation_0-mae:3198.47318
[45]	validation_0-mae:3162.71682
[46]	validation_0-mae:3129.91086
[47]	validation_0-mae:3082.27604
[48]	validation_0-mae:3052.77180
[49]	validation_0-mae:3017.48110
[50]	validation_0-mae:2994.76851
[51]	validation_0-mae:2966.87958
[52]	validation_0-mae:2930.12278
[53]	validation_0-mae:2909.77535
[54]	validation_0-mae:2885.14310
[55]	validation_0-mae:2867.68617
[56]	validation_0-mae:2847.95630
[57]	validation_0-mae:2818.93938
[58]	validation_0-mae:2792.98763
[59]	validation_0-mae:2774.66194
[60]	validation_0-mae:2759.73965
[61]	validation_0-mae:2744.29418
[62]	validation_0-mae:2720.06506
[63]	validation_0-mae:2701.77979
[64]	validation_0-mae:2691.47183
[65]	validation_0-mae:2678.34926
[66]	validation_0-mae:2667.73318
[67]	validation_0-mae:2653.96242
[68]	validation_0-mae:2643.94494
[69]	validation_0-mae:2636.83516
[70]	validation_0-mae:2628.75544
[71]	validation_0-mae:2621.15402
[72]	validation_0-mae:2602.61440
[73]	validation_0-mae:2595.94076
[74]	validation_0-mae:2583.66084
[75]	validation_0-mae:2565.81489
[76]	validation_0-mae:2557.18168
[77]	validation_0-mae:2548.01209
[78]	validation_0-mae:2535.81520
[79]	validation_0-mae:2525.46125
[80]	validation_0-mae:2520.31299
[81]	validation_0-mae:2512.46749
[82]	validation_0-mae:2505.17261
[83]	validation_0-mae:2494.86141
[84]	validation_0-mae:2485.75847
[85]	validation_0-mae:2478.31882
[86]	validation_0-mae:2467.38425
[87]	validation_0-mae:2458.96369
[88]	validation_0-mae:2456.07881
[89]	validation_0-mae:2447.89697
[90]	validation_0-mae:2442.55919
[91]	validation_0-mae:2435.22676
[92]	validation_0-mae:2427.74360
[93]	validation_0-mae:2418.40730
[94]	validation_0-mae:2414.01006
[95]	validation_0-mae:2407.93963
[96]	validation_0-mae:2403.30696
[97]	validation_0-mae:2395.75084
[98]	validation_0-mae:2392.74270
[99]	validation_0-mae:2387.20599
[100]	validation_0-mae:2382.57920
[101]	validation_0-mae:2376.23465
[102]	validation_0-mae:2370.81153
[103]	validation_0-mae:2361.91752
[104]	validation_0-mae:2359.04295
[105]	validation_0-mae:2355.12433
[106]	validation_0-mae:2349.62240
[107]	validation_0-mae:2342.54907
[108]	validation_0-mae:2339.04679
[109]	validation_0-mae:2337.38132
[110]	validation_0-mae:2334.31621
[111]	validation_0-mae:2330.79466
[112]	validation_0-mae:2326.54460
[113]	validation_0-mae:2323.89653
[114]	validation_0-mae:2318.82679
[115]	validation_0-mae:2315.26828
[116]	validation_0-mae:2309.61874
[117]	validation_0-mae:2306.03677
[118]	validation_0-mae:2301.65939
[119]	validation_0-mae:2300.67949
[120]	validation_0-mae:2295.28870
[121]	validation_0-mae:2291.32983
[122]	validation_0-mae:2286.55618
[123]	validation_0-mae:2282.26593
[124]	validation_0-mae:2275.86685
[125]	validation_0-mae:2274.23513
[126]	validation_0-mae:2268.60281
[127]	validation_0-mae:2265.07915
[128]	validation_0-mae:2263.41643
[129]	validation_0-mae:2259.26141
[130]	validation_0-mae:2258.58729
[131]	validation_0-mae:2255.02245
[132]	validation_0-mae:2253.55867
[133]	validation_0-mae:2252.80776
[134]	validation_0-mae:2248.56747
[135]	validation_0-mae:2243.49325
[136]	validation_0-mae:2242.78322
[137]	validation_0-mae:2239.65652
[138]	validation_0-mae:2238.87098
[139]	validation_0-mae:2235.25137
[140]	validation_0-mae:2232.52530
[141]	validation_0-mae:2229.37595
[142]	validation_0-mae:2227.22800
[143]	validation_0-mae:2225.39112
[144]	validation_0-mae:2224.08254
[145]	validation_0-mae:2221.60093
[146]	validation_0-mae:2222.89911
[147]	validation_0-mae:2219.63153
[148]	validation_0-mae:2218.49115
[149]	validation_0-mae:2217.89301
[150]	validation_0-mae:2216.01052
[151]	validation_0-mae:2214.90037
[152]	validation_0-mae:2212.26675
[153]	validation_0-mae:2211.50494
[154]	validation_0-mae:2211.96732
[155]	validation_0-mae:2211.49895
[156]	validation_0-mae:2210.51049
[157]	validation_0-mae:2207.77494
[158]	validation_0-mae:2207.38446
[159]	validation_0-mae:2204.07834
[160]	validation_0-mae:2201.60913
[161]	validation_0-mae:2199.16894
[162]	validation_0-mae:2197.52144
[163]	validation_0-mae:2197.04280
[164]	validation_0-mae:2195.20641
[165]	validation_0-mae:2194.10889
[166]	validation_0-mae:2191.65911
[167]	validation_0-mae:2190.69436
[168]	validation_0-mae:2190.40025
[169]	validation_0-mae:2188.70897
[170]	validation_0-mae:2190.16518
[171]	validation_0-mae:2188.47172
[172]	validation_0-mae:2187.56294
[173]	validation_0-mae:2187.46726
[174]	validation_0-mae:2185.87248
[175]	validation_0-mae:2183.75864
[176]	validation_0-mae:2183.44992
[177]	validation_0-mae:2183.14019
[178]	validation_0-mae:2180.11993
[179]	validation_0-mae:2179.79435
[180]	validation_0-mae:2176.95710
[181]	validation_0-mae:2175.33026
[182]	validation_0-mae:2174.20556
[183]	validation_0-mae:2173.98789
[184]	validation_0-mae:2173.62297
[185]	validation_0-mae:2171.64819
[186]	validation_0-mae:2169.32390
[187]	validation_0-mae:2165.98349
[188]	validation_0-mae:2163.97055
[189]	validation_0-mae:2162.82639
[190]	validation_0-mae:2163.71145
[191]	validation_0-mae:2162.78924
[192]	validation_0-mae:2163.23228
[193]	validation_0-mae:2162.32383
[194]	validation_0-mae:2160.75567
[195]	validation_0-mae:2160.08668
[196]	validation_0-mae:2158.66626
[197]	validation_0-mae:2158.62200
[198]	validation_0-mae:2158.08385
[199]	validation_0-mae:2158.61198
[200]	validation_0-mae:2157.88601
[201]	validation_0-mae:2156.74408
[202]	validation_0-mae:2156.56432
[203]	validation_0-mae:2155.62437
[204]	validation_0-mae:2155.71690
[205]	validation_0-mae:2155.18036
[206]	validation_0-mae:2152.78273
[207]	validation_0-mae:2153.72024
[208]	validation_0-mae:2153.57446
[209]	validation_0-mae:2152.73451
[210]	validation_0-mae:2153.86651
[211]	validation_0-mae:2154.34581
[212]	validation_0-mae:2154.15473
[213]	validation_0-mae:2154.26556
[214]	validation_0-mae:2151.09784
[215]	validation_0-mae:2149.47121
[216]	validation_0-mae:2147.80524
[217]	validation_0-mae:2145.83592
[218]	validation_0-mae:2143.89092
[219]	validation_0-mae:2141.28743
[220]	validation_0-mae:2141.41123
[221]	validation_0-mae:2140.43311
[222]	validation_0-mae:2140.69005
[223]	validation_0-mae:2139.58965
[224]	validation_0-mae:2139.13680
[225]	validation_0-mae:2139.51122
[226]	validation_0-mae:2140.34624
[227]	validation_0-mae:2140.70919
[228]	validation_0-mae:2140.02937
[229]	validation_0-mae:2139.29562
[230]	validation_0-mae:2138.77207
[231]	validation_0-mae:2139.42520
[232]	validation_0-mae:2138.69197
[233]	validation_0-mae:2138.33335
[234]	validation_0-mae:2138.03961
[235]	validation_0-mae:2138.34520
[236]	validation_0-mae:2138.06592
[237]	validation_0-mae:2138.17062
[238]	validation_0-mae:2135.01536
[239]	validation_0-mae:2135.67487
[240]	validation_0-mae:2132.93898
[241]	validation_0-mae:2133.54630
[242]	validation_0-mae:2133.31234
[243]	validation_0-mae:2132.47529
[244]	validation_0-mae:2132.56762
[245]	validation_0-mae:2132.58885
[246]	validation_0-mae:2133.00956
[247]	validation_0-mae:2134.11541
[248]	validation_0-mae:2133.65090
[249]	validation_0-mae:2133.46159
[250]	validation_0-mae:2133.04836
[251]	validation_0-mae:2132.15696
[252]	validation_0-mae:2131.83877
[253]	validation_0-mae:2131.03881
[254]	validation_0-mae:2130.29506
[255]	validation_0-mae:2130.11329
[256]	validation_0-mae:2128.93278
[257]	validation_0-mae:2127.89063
[258]	validation_0-mae:2127.50422
[259]	validation_0-mae:2127.34795
[260]	validation_0-mae:2127.20146
[261]	validation_0-mae:2127.58355
[262]	validation_0-mae:2127.66207
[263]	validation_0-mae:2128.11567
[264]	validation_0-mae:2129.04002
[265]	validation_0-mae:2129.06712
[266]	validation_0-mae:2128.58087
[267]	validation_0-mae:2128.65181
[268]	validation_0-mae:2128.75040
[269]	validation_0-mae:2127.77918
[270]	validation_0-mae:2127.74640
[271]	validation_0-mae:2127.86801
[272]	validation_0-mae:2127.66694
[273]	validation_0-mae:2126.41076
[274]	validation_0-mae:2125.67033
[275]	validation_0-mae:2125.38982
[276]	validation_0-mae:2124.02172
[277]	validation_0-mae:2124.13090
[278]	validation_0-mae:2123.68906
[279]	validation_0-mae:2122.07614
[280]	validation_0-mae:2121.35511
[281]	validation_0-mae:2120.57637
[282]	validation_0-mae:2120.88207
[283]	validation_0-mae:2119.79689
[284]	validation_0-mae:2119.99394
[285]	validation_0-mae:2120.50017
[286]	validation_0-mae:2119.46173
[287]	validation_0-mae:2119.29295
[288]	validation_0-mae:2118.48913
[289]	validation_0-mae:2118.64604
[290]	validation_0-mae:2118.06865
[291]	validation_0-mae:2118.74102
[292]	validation_0-mae:2119.57416
[293]	validation_0-mae:2119.84327
[294]	validation_0-mae:2119.78165
[295]	validation_0-mae:2120.14785
[296]	validation_0-mae:2119.57803
[297]	validation_0-mae:2117.94262
[298]	validation_0-mae:2117.79748
[299]	validation_0-mae:2117.73917
[300]	validation_0-mae:2118.04706
[301]	validation_0-mae:2118.42927
[302]	validation_0-mae:2119.36904
[303]	validation_0-mae:2119.07214
[304]	validation_0-mae:2118.82080
[305]	validation_0-mae:2118.71691
[306]	validation_0-mae:2119.03204
[307]	validation_0-mae:2119.23700
[308]	validation_0-mae:2119.46067
[309]	validation_0-mae:2119.81674
[310]	validation_0-mae:2119.68638
[311]	validation_0-mae:2120.02102
[312]	validation_0-mae:2119.47474
[313]	validation_0-mae:2118.65310
[314]	validation_0-mae:2118.79916
[315]	validation_0-mae:2119.02925
[316]	validation_0-mae:2118.87152
[317]	validation_0-mae:2119.05036
[318]	validation_0-mae:2119.10023
[319]	validation_0-mae:2118.37109
[320]	validation_0-mae:2118.15962
[321]	validation_0-mae:2117.64528
[322]	validation_0-mae:2117.30452
[323]	validation_0-mae:2117.59608
[324]	validation_0-mae:2116.74443
[325]	validation_0-mae:2115.26085
[326]	validation_0-mae:2114.30135
[327]	validation_0-mae:2112.41083
[328]	validation_0-mae:2111.79863
[329]	validation_0-mae:2111.26714
[330]	validation_0-mae:2111.22244
[331]	validation_0-mae:2111.50173
[332]	validation_0-mae:2111.31598
[333]	validation_0-mae:2110.93955
[334]	validation_0-mae:2111.25941
[335]	validation_0-mae:2110.91770
[336]	validation_0-mae:2110.76408
[337]	validation_0-mae:2110.62258
[338]	validation_0-mae:2110.13234
[339]	validation_0-mae:2109.57148
[340]	validation_0-mae:2108.95744
[341]	validation_0-mae:2109.13590
[342]	validation_0-mae:2109.31563
[343]	validation_0-mae:2108.74107
[344]	validation_0-mae:2108.51488
[345]	validation_0-mae:2107.79058
[346]	validation_0-mae:2107.56996
[347]	validation_0-mae:2107.62416
[348]	validation_0-mae:2107.29745
[349]	validation_0-mae:2106.86817
[350]	validation_0-mae:2106.71185
[351]	validation_0-mae:2107.05876
[352]	validation_0-mae:2106.99523
[353]	validation_0-mae:2107.32164
[354]	validation_0-mae:2107.29200
[355]	validation_0-mae:2107.44734
[356]	validation_0-mae:2106.29361
[357]	validation_0-mae:2105.49144
[358]	validation_0-mae:2105.69770
[359]	validation_0-mae:2105.88376
[360]	validation_0-mae:2105.40934
[361]	validation_0-mae:2106.01043
[362]	validation_0-mae:2106.63882
[363]	validation_0-mae:2106.72504
[364]	validation_0-mae:2106.77423
[365]	validation_0-mae:2106.59099
[366]	validation_0-mae:2106.68498
[367]	validation_0-mae:2106.48761
[368]	validation_0-mae:2106.42972
[369]	validation_0-mae:2106.49853
[370]	validation_0-mae:2107.20888
[371]	validation_0-mae:2107.26951
[372]	validation_0-mae:2107.16850
[373]	validation_0-mae:2107.18748
[374]	validation_0-mae:2107.34993
[375]	validation_0-mae:2107.48844
[376]	validation_0-mae:2107.58488
[377]	validation_0-mae:2107.56906
[378]	validation_0-mae:2107.66137
[379]	validation_0-mae:2107.50481
[380]	validation_0-mae:2107.58539
[381]	validation_0-mae:2107.75584
[382]	validation_0-mae:2107.88496
[383]	validation_0-mae:2107.55402
[384]	validation_0-mae:2107.70713
[385]	validation_0-mae:2106.78028
[386]	validation_0-mae:2106.83665
[387]	validation_0-mae:2106.83465
[388]	validation_0-mae:2106.41856
[389]	validation_0-mae:2106.95533
[390]	validation_0-mae:2107.54367
[391]	validation_0-mae:2107.64742
[392]	validation_0-mae:2107.46741
[393]	validation_0-mae:2106.70747
[394]	validation_0-mae:2107.05645
[395]	validation_0-mae:2107.07130
[396]	validation_0-mae:2107.20107
[397]	validation_0-mae:2105.85593
[398]	validation_0-mae:2105.85959
[399]	validation_0-mae:2106.15870
[400]	validation_0-mae:2105.43899
[401]	validation_0-mae:2105.22176
[402]	validation_0-mae:2105.59444
[403]	validation_0-mae:2105.18190
[404]	validation_0-mae:2105.41333
[405]	validation_0-mae:2105.38433
[406]	validation_0-mae:2104.77662
[407]	validation_0-mae:2104.89158
[408]	validation_0-mae:2105.22952
[409]	validation_0-mae:2105.27807
[410]	validation_0-mae:2103.97719
[411]	validation_0-mae:2103.02008
[412]	validation_0-mae:2102.97007
[413]	validation_0-mae:2102.84488
[414]	validation_0-mae:2102.82064
[415]	validation_0-mae:2102.14143
[416]	validation_0-mae:2102.43335
[417]	validation_0-mae:2101.37018
[418]	validation_0-mae:2101.61856
[419]	validation_0-mae:2102.25628
[420]	validation_0-mae:2102.96271
[421]	validation_0-mae:2102.29850
[422]	validation_0-mae:2102.22368
[423]	validation_0-mae:2102.30698
[424]	validation_0-mae:2102.06356
[425]	validation_0-mae:2102.16690
[426]	validation_0-mae:2102.44070
[427]	validation_0-mae:2102.78324
[428]	validation_0-mae:2102.85822
[429]	validation_0-mae:2103.34815
[430]	validation_0-mae:2103.35196
[431]	validation_0-mae:2103.59146
[432]	validation_0-mae:2103.61721
[433]	validation_0-mae:2103.81458
[434]	validation_0-mae:2104.37837
[435]	validation_0-mae:2104.39029
[436]	validation_0-mae:2104.07810
[437]	validation_0-mae:2104.05943
[438]	validation_0-mae:2104.61553
[439]	validation_0-mae:2104.68903
[440]	validation_0-mae:2104.54788
[441]	validation_0-mae:2104.65700
[442]	validation_0-mae:2104.36095
[443]	validation_0-mae:2104.04063
[444]	validation_0-mae:2104.46350
[445]	validation_0-mae:2104.59114
[446]	validation_0-mae:2104.36272
[447]	validation_0-mae:2103.87817
[448]	validation_0-mae:2102.69963
[449]	validation_0-mae:2103.06235
[450]	validation_0-mae:2102.45414
[451]	validation_0-mae:2102.52286
[452]	validation_0-mae:2102.62725
[453]	validation_0-mae:2102.78009
[454]	validation_0-mae:2102.95704
[455]	validation_0-mae:2102.42814
[456]	validation_0-mae:2102.36745
[457]	validation_0-mae:2102.65081
[458]	validation_0-mae:2102.23500
[459]	validation_0-mae:2100.98408
[460]	validation_0-mae:2099.96785
[461]	validation_0-mae:2099.94050
[462]	validation_0-mae:2099.66705
[463]	validation_0-mae:2099.14251
[464]	validation_0-mae:2099.35428
[465]	validation_0-mae:2099.63760
[466]	validation_0-mae:2098.71801
[467]	validation_0-mae:2098.77342
[468]	validation_0-mae:2098.68258
[469]	validation_0-mae:2099.00008
[470]	validation_0-mae:2099.26885
[471]	validation_0-mae:2099.54749
[472]	validation_0-mae:2099.71904
[473]	validation_0-mae:2100.35284
[474]	validation_0-mae:2099.17489
[475]	validation_0-mae:2098.89461
[476]	validation_0-mae:2098.68212
[477]	validation_0-mae:2098.42708
[478]	validation_0-mae:2098.23894
[479]	validation_0-mae:2098.23938
[480]	validation_0-mae:2098.08415
[481]	validation_0-mae:2097.63693
[482]	validation_0-mae:2097.44586
[483]	validation_0-mae:2097.38853
[484]	validation_0-mae:2097.34480
[485]	validation_0-mae:2096.94377
[486]	validation_0-mae:2096.38607
[487]	validation_0-mae:2096.32148
[488]	validation_0-mae:2095.80970
[489]	validation_0-mae:2095.71251
[490]	validation_0-mae:2095.55733
[491]	validation_0-mae:2095.56635
[492]	validation_0-mae:2095.82098
[493]	validation_0-mae:2095.56780
[494]	validation_0-mae:2095.74768
[495]	validation_0-mae:2095.41237
[496]	validation_0-mae:2095.78706
[497]	validation_0-mae:2095.40298
[498]	validation_0-mae:2095.45787
[499]	validation_0-mae:2095.17217
[500]	validation_0-mae:2095.26748
[501]	validation_0-mae:2095.15111
[502]	validation_0-mae:2095.22793
[503]	validation_0-mae:2094.48715
[504]	validation_0-mae:2094.71490
[505]	validation_0-mae:2095.02994
[506]	validation_0-mae:2094.48628
[507]	validation_0-mae:2094.41268
[508]	validation_0-mae:2095.08263
[509]	validation_0-mae:2094.94014
[510]	validation_0-mae:2095.01032
[511]	validation_0-mae:2094.45912
[512]	validation_0-mae:2094.50251
[513]	validation_0-mae:2094.72620
[514]	validation_0-mae:2094.62072
[515]	validation_0-mae:2094.90644
[516]	validation_0-mae:2095.02078
[517]	validation_0-mae:2094.42650
[518]	validation_0-mae:2094.76875
[519]	validation_0-mae:2094.37451
[520]	validation_0-mae:2094.46545
[521]	validation_0-mae:2094.59385
[522]	validation_0-mae:2094.33423
[523]	validation_0-mae:2094.22577
[524]	validation_0-mae:2094.14102
[525]	validation_0-mae:2093.50511
[526]	validation_0-mae:2093.46344
[527]	validation_0-mae:2093.34652
[528]	validation_0-mae:2093.59214
[529]	validation_0-mae:2093.53992
[530]	validation_0-mae:2092.37384
[531]	validation_0-mae:2092.37782
[532]	validation_0-mae:2092.26197
[533]	validation_0-mae:2092.42591
[534]	validation_0-mae:2092.35627
[535]	validation_0-mae:2092.33242
[536]	validation_0-mae:2092.42365
[537]	validation_0-mae:2092.20848
[538]	validation_0-mae:2092.01001
[539]	validation_0-mae:2092.50634
[540]	validation_0-mae:2092.44837
[541]	validation_0-mae:2092.74967
[542]	validation_0-mae:2092.96807
[543]	validation_0-mae:2093.31814
[544]	validation_0-mae:2093.43615
[545]	validation_0-mae:2093.46443
[546]	validation_0-mae:2093.32316
[547]	validation_0-mae:2092.67005
[548]	validation_0-mae:2092.79617
[549]	validation_0-mae:2092.97166
[550]	validation_0-mae:2092.72285
[551]	validation_0-mae:2092.74919
[552]	validation_0-mae:2092.51810
[553]	validation_0-mae:2092.92594
[554]	validation_0-mae:2092.61470
[555]	validation_0-mae:2092.68131
[556]	validation_0-mae:2092.38612
[557]	validation_0-mae:2092.41366
[558]	validation_0-mae:2092.27603
[559]	validation_0-mae:2092.52287
[560]	validation_0-mae:2092.46619
[561]	validation_0-mae:2092.80704
[562]	validation_0-mae:2092.90346
[563]	validation_0-mae:2092.88285
[564]	validation_0-mae:2092.97958
[565]	validation_0-mae:2093.08225
[566]	validation_0-mae:2093.05239
[567]	validation_0-mae:2093.18970
[568]	validation_0-mae:2092.98943
[569]	validation_0-mae:2093.05448
[570]	validation_0-mae:2092.66642
[571]	validation_0-mae:2092.62845
[572]	validation_0-mae:2092.84380
[573]	validation_0-mae:2092.29374
[574]	validation_0-mae:2092.22350
[575]	validation_0-mae:2092.62060
[576]	validation_0-mae:2092.98292
[577]	validation_0-mae:2092.71196
[578]	validation_0-mae:2092.12403
[579]	validation_0-mae:2091.68739
[580]	validation_0-mae:2091.66735
[581]	validation_0-mae:2092.04606
[582]	validation_0-mae:2092.16969
[583]	validation_0-mae:2092.29840
[584]	validation_0-mae:2092.10208
[585]	validation_0-mae:2092.09633
[586]	validation_0-mae:2092.49487
[587]	validation_0-mae:2092.77251
[588]	validation_0-mae:2092.88694
[589]	validation_0-mae:2093.06430
[590]	validation_0-mae:2093.25814
[591]	validation_0-mae:2093.05246
[592]	validation_0-mae:2093.17230
[593]	validation_0-mae:2093.21415
[594]	validation_0-mae:2092.89322
[595]	validation_0-mae:2093.05372
[596]	validation_0-mae:2092.90146
[597]	validation_0-mae:2093.13179
[598]	validation_0-mae:2093.46364
[599]	validation_0-mae:2093.29413
[600]	validation_0-mae:2093.48477
[601]	validation_0-mae:2092.98082
[602]	validation_0-mae:2093.03666
[603]	validation_0-mae:2093.13819
[604]	validation_0-mae:2093.21713
[605]	validation_0-mae:2093.22141
[606]	validation_0-mae:2093.28224
[607]	validation_0-mae:2093.03756
[608]	validation_0-mae:2093.05653
[609]	validation_0-mae:2092.67418
[610]	validation_0-mae:2092.47516
[611]	validation_0-mae:2091.62532
[612]	validation_0-mae:2091.58345
[613]	validation_0-mae:2091.28927
[614]	validation_0-mae:2090.89433
[615]	validation_0-mae:2090.88737
[616]	validation_0-mae:2090.28876
[617]	validation_0-mae:2090.10746
[618]	validation_0-mae:2089.87289
[619]	validation_0-mae:2089.46661
[620]	validation_0-mae:2089.51281
[621]	validation_0-mae:2089.17137
[622]	validation_0-mae:2089.22282
[623]	validation_0-mae:2089.06218
[624]	validation_0-mae:2088.94249
[625]	validation_0-mae:2089.03337
[626]	validation_0-mae:2088.59056
[627]	validation_0-mae:2088.52339
[628]	validation_0-mae:2088.40344
[629]	validation_0-mae:2088.56976

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[42]	validation_0-mae:3323.98990
[43]	validation_0-mae:3279.39472
[44]	validation_0-mae:3246.89767
[45]	validation_0-mae:3214.53495
[46]	validation_0-mae:3180.57742
[47]	validation_0-mae:3151.80308
[48]	validation_0-mae:3124.99477
[49]	validation_0-mae:3080.57584
[50]	validation_0-mae:3053.84402
[51]	validation_0-mae:3033.04724
[52]	validation_0-mae:3015.02911
[53]	validation_0-mae:2989.45419
[0]	validation_0-mae:12500.22008
[1]	validation_0-mae:11809.48040
[2]	validation_0-mae:11181.55635
[3]	validation_0-mae:10582.85754
[4]	validation_0-mae:10049.72564
[5]	validation_0-mae:9567.94173
[6]	validation_0-mae:9123.22176
[7]	validation_0-mae:8714.06763
[8]	validation_0-mae:8354.68329
[9]	validation_0-mae:8011.09251
[10]	validation_0-mae:7692.24357

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[0]	validation_0-mae:12458.95881
[1]	validation_0-mae:11735.87352
[2]	validation_0-mae:11085.15717
[3]	validation_0-mae:10454.66487
[4]	validation_0-mae:9910.64359
[5]	validation_0-mae:9406.54722
[6]	validation_0-mae:8950.59882
[7]	validation_0-mae:8524.24004
[8]	validation_0-mae:8156.03797
[9]	validation_0-mae:7808.67993
[10]	validation_0-mae:7498.28443
[11]	validation_0-mae:7202.08285
[12]	validation_0-mae:6944.71438
[13]	validation_0-mae:6690.38592
[14]	validation_0-mae:6434.60861
[15]	validation_0-mae:6202.72033
[16]	validation_0-mae:5967.75776
[17]	validation_0-mae:5769.01133
[18]	validation_0-mae:5588.24568
[19]	validation_0-mae:5422.65515
[20]	validation_0-mae:5260.06715
[21]	validation_0-mae:5101.10440
[22]	validation_0-mae:4945.86483
[23]	validation_0-mae:4806.68244
[24]	validation_0-mae:4672.70785
[25]	validation_0-mae:4545.28842
[26]	validation_0-mae:4435.69424
[27]	validation_0-mae:4330.42536
[28]	validation_0-mae:4228.58738
[29]	validation_0-mae:4127.89442
[30]	validation_0-mae:4043.92185
[31]	validation_0-mae:3951.11095
[32]	validation_0-mae:3865.04791
[33]	validation_0-mae:3785.56837
[34]	validation_0-mae:3711.62137
[35]	validation_0-mae:3647.90648
[36]	validation_0-mae:3579.41930
[37]	validation_0-mae:3526.01317
[38]	validation_0-mae:3461.45710
[39]	validation_0-mae:3411.88804
[40]	validation_0-mae:3359.34168
[41]	validation_0-mae:3310.40662
[42]	validation_0-mae:3255.14109
[43]	validation_0-mae:3204.21710
[44]	validation_0-mae:3171.21841
[45]	validation_0-mae:3133.08372
[46]	validation_0-mae:3097.72340
[47]	validation_0-mae:3066.53898
[48]	validation_0-mae:3038.90370
[49]	validation_0-mae:3014.70935
[50]	validation_0-mae:2993.90405
[51]	validation_0-mae:2966.84700
[52]	validation_0-mae:2944.90485
[53]	validation_0-mae:2919.93663
[54]	validation_0-mae:2890.69853
[55]	validation_0-mae:2870.42970
[56]	validation_0-mae:2844.00909
[57]	validation_0-mae:2819.75823
[58]	validation_0-mae:2802.49160
[59]	validation_0-mae:2791.38122
[60]	validation_0-mae:2776.10731
[61]	validation_0-mae:2762.13824
[62]	validation_0-mae:2747.88391
[63]	validation_0-mae:2721.97562
[64]	validation_0-mae:2701.08103
[65]	validation_0-mae:2680.92534
[66]	validation_0-mae:2669.79447
[67]	validation_0-mae:2660.81591
[68]	validation_0-mae:2649.12042
[69]	validation_0-mae:2632.41523
[70]	validation_0-mae:2621.19657
[71]	validation_0-mae:2612.03629
[72]	validation_0-mae:2596.98706
[73]	validation_0-mae:2580.38875
[74]	validation_0-mae:2571.13762
[75]	validation_0-mae:2560.86328
[76]	validation_0-mae:2555.33485
[77]	validation_0-mae:2546.98744
[78]	validation_0-mae:2538.18970
[79]	validation_0-mae:2522.70813
[80]	validation_0-mae:2513.59314
[81]	validation_0-mae:2501.61481
[82]	validation_0-mae:2493.94672
[83]	validation_0-mae:2483.55705
[84]	validation_0-mae:2477.02112
[85]	validation_0-mae:2470.65797
[86]	validation_0-mae:2463.89209
[87]	validation_0-mae:2457.73704
[88]	validation_0-mae:2454.72412
[89]	validation_0-mae:2445.71333
[90]	validation_0-mae:2440.16256
[91]	validation_0-mae:2427.91986
[92]	validation_0-mae:2420.40697
[93]	validation_0-mae:2415.29706
[94]	validation_0-mae:2409.93150
[95]	validation_0-mae:2402.38979
[96]	validation_0-mae:2398.00933
[97]	validation_0-mae:2391.40997
[98]	validation_0-mae:2385.38794
[99]	validation_0-mae:2380.54229
[100]	validation_0-mae:2374.30322
[101]	validation_0-mae:2365.54735
[102]	validation_0-mae:2362.83095
[103]	validation_0-mae:2357.14579
[104]	validation_0-mae:2352.72271
[105]	validation_0-mae:2348.38436
[106]	validation_0-mae:2339.23090
[107]	validation_0-mae:2335.88049
[108]	validation_0-mae:2333.53238
[109]	validation_0-mae:2330.94678
[110]	validation_0-mae:2324.05047
[111]	validation_0-mae:2320.91878
[112]	validation_0-mae:2315.43744
[113]	validation_0-mae:2312.85693
[114]	validation_0-mae:2310.97880
[115]	validation_0-mae:2306.34078
[116]	validation_0-mae:2298.45756
[117]	validation_0-mae:2297.59962
[118]	validation_0-mae:2293.47945
[119]	validation_0-mae:2289.69768
[120]	validation_0-mae:2284.64963
[121]	validation_0-mae:2278.18908
[122]	validation_0-mae:2277.05184
[123]	validation_0-mae:2273.66086
[124]	validation_0-mae:2270.55609
[125]	validation_0-mae:2266.88970
[126]	validation_0-mae:2263.35362
[127]	validation_0-mae:2262.45980
[128]	validation_0-mae:2258.82260
[129]	validation_0-mae:2256.72758
[130]	validation_0-mae:2255.44260
[131]	validation_0-mae:2253.28023
[132]	validation_0-mae:2249.17257
[133]	validation_0-mae:2248.82430
[134]	validation_0-mae:2244.51128
[135]	validation_0-mae:2241.58878
[136]	validation_0-mae:2239.24129
[137]	validation_0-mae:2238.76341
[138]	validation_0-mae:2233.93924
[139]	validation_0-mae:2232.17137
[140]	validation_0-mae:2230.71211
[141]	validation_0-mae:2230.16446
[142]	validation_0-mae:2227.83345
[143]	validation_0-mae:2225.88830
[144]	validation_0-mae:2223.62866
[145]	validation_0-mae:2221.00880
[146]	validation_0-mae:2219.82549
[147]	validation_0-mae:2219.20255
[148]	validation_0-mae:2219.87202
[149]	validation_0-mae:2218.13519
[150]	validation_0-mae:2215.85805
[151]	validation_0-mae:2214.32183
[152]	validation_0-mae:2212.36567
[153]	validation_0-mae:2208.46458
[154]	validation_0-mae:2208.45474
[155]	validation_0-mae:2207.28351
[156]	validation_0-mae:2203.16842
[157]	validation_0-mae:2200.42518
[158]	validation_0-mae:2197.71129
[159]	validation_0-mae:2196.63260
[160]	validation_0-mae:2196.31298
[161]	validation_0-mae:2196.19267
[162]	validation_0-mae:2195.15254
[163]	validation_0-mae:2192.08030
[164]	validation_0-mae:2190.31437
[165]	validation_0-mae:2188.58910
[166]	validation_0-mae:2189.19868
[167]	validation_0-mae:2187.87420
[168]	validation_0-mae:2187.20619
[169]	validation_0-mae:2186.28024
[170]	validation_0-mae:2185.44474
[171]	validation_0-mae:2185.29882
[172]	validation_0-mae:2185.22525
[173]	validation_0-mae:2184.92915
[174]	validation_0-mae:2184.77912
[175]	validation_0-mae:2183.87559
[176]	validation_0-mae:2182.89675
[177]	validation_0-mae:2182.70763
[178]	validation_0-mae:2182.88317
[179]	validation_0-mae:2181.88270
[180]	validation_0-mae:2181.62569
[181]	validation_0-mae:2176.83472
[182]	validation_0-mae:2176.11539
[183]	validation_0-mae:2175.81079
[184]	validation_0-mae:2173.13044
[185]	validation_0-mae:2171.23181
[186]	validation_0-mae:2171.30341
[187]	validation_0-mae:2169.26624
[188]	validation_0-mae:2168.65337
[189]	validation_0-mae:2167.52673
[190]	validation_0-mae:2167.94878
[191]	validation_0-mae:2165.34350
[192]	validation_0-mae:2164.88377
[193]	validation_0-mae:2165.47617
[194]	validation_0-mae:2164.83671
[195]	validation_0-mae:2165.44333
[196]	validation_0-mae:2164.79506
[197]	validation_0-mae:2163.07181
[198]	validation_0-mae:2164.12771
[199]	validation_0-mae:2163.66194
[200]	validation_0-mae:2163.35110
[201]	validation_0-mae:2162.57850
[202]	validation_0-mae:2161.14701
[203]	validation_0-mae:2160.43906
[204]	validation_0-mae:2159.50722
[205]	validation_0-mae:2159.37595
[206]	validation_0-mae:2157.63313
[207]	validation_0-mae:2156.39051
[208]	validation_0-mae:2155.83196
[209]	validation_0-mae:2155.18962
[210]	validation_0-mae:2153.18077
[211]	validation_0-mae:2152.55109
[212]	validation_0-mae:2150.68774
[213]	validation_0-mae:2150.15874
[214]	validation_0-mae:2148.88481
[215]	validation_0-mae:2148.01517
[216]	validation_0-mae:2147.87480
[217]	validation_0-mae:2146.20385
[218]	validation_0-mae:2146.96175
[219]	validation_0-mae:2147.66677
[220]	validation_0-mae:2147.35313
[221]	validation_0-mae:2144.99371
[222]	validation_0-mae:2143.47990
[223]	validation_0-mae:2143.43976
[224]	validation_0-mae:2141.77874
[225]	validation_0-mae:2141.97228
[226]	validation_0-mae:2141.95662
[227]	validation_0-mae:2142.18607
[228]	validation_0-mae:2142.01224
[229]	validation_0-mae:2140.99312
[230]	validation_0-mae:2139.32908
[231]	validation_0-mae:2138.73978
[232]	validation_0-mae:2137.88314
[233]	validation_0-mae:2138.31970
[234]	validation_0-mae:2137.60442
[235]	validation_0-mae:2136.92927
[236]	validation_0-mae:2136.91676
[237]	validation_0-mae:2136.41815
[238]	validation_0-mae:2136.27380
[239]	validation_0-mae:2136.00780
[240]	validation_0-mae:2135.73596
[241]	validation_0-mae:2134.23809
[242]	validation_0-mae:2134.31356
[243]	validation_0-mae:2134.09563
[244]	validation_0-mae:2133.68286
[245]	validation_0-mae:2133.62045
[246]	validation_0-mae:2133.66280
[247]	validation_0-mae:2132.44545
[248]	validation_0-mae:2132.29400
[249]	validation_0-mae:2130.56309
[250]	validation_0-mae:2129.97655
[251]	validation_0-mae:2128.18720
[252]	validation_0-mae:2126.88762
[253]	validation_0-mae:2126.90424
[254]	validation_0-mae:2127.54716
[255]	validation_0-mae:2126.49347
[256]	validation_0-mae:2125.73850
[257]	validation_0-mae:2125.31138
[258]	validation_0-mae:2124.46580
[259]	validation_0-mae:2124.34710
[260]	validation_0-mae:2123.11262
[261]	validation_0-mae:2123.77894
[262]	validation_0-mae:2123.78986
[263]	validation_0-mae:2123.30244
[264]	validation_0-mae:2123.30871
[265]	validation_0-mae:2122.82923
[266]	validation_0-mae:2122.96263
[267]	validation_0-mae:2122.60063
[268]	validation_0-mae:2122.48216
[269]	validation_0-mae:2121.74806
[270]	validation_0-mae:2121.16152
[271]	validation_0-mae:2120.16608
[272]	validation_0-mae:2119.67050
[273]	validation_0-mae:2119.27764
[274]	validation_0-mae:2118.71964
[275]	validation_0-mae:2118.31224
[276]	validation_0-mae:2117.99066
[277]	validation_0-mae:2117.37534
[278]	validation_0-mae:2116.00516
[279]	validation_0-mae:2116.03571
[280]	validation_0-mae:2114.72083
[281]	validation_0-mae:2115.56227
[282]	validation_0-mae:2114.79642
[283]	validation_0-mae:2114.20167
[284]	validation_0-mae:2114.18716
[285]	validation_0-mae:2113.44847
[286]	validation_0-mae:2112.49007
[287]	validation_0-mae:2111.64484
[288]	validation_0-mae:2112.11908
[289]	validation_0-mae:2111.53151
[290]	validation_0-mae:2109.54699
[291]	validation_0-mae:2108.87759
[292]	validation_0-mae:2107.50172
[293]	validation_0-mae:2107.64913
[294]	validation_0-mae:2106.57438
[295]	validation_0-mae:2106.53153
[296]	validation_0-mae:2105.71205
[297]	validation_0-mae:2106.23986
[298]	validation_0-mae:2106.59360
[299]	validation_0-mae:2106.69643
[300]	validation_0-mae:2107.12181
[301]	validation_0-mae:2106.92804
[302]	validation_0-mae:2107.78188
[303]	validation_0-mae:2107.72615
[304]	validation_0-mae:2106.26027
[305]	validation_0-mae:2106.39758
[306]	validation_0-mae:2104.06485
[307]	validation_0-mae:2102.61412
[308]	validation_0-mae:2102.11571
[309]	validation_0-mae:2101.43609
[310]	validation_0-mae:2099.94304
[311]	validation_0-mae:2099.75315
[312]	validation_0-mae:2098.99879
[313]	validation_0-mae:2098.77754
[314]	validation_0-mae:2098.07602
[315]	validation_0-mae:2097.48458
[316]	validation_0-mae:2097.35364
[317]	validation_0-mae:2097.22366
[318]	validation_0-mae:2096.74451
[319]	validation_0-mae:2097.49053
[320]	validation_0-mae:2097.13740
[321]	validation_0-mae:2096.69992
[322]	validation_0-mae:2097.12147
[323]	validation_0-mae:2096.62420
[324]	validation_0-mae:2095.49796
[325]	validation_0-mae:2094.62975
[326]	validation_0-mae:2094.53560
[327]	validation_0-mae:2094.56774
[328]	validation_0-mae:2094.01255
[329]	validation_0-mae:2091.47378
[330]	validation_0-mae:2091.25782
[331]	validation_0-mae:2090.67025
[332]	validation_0-mae:2090.55609
[333]	validation_0-mae:2088.32615
[334]	validation_0-mae:2088.56125
[335]	validation_0-mae:2086.72615
[336]	validation_0-mae:2086.36457
[337]	validation_0-mae:2086.26681
[338]	validation_0-mae:2085.47181
[339]	validation_0-mae:2084.83855
[340]	validation_0-mae:2084.42016
[341]	validation_0-mae:2085.12406
[342]	validation_0-mae:2085.86973
[343]	validation_0-mae:2085.18775
[344]	validation_0-mae:2084.40367
[345]	validation_0-mae:2084.56654
[346]	validation_0-mae:2083.90342
[347]	validation_0-mae:2082.90382
[348]	validation_0-mae:2082.76259
[349]	validation_0-mae:2082.72930
[350]	validation_0-mae:2082.34294
[351]	validation_0-mae:2082.83441
[352]	validation_0-mae:2083.14004
[353]	validation_0-mae:2083.45963
[354]	validation_0-mae:2083.36655
[355]	validation_0-mae:2083.18418
[356]	validation_0-mae:2083.15098
[357]	validation_0-mae:2083.60702
[358]	validation_0-mae:2083.68665
[359]	validation_0-mae:2082.91533
[360]	validation_0-mae:2083.27014
[361]	validation_0-mae:2083.59846
[362]	validation_0-mae:2083.18115
[363]	validation_0-mae:2083.04618
[364]	validation_0-mae:2083.14137
[365]	validation_0-mae:2083.04798
[366]	validation_0-mae:2082.98199
[367]	validation_0-mae:2082.52473
[368]	validation_0-mae:2083.12098
[369]	validation_0-mae:2082.72445
[370]	validation_0-mae:2082.97541
[371]	validation_0-mae:2083.43113
[372]	validation_0-mae:2083.38909
[373]	validation_0-mae:2083.77007
[374]	validation_0-mae:2083.65509
[375]	validation_0-mae:2083.72995
[376]	validation_0-mae:2083.65555
[377]	validation_0-mae:2083.88268
[378]	validation_0-mae:2083.36924
[379]	validation_0-mae:2083.29280
[380]	validation_0-mae:2083.17910
[381]	validation_0-mae:2083.11806
[382]	validation_0-mae:2082.20184
[383]	validation_0-mae:2082.66529
[384]	validation_0-mae:2082.14615
[385]	validation_0-mae:2081.96265
[386]	validation_0-mae:2081.63629
[387]	validation_0-mae:2081.46775
[388]	validation_0-mae:2081.59588
[389]	validation_0-mae:2080.91738
[390]	validation_0-mae:2079.71962
[391]	validation_0-mae:2079.85387
[392]	validation_0-mae:2080.23150
[393]	validation_0-mae:2080.65368
[394]	validation_0-mae:2080.22476
[395]	validation_0-mae:2080.39504
[396]	validation_0-mae:2081.24068
[397]	validation_0-mae:2081.37252
[398]	validation_0-mae:2082.14119
[399]	validation_0-mae:2081.90666
[400]	validation_0-mae:2081.99922
[401]	validation_0-mae:2081.31897
[402]	validation_0-mae:2081.96117
[403]	validation_0-mae:2081.79705
[404]	validation_0-mae:2081.33454
[405]	validation_0-mae:2081.41779
[406]	validation_0-mae:2081.57460
[407]	validation_0-mae:2081.91100
[408]	validation_0-mae:2082.20442
[409]	validation_0-mae:2082.19436
[410]	validation_0-mae:2081.92192
[411]	validation_0-mae:2081.69278
[412]	validation_0-mae:2081.53811
[413]	validation_0-mae:2081.29731
[414]	validation_0-mae:2081.33125
[415]	validation_0-mae:2081.36450
[416]	validation_0-mae:2081.54582
[417]	validation_0-mae:2081.67345
[418]	validation_0-mae:2081.72415
[419]	validation_0-mae:2081.94837
[420]	validation_0-mae:2081.80297
[421]	validation_0-mae:2082.06801
[422]	validation_0-mae:2082.51761
[423]	validation_0-mae:2082.54782
[424]	validation_0-mae:2082.27107
[425]	validation_0-mae:2082.89292
[426]	validation_0-mae:2083.45115
[427]	validation_0-mae:2084.22158
[428]	validation_0-mae:2084.33479
[429]	validation_0-mae:2084.70452
[430]	validation_0-mae:2084.98970
[431]	validation_0-mae:2085.58037
[432]	validation_0-mae:2085.81813
[433]	validation_0-mae:2086.05407
[434]	validation_0-mae:2085.82768
[435]	validation_0-mae:2086.35010
[436]	validation_0-mae:2086.57029
[437]	validation_0-mae:2086.79962
[438]	validation_0-mae:2086.45686
[439]	validation_0-mae:2086.64509
[440]	validation_0-mae:2086.95443
[441]	validation_0-mae:2086.50600
[442]	validation_0-mae:2086.59051
[443]	validation_0-mae:2086.78030
[444]	validation_0-mae:2087.14248
[445]	validation_0-mae:2086.71528
[446]	validation_0-mae:2086.82238
[447]	validation_0-mae:2087.12937
[448]	validation_0-mae:2087.17043
[449]	validation_0-mae:2087.34591
[450]	validation_0-mae:2087.22841
[451]	validation_0-mae:2087.19449
[452]	validation_0-mae:2087.19480
[453]	validation_0-mae:2087.65900
[454]	validation_0-mae:2087.59585
[455]	validation_0-mae:2087.39233
[456]	validation_0-mae:2087.42443
[457]	validation_0-mae:2087.33076
[458]	validation_0-mae:2086.33122
[459]	validation_0-mae:2086.33761
[460]	validation_0-mae:2086.26304
[461]	validation_0-mae:2085.85470
[462]	validation_0-mae:2085.66464
[463]	validation_0-mae:2085.59294
[464]	validation_0-mae:2085.44570
[465]	validation_0-mae:2085.75322
[466]	validation_0-mae:2086.16390
[467]	validation_0-mae:2086.42399
[468]	validation_0-mae:2085.76128
[469]	validation_0-mae:2086.02601
[470]	validation_0-mae:2085.87375
[471]	validation_0-mae:2085.69569
[472]	validation_0-mae:2085.25249
[473]	validation_0-mae:2084.95602
[474]	validation_0-mae:2085.39312
[475]	validation_0-mae:2085.35592
[476]	validation_0-mae:2085.02657
[477]	validation_0-mae:2085.10399
[478]	validation_0-mae:2085.09887
[479]	validation_0-mae:2084.96098
[480]	validation_0-mae:2084.72839
[481]	validation_0-mae:2084.61840
[482]	validation_0-mae:2084.61474
[483]	validation_0-mae:2084.84876
[484]	validation_0-mae:2083.56157
[485]	validation_0-mae:2083.62629
[486]	validation_0-mae:2083.64085
[487]	validation_0-mae:2083.24509
[488]	validation_0-mae:2083.19786
[489]	validation_0-mae:2083.17055
[490]	validation_0-mae:2083.42138
[491]	validation_0-mae:2083.14464
[492]	validation_0-mae:2083.48441
[493]	validation_0-mae:2082.60344
[494]	validation_0-mae:2082.26564
[495]	validation_0-mae:2082.55573
[496]	validation_0-mae:2082.47262
[497]	validation_0-mae:2082.49863
[498]	validation_0-mae:2082.92115
[499]	validation_0-mae:2082.95385
[500]	validation_0-mae:2082.31455
[501]	validation_0-mae:2082.33012
[502]	validation_0-mae:2082.66417
[503]	validation_0-mae:2082.40623
[504]	validation_0-mae:2082.52950
[505]	validation_0-mae:2082.24539
[506]	validation_0-mae:2082.48595
[507]	validation_0-mae:2082.83546
[508]	validation_0-mae:2082.12821
[509]	validation_0-mae:2081.08703
[510]	validation_0-mae:2080.82114
[511]	validation_0-mae:2080.33683
[512]	validation_0-mae:2080.54432
[513]	validation_0-mae:2079.36147
[514]	validation_0-mae:2079.15652
[515]	validation_0-mae:2078.78348
[516]	validation_0-mae:2078.88171
[517]	validation_0-mae:2078.48067
[518]	validation_0-mae:2078.92597
[519]	validation_0-mae:2077.66771
[520]	validation_0-mae:2077.43834
[521]	validation_0-mae:2077.53095
[522]	validation_0-mae:2077.68242
[523]	validation_0-mae:2076.39445
[524]	validation_0-mae:2076.34931
[525]	validation_0-mae:2076.23072
[526]	validation_0-mae:2075.91683
[527]	validation_0-mae:2074.79739
[528]	validation_0-mae:2074.96051
[529]	validation_0-mae:2075.21682
[530]	validation_0-mae:2075.26379
[531]	validation_0-mae:2075.16399
[532]	validation_0-mae:2075.11759
[533]	validation_0-mae:2074.90865
[534]	validation_0-mae:2075.17502
[535]	validation_0-mae:2075.10779
[536]	validation_0-mae:2075.51556
[537]	validation_0-mae:2075.12084
[538]	validation_0-mae:2075.34395
[539]	validation_0-mae:2075.03762
[540]	validation_0-mae:2075.10283
[541]	validation_0-mae:2075.05284
[542]	validation_0-mae:2074.86936
[543]	validation_0-mae:2074.95011
[544]	validation_0-mae:2074.64977
[545]	validation_0-mae:2074.66827
[546]	validation_0-mae:2074.64158
[547]	validation_0-mae:2074.59565
[548]	validation_0-mae:2074.42570
[549]	validation_0-mae:2074.23083
[550]	validation_0-mae:2074.10050
[551]	validation_0-mae:2073.82493
[552]	validation_0-mae:2073.72308
[553]	validation_0-mae:2073.69165
[554]	validation_0-mae:2073.69731
[555]	validation_0-mae:2073.20675
[556]	validation_0-mae:2073.40242
[557]	validation_0-mae:2073.29410
[558]	validation_0-mae:2073.26204
[559]	validation_0-mae:2073.44511
[560]	validation_0-mae:2073.15572
[561]	validation_0-mae:2073.66387
[562]	validation_0-mae:2073.71708
[563]	validation_0-mae:2073.15412
[564]	validation_0-mae:2072.55387
[565]	validation_0-mae:2072.88595
[566]	validation_0-mae:2073.01605
[567]	validation_0-mae:2072.97215
[568]	validation_0-mae:2073.10188
[569]	validation_0-mae:2072.58195
[570]	validation_0-mae:2072.29953
[571]	validation_0-mae:2072.32160
[572]	validation_0-mae:2072.17686
[573]	validation_0-mae:2071.87041
[574]	validation_0-mae:2071.90673
[575]	validation_0-mae:2071.62424
[576]	validation_0-mae:2071.64102
[577]	validation_0-mae:2071.14575
[578]	validation_0-mae:2071.31243
[579]	validation_0-mae:2071.18215
[580]	validation_0-mae:2070.93919
[581]	validation_0-mae:2070.71656
[582]	validation_0-mae:2070.35691
[583]	validation_0-mae:2070.24667
[584]	validation_0-mae:2070.22725
[585]	validation_0-mae:2070.31506
[586]	validation_0-mae:2070.07117
[587]	validation_0-mae:2070.18705
[588]	validation_0-mae:2069.83084
[589]	validation_0-mae:2069.62376
[590]	validation_0-mae:2069.49310

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[1]	validation_0-mae:11753.90064
[2]	validation_0-mae:11108.16618
[3]	validation_0-mae:10533.30560
[4]	validation_0-mae:10015.34379
[5]	validation_0-mae:9561.54417
[6]	validation_0-mae:9162.62846
[7]	validation_0-mae:8794.94751
[8]	validation_0-mae:8478.40301
[9]	validation_0-mae:8180.60523
[0]	validation_0-mae:12417.99363
[1]	validation_0-mae:11668.49197
[2]	validation_0-mae:10994.79343
[3]	validation_0-mae:10347.82169
[4]	validation_0-mae:9794.37561
[5]	validation_0-mae:9276.42146
[6]	validation_0-mae:8812.16490
[7]	validation_0-mae:8391.07489
[8]	validation_0-mae:8006.47637
[9]	validation_0-mae:7646.04052
[10]	validation_0-mae:7348.71779
[11]	validation_0-mae:7024.65519
[12]	validation_0-mae:6728.36014
[13]	validation_0-mae:6477.27574
[14]	validation_0-mae:6249.03682
[15]	validation_0-mae:6016.60983
[16]	validation_0-mae:5776.97182
[17]	validation_0-mae:5575.11922
[18]	validation_0-mae:5390.38400
[19]	validation_0-mae:5236.07912
[20]	validation_0-mae:5082.00386
[21]	validation_0-mae:4913.47534
[22]	validation_0-mae:4774.80920
[23]	validation_0-mae:4652.04112
[24]	validation_0-mae:4516.80465
[25]	validation_0-mae:4409.23683
[26]	validation_0-mae:4290.94722
[27]	validation_0-mae:4173.25721
[28]	validation_0-mae:4070.03433
[29]	validation_0-mae:3970.73613
[30]	validation_0-mae:3883.23655
[31]	validation_0-mae:3791.85293
[32]	validation_0-mae:3707.94421
[33]	validation_0-mae:3644.76907
[34]	validation_0-mae:3571.60215
[35]	validation_0-mae:3510.79980
[36]	validation_0-mae:3456.14372
[37]	validation_0-mae:3398.60103
[38]	validation_0-mae:3349.52019

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[39]	validation_0-mae:3303.73822
[40]	validation_0-mae:3258.82056
[41]	validation_0-mae:3218.36076
[42]	validation_0-mae:3176.83450
[43]	validation_0-mae:3122.36047
[44]	validation_0-mae:3089.19598
[45]	validation_0-mae:3054.89914
[46]	validation_0-mae:3023.70159
[47]	validation_0-mae:3000.08621
[48]	validation_0-mae:2967.88787
[49]	validation_0-mae:2940.39041
[50]	validation_0-mae:2912.30338
[51]	validation_0-mae:2883.75466
[52]	validation_0-mae:2855.55405
[53]	validation_0-mae:2834.78997
[54]	validation_0-mae:2817.72291
[55]	validation_0-mae:2798.99146
[56]	validation_0-mae:2785.66313
[57]	validation_0-mae:2759.71704
[58]	validation_0-mae:2743.50714
[59]	validation_0-mae:2727.37687
[60]	validation_0-mae:2715.41637
[61]	validation_0-mae:2690.72248
[62]	validation_0-mae:2682.06746
[63]	validation_0-mae:2662.42681
[64]	validation_0-mae:2649.44502
[65]	validation_0-mae:2629.97908
[66]	validation_0-mae:2620.16910
[67]	validation_0-mae:2609.26492
[68]	validation_0-mae:2601.20961
[69]	validation_0-mae:2589.80641
[70]	validation_0-mae:2578.15120
[71]	validation_0-mae:2566.45465
[72]	validation_0-mae:2555.87520
[73]	validation_0-mae:2545.35736
[74]	validation_0-mae:2537.53798
[75]	validation_0-mae:2527.96445
[76]	validation_0-mae:2513.87660
[77]	validation_0-mae:2497.43443
[78]	validation_0-mae:2487.35524
[79]	validation_0-mae:2480.94259
[80]	validation_0-mae:2475.08683
[81]	validation_0-mae:2470.84036
[82]	validation_0-mae:2460.27011
[83]	validation_0-mae:2451.39879
[84]	validation_0-mae:2444.61605
[85]	validation_0-mae:2435.47875
[86]	validation_0-mae:2426.32180
[87]	validation_0-mae:2420.54085
[88]	validation_0-mae:2414.49727
[89]	validation_0-mae:2407.25149
[90]	validation_0-mae:2398.62432
[91]	validation_0-mae:2394.15023
[92]	validation_0-mae:2390.92360
[93]	validation_0-mae:2386.27038
[94]	validation_0-mae:2378.37071
[95]	validation_0-mae:2374.54116
[96]	validation_0-mae:2367.96717
[97]	validation_0-mae:2363.88024
[98]	validation_0-mae:2360.99551
[99]	validation_0-mae:2352.33911
[100]	validation_0-mae:2351.11770
[101]	validation_0-mae:2341.24876
[102]	validation_0-mae:2337.87241
[103]	validation_0-mae:2330.79540
[104]	validation_0-mae:2324.95151
[105]	validation_0-mae:2321.97125
[106]	validation_0-mae:2320.44512
[107]	validation_0-mae:2314.98876
[108]	validation_0-mae:2307.85083
[109]	validation_0-mae:2301.75757
[110]	validation_0-mae:2297.11531
[111]	validation_0-mae:2293.11798
[112]	validation_0-mae:2290.49212
[113]	validation_0-mae:2286.03400
[114]	validation_0-mae:2283.68631
[115]	validation_0-mae:2281.49604
[116]	validation_0-mae:2275.69891
[117]	validation_0-mae:2274.45592
[118]	validation_0-mae:2272.73388
[119]	validation_0-mae:2267.38583
[120]	validation_0-mae:2266.07904
[121]	validation_0-mae:2262.13242
[122]	validation_0-mae:2260.07497
[123]	validation_0-mae:2259.23621
[124]	validation_0-mae:2257.27882
[125]	validation_0-mae:2254.43076
[126]	validation_0-mae:2251.14231
[127]	validation_0-mae:2248.01223
[128]	validation_0-mae:2244.02758
[129]	validation_0-mae:2242.02585
[130]	validation_0-mae:2240.39868
[131]	validation_0-mae:2237.81458
[132]	validation_0-mae:2235.62426
[133]	validation_0-mae:2235.28827
[134]	validation_0-mae:2231.37026
[135]	validation_0-mae:2227.36404
[136]	validation_0-mae:2227.16951
[137]	validation_0-mae:2224.26002
[138]	validation_0-mae:2221.72336
[139]	validation_0-mae:2218.17480
[140]	validation_0-mae:2214.93137
[141]	validation_0-mae:2213.21469
[142]	validation_0-mae:2211.82158
[143]	validation_0-mae:2210.45487
[144]	validation_0-mae:2204.60286
[145]	validation_0-mae:2203.98806
[146]	validation_0-mae:2198.97208
[147]	validation_0-mae:2196.59118
[148]	validation_0-mae:2195.73338
[149]	validation_0-mae:2195.14153
[150]	validation_0-mae:2192.57956
[151]	validation_0-mae:2191.25252
[152]	validation_0-mae:2189.75968
[153]	validation_0-mae:2189.56079
[154]	validation_0-mae:2186.90855
[155]	validation_0-mae:2186.42663
[156]	validation_0-mae:2186.82284
[157]	validation_0-mae:2186.09935
[158]	validation_0-mae:2185.20042
[159]	validation_0-mae:2185.14268
[160]	validation_0-mae:2182.87294
[161]	validation_0-mae:2180.86111
[162]	validation_0-mae:2180.12139
[163]	validation_0-mae:2178.14917
[164]	validation_0-mae:2174.51105
[165]	validation_0-mae:2174.29360
[166]	validation_0-mae:2173.94840
[167]	validation_0-mae:2173.21776
[168]	validation_0-mae:2173.41770
[169]	validation_0-mae:2169.78375
[170]	validation_0-mae:2170.22871
[171]	validation_0-mae:2170.45217
[172]	validation_0-mae:2167.81314
[173]	validation_0-mae:2165.59157
[174]	validation_0-mae:2166.46482
[175]	validation_0-mae:2165.58405
[176]	validation_0-mae:2165.18311
[177]	validation_0-mae:2163.79394
[178]	validation_0-mae:2162.89831
[179]	validation_0-mae:2161.67157
[180]	validation_0-mae:2158.46800
[181]	validation_0-mae:2158.60189
[182]	validation_0-mae:2159.13438
[183]	validation_0-mae:2157.46667
[184]	validation_0-mae:2158.23378
[185]	validation_0-mae:2157.81529
[186]	validation_0-mae:2156.24571
[187]	validation_0-mae:2154.99729
[188]	validation_0-mae:2153.70322
[189]	validation_0-mae:2154.45952
[190]	validation_0-mae:2153.97252
[191]	validation_0-mae:2153.91517
[192]	validation_0-mae:2152.78193
[193]	validation_0-mae:2150.65549
[194]	validation_0-mae:2150.11670
[195]	validation_0-mae:2149.27913
[196]	validation_0-mae:2149.00188
[197]	validation_0-mae:2146.24053
[198]	validation_0-mae:2146.08217
[199]	validation_0-mae:2145.84194
[200]	validation_0-mae:2145.17238
[201]	validation_0-mae:2142.57628
[202]	validation_0-mae:2143.10399
[203]	validation_0-mae:2140.82986
[204]	validation_0-mae:2141.13722
[205]	validation_0-mae:2139.96808
[206]	validation_0-mae:2139.26891
[207]	validation_0-mae:2138.88727
[208]	validation_0-mae:2138.36904
[209]	validation_0-mae:2138.32183
[210]	validation_0-mae:2137.23045
[211]	validation_0-mae:2134.70282
[212]	validation_0-mae:2135.17857
[213]	validation_0-mae:2133.97611
[214]	validation_0-mae:2132.12895
[215]	validation_0-mae:2129.91069
[216]	validation_0-mae:2129.03043
[217]	validation_0-mae:2129.29072
[218]	validation_0-mae:2128.94005
[219]	validation_0-mae:2128.36928
[220]	validation_0-mae:2126.88846
[221]	validation_0-mae:2126.51029
[222]	validation_0-mae:2124.97865
[223]	validation_0-mae:2124.01076
[224]	validation_0-mae:2124.51717
[225]	validation_0-mae:2124.38745
[226]	validation_0-mae:2125.02287
[227]	validation_0-mae:2123.99939
[228]	validation_0-mae:2124.56322
[229]	validation_0-mae:2124.96036
[230]	validation_0-mae:2123.79623
[231]	validation_0-mae:2123.18893
[232]	validation_0-mae:2123.28092
[233]	validation_0-mae:2122.94533
[234]	validation_0-mae:2123.43108
[235]	validation_0-mae:2123.64259
[236]	validation_0-mae:2122.65266
[237]	validation_0-mae:2122.33056
[238]	validation_0-mae:2121.81433
[239]	validation_0-mae:2121.37301
[240]	validation_0-mae:2121.83152
[241]	validation_0-mae:2122.07564
[242]	validation_0-mae:2121.05550
[243]	validation_0-mae:2119.50345
[244]	validation_0-mae:2120.06578
[245]	validation_0-mae:2119.33722
[246]	validation_0-mae:2118.39994
[247]	validation_0-mae:2118.70965
[248]	validation_0-mae:2118.34270
[249]	validation_0-mae:2117.33979
[250]	validation_0-mae:2117.52961
[251]	validation_0-mae:2117.15014
[252]	validation_0-mae:2117.08054
[253]	validation_0-mae:2117.09555
[254]	validation_0-mae:2116.53861
[255]	validation_0-mae:2116.65298
[256]	validation_0-mae:2117.06835
[257]	validation_0-mae:2117.04381
[258]	validation_0-mae:2116.41637
[259]	validation_0-mae:2115.62755
[260]	validation_0-mae:2116.09642
[261]	validation_0-mae:2116.52587
[262]	validation_0-mae:2116.72178
[263]	validation_0-mae:2115.73629
[264]	validation_0-mae:2115.45821
[265]	validation_0-mae:2115.11415
[266]	validation_0-mae:2113.64879
[267]	validation_0-mae:2112.29853
[268]	validation_0-mae:2111.60745
[269]	validation_0-mae:2112.21690
[270]	validation_0-mae:2112.12720
[271]	validation_0-mae:2112.11597
[272]	validation_0-mae:2111.95717
[273]	validation_0-mae:2110.62418
[274]	validation_0-mae:2110.44189
[275]	validation_0-mae:2110.58131
[276]	validation_0-mae:2110.71211
[277]	validation_0-mae:2109.44448
[278]	validation_0-mae:2108.59123
[279]	validation_0-mae:2107.70735
[280]	validation_0-mae:2107.52081
[281]	validation_0-mae:2107.36205
[282]	validation_0-mae:2106.97229
[283]	validation_0-mae:2106.87509
[284]	validation_0-mae:2106.98663
[285]	validation_0-mae:2106.29691
[286]	validation_0-mae:2106.38023
[287]	validation_0-mae:2106.29268
[288]	validation_0-mae:2106.44597
[289]	validation_0-mae:2106.66056
[290]	validation_0-mae:2106.19467
[291]	validation_0-mae:2106.10477
[292]	validation_0-mae:2107.02311
[293]	validation_0-mae:2106.75037
[294]	validation_0-mae:2107.57688
[295]	validation_0-mae:2107.68400
[296]	validation_0-mae:2107.85331
[297]	validation_0-mae:2106.79556
[298]	validation_0-mae:2106.18277
[299]	validation_0-mae:2106.29211
[300]	validation_0-mae:2106.07991
[301]	validation_0-mae:2105.44224
[302]	validation_0-mae:2104.72226
[303]	validation_0-mae:2104.40637
[304]	validation_0-mae:2104.34941
[305]	validation_0-mae:2103.08080
[306]	validation_0-mae:2103.06313
[307]	validation_0-mae:2103.29154
[308]	validation_0-mae:2102.53528
[309]	validation_0-mae:2102.01276
[310]	validation_0-mae:2101.69662
[311]	validation_0-mae:2101.95306
[312]	validation_0-mae:2101.63429
[313]	validation_0-mae:2101.25143
[314]	validation_0-mae:2100.76085
[315]	validation_0-mae:2100.66811
[316]	validation_0-mae:2101.17594
[317]	validation_0-mae:2100.56283
[318]	validation_0-mae:2100.43307
[319]	validation_0-mae:2100.56754
[320]	validation_0-mae:2101.00152
[321]	validation_0-mae:2099.66512
[322]	validation_0-mae:2099.17346
[323]	validation_0-mae:2099.07850
[324]	validation_0-mae:2099.50324
[325]	validation_0-mae:2099.74642
[326]	validation_0-mae:2099.77061
[327]	validation_0-mae:2099.11995
[328]	validation_0-mae:2099.67720
[329]	validation_0-mae:2099.96096
[330]	validation_0-mae:2099.62881
[331]	validation_0-mae:2098.62111
[332]	validation_0-mae:2098.67346
[333]	validation_0-mae:2098.94385
[334]	validation_0-mae:2099.24009
[335]	validation_0-mae:2099.22214
[336]	validation_0-mae:2098.98280
[337]	validation_0-mae:2098.25854
[338]	validation_0-mae:2098.85337
[339]	validation_0-mae:2098.90299
[340]	validation_0-mae:2097.78186
[341]	validation_0-mae:2098.15727
[342]	validation_0-mae:2098.16835
[343]	validation_0-mae:2097.73581
[344]	validation_0-mae:2096.86277
[345]	validation_0-mae:2095.80136
[346]	validation_0-mae:2095.07780
[347]	validation_0-mae:2094.86823
[348]	validation_0-mae:2094.74214
[349]	validation_0-mae:2094.87040
[350]	validation_0-mae:2094.96770
[351]	validation_0-mae:2094.72667
[352]	validation_0-mae:2094.73103
[353]	validation_0-mae:2095.05693
[354]	validation_0-mae:2095.27500
[355]	validation_0-mae:2095.24294
[356]	validation_0-mae:2094.18916
[357]	validation_0-mae:2093.17961
[358]	validation_0-mae:2093.09624
[359]	validation_0-mae:2094.07250
[360]	validation_0-mae:2094.25567
[361]	validation_0-mae:2094.91137
[362]	validation_0-mae:2095.34097
[363]	validation_0-mae:2094.92335
[364]	validation_0-mae:2095.39283
[365]	validation_0-mae:2095.34249
[366]	validation_0-mae:2095.88053
[367]	validation_0-mae:2095.67495
[368]	validation_0-mae:2095.67176
[369]	validation_0-mae:2095.50458
[370]	validation_0-mae:2095.43378
[371]	validation_0-mae:2095.69350
[372]	validation_0-mae:2094.65115
[373]	validation_0-mae:2094.71368
[374]	validation_0-mae:2094.72390
[375]	validation_0-mae:2094.71914
[376]	validation_0-mae:2095.10678
[377]	validation_0-mae:2095.13902
[378]	validation_0-mae:2094.44369
[379]	validation_0-mae:2094.97200
[380]	validation_0-mae:2094.88059
[381]	validation_0-mae:2095.15957
[382]	validation_0-mae:2095.41559
[383]	validation_0-mae:2094.28738
[384]	validation_0-mae:2094.09378
[385]	validation_0-mae:2094.43846
[386]	validation_0-mae:2094.34016
[387]	validation_0-mae:2094.29715
[388]	validation_0-mae:2093.80210
[389]	validation_0-mae:2093.52436
[390]	validation_0-mae:2093.60954
[391]	validation_0-mae:2093.79058
[392]	validation_0-mae:2093.52278
[393]	validation_0-mae:2093.65546
[394]	validation_0-mae:2093.92387
[395]	validation_0-mae:2093.79550
[396]	validation_0-mae:2093.78931
[397]	validation_0-mae:2093.57684
[398]	validation_0-mae:2093.29741
[399]	validation_0-mae:2093.47015
[400]	validation_0-mae:2093.69734
[401]	validation_0-mae:2093.42816
[402]	validation_0-mae:2093.33271
[403]	validation_0-mae:2093.77448
[404]	validation_0-mae:2093.77154
[405]	validation_0-mae:2094.42111
[406]	validation_0-mae:2094.66470
[407]	validation_0-mae:2094.63507
[408]	validation_0-mae:2095.18917
[409]	validation_0-mae:2095.14538
[410]	validation_0-mae:2095.22543
[411]	validation_0-mae:2094.57137
[412]	validation_0-mae:2094.78872
[413]	validation_0-mae:2094.08115
[414]	validation_0-mae:2093.81621
[415]	validation_0-mae:2093.49938
[416]	validation_0-mae:2093.09173
[417]	validation_0-mae:2091.88720
[418]	validation_0-mae:2091.55120
[419]	validation_0-mae:2091.30207
[420]	validation_0-mae:2091.07233
[421]	validation_0-mae:2091.26727
[422]	validation_0-mae:2091.15667
[423]	validation_0-mae:2091.70624
[424]	validation_0-mae:2091.53539
[425]	validation_0-mae:2091.39727
[426]	validation_0-mae:2092.29553
[427]	validation_0-mae:2092.35873
[428]	validation_0-mae:2092.88732
[429]	validation_0-mae:2092.84910
[430]	validation_0-mae:2092.92093
[431]	validation_0-mae:2093.28250
[432]	validation_0-mae:2093.26850
[433]	validation_0-mae:2093.07744
[434]	validation_0-mae:2092.89418
[435]	validation_0-mae:2092.97766
[436]	validation_0-mae:2092.75762
[437]	validation_0-mae:2092.19023
[438]	validation_0-mae:2091.76833
[439]	validation_0-mae:2091.78005
[440]	validation_0-mae:2091.59555
[441]	validation_0-mae:2091.05133
[442]	validation_0-mae:2090.73487
[443]	validation_0-mae:2090.37723
[444]	validation_0-mae:2089.45938
[445]	validation_0-mae:2089.80476
[446]	validation_0-mae:2089.57330
[447]	validation_0-mae:2089.43632
[448]	validation_0-mae:2089.14501
[449]	validation_0-mae:2088.97956
[450]	validation_0-mae:2088.23409
[451]	validation_0-mae:2087.81478
[452]	validation_0-mae:2088.12309
[453]	validation_0-mae:2087.71088
[454]	validation_0-mae:2087.95731
[455]	validation_0-mae:2087.67679
[456]	validation_0-mae:2087.80307
[457]	validation_0-mae:2087.21152
[458]	validation_0-mae:2087.42544
[459]	validation_0-mae:2087.07686
[460]	validation_0-mae:2086.99011
[461]	validation_0-mae:2086.80417
[462]	validation_0-mae:2086.53420
[463]	validation_0-mae:2086.55867
[464]	validation_0-mae:2086.25501
[465]	validation_0-mae:2086.41006
[466]	validation_0-mae:2086.36658
[467]	validation_0-mae:2086.04429
[468]	validation_0-mae:2085.64966
[469]	validation_0-mae:2085.34507
[470]	validation_0-mae:2085.71922
[471]	validation_0-mae:2085.52730
[472]	validation_0-mae:2085.43585
[473]	validation_0-mae:2085.41084
[474]	validation_0-mae:2085.48929
[475]	validation_0-mae:2085.08539
[476]	validation_0-mae:2085.44720
[477]	validation_0-mae:2085.70576
[478]	validation_0-mae:2085.84512
[479]	validation_0-mae:2085.77429
[480]	validation_0-mae:2086.05475
[481]	validation_0-mae:2085.76338
[482]	validation_0-mae:2085.86742
[483]	validation_0-mae:2085.73371
[484]	validation_0-mae:2085.65210
[485]	validation_0-mae:2085.20404
[486]	validation_0-mae:2085.22711
[487]	validation_0-mae:2085.25472
[488]	validation_0-mae:2085.13751
[489]	validation_0-mae:2085.05070
[490]	validation_0-mae:2085.14253
[491]	validation_0-mae:2085.00316
[492]	validation_0-mae:2084.32967
[493]	validation_0-mae:2083.89605
[494]	validation_0-mae:2084.00618
[495]	validation_0-mae:2083.71946
[496]	validation_0-mae:2083.73712
[497]	validation_0-mae:2083.12061
[498]	validation_0-mae:2082.88039
[499]	validation_0-mae:2082.87422
[500]	validation_0-mae:2082.96401
[501]	validation_0-mae:2082.97599
[502]	validation_0-mae:2082.80141
[503]	validation_0-mae:2082.01460
[504]	validation_0-mae:2081.99685
[505]	validation_0-mae:2082.32404
[506]	validation_0-mae:2082.10989
[507]	validation_0-mae:2082.28903
[508]	validation_0-mae:2081.51421
[509]	validation_0-mae:2081.47106
[510]	validation_0-mae:2081.38853
[511]	validation_0-mae:2081.09207
[512]	validation_0-mae:2081.33787
[513]	validation_0-mae:2081.32126
[514]	validation_0-mae:2081.03063
[515]	validation_0-mae:2081.28953
[516]	validation_0-mae:2081.05547
[517]	validation_0-mae:2080.71881
[518]	validation_0-mae:2080.95600
[519]	validation_0-mae:2080.67424
[520]	validation_0-mae:2080.92179
[521]	validation_0-mae:2080.52317
[522]	validation_0-mae:2080.26041
[523]	validation_0-mae:2079.70411
[524]	validation_0-mae:2079.57995
[525]	validation_0-mae:2079.41944
[526]	validation_0-mae:2079.57266
[527]	validation_0-mae:2079.15755
[528]	validation_0-mae:2079.05320
[529]	validation_0-mae:2078.98990
[530]	validation_0-mae:2078.81529
[531]	validation_0-mae:2078.09439
[532]	validation_0-mae:2077.88415
[533]	validation_0-mae:2077.97929
[534]	validation_0-mae:2077.92641
[535]	validation_0-mae:2077.97156
[536]	validation_0-mae:2077.95029
[537]	validation_0-mae:2077.81035
[538]	validation_0-mae:2077.57456
[539]	validation_0-mae:2077.86068
[540]	validation_0-mae:2077.62024
[541]	validation_0-mae:2077.42817
[542]	validation_0-mae:2077.55078
[543]	validation_0-mae:2077.62182
[544]	validation_0-mae:2076.87649
[545]	validation_0-mae:2076.35366
[546]	validation_0-mae:2075.59516
[547]	validation_0-mae:2075.50244
[548]	validation_0-mae:2075.29596
[549]	validation_0-mae:2074.80633
[550]	validation_0-mae:2075.10810
[551]	validation_0-mae:2074.76783
[552]	validation_0-mae:2075.09483
[553]	validation_0-mae:2075.05356
[554]	validation_0-mae:2074.80335
[555]	validation_0-mae:2074.85378
[556]	validation_0-mae:2074.93716
[557]	validation_0-mae:2074.44193
[558]	validation_0-mae:2074.37355
[559]	validation_0-mae:2074.47185
[560]	validation_0-mae:2074.41067
[561]	validation_0-mae:2074.47083
[562]	validation_0-mae:2074.47402
[563]	validation_0-mae:2074.51744
[564]	validation_0-mae:2074.68726
[565]	validation_0-mae:2074.71187
[566]	validation_0-mae:2074.79337
[567]	validation_0-mae:2074.46480
[568]	validation_0-mae:2074.52472
[569]	validation_0-mae:2074.44417
[570]	validation_0-mae:2074.23538
[571]	validation_0-mae:2074.16938
[572]	validation_0-mae:2074.14625
[573]	validation_0-mae:2074.08844
[574]	validation_0-mae:2074.12177
[575]	validation_0-mae:2074.17866
[576]	validation_0-mae:2074.10757
[577]	validation_0-mae:2073.62859
[578]	validation_0-mae:2073.55723
[579]	validation_0-mae:2073.35257
[580]	validation_0-mae:2073.53268
[581]	validation_0-mae:2073.41348
[582]	validation_0-mae:2073.05589
[583]	validation_0-mae:2072.31441
[584]	validation_0-mae:2072.22463
[585]	validation_0-mae:2072.02149
[586]	validation_0-mae:2071.79934
[587]	validation_0-mae:2071.88736
[588]	validation_0-mae:2071.80405
[589]	validation_0-mae:2071.86739
[590]	validation_0-mae:2071.51432
[591]	validation_0-mae:2071.03202
[592]	validation_0-mae:2070.86003
[593]	validation_0-mae:2070.87100
[594]	validation_0-mae:2070.75640
[595]	validation_0-mae:2070.34735
[596]	validation_0-mae:2070.60785
[597]	validation_0-mae:2070.77307
[598]	validation_0-mae:2070.12503
[599]	validation_0-mae:2070.26292
[600]	validation_0-mae:2070.05932
[601]	validation_0-mae:2069.87931
[602]	validation_0-mae:2070.09150
[603]	validation_0-mae:2070.37614
[604]	validation_0-mae:2070.41154
[605]	validation_0-mae:2070.54277
[606]	validation_0-mae:2070.86301
[607]	validation_0-mae:2070.67898
[608]	validation_0-mae:2070.74601
[609]	validation_0-mae:2070.80085
[610]	validation_0-mae:2070.31730
[611]	validation_0-mae:2070.19071
[612]	validation_0-mae:2070.25000
[613]	validation_0-mae:2070.21669
[614]	validation_0-mae:2070.27860
[615]	validation_0-mae:2070.32145
[616]	validation_0-mae:2070.51820
[617]	validation_0-mae:2070.61107
[618]	validation_0-mae:2070.73442
[619]	validation_0-mae:2070.66648
[620]	validation_0-mae:2070.21824
[621]	validation_0-mae:2070.16563
[622]	validation_0-mae:2070.35438
[623]	validation_0-mae:2070.49872
[624]	validation_0-mae:2070.52863
[625]	validation_0-mae:2070.63287
[626]	validation_0-mae:2070.38269
[627]	validation_0-mae:2070.63770
[628]	validation_0-mae:2070.93323

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[0]	validation_0-mae:12419.44994
[1]	validation_0-mae:11667.98155
[2]	validation_0-mae:10994.24661
[3]	validation_0-mae:10347.72334
[4]	validation_0-mae:9793.76374
[5]	validation_0-mae:9277.67177
[6]	validation_0-mae:8814.83978
[7]	validation_0-mae:8405.33920
[8]	validation_0-mae:8017.42186
[9]	validation_0-mae:7672.56833
[10]	validation_0-mae:7354.38459
[11]	validation_0-mae:7065.22657
[12]	validation_0-mae:6779.56313
[13]	validation_0-mae:6499.55591
[14]	validation_0-mae:6257.37597
[15]	validation_0-mae:6020.60495
[16]	validation_0-mae:5814.28790
[17]	validation_0-mae:5594.40519
[18]	validation_0-mae:5410.34802
[19]	validation_0-mae:5226.15552
[20]	validation_0-mae:5029.93769
[21]	validation_0-mae:4886.98288
[22]	validation_0-mae:4732.97781
[23]	validation_0-mae:4590.88137
[24]	validation_0-mae:4461.64970
[25]	validation_0-mae:4348.37281
[26]	validation_0-mae:4241.76992
[27]	validation_0-mae:4160.96439
[28]	validation_0-mae:4054.69182
[29]	validation_0-mae:3972.88818
[30]	validation_0-mae:3880.75961
[31]	validation_0-mae:3792.28060
[32]	validation_0-mae:3714.69249
[33]	validation_0-mae:3634.42798
[34]	validation_0-mae:3575.59548
[35]	validation_0-mae:3514.51275
[36]	validation_0-mae:3440.49990
[37]	validation_0-mae:3385.17837
[38]	validation_0-mae:3344.19846
[39]	validation_0-mae:3285.68802
[40]	validation_0-mae:3239.71134
[41]	validation_0-mae:3202.34489
[42]	validation_0-mae:3164.54306
[43]	validation_0-mae:3129.77311
[44]	validation_0-mae:3075.75013
[45]	validation_0-mae:3044.54912
[46]	validation_0-mae:3011.05312
[47]	validation_0-mae:2984.16911
[48]	validation_0-mae:2945.56386
[49]	validation_0-mae:2925.08793
[50]	validation_0-mae:2897.11227
[51]	validation_0-mae:2871.62244
[52]	validation_0-mae:2844.01617
[53]	validation_0-mae:2823.71918
[54]	validation_0-mae:2804.40775
[55]	validation_0-mae:2788.00871
[56]	validation_0-mae:2769.56078
[57]	validation_0-mae:2751.09711
[58]	validation_0-mae:2720.65249
[59]	validation_0-mae:2709.64120
[60]	validation_0-mae:2696.29512
[61]	validation_0-mae:2686.52191
[62]	validation_0-mae:2673.56677
[63]	validation_0-mae:2661.92084
[64]	validation_0-mae:2650.17242
[65]	validation_0-mae:2623.97993
[66]	validation_0-mae:2607.07019
[67]	validation_0-mae:2601.81895
[68]	validation_0-mae:2591.78120
[69]	validation_0-mae:2586.74462
[70]	validation_0-mae:2577.17543
[71]	validation_0-mae:2567.32355
[72]	validation_0-mae:2558.56002
[73]	validation_0-mae:2553.02049
[74]	validation_0-mae:2541.96562
[75]	validation_0-mae:2527.23865
[76]	validation_0-mae:2516.50089
[77]	validation_0-mae:2509.41171
[78]	validation_0-mae:2503.65432
[79]	validation_0-mae:2496.24659
[80]	validation_0-mae:2477.97592
[81]	validation_0-mae:2469.85565
[82]	validation_0-mae:2455.75918
[83]	validation_0-mae:2450.98184
[84]	validation_0-mae:2446.51269
[85]	validation_0-mae:2441.16765
[86]	validation_0-mae:2436.52586
[87]	validation_0-mae:2428.61485
[88]	validation_0-mae:2424.36993
[89]	validation_0-mae:2417.34817
[90]	validation_0-mae:2411.82227
[91]	validation_0-mae:2410.22646
[92]	validation_0-mae:2401.24602
[93]	validation_0-mae:2398.63757
[94]	validation_0-mae:2395.18415
[95]	validation_0-mae:2388.90243
[96]	validation_0-mae:2377.99625
[97]	validation_0-mae:2374.06677
[98]	validation_0-mae:2368.38782
[99]	validation_0-mae:2364.41895
[100]	validation_0-mae:2359.39668
[101]	validation_0-mae:2355.95413
[102]	validation_0-mae:2352.14514
[103]	validation_0-mae:2348.99285
[104]	validation_0-mae:2343.92507
[105]	validation_0-mae:2336.93465
[106]	validation_0-mae:2333.50403
[107]	validation_0-mae:2332.08078
[108]	validation_0-mae:2327.47795
[109]	validation_0-mae:2322.76726
[110]	validation_0-mae:2318.38235
[111]	validation_0-mae:2316.10228
[112]	validation_0-mae:2310.21358
[113]	validation_0-mae:2308.38873
[114]	validation_0-mae:2305.91322
[115]	validation_0-mae:2303.79711
[116]	validation_0-mae:2302.59004
[117]	validation_0-mae:2300.31172
[118]	validation_0-mae:2295.20332
[119]	validation_0-mae:2292.49573
[120]	validation_0-mae:2291.83950
[121]	validation_0-mae:2289.26436
[122]	validation_0-mae:2286.54172
[123]	validation_0-mae:2283.58882
[124]	validation_0-mae:2281.78106
[125]	validation_0-mae:2281.57814
[126]	validation_0-mae:2281.04234
[127]	validation_0-mae:2278.93790
[128]	validation_0-mae:2274.54030
[129]	validation_0-mae:2274.68474
[130]	validation_0-mae:2270.35138
[131]	validation_0-mae:2266.87750
[132]	validation_0-mae:2263.71485
[133]	validation_0-mae:2263.81284
[134]	validation_0-mae:2259.87471
[135]	validation_0-mae:2260.18042
[136]	validation_0-mae:2259.65424
[137]	validation_0-mae:2258.83157
[138]	validation_0-mae:2256.12966
[139]	validation_0-mae:2254.28569
[140]	validation_0-mae:2255.18243
[141]	validation_0-mae:2255.53049
[142]	validation_0-mae:2252.24112
[143]	validation_0-mae:2249.36096
[144]	validation_0-mae:2246.45606
[145]	validation_0-mae:2246.36810
[146]	validation_0-mae:2244.06656
[147]	validation_0-mae:2241.23249
[148]	validation_0-mae:2241.16877
[149]	validation_0-mae:2241.85534
[150]	validation_0-mae:2239.30632
[151]	validation_0-mae:2234.31125
[152]	validation_0-mae:2232.80713
[153]	validation_0-mae:2232.75165
[154]	validation_0-mae:2232.10622
[155]	validation_0-mae:2231.18071
[156]	validation_0-mae:2230.58243
[157]	validation_0-mae:2231.44583
[158]	validation_0-mae:2231.31089
[159]	validation_0-mae:2230.63812
[160]	validation_0-mae:2230.04490
[161]	validation_0-mae:2228.68151
[162]	validation_0-mae:2227.33815
[163]	validation_0-mae:2225.44255
[164]	validation_0-mae:2223.49303
[165]	validation_0-mae:2221.40135
[166]	validation_0-mae:2219.27989
[167]	validation_0-mae:2220.00143
[168]	validation_0-mae:2218.76354
[169]	validation_0-mae:2216.45683
[170]	validation_0-mae:2215.67329
[171]	validation_0-mae:2214.45715
[172]	validation_0-mae:2212.16727
[173]	validation_0-mae:2210.15236
[174]	validation_0-mae:2209.40524
[175]	validation_0-mae:2208.57914
[176]	validation_0-mae:2208.70774
[177]	validation_0-mae:2207.85855
[178]	validation_0-mae:2207.15904
[179]	validation_0-mae:2207.17757
[180]	validation_0-mae:2207.13982
[181]	validation_0-mae:2204.58673
[182]	validation_0-mae:2204.40688
[183]	validation_0-mae:2202.75063
[184]	validation_0-mae:2200.41998
[185]	validation_0-mae:2197.73485
[186]	validation_0-mae:2197.67715
[187]	validation_0-mae:2196.44867
[188]	validation_0-mae:2197.40215
[189]	validation_0-mae:2196.53631
[190]	validation_0-mae:2194.72315
[191]	validation_0-mae:2192.52079
[192]	validation_0-mae:2190.72250
[193]	validation_0-mae:2190.04501
[194]	validation_0-mae:2188.24698
[195]	validation_0-mae:2187.53449
[196]	validation_0-mae:2186.91181
[197]	validation_0-mae:2187.23521
[198]	validation_0-mae:2186.95535
[199]	validation_0-mae:2185.63022
[200]	validation_0-mae:2186.06507
[201]	validation_0-mae:2185.82415
[202]	validation_0-mae:2184.89812
[203]	validation_0-mae:2184.59030
[204]	validation_0-mae:2185.29914
[205]	validation_0-mae:2184.43055
[206]	validation_0-mae:2184.68508
[207]	validation_0-mae:2184.78293
[208]	validation_0-mae:2183.27556
[209]	validation_0-mae:2182.77721
[210]	validation_0-mae:2182.56414
[211]	validation_0-mae:2181.69055
[212]	validation_0-mae:2178.60875
[213]	validation_0-mae:2176.81727
[214]	validation_0-mae:2176.84786
[215]	validation_0-mae:2176.69526
[216]	validation_0-mae:2176.70328
[217]	validation_0-mae:2176.78720
[218]	validation_0-mae:2175.48752
[219]	validation_0-mae:2174.59712
[220]	validation_0-mae:2174.44618
[221]	validation_0-mae:2172.69656
[222]	validation_0-mae:2171.77688
[223]	validation_0-mae:2171.87419
[224]	validation_0-mae:2171.02247
[225]	validation_0-mae:2171.70550
[226]	validation_0-mae:2171.29951
[227]	validation_0-mae:2170.52387
[228]	validation_0-mae:2170.29519
[229]	validation_0-mae:2167.76313
[230]	validation_0-mae:2165.29162
[231]	validation_0-mae:2163.99914
[232]	validation_0-mae:2163.61249
[233]	validation_0-mae:2163.60572
[234]	validation_0-mae:2162.39423
[235]	validation_0-mae:2161.24298
[236]	validation_0-mae:2161.20786
[237]	validation_0-mae:2161.49730
[238]	validation_0-mae:2161.09498
[239]	validation_0-mae:2161.23191
[240]	validation_0-mae:2159.75754
[241]	validation_0-mae:2159.58075
[242]	validation_0-mae:2159.20626
[243]	validation_0-mae:2158.93730
[244]	validation_0-mae:2157.66503
[245]	validation_0-mae:2158.25249
[246]	validation_0-mae:2159.36130
[247]	validation_0-mae:2158.52436
[248]	validation_0-mae:2158.57420
[249]	validation_0-mae:2159.14336
[250]	validation_0-mae:2159.43472
[251]	validation_0-mae:2158.99787
[252]	validation_0-mae:2158.54705
[253]	validation_0-mae:2158.34755
[254]	validation_0-mae:2158.14835
[255]	validation_0-mae:2157.47973
[256]	validation_0-mae:2157.25921
[257]	validation_0-mae:2156.77616
[258]	validation_0-mae:2156.49504
[259]	validation_0-mae:2156.35949
[260]	validation_0-mae:2155.92944
[261]	validation_0-mae:2155.74312
[262]	validation_0-mae:2155.89678
[263]	validation_0-mae:2156.06005
[264]	validation_0-mae:2155.90046
[265]	validation_0-mae:2156.10599
[266]	validation_0-mae:2156.35564
[267]	validation_0-mae:2156.74709
[268]	validation_0-mae:2154.76923
[269]	validation_0-mae:2155.44017
[270]	validation_0-mae:2155.60291
[271]	validation_0-mae:2155.30311
[272]	validation_0-mae:2155.81179
[273]	validation_0-mae:2156.74037
[274]	validation_0-mae:2155.89519
[275]	validation_0-mae:2155.67514
[276]	validation_0-mae:2155.38458
[277]	validation_0-mae:2155.55567
[278]	validation_0-mae:2153.73481
[279]	validation_0-mae:2151.06480
[280]	validation_0-mae:2151.18816
[281]	validation_0-mae:2151.47666
[282]	validation_0-mae:2151.23656
[283]	validation_0-mae:2152.71456
[284]	validation_0-mae:2152.67496
[285]	validation_0-mae:2152.78938
[286]	validation_0-mae:2151.59427
[287]	validation_0-mae:2151.50009
[288]	validation_0-mae:2152.21661
[289]	validation_0-mae:2149.83606
[290]	validation_0-mae:2148.67306
[291]	validation_0-mae:2149.31508
[292]	validation_0-mae:2149.00509
[293]	validation_0-mae:2149.31581
[294]	validation_0-mae:2149.24703
[295]	validation_0-mae:2148.30538
[296]	validation_0-mae:2147.83610
[297]	validation_0-mae:2147.87371
[298]	validation_0-mae:2147.36312
[299]	validation_0-mae:2146.58556
[300]	validation_0-mae:2146.31206
[301]	validation_0-mae:2146.00196
[302]	validation_0-mae:2145.60335
[303]	validation_0-mae:2145.53120
[304]	validation_0-mae:2144.96809
[305]	validation_0-mae:2144.96341
[306]	validation_0-mae:2144.08183
[307]	validation_0-mae:2143.73564
[308]	validation_0-mae:2142.40408
[309]	validation_0-mae:2141.21669
[310]	validation_0-mae:2140.31141
[311]	validation_0-mae:2139.63251
[312]	validation_0-mae:2139.24701
[313]	validation_0-mae:2138.46258
[314]	validation_0-mae:2138.59151
[315]	validation_0-mae:2137.84747
[316]	validation_0-mae:2137.82163
[317]	validation_0-mae:2138.02037
[318]	validation_0-mae:2137.24932
[319]	validation_0-mae:2136.59156
[320]	validation_0-mae:2136.09853
[321]	validation_0-mae:2135.54810
[322]	validation_0-mae:2135.36431
[323]	validation_0-mae:2135.08813
[324]	validation_0-mae:2134.10209
[325]	validation_0-mae:2133.49007
[326]	validation_0-mae:2134.08861
[327]	validation_0-mae:2133.97317
[328]	validation_0-mae:2134.57760
[329]	validation_0-mae:2132.82080
[330]	validation_0-mae:2131.19323
[331]	validation_0-mae:2130.58884
[332]	validation_0-mae:2128.95884
[333]	validation_0-mae:2128.82442
[334]	validation_0-mae:2127.45481
[335]	validation_0-mae:2127.03001
[336]	validation_0-mae:2125.68295
[337]	validation_0-mae:2124.99474
[338]	validation_0-mae:2123.77247
[339]	validation_0-mae:2123.65557
[340]	validation_0-mae:2122.97540
[341]	validation_0-mae:2123.14465
[342]	validation_0-mae:2124.03482
[343]	validation_0-mae:2124.14242
[344]	validation_0-mae:2123.69450
[345]	validation_0-mae:2123.62996
[346]	validation_0-mae:2122.69508
[347]	validation_0-mae:2122.64528
[348]	validation_0-mae:2122.32881
[349]	validation_0-mae:2121.61137
[350]	validation_0-mae:2121.51051
[351]	validation_0-mae:2120.70887
[352]	validation_0-mae:2119.64965
[353]	validation_0-mae:2119.71257
[354]	validation_0-mae:2119.61553
[355]	validation_0-mae:2119.29278
[356]	validation_0-mae:2119.17381
[357]	validation_0-mae:2119.15104
[358]	validation_0-mae:2119.00916
[359]	validation_0-mae:2118.97034
[360]	validation_0-mae:2119.14311
[361]	validation_0-mae:2119.73950
[362]	validation_0-mae:2119.46942
[363]	validation_0-mae:2119.30315
[364]	validation_0-mae:2119.38264
[365]	validation_0-mae:2118.87243
[366]	validation_0-mae:2118.38191
[367]	validation_0-mae:2118.29069
[368]	validation_0-mae:2117.09531
[369]	validation_0-mae:2117.35690
[370]	validation_0-mae:2117.55201
[371]	validation_0-mae:2117.39728
[372]	validation_0-mae:2116.98264
[373]	validation_0-mae:2117.16743
[374]	validation_0-mae:2117.95782
[375]	validation_0-mae:2117.12239
[376]	validation_0-mae:2116.60725
[377]	validation_0-mae:2116.57429
[378]	validation_0-mae:2117.13200
[379]	validation_0-mae:2116.61069
[380]	validation_0-mae:2115.73917
[381]	validation_0-mae:2116.03704
[382]	validation_0-mae:2116.12876
[383]	validation_0-mae:2115.88143
[384]	validation_0-mae:2115.84114
[385]	validation_0-mae:2115.11163
[386]	validation_0-mae:2114.87428
[387]	validation_0-mae:2114.96147
[388]	validation_0-mae:2115.40126
[389]	validation_0-mae:2115.58788
[390]	validation_0-mae:2115.49074
[391]	validation_0-mae:2115.52217
[392]	validation_0-mae:2116.03183
[393]	validation_0-mae:2116.35306
[394]	validation_0-mae:2116.50901
[395]	validation_0-mae:2116.68682
[396]	validation_0-mae:2116.32459
[397]	validation_0-mae:2115.87555
[398]	validation_0-mae:2116.13410
[399]	validation_0-mae:2116.13103
[400]	validation_0-mae:2115.68529
[401]	validation_0-mae:2115.58668
[402]	validation_0-mae:2115.31966
[403]	validation_0-mae:2115.21590
[404]	validation_0-mae:2114.96341
[405]	validation_0-mae:2115.23078
[406]	validation_0-mae:2115.71210
[407]	validation_0-mae:2115.47646
[408]	validation_0-mae:2115.20249
[409]	validation_0-mae:2115.25751
[0]	validation_0-mae:12375.25638
[1]	validation_0-mae:11586.39244
[2]	validation_0-mae:10859.33349
[3]	validation_0-mae:10202.12159
[4]	validation_0-mae:9629.11155
[5]	validation_0-mae:9086.54215
[6]	validation_0-mae:8630.28067
[7]	validation_0-mae:8213.80948
[8]	validation_0-mae:7820.07600
[9]	validation_0-mae:7470.33558
[10]	validation_0-mae:7150.25859
[11]	validation_0-mae:6849.25595
[12]	validation_0-mae:6561.85219
[13]	validation_0-mae:6300.48987
[14]	validation_0-mae:6070.63796
[15]	validation_0-mae:5846.86394
[16]	validation_0-mae:5629.07486
[17]	validation_0-mae:5430.87120
[18]	validation_0-mae:5260.73331
[19]	validation_0-mae:5074.58768
[20]	validation_0-mae:4927.93561
[21]	validation_0-mae:4768.34240
[22]	validation_0-mae:4609.56518
[23]	validation_0-mae:4490.64948
[24]	validation_0-mae:4374.84826
[25]	validation_0-mae:4251.05350
[26]	validation_0-mae:4143.59431
[27]	validation_0-mae:4035.33481
[28]	validation_0-mae:3952.59646
[29]	validation_0-mae:3852.54650
[30]	validation_0-mae:3761.49048
[31]	validation_0-mae:3689.80326
[32]	validation_0-mae:3615.85244
[33]	validation_0-mae:3549.57803
[34]	validation_0-mae:3472.51829

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[35]	validation_0-mae:3419.69376
[36]	validation_0-mae:3375.77633
[37]	validation_0-mae:3320.63482
[38]	validation_0-mae:3272.21754
[39]	validation_0-mae:3229.67378
[40]	validation_0-mae:3197.60757
[41]	validation_0-mae:3151.84046
[42]	validation_0-mae:3118.34658
[43]	validation_0-mae:3084.35479
[44]	validation_0-mae:3046.81311
[45]	validation_0-mae:3014.89008
[46]	validation_0-mae:2977.60423
[47]	validation_0-mae:2941.57133
[48]	validation_0-mae:2904.57461
[49]	validation_0-mae:2884.43217
[50]	validation_0-mae:2867.23528
[51]	validation_0-mae:2839.97416
[52]	validation_0-mae:2821.17741
[53]	validation_0-mae:2795.61963
[54]	validation_0-mae:2775.16104
[55]	validation_0-mae:2762.27114
[56]	validation_0-mae:2744.88315
[57]	validation_0-mae:2723.73742
[58]	validation_0-mae:2709.82846
[59]	validation_0-mae:2694.61267
[60]	validation_0-mae:2682.96534
[61]	validation_0-mae:2664.82758
[62]	validation_0-mae:2653.67712
[63]	validation_0-mae:2641.05417
[64]	validation_0-mae:2630.62447
[65]	validation_0-mae:2619.64115
[66]	validation_0-mae:2608.96456
[67]	validation_0-mae:2586.36577
[68]	validation_0-mae:2576.71795
[69]	validation_0-mae:2567.37389
[70]	validation_0-mae:2553.12663
[71]	validation_0-mae:2549.52480
[72]	validation_0-mae:2541.97539
[73]	validation_0-mae:2525.76824
[74]	validation_0-mae:2510.56611
[75]	validation_0-mae:2500.50376
[76]	validation_0-mae:2494.27036
[77]	validation_0-mae:2486.00801
[78]	validation_0-mae:2475.32434
[79]	validation_0-mae:2470.17198
[80]	validation_0-mae:2463.15319
[81]	validation_0-mae:2454.89664
[82]	validation_0-mae:2450.01229
[83]	validation_0-mae:2438.40062
[84]	validation_0-mae:2430.57267
[85]	validation_0-mae:2424.72956
[86]	validation_0-mae:2416.09035
[87]	validation_0-mae:2412.12283
[88]	validation_0-mae:2410.84088
[89]	validation_0-mae:2408.29219
[90]	validation_0-mae:2405.60807
[91]	validation_0-mae:2400.78715
[92]	validation_0-mae:2398.31550
[93]	validation_0-mae:2392.65147
[94]	validation_0-mae:2391.92283
[95]	validation_0-mae:2384.61467
[96]	validation_0-mae:2376.31613
[97]	validation_0-mae:2374.84127
[98]	validation_0-mae:2366.28219
[99]	validation_0-mae:2366.95929
[100]	validation_0-mae:2364.81994
[101]	validation_0-mae:2362.26208
[102]	validation_0-mae:2358.10119
[103]	validation_0-mae:2357.81034
[104]	validation_0-mae:2354.59621
[105]	validation_0-mae:2355.12193
[106]	validation_0-mae:2354.26072
[107]	validation_0-mae:2346.77940
[108]	validation_0-mae:2345.70120
[109]	validation_0-mae:2341.35665
[110]	validation_0-mae:2341.35086
[111]	validation_0-mae:2341.07721
[112]	validation_0-mae:2340.06732
[113]	validation_0-mae:2337.38411
[114]	validation_0-mae:2333.71967
[115]	validation_0-mae:2331.92645
[116]	validation_0-mae:2327.03753
[117]	validation_0-mae:2327.01125
[118]	validation_0-mae:2325.96169
[119]	validation_0-mae:2322.85969
[120]	validation_0-mae:2315.89292
[121]	validation_0-mae:2317.20193
[122]	validation_0-mae:2315.86019
[123]	validation_0-mae:2315.55950
[124]	validation_0-mae:2316.22238
[0]	validation_0-mae:12348.85966
[1]	validation_0-mae:11561.55284
[2]	validation_0-mae:10832.65950
[3]	validation_0-mae:10142.96312
[4]	validation_0-mae:9549.32522
[5]	validation_0-mae:9030.72148
[6]	validation_0-mae:8564.12117
[7]	validation_0-mae:8127.22997
[8]	validation_0-mae:7745.14094
[9]	validation_0-mae:7395.63986
[10]	validation_0-mae:7045.47235
[11]	validation_0-mae:6735.75131
[12]	validation_0-mae:6451.02705
[13]	validation_0-mae:6190.92791
[14]	validation_0-mae:5950.19041
[15]	validation_0-mae:5728.82104
[16]	validation_0-mae:5507.21146
[17]	validation_0-mae:5305.25981
[18]	validation_0-mae:5113.17886
[19]	validation_0-mae:4952.05376
[20]	validation_0-mae:4793.26529
[21]	validation_0-mae:4641.36134
[22]	validation_0-mae:4498.71421
[23]	validation_0-mae:4368.03294
[24]	validation_0-mae:4251.89661
[25]	validation_0-mae:4140.52098
[26]	validation_0-mae:4034.38573
[27]	validation_0-mae:3959.05893

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[28]	validation_0-mae:3870.81753
[29]	validation_0-mae:3776.85289
[30]	validation_0-mae:3699.83524
[31]	validation_0-mae:3628.90906
[32]	validation_0-mae:3566.18796
[33]	validation_0-mae:3504.11457
[34]	validation_0-mae:3434.46701
[35]	validation_0-mae:3384.00250
[36]	validation_0-mae:3321.23483
[37]	validation_0-mae:3273.08125
[38]	validation_0-mae:3234.25143
[39]	validation_0-mae:3192.40104
[40]	validation_0-mae:3152.57632
[41]	validation_0-mae:3118.35368
[42]	validation_0-mae:3073.06320
[43]	validation_0-mae:3043.82134
[44]	validation_0-mae:3014.44085
[45]	validation_0-mae:2983.58942
[46]	validation_0-mae:2944.93125
[47]	validation_0-mae:2920.64681
[48]	validation_0-mae:2895.05933
[49]	validation_0-mae:2872.35047
[50]	validation_0-mae:2831.43096
[51]	validation_0-mae:2799.56257
[52]	validation_0-mae:2778.80380
[53]	validation_0-mae:2764.28525
[54]	validation_0-mae:2739.52266
[55]	validation_0-mae:2719.54628
[56]	validation_0-mae:2703.54951
[57]	validation_0-mae:2688.43561
[58]	validation_0-mae:2670.13142
[59]	validation_0-mae:2656.17920
[60]	validation_0-mae:2634.29207
[61]	validation_0-mae:2621.75822
[62]	validation_0-mae:2612.16736
[63]	validation_0-mae:2596.61101
[64]	validation_0-mae:2576.11417
[65]	validation_0-mae:2564.45149
[66]	validation_0-mae:2555.15593
[67]	validation_0-mae:2546.09597
[68]	validation_0-mae:2528.94256
[69]	validation_0-mae:2524.24716
[70]	validation_0-mae:2509.03557
[71]	validation_0-mae:2502.88010
[72]	validation_0-mae:2496.34592
[73]	validation_0-mae:2484.63678
[74]	validation_0-mae:2475.87739
[75]	validation_0-mae:2465.52572
[76]	validation_0-mae:2461.97069
[77]	validation_0-mae:2451.38729
[78]	validation_0-mae:2443.72969
[79]	validation_0-mae:2431.93823
[80]	validation_0-mae:2422.95826
[81]	validation_0-mae:2417.00891
[82]	validation_0-mae:2405.39447
[83]	validation_0-mae:2397.99841
[84]	validation_0-mae:2392.51173
[85]	validation_0-mae:2383.85775
[86]	validation_0-mae:2376.85374
[87]	validation_0-mae:2369.92339
[88]	validation_0-mae:2362.59713
[89]	validation_0-mae:2359.45502
[90]	validation_0-mae:2355.13512
[91]	validation_0-mae:2351.80459
[92]	validation_0-mae:2345.08024
[93]	validation_0-mae:2339.85828
[94]	validation_0-mae:2334.93329
[95]	validation_0-mae:2333.02853
[96]	validation_0-mae:2326.30803
[97]	validation_0-mae:2318.45977
[98]	validation_0-mae:2312.75282
[99]	validation_0-mae:2312.22087
[100]	validation_0-mae:2307.57071
[101]	validation_0-mae:2305.70851
[102]	validation_0-mae:2303.39747
[103]	validation_0-mae:2297.27210
[104]	validation_0-mae:2293.93841
[105]	validation_0-mae:2292.80943
[106]	validation_0-mae:2289.21487
[107]	validation_0-mae:2282.57413
[108]	validation_0-mae:2277.09544
[109]	validation_0-mae:2275.62450
[110]	validation_0-mae:2273.45413
[111]	validation_0-mae:2270.77812
[112]	validation_0-mae:2268.08103
[113]	validation_0-mae:2265.90791
[114]	validation_0-mae:2265.20667
[115]	validation_0-mae:2261.29695
[116]	validation_0-mae:2255.03792
[117]	validation_0-mae:2254.21489
[118]	validation_0-mae:2254.78660
[119]	validation_0-mae:2252.56243
[120]	validation_0-mae:2249.27886
[121]	validation_0-mae:2244.24790
[122]	validation_0-mae:2243.33785
[123]	validation_0-mae:2239.92466
[124]	validation_0-mae:2236.72387
[125]	validation_0-mae:2236.56909
[126]	validation_0-mae:2232.61079
[127]	validation_0-mae:2230.33609
[128]	validation_0-mae:2227.21904
[129]	validation_0-mae:2226.57996
[130]	validation_0-mae:2227.19627
[131]	validation_0-mae:2226.17765
[132]	validation_0-mae:2223.13066
[133]	validation_0-mae:2221.82740
[134]	validation_0-mae:2222.22637
[135]	validation_0-mae:2222.08439
[136]	validation_0-mae:2218.38244
[137]	validation_0-mae:2217.25466
[138]	validation_0-mae:2216.56349
[139]	validation_0-mae:2213.50559
[140]	validation_0-mae:2212.36757
[141]	validation_0-mae:2213.62823
[142]	validation_0-mae:2214.12253
[143]	validation_0-mae:2213.14734
[144]	validation_0-mae:2211.84609
[145]	validation_0-mae:2207.99612
[146]	validation_0-mae:2207.05198
[147]	validation_0-mae:2204.34501
[148]	validation_0-mae:2204.12076
[149]	validation_0-mae:2205.45827
[150]	validation_0-mae:2205.72010
[151]	validation_0-mae:2204.35035
[152]	validation_0-mae:2202.24369
[153]	validation_0-mae:2200.32744
[154]	validation_0-mae:2197.74595
[155]	validation_0-mae:2192.49042
[156]	validation_0-mae:2192.27214
[157]	validation_0-mae:2190.07853
[158]	validation_0-mae:2189.60423
[159]	validation_0-mae:2188.59945
[160]	validation_0-mae:2188.43325
[161]	validation_0-mae:2187.36473
[162]	validation_0-mae:2186.98243
[163]	validation_0-mae:2185.83678
[164]	validation_0-mae:2185.41692
[165]	validation_0-mae:2185.37416
[166]	validation_0-mae:2185.39479
[167]	validation_0-mae:2185.51504
[168]	validation_0-mae:2186.09559
[169]	validation_0-mae:2184.41881
[170]	validation_0-mae:2182.07367
[171]	validation_0-mae:2180.63468
[172]	validation_0-mae:2180.28429
[173]	validation_0-mae:2179.46518
[174]	validation_0-mae:2180.71641
[175]	validation_0-mae:2179.84450
[176]	validation_0-mae:2179.01624
[177]	validation_0-mae:2177.53383
[178]	validation_0-mae:2177.83722
[179]	validation_0-mae:2176.13785
[180]	validation_0-mae:2176.02301
[181]	validation_0-mae:2175.13014
[182]	validation_0-mae:2174.52128
[183]	validation_0-mae:2173.43295
[184]	validation_0-mae:2173.53163
[185]	validation_0-mae:2172.96812
[186]	validation_0-mae:2172.68013
[187]	validation_0-mae:2173.02185
[188]	validation_0-mae:2173.66541
[189]	validation_0-mae:2172.45365
[190]	validation_0-mae:2173.06442
[191]	validation_0-mae:2173.64473
[192]	validation_0-mae:2172.04813
[193]	validation_0-mae:2172.58392
[194]	validation_0-mae:2172.59651
[195]	validation_0-mae:2173.16224
[196]	validation_0-mae:2174.19868
[197]	validation_0-mae:2173.60255
[198]	validation_0-mae:2174.18852
[199]	validation_0-mae:2172.60919
[200]	validation_0-mae:2172.70942
[201]	validation_0-mae:2173.21142
[202]	validation_0-mae:2173.60409
[203]	validation_0-mae:2174.22083
[204]	validation_0-mae:2172.61538
[205]	validation_0-mae:2171.50396
[206]	validation_0-mae:2170.49392
[207]	validation_0-mae:2169.49054
[208]	validation_0-mae:2169.28648
[209]	validation_0-mae:2168.13009
[210]	validation_0-mae:2166.88686
[211]	validation_0-mae:2166.66726
[212]	validation_0-mae:2166.69147
[213]	validation_0-mae:2165.77330
[214]	validation_0-mae:2164.95749
[215]	validation_0-mae:2163.65476
[216]	validation_0-mae:2162.70634
[217]	validation_0-mae:2163.05966
[218]	validation_0-mae:2162.73396
[219]	validation_0-mae:2161.99069
[220]	validation_0-mae:2161.21092
[221]	validation_0-mae:2161.28788
[222]	validation_0-mae:2161.01906
[223]	validation_0-mae:2160.06825
[224]	validation_0-mae:2160.17450
[225]	validation_0-mae:2159.56121
[226]	validation_0-mae:2158.27515
[227]	validation_0-mae:2158.28791
[228]	validation_0-mae:2158.24631
[229]	validation_0-mae:2159.16534
[230]	validation_0-mae:2158.79712
[231]	validation_0-mae:2158.93866
[232]	validation_0-mae:2158.56996
[233]	validation_0-mae:2158.90194
[234]	validation_0-mae:2159.10662
[235]	validation_0-mae:2157.92294
[236]	validation_0-mae:2155.86013
[237]	validation_0-mae:2155.45001
[238]	validation_0-mae:2155.07869
[239]	validation_0-mae:2153.29180
[240]	validation_0-mae:2153.40455
[241]	validation_0-mae:2153.77986
[242]	validation_0-mae:2153.82274
[243]	validation_0-mae:2153.00259
[244]	validation_0-mae:2153.40766
[245]	validation_0-mae:2154.01058
[246]	validation_0-mae:2153.42102
[247]	validation_0-mae:2152.47110
[248]	validation_0-mae:2152.02351
[249]	validation_0-mae:2151.41407
[250]	validation_0-mae:2150.91545
[251]	validation_0-mae:2150.61604
[252]	validation_0-mae:2150.01949
[253]	validation_0-mae:2149.14651
[254]	validation_0-mae:2150.06363
[255]	validation_0-mae:2150.21528
[256]	validation_0-mae:2149.56714
[257]	validation_0-mae:2149.90156
[258]	validation_0-mae:2150.18761
[259]	validation_0-mae:2149.85905
[260]	validation_0-mae:2149.26266
[261]	validation_0-mae:2148.78763
[262]	validation_0-mae:2148.61495
[263]	validation_0-mae:2148.95193
[264]	validation_0-mae:2148.05112
[265]	validation_0-mae:2148.53861
[266]	validation_0-mae:2147.69037
[267]	validation_0-mae:2146.42283
[268]	validation_0-mae:2145.87268
[269]	validation_0-mae:2145.19225
[270]	validation_0-mae:2145.10451
[271]	validation_0-mae:2142.60743
[272]	validation_0-mae:2142.19640
[273]	validation_0-mae:2141.79464
[274]	validation_0-mae:2141.18133
[275]	validation_0-mae:2140.90709
[276]	validation_0-mae:2140.90439
[277]	validation_0-mae:2140.29594
[278]	validation_0-mae:2139.73490
[279]	validation_0-mae:2139.79037
[280]	validation_0-mae:2140.08963
[281]	validation_0-mae:2139.81018
[282]	validation_0-mae:2139.60606
[283]	validation_0-mae:2139.56690
[284]	validation_0-mae:2140.02093
[285]	validation_0-mae:2138.43905
[286]	validation_0-mae:2139.13507
[287]	validation_0-mae:2138.83023
[288]	validation_0-mae:2138.94735
[289]	validation_0-mae:2138.43456
[290]	validation_0-mae:2138.68146
[291]	validation_0-mae:2139.01331
[292]	validation_0-mae:2139.52142
[293]	validation_0-mae:2139.35130
[294]	validation_0-mae:2139.36919
[295]	validation_0-mae:2139.23805
[296]	validation_0-mae:2138.72548
[297]	validation_0-mae:2138.87639
[298]	validation_0-mae:2139.23873
[299]	validation_0-mae:2139.60614
[300]	validation_0-mae:2140.28145
[301]	validation_0-mae:2139.77907
[302]	validation_0-mae:2140.61615
[303]	validation_0-mae:2140.77996
[304]	validation_0-mae:2140.59792
[305]	validation_0-mae:2140.75220
[306]	validation_0-mae:2140.41245
[307]	validation_0-mae:2139.90008
[308]	validation_0-mae:2138.83523
[309]	validation_0-mae:2138.65339
[310]	validation_0-mae:2138.15825
[311]	validation_0-mae:2138.17465
[312]	validation_0-mae:2138.06236
[313]	validation_0-mae:2136.97934
[314]	validation_0-mae:2136.96555
[315]	validation_0-mae:2136.15802
[316]	validation_0-mae:2136.25543
[317]	validation_0-mae:2136.28909
[318]	validation_0-mae:2136.57202
[319]	validation_0-mae:2136.31965
[320]	validation_0-mae:2136.24356
[321]	validation_0-mae:2135.29662
[322]	validation_0-mae:2135.27380
[323]	validation_0-mae:2134.57798
[324]	validation_0-mae:2134.44987
[325]	validation_0-mae:2135.16219
[326]	validation_0-mae:2134.89220
[327]	validation_0-mae:2134.66687
[328]	validation_0-mae:2134.49953
[329]	validation_0-mae:2134.37532
[330]	validation_0-mae:2134.24125
[331]	validation_0-mae:2134.14050
[332]	validation_0-mae:2133.42220
[333]	validation_0-mae:2133.23948
[334]	validation_0-mae:2133.21499
[335]	validation_0-mae:2133.30724
[336]	validation_0-mae:2133.76467
[337]	validation_0-mae:2133.85449
[338]	validation_0-mae:2134.11286
[339]	validation_0-mae:2133.93880
[340]	validation_0-mae:2134.11502
[341]	validation_0-mae:2133.84557
[342]	validation_0-mae:2133.19500
[343]	validation_0-mae:2133.37734
[344]	validation_0-mae:2133.59218
[345]	validation_0-mae:2133.65989
[346]	validation_0-mae:2133.63906
[347]	validation_0-mae:2133.05418
[348]	validation_0-mae:2132.65051
[349]	validation_0-mae:2132.64473
[350]	validation_0-mae:2132.70685
[351]	validation_0-mae:2131.92953
[352]	validation_0-mae:2132.24600
[353]	validation_0-mae:2132.00980
[354]	validation_0-mae:2132.31066
[355]	validation_0-mae:2132.14674
[356]	validation_0-mae:2132.54979
[357]	validation_0-mae:2132.38482
[358]	validation_0-mae:2132.34614
[359]	validation_0-mae:2132.67969
[360]	validation_0-mae:2132.24174
[361]	validation_0-mae:2131.98582
[362]	validation_0-mae:2132.24365
[363]	validation_0-mae:2131.97598
[364]	validation_0-mae:2132.17265
[365]	validation_0-mae:2132.38320
[366]	validation_0-mae:2132.22023
[367]	validation_0-mae:2131.04350
[368]	validation_0-mae:2131.05400
[369]	validation_0-mae:2129.88109
[370]	validation_0-mae:2130.41670
[371]	validation_0-mae:2130.23744
[372]	validation_0-mae:2130.40776
[373]	validation_0-mae:2130.31870
[374]	validation_0-mae:2130.87237
[375]	validation_0-mae:2131.41202
[376]	validation_0-mae:2129.78193
[377]	validation_0-mae:2130.17623
[378]	validation_0-mae:2129.96631
[379]	validation_0-mae:2128.88390
[380]	validation_0-mae:2127.84452
[381]	validation_0-mae:2128.00464
[382]	validation_0-mae:2126.10321
[383]	validation_0-mae:2126.12916
[384]	validation_0-mae:2125.37212
[385]	validation_0-mae:2123.72539
[386]	validation_0-mae:2122.30761
[387]	validation_0-mae:2121.38038
[388]	validation_0-mae:2121.53485
[389]	validation_0-mae:2120.59951
[390]	validation_0-mae:2120.22791
[391]	validation_0-mae:2119.86269
[392]	validation_0-mae:2119.71440
[393]	validation_0-mae:2118.95538
[394]	validation_0-mae:2119.18519
[395]	validation_0-mae:2119.14159
[396]	validation_0-mae:2119.21596
[397]	validation_0-mae:2119.09907
[398]	validation_0-mae:2119.17649
[399]	validation_0-mae:2118.68027
[400]	validation_0-mae:2118.35273
[401]	validation_0-mae:2118.57850
[402]	validation_0-mae:2118.96949
[403]	validation_0-mae:2118.61973
[404]	validation_0-mae:2118.52435
[405]	validation_0-mae:2118.56572
[406]	validation_0-mae:2118.16055
[407]	validation_0-mae:2118.32885
[408]	validation_0-mae:2118.32208
[409]	validation_0-mae:2118.49166
[410]	validation_0-mae:2118.60742
[411]	validation_0-mae:2118.71342
[412]	validation_0-mae:2118.88224
[413]	validation_0-mae:2118.87621
[414]	validation_0-mae:2118.74040
[415]	validation_0-mae:2118.85974
[416]	validation_0-mae:2119.12990
[417]	validation_0-mae:2119.07189
[418]	validation_0-mae:2119.17214
[419]	validation_0-mae:2119.11720
[420]	validation_0-mae:2118.40264
[421]	validation_0-mae:2117.79991
[422]	validation_0-mae:2117.86880
[423]	validation_0-mae:2117.88267
[424]	validation_0-mae:2117.79527
[425]	validation_0-mae:2117.63685
[426]	validation_0-mae:2117.27371
[427]	validation_0-mae:2117.42046
[428]	validation_0-mae:2117.21098
[429]	validation_0-mae:2117.51524
[430]	validation_0-mae:2117.47323
[431]	validation_0-mae:2117.26228
[432]	validation_0-mae:2117.23952
[433]	validation_0-mae:2116.27551
[434]	validation_0-mae:2115.85682
[435]	validation_0-mae:2114.99340
[436]	validation_0-mae:2114.65157
[437]	validation_0-mae:2114.54877
[438]	validation_0-mae:2114.73443
[439]	validation_0-mae:2114.59830
[440]	validation_0-mae:2114.53586
[441]	validation_0-mae:2114.03322
[442]	validation_0-mae:2114.28105
[443]	validation_0-mae:2114.08166
[444]	validation_0-mae:2113.66360
[445]	validation_0-mae:2114.04839
[446]	validation_0-mae:2114.14009
[447]	validation_0-mae:2114.25727
[448]	validation_0-mae:2113.96876
[449]	validation_0-mae:2113.85524
[450]	validation_0-mae:2113.66118
[451]	validation_0-mae:2113.32992
[452]	validation_0-mae:2113.75365
[453]	validation_0-mae:2113.11396
[454]	validation_0-mae:2113.28696
[455]	validation_0-mae:2113.39143
[456]	validation_0-mae:2113.36923
[457]	validation_0-mae:2113.45161
[458]	validation_0-mae:2113.34201
[459]	validation_0-mae:2112.96929
[460]	validation_0-mae:2112.90773
[461]	validation_0-mae:2112.91798
[462]	validation_0-mae:2112.50335
[463]	validation_0-mae:2112.79878
[464]	validation_0-mae:2112.88558
[465]	validation_0-mae:2112.74739
[466]	validation_0-mae:2113.02097
[467]	validation_0-mae:2113.15520
[468]	validation_0-mae:2113.19647
[469]	validation_0-mae:2113.27080
[470]	validation_0-mae:2113.30771
[471]	validation_0-mae:2113.85179
[472]	validation_0-mae:2114.05324
[473]	validation_0-mae:2114.18449
[474]	validation_0-mae:2114.33638
[475]	validation_0-mae:2114.43567
[476]	validation_0-mae:2114.67988
[477]	validation_0-mae:2114.89779
[478]	validation_0-mae:2114.69325
[479]	validation_0-mae:2114.85861
[480]	validation_0-mae:2114.87898
[481]	validation_0-mae:2114.82070
[482]	validation_0-mae:2115.03193
[483]	validation_0-mae:2115.16904
[484]	validation_0-mae:2115.20369
[485]	validation_0-mae:2114.93504
[486]	validation_0-mae:2114.09016
[487]	validation_0-mae:2114.15898
[488]	validation_0-mae:2114.70170
[489]	validation_0-mae:2114.80222
[490]	validation_0-mae:2114.64640
[491]	validation_0-mae:2114.68414
[492]	validation_0-mae:2114.87213
[493]	validation_0-mae:2114.42700
[494]	validation_0-mae:2114.32477
[495]	validation_0-mae:2114.34528
[496]	validation_0-mae:2114.23966
[497]	validation_0-mae:2114.24638
[498]	validation_0-mae:2114.00265
[499]	validation_0-mae:2113.91431
[500]	validation_0-mae:2113.52382
[501]	validation_0-mae:2113.51106
[502]	validation_0-mae:2113.38491
[503]	validation_0-mae:2113.42924
[504]	validation_0-mae:2112.73219
[505]	validation_0-mae:2112.57732
[506]	validation_0-mae:2112.54913
[507]	validation_0-mae:2112.49797
[508]	validation_0-mae:2112.40592
[509]	validation_0-mae:2111.96267
[510]	validation_0-mae:2111.52247
[511]	validation_0-mae:2111.65312
[512]	validation_0-mae:2111.41745
[513]	validation_0-mae:2111.73815
[514]	validation_0-mae:2112.10785
[515]	validation_0-mae:2111.82193
[0]	validation_0-mae:12878.28415
[1]	validation_0-mae:12482.10802
[2]	validation_0-mae:12120.14935
[3]	validation_0-mae:11774.42360
[4]	validation_0-mae:11442.51027
[5]	validation_0-mae:11122.69872
[6]	validation_0-mae:10816.30634
[7]	validation_0-mae:10526.37406
[8]	validation_0-mae:10247.10185
[9]	validation_0-mae:9994.97043
[10]	validation_0-mae:9738.81146

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[0]	validation_0-mae:12475.11544
[1]	validation_0-mae:11770.96146
[2]	validation_0-mae:11118.61782
[3]	validation_0-mae:10515.19735
[4]	validation_0-mae:9986.55375
[5]	validation_0-mae:9498.81677
[6]	validation_0-mae:9056.60911
[7]	validation_0-mae:8650.20139
[8]	validation_0-mae:8310.69727
[9]	validation_0-mae:7972.82895
[10]	validation_0-mae:7660.62012
[0]	validation_0-mae:12716.48437
[1]	validation_0-mae:12212.31157
[2]	validation_0-mae:11784.50928
[3]	validation_0-mae:11365.61371
[4]	validation_0-mae:11005.98121
[5]	validation_0-mae:10714.43654
[6]	validation_0-mae:10446.08784
[7]	validation_0-mae:10161.62390
[8]	validation_0-mae:9909.80970
[9]	validation_0-mae:9671.15686

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[0]	validation_0-mae:12404.54064
[1]	validation_0-mae:11652.82855
[2]	validation_0-mae:10951.24827
[3]	validation_0-mae:10306.00975
[4]	validation_0-mae:9751.49358
[5]	validation_0-mae:9252.97545
[6]	validation_0-mae:8800.47874
[7]	validation_0-mae:8380.97025
[8]	validation_0-mae:8004.63972
[9]	validation_0-mae:7677.45033
[10]	validation_0-mae:7359.68379
[11]	validation_0-mae:7045.58370
[12]	validation_0-mae:6771.42343
[13]	validation_0-mae:6523.03919
[14]	validation_0-mae:6271.07398
[15]	validation_0-mae:6031.08975
[16]	validation_0-mae:5780.36833
[17]	validation_0-mae:5596.80690
[18]	validation_0-mae:5419.85768
[19]	validation_0-mae:5245.50438
[20]	validation_0-mae:5076.28564
[21]	validation_0-mae:4916.51395
[22]	validation_0-mae:4760.98309
[23]	validation_0-mae:4628.90999
[24]	validation_0-mae:4499.40984
[25]	validation_0-mae:4397.37998
[26]	validation_0-mae:4285.32934
[27]	validation_0-mae:4189.75957
[28]	validation_0-mae:4091.50487
[29]	validation_0-mae:3988.00207
[30]	validation_0-mae:3908.25367
[31]	validation_0-mae:3827.27319
[32]	validation_0-mae:3745.76757
[33]	validation_0-mae:3683.28196
[34]	validation_0-mae:3611.21087
[35]	validation_0-mae:3546.42420
[36]	validation_0-mae:3489.28173
[37]	validation_0-mae:3432.43059
[38]	validation_0-mae:3377.81967
[39]	validation_0-mae:3327.94602
[40]	validation_0-mae:3279.97519
[41]	validation_0-mae:3241.85603
[42]	validation_0-mae:3199.82491
[43]	validation_0-mae:3160.44852
[44]	validation_0-mae:3123.80980
[45]	validation_0-mae:3074.24382
[46]	validation_0-mae:3051.24076
[47]	validation_0-mae:3022.32444
[48]	validation_0-mae:2984.30716
[49]	validation_0-mae:2956.48761
[50]	validation_0-mae:2932.43556
[51]	validation_0-mae:2894.70820
[52]	validation_0-mae:2870.84629
[53]	validation_0-mae:2853.06912
[54]	validation_0-mae:2828.23138
[55]	validation_0-mae:2807.65689
[56]	validation_0-mae:2787.22750
[57]	validation_0-mae:2768.07482
[58]	validation_0-mae:2755.87161
[59]	validation_0-mae:2741.10412
[60]	validation_0-mae:2728.71113
[61]	validation_0-mae:2712.31540
[62]	validation_0-mae:2697.28185
[63]	validation_0-mae:2685.87043
[64]	validation_0-mae:2673.76008
[65]	validation_0-mae:2657.00579
[66]	validation_0-mae:2642.07943
[67]	validation_0-mae:2632.93294
[68]	validation_0-mae:2619.75096
[69]	validation_0-mae:2602.84268
[70]	validation_0-mae:2591.16507
[71]	validation_0-mae:2580.98885
[72]	validation_0-mae:2561.82031
[73]	validation_0-mae:2547.93764
[74]	validation_0-mae:2540.58332
[75]	validation_0-mae:2528.97826
[76]	validation_0-mae:2525.28497
[77]	validation_0-mae:2513.42104
[78]	validation_0-mae:2504.34275
[79]	validation_0-mae:2495.61142
[80]	validation_0-mae:2490.46604
[81]	validation_0-mae:2483.31772
[82]	validation_0-mae:2462.14344
[83]	validation_0-mae:2456.31655
[84]	validation_0-mae:2449.70699
[85]	validation_0-mae:2441.70437
[86]	validation_0-mae:2434.46874
[87]	validation_0-mae:2427.53547
[88]	validation_0-mae:2417.18067
[89]	validation_0-mae:2412.56702
[90]	validation_0-mae:2406.26395
[91]	validation_0-mae:2400.43491
[92]	validation_0-mae:2393.80209
[93]	validation_0-mae:2383.25030
[94]	validation_0-mae:2374.58244
[95]	validation_0-mae:2370.76765
[96]	validation_0-mae:2371.79979
[97]	validation_0-mae:2366.25477
[98]	validation_0-mae:2361.05371
[99]	validation_0-mae:2354.55162
[100]	validation_0-mae:2345.84337
[101]	validation_0-mae:2340.86379
[102]	validation_0-mae:2334.25477
[103]	validation_0-mae:2334.04516
[104]	validation_0-mae:2328.22235
[105]	validation_0-mae:2324.77290
[106]	validation_0-mae:2323.82096
[107]	validation_0-mae:2320.75478
[108]	validation_0-mae:2318.75888
[109]	validation_0-mae:2314.68921
[110]	validation_0-mae:2312.83676
[111]	validation_0-mae:2309.86379
[112]	validation_0-mae:2306.14941
[113]	validation_0-mae:2305.48627
[114]	validation_0-mae:2302.30425
[115]	validation_0-mae:2301.27027
[116]	validation_0-mae:2301.66876
[117]	validation_0-mae:2302.83688
[118]	validation_0-mae:2299.02535
[119]	validation_0-mae:2295.73105
[120]	validation_0-mae:2289.25098
[121]	validation_0-mae:2288.34789
[122]	validation_0-mae:2283.95908
[123]	validation_0-mae:2283.08660
[124]	validation_0-mae:2280.89021
[125]	validation_0-mae:2277.46195
[126]	validation_0-mae:2273.54954
[127]	validation_0-mae:2271.90391
[128]	validation_0-mae:2269.70820
[129]	validation_0-mae:2265.66633
[130]	validation_0-mae:2265.32015
[131]	validation_0-mae:2264.16344
[132]	validation_0-mae:2261.86190
[133]	validation_0-mae:2258.17121
[134]	validation_0-mae:2254.90171
[135]	validation_0-mae:2253.42500
[136]	validation_0-mae:2251.24949
[137]	validation_0-mae:2250.81109
[138]	validation_0-mae:2249.70831
[139]	validation_0-mae:2248.84978
[140]	validation_0-mae:2245.19928
[141]	validation_0-mae:2243.12916
[142]	validation_0-mae:2241.25615
[143]	validation_0-mae:2242.24847
[144]	validation_0-mae:2240.69609
[145]	validation_0-mae:2239.40914
[146]	validation_0-mae:2239.51508
[147]	validation_0-mae:2239.73499
[148]	validation_0-mae:2238.56040
[149]	validation_0-mae:2238.08788
[150]	validation_0-mae:2234.71444
[151]	validation_0-mae:2234.33395
[152]	validation_0-mae:2235.21612
[153]	validation_0-mae:2234.14098
[154]	validation_0-mae:2232.85780
[155]	validation_0-mae:2231.89509
[156]	validation_0-mae:2231.28699
[157]	validation_0-mae:2231.92623
[158]	validation_0-mae:2230.47371
[159]	validation_0-mae:2228.65269
[160]	validation_0-mae:2228.18234
[161]	validation_0-mae:2225.27209
[162]	validation_0-mae:2223.55733
[163]	validation_0-mae:2223.70033
[164]	validation_0-mae:2222.96997
[165]	validation_0-mae:2221.09670
[166]	validation_0-mae:2222.08444
[167]	validation_0-mae:2220.95215
[168]	validation_0-mae:2217.88270
[169]	validation_0-mae:2217.84457
[170]	validation_0-mae:2217.50373
[171]	validation_0-mae:2216.00760
[172]	validation_0-mae:2213.92083
[173]	validation_0-mae:2212.91395
[174]	validation_0-mae:2211.01615
[175]	validation_0-mae:2210.75175
[176]	validation_0-mae:2210.41541
[177]	validation_0-mae:2209.43674
[178]	validation_0-mae:2209.29155
[179]	validation_0-mae:2209.37624
[180]	validation_0-mae:2208.20140
[181]	validation_0-mae:2206.50613
[182]	validation_0-mae:2206.09903
[183]	validation_0-mae:2202.13654
[184]	validation_0-mae:2201.08054
[185]	validation_0-mae:2199.69402
[186]	validation_0-mae:2198.58463
[187]	validation_0-mae:2197.68750
[188]	validation_0-mae:2195.59578
[189]	validation_0-mae:2196.01171
[190]	validation_0-mae:2195.91198
[191]	validation_0-mae:2193.72677
[192]	validation_0-mae:2190.80598
[193]	validation_0-mae:2190.33178
[194]	validation_0-mae:2190.41230
[195]	validation_0-mae:2190.17504
[196]	validation_0-mae:2188.96143
[197]	validation_0-mae:2188.80874
[198]	validation_0-mae:2188.04767
[199]	validation_0-mae:2186.78681
[200]	validation_0-mae:2183.27206
[201]	validation_0-mae:2182.70699
[202]	validation_0-mae:2182.00307
[203]	validation_0-mae:2181.85430
[204]	validation_0-mae:2182.23738
[205]	validation_0-mae:2182.09564
[206]	validation_0-mae:2181.36866
[207]	validation_0-mae:2181.09395
[208]	validation_0-mae:2180.67274
[209]	validation_0-mae:2177.88272
[210]	validation_0-mae:2177.91399
[211]	validation_0-mae:2178.49312
[212]	validation_0-mae:2178.28144
[213]	validation_0-mae:2178.49411
[214]	validation_0-mae:2178.88941
[215]	validation_0-mae:2177.81780
[216]	validation_0-mae:2176.33857
[217]	validation_0-mae:2176.01482
[218]	validation_0-mae:2175.26979
[219]	validation_0-mae:2174.87793
[220]	validation_0-mae:2174.17034
[221]	validation_0-mae:2172.03130
[222]	validation_0-mae:2171.73825
[223]	validation_0-mae:2171.22988
[224]	validation_0-mae:2169.85167
[225]	validation_0-mae:2170.18011
[226]	validation_0-mae:2170.91209
[227]	validation_0-mae:2169.71228
[228]	validation_0-mae:2168.68962
[229]	validation_0-mae:2170.16826
[230]	validation_0-mae:2169.90974
[231]	validation_0-mae:2171.04590
[232]	validation_0-mae:2170.55523
[233]	validation_0-mae:2170.74357
[234]	validation_0-mae:2170.27187
[235]	validation_0-mae:2171.33451
[236]	validation_0-mae:2170.30818
[237]	validation_0-mae:2168.76337
[238]	validation_0-mae:2169.59611
[239]	validation_0-mae:2169.37550
[240]	validation_0-mae:2169.87623
[241]	validation_0-mae:2169.60056
[242]	validation_0-mae:2169.02161
[243]	validation_0-mae:2167.67334
[244]	validation_0-mae:2168.01771
[245]	validation_0-mae:2168.49584
[246]	validation_0-mae:2167.21983
[247]	validation_0-mae:2164.95502
[248]	validation_0-mae:2164.00875
[249]	validation_0-mae:2162.82173
[250]	validation_0-mae:2161.69394
[251]	validation_0-mae:2161.43722
[252]	validation_0-mae:2160.76931
[253]	validation_0-mae:2160.43177
[254]	validation_0-mae:2159.21483
[255]	validation_0-mae:2158.87371
[256]	validation_0-mae:2157.69347
[257]	validation_0-mae:2158.26252
[258]	validation_0-mae:2155.05749
[259]	validation_0-mae:2154.76584
[260]	validation_0-mae:2155.70115
[261]	validation_0-mae:2154.74472
[262]	validation_0-mae:2155.43640
[263]	validation_0-mae:2154.92464
[264]	validation_0-mae:2155.34876
[265]	validation_0-mae:2155.01508
[266]	validation_0-mae:2155.28892
[267]	validation_0-mae:2154.45957
[268]	validation_0-mae:2154.31944
[269]	validation_0-mae:2154.17738
[270]	validation_0-mae:2154.00791
[271]	validation_0-mae:2152.00129
[272]	validation_0-mae:2152.36216
[273]	validation_0-mae:2151.46980
[274]	validation_0-mae:2151.50567
[275]	validation_0-mae:2149.64442
[276]	validation_0-mae:2149.25275
[277]	validation_0-mae:2148.89114
[278]	validation_0-mae:2148.87040
[279]	validation_0-mae:2148.90722
[280]	validation_0-mae:2146.82850
[281]	validation_0-mae:2147.44276
[282]	validation_0-mae:2148.13037
[283]	validation_0-mae:2148.43305
[284]	validation_0-mae:2148.55923
[285]	validation_0-mae:2149.03295
[286]	validation_0-mae:2148.70369
[287]	validation_0-mae:2148.44702
[288]	validation_0-mae:2148.87421
[289]	validation_0-mae:2148.21321
[290]	validation_0-mae:2148.37921
[291]	validation_0-mae:2147.88828
[292]	validation_0-mae:2147.99563
[293]	validation_0-mae:2148.02436
[294]	validation_0-mae:2148.00581
[295]	validation_0-mae:2148.54766
[296]	validation_0-mae:2148.38982
[297]	validation_0-mae:2148.22801
[298]	validation_0-mae:2148.43415
[299]	validation_0-mae:2146.96748
[300]	validation_0-mae:2145.74622
[301]	validation_0-mae:2145.60760
[302]	validation_0-mae:2144.76956
[303]	validation_0-mae:2144.54221
[304]	validation_0-mae:2143.16724
[305]	validation_0-mae:2143.28258
[306]	validation_0-mae:2142.54095
[307]	validation_0-mae:2142.42459
[308]	validation_0-mae:2141.41634
[309]	validation_0-mae:2140.56247
[310]	validation_0-mae:2139.84459
[311]	validation_0-mae:2138.78314
[312]	validation_0-mae:2138.61489
[313]	validation_0-mae:2138.00262
[314]	validation_0-mae:2138.07303
[315]	validation_0-mae:2138.31560
[316]	validation_0-mae:2137.07805
[317]	validation_0-mae:2135.69600
[318]	validation_0-mae:2135.59139
[319]	validation_0-mae:2135.79278
[320]	validation_0-mae:2135.87727
[321]	validation_0-mae:2136.07254
[322]	validation_0-mae:2135.66164
[323]	validation_0-mae:2134.49725
[324]	validation_0-mae:2134.89923
[325]	validation_0-mae:2134.58969
[326]	validation_0-mae:2134.49171
[327]	validation_0-mae:2134.14530
[328]	validation_0-mae:2134.00310
[329]	validation_0-mae:2133.49360
[330]	validation_0-mae:2132.32144
[331]	validation_0-mae:2132.13537
[332]	validation_0-mae:2132.50244
[333]	validation_0-mae:2132.26173
[334]	validation_0-mae:2132.33126
[335]	validation_0-mae:2132.48690
[336]	validation_0-mae:2132.37138
[337]	validation_0-mae:2132.92379
[338]	validation_0-mae:2132.38601
[339]	validation_0-mae:2130.97718
[340]	validation_0-mae:2131.83440
[341]	validation_0-mae:2130.78206
[342]	validation_0-mae:2130.16757
[343]	validation_0-mae:2129.35411
[344]	validation_0-mae:2128.65511
[345]	validation_0-mae:2127.38545
[346]	validation_0-mae:2127.16057
[347]	validation_0-mae:2127.48016
[348]	validation_0-mae:2127.38669
[349]	validation_0-mae:2127.47561
[350]	validation_0-mae:2127.79474
[351]	validation_0-mae:2127.54854
[352]	validation_0-mae:2127.58184
[353]	validation_0-mae:2126.62456
[354]	validation_0-mae:2127.22485
[355]	validation_0-mae:2126.82115
[356]	validation_0-mae:2126.64856
[357]	validation_0-mae:2126.76854
[358]	validation_0-mae:2126.89127
[359]	validation_0-mae:2126.42110
[360]	validation_0-mae:2127.01811
[361]	validation_0-mae:2127.40288
[362]	validation_0-mae:2127.05204
[363]	validation_0-mae:2126.86255
[364]	validation_0-mae:2126.95552
[365]	validation_0-mae:2126.69403
[366]	validation_0-mae:2126.80577
[367]	validation_0-mae:2127.37497
[368]	validation_0-mae:2127.11532
[369]	validation_0-mae:2127.32451
[370]	validation_0-mae:2127.21707
[371]	validation_0-mae:2127.61926
[372]	validation_0-mae:2127.90912
[373]	validation_0-mae:2127.92350
[374]	validation_0-mae:2127.23850
[375]	validation_0-mae:2127.44932
[376]	validation_0-mae:2127.18417
[377]	validation_0-mae:2127.37077
[378]	validation_0-mae:2127.74100
[379]	validation_0-mae:2127.50793
[380]	validation_0-mae:2126.94465
[381]	validation_0-mae:2126.87900
[382]	validation_0-mae:2126.85831
[383]	validation_0-mae:2126.60906
[384]	validation_0-mae:2125.84681
[385]	validation_0-mae:2125.50966
[386]	validation_0-mae:2124.84885
[387]	validation_0-mae:2124.22155
[388]	validation_0-mae:2124.86650
[389]	validation_0-mae:2125.46017
[390]	validation_0-mae:2125.47398
[391]	validation_0-mae:2125.56701
[392]	validation_0-mae:2125.31804
[393]	validation_0-mae:2125.38551
[394]	validation_0-mae:2125.05430
[395]	validation_0-mae:2125.07998
[396]	validation_0-mae:2124.45305
[397]	validation_0-mae:2125.50894
[398]	validation_0-mae:2125.76668
[399]	validation_0-mae:2125.64859
[400]	validation_0-mae:2125.56365
[401]	validation_0-mae:2125.19039
[402]	validation_0-mae:2125.69978
[403]	validation_0-mae:2125.82715
[404]	validation_0-mae:2125.64037
[405]	validation_0-mae:2125.49383
[406]	validation_0-mae:2125.62782
[407]	validation_0-mae:2125.95866
[408]	validation_0-mae:2126.10651
[409]	validation_0-mae:2125.46928
[410]	validation_0-mae:2125.47636
[411]	validation_0-mae:2125.20148
[412]	validation_0-mae:2125.47132
[413]	validation_0-mae:2125.68108
[414]	validation_0-mae:2125.62502
[415]	validation_0-mae:2125.09517
[416]	validation_0-mae:2125.15472
[417]	validation_0-mae:2124.98929
[418]	validation_0-mae:2124.25815
[419]	validation_0-mae:2123.40047
[420]	validation_0-mae:2122.30486
[421]	validation_0-mae:2122.00902
[422]	validation_0-mae:2122.10579
[423]	validation_0-mae:2122.07208
[424]	validation_0-mae:2121.70591
[425]	validation_0-mae:2121.74092
[426]	validation_0-mae:2122.05820
[427]	validation_0-mae:2122.35245
[428]	validation_0-mae:2121.73758
[429]	validation_0-mae:2121.39506
[430]	validation_0-mae:2120.51396
[431]	validation_0-mae:2120.68640
[432]	validation_0-mae:2120.21482
[433]	validation_0-mae:2119.52852
[434]	validation_0-mae:2119.42888
[435]	validation_0-mae:2118.77820
[436]	validation_0-mae:2118.51963
[437]	validation_0-mae:2116.71738
[438]	validation_0-mae:2117.31647
[439]	validation_0-mae:2117.23325
[440]	validation_0-mae:2117.08412
[441]	validation_0-mae:2117.40645
[442]	validation_0-mae:2117.55472
[443]	validation_0-mae:2117.67088
[444]	validation_0-mae:2118.04807
[445]	validation_0-mae:2117.85096
[446]	validation_0-mae:2117.78004
[447]	validation_0-mae:2117.87250
[448]	validation_0-mae:2118.02215
[449]	validation_0-mae:2118.20032
[450]	validation_0-mae:2118.03407
[451]	validation_0-mae:2118.27818
[452]	validation_0-mae:2118.50962
[453]	validation_0-mae:2117.96717
[454]	validation_0-mae:2118.02158
[455]	validation_0-mae:2117.65931
[456]	validation_0-mae:2117.82403
[457]	validation_0-mae:2118.13742
[458]	validation_0-mae:2118.58760
[459]	validation_0-mae:2118.51471
[460]	validation_0-mae:2118.94866
[461]	validation_0-mae:2118.23225
[462]	validation_0-mae:2118.31138
[463]	validation_0-mae:2118.36074
[464]	validation_0-mae:2117.62272
[465]	validation_0-mae:2116.91471
[466]	validation_0-mae:2116.33442
[467]	validation_0-mae:2116.47943
[468]	validation_0-mae:2116.30242
[469]	validation_0-mae:2116.38037
[470]	validation_0-mae:2116.55473
[471]	validation_0-mae:2116.45181
[472]	validation_0-mae:2116.81182
[473]	validation_0-mae:2116.86849
[474]	validation_0-mae:2117.13318
[475]	validation_0-mae:2116.90512
[476]	validation_0-mae:2117.20168
[477]	validation_0-mae:2116.75813
[478]	validation_0-mae:2116.69532
[479]	validation_0-mae:2116.61978
[480]	validation_0-mae:2116.73461
[481]	validation_0-mae:2116.81478
[482]	validation_0-mae:2116.68914
[483]	validation_0-mae:2116.60578
[484]	validation_0-mae:2116.90170
[485]	validation_0-mae:2116.37792
[486]	validation_0-mae:2116.39249
[487]	validation_0-mae:2116.63737
[488]	validation_0-mae:2116.88963
[489]	validation_0-mae:2116.85880
[490]	validation_0-mae:2116.94174
[0]	validation_0-mae:12435.41256
[1]	validation_0-mae:11686.91453
[2]	validation_0-mae:11012.25241
[3]	validation_0-mae:10409.01400
[4]	validation_0-mae:9871.77318
[5]	validation_0-mae:9390.68800
[6]	validation_0-mae:8965.22404
[7]	validation_0-mae:8605.69000
[8]	validation_0-mae:8274.28895
[9]	validation_0-mae:7995.71087
[10]	validation_0-mae:7734.86685

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[0]	validation_0-mae:12608.97490
[1]	validation_0-mae:11986.26550
[2]	validation_0-mae:11437.42457
[3]	validation_0-mae:10965.94311
[4]	validation_0-mae:10533.38358
[5]	validation_0-mae:10113.31931
[6]	validation_0-mae:9729.82100
[7]	validation_0-mae:9387.72015
[8]	validation_0-mae:9102.09469
[9]	validation_0-mae:8796.50988
[10]	validation_0-mae:8518.19035
[0]	validation_0-mae:12453.20799
[1]	validation_0-mae:11726.72833
[2]	validation_0-mae:11071.49997
[3]	validation_0-mae:10436.83227
[4]	validation_0-mae:9891.32854
[5]	validation_0-mae:9391.85827
[6]	validation_0-mae:8937.46385
[7]	validation_0-mae:8511.85292
[8]	validation_0-mae:8140.69845
[9]	validation_0-mae:7805.23851
[10]	validation_0-mae:7485.76115
[11]	validation_0-mae:7172.26832
[12]	validation_0-mae:6905.57707
[13]	validation_0-mae:6649.24301
[14]	validation_0-mae:6391.36701
[15]	validation_0-mae:6150.05167
[16]	validation_0-mae:5934.75087
[17]	validation_0-mae:5727.99097
[18]	validation_0-mae:5541.34183
[19]	validation_0-mae:5359.54222
[20]	validation_0-mae:5207.56017
[21]	validation_0-mae:5033.70414
[22]	validation_0-mae:4896.97915
[23]	validation_0-mae:4759.05992
[24]	validation_0-mae:4637.45667
[25]	validation_0-mae:4520.76292
[26]	validation_0-mae:4421.14367
[27]	validation_0-mae:4316.02770
[28]	validation_0-mae:4221.80521
[29]	validation_0-mae:4122.22717
[30]	validation_0-mae:4025.44154
[31]	validation_0-mae:3943.95665
[32]	validation_0-mae:3859.80149
[33]	validation_0-mae:3787.32852
[34]	validation_0-mae:3698.72093
[35]	validation_0-mae:3634.35152
[36]	validation_0-mae:3569.50970
[37]	validation_0-mae:3509.77645
[38]	validation_0-mae:3449.11648

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[39]	validation_0-mae:3404.86731
[40]	validation_0-mae:3353.91109
[41]	validation_0-mae:3314.56548
[42]	validation_0-mae:3272.29550
[43]	validation_0-mae:3233.31309
[44]	validation_0-mae:3192.79326
[45]	validation_0-mae:3161.30139
[46]	validation_0-mae:3128.11734
[47]	validation_0-mae:3101.03035
[48]	validation_0-mae:3057.59107
[49]	validation_0-mae:3027.65851
[50]	validation_0-mae:3008.39991
[51]	validation_0-mae:2973.87581
[52]	validation_0-mae:2939.99340
[53]	validation_0-mae:2919.65163
[54]	validation_0-mae:2888.12924
[55]	validation_0-mae:2870.42559
[56]	validation_0-mae:2852.98049
[57]	validation_0-mae:2838.95326
[58]	validation_0-mae:2814.08190
[59]	validation_0-mae:2799.84296
[60]	validation_0-mae:2787.19009
[61]	validation_0-mae:2771.81769
[62]	validation_0-mae:2748.70315
[63]	validation_0-mae:2736.22142
[64]	validation_0-mae:2729.31815
[65]	validation_0-mae:2709.28077
[66]	validation_0-mae:2698.18264
[67]	validation_0-mae:2673.88211
[68]	validation_0-mae:2655.83831
[69]	validation_0-mae:2646.41560
[70]	validation_0-mae:2635.97970
[71]	validation_0-mae:2627.39731
[72]	validation_0-mae:2614.33574
[73]	validation_0-mae:2609.99322
[74]	validation_0-mae:2598.90065
[75]	validation_0-mae:2586.01699
[76]	validation_0-mae:2575.23388
[77]	validation_0-mae:2568.04852
[78]	validation_0-mae:2561.68486
[79]	validation_0-mae:2550.77959
[80]	validation_0-mae:2543.19895
[81]	validation_0-mae:2533.38741
[82]	validation_0-mae:2524.05708
[83]	validation_0-mae:2518.39284
[84]	validation_0-mae:2512.85953
[85]	validation_0-mae:2502.97851
[86]	validation_0-mae:2498.20584
[87]	validation_0-mae:2491.68537
[88]	validation_0-mae:2483.74604
[89]	validation_0-mae:2472.97023
[90]	validation_0-mae:2465.02564
[91]	validation_0-mae:2457.05903
[92]	validation_0-mae:2452.88647
[93]	validation_0-mae:2441.25697
[94]	validation_0-mae:2435.72083
[95]	validation_0-mae:2423.45702
[96]	validation_0-mae:2419.12719
[97]	validation_0-mae:2413.73710
[98]	validation_0-mae:2408.27409
[99]	validation_0-mae:2398.26271
[100]	validation_0-mae:2393.41078
[101]	validation_0-mae:2383.09980
[102]	validation_0-mae:2378.31055
[103]	validation_0-mae:2371.89058
[104]	validation_0-mae:2367.49209
[105]	validation_0-mae:2362.85695
[106]	validation_0-mae:2362.07538
[107]	validation_0-mae:2355.94773
[108]	validation_0-mae:2353.36252
[109]	validation_0-mae:2351.10861
[110]	validation_0-mae:2346.85403
[111]	validation_0-mae:2340.83033
[112]	validation_0-mae:2335.32328
[113]	validation_0-mae:2332.81725
[114]	validation_0-mae:2325.47707
[115]	validation_0-mae:2319.69669
[116]	validation_0-mae:2313.48700
[117]	validation_0-mae:2310.20001
[118]	validation_0-mae:2306.34560
[119]	validation_0-mae:2305.15853
[120]	validation_0-mae:2298.45673
[121]	validation_0-mae:2290.51480
[122]	validation_0-mae:2286.96178
[123]	validation_0-mae:2284.44835
[124]	validation_0-mae:2281.58113
[125]	validation_0-mae:2274.21871
[126]	validation_0-mae:2271.97332
[127]	validation_0-mae:2271.48227
[128]	validation_0-mae:2270.54799
[129]	validation_0-mae:2267.67888
[130]	validation_0-mae:2263.73941
[131]	validation_0-mae:2262.57824
[132]	validation_0-mae:2260.88735
[133]	validation_0-mae:2257.75397
[134]	validation_0-mae:2254.29547
[135]	validation_0-mae:2253.22013
[136]	validation_0-mae:2252.34860
[137]	validation_0-mae:2251.73105
[138]	validation_0-mae:2248.51851
[139]	validation_0-mae:2243.14338
[140]	validation_0-mae:2236.96653
[141]	validation_0-mae:2236.47502
[142]	validation_0-mae:2233.06160
[143]	validation_0-mae:2230.67572
[144]	validation_0-mae:2228.97821
[145]	validation_0-mae:2227.39179
[146]	validation_0-mae:2224.06181
[147]	validation_0-mae:2221.15499
[148]	validation_0-mae:2221.46120
[149]	validation_0-mae:2221.42162
[150]	validation_0-mae:2220.14595
[151]	validation_0-mae:2216.41543
[152]	validation_0-mae:2214.58373
[153]	validation_0-mae:2214.44980
[154]	validation_0-mae:2214.90851
[155]	validation_0-mae:2214.95126
[156]	validation_0-mae:2213.37391
[157]	validation_0-mae:2210.25570
[158]	validation_0-mae:2207.96061
[159]	validation_0-mae:2206.66239
[160]	validation_0-mae:2205.95780
[161]	validation_0-mae:2205.69390
[162]	validation_0-mae:2204.22537
[163]	validation_0-mae:2201.36535
[164]	validation_0-mae:2198.98175
[165]	validation_0-mae:2198.51854
[166]	validation_0-mae:2197.57141
[167]	validation_0-mae:2197.75451
[168]	validation_0-mae:2196.75335
[169]	validation_0-mae:2195.56574
[170]	validation_0-mae:2193.95717
[171]	validation_0-mae:2192.30497
[172]	validation_0-mae:2192.11407
[173]	validation_0-mae:2190.86284
[174]	validation_0-mae:2191.77790
[175]	validation_0-mae:2190.36185
[176]	validation_0-mae:2189.21695
[177]	validation_0-mae:2187.55589
[178]	validation_0-mae:2186.62877
[179]	validation_0-mae:2183.56201
[180]	validation_0-mae:2183.04298
[181]	validation_0-mae:2181.21797
[182]	validation_0-mae:2180.64657
[183]	validation_0-mae:2178.04718
[184]	validation_0-mae:2175.94715
[185]	validation_0-mae:2175.87177
[186]	validation_0-mae:2175.38500
[187]	validation_0-mae:2175.53418
[188]	validation_0-mae:2174.96833
[189]	validation_0-mae:2174.43250
[190]	validation_0-mae:2174.64582
[191]	validation_0-mae:2175.32761
[192]	validation_0-mae:2172.48251
[193]	validation_0-mae:2172.19202
[194]	validation_0-mae:2171.15291
[195]	validation_0-mae:2171.36914
[196]	validation_0-mae:2172.42293
[197]	validation_0-mae:2171.42160
[198]	validation_0-mae:2171.05760
[199]	validation_0-mae:2169.85032
[200]	validation_0-mae:2169.23240
[201]	validation_0-mae:2169.83390
[202]	validation_0-mae:2169.11763
[203]	validation_0-mae:2167.34808
[204]	validation_0-mae:2167.06217
[205]	validation_0-mae:2165.65903
[206]	validation_0-mae:2165.60750
[207]	validation_0-mae:2166.31498
[208]	validation_0-mae:2166.13806
[209]	validation_0-mae:2166.44949
[210]	validation_0-mae:2165.53161
[211]	validation_0-mae:2165.27026
[212]	validation_0-mae:2165.43751
[213]	validation_0-mae:2163.76823
[214]	validation_0-mae:2164.06639
[215]	validation_0-mae:2164.23638
[216]	validation_0-mae:2164.01387
[217]	validation_0-mae:2162.14125
[218]	validation_0-mae:2161.83580
[219]	validation_0-mae:2160.13321
[220]	validation_0-mae:2160.67832
[221]	validation_0-mae:2160.61084
[222]	validation_0-mae:2160.13600
[223]	validation_0-mae:2161.00251
[224]	validation_0-mae:2161.23959
[225]	validation_0-mae:2159.58633
[226]	validation_0-mae:2159.53462
[227]	validation_0-mae:2158.09677
[228]	validation_0-mae:2157.09573
[229]	validation_0-mae:2157.40492
[230]	validation_0-mae:2157.02116
[231]	validation_0-mae:2156.31311
[232]	validation_0-mae:2156.64214
[233]	validation_0-mae:2154.77256
[234]	validation_0-mae:2155.31335
[235]	validation_0-mae:2154.88558
[236]	validation_0-mae:2154.81863
[237]	validation_0-mae:2154.10057
[238]	validation_0-mae:2153.35232
[239]	validation_0-mae:2153.26007
[240]	validation_0-mae:2153.89197
[241]	validation_0-mae:2153.14192
[242]	validation_0-mae:2153.26151
[243]	validation_0-mae:2153.41203
[244]	validation_0-mae:2152.36476
[245]	validation_0-mae:2152.47186
[246]	validation_0-mae:2152.59888
[247]	validation_0-mae:2153.14401
[248]	validation_0-mae:2152.59862
[249]	validation_0-mae:2151.76391
[250]	validation_0-mae:2150.10234
[251]	validation_0-mae:2150.48330
[252]	validation_0-mae:2150.83031
[253]	validation_0-mae:2149.46192
[254]	validation_0-mae:2148.58619
[255]	validation_0-mae:2147.51820
[256]	validation_0-mae:2148.36801
[257]	validation_0-mae:2147.84197
[258]	validation_0-mae:2146.86985
[259]	validation_0-mae:2146.66349
[260]	validation_0-mae:2145.59413
[261]	validation_0-mae:2144.74128
[262]	validation_0-mae:2144.69897
[263]	validation_0-mae:2144.92087
[264]	validation_0-mae:2144.08973
[265]	validation_0-mae:2145.07458
[266]	validation_0-mae:2145.18865
[267]	validation_0-mae:2144.83884
[268]	validation_0-mae:2144.79599
[269]	validation_0-mae:2144.78256
[270]	validation_0-mae:2144.89613
[271]	validation_0-mae:2144.71624
[272]	validation_0-mae:2143.54916
[273]	validation_0-mae:2142.90769
[274]	validation_0-mae:2143.45349
[275]	validation_0-mae:2143.10445
[276]	validation_0-mae:2143.79768
[277]	validation_0-mae:2144.47303
[278]	validation_0-mae:2144.58421
[279]	validation_0-mae:2143.63443
[280]	validation_0-mae:2143.18237
[281]	validation_0-mae:2143.39586
[282]	validation_0-mae:2143.67744
[283]	validation_0-mae:2143.42850
[284]	validation_0-mae:2143.56994
[285]	validation_0-mae:2143.19370
[286]	validation_0-mae:2142.67390
[287]	validation_0-mae:2142.54928
[288]	validation_0-mae:2142.60149
[289]	validation_0-mae:2142.08305
[290]	validation_0-mae:2141.75565
[291]	validation_0-mae:2141.82941
[292]	validation_0-mae:2141.15956
[293]	validation_0-mae:2140.46823
[294]	validation_0-mae:2139.57769
[295]	validation_0-mae:2139.45107
[296]	validation_0-mae:2139.40779
[297]	validation_0-mae:2139.31249
[298]	validation_0-mae:2138.64760
[299]	validation_0-mae:2138.37083
[300]	validation_0-mae:2138.00072
[301]	validation_0-mae:2137.66581
[302]	validation_0-mae:2138.20489
[303]	validation_0-mae:2138.33011
[304]	validation_0-mae:2138.53182
[305]	validation_0-mae:2138.75397
[306]	validation_0-mae:2139.08676
[307]	validation_0-mae:2139.53131
[308]	validation_0-mae:2139.59561
[309]	validation_0-mae:2139.65442
[310]	validation_0-mae:2139.05129
[311]	validation_0-mae:2138.66554
[312]	validation_0-mae:2138.65378
[313]	validation_0-mae:2138.63314
[314]	validation_0-mae:2138.38923
[315]	validation_0-mae:2137.04253
[316]	validation_0-mae:2137.09898
[317]	validation_0-mae:2136.51590
[318]	validation_0-mae:2136.74487
[319]	validation_0-mae:2136.25841
[320]	validation_0-mae:2136.43254
[321]	validation_0-mae:2135.07732
[322]	validation_0-mae:2134.18345
[323]	validation_0-mae:2134.07465
[324]	validation_0-mae:2133.44798
[325]	validation_0-mae:2133.21663
[326]	validation_0-mae:2132.64735
[327]	validation_0-mae:2132.74403
[328]	validation_0-mae:2132.79630
[329]	validation_0-mae:2133.04716
[330]	validation_0-mae:2132.68740
[331]	validation_0-mae:2132.52634
[332]	validation_0-mae:2132.15724
[333]	validation_0-mae:2132.13193
[334]	validation_0-mae:2131.98096
[335]	validation_0-mae:2131.68549
[336]	validation_0-mae:2131.59375
[337]	validation_0-mae:2130.70216
[338]	validation_0-mae:2131.40101
[339]	validation_0-mae:2131.39558
[340]	validation_0-mae:2130.99282
[341]	validation_0-mae:2131.30194
[342]	validation_0-mae:2130.89400
[343]	validation_0-mae:2131.30579
[344]	validation_0-mae:2131.18377
[345]	validation_0-mae:2130.36559
[346]	validation_0-mae:2129.18653
[347]	validation_0-mae:2129.36530
[348]	validation_0-mae:2129.42826
[349]	validation_0-mae:2128.56427
[350]	validation_0-mae:2128.14175
[351]	validation_0-mae:2128.14978
[352]	validation_0-mae:2128.74273
[353]	validation_0-mae:2128.14043
[354]	validation_0-mae:2127.52548
[355]	validation_0-mae:2127.49952
[356]	validation_0-mae:2127.67488
[357]	validation_0-mae:2127.62544
[358]	validation_0-mae:2126.82606
[359]	validation_0-mae:2126.19621
[360]	validation_0-mae:2126.28694
[361]	validation_0-mae:2125.62594
[362]	validation_0-mae:2124.95544
[363]	validation_0-mae:2124.60652
[364]	validation_0-mae:2123.91494
[365]	validation_0-mae:2124.12980
[366]	validation_0-mae:2124.09576
[367]	validation_0-mae:2124.23154
[368]	validation_0-mae:2124.04588
[369]	validation_0-mae:2123.44530
[370]	validation_0-mae:2123.16728
[371]	validation_0-mae:2123.18486
[372]	validation_0-mae:2122.95672
[373]	validation_0-mae:2123.56247
[374]	validation_0-mae:2123.32002
[375]	validation_0-mae:2123.28287
[376]	validation_0-mae:2123.77435
[377]	validation_0-mae:2123.80266
[378]	validation_0-mae:2123.74257
[379]	validation_0-mae:2123.65259
[380]	validation_0-mae:2123.98746
[381]	validation_0-mae:2123.77530
[382]	validation_0-mae:2123.61375
[383]	validation_0-mae:2123.06651
[384]	validation_0-mae:2122.32918
[385]	validation_0-mae:2122.12235
[386]	validation_0-mae:2122.07738
[387]	validation_0-mae:2122.17739
[388]	validation_0-mae:2122.25920
[389]	validation_0-mae:2122.38952
[390]	validation_0-mae:2122.36090
[391]	validation_0-mae:2122.43659
[392]	validation_0-mae:2122.58065
[393]	validation_0-mae:2122.45249
[394]	validation_0-mae:2121.82514
[395]	validation_0-mae:2122.52105
[396]	validation_0-mae:2122.31821
[397]	validation_0-mae:2122.04905
[398]	validation_0-mae:2121.75800
[399]	validation_0-mae:2121.78221
[400]	validation_0-mae:2120.77171
[401]	validation_0-mae:2121.16181
[402]	validation_0-mae:2120.42126
[403]	validation_0-mae:2120.74045
[404]	validation_0-mae:2120.15679
[405]	validation_0-mae:2119.98339
[406]	validation_0-mae:2119.41672
[407]	validation_0-mae:2119.03617
[408]	validation_0-mae:2119.13154
[409]	validation_0-mae:2118.92714
[410]	validation_0-mae:2119.01168
[411]	validation_0-mae:2119.97269
[412]	validation_0-mae:2119.04402
[413]	validation_0-mae:2119.28173
[414]	validation_0-mae:2118.55681
[415]	validation_0-mae:2118.93726
[416]	validation_0-mae:2118.86824
[417]	validation_0-mae:2118.81438
[418]	validation_0-mae:2118.86919
[419]	validation_0-mae:2118.87785
[420]	validation_0-mae:2119.37802
[421]	validation_0-mae:2118.95336
[422]	validation_0-mae:2118.75055
[423]	validation_0-mae:2118.60448
[424]	validation_0-mae:2118.77403
[425]	validation_0-mae:2119.03541
[426]	validation_0-mae:2118.13345
[427]	validation_0-mae:2117.89826
[428]	validation_0-mae:2117.86000
[429]	validation_0-mae:2117.71468
[430]	validation_0-mae:2117.57119
[431]	validation_0-mae:2117.44340
[432]	validation_0-mae:2117.21533
[433]	validation_0-mae:2117.25047
[434]	validation_0-mae:2117.14814
[435]	validation_0-mae:2117.30128
[436]	validation_0-mae:2117.49739
[437]	validation_0-mae:2117.86629
[438]	validation_0-mae:2117.59478
[439]	validation_0-mae:2117.76683
[440]	validation_0-mae:2117.34751
[441]	validation_0-mae:2117.59487
[442]	validation_0-mae:2117.26687
[443]	validation_0-mae:2117.31020
[444]	validation_0-mae:2117.08640
[445]	validation_0-mae:2117.69599
[446]	validation_0-mae:2117.74194
[447]	validation_0-mae:2118.33701
[448]	validation_0-mae:2118.16217
[449]	validation_0-mae:2118.33553
[450]	validation_0-mae:2118.36955
[451]	validation_0-mae:2118.25449
[452]	validation_0-mae:2117.58473
[453]	validation_0-mae:2117.61528
[454]	validation_0-mae:2118.02421
[455]	validation_0-mae:2117.91582
[456]	validation_0-mae:2117.83261
[457]	validation_0-mae:2118.14244
[458]	validation_0-mae:2118.50610
[459]	validation_0-mae:2118.65958
[460]	validation_0-mae:2118.54006
[461]	validation_0-mae:2117.72704
[462]	validation_0-mae:2117.67666
[463]	validation_0-mae:2116.98951
[464]	validation_0-mae:2116.89931
[465]	validation_0-mae:2117.00695
[466]	validation_0-mae:2116.91594
[467]	validation_0-mae:2116.49892
[468]	validation_0-mae:2116.50499
[469]	validation_0-mae:2116.35576
[470]	validation_0-mae:2115.65388
[471]	validation_0-mae:2115.30019
[472]	validation_0-mae:2115.20786
[473]	validation_0-mae:2115.01323
[474]	validation_0-mae:2115.43727
[475]	validation_0-mae:2115.50636
[476]	validation_0-mae:2115.15879
[477]	validation_0-mae:2115.11627
[478]	validation_0-mae:2114.26343
[479]	validation_0-mae:2114.32468
[480]	validation_0-mae:2114.38311
[481]	validation_0-mae:2114.78009
[482]	validation_0-mae:2114.37414
[483]	validation_0-mae:2113.24639
[484]	validation_0-mae:2112.95776
[485]	validation_0-mae:2113.22672
[486]	validation_0-mae:2113.20384
[487]	validation_0-mae:2113.23117
[488]	validation_0-mae:2113.28257
[489]	validation_0-mae:2113.45192
[490]	validation_0-mae:2113.58452
[491]	validation_0-mae:2113.56130
[492]	validation_0-mae:2113.16658
[493]	validation_0-mae:2113.41076
[494]	validation_0-mae:2113.68237
[495]	validation_0-mae:2113.65993
[496]	validation_0-mae:2113.88653
[497]	validation_0-mae:2114.09412
[498]	validation_0-mae:2114.14930
[499]	validation_0-mae:2114.03509
[500]	validation_0-mae:2114.60699
[501]	validation_0-mae:2114.75284
[502]	validation_0-mae:2114.80770
[503]	validation_0-mae:2114.10902
[504]	validation_0-mae:2114.26850
[505]	validation_0-mae:2114.14934
[506]	validation_0-mae:2114.67330
[507]	validation_0-mae:2114.41186
[508]	validation_0-mae:2114.07021
[509]	validation_0-mae:2113.98567
[510]	validation_0-mae:2113.53831
[511]	validation_0-mae:2113.24354
[512]	validation_0-mae:2113.41226
[513]	validation_0-mae:2113.41267
[514]	validation_0-mae:2113.66875
[0]	validation_0-mae:12408.02753
[1]	validation_0-mae:11647.72866
[2]	validation_0-mae:10967.33282
[3]	validation_0-mae:10309.01391
[4]	validation_0-mae:9746.84729
[5]	validation_0-mae:9227.36820
[6]	validation_0-mae:8763.19350
[7]	validation_0-mae:8332.54690
[8]	validation_0-mae:7935.00598
[9]	validation_0-mae:7587.82950
[10]	validation_0-mae:7271.20049
[11]	validation_0-mae:6963.31085
[12]	validation_0-mae:6688.48025
[13]	validation_0-mae:6425.19625
[14]	validation_0-mae:6188.12768
[15]	validation_0-mae:5960.62490
[16]	validation_0-mae:5741.63423
[17]	validation_0-mae:5539.36429
[18]	validation_0-mae:5337.64498
[19]	validation_0-mae:5155.65533
[20]	validation_0-mae:5001.75421
[21]	validation_0-mae:4851.79507
[22]	validation_0-mae:4700.11724
[23]	validation_0-mae:4565.02307
[24]	validation_0-mae:4450.10341
[25]	validation_0-mae:4330.05662
[26]	validation_0-mae:4216.35149
[27]	validation_0-mae:4124.85486
[28]	validation_0-mae:4035.05887
[29]	validation_0-mae:3923.99278
[30]	validation_0-mae:3837.04574
[31]	validation_0-mae:3758.50932
[32]	validation_0-mae:3690.67327
[33]	validation_0-mae:3602.27977
[34]	validation_0-mae:3533.17910
[35]	validation_0-mae:3480.78049
[36]	validation_0-mae:3426.27327
[37]	validation_0-mae:3379.11326
[38]	validation_0-mae:3321.25796
[39]	validation_0-mae:3272.38755

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[40]	validation_0-mae:3240.29094
[41]	validation_0-mae:3201.77993
[42]	validation_0-mae:3166.02683
[43]	validation_0-mae:3133.44633
[44]	validation_0-mae:3103.68127
[45]	validation_0-mae:3072.40600
[46]	validation_0-mae:3042.88251
[47]	validation_0-mae:3012.95926
[48]	validation_0-mae:2982.27380
[49]	validation_0-mae:2965.03047
[50]	validation_0-mae:2941.18922
[51]	validation_0-mae:2917.00542
[52]	validation_0-mae:2892.56740
[53]	validation_0-mae:2879.28290
[54]	validation_0-mae:2851.86896
[55]	validation_0-mae:2822.26851
[56]	validation_0-mae:2806.54665
[57]	validation_0-mae:2778.24012
[58]	validation_0-mae:2759.89567
[59]	validation_0-mae:2745.83054
[60]	validation_0-mae:2721.93152
[61]	validation_0-mae:2713.44064
[62]	validation_0-mae:2703.18630
[63]	validation_0-mae:2692.01442
[64]	validation_0-mae:2670.58653
[65]	validation_0-mae:2662.58740
[66]	validation_0-mae:2654.12368
[67]	validation_0-mae:2646.37854
[68]	validation_0-mae:2628.21114
[69]	validation_0-mae:2613.86769
[70]	validation_0-mae:2604.24680
[71]	validation_0-mae:2586.13161
[72]	validation_0-mae:2581.44031
[73]	validation_0-mae:2569.09481
[74]	validation_0-mae:2559.63687
[75]	validation_0-mae:2553.72576
[76]	validation_0-mae:2541.10658
[77]	validation_0-mae:2527.80492
[78]	validation_0-mae:2525.62668
[79]	validation_0-mae:2520.48112
[80]	validation_0-mae:2510.86791
[81]	validation_0-mae:2493.87722
[82]	validation_0-mae:2488.34135
[83]	validation_0-mae:2472.97107
[84]	validation_0-mae:2467.28890
[85]	validation_0-mae:2463.31183
[86]	validation_0-mae:2456.35159
[87]	validation_0-mae:2447.98513
[88]	validation_0-mae:2441.41517
[89]	validation_0-mae:2436.61825
[90]	validation_0-mae:2430.43272
[91]	validation_0-mae:2422.97912
[92]	validation_0-mae:2414.01424
[93]	validation_0-mae:2404.48347
[94]	validation_0-mae:2401.96735
[95]	validation_0-mae:2396.48616
[96]	validation_0-mae:2396.01711
[97]	validation_0-mae:2388.44344
[98]	validation_0-mae:2383.35269
[99]	validation_0-mae:2377.72875
[100]	validation_0-mae:2375.28629
[101]	validation_0-mae:2371.03862
[102]	validation_0-mae:2369.01211
[103]	validation_0-mae:2365.71833
[104]	validation_0-mae:2356.81761
[105]	validation_0-mae:2354.02333
[106]	validation_0-mae:2349.03086
[107]	validation_0-mae:2346.70837
[108]	validation_0-mae:2343.12897
[109]	validation_0-mae:2341.29387
[110]	validation_0-mae:2337.95941
[111]	validation_0-mae:2333.03366
[112]	validation_0-mae:2326.51416
[113]	validation_0-mae:2324.16391
[114]	validation_0-mae:2318.40835
[115]	validation_0-mae:2316.16609
[116]	validation_0-mae:2312.30207
[117]	validation_0-mae:2308.15613
[118]	validation_0-mae:2305.68917
[119]	validation_0-mae:2296.66945
[120]	validation_0-mae:2294.26608
[121]	validation_0-mae:2289.99617
[122]	validation_0-mae:2287.30913
[123]	validation_0-mae:2281.69238
[124]	validation_0-mae:2279.34068
[125]	validation_0-mae:2278.00342
[126]	validation_0-mae:2274.61105
[127]	validation_0-mae:2273.96467
[128]	validation_0-mae:2268.69962
[129]	validation_0-mae:2268.28113
[130]	validation_0-mae:2265.08118
[131]	validation_0-mae:2259.87902
[132]	validation_0-mae:2258.47307
[133]	validation_0-mae:2257.78369
[134]	validation_0-mae:2253.64052
[135]	validation_0-mae:2251.65719
[136]	validation_0-mae:2247.18089
[137]	validation_0-mae:2244.80797
[138]	validation_0-mae:2241.38175
[139]	validation_0-mae:2238.39986
[140]	validation_0-mae:2234.76091
[141]	validation_0-mae:2229.05417
[142]	validation_0-mae:2227.64351
[143]	validation_0-mae:2226.53391
[144]	validation_0-mae:2226.15616
[145]	validation_0-mae:2224.35337
[146]	validation_0-mae:2220.88293
[147]	validation_0-mae:2219.91539
[148]	validation_0-mae:2218.59930
[149]	validation_0-mae:2218.69015
[150]	validation_0-mae:2216.01276
[151]	validation_0-mae:2214.33332
[152]	validation_0-mae:2214.97536
[153]	validation_0-mae:2215.20419
[154]	validation_0-mae:2213.25427
[155]	validation_0-mae:2208.69168
[156]	validation_0-mae:2206.93703
[157]	validation_0-mae:2204.33697
[158]	validation_0-mae:2202.66891
[159]	validation_0-mae:2200.94713
[160]	validation_0-mae:2201.66776
[161]	validation_0-mae:2202.46688
[162]	validation_0-mae:2201.87651
[163]	validation_0-mae:2201.96391
[164]	validation_0-mae:2199.80344
[165]	validation_0-mae:2199.59207
[166]	validation_0-mae:2199.79154
[167]	validation_0-mae:2198.22355
[168]	validation_0-mae:2196.85082
[169]	validation_0-mae:2197.98310
[170]	validation_0-mae:2196.18604
[171]	validation_0-mae:2195.06620
[172]	validation_0-mae:2192.55110
[173]	validation_0-mae:2190.69281
[174]	validation_0-mae:2190.42037
[175]	validation_0-mae:2188.03068
[176]	validation_0-mae:2187.97450
[177]	validation_0-mae:2188.20534
[178]	validation_0-mae:2185.86190
[179]	validation_0-mae:2186.21513
[180]	validation_0-mae:2185.83653
[181]	validation_0-mae:2186.90035
[182]	validation_0-mae:2187.23083
[183]	validation_0-mae:2185.89577
[184]	validation_0-mae:2183.01771
[185]	validation_0-mae:2183.32698
[186]	validation_0-mae:2182.82086
[187]	validation_0-mae:2182.72245
[188]	validation_0-mae:2183.55241
[189]	validation_0-mae:2181.32642
[190]	validation_0-mae:2177.69049
[191]	validation_0-mae:2177.09539
[192]	validation_0-mae:2176.24400
[193]	validation_0-mae:2173.81076
[194]	validation_0-mae:2174.46707
[195]	validation_0-mae:2172.97440
[196]	validation_0-mae:2172.45564
[197]	validation_0-mae:2172.36942
[198]	validation_0-mae:2170.55642
[199]	validation_0-mae:2168.02608
[200]	validation_0-mae:2167.52943
[201]	validation_0-mae:2167.31022
[202]	validation_0-mae:2164.63670
[203]	validation_0-mae:2162.68018
[204]	validation_0-mae:2160.39761
[205]	validation_0-mae:2160.87344
[206]	validation_0-mae:2160.66536
[207]	validation_0-mae:2159.29008
[208]	validation_0-mae:2158.42903
[209]	validation_0-mae:2157.38888
[210]	validation_0-mae:2156.20496
[211]	validation_0-mae:2155.11329
[212]	validation_0-mae:2154.88095
[213]	validation_0-mae:2153.87891
[214]	validation_0-mae:2154.57241
[215]	validation_0-mae:2154.60954
[216]	validation_0-mae:2153.59598
[217]	validation_0-mae:2151.76099
[218]	validation_0-mae:2150.49391
[219]	validation_0-mae:2149.41190
[220]	validation_0-mae:2148.82239
[221]	validation_0-mae:2147.12692
[222]	validation_0-mae:2145.79044
[223]	validation_0-mae:2146.29022
[224]	validation_0-mae:2145.12541
[225]	validation_0-mae:2144.28302
[226]	validation_0-mae:2144.45794
[227]	validation_0-mae:2143.23468
[228]	validation_0-mae:2142.69166
[229]	validation_0-mae:2141.63944
[230]	validation_0-mae:2140.86223
[231]	validation_0-mae:2140.45163
[232]	validation_0-mae:2138.44424
[233]	validation_0-mae:2138.77070
[234]	validation_0-mae:2138.56961
[235]	validation_0-mae:2138.88459
[236]	validation_0-mae:2138.88134
[237]	validation_0-mae:2139.71940
[238]	validation_0-mae:2139.82490
[239]	validation_0-mae:2139.36462
[240]	validation_0-mae:2139.16420
[241]	validation_0-mae:2139.47288
[242]	validation_0-mae:2139.47090
[243]	validation_0-mae:2137.28128
[244]	validation_0-mae:2136.48913
[245]	validation_0-mae:2136.65827
[246]	validation_0-mae:2137.49836
[247]	validation_0-mae:2138.17803
[248]	validation_0-mae:2137.85310
[249]	validation_0-mae:2137.58510
[250]	validation_0-mae:2137.36374
[251]	validation_0-mae:2135.59559
[252]	validation_0-mae:2135.23737
[253]	validation_0-mae:2133.61152
[254]	validation_0-mae:2132.84403
[255]	validation_0-mae:2132.37815
[256]	validation_0-mae:2132.20598
[257]	validation_0-mae:2131.86861
[258]	validation_0-mae:2132.28580
[259]	validation_0-mae:2132.24458
[260]	validation_0-mae:2131.98601
[261]	validation_0-mae:2131.26416
[262]	validation_0-mae:2131.63986
[263]	validation_0-mae:2131.45914
[264]	validation_0-mae:2131.52261
[265]	validation_0-mae:2131.01121
[266]	validation_0-mae:2131.29696
[267]	validation_0-mae:2131.24478
[268]	validation_0-mae:2131.25199
[269]	validation_0-mae:2129.92480
[270]	validation_0-mae:2130.52524
[271]	validation_0-mae:2130.49840
[272]	validation_0-mae:2130.33471
[273]	validation_0-mae:2130.06128
[274]	validation_0-mae:2129.99328
[275]	validation_0-mae:2129.85672
[276]	validation_0-mae:2128.76233
[277]	validation_0-mae:2128.88783
[278]	validation_0-mae:2130.23765
[279]	validation_0-mae:2130.39036
[280]	validation_0-mae:2130.59740
[281]	validation_0-mae:2130.81035
[282]	validation_0-mae:2130.03498
[283]	validation_0-mae:2129.84918
[284]	validation_0-mae:2130.20521
[285]	validation_0-mae:2130.98111
[286]	validation_0-mae:2131.20092
[287]	validation_0-mae:2130.08275
[288]	validation_0-mae:2130.44645
[289]	validation_0-mae:2129.87204
[290]	validation_0-mae:2129.95631
[291]	validation_0-mae:2129.78545
[292]	validation_0-mae:2128.87542
[293]	validation_0-mae:2128.83740
[294]	validation_0-mae:2128.21332
[295]	validation_0-mae:2128.25309
[296]	validation_0-mae:2128.27312
[297]	validation_0-mae:2127.72222
[298]	validation_0-mae:2127.75100
[299]	validation_0-mae:2127.14914
[300]	validation_0-mae:2127.52376
[301]	validation_0-mae:2127.51287
[302]	validation_0-mae:2127.63545
[303]	validation_0-mae:2126.77061
[304]	validation_0-mae:2127.34525
[305]	validation_0-mae:2127.33627
[306]	validation_0-mae:2127.38295
[307]	validation_0-mae:2127.81937
[308]	validation_0-mae:2128.67536
[309]	validation_0-mae:2128.61590
[310]	validation_0-mae:2129.38512
[311]	validation_0-mae:2128.97197
[312]	validation_0-mae:2128.57389
[313]	validation_0-mae:2128.52585
[314]	validation_0-mae:2128.51448
[315]	validation_0-mae:2128.63804
[316]	validation_0-mae:2127.85244
[317]	validation_0-mae:2128.47060
[318]	validation_0-mae:2128.36305
[319]	validation_0-mae:2128.18524
[320]	validation_0-mae:2127.84911
[321]	validation_0-mae:2128.26393
[322]	validation_0-mae:2127.83506
[323]	validation_0-mae:2127.45902
[324]	validation_0-mae:2127.50957
[325]	validation_0-mae:2127.58510
[326]	validation_0-mae:2126.96589
[327]	validation_0-mae:2127.34873
[328]	validation_0-mae:2127.29321
[329]	validation_0-mae:2126.26810
[330]	validation_0-mae:2125.08384
[331]	validation_0-mae:2124.42976
[332]	validation_0-mae:2124.19273
[333]	validation_0-mae:2124.20451
[334]	validation_0-mae:2124.49940
[335]	validation_0-mae:2124.88618
[336]	validation_0-mae:2125.43829
[337]	validation_0-mae:2125.48531
[338]	validation_0-mae:2124.98350
[339]	validation_0-mae:2125.36217
[340]	validation_0-mae:2125.56014
[341]	validation_0-mae:2126.20891
[342]	validation_0-mae:2125.96977
[343]	validation_0-mae:2125.73384
[344]	validation_0-mae:2125.92333
[345]	validation_0-mae:2125.50805
[346]	validation_0-mae:2125.16139
[347]	validation_0-mae:2125.25414
[348]	validation_0-mae:2124.90207
[349]	validation_0-mae:2124.52920
[350]	validation_0-mae:2124.67434
[351]	validation_0-mae:2123.62514
[352]	validation_0-mae:2123.82883
[353]	validation_0-mae:2124.21564
[354]	validation_0-mae:2123.60318
[355]	validation_0-mae:2123.87372
[356]	validation_0-mae:2124.18628
[357]	validation_0-mae:2124.37789
[358]	validation_0-mae:2123.09332
[359]	validation_0-mae:2123.56564
[360]	validation_0-mae:2123.24313
[361]	validation_0-mae:2123.15541
[362]	validation_0-mae:2123.45284
[363]	validation_0-mae:2122.94091
[364]	validation_0-mae:2123.12086
[365]	validation_0-mae:2122.72937
[366]	validation_0-mae:2122.78151
[367]	validation_0-mae:2122.84183
[368]	validation_0-mae:2123.02619
[369]	validation_0-mae:2122.07925
[370]	validation_0-mae:2121.69441
[371]	validation_0-mae:2121.60976
[372]	validation_0-mae:2120.97191
[373]	validation_0-mae:2121.27285
[374]	validation_0-mae:2121.24289
[375]	validation_0-mae:2121.18358
[376]	validation_0-mae:2121.37747
[377]	validation_0-mae:2121.07882
[378]	validation_0-mae:2121.11125
[379]	validation_0-mae:2120.97869
[380]	validation_0-mae:2120.97329
[381]	validation_0-mae:2120.76516
[382]	validation_0-mae:2121.12523
[383]	validation_0-mae:2121.13637
[384]	validation_0-mae:2121.25476
[385]	validation_0-mae:2121.43001
[386]	validation_0-mae:2121.52573
[387]	validation_0-mae:2121.37856
[388]	validation_0-mae:2121.41123
[389]	validation_0-mae:2122.22155
[390]	validation_0-mae:2121.48114
[391]	validation_0-mae:2122.11190
[392]	validation_0-mae:2121.77074
[393]	validation_0-mae:2121.94948
[394]	validation_0-mae:2121.64322
[395]	validation_0-mae:2121.62139
[396]	validation_0-mae:2119.65905
[397]	validation_0-mae:2119.35200
[398]	validation_0-mae:2119.08682
[399]	validation_0-mae:2119.18754
[400]	validation_0-mae:2117.79721
[401]	validation_0-mae:2118.14076
[402]	validation_0-mae:2117.60105
[403]	validation_0-mae:2117.42592
[404]	validation_0-mae:2117.69587
[405]	validation_0-mae:2117.69476
[406]	validation_0-mae:2117.52703
[407]	validation_0-mae:2117.69961
[408]	validation_0-mae:2118.22371
[409]	validation_0-mae:2118.68036
[410]	validation_0-mae:2118.76731
[411]	validation_0-mae:2118.83263
[412]	validation_0-mae:2118.33671
[413]	validation_0-mae:2117.78833
[414]	validation_0-mae:2118.13152
[415]	validation_0-mae:2117.25606
[416]	validation_0-mae:2116.68239
[417]	validation_0-mae:2115.89486
[418]	validation_0-mae:2115.47831
[419]	validation_0-mae:2114.84870
[420]	validation_0-mae:2114.75657
[421]	validation_0-mae:2114.80101
[422]	validation_0-mae:2114.73517
[423]	validation_0-mae:2114.73723
[424]	validation_0-mae:2114.90151
[425]	validation_0-mae:2114.80167
[426]	validation_0-mae:2114.91752
[427]	validation_0-mae:2114.87405
[428]	validation_0-mae:2114.37223
[429]	validation_0-mae:2113.65746
[430]	validation_0-mae:2113.03730
[431]	validation_0-mae:2112.66345
[432]	validation_0-mae:2112.10383
[433]	validation_0-mae:2112.53901
[434]	validation_0-mae:2112.40019
[435]	validation_0-mae:2112.04450
[436]	validation_0-mae:2112.07340
[437]	validation_0-mae:2112.90421
[438]	validation_0-mae:2113.08103
[439]	validation_0-mae:2112.70325
[440]	validation_0-mae:2112.19882
[441]	validation_0-mae:2112.17545
[442]	validation_0-mae:2112.17446
[443]	validation_0-mae:2112.20738
[444]	validation_0-mae:2112.09498
[445]	validation_0-mae:2112.33293
[446]	validation_0-mae:2112.19592
[447]	validation_0-mae:2112.25934
[448]	validation_0-mae:2111.10261
[449]	validation_0-mae:2110.98321
[450]	validation_0-mae:2111.37118
[451]	validation_0-mae:2111.49290
[452]	validation_0-mae:2111.08204
[453]	validation_0-mae:2111.39434
[454]	validation_0-mae:2111.23894
[455]	validation_0-mae:2111.51996
[456]	validation_0-mae:2111.67627
[457]	validation_0-mae:2111.43594
[458]	validation_0-mae:2111.72020
[459]	validation_0-mae:2111.89970
[460]	validation_0-mae:2112.16377
[461]	validation_0-mae:2112.33746
[462]	validation_0-mae:2112.27641
[463]	validation_0-mae:2112.38594
[464]	validation_0-mae:2111.38855
[465]	validation_0-mae:2111.27271
[466]	validation_0-mae:2111.38095
[467]	validation_0-mae:2111.46211
[468]	validation_0-mae:2111.32038
[469]	validation_0-mae:2111.59258
[470]	validation_0-mae:2111.63342
[471]	validation_0-mae:2111.81375
[472]	validation_0-mae:2111.77313
[473]	validation_0-mae:2111.80446
[474]	validation_0-mae:2111.81992
[475]	validation_0-mae:2111.84448
[476]	validation_0-mae:2112.25042
[477]	validation_0-mae:2112.07218
[478]	validation_0-mae:2112.00197
[479]	validation_0-mae:2112.52757
[480]	validation_0-mae:2112.70617
[481]	validation_0-mae:2112.74840
[482]	validation_0-mae:2112.86096
[483]	validation_0-mae:2112.65276
[484]	validation_0-mae:2112.44144
[485]	validation_0-mae:2112.46997
[486]	validation_0-mae:2112.39594
[487]	validation_0-mae:2112.09190
[488]	validation_0-mae:2112.17962
[489]	validation_0-mae:2111.44093
[490]	validation_0-mae:2111.61382
[491]	validation_0-mae:2111.23625
[492]	validation_0-mae:2111.37113
[493]	validation_0-mae:2111.61953
[494]	validation_0-mae:2111.88199
[495]	validation_0-mae:2111.82617
[496]	validation_0-mae:2111.74572
[497]	validation_0-mae:2110.72370
[498]	validation_0-mae:2110.73635
[499]	validation_0-mae:2110.65466
[500]	validation_0-mae:2110.44630
[501]	validation_0-mae:2110.42505
[502]	validation_0-mae:2110.39167
[503]	validation_0-mae:2110.45656
[504]	validation_0-mae:2110.98072
[505]	validation_0-mae:2110.36029
[506]	validation_0-mae:2110.07491
[507]	validation_0-mae:2110.12560
[508]	validation_0-mae:2110.24395
[509]	validation_0-mae:2110.39440
[510]	validation_0-mae:2110.64205
[511]	validation_0-mae:2110.76365
[512]	validation_0-mae:2110.80031
[513]	validation_0-mae:2111.30228
[514]	validation_0-mae:2111.12673
[515]	validation_0-mae:2111.36656
[516]	validation_0-mae:2111.01682
[517]	validation_0-mae:2110.91945
[518]	validation_0-mae:2110.69293
[519]	validation_0-mae:2111.01852
[520]	validation_0-mae:2110.79686
[521]	validation_0-mae:2110.77455
[522]	validation_0-mae:2110.81461
[523]	validation_0-mae:2110.54516
[524]	validation_0-mae:2109.51800
[525]	validation_0-mae:2109.22744
[526]	validation_0-mae:2109.27961
[527]	validation_0-mae:2109.52904
[528]	validation_0-mae:2109.61983
[529]	validation_0-mae:2109.54117
[530]	validation_0-mae:2109.08508
[531]	validation_0-mae:2109.31119
[532]	validation_0-mae:2109.23116
[533]	validation_0-mae:2108.89026
[534]	validation_0-mae:2108.05478
[535]	validation_0-mae:2108.09240
[536]	validation_0-mae:2108.47444
[537]	validation_0-mae:2108.58765
[538]	validation_0-mae:2108.70915
[539]	validation_0-mae:2108.55178
[540]	validation_0-mae:2108.35729
[541]	validation_0-mae:2107.95449
[542]	validation_0-mae:2108.09656
[543]	validation_0-mae:2108.25950
[544]	validation_0-mae:2108.34906
[545]	validation_0-mae:2108.24933
[546]	validation_0-mae:2108.05128
[547]	validation_0-mae:2107.95193
[548]	validation_0-mae:2107.93238
[549]	validation_0-mae:2107.72126
[0]	validation_0-mae:12438.93554
[1]	validation_0-mae:11694.48550
[2]	validation_0-mae:11035.36922
[3]	validation_0-mae:10403.50641
[4]	validation_0-mae:9859.66880
[5]	validation_0-mae:9349.82997
[6]	validation_0-mae:8905.05991
[7]	validation_0-mae:8491.25794
[8]	validation_0-mae:8119.34061
[9]	validation_0-mae:7791.78422
[10]	validation_0-mae:7463.92030
[11]	validation_0-mae:7163.72210
[12]	validation_0-mae:6910.57068
[13]	validation_0-mae:6629.05100
[14]	validation_0-mae:6404.35509
[15]	validation_0-mae:6163.98551
[16]	validation_0-mae:5955.24368
[17]	validation_0-mae:5771.33752
[18]	validation_0-mae:5588.66330
[19]	validation_0-mae:5407.51610
[20]	validation_0-mae:5233.43797
[21]	validation_0-mae:5061.22668
[22]	validation_0-mae:4920.40619
[23]	validation_0-mae:4792.37045
[24]	validation_0-mae:4643.52488
[25]	validation_0-mae:4529.50398
[26]	validation_0-mae:4412.41013
[27]	validation_0-mae:4299.78961
[28]	validation_0-mae:4199.41497
[29]	validation_0-mae:4108.59805
[30]	validation_0-mae:4009.81654
[31]	validation_0-mae:3913.40535

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[32]	validation_0-mae:3829.89028
[33]	validation_0-mae:3746.61420
[34]	validation_0-mae:3678.55928
[35]	validation_0-mae:3603.42086
[36]	validation_0-mae:3548.51359
[37]	validation_0-mae:3485.98054
[38]	validation_0-mae:3440.12197
[39]	validation_0-mae:3384.78092
[40]	validation_0-mae:3344.09346
[41]	validation_0-mae:3303.80485
[42]	validation_0-mae:3268.34635
[43]	validation_0-mae:3211.17528
[44]	validation_0-mae:3171.51488
[45]	validation_0-mae:3132.67560
[46]	validation_0-mae:3082.48150
[47]	validation_0-mae:3052.63798
[48]	validation_0-mae:3020.22025
[49]	validation_0-mae:2991.34091
[50]	validation_0-mae:2956.52752
[51]	validation_0-mae:2931.30817
[52]	validation_0-mae:2910.18797
[53]	validation_0-mae:2888.63471
[54]	validation_0-mae:2869.47835
[55]	validation_0-mae:2838.05075
[56]	validation_0-mae:2820.47616
[57]	validation_0-mae:2802.87086
[58]	validation_0-mae:2784.30273
[59]	validation_0-mae:2760.12222
[60]	validation_0-mae:2748.30990
[61]	validation_0-mae:2728.82591
[62]	validation_0-mae:2716.49421
[63]	validation_0-mae:2703.54413
[64]	validation_0-mae:2680.53662
[65]	validation_0-mae:2669.86288
[66]	validation_0-mae:2661.04147
[67]	validation_0-mae:2642.32003
[68]	validation_0-mae:2629.57498
[69]	validation_0-mae:2621.30320
[70]	validation_0-mae:2613.13299
[71]	validation_0-mae:2597.24966
[72]	validation_0-mae:2582.77441
[73]	validation_0-mae:2575.86120
[74]	validation_0-mae:2562.57576
[75]	validation_0-mae:2553.12687
[76]	validation_0-mae:2540.06037
[77]	validation_0-mae:2535.33179
[78]	validation_0-mae:2527.33597
[79]	validation_0-mae:2514.19124
[80]	validation_0-mae:2510.45316
[81]	validation_0-mae:2504.94669
[82]	validation_0-mae:2496.81162
[83]	validation_0-mae:2489.11355
[84]	validation_0-mae:2478.36478
[85]	validation_0-mae:2469.95322
[86]	validation_0-mae:2462.78528
[87]	validation_0-mae:2452.76182
[88]	validation_0-mae:2438.15220
[89]	validation_0-mae:2431.46113
[90]	validation_0-mae:2427.17348
[91]	validation_0-mae:2420.44562
[92]	validation_0-mae:2408.46651
[93]	validation_0-mae:2398.91119
[94]	validation_0-mae:2396.29802
[95]	validation_0-mae:2390.41242
[96]	validation_0-mae:2385.83135
[97]	validation_0-mae:2381.91478
[98]	validation_0-mae:2376.33905
[99]	validation_0-mae:2374.04205
[100]	validation_0-mae:2367.66911
[101]	validation_0-mae:2367.98328
[102]	validation_0-mae:2360.87185
[103]	validation_0-mae:2357.67489
[104]	validation_0-mae:2352.67354
[105]	validation_0-mae:2343.85876
[106]	validation_0-mae:2341.56402
[107]	validation_0-mae:2331.30872
[108]	validation_0-mae:2326.52738
[109]	validation_0-mae:2321.95783
[110]	validation_0-mae:2319.70376
[111]	validation_0-mae:2316.90326
[112]	validation_0-mae:2313.63970
[113]	validation_0-mae:2310.82117
[114]	validation_0-mae:2308.53731
[115]	validation_0-mae:2303.41718
[116]	validation_0-mae:2299.87038
[117]	validation_0-mae:2296.91412
[118]	validation_0-mae:2292.33533
[119]	validation_0-mae:2290.08327
[120]	validation_0-mae:2287.82208
[121]	validation_0-mae:2284.87055
[122]	validation_0-mae:2283.40093
[123]	validation_0-mae:2278.88978
[124]	validation_0-mae:2275.77297
[125]	validation_0-mae:2273.11570
[126]	validation_0-mae:2268.26395
[127]	validation_0-mae:2263.00528
[128]	validation_0-mae:2261.67209
[129]	validation_0-mae:2258.50841
[130]	validation_0-mae:2257.07070
[131]	validation_0-mae:2254.33900
[132]	validation_0-mae:2249.68737
[133]	validation_0-mae:2248.73908
[134]	validation_0-mae:2248.78906
[135]	validation_0-mae:2244.97404
[136]	validation_0-mae:2239.89148
[137]	validation_0-mae:2239.21222
[138]	validation_0-mae:2237.49990
[139]	validation_0-mae:2236.82854
[140]	validation_0-mae:2236.44139
[141]	validation_0-mae:2236.22229
[142]	validation_0-mae:2234.62088
[143]	validation_0-mae:2232.37255
[144]	validation_0-mae:2228.79317
[145]	validation_0-mae:2228.70247
[146]	validation_0-mae:2227.86714
[147]	validation_0-mae:2226.96387
[148]	validation_0-mae:2225.25225
[149]	validation_0-mae:2223.58535
[150]	validation_0-mae:2221.16937
[151]	validation_0-mae:2219.81693
[152]	validation_0-mae:2220.28042
[153]	validation_0-mae:2218.54246
[154]	validation_0-mae:2217.86996
[155]	validation_0-mae:2217.82093
[156]	validation_0-mae:2216.24888
[157]	validation_0-mae:2216.50920
[158]	validation_0-mae:2214.45530
[159]	validation_0-mae:2213.81193
[160]	validation_0-mae:2210.35418
[161]	validation_0-mae:2208.96003
[162]	validation_0-mae:2205.17710
[163]	validation_0-mae:2204.38415
[164]	validation_0-mae:2204.03151
[165]	validation_0-mae:2204.10784
[166]	validation_0-mae:2201.55785
[167]	validation_0-mae:2200.54307
[168]	validation_0-mae:2200.11128
[169]	validation_0-mae:2198.83215
[170]	validation_0-mae:2197.41276
[171]	validation_0-mae:2194.24873
[172]	validation_0-mae:2193.19576
[173]	validation_0-mae:2190.58807
[174]	validation_0-mae:2188.58600
[175]	validation_0-mae:2184.97631
[176]	validation_0-mae:2184.91050
[177]	validation_0-mae:2184.99878
[178]	validation_0-mae:2185.58007
[179]	validation_0-mae:2183.44308
[180]	validation_0-mae:2183.47970
[181]	validation_0-mae:2182.50626
[182]	validation_0-mae:2182.80721
[183]	validation_0-mae:2179.60338
[184]	validation_0-mae:2180.59068
[185]	validation_0-mae:2176.52547
[186]	validation_0-mae:2177.58100
[187]	validation_0-mae:2176.70669
[188]	validation_0-mae:2175.78550
[189]	validation_0-mae:2176.13387
[190]	validation_0-mae:2176.80211
[191]	validation_0-mae:2175.65798
[192]	validation_0-mae:2174.26058
[193]	validation_0-mae:2173.48284
[194]	validation_0-mae:2175.30977
[195]	validation_0-mae:2173.68785
[196]	validation_0-mae:2172.42110
[197]	validation_0-mae:2170.00953
[198]	validation_0-mae:2168.84201
[199]	validation_0-mae:2169.03817
[200]	validation_0-mae:2168.31746
[201]	validation_0-mae:2167.43633
[202]	validation_0-mae:2166.03424
[203]	validation_0-mae:2164.87812
[204]	validation_0-mae:2164.09798
[205]	validation_0-mae:2162.28097
[206]	validation_0-mae:2159.01239
[207]	validation_0-mae:2158.77609
[208]	validation_0-mae:2158.44953
[209]	validation_0-mae:2157.56063
[210]	validation_0-mae:2155.12086
[211]	validation_0-mae:2155.27916
[212]	validation_0-mae:2154.48660
[213]	validation_0-mae:2153.53603
[214]	validation_0-mae:2152.79191
[215]	validation_0-mae:2150.65371
[216]	validation_0-mae:2150.73842
[217]	validation_0-mae:2150.65434
[218]	validation_0-mae:2150.63921
[219]	validation_0-mae:2150.79928
[220]	validation_0-mae:2150.15781
[221]	validation_0-mae:2150.74561
[222]	validation_0-mae:2149.73157
[223]	validation_0-mae:2148.23058
[224]	validation_0-mae:2146.22860
[225]	validation_0-mae:2145.62625
[226]	validation_0-mae:2144.69676
[227]	validation_0-mae:2145.15840
[228]	validation_0-mae:2145.51824
[229]	validation_0-mae:2145.28026
[230]	validation_0-mae:2144.27894
[231]	validation_0-mae:2143.53660
[232]	validation_0-mae:2143.94818
[233]	validation_0-mae:2143.85023
[234]	validation_0-mae:2144.34615
[235]	validation_0-mae:2143.91530
[236]	validation_0-mae:2141.65855
[237]	validation_0-mae:2140.61435
[238]	validation_0-mae:2139.15323
[239]	validation_0-mae:2139.40881
[240]	validation_0-mae:2139.40579
[241]	validation_0-mae:2138.44622
[242]	validation_0-mae:2136.09122
[243]	validation_0-mae:2135.64406
[244]	validation_0-mae:2134.56628
[245]	validation_0-mae:2134.80424
[246]	validation_0-mae:2133.40263
[247]	validation_0-mae:2133.41399
[248]	validation_0-mae:2131.34857
[249]	validation_0-mae:2131.14081
[250]	validation_0-mae:2130.69456
[251]	validation_0-mae:2131.12917
[252]	validation_0-mae:2131.26572
[253]	validation_0-mae:2130.85186
[254]	validation_0-mae:2131.27221
[255]	validation_0-mae:2131.29201
[256]	validation_0-mae:2131.42392
[257]	validation_0-mae:2131.28140
[258]	validation_0-mae:2130.06207
[259]	validation_0-mae:2129.52887
[260]	validation_0-mae:2127.34691
[261]	validation_0-mae:2127.62413
[262]	validation_0-mae:2126.26961
[263]	validation_0-mae:2126.39373
[264]	validation_0-mae:2126.14967
[265]	validation_0-mae:2126.93183
[266]	validation_0-mae:2127.39970
[267]	validation_0-mae:2127.66605
[268]	validation_0-mae:2127.21035
[269]	validation_0-mae:2125.70305
[270]	validation_0-mae:2125.49278
[271]	validation_0-mae:2125.70942
[272]	validation_0-mae:2125.27089
[273]	validation_0-mae:2125.12646
[274]	validation_0-mae:2125.33710
[275]	validation_0-mae:2125.55839
[276]	validation_0-mae:2125.12731
[277]	validation_0-mae:2124.09984
[278]	validation_0-mae:2123.50729
[279]	validation_0-mae:2122.23073
[280]	validation_0-mae:2122.30636
[281]	validation_0-mae:2122.01690
[282]	validation_0-mae:2120.78798
[283]	validation_0-mae:2120.68163
[284]	validation_0-mae:2119.89998
[285]	validation_0-mae:2119.27683
[286]	validation_0-mae:2118.63501
[287]	validation_0-mae:2118.10241
[288]	validation_0-mae:2116.24058
[289]	validation_0-mae:2115.50837
[290]	validation_0-mae:2115.75500
[291]	validation_0-mae:2115.55076
[292]	validation_0-mae:2115.14208
[293]	validation_0-mae:2115.79991
[294]	validation_0-mae:2116.79798
[295]	validation_0-mae:2116.15839
[296]	validation_0-mae:2115.25638
[297]	validation_0-mae:2116.06236
[298]	validation_0-mae:2115.12836
[299]	validation_0-mae:2114.92114
[300]	validation_0-mae:2114.07411
[301]	validation_0-mae:2113.55962
[302]	validation_0-mae:2113.54619
[303]	validation_0-mae:2112.17639
[304]	validation_0-mae:2112.16529
[305]	validation_0-mae:2111.35968
[306]	validation_0-mae:2110.70511
[307]	validation_0-mae:2110.78337
[308]	validation_0-mae:2110.44594
[309]	validation_0-mae:2109.32300
[310]	validation_0-mae:2108.77287
[311]	validation_0-mae:2108.46088
[312]	validation_0-mae:2108.52731
[313]	validation_0-mae:2108.56115
[314]	validation_0-mae:2107.11719
[315]	validation_0-mae:2106.12442
[316]	validation_0-mae:2105.26890
[317]	validation_0-mae:2105.24082
[318]	validation_0-mae:2105.26859
[319]	validation_0-mae:2105.00747
[320]	validation_0-mae:2104.24355
[321]	validation_0-mae:2103.78112
[322]	validation_0-mae:2103.50032
[323]	validation_0-mae:2102.62304
[324]	validation_0-mae:2102.55203
[325]	validation_0-mae:2102.55058
[326]	validation_0-mae:2101.48239
[327]	validation_0-mae:2100.69308
[328]	validation_0-mae:2100.55808
[329]	validation_0-mae:2100.09013
[330]	validation_0-mae:2098.99564
[331]	validation_0-mae:2098.88688
[332]	validation_0-mae:2098.93936
[333]	validation_0-mae:2098.89639
[334]	validation_0-mae:2098.34340
[335]	validation_0-mae:2098.26037
[336]	validation_0-mae:2098.03957
[337]	validation_0-mae:2097.86193
[338]	validation_0-mae:2097.93611
[339]	validation_0-mae:2096.02031
[340]	validation_0-mae:2096.24616
[341]	validation_0-mae:2096.61770
[342]	validation_0-mae:2095.21736
[343]	validation_0-mae:2092.69393
[344]	validation_0-mae:2092.58665
[345]	validation_0-mae:2092.19667
[346]	validation_0-mae:2091.92705
[347]	validation_0-mae:2091.86956
[348]	validation_0-mae:2091.66781
[349]	validation_0-mae:2091.90955
[350]	validation_0-mae:2092.05564
[351]	validation_0-mae:2091.65240
[352]	validation_0-mae:2090.69983
[353]	validation_0-mae:2090.82366
[354]	validation_0-mae:2091.03117
[355]	validation_0-mae:2090.67641
[356]	validation_0-mae:2090.31567
[357]	validation_0-mae:2090.10688
[358]	validation_0-mae:2090.62148
[359]	validation_0-mae:2090.90284
[360]	validation_0-mae:2091.05687
[361]	validation_0-mae:2091.28983
[362]	validation_0-mae:2091.84159
[363]	validation_0-mae:2091.21425
[364]	validation_0-mae:2091.12550
[365]	validation_0-mae:2090.12776
[366]	validation_0-mae:2090.75948
[367]	validation_0-mae:2091.28073
[368]	validation_0-mae:2091.62352
[369]	validation_0-mae:2092.03693
[370]	validation_0-mae:2092.00870
[371]	validation_0-mae:2091.87550
[372]	validation_0-mae:2091.52180
[373]	validation_0-mae:2089.88377
[374]	validation_0-mae:2088.42392
[375]	validation_0-mae:2088.45537
[376]	validation_0-mae:2088.76135
[377]	validation_0-mae:2089.11018
[378]	validation_0-mae:2088.92777
[379]	validation_0-mae:2088.60614
[380]	validation_0-mae:2088.82293
[381]	validation_0-mae:2088.24885
[382]	validation_0-mae:2087.71843
[383]	validation_0-mae:2087.32142
[384]	validation_0-mae:2087.00954
[385]	validation_0-mae:2086.89888
[386]	validation_0-mae:2087.03493
[387]	validation_0-mae:2087.44292
[388]	validation_0-mae:2087.15761
[389]	validation_0-mae:2086.52383
[390]	validation_0-mae:2085.37180
[391]	validation_0-mae:2085.44465
[392]	validation_0-mae:2085.42950
[393]	validation_0-mae:2085.68568
[394]	validation_0-mae:2085.93273
[395]	validation_0-mae:2085.34271
[396]	validation_0-mae:2085.26163
[397]	validation_0-mae:2084.96835
[398]	validation_0-mae:2084.77153
[399]	validation_0-mae:2084.28980
[400]	validation_0-mae:2084.16325
[401]	validation_0-mae:2084.81482
[402]	validation_0-mae:2085.10878
[403]	validation_0-mae:2084.71208
[404]	validation_0-mae:2085.14178
[405]	validation_0-mae:2084.99015
[406]	validation_0-mae:2084.80692
[407]	validation_0-mae:2084.84685
[408]	validation_0-mae:2084.61390
[409]	validation_0-mae:2084.00563
[410]	validation_0-mae:2083.07211
[411]	validation_0-mae:2082.65729
[412]	validation_0-mae:2081.77997
[413]	validation_0-mae:2080.87046
[414]	validation_0-mae:2080.62757
[415]	validation_0-mae:2080.82525
[416]	validation_0-mae:2080.48155
[417]	validation_0-mae:2079.99811
[418]	validation_0-mae:2080.14296
[419]	validation_0-mae:2080.02751
[420]	validation_0-mae:2080.24816
[421]	validation_0-mae:2079.62375
[422]	validation_0-mae:2079.39503
[423]	validation_0-mae:2079.58230
[424]	validation_0-mae:2079.67012
[425]	validation_0-mae:2079.95604
[426]	validation_0-mae:2079.99458
[427]	validation_0-mae:2079.95197
[428]	validation_0-mae:2079.91888
[429]	validation_0-mae:2079.93437
[430]	validation_0-mae:2079.97363
[431]	validation_0-mae:2080.15204
[432]	validation_0-mae:2080.16023
[433]	validation_0-mae:2080.44702
[434]	validation_0-mae:2080.14114
[435]	validation_0-mae:2080.30189
[436]	validation_0-mae:2080.24498
[437]	validation_0-mae:2080.37686
[438]	validation_0-mae:2080.54992
[439]	validation_0-mae:2080.28099
[440]	validation_0-mae:2080.52475
[441]	validation_0-mae:2080.90365
[442]	validation_0-mae:2080.61642
[443]	validation_0-mae:2080.29100
[444]	validation_0-mae:2080.48654
[445]	validation_0-mae:2080.47160
[446]	validation_0-mae:2080.33925
[447]	validation_0-mae:2079.82124
[448]	validation_0-mae:2079.58646
[449]	validation_0-mae:2078.97591
[450]	validation_0-mae:2078.62277
[451]	validation_0-mae:2078.63894
[452]	validation_0-mae:2078.62766
[453]	validation_0-mae:2078.41713
[454]	validation_0-mae:2078.47576
[455]	validation_0-mae:2078.59028
[456]	validation_0-mae:2078.51871
[457]	validation_0-mae:2078.77012
[458]	validation_0-mae:2077.73925
[459]	validation_0-mae:2077.90154
[460]	validation_0-mae:2077.97191
[461]	validation_0-mae:2077.40915
[462]	validation_0-mae:2077.46227
[463]	validation_0-mae:2076.97851
[464]	validation_0-mae:2077.28688
[465]	validation_0-mae:2077.36143
[466]	validation_0-mae:2077.29433
[467]	validation_0-mae:2077.13815
[468]	validation_0-mae:2076.96912
[469]	validation_0-mae:2076.93894
[470]	validation_0-mae:2077.01860
[471]	validation_0-mae:2076.88000
[472]	validation_0-mae:2076.79765
[473]	validation_0-mae:2076.63501
[474]	validation_0-mae:2076.67521
[475]	validation_0-mae:2076.34745
[476]	validation_0-mae:2076.31409
[477]	validation_0-mae:2076.42508
[478]	validation_0-mae:2076.57691
[479]	validation_0-mae:2075.79620
[480]	validation_0-mae:2075.72085
[481]	validation_0-mae:2076.06020
[482]	validation_0-mae:2075.68733
[483]	validation_0-mae:2076.16192
[484]	validation_0-mae:2075.83367
[485]	validation_0-mae:2075.71125
[486]	validation_0-mae:2076.02314
[487]	validation_0-mae:2075.73680
[488]	validation_0-mae:2075.64682
[489]	validation_0-mae:2075.55557
[490]	validation_0-mae:2075.50545
[491]	validation_0-mae:2075.36557
[492]	validation_0-mae:2075.15289
[493]	validation_0-mae:2075.16214
[494]	validation_0-mae:2075.70753
[495]	validation_0-mae:2075.19812
[496]	validation_0-mae:2074.97812
[497]	validation_0-mae:2074.50435
[498]	validation_0-mae:2074.84243
[499]	validation_0-mae:2074.36471
[500]	validation_0-mae:2074.58139
[501]	validation_0-mae:2074.62216
[502]	validation_0-mae:2074.85303
[503]	validation_0-mae:2074.91540
[504]	validation_0-mae:2074.83412
[505]	validation_0-mae:2075.08001
[506]	validation_0-mae:2075.17183
[507]	validation_0-mae:2075.53289
[508]	validation_0-mae:2074.57933
[509]	validation_0-mae:2074.20181
[510]	validation_0-mae:2074.37962
[511]	validation_0-mae:2074.56641
[512]	validation_0-mae:2074.64916
[513]	validation_0-mae:2074.75175
[514]	validation_0-mae:2074.85930
[515]	validation_0-mae:2074.59779
[516]	validation_0-mae:2074.11168
[517]	validation_0-mae:2074.25200
[518]	validation_0-mae:2073.83613
[519]	validation_0-mae:2073.61457
[520]	validation_0-mae:2073.40370
[521]	validation_0-mae:2073.47068
[522]	validation_0-mae:2073.21470
[523]	validation_0-mae:2073.29977
[524]	validation_0-mae:2072.91317
[525]	validation_0-mae:2073.09240
[526]	validation_0-mae:2072.78226
[527]	validation_0-mae:2072.42507
[528]	validation_0-mae:2072.66358
[529]	validation_0-mae:2072.13151
[530]	validation_0-mae:2072.35415
[531]	validation_0-mae:2072.55817
[532]	validation_0-mae:2072.03133
[533]	validation_0-mae:2072.25491
[534]	validation_0-mae:2072.18391
[535]	validation_0-mae:2072.32768
[536]	validation_0-mae:2072.74307
[537]	validation_0-mae:2072.72754
[538]	validation_0-mae:2072.60429
[539]	validation_0-mae:2072.38652
[540]	validation_0-mae:2072.52364
[541]	validation_0-mae:2072.41179
[542]	validation_0-mae:2072.52620
[543]	validation_0-mae:2072.68679
[544]	validation_0-mae:2072.79532
[545]	validation_0-mae:2072.93566
[546]	validation_0-mae:2072.76355
[547]	validation_0-mae:2072.87214
[548]	validation_0-mae:2072.80212
[549]	validation_0-mae:2072.95597
[550]	validation_0-mae:2073.01445
[551]	validation_0-mae:2072.71952
[552]	validation_0-mae:2072.96127
[553]	validation_0-mae:2072.73336
[554]	validation_0-mae:2072.71841
[555]	validation_0-mae:2072.91279
[556]	validation_0-mae:2072.44706
[557]	validation_0-mae:2072.84895
[558]	validation_0-mae:2073.29377
[559]	validation_0-mae:2073.42808
[560]	validation_0-mae:2073.62458
[561]	validation_0-mae:2073.94191
[562]	validation_0-mae:2073.01572
[563]	validation_0-mae:2072.78332
[564]	validation_0-mae:2072.61624
[565]	validation_0-mae:2072.19269
[566]	validation_0-mae:2072.11250
[567]	validation_0-mae:2072.20889
[568]	validation_0-mae:2072.15763
[569]	validation_0-mae:2072.01481
[570]	validation_0-mae:2071.88878
[571]	validation_0-mae:2071.67279
[572]	validation_0-mae:2071.41062
[573]	validation_0-mae:2071.98413
[574]	validation_0-mae:2071.69766
[575]	validation_0-mae:2071.75711
[576]	validation_0-mae:2072.05458
[577]	validation_0-mae:2071.77364
[578]	validation_0-mae:2071.80439
[579]	validation_0-mae:2071.68990
[580]	validation_0-mae:2071.83269
[581]	validation_0-mae:2071.77979
[582]	validation_0-mae:2071.57957
[583]	validation_0-mae:2071.86504
[584]	validation_0-mae:2071.56076
[585]	validation_0-mae:2071.54336
[586]	validation_0-mae:2071.62114
[587]	validation_0-mae:2071.58249
[588]	validation_0-mae:2071.64242
[589]	validation_0-mae:2071.80023
[590]	validation_0-mae:2071.76023
[591]	validation_0-mae:2071.45588
[592]	validation_0-mae:2070.93619
[593]	validation_0-mae:2070.73070
[594]	validation_0-mae:2071.02085
[595]	validation_0-mae:2071.32484
[596]	validation_0-mae:2071.09672
[597]	validation_0-mae:2071.04901
[598]	validation_0-mae:2070.79704
[599]	validation_0-mae:2070.64291
[600]	validation_0-mae:2070.69702
[601]	validation_0-mae:2069.86681
[602]	validation_0-mae:2069.29287
[603]	validation_0-mae:2069.23048
[604]	validation_0-mae:2069.05360
[605]	validation_0-mae:2069.04636
[606]	validation_0-mae:2069.25419
[607]	validation_0-mae:2069.34218
[608]	validation_0-mae:2069.56901
[609]	validation_0-mae:2069.56887
[610]	validation_0-mae:2069.56612
[611]	validation_0-mae:2069.75387
[612]	validation_0-mae:2069.56827
[613]	validation_0-mae:2069.05701
[614]	validation_0-mae:2069.68935
[615]	validation_0-mae:2069.88374
[616]	validation_0-mae:2070.08272
[617]	validation_0-mae:2070.19609
[618]	validation_0-mae:2070.40129
[619]	validation_0-mae:2070.22291
[620]	validation_0-mae:2070.29984
[621]	validation_0-mae:2070.49802

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[35]	validation_0-mae:3491.52347
[36]	validation_0-mae:3442.50080
[37]	validation_0-mae:3390.21399
[38]	validation_0-mae:3348.81720
[39]	validation_0-mae:3304.48032
[40]	validation_0-mae:3264.46129
[41]	validation_0-mae:3229.87100
[42]	validation_0-mae:3177.54154
[43]	validation_0-mae:3138.58621
[44]	validation_0-mae:3100.24175
[45]	validation_0-mae:3054.28602
[46]	validation_0-mae:3014.10880
[47]	validation_0-mae:2981.32385
[48]	validation_0-mae:2961.60749
[49]	validation_0-mae:2937.47882
[50]	validation_0-mae:2912.45102
[51]	validation_0-mae:2889.65434
[52]	validation_0-mae:2853.39343
[53]	validation_0-mae:2830.78045
[54]	validation_0-mae:2808.11869
[55]	validation_0-mae:2790.39595
[56]	validation_0-mae:2769.59701
[57]	validation_0-mae:2755.55441
[58]	validation_0-mae:2738.66736
[59]	validation_0-mae:2716.26127
[60]	validation_0-mae:2706.06121
[61]	validation_0-mae:2691.72963
[62]	validation_0-mae:2681.70879
[63]	validation_0-mae:2667.63219
[64]	validation_0-mae:2656.31099
[65]	validation_0-mae:2635.18985
[66]	validation_0-mae:2612.19503
[67]	validation_0-mae:2605.78677
[68]	validation_0-mae:2591.93398
[69]	validation_0-mae:2580.75293
[70]	validation_0-mae:2573.67338
[71]	validation_0-mae:2567.74096
[72]	validation_0-mae:2559.98792
[73]	validation_0-mae:2553.73801
[74]	validation_0-mae:2549.86095
[75]	validation_0-mae:2540.38424
[76]	validation_0-mae:2533.25878
[77]	validation_0-mae:2524.09008
[78]	validation_0-mae:2513.18217
[79]	validation_0-mae:2508.54831
[80]	validation_0-mae:2505.77148
[81]	validation_0-mae:2498.29815
[82]	validation_0-mae:2491.92582
[83]	validation_0-mae:2485.48339
[84]	validation_0-mae:2477.81211
[85]	validation_0-mae:2469.30390
[86]	validation_0-mae:2467.40033
[87]	validation_0-mae:2459.44729
[88]	validation_0-mae:2454.11615
[89]	validation_0-mae:2452.14771
[90]	validation_0-mae:2444.61705
[91]	validation_0-mae:2438.56397
[92]	validation_0-mae:2432.22726
[93]	validation_0-mae:2426.80674
[94]	validation_0-mae:2423.37054
[95]	validation_0-mae:2415.86633
[96]	validation_0-mae:2412.84499
[97]	validation_0-mae:2408.47505
[98]	validation_0-mae:2404.99727
[99]	validation_0-mae:2403.88970
[100]	validation_0-mae:2396.69361
[101]	validation_0-mae:2392.05800
[102]	validation_0-mae:2389.34932
[103]	validation_0-mae:2387.48443
[104]	validation_0-mae:2384.88111
[105]	validation_0-mae:2381.94371
[106]	validation_0-mae:2378.69723
[107]	validation_0-mae:2372.80541
[108]	validation_0-mae:2370.40301
[109]	validation_0-mae:2363.92679
[110]	validation_0-mae:2359.88131
[111]	validation_0-mae:2358.21131
[0]	validation_0-mae:12438.23938
[1]	validation_0-mae:11702.13363
[2]	validation_0-mae:11043.42900
[3]	validation_0-mae:10414.14530
[4]	validation_0-mae:9879.36132
[5]	validation_0-mae:9364.96401
[6]	validation_0-mae:8921.96716
[7]	validation_0-mae:8506.66024
[8]	validation_0-mae:8135.13810
[9]	validation_0-mae:7800.33073
[10]	validation_0-mae:7481.18159
[11]	validation_0-mae:7188.16211
[12]	validation_0-mae:6904.41730
[13]	validation_0-mae:6644.75532
[14]	validation_0-mae:6411.95305
[15]	validation_0-mae:6199.15066
[16]	validation_0-mae:5971.55525
[17]	validation_0-mae:5744.89879
[18]	validation_0-mae:5547.80834
[19]	validation_0-mae:5368.55869
[20]	validation_0-mae:5201.24909
[21]	validation_0-mae:5035.62641
[22]	validation_0-mae:4893.81107
[23]	validation_0-mae:4758.73824
[24]	validation_0-mae:4642.03180
[25]	validation_0-mae:4522.00986
[26]	validation_0-mae:4419.27041
[27]	validation_0-mae:4318.42148
[28]	validation_0-mae:4206.87769
[29]	validation_0-mae:4096.87172
[30]	validation_0-mae:4001.44933
[31]	validation_0-mae:3912.41392
[32]	validation_0-mae:3821.22526
[33]	validation_0-mae:3748.80847
[34]	validation_0-mae:3684.31021

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[35]	validation_0-mae:3615.22251
[36]	validation_0-mae:3553.25619
[37]	validation_0-mae:3495.11851
[38]	validation_0-mae:3441.68515
[39]	validation_0-mae:3391.11302
[40]	validation_0-mae:3340.91519
[41]	validation_0-mae:3298.77654
[42]	validation_0-mae:3256.07353
[43]	validation_0-mae:3217.22305
[44]	validation_0-mae:3171.86718
[45]	validation_0-mae:3120.96854
[46]	validation_0-mae:3088.87875
[47]	validation_0-mae:3057.36896
[48]	validation_0-mae:3014.52982
[49]	validation_0-mae:2992.43980
[50]	validation_0-mae:2969.16375
[51]	validation_0-mae:2938.92090
[52]	validation_0-mae:2912.18392
[53]	validation_0-mae:2887.13149
[54]	validation_0-mae:2861.02453
[55]	validation_0-mae:2843.19523
[56]	validation_0-mae:2817.43056
[57]	validation_0-mae:2799.51295
[58]	validation_0-mae:2778.75956
[59]	validation_0-mae:2761.78155
[60]	validation_0-mae:2746.02184
[61]	validation_0-mae:2727.38598
[62]	validation_0-mae:2705.30440
[63]	validation_0-mae:2687.95112
[64]	validation_0-mae:2679.65420
[65]	validation_0-mae:2659.42058
[66]	validation_0-mae:2652.04214
[67]	validation_0-mae:2639.24324
[68]	validation_0-mae:2624.21511
[69]	validation_0-mae:2610.74442
[70]	validation_0-mae:2603.28199
[71]	validation_0-mae:2595.19170
[72]	validation_0-mae:2582.13503
[73]	validation_0-mae:2564.16781
[74]	validation_0-mae:2552.79713
[75]	validation_0-mae:2544.16945
[76]	validation_0-mae:2539.93909
[77]	validation_0-mae:2526.96483
[78]	validation_0-mae:2510.61602
[79]	validation_0-mae:2505.18574
[80]	validation_0-mae:2493.53128
[81]	validation_0-mae:2487.15555
[82]	validation_0-mae:2482.78937
[83]	validation_0-mae:2473.25970
[84]	validation_0-mae:2463.93312
[85]	validation_0-mae:2453.18728
[86]	validation_0-mae:2440.45109
[87]	validation_0-mae:2434.35307
[88]	validation_0-mae:2427.09586
[89]	validation_0-mae:2420.42310
[90]	validation_0-mae:2413.69481
[91]	validation_0-mae:2405.01933
[92]	validation_0-mae:2398.04633
[93]	validation_0-mae:2394.81660
[94]	validation_0-mae:2391.28659
[95]	validation_0-mae:2383.09254
[96]	validation_0-mae:2376.14049
[97]	validation_0-mae:2368.91415
[98]	validation_0-mae:2364.35137
[99]	validation_0-mae:2362.05403
[100]	validation_0-mae:2356.86288
[101]	validation_0-mae:2346.71356
[102]	validation_0-mae:2340.42869
[103]	validation_0-mae:2329.99886
[104]	validation_0-mae:2323.81502
[105]	validation_0-mae:2320.17613
[106]	validation_0-mae:2317.53588
[107]	validation_0-mae:2316.81943
[108]	validation_0-mae:2313.79811
[109]	validation_0-mae:2309.59487
[110]	validation_0-mae:2301.85555
[111]	validation_0-mae:2298.12928
[112]	validation_0-mae:2293.70935
[113]	validation_0-mae:2289.93286
[114]	validation_0-mae:2287.70145
[115]	validation_0-mae:2282.87109
[116]	validation_0-mae:2276.54893
[117]	validation_0-mae:2272.75783
[118]	validation_0-mae:2269.49787
[119]	validation_0-mae:2262.23510
[120]	validation_0-mae:2258.73780
[121]	validation_0-mae:2256.35826
[122]	validation_0-mae:2253.93390
[123]	validation_0-mae:2251.87848
[124]	validation_0-mae:2249.26894
[125]	validation_0-mae:2244.39278
[126]	validation_0-mae:2240.78980
[127]	validation_0-mae:2237.25667
[128]	validation_0-mae:2233.33417
[129]	validation_0-mae:2231.28369
[130]	validation_0-mae:2229.83494
[131]	validation_0-mae:2226.90657
[132]	validation_0-mae:2223.92751
[133]	validation_0-mae:2222.09185
[134]	validation_0-mae:2219.69348
[135]	validation_0-mae:2216.85067
[136]	validation_0-mae:2212.38539
[137]	validation_0-mae:2211.12616
[138]	validation_0-mae:2209.19468
[139]	validation_0-mae:2208.80270
[140]	validation_0-mae:2207.08184
[141]	validation_0-mae:2205.67598
[142]	validation_0-mae:2200.61594
[143]	validation_0-mae:2200.09389
[144]	validation_0-mae:2199.24850
[145]	validation_0-mae:2194.69557
[146]	validation_0-mae:2191.81660
[147]	validation_0-mae:2189.26358
[148]	validation_0-mae:2187.69884
[149]	validation_0-mae:2183.96670
[150]	validation_0-mae:2182.89066
[151]	validation_0-mae:2181.10815
[152]	validation_0-mae:2179.11633
[153]	validation_0-mae:2178.74138
[154]	validation_0-mae:2177.57429
[155]	validation_0-mae:2178.14509
[156]	validation_0-mae:2177.47654
[157]	validation_0-mae:2174.54255
[158]	validation_0-mae:2170.46211
[159]	validation_0-mae:2170.33133
[160]	validation_0-mae:2166.92338
[161]	validation_0-mae:2167.47257
[162]	validation_0-mae:2164.65757
[163]	validation_0-mae:2164.01358
[164]	validation_0-mae:2163.98574
[165]	validation_0-mae:2162.80275
[166]	validation_0-mae:2160.26180
[167]	validation_0-mae:2159.33861
[168]	validation_0-mae:2158.94230
[169]	validation_0-mae:2157.45856
[170]	validation_0-mae:2156.86260
[171]	validation_0-mae:2157.36892
[172]	validation_0-mae:2155.65591
[173]	validation_0-mae:2152.78354
[174]	validation_0-mae:2151.78033
[175]	validation_0-mae:2149.32959
[176]	validation_0-mae:2148.87471
[177]	validation_0-mae:2145.89173
[178]	validation_0-mae:2146.46618
[179]	validation_0-mae:2145.13024
[180]	validation_0-mae:2143.07738
[181]	validation_0-mae:2142.03561
[182]	validation_0-mae:2142.36982
[183]	validation_0-mae:2141.54755
[184]	validation_0-mae:2139.70214
[185]	validation_0-mae:2138.36258
[186]	validation_0-mae:2136.32181
[187]	validation_0-mae:2133.43934
[188]	validation_0-mae:2130.19039
[189]	validation_0-mae:2128.30696
[190]	validation_0-mae:2127.80622
[191]	validation_0-mae:2126.09292
[192]	validation_0-mae:2124.65624
[193]	validation_0-mae:2123.81790
[194]	validation_0-mae:2125.66195
[195]	validation_0-mae:2125.06924
[196]	validation_0-mae:2124.94724
[197]	validation_0-mae:2124.21165
[198]	validation_0-mae:2124.26434
[199]	validation_0-mae:2124.77310
[200]	validation_0-mae:2124.70838
[201]	validation_0-mae:2125.21105
[202]	validation_0-mae:2124.20642
[203]	validation_0-mae:2123.42772
[204]	validation_0-mae:2122.39190
[205]	validation_0-mae:2122.71723
[206]	validation_0-mae:2121.77078
[207]	validation_0-mae:2121.89941
[208]	validation_0-mae:2121.17237
[209]	validation_0-mae:2119.32307
[210]	validation_0-mae:2118.42885
[211]	validation_0-mae:2119.02720
[212]	validation_0-mae:2117.23642
[213]	validation_0-mae:2116.89556
[214]	validation_0-mae:2115.61468
[215]	validation_0-mae:2114.80967
[216]	validation_0-mae:2114.34082
[217]	validation_0-mae:2114.05067
[218]	validation_0-mae:2112.26827
[219]	validation_0-mae:2113.44584
[220]	validation_0-mae:2112.73032
[221]	validation_0-mae:2112.99782
[222]	validation_0-mae:2112.49270
[223]	validation_0-mae:2112.30966
[224]	validation_0-mae:2111.40669
[225]	validation_0-mae:2112.05962
[226]	validation_0-mae:2112.79035
[227]	validation_0-mae:2113.23382
[228]	validation_0-mae:2113.54039
[229]	validation_0-mae:2112.10876
[230]	validation_0-mae:2112.29626
[231]	validation_0-mae:2112.51975
[232]	validation_0-mae:2111.45596
[233]	validation_0-mae:2108.61743
[234]	validation_0-mae:2108.10103
[235]	validation_0-mae:2106.30553
[236]	validation_0-mae:2106.46082
[237]	validation_0-mae:2104.38244
[238]	validation_0-mae:2102.63824
[239]	validation_0-mae:2102.39284
[240]	validation_0-mae:2102.25367
[241]	validation_0-mae:2100.81992
[242]	validation_0-mae:2100.72384
[243]	validation_0-mae:2100.34330
[244]	validation_0-mae:2100.29392
[245]	validation_0-mae:2099.66081
[246]	validation_0-mae:2098.96871
[247]	validation_0-mae:2098.83435
[248]	validation_0-mae:2098.90877
[249]	validation_0-mae:2098.84164
[250]	validation_0-mae:2098.46825
[251]	validation_0-mae:2097.21436
[252]	validation_0-mae:2097.62131
[253]	validation_0-mae:2096.72748
[254]	validation_0-mae:2096.96328
[255]	validation_0-mae:2096.83030
[256]	validation_0-mae:2096.47440
[257]	validation_0-mae:2095.92124
[258]	validation_0-mae:2095.73999
[259]	validation_0-mae:2095.75179
[260]	validation_0-mae:2095.37061
[261]	validation_0-mae:2094.47196
[262]	validation_0-mae:2094.62336
[263]	validation_0-mae:2094.37014
[264]	validation_0-mae:2094.50182
[265]	validation_0-mae:2095.21244
[266]	validation_0-mae:2095.06647
[267]	validation_0-mae:2094.55434
[268]	validation_0-mae:2094.45765
[269]	validation_0-mae:2094.38742
[270]	validation_0-mae:2094.20485
[271]	validation_0-mae:2094.56216
[272]	validation_0-mae:2094.38660
[273]	validation_0-mae:2094.88422
[274]	validation_0-mae:2094.49350
[275]	validation_0-mae:2094.55270
[276]	validation_0-mae:2093.23938
[277]	validation_0-mae:2093.42616
[278]	validation_0-mae:2091.89333
[279]	validation_0-mae:2091.38470
[280]	validation_0-mae:2090.94504
[281]	validation_0-mae:2089.26332
[282]	validation_0-mae:2090.50852
[283]	validation_0-mae:2091.11346
[284]	validation_0-mae:2091.68674
[285]	validation_0-mae:2091.06479
[286]	validation_0-mae:2090.72246
[287]	validation_0-mae:2090.70103
[288]	validation_0-mae:2090.98997
[289]	validation_0-mae:2090.84734
[290]	validation_0-mae:2090.97265
[291]	validation_0-mae:2090.44702
[292]	validation_0-mae:2089.92293
[293]	validation_0-mae:2088.86144
[294]	validation_0-mae:2088.78544
[295]	validation_0-mae:2088.40193
[296]	validation_0-mae:2087.65588
[297]	validation_0-mae:2086.59969
[298]	validation_0-mae:2086.12645
[299]	validation_0-mae:2086.29453
[300]	validation_0-mae:2086.47251
[301]	validation_0-mae:2086.25441
[302]	validation_0-mae:2085.02165
[303]	validation_0-mae:2084.50147
[304]	validation_0-mae:2083.93433
[305]	validation_0-mae:2083.84423
[306]	validation_0-mae:2083.30572
[307]	validation_0-mae:2082.78891
[308]	validation_0-mae:2082.38076
[309]	validation_0-mae:2081.55923
[310]	validation_0-mae:2081.98198
[311]	validation_0-mae:2081.76921
[312]	validation_0-mae:2081.32979
[313]	validation_0-mae:2081.13299
[314]	validation_0-mae:2080.59291
[315]	validation_0-mae:2080.75077
[316]	validation_0-mae:2080.26220
[317]	validation_0-mae:2079.33401
[318]	validation_0-mae:2079.39760
[319]	validation_0-mae:2080.32906
[320]	validation_0-mae:2078.75015
[321]	validation_0-mae:2078.24267
[322]	validation_0-mae:2078.16626
[323]	validation_0-mae:2078.12220
[324]	validation_0-mae:2078.82737
[325]	validation_0-mae:2078.72248
[326]	validation_0-mae:2078.45413
[327]	validation_0-mae:2078.99971
[328]	validation_0-mae:2078.83084
[329]	validation_0-mae:2077.26589
[330]	validation_0-mae:2076.59171
[331]	validation_0-mae:2076.38594
[332]	validation_0-mae:2076.13467
[333]	validation_0-mae:2077.05022
[334]	validation_0-mae:2076.84480
[335]	validation_0-mae:2076.38208
[336]	validation_0-mae:2075.27603
[337]	validation_0-mae:2075.48413
[338]	validation_0-mae:2075.43794
[339]	validation_0-mae:2075.48650
[340]	validation_0-mae:2075.44465
[341]	validation_0-mae:2075.12668
[342]	validation_0-mae:2074.15649
[343]	validation_0-mae:2074.03582
[344]	validation_0-mae:2074.33934
[345]	validation_0-mae:2074.17465
[346]	validation_0-mae:2074.33454
[347]	validation_0-mae:2074.47835
[348]	validation_0-mae:2074.45333
[349]	validation_0-mae:2074.23306
[350]	validation_0-mae:2073.14394
[351]	validation_0-mae:2072.49986
[352]	validation_0-mae:2072.38096
[353]	validation_0-mae:2071.99065
[354]	validation_0-mae:2072.03317
[355]	validation_0-mae:2070.13775
[356]	validation_0-mae:2069.80597
[357]	validation_0-mae:2069.53544
[358]	validation_0-mae:2069.33764
[359]	validation_0-mae:2069.31447
[360]	validation_0-mae:2069.35245
[361]	validation_0-mae:2069.20891
[362]	validation_0-mae:2069.67733
[363]	validation_0-mae:2069.72292
[364]	validation_0-mae:2070.47429
[365]	validation_0-mae:2070.42084
[366]	validation_0-mae:2069.43832
[367]	validation_0-mae:2069.44407
[368]	validation_0-mae:2069.94619
[369]	validation_0-mae:2068.78792
[370]	validation_0-mae:2068.43369
[371]	validation_0-mae:2068.43388
[372]	validation_0-mae:2068.78877
[373]	validation_0-mae:2069.35516
[374]	validation_0-mae:2069.32414
[375]	validation_0-mae:2069.14390
[376]	validation_0-mae:2068.76028
[377]	validation_0-mae:2069.06312
[378]	validation_0-mae:2068.99932
[379]	validation_0-mae:2069.76774
[380]	validation_0-mae:2069.65304
[381]	validation_0-mae:2069.44976
[382]	validation_0-mae:2070.29749
[383]	validation_0-mae:2070.36018
[384]	validation_0-mae:2070.07423
[385]	validation_0-mae:2067.87021
[386]	validation_0-mae:2067.75741
[387]	validation_0-mae:2067.82892
[388]	validation_0-mae:2067.81486
[389]	validation_0-mae:2067.92885
[390]	validation_0-mae:2068.54283
[391]	validation_0-mae:2068.40416
[392]	validation_0-mae:2068.38874
[393]	validation_0-mae:2068.87104
[394]	validation_0-mae:2069.59536
[395]	validation_0-mae:2069.65444
[396]	validation_0-mae:2069.65983
[397]	validation_0-mae:2070.09212
[398]	validation_0-mae:2070.11594
[399]	validation_0-mae:2069.80348
[400]	validation_0-mae:2069.92435
[401]	validation_0-mae:2069.56815
[402]	validation_0-mae:2068.39702
[403]	validation_0-mae:2068.77851
[404]	validation_0-mae:2069.53098
[405]	validation_0-mae:2070.15499
[406]	validation_0-mae:2070.64641
[407]	validation_0-mae:2070.78623
[408]	validation_0-mae:2071.00123
[409]	validation_0-mae:2071.13437
[410]	validation_0-mae:2071.27339
[411]	validation_0-mae:2071.64661
[412]	validation_0-mae:2071.56254
[413]	validation_0-mae:2071.10166
[414]	validation_0-mae:2071.41743
[415]	validation_0-mae:2071.08539
[416]	validation_0-mae:2070.58971
[417]	validation_0-mae:2071.16146
[418]	validation_0-mae:2070.70114
[419]	validation_0-mae:2070.52375
[420]	validation_0-mae:2070.50250
[421]	validation_0-mae:2070.73657
[422]	validation_0-mae:2071.12394
[423]	validation_0-mae:2071.24741
[424]	validation_0-mae:2071.11615
[425]	validation_0-mae:2071.66562
[426]	validation_0-mae:2071.63594
[427]	validation_0-mae:2070.70007
[428]	validation_0-mae:2070.63513
[429]	validation_0-mae:2070.37904
[430]	validation_0-mae:2070.71089
[431]	validation_0-mae:2070.57788
[432]	validation_0-mae:2070.90659
[433]	validation_0-mae:2071.71810
[434]	validation_0-mae:2071.52759
[435]	validation_0-mae:2071.36570
[436]	validation_0-mae:2071.96843
[437]	validation_0-mae:2072.31536
[438]	validation_0-mae:2071.88948
[439]	validation_0-mae:2071.90046
[440]	validation_0-mae:2072.43428
[441]	validation_0-mae:2072.45744
[442]	validation_0-mae:2072.75278
[443]	validation_0-mae:2072.72913
[444]	validation_0-mae:2072.81012
[445]	validation_0-mae:2072.71595
[446]	validation_0-mae:2072.84011
[447]	validation_0-mae:2073.32634
[448]	validation_0-mae:2073.27806
[449]	validation_0-mae:2073.03824
[450]	validation_0-mae:2073.64318
[451]	validation_0-mae:2073.81638
[452]	validation_0-mae:2073.13611
[453]	validation_0-mae:2072.84407
[454]	validation_0-mae:2073.15726
[455]	validation_0-mae:2072.85976
[456]	validation_0-mae:2071.99974
[457]	validation_0-mae:2071.50684
[458]	validation_0-mae:2071.83421
[459]	validation_0-mae:2071.78871
[460]	validation_0-mae:2072.31611
[461]	validation_0-mae:2072.83777
[462]	validation_0-mae:2073.08732
[463]	validation_0-mae:2073.18816
[464]	validation_0-mae:2072.49643
[465]	validation_0-mae:2073.33141
[466]	validation_0-mae:2073.29288
[467]	validation_0-mae:2072.17188
[468]	validation_0-mae:2072.41146
[469]	validation_0-mae:2072.55566
[470]	validation_0-mae:2072.65624
[471]	validation_0-mae:2072.67225
[472]	validation_0-mae:2072.36679
[473]	validation_0-mae:2072.37559
[474]	validation_0-mae:2072.18321
[475]	validation_0-mae:2072.02453
[476]	validation_0-mae:2072.20509
[477]	validation_0-mae:2071.74480
[478]	validation_0-mae:2071.68992
[479]	validation_0-mae:2071.83594
[480]	validation_0-mae:2071.84550
[481]	validation_0-mae:2071.79216
[482]	validation_0-mae:2071.41219
[483]	validation_0-mae:2070.44231
[484]	validation_0-mae:2070.42186
[485]	validation_0-mae:2070.27073
[486]	validation_0-mae:2070.11846
[487]	validation_0-mae:2070.44659
[488]	validation_0-mae:2070.71735
[489]	validation_0-mae:2070.60651
[490]	validation_0-mae:2070.61209
[491]	validation_0-mae:2069.88429
[492]	validation_0-mae:2070.23435
[493]	validation_0-mae:2070.51622
[494]	validation_0-mae:2070.26839
[495]	validation_0-mae:2070.16886
[496]	validation_0-mae:2070.13287
[497]	validation_0-mae:2070.37336
[498]	validation_0-mae:2069.99063
[499]	validation_0-mae:2070.02038
[500]	validation_0-mae:2070.25026
[501]	validation_0-mae:2070.44118
[502]	validation_0-mae:2070.51775
[503]	validation_0-mae:2070.90184
[504]	validation_0-mae:2070.95372
[505]	validation_0-mae:2071.11693
[506]	validation_0-mae:2071.19854
[507]	validation_0-mae:2071.04584
[508]	validation_0-mae:2070.50247
[509]	validation_0-mae:2070.16684
[510]	validation_0-mae:2069.89087
[511]	validation_0-mae:2069.34293
[512]	validation_0-mae:2069.03395
[513]	validation_0-mae:2068.83109
[514]	validation_0-mae:2066.99570
[515]	validation_0-mae:2066.04442
[516]	validation_0-mae:2065.23876
[517]	validation_0-mae:2065.09647
[518]	validation_0-mae:2064.75303
[519]	validation_0-mae:2064.72531
[520]	validation_0-mae:2064.67856
[521]	validation_0-mae:2064.22314
[522]	validation_0-mae:2063.93390
[523]	validation_0-mae:2063.64975
[524]	validation_0-mae:2062.94452
[525]	validation_0-mae:2062.97613
[526]	validation_0-mae:2062.88413
[527]	validation_0-mae:2063.04719
[528]	validation_0-mae:2062.84741
[529]	validation_0-mae:2062.72022
[530]	validation_0-mae:2062.85636
[531]	validation_0-mae:2062.58797
[532]	validation_0-mae:2062.85174
[533]	validation_0-mae:2062.81962
[534]	validation_0-mae:2062.88839
[535]	validation_0-mae:2062.80978
[536]	validation_0-mae:2062.98866
[537]	validation_0-mae:2063.07091
[538]	validation_0-mae:2063.31746
[539]	validation_0-mae:2063.44071
[540]	validation_0-mae:2062.48442
[541]	validation_0-mae:2062.51632
[542]	validation_0-mae:2062.52302
[543]	validation_0-mae:2062.70658
[544]	validation_0-mae:2062.25139
[545]	validation_0-mae:2062.44764
[546]	validation_0-mae:2062.88729
[547]	validation_0-mae:2062.98835
[548]	validation_0-mae:2063.27970
[549]	validation_0-mae:2063.45323
[550]	validation_0-mae:2062.98181
[551]	validation_0-mae:2063.51673
[552]	validation_0-mae:2063.74680
[553]	validation_0-mae:2063.93198
[554]	validation_0-mae:2063.96332
[555]	validation_0-mae:2064.26543
[556]	validation_0-mae:2063.81218
[557]	validation_0-mae:2064.09494
[558]	validation_0-mae:2064.10300
[559]	validation_0-mae:2064.11037
[560]	validation_0-mae:2064.07533
[561]	validation_0-mae:2064.08245
[562]	validation_0-mae:2064.32547
[563]	validation_0-mae:2064.36876
[564]	validation_0-mae:2064.37169
[565]	validation_0-mae:2064.30308
[566]	validation_0-mae:2063.80150
[567]	validation_0-mae:2063.91899
[568]	validation_0-mae:2063.85935
[569]	validation_0-mae:2063.73645
[570]	validation_0-mae:2063.64913
[571]	validation_0-mae:2063.70192
[572]	validation_0-mae:2063.39340
[573]	validation_0-mae:2063.15942
[574]	validation_0-mae:2063.46824
[575]	validation_0-mae:2063.34870
[576]	validation_0-mae:2063.89856
[577]	validation_0-mae:2063.84809
[578]	validation_0-mae:2063.95146
[579]	validation_0-mae:2063.65538
[580]	validation_0-mae:2063.90940
[581]	validation_0-mae:2063.99788
[582]	validation_0-mae:2063.89367
[583]	validation_0-mae:2064.02337
[584]	validation_0-mae:2064.21798
[585]	validation_0-mae:2064.20672
[586]	validation_0-mae:2064.32170
[587]	validation_0-mae:2064.23836
[588]	validation_0-mae:2063.57180
[589]	validation_0-mae:2063.38215
[590]	validation_0-mae:2063.15964
[591]	validation_0-mae:2063.08413
[592]	validation_0-mae:2062.95960
[593]	validation_0-mae:2062.80340
[594]	validation_0-mae:2062.88904
[595]	validation_0-mae:2062.66377
[596]	validation_0-mae:2062.53281
[597]	validation_0-mae:2062.01462
[598]	validation_0-mae:2061.98959
[599]	validation_0-mae:2062.09631
[600]	validation_0-mae:2062.24999
[601]	validation_0-mae:2061.88895
[602]	validation_0-mae:2061.75436
[603]	validation_0-mae:2061.85766
[604]	validation_0-mae:2062.08915
[605]	validation_0-mae:2061.92155
[606]	validation_0-mae:2062.28274
[607]	validation_0-mae:2061.76629
[608]	validation_0-mae:2061.36394
[609]	validation_0-mae:2061.22403
[610]	validation_0-mae:2061.36446
[611]	validation_0-mae:2061.38608
[612]	validation_0-mae:2061.50943
[613]	validation_0-mae:2061.53198
[614]	validation_0-mae:2061.66029
[615]	validation_0-mae:2061.33534
[616]	validation_0-mae:2061.12643
[617]	validation_0-mae:2061.40748
[618]	validation_0-mae:2061.08504
[619]	validation_0-mae:2061.11091
[620]	validation_0-mae:2061.01679
[621]	validation_0-mae:2060.42045
[622]	validation_0-mae:2060.30768
[623]	validation_0-mae:2060.25049
[624]	validation_0-mae:2059.78618

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[37]	validation_0-mae:3492.68627
[38]	validation_0-mae:3440.03061
[39]	validation_0-mae:3392.12807
[40]	validation_0-mae:3343.38889
[41]	validation_0-mae:3304.51757
[42]	validation_0-mae:3263.78736
[43]	validation_0-mae:3222.22521
[44]	validation_0-mae:3192.05798
[45]	validation_0-mae:3159.93757
[46]	validation_0-mae:3127.93521
[47]	validation_0-mae:3090.59089
[48]	validation_0-mae:3064.21498
[49]	validation_0-mae:3039.57365
[50]	validation_0-mae:3000.98660
[51]	validation_0-mae:2976.05228
[52]	validation_0-mae:2956.55635
[53]	validation_0-mae:2935.99364
[54]	validation_0-mae:2910.09013
[55]	validation_0-mae:2892.57861
[56]	validation_0-mae:2876.43425
[0]	validation_0-mae:12532.62975
[1]	validation_0-mae:11878.98738
[2]	validation_0-mae:11314.39964
[3]	validation_0-mae:10840.81834
[4]	validation_0-mae:10426.64305
[5]	validation_0-mae:10086.15032
[6]	validation_0-mae:9777.14539
[7]	validation_0-mae:9515.15177
[8]	validation_0-mae:9299.99006
[9]	validation_0-mae:9110.75885
[10]	validation_0-mae:8959.53123

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[0]	validation_0-mae:12454.00530
[1]	validation_0-mae:11725.52789
[2]	validation_0-mae:11072.86815
[3]	validation_0-mae:10445.47354
[4]	validation_0-mae:9898.70015
[5]	validation_0-mae:9392.43903
[6]	validation_0-mae:8938.59460
[7]	validation_0-mae:8525.74496
[8]	validation_0-mae:8150.51039
[9]	validation_0-mae:7820.26953
[10]	validation_0-mae:7505.56084
[11]	validation_0-mae:7209.91071
[12]	validation_0-mae:6940.46458
[13]	validation_0-mae:6669.74810
[14]	validation_0-mae:6424.20909
[15]	validation_0-mae:6200.56473
[16]	validation_0-mae:5972.41094
[17]	validation_0-mae:5767.88838
[18]	validation_0-mae:5592.88874
[19]	validation_0-mae:5402.92546
[20]	validation_0-mae:5232.93645
[21]	validation_0-mae:5088.69966
[22]	validation_0-mae:4938.37105
[23]	validation_0-mae:4804.41221
[24]	validation_0-mae:4666.93188
[25]	validation_0-mae:4573.47115
[26]	validation_0-mae:4460.02426
[27]	validation_0-mae:4349.08691
[28]	validation_0-mae:4255.25431
[29]	validation_0-mae:4152.16903
[30]	validation_0-mae:4077.53696
[31]	validation_0-mae:3986.52692
[32]	validation_0-mae:3898.02551
[33]	validation_0-mae:3812.54994
[34]	validation_0-mae:3734.96530
[35]	validation_0-mae:3667.44535
[36]	validation_0-mae:3604.55379
[37]	validation_0-mae:3541.54779
[38]	validation_0-mae:3481.68174
[39]	validation_0-mae:3436.30516
[40]	validation_0-mae:3381.89978
[41]	validation_0-mae:3344.76525
[42]	validation_0-mae:3300.36093
[43]	validation_0-mae:3263.00378
[44]	validation_0-mae:3223.16711
[45]	validation_0-mae:3192.25257
[46]	validation_0-mae:3145.75338
[47]	validation_0-mae:3113.19271
[48]	validation_0-mae:3078.24661
[49]	validation_0-mae:3054.07208
[50]	validation_0-mae:3011.27863
[51]	validation_0-mae:2987.84354
[52]	validation_0-mae:2953.02140
[53]	validation_0-mae:2927.59573
[54]	validation_0-mae:2909.26967
[55]	validation_0-mae:2882.50199
[56]	validation_0-mae:2857.66181
[57]	validation_0-mae:2840.84052
[58]	validation_0-mae:2827.75169
[59]	validation_0-mae:2804.98523
[60]	validation_0-mae:2788.33135
[61]	validation_0-mae:2768.81698
[62]	validation_0-mae:2754.22844
[63]	validation_0-mae:2732.86527
[64]	validation_0-mae:2721.64948
[65]	validation_0-mae:2706.29380
[66]	validation_0-mae:2695.14836
[67]	validation_0-mae:2682.57243
[68]	validation_0-mae:2671.70490
[69]	validation_0-mae:2660.02455
[70]	validation_0-mae:2646.40529
[71]	validation_0-mae:2638.19567
[72]	validation_0-mae:2619.74407
[73]	validation_0-mae:2603.13274
[74]	validation_0-mae:2596.43294
[75]	validation_0-mae:2584.93879
[76]	validation_0-mae:2579.21370
[77]	validation_0-mae:2564.01369
[78]	validation_0-mae:2553.85801
[79]	validation_0-mae:2544.93757
[80]	validation_0-mae:2539.27783
[81]	validation_0-mae:2527.50091
[82]	validation_0-mae:2519.30428
[83]	validation_0-mae:2508.40711
[84]	validation_0-mae:2501.37630
[85]	validation_0-mae:2495.23419
[86]	validation_0-mae:2489.94617
[87]	validation_0-mae:2480.37876
[88]	validation_0-mae:2469.80692
[89]	validation_0-mae:2467.77720
[90]	validation_0-mae:2459.92931
[91]	validation_0-mae:2453.29344
[92]	validation_0-mae:2447.02364
[93]	validation_0-mae:2437.14893
[94]	validation_0-mae:2432.81019
[95]	validation_0-mae:2425.57934
[96]	validation_0-mae:2421.50368
[97]	validation_0-mae:2411.97544
[98]	validation_0-mae:2407.65740
[99]	validation_0-mae:2402.94230
[100]	validation_0-mae:2400.09594
[101]	validation_0-mae:2395.60694
[102]	validation_0-mae:2391.43094
[103]	validation_0-mae:2385.14473
[104]	validation_0-mae:2380.27581
[105]	validation_0-mae:2370.98869
[106]	validation_0-mae:2369.34857
[107]	validation_0-mae:2364.02924
[108]	validation_0-mae:2358.18066
[109]	validation_0-mae:2354.53012
[110]	validation_0-mae:2349.62077
[111]	validation_0-mae:2344.86954
[112]	validation_0-mae:2342.12321
[113]	validation_0-mae:2340.22171
[114]	validation_0-mae:2334.16918
[115]	validation_0-mae:2328.60006
[116]	validation_0-mae:2325.42179
[117]	validation_0-mae:2323.29967
[118]	validation_0-mae:2320.50512
[119]	validation_0-mae:2316.15830
[120]	validation_0-mae:2310.27292
[121]	validation_0-mae:2309.91085
[122]	validation_0-mae:2308.00126
[123]	validation_0-mae:2305.45148
[124]	validation_0-mae:2298.81564
[125]	validation_0-mae:2297.44069
[126]	validation_0-mae:2292.58676
[127]	validation_0-mae:2291.82171
[128]	validation_0-mae:2289.14002
[129]	validation_0-mae:2286.95742
[130]	validation_0-mae:2286.54703
[131]	validation_0-mae:2283.77235
[132]	validation_0-mae:2281.63547
[133]	validation_0-mae:2278.31141
[134]	validation_0-mae:2277.37866
[135]	validation_0-mae:2275.35141
[136]	validation_0-mae:2274.85172
[137]	validation_0-mae:2271.87961
[138]	validation_0-mae:2264.71418
[139]	validation_0-mae:2260.71205
[140]	validation_0-mae:2260.09735
[141]	validation_0-mae:2259.13981
[142]	validation_0-mae:2257.31460
[143]	validation_0-mae:2257.55910
[144]	validation_0-mae:2253.53315
[145]	validation_0-mae:2254.72907
[146]	validation_0-mae:2252.65109
[147]	validation_0-mae:2246.56479
[148]	validation_0-mae:2245.89564
[149]	validation_0-mae:2243.97933
[150]	validation_0-mae:2243.62616
[151]	validation_0-mae:2241.79080
[152]	validation_0-mae:2236.89564
[153]	validation_0-mae:2237.00260
[154]	validation_0-mae:2236.22460
[155]	validation_0-mae:2235.53128
[156]	validation_0-mae:2231.68301
[157]	validation_0-mae:2230.44386
[158]	validation_0-mae:2229.66789
[159]	validation_0-mae:2227.44976
[160]	validation_0-mae:2226.88796
[161]	validation_0-mae:2223.37487
[162]	validation_0-mae:2221.04838
[163]	validation_0-mae:2220.13281
[164]	validation_0-mae:2218.58467
[165]	validation_0-mae:2215.27035
[166]	validation_0-mae:2213.91813
[167]	validation_0-mae:2211.75724
[168]	validation_0-mae:2209.99002
[169]	validation_0-mae:2206.75096
[170]	validation_0-mae:2206.86361
[171]	validation_0-mae:2205.37668
[172]	validation_0-mae:2204.24077
[173]	validation_0-mae:2204.39124
[174]	validation_0-mae:2203.86534
[175]	validation_0-mae:2201.07361
[176]	validation_0-mae:2198.15635
[177]	validation_0-mae:2195.43067
[178]	validation_0-mae:2194.54097
[179]	validation_0-mae:2191.35364
[180]	validation_0-mae:2190.08520
[181]	validation_0-mae:2190.24872
[182]	validation_0-mae:2187.99647
[183]	validation_0-mae:2186.73112
[184]	validation_0-mae:2184.79258
[185]	validation_0-mae:2183.15811
[186]	validation_0-mae:2180.28819
[187]	validation_0-mae:2179.57105
[188]	validation_0-mae:2179.06505
[189]	validation_0-mae:2176.01844
[190]	validation_0-mae:2176.41059
[191]	validation_0-mae:2176.56204
[192]	validation_0-mae:2174.90532
[193]	validation_0-mae:2173.67705
[194]	validation_0-mae:2172.55326
[195]	validation_0-mae:2171.45657
[196]	validation_0-mae:2171.36965
[197]	validation_0-mae:2169.89322
[198]	validation_0-mae:2168.71908
[199]	validation_0-mae:2166.62636
[200]	validation_0-mae:2164.84866
[201]	validation_0-mae:2162.33519
[202]	validation_0-mae:2162.21604
[203]	validation_0-mae:2160.43730
[204]	validation_0-mae:2159.61407
[205]	validation_0-mae:2158.24527
[206]	validation_0-mae:2158.25948
[207]	validation_0-mae:2158.73666
[208]	validation_0-mae:2159.13981
[209]	validation_0-mae:2159.80679
[210]	validation_0-mae:2158.92864
[211]	validation_0-mae:2159.64086
[212]	validation_0-mae:2160.34340
[213]	validation_0-mae:2159.96954
[214]	validation_0-mae:2158.52526
[215]	validation_0-mae:2158.30354
[216]	validation_0-mae:2157.16649
[217]	validation_0-mae:2157.72510
[218]	validation_0-mae:2157.86989
[219]	validation_0-mae:2158.62045
[220]	validation_0-mae:2157.92890
[221]	validation_0-mae:2159.09209
[222]	validation_0-mae:2159.66485
[223]	validation_0-mae:2159.59761
[224]	validation_0-mae:2159.69035
[225]	validation_0-mae:2159.20137
[226]	validation_0-mae:2157.27620
[227]	validation_0-mae:2157.19415
[228]	validation_0-mae:2156.95128
[229]	validation_0-mae:2158.36868
[230]	validation_0-mae:2157.81724
[231]	validation_0-mae:2156.65837
[232]	validation_0-mae:2154.55324
[233]	validation_0-mae:2152.66807
[234]	validation_0-mae:2153.59258
[235]	validation_0-mae:2152.02046
[236]	validation_0-mae:2153.13538
[237]	validation_0-mae:2152.44126
[238]	validation_0-mae:2152.48602
[239]	validation_0-mae:2150.92593
[240]	validation_0-mae:2151.16416
[241]	validation_0-mae:2150.71749
[242]	validation_0-mae:2149.71161
[243]	validation_0-mae:2149.88602
[244]	validation_0-mae:2149.02562
[245]	validation_0-mae:2149.62706
[246]	validation_0-mae:2148.30111
[247]	validation_0-mae:2148.14680
[248]	validation_0-mae:2148.30694
[249]	validation_0-mae:2147.33000
[250]	validation_0-mae:2147.24989
[251]	validation_0-mae:2146.67464
[252]	validation_0-mae:2146.45406
[253]	validation_0-mae:2146.59582
[254]	validation_0-mae:2147.09299
[255]	validation_0-mae:2146.25649
[256]	validation_0-mae:2144.45597
[257]	validation_0-mae:2144.42713
[258]	validation_0-mae:2143.48871
[259]	validation_0-mae:2144.13270
[260]	validation_0-mae:2145.19576
[261]	validation_0-mae:2145.52659
[262]	validation_0-mae:2144.79002
[263]	validation_0-mae:2143.08711
[264]	validation_0-mae:2142.25624
[265]	validation_0-mae:2142.24915
[266]	validation_0-mae:2141.21507
[267]	validation_0-mae:2140.85937
[268]	validation_0-mae:2140.34479
[269]	validation_0-mae:2139.61452
[270]	validation_0-mae:2139.01522
[271]	validation_0-mae:2138.73815
[272]	validation_0-mae:2139.65851
[273]	validation_0-mae:2140.55139
[274]	validation_0-mae:2140.21284
[275]	validation_0-mae:2139.81627
[276]	validation_0-mae:2139.59094
[277]	validation_0-mae:2139.71738
[278]	validation_0-mae:2140.55317
[279]	validation_0-mae:2140.87751
[280]	validation_0-mae:2140.46266
[281]	validation_0-mae:2140.31672
[282]	validation_0-mae:2140.66502
[283]	validation_0-mae:2140.29630
[284]	validation_0-mae:2137.84599
[285]	validation_0-mae:2137.43773
[286]	validation_0-mae:2138.00278
[287]	validation_0-mae:2136.35115
[288]	validation_0-mae:2136.04914
[289]	validation_0-mae:2136.51238
[290]	validation_0-mae:2135.98783
[291]	validation_0-mae:2136.22603
[292]	validation_0-mae:2136.35480
[293]	validation_0-mae:2135.80302
[294]	validation_0-mae:2135.56359
[295]	validation_0-mae:2134.21691
[296]	validation_0-mae:2132.79541
[297]	validation_0-mae:2132.82352
[298]	validation_0-mae:2132.48396
[299]	validation_0-mae:2133.25013
[300]	validation_0-mae:2132.63087
[301]	validation_0-mae:2132.04732
[302]	validation_0-mae:2131.55344
[303]	validation_0-mae:2132.55187
[304]	validation_0-mae:2132.61933
[305]	validation_0-mae:2131.69820
[306]	validation_0-mae:2131.69312
[307]	validation_0-mae:2131.48107
[308]	validation_0-mae:2131.20844
[309]	validation_0-mae:2131.17398
[310]	validation_0-mae:2130.51391
[311]	validation_0-mae:2130.94917
[312]	validation_0-mae:2131.54354
[313]	validation_0-mae:2132.12537
[314]	validation_0-mae:2131.27519
[315]	validation_0-mae:2131.50458
[316]	validation_0-mae:2130.84952
[317]	validation_0-mae:2130.19943
[318]	validation_0-mae:2130.85354
[319]	validation_0-mae:2130.19990
[320]	validation_0-mae:2129.60641
[321]	validation_0-mae:2129.52274
[322]	validation_0-mae:2129.50251
[323]	validation_0-mae:2129.48594
[324]	validation_0-mae:2128.84935
[325]	validation_0-mae:2129.16030
[326]	validation_0-mae:2129.20762
[327]	validation_0-mae:2129.33152
[328]	validation_0-mae:2129.04665
[329]	validation_0-mae:2128.75814
[330]	validation_0-mae:2128.58501
[331]	validation_0-mae:2129.06733
[332]	validation_0-mae:2127.82089
[333]	validation_0-mae:2127.08089
[334]	validation_0-mae:2126.76310
[335]	validation_0-mae:2126.64929
[336]	validation_0-mae:2126.56029
[337]	validation_0-mae:2126.29801
[338]	validation_0-mae:2125.59722
[339]	validation_0-mae:2125.61858
[340]	validation_0-mae:2125.36032
[341]	validation_0-mae:2125.02904
[342]	validation_0-mae:2124.69492
[343]	validation_0-mae:2124.75907
[344]	validation_0-mae:2124.89670
[345]	validation_0-mae:2125.37122
[346]	validation_0-mae:2125.26800
[347]	validation_0-mae:2124.66528
[348]	validation_0-mae:2124.39486
[349]	validation_0-mae:2124.74101
[350]	validation_0-mae:2124.12117
[351]	validation_0-mae:2124.63554
[352]	validation_0-mae:2123.92548
[353]	validation_0-mae:2124.06455
[354]	validation_0-mae:2123.05639
[355]	validation_0-mae:2121.26200
[356]	validation_0-mae:2121.22464
[357]	validation_0-mae:2120.25462
[358]	validation_0-mae:2119.99046
[359]	validation_0-mae:2119.96373
[360]	validation_0-mae:2119.71230
[361]	validation_0-mae:2119.87369
[362]	validation_0-mae:2119.70322
[363]	validation_0-mae:2118.53285
[364]	validation_0-mae:2118.91738
[365]	validation_0-mae:2118.39357
[366]	validation_0-mae:2118.18745
[367]	validation_0-mae:2117.93584
[368]	validation_0-mae:2117.12225
[369]	validation_0-mae:2117.06392
[370]	validation_0-mae:2117.90605
[371]	validation_0-mae:2117.80892
[372]	validation_0-mae:2118.14892
[373]	validation_0-mae:2118.10432
[374]	validation_0-mae:2117.09304
[375]	validation_0-mae:2116.91936
[376]	validation_0-mae:2117.49769
[377]	validation_0-mae:2117.40187
[378]	validation_0-mae:2117.07679
[379]	validation_0-mae:2117.20587
[380]	validation_0-mae:2117.73423
[381]	validation_0-mae:2118.20325
[382]	validation_0-mae:2117.48608
[383]	validation_0-mae:2116.11087
[384]	validation_0-mae:2115.83946
[385]	validation_0-mae:2115.70633
[386]	validation_0-mae:2115.56107
[387]	validation_0-mae:2114.38545
[388]	validation_0-mae:2114.84066
[389]	validation_0-mae:2112.64964
[390]	validation_0-mae:2112.77689
[391]	validation_0-mae:2112.93516
[392]	validation_0-mae:2112.75221
[393]	validation_0-mae:2112.89006
[394]	validation_0-mae:2113.06531
[395]	validation_0-mae:2112.44638
[396]	validation_0-mae:2113.05672
[397]	validation_0-mae:2112.49100
[398]	validation_0-mae:2112.92023
[399]	validation_0-mae:2112.92121
[400]	validation_0-mae:2112.42995
[401]	validation_0-mae:2112.26705
[402]	validation_0-mae:2112.73714
[403]	validation_0-mae:2112.10320
[404]	validation_0-mae:2111.62387
[405]	validation_0-mae:2111.67547
[406]	validation_0-mae:2111.30170
[407]	validation_0-mae:2111.15549
[408]	validation_0-mae:2111.46648
[409]	validation_0-mae:2111.45843
[410]	validation_0-mae:2111.52868
[411]	validation_0-mae:2111.20901
[412]	validation_0-mae:2110.99192
[413]	validation_0-mae:2111.32208
[414]	validation_0-mae:2111.07539
[415]	validation_0-mae:2110.01027
[416]	validation_0-mae:2109.76069
[417]	validation_0-mae:2110.34356
[418]	validation_0-mae:2110.47582
[419]	validation_0-mae:2110.78830
[420]	validation_0-mae:2110.93788
[421]	validation_0-mae:2110.64773
[422]	validation_0-mae:2110.83991
[423]	validation_0-mae:2111.27081
[424]	validation_0-mae:2111.23992
[425]	validation_0-mae:2110.97797
[426]	validation_0-mae:2110.52727
[427]	validation_0-mae:2110.59696
[428]	validation_0-mae:2110.56026
[429]	validation_0-mae:2110.26736
[430]	validation_0-mae:2110.37656
[431]	validation_0-mae:2110.20725
[432]	validation_0-mae:2110.28006
[433]	validation_0-mae:2109.52130
[434]	validation_0-mae:2109.53183
[435]	validation_0-mae:2109.78308
[436]	validation_0-mae:2109.35649
[437]	validation_0-mae:2108.46335
[438]	validation_0-mae:2107.88376
[439]	validation_0-mae:2107.91831
[440]	validation_0-mae:2108.06046
[441]	validation_0-mae:2108.12275
[442]	validation_0-mae:2107.45364
[443]	validation_0-mae:2107.62749
[444]	validation_0-mae:2107.59178
[445]	validation_0-mae:2106.84670
[446]	validation_0-mae:2106.43453
[447]	validation_0-mae:2106.38750
[448]	validation_0-mae:2106.67819
[449]	validation_0-mae:2106.34546
[450]	validation_0-mae:2106.38076
[451]	validation_0-mae:2106.13567
[452]	validation_0-mae:2105.27151
[453]	validation_0-mae:2104.95507
[454]	validation_0-mae:2104.85343
[455]	validation_0-mae:2105.35447
[456]	validation_0-mae:2105.25467
[457]	validation_0-mae:2104.64870
[458]	validation_0-mae:2104.95354
[459]	validation_0-mae:2105.50297
[460]	validation_0-mae:2105.41064
[461]	validation_0-mae:2105.65582
[462]	validation_0-mae:2105.95877
[463]	validation_0-mae:2105.07818
[464]	validation_0-mae:2104.75728
[465]	validation_0-mae:2104.96642
[466]	validation_0-mae:2104.74081
[467]	validation_0-mae:2105.03902
[468]	validation_0-mae:2104.95329
[469]	validation_0-mae:2104.73111
[470]	validation_0-mae:2105.15228
[471]	validation_0-mae:2105.36372
[472]	validation_0-mae:2105.19947
[473]	validation_0-mae:2105.44638
[474]	validation_0-mae:2105.46592
[475]	validation_0-mae:2105.15522
[476]	validation_0-mae:2105.08441
[477]	validation_0-mae:2105.10902
[478]	validation_0-mae:2105.29030
[479]	validation_0-mae:2105.06518
[480]	validation_0-mae:2105.22752
[481]	validation_0-mae:2105.33645
[482]	validation_0-mae:2104.83220
[483]	validation_0-mae:2104.73715
[484]	validation_0-mae:2104.53603
[485]	validation_0-mae:2104.43857
[486]	validation_0-mae:2104.48929
[487]	validation_0-mae:2104.58419
[488]	validation_0-mae:2104.65135
[489]	validation_0-mae:2104.35441
[490]	validation_0-mae:2104.12219
[491]	validation_0-mae:2104.38259
[492]	validation_0-mae:2104.06032
[493]	validation_0-mae:2103.65115
[494]	validation_0-mae:2103.66768
[495]	validation_0-mae:2103.85399
[496]	validation_0-mae:2103.72442
[497]	validation_0-mae:2103.87656
[498]	validation_0-mae:2103.99442
[499]	validation_0-mae:2103.87877
[500]	validation_0-mae:2103.60180
[501]	validation_0-mae:2103.08110
[502]	validation_0-mae:2102.82584
[503]	validation_0-mae:2103.00673
[504]	validation_0-mae:2102.94460
[505]	validation_0-mae:2102.66335
[506]	validation_0-mae:2102.93279
[507]	validation_0-mae:2103.29096
[508]	validation_0-mae:2103.11216
[509]	validation_0-mae:2103.01534
[510]	validation_0-mae:2103.43172
[511]	validation_0-mae:2103.57847
[512]	validation_0-mae:2103.19600
[513]	validation_0-mae:2103.07656
[514]	validation_0-mae:2103.52255
[515]	validation_0-mae:2103.17965
[516]	validation_0-mae:2102.74775
[517]	validation_0-mae:2102.52556
[518]	validation_0-mae:2102.46702
[519]	validation_0-mae:2102.58026
[520]	validation_0-mae:2102.71163
[521]	validation_0-mae:2102.47407
[522]	validation_0-mae:2102.37052
[523]	validation_0-mae:2102.79248
[524]	validation_0-mae:2102.91630
[525]	validation_0-mae:2102.51321
[526]	validation_0-mae:2102.39513
[527]	validation_0-mae:2102.40587
[528]	validation_0-mae:2101.59552
[529]	validation_0-mae:2101.92891
[530]	validation_0-mae:2102.19665
[531]	validation_0-mae:2102.23472
[532]	validation_0-mae:2101.87095
[533]	validation_0-mae:2102.20470
[534]	validation_0-mae:2102.37139
[535]	validation_0-mae:2102.52477
[536]	validation_0-mae:2102.54815
[537]	validation_0-mae:2102.58049
[538]	validation_0-mae:2102.88730
[539]	validation_0-mae:2102.79423
[540]	validation_0-mae:2103.04911
[541]	validation_0-mae:2103.48118
[542]	validation_0-mae:2103.23406
[543]	validation_0-mae:2103.17462
[544]	validation_0-mae:2103.47279
[545]	validation_0-mae:2103.21634
[546]	validation_0-mae:2102.96947
[547]	validation_0-mae:2103.39170
[548]	validation_0-mae:2103.21689
[549]	validation_0-mae:2102.63143
[550]	validation_0-mae:2102.27842
[551]	validation_0-mae:2102.10052
[552]	validation_0-mae:2101.96202
[553]	validation_0-mae:2101.88695
[554]	validation_0-mae:2101.43947
[555]	validation_0-mae:2101.63631
[556]	validation_0-mae:2101.76354
[557]	validation_0-mae:2102.06147
[558]	validation_0-mae:2102.26877
[559]	validation_0-mae:2102.41082
[560]	validation_0-mae:2102.64936
[561]	validation_0-mae:2102.50842
[562]	validation_0-mae:2102.50374
[563]	validation_0-mae:2102.65838
[564]	validation_0-mae:2102.87232
[565]	validation_0-mae:2102.84110
[566]	validation_0-mae:2102.69538
[567]	validation_0-mae:2102.38617
[568]	validation_0-mae:2102.33438
[569]	validation_0-mae:2102.66791
[570]	validation_0-mae:2102.67465
[571]	validation_0-mae:2102.50409
[572]	validation_0-mae:2102.13493
[573]	validation_0-mae:2101.94222
[574]	validation_0-mae:2101.82695
[575]	validation_0-mae:2101.63644
[576]	validation_0-mae:2101.74043
[577]	validation_0-mae:2101.58913
[578]	validation_0-mae:2101.35700
[579]	validation_0-mae:2101.11885
[580]	validation_0-mae:2101.09300
[581]	validation_0-mae:2100.13805
[582]	validation_0-mae:2100.29125
[583]	validation_0-mae:2100.20472
[584]	validation_0-mae:2099.89346
[585]	validation_0-mae:2099.78038
[586]	validation_0-mae:2099.51367
[587]	validation_0-mae:2099.27346
[588]	validation_0-mae:2099.33023
[589]	validation_0-mae:2099.28242
[590]	validation_0-mae:2099.23038

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[0]	validation_0-mae:12392.47218
[1]	validation_0-mae:11611.35819
[2]	validation_0-mae:10917.83553
[3]	validation_0-mae:10280.82172
[4]	validation_0-mae:9703.76535
[5]	validation_0-mae:9209.82931
[6]	validation_0-mae:8773.21859
[7]	validation_0-mae:8360.55551
[8]	validation_0-mae:7996.59846
[9]	validation_0-mae:7667.28232
[10]	validation_0-mae:7356.70332
[11]	validation_0-mae:7064.96214
[12]	validation_0-mae:6786.01710
[13]	validation_0-mae:6518.16111
[14]	validation_0-mae:6258.75925
[15]	validation_0-mae:6047.43543
[16]	validation_0-mae:5826.45137
[17]	validation_0-mae:5635.96066
[18]	validation_0-mae:5433.14496
[19]	validation_0-mae:5242.87030
[20]	validation_0-mae:5073.19434
[21]	validation_0-mae:4917.60819
[22]	validation_0-mae:4783.00770
[23]	validation_0-mae:4649.36832
[24]	validation_0-mae:4530.93862
[25]	validation_0-mae:4406.36674
[26]	validation_0-mae:4288.41447
[27]	validation_0-mae:4193.49952
[28]	validation_0-mae:4110.54686
[29]	validation_0-mae:4023.90283
[30]	validation_0-mae:3932.75755
[31]	validation_0-mae:3848.03718
[32]	validation_0-mae:3758.46895
[33]	validation_0-mae:3692.86899
[34]	validation_0-mae:3620.45159
[35]	validation_0-mae:3551.89745
[36]	validation_0-mae:3490.73583
[37]	validation_0-mae:3448.70813
[38]	validation_0-mae:3399.28597
[39]	validation_0-mae:3356.68933
[40]	validation_0-mae:3315.93060
[41]	validation_0-mae:3274.04283
[42]	validation_0-mae:3234.67858
[43]	validation_0-mae:3203.12151
[44]	validation_0-mae:3162.08346
[45]	validation_0-mae:3129.01937
[46]	validation_0-mae:3101.88843
[47]	validation_0-mae:3055.00837
[48]	validation_0-mae:3027.09460
[49]	validation_0-mae:3003.28683
[50]	validation_0-mae:2965.30187
[51]	validation_0-mae:2937.62271
[52]	validation_0-mae:2915.17399
[53]	validation_0-mae:2889.79732
[54]	validation_0-mae:2870.57188
[55]	validation_0-mae:2852.31330
[56]	validation_0-mae:2830.39729
[57]	validation_0-mae:2814.89961
[58]	validation_0-mae:2800.38181
[59]	validation_0-mae:2784.76084
[60]	validation_0-mae:2772.26954
[61]	validation_0-mae:2757.84475
[62]	validation_0-mae:2745.96392
[63]	validation_0-mae:2721.61445
[64]	validation_0-mae:2709.73831
[65]	validation_0-mae:2691.16208
[66]	validation_0-mae:2677.75919
[67]	validation_0-mae:2662.41413
[68]	validation_0-mae:2652.03009
[69]	validation_0-mae:2633.79197
[70]	validation_0-mae:2622.71786
[71]	validation_0-mae:2618.51133
[72]	validation_0-mae:2609.99251
[73]	validation_0-mae:2589.83835
[74]	validation_0-mae:2579.62355
[75]	validation_0-mae:2572.58038
[76]	validation_0-mae:2556.40647
[77]	validation_0-mae:2540.52271
[78]	validation_0-mae:2528.29368
[79]	validation_0-mae:2521.15787
[80]	validation_0-mae:2510.54292
[81]	validation_0-mae:2500.24171
[82]	validation_0-mae:2492.57201
[83]	validation_0-mae:2490.65852
[84]	validation_0-mae:2479.69501
[85]	validation_0-mae:2468.72095
[86]	validation_0-mae:2462.20768
[87]	validation_0-mae:2453.53390
[88]	validation_0-mae:2449.13670
[89]	validation_0-mae:2440.31203
[90]	validation_0-mae:2433.26256
[91]	validation_0-mae:2430.59744
[92]	validation_0-mae:2423.78466
[93]	validation_0-mae:2419.53101
[94]	validation_0-mae:2411.73687
[95]	validation_0-mae:2407.36641
[96]	validation_0-mae:2401.47522
[97]	validation_0-mae:2396.67837
[98]	validation_0-mae:2390.27812
[99]	validation_0-mae:2388.42874
[100]	validation_0-mae:2385.06529
[101]	validation_0-mae:2378.85797
[102]	validation_0-mae:2370.25875
[103]	validation_0-mae:2368.76970
[104]	validation_0-mae:2364.05691
[105]	validation_0-mae:2361.83231
[106]	validation_0-mae:2356.71715
[107]	validation_0-mae:2354.43710
[108]	validation_0-mae:2350.47442
[109]	validation_0-mae:2346.16336
[110]	validation_0-mae:2340.41188
[111]	validation_0-mae:2337.55781
[112]	validation_0-mae:2334.93762
[113]	validation_0-mae:2332.17576
[114]	validation_0-mae:2329.19208
[115]	validation_0-mae:2327.37559
[116]	validation_0-mae:2326.37053
[117]	validation_0-mae:2320.50637
[118]	validation_0-mae:2316.34297
[119]	validation_0-mae:2313.59626
[120]	validation_0-mae:2311.69005
[121]	validation_0-mae:2309.20049
[122]	validation_0-mae:2307.69442
[123]	validation_0-mae:2305.09803
[124]	validation_0-mae:2303.62872
[125]	validation_0-mae:2299.94540
[126]	validation_0-mae:2297.61898
[127]	validation_0-mae:2295.41306
[128]	validation_0-mae:2295.00639
[129]	validation_0-mae:2294.44541
[130]	validation_0-mae:2293.24397
[131]	validation_0-mae:2287.05958
[132]	validation_0-mae:2284.66661
[133]	validation_0-mae:2282.20332
[134]	validation_0-mae:2280.12995
[135]	validation_0-mae:2278.08966
[136]	validation_0-mae:2275.13224
[137]	validation_0-mae:2274.78985
[138]	validation_0-mae:2273.74030
[139]	validation_0-mae:2269.84285
[140]	validation_0-mae:2265.33861
[141]	validation_0-mae:2262.62043
[142]	validation_0-mae:2259.24575
[143]	validation_0-mae:2255.61010
[144]	validation_0-mae:2253.52898
[145]	validation_0-mae:2252.00311
[146]	validation_0-mae:2248.25465
[147]	validation_0-mae:2246.57757
[148]	validation_0-mae:2244.64249
[149]	validation_0-mae:2242.17885
[150]	validation_0-mae:2239.29117
[151]	validation_0-mae:2240.12110
[152]	validation_0-mae:2238.77906
[153]	validation_0-mae:2238.60643
[154]	validation_0-mae:2238.58761
[155]	validation_0-mae:2238.13687
[156]	validation_0-mae:2238.86107
[157]	validation_0-mae:2237.13164
[158]	validation_0-mae:2237.04950
[0]	validation_0-mae:12483.98940
[1]	validation_0-mae:11779.96059
[2]	validation_0-mae:11141.63353
[3]	validation_0-mae:10550.00252
[4]	validation_0-mae:10021.63684
[5]	validation_0-mae:9535.59944
[6]	validation_0-mae:9092.14829
[7]	validation_0-mae:8682.29210
[8]	validation_0-mae:8310.17375
[9]	validation_0-mae:7977.73849

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[0]	validation_0-mae:12446.82860
[1]	validation_0-mae:11715.20827
[2]	validation_0-mae:11058.62483
[3]	validation_0-mae:10429.71802
[4]	validation_0-mae:9891.07307
[5]	validation_0-mae:9381.60008
[6]	validation_0-mae:8927.53934
[7]	validation_0-mae:8521.26433
[8]	validation_0-mae:8141.87687
[9]	validation_0-mae:7794.84313
[10]	validation_0-mae:7482.10031
[11]	validation_0-mae:7191.06691
[12]	validation_0-mae:6901.65688
[13]	validation_0-mae:6634.85536
[14]	validation_0-mae:6385.06860
[15]	validation_0-mae:6156.33875
[16]	validation_0-mae:5924.28973
[17]	validation_0-mae:5725.18662
[18]	validation_0-mae:5538.69070
[19]	validation_0-mae:5371.52656
[20]	validation_0-mae:5197.94058
[21]	validation_0-mae:5018.04583
[22]	validation_0-mae:4882.43073
[23]	validation_0-mae:4735.73119
[24]	validation_0-mae:4620.98427
[25]	validation_0-mae:4484.86640
[26]	validation_0-mae:4382.60863
[27]	validation_0-mae:4279.47530
[28]	validation_0-mae:4188.94802
[29]	validation_0-mae:4092.78887
[30]	validation_0-mae:3995.68114
[31]	validation_0-mae:3918.72839
[32]	validation_0-mae:3826.89283
[33]	validation_0-mae:3760.62240
[34]	validation_0-mae:3687.62950
[35]	validation_0-mae:3619.44008
[36]	validation_0-mae:3557.83328
[37]	validation_0-mae:3493.69714
[38]	validation_0-mae:3446.31285
[39]	validation_0-mae:3398.37281
[40]	validation_0-mae:3349.99025
[41]	validation_0-mae:3302.34120
[42]	validation_0-mae:3262.86018
[43]	validation_0-mae:3219.59162
[44]	validation_0-mae:3184.84183
[45]	validation_0-mae:3150.83316
[46]	validation_0-mae:3105.05332
[47]	validation_0-mae:3068.19757
[48]	validation_0-mae:3036.80024
[49]	validation_0-mae:3005.27080
[50]	validation_0-mae:2981.54792
[51]	validation_0-mae:2959.80398
[52]	validation_0-mae:2931.68193
[53]	validation_0-mae:2895.70881
[54]	validation_0-mae:2874.11149
[55]	validation_0-mae:2852.43639
[56]	validation_0-mae:2826.65771
[57]	validation_0-mae:2806.94605
[58]	validation_0-mae:2789.40169
[59]	validation_0-mae:2772.83193
[60]	validation_0-mae:2760.51535
[61]	validation_0-mae:2741.47593
[62]	validation_0-mae:2731.42547
[63]	validation_0-mae:2718.64573
[64]	validation_0-mae:2707.44351
[65]	validation_0-mae:2694.08446
[66]	validation_0-mae:2684.21151
[67]	validation_0-mae:2673.16002
[68]	validation_0-mae:2657.84313
[69]	validation_0-mae:2648.65571
[70]	validation_0-mae:2634.11780
[71]	validation_0-mae:2624.50300
[72]	validation_0-mae:2614.28882
[73]	validation_0-mae:2606.81842
[74]	validation_0-mae:2598.04874
[75]	validation_0-mae:2574.92166
[76]	validation_0-mae:2561.47218
[77]	validation_0-mae:2552.02459
[78]	validation_0-mae:2546.34935
[79]	validation_0-mae:2539.48275
[80]	validation_0-mae:2532.10414
[81]	validation_0-mae:2524.59400
[82]	validation_0-mae:2514.77116
[83]	validation_0-mae:2502.20886
[84]	validation_0-mae:2492.27708
[85]	validation_0-mae:2479.06857
[86]	validation_0-mae:2472.60671
[87]	validation_0-mae:2463.47753
[88]	validation_0-mae:2456.71388
[89]	validation_0-mae:2452.41810
[90]	validation_0-mae:2442.70450
[91]	validation_0-mae:2432.15537
[92]	validation_0-mae:2427.21736
[93]	validation_0-mae:2418.42528
[94]	validation_0-mae:2413.59168
[95]	validation_0-mae:2402.54294
[96]	validation_0-mae:2389.97187
[97]	validation_0-mae:2381.96067
[98]	validation_0-mae:2378.50620
[99]	validation_0-mae:2369.64447
[100]	validation_0-mae:2359.35310
[101]	validation_0-mae:2353.23638
[102]	validation_0-mae:2349.22327
[103]	validation_0-mae:2345.72702
[104]	validation_0-mae:2342.78463
[105]	validation_0-mae:2334.93803
[106]	validation_0-mae:2332.36165
[107]	validation_0-mae:2330.22263
[108]	validation_0-mae:2327.49586
[109]	validation_0-mae:2322.50453
[110]	validation_0-mae:2319.64616
[111]	validation_0-mae:2313.51964
[112]	validation_0-mae:2311.16697
[113]	validation_0-mae:2308.60304
[114]	validation_0-mae:2306.05981
[115]	validation_0-mae:2296.87784
[116]	validation_0-mae:2291.85170
[117]	validation_0-mae:2287.60776
[118]	validation_0-mae:2280.94984
[119]	validation_0-mae:2279.51867
[120]	validation_0-mae:2278.58445
[121]	validation_0-mae:2272.59925
[122]	validation_0-mae:2267.65972
[123]	validation_0-mae:2266.00969
[124]	validation_0-mae:2260.80691
[125]	validation_0-mae:2259.70901
[126]	validation_0-mae:2251.58058
[127]	validation_0-mae:2251.02096
[128]	validation_0-mae:2249.04535
[129]	validation_0-mae:2244.88869
[130]	validation_0-mae:2240.56207
[131]	validation_0-mae:2238.54466
[132]	validation_0-mae:2235.85941
[133]	validation_0-mae:2233.81377
[134]	validation_0-mae:2231.55355
[135]	validation_0-mae:2228.49396
[136]	validation_0-mae:2222.76267
[137]	validation_0-mae:2221.16868
[138]	validation_0-mae:2216.50597
[139]	validation_0-mae:2213.74208
[140]	validation_0-mae:2211.62814
[141]	validation_0-mae:2209.68256
[142]	validation_0-mae:2208.61115
[143]	validation_0-mae:2206.28909
[144]	validation_0-mae:2203.86969
[145]	validation_0-mae:2201.14943
[146]	validation_0-mae:2198.99542
[147]	validation_0-mae:2198.20406
[148]	validation_0-mae:2195.37523
[149]	validation_0-mae:2189.16944
[150]	validation_0-mae:2187.16662
[151]	validation_0-mae:2186.18491
[152]	validation_0-mae:2184.52245
[153]	validation_0-mae:2183.25544
[154]	validation_0-mae:2181.91035
[155]	validation_0-mae:2180.20047
[156]	validation_0-mae:2179.01261
[157]	validation_0-mae:2178.90896
[158]	validation_0-mae:2178.32928
[159]	validation_0-mae:2176.20975
[160]	validation_0-mae:2175.81312
[161]	validation_0-mae:2175.28014
[162]	validation_0-mae:2175.38676
[163]	validation_0-mae:2173.97554
[164]	validation_0-mae:2174.14729
[165]	validation_0-mae:2174.71583
[166]	validation_0-mae:2173.27874
[167]	validation_0-mae:2172.88122
[168]	validation_0-mae:2172.45258
[169]	validation_0-mae:2171.86454
[170]	validation_0-mae:2171.36478
[171]	validation_0-mae:2167.78392
[172]	validation_0-mae:2166.98065
[173]	validation_0-mae:2166.04106
[174]	validation_0-mae:2164.81062
[175]	validation_0-mae:2164.84165
[176]	validation_0-mae:2163.75635
[177]	validation_0-mae:2161.27629
[178]	validation_0-mae:2161.24605
[179]	validation_0-mae:2160.22288
[180]	validation_0-mae:2160.53227
[181]	validation_0-mae:2159.78136
[182]	validation_0-mae:2159.95228
[183]	validation_0-mae:2156.38789
[184]	validation_0-mae:2156.14058
[185]	validation_0-mae:2156.15609
[186]	validation_0-mae:2156.53032
[187]	validation_0-mae:2155.51266
[188]	validation_0-mae:2156.12582
[189]	validation_0-mae:2152.32577
[190]	validation_0-mae:2148.78704
[191]	validation_0-mae:2146.94377
[192]	validation_0-mae:2144.22587
[193]	validation_0-mae:2143.22037
[194]	validation_0-mae:2144.80113
[195]	validation_0-mae:2143.13280
[196]	validation_0-mae:2143.37641
[197]	validation_0-mae:2139.26340
[198]	validation_0-mae:2137.01995
[199]	validation_0-mae:2138.59801
[200]	validation_0-mae:2137.42889
[201]	validation_0-mae:2136.82807
[202]	validation_0-mae:2136.38543
[203]	validation_0-mae:2134.21185
[204]	validation_0-mae:2134.49241
[205]	validation_0-mae:2134.86497
[206]	validation_0-mae:2135.74566
[207]	validation_0-mae:2136.05717
[208]	validation_0-mae:2135.24583
[209]	validation_0-mae:2133.96607
[210]	validation_0-mae:2134.24427
[211]	validation_0-mae:2131.59746
[212]	validation_0-mae:2130.69141
[213]	validation_0-mae:2128.66066
[214]	validation_0-mae:2128.18477
[215]	validation_0-mae:2128.18223
[216]	validation_0-mae:2127.44812
[217]	validation_0-mae:2127.29085
[218]	validation_0-mae:2126.57102
[219]	validation_0-mae:2125.87750
[220]	validation_0-mae:2124.98156
[221]	validation_0-mae:2124.91962
[222]	validation_0-mae:2124.59081
[223]	validation_0-mae:2124.66311
[224]	validation_0-mae:2125.07784
[225]	validation_0-mae:2124.56284
[226]	validation_0-mae:2124.47201
[227]	validation_0-mae:2124.67471
[228]	validation_0-mae:2123.19951
[229]	validation_0-mae:2123.58725
[230]	validation_0-mae:2123.20630
[231]	validation_0-mae:2122.73201
[232]	validation_0-mae:2122.87678
[233]	validation_0-mae:2121.59077
[234]	validation_0-mae:2122.04639
[235]	validation_0-mae:2121.64567
[236]	validation_0-mae:2121.08211
[237]	validation_0-mae:2119.62971
[238]	validation_0-mae:2119.39438
[239]	validation_0-mae:2119.86155
[240]	validation_0-mae:2120.23333
[241]	validation_0-mae:2119.10345
[242]	validation_0-mae:2118.21409
[243]	validation_0-mae:2118.53126
[244]	validation_0-mae:2117.69587
[245]	validation_0-mae:2116.80582
[246]	validation_0-mae:2115.26733
[247]	validation_0-mae:2114.72695
[248]	validation_0-mae:2114.09145
[249]	validation_0-mae:2112.93837
[250]	validation_0-mae:2113.49925
[251]	validation_0-mae:2112.85526
[252]	validation_0-mae:2112.23922
[253]	validation_0-mae:2110.86145
[254]	validation_0-mae:2109.95847
[255]	validation_0-mae:2109.03059
[256]	validation_0-mae:2108.49079
[257]	validation_0-mae:2108.23005
[258]	validation_0-mae:2107.93895
[259]	validation_0-mae:2107.63257
[260]	validation_0-mae:2106.08815
[261]	validation_0-mae:2106.25163
[262]	validation_0-mae:2106.41636
[263]	validation_0-mae:2106.15665
[264]	validation_0-mae:2106.22698
[265]	validation_0-mae:2105.15924
[266]	validation_0-mae:2104.42282
[267]	validation_0-mae:2104.89961
[268]	validation_0-mae:2104.96202
[269]	validation_0-mae:2105.09208
[270]	validation_0-mae:2104.77803
[271]	validation_0-mae:2104.45229
[272]	validation_0-mae:2104.99730
[273]	validation_0-mae:2105.12797
[274]	validation_0-mae:2106.01222
[275]	validation_0-mae:2106.03537
[276]	validation_0-mae:2106.68018
[277]	validation_0-mae:2105.03851
[278]	validation_0-mae:2105.01571
[279]	validation_0-mae:2103.91340
[280]	validation_0-mae:2103.65057
[281]	validation_0-mae:2102.96810
[282]	validation_0-mae:2103.12468
[283]	validation_0-mae:2103.11633
[284]	validation_0-mae:2103.32490
[285]	validation_0-mae:2103.88650
[286]	validation_0-mae:2103.09275
[287]	validation_0-mae:2101.65776
[288]	validation_0-mae:2101.84459
[289]	validation_0-mae:2101.09196
[290]	validation_0-mae:2100.16299
[291]	validation_0-mae:2100.36122
[292]	validation_0-mae:2100.67685
[293]	validation_0-mae:2100.01631
[294]	validation_0-mae:2100.16672
[295]	validation_0-mae:2100.16083
[296]	validation_0-mae:2100.68365
[297]	validation_0-mae:2100.01711
[298]	validation_0-mae:2099.63438
[299]	validation_0-mae:2099.68984
[300]	validation_0-mae:2099.70366
[301]	validation_0-mae:2099.70196
[302]	validation_0-mae:2099.62719
[303]	validation_0-mae:2099.35766
[304]	validation_0-mae:2098.58659
[305]	validation_0-mae:2097.88640
[306]	validation_0-mae:2096.93895
[307]	validation_0-mae:2095.88967
[308]	validation_0-mae:2095.49028
[309]	validation_0-mae:2095.30667
[310]	validation_0-mae:2095.21611
[311]	validation_0-mae:2094.37194
[312]	validation_0-mae:2093.30499
[313]	validation_0-mae:2091.04304
[314]	validation_0-mae:2091.11987
[315]	validation_0-mae:2091.37977
[316]	validation_0-mae:2091.25443
[317]	validation_0-mae:2091.55330
[318]	validation_0-mae:2090.84610
[319]	validation_0-mae:2090.49984
[320]	validation_0-mae:2090.35403
[321]	validation_0-mae:2090.50695
[322]	validation_0-mae:2090.55918
[323]	validation_0-mae:2090.78213
[324]	validation_0-mae:2090.80877
[325]	validation_0-mae:2089.93156
[326]	validation_0-mae:2089.54784
[327]	validation_0-mae:2089.13874
[328]	validation_0-mae:2089.60088
[329]	validation_0-mae:2089.39121
[330]	validation_0-mae:2089.54456
[331]	validation_0-mae:2089.95164
[332]	validation_0-mae:2089.66080
[333]	validation_0-mae:2089.53336
[334]	validation_0-mae:2087.03192
[335]	validation_0-mae:2086.53375
[336]	validation_0-mae:2086.87882
[337]	validation_0-mae:2086.77421
[338]	validation_0-mae:2086.01878
[339]	validation_0-mae:2085.93722
[340]	validation_0-mae:2083.18783
[341]	validation_0-mae:2082.70452
[342]	validation_0-mae:2082.74077
[343]	validation_0-mae:2081.76549
[344]	validation_0-mae:2082.66278
[345]	validation_0-mae:2082.67741
[346]	validation_0-mae:2082.98649
[347]	validation_0-mae:2082.36698
[348]	validation_0-mae:2082.65378
[349]	validation_0-mae:2082.46569
[350]	validation_0-mae:2082.65538
[351]	validation_0-mae:2082.95173
[352]	validation_0-mae:2082.60935
[353]	validation_0-mae:2082.82828
[354]	validation_0-mae:2082.46343
[355]	validation_0-mae:2082.71090
[356]	validation_0-mae:2083.53089
[357]	validation_0-mae:2083.50329
[358]	validation_0-mae:2083.40983
[359]	validation_0-mae:2082.45965
[360]	validation_0-mae:2082.42748
[361]	validation_0-mae:2082.33915
[362]	validation_0-mae:2079.97739
[363]	validation_0-mae:2080.28285
[364]	validation_0-mae:2079.90782
[365]	validation_0-mae:2080.12593
[366]	validation_0-mae:2080.15336
[367]	validation_0-mae:2079.18716
[368]	validation_0-mae:2077.97209
[369]	validation_0-mae:2079.26901
[370]	validation_0-mae:2079.61239
[371]	validation_0-mae:2079.05908
[372]	validation_0-mae:2079.42461
[373]	validation_0-mae:2079.21205
[374]	validation_0-mae:2078.84084
[375]	validation_0-mae:2078.61997
[376]	validation_0-mae:2078.42950
[377]	validation_0-mae:2078.75536
[378]	validation_0-mae:2077.73906
[379]	validation_0-mae:2077.80954
[380]	validation_0-mae:2077.39071
[381]	validation_0-mae:2077.22605
[382]	validation_0-mae:2077.11795
[383]	validation_0-mae:2077.45344
[384]	validation_0-mae:2077.52813
[385]	validation_0-mae:2077.37358
[386]	validation_0-mae:2076.12760
[387]	validation_0-mae:2076.34530
[388]	validation_0-mae:2076.50321
[389]	validation_0-mae:2076.51115
[390]	validation_0-mae:2077.02704
[391]	validation_0-mae:2076.95422
[392]	validation_0-mae:2075.87565
[393]	validation_0-mae:2075.52807
[394]	validation_0-mae:2074.46551
[395]	validation_0-mae:2073.81261
[396]	validation_0-mae:2073.42243
[397]	validation_0-mae:2072.68606
[398]	validation_0-mae:2072.73582
[399]	validation_0-mae:2071.88910
[400]	validation_0-mae:2071.76998
[401]	validation_0-mae:2071.35455
[402]	validation_0-mae:2071.17078
[403]	validation_0-mae:2071.33682
[404]	validation_0-mae:2071.09148
[405]	validation_0-mae:2070.85400
[406]	validation_0-mae:2070.31417
[407]	validation_0-mae:2069.57144
[408]	validation_0-mae:2069.87546
[409]	validation_0-mae:2067.82481
[410]	validation_0-mae:2067.84605
[411]	validation_0-mae:2067.89693
[412]	validation_0-mae:2068.20131
[413]	validation_0-mae:2067.84276
[414]	validation_0-mae:2068.03546
[415]	validation_0-mae:2068.08186
[416]	validation_0-mae:2068.07705
[417]	validation_0-mae:2067.57375
[418]	validation_0-mae:2067.13541
[419]	validation_0-mae:2066.70394
[420]	validation_0-mae:2066.71138
[421]	validation_0-mae:2066.98818
[422]	validation_0-mae:2066.87173
[423]	validation_0-mae:2067.15569
[424]	validation_0-mae:2065.20121
[425]	validation_0-mae:2065.12523
[426]	validation_0-mae:2064.81240
[427]	validation_0-mae:2064.50947
[428]	validation_0-mae:2064.45533
[429]	validation_0-mae:2064.24271
[430]	validation_0-mae:2064.24438
[431]	validation_0-mae:2063.69290
[432]	validation_0-mae:2063.05142
[433]	validation_0-mae:2060.61177
[434]	validation_0-mae:2059.32920
[435]	validation_0-mae:2059.08534
[436]	validation_0-mae:2058.52930
[437]	validation_0-mae:2058.63569
[438]	validation_0-mae:2058.44234
[439]	validation_0-mae:2058.20784
[440]	validation_0-mae:2058.55287
[441]	validation_0-mae:2058.21533
[442]	validation_0-mae:2058.26858
[443]	validation_0-mae:2058.46089
[444]	validation_0-mae:2058.54710
[445]	validation_0-mae:2057.39893
[446]	validation_0-mae:2057.22235
[447]	validation_0-mae:2057.25459
[448]	validation_0-mae:2057.77605
[449]	validation_0-mae:2057.79754
[450]	validation_0-mae:2057.73466
[451]	validation_0-mae:2057.57542
[452]	validation_0-mae:2057.26198
[453]	validation_0-mae:2057.33002
[454]	validation_0-mae:2057.35486
[455]	validation_0-mae:2057.56880
[456]	validation_0-mae:2057.89183
[457]	validation_0-mae:2057.55320
[458]	validation_0-mae:2057.84149
[459]	validation_0-mae:2057.81696
[460]	validation_0-mae:2057.33627
[461]	validation_0-mae:2057.20725
[462]	validation_0-mae:2056.90832
[463]	validation_0-mae:2056.41747
[464]	validation_0-mae:2056.45484
[465]	validation_0-mae:2056.14277
[466]	validation_0-mae:2056.13822
[467]	validation_0-mae:2056.29898
[468]	validation_0-mae:2055.98291
[469]	validation_0-mae:2055.19360
[470]	validation_0-mae:2054.50396
[471]	validation_0-mae:2054.52873
[472]	validation_0-mae:2054.55255
[473]	validation_0-mae:2054.97856
[474]	validation_0-mae:2055.03690
[475]	validation_0-mae:2055.01878
[476]	validation_0-mae:2054.89475
[477]	validation_0-mae:2055.04177
[478]	validation_0-mae:2055.28548
[479]	validation_0-mae:2055.31411
[480]	validation_0-mae:2055.38724
[481]	validation_0-mae:2055.27837
[482]	validation_0-mae:2055.32251
[483]	validation_0-mae:2055.14700
[484]	validation_0-mae:2054.86490
[485]	validation_0-mae:2054.48076
[486]	validation_0-mae:2054.23983
[487]	validation_0-mae:2054.38540
[488]	validation_0-mae:2054.08414
[489]	validation_0-mae:2053.96818
[490]	validation_0-mae:2053.68401
[491]	validation_0-mae:2053.77730
[492]	validation_0-mae:2053.76965
[493]	validation_0-mae:2053.65263
[494]	validation_0-mae:2053.78654
[495]	validation_0-mae:2053.38123
[496]	validation_0-mae:2053.62854
[497]	validation_0-mae:2053.45151
[498]	validation_0-mae:2053.65349
[499]	validation_0-mae:2053.56017
[500]	validation_0-mae:2053.42905
[501]	validation_0-mae:2053.75331
[502]	validation_0-mae:2054.03698
[503]	validation_0-mae:2054.22467
[504]	validation_0-mae:2054.40370
[505]	validation_0-mae:2054.51262
[506]	validation_0-mae:2054.55661
[507]	validation_0-mae:2054.53204
[508]	validation_0-mae:2054.52102
[509]	validation_0-mae:2054.37921
[510]	validation_0-mae:2054.70418
[511]	validation_0-mae:2055.27970
[512]	validation_0-mae:2054.87618
[513]	validation_0-mae:2055.09762
[514]	validation_0-mae:2055.15570
[515]	validation_0-mae:2054.87596
[516]	validation_0-mae:2054.82899
[517]	validation_0-mae:2054.94795
[518]	validation_0-mae:2055.18257
[519]	validation_0-mae:2054.87694
[520]	validation_0-mae:2054.98808
[521]	validation_0-mae:2055.08323
[522]	validation_0-mae:2055.11369
[523]	validation_0-mae:2054.92702
[524]	validation_0-mae:2054.71260
[525]	validation_0-mae:2054.92206
[526]	validation_0-mae:2054.94774
[527]	validation_0-mae:2055.09578
[528]	validation_0-mae:2055.11623
[529]	validation_0-mae:2055.12958
[530]	validation_0-mae:2055.21740
[531]	validation_0-mae:2055.26970
[532]	validation_0-mae:2055.30089
[533]	validation_0-mae:2055.05187
[534]	validation_0-mae:2055.14095
[535]	validation_0-mae:2054.82823
[536]	validation_0-mae:2055.03095
[537]	validation_0-mae:2054.89687
[538]	validation_0-mae:2054.80066
[539]	validation_0-mae:2054.58100
[540]	validation_0-mae:2054.32457
[541]	validation_0-mae:2054.32467
[542]	validation_0-mae:2054.41722
[543]	validation_0-mae:2054.35860
[544]	validation_0-mae:2054.06716
[545]	validation_0-mae:2054.13517
[546]	validation_0-mae:2053.98506
[547]	validation_0-mae:2054.07495
[548]	validation_0-mae:2054.21458
[549]	validation_0-mae:2054.40889
[550]	validation_0-mae:2054.14955
[551]	validation_0-mae:2054.22142
[552]	validation_0-mae:2054.51864
[553]	validation_0-mae:2054.69825
[554]	validation_0-mae:2054.70324
[555]	validation_0-mae:2054.65625
[556]	validation_0-mae:2054.99424
[557]	validation_0-mae:2055.15407
[558]	validation_0-mae:2054.75603
[559]	validation_0-mae:2054.92713
[560]	validation_0-mae:2055.23253
[561]	validation_0-mae:2055.36753
[562]	validation_0-mae:2055.32628
[563]	validation_0-mae:2055.31399
[564]	validation_0-mae:2055.21216
[565]	validation_0-mae:2055.12397
[566]	validation_0-mae:2055.15368
[567]	validation_0-mae:2055.00460
[568]	validation_0-mae:2055.27860
[569]	validation_0-mae:2055.31799
[570]	validation_0-mae:2054.93843
[571]	validation_0-mae:2054.73578
[572]	validation_0-mae:2055.07313
[573]	validation_0-mae:2055.02752
[574]	validation_0-mae:2055.49331
[575]	validation_0-mae:2055.50269
[576]	validation_0-mae:2055.52992
[577]	validation_0-mae:2055.67180
[578]	validation_0-mae:2055.86259
[579]	validation_0-mae:2055.90213
[580]	validation_0-mae:2055.43117
[581]	validation_0-mae:2055.56313
[582]	validation_0-mae:2055.75743
[583]	validation_0-mae:2056.04965
[584]	validation_0-mae:2056.12480
[585]	validation_0-mae:2055.82680
[586]	validation_0-mae:2054.82034
[587]	validation_0-mae:2054.81761
[588]	validation_0-mae:2054.08170
[589]	validation_0-mae:2053.83157
[590]	validation_0-mae:2053.58059

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[35]	validation_0-mae:3560.17898
[36]	validation_0-mae:3490.99927
[37]	validation_0-mae:3442.09928
[38]	validation_0-mae:3386.25272
[39]	validation_0-mae:3341.01740
[40]	validation_0-mae:3297.90979
[41]	validation_0-mae:3248.45031
[42]	validation_0-mae:3191.72997
[43]	validation_0-mae:3148.81398
[44]	validation_0-mae:3112.68250
[45]	validation_0-mae:3085.20985
[46]	validation_0-mae:3043.96773
[47]	validation_0-mae:3019.55738
[48]	validation_0-mae:2987.27974
[49]	validation_0-mae:2962.85979
[50]	validation_0-mae:2935.00272
[51]	validation_0-mae:2916.76862
[52]	validation_0-mae:2892.05320
[53]	validation_0-mae:2858.16294
[54]	validation_0-mae:2841.78014
[55]	validation_0-mae:2828.39787
[56]	validation_0-mae:2798.49735
[57]	validation_0-mae:2780.02225
[58]	validation_0-mae:2756.66636
[59]	validation_0-mae:2738.98915
[60]	validation_0-mae:2723.80326
[61]	validation_0-mae:2705.84153
[62]	validation_0-mae:2691.99588
[63]	validation_0-mae:2679.62045
[64]	validation_0-mae:2664.99018
[65]	validation_0-mae:2654.16501
[66]	validation_0-mae:2633.27252
[67]	validation_0-mae:2625.71146
[68]	validation_0-mae:2612.74320
[69]	validation_0-mae:2601.83892
[70]	validation_0-mae:2591.22185
[71]	validation_0-mae:2580.35470
[72]	validation_0-mae:2565.69190
[73]	validation_0-mae:2560.85619
[74]	validation_0-mae:2552.58698
[75]	validation_0-mae:2546.22418
[76]	validation_0-mae:2533.27582
[77]	validation_0-mae:2520.86264
[78]	validation_0-mae:2513.70567
[79]	validation_0-mae:2507.99175
[80]	validation_0-mae:2499.50934
[81]	validation_0-mae:2487.94738
[82]	validation_0-mae:2475.63135
[83]	validation_0-mae:2468.67650
[84]	validation_0-mae:2458.52640
[85]	validation_0-mae:2455.56455
[86]	validation_0-mae:2449.34868
[87]	validation_0-mae:2435.38210
[88]	validation_0-mae:2429.32052
[89]	validation_0-mae:2423.55985
[90]	validation_0-mae:2419.84724
[91]	validation_0-mae:2414.04549
[92]	validation_0-mae:2408.03657
[93]	validation_0-mae:2399.53294
[94]	validation_0-mae:2392.65667
[95]	validation_0-mae:2388.93342
[96]	validation_0-mae:2380.30200
[97]	validation_0-mae:2376.83556
[98]	validation_0-mae:2369.34591
[99]	validation_0-mae:2366.24579
[100]	validation_0-mae:2362.64324
[101]	validation_0-mae:2358.65964
[102]	validation_0-mae:2355.63226
[103]	validation_0-mae:2347.09564
[104]	validation_0-mae:2344.61625
[105]	validation_0-mae:2339.61854
[106]	validation_0-mae:2335.93726
[107]	validation_0-mae:2333.22982
[108]	validation_0-mae:2332.03588
[109]	validation_0-mae:2327.26608
[110]	validation_0-mae:2326.00384
[111]	validation_0-mae:2320.75300
[112]	validation_0-mae:2317.78898
[113]	validation_0-mae:2311.05869
[114]	validation_0-mae:2307.08306
[115]	validation_0-mae:2304.74946
[116]	validation_0-mae:2301.71856
[117]	validation_0-mae:2296.73667
[118]	validation_0-mae:2295.36741
[119]	validation_0-mae:2289.35464
[120]	validation_0-mae:2286.62008
[121]	validation_0-mae:2285.54085
[122]	validation_0-mae:2281.28447
[123]	validation_0-mae:2280.68458
[124]	validation_0-mae:2278.03969
[125]	validation_0-mae:2272.17171
[126]	validation_0-mae:2270.52702
[127]	validation_0-mae:2268.35518
[128]	validation_0-mae:2265.26352
[129]	validation_0-mae:2263.66321
[130]	validation_0-mae:2262.73150
[131]	validation_0-mae:2258.86788
[132]	validation_0-mae:2258.06368
[133]	validation_0-mae:2256.46770
[134]	validation_0-mae:2253.95700
[135]	validation_0-mae:2248.18184
[136]	validation_0-mae:2243.94725
[137]	validation_0-mae:2241.38884
[138]	validation_0-mae:2239.27200
[139]	validation_0-mae:2239.85655
[140]	validation_0-mae:2236.43316
[141]	validation_0-mae:2235.28857
[142]	validation_0-mae:2233.75637
[143]	validation_0-mae:2234.49040
[144]	validation_0-mae:2231.06347
[145]	validation_0-mae:2226.70977
[146]	validation_0-mae:2226.46482
[147]	validation_0-mae:2225.38482
[148]	validation_0-mae:2220.93734
[149]	validation_0-mae:2220.48247
[150]	validation_0-mae:2216.88104
[151]	validation_0-mae:2216.45670
[152]	validation_0-mae:2214.13650
[153]	validation_0-mae:2213.50309
[154]	validation_0-mae:2213.06559
[155]	validation_0-mae:2211.84829
[156]	validation_0-mae:2211.60985
[157]	validation_0-mae:2210.36218
[158]	validation_0-mae:2209.14944
[159]	validation_0-mae:2208.42804
[160]	validation_0-mae:2208.55179
[161]	validation_0-mae:2209.36062
[162]	validation_0-mae:2207.28900
[163]	validation_0-mae:2205.80732
[164]	validation_0-mae:2203.95151
[165]	validation_0-mae:2200.33169
[166]	validation_0-mae:2199.96081
[167]	validation_0-mae:2199.27719
[168]	validation_0-mae:2199.07989
[169]	validation_0-mae:2196.77269
[170]	validation_0-mae:2194.16634
[171]	validation_0-mae:2194.57888
[172]	validation_0-mae:2195.58083
[173]	validation_0-mae:2195.54981
[174]	validation_0-mae:2193.88760
[175]	validation_0-mae:2192.18320
[176]	validation_0-mae:2190.73890
[177]	validation_0-mae:2189.48412
[178]	validation_0-mae:2188.10436
[179]	validation_0-mae:2186.71666
[180]	validation_0-mae:2185.73570
[181]	validation_0-mae:2183.20919
[182]	validation_0-mae:2182.49247
[183]	validation_0-mae:2182.12756
[184]	validation_0-mae:2181.57312
[185]	validation_0-mae:2181.10436
[186]	validation_0-mae:2181.10321
[187]	validation_0-mae:2180.65559
[188]	validation_0-mae:2179.79146
[189]	validation_0-mae:2177.02681
[190]	validation_0-mae:2177.28600
[191]	validation_0-mae:2176.50635
[192]	validation_0-mae:2176.41356
[193]	validation_0-mae:2176.99840
[194]	validation_0-mae:2173.78396
[195]	validation_0-mae:2173.72411
[196]	validation_0-mae:2173.81858
[197]	validation_0-mae:2173.03597
[198]	validation_0-mae:2172.54277
[199]	validation_0-mae:2173.60098
[200]	validation_0-mae:2172.61839
[201]	validation_0-mae:2170.61364
[202]	validation_0-mae:2170.92045
[203]	validation_0-mae:2170.70136
[204]	validation_0-mae:2170.48832
[205]	validation_0-mae:2171.60572
[206]	validation_0-mae:2170.03929
[207]	validation_0-mae:2170.25175
[208]	validation_0-mae:2168.65676
[209]	validation_0-mae:2166.91513
[210]	validation_0-mae:2166.20151
[211]	validation_0-mae:2164.52718
[212]	validation_0-mae:2163.92611
[213]	validation_0-mae:2163.63927
[214]	validation_0-mae:2162.65231
[215]	validation_0-mae:2161.22312
[216]	validation_0-mae:2161.95720
[217]	validation_0-mae:2162.27529
[218]	validation_0-mae:2162.13979
[219]	validation_0-mae:2162.15122
[220]	validation_0-mae:2161.37853
[221]	validation_0-mae:2161.08790
[222]	validation_0-mae:2160.60771
[223]	validation_0-mae:2160.42257
[224]	validation_0-mae:2160.17487
[225]	validation_0-mae:2157.96418
[226]	validation_0-mae:2157.22559
[227]	validation_0-mae:2155.65149
[228]	validation_0-mae:2155.40944
[229]	validation_0-mae:2156.04655
[230]	validation_0-mae:2155.17072
[231]	validation_0-mae:2154.39561
[232]	validation_0-mae:2154.55711
[233]	validation_0-mae:2154.50282
[234]	validation_0-mae:2153.26144
[235]	validation_0-mae:2152.51825
[236]	validation_0-mae:2151.86605
[237]	validation_0-mae:2151.21802
[238]	validation_0-mae:2151.16034
[239]	validation_0-mae:2151.39571
[240]	validation_0-mae:2149.62988
[241]	validation_0-mae:2149.27266
[242]	validation_0-mae:2146.98108
[243]	validation_0-mae:2145.87469
[244]	validation_0-mae:2144.12691
[245]	validation_0-mae:2143.56886
[246]	validation_0-mae:2140.11224
[247]	validation_0-mae:2138.53515
[248]	validation_0-mae:2136.04240
[249]	validation_0-mae:2136.05277
[250]	validation_0-mae:2136.54731
[251]	validation_0-mae:2134.57764
[252]	validation_0-mae:2134.87299
[253]	validation_0-mae:2135.55411
[254]	validation_0-mae:2134.80387
[255]	validation_0-mae:2134.01647
[256]	validation_0-mae:2135.47814
[257]	validation_0-mae:2134.01941
[258]	validation_0-mae:2133.38179
[259]	validation_0-mae:2132.76708
[260]	validation_0-mae:2132.80949
[261]	validation_0-mae:2132.58885
[262]	validation_0-mae:2133.23431
[263]	validation_0-mae:2133.62187
[264]	validation_0-mae:2133.32806
[265]	validation_0-mae:2134.17864
[266]	validation_0-mae:2133.95797
[267]	validation_0-mae:2134.41337
[268]	validation_0-mae:2133.97189
[269]	validation_0-mae:2133.82417
[270]	validation_0-mae:2134.57297
[271]	validation_0-mae:2134.86906
[272]	validation_0-mae:2135.18550
[273]	validation_0-mae:2134.73322
[274]	validation_0-mae:2135.72809
[275]	validation_0-mae:2135.35242
[276]	validation_0-mae:2134.63994
[277]	validation_0-mae:2133.00520
[278]	validation_0-mae:2132.94529
[279]	validation_0-mae:2131.75960
[280]	validation_0-mae:2131.73197
[281]	validation_0-mae:2131.95788
[282]	validation_0-mae:2130.64840
[283]	validation_0-mae:2129.32560
[284]	validation_0-mae:2128.43239
[285]	validation_0-mae:2126.46571
[286]	validation_0-mae:2124.54813
[287]	validation_0-mae:2124.49067
[288]	validation_0-mae:2124.42444
[289]	validation_0-mae:2124.25081
[290]	validation_0-mae:2122.15795
[291]	validation_0-mae:2122.04794
[292]	validation_0-mae:2122.64115
[293]	validation_0-mae:2122.41034
[294]	validation_0-mae:2121.20463
[295]	validation_0-mae:2120.89865
[296]	validation_0-mae:2120.84523
[297]	validation_0-mae:2121.23108
[298]	validation_0-mae:2120.91785
[299]	validation_0-mae:2118.89944
[300]	validation_0-mae:2117.91750
[301]	validation_0-mae:2117.35691
[302]	validation_0-mae:2117.52885
[303]	validation_0-mae:2117.51854
[304]	validation_0-mae:2116.80781
[305]	validation_0-mae:2115.10608
[306]	validation_0-mae:2114.92207
[307]	validation_0-mae:2114.93388
[308]	validation_0-mae:2115.06483
[309]	validation_0-mae:2114.59494
[310]	validation_0-mae:2114.05875
[311]	validation_0-mae:2112.34120
[312]	validation_0-mae:2112.74238
[313]	validation_0-mae:2112.76527
[314]	validation_0-mae:2112.25416
[315]	validation_0-mae:2112.37689
[316]	validation_0-mae:2111.64299
[317]	validation_0-mae:2111.92710
[318]	validation_0-mae:2110.36749
[319]	validation_0-mae:2110.48227
[320]	validation_0-mae:2110.85143
[321]	validation_0-mae:2109.98961
[322]	validation_0-mae:2110.57561
[323]	validation_0-mae:2110.41069
[324]	validation_0-mae:2109.53433
[325]	validation_0-mae:2109.76693
[326]	validation_0-mae:2109.23532
[327]	validation_0-mae:2109.42866
[328]	validation_0-mae:2109.47377
[329]	validation_0-mae:2109.89767
[330]	validation_0-mae:2107.50044
[331]	validation_0-mae:2107.37671
[332]	validation_0-mae:2107.64857
[333]	validation_0-mae:2107.84955
[334]	validation_0-mae:2108.47524
[335]	validation_0-mae:2108.21133
[336]	validation_0-mae:2108.80439
[337]	validation_0-mae:2108.59798
[338]	validation_0-mae:2108.10161
[339]	validation_0-mae:2108.20836
[340]	validation_0-mae:2107.79695
[341]	validation_0-mae:2108.03995
[342]	validation_0-mae:2108.02924
[343]	validation_0-mae:2107.57215
[344]	validation_0-mae:2107.33091
[345]	validation_0-mae:2106.83778
[346]	validation_0-mae:2106.32636
[347]	validation_0-mae:2106.44163
[348]	validation_0-mae:2106.92294
[349]	validation_0-mae:2106.63128
[350]	validation_0-mae:2106.80202
[351]	validation_0-mae:2106.62984
[352]	validation_0-mae:2106.74279
[353]	validation_0-mae:2106.74520
[354]	validation_0-mae:2107.10873
[355]	validation_0-mae:2107.44164
[356]	validation_0-mae:2106.69710
[357]	validation_0-mae:2107.05851
[358]	validation_0-mae:2106.26406
[359]	validation_0-mae:2106.69809
[360]	validation_0-mae:2107.12052
[361]	validation_0-mae:2107.15217
[362]	validation_0-mae:2106.99349
[363]	validation_0-mae:2107.05478
[364]	validation_0-mae:2105.96094
[365]	validation_0-mae:2104.82846
[366]	validation_0-mae:2103.75559
[367]	validation_0-mae:2103.86318
[368]	validation_0-mae:2102.92362
[369]	validation_0-mae:2102.83242
[370]	validation_0-mae:2102.86244
[371]	validation_0-mae:2102.51061
[372]	validation_0-mae:2102.22643
[373]	validation_0-mae:2101.72615
[374]	validation_0-mae:2101.71766
[375]	validation_0-mae:2101.94453
[376]	validation_0-mae:2101.85622
[377]	validation_0-mae:2101.51999
[378]	validation_0-mae:2101.50659
[379]	validation_0-mae:2101.17376
[380]	validation_0-mae:2101.49179
[381]	validation_0-mae:2102.06905
[382]	validation_0-mae:2101.62050
[383]	validation_0-mae:2102.15538
[384]	validation_0-mae:2101.77730
[385]	validation_0-mae:2101.71610
[386]	validation_0-mae:2102.34802
[387]	validation_0-mae:2102.25274
[388]	validation_0-mae:2102.16811
[389]	validation_0-mae:2101.84273
[390]	validation_0-mae:2102.57832
[391]	validation_0-mae:2102.02908
[392]	validation_0-mae:2102.42700
[393]	validation_0-mae:2103.44470
[394]	validation_0-mae:2103.44826
[395]	validation_0-mae:2102.06280
[396]	validation_0-mae:2101.93502
[397]	validation_0-mae:2101.41263
[398]	validation_0-mae:2101.50324
[399]	validation_0-mae:2101.66789
[400]	validation_0-mae:2102.05691
[401]	validation_0-mae:2102.28700
[402]	validation_0-mae:2101.63614
[403]	validation_0-mae:2101.63476
[404]	validation_0-mae:2100.96180
[405]	validation_0-mae:2101.55203
[406]	validation_0-mae:2100.04990
[407]	validation_0-mae:2100.47747
[408]	validation_0-mae:2099.50127
[409]	validation_0-mae:2099.15695
[410]	validation_0-mae:2099.46177
[411]	validation_0-mae:2099.58101
[412]	validation_0-mae:2098.96867
[413]	validation_0-mae:2099.17967
[414]	validation_0-mae:2099.20024
[415]	validation_0-mae:2097.53112
[416]	validation_0-mae:2097.37405
[417]	validation_0-mae:2097.20331
[418]	validation_0-mae:2097.01175
[419]	validation_0-mae:2096.79676
[420]	validation_0-mae:2096.52312
[421]	validation_0-mae:2095.77617
[422]	validation_0-mae:2095.61122
[423]	validation_0-mae:2095.80998
[424]	validation_0-mae:2095.80065
[425]	validation_0-mae:2095.95795
[426]	validation_0-mae:2096.10052
[427]	validation_0-mae:2095.26918
[428]	validation_0-mae:2094.85481
[429]	validation_0-mae:2094.53376
[430]	validation_0-mae:2094.81521
[431]	validation_0-mae:2094.53803
[432]	validation_0-mae:2094.77401
[433]	validation_0-mae:2094.92757
[434]	validation_0-mae:2094.51303
[435]	validation_0-mae:2094.98148
[436]	validation_0-mae:2095.28929
[437]	validation_0-mae:2095.15758
[438]	validation_0-mae:2095.27417
[439]	validation_0-mae:2095.22147
[440]	validation_0-mae:2095.48110
[441]	validation_0-mae:2095.06207
[442]	validation_0-mae:2095.06900
[443]	validation_0-mae:2094.95414
[444]	validation_0-mae:2095.18883
[445]	validation_0-mae:2094.55269
[446]	validation_0-mae:2094.32827
[447]	validation_0-mae:2093.66019
[448]	validation_0-mae:2093.02573
[449]	validation_0-mae:2092.62194
[450]	validation_0-mae:2092.13517
[451]	validation_0-mae:2092.11769
[452]	validation_0-mae:2092.30940
[453]	validation_0-mae:2092.84388
[454]	validation_0-mae:2093.17074
[455]	validation_0-mae:2093.05233
[456]	validation_0-mae:2092.55857
[457]	validation_0-mae:2091.86550
[458]	validation_0-mae:2092.13884
[459]	validation_0-mae:2092.09386
[460]	validation_0-mae:2091.96135
[461]	validation_0-mae:2091.93080
[462]	validation_0-mae:2091.60825
[463]	validation_0-mae:2091.23641
[464]	validation_0-mae:2090.93921
[465]	validation_0-mae:2091.24062
[466]	validation_0-mae:2091.78035
[467]	validation_0-mae:2091.46410
[468]	validation_0-mae:2091.70447
[469]	validation_0-mae:2092.01081
[470]	validation_0-mae:2091.94204
[471]	validation_0-mae:2091.84022
[472]	validation_0-mae:2091.82084
[473]	validation_0-mae:2092.09506
[474]	validation_0-mae:2092.12023
[475]	validation_0-mae:2092.53835
[476]	validation_0-mae:2092.03703
[477]	validation_0-mae:2091.81578
[478]	validation_0-mae:2091.45382
[479]	validation_0-mae:2091.25125
[480]	validation_0-mae:2091.02927
[481]	validation_0-mae:2090.97808
[482]	validation_0-mae:2090.85908
[483]	validation_0-mae:2091.12922
[484]	validation_0-mae:2091.23603
[485]	validation_0-mae:2091.21427
[486]	validation_0-mae:2090.52359
[487]	validation_0-mae:2090.57349
[488]	validation_0-mae:2089.95167
[489]	validation_0-mae:2089.54433
[490]	validation_0-mae:2089.12931
[491]	validation_0-mae:2088.76595
[492]	validation_0-mae:2088.72860
[493]	validation_0-mae:2088.32425
[494]	validation_0-mae:2088.55428
[495]	validation_0-mae:2088.43546
[496]	validation_0-mae:2088.29141
[497]	validation_0-mae:2088.24743
[498]	validation_0-mae:2088.15130
[499]	validation_0-mae:2088.62285
[500]	validation_0-mae:2088.04034
[501]	validation_0-mae:2087.42481
[502]	validation_0-mae:2087.22364
[503]	validation_0-mae:2087.28263
[504]	validation_0-mae:2086.81519
[505]	validation_0-mae:2086.81304
[506]	validation_0-mae:2086.85503
[507]	validation_0-mae:2086.77737
[508]	validation_0-mae:2086.71268
[509]	validation_0-mae:2087.10238
[510]	validation_0-mae:2087.12228
[511]	validation_0-mae:2087.26412
[512]	validation_0-mae:2087.07572
[513]	validation_0-mae:2087.12871
[514]	validation_0-mae:2087.25315
[515]	validation_0-mae:2086.90762
[516]	validation_0-mae:2086.59925
[517]	validation_0-mae:2086.51759
[518]	validation_0-mae:2086.74757
[519]	validation_0-mae:2086.52449
[520]	validation_0-mae:2086.42587
[521]	validation_0-mae:2086.25669
[522]	validation_0-mae:2086.56292
[523]	validation_0-mae:2086.92875
[524]	validation_0-mae:2086.86486
[525]	validation_0-mae:2087.18729
[526]	validation_0-mae:2087.20886
[527]	validation_0-mae:2086.46637
[528]	validation_0-mae:2086.57755
[529]	validation_0-mae:2086.79007
[530]	validation_0-mae:2087.41456
[531]	validation_0-mae:2087.75248
[532]	validation_0-mae:2087.72409
[533]	validation_0-mae:2087.83792
[534]	validation_0-mae:2087.72539
[535]	validation_0-mae:2088.18828
[536]	validation_0-mae:2087.94805
[537]	validation_0-mae:2088.18550
[538]	validation_0-mae:2088.37800
[539]	validation_0-mae:2088.17472
[540]	validation_0-mae:2087.76081
[541]	validation_0-mae:2088.12230
[542]	validation_0-mae:2088.39053
[543]	validation_0-mae:2088.02533
[544]	validation_0-mae:2088.15823
[545]	validation_0-mae:2088.11276
[546]	validation_0-mae:2088.08791
[547]	validation_0-mae:2088.43897
[548]	validation_0-mae:2088.55912
[549]	validation_0-mae:2088.63717
[550]	validation_0-mae:2088.59314
[551]	validation_0-mae:2087.87314
[552]	validation_0-mae:2087.91831
[553]	validation_0-mae:2087.72323
[554]	validation_0-mae:2087.49108
[555]	validation_0-mae:2087.61435
[556]	validation_0-mae:2087.52940
[557]	validation_0-mae:2087.68782
[558]	validation_0-mae:2087.67162
[559]	validation_0-mae:2087.50066
[560]	validation_0-mae:2088.12374
[561]	validation_0-mae:2087.80488
[562]	validation_0-mae:2088.28031
[563]	validation_0-mae:2087.75106
[564]	validation_0-mae:2087.83935
[565]	validation_0-mae:2088.04212
[566]	validation_0-mae:2088.11053
[567]	validation_0-mae:2087.82082
[568]	validation_0-mae:2088.01392
[569]	validation_0-mae:2088.14928
[570]	validation_0-mae:2088.04735
[571]	validation_0-mae:2087.64002
[572]	validation_0-mae:2087.30215
[573]	validation_0-mae:2087.38485
[574]	validation_0-mae:2087.19410
[575]	validation_0-mae:2087.53727
[576]	validation_0-mae:2087.37334
[577]	validation_0-mae:2087.41429
[578]	validation_0-mae:2087.29111
[579]	validation_0-mae:2087.50603
[580]	validation_0-mae:2087.38879
[581]	validation_0-mae:2087.35837
[582]	validation_0-mae:2087.20585
[583]	validation_0-mae:2086.84934
[584]	validation_0-mae:2086.86832
[585]	validation_0-mae:2087.25793
[586]	validation_0-mae:2087.59823
[587]	validation_0-mae:2087.58510
[588]	validation_0-mae:2087.92322
[589]	validation_0-mae:2087.91637
[590]	validation_0-mae:2087.82527
[591]	validation_0-mae:2087.71972
[592]	validation_0-mae:2087.63583
[593]	validation_0-mae:2087.46552
[594]	validation_0-mae:2087.38832
[595]	validation_0-mae:2087.53172
[596]	validation_0-mae:2087.28684
[597]	validation_0-mae:2086.52530
[598]	validation_0-mae:2086.62630
[599]	validation_0-mae:2086.78309
[600]	validation_0-mae:2086.45363
[601]	validation_0-mae:2086.47544
[602]	validation_0-mae:2086.35482
[603]	validation_0-mae:2086.36884
[604]	validation_0-mae:2086.38767
[605]	validation_0-mae:2085.90819
[606]	validation_0-mae:2086.07434
[607]	validation_0-mae:2086.34299
[608]	validation_0-mae:2086.34926
[609]	validation_0-mae:2086.54585
[610]	validation_0-mae:2086.57940
[611]	validation_0-mae:2086.05510
[612]	validation_0-mae:2086.12897
[613]	validation_0-mae:2085.72393
[614]	validation_0-mae:2085.18002
[615]	validation_0-mae:2085.31027
[616]	validation_0-mae:2085.41788
[617]	validation_0-mae:2085.58882
[618]	validation_0-mae:2085.57072
[619]	validation_0-mae:2085.68953
[620]	validation_0-mae:2085.63746
[621]	validation_0-mae:2085.76114
[622]	validation_0-mae:2085.25212
[623]	validation_0-mae:2084.73387
[624]	validation_0-mae:2085.16047

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[28]	validation_0-mae:3819.25819
[29]	validation_0-mae:3736.06871
[30]	validation_0-mae:3656.47452
[31]	validation_0-mae:3590.59842
[32]	validation_0-mae:3516.92704
[33]	validation_0-mae:3458.28709
[34]	validation_0-mae:3402.13829
[35]	validation_0-mae:3339.63043
[36]	validation_0-mae:3289.85300
[37]	validation_0-mae:3247.03574
[38]	validation_0-mae:3207.33598
[39]	validation_0-mae:3168.13096
[40]	validation_0-mae:3128.64501
[41]	validation_0-mae:3096.65734
[42]	validation_0-mae:3037.96694
[43]	validation_0-mae:3007.97033
[44]	validation_0-mae:2979.18182
[45]	validation_0-mae:2936.78724
[46]	validation_0-mae:2912.96947
[47]	validation_0-mae:2883.50041
[48]	validation_0-mae:2863.92385
[49]	validation_0-mae:2837.13369
[50]	validation_0-mae:2804.22599
[51]	validation_0-mae:2785.34019
[52]	validation_0-mae:2773.19567
[53]	validation_0-mae:2756.75003
[54]	validation_0-mae:2723.49228
[55]	validation_0-mae:2707.52691
[56]	validation_0-mae:2689.38291
[57]	validation_0-mae:2667.97674
[58]	validation_0-mae:2649.42700
[59]	validation_0-mae:2635.94386
[60]	validation_0-mae:2627.79025
[61]	validation_0-mae:2613.62163
[62]	validation_0-mae:2601.01315
[63]	validation_0-mae:2590.25468
[64]	validation_0-mae:2574.86534
[65]	validation_0-mae:2568.34881
[66]	validation_0-mae:2557.84318
[67]	validation_0-mae:2548.82931
[68]	validation_0-mae:2539.27737
[69]	validation_0-mae:2533.16235
[70]	validation_0-mae:2523.75651
[71]	validation_0-mae:2516.50922
[72]	validation_0-mae:2502.87529
[73]	validation_0-mae:2494.37467
[74]	validation_0-mae:2488.27382
[75]	validation_0-mae:2475.74679
[76]	validation_0-mae:2467.72566
[77]	validation_0-mae:2456.79617
[78]	validation_0-mae:2448.90785
[79]	validation_0-mae:2446.46797
[80]	validation_0-mae:2440.05836
[81]	validation_0-mae:2431.36757
[82]	validation_0-mae:2424.61245
[83]	validation_0-mae:2421.79649
[84]	validation_0-mae:2416.59307
[85]	validation_0-mae:2409.28522
[86]	validation_0-mae:2404.06400
[87]	validation_0-mae:2396.77295
[88]	validation_0-mae:2385.18049
[89]	validation_0-mae:2376.73927
[90]	validation_0-mae:2374.64625
[91]	validation_0-mae:2373.18095
[92]	validation_0-mae:2365.26314
[93]	validation_0-mae:2357.41450
[94]	validation_0-mae:2354.10456
[95]	validation_0-mae:2348.04169
[96]	validation_0-mae:2340.70209
[97]	validation_0-mae:2335.99352
[98]	validation_0-mae:2333.05525
[99]	validation_0-mae:2330.38673
[100]	validation_0-mae:2325.38393
[101]	validation_0-mae:2321.36882
[102]	validation_0-mae:2315.07462
[103]	validation_0-mae:2309.77274
[104]	validation_0-mae:2303.90011
[105]	validation_0-mae:2296.34544
[106]	validation_0-mae:2294.76909
[107]	validation_0-mae:2291.97346
[108]	validation_0-mae:2288.14383
[109]	validation_0-mae:2284.11194
[110]	validation_0-mae:2282.87233
[111]	validation_0-mae:2283.41623
[112]	validation_0-mae:2280.30541
[113]	validation_0-mae:2280.01845
[114]	validation_0-mae:2278.67155
[115]	validation_0-mae:2273.31766
[116]	validation_0-mae:2269.66512
[117]	validation_0-mae:2265.65720
[118]	validation_0-mae:2264.22414
[119]	validation_0-mae:2261.68706
[120]	validation_0-mae:2258.10771
[121]	validation_0-mae:2257.18363
[122]	validation_0-mae:2253.77938
[123]	validation_0-mae:2249.29440
[124]	validation_0-mae:2246.45617
[125]	validation_0-mae:2244.34364
[126]	validation_0-mae:2240.18285
[127]	validation_0-mae:2237.28182
[128]	validation_0-mae:2235.83904
[129]	validation_0-mae:2232.90903
[130]	validation_0-mae:2233.41593
[131]	validation_0-mae:2232.58850
[132]	validation_0-mae:2231.11638
[133]	validation_0-mae:2229.22036
[134]	validation_0-mae:2223.20255
[135]	validation_0-mae:2223.02934
[136]	validation_0-mae:2221.25280
[137]	validation_0-mae:2218.97408
[138]	validation_0-mae:2219.42878
[139]	validation_0-mae:2218.00032
[140]	validation_0-mae:2217.65248
[141]	validation_0-mae:2216.04968
[142]	validation_0-mae:2216.14181
[143]	validation_0-mae:2213.19967
[144]	validation_0-mae:2211.32454
[145]	validation_0-mae:2211.46578
[146]	validation_0-mae:2209.36952
[147]	validation_0-mae:2207.05613
[148]	validation_0-mae:2205.75399
[149]	validation_0-mae:2203.21378
[150]	validation_0-mae:2202.45698
[151]	validation_0-mae:2201.09016
[152]	validation_0-mae:2200.75278
[153]	validation_0-mae:2199.12310
[154]	validation_0-mae:2198.63294
[155]	validation_0-mae:2198.86019
[156]	validation_0-mae:2196.35112
[157]	validation_0-mae:2195.80069
[158]	validation_0-mae:2193.57718
[159]	validation_0-mae:2192.17478
[160]	validation_0-mae:2189.97198
[161]	validation_0-mae:2187.85239
[162]	validation_0-mae:2186.23637
[163]	validation_0-mae:2183.37474
[164]	validation_0-mae:2182.89043
[165]	validation_0-mae:2180.64697
[166]	validation_0-mae:2179.16820
[167]	validation_0-mae:2176.68049
[168]	validation_0-mae:2176.77157
[169]	validation_0-mae:2174.16877
[170]	validation_0-mae:2174.43088
[171]	validation_0-mae:2173.70601
[172]	validation_0-mae:2173.52227
[173]	validation_0-mae:2171.32290
[174]	validation_0-mae:2169.54476
[175]	validation_0-mae:2169.36235
[176]	validation_0-mae:2169.65714
[177]	validation_0-mae:2169.27487
[178]	validation_0-mae:2168.90526
[179]	validation_0-mae:2169.06401
[180]	validation_0-mae:2167.76501
[181]	validation_0-mae:2168.50938
[182]	validation_0-mae:2169.18807
[183]	validation_0-mae:2168.07790
[184]	validation_0-mae:2168.15610
[185]	validation_0-mae:2166.78094
[186]	validation_0-mae:2168.15711
[187]	validation_0-mae:2168.08604
[188]	validation_0-mae:2166.87030
[189]	validation_0-mae:2167.12290
[190]	validation_0-mae:2164.50958
[191]	validation_0-mae:2164.23035
[192]	validation_0-mae:2164.54387
[193]	validation_0-mae:2160.96576
[194]	validation_0-mae:2158.44756
[195]	validation_0-mae:2158.65352
[196]	validation_0-mae:2157.23401
[197]	validation_0-mae:2157.64103
[198]	validation_0-mae:2155.13004
[199]	validation_0-mae:2154.30602
[200]	validation_0-mae:2153.42142
[201]	validation_0-mae:2154.26286
[202]	validation_0-mae:2153.03223
[203]	validation_0-mae:2152.95905
[204]	validation_0-mae:2152.64985
[205]	validation_0-mae:2151.02224
[206]	validation_0-mae:2149.14550
[207]	validation_0-mae:2149.71213
[208]	validation_0-mae:2148.53874
[209]	validation_0-mae:2148.69805
[210]	validation_0-mae:2148.53208
[211]	validation_0-mae:2148.37621
[212]	validation_0-mae:2147.25725
[213]	validation_0-mae:2147.52891
[214]	validation_0-mae:2147.27170
[215]	validation_0-mae:2147.54230
[216]	validation_0-mae:2148.00942
[217]	validation_0-mae:2147.87611
[218]	validation_0-mae:2147.10294
[219]	validation_0-mae:2147.57957
[220]	validation_0-mae:2147.73858
[221]	validation_0-mae:2148.11098
[222]	validation_0-mae:2148.17366
[223]	validation_0-mae:2145.57260
[224]	validation_0-mae:2143.86978
[225]	validation_0-mae:2144.36059
[226]	validation_0-mae:2144.30488
[227]	validation_0-mae:2144.20785
[228]	validation_0-mae:2144.98055
[229]	validation_0-mae:2144.96689
[230]	validation_0-mae:2144.15597
[231]	validation_0-mae:2143.36176
[232]	validation_0-mae:2145.01097
[233]	validation_0-mae:2144.21957
[234]	validation_0-mae:2144.10603
[235]	validation_0-mae:2142.67553
[236]	validation_0-mae:2143.17608
[237]	validation_0-mae:2143.27335
[238]	validation_0-mae:2142.77333
[239]	validation_0-mae:2142.25621
[240]	validation_0-mae:2141.57199
[241]	validation_0-mae:2142.11712
[242]	validation_0-mae:2142.21603
[243]	validation_0-mae:2142.70010
[244]	validation_0-mae:2142.72978
[245]	validation_0-mae:2142.04468
[246]	validation_0-mae:2142.03686
[247]	validation_0-mae:2141.70274
[248]	validation_0-mae:2141.23472
[249]	validation_0-mae:2140.17216
[250]	validation_0-mae:2140.46660
[251]	validation_0-mae:2140.53937
[252]	validation_0-mae:2139.51719
[253]	validation_0-mae:2139.16187
[254]	validation_0-mae:2138.11698
[255]	validation_0-mae:2138.24045
[256]	validation_0-mae:2137.51798
[257]	validation_0-mae:2138.05770
[258]	validation_0-mae:2137.75823
[259]	validation_0-mae:2136.63489
[260]	validation_0-mae:2135.61451
[261]	validation_0-mae:2136.28955
[262]	validation_0-mae:2136.28366
[263]	validation_0-mae:2136.39387
[264]	validation_0-mae:2135.74576
[265]	validation_0-mae:2135.98818
[266]	validation_0-mae:2135.60068
[267]	validation_0-mae:2135.28743
[268]	validation_0-mae:2135.79177
[269]	validation_0-mae:2134.98072
[270]	validation_0-mae:2134.87743
[271]	validation_0-mae:2135.12911
[272]	validation_0-mae:2134.92812
[273]	validation_0-mae:2135.02807
[274]	validation_0-mae:2135.03763
[275]	validation_0-mae:2134.47196
[276]	validation_0-mae:2134.60740
[277]	validation_0-mae:2134.26770
[278]	validation_0-mae:2134.65691
[279]	validation_0-mae:2134.23255
[280]	validation_0-mae:2134.72807
[281]	validation_0-mae:2135.16821
[282]	validation_0-mae:2135.11749
[283]	validation_0-mae:2135.92516
[284]	validation_0-mae:2135.89165
[285]	validation_0-mae:2135.86316
[286]	validation_0-mae:2134.56754
[287]	validation_0-mae:2135.67233
[288]	validation_0-mae:2136.76051
[289]	validation_0-mae:2136.81892
[290]	validation_0-mae:2137.02960
[291]	validation_0-mae:2136.87172
[292]	validation_0-mae:2136.79538
[293]	validation_0-mae:2136.18955
[294]	validation_0-mae:2134.36373
[295]	validation_0-mae:2134.67489
[296]	validation_0-mae:2134.49812
[297]	validation_0-mae:2134.21714
[298]	validation_0-mae:2133.49637
[299]	validation_0-mae:2133.71731
[300]	validation_0-mae:2133.84893
[301]	validation_0-mae:2134.33151
[302]	validation_0-mae:2134.56512
[303]	validation_0-mae:2134.73015
[304]	validation_0-mae:2134.93415
[305]	validation_0-mae:2133.94099
[306]	validation_0-mae:2132.58503
[307]	validation_0-mae:2132.02091
[308]	validation_0-mae:2130.42502
[309]	validation_0-mae:2130.13246
[310]	validation_0-mae:2129.81508
[311]	validation_0-mae:2129.69971
[312]	validation_0-mae:2130.69614
[313]	validation_0-mae:2130.80004
[314]	validation_0-mae:2130.81105
[315]	validation_0-mae:2131.13280
[316]	validation_0-mae:2130.49932
[317]	validation_0-mae:2130.12877
[318]	validation_0-mae:2128.96406
[319]	validation_0-mae:2129.43607
[320]	validation_0-mae:2129.34255
[321]	validation_0-mae:2129.39975
[322]	validation_0-mae:2129.75239
[323]	validation_0-mae:2128.97457
[324]	validation_0-mae:2128.20985
[325]	validation_0-mae:2128.41063
[326]	validation_0-mae:2127.85162
[327]	validation_0-mae:2125.03580
[328]	validation_0-mae:2125.00638
[329]	validation_0-mae:2125.68771
[330]	validation_0-mae:2125.31766
[331]	validation_0-mae:2125.23260
[332]	validation_0-mae:2125.13735
[333]	validation_0-mae:2125.86570
[334]	validation_0-mae:2125.72735
[335]	validation_0-mae:2125.15366
[336]	validation_0-mae:2124.69895
[337]	validation_0-mae:2124.57627
[338]	validation_0-mae:2124.52542
[339]	validation_0-mae:2124.55083
[340]	validation_0-mae:2124.57049
[341]	validation_0-mae:2124.52643
[342]	validation_0-mae:2124.35585
[343]	validation_0-mae:2124.34713
[344]	validation_0-mae:2123.98005
[345]	validation_0-mae:2123.00724
[346]	validation_0-mae:2123.10955
[347]	validation_0-mae:2123.42433
[348]	validation_0-mae:2122.83480
[349]	validation_0-mae:2122.71437
[350]	validation_0-mae:2122.62317
[351]	validation_0-mae:2122.67233
[352]	validation_0-mae:2122.34618
[353]	validation_0-mae:2122.47525
[354]	validation_0-mae:2122.46966
[355]	validation_0-mae:2122.26994
[356]	validation_0-mae:2122.28219
[357]	validation_0-mae:2121.75500
[358]	validation_0-mae:2122.31331
[359]	validation_0-mae:2122.30099
[360]	validation_0-mae:2121.91006
[361]	validation_0-mae:2121.83460
[362]	validation_0-mae:2121.83790
[363]	validation_0-mae:2122.03928
[364]	validation_0-mae:2122.39582
[365]	validation_0-mae:2122.65789
[366]	validation_0-mae:2122.40330
[367]	validation_0-mae:2123.02878
[368]	validation_0-mae:2122.97346
[369]	validation_0-mae:2122.35843
[370]	validation_0-mae:2121.73202
[371]	validation_0-mae:2121.37887
[372]	validation_0-mae:2120.86915
[373]	validation_0-mae:2120.20523
[374]	validation_0-mae:2119.15262
[375]	validation_0-mae:2118.58605
[376]	validation_0-mae:2118.66884
[377]	validation_0-mae:2118.40330
[378]	validation_0-mae:2118.43575
[379]	validation_0-mae:2118.23854
[380]	validation_0-mae:2118.14354
[381]	validation_0-mae:2117.84138
[382]	validation_0-mae:2118.16330
[383]	validation_0-mae:2119.30767
[384]	validation_0-mae:2119.34760
[385]	validation_0-mae:2119.07902
[386]	validation_0-mae:2119.08736
[387]	validation_0-mae:2118.32711
[388]	validation_0-mae:2118.49891
[389]	validation_0-mae:2119.23035
[390]	validation_0-mae:2119.03110
[391]	validation_0-mae:2119.39727
[392]	validation_0-mae:2119.34125
[393]	validation_0-mae:2119.83486
[394]	validation_0-mae:2119.84680
[395]	validation_0-mae:2119.95360
[396]	validation_0-mae:2119.89775
[397]	validation_0-mae:2119.32368
[398]	validation_0-mae:2119.26076
[399]	validation_0-mae:2119.26553
[400]	validation_0-mae:2119.01937
[401]	validation_0-mae:2119.50826
[402]	validation_0-mae:2119.22974
[403]	validation_0-mae:2118.88749
[404]	validation_0-mae:2119.25869
[405]	validation_0-mae:2119.46393
[406]	validation_0-mae:2119.38755
[407]	validation_0-mae:2118.90791
[408]	validation_0-mae:2118.75657
[409]	validation_0-mae:2118.59415
[410]	validation_0-mae:2118.78220
[411]	validation_0-mae:2118.46624
[412]	validation_0-mae:2118.48614
[413]	validation_0-mae:2118.53917
[414]	validation_0-mae:2118.63239
[415]	validation_0-mae:2118.11747
[416]	validation_0-mae:2117.87044
[417]	validation_0-mae:2117.08959
[418]	validation_0-mae:2117.26685
[419]	validation_0-mae:2117.08589
[420]	validation_0-mae:2117.13825
[421]	validation_0-mae:2117.39786
[422]	validation_0-mae:2117.41587
[423]	validation_0-mae:2116.06416
[424]	validation_0-mae:2116.10852
[425]	validation_0-mae:2115.92629
[426]	validation_0-mae:2115.09158
[427]	validation_0-mae:2114.84107
[428]	validation_0-mae:2114.78397
[429]	validation_0-mae:2114.86728
[430]	validation_0-mae:2114.81835
[431]	validation_0-mae:2114.33860
[432]	validation_0-mae:2113.62214
[433]	validation_0-mae:2113.57888
[434]	validation_0-mae:2113.31969
[435]	validation_0-mae:2113.74613
[436]	validation_0-mae:2113.23254
[437]	validation_0-mae:2113.20780
[438]	validation_0-mae:2112.98156
[439]	validation_0-mae:2112.52430
[440]	validation_0-mae:2112.21981
[441]	validation_0-mae:2112.00827
[442]	validation_0-mae:2111.82455
[443]	validation_0-mae:2111.67027
[444]	validation_0-mae:2110.35650
[445]	validation_0-mae:2110.06104
[446]	validation_0-mae:2109.99246
[447]	validation_0-mae:2110.26534
[448]	validation_0-mae:2110.47904
[449]	validation_0-mae:2109.96799
[450]	validation_0-mae:2109.83790
[451]	validation_0-mae:2109.79359
[452]	validation_0-mae:2109.93386
[453]	validation_0-mae:2109.20718
[454]	validation_0-mae:2110.10609
[455]	validation_0-mae:2110.49137
[456]	validation_0-mae:2110.90422
[457]	validation_0-mae:2110.78387
[458]	validation_0-mae:2110.89333
[459]	validation_0-mae:2110.65056
[460]	validation_0-mae:2111.19951
[461]	validation_0-mae:2110.84225
[462]	validation_0-mae:2110.68048
[463]	validation_0-mae:2110.95463
[464]	validation_0-mae:2110.65361
[465]	validation_0-mae:2110.03935
[466]	validation_0-mae:2108.62632
[467]	validation_0-mae:2108.57607
[468]	validation_0-mae:2108.75787
[469]	validation_0-mae:2108.57290
[470]	validation_0-mae:2108.62210
[471]	validation_0-mae:2108.66862
[472]	validation_0-mae:2107.88045
[473]	validation_0-mae:2108.05364
[474]	validation_0-mae:2107.46102
[475]	validation_0-mae:2107.43250
[476]	validation_0-mae:2107.84472
[477]	validation_0-mae:2107.79752
[478]	validation_0-mae:2107.81114
[479]	validation_0-mae:2107.52876
[480]	validation_0-mae:2107.84522
[481]	validation_0-mae:2108.00195
[482]	validation_0-mae:2108.18015
[483]	validation_0-mae:2108.24476
[484]	validation_0-mae:2108.41159
[485]	validation_0-mae:2108.33641
[486]	validation_0-mae:2108.57172
[487]	validation_0-mae:2108.91638
[488]	validation_0-mae:2108.89909
[489]	validation_0-mae:2108.58183
[490]	validation_0-mae:2107.81586
[491]	validation_0-mae:2107.47221
[492]	validation_0-mae:2107.79355
[493]	validation_0-mae:2107.19536
[494]	validation_0-mae:2107.38536
[495]	validation_0-mae:2107.47470
[496]	validation_0-mae:2107.74427
[497]	validation_0-mae:2107.69913
[498]	validation_0-mae:2107.63448
[499]	validation_0-mae:2107.83400
[500]	validation_0-mae:2107.67366
[501]	validation_0-mae:2107.38900
[502]	validation_0-mae:2107.34146
[503]	validation_0-mae:2106.60948
[504]	validation_0-mae:2106.92324
[505]	validation_0-mae:2106.28678
[506]	validation_0-mae:2106.53263
[507]	validation_0-mae:2106.07859
[508]	validation_0-mae:2105.89026
[509]	validation_0-mae:2105.99793
[510]	validation_0-mae:2106.00300
[511]	validation_0-mae:2105.72897
[512]	validation_0-mae:2106.17852
[513]	validation_0-mae:2106.30576
[514]	validation_0-mae:2106.29094
[515]	validation_0-mae:2106.17348
[516]	validation_0-mae:2106.34648
[517]	validation_0-mae:2106.40974
[518]	validation_0-mae:2106.71604
[519]	validation_0-mae:2106.73189
[520]	validation_0-mae:2106.59435
[521]	validation_0-mae:2105.87365
[522]	validation_0-mae:2105.84916
[523]	validation_0-mae:2105.64777
[524]	validation_0-mae:2105.46589
[525]	validation_0-mae:2105.59863
[526]	validation_0-mae:2105.55224
[527]	validation_0-mae:2105.85904
[528]	validation_0-mae:2105.00196
[529]	validation_0-mae:2105.44832
[530]	validation_0-mae:2104.87215
[531]	validation_0-mae:2104.59523
[532]	validation_0-mae:2104.42990
[533]	validation_0-mae:2104.49369
[534]	validation_0-mae:2104.32002
[535]	validation_0-mae:2104.08625
[536]	validation_0-mae:2104.25724
[537]	validation_0-mae:2103.99918
[538]	validation_0-mae:2104.33967
[539]	validation_0-mae:2104.38819
[540]	validation_0-mae:2104.39844
[541]	validation_0-mae:2104.40381
[542]	validation_0-mae:2104.36054
[543]	validation_0-mae:2104.25282
[544]	validation_0-mae:2104.15400
[545]	validation_0-mae:2104.24282
[546]	validation_0-mae:2104.48243
[547]	validation_0-mae:2104.64713
[548]	validation_0-mae:2104.49796
[549]	validation_0-mae:2103.91319
[550]	validation_0-mae:2103.62926
[551]	validation_0-mae:2103.86904
[552]	validation_0-mae:2103.87191
[553]	validation_0-mae:2103.87587
[554]	validation_0-mae:2103.76911
[555]	validation_0-mae:2103.73279
[556]	validation_0-mae:2103.77411
[557]	validation_0-mae:2104.01432
[558]	validation_0-mae:2103.63754
[559]	validation_0-mae:2103.97514
[560]	validation_0-mae:2104.11597
[561]	validation_0-mae:2104.08948
[562]	validation_0-mae:2104.14989
[563]	validation_0-mae:2104.01073
[564]	validation_0-mae:2104.18347
[565]	validation_0-mae:2104.02501
[566]	validation_0-mae:2103.95805
[567]	validation_0-mae:2103.63316
[568]	validation_0-mae:2103.59837
[569]	validation_0-mae:2103.68064
[570]	validation_0-mae:2103.33503
[571]	validation_0-mae:2103.42134
[0]	validation_0-mae:12444.21738
[1]	validation_0-mae:11710.55466
[2]	validation_0-mae:11053.65519
[3]	validation_0-mae:10423.37988
[4]	validation_0-mae:9883.90834
[5]	validation_0-mae:9369.65921
[6]	validation_0-mae:8915.02027
[7]	validation_0-mae:8508.92844
[8]	validation_0-mae:8132.48411
[9]	validation_0-mae:7784.92539
[10]	validation_0-mae:7473.37642
[11]	validation_0-mae:7180.78361
[12]	validation_0-mae:6920.03376
[13]	validation_0-mae:6656.32386
[14]	validation_0-mae:6426.52253
[15]	validation_0-mae:6202.99166
[16]	validation_0-mae:5971.46554
[17]	validation_0-mae:5765.29278
[18]	validation_0-mae:5569.85912
[19]	validation_0-mae:5399.35855
[20]	validation_0-mae:5227.06437
[21]	validation_0-mae:5070.58546
[22]	validation_0-mae:4921.99285
[23]	validation_0-mae:4779.91003
[24]	validation_0-mae:4637.28560
[25]	validation_0-mae:4501.78169
[26]	validation_0-mae:4391.84312
[27]	validation_0-mae:4283.66202
[28]	validation_0-mae:4174.72344
[29]	validation_0-mae:4081.66396
[30]	validation_0-mae:4009.05701
[31]	validation_0-mae:3914.26178
[32]	validation_0-mae:3827.83781
[33]	validation_0-mae:3746.08824
[34]	validation_0-mae:3672.72751

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[35]	validation_0-mae:3613.60373
[36]	validation_0-mae:3553.87661
[37]	validation_0-mae:3491.70028
[38]	validation_0-mae:3438.53553
[39]	validation_0-mae:3393.00450
[40]	validation_0-mae:3353.21099
[41]	validation_0-mae:3309.07961
[42]	validation_0-mae:3271.34015
[43]	validation_0-mae:3231.33638
[44]	validation_0-mae:3193.61265
[45]	validation_0-mae:3162.69330
[46]	validation_0-mae:3135.53801
[47]	validation_0-mae:3104.07970
[48]	validation_0-mae:3073.74816
[49]	validation_0-mae:3048.35922
[50]	validation_0-mae:3012.60806
[51]	validation_0-mae:2971.75213
[52]	validation_0-mae:2949.39312
[53]	validation_0-mae:2926.06406
[54]	validation_0-mae:2900.69733
[55]	validation_0-mae:2868.26663
[56]	validation_0-mae:2846.64867
[57]	validation_0-mae:2823.23370
[58]	validation_0-mae:2806.92897
[59]	validation_0-mae:2789.96028
[60]	validation_0-mae:2776.20528
[61]	validation_0-mae:2760.09310
[62]	validation_0-mae:2749.16628
[63]	validation_0-mae:2733.15771
[64]	validation_0-mae:2720.71505
[65]	validation_0-mae:2696.77784
[66]	validation_0-mae:2676.98942
[67]	validation_0-mae:2663.00829
[68]	validation_0-mae:2650.49764
[69]	validation_0-mae:2642.66839
[70]	validation_0-mae:2625.99372
[71]	validation_0-mae:2617.89400
[72]	validation_0-mae:2604.80492
[73]	validation_0-mae:2590.16447
[74]	validation_0-mae:2575.29060
[75]	validation_0-mae:2567.71088
[76]	validation_0-mae:2562.78798
[77]	validation_0-mae:2553.01963
[78]	validation_0-mae:2542.95982
[79]	validation_0-mae:2536.43313
[80]	validation_0-mae:2524.85079
[81]	validation_0-mae:2517.19617
[82]	validation_0-mae:2510.90876
[83]	validation_0-mae:2502.86999
[84]	validation_0-mae:2497.79304
[85]	validation_0-mae:2490.30089
[86]	validation_0-mae:2485.48988
[87]	validation_0-mae:2481.10227
[88]	validation_0-mae:2476.32501
[89]	validation_0-mae:2470.17587
[90]	validation_0-mae:2462.14297
[91]	validation_0-mae:2456.05076
[92]	validation_0-mae:2451.31929
[93]	validation_0-mae:2442.93161
[94]	validation_0-mae:2435.37484
[95]	validation_0-mae:2431.03657
[96]	validation_0-mae:2428.01845
[0]	validation_0-mae:12499.16984
[1]	validation_0-mae:11809.83410
[2]	validation_0-mae:11184.63067
[3]	validation_0-mae:10593.59216
[4]	validation_0-mae:10071.96791
[5]	validation_0-mae:9588.25176
[6]	validation_0-mae:9149.99250
[7]	validation_0-mae:8743.48008
[8]	validation_0-mae:8381.09757
[9]	validation_0-mae:8042.17519
[10]	validation_0-mae:7743.46726

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[0]	validation_0-mae:12401.16298
[1]	validation_0-mae:11630.63163
[2]	validation_0-mae:10927.85813
[3]	validation_0-mae:10277.69801
[4]	validation_0-mae:9708.61330
[5]	validation_0-mae:9183.64765
[6]	validation_0-mae:8729.91512
[7]	validation_0-mae:8303.46307
[8]	validation_0-mae:7920.47225
[9]	validation_0-mae:7572.96643
[10]	validation_0-mae:7260.81266
[11]	validation_0-mae:6961.28253
[12]	validation_0-mae:6653.38297
[13]	validation_0-mae:6392.17479
[14]	validation_0-mae:6158.27127
[15]	validation_0-mae:5919.13878
[16]	validation_0-mae:5701.13953
[17]	validation_0-mae:5506.03350
[18]	validation_0-mae:5323.93589
[19]	validation_0-mae:5137.69156
[20]	validation_0-mae:4968.03943
[21]	validation_0-mae:4816.02802
[22]	validation_0-mae:4680.93067
[23]	validation_0-mae:4557.43324
[24]	validation_0-mae:4428.34126
[25]	validation_0-mae:4310.48580
[26]	validation_0-mae:4191.22732
[27]	validation_0-mae:4098.24539
[28]	validation_0-mae:4009.63087
[29]	validation_0-mae:3917.85171
[30]	validation_0-mae:3836.68700
[31]	validation_0-mae:3767.00180
[32]	validation_0-mae:3691.26855
[33]	validation_0-mae:3618.39337
[34]	validation_0-mae:3551.13999
[35]	validation_0-mae:3490.47603
[36]	validation_0-mae:3432.54068
[37]	validation_0-mae:3385.39949
[38]	validation_0-mae:3346.76298
[39]	validation_0-mae:3306.66827
[40]	validation_0-mae:3267.46630
[41]	validation_0-mae:3214.77299
[42]	validation_0-mae:3183.14699
[43]	validation_0-mae:3154.42616
[44]	validation_0-mae:3117.41018
[45]	validation_0-mae:3087.64192
[46]	validation_0-mae:3043.33851
[47]	validation_0-mae:3015.55000
[48]	validation_0-mae:2996.67981
[49]	validation_0-mae:2971.04044
[50]	validation_0-mae:2934.87333
[51]	validation_0-mae:2913.76479
[52]	validation_0-mae:2890.42222
[53]	validation_0-mae:2865.51472
[54]	validation_0-mae:2849.83255
[55]	validation_0-mae:2830.92301
[56]	validation_0-mae:2814.77350
[57]	validation_0-mae:2798.28217
[58]	validation_0-mae:2776.04216
[59]	validation_0-mae:2758.87375
[60]	validation_0-mae:2740.23289
[61]	validation_0-mae:2726.51273
[62]	validation_0-mae:2712.00553
[63]	validation_0-mae:2693.93306
[64]	validation_0-mae:2680.62845
[65]	validation_0-mae:2666.96162
[66]	validation_0-mae:2649.62350
[67]	validation_0-mae:2643.63772
[68]	validation_0-mae:2629.12432
[69]	validation_0-mae:2616.80760
[70]	validation_0-mae:2610.51393
[71]	validation_0-mae:2597.10094
[72]	validation_0-mae:2589.44973
[73]	validation_0-mae:2576.10507
[74]	validation_0-mae:2561.72930
[75]	validation_0-mae:2551.68725
[76]	validation_0-mae:2540.88351
[77]	validation_0-mae:2535.81456
[78]	validation_0-mae:2529.50719
[79]	validation_0-mae:2521.35939
[80]	validation_0-mae:2511.98625
[81]	validation_0-mae:2509.78198
[82]	validation_0-mae:2500.75993
[83]	validation_0-mae:2494.15983
[84]	validation_0-mae:2486.40052
[85]	validation_0-mae:2478.11092
[86]	validation_0-mae:2469.49055
[87]	validation_0-mae:2461.66345
[88]	validation_0-mae:2453.74191
[89]	validation_0-mae:2447.38550
[90]	validation_0-mae:2440.79724
[91]	validation_0-mae:2434.24924
[92]	validation_0-mae:2426.82461
[93]	validation_0-mae:2422.08720
[94]	validation_0-mae:2414.67840
[95]	validation_0-mae:2406.11466
[96]	validation_0-mae:2397.49205
[97]	validation_0-mae:2393.79203
[98]	validation_0-mae:2388.53678
[99]	validation_0-mae:2380.56866
[100]	validation_0-mae:2373.35613
[101]	validation_0-mae:2372.26144
[102]	validation_0-mae:2367.96467
[103]	validation_0-mae:2366.62010
[104]	validation_0-mae:2363.50294
[105]	validation_0-mae:2357.94954
[106]	validation_0-mae:2353.28342
[107]	validation_0-mae:2352.12044
[108]	validation_0-mae:2348.60534
[109]	validation_0-mae:2342.43792
[110]	validation_0-mae:2338.32610
[111]	validation_0-mae:2329.89517
[112]	validation_0-mae:2324.60119
[113]	validation_0-mae:2316.14157
[114]	validation_0-mae:2311.50634
[115]	validation_0-mae:2309.38732
[116]	validation_0-mae:2307.78115
[117]	validation_0-mae:2302.61035
[118]	validation_0-mae:2302.09953
[119]	validation_0-mae:2301.19118
[120]	validation_0-mae:2299.08440
[121]	validation_0-mae:2296.39451
[122]	validation_0-mae:2292.69161
[123]	validation_0-mae:2293.50535
[124]	validation_0-mae:2293.03452
[125]	validation_0-mae:2291.25135
[126]	validation_0-mae:2290.97930
[127]	validation_0-mae:2285.91183
[128]	validation_0-mae:2284.97454
[129]	validation_0-mae:2284.50183
[130]	validation_0-mae:2282.78108
[131]	validation_0-mae:2278.35806
[132]	validation_0-mae:2274.98569
[133]	validation_0-mae:2272.09868
[134]	validation_0-mae:2269.50309
[135]	validation_0-mae:2268.37359
[136]	validation_0-mae:2264.44238
[137]	validation_0-mae:2262.53331
[138]	validation_0-mae:2258.65446
[139]	validation_0-mae:2257.91715
[140]	validation_0-mae:2254.17971
[141]	validation_0-mae:2254.35776
[142]	validation_0-mae:2248.94340
[143]	validation_0-mae:2244.60736
[144]	validation_0-mae:2244.42105
[145]	validation_0-mae:2242.16693
[146]	validation_0-mae:2241.32464
[147]	validation_0-mae:2240.64132
[148]	validation_0-mae:2239.12376
[149]	validation_0-mae:2238.84761
[150]	validation_0-mae:2236.27385
[151]	validation_0-mae:2234.52503
[152]	validation_0-mae:2233.89240
[153]	validation_0-mae:2230.47928
[154]	validation_0-mae:2228.65698
[155]	validation_0-mae:2226.21011
[156]	validation_0-mae:2222.31576
[157]	validation_0-mae:2220.19764
[158]	validation_0-mae:2218.77822
[159]	validation_0-mae:2218.00765
[160]	validation_0-mae:2217.00068
[161]	validation_0-mae:2215.68885
[162]	validation_0-mae:2215.40486
[163]	validation_0-mae:2212.98336
[164]	validation_0-mae:2212.73593
[165]	validation_0-mae:2211.44543
[166]	validation_0-mae:2211.06084
[167]	validation_0-mae:2211.00760
[168]	validation_0-mae:2210.06892
[169]	validation_0-mae:2207.88258
[170]	validation_0-mae:2206.09457
[171]	validation_0-mae:2204.78775
[172]	validation_0-mae:2203.33817
[173]	validation_0-mae:2202.28471
[174]	validation_0-mae:2202.31411
[175]	validation_0-mae:2199.87138
[176]	validation_0-mae:2197.94663
[177]	validation_0-mae:2195.76905
[178]	validation_0-mae:2194.19936
[179]	validation_0-mae:2193.57929
[180]	validation_0-mae:2191.57055
[181]	validation_0-mae:2188.95637
[182]	validation_0-mae:2188.84070
[183]	validation_0-mae:2189.42717
[184]	validation_0-mae:2188.84549
[185]	validation_0-mae:2189.51718
[186]	validation_0-mae:2188.16748
[187]	validation_0-mae:2188.55494
[188]	validation_0-mae:2187.66788
[189]	validation_0-mae:2183.72531
[190]	validation_0-mae:2182.21630
[191]	validation_0-mae:2182.44889
[192]	validation_0-mae:2183.11130
[193]	validation_0-mae:2182.30929
[194]	validation_0-mae:2181.60264
[195]	validation_0-mae:2181.59445
[196]	validation_0-mae:2181.31691
[197]	validation_0-mae:2181.48238
[198]	validation_0-mae:2180.69030
[199]	validation_0-mae:2180.65778
[200]	validation_0-mae:2181.14367
[201]	validation_0-mae:2178.15496
[202]	validation_0-mae:2179.29377
[203]	validation_0-mae:2178.00036
[204]	validation_0-mae:2177.49587
[205]	validation_0-mae:2176.99146
[206]	validation_0-mae:2175.26269
[207]	validation_0-mae:2174.11082
[208]	validation_0-mae:2174.36861
[209]	validation_0-mae:2174.89707
[210]	validation_0-mae:2174.54609
[211]	validation_0-mae:2174.65892
[212]	validation_0-mae:2174.22927
[213]	validation_0-mae:2170.84081
[214]	validation_0-mae:2169.71527
[215]	validation_0-mae:2167.68621
[216]	validation_0-mae:2165.61336
[217]	validation_0-mae:2164.73313
[218]	validation_0-mae:2163.97317
[219]	validation_0-mae:2161.70410
[220]	validation_0-mae:2158.81183
[221]	validation_0-mae:2157.43634
[222]	validation_0-mae:2156.18636
[223]	validation_0-mae:2155.20856
[224]	validation_0-mae:2154.39546
[225]	validation_0-mae:2152.06758
[226]	validation_0-mae:2151.22620
[227]	validation_0-mae:2149.22452
[228]	validation_0-mae:2148.45943
[229]	validation_0-mae:2148.04884
[230]	validation_0-mae:2146.96252
[231]	validation_0-mae:2146.68976
[232]	validation_0-mae:2146.62500
[233]	validation_0-mae:2144.59678
[234]	validation_0-mae:2144.46503
[235]	validation_0-mae:2144.23364
[236]	validation_0-mae:2144.11794
[237]	validation_0-mae:2143.63048
[238]	validation_0-mae:2144.17670
[239]	validation_0-mae:2144.22958
[240]	validation_0-mae:2144.17692
[241]	validation_0-mae:2144.85125
[242]	validation_0-mae:2144.24287
[243]	validation_0-mae:2144.68083
[244]	validation_0-mae:2144.37521
[245]	validation_0-mae:2142.82119
[246]	validation_0-mae:2142.08281
[247]	validation_0-mae:2142.22390
[248]	validation_0-mae:2140.74017
[249]	validation_0-mae:2140.89593
[250]	validation_0-mae:2139.92044
[251]	validation_0-mae:2138.80535
[252]	validation_0-mae:2138.72361
[253]	validation_0-mae:2138.31373
[254]	validation_0-mae:2138.15224
[255]	validation_0-mae:2136.35653
[256]	validation_0-mae:2136.00035
[257]	validation_0-mae:2135.23352
[258]	validation_0-mae:2133.98869
[259]	validation_0-mae:2134.07058
[260]	validation_0-mae:2134.20327
[261]	validation_0-mae:2133.77781
[262]	validation_0-mae:2132.51506
[263]	validation_0-mae:2132.13708
[264]	validation_0-mae:2132.05027
[265]	validation_0-mae:2131.72920
[266]	validation_0-mae:2130.94988
[267]	validation_0-mae:2130.66747
[268]	validation_0-mae:2131.54418
[269]	validation_0-mae:2131.19972
[270]	validation_0-mae:2131.41544
[271]	validation_0-mae:2131.71434
[272]	validation_0-mae:2130.84789
[273]	validation_0-mae:2130.72214
[274]	validation_0-mae:2130.41574
[275]	validation_0-mae:2130.45341
[276]	validation_0-mae:2130.53552
[277]	validation_0-mae:2130.54606
[278]	validation_0-mae:2130.46879
[279]	validation_0-mae:2129.81195
[280]	validation_0-mae:2129.12469
[281]	validation_0-mae:2128.36903
[282]	validation_0-mae:2128.40073
[283]	validation_0-mae:2128.03496
[284]	validation_0-mae:2126.89904
[285]	validation_0-mae:2125.24164
[286]	validation_0-mae:2125.20753
[287]	validation_0-mae:2124.85394
[288]	validation_0-mae:2124.80423
[289]	validation_0-mae:2124.98941
[290]	validation_0-mae:2124.56442
[291]	validation_0-mae:2124.61728
[292]	validation_0-mae:2124.28821
[293]	validation_0-mae:2124.07859
[294]	validation_0-mae:2122.62395
[295]	validation_0-mae:2122.85478
[296]	validation_0-mae:2122.33604
[297]	validation_0-mae:2120.98857
[298]	validation_0-mae:2121.13632
[299]	validation_0-mae:2120.68867
[300]	validation_0-mae:2120.29382
[301]	validation_0-mae:2119.13900
[302]	validation_0-mae:2119.47277
[303]	validation_0-mae:2117.52197
[304]	validation_0-mae:2117.97399
[305]	validation_0-mae:2118.45008
[306]	validation_0-mae:2118.73938
[307]	validation_0-mae:2118.82979
[308]	validation_0-mae:2119.55745
[309]	validation_0-mae:2120.02033
[310]	validation_0-mae:2119.53437
[311]	validation_0-mae:2119.22578
[312]	validation_0-mae:2119.06997
[313]	validation_0-mae:2119.19666
[314]	validation_0-mae:2119.46778
[315]	validation_0-mae:2119.41219
[316]	validation_0-mae:2118.91826
[317]	validation_0-mae:2118.90862
[318]	validation_0-mae:2117.75496
[319]	validation_0-mae:2117.89334
[320]	validation_0-mae:2118.25667
[321]	validation_0-mae:2117.81156
[322]	validation_0-mae:2117.67348
[323]	validation_0-mae:2117.88836
[324]	validation_0-mae:2118.16298
[325]	validation_0-mae:2117.62492
[326]	validation_0-mae:2117.67885
[327]	validation_0-mae:2118.28768
[328]	validation_0-mae:2118.39894
[329]	validation_0-mae:2118.61685
[330]	validation_0-mae:2119.21438
[331]	validation_0-mae:2119.09735
[332]	validation_0-mae:2120.04589
[333]	validation_0-mae:2120.46955
[334]	validation_0-mae:2120.36527
[335]	validation_0-mae:2120.36559
[336]	validation_0-mae:2118.13742
[337]	validation_0-mae:2118.38290
[338]	validation_0-mae:2117.62838
[339]	validation_0-mae:2118.26195
[340]	validation_0-mae:2118.37557
[341]	validation_0-mae:2117.63587
[342]	validation_0-mae:2116.30199
[343]	validation_0-mae:2116.58856
[344]	validation_0-mae:2115.78375
[345]	validation_0-mae:2115.51145
[346]	validation_0-mae:2115.17621
[347]	validation_0-mae:2115.41859
[348]	validation_0-mae:2114.95124
[349]	validation_0-mae:2115.84638
[350]	validation_0-mae:2115.58960
[351]	validation_0-mae:2115.84749
[352]	validation_0-mae:2116.47803
[353]	validation_0-mae:2115.27399
[354]	validation_0-mae:2114.75886
[355]	validation_0-mae:2115.26750
[356]	validation_0-mae:2114.89207
[357]	validation_0-mae:2114.32587
[358]	validation_0-mae:2114.03274
[359]	validation_0-mae:2113.72250
[360]	validation_0-mae:2113.30032
[361]	validation_0-mae:2114.05466
[362]	validation_0-mae:2113.24878
[363]	validation_0-mae:2114.01285
[364]	validation_0-mae:2113.29142
[365]	validation_0-mae:2111.82044
[366]	validation_0-mae:2111.23593
[367]	validation_0-mae:2110.92873
[368]	validation_0-mae:2110.56086
[369]	validation_0-mae:2110.36839
[370]	validation_0-mae:2110.74616
[371]	validation_0-mae:2110.84826
[372]	validation_0-mae:2111.14933
[373]	validation_0-mae:2111.68294
[374]	validation_0-mae:2111.88462
[375]	validation_0-mae:2111.06250
[376]	validation_0-mae:2111.61124
[377]	validation_0-mae:2111.76603
[378]	validation_0-mae:2111.94281
[379]	validation_0-mae:2112.36440
[380]	validation_0-mae:2112.49821
[381]	validation_0-mae:2112.72043
[382]	validation_0-mae:2112.71995
[383]	validation_0-mae:2112.34534
[384]	validation_0-mae:2111.93945
[385]	validation_0-mae:2111.83780
[386]	validation_0-mae:2112.23733
[387]	validation_0-mae:2111.28882
[388]	validation_0-mae:2110.92474
[389]	validation_0-mae:2110.39502
[390]	validation_0-mae:2109.90595
[391]	validation_0-mae:2108.86733
[392]	validation_0-mae:2108.53461
[393]	validation_0-mae:2108.68139
[394]	validation_0-mae:2108.31664
[395]	validation_0-mae:2107.93915
[396]	validation_0-mae:2107.94937
[397]	validation_0-mae:2108.38868
[398]	validation_0-mae:2107.11824
[399]	validation_0-mae:2107.21347
[400]	validation_0-mae:2107.25492
[401]	validation_0-mae:2107.24162
[402]	validation_0-mae:2106.87398
[403]	validation_0-mae:2106.70329
[404]	validation_0-mae:2107.11641
[405]	validation_0-mae:2107.11208
[406]	validation_0-mae:2107.35352
[407]	validation_0-mae:2107.45066
[408]	validation_0-mae:2106.14659
[409]	validation_0-mae:2105.81962
[410]	validation_0-mae:2105.71387
[411]	validation_0-mae:2105.74747
[412]	validation_0-mae:2106.19495
[413]	validation_0-mae:2106.70974
[414]	validation_0-mae:2106.99718
[415]	validation_0-mae:2107.22248
[416]	validation_0-mae:2107.33321
[417]	validation_0-mae:2107.60650
[418]	validation_0-mae:2107.48802
[419]	validation_0-mae:2107.38287
[420]	validation_0-mae:2107.16271
[421]	validation_0-mae:2106.69275
[422]	validation_0-mae:2106.52611
[423]	validation_0-mae:2106.03457
[424]	validation_0-mae:2105.67962
[425]	validation_0-mae:2105.52840
[426]	validation_0-mae:2105.04732
[427]	validation_0-mae:2105.01828
[428]	validation_0-mae:2104.71981
[429]	validation_0-mae:2104.84804
[430]	validation_0-mae:2104.21694
[431]	validation_0-mae:2104.45390
[432]	validation_0-mae:2104.18568
[433]	validation_0-mae:2104.51852
[434]	validation_0-mae:2103.76311
[435]	validation_0-mae:2103.53981
[436]	validation_0-mae:2103.75857
[437]	validation_0-mae:2103.51562
[438]	validation_0-mae:2104.35525
[439]	validation_0-mae:2104.21458
[440]	validation_0-mae:2103.58751
[441]	validation_0-mae:2103.18150
[442]	validation_0-mae:2102.79972
[443]	validation_0-mae:2103.27740
[444]	validation_0-mae:2103.71272
[445]	validation_0-mae:2103.57035
[446]	validation_0-mae:2103.41581
[447]	validation_0-mae:2103.27216
[448]	validation_0-mae:2103.62683
[449]	validation_0-mae:2103.47075
[450]	validation_0-mae:2104.21589
[451]	validation_0-mae:2104.30426
[452]	validation_0-mae:2104.21091
[453]	validation_0-mae:2103.54329
[454]	validation_0-mae:2102.60442
[455]	validation_0-mae:2103.13171
[456]	validation_0-mae:2102.48539
[457]	validation_0-mae:2102.82398
[458]	validation_0-mae:2102.84615
[459]	validation_0-mae:2102.78672
[460]	validation_0-mae:2102.91380
[461]	validation_0-mae:2103.33993
[462]	validation_0-mae:2103.28147
[463]	validation_0-mae:2103.49696
[464]	validation_0-mae:2103.59440
[465]	validation_0-mae:2102.74104
[466]	validation_0-mae:2103.05543
[467]	validation_0-mae:2103.16066
[468]	validation_0-mae:2102.65329
[469]	validation_0-mae:2101.79663
[470]	validation_0-mae:2101.83417
[471]	validation_0-mae:2101.69248
[472]	validation_0-mae:2100.87327
[473]	validation_0-mae:2100.14693
[474]	validation_0-mae:2099.61170
[475]	validation_0-mae:2099.05740
[476]	validation_0-mae:2097.92512
[477]	validation_0-mae:2097.56596
[478]	validation_0-mae:2097.72968
[479]	validation_0-mae:2097.42031
[480]	validation_0-mae:2096.92160
[481]	validation_0-mae:2096.89274
[482]	validation_0-mae:2096.85635
[483]	validation_0-mae:2096.82538
[484]	validation_0-mae:2096.83468
[485]	validation_0-mae:2096.58610
[486]	validation_0-mae:2096.76191
[487]	validation_0-mae:2096.43857
[488]	validation_0-mae:2096.51535
[489]	validation_0-mae:2096.16356
[490]	validation_0-mae:2095.91310
[491]	validation_0-mae:2096.01690
[492]	validation_0-mae:2095.03941
[493]	validation_0-mae:2095.51521
[494]	validation_0-mae:2095.40669
[495]	validation_0-mae:2095.61193
[496]	validation_0-mae:2095.18399
[497]	validation_0-mae:2094.69729
[498]	validation_0-mae:2094.33703
[499]	validation_0-mae:2094.48789
[500]	validation_0-mae:2094.39805
[501]	validation_0-mae:2094.43745
[502]	validation_0-mae:2094.49874
[503]	validation_0-mae:2094.65463
[504]	validation_0-mae:2094.76700
[505]	validation_0-mae:2095.02753
[506]	validation_0-mae:2094.99690
[507]	validation_0-mae:2095.06942
[508]	validation_0-mae:2094.68180
[509]	validation_0-mae:2094.30592
[510]	validation_0-mae:2094.35401
[511]	validation_0-mae:2094.45579
[512]	validation_0-mae:2094.71286
[513]	validation_0-mae:2094.74495
[514]	validation_0-mae:2094.30265
[515]	validation_0-mae:2094.54752
[516]	validation_0-mae:2094.36906
[517]	validation_0-mae:2093.88944
[518]	validation_0-mae:2094.03841
[519]	validation_0-mae:2094.23683
[520]	validation_0-mae:2094.38671
[521]	validation_0-mae:2094.02362
[522]	validation_0-mae:2093.22049
[523]	validation_0-mae:2093.36079
[524]	validation_0-mae:2093.59618
[525]	validation_0-mae:2093.34671
[526]	validation_0-mae:2093.38794
[527]	validation_0-mae:2093.45888
[528]	validation_0-mae:2093.05520
[529]	validation_0-mae:2093.35986
[530]	validation_0-mae:2093.56026
[531]	validation_0-mae:2093.86257
[532]	validation_0-mae:2094.18282
[533]	validation_0-mae:2094.58029
[534]	validation_0-mae:2094.34012
[535]	validation_0-mae:2094.67231
[536]	validation_0-mae:2094.40362
[537]	validation_0-mae:2093.93731
[538]	validation_0-mae:2093.80144
[539]	validation_0-mae:2094.13445
[540]	validation_0-mae:2093.80260
[541]	validation_0-mae:2093.52873
[542]	validation_0-mae:2093.53212
[543]	validation_0-mae:2093.71770
[544]	validation_0-mae:2093.48236
[545]	validation_0-mae:2093.46883
[546]	validation_0-mae:2093.69073
[547]	validation_0-mae:2093.83609
[548]	validation_0-mae:2093.77477
[549]	validation_0-mae:2093.84195
[550]	validation_0-mae:2093.83296
[551]	validation_0-mae:2093.98501
[552]	validation_0-mae:2093.94567
[553]	validation_0-mae:2093.92607
[554]	validation_0-mae:2094.05742
[555]	validation_0-mae:2093.32911
[556]	validation_0-mae:2093.29200
[557]	validation_0-mae:2093.38667
[558]	validation_0-mae:2093.30010
[559]	validation_0-mae:2093.25527
[560]	validation_0-mae:2093.27916
[561]	validation_0-mae:2093.21243
[562]	validation_0-mae:2092.90775
[563]	validation_0-mae:2092.82532
[564]	validation_0-mae:2092.86804
[565]	validation_0-mae:2093.01644
[566]	validation_0-mae:2093.29281
[567]	validation_0-mae:2093.57521
[568]	validation_0-mae:2093.16525
[569]	validation_0-mae:2093.20655
[570]	validation_0-mae:2093.30559
[571]	validation_0-mae:2093.54093
[572]	validation_0-mae:2093.47167
[573]	validation_0-mae:2093.28250
[574]	validation_0-mae:2093.32572
[575]	validation_0-mae:2093.38757
[576]	validation_0-mae:2093.51273
[577]	validation_0-mae:2093.47193
[578]	validation_0-mae:2093.12061
[579]	validation_0-mae:2093.21950
[580]	validation_0-mae:2093.19972
[581]	validation_0-mae:2092.90811
[582]	validation_0-mae:2092.91215
[583]	validation_0-mae:2092.62331
[584]	validation_0-mae:2092.56965
[585]	validation_0-mae:2091.96774
[586]	validation_0-mae:2091.91725
[587]	validation_0-mae:2092.05459
[588]	validation_0-mae:2091.77529
[589]	validation_0-mae:2091.63512
[590]	validation_0-mae:2091.69914

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[0]	validation_0-mae:12442.28985
[1]	validation_0-mae:11697.49473
[2]	validation_0-mae:11032.71022
[3]	validation_0-mae:10395.89952
[4]	validation_0-mae:9844.51954
[5]	validation_0-mae:9333.84172
[6]	validation_0-mae:8874.49946
[7]	validation_0-mae:8435.87642
[8]	validation_0-mae:8073.85295
[9]	validation_0-mae:7722.25213
[10]	validation_0-mae:7414.57059
[11]	validation_0-mae:7118.31452
[12]	validation_0-mae:6842.04555
[13]	validation_0-mae:6605.76830
[14]	validation_0-mae:6349.45778
[15]	validation_0-mae:6125.71801
[16]	validation_0-mae:5886.83818
[17]	validation_0-mae:5664.70809
[18]	validation_0-mae:5499.61954
[19]	validation_0-mae:5309.57685
[20]	validation_0-mae:5163.61887
[21]	validation_0-mae:4993.40773
[22]	validation_0-mae:4845.70555
[23]	validation_0-mae:4712.85402
[24]	validation_0-mae:4575.94171
[25]	validation_0-mae:4454.68949
[26]	validation_0-mae:4340.74117
[27]	validation_0-mae:4251.18234
[28]	validation_0-mae:4160.55136
[29]	validation_0-mae:4065.64705
[30]	validation_0-mae:3976.75484
[31]	validation_0-mae:3896.05425
[32]	validation_0-mae:3817.71537
[33]	validation_0-mae:3740.85292
[34]	validation_0-mae:3680.34754
[35]	validation_0-mae:3597.42083
[36]	validation_0-mae:3534.77241
[37]	validation_0-mae:3478.45240
[38]	validation_0-mae:3424.09854
[39]	validation_0-mae:3380.45676
[40]	validation_0-mae:3334.68990
[41]	validation_0-mae:3289.32344
[42]	validation_0-mae:3248.16989
[43]	validation_0-mae:3216.22280
[44]	validation_0-mae:3151.96561
[45]	validation_0-mae:3115.19537
[46]	validation_0-mae:3088.49608
[47]	validation_0-mae:3065.95592
[48]	validation_0-mae:3027.58066
[49]	validation_0-mae:3001.39081
[50]	validation_0-mae:2963.65721
[51]	validation_0-mae:2935.90746
[52]	validation_0-mae:2905.45690
[53]	validation_0-mae:2884.52792
[54]	validation_0-mae:2861.43778
[55]	validation_0-mae:2844.65132
[56]	validation_0-mae:2829.41139
[57]	validation_0-mae:2809.36044
[58]	validation_0-mae:2796.13651
[59]	validation_0-mae:2781.34654
[60]	validation_0-mae:2757.10993
[61]	validation_0-mae:2742.18858
[62]	validation_0-mae:2725.59149
[63]	validation_0-mae:2710.35172
[64]	validation_0-mae:2697.01824
[65]	validation_0-mae:2680.46090
[66]	validation_0-mae:2668.65611
[67]	validation_0-mae:2659.61627
[68]	validation_0-mae:2649.13786
[69]	validation_0-mae:2630.44586
[70]	validation_0-mae:2622.33487
[71]	validation_0-mae:2607.69143
[72]	validation_0-mae:2589.27141
[73]	validation_0-mae:2583.05937
[74]	validation_0-mae:2575.49662
[75]	validation_0-mae:2556.74208
[76]	validation_0-mae:2548.19982
[77]	validation_0-mae:2538.65054
[78]	validation_0-mae:2531.05585
[79]	validation_0-mae:2524.98279
[80]	validation_0-mae:2515.67710
[81]	validation_0-mae:2511.05289
[82]	validation_0-mae:2503.01178
[83]	validation_0-mae:2495.68056
[84]	validation_0-mae:2485.82794
[85]	validation_0-mae:2477.10074
[86]	validation_0-mae:2468.86338
[87]	validation_0-mae:2460.27828
[88]	validation_0-mae:2452.32216
[89]	validation_0-mae:2447.23446
[90]	validation_0-mae:2441.61565
[91]	validation_0-mae:2434.71700
[92]	validation_0-mae:2427.40269
[93]	validation_0-mae:2419.66235
[94]	validation_0-mae:2413.19496
[95]	validation_0-mae:2408.40715
[96]	validation_0-mae:2404.90215
[97]	validation_0-mae:2401.61883
[98]	validation_0-mae:2397.37807
[99]	validation_0-mae:2396.74288
[100]	validation_0-mae:2392.09736
[101]	validation_0-mae:2384.93562
[102]	validation_0-mae:2379.88338
[103]	validation_0-mae:2378.10314
[104]	validation_0-mae:2375.58706
[105]	validation_0-mae:2370.42056
[106]	validation_0-mae:2367.62858
[107]	validation_0-mae:2362.85863
[108]	validation_0-mae:2354.98129
[109]	validation_0-mae:2350.15625
[110]	validation_0-mae:2344.74771
[111]	validation_0-mae:2339.93515
[112]	validation_0-mae:2338.89207
[113]	validation_0-mae:2330.69886
[114]	validation_0-mae:2329.97519
[115]	validation_0-mae:2327.13072
[116]	validation_0-mae:2322.72338
[117]	validation_0-mae:2321.88335
[118]	validation_0-mae:2315.91437
[119]	validation_0-mae:2314.25581
[120]	validation_0-mae:2312.71491
[121]	validation_0-mae:2312.13803
[122]	validation_0-mae:2309.78488
[123]	validation_0-mae:2308.23884
[124]	validation_0-mae:2307.73104
[125]	validation_0-mae:2306.19932
[126]	validation_0-mae:2304.12600
[127]	validation_0-mae:2301.82831
[0]	validation_0-mae:12371.84006
[1]	validation_0-mae:11597.52120
[2]	validation_0-mae:10877.87648
[3]	validation_0-mae:10218.80376
[4]	validation_0-mae:9646.36750
[5]	validation_0-mae:9106.53418
[6]	validation_0-mae:8660.68737
[7]	validation_0-mae:8250.22005
[8]	validation_0-mae:7873.26914
[9]	validation_0-mae:7517.74148
[10]	validation_0-mae:7189.79657
[11]	validation_0-mae:6918.11897
[12]	validation_0-mae:6642.03390
[13]	validation_0-mae:6385.15059
[14]	validation_0-mae:6132.53647
[15]	validation_0-mae:5884.85429
[16]	validation_0-mae:5664.18692
[17]	validation_0-mae:5462.26617
[18]	validation_0-mae:5261.38008
[19]	validation_0-mae:5111.83202
[20]	validation_0-mae:4936.11756
[21]	validation_0-mae:4794.22637
[22]	validation_0-mae:4658.56853
[23]	validation_0-mae:4525.52851
[24]	validation_0-mae:4397.77975
[25]	validation_0-mae:4295.23858
[26]	validation_0-mae:4187.91846
[27]	validation_0-mae:4093.83057
[28]	validation_0-mae:3994.09033
[29]	validation_0-mae:3885.64242
[30]	validation_0-mae:3811.70489
[31]	validation_0-mae:3727.69398
[32]	validation_0-mae:3652.29663
[33]	validation_0-mae:3572.12835
[34]	validation_0-mae:3517.55585
[35]	validation_0-mae:3445.65104

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[36]	validation_0-mae:3404.56072
[37]	validation_0-mae:3365.17101
[38]	validation_0-mae:3312.12416
[39]	validation_0-mae:3269.74280
[40]	validation_0-mae:3225.52087
[41]	validation_0-mae:3184.24204
[42]	validation_0-mae:3153.23555
[43]	validation_0-mae:3120.12570
[44]	validation_0-mae:3075.96917
[45]	validation_0-mae:3044.63907
[46]	validation_0-mae:3014.51043
[47]	validation_0-mae:2971.32658
[48]	validation_0-mae:2947.27879
[49]	validation_0-mae:2910.60868
[50]	validation_0-mae:2882.28828
[51]	validation_0-mae:2862.85413
[52]	validation_0-mae:2848.46898
[53]	validation_0-mae:2827.74204
[54]	validation_0-mae:2811.01366
[55]	validation_0-mae:2787.43904
[56]	validation_0-mae:2773.50255
[57]	validation_0-mae:2754.46079
[58]	validation_0-mae:2738.41401
[59]	validation_0-mae:2724.11122
[60]	validation_0-mae:2707.50888
[61]	validation_0-mae:2686.09719
[62]	validation_0-mae:2679.92943
[63]	validation_0-mae:2667.02081
[64]	validation_0-mae:2651.85573
[65]	validation_0-mae:2633.06392
[66]	validation_0-mae:2622.97076
[67]	validation_0-mae:2611.68021
[68]	validation_0-mae:2603.09396
[69]	validation_0-mae:2593.33296
[70]	validation_0-mae:2569.92686
[71]	validation_0-mae:2559.11117
[72]	validation_0-mae:2546.86875
[73]	validation_0-mae:2535.63187
[74]	validation_0-mae:2525.29492
[75]	validation_0-mae:2517.48494
[76]	validation_0-mae:2507.64735
[77]	validation_0-mae:2498.69296
[78]	validation_0-mae:2491.36680
[79]	validation_0-mae:2482.98255
[80]	validation_0-mae:2473.24863
[81]	validation_0-mae:2466.34638
[82]	validation_0-mae:2458.56813
[83]	validation_0-mae:2452.89567
[84]	validation_0-mae:2446.66908
[85]	validation_0-mae:2437.08063
[86]	validation_0-mae:2433.24912
[87]	validation_0-mae:2422.08903
[88]	validation_0-mae:2412.66246
[89]	validation_0-mae:2406.89819
[90]	validation_0-mae:2398.95986
[91]	validation_0-mae:2395.33810
[92]	validation_0-mae:2384.80738
[93]	validation_0-mae:2377.25460
[94]	validation_0-mae:2372.13403
[95]	validation_0-mae:2364.59594
[96]	validation_0-mae:2362.98866
[97]	validation_0-mae:2358.21675
[98]	validation_0-mae:2353.22198
[99]	validation_0-mae:2347.09289
[100]	validation_0-mae:2341.66322
[101]	validation_0-mae:2337.02513
[102]	validation_0-mae:2330.77863
[103]	validation_0-mae:2326.73072
[104]	validation_0-mae:2324.80250
[105]	validation_0-mae:2319.52283
[106]	validation_0-mae:2315.13871
[107]	validation_0-mae:2311.21649
[108]	validation_0-mae:2310.28099
[109]	validation_0-mae:2306.85469
[110]	validation_0-mae:2303.01130
[111]	validation_0-mae:2297.72066
[112]	validation_0-mae:2294.55239
[113]	validation_0-mae:2291.22055
[114]	validation_0-mae:2285.68850
[115]	validation_0-mae:2281.04615
[116]	validation_0-mae:2281.22544
[117]	validation_0-mae:2277.88497
[118]	validation_0-mae:2277.33352
[119]	validation_0-mae:2275.28324
[120]	validation_0-mae:2269.73487
[121]	validation_0-mae:2268.79752
[122]	validation_0-mae:2264.26244
[123]	validation_0-mae:2261.44436
[124]	validation_0-mae:2257.50827
[125]	validation_0-mae:2254.78282
[126]	validation_0-mae:2254.07257
[127]	validation_0-mae:2253.31530
[128]	validation_0-mae:2250.05079
[129]	validation_0-mae:2248.71327
[130]	validation_0-mae:2247.67404
[131]	validation_0-mae:2247.43119
[132]	validation_0-mae:2245.13189
[133]	validation_0-mae:2242.72339
[134]	validation_0-mae:2242.55180
[135]	validation_0-mae:2242.03765
[136]	validation_0-mae:2241.13830
[137]	validation_0-mae:2237.79672
[138]	validation_0-mae:2236.14851
[139]	validation_0-mae:2235.27216
[140]	validation_0-mae:2234.97662
[141]	validation_0-mae:2233.82779
[142]	validation_0-mae:2232.21171
[143]	validation_0-mae:2229.97346
[144]	validation_0-mae:2229.40213
[145]	validation_0-mae:2226.80874
[146]	validation_0-mae:2225.52608
[147]	validation_0-mae:2223.18529
[148]	validation_0-mae:2218.81093
[149]	validation_0-mae:2218.29275
[150]	validation_0-mae:2216.28764
[151]	validation_0-mae:2215.93037
[152]	validation_0-mae:2216.62637
[153]	validation_0-mae:2217.55310
[154]	validation_0-mae:2215.47241
[155]	validation_0-mae:2212.90329
[156]	validation_0-mae:2212.16536
[157]	validation_0-mae:2211.19999
[158]	validation_0-mae:2210.90582
[159]	validation_0-mae:2207.64871
[160]	validation_0-mae:2206.54054
[161]	validation_0-mae:2206.18831
[162]	validation_0-mae:2203.37033
[163]	validation_0-mae:2202.65748
[164]	validation_0-mae:2201.34089
[165]	validation_0-mae:2201.74091
[166]	validation_0-mae:2199.14085
[167]	validation_0-mae:2197.87813
[168]	validation_0-mae:2197.36291
[169]	validation_0-mae:2194.44593
[170]	validation_0-mae:2194.16214
[171]	validation_0-mae:2195.43707
[172]	validation_0-mae:2193.93585
[173]	validation_0-mae:2192.68197
[174]	validation_0-mae:2190.20678
[175]	validation_0-mae:2189.01977
[176]	validation_0-mae:2189.91994
[177]	validation_0-mae:2189.12866
[178]	validation_0-mae:2187.98010
[179]	validation_0-mae:2188.54302
[180]	validation_0-mae:2189.30067
[181]	validation_0-mae:2188.60218
[182]	validation_0-mae:2186.56939
[183]	validation_0-mae:2183.71568
[184]	validation_0-mae:2184.28041
[185]	validation_0-mae:2183.31139
[186]	validation_0-mae:2183.02201
[187]	validation_0-mae:2182.08727
[188]	validation_0-mae:2182.28795
[189]	validation_0-mae:2181.72600
[190]	validation_0-mae:2181.18350
[191]	validation_0-mae:2180.09804
[192]	validation_0-mae:2178.08928
[193]	validation_0-mae:2177.81680
[194]	validation_0-mae:2176.55016
[195]	validation_0-mae:2176.82032
[196]	validation_0-mae:2176.24932
[197]	validation_0-mae:2172.75813
[198]	validation_0-mae:2170.93565
[199]	validation_0-mae:2169.97155
[200]	validation_0-mae:2170.21044
[201]	validation_0-mae:2170.60750
[202]	validation_0-mae:2168.97237
[203]	validation_0-mae:2169.00877
[204]	validation_0-mae:2169.40789
[205]	validation_0-mae:2169.43906
[206]	validation_0-mae:2168.88463
[207]	validation_0-mae:2167.87435
[208]	validation_0-mae:2167.58366
[209]	validation_0-mae:2166.27991
[210]	validation_0-mae:2163.37615
[211]	validation_0-mae:2164.01478
[212]	validation_0-mae:2161.97924
[213]	validation_0-mae:2158.72231
[214]	validation_0-mae:2157.75099
[215]	validation_0-mae:2156.40320
[216]	validation_0-mae:2156.01333
[217]	validation_0-mae:2155.23572
[218]	validation_0-mae:2154.01688
[219]	validation_0-mae:2153.55687
[220]	validation_0-mae:2152.40117
[221]	validation_0-mae:2152.33105
[222]	validation_0-mae:2152.08941
[223]	validation_0-mae:2151.68250
[224]	validation_0-mae:2148.88970
[225]	validation_0-mae:2147.86064
[226]	validation_0-mae:2145.20063
[227]	validation_0-mae:2145.44570
[228]	validation_0-mae:2145.03259
[229]	validation_0-mae:2144.34065
[230]	validation_0-mae:2144.37901
[231]	validation_0-mae:2143.42191
[232]	validation_0-mae:2142.21875
[233]	validation_0-mae:2141.73979
[234]	validation_0-mae:2140.34351
[235]	validation_0-mae:2140.42301
[236]	validation_0-mae:2141.33370
[237]	validation_0-mae:2140.62359
[238]	validation_0-mae:2141.14413
[239]	validation_0-mae:2140.86686
[240]	validation_0-mae:2140.22835
[241]	validation_0-mae:2138.65640
[242]	validation_0-mae:2138.30508
[243]	validation_0-mae:2136.78743
[244]	validation_0-mae:2136.35998
[245]	validation_0-mae:2134.70242
[246]	validation_0-mae:2133.69422
[247]	validation_0-mae:2134.34893
[248]	validation_0-mae:2134.71206
[249]	validation_0-mae:2134.37709
[250]	validation_0-mae:2134.28030
[251]	validation_0-mae:2134.43474
[252]	validation_0-mae:2134.04206
[253]	validation_0-mae:2131.91437
[254]	validation_0-mae:2131.69264
[255]	validation_0-mae:2133.19547
[256]	validation_0-mae:2132.20850
[257]	validation_0-mae:2132.45064
[258]	validation_0-mae:2132.33352
[259]	validation_0-mae:2132.16726
[260]	validation_0-mae:2131.08466
[261]	validation_0-mae:2130.63157
[262]	validation_0-mae:2130.07516
[263]	validation_0-mae:2128.77562
[264]	validation_0-mae:2128.73386
[265]	validation_0-mae:2127.92028
[266]	validation_0-mae:2127.86335
[267]	validation_0-mae:2127.18580
[268]	validation_0-mae:2126.74306
[269]	validation_0-mae:2125.67407
[270]	validation_0-mae:2125.66738
[271]	validation_0-mae:2124.99584
[272]	validation_0-mae:2124.78865
[273]	validation_0-mae:2125.17145
[274]	validation_0-mae:2123.77758
[275]	validation_0-mae:2123.77748
[276]	validation_0-mae:2124.21471
[277]	validation_0-mae:2124.31058
[278]	validation_0-mae:2124.66338
[279]	validation_0-mae:2123.45970
[280]	validation_0-mae:2120.63423
[281]	validation_0-mae:2119.67537
[282]	validation_0-mae:2119.70113
[283]	validation_0-mae:2118.33602
[284]	validation_0-mae:2116.04128
[285]	validation_0-mae:2116.50150
[286]	validation_0-mae:2116.52265
[287]	validation_0-mae:2115.45637
[288]	validation_0-mae:2115.33293
[289]	validation_0-mae:2114.86963
[290]	validation_0-mae:2111.30144
[291]	validation_0-mae:2110.82561
[292]	validation_0-mae:2109.81452
[293]	validation_0-mae:2108.86395
[294]	validation_0-mae:2107.12560
[295]	validation_0-mae:2106.77411
[296]	validation_0-mae:2105.87324
[297]	validation_0-mae:2105.29926
[298]	validation_0-mae:2105.13227
[299]	validation_0-mae:2103.52751
[300]	validation_0-mae:2103.48537
[301]	validation_0-mae:2102.11173
[302]	validation_0-mae:2102.04414
[303]	validation_0-mae:2102.59596
[304]	validation_0-mae:2102.79656
[305]	validation_0-mae:2101.90215
[306]	validation_0-mae:2101.78240
[307]	validation_0-mae:2101.87616
[308]	validation_0-mae:2102.65664
[309]	validation_0-mae:2102.46559
[310]	validation_0-mae:2100.24040
[311]	validation_0-mae:2100.48716
[312]	validation_0-mae:2100.96924
[313]	validation_0-mae:2100.52307
[314]	validation_0-mae:2100.82194
[315]	validation_0-mae:2100.24446
[316]	validation_0-mae:2100.28746
[317]	validation_0-mae:2099.94108
[318]	validation_0-mae:2100.74075
[319]	validation_0-mae:2101.01701
[320]	validation_0-mae:2101.06344
[321]	validation_0-mae:2100.71104
[322]	validation_0-mae:2100.26999
[323]	validation_0-mae:2101.22068
[324]	validation_0-mae:2101.97804
[325]	validation_0-mae:2101.01176
[326]	validation_0-mae:2101.34702
[327]	validation_0-mae:2100.71750
[328]	validation_0-mae:2099.02888
[329]	validation_0-mae:2098.21265
[330]	validation_0-mae:2098.27839
[331]	validation_0-mae:2097.47497
[332]	validation_0-mae:2097.68061
[333]	validation_0-mae:2097.95953
[334]	validation_0-mae:2097.24752
[335]	validation_0-mae:2097.17881
[336]	validation_0-mae:2096.45143
[337]	validation_0-mae:2095.86531
[338]	validation_0-mae:2095.25878
[339]	validation_0-mae:2095.65011
[340]	validation_0-mae:2094.57204
[341]	validation_0-mae:2094.46777
[342]	validation_0-mae:2093.70358
[343]	validation_0-mae:2092.68623
[344]	validation_0-mae:2092.95655
[345]	validation_0-mae:2092.98396
[346]	validation_0-mae:2093.07599
[347]	validation_0-mae:2092.99833
[348]	validation_0-mae:2093.60651
[349]	validation_0-mae:2093.26780
[350]	validation_0-mae:2093.58589
[351]	validation_0-mae:2092.66105
[352]	validation_0-mae:2093.04670
[353]	validation_0-mae:2092.70387
[354]	validation_0-mae:2092.91793
[355]	validation_0-mae:2092.74933
[356]	validation_0-mae:2092.69257
[357]	validation_0-mae:2093.25883
[358]	validation_0-mae:2093.43048
[359]	validation_0-mae:2092.69395
[360]	validation_0-mae:2093.18548
[361]	validation_0-mae:2093.29423
[362]	validation_0-mae:2093.47565
[363]	validation_0-mae:2093.34290
[364]	validation_0-mae:2094.59103
[365]	validation_0-mae:2094.51410
[366]	validation_0-mae:2094.75139
[367]	validation_0-mae:2094.95051
[368]	validation_0-mae:2094.72217
[369]	validation_0-mae:2093.90094
[370]	validation_0-mae:2094.07968
[371]	validation_0-mae:2094.44637
[372]	validation_0-mae:2094.81184
[373]	validation_0-mae:2094.79557
[374]	validation_0-mae:2095.16130
[375]	validation_0-mae:2095.33340
[376]	validation_0-mae:2095.57743
[377]	validation_0-mae:2095.84359
[378]	validation_0-mae:2095.85150
[379]	validation_0-mae:2094.46616
[380]	validation_0-mae:2094.26731
[381]	validation_0-mae:2094.42859
[382]	validation_0-mae:2094.46646
[383]	validation_0-mae:2094.41504
[384]	validation_0-mae:2094.55879
[385]	validation_0-mae:2095.18990
[386]	validation_0-mae:2094.79334
[387]	validation_0-mae:2094.89088
[388]	validation_0-mae:2095.11042
[389]	validation_0-mae:2094.47647
[390]	validation_0-mae:2095.07396
[391]	validation_0-mae:2093.37771
[392]	validation_0-mae:2093.26055
[393]	validation_0-mae:2093.23960
[394]	validation_0-mae:2093.32141
[395]	validation_0-mae:2093.78527
[396]	validation_0-mae:2093.84480
[397]	validation_0-mae:2093.78898
[398]	validation_0-mae:2094.32798
[399]	validation_0-mae:2095.14986
[400]	validation_0-mae:2094.84699
[401]	validation_0-mae:2094.69502
[402]	validation_0-mae:2094.62678
[403]	validation_0-mae:2094.58830
[404]	validation_0-mae:2095.07585
[405]	validation_0-mae:2095.11793
[406]	validation_0-mae:2095.06224
[407]	validation_0-mae:2094.93014
[408]	validation_0-mae:2094.81179
[409]	validation_0-mae:2095.12944
[410]	validation_0-mae:2094.94071
[411]	validation_0-mae:2094.26967
[412]	validation_0-mae:2093.99696
[413]	validation_0-mae:2093.62434
[414]	validation_0-mae:2093.82572
[415]	validation_0-mae:2093.74093
[416]	validation_0-mae:2093.74495
[417]	validation_0-mae:2093.87874
[418]	validation_0-mae:2093.24222
[419]	validation_0-mae:2092.92129
[420]	validation_0-mae:2092.91609
[421]	validation_0-mae:2092.93136
[422]	validation_0-mae:2092.09176
[423]	validation_0-mae:2092.73640
[424]	validation_0-mae:2093.11192
[425]	validation_0-mae:2093.44144
[426]	validation_0-mae:2093.40315
[427]	validation_0-mae:2093.19102
[428]	validation_0-mae:2093.29305
[429]	validation_0-mae:2093.55283
[430]	validation_0-mae:2093.86526
[431]	validation_0-mae:2093.70940
[432]	validation_0-mae:2093.28912
[433]	validation_0-mae:2092.60743
[434]	validation_0-mae:2093.32406
[435]	validation_0-mae:2093.03956
[436]	validation_0-mae:2093.72740
[437]	validation_0-mae:2094.01946
[438]	validation_0-mae:2093.27693
[439]	validation_0-mae:2093.82364
[440]	validation_0-mae:2093.14298
[441]	validation_0-mae:2092.61794
[442]	validation_0-mae:2092.66192
[443]	validation_0-mae:2092.25421
[444]	validation_0-mae:2091.93839
[445]	validation_0-mae:2091.45155
[446]	validation_0-mae:2089.94293
[447]	validation_0-mae:2089.84817
[448]	validation_0-mae:2089.56279
[449]	validation_0-mae:2088.17202
[450]	validation_0-mae:2088.23377
[451]	validation_0-mae:2088.17985
[452]	validation_0-mae:2087.19084
[453]	validation_0-mae:2086.48328
[454]	validation_0-mae:2085.88604
[455]	validation_0-mae:2086.18726
[456]	validation_0-mae:2085.87191
[457]	validation_0-mae:2085.84182
[458]	validation_0-mae:2084.75476
[459]	validation_0-mae:2084.66886
[460]	validation_0-mae:2084.58519
[461]	validation_0-mae:2084.03822
[462]	validation_0-mae:2084.08440
[463]	validation_0-mae:2083.67287
[464]	validation_0-mae:2083.61433
[465]	validation_0-mae:2083.51850
[466]	validation_0-mae:2083.51764
[467]	validation_0-mae:2082.66087
[468]	validation_0-mae:2082.45968
[469]	validation_0-mae:2082.21834
[470]	validation_0-mae:2082.22412
[471]	validation_0-mae:2082.21078
[472]	validation_0-mae:2082.39206
[473]	validation_0-mae:2082.03107
[474]	validation_0-mae:2081.94771
[475]	validation_0-mae:2081.64659
[476]	validation_0-mae:2081.49020
[477]	validation_0-mae:2081.28788
[478]	validation_0-mae:2081.52287
[479]	validation_0-mae:2081.28645
[480]	validation_0-mae:2080.76315
[481]	validation_0-mae:2080.52849
[482]	validation_0-mae:2080.63683
[483]	validation_0-mae:2080.24612
[484]	validation_0-mae:2080.11058
[485]	validation_0-mae:2079.92641
[486]	validation_0-mae:2079.87068
[487]	validation_0-mae:2079.93268
[488]	validation_0-mae:2080.10951
[489]	validation_0-mae:2080.02092
[490]	validation_0-mae:2079.95886
[491]	validation_0-mae:2080.00939
[492]	validation_0-mae:2080.07370
[493]	validation_0-mae:2079.99551
[494]	validation_0-mae:2079.62791
[495]	validation_0-mae:2079.69500
[496]	validation_0-mae:2079.63946
[497]	validation_0-mae:2079.91719
[498]	validation_0-mae:2079.72923
[499]	validation_0-mae:2079.48946
[500]	validation_0-mae:2079.49637
[501]	validation_0-mae:2079.57264
[502]	validation_0-mae:2079.39317
[503]	validation_0-mae:2079.97065
[504]	validation_0-mae:2079.78501
[505]	validation_0-mae:2079.74949
[506]	validation_0-mae:2079.27952
[507]	validation_0-mae:2079.70759
[508]	validation_0-mae:2079.40178
[509]	validation_0-mae:2079.24187
[510]	validation_0-mae:2079.19967
[511]	validation_0-mae:2080.06791
[512]	validation_0-mae:2080.15336
[513]	validation_0-mae:2080.18724
[514]	validation_0-mae:2079.88982
[515]	validation_0-mae:2079.99022
[516]	validation_0-mae:2080.01543
[517]	validation_0-mae:2080.25117
[518]	validation_0-mae:2080.42614
[519]	validation_0-mae:2080.74709
[520]	validation_0-mae:2080.63533
[521]	validation_0-mae:2080.56880
[522]	validation_0-mae:2080.51451
[523]	validation_0-mae:2080.12945
[524]	validation_0-mae:2079.97276
[525]	validation_0-mae:2080.16046
[526]	validation_0-mae:2080.01019
[527]	validation_0-mae:2079.68449
[528]	validation_0-mae:2079.73208
[529]	validation_0-mae:2079.69991
[530]	validation_0-mae:2080.02861
[531]	validation_0-mae:2079.99120
[532]	validation_0-mae:2080.09289
[533]	validation_0-mae:2080.21641
[534]	validation_0-mae:2080.58682
[535]	validation_0-mae:2080.79277
[536]	validation_0-mae:2080.44916
[537]	validation_0-mae:2080.37779
[538]	validation_0-mae:2080.15685
[539]	validation_0-mae:2080.04316
[540]	validation_0-mae:2079.94116
[541]	validation_0-mae:2080.28469
[542]	validation_0-mae:2080.00641
[543]	validation_0-mae:2080.48018
[544]	validation_0-mae:2080.73473
[545]	validation_0-mae:2081.08420
[546]	validation_0-mae:2081.01016
[547]	validation_0-mae:2081.05311
[548]	validation_0-mae:2081.21199
[549]	validation_0-mae:2080.78086
[550]	validation_0-mae:2080.80674
[551]	validation_0-mae:2081.06593
[552]	validation_0-mae:2081.22805
[553]	validation_0-mae:2081.26669
[554]	validation_0-mae:2081.39331
[555]	validation_0-mae:2081.70234
[556]	validation_0-mae:2081.72882
[557]	validation_0-mae:2081.89954
[558]	validation_0-mae:2081.79633
[559]	validation_0-mae:2081.66222
[560]	validation_0-mae:2081.72416
[561]	validation_0-mae:2081.71494
[562]	validation_0-mae:2081.36251
[563]	validation_0-mae:2081.20172
[564]	validation_0-mae:2081.24641
[565]	validation_0-mae:2081.52026
[566]	validation_0-mae:2081.19373
[567]	validation_0-mae:2081.47743
[568]	validation_0-mae:2081.63122
[569]	validation_0-mae:2081.24220
[570]	validation_0-mae:2081.49449
[571]	validation_0-mae:2081.53924
[572]	validation_0-mae:2081.30346
[573]	validation_0-mae:2080.89906
[574]	validation_0-mae:2081.47393
[575]	validation_0-mae:2081.29899
[576]	validation_0-mae:2081.18013
[577]	validation_0-mae:2081.32261
[578]	validation_0-mae:2080.76891
[579]	validation_0-mae:2081.04965
[580]	validation_0-mae:2080.69503
[581]	validation_0-mae:2080.96061
[582]	validation_0-mae:2081.24217
[583]	validation_0-mae:2081.25671
[584]	validation_0-mae:2081.38603
[585]	validation_0-mae:2081.48077
[586]	validation_0-mae:2081.24565
[587]	validation_0-mae:2081.20272
[588]	validation_0-mae:2081.36881
[589]	validation_0-mae:2081.11930
[590]	validation_0-mae:2080.86191
[591]	validation_0-mae:2080.78683
[592]	validation_0-mae:2080.88587
[593]	validation_0-mae:2080.81784
[594]	validation_0-mae:2080.97313
[595]	validation_0-mae:2081.06535
[596]	validation_0-mae:2080.61611
[597]	validation_0-mae:2080.72074
[598]	validation_0-mae:2080.82177
[599]	validation_0-mae:2080.76685
[600]	validation_0-mae:2080.64500
[601]	validation_0-mae:2080.79392
[602]	validation_0-mae:2080.92993
[603]	validation_0-mae:2080.95211
[604]	validation_0-mae:2080.91892
[605]	validation_0-mae:2080.87602
[606]	validation_0-mae:2080.78921
[607]	validation_0-mae:2080.83414
[608]	validation_0-mae:2080.89047
[609]	validation_0-mae:2080.80439
[610]	validation_0-mae:2081.11591
[611]	validation_0-mae:2081.07230
[612]	validation_0-mae:2080.70719
[613]	validation_0-mae:2080.28112
[614]	validation_0-mae:2080.31858
[615]	validation_0-mae:2079.50516
[616]	validation_0-mae:2079.44252
[617]	validation_0-mae:2079.19536
[618]	validation_0-mae:2079.33915
[619]	validation_0-mae:2079.07568
[620]	validation_0-mae:2078.98858
[621]	validation_0-mae:2079.03701
[622]	validation_0-mae:2079.31255
[623]	validation_0-mae:2079.18981
[624]	validation_0-mae:2079.40232
[625]	validation_0-mae:2079.49837

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[36]	validation_0-mae:3481.49959
[37]	validation_0-mae:3440.67462
[38]	validation_0-mae:3394.82340
[39]	validation_0-mae:3350.49903
[40]	validation_0-mae:3300.83799
[41]	validation_0-mae:3230.81006
[42]	validation_0-mae:3191.57667
[43]	validation_0-mae:3160.90522
[44]	validation_0-mae:3113.89016
[45]	validation_0-mae:3083.53916
[46]	validation_0-mae:3051.73319
[47]	validation_0-mae:3007.65734
[48]	validation_0-mae:2979.30781
[49]	validation_0-mae:2947.74747
[50]	validation_0-mae:2915.93925
[51]	validation_0-mae:2891.27464
[52]	validation_0-mae:2866.89700
[53]	validation_0-mae:2846.02534
[54]	validation_0-mae:2819.27613
[55]	validation_0-mae:2801.05037
[56]	validation_0-mae:2781.75525
[57]	validation_0-mae:2764.80903
[58]	validation_0-mae:2748.67521
[59]	validation_0-mae:2729.82799
[60]	validation_0-mae:2706.58037
[61]	validation_0-mae:2690.17871
[62]	validation_0-mae:2668.06558
[63]	validation_0-mae:2656.19799
[64]	validation_0-mae:2644.27990
[65]	validation_0-mae:2634.00510
[66]	validation_0-mae:2622.45948
[67]	validation_0-mae:2603.43959
[68]	validation_0-mae:2598.17496
[69]	validation_0-mae:2591.98937
[70]	validation_0-mae:2581.74834
[71]	validation_0-mae:2573.99736
[72]	validation_0-mae:2557.33413
[73]	validation_0-mae:2536.58548
[74]	validation_0-mae:2530.72869
[75]	validation_0-mae:2519.14458
[76]	validation_0-mae:2511.12740
[77]	validation_0-mae:2504.73534
[78]	validation_0-mae:2499.59088
[79]	validation_0-mae:2490.54446
[80]	validation_0-mae:2484.13921
[81]	validation_0-mae:2477.66264
[82]	validation_0-mae:2473.18827
[83]	validation_0-mae:2463.32346
[84]	validation_0-mae:2457.04622
[85]	validation_0-mae:2445.05864
[86]	validation_0-mae:2444.01206
[87]	validation_0-mae:2440.07264
[88]	validation_0-mae:2430.86017
[89]	validation_0-mae:2423.76288
[90]	validation_0-mae:2417.51830
[91]	validation_0-mae:2411.02106
[92]	validation_0-mae:2401.01731
[93]	validation_0-mae:2397.64288
[94]	validation_0-mae:2393.73826
[95]	validation_0-mae:2386.58608
[96]	validation_0-mae:2379.20568
[97]	validation_0-mae:2373.16555
[98]	validation_0-mae:2370.03548
[99]	validation_0-mae:2365.98943
[100]	validation_0-mae:2363.73735
[101]	validation_0-mae:2357.12172
[102]	validation_0-mae:2353.46735
[103]	validation_0-mae:2348.35622
[104]	validation_0-mae:2346.92132
[105]	validation_0-mae:2340.79897
[106]	validation_0-mae:2334.65433
[107]	validation_0-mae:2333.86688
[108]	validation_0-mae:2332.26989
[109]	validation_0-mae:2328.86826
[110]	validation_0-mae:2323.43743
[111]	validation_0-mae:2318.62012
[112]	validation_0-mae:2311.51360
[113]	validation_0-mae:2311.77720
[114]	validation_0-mae:2307.67264
[115]	validation_0-mae:2303.96166
[116]	validation_0-mae:2301.82339
[117]	validation_0-mae:2301.29127
[118]	validation_0-mae:2296.47263
[119]	validation_0-mae:2292.63890
[120]	validation_0-mae:2290.95565
[121]	validation_0-mae:2290.78450
[122]	validation_0-mae:2287.58574
[123]	validation_0-mae:2286.07061
[124]	validation_0-mae:2278.55400
[125]	validation_0-mae:2277.98355
[126]	validation_0-mae:2275.92214
[127]	validation_0-mae:2275.16989
[128]	validation_0-mae:2272.38847
[129]	validation_0-mae:2266.94526
[130]	validation_0-mae:2267.83742
[131]	validation_0-mae:2267.14712
[132]	validation_0-mae:2266.27849
[133]	validation_0-mae:2264.12199
[134]	validation_0-mae:2263.58794
[135]	validation_0-mae:2259.80855
[136]	validation_0-mae:2258.20255
[137]	validation_0-mae:2259.54737
[138]	validation_0-mae:2259.87424
[139]	validation_0-mae:2258.45483
[140]	validation_0-mae:2257.18152
[141]	validation_0-mae:2254.15827
[142]	validation_0-mae:2251.82904
[143]	validation_0-mae:2250.42101
[144]	validation_0-mae:2247.53803
[145]	validation_0-mae:2247.42629
[146]	validation_0-mae:2244.91007
[147]	validation_0-mae:2241.66647
[148]	validation_0-mae:2238.66306
[149]	validation_0-mae:2234.77669
[150]	validation_0-mae:2232.17501
[151]	validation_0-mae:2230.51238
[152]	validation_0-mae:2229.96988
[153]	validation_0-mae:2228.13246
[154]	validation_0-mae:2226.86483
[155]	validation_0-mae:2226.47849
[156]	validation_0-mae:2224.77363
[157]	validation_0-mae:2223.36045
[158]	validation_0-mae:2223.90666
[159]	validation_0-mae:2222.07724
[160]	validation_0-mae:2220.97978
[161]	validation_0-mae:2218.84459
[162]	validation_0-mae:2219.04130
[163]	validation_0-mae:2217.03571
[164]	validation_0-mae:2216.12526
[165]	validation_0-mae:2217.45192
[166]	validation_0-mae:2216.18531
[167]	validation_0-mae:2214.62197
[168]	validation_0-mae:2213.62863
[169]	validation_0-mae:2211.64116
[170]	validation_0-mae:2211.35776
[171]	validation_0-mae:2211.36916
[172]	validation_0-mae:2210.16414
[173]	validation_0-mae:2208.11995
[174]	validation_0-mae:2208.42432
[175]	validation_0-mae:2205.99431
[176]	validation_0-mae:2206.81467
[177]	validation_0-mae:2206.60831
[178]	validation_0-mae:2206.19550
[179]	validation_0-mae:2205.63202
[180]	validation_0-mae:2203.67366
[181]	validation_0-mae:2202.80356
[182]	validation_0-mae:2199.80082
[183]	validation_0-mae:2199.90987
[184]	validation_0-mae:2199.69690
[185]	validation_0-mae:2200.64140
[186]	validation_0-mae:2201.29568
[187]	validation_0-mae:2198.98918
[188]	validation_0-mae:2197.87634
[189]	validation_0-mae:2196.81207
[190]	validation_0-mae:2198.56139
[191]	validation_0-mae:2196.80684
[192]	validation_0-mae:2195.49531
[193]	validation_0-mae:2194.32047
[194]	validation_0-mae:2194.07059
[195]	validation_0-mae:2193.67842
[196]	validation_0-mae:2192.85913
[0]	validation_0-mae:12388.52482
[1]	validation_0-mae:11604.34321
[2]	validation_0-mae:10921.71675
[3]	validation_0-mae:10313.75837
[4]	validation_0-mae:9780.63978
[5]	validation_0-mae:9293.74884
[6]	validation_0-mae:8847.78343
[7]	validation_0-mae:8516.41142
[8]	validation_0-mae:8187.23539
[9]	validation_0-mae:7883.96300
[0]	validation_0-mae:12397.79204

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[1]	validation_0-mae:11627.99039
[2]	validation_0-mae:10923.48208
[3]	validation_0-mae:10285.14768
[4]	validation_0-mae:9719.91117
[5]	validation_0-mae:9190.38983
[6]	validation_0-mae:8727.26404
[7]	validation_0-mae:8330.86639
[8]	validation_0-mae:7944.35959
[9]	validation_0-mae:7610.28523
[10]	validation_0-mae:7310.15649
[11]	validation_0-mae:7016.36017
[12]	validation_0-mae:6726.14415
[13]	validation_0-mae:6440.26783
[14]	validation_0-mae:6210.10081
[15]	validation_0-mae:6006.02651
[16]	validation_0-mae:5772.66431
[17]	validation_0-mae:5583.86920
[18]	validation_0-mae:5380.65802
[19]	validation_0-mae:5201.08004
[20]	validation_0-mae:5033.06974
[21]	validation_0-mae:4899.01600
[22]	validation_0-mae:4753.91281
[23]	validation_0-mae:4619.08536
[24]	validation_0-mae:4480.99805
[25]	validation_0-mae:4367.04386
[26]	validation_0-mae:4256.74975
[27]	validation_0-mae:4154.32422
[28]	validation_0-mae:4052.49589
[29]	validation_0-mae:3947.25266
[30]	validation_0-mae:3864.72906
[31]	validation_0-mae:3784.60868
[32]	validation_0-mae:3716.88686
[33]	validation_0-mae:3641.15921
[34]	validation_0-mae:3574.62874
[35]	validation_0-mae:3498.97547
[36]	validation_0-mae:3446.58479
[37]	validation_0-mae:3393.93039
[38]	validation_0-mae:3339.40348
[39]	validation_0-mae:3292.68746
[40]	validation_0-mae:3246.44868
[41]	validation_0-mae:3205.37182
[42]	validation_0-mae:3168.92209
[43]	validation_0-mae:3134.07143
[44]	validation_0-mae:3097.20242
[45]	validation_0-mae:3056.42068
[46]	validation_0-mae:3027.85925
[47]	validation_0-mae:2988.15765
[48]	validation_0-mae:2961.62599
[49]	validation_0-mae:2924.56889
[50]	validation_0-mae:2903.33154
[51]	validation_0-mae:2878.32172
[52]	validation_0-mae:2864.24780
[53]	validation_0-mae:2832.90937
[54]	validation_0-mae:2816.02747
[55]	validation_0-mae:2798.59569
[56]	validation_0-mae:2785.19686
[57]	validation_0-mae:2767.47503
[58]	validation_0-mae:2757.56243
[59]	validation_0-mae:2747.05156
[60]	validation_0-mae:2723.87956
[61]	validation_0-mae:2712.49015
[62]	validation_0-mae:2704.14347
[63]	validation_0-mae:2693.34972
[64]	validation_0-mae:2672.81430
[65]	validation_0-mae:2662.72471
[66]	validation_0-mae:2653.75224
[67]	validation_0-mae:2642.95764
[68]	validation_0-mae:2618.24808
[69]	validation_0-mae:2607.04225
[70]	validation_0-mae:2595.26895
[71]	validation_0-mae:2580.32417
[72]	validation_0-mae:2567.82895
[73]	validation_0-mae:2560.83411
[74]	validation_0-mae:2552.16590
[75]	validation_0-mae:2542.18811
[76]	validation_0-mae:2538.28435
[77]	validation_0-mae:2525.43882
[78]	validation_0-mae:2517.84399
[79]	validation_0-mae:2509.27023
[80]	validation_0-mae:2500.45685
[81]	validation_0-mae:2492.96572
[82]	validation_0-mae:2488.50685
[83]	validation_0-mae:2481.63237
[84]	validation_0-mae:2477.89465
[85]	validation_0-mae:2468.03759
[86]	validation_0-mae:2455.98885
[87]	validation_0-mae:2447.65140
[88]	validation_0-mae:2440.91725
[89]	validation_0-mae:2428.76671
[90]	validation_0-mae:2421.38064
[91]	validation_0-mae:2416.78776
[92]	validation_0-mae:2411.67444
[93]	validation_0-mae:2405.47371
[94]	validation_0-mae:2398.91599
[95]	validation_0-mae:2386.05662
[96]	validation_0-mae:2382.16519
[97]	validation_0-mae:2375.87326
[98]	validation_0-mae:2368.66204
[99]	validation_0-mae:2360.47877
[100]	validation_0-mae:2358.32584
[101]	validation_0-mae:2352.72113
[102]	validation_0-mae:2348.35466
[103]	validation_0-mae:2346.08296
[104]	validation_0-mae:2343.90026
[105]	validation_0-mae:2340.23197
[106]	validation_0-mae:2332.76206
[107]	validation_0-mae:2328.69010
[108]	validation_0-mae:2323.23258
[109]	validation_0-mae:2324.08752
[110]	validation_0-mae:2320.82772
[111]	validation_0-mae:2310.45681
[112]	validation_0-mae:2310.41683
[113]	validation_0-mae:2302.22922
[114]	validation_0-mae:2300.07079
[115]	validation_0-mae:2296.41115
[116]	validation_0-mae:2292.24032
[117]	validation_0-mae:2289.21448
[118]	validation_0-mae:2287.22218
[119]	validation_0-mae:2284.76245
[120]	validation_0-mae:2280.76942
[121]	validation_0-mae:2275.26937
[122]	validation_0-mae:2273.80264
[123]	validation_0-mae:2271.18237
[124]	validation_0-mae:2270.72245
[125]	validation_0-mae:2268.20326
[126]	validation_0-mae:2265.48878
[127]	validation_0-mae:2261.30754
[128]	validation_0-mae:2260.50430
[129]	validation_0-mae:2254.24406
[130]	validation_0-mae:2251.98913
[131]	validation_0-mae:2250.06157
[132]	validation_0-mae:2247.51448
[133]	validation_0-mae:2245.80745
[134]	validation_0-mae:2245.54728
[135]	validation_0-mae:2243.41894
[136]	validation_0-mae:2242.91882
[137]	validation_0-mae:2242.09372
[138]	validation_0-mae:2238.57843
[139]	validation_0-mae:2237.10170
[140]	validation_0-mae:2235.47204
[141]	validation_0-mae:2235.95412
[142]	validation_0-mae:2234.91939
[143]	validation_0-mae:2232.47719
[144]	validation_0-mae:2232.04678
[145]	validation_0-mae:2231.65281
[146]	validation_0-mae:2230.25698
[147]	validation_0-mae:2225.67244
[148]	validation_0-mae:2222.57419
[149]	validation_0-mae:2220.80693
[150]	validation_0-mae:2217.92512
[151]	validation_0-mae:2215.13704
[152]	validation_0-mae:2212.10358
[153]	validation_0-mae:2212.04961
[154]	validation_0-mae:2212.15981
[155]	validation_0-mae:2209.96209
[156]	validation_0-mae:2209.20028
[157]	validation_0-mae:2210.18045
[158]	validation_0-mae:2206.63633
[159]	validation_0-mae:2205.90028
[160]	validation_0-mae:2205.94778
[161]	validation_0-mae:2202.44479
[162]	validation_0-mae:2201.81442
[163]	validation_0-mae:2202.97947
[164]	validation_0-mae:2200.96490
[165]	validation_0-mae:2199.53873
[166]	validation_0-mae:2199.81108
[167]	validation_0-mae:2199.17888
[168]	validation_0-mae:2198.87985
[169]	validation_0-mae:2198.66108
[170]	validation_0-mae:2195.91065
[171]	validation_0-mae:2192.21124
[172]	validation_0-mae:2193.85990
[173]	validation_0-mae:2194.22330
[174]	validation_0-mae:2193.89806
[175]	validation_0-mae:2192.68799
[176]	validation_0-mae:2191.94566
[177]	validation_0-mae:2190.97369
[178]	validation_0-mae:2189.70893
[179]	validation_0-mae:2188.00636
[180]	validation_0-mae:2186.92112
[181]	validation_0-mae:2183.33442
[182]	validation_0-mae:2184.07148
[183]	validation_0-mae:2183.78589
[184]	validation_0-mae:2182.20099
[185]	validation_0-mae:2180.27169
[186]	validation_0-mae:2180.06146
[187]	validation_0-mae:2180.04986
[188]	validation_0-mae:2181.07670
[189]	validation_0-mae:2181.51283
[190]	validation_0-mae:2180.94596
[191]	validation_0-mae:2180.15958
[192]	validation_0-mae:2179.83907
[193]	validation_0-mae:2179.34695
[194]	validation_0-mae:2179.41763
[195]	validation_0-mae:2178.03008
[196]	validation_0-mae:2177.53207
[197]	validation_0-mae:2177.63861
[198]	validation_0-mae:2177.83560
[199]	validation_0-mae:2177.96287
[200]	validation_0-mae:2176.70263
[201]	validation_0-mae:2173.56081
[202]	validation_0-mae:2172.25179
[203]	validation_0-mae:2171.25372
[204]	validation_0-mae:2171.57364
[205]	validation_0-mae:2171.76079
[206]	validation_0-mae:2171.20279
[207]	validation_0-mae:2170.63131
[208]	validation_0-mae:2170.51049
[209]	validation_0-mae:2168.96074
[210]	validation_0-mae:2167.66626
[211]	validation_0-mae:2165.65324
[212]	validation_0-mae:2164.86891
[213]	validation_0-mae:2165.91535
[214]	validation_0-mae:2164.03389
[215]	validation_0-mae:2163.30760
[216]	validation_0-mae:2161.66892
[217]	validation_0-mae:2161.62452
[218]	validation_0-mae:2160.61493
[219]	validation_0-mae:2161.37973
[220]	validation_0-mae:2160.14211
[221]	validation_0-mae:2161.44850
[222]	validation_0-mae:2160.04797
[223]	validation_0-mae:2160.01561
[224]	validation_0-mae:2159.50920
[225]	validation_0-mae:2159.90217
[226]	validation_0-mae:2160.43444
[227]	validation_0-mae:2160.37877
[228]	validation_0-mae:2158.52997
[229]	validation_0-mae:2154.42770
[230]	validation_0-mae:2153.46802
[231]	validation_0-mae:2154.12839
[232]	validation_0-mae:2153.40676
[233]	validation_0-mae:2152.27787
[234]	validation_0-mae:2150.43123
[235]	validation_0-mae:2148.69006
[236]	validation_0-mae:2146.00355
[237]	validation_0-mae:2145.76765
[238]	validation_0-mae:2145.45059
[239]	validation_0-mae:2144.78929
[240]	validation_0-mae:2144.76523
[241]	validation_0-mae:2142.61211
[242]	validation_0-mae:2141.25984
[243]	validation_0-mae:2141.02717
[244]	validation_0-mae:2141.00129
[245]	validation_0-mae:2139.61591
[246]	validation_0-mae:2138.90656
[247]	validation_0-mae:2138.59431
[248]	validation_0-mae:2138.56473
[249]	validation_0-mae:2137.90199
[250]	validation_0-mae:2137.33870
[251]	validation_0-mae:2135.87962
[252]	validation_0-mae:2133.96045
[253]	validation_0-mae:2130.74353
[254]	validation_0-mae:2129.54284
[255]	validation_0-mae:2128.85368
[256]	validation_0-mae:2128.73969
[257]	validation_0-mae:2128.18401
[258]	validation_0-mae:2126.61906
[259]	validation_0-mae:2126.23961
[260]	validation_0-mae:2124.46950
[261]	validation_0-mae:2123.72846
[262]	validation_0-mae:2122.66152
[263]	validation_0-mae:2120.69402
[264]	validation_0-mae:2120.39287
[265]	validation_0-mae:2119.78087
[266]	validation_0-mae:2119.79822
[267]	validation_0-mae:2119.67879
[268]	validation_0-mae:2119.98939
[269]	validation_0-mae:2120.05550
[270]	validation_0-mae:2119.51516
[271]	validation_0-mae:2118.25231
[272]	validation_0-mae:2118.68682
[273]	validation_0-mae:2118.98740
[274]	validation_0-mae:2117.07560
[275]	validation_0-mae:2116.46009
[276]	validation_0-mae:2116.02851
[277]	validation_0-mae:2115.24941
[278]	validation_0-mae:2116.06788
[279]	validation_0-mae:2115.36412
[280]	validation_0-mae:2114.32721
[281]	validation_0-mae:2114.22220
[282]	validation_0-mae:2113.97817
[283]	validation_0-mae:2113.86868
[284]	validation_0-mae:2114.04542
[285]	validation_0-mae:2113.98231
[286]	validation_0-mae:2113.43483
[287]	validation_0-mae:2112.62687
[288]	validation_0-mae:2111.19246
[289]	validation_0-mae:2111.54739
[290]	validation_0-mae:2109.71274
[291]	validation_0-mae:2109.19974
[292]	validation_0-mae:2109.72365
[293]	validation_0-mae:2110.19041
[294]	validation_0-mae:2109.92756
[295]	validation_0-mae:2109.70188
[296]	validation_0-mae:2109.33292
[297]	validation_0-mae:2108.89815
[298]	validation_0-mae:2107.62035
[299]	validation_0-mae:2106.89555
[300]	validation_0-mae:2107.72787
[301]	validation_0-mae:2107.69678
[302]	validation_0-mae:2107.17954
[303]	validation_0-mae:2107.17463
[304]	validation_0-mae:2107.02553
[305]	validation_0-mae:2107.15303
[306]	validation_0-mae:2107.25991
[307]	validation_0-mae:2106.89291
[308]	validation_0-mae:2106.98692
[309]	validation_0-mae:2107.22167
[310]	validation_0-mae:2106.00504
[311]	validation_0-mae:2105.72879
[312]	validation_0-mae:2104.73456
[313]	validation_0-mae:2104.21414
[314]	validation_0-mae:2104.39827
[315]	validation_0-mae:2104.23279
[316]	validation_0-mae:2102.84619
[317]	validation_0-mae:2102.64118
[318]	validation_0-mae:2102.76908
[319]	validation_0-mae:2102.51083
[320]	validation_0-mae:2102.16154
[321]	validation_0-mae:2101.79955
[322]	validation_0-mae:2102.28766
[323]	validation_0-mae:2102.44483
[324]	validation_0-mae:2101.00978
[325]	validation_0-mae:2100.78922
[326]	validation_0-mae:2099.18092
[327]	validation_0-mae:2097.59291
[328]	validation_0-mae:2097.62134
[329]	validation_0-mae:2097.39336
[330]	validation_0-mae:2097.36179
[331]	validation_0-mae:2096.94439
[332]	validation_0-mae:2096.94686
[333]	validation_0-mae:2096.95257
[334]	validation_0-mae:2096.59623
[335]	validation_0-mae:2095.75093
[336]	validation_0-mae:2095.25012
[337]	validation_0-mae:2094.47122
[338]	validation_0-mae:2094.54817
[339]	validation_0-mae:2094.63540
[340]	validation_0-mae:2094.87578
[341]	validation_0-mae:2094.72834
[342]	validation_0-mae:2094.62034
[343]	validation_0-mae:2093.76265
[344]	validation_0-mae:2092.15084
[345]	validation_0-mae:2091.99865
[346]	validation_0-mae:2091.79676
[347]	validation_0-mae:2091.43675
[348]	validation_0-mae:2091.97395
[349]	validation_0-mae:2090.80439
[350]	validation_0-mae:2091.14435
[351]	validation_0-mae:2090.49741
[352]	validation_0-mae:2090.36152
[353]	validation_0-mae:2090.27738
[354]	validation_0-mae:2089.54455
[355]	validation_0-mae:2089.51411
[356]	validation_0-mae:2090.19651
[357]	validation_0-mae:2089.47321
[358]	validation_0-mae:2088.96222
[359]	validation_0-mae:2089.42833
[360]	validation_0-mae:2089.73225
[361]	validation_0-mae:2089.61582
[362]	validation_0-mae:2089.19352
[363]	validation_0-mae:2089.78662
[364]	validation_0-mae:2089.63918
[365]	validation_0-mae:2089.10475
[366]	validation_0-mae:2089.79391
[367]	validation_0-mae:2089.90325
[368]	validation_0-mae:2089.35328
[369]	validation_0-mae:2088.55981
[370]	validation_0-mae:2088.67966
[371]	validation_0-mae:2087.61154
[372]	validation_0-mae:2086.88903
[373]	validation_0-mae:2086.86631
[374]	validation_0-mae:2086.04358
[375]	validation_0-mae:2085.10505
[376]	validation_0-mae:2084.63110
[377]	validation_0-mae:2083.78019
[378]	validation_0-mae:2083.52308
[379]	validation_0-mae:2082.80909
[380]	validation_0-mae:2081.75251
[381]	validation_0-mae:2081.99438
[382]	validation_0-mae:2082.34976
[383]	validation_0-mae:2081.14355
[384]	validation_0-mae:2080.40034
[385]	validation_0-mae:2080.27923
[386]	validation_0-mae:2079.84685
[387]	validation_0-mae:2079.58826
[388]	validation_0-mae:2079.30174
[389]	validation_0-mae:2079.34473
[390]	validation_0-mae:2079.41716
[391]	validation_0-mae:2079.67545
[392]	validation_0-mae:2079.41779
[393]	validation_0-mae:2079.41126
[394]	validation_0-mae:2079.90540
[395]	validation_0-mae:2079.49068
[396]	validation_0-mae:2079.56253
[397]	validation_0-mae:2079.85326
[398]	validation_0-mae:2079.78761
[399]	validation_0-mae:2079.45740
[400]	validation_0-mae:2079.41455
[401]	validation_0-mae:2079.41150
[402]	validation_0-mae:2078.97679
[403]	validation_0-mae:2078.57844
[404]	validation_0-mae:2077.89944
[405]	validation_0-mae:2076.70195
[406]	validation_0-mae:2076.80955
[407]	validation_0-mae:2076.57254
[408]	validation_0-mae:2076.48958
[409]	validation_0-mae:2076.63151
[410]	validation_0-mae:2077.13274
[411]	validation_0-mae:2077.24889
[412]	validation_0-mae:2077.10044
[413]	validation_0-mae:2077.31388
[414]	validation_0-mae:2077.24521
[415]	validation_0-mae:2076.73168
[416]	validation_0-mae:2076.36545
[417]	validation_0-mae:2075.72189
[418]	validation_0-mae:2075.03342
[419]	validation_0-mae:2075.27004
[420]	validation_0-mae:2075.44429
[421]	validation_0-mae:2074.90398
[422]	validation_0-mae:2074.54543
[423]	validation_0-mae:2074.49064
[424]	validation_0-mae:2074.34549
[425]	validation_0-mae:2074.40622
[426]	validation_0-mae:2074.02605
[427]	validation_0-mae:2074.01553
[428]	validation_0-mae:2073.30478
[429]	validation_0-mae:2073.14822
[430]	validation_0-mae:2072.61344
[431]	validation_0-mae:2072.49669
[432]	validation_0-mae:2072.62429
[433]	validation_0-mae:2072.38228
[434]	validation_0-mae:2071.50363
[435]	validation_0-mae:2070.73663
[436]	validation_0-mae:2070.67745
[437]	validation_0-mae:2071.07524
[438]	validation_0-mae:2071.34206
[439]	validation_0-mae:2071.26863
[440]	validation_0-mae:2071.19272
[441]	validation_0-mae:2071.22623
[442]	validation_0-mae:2071.39939
[443]	validation_0-mae:2071.74473
[444]	validation_0-mae:2071.42649
[445]	validation_0-mae:2070.94991
[446]	validation_0-mae:2071.18487
[447]	validation_0-mae:2071.13574
[448]	validation_0-mae:2071.56497
[449]	validation_0-mae:2071.54889
[450]	validation_0-mae:2071.23698
[451]	validation_0-mae:2071.05893
[452]	validation_0-mae:2071.20909
[453]	validation_0-mae:2071.01373
[454]	validation_0-mae:2071.12166
[455]	validation_0-mae:2071.19601
[456]	validation_0-mae:2071.03891
[457]	validation_0-mae:2071.24983
[458]	validation_0-mae:2071.29457
[459]	validation_0-mae:2070.89648
[460]	validation_0-mae:2071.27762
[461]	validation_0-mae:2071.76240
[462]	validation_0-mae:2071.97391
[463]	validation_0-mae:2072.19774
[464]	validation_0-mae:2072.41262
[465]	validation_0-mae:2072.52899
[466]	validation_0-mae:2071.97753
[467]	validation_0-mae:2072.28340
[468]	validation_0-mae:2071.77960
[469]	validation_0-mae:2072.15636
[470]	validation_0-mae:2072.24916
[471]	validation_0-mae:2072.43416
[472]	validation_0-mae:2072.38117
[473]	validation_0-mae:2072.09691
[474]	validation_0-mae:2071.66373
[475]	validation_0-mae:2071.43118
[476]	validation_0-mae:2071.42430
[477]	validation_0-mae:2071.46612
[478]	validation_0-mae:2071.47363
[479]	validation_0-mae:2071.62516
[480]	validation_0-mae:2071.67090
[481]	validation_0-mae:2071.77773
[482]	validation_0-mae:2072.18868
[483]	validation_0-mae:2071.84694
[484]	validation_0-mae:2071.94964
[485]	validation_0-mae:2071.92860
[486]	validation_0-mae:2072.15718
[487]	validation_0-mae:2072.35501
[488]	validation_0-mae:2072.48759
[489]	validation_0-mae:2072.93773
[490]	validation_0-mae:2073.45247
[491]	validation_0-mae:2073.50664
[492]	validation_0-mae:2072.57354
[493]	validation_0-mae:2072.64868
[494]	validation_0-mae:2072.59494
[495]	validation_0-mae:2072.96529
[496]	validation_0-mae:2072.86610
[497]	validation_0-mae:2073.10419
[498]	validation_0-mae:2073.46365
[499]	validation_0-mae:2073.33609
[500]	validation_0-mae:2073.17233
[501]	validation_0-mae:2072.32163
[502]	validation_0-mae:2072.27161
[503]	validation_0-mae:2072.87142
[504]	validation_0-mae:2073.04715
[505]	validation_0-mae:2073.18622
[506]	validation_0-mae:2073.45759
[507]	validation_0-mae:2073.52364
[508]	validation_0-mae:2073.48646
[509]	validation_0-mae:2073.56770
[510]	validation_0-mae:2073.89877
[511]	validation_0-mae:2074.02307
[512]	validation_0-mae:2074.02370
[513]	validation_0-mae:2074.23994
[514]	validation_0-mae:2074.31718
[515]	validation_0-mae:2074.11420
[516]	validation_0-mae:2073.29212
[517]	validation_0-mae:2073.11620
[518]	validation_0-mae:2072.94562
[519]	validation_0-mae:2072.94879
[520]	validation_0-mae:2073.08433
[521]	validation_0-mae:2073.50481
[522]	validation_0-mae:2073.65195
[523]	validation_0-mae:2073.59658
[524]	validation_0-mae:2073.69819
[525]	validation_0-mae:2073.71102
[526]	validation_0-mae:2072.92935
[527]	validation_0-mae:2072.70428
[528]	validation_0-mae:2072.31517
[529]	validation_0-mae:2071.95267
[530]	validation_0-mae:2072.06633
[531]	validation_0-mae:2072.19747
[532]	validation_0-mae:2072.39766
[533]	validation_0-mae:2072.37210
[534]	validation_0-mae:2072.47705
[535]	validation_0-mae:2072.46871
[536]	validation_0-mae:2072.59509
[537]	validation_0-mae:2072.44912
[538]	validation_0-mae:2072.81368
[539]	validation_0-mae:2072.89749
[540]	validation_0-mae:2072.82564
[541]	validation_0-mae:2072.71367
[542]	validation_0-mae:2072.39394
[543]	validation_0-mae:2072.45048
[544]	validation_0-mae:2072.59103
[545]	validation_0-mae:2072.38844
[546]	validation_0-mae:2072.31613
[547]	validation_0-mae:2072.46464
[548]	validation_0-mae:2073.22064
[549]	validation_0-mae:2071.48742
[550]	validation_0-mae:2071.02403
[551]	validation_0-mae:2070.62768
[552]	validation_0-mae:2070.64484
[553]	validation_0-mae:2070.58669
[554]	validation_0-mae:2070.70318
[555]	validation_0-mae:2070.79151
[556]	validation_0-mae:2070.85139
[557]	validation_0-mae:2071.13967
[558]	validation_0-mae:2071.36677
[559]	validation_0-mae:2070.37832
[560]	validation_0-mae:2070.03664
[561]	validation_0-mae:2069.12651
[562]	validation_0-mae:2069.06010
[563]	validation_0-mae:2069.03206
[564]	validation_0-mae:2068.57872
[565]	validation_0-mae:2068.31963
[566]	validation_0-mae:2068.45806
[567]	validation_0-mae:2068.13579
[568]	validation_0-mae:2068.00694
[569]	validation_0-mae:2068.16597
[570]	validation_0-mae:2068.05496
[571]	validation_0-mae:2068.06171
[572]	validation_0-mae:2068.12403
[573]	validation_0-mae:2068.22474
[574]	validation_0-mae:2068.18258
[575]	validation_0-mae:2068.24159
[576]	validation_0-mae:2068.10488
[577]	validation_0-mae:2068.22338
[578]	validation_0-mae:2068.06414
[579]	validation_0-mae:2068.25500
[580]	validation_0-mae:2068.41910
[581]	validation_0-mae:2068.41124
[582]	validation_0-mae:2068.64842
[583]	validation_0-mae:2068.57556
[584]	validation_0-mae:2068.25407
[585]	validation_0-mae:2068.17569
[586]	validation_0-mae:2068.00068
[587]	validation_0-mae:2067.90903
[588]	validation_0-mae:2067.68071
[589]	validation_0-mae:2067.66294
[590]	validation_0-mae:2067.73051
[591]	validation_0-mae:2067.79587

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[38]	validation_0-mae:3356.83865
[39]	validation_0-mae:3314.54822
[40]	validation_0-mae:3274.49563
[41]	validation_0-mae:3236.89620
[42]	validation_0-mae:3189.74287
[43]	validation_0-mae:3148.70735
[44]	validation_0-mae:3115.93318
[45]	validation_0-mae:3086.22037
[46]	validation_0-mae:3050.42705
[47]	validation_0-mae:3020.87192
[48]	validation_0-mae:2984.20850
[49]	validation_0-mae:2962.95209
[50]	validation_0-mae:2923.83721
[51]	validation_0-mae:2904.94394
[52]	validation_0-mae:2887.69084
[53]	validation_0-mae:2863.83174
[54]	validation_0-mae:2846.17421
[55]	validation_0-mae:2834.53462
[56]	validation_0-mae:2817.16402
[57]	validation_0-mae:2789.01836
[58]	validation_0-mae:2768.19156
[59]	validation_0-mae:2756.35743
[60]	validation_0-mae:2744.62822
[61]	validation_0-mae:2727.60950
[62]	validation_0-mae:2714.12388
[63]	validation_0-mae:2697.54141
[64]	validation_0-mae:2688.99371
[65]	validation_0-mae:2675.71351
[66]	validation_0-mae:2666.55331
[67]	validation_0-mae:2657.83280
[68]	validation_0-mae:2646.00733
[69]	validation_0-mae:2626.52531
[70]	validation_0-mae:2615.15043
[71]	validation_0-mae:2605.16468
[72]	validation_0-mae:2597.67391
[73]	validation_0-mae:2588.28322
[74]	validation_0-mae:2574.74109
[75]	validation_0-mae:2568.27526
[76]	validation_0-mae:2562.36959
[77]	validation_0-mae:2539.91960
[78]	validation_0-mae:2529.67900
[79]	validation_0-mae:2517.68493
[80]	validation_0-mae:2503.03113
[81]	validation_0-mae:2492.21817
[82]	validation_0-mae:2484.27119
[83]	validation_0-mae:2479.42981
[84]	validation_0-mae:2471.68455
[85]	validation_0-mae:2465.32407
[86]	validation_0-mae:2448.57503
[87]	validation_0-mae:2436.73095
[88]	validation_0-mae:2425.09095
[89]	validation_0-mae:2417.74848
[90]	validation_0-mae:2413.79312
[91]	validation_0-mae:2407.91668
[92]	validation_0-mae:2403.29028
[93]	validation_0-mae:2398.73161
[94]	validation_0-mae:2391.59813
[95]	validation_0-mae:2379.02400
[96]	validation_0-mae:2373.15955
[97]	validation_0-mae:2362.47591
[98]	validation_0-mae:2359.61426
[99]	validation_0-mae:2357.75629
[100]	validation_0-mae:2353.73633
[101]	validation_0-mae:2347.71771
[102]	validation_0-mae:2345.69040
[103]	validation_0-mae:2341.92280
[104]	validation_0-mae:2338.75724
[105]	validation_0-mae:2329.82783
[106]	validation_0-mae:2326.52379
[107]	validation_0-mae:2322.21623
[108]	validation_0-mae:2320.45370
[109]	validation_0-mae:2314.44903
[110]	validation_0-mae:2313.89784
[111]	validation_0-mae:2311.78356
[112]	validation_0-mae:2306.07834
[113]	validation_0-mae:2304.61852
[114]	validation_0-mae:2300.53893
[115]	validation_0-mae:2293.14167
[116]	validation_0-mae:2291.23635
[117]	validation_0-mae:2291.02474
[118]	validation_0-mae:2285.98148
[119]	validation_0-mae:2281.95723
[120]	validation_0-mae:2278.50579
[121]	validation_0-mae:2275.59146
[122]	validation_0-mae:2275.29787
[123]	validation_0-mae:2271.64999
[124]	validation_0-mae:2269.86512
[125]	validation_0-mae:2267.21439
[126]	validation_0-mae:2265.14090
[127]	validation_0-mae:2262.33639
[128]	validation_0-mae:2261.64868
[129]	validation_0-mae:2256.76321
[130]	validation_0-mae:2256.15511
[131]	validation_0-mae:2254.15982
[132]	validation_0-mae:2249.17019
[133]	validation_0-mae:2248.08023
[134]	validation_0-mae:2244.08152
[135]	validation_0-mae:2239.90773
[136]	validation_0-mae:2240.22974
[137]	validation_0-mae:2238.28385
[138]	validation_0-mae:2236.74373
[139]	validation_0-mae:2238.64564
[140]	validation_0-mae:2235.68101
[141]	validation_0-mae:2234.55637
[142]	validation_0-mae:2232.79873
[143]	validation_0-mae:2230.21241
[144]	validation_0-mae:2228.36629
[145]	validation_0-mae:2228.06798
[146]	validation_0-mae:2226.06807
[147]	validation_0-mae:2224.79951
[148]	validation_0-mae:2223.85192
[149]	validation_0-mae:2222.99114
[150]	validation_0-mae:2220.26118
[151]	validation_0-mae:2216.49302
[152]	validation_0-mae:2216.29255
[153]	validation_0-mae:2215.70533
[154]	validation_0-mae:2212.49483
[155]	validation_0-mae:2211.65463
[156]	validation_0-mae:2210.10827
[157]	validation_0-mae:2207.99877
[158]	validation_0-mae:2207.60613
[159]	validation_0-mae:2207.31852
[160]	validation_0-mae:2205.91151
[161]	validation_0-mae:2205.34228
[162]	validation_0-mae:2203.46790
[163]	validation_0-mae:2202.83562
[164]	validation_0-mae:2201.96127
[165]	validation_0-mae:2200.75189
[166]	validation_0-mae:2200.09771
[167]	validation_0-mae:2196.10554
[168]	validation_0-mae:2195.26748
[169]	validation_0-mae:2193.76859
[170]	validation_0-mae:2194.28266
[171]	validation_0-mae:2193.17830
[172]	validation_0-mae:2190.56237
[173]	validation_0-mae:2189.60709
[174]	validation_0-mae:2189.03100
[175]	validation_0-mae:2187.56347
[176]	validation_0-mae:2186.60992
[177]	validation_0-mae:2186.01167
[178]	validation_0-mae:2184.71168
[179]	validation_0-mae:2184.74618
[180]	validation_0-mae:2185.78083
[181]	validation_0-mae:2184.10881
[182]	validation_0-mae:2184.85460
[183]	validation_0-mae:2185.01096
[184]	validation_0-mae:2183.23597
[185]	validation_0-mae:2181.63408
[186]	validation_0-mae:2182.19781
[187]	validation_0-mae:2180.87023
[188]	validation_0-mae:2180.76121
[189]	validation_0-mae:2180.13584
[190]	validation_0-mae:2180.22202
[191]	validation_0-mae:2178.60344
[192]	validation_0-mae:2178.43046
[193]	validation_0-mae:2176.77158
[194]	validation_0-mae:2177.59078
[195]	validation_0-mae:2176.68637
[196]	validation_0-mae:2175.03334
[197]	validation_0-mae:2173.74611
[198]	validation_0-mae:2174.06323
[199]	validation_0-mae:2173.47508
[200]	validation_0-mae:2173.23999
[201]	validation_0-mae:2174.02564
[202]	validation_0-mae:2174.20979
[203]	validation_0-mae:2172.29800
[204]	validation_0-mae:2171.78936
[205]	validation_0-mae:2171.49745
[206]	validation_0-mae:2170.41791
[207]	validation_0-mae:2168.65202
[208]	validation_0-mae:2168.85142
[209]	validation_0-mae:2168.60125
[210]	validation_0-mae:2168.87668
[211]	validation_0-mae:2169.02671
[212]	validation_0-mae:2168.68549
[213]	validation_0-mae:2168.66911
[214]	validation_0-mae:2168.61170
[215]	validation_0-mae:2167.43229
[216]	validation_0-mae:2166.06320
[217]	validation_0-mae:2166.61672
[218]	validation_0-mae:2165.43756
[219]	validation_0-mae:2164.61967
[220]	validation_0-mae:2164.44115
[221]	validation_0-mae:2162.01548
[222]	validation_0-mae:2160.30814
[223]	validation_0-mae:2160.61856
[224]	validation_0-mae:2157.82550
[225]	validation_0-mae:2156.84345
[226]	validation_0-mae:2156.67273
[227]	validation_0-mae:2155.94179
[228]	validation_0-mae:2154.88701
[229]	validation_0-mae:2154.86473
[230]	validation_0-mae:2155.16798
[231]	validation_0-mae:2155.75455
[232]	validation_0-mae:2155.48752
[233]	validation_0-mae:2154.83769
[234]	validation_0-mae:2154.65512
[235]	validation_0-mae:2153.25991
[236]	validation_0-mae:2153.26691
[237]	validation_0-mae:2152.81733
[238]	validation_0-mae:2151.39453
[239]	validation_0-mae:2151.35363
[240]	validation_0-mae:2151.40520
[241]	validation_0-mae:2150.27463
[242]	validation_0-mae:2149.14441
[243]	validation_0-mae:2148.21346
[244]	validation_0-mae:2147.93562
[245]	validation_0-mae:2148.45080
[246]	validation_0-mae:2148.18002
[247]	validation_0-mae:2147.97831
[248]	validation_0-mae:2147.35011
[249]	validation_0-mae:2146.76806
[250]	validation_0-mae:2146.24465
[251]	validation_0-mae:2145.25366
[252]	validation_0-mae:2145.55361
[253]	validation_0-mae:2145.40833
[254]	validation_0-mae:2143.96426
[255]	validation_0-mae:2144.63714
[256]	validation_0-mae:2145.26297
[257]	validation_0-mae:2145.07899
[258]	validation_0-mae:2145.34162
[259]	validation_0-mae:2144.75227
[260]	validation_0-mae:2145.22942
[261]	validation_0-mae:2145.05085
[262]	validation_0-mae:2144.13207
[263]	validation_0-mae:2144.15778
[264]	validation_0-mae:2144.07344
[265]	validation_0-mae:2143.55403
[266]	validation_0-mae:2143.24904
[267]	validation_0-mae:2141.63205
[268]	validation_0-mae:2140.13368
[269]	validation_0-mae:2139.40807
[270]	validation_0-mae:2138.61873
[271]	validation_0-mae:2138.20356
[272]	validation_0-mae:2137.96746
[273]	validation_0-mae:2137.58689
[274]	validation_0-mae:2136.56166
[275]	validation_0-mae:2135.04225
[276]	validation_0-mae:2134.96990
[277]	validation_0-mae:2135.12935
[278]	validation_0-mae:2133.59625
[279]	validation_0-mae:2133.35090
[280]	validation_0-mae:2133.30673
[281]	validation_0-mae:2132.44436
[282]	validation_0-mae:2132.79102
[283]	validation_0-mae:2131.03443
[284]	validation_0-mae:2129.74016
[285]	validation_0-mae:2130.56696
[286]	validation_0-mae:2130.90818
[287]	validation_0-mae:2130.66553
[288]	validation_0-mae:2130.31512
[289]	validation_0-mae:2129.44325
[290]	validation_0-mae:2128.25632
[291]	validation_0-mae:2128.48354
[292]	validation_0-mae:2127.81926
[293]	validation_0-mae:2127.50907
[294]	validation_0-mae:2128.22903
[295]	validation_0-mae:2127.97490
[296]	validation_0-mae:2127.09934
[297]	validation_0-mae:2127.14786
[298]	validation_0-mae:2126.13297
[299]	validation_0-mae:2126.28168
[300]	validation_0-mae:2126.52361
[301]	validation_0-mae:2125.86319
[302]	validation_0-mae:2125.07115
[303]	validation_0-mae:2125.14648
[304]	validation_0-mae:2123.82008
[305]	validation_0-mae:2123.91213
[306]	validation_0-mae:2123.22780
[307]	validation_0-mae:2122.39362
[308]	validation_0-mae:2122.47979
[309]	validation_0-mae:2122.29264
[310]	validation_0-mae:2122.11243
[311]	validation_0-mae:2121.40321
[312]	validation_0-mae:2121.49743
[313]	validation_0-mae:2121.56221
[314]	validation_0-mae:2121.54566
[315]	validation_0-mae:2120.92028
[316]	validation_0-mae:2121.09385
[317]	validation_0-mae:2120.51900
[318]	validation_0-mae:2119.68604
[319]	validation_0-mae:2119.24130
[320]	validation_0-mae:2118.27041
[321]	validation_0-mae:2118.11116
[322]	validation_0-mae:2117.83376
[323]	validation_0-mae:2117.55854
[324]	validation_0-mae:2116.65228
[325]	validation_0-mae:2116.99578
[326]	validation_0-mae:2117.18523
[327]	validation_0-mae:2117.21997
[328]	validation_0-mae:2117.09176
[329]	validation_0-mae:2115.91163
[330]	validation_0-mae:2116.13138
[331]	validation_0-mae:2115.83989
[332]	validation_0-mae:2116.11426
[333]	validation_0-mae:2115.97874
[334]	validation_0-mae:2116.62884
[335]	validation_0-mae:2116.87815
[336]	validation_0-mae:2115.84542
[337]	validation_0-mae:2116.00746
[338]	validation_0-mae:2116.14668
[339]	validation_0-mae:2115.35384
[340]	validation_0-mae:2113.84975
[341]	validation_0-mae:2113.19561
[342]	validation_0-mae:2113.54869
[343]	validation_0-mae:2113.31847
[344]	validation_0-mae:2113.43257
[345]	validation_0-mae:2114.22241
[346]	validation_0-mae:2114.06396
[347]	validation_0-mae:2111.42449
[348]	validation_0-mae:2110.86812
[349]	validation_0-mae:2110.76816
[350]	validation_0-mae:2111.03012
[351]	validation_0-mae:2110.66469
[352]	validation_0-mae:2110.67987
[353]	validation_0-mae:2110.98733
[354]	validation_0-mae:2110.68186
[355]	validation_0-mae:2110.35366
[356]	validation_0-mae:2110.38755
[357]	validation_0-mae:2110.60714
[358]	validation_0-mae:2111.21610
[359]	validation_0-mae:2110.88517
[360]	validation_0-mae:2111.13172
[361]	validation_0-mae:2111.29265
[362]	validation_0-mae:2111.36027
[363]	validation_0-mae:2111.02522
[364]	validation_0-mae:2110.91084
[365]	validation_0-mae:2110.04305
[366]	validation_0-mae:2109.87562
[367]	validation_0-mae:2109.29779
[368]	validation_0-mae:2109.21343
[369]	validation_0-mae:2109.54697
[370]	validation_0-mae:2109.37879
[371]	validation_0-mae:2109.15519
[372]	validation_0-mae:2108.93150
[373]	validation_0-mae:2108.86327
[374]	validation_0-mae:2107.92230
[375]	validation_0-mae:2108.81504
[376]	validation_0-mae:2108.59550
[377]	validation_0-mae:2107.76076
[378]	validation_0-mae:2107.23384
[379]	validation_0-mae:2106.72448
[380]	validation_0-mae:2105.66880
[381]	validation_0-mae:2105.61811
[382]	validation_0-mae:2105.91323
[383]	validation_0-mae:2106.15091
[384]	validation_0-mae:2106.16606
[385]	validation_0-mae:2106.41581
[386]	validation_0-mae:2106.07843
[387]	validation_0-mae:2104.36695
[388]	validation_0-mae:2104.16105
[389]	validation_0-mae:2104.66319
[390]	validation_0-mae:2104.82261
[391]	validation_0-mae:2104.10019
[392]	validation_0-mae:2104.68833
[393]	validation_0-mae:2104.17104
[394]	validation_0-mae:2104.42720
[395]	validation_0-mae:2103.88877
[396]	validation_0-mae:2103.89115
[397]	validation_0-mae:2102.95732
[398]	validation_0-mae:2103.56773
[399]	validation_0-mae:2104.11687
[400]	validation_0-mae:2104.84999
[401]	validation_0-mae:2105.11214
[402]	validation_0-mae:2104.68795
[403]	validation_0-mae:2104.37797
[404]	validation_0-mae:2103.97269
[405]	validation_0-mae:2104.47419
[406]	validation_0-mae:2103.25771
[407]	validation_0-mae:2103.13003
[408]	validation_0-mae:2103.32978
[409]	validation_0-mae:2102.84204
[410]	validation_0-mae:2103.07865
[411]	validation_0-mae:2103.06392
[412]	validation_0-mae:2102.30577
[413]	validation_0-mae:2102.61712
[414]	validation_0-mae:2102.83098
[415]	validation_0-mae:2101.72253
[416]	validation_0-mae:2100.50647
[417]	validation_0-mae:2099.99953
[418]	validation_0-mae:2100.21961
[419]	validation_0-mae:2100.10602
[420]	validation_0-mae:2099.93787
[421]	validation_0-mae:2100.00958
[422]	validation_0-mae:2099.76713
[423]	validation_0-mae:2099.29940
[424]	validation_0-mae:2099.33782
[425]	validation_0-mae:2099.49809
[426]	validation_0-mae:2098.86225
[427]	validation_0-mae:2098.76123
[428]	validation_0-mae:2098.67994
[429]	validation_0-mae:2098.55555
[430]	validation_0-mae:2098.41543
[431]	validation_0-mae:2098.42699
[432]	validation_0-mae:2098.11903
[433]	validation_0-mae:2097.79165
[434]	validation_0-mae:2097.52671
[435]	validation_0-mae:2097.83643
[436]	validation_0-mae:2096.71762
[437]	validation_0-mae:2096.47101
[438]	validation_0-mae:2097.04175
[439]	validation_0-mae:2097.39424
[440]	validation_0-mae:2097.15582
[441]	validation_0-mae:2096.87228
[442]	validation_0-mae:2096.92507
[443]	validation_0-mae:2096.96607
[444]	validation_0-mae:2097.11118
[445]	validation_0-mae:2097.37471
[446]	validation_0-mae:2097.29584
[447]	validation_0-mae:2097.57950
[448]	validation_0-mae:2097.39763
[449]	validation_0-mae:2097.83514
[450]	validation_0-mae:2098.32402
[451]	validation_0-mae:2098.10249
[452]	validation_0-mae:2098.52114
[453]	validation_0-mae:2098.77609
[454]	validation_0-mae:2098.41247
[455]	validation_0-mae:2098.29826
[456]	validation_0-mae:2098.49282
[457]	validation_0-mae:2099.16882
[458]	validation_0-mae:2100.02649
[459]	validation_0-mae:2100.08160
[460]	validation_0-mae:2100.14095
[461]	validation_0-mae:2101.16037
[462]	validation_0-mae:2101.03205
[463]	validation_0-mae:2101.14783
[464]	validation_0-mae:2101.63471
[465]	validation_0-mae:2100.63934
[466]	validation_0-mae:2100.10191
[467]	validation_0-mae:2099.71869
[468]	validation_0-mae:2099.57339
[469]	validation_0-mae:2099.56790
[470]	validation_0-mae:2100.00591
[471]	validation_0-mae:2099.76426
[472]	validation_0-mae:2099.95303
[473]	validation_0-mae:2099.80682
[474]	validation_0-mae:2100.05873
[475]	validation_0-mae:2100.45246
[476]	validation_0-mae:2100.52145
[477]	validation_0-mae:2100.86167
[478]	validation_0-mae:2100.71193
[479]	validation_0-mae:2100.20154
[480]	validation_0-mae:2099.52415
[481]	validation_0-mae:2099.52519
[482]	validation_0-mae:2098.83342
[483]	validation_0-mae:2098.62674
[484]	validation_0-mae:2098.40244
[485]	validation_0-mae:2098.70079
[486]	validation_0-mae:2098.72640
[487]	validation_0-mae:2097.51565
[488]	validation_0-mae:2097.19917
[489]	validation_0-mae:2096.61263
[490]	validation_0-mae:2096.48928
[491]	validation_0-mae:2096.64114
[492]	validation_0-mae:2096.58671
[493]	validation_0-mae:2096.93189
[494]	validation_0-mae:2096.05620
[495]	validation_0-mae:2096.27584
[496]	validation_0-mae:2096.44319
[497]	validation_0-mae:2096.27727
[498]	validation_0-mae:2096.04978
[499]	validation_0-mae:2096.31472
[500]	validation_0-mae:2096.46018
[501]	validation_0-mae:2096.40505
[502]	validation_0-mae:2096.31658
[503]	validation_0-mae:2095.68240
[504]	validation_0-mae:2095.50320
[505]	validation_0-mae:2095.49388
[506]	validation_0-mae:2095.55901
[507]	validation_0-mae:2095.42618
[508]	validation_0-mae:2095.15516
[509]	validation_0-mae:2094.58315
[510]	validation_0-mae:2094.68220
[511]	validation_0-mae:2094.80380
[512]	validation_0-mae:2094.80520
[513]	validation_0-mae:2094.82228
[514]	validation_0-mae:2094.91167
[515]	validation_0-mae:2094.81736
[516]	validation_0-mae:2094.82954
[517]	validation_0-mae:2094.25594
[518]	validation_0-mae:2094.44445
[519]	validation_0-mae:2094.38908
[520]	validation_0-mae:2094.40277
[521]	validation_0-mae:2094.15981
[522]	validation_0-mae:2094.55892
[523]	validation_0-mae:2094.56249
[524]	validation_0-mae:2094.77919
[525]	validation_0-mae:2094.89831
[526]	validation_0-mae:2095.34761
[527]	validation_0-mae:2095.52672
[528]	validation_0-mae:2095.74523
[529]	validation_0-mae:2095.98856
[530]	validation_0-mae:2096.19351
[531]	validation_0-mae:2095.31834
[532]	validation_0-mae:2095.21787
[533]	validation_0-mae:2095.21110
[534]	validation_0-mae:2094.91323
[535]	validation_0-mae:2094.99833
[536]	validation_0-mae:2095.05317
[537]	validation_0-mae:2094.27172
[538]	validation_0-mae:2094.24212
[539]	validation_0-mae:2094.40663
[540]	validation_0-mae:2094.62353
[541]	validation_0-mae:2094.05708
[542]	validation_0-mae:2094.21435
[543]	validation_0-mae:2094.03947
[544]	validation_0-mae:2094.09845
[545]	validation_0-mae:2094.23206
[546]	validation_0-mae:2093.96957
[547]	validation_0-mae:2093.97781
[548]	validation_0-mae:2094.04768
[549]	validation_0-mae:2093.62458
[550]	validation_0-mae:2093.12175
[551]	validation_0-mae:2092.75387
[552]	validation_0-mae:2092.78188
[553]	validation_0-mae:2092.80536
[554]	validation_0-mae:2092.72436
[555]	validation_0-mae:2092.19320
[556]	validation_0-mae:2092.09923
[557]	validation_0-mae:2092.08539
[558]	validation_0-mae:2092.33535
[559]	validation_0-mae:2092.48376
[560]	validation_0-mae:2093.03616
[561]	validation_0-mae:2092.95058
[562]	validation_0-mae:2092.83272
[563]	validation_0-mae:2092.61143
[564]	validation_0-mae:2092.47087
[565]	validation_0-mae:2092.37779
[566]	validation_0-mae:2092.23456
[567]	validation_0-mae:2092.24821
[568]	validation_0-mae:2092.25914
[569]	validation_0-mae:2092.07871
[570]	validation_0-mae:2092.16984
[571]	validation_0-mae:2092.51043
[572]	validation_0-mae:2092.45970
[573]	validation_0-mae:2092.55592
[574]	validation_0-mae:2092.11119
[575]	validation_0-mae:2091.84573
[576]	validation_0-mae:2091.32693
[577]	validation_0-mae:2090.86023
[578]	validation_0-mae:2090.96200
[579]	validation_0-mae:2090.48916
[580]	validation_0-mae:2089.77898
[581]	validation_0-mae:2089.92643
[582]	validation_0-mae:2089.76729
[583]	validation_0-mae:2089.70456
[584]	validation_0-mae:2090.03272
[585]	validation_0-mae:2090.06639
[586]	validation_0-mae:2089.86761
[587]	validation_0-mae:2089.76736
[588]	validation_0-mae:2088.87587
[589]	validation_0-mae:2088.98364
[590]	validation_0-mae:2088.86036
[591]	validation_0-mae:2088.88214
[592]	validation_0-mae:2089.21445
[593]	validation_0-mae:2089.28783
[594]	validation_0-mae:2089.09251
[595]	validation_0-mae:2089.07095
[596]	validation_0-mae:2089.08466
[597]	validation_0-mae:2089.11204
[598]	validation_0-mae:2089.16130
[599]	validation_0-mae:2089.21341
[600]	validation_0-mae:2089.01682
[601]	validation_0-mae:2089.02961
[602]	validation_0-mae:2089.12080
[603]	validation_0-mae:2088.83603
[604]	validation_0-mae:2088.18842
[605]	validation_0-mae:2087.85727
[606]	validation_0-mae:2087.76626
[607]	validation_0-mae:2087.89497
[608]	validation_0-mae:2087.80473
[609]	validation_0-mae:2087.03724
[610]	validation_0-mae:2086.84219
[611]	validation_0-mae:2086.60691
[612]	validation_0-mae:2086.66318
[613]	validation_0-mae:2086.37479
[614]	validation_0-mae:2085.94688
[615]	validation_0-mae:2086.02497
[616]	validation_0-mae:2086.24260
[617]	validation_0-mae:2086.05879
[618]	validation_0-mae:2086.05319
[619]	validation_0-mae:2085.86788
[620]	validation_0-mae:2085.96224
[621]	validation_0-mae:2086.19888
[622]	validation_0-mae:2086.43715
[623]	validation_0-mae:2086.24863
[624]	validation_0-mae:2086.15390
[625]	validation_0-mae:2086.37206
[626]	validation_0-mae:2086.47608
[627]	validation_0-mae:2086.62525

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[35]	validation_0-mae:3520.23643
[36]	validation_0-mae:3471.22832
[37]	validation_0-mae:3418.02948
[38]	validation_0-mae:3372.85515
[39]	validation_0-mae:3323.09174
[40]	validation_0-mae:3279.81408
[41]	validation_0-mae:3248.43573
[42]	validation_0-mae:3190.38351
[43]	validation_0-mae:3157.37647
[44]	validation_0-mae:3125.83625
[45]	validation_0-mae:3084.34161
[46]	validation_0-mae:3058.20835
[47]	validation_0-mae:3024.42346
[48]	validation_0-mae:2990.87630
[49]	validation_0-mae:2968.13041
[50]	validation_0-mae:2933.25416
[51]	validation_0-mae:2915.06783
[52]	validation_0-mae:2890.47293
[53]	validation_0-mae:2874.50810
[54]	validation_0-mae:2847.43277
[55]	validation_0-mae:2834.44339
[56]	validation_0-mae:2810.88816
[57]	validation_0-mae:2790.44587
[58]	validation_0-mae:2768.49770
[59]	validation_0-mae:2750.73574
[60]	validation_0-mae:2742.13228
[61]	validation_0-mae:2733.32550
[62]	validation_0-mae:2724.16385
[63]	validation_0-mae:2703.50936
[64]	validation_0-mae:2687.96158
[65]	validation_0-mae:2680.15104
[66]	validation_0-mae:2671.02449
[67]	validation_0-mae:2656.32318
[68]	validation_0-mae:2649.79697
[69]	validation_0-mae:2641.03888
[70]	validation_0-mae:2621.14417
[71]	validation_0-mae:2610.43479
[72]	validation_0-mae:2595.49396
[73]	validation_0-mae:2588.76349
[74]	validation_0-mae:2574.59658
[75]	validation_0-mae:2558.18965
[76]	validation_0-mae:2551.79644
[77]	validation_0-mae:2543.66437
[78]	validation_0-mae:2532.97115
[79]	validation_0-mae:2525.76268
[80]	validation_0-mae:2520.26445
[81]	validation_0-mae:2509.82522
[82]	validation_0-mae:2502.75758
[83]	validation_0-mae:2497.06066
[84]	validation_0-mae:2489.75776
[85]	validation_0-mae:2482.82950
[86]	validation_0-mae:2470.63896
[87]	validation_0-mae:2462.40257
[88]	validation_0-mae:2458.68754
[89]	validation_0-mae:2451.33003
[90]	validation_0-mae:2441.30831
[91]	validation_0-mae:2437.61271
[92]	validation_0-mae:2428.68275
[93]	validation_0-mae:2425.75760
[94]	validation_0-mae:2417.51420
[95]	validation_0-mae:2410.62025
[96]	validation_0-mae:2405.08950
[97]	validation_0-mae:2401.16572
[98]	validation_0-mae:2398.33613
[99]	validation_0-mae:2392.14906
[100]	validation_0-mae:2389.95601
[101]	validation_0-mae:2384.22656
[102]	validation_0-mae:2379.99848
[103]	validation_0-mae:2377.79017
[104]	validation_0-mae:2368.71515
[105]	validation_0-mae:2367.08585
[106]	validation_0-mae:2365.31666
[107]	validation_0-mae:2360.20115
[108]	validation_0-mae:2354.79378
[109]	validation_0-mae:2348.24299
[110]	validation_0-mae:2340.40198
[111]	validation_0-mae:2337.90383
[112]	validation_0-mae:2332.78811
[113]	validation_0-mae:2330.53791
[114]	validation_0-mae:2326.82966
[115]	validation_0-mae:2326.01753
[116]	validation_0-mae:2323.76950
[117]	validation_0-mae:2321.02166
[118]	validation_0-mae:2320.17671
[119]	validation_0-mae:2317.05614
[0]	validation_0-mae:12368.42254
[1]	validation_0-mae:11588.35117
[2]	validation_0-mae:10865.38034
[3]	validation_0-mae:10197.46187
[4]	validation_0-mae:9621.92702
[5]	validation_0-mae:9120.04664
[6]	validation_0-mae:8664.41631
[7]	validation_0-mae:8242.09930
[8]	validation_0-mae:7870.33754
[9]	validation_0-mae:7502.94237
[10]	validation_0-mae:7173.72482
[11]	validation_0-mae:6880.10037
[12]	validation_0-mae:6609.04329
[13]	validation_0-mae:6342.63622
[14]	validation_0-mae:6099.61949
[15]	validation_0-mae:5857.85725
[16]	validation_0-mae:5669.04781
[17]	validation_0-mae:5461.86487
[18]	validation_0-mae:5264.32740
[19]	validation_0-mae:5086.43878
[20]	validation_0-mae:4915.02281
[21]	validation_0-mae:4765.35024
[22]	validation_0-mae:4625.33937
[23]	validation_0-mae:4479.16653
[24]	validation_0-mae:4360.55146
[25]	validation_0-mae:4253.17103
[26]	validation_0-mae:4151.99669
[27]	validation_0-mae:4073.68050
[28]	validation_0-mae:3965.47713
[29]	validation_0-mae:3895.42742
[30]	validation_0-mae:3814.47807
[31]	validation_0-mae:3726.87379
[32]	validation_0-mae:3655.45862
[33]	validation_0-mae:3587.45620
[34]	validation_0-mae:3528.06048
[35]	validation_0-mae:3466.14986
[36]	validation_0-mae:3416.04110

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[37]	validation_0-mae:3372.86027
[38]	validation_0-mae:3326.78306
[39]	validation_0-mae:3291.51018
[40]	validation_0-mae:3252.56725
[41]	validation_0-mae:3218.53100
[42]	validation_0-mae:3172.73500
[43]	validation_0-mae:3139.86616
[44]	validation_0-mae:3107.79368
[45]	validation_0-mae:3078.07838
[46]	validation_0-mae:3040.43412
[47]	validation_0-mae:3015.25685
[48]	validation_0-mae:2986.45211
[49]	validation_0-mae:2963.49999
[50]	validation_0-mae:2943.52334
[51]	validation_0-mae:2916.77447
[52]	validation_0-mae:2896.53194
[53]	validation_0-mae:2878.07480
[54]	validation_0-mae:2864.19648
[55]	validation_0-mae:2839.26523
[56]	validation_0-mae:2818.08840
[57]	validation_0-mae:2798.91187
[58]	validation_0-mae:2783.00079
[59]	validation_0-mae:2771.87704
[60]	validation_0-mae:2759.97713
[61]	validation_0-mae:2746.38699
[62]	validation_0-mae:2717.40985
[63]	validation_0-mae:2709.55849
[64]	validation_0-mae:2690.04085
[65]	validation_0-mae:2668.07148
[66]	validation_0-mae:2644.97677
[67]	validation_0-mae:2637.10204
[68]	validation_0-mae:2625.77398
[69]	validation_0-mae:2615.13694
[70]	validation_0-mae:2602.72520
[71]	validation_0-mae:2595.95205
[72]	validation_0-mae:2583.04889
[73]	validation_0-mae:2575.16885
[74]	validation_0-mae:2565.86629
[75]	validation_0-mae:2558.81995
[76]	validation_0-mae:2554.38754
[77]	validation_0-mae:2550.51862
[78]	validation_0-mae:2541.58933
[79]	validation_0-mae:2531.46978
[80]	validation_0-mae:2523.89591
[81]	validation_0-mae:2506.92009
[82]	validation_0-mae:2499.47721
[83]	validation_0-mae:2496.91470
[84]	validation_0-mae:2491.27383
[85]	validation_0-mae:2488.41322
[86]	validation_0-mae:2478.75263
[87]	validation_0-mae:2467.96556
[88]	validation_0-mae:2460.84808
[89]	validation_0-mae:2455.92711
[90]	validation_0-mae:2452.67511
[91]	validation_0-mae:2445.34633
[92]	validation_0-mae:2440.76583
[93]	validation_0-mae:2433.02088
[94]	validation_0-mae:2427.56689
[95]	validation_0-mae:2422.80119
[96]	validation_0-mae:2417.45937
[97]	validation_0-mae:2408.92909
[98]	validation_0-mae:2404.09064
[99]	validation_0-mae:2396.98605
[100]	validation_0-mae:2390.74205
[101]	validation_0-mae:2385.62403
[102]	validation_0-mae:2381.06537
[103]	validation_0-mae:2378.28159
[104]	validation_0-mae:2375.60962
[105]	validation_0-mae:2369.18749
[106]	validation_0-mae:2363.90702
[107]	validation_0-mae:2361.45539
[108]	validation_0-mae:2356.35943
[109]	validation_0-mae:2352.32288
[0]	validation_0-mae:12425.03385
[1]	validation_0-mae:11670.78089
[2]	validation_0-mae:10998.64336
[3]	validation_0-mae:10389.42335
[4]	validation_0-mae:9849.06651
[5]	validation_0-mae:9344.19872
[6]	validation_0-mae:8920.98727
[7]	validation_0-mae:8520.68604
[8]	validation_0-mae:8150.22018
[9]	validation_0-mae:7812.62071
[10]	validation_0-mae:7514.37021
[11]	validation_0-mae:7209.38854
[12]	validation_0-mae:6921.23621
[13]	validation_0-mae:6639.46533
[14]	validation_0-mae:6406.99265
[15]	validation_0-mae:6187.45439
[16]	validation_0-mae:5967.61540
[17]	validation_0-mae:5747.13172
[18]	validation_0-mae:5565.60204
[19]	validation_0-mae:5376.21162
[20]	validation_0-mae:5227.72895
[21]	validation_0-mae:5068.26755
[22]	validation_0-mae:4914.77358
[23]	validation_0-mae:4777.33265
[24]	validation_0-mae:4656.52035
[25]	validation_0-mae:4522.47317
[26]	validation_0-mae:4417.13761
[27]	validation_0-mae:4307.91451
[28]	validation_0-mae:4206.48793
[29]	validation_0-mae:4110.99508
[30]	validation_0-mae:4015.61643
[31]	validation_0-mae:3927.76909
[32]	validation_0-mae:3850.26477
[33]	validation_0-mae:3782.66550

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[34]	validation_0-mae:3719.58895
[35]	validation_0-mae:3647.73361
[36]	validation_0-mae:3584.22748
[37]	validation_0-mae:3513.90481
[38]	validation_0-mae:3463.76976
[39]	validation_0-mae:3409.79519
[40]	validation_0-mae:3364.49385
[41]	validation_0-mae:3323.24675
[42]	validation_0-mae:3275.82192
[43]	validation_0-mae:3240.04214
[44]	validation_0-mae:3205.83324
[45]	validation_0-mae:3180.50014
[0]	validation_0-mae:12396.05226
[1]	validation_0-mae:11612.84712
[2]	validation_0-mae:10906.44675
[3]	validation_0-mae:10275.06906
[4]	validation_0-mae:9708.36121
[5]	validation_0-mae:9180.14667
[6]	validation_0-mae:8724.02739
[7]	validation_0-mae:8324.65869
[8]	validation_0-mae:7966.80281
[9]	validation_0-mae:7614.85999
[10]	validation_0-mae:7272.75973
[11]	validation_0-mae:7004.88563
[12]	validation_0-mae:6738.93382
[13]	validation_0-mae:6480.92824
[14]	validation_0-mae:6227.89161
[15]	validation_0-mae:6017.93592
[16]	validation_0-mae:5781.97646
[17]	validation_0-mae:5600.49806
[18]	validation_0-mae:5399.71324
[19]	validation_0-mae:5221.25293
[20]	validation_0-mae:5052.65472
[21]	validation_0-mae:4890.48912
[22]	validation_0-mae:4740.76146
[23]	validation_0-mae:4620.99105
[24]	validation_0-mae:4488.29871
[25]	validation_0-mae:4371.96512
[26]	validation_0-mae:4282.29676
[27]	validation_0-mae:4167.85864
[28]	validation_0-mae:4069.21431
[29]	validation_0-mae:3993.58792
[30]	validation_0-mae:3915.01667
[31]	validation_0-mae:3832.77907
[32]	validation_0-mae:3754.15786
[33]	validation_0-mae:3685.01473

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[34]	validation_0-mae:3626.27143
[35]	validation_0-mae:3571.10326
[36]	validation_0-mae:3514.26905
[37]	validation_0-mae:3460.44905
[38]	validation_0-mae:3412.95908
[39]	validation_0-mae:3371.19880
[40]	validation_0-mae:3332.34844
[41]	validation_0-mae:3265.62196
[42]	validation_0-mae:3222.78512
[43]	validation_0-mae:3185.14733
[44]	validation_0-mae:3159.33798
[45]	validation_0-mae:3117.47957
[46]	validation_0-mae:3079.08611
[47]	validation_0-mae:3049.56818
[48]	validation_0-mae:3023.89337
[49]	validation_0-mae:3000.13609
[50]	validation_0-mae:2976.17309
[51]	validation_0-mae:2960.18184
[52]	validation_0-mae:2933.15185
[53]	validation_0-mae:2909.50119
[54]	validation_0-mae:2882.15961
[55]	validation_0-mae:2858.50394
[56]	validation_0-mae:2839.81775
[57]	validation_0-mae:2815.61428
[58]	validation_0-mae:2801.25749
[59]	validation_0-mae:2783.07600
[60]	validation_0-mae:2757.28520
[61]	validation_0-mae:2743.31820
[62]	validation_0-mae:2728.71830
[63]	validation_0-mae:2719.09964
[64]	validation_0-mae:2703.50398
[65]	validation_0-mae:2684.20911
[66]	validation_0-mae:2670.24222
[67]	validation_0-mae:2661.92068
[68]	validation_0-mae:2654.34004
[69]	validation_0-mae:2632.88330
[70]	validation_0-mae:2621.96595
[71]	validation_0-mae:2610.77030
[72]	validation_0-mae:2592.06212
[73]	validation_0-mae:2583.87525
[74]	validation_0-mae:2577.25664
[75]	validation_0-mae:2564.66250
[76]	validation_0-mae:2554.16918
[77]	validation_0-mae:2549.80962
[78]	validation_0-mae:2543.06404
[79]	validation_0-mae:2532.89771
[80]	validation_0-mae:2524.93051
[81]	validation_0-mae:2520.38427
[82]	validation_0-mae:2512.26251
[83]	validation_0-mae:2497.72379
[84]	validation_0-mae:2493.32087
[85]	validation_0-mae:2488.01360
[86]	validation_0-mae:2474.53997
[87]	validation_0-mae:2462.54512
[88]	validation_0-mae:2456.57180
[89]	validation_0-mae:2448.55984
[90]	validation_0-mae:2439.07856
[91]	validation_0-mae:2432.80467
[92]	validation_0-mae:2425.76626
[93]	validation_0-mae:2422.94365
[94]	validation_0-mae:2411.97274
[95]	validation_0-mae:2406.35416
[96]	validation_0-mae:2400.34944
[97]	validation_0-mae:2394.12214
[98]	validation_0-mae:2390.44173
[99]	validation_0-mae:2385.98304
[100]	validation_0-mae:2381.07308
[101]	validation_0-mae:2377.91692
[102]	validation_0-mae:2373.69808
[103]	validation_0-mae:2366.88927
[104]	validation_0-mae:2360.64157
[105]	validation_0-mae:2356.29430
[106]	validation_0-mae:2347.87429
[107]	validation_0-mae:2339.69556
[108]	validation_0-mae:2336.41456
[109]	validation_0-mae:2333.37885
[110]	validation_0-mae:2330.50309
[111]	validation_0-mae:2319.95018
[112]	validation_0-mae:2316.57293
[113]	validation_0-mae:2314.59839
[114]	validation_0-mae:2312.26392
[115]	validation_0-mae:2307.76524
[116]	validation_0-mae:2306.57208
[117]	validation_0-mae:2303.02406
[118]	validation_0-mae:2302.23817
[119]	validation_0-mae:2300.40739
[120]	validation_0-mae:2298.12773
[121]	validation_0-mae:2296.79601
[122]	validation_0-mae:2294.44541
[123]	validation_0-mae:2287.52605
[124]	validation_0-mae:2286.02328
[125]	validation_0-mae:2284.70679
[126]	validation_0-mae:2281.86469
[127]	validation_0-mae:2277.51981
[128]	validation_0-mae:2275.39840
[129]	validation_0-mae:2271.71982
[130]	validation_0-mae:2271.69487
[131]	validation_0-mae:2264.64239
[132]	validation_0-mae:2264.58162
[133]	validation_0-mae:2260.66372
[134]	validation_0-mae:2260.27692
[135]	validation_0-mae:2261.01500
[136]	validation_0-mae:2261.79576
[137]	validation_0-mae:2258.90692
[138]	validation_0-mae:2257.57492
[139]	validation_0-mae:2255.59762
[140]	validation_0-mae:2254.60294
[141]	validation_0-mae:2253.03187
[142]	validation_0-mae:2252.15048
[143]	validation_0-mae:2248.96592
[144]	validation_0-mae:2247.33380
[145]	validation_0-mae:2245.50750
[146]	validation_0-mae:2242.46804
[147]	validation_0-mae:2241.57544
[148]	validation_0-mae:2241.05289
[149]	validation_0-mae:2238.41329
[150]	validation_0-mae:2236.46482
[151]	validation_0-mae:2231.51025
[152]	validation_0-mae:2229.73972
[153]	validation_0-mae:2227.45048
[154]	validation_0-mae:2226.01795
[155]	validation_0-mae:2224.64869
[156]	validation_0-mae:2223.26489
[157]	validation_0-mae:2221.16730
[158]	validation_0-mae:2216.99476
[159]	validation_0-mae:2216.59342
[160]	validation_0-mae:2214.23214
[161]	validation_0-mae:2212.24681
[162]	validation_0-mae:2212.70773
[163]	validation_0-mae:2210.14034
[164]	validation_0-mae:2209.93191
[165]	validation_0-mae:2209.06715
[166]	validation_0-mae:2207.43053
[167]	validation_0-mae:2207.55838
[168]	validation_0-mae:2206.66358
[169]	validation_0-mae:2203.11115
[170]	validation_0-mae:2201.52328
[171]	validation_0-mae:2200.81878
[172]	validation_0-mae:2199.54212
[173]	validation_0-mae:2197.16591
[174]	validation_0-mae:2197.17147
[175]	validation_0-mae:2198.48364
[176]	validation_0-mae:2196.82381
[177]	validation_0-mae:2195.83493
[178]	validation_0-mae:2195.38908
[179]	validation_0-mae:2193.11195
[180]	validation_0-mae:2188.31332
[181]	validation_0-mae:2185.34981
[182]	validation_0-mae:2184.67646
[183]	validation_0-mae:2184.82063
[184]	validation_0-mae:2183.22643
[185]	validation_0-mae:2181.40205
[186]	validation_0-mae:2180.17298
[187]	validation_0-mae:2181.04484
[188]	validation_0-mae:2180.56215
[189]	validation_0-mae:2180.19719
[190]	validation_0-mae:2180.55246
[191]	validation_0-mae:2177.32482
[192]	validation_0-mae:2175.04783
[193]	validation_0-mae:2174.81325
[194]	validation_0-mae:2173.17424
[195]	validation_0-mae:2172.54499
[196]	validation_0-mae:2170.40330
[197]	validation_0-mae:2169.75690
[198]	validation_0-mae:2167.93586
[199]	validation_0-mae:2166.56057
[200]	validation_0-mae:2165.65770
[201]	validation_0-mae:2163.51813
[202]	validation_0-mae:2162.78212
[203]	validation_0-mae:2160.71711
[204]	validation_0-mae:2159.53148
[205]	validation_0-mae:2156.21823
[206]	validation_0-mae:2156.81197
[207]	validation_0-mae:2154.29751
[208]	validation_0-mae:2152.66436
[209]	validation_0-mae:2151.56136
[210]	validation_0-mae:2152.35834
[211]	validation_0-mae:2153.42371
[212]	validation_0-mae:2152.83065
[213]	validation_0-mae:2152.59226
[214]	validation_0-mae:2151.35444
[215]	validation_0-mae:2148.60529
[216]	validation_0-mae:2149.13096
[217]	validation_0-mae:2149.14155
[218]	validation_0-mae:2147.83386
[219]	validation_0-mae:2146.30957
[220]	validation_0-mae:2146.04435
[221]	validation_0-mae:2144.39939
[222]	validation_0-mae:2144.19165
[223]	validation_0-mae:2143.10978
[224]	validation_0-mae:2142.41820
[225]	validation_0-mae:2141.85384
[226]	validation_0-mae:2142.71288
[227]	validation_0-mae:2143.56863
[228]	validation_0-mae:2143.64937
[229]	validation_0-mae:2143.24832
[230]	validation_0-mae:2142.45840
[231]	validation_0-mae:2142.04033
[232]	validation_0-mae:2142.48545
[233]	validation_0-mae:2141.35974
[234]	validation_0-mae:2141.94692
[235]	validation_0-mae:2141.05393
[236]	validation_0-mae:2140.64685
[237]	validation_0-mae:2140.74655
[238]	validation_0-mae:2139.70781
[239]	validation_0-mae:2138.35166
[240]	validation_0-mae:2137.81221
[241]	validation_0-mae:2136.83219
[242]	validation_0-mae:2137.13109
[243]	validation_0-mae:2136.97812
[244]	validation_0-mae:2135.88716
[245]	validation_0-mae:2134.76821
[246]	validation_0-mae:2135.18266
[247]	validation_0-mae:2134.91930
[248]	validation_0-mae:2135.32197
[249]	validation_0-mae:2134.57827
[250]	validation_0-mae:2133.80855
[251]	validation_0-mae:2133.16211
[252]	validation_0-mae:2133.68625
[253]	validation_0-mae:2134.11758
[254]	validation_0-mae:2133.55547
[255]	validation_0-mae:2133.77188
[256]	validation_0-mae:2134.76776
[257]	validation_0-mae:2134.25226
[258]	validation_0-mae:2132.79325
[259]	validation_0-mae:2131.68714
[260]	validation_0-mae:2132.09726
[261]	validation_0-mae:2131.32925
[262]	validation_0-mae:2132.46191
[263]	validation_0-mae:2132.97860
[264]	validation_0-mae:2134.20576
[265]	validation_0-mae:2133.65059
[266]	validation_0-mae:2133.39748
[267]	validation_0-mae:2134.12990
[268]	validation_0-mae:2132.71363
[269]	validation_0-mae:2131.66899
[270]	validation_0-mae:2131.24782
[271]	validation_0-mae:2129.98992
[272]	validation_0-mae:2129.89884
[273]	validation_0-mae:2129.65824
[274]	validation_0-mae:2129.89478
[275]	validation_0-mae:2128.67408
[276]	validation_0-mae:2127.67494
[277]	validation_0-mae:2126.72764
[278]	validation_0-mae:2126.85240
[279]	validation_0-mae:2126.78099
[280]	validation_0-mae:2126.01292
[281]	validation_0-mae:2125.35373
[282]	validation_0-mae:2123.00173
[283]	validation_0-mae:2122.71038
[284]	validation_0-mae:2122.81483
[285]	validation_0-mae:2121.26569
[286]	validation_0-mae:2121.33199
[287]	validation_0-mae:2121.44483
[288]	validation_0-mae:2121.10186
[289]	validation_0-mae:2120.90997
[290]	validation_0-mae:2120.50518
[291]	validation_0-mae:2118.23978
[292]	validation_0-mae:2118.26240
[293]	validation_0-mae:2118.52543
[294]	validation_0-mae:2118.32008
[295]	validation_0-mae:2118.16862
[296]	validation_0-mae:2117.76646
[297]	validation_0-mae:2117.95227
[298]	validation_0-mae:2118.43058
[299]	validation_0-mae:2117.64064
[300]	validation_0-mae:2117.51628
[301]	validation_0-mae:2116.87926
[302]	validation_0-mae:2116.40227
[303]	validation_0-mae:2116.54662
[304]	validation_0-mae:2115.92994
[305]	validation_0-mae:2115.87832
[306]	validation_0-mae:2116.65483
[307]	validation_0-mae:2116.18541
[308]	validation_0-mae:2115.10561
[309]	validation_0-mae:2115.17250
[310]	validation_0-mae:2115.05214
[311]	validation_0-mae:2115.54632
[312]	validation_0-mae:2115.66433
[313]	validation_0-mae:2115.22879
[314]	validation_0-mae:2115.55657
[315]	validation_0-mae:2116.52043
[316]	validation_0-mae:2116.17251
[317]	validation_0-mae:2115.81988
[318]	validation_0-mae:2115.31542
[319]	validation_0-mae:2114.95375
[320]	validation_0-mae:2114.43315
[321]	validation_0-mae:2114.17928
[322]	validation_0-mae:2113.39363
[323]	validation_0-mae:2113.58468
[324]	validation_0-mae:2113.04284
[325]	validation_0-mae:2113.48048
[326]	validation_0-mae:2113.58268
[327]	validation_0-mae:2113.65239
[328]	validation_0-mae:2112.51068
[329]	validation_0-mae:2111.90617
[330]	validation_0-mae:2111.89369
[331]	validation_0-mae:2111.16059
[332]	validation_0-mae:2110.37936
[333]	validation_0-mae:2110.13746
[334]	validation_0-mae:2109.21007
[335]	validation_0-mae:2108.79011
[336]	validation_0-mae:2107.58673
[337]	validation_0-mae:2107.29861
[338]	validation_0-mae:2106.17522
[339]	validation_0-mae:2106.35636
[340]	validation_0-mae:2106.74317
[341]	validation_0-mae:2106.42137
[342]	validation_0-mae:2105.96378
[343]	validation_0-mae:2105.23696
[344]	validation_0-mae:2104.56960
[345]	validation_0-mae:2104.32741
[346]	validation_0-mae:2103.40745
[347]	validation_0-mae:2103.31714
[348]	validation_0-mae:2103.26173
[349]	validation_0-mae:2102.89915
[350]	validation_0-mae:2102.47407
[351]	validation_0-mae:2103.08940
[352]	validation_0-mae:2102.80341
[353]	validation_0-mae:2103.37646
[354]	validation_0-mae:2102.86208
[355]	validation_0-mae:2101.01344
[356]	validation_0-mae:2101.32195
[357]	validation_0-mae:2100.31922
[358]	validation_0-mae:2099.39970
[359]	validation_0-mae:2099.39292
[360]	validation_0-mae:2098.46858
[361]	validation_0-mae:2098.43640
[362]	validation_0-mae:2098.62576
[363]	validation_0-mae:2096.89849
[364]	validation_0-mae:2096.70487
[365]	validation_0-mae:2096.43322
[366]	validation_0-mae:2096.14427
[367]	validation_0-mae:2095.92906
[368]	validation_0-mae:2095.93802
[369]	validation_0-mae:2094.80592
[370]	validation_0-mae:2094.71474
[371]	validation_0-mae:2094.97644
[372]	validation_0-mae:2094.01716
[373]	validation_0-mae:2094.07628
[374]	validation_0-mae:2093.44258
[375]	validation_0-mae:2092.74472
[376]	validation_0-mae:2091.98722
[377]	validation_0-mae:2091.86828
[378]	validation_0-mae:2092.34377
[379]	validation_0-mae:2092.43371
[380]	validation_0-mae:2092.47438
[381]	validation_0-mae:2092.43184
[382]	validation_0-mae:2091.99769
[383]	validation_0-mae:2091.95013
[384]	validation_0-mae:2092.20949
[385]	validation_0-mae:2091.82462
[386]	validation_0-mae:2092.40844
[387]	validation_0-mae:2092.02567
[388]	validation_0-mae:2091.40913
[389]	validation_0-mae:2091.27861
[390]	validation_0-mae:2091.53988
[391]	validation_0-mae:2091.38115
[392]	validation_0-mae:2091.40538
[393]	validation_0-mae:2091.76858
[394]	validation_0-mae:2092.35416
[395]	validation_0-mae:2092.06191
[396]	validation_0-mae:2092.30132
[397]	validation_0-mae:2092.23403
[398]	validation_0-mae:2091.75647
[399]	validation_0-mae:2091.82535
[400]	validation_0-mae:2091.89746
[401]	validation_0-mae:2091.00001
[402]	validation_0-mae:2091.27520
[403]	validation_0-mae:2090.33094
[404]	validation_0-mae:2090.03347
[405]	validation_0-mae:2090.54600
[406]	validation_0-mae:2090.64400
[407]	validation_0-mae:2090.66716
[408]	validation_0-mae:2090.48950
[409]	validation_0-mae:2089.34913
[410]	validation_0-mae:2088.82039
[411]	validation_0-mae:2089.12405
[412]	validation_0-mae:2088.46128
[413]	validation_0-mae:2088.79679
[414]	validation_0-mae:2087.55921
[415]	validation_0-mae:2086.81611
[416]	validation_0-mae:2087.01032
[417]	validation_0-mae:2085.98886
[418]	validation_0-mae:2086.22121
[419]	validation_0-mae:2085.16476
[420]	validation_0-mae:2084.72653
[421]	validation_0-mae:2084.67421
[422]	validation_0-mae:2084.20852
[423]	validation_0-mae:2083.83978
[424]	validation_0-mae:2083.03970
[425]	validation_0-mae:2083.44515
[426]	validation_0-mae:2083.94366
[427]	validation_0-mae:2084.10302
[428]	validation_0-mae:2084.97038
[429]	validation_0-mae:2085.30278
[430]	validation_0-mae:2084.98525
[431]	validation_0-mae:2085.11866
[432]	validation_0-mae:2085.28209
[433]	validation_0-mae:2085.23443
[434]	validation_0-mae:2085.22577
[435]	validation_0-mae:2085.42844
[436]	validation_0-mae:2085.62022
[437]	validation_0-mae:2085.19369
[438]	validation_0-mae:2085.40002
[439]	validation_0-mae:2084.67673
[440]	validation_0-mae:2084.28218
[441]	validation_0-mae:2084.61798
[442]	validation_0-mae:2083.90936
[443]	validation_0-mae:2083.44453
[444]	validation_0-mae:2083.39238
[445]	validation_0-mae:2083.59191
[446]	validation_0-mae:2083.60417
[447]	validation_0-mae:2083.16567
[448]	validation_0-mae:2083.16669
[449]	validation_0-mae:2082.60608
[450]	validation_0-mae:2082.35250
[451]	validation_0-mae:2082.44777
[452]	validation_0-mae:2082.49245
[453]	validation_0-mae:2082.21448
[454]	validation_0-mae:2082.44396
[455]	validation_0-mae:2082.61959
[456]	validation_0-mae:2082.22105
[457]	validation_0-mae:2081.92202
[458]	validation_0-mae:2081.96097
[459]	validation_0-mae:2081.99836
[460]	validation_0-mae:2081.74844
[461]	validation_0-mae:2082.21691
[462]	validation_0-mae:2081.92500
[463]	validation_0-mae:2082.02250
[464]	validation_0-mae:2081.58940
[465]	validation_0-mae:2081.70841
[466]	validation_0-mae:2082.06847
[467]	validation_0-mae:2082.57777
[468]	validation_0-mae:2082.09105
[469]	validation_0-mae:2082.22087
[470]	validation_0-mae:2081.93092
[471]	validation_0-mae:2080.78153
[472]	validation_0-mae:2080.63882
[473]	validation_0-mae:2080.86084
[474]	validation_0-mae:2080.65348
[475]	validation_0-mae:2081.40581
[476]	validation_0-mae:2081.71895
[477]	validation_0-mae:2082.13307
[478]	validation_0-mae:2082.38948
[479]	validation_0-mae:2082.76521
[480]	validation_0-mae:2083.11986
[481]	validation_0-mae:2083.07221
[482]	validation_0-mae:2081.88614
[483]	validation_0-mae:2081.48118
[484]	validation_0-mae:2081.18263
[485]	validation_0-mae:2080.75152
[486]	validation_0-mae:2080.72848
[487]	validation_0-mae:2081.11945
[488]	validation_0-mae:2080.86553
[489]	validation_0-mae:2081.38292
[490]	validation_0-mae:2081.69888
[491]	validation_0-mae:2081.39063
[492]	validation_0-mae:2081.61371
[493]	validation_0-mae:2080.88814
[494]	validation_0-mae:2081.04587
[495]	validation_0-mae:2080.98639
[496]	validation_0-mae:2080.92711
[497]	validation_0-mae:2080.82698
[498]	validation_0-mae:2080.83592
[499]	validation_0-mae:2080.65158
[500]	validation_0-mae:2080.34275
[501]	validation_0-mae:2080.32400
[502]	validation_0-mae:2080.64563
[503]	validation_0-mae:2080.92858
[504]	validation_0-mae:2080.68475
[505]	validation_0-mae:2080.77264
[506]	validation_0-mae:2080.79705
[507]	validation_0-mae:2080.75748
[508]	validation_0-mae:2080.49663
[509]	validation_0-mae:2080.43452
[510]	validation_0-mae:2080.73190
[511]	validation_0-mae:2080.65544
[512]	validation_0-mae:2080.73933
[513]	validation_0-mae:2081.12956
[514]	validation_0-mae:2081.28901
[515]	validation_0-mae:2080.81543
[516]	validation_0-mae:2080.41574
[517]	validation_0-mae:2080.27662
[518]	validation_0-mae:2079.98711
[519]	validation_0-mae:2080.45662
[520]	validation_0-mae:2080.37339
[521]	validation_0-mae:2080.75604
[522]	validation_0-mae:2080.41395
[523]	validation_0-mae:2080.55889
[524]	validation_0-mae:2080.40025
[525]	validation_0-mae:2081.03489
[526]	validation_0-mae:2080.51912
[527]	validation_0-mae:2079.07192
[528]	validation_0-mae:2078.03607
[529]	validation_0-mae:2077.08014
[530]	validation_0-mae:2077.19984
[531]	validation_0-mae:2077.40933
[532]	validation_0-mae:2077.51874
[533]	validation_0-mae:2077.66588
[534]	validation_0-mae:2077.50675
[535]	validation_0-mae:2077.55622
[536]	validation_0-mae:2077.60073
[537]	validation_0-mae:2077.83555
[538]	validation_0-mae:2077.57877
[539]	validation_0-mae:2077.14175
[540]	validation_0-mae:2077.27971
[541]	validation_0-mae:2076.57218
[542]	validation_0-mae:2076.88059
[543]	validation_0-mae:2076.85514
[544]	validation_0-mae:2077.33009
[545]	validation_0-mae:2077.76434
[546]	validation_0-mae:2077.43193
[547]	validation_0-mae:2077.41212
[548]	validation_0-mae:2077.70324
[549]	validation_0-mae:2077.64210
[550]	validation_0-mae:2077.76190
[551]	validation_0-mae:2077.86732
[552]	validation_0-mae:2078.02776
[553]	validation_0-mae:2078.06969
[554]	validation_0-mae:2077.90143
[555]	validation_0-mae:2078.06949
[556]	validation_0-mae:2078.48689
[557]	validation_0-mae:2078.08171
[558]	validation_0-mae:2078.09354
[559]	validation_0-mae:2077.67303
[560]	validation_0-mae:2077.58349
[561]	validation_0-mae:2077.68856
[562]	validation_0-mae:2077.60622
[563]	validation_0-mae:2077.07853
[564]	validation_0-mae:2077.24548
[565]	validation_0-mae:2077.60593
[566]	validation_0-mae:2077.54825
[567]	validation_0-mae:2078.09169
[568]	validation_0-mae:2078.30976
[569]	validation_0-mae:2078.23193
[570]	validation_0-mae:2077.74496
[571]	validation_0-mae:2077.36748
[572]	validation_0-mae:2077.45994
[573]	validation_0-mae:2077.69093
[574]	validation_0-mae:2077.72532
[575]	validation_0-mae:2077.74158
[576]	validation_0-mae:2076.47053
[577]	validation_0-mae:2076.25217
[578]	validation_0-mae:2076.37062
[579]	validation_0-mae:2076.24043
[580]	validation_0-mae:2076.39760
[581]	validation_0-mae:2076.52856
[582]	validation_0-mae:2076.63982
[583]	validation_0-mae:2076.79445
[584]	validation_0-mae:2076.97881
[585]	validation_0-mae:2076.96154
[586]	validation_0-mae:2077.16104
[587]	validation_0-mae:2077.73830
[588]	validation_0-mae:2077.51068
[589]	validation_0-mae:2076.11487
[590]	validation_0-mae:2076.63227
[591]	validation_0-mae:2076.24692
[592]	validation_0-mae:2076.14149
[593]	validation_0-mae:2075.28172
[594]	validation_0-mae:2075.26080
[595]	validation_0-mae:2074.78432
[596]	validation_0-mae:2074.63510
[597]	validation_0-mae:2074.25826
[598]	validation_0-mae:2074.27516
[599]	validation_0-mae:2073.86096
[600]	validation_0-mae:2073.55222
[601]	validation_0-mae:2073.36197
[602]	validation_0-mae:2073.33482
[603]	validation_0-mae:2073.70403
[604]	validation_0-mae:2073.50957
[605]	validation_0-mae:2073.18217
[606]	validation_0-mae:2073.17038
[607]	validation_0-mae:2072.52125
[608]	validation_0-mae:2072.69673
[609]	validation_0-mae:2072.81768
[610]	validation_0-mae:2072.66715
[611]	validation_0-mae:2072.79420
[612]	validation_0-mae:2072.98880
[613]	validation_0-mae:2072.85556
[614]	validation_0-mae:2072.97502
[615]	validation_0-mae:2072.56432
[616]	validation_0-mae:2071.90686
[617]	validation_0-mae:2071.67895
[618]	validation_0-mae:2071.77211
[619]	validation_0-mae:2072.03982
[620]	validation_0-mae:2072.17603
[621]	validation_0-mae:2072.04772
[622]	validation_0-mae:2071.59606
[623]	validation_0-mae:2071.65710

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[33]	validation_0-mae:3515.92839
[34]	validation_0-mae:3454.89120
[35]	validation_0-mae:3373.86257
[36]	validation_0-mae:3316.41126
[37]	validation_0-mae:3261.47635
[38]	validation_0-mae:3221.56190
[39]	validation_0-mae:3177.46750
[40]	validation_0-mae:3142.97839
[41]	validation_0-mae:3101.36039
[42]	validation_0-mae:3070.66675
[43]	validation_0-mae:3030.86520
[44]	validation_0-mae:2993.27737
[45]	validation_0-mae:2963.06319
[46]	validation_0-mae:2920.46080
[47]	validation_0-mae:2897.12156
[48]	validation_0-mae:2862.83941
[49]	validation_0-mae:2838.54545
[50]	validation_0-mae:2807.20798
[51]	validation_0-mae:2784.07658
[52]	validation_0-mae:2761.92173
[53]	validation_0-mae:2743.86282
[54]	validation_0-mae:2724.44575
[55]	validation_0-mae:2701.52832
[56]	validation_0-mae:2685.28271
[57]	validation_0-mae:2668.42734
[58]	validation_0-mae:2655.06444
[59]	validation_0-mae:2636.92735
[60]	validation_0-mae:2620.78341
[61]	validation_0-mae:2609.87592
[62]	validation_0-mae:2589.40385
[63]	validation_0-mae:2568.20026
[64]	validation_0-mae:2558.15732
[65]	validation_0-mae:2541.34637
[66]	validation_0-mae:2520.88464
[67]	validation_0-mae:2511.84599
[68]	validation_0-mae:2504.72945
[69]	validation_0-mae:2493.94397
[70]	validation_0-mae:2474.77216
[71]	validation_0-mae:2464.40956
[72]	validation_0-mae:2454.44113
[73]	validation_0-mae:2441.85711
[74]	validation_0-mae:2434.01941
[75]	validation_0-mae:2426.48147
[76]	validation_0-mae:2413.69553
[77]	validation_0-mae:2408.53155
[78]	validation_0-mae:2405.23065
[79]	validation_0-mae:2400.05408
[80]	validation_0-mae:2396.04145
[81]	validation_0-mae:2387.33235
[82]	validation_0-mae:2380.53978
[83]	validation_0-mae:2371.48957
[84]	validation_0-mae:2360.46393
[85]	validation_0-mae:2351.57972
[86]	validation_0-mae:2345.17909
[87]	validation_0-mae:2338.50343
[88]	validation_0-mae:2332.96417
[89]	validation_0-mae:2322.74343
[90]	validation_0-mae:2319.82770
[91]	validation_0-mae:2317.70856
[92]	validation_0-mae:2309.77628
[93]	validation_0-mae:2306.12409
[94]	validation_0-mae:2304.83665
[95]	validation_0-mae:2301.24153
[96]	validation_0-mae:2299.55985
[97]	validation_0-mae:2293.19440
[98]	validation_0-mae:2290.25763
[99]	validation_0-mae:2283.11136
[100]	validation_0-mae:2279.06279
[101]	validation_0-mae:2273.75863
[102]	validation_0-mae:2271.41454
[103]	validation_0-mae:2270.01117
[104]	validation_0-mae:2266.44265
[105]	validation_0-mae:2265.95380
[106]	validation_0-mae:2259.81606
[107]	validation_0-mae:2254.98000
[108]	validation_0-mae:2249.23272
[109]	validation_0-mae:2246.00843
[110]	validation_0-mae:2245.69414
[111]	validation_0-mae:2241.40705
[112]	validation_0-mae:2239.47633
[113]	validation_0-mae:2233.43620
[114]	validation_0-mae:2229.89506
[115]	validation_0-mae:2230.46406
[116]	validation_0-mae:2228.14165
[117]	validation_0-mae:2226.04371
[118]	validation_0-mae:2225.51960
[119]	validation_0-mae:2225.85060
[120]	validation_0-mae:2221.86060
[121]	validation_0-mae:2222.71894
[122]	validation_0-mae:2218.40359
[123]	validation_0-mae:2215.80803
[124]	validation_0-mae:2215.31859
[125]	validation_0-mae:2213.52224
[126]	validation_0-mae:2212.00939
[127]	validation_0-mae:2205.46864
[128]	validation_0-mae:2202.86665
[129]	validation_0-mae:2203.22045
[130]	validation_0-mae:2200.09103
[131]	validation_0-mae:2199.86187
[132]	validation_0-mae:2200.37760
[133]	validation_0-mae:2200.66527
[134]	validation_0-mae:2195.83636
[135]	validation_0-mae:2193.15883
[136]	validation_0-mae:2192.26608
[137]	validation_0-mae:2190.36884
[138]	validation_0-mae:2187.55210
[139]	validation_0-mae:2187.58492
[140]	validation_0-mae:2186.21384
[141]	validation_0-mae:2183.73717
[142]	validation_0-mae:2182.48211
[143]	validation_0-mae:2180.54592
[144]	validation_0-mae:2178.96071
[145]	validation_0-mae:2177.40840
[146]	validation_0-mae:2175.26922
[147]	validation_0-mae:2174.03909
[148]	validation_0-mae:2173.60447
[149]	validation_0-mae:2172.69729
[150]	validation_0-mae:2172.67018
[151]	validation_0-mae:2172.34312
[152]	validation_0-mae:2172.25905
[153]	validation_0-mae:2171.80468
[154]	validation_0-mae:2169.20206
[155]	validation_0-mae:2168.63813
[156]	validation_0-mae:2166.03221
[157]	validation_0-mae:2165.51860
[158]	validation_0-mae:2163.95237
[159]	validation_0-mae:2161.30775
[160]	validation_0-mae:2161.19367
[161]	validation_0-mae:2159.44693
[162]	validation_0-mae:2159.43679
[163]	validation_0-mae:2156.15352
[164]	validation_0-mae:2155.89146
[165]	validation_0-mae:2156.41527
[166]	validation_0-mae:2154.63777
[167]	validation_0-mae:2154.02886
[168]	validation_0-mae:2153.89230
[169]	validation_0-mae:2153.96758
[170]	validation_0-mae:2152.75655
[171]	validation_0-mae:2152.48680
[172]	validation_0-mae:2152.23940
[173]	validation_0-mae:2150.98724
[174]	validation_0-mae:2151.86391
[175]	validation_0-mae:2152.02853
[176]	validation_0-mae:2151.74112
[177]	validation_0-mae:2151.98168
[178]	validation_0-mae:2151.29779
[179]	validation_0-mae:2150.55633
[180]	validation_0-mae:2151.93792
[181]	validation_0-mae:2151.61021
[182]	validation_0-mae:2151.20443
[183]	validation_0-mae:2148.51763
[184]	validation_0-mae:2148.00799
[185]	validation_0-mae:2147.47048
[186]	validation_0-mae:2147.31683
[187]	validation_0-mae:2145.17103
[188]	validation_0-mae:2144.06079
[189]	validation_0-mae:2143.60548
[190]	validation_0-mae:2142.58460
[191]	validation_0-mae:2140.00192
[192]	validation_0-mae:2140.20962
[193]	validation_0-mae:2138.78395
[194]	validation_0-mae:2139.43449
[195]	validation_0-mae:2139.72706
[196]	validation_0-mae:2140.02098
[197]	validation_0-mae:2139.33600
[198]	validation_0-mae:2139.61413
[199]	validation_0-mae:2139.81830
[200]	validation_0-mae:2138.67269
[201]	validation_0-mae:2138.75142
[202]	validation_0-mae:2136.32957
[203]	validation_0-mae:2135.82960
[204]	validation_0-mae:2135.90337
[205]	validation_0-mae:2135.17870
[206]	validation_0-mae:2135.82677
[207]	validation_0-mae:2133.24425
[208]	validation_0-mae:2133.61709
[209]	validation_0-mae:2132.53545
[210]	validation_0-mae:2131.98599
[211]	validation_0-mae:2129.96683
[212]	validation_0-mae:2129.61014
[213]	validation_0-mae:2129.04777
[214]	validation_0-mae:2128.77756
[215]	validation_0-mae:2127.68397
[216]	validation_0-mae:2126.58622
[217]	validation_0-mae:2126.83461
[218]	validation_0-mae:2126.06495
[219]	validation_0-mae:2125.24650
[220]	validation_0-mae:2125.85077
[221]	validation_0-mae:2125.57725
[222]	validation_0-mae:2122.70910
[223]	validation_0-mae:2122.37407
[224]	validation_0-mae:2122.85214
[225]	validation_0-mae:2120.71193
[226]	validation_0-mae:2120.24447
[227]	validation_0-mae:2118.71007
[228]	validation_0-mae:2118.71162
[229]	validation_0-mae:2118.53070
[230]	validation_0-mae:2118.79902
[231]	validation_0-mae:2117.94991
[232]	validation_0-mae:2117.87995
[233]	validation_0-mae:2118.31075
[234]	validation_0-mae:2117.40456
[235]	validation_0-mae:2117.68162
[236]	validation_0-mae:2118.22865
[237]	validation_0-mae:2118.28059
[238]	validation_0-mae:2117.53128
[239]	validation_0-mae:2115.54128
[240]	validation_0-mae:2115.21255
[241]	validation_0-mae:2115.04355
[242]	validation_0-mae:2114.47198
[243]	validation_0-mae:2114.39150
[244]	validation_0-mae:2114.31672
[245]	validation_0-mae:2114.12331
[246]	validation_0-mae:2113.66730
[247]	validation_0-mae:2113.55433
[248]	validation_0-mae:2114.03296
[249]	validation_0-mae:2114.27541
[250]	validation_0-mae:2114.35869
[251]	validation_0-mae:2113.68745
[252]	validation_0-mae:2113.74449
[253]	validation_0-mae:2113.87810
[254]	validation_0-mae:2112.69005
[255]	validation_0-mae:2112.55451
[256]	validation_0-mae:2112.00025
[257]	validation_0-mae:2111.59012
[258]	validation_0-mae:2111.37218
[259]	validation_0-mae:2111.53859
[260]	validation_0-mae:2111.70252
[261]	validation_0-mae:2111.69102
[262]	validation_0-mae:2110.49190
[263]	validation_0-mae:2109.67327
[264]	validation_0-mae:2109.27074
[265]	validation_0-mae:2108.73298
[266]	validation_0-mae:2109.07619
[267]	validation_0-mae:2109.06213
[268]	validation_0-mae:2108.33098
[269]	validation_0-mae:2107.71777
[270]	validation_0-mae:2107.85876
[271]	validation_0-mae:2107.73229
[272]	validation_0-mae:2106.93600
[273]	validation_0-mae:2107.38554
[274]	validation_0-mae:2106.35924
[275]	validation_0-mae:2106.95003
[276]	validation_0-mae:2106.53491
[277]	validation_0-mae:2106.30872
[278]	validation_0-mae:2105.64545
[279]	validation_0-mae:2105.97989
[280]	validation_0-mae:2105.43401
[281]	validation_0-mae:2104.98902
[282]	validation_0-mae:2105.08333
[283]	validation_0-mae:2104.85623
[284]	validation_0-mae:2103.95054
[285]	validation_0-mae:2103.32840
[286]	validation_0-mae:2103.95008
[287]	validation_0-mae:2103.72237
[288]	validation_0-mae:2104.13406
[289]	validation_0-mae:2103.76800
[290]	validation_0-mae:2103.20607
[291]	validation_0-mae:2102.66256
[292]	validation_0-mae:2101.29921
[293]	validation_0-mae:2101.02224
[294]	validation_0-mae:2100.08822
[295]	validation_0-mae:2099.21198
[296]	validation_0-mae:2099.50518
[297]	validation_0-mae:2099.02156
[298]	validation_0-mae:2098.60951
[299]	validation_0-mae:2098.35514
[300]	validation_0-mae:2098.40717
[301]	validation_0-mae:2098.52227
[302]	validation_0-mae:2098.45319
[303]	validation_0-mae:2097.17614
[304]	validation_0-mae:2096.51995
[305]	validation_0-mae:2096.56011
[306]	validation_0-mae:2095.50377
[307]	validation_0-mae:2095.95414
[308]	validation_0-mae:2095.98555
[309]	validation_0-mae:2096.02097
[310]	validation_0-mae:2095.98338
[311]	validation_0-mae:2096.30622
[312]	validation_0-mae:2096.05046
[313]	validation_0-mae:2096.00588
[314]	validation_0-mae:2096.82200
[315]	validation_0-mae:2096.50290
[316]	validation_0-mae:2096.43326
[317]	validation_0-mae:2096.54496
[318]	validation_0-mae:2096.82233
[319]	validation_0-mae:2096.75505
[320]	validation_0-mae:2096.01644
[321]	validation_0-mae:2095.87766
[322]	validation_0-mae:2095.91784
[323]	validation_0-mae:2095.96385
[324]	validation_0-mae:2096.45795
[325]	validation_0-mae:2096.23885
[326]	validation_0-mae:2096.53632
[327]	validation_0-mae:2096.53484
[328]	validation_0-mae:2096.21341
[329]	validation_0-mae:2096.19179
[330]	validation_0-mae:2095.47788
[331]	validation_0-mae:2095.62288
[332]	validation_0-mae:2095.22511
[333]	validation_0-mae:2094.76359
[334]	validation_0-mae:2094.31856
[335]	validation_0-mae:2094.90651
[336]	validation_0-mae:2094.71304
[337]	validation_0-mae:2094.46092
[338]	validation_0-mae:2094.32674
[339]	validation_0-mae:2094.61888
[340]	validation_0-mae:2093.63947
[341]	validation_0-mae:2094.00571
[342]	validation_0-mae:2093.24921
[343]	validation_0-mae:2093.40024
[344]	validation_0-mae:2092.99581
[345]	validation_0-mae:2092.96342
[346]	validation_0-mae:2092.96269
[347]	validation_0-mae:2092.52740
[348]	validation_0-mae:2092.52729
[349]	validation_0-mae:2092.61794
[350]	validation_0-mae:2092.21128
[351]	validation_0-mae:2091.74176
[352]	validation_0-mae:2091.23590
[353]	validation_0-mae:2091.02526
[354]	validation_0-mae:2090.97740
[355]	validation_0-mae:2091.08525
[356]	validation_0-mae:2091.28031
[357]	validation_0-mae:2091.74841
[358]	validation_0-mae:2091.58859
[359]	validation_0-mae:2091.83065
[360]	validation_0-mae:2091.64827
[361]	validation_0-mae:2092.72366
[362]	validation_0-mae:2092.36540
[363]	validation_0-mae:2091.87949
[364]	validation_0-mae:2091.14603
[365]	validation_0-mae:2090.76935
[366]	validation_0-mae:2090.74898
[367]	validation_0-mae:2090.60476
[368]	validation_0-mae:2090.50559
[369]	validation_0-mae:2090.17965
[370]	validation_0-mae:2090.30654
[371]	validation_0-mae:2089.87999
[372]	validation_0-mae:2089.54882
[373]	validation_0-mae:2088.93636
[374]	validation_0-mae:2089.23075
[375]	validation_0-mae:2089.41785
[376]	validation_0-mae:2089.30740
[377]	validation_0-mae:2088.93834
[378]	validation_0-mae:2088.32965
[379]	validation_0-mae:2088.21437
[380]	validation_0-mae:2087.86633
[381]	validation_0-mae:2087.69879
[382]	validation_0-mae:2087.41318
[383]	validation_0-mae:2086.92066
[384]	validation_0-mae:2087.19722
[385]	validation_0-mae:2085.64968
[386]	validation_0-mae:2085.35796
[387]	validation_0-mae:2085.06988
[388]	validation_0-mae:2085.44173
[389]	validation_0-mae:2085.01447
[390]	validation_0-mae:2085.21044
[391]	validation_0-mae:2085.26841
[392]	validation_0-mae:2085.20251
[393]	validation_0-mae:2085.04521
[394]	validation_0-mae:2084.81710
[395]	validation_0-mae:2084.80011
[396]	validation_0-mae:2085.22620
[397]	validation_0-mae:2084.81083
[398]	validation_0-mae:2084.57552
[399]	validation_0-mae:2084.73347
[400]	validation_0-mae:2084.49792
[401]	validation_0-mae:2084.81349
[402]	validation_0-mae:2084.44468
[403]	validation_0-mae:2084.41966
[404]	validation_0-mae:2084.36386
[405]	validation_0-mae:2084.47036
[406]	validation_0-mae:2084.24992
[407]	validation_0-mae:2084.22494
[408]	validation_0-mae:2083.43199
[409]	validation_0-mae:2083.19364
[410]	validation_0-mae:2083.26659
[411]	validation_0-mae:2083.02608
[412]	validation_0-mae:2082.60697
[413]	validation_0-mae:2082.50972
[414]	validation_0-mae:2082.08924
[415]	validation_0-mae:2082.27649
[416]	validation_0-mae:2082.71959
[417]	validation_0-mae:2082.87164
[418]	validation_0-mae:2082.51106
[419]	validation_0-mae:2082.77411
[420]	validation_0-mae:2082.73479
[421]	validation_0-mae:2082.67278
[422]	validation_0-mae:2082.83209
[423]	validation_0-mae:2082.70465
[424]	validation_0-mae:2082.84438
[425]	validation_0-mae:2083.10869
[426]	validation_0-mae:2083.31039
[427]	validation_0-mae:2083.75705
[428]	validation_0-mae:2083.84239
[429]	validation_0-mae:2083.93583
[430]	validation_0-mae:2084.11448
[431]	validation_0-mae:2084.05885
[432]	validation_0-mae:2083.86388
[433]	validation_0-mae:2083.85130
[434]	validation_0-mae:2083.69922
[435]	validation_0-mae:2084.02065
[436]	validation_0-mae:2084.27718
[437]	validation_0-mae:2084.05542
[438]	validation_0-mae:2084.09497
[439]	validation_0-mae:2084.14356
[440]	validation_0-mae:2083.96757
[441]	validation_0-mae:2083.83889
[442]	validation_0-mae:2083.50436
[443]	validation_0-mae:2082.97656
[444]	validation_0-mae:2082.51266
[445]	validation_0-mae:2082.22087
[446]	validation_0-mae:2082.04234
[447]	validation_0-mae:2082.19312
[448]	validation_0-mae:2082.65182
[449]	validation_0-mae:2082.52105
[450]	validation_0-mae:2082.56360
[451]	validation_0-mae:2082.81231
[452]	validation_0-mae:2082.91878
[453]	validation_0-mae:2083.39873
[454]	validation_0-mae:2083.01990
[455]	validation_0-mae:2083.21108
[456]	validation_0-mae:2083.24858
[457]	validation_0-mae:2082.88244
[458]	validation_0-mae:2082.85805
[459]	validation_0-mae:2082.81003
[460]	validation_0-mae:2082.32071
[461]	validation_0-mae:2082.20516
[462]	validation_0-mae:2082.27733
[463]	validation_0-mae:2082.42746
[464]	validation_0-mae:2082.64379
[465]	validation_0-mae:2082.92391
[466]	validation_0-mae:2083.23016
[467]	validation_0-mae:2083.07733
[468]	validation_0-mae:2082.59130
[469]	validation_0-mae:2082.44583
[470]	validation_0-mae:2082.71133
[471]	validation_0-mae:2082.40080
[472]	validation_0-mae:2082.05104
[473]	validation_0-mae:2083.00008
[474]	validation_0-mae:2083.17179
[475]	validation_0-mae:2082.76512
[476]	validation_0-mae:2082.82483
[477]	validation_0-mae:2082.60127
[478]	validation_0-mae:2082.93384
[479]	validation_0-mae:2083.18511
[480]	validation_0-mae:2083.32592
[481]	validation_0-mae:2083.17693
[482]	validation_0-mae:2083.01852
[483]	validation_0-mae:2083.06163
[484]	validation_0-mae:2082.90751
[485]	validation_0-mae:2082.85707
[486]	validation_0-mae:2083.20257
[487]	validation_0-mae:2083.54000
[488]	validation_0-mae:2083.80515
[489]	validation_0-mae:2083.96200
[490]	validation_0-mae:2083.89639
[491]	validation_0-mae:2084.06325
[492]	validation_0-mae:2083.80170
[493]	validation_0-mae:2084.33684
[494]	validation_0-mae:2084.13047
[495]	validation_0-mae:2084.47945
[496]	validation_0-mae:2084.04052
[497]	validation_0-mae:2083.87705
[498]	validation_0-mae:2083.98484
[499]	validation_0-mae:2082.87466
[500]	validation_0-mae:2083.07591
[501]	validation_0-mae:2083.12621
[502]	validation_0-mae:2083.40323
[503]	validation_0-mae:2083.34223
[504]	validation_0-mae:2083.39384
[505]	validation_0-mae:2083.62544
[506]	validation_0-mae:2083.32828
[507]	validation_0-mae:2083.38401
[508]	validation_0-mae:2083.45910
[509]	validation_0-mae:2083.35203
[510]	validation_0-mae:2083.46552
[511]	validation_0-mae:2083.31923
[512]	validation_0-mae:2083.48174
[513]	validation_0-mae:2083.64369
[514]	validation_0-mae:2083.84499
[515]	validation_0-mae:2083.89450
[516]	validation_0-mae:2084.02320
[517]	validation_0-mae:2084.06926
[518]	validation_0-mae:2083.92827
[519]	validation_0-mae:2083.82635
[520]	validation_0-mae:2083.55922
[521]	validation_0-mae:2083.53573
[522]	validation_0-mae:2083.63138
[523]	validation_0-mae:2083.46535
[524]	validation_0-mae:2083.25100
[525]	validation_0-mae:2083.40978
[526]	validation_0-mae:2083.51111
[527]	validation_0-mae:2083.22785
[528]	validation_0-mae:2083.42208
[529]	validation_0-mae:2083.49675
[530]	validation_0-mae:2083.60420
[531]	validation_0-mae:2083.27813
[532]	validation_0-mae:2083.77967
[533]	validation_0-mae:2083.70702
[534]	validation_0-mae:2083.79847
[535]	validation_0-mae:2083.82971
[536]	validation_0-mae:2084.17676
[537]	validation_0-mae:2084.38088
[538]	validation_0-mae:2084.59807
[539]	validation_0-mae:2084.85124
[540]	validation_0-mae:2084.67977
[541]	validation_0-mae:2084.80891
[542]	validation_0-mae:2084.96401
[543]	validation_0-mae:2084.97582
[544]	validation_0-mae:2085.11879
[545]	validation_0-mae:2085.18772
[546]	validation_0-mae:2085.27576
[547]	validation_0-mae:2084.82242
[548]	validation_0-mae:2084.97467
[549]	validation_0-mae:2085.02806
[550]	validation_0-mae:2085.29523
[551]	validation_0-mae:2085.22757
[552]	validation_0-mae:2085.39495
[553]	validation_0-mae:2085.27030
[554]	validation_0-mae:2085.24641
[555]	validation_0-mae:2085.34567
[556]	validation_0-mae:2085.32381
[557]	validation_0-mae:2085.43818
[558]	validation_0-mae:2085.70428
[559]	validation_0-mae:2085.56947
[560]	validation_0-mae:2085.17905
[561]	validation_0-mae:2085.17701
[562]	validation_0-mae:2084.84638
[563]	validation_0-mae:2084.63219
[564]	validation_0-mae:2084.54667
[565]	validation_0-mae:2084.47737
[566]	validation_0-mae:2084.21130
[567]	validation_0-mae:2084.43441
[568]	validation_0-mae:2084.52766
[569]	validation_0-mae:2084.36203
[570]	validation_0-mae:2084.66264
[571]	validation_0-mae:2084.68838
[572]	validation_0-mae:2084.35319
[573]	validation_0-mae:2084.54818
[574]	validation_0-mae:2084.56934
[575]	validation_0-mae:2084.59725
[576]	validation_0-mae:2084.38882
[577]	validation_0-mae:2084.63724
[578]	validation_0-mae:2084.73446
[579]	validation_0-mae:2084.68207
[580]	validation_0-mae:2084.15861
[581]	validation_0-mae:2084.06249
[582]	validation_0-mae:2084.03653
[583]	validation_0-mae:2084.01753
[584]	validation_0-mae:2083.84859
[585]	validation_0-mae:2083.73687
[586]	validation_0-mae:2083.67293
[587]	validation_0-mae:2083.20842
[588]	validation_0-mae:2082.63643
[589]	validation_0-mae:2082.61723
[590]	validation_0-mae:2082.48751
[591]	validation_0-mae:2082.42953
[592]	validation_0-mae:2082.37528
[593]	validation_0-mae:2082.46319
[594]	validation_0-mae:2082.43282
[595]	validation_0-mae:2082.48750
[596]	validation_0-mae:2082.48469
[597]	validation_0-mae:2082.35615
[598]	validation_0-mae:2082.30733
[599]	validation_0-mae:2082.06712
[600]	validation_0-mae:2082.01631
[601]	validation_0-mae:2081.87423
[602]	validation_0-mae:2081.90710
[603]	validation_0-mae:2081.79114
[604]	validation_0-mae:2081.83664
[605]	validation_0-mae:2081.88880
[606]	validation_0-mae:2082.20555
[607]	validation_0-mae:2082.12645
[608]	validation_0-mae:2082.04310
[609]	validation_0-mae:2082.02824
[610]	validation_0-mae:2081.84354
[611]	validation_0-mae:2081.70051
[612]	validation_0-mae:2081.40969
[613]	validation_0-mae:2081.39880
[614]	validation_0-mae:2081.31709
[615]	validation_0-mae:2081.14996
[616]	validation_0-mae:2081.04559
[617]	validation_0-mae:2080.78674
[618]	validation_0-mae:2080.91035
[619]	validation_0-mae:2081.00090
[620]	validation_0-mae:2080.42800
[621]	validation_0-mae:2080.25359
[622]	validation_0-mae:2080.24859

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[41]	validation_0-mae:3288.57762
[42]	validation_0-mae:3250.32567
[43]	validation_0-mae:3217.10745
[44]	validation_0-mae:3183.06999
[45]	validation_0-mae:3149.01469
[46]	validation_0-mae:3113.32578
[47]	validation_0-mae:3085.11215
[48]	validation_0-mae:3041.50074
[49]	validation_0-mae:3017.46846
[50]	validation_0-mae:2992.65548
[51]	validation_0-mae:2968.30406
[52]	validation_0-mae:2942.50078
[53]	validation_0-mae:2907.55512
[54]	validation_0-mae:2889.69256
[55]	validation_0-mae:2870.86122
[56]	validation_0-mae:2852.14547
[57]	validation_0-mae:2829.82041
[58]	validation_0-mae:2809.17125
[59]	validation_0-mae:2794.01636
[60]	validation_0-mae:2763.15854
[61]	validation_0-mae:2744.87452
[62]	validation_0-mae:2732.64259
[63]	validation_0-mae:2721.16571
[64]	validation_0-mae:2711.75751
[65]	validation_0-mae:2690.97104
[66]	validation_0-mae:2680.09280
[67]	validation_0-mae:2672.34962
[68]	validation_0-mae:2665.24788
[69]	validation_0-mae:2656.81843
[0]	validation_0-mae:12457.62964
[1]	validation_0-mae:11730.17542
[2]	validation_0-mae:11092.63424
[3]	validation_0-mae:10490.07297
[4]	validation_0-mae:9968.53848
[5]	validation_0-mae:9487.65348
[6]	validation_0-mae:9059.93507
[7]	validation_0-mae:8662.29137
[8]	validation_0-mae:8320.21467
[9]	validation_0-mae:7974.47934

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[0]	validation_0-mae:12353.41317
[1]	validation_0-mae:11555.29486
[2]	validation_0-mae:10822.77086
[3]	validation_0-mae:10144.36456
[4]	validation_0-mae:9559.22454
[5]	validation_0-mae:9054.52809
[6]	validation_0-mae:8602.53697
[7]	validation_0-mae:8180.50741
[8]	validation_0-mae:7816.50844
[9]	validation_0-mae:7465.13012
[10]	validation_0-mae:7125.73530
[11]	validation_0-mae:6806.59676
[12]	validation_0-mae:6528.22899
[13]	validation_0-mae:6285.41385
[14]	validation_0-mae:6042.80400
[15]	validation_0-mae:5797.10149
[16]	validation_0-mae:5592.93703
[17]	validation_0-mae:5405.26785
[18]	validation_0-mae:5200.80671
[19]	validation_0-mae:5036.36694
[20]	validation_0-mae:4862.66876
[21]	validation_0-mae:4710.58130
[22]	validation_0-mae:4578.94959
[23]	validation_0-mae:4452.11267
[24]	validation_0-mae:4325.38045
[25]	validation_0-mae:4211.75977
[26]	validation_0-mae:4093.90515
[27]	validation_0-mae:3999.97605
[28]	validation_0-mae:3903.58567
[29]	validation_0-mae:3816.89569
[30]	validation_0-mae:3732.58006
[31]	validation_0-mae:3663.98711
[32]	validation_0-mae:3592.95599
[33]	validation_0-mae:3525.71307
[34]	validation_0-mae:3471.52460
[35]	validation_0-mae:3413.44356
[36]	validation_0-mae:3357.47168
[37]	validation_0-mae:3311.08461
[38]	validation_0-mae:3251.70064
[39]	validation_0-mae:3201.89569
[40]	validation_0-mae:3163.94492
[41]	validation_0-mae:3126.67907
[42]	validation_0-mae:3098.61427
[43]	validation_0-mae:3060.52395
[44]	validation_0-mae:3028.55207
[45]	validation_0-mae:3011.05262
[46]	validation_0-mae:2990.91722
[47]	validation_0-mae:2969.61828
[48]	validation_0-mae:2933.29359
[49]	validation_0-mae:2910.96062
[50]	validation_0-mae:2885.46139
[51]	validation_0-mae:2860.86438
[52]	validation_0-mae:2842.93481
[53]	validation_0-mae:2826.96631
[54]	validation_0-mae:2808.17513
[55]	validation_0-mae:2780.91523
[56]	validation_0-mae:2768.21601
[57]	validation_0-mae:2753.90912
[58]	validation_0-mae:2739.09467
[59]	validation_0-mae:2729.81086
[60]	validation_0-mae:2712.43662
[61]	validation_0-mae:2688.63902
[62]	validation_0-mae:2678.02762
[63]	validation_0-mae:2661.41917
[64]	validation_0-mae:2650.85026
[65]	validation_0-mae:2639.58972
[66]	validation_0-mae:2628.02367
[67]	validation_0-mae:2611.80241
[68]	validation_0-mae:2604.00199
[69]	validation_0-mae:2597.25154
[70]	validation_0-mae:2593.02772
[71]	validation_0-mae:2581.67309
[72]	validation_0-mae:2572.29289
[73]	validation_0-mae:2561.79064
[74]	validation_0-mae:2551.63936
[75]	validation_0-mae:2541.12224
[76]	validation_0-mae:2533.37266
[77]	validation_0-mae:2523.66886
[78]	validation_0-mae:2516.97881
[79]	validation_0-mae:2501.97410
[80]	validation_0-mae:2494.63874
[81]	validation_0-mae:2481.27428
[82]	validation_0-mae:2472.70485
[83]	validation_0-mae:2467.23531
[84]	validation_0-mae:2461.49739
[85]	validation_0-mae:2447.27441
[86]	validation_0-mae:2440.87017
[87]	validation_0-mae:2437.97046
[88]	validation_0-mae:2434.44408
[89]	validation_0-mae:2425.64824
[90]	validation_0-mae:2419.63421
[91]	validation_0-mae:2417.30667
[92]	validation_0-mae:2412.58375
[93]	validation_0-mae:2408.75721
[94]	validation_0-mae:2402.22853
[95]	validation_0-mae:2401.11141
[96]	validation_0-mae:2399.78339
[97]	validation_0-mae:2397.01697
[98]	validation_0-mae:2391.35702
[99]	validation_0-mae:2385.66832
[100]	validation_0-mae:2377.16523
[101]	validation_0-mae:2373.83016
[102]	validation_0-mae:2367.67289
[103]	validation_0-mae:2366.17564
[104]	validation_0-mae:2359.17644
[105]	validation_0-mae:2356.95381
[106]	validation_0-mae:2350.66345
[107]	validation_0-mae:2346.92700
[108]	validation_0-mae:2343.44443
[109]	validation_0-mae:2339.51908
[110]	validation_0-mae:2336.56174
[111]	validation_0-mae:2335.34665
[112]	validation_0-mae:2330.48929
[113]	validation_0-mae:2325.41490
[114]	validation_0-mae:2321.38778
[115]	validation_0-mae:2316.22150
[116]	validation_0-mae:2312.90669
[117]	validation_0-mae:2311.74355
[118]	validation_0-mae:2305.69212
[119]	validation_0-mae:2304.24282
[120]	validation_0-mae:2302.60325
[121]	validation_0-mae:2299.26193
[122]	validation_0-mae:2296.11241
[123]	validation_0-mae:2295.78588
[124]	validation_0-mae:2294.36687
[125]	validation_0-mae:2292.68978
[126]	validation_0-mae:2288.54378
[127]	validation_0-mae:2288.84256
[128]	validation_0-mae:2287.46614
[129]	validation_0-mae:2284.80929
[0]	validation_0-mae:12568.15134
[1]	validation_0-mae:11937.91271
[2]	validation_0-mae:11402.54252
[3]	validation_0-mae:10947.56596
[4]	validation_0-mae:10549.49272
[5]	validation_0-mae:10203.52936
[6]	validation_0-mae:9904.10863
[7]	validation_0-mae:9645.63644
[8]	validation_0-mae:9418.95109
[9]	validation_0-mae:9222.77609

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[0]	validation_0-mae:12766.75142
[1]	validation_0-mae:12290.30162
[2]	validation_0-mae:11835.07943
[3]	validation_0-mae:11394.91945
[4]	validation_0-mae:10990.84813
[5]	validation_0-mae:10596.94121
[6]	validation_0-mae:10255.04258
[7]	validation_0-mae:9922.93461
[8]	validation_0-mae:9615.92268
[9]	validation_0-mae:9333.71772
[10]	validation_0-mae:9048.54563
[0]	validation_0-mae:12390.00856
[1]	validation_0-mae:11618.17464
[2]	validation_0-mae:10905.20328
[3]	validation_0-mae:10257.87892
[4]	validation_0-mae:9691.75605
[5]	validation_0-mae:9172.69058
[6]	validation_0-mae:8720.67158
[7]	validation_0-mae:8301.84972
[8]	validation_0-mae:7921.60477
[9]	validation_0-mae:7557.86612
[10]	validation_0-mae:7213.75271
[11]	validation_0-mae:6904.45444
[12]	validation_0-mae:6627.71921
[13]	validation_0-mae:6348.75185
[14]	validation_0-mae:6114.73027
[15]	validation_0-mae:5886.27834
[16]	validation_0-mae:5663.98453
[17]	validation_0-mae:5471.69833
[18]	validation_0-mae:5261.35625
[19]	validation_0-mae:5105.84367
[20]	validation_0-mae:4934.49011
[21]	validation_0-mae:4772.73870
[22]	validation_0-mae:4635.70237
[23]	validation_0-mae:4515.42141
[24]	validation_0-mae:4393.25958
[25]	validation_0-mae:4292.11159
[26]	validation_0-mae:4170.73255
[27]	validation_0-mae:4075.65531
[28]	validation_0-mae:3961.28392
[29]	validation_0-mae:3856.93413
[30]	validation_0-mae:3765.23714
[31]	validation_0-mae:3698.65239
[32]	validation_0-mae:3625.60800
[33]	validation_0-mae:3544.80300
[34]	validation_0-mae:3473.38593
[35]	validation_0-mae:3415.33327
[36]	validation_0-mae:3367.21653
[37]	validation_0-mae:3308.71596

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[38]	validation_0-mae:3252.21889
[39]	validation_0-mae:3201.37520
[40]	validation_0-mae:3163.55088
[41]	validation_0-mae:3124.39193
[42]	validation_0-mae:3082.33199
[43]	validation_0-mae:3028.23575
[44]	validation_0-mae:2999.36481
[45]	validation_0-mae:2971.54649
[46]	validation_0-mae:2937.92917
[47]	validation_0-mae:2920.17115
[48]	validation_0-mae:2898.42936
[49]	validation_0-mae:2853.57346
[50]	validation_0-mae:2822.07083
[51]	validation_0-mae:2801.68887
[52]	validation_0-mae:2773.63289
[53]	validation_0-mae:2756.78871
[54]	validation_0-mae:2737.52615
[55]	validation_0-mae:2707.40947
[56]	validation_0-mae:2697.56368
[57]	validation_0-mae:2685.30921
[58]	validation_0-mae:2657.94102
[59]	validation_0-mae:2636.44570
[60]	validation_0-mae:2620.54047
[61]	validation_0-mae:2598.36640
[62]	validation_0-mae:2585.56951
[63]	validation_0-mae:2572.09432
[64]	validation_0-mae:2560.77842
[65]	validation_0-mae:2548.39415
[66]	validation_0-mae:2536.51663
[67]	validation_0-mae:2527.67223
[68]	validation_0-mae:2515.73399
[69]	validation_0-mae:2495.33042
[70]	validation_0-mae:2491.67533
[71]	validation_0-mae:2481.74121
[72]	validation_0-mae:2468.50425
[73]	validation_0-mae:2462.28604
[74]	validation_0-mae:2450.02602
[75]	validation_0-mae:2438.97553
[76]	validation_0-mae:2433.42548
[77]	validation_0-mae:2430.90932
[78]	validation_0-mae:2425.63492
[79]	validation_0-mae:2418.45681
[80]	validation_0-mae:2408.90324
[81]	validation_0-mae:2397.32663
[82]	validation_0-mae:2389.53009
[83]	validation_0-mae:2382.57124
[84]	validation_0-mae:2378.23898
[85]	validation_0-mae:2371.01738
[86]	validation_0-mae:2362.61177
[87]	validation_0-mae:2354.49210
[88]	validation_0-mae:2348.90596
[89]	validation_0-mae:2345.87546
[90]	validation_0-mae:2338.16670
[91]	validation_0-mae:2331.85304
[92]	validation_0-mae:2323.25190
[93]	validation_0-mae:2317.72967
[94]	validation_0-mae:2314.06807
[95]	validation_0-mae:2308.19040
[96]	validation_0-mae:2304.02311
[97]	validation_0-mae:2297.42689
[98]	validation_0-mae:2294.11887
[99]	validation_0-mae:2292.55194
[100]	validation_0-mae:2288.99570
[101]	validation_0-mae:2283.49355
[102]	validation_0-mae:2278.66216
[103]	validation_0-mae:2275.49628
[104]	validation_0-mae:2269.62051
[105]	validation_0-mae:2268.73264
[106]	validation_0-mae:2264.54689
[107]	validation_0-mae:2255.08666
[108]	validation_0-mae:2251.92402
[109]	validation_0-mae:2249.40674
[110]	validation_0-mae:2248.30495
[111]	validation_0-mae:2244.99547
[112]	validation_0-mae:2238.85051
[113]	validation_0-mae:2236.13231
[114]	validation_0-mae:2234.01961
[115]	validation_0-mae:2229.88464
[116]	validation_0-mae:2230.34606
[117]	validation_0-mae:2228.89863
[118]	validation_0-mae:2226.30803
[119]	validation_0-mae:2226.62920
[120]	validation_0-mae:2224.82164
[121]	validation_0-mae:2223.54352
[122]	validation_0-mae:2219.51730
[123]	validation_0-mae:2218.30060
[124]	validation_0-mae:2215.00205
[125]	validation_0-mae:2211.21366
[126]	validation_0-mae:2210.10179
[127]	validation_0-mae:2208.70427
[128]	validation_0-mae:2209.11818
[129]	validation_0-mae:2204.99106
[130]	validation_0-mae:2203.19700
[131]	validation_0-mae:2202.28774
[132]	validation_0-mae:2201.84046
[133]	validation_0-mae:2200.75889
[134]	validation_0-mae:2199.62380
[135]	validation_0-mae:2199.25311
[136]	validation_0-mae:2197.65460
[137]	validation_0-mae:2196.96638
[138]	validation_0-mae:2197.32934
[139]	validation_0-mae:2194.72120
[140]	validation_0-mae:2195.36143
[141]	validation_0-mae:2192.03908
[142]	validation_0-mae:2191.25983
[143]	validation_0-mae:2190.70445
[144]	validation_0-mae:2189.42627
[145]	validation_0-mae:2189.24068
[146]	validation_0-mae:2185.32978
[147]	validation_0-mae:2183.49818
[148]	validation_0-mae:2181.75123
[149]	validation_0-mae:2181.15060
[150]	validation_0-mae:2179.56816
[151]	validation_0-mae:2176.07684
[152]	validation_0-mae:2175.45429
[153]	validation_0-mae:2173.99113
[154]	validation_0-mae:2173.60633
[155]	validation_0-mae:2173.16396
[156]	validation_0-mae:2172.05836
[157]	validation_0-mae:2172.68400
[158]	validation_0-mae:2173.61353
[159]	validation_0-mae:2173.24231
[160]	validation_0-mae:2173.23318
[161]	validation_0-mae:2171.20241
[162]	validation_0-mae:2168.04994
[163]	validation_0-mae:2166.63532
[164]	validation_0-mae:2166.41039
[165]	validation_0-mae:2166.43395
[166]	validation_0-mae:2164.42539
[167]	validation_0-mae:2162.94401
[168]	validation_0-mae:2162.69969
[169]	validation_0-mae:2162.45633
[170]	validation_0-mae:2162.43984
[171]	validation_0-mae:2160.75043
[172]	validation_0-mae:2158.31689
[173]	validation_0-mae:2157.55870
[174]	validation_0-mae:2156.98956
[175]	validation_0-mae:2157.18639
[176]	validation_0-mae:2157.70738
[177]	validation_0-mae:2155.75696
[178]	validation_0-mae:2154.96614
[179]	validation_0-mae:2154.90567
[180]	validation_0-mae:2154.76133
[181]	validation_0-mae:2153.34492
[182]	validation_0-mae:2152.16060
[183]	validation_0-mae:2152.03550
[184]	validation_0-mae:2152.21947
[185]	validation_0-mae:2151.20344
[186]	validation_0-mae:2150.40829
[187]	validation_0-mae:2150.60705
[188]	validation_0-mae:2148.90392
[189]	validation_0-mae:2149.37279
[190]	validation_0-mae:2149.65117
[191]	validation_0-mae:2150.25975
[192]	validation_0-mae:2150.65707
[193]	validation_0-mae:2150.22178
[194]	validation_0-mae:2148.26656
[195]	validation_0-mae:2147.96664
[196]	validation_0-mae:2147.89521
[197]	validation_0-mae:2147.17339
[198]	validation_0-mae:2145.33401
[199]	validation_0-mae:2143.88849
[200]	validation_0-mae:2143.21861
[201]	validation_0-mae:2142.90062
[202]	validation_0-mae:2140.40401
[203]	validation_0-mae:2138.70846
[204]	validation_0-mae:2137.06507
[205]	validation_0-mae:2136.45535
[206]	validation_0-mae:2135.54444
[207]	validation_0-mae:2135.48844
[208]	validation_0-mae:2136.16162
[209]	validation_0-mae:2135.00649
[210]	validation_0-mae:2135.82380
[211]	validation_0-mae:2134.76100
[212]	validation_0-mae:2135.34169
[213]	validation_0-mae:2135.32853
[214]	validation_0-mae:2133.29135
[215]	validation_0-mae:2133.09775
[216]	validation_0-mae:2131.86272
[217]	validation_0-mae:2131.45246
[218]	validation_0-mae:2132.30763
[219]	validation_0-mae:2130.78353
[220]	validation_0-mae:2130.46365
[221]	validation_0-mae:2130.91039
[222]	validation_0-mae:2131.00129
[223]	validation_0-mae:2131.23192
[224]	validation_0-mae:2129.18751
[225]	validation_0-mae:2128.24227
[226]	validation_0-mae:2128.32962
[227]	validation_0-mae:2127.40450
[228]	validation_0-mae:2127.07726
[229]	validation_0-mae:2126.57132
[230]	validation_0-mae:2125.92475
[231]	validation_0-mae:2126.51285
[232]	validation_0-mae:2126.65614
[233]	validation_0-mae:2127.29309
[234]	validation_0-mae:2127.02071
[235]	validation_0-mae:2127.22070
[236]	validation_0-mae:2125.87055
[237]	validation_0-mae:2126.32243
[238]	validation_0-mae:2126.67570
[239]	validation_0-mae:2126.83246
[240]	validation_0-mae:2126.64457
[241]	validation_0-mae:2126.23773
[242]	validation_0-mae:2125.35523
[243]	validation_0-mae:2125.03725
[244]	validation_0-mae:2124.98421
[245]	validation_0-mae:2124.87441
[246]	validation_0-mae:2123.39958
[247]	validation_0-mae:2122.60820
[248]	validation_0-mae:2122.66778
[249]	validation_0-mae:2122.60450
[250]	validation_0-mae:2122.59827
[251]	validation_0-mae:2121.82623
[252]	validation_0-mae:2120.79534
[253]	validation_0-mae:2121.06004
[254]	validation_0-mae:2121.74313
[255]	validation_0-mae:2121.73794
[256]	validation_0-mae:2122.00892
[257]	validation_0-mae:2120.96624
[258]	validation_0-mae:2120.49386
[259]	validation_0-mae:2120.21471
[260]	validation_0-mae:2119.85392
[261]	validation_0-mae:2119.46299
[262]	validation_0-mae:2120.24459
[263]	validation_0-mae:2121.27072
[264]	validation_0-mae:2122.17274
[265]	validation_0-mae:2122.36093
[266]	validation_0-mae:2122.22312
[267]	validation_0-mae:2122.91691
[268]	validation_0-mae:2122.22663
[269]	validation_0-mae:2122.13018
[270]	validation_0-mae:2122.04540
[271]	validation_0-mae:2120.83840
[272]	validation_0-mae:2120.65173
[273]	validation_0-mae:2121.07287
[274]	validation_0-mae:2121.15402
[275]	validation_0-mae:2120.87231
[276]	validation_0-mae:2121.14335
[277]	validation_0-mae:2121.08273
[278]	validation_0-mae:2121.02585
[279]	validation_0-mae:2121.01948
[280]	validation_0-mae:2120.52737
[281]	validation_0-mae:2120.87225
[282]	validation_0-mae:2120.57852
[283]	validation_0-mae:2120.55488
[284]	validation_0-mae:2120.60571
[285]	validation_0-mae:2121.43061
[286]	validation_0-mae:2120.90800
[287]	validation_0-mae:2121.38793
[288]	validation_0-mae:2121.02233
[289]	validation_0-mae:2121.19666
[290]	validation_0-mae:2121.03737
[291]	validation_0-mae:2120.85906
[292]	validation_0-mae:2120.77472
[293]	validation_0-mae:2120.59269
[294]	validation_0-mae:2120.62307
[295]	validation_0-mae:2120.95652
[296]	validation_0-mae:2121.22769
[297]	validation_0-mae:2120.42559
[298]	validation_0-mae:2121.18326
[299]	validation_0-mae:2121.50362
[300]	validation_0-mae:2121.76238
[301]	validation_0-mae:2121.74138
[302]	validation_0-mae:2121.95405
[303]	validation_0-mae:2121.97839
[304]	validation_0-mae:2121.64429
[305]	validation_0-mae:2121.63902
[306]	validation_0-mae:2121.96732
[307]	validation_0-mae:2121.17549
[308]	validation_0-mae:2120.49495
[309]	validation_0-mae:2121.10714
[310]	validation_0-mae:2121.12887
[311]	validation_0-mae:2121.78518
[312]	validation_0-mae:2120.90043
[313]	validation_0-mae:2120.96625
[314]	validation_0-mae:2120.87687
[315]	validation_0-mae:2118.68793
[316]	validation_0-mae:2118.22828
[317]	validation_0-mae:2118.52803
[318]	validation_0-mae:2119.07881
[319]	validation_0-mae:2119.36269
[320]	validation_0-mae:2119.00793
[321]	validation_0-mae:2119.63401
[322]	validation_0-mae:2119.41532
[323]	validation_0-mae:2119.63598
[324]	validation_0-mae:2119.49504
[325]	validation_0-mae:2117.83215
[326]	validation_0-mae:2117.98968
[327]	validation_0-mae:2117.38460
[328]	validation_0-mae:2117.03861
[329]	validation_0-mae:2116.81518
[330]	validation_0-mae:2115.58513
[331]	validation_0-mae:2115.85855
[332]	validation_0-mae:2115.93180
[333]	validation_0-mae:2115.37806
[334]	validation_0-mae:2115.58428
[335]	validation_0-mae:2116.01485
[336]	validation_0-mae:2116.13504
[337]	validation_0-mae:2114.91468
[338]	validation_0-mae:2115.33475
[339]	validation_0-mae:2115.00667
[340]	validation_0-mae:2114.53120
[341]	validation_0-mae:2114.29467
[342]	validation_0-mae:2114.54900
[343]	validation_0-mae:2114.23113
[344]	validation_0-mae:2113.59068
[345]	validation_0-mae:2113.73264
[346]	validation_0-mae:2114.02146
[347]	validation_0-mae:2113.82264
[348]	validation_0-mae:2112.66771
[349]	validation_0-mae:2111.71828
[350]	validation_0-mae:2112.07254
[351]	validation_0-mae:2112.18078
[352]	validation_0-mae:2111.99153
[353]	validation_0-mae:2112.38337
[354]	validation_0-mae:2111.94486
[355]	validation_0-mae:2111.56339
[356]	validation_0-mae:2111.59730
[357]	validation_0-mae:2111.37927
[358]	validation_0-mae:2111.41421
[359]	validation_0-mae:2111.69479
[360]	validation_0-mae:2111.42223
[361]	validation_0-mae:2110.03570
[362]	validation_0-mae:2110.06081
[363]	validation_0-mae:2110.14933
[364]	validation_0-mae:2109.17925
[365]	validation_0-mae:2108.11956
[366]	validation_0-mae:2108.26476
[367]	validation_0-mae:2108.56547
[368]	validation_0-mae:2108.57940
[369]	validation_0-mae:2108.89704
[370]	validation_0-mae:2108.91417
[371]	validation_0-mae:2108.79627
[372]	validation_0-mae:2108.81592
[373]	validation_0-mae:2108.77278
[374]	validation_0-mae:2108.68791
[375]	validation_0-mae:2108.27381
[376]	validation_0-mae:2107.13382
[377]	validation_0-mae:2106.80204
[378]	validation_0-mae:2107.02292
[379]	validation_0-mae:2107.87488
[380]	validation_0-mae:2108.16213
[381]	validation_0-mae:2108.34545
[382]	validation_0-mae:2106.59379
[383]	validation_0-mae:2106.44226
[384]	validation_0-mae:2106.45453
[385]	validation_0-mae:2106.78262
[386]	validation_0-mae:2107.33101
[387]	validation_0-mae:2107.93532
[388]	validation_0-mae:2108.37719
[389]	validation_0-mae:2108.52642
[390]	validation_0-mae:2107.93611
[391]	validation_0-mae:2107.95245
[392]	validation_0-mae:2108.42375
[393]	validation_0-mae:2108.83741
[394]	validation_0-mae:2109.01083
[395]	validation_0-mae:2108.83302
[396]	validation_0-mae:2108.95260
[397]	validation_0-mae:2108.37209
[398]	validation_0-mae:2108.20487
[399]	validation_0-mae:2108.48198
[400]	validation_0-mae:2107.62679
[401]	validation_0-mae:2106.70007
[402]	validation_0-mae:2106.77736
[403]	validation_0-mae:2106.85262
[404]	validation_0-mae:2106.95614
[405]	validation_0-mae:2107.09785
[406]	validation_0-mae:2106.42781
[407]	validation_0-mae:2105.49761
[408]	validation_0-mae:2105.51480
[409]	validation_0-mae:2105.40342
[410]	validation_0-mae:2105.44392
[411]	validation_0-mae:2105.63642
[412]	validation_0-mae:2105.31668
[413]	validation_0-mae:2104.96008
[414]	validation_0-mae:2104.32821
[415]	validation_0-mae:2104.42125
[416]	validation_0-mae:2104.56501
[417]	validation_0-mae:2104.39247
[418]	validation_0-mae:2104.54108
[419]	validation_0-mae:2104.60268
[420]	validation_0-mae:2104.47763
[421]	validation_0-mae:2104.27913
[422]	validation_0-mae:2104.41992
[423]	validation_0-mae:2104.32533
[424]	validation_0-mae:2104.10932
[425]	validation_0-mae:2103.54012
[426]	validation_0-mae:2102.87777
[427]	validation_0-mae:2102.85044
[428]	validation_0-mae:2102.27649
[429]	validation_0-mae:2102.15453
[430]	validation_0-mae:2101.58524
[431]	validation_0-mae:2101.54459
[432]	validation_0-mae:2101.25462
[433]	validation_0-mae:2101.31256
[434]	validation_0-mae:2101.40043
[435]	validation_0-mae:2100.96379
[436]	validation_0-mae:2100.69412
[437]	validation_0-mae:2100.59718
[438]	validation_0-mae:2100.03999
[439]	validation_0-mae:2099.68557
[440]	validation_0-mae:2099.67453
[441]	validation_0-mae:2099.50513
[442]	validation_0-mae:2099.60228
[443]	validation_0-mae:2099.39302
[444]	validation_0-mae:2099.49968
[445]	validation_0-mae:2099.25211
[446]	validation_0-mae:2099.19054
[447]	validation_0-mae:2099.12897
[448]	validation_0-mae:2098.06286
[449]	validation_0-mae:2098.27737
[450]	validation_0-mae:2097.51543
[451]	validation_0-mae:2097.54614
[452]	validation_0-mae:2097.79699
[453]	validation_0-mae:2098.03754
[454]	validation_0-mae:2097.92999
[455]	validation_0-mae:2097.88677
[456]	validation_0-mae:2097.94907
[457]	validation_0-mae:2097.72396
[458]	validation_0-mae:2097.59966
[459]	validation_0-mae:2098.18746
[460]	validation_0-mae:2098.34831
[461]	validation_0-mae:2098.13515
[462]	validation_0-mae:2098.25503
[463]	validation_0-mae:2098.43006
[464]	validation_0-mae:2098.53088
[465]	validation_0-mae:2098.73326
[466]	validation_0-mae:2098.23729
[467]	validation_0-mae:2098.06041
[468]	validation_0-mae:2098.27487
[469]	validation_0-mae:2098.42468
[470]	validation_0-mae:2097.97994
[471]	validation_0-mae:2098.05498
[472]	validation_0-mae:2098.09529
[473]	validation_0-mae:2098.37026
[474]	validation_0-mae:2098.47675
[475]	validation_0-mae:2098.67911
[476]	validation_0-mae:2098.12706
[477]	validation_0-mae:2098.31469
[478]	validation_0-mae:2098.41184
[479]	validation_0-mae:2098.43422
[480]	validation_0-mae:2098.30325
[481]	validation_0-mae:2098.61816
[482]	validation_0-mae:2098.07101
[483]	validation_0-mae:2098.43434
[484]	validation_0-mae:2097.72872
[485]	validation_0-mae:2097.00042
[486]	validation_0-mae:2096.94036
[487]	validation_0-mae:2097.41453
[488]	validation_0-mae:2096.71565
[489]	validation_0-mae:2096.73128
[490]	validation_0-mae:2096.50492
[491]	validation_0-mae:2096.36311
[492]	validation_0-mae:2096.31599
[493]	validation_0-mae:2096.49141
[494]	validation_0-mae:2096.75100
[495]	validation_0-mae:2096.22087
[496]	validation_0-mae:2096.17111
[497]	validation_0-mae:2095.97578
[498]	validation_0-mae:2095.96155
[499]	validation_0-mae:2095.97749
[500]	validation_0-mae:2095.97613
[501]	validation_0-mae:2096.06077
[502]	validation_0-mae:2096.20534
[503]	validation_0-mae:2096.52336
[504]	validation_0-mae:2096.30801
[505]	validation_0-mae:2096.42020
[506]	validation_0-mae:2096.34284
[507]	validation_0-mae:2096.31658
[508]	validation_0-mae:2096.05294
[509]	validation_0-mae:2096.13353
[510]	validation_0-mae:2095.76456
[511]	validation_0-mae:2094.95888
[512]	validation_0-mae:2094.65806
[513]	validation_0-mae:2094.19814
[514]	validation_0-mae:2093.82665
[515]	validation_0-mae:2093.83732
[516]	validation_0-mae:2093.82697
[517]	validation_0-mae:2093.96559
[518]	validation_0-mae:2093.77796
[519]	validation_0-mae:2093.13906
[520]	validation_0-mae:2093.33026
[521]	validation_0-mae:2092.66670
[522]	validation_0-mae:2092.40031
[523]	validation_0-mae:2092.05741
[524]	validation_0-mae:2091.48538
[525]	validation_0-mae:2091.63631
[526]	validation_0-mae:2091.47250
[527]	validation_0-mae:2091.41875
[528]	validation_0-mae:2091.15489
[529]	validation_0-mae:2091.01022
[530]	validation_0-mae:2090.83168
[531]	validation_0-mae:2090.91704
[532]	validation_0-mae:2091.11960
[533]	validation_0-mae:2091.18689
[534]	validation_0-mae:2091.31091
[535]	validation_0-mae:2090.57141
[536]	validation_0-mae:2090.54284
[537]	validation_0-mae:2090.74768
[538]	validation_0-mae:2090.75733
[539]	validation_0-mae:2090.81197
[540]	validation_0-mae:2090.87917
[541]	validation_0-mae:2091.07657
[542]	validation_0-mae:2090.50798
[543]	validation_0-mae:2090.69817
[544]	validation_0-mae:2090.63788
[545]	validation_0-mae:2090.80178
[546]	validation_0-mae:2090.70697
[547]	validation_0-mae:2090.69789
[548]	validation_0-mae:2090.53999
[549]	validation_0-mae:2089.87739
[550]	validation_0-mae:2089.64896
[551]	validation_0-mae:2089.33611
[552]	validation_0-mae:2089.41647
[553]	validation_0-mae:2089.35860
[554]	validation_0-mae:2089.53611
[555]	validation_0-mae:2089.34899
[556]	validation_0-mae:2089.37160
[557]	validation_0-mae:2089.38833
[558]	validation_0-mae:2088.98216
[559]	validation_0-mae:2088.88729
[560]	validation_0-mae:2088.64859
[561]	validation_0-mae:2088.77049
[562]	validation_0-mae:2088.69833
[563]	validation_0-mae:2088.67788
[564]	validation_0-mae:2088.44259
[565]	validation_0-mae:2088.60560
[566]	validation_0-mae:2088.79287
[567]	validation_0-mae:2088.69166
[568]	validation_0-mae:2088.51761
[569]	validation_0-mae:2088.33343
[570]	validation_0-mae:2088.18842
[571]	validation_0-mae:2088.43716
[572]	validation_0-mae:2088.71601
[573]	validation_0-mae:2088.70274
[574]	validation_0-mae:2088.65997
[575]	validation_0-mae:2088.82559
[576]	validation_0-mae:2088.54680
[577]	validation_0-mae:2088.71973
[578]	validation_0-mae:2088.89595
[579]	validation_0-mae:2088.97402
[580]	validation_0-mae:2088.93503
[581]	validation_0-mae:2088.86676
[582]	validation_0-mae:2088.55096
[583]	validation_0-mae:2088.47838
[584]	validation_0-mae:2088.42574
[585]	validation_0-mae:2088.29203
[586]	validation_0-mae:2088.45497
[587]	validation_0-mae:2088.50647
[588]	validation_0-mae:2088.56207
[589]	validation_0-mae:2088.38300
[590]	validation_0-mae:2088.27772
[591]	validation_0-mae:2087.99220
[592]	validation_0-mae:2088.05728
[593]	validation_0-mae:2088.13612
[594]	validation_0-mae:2088.14692
[595]	validation_0-mae:2088.23614
[596]	validation_0-mae:2088.24465
[597]	validation_0-mae:2088.44440
[598]	validation_0-mae:2088.48244
[599]	validation_0-mae:2088.45472
[600]	validation_0-mae:2088.61577
[601]	validation_0-mae:2088.68017
[602]	validation_0-mae:2088.68957
[603]	validation_0-mae:2088.77569
[604]	validation_0-mae:2088.75281
[605]	validation_0-mae:2088.36928
[606]	validation_0-mae:2088.36176
[607]	validation_0-mae:2088.56103
[608]	validation_0-mae:2088.76238
[609]	validation_0-mae:2088.79783
[610]	validation_0-mae:2088.42004
[611]	validation_0-mae:2088.58161
[612]	validation_0-mae:2088.29431
[613]	validation_0-mae:2088.18072
[614]	validation_0-mae:2088.05611
[615]	validation_0-mae:2088.36638
[616]	validation_0-mae:2088.27896
[617]	validation_0-mae:2088.15904
[618]	validation_0-mae:2088.24863
[619]	validation_0-mae:2088.19560
[620]	validation_0-mae:2088.43579
[621]	validation_0-mae:2088.51838
[622]	validation_0-mae:2088.79282
[623]	validation_0-mae:2088.70289
[624]	validation_0-mae:2088.82470
[625]	validation_0-mae:2088.69498
[626]	validation_0-mae:2088.77128
[627]	validation_0-mae:2088.80001

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[32]	validation_0-mae:3600.84069
[33]	validation_0-mae:3541.40912
[34]	validation_0-mae:3472.24733
[35]	validation_0-mae:3424.42511
[36]	validation_0-mae:3363.80538
[37]	validation_0-mae:3318.99100
[38]	validation_0-mae:3276.75113
[39]	validation_0-mae:3231.83348
[40]	validation_0-mae:3193.48805
[41]	validation_0-mae:3150.86514
[42]	validation_0-mae:3116.63063
[43]	validation_0-mae:3062.67621
[44]	validation_0-mae:3015.98671
[45]	validation_0-mae:2990.27725
[46]	validation_0-mae:2961.10587
[47]	validation_0-mae:2926.42471
[48]	validation_0-mae:2903.74704
[49]	validation_0-mae:2872.27086
[50]	validation_0-mae:2840.00144
[51]	validation_0-mae:2816.71167
[52]	validation_0-mae:2800.51074
[53]	validation_0-mae:2783.12616
[54]	validation_0-mae:2760.35569
[55]	validation_0-mae:2740.77835
[56]	validation_0-mae:2724.87929
[57]	validation_0-mae:2712.15783
[58]	validation_0-mae:2694.97317
[59]	validation_0-mae:2680.39560
[60]	validation_0-mae:2663.71661
[61]	validation_0-mae:2649.38910
[62]	validation_0-mae:2637.87106
[63]	validation_0-mae:2621.82019
[64]	validation_0-mae:2601.50688
[65]	validation_0-mae:2590.59842
[66]	validation_0-mae:2580.26071
[67]	validation_0-mae:2574.36256
[68]	validation_0-mae:2566.50078
[69]	validation_0-mae:2560.87982
[70]	validation_0-mae:2555.71213
[71]	validation_0-mae:2534.65245
[72]	validation_0-mae:2526.43280
[73]	validation_0-mae:2517.23166
[74]	validation_0-mae:2512.02088
[75]	validation_0-mae:2500.05050
[76]	validation_0-mae:2495.66287
[77]	validation_0-mae:2487.27948
[78]	validation_0-mae:2480.25353
[79]	validation_0-mae:2473.29852
[80]	validation_0-mae:2465.05062
[81]	validation_0-mae:2459.12899
[82]	validation_0-mae:2450.14092
[83]	validation_0-mae:2441.36828
[84]	validation_0-mae:2434.39078
[85]	validation_0-mae:2430.75794
[86]	validation_0-mae:2420.25444
[87]	validation_0-mae:2415.50400
[88]	validation_0-mae:2411.00843
[89]	validation_0-mae:2404.30709
[90]	validation_0-mae:2398.62231
[91]	validation_0-mae:2392.80599
[92]	validation_0-mae:2384.05067
[93]	validation_0-mae:2380.94793
[94]	validation_0-mae:2377.23741
[95]	validation_0-mae:2370.55116
[96]	validation_0-mae:2366.52132
[97]	validation_0-mae:2362.59982
[98]	validation_0-mae:2356.73275
[99]	validation_0-mae:2352.96629
[100]	validation_0-mae:2347.69530
[101]	validation_0-mae:2343.67140
[102]	validation_0-mae:2340.80632
[103]	validation_0-mae:2335.31104
[104]	validation_0-mae:2330.43292
[105]	validation_0-mae:2325.10121
[106]	validation_0-mae:2320.30522
[107]	validation_0-mae:2315.33600
[108]	validation_0-mae:2315.29966
[109]	validation_0-mae:2311.55051
[110]	validation_0-mae:2308.24123
[111]	validation_0-mae:2302.97677
[112]	validation_0-mae:2298.36198
[113]	validation_0-mae:2293.78565
[114]	validation_0-mae:2292.07365
[115]	validation_0-mae:2288.54381
[116]	validation_0-mae:2286.71834
[117]	validation_0-mae:2283.01379
[118]	validation_0-mae:2280.13893
[119]	validation_0-mae:2277.64226
[120]	validation_0-mae:2274.67560
[121]	validation_0-mae:2267.54943
[122]	validation_0-mae:2265.93393
[123]	validation_0-mae:2262.52436
[124]	validation_0-mae:2261.14283
[125]	validation_0-mae:2262.40541
[126]	validation_0-mae:2257.65668
[127]	validation_0-mae:2256.91838
[128]	validation_0-mae:2256.37168
[129]	validation_0-mae:2253.64637
[130]	validation_0-mae:2248.90829
[131]	validation_0-mae:2246.55725
[132]	validation_0-mae:2244.41252
[133]	validation_0-mae:2244.63753
[134]	validation_0-mae:2242.25537
[135]	validation_0-mae:2242.07223
[136]	validation_0-mae:2241.03874
[137]	validation_0-mae:2237.80786
[138]	validation_0-mae:2237.73177
[139]	validation_0-mae:2234.60203
[140]	validation_0-mae:2232.12662
[141]	validation_0-mae:2226.40711
[142]	validation_0-mae:2226.47882
[143]	validation_0-mae:2223.37631
[144]	validation_0-mae:2222.90322
[145]	validation_0-mae:2222.90729
[146]	validation_0-mae:2219.80448
[147]	validation_0-mae:2216.98990
[148]	validation_0-mae:2215.08864
[149]	validation_0-mae:2215.90675
[150]	validation_0-mae:2214.93245
[151]	validation_0-mae:2211.46807
[152]	validation_0-mae:2211.24867
[153]	validation_0-mae:2210.11347
[154]	validation_0-mae:2210.11196
[155]	validation_0-mae:2209.38866
[156]	validation_0-mae:2203.69853
[157]	validation_0-mae:2200.54266
[158]	validation_0-mae:2197.24170
[159]	validation_0-mae:2196.48621
[160]	validation_0-mae:2194.38927
[161]	validation_0-mae:2192.60368
[162]	validation_0-mae:2193.06396
[163]	validation_0-mae:2193.16071
[164]	validation_0-mae:2191.63960
[165]	validation_0-mae:2190.17689
[166]	validation_0-mae:2188.03164
[167]	validation_0-mae:2187.94565
[168]	validation_0-mae:2187.02329
[169]	validation_0-mae:2185.87782
[170]	validation_0-mae:2185.80388
[171]	validation_0-mae:2185.34801
[172]	validation_0-mae:2185.42594
[173]	validation_0-mae:2184.80778
[174]	validation_0-mae:2184.09566
[175]	validation_0-mae:2183.11762
[176]	validation_0-mae:2182.58051
[177]	validation_0-mae:2181.48228
[178]	validation_0-mae:2181.49601
[179]	validation_0-mae:2181.99921
[180]	validation_0-mae:2180.85874
[181]	validation_0-mae:2179.43719
[182]	validation_0-mae:2180.42440
[183]	validation_0-mae:2179.88419
[184]	validation_0-mae:2178.82878
[185]	validation_0-mae:2176.09355
[186]	validation_0-mae:2175.77082
[187]	validation_0-mae:2175.44589
[188]	validation_0-mae:2175.71716
[189]	validation_0-mae:2174.70402
[190]	validation_0-mae:2173.73733
[191]	validation_0-mae:2173.40255
[192]	validation_0-mae:2173.04775
[193]	validation_0-mae:2173.45508
[194]	validation_0-mae:2171.61082
[195]	validation_0-mae:2171.65356
[196]	validation_0-mae:2171.84625
[197]	validation_0-mae:2171.16708
[198]	validation_0-mae:2170.72158
[199]	validation_0-mae:2169.81247
[200]	validation_0-mae:2168.81788
[201]	validation_0-mae:2165.54061
[202]	validation_0-mae:2164.53383
[203]	validation_0-mae:2161.99966
[204]	validation_0-mae:2161.02848
[205]	validation_0-mae:2161.41174
[206]	validation_0-mae:2160.70240
[207]	validation_0-mae:2160.75979
[208]	validation_0-mae:2160.19565
[209]	validation_0-mae:2158.74823
[210]	validation_0-mae:2158.56110
[211]	validation_0-mae:2157.71556
[212]	validation_0-mae:2157.25302
[213]	validation_0-mae:2157.82516
[214]	validation_0-mae:2158.92684
[215]	validation_0-mae:2158.95725
[216]	validation_0-mae:2158.78565
[217]	validation_0-mae:2158.06731
[218]	validation_0-mae:2157.24763
[219]	validation_0-mae:2157.55799
[220]	validation_0-mae:2156.92048
[221]	validation_0-mae:2157.03883
[222]	validation_0-mae:2157.73908
[223]	validation_0-mae:2156.32405
[224]	validation_0-mae:2156.57118
[225]	validation_0-mae:2155.40641
[226]	validation_0-mae:2155.89632
[227]	validation_0-mae:2154.38717
[228]	validation_0-mae:2154.30557
[229]	validation_0-mae:2152.63875
[230]	validation_0-mae:2152.33709
[231]	validation_0-mae:2152.05812
[232]	validation_0-mae:2152.33522
[233]	validation_0-mae:2152.35699
[234]	validation_0-mae:2152.44822
[235]	validation_0-mae:2151.90982
[236]	validation_0-mae:2152.36471
[237]	validation_0-mae:2153.18893
[238]	validation_0-mae:2153.78967
[239]	validation_0-mae:2153.47067
[240]	validation_0-mae:2153.52013
[241]	validation_0-mae:2153.05451
[242]	validation_0-mae:2152.83066
[243]	validation_0-mae:2153.21770
[244]	validation_0-mae:2153.30752
[245]	validation_0-mae:2153.37767
[246]	validation_0-mae:2153.14570
[247]	validation_0-mae:2153.65420
[248]	validation_0-mae:2153.32060
[249]	validation_0-mae:2151.72234
[250]	validation_0-mae:2150.76936
[251]	validation_0-mae:2150.28233
[252]	validation_0-mae:2149.67811
[253]	validation_0-mae:2150.17322
[254]	validation_0-mae:2151.34272
[255]	validation_0-mae:2151.62689
[256]	validation_0-mae:2151.69242
[257]	validation_0-mae:2151.62109
[258]	validation_0-mae:2150.97893
[259]	validation_0-mae:2150.91072
[260]	validation_0-mae:2151.04854
[261]	validation_0-mae:2150.93254
[262]	validation_0-mae:2150.23838
[263]	validation_0-mae:2149.79196
[264]	validation_0-mae:2150.28202
[265]	validation_0-mae:2149.71343
[266]	validation_0-mae:2149.34263
[267]	validation_0-mae:2150.03595
[268]	validation_0-mae:2151.07685
[269]	validation_0-mae:2151.46657
[270]	validation_0-mae:2150.97942
[271]	validation_0-mae:2149.64787
[272]	validation_0-mae:2148.68800
[273]	validation_0-mae:2146.21980
[274]	validation_0-mae:2145.25624
[275]	validation_0-mae:2144.89809
[276]	validation_0-mae:2143.90336
[277]	validation_0-mae:2142.72269
[278]	validation_0-mae:2143.42396
[279]	validation_0-mae:2143.64416
[280]	validation_0-mae:2143.80569
[281]	validation_0-mae:2142.42643
[282]	validation_0-mae:2141.97215
[283]	validation_0-mae:2141.51599
[284]	validation_0-mae:2140.74389
[285]	validation_0-mae:2140.38872
[286]	validation_0-mae:2140.12551
[287]	validation_0-mae:2139.93635
[288]	validation_0-mae:2140.47585
[289]	validation_0-mae:2139.58774
[290]	validation_0-mae:2139.59917
[291]	validation_0-mae:2140.19198
[292]	validation_0-mae:2140.02819
[293]	validation_0-mae:2139.81949
[294]	validation_0-mae:2139.69146
[295]	validation_0-mae:2139.58144
[296]	validation_0-mae:2139.60430
[297]	validation_0-mae:2138.32077
[298]	validation_0-mae:2139.13580
[299]	validation_0-mae:2139.19101
[300]	validation_0-mae:2140.07326
[301]	validation_0-mae:2139.97627
[302]	validation_0-mae:2140.02722
[303]	validation_0-mae:2140.39899
[304]	validation_0-mae:2139.73642
[305]	validation_0-mae:2139.45051
[306]	validation_0-mae:2138.39457
[307]	validation_0-mae:2137.85824
[308]	validation_0-mae:2137.82318
[309]	validation_0-mae:2137.77005
[310]	validation_0-mae:2136.39364
[311]	validation_0-mae:2136.10049
[312]	validation_0-mae:2135.75254
[313]	validation_0-mae:2135.48243
[314]	validation_0-mae:2135.04255
[315]	validation_0-mae:2135.07740
[316]	validation_0-mae:2135.78071
[317]	validation_0-mae:2135.23731
[318]	validation_0-mae:2135.32515
[319]	validation_0-mae:2135.12391
[320]	validation_0-mae:2134.95873
[321]	validation_0-mae:2134.99607
[322]	validation_0-mae:2134.57891
[323]	validation_0-mae:2134.43603
[324]	validation_0-mae:2134.90056
[325]	validation_0-mae:2134.84953
[326]	validation_0-mae:2135.09658
[327]	validation_0-mae:2135.07919
[328]	validation_0-mae:2135.15677
[329]	validation_0-mae:2135.41284
[330]	validation_0-mae:2134.77714
[0]	validation_0-mae:12378.00957
[1]	validation_0-mae:11608.00519
[2]	validation_0-mae:10887.44759
[3]	validation_0-mae:10217.79959
[4]	validation_0-mae:9650.39034
[5]	validation_0-mae:9108.60157
[6]	validation_0-mae:8661.33152
[7]	validation_0-mae:8232.23000
[8]	validation_0-mae:7834.88284
[9]	validation_0-mae:7461.60286
[10]	validation_0-mae:7132.98111
[11]	validation_0-mae:6828.50207
[12]	validation_0-mae:6550.79454
[13]	validation_0-mae:6275.43253
[14]	validation_0-mae:6050.50772
[15]	validation_0-mae:5817.50405
[16]	validation_0-mae:5604.54499
[17]	validation_0-mae:5403.02574
[18]	validation_0-mae:5224.21697
[19]	validation_0-mae:5053.47951
[20]	validation_0-mae:4882.62905
[21]	validation_0-mae:4724.19074
[22]	validation_0-mae:4588.91920
[23]	validation_0-mae:4456.05394
[24]	validation_0-mae:4349.87974
[25]	validation_0-mae:4241.83154
[26]	validation_0-mae:4127.61694
[27]	validation_0-mae:4022.26482
[28]	validation_0-mae:3937.39039
[29]	validation_0-mae:3832.36777
[30]	validation_0-mae:3729.91784
[31]	validation_0-mae:3650.07110
[32]	validation_0-mae:3576.21556

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[33]	validation_0-mae:3508.82408
[34]	validation_0-mae:3443.71927
[35]	validation_0-mae:3393.16700
[36]	validation_0-mae:3332.70771
[37]	validation_0-mae:3261.15602
[38]	validation_0-mae:3218.39296
[39]	validation_0-mae:3169.49219
[40]	validation_0-mae:3125.49748
[41]	validation_0-mae:3084.33951
[42]	validation_0-mae:3045.17476
[43]	validation_0-mae:3013.82028
[44]	validation_0-mae:2979.35416
[45]	validation_0-mae:2948.89880
[46]	validation_0-mae:2912.89122
[47]	validation_0-mae:2885.42179
[48]	validation_0-mae:2863.26730
[49]	validation_0-mae:2841.23252
[50]	validation_0-mae:2822.46221
[51]	validation_0-mae:2787.37988
[52]	validation_0-mae:2755.27126
[53]	validation_0-mae:2741.70053
[54]	validation_0-mae:2722.21097
[55]	validation_0-mae:2706.76121
[56]	validation_0-mae:2682.37448
[57]	validation_0-mae:2666.24259
[58]	validation_0-mae:2656.67768
[59]	validation_0-mae:2643.26275
[60]	validation_0-mae:2624.46252
[61]	validation_0-mae:2600.45378
[62]	validation_0-mae:2584.03355
[63]	validation_0-mae:2573.96120
[64]	validation_0-mae:2564.53588
[65]	validation_0-mae:2553.12646
[66]	validation_0-mae:2540.12047
[67]	validation_0-mae:2522.15032
[68]	validation_0-mae:2500.77006
[69]	validation_0-mae:2492.47630
[70]	validation_0-mae:2483.05441
[71]	validation_0-mae:2476.05900
[72]	validation_0-mae:2470.57074
[73]	validation_0-mae:2459.38968
[74]	validation_0-mae:2445.67820
[75]	validation_0-mae:2438.91536
[76]	validation_0-mae:2433.02239
[77]	validation_0-mae:2421.50564
[78]	validation_0-mae:2416.10557
[79]	validation_0-mae:2409.54095
[80]	validation_0-mae:2399.03740
[81]	validation_0-mae:2392.83588
[82]	validation_0-mae:2386.42958
[83]	validation_0-mae:2375.84444
[84]	validation_0-mae:2372.60043
[85]	validation_0-mae:2363.00567
[86]	validation_0-mae:2356.68302
[87]	validation_0-mae:2351.08534
[88]	validation_0-mae:2346.98438
[89]	validation_0-mae:2340.37513
[90]	validation_0-mae:2331.52592
[91]	validation_0-mae:2325.20123
[92]	validation_0-mae:2321.52525
[93]	validation_0-mae:2321.52003
[94]	validation_0-mae:2318.05260
[95]	validation_0-mae:2313.37779
[96]	validation_0-mae:2306.89457
[97]	validation_0-mae:2302.85461
[98]	validation_0-mae:2299.34893
[99]	validation_0-mae:2297.85589
[100]	validation_0-mae:2291.68498
[101]	validation_0-mae:2290.45365
[102]	validation_0-mae:2289.02455
[103]	validation_0-mae:2287.96085
[104]	validation_0-mae:2280.94504
[105]	validation_0-mae:2275.24037
[106]	validation_0-mae:2274.16242
[107]	validation_0-mae:2268.96082
[108]	validation_0-mae:2267.99324
[109]	validation_0-mae:2262.57606
[110]	validation_0-mae:2260.71418
[111]	validation_0-mae:2258.03651
[112]	validation_0-mae:2255.71611
[113]	validation_0-mae:2252.94127
[114]	validation_0-mae:2252.88468
[115]	validation_0-mae:2252.84326
[116]	validation_0-mae:2250.01021
[117]	validation_0-mae:2247.76871
[118]	validation_0-mae:2242.44138
[119]	validation_0-mae:2240.53469
[120]	validation_0-mae:2238.32681
[121]	validation_0-mae:2235.80006
[122]	validation_0-mae:2235.82654
[123]	validation_0-mae:2234.12339
[124]	validation_0-mae:2231.78940
[125]	validation_0-mae:2230.29062
[126]	validation_0-mae:2227.88974
[127]	validation_0-mae:2226.23425
[128]	validation_0-mae:2225.55487
[129]	validation_0-mae:2223.75836
[130]	validation_0-mae:2224.16209
[131]	validation_0-mae:2224.34394
[132]	validation_0-mae:2222.58078
[133]	validation_0-mae:2221.46283
[134]	validation_0-mae:2219.67468
[135]	validation_0-mae:2217.65599
[136]	validation_0-mae:2216.86345
[137]	validation_0-mae:2215.01354
[138]	validation_0-mae:2214.45091
[139]	validation_0-mae:2211.68820
[140]	validation_0-mae:2210.72403
[141]	validation_0-mae:2207.77450
[142]	validation_0-mae:2206.82149
[143]	validation_0-mae:2205.72365
[144]	validation_0-mae:2205.63477
[145]	validation_0-mae:2204.93751
[146]	validation_0-mae:2204.40488
[147]	validation_0-mae:2203.67861
[148]	validation_0-mae:2202.74359
[149]	validation_0-mae:2202.54076
[150]	validation_0-mae:2200.58743
[151]	validation_0-mae:2199.69855
[152]	validation_0-mae:2198.80000
[153]	validation_0-mae:2197.77186
[154]	validation_0-mae:2198.16481
[155]	validation_0-mae:2196.89593
[156]	validation_0-mae:2197.84111
[157]	validation_0-mae:2195.98657
[158]	validation_0-mae:2195.35921
[159]	validation_0-mae:2195.02731
[160]	validation_0-mae:2190.65679
[161]	validation_0-mae:2190.39754
[162]	validation_0-mae:2188.97796
[163]	validation_0-mae:2187.28842
[164]	validation_0-mae:2185.86408
[165]	validation_0-mae:2185.75272
[166]	validation_0-mae:2183.54467
[167]	validation_0-mae:2183.20662
[168]	validation_0-mae:2183.33252
[169]	validation_0-mae:2184.48866
[170]	validation_0-mae:2181.96341
[171]	validation_0-mae:2180.07305
[172]	validation_0-mae:2179.91562
[173]	validation_0-mae:2179.97047
[174]	validation_0-mae:2178.80629
[175]	validation_0-mae:2177.34797
[176]	validation_0-mae:2176.59966
[177]	validation_0-mae:2173.08138
[178]	validation_0-mae:2171.70746
[179]	validation_0-mae:2170.04860
[180]	validation_0-mae:2170.12351
[181]	validation_0-mae:2170.71906
[182]	validation_0-mae:2170.40578
[183]	validation_0-mae:2170.11885
[184]	validation_0-mae:2170.35435
[185]	validation_0-mae:2170.92287
[186]	validation_0-mae:2169.92491
[187]	validation_0-mae:2166.08687
[188]	validation_0-mae:2166.24598
[189]	validation_0-mae:2165.20228
[190]	validation_0-mae:2164.55471
[191]	validation_0-mae:2163.72036
[192]	validation_0-mae:2164.02637
[193]	validation_0-mae:2163.84830
[194]	validation_0-mae:2163.21434
[195]	validation_0-mae:2161.69886
[196]	validation_0-mae:2159.05664
[197]	validation_0-mae:2158.50926
[198]	validation_0-mae:2158.52284
[199]	validation_0-mae:2157.66688
[200]	validation_0-mae:2156.86147
[201]	validation_0-mae:2156.71709
[202]	validation_0-mae:2155.78621
[203]	validation_0-mae:2155.06857
[204]	validation_0-mae:2154.01952
[205]	validation_0-mae:2153.60764
[206]	validation_0-mae:2154.89896
[207]	validation_0-mae:2155.44330
[208]	validation_0-mae:2155.61777
[209]	validation_0-mae:2154.90239
[210]	validation_0-mae:2154.82365
[211]	validation_0-mae:2155.53002
[212]	validation_0-mae:2155.39699
[213]	validation_0-mae:2154.16602
[214]	validation_0-mae:2153.86343
[215]	validation_0-mae:2153.57189
[216]	validation_0-mae:2152.94965
[217]	validation_0-mae:2153.83384
[218]	validation_0-mae:2151.73321
[219]	validation_0-mae:2151.54755
[220]	validation_0-mae:2150.97823
[221]	validation_0-mae:2151.35850
[222]	validation_0-mae:2148.76665
[223]	validation_0-mae:2148.41162
[224]	validation_0-mae:2148.74258
[225]	validation_0-mae:2148.07905
[226]	validation_0-mae:2147.12829
[227]	validation_0-mae:2147.77451
[228]	validation_0-mae:2148.54914
[229]	validation_0-mae:2147.67622
[230]	validation_0-mae:2147.08805
[231]	validation_0-mae:2146.37977
[232]	validation_0-mae:2145.72070
[233]	validation_0-mae:2144.25518
[234]	validation_0-mae:2143.53667
[235]	validation_0-mae:2141.60890
[236]	validation_0-mae:2141.80412
[237]	validation_0-mae:2141.27642
[238]	validation_0-mae:2140.89549
[239]	validation_0-mae:2139.54522
[240]	validation_0-mae:2137.85337
[241]	validation_0-mae:2136.23346
[242]	validation_0-mae:2135.79002
[243]	validation_0-mae:2135.62451
[244]	validation_0-mae:2134.57006
[245]	validation_0-mae:2133.51115
[246]	validation_0-mae:2133.77173
[247]	validation_0-mae:2132.20961
[248]	validation_0-mae:2132.06604
[249]	validation_0-mae:2132.05661
[250]	validation_0-mae:2131.92565
[251]	validation_0-mae:2131.88645
[252]	validation_0-mae:2130.46150
[253]	validation_0-mae:2129.95664
[254]	validation_0-mae:2129.57167
[255]	validation_0-mae:2130.05346
[256]	validation_0-mae:2130.47767
[257]	validation_0-mae:2130.67351
[258]	validation_0-mae:2131.14821
[259]	validation_0-mae:2130.78400
[260]	validation_0-mae:2131.20490
[261]	validation_0-mae:2131.01613
[262]	validation_0-mae:2131.46794
[263]	validation_0-mae:2131.76972
[264]	validation_0-mae:2131.45985
[265]	validation_0-mae:2130.75236
[266]	validation_0-mae:2130.24694
[267]	validation_0-mae:2130.29312
[268]	validation_0-mae:2131.09065
[269]	validation_0-mae:2131.05474
[270]	validation_0-mae:2130.62942
[271]	validation_0-mae:2129.97736
[272]	validation_0-mae:2129.77374
[273]	validation_0-mae:2129.94147
[274]	validation_0-mae:2129.42654
[275]	validation_0-mae:2128.62852
[276]	validation_0-mae:2127.57782
[277]	validation_0-mae:2127.05702
[278]	validation_0-mae:2126.18352
[279]	validation_0-mae:2125.85402
[280]	validation_0-mae:2123.93340
[281]	validation_0-mae:2123.91246
[282]	validation_0-mae:2123.50034
[283]	validation_0-mae:2121.75397
[284]	validation_0-mae:2121.31648
[285]	validation_0-mae:2121.51200
[286]	validation_0-mae:2121.78779
[287]	validation_0-mae:2121.54986
[288]	validation_0-mae:2120.64680
[289]	validation_0-mae:2119.99486
[290]	validation_0-mae:2120.10125
[291]	validation_0-mae:2119.62900
[292]	validation_0-mae:2119.56491
[293]	validation_0-mae:2119.59943
[294]	validation_0-mae:2119.65493
[295]	validation_0-mae:2119.06511
[296]	validation_0-mae:2119.31111
[297]	validation_0-mae:2119.12827
[298]	validation_0-mae:2118.85508
[299]	validation_0-mae:2118.88059
[300]	validation_0-mae:2117.55711
[301]	validation_0-mae:2117.77093
[302]	validation_0-mae:2117.85116
[303]	validation_0-mae:2117.98818
[304]	validation_0-mae:2118.03832
[305]	validation_0-mae:2117.06684
[306]	validation_0-mae:2117.31051
[307]	validation_0-mae:2117.30927
[308]	validation_0-mae:2117.18690
[309]	validation_0-mae:2116.44034
[310]	validation_0-mae:2116.22695
[311]	validation_0-mae:2116.38877
[312]	validation_0-mae:2116.79318
[313]	validation_0-mae:2116.20260
[314]	validation_0-mae:2116.32635
[315]	validation_0-mae:2116.39404
[316]	validation_0-mae:2116.09591
[317]	validation_0-mae:2115.94578
[318]	validation_0-mae:2115.59791
[319]	validation_0-mae:2115.94712
[320]	validation_0-mae:2115.45397
[321]	validation_0-mae:2115.57803
[322]	validation_0-mae:2115.03555
[323]	validation_0-mae:2114.35182
[324]	validation_0-mae:2113.80595
[325]	validation_0-mae:2113.81722
[326]	validation_0-mae:2113.33460
[327]	validation_0-mae:2113.21024
[328]	validation_0-mae:2112.89206
[329]	validation_0-mae:2112.85133
[330]	validation_0-mae:2111.59098
[331]	validation_0-mae:2110.90460
[332]	validation_0-mae:2111.00732
[333]	validation_0-mae:2111.09019
[334]	validation_0-mae:2110.91377
[335]	validation_0-mae:2110.12314
[336]	validation_0-mae:2108.86370
[337]	validation_0-mae:2108.74591
[338]	validation_0-mae:2108.06450
[339]	validation_0-mae:2108.08103
[340]	validation_0-mae:2107.77770
[341]	validation_0-mae:2107.92143
[342]	validation_0-mae:2107.54684
[343]	validation_0-mae:2107.83842
[344]	validation_0-mae:2107.36874
[345]	validation_0-mae:2107.17223
[346]	validation_0-mae:2107.39744
[347]	validation_0-mae:2107.78971
[348]	validation_0-mae:2107.34384
[349]	validation_0-mae:2107.11419
[350]	validation_0-mae:2107.37906
[351]	validation_0-mae:2107.49761
[352]	validation_0-mae:2107.78888
[353]	validation_0-mae:2107.68888
[354]	validation_0-mae:2107.47514
[355]	validation_0-mae:2107.53551
[356]	validation_0-mae:2107.71630
[357]	validation_0-mae:2107.60638
[358]	validation_0-mae:2108.03671
[359]	validation_0-mae:2107.50995
[360]	validation_0-mae:2107.91026
[361]	validation_0-mae:2107.88383
[362]	validation_0-mae:2107.95544
[363]	validation_0-mae:2106.91339
[364]	validation_0-mae:2107.13715
[365]	validation_0-mae:2107.09759
[366]	validation_0-mae:2106.44843
[367]	validation_0-mae:2105.90902
[368]	validation_0-mae:2105.24606
[369]	validation_0-mae:2105.14252
[370]	validation_0-mae:2105.40538
[371]	validation_0-mae:2105.33917
[372]	validation_0-mae:2104.68774
[373]	validation_0-mae:2104.53153
[374]	validation_0-mae:2103.82704
[375]	validation_0-mae:2103.43230
[376]	validation_0-mae:2103.74324
[377]	validation_0-mae:2103.97948
[378]	validation_0-mae:2104.05251
[379]	validation_0-mae:2104.14215
[380]	validation_0-mae:2104.30404
[381]	validation_0-mae:2103.86192
[382]	validation_0-mae:2103.78258
[383]	validation_0-mae:2103.36154
[384]	validation_0-mae:2103.25753
[385]	validation_0-mae:2103.45932
[386]	validation_0-mae:2103.18599
[387]	validation_0-mae:2103.06445
[388]	validation_0-mae:2102.50155
[389]	validation_0-mae:2101.68916
[390]	validation_0-mae:2101.36593
[391]	validation_0-mae:2101.51814
[392]	validation_0-mae:2101.74843
[393]	validation_0-mae:2101.53179
[394]	validation_0-mae:2101.71134
[395]	validation_0-mae:2102.47496
[396]	validation_0-mae:2101.77857
[397]	validation_0-mae:2100.81618
[398]	validation_0-mae:2101.35931
[399]	validation_0-mae:2101.33709
[400]	validation_0-mae:2101.45509
[401]	validation_0-mae:2100.13594
[402]	validation_0-mae:2100.19172
[403]	validation_0-mae:2099.45142
[404]	validation_0-mae:2099.22702
[405]	validation_0-mae:2099.30755
[406]	validation_0-mae:2099.55557
[407]	validation_0-mae:2099.47821
[408]	validation_0-mae:2099.51173
[409]	validation_0-mae:2099.38485
[410]	validation_0-mae:2099.55018
[411]	validation_0-mae:2099.66348
[412]	validation_0-mae:2099.76227
[413]	validation_0-mae:2099.83299
[414]	validation_0-mae:2099.63240
[415]	validation_0-mae:2099.63139
[416]	validation_0-mae:2099.60239
[417]	validation_0-mae:2099.18390
[418]	validation_0-mae:2099.34409
[419]	validation_0-mae:2099.98210
[420]	validation_0-mae:2099.75632
[421]	validation_0-mae:2099.99288
[422]	validation_0-mae:2099.95516
[423]	validation_0-mae:2100.57209
[424]	validation_0-mae:2100.74022
[425]	validation_0-mae:2100.78096
[426]	validation_0-mae:2100.32027
[427]	validation_0-mae:2099.96311
[428]	validation_0-mae:2100.53724
[429]	validation_0-mae:2100.27708
[430]	validation_0-mae:2100.11425
[431]	validation_0-mae:2100.12239
[432]	validation_0-mae:2099.57796
[433]	validation_0-mae:2099.67966
[434]	validation_0-mae:2099.56718
[435]	validation_0-mae:2099.61127
[436]	validation_0-mae:2099.65694
[437]	validation_0-mae:2099.79409
[438]	validation_0-mae:2099.72081
[439]	validation_0-mae:2099.51422
[440]	validation_0-mae:2099.18249
[441]	validation_0-mae:2099.16380
[442]	validation_0-mae:2098.76530
[443]	validation_0-mae:2098.47616
[444]	validation_0-mae:2098.58356
[445]	validation_0-mae:2098.09887
[446]	validation_0-mae:2097.90968
[447]	validation_0-mae:2097.55293
[448]	validation_0-mae:2096.54965
[449]	validation_0-mae:2096.56336
[450]	validation_0-mae:2096.50800
[451]	validation_0-mae:2096.57633
[452]	validation_0-mae:2096.36988
[453]	validation_0-mae:2096.39175
[454]	validation_0-mae:2095.75183
[455]	validation_0-mae:2095.54754
[456]	validation_0-mae:2095.52997
[457]	validation_0-mae:2095.61732
[458]	validation_0-mae:2095.89427
[459]	validation_0-mae:2095.92023
[460]	validation_0-mae:2096.13479
[461]	validation_0-mae:2096.36932
[462]	validation_0-mae:2095.84440
[463]	validation_0-mae:2095.49202
[464]	validation_0-mae:2095.56209
[465]	validation_0-mae:2095.15638
[466]	validation_0-mae:2094.92778
[467]	validation_0-mae:2094.85049
[468]	validation_0-mae:2094.87530
[469]	validation_0-mae:2094.93849
[470]	validation_0-mae:2095.01082
[471]	validation_0-mae:2094.81802
[472]	validation_0-mae:2094.87389
[473]	validation_0-mae:2095.02281
[474]	validation_0-mae:2094.69507
[475]	validation_0-mae:2094.77664
[476]	validation_0-mae:2094.79109
[477]	validation_0-mae:2095.00529
[478]	validation_0-mae:2094.85815
[479]	validation_0-mae:2094.62780
[480]	validation_0-mae:2094.82213
[481]	validation_0-mae:2094.71813
[482]	validation_0-mae:2094.83107
[483]	validation_0-mae:2094.63805
[484]	validation_0-mae:2094.78318
[485]	validation_0-mae:2094.78453
[486]	validation_0-mae:2095.08753
[487]	validation_0-mae:2094.96666
[488]	validation_0-mae:2095.09989
[489]	validation_0-mae:2095.04802
[490]	validation_0-mae:2094.49382
[491]	validation_0-mae:2095.05410
[492]	validation_0-mae:2094.79152
[493]	validation_0-mae:2094.86518
[494]	validation_0-mae:2094.76150
[495]	validation_0-mae:2094.75677
[496]	validation_0-mae:2094.28538
[497]	validation_0-mae:2094.27787
[498]	validation_0-mae:2094.69756
[499]	validation_0-mae:2094.98167
[500]	validation_0-mae:2094.72835
[501]	validation_0-mae:2094.52913
[502]	validation_0-mae:2094.32503
[503]	validation_0-mae:2094.45106
[504]	validation_0-mae:2094.64331
[505]	validation_0-mae:2094.43246
[506]	validation_0-mae:2094.70049
[507]	validation_0-mae:2094.28082
[508]	validation_0-mae:2094.07046
[509]	validation_0-mae:2094.23579
[510]	validation_0-mae:2094.46465
[511]	validation_0-mae:2094.09139
[512]	validation_0-mae:2094.24736
[513]	validation_0-mae:2093.97185
[514]	validation_0-mae:2093.82023
[515]	validation_0-mae:2094.00978
[516]	validation_0-mae:2094.09261
[517]	validation_0-mae:2094.21419
[518]	validation_0-mae:2094.41842
[519]	validation_0-mae:2094.16709
[520]	validation_0-mae:2094.32807
[521]	validation_0-mae:2094.11978
[522]	validation_0-mae:2093.02099
[523]	validation_0-mae:2093.03619
[524]	validation_0-mae:2093.14182
[525]	validation_0-mae:2093.16221
[526]	validation_0-mae:2093.01423
[527]	validation_0-mae:2093.08803
[528]	validation_0-mae:2093.07914
[529]	validation_0-mae:2092.87508
[530]	validation_0-mae:2092.98230
[531]	validation_0-mae:2092.81502
[532]	validation_0-mae:2091.81855
[533]	validation_0-mae:2091.45917
[534]	validation_0-mae:2091.46395
[535]	validation_0-mae:2091.48353
[536]	validation_0-mae:2091.46068
[537]	validation_0-mae:2091.36884
[538]	validation_0-mae:2091.42565
[539]	validation_0-mae:2091.73519
[540]	validation_0-mae:2091.68708
[541]	validation_0-mae:2091.59673
[542]	validation_0-mae:2091.78277
[543]	validation_0-mae:2091.55626
[544]	validation_0-mae:2091.42904
[545]	validation_0-mae:2091.52006
[546]	validation_0-mae:2091.47031
[547]	validation_0-mae:2091.36768
[548]	validation_0-mae:2091.43221
[549]	validation_0-mae:2091.41453
[550]	validation_0-mae:2091.67313
[551]	validation_0-mae:2091.75942
[552]	validation_0-mae:2091.35979
[553]	validation_0-mae:2091.25832
[554]	validation_0-mae:2091.40382
[555]	validation_0-mae:2091.50779
[556]	validation_0-mae:2091.21778
[557]	validation_0-mae:2090.90903
[558]	validation_0-mae:2091.06523
[559]	validation_0-mae:2091.06370
[560]	validation_0-mae:2091.18823
[561]	validation_0-mae:2091.16536
[562]	validation_0-mae:2090.82470
[563]	validation_0-mae:2090.82843
[564]	validation_0-mae:2090.92999
[565]	validation_0-mae:2090.82115
[566]	validation_0-mae:2090.86462
[567]	validation_0-mae:2091.08477
[568]	validation_0-mae:2091.13834
[569]	validation_0-mae:2091.14220
[570]	validation_0-mae:2091.29198
[571]	validation_0-mae:2091.29190
[572]	validation_0-mae:2090.94411
[573]	validation_0-mae:2090.53944
[574]	validation_0-mae:2090.59961
[575]	validation_0-mae:2090.53904
[576]	validation_0-mae:2090.46661
[577]	validation_0-mae:2090.26317
[578]	validation_0-mae:2090.09267
[579]	validation_0-mae:2089.83816
[580]	validation_0-mae:2090.04100
[581]	validation_0-mae:2089.78506
[582]	validation_0-mae:2089.67818
[583]	validation_0-mae:2089.83283
[584]	validation_0-mae:2089.71163
[585]	validation_0-mae:2089.63857
[586]	validation_0-mae:2089.53491
[587]	validation_0-mae:2089.42288
[588]	validation_0-mae:2089.43418
[589]	validation_0-mae:2089.37035
[590]	validation_0-mae:2089.36340
[591]	validation_0-mae:2089.44356
[592]	validation_0-mae:2089.40264
[593]	validation_0-mae:2089.44825
[594]	validation_0-mae:2089.29746
[595]	validation_0-mae:2089.09870
[596]	validation_0-mae:2089.16354
[597]	validation_0-mae:2089.00751
[598]	validation_0-mae:2089.05054
[599]	validation_0-mae:2088.90125
[600]	validation_0-mae:2088.95026
[601]	validation_0-mae:2088.73805
[602]	validation_0-mae:2088.68304
[603]	validation_0-mae:2088.42320
[604]	validation_0-mae:2088.60113
[605]	validation_0-mae:2088.61241
[606]	validation_0-mae:2088.74544
[607]	validation_0-mae:2088.70740
[608]	validation_0-mae:2088.86539
[609]	validation_0-mae:2089.02685
[610]	validation_0-mae:2088.96444
[611]	validation_0-mae:2088.89026
[612]	validation_0-mae:2088.88488
[613]	validation_0-mae:2088.95464
[614]	validation_0-mae:2088.87263
[615]	validation_0-mae:2088.76535
[616]	validation_0-mae:2088.87494
[617]	validation_0-mae:2089.07875
[618]	validation_0-mae:2089.03144
[619]	validation_0-mae:2088.75077
[620]	validation_0-mae:2088.56881
[621]	validation_0-mae:2088.55456
[622]	validation_0-mae:2088.45581

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[18]	validation_0-mae:5394.16386
[19]	validation_0-mae:5206.71916
[20]	validation_0-mae:5030.48080
[21]	validation_0-mae:4873.66609
[22]	validation_0-mae:4748.71266
[23]	validation_0-mae:4605.21936
[24]	validation_0-mae:4479.50419
[25]	validation_0-mae:4364.40429
[26]	validation_0-mae:4252.32423
[27]	validation_0-mae:4150.96300
[28]	validation_0-mae:4046.52668
[29]	validation_0-mae:3965.47633
[30]	validation_0-mae:3873.80481
[31]	validation_0-mae:3788.22826
[32]	validation_0-mae:3709.78689
[33]	validation_0-mae:3630.15191
[34]	validation_0-mae:3571.40029
[35]	validation_0-mae:3491.05120
[36]	validation_0-mae:3432.56846
[37]	validation_0-mae:3371.74393
[38]	validation_0-mae:3325.84039
[39]	validation_0-mae:3279.78370
[40]	validation_0-mae:3225.43526
[41]	validation_0-mae:3181.69405
[42]	validation_0-mae:3136.69178
[43]	validation_0-mae:3093.08132
[44]	validation_0-mae:3049.11793
[45]	validation_0-mae:3005.50958
[46]	validation_0-mae:2975.07644
[47]	validation_0-mae:2940.53164
[48]	validation_0-mae:2913.63231
[49]	validation_0-mae:2892.52078
[50]	validation_0-mae:2868.81875
[51]	validation_0-mae:2847.62030
[52]	validation_0-mae:2817.88446
[53]	validation_0-mae:2797.45146
[54]	validation_0-mae:2782.84221
[55]	validation_0-mae:2760.67447
[56]	validation_0-mae:2744.95560
[57]	validation_0-mae:2722.24594
[58]	validation_0-mae:2711.42214
[59]	validation_0-mae:2687.84796
[60]	validation_0-mae:2671.32719
[61]	validation_0-mae:2650.44493
[62]	validation_0-mae:2636.05717
[63]	validation_0-mae:2622.19027
[64]	validation_0-mae:2607.72057
[65]	validation_0-mae:2596.50554
[66]	validation_0-mae:2583.02080
[67]	validation_0-mae:2574.51222
[68]	validation_0-mae:2557.71267
[69]	validation_0-mae:2545.38693
[70]	validation_0-mae:2535.57523
[71]	validation_0-mae:2528.18036
[72]	validation_0-mae:2520.93967
[73]	validation_0-mae:2514.37625
[74]	validation_0-mae:2505.82708
[75]	validation_0-mae:2498.53752
[76]	validation_0-mae:2491.32827
[77]	validation_0-mae:2479.13764
[78]	validation_0-mae:2471.79593
[79]	validation_0-mae:2464.88818
[80]	validation_0-mae:2455.86606
[81]	validation_0-mae:2448.44578
[82]	validation_0-mae:2441.30994
[83]	validation_0-mae:2435.11181
[84]	validation_0-mae:2429.23960
[85]	validation_0-mae:2422.54391
[86]	validation_0-mae:2413.03770
[87]	validation_0-mae:2411.73470
[88]	validation_0-mae:2398.68777
[89]	validation_0-mae:2391.71228
[90]	validation_0-mae:2384.25892
[91]	validation_0-mae:2376.06023
[92]	validation_0-mae:2372.16170
[93]	validation_0-mae:2369.05916
[94]	validation_0-mae:2358.72960
[95]	validation_0-mae:2353.92058
[96]	validation_0-mae:2348.26983
[97]	validation_0-mae:2344.52582
[98]	validation_0-mae:2336.95442
[99]	validation_0-mae:2332.53598
[100]	validation_0-mae:2328.27452
[101]	validation_0-mae:2326.07960
[102]	validation_0-mae:2317.74733
[103]	validation_0-mae:2313.16490
[104]	validation_0-mae:2304.27011
[105]	validation_0-mae:2301.49200
[106]	validation_0-mae:2297.07360
[107]	validation_0-mae:2291.19964
[108]	validation_0-mae:2286.61712
[109]	validation_0-mae:2283.61693
[110]	validation_0-mae:2280.06816
[111]	validation_0-mae:2278.48435
[112]	validation_0-mae:2271.61087
[113]	validation_0-mae:2270.63008
[114]	validation_0-mae:2268.19071
[115]	validation_0-mae:2262.02769
[116]	validation_0-mae:2260.51654
[117]	validation_0-mae:2260.16267
[118]	validation_0-mae:2256.11517
[119]	validation_0-mae:2248.28892
[120]	validation_0-mae:2244.12117
[121]	validation_0-mae:2240.78092
[122]	validation_0-mae:2238.03566
[123]	validation_0-mae:2236.93066
[124]	validation_0-mae:2233.71282
[125]	validation_0-mae:2232.15588
[126]	validation_0-mae:2232.36923
[127]	validation_0-mae:2229.72543
[128]	validation_0-mae:2226.22518
[129]	validation_0-mae:2222.24583
[130]	validation_0-mae:2219.91006
[131]	validation_0-mae:2218.19046
[132]	validation_0-mae:2213.92047
[133]	validation_0-mae:2211.45895
[134]	validation_0-mae:2210.89025
[135]	validation_0-mae:2208.04065
[136]	validation_0-mae:2207.48614
[137]	validation_0-mae:2205.09558
[138]	validation_0-mae:2203.09765
[139]	validation_0-mae:2198.19581
[140]	validation_0-mae:2196.00040
[141]	validation_0-mae:2196.53159
[142]	validation_0-mae:2193.94769
[143]	validation_0-mae:2190.58643
[144]	validation_0-mae:2187.04348
[145]	validation_0-mae:2187.53215
[146]	validation_0-mae:2185.68588
[147]	validation_0-mae:2185.27036
[148]	validation_0-mae:2185.32891
[149]	validation_0-mae:2183.72392
[150]	validation_0-mae:2182.48830
[151]	validation_0-mae:2181.58358
[152]	validation_0-mae:2178.99926
[153]	validation_0-mae:2177.05682
[154]	validation_0-mae:2176.91620
[155]	validation_0-mae:2175.48541
[156]	validation_0-mae:2173.83995
[157]	validation_0-mae:2172.75050
[158]	validation_0-mae:2170.71936
[159]	validation_0-mae:2171.22203
[160]	validation_0-mae:2169.30085
[161]	validation_0-mae:2168.74063
[162]	validation_0-mae:2168.17269
[163]	validation_0-mae:2166.11523
[164]	validation_0-mae:2165.71618
[165]	validation_0-mae:2162.49497
[166]	validation_0-mae:2161.50831
[167]	validation_0-mae:2158.92048
[168]	validation_0-mae:2158.25369
[169]	validation_0-mae:2158.05867
[170]	validation_0-mae:2157.32924
[171]	validation_0-mae:2157.31744
[172]	validation_0-mae:2158.04895
[173]	validation_0-mae:2156.37269
[174]	validation_0-mae:2155.46308
[175]	validation_0-mae:2154.95677
[176]	validation_0-mae:2155.25825
[177]	validation_0-mae:2156.04787
[178]	validation_0-mae:2154.01396
[179]	validation_0-mae:2153.15788
[180]	validation_0-mae:2152.32248
[181]	validation_0-mae:2151.58876
[182]	validation_0-mae:2151.20989
[183]	validation_0-mae:2149.66653
[184]	validation_0-mae:2149.77467
[185]	validation_0-mae:2147.04674
[186]	validation_0-mae:2148.27853
[187]	validation_0-mae:2146.50210
[188]	validation_0-mae:2145.33212
[189]	validation_0-mae:2145.33058
[190]	validation_0-mae:2144.28361
[191]	validation_0-mae:2145.11170
[192]	validation_0-mae:2144.85594
[193]	validation_0-mae:2143.18423
[194]	validation_0-mae:2143.74528
[195]	validation_0-mae:2141.38686
[196]	validation_0-mae:2141.01119
[197]	validation_0-mae:2140.27663
[198]	validation_0-mae:2141.11382
[199]	validation_0-mae:2140.10528
[200]	validation_0-mae:2139.71533
[201]	validation_0-mae:2139.36507
[202]	validation_0-mae:2139.13414
[203]	validation_0-mae:2137.92951
[204]	validation_0-mae:2138.25855
[205]	validation_0-mae:2137.31013
[206]	validation_0-mae:2136.94016
[207]	validation_0-mae:2136.03533
[208]	validation_0-mae:2135.26357
[209]	validation_0-mae:2132.62975
[210]	validation_0-mae:2132.50418
[211]	validation_0-mae:2132.62305
[212]	validation_0-mae:2132.47616
[213]	validation_0-mae:2131.26355
[214]	validation_0-mae:2132.12694
[215]	validation_0-mae:2131.49517
[216]	validation_0-mae:2131.38449
[217]	validation_0-mae:2131.61062
[218]	validation_0-mae:2130.69973
[219]	validation_0-mae:2130.39873
[220]	validation_0-mae:2130.05079
[221]	validation_0-mae:2130.62348
[222]	validation_0-mae:2130.55454
[223]	validation_0-mae:2131.16363
[224]	validation_0-mae:2130.23895
[225]	validation_0-mae:2128.74379
[226]	validation_0-mae:2128.15404
[227]	validation_0-mae:2128.65858
[228]	validation_0-mae:2128.39059
[229]	validation_0-mae:2127.52032
[230]	validation_0-mae:2127.45946
[231]	validation_0-mae:2126.76472
[232]	validation_0-mae:2127.08664
[233]	validation_0-mae:2125.96563
[234]	validation_0-mae:2127.24977
[235]	validation_0-mae:2127.79452
[236]	validation_0-mae:2127.86277
[237]	validation_0-mae:2128.18512
[238]	validation_0-mae:2127.85504
[239]	validation_0-mae:2127.84135
[240]	validation_0-mae:2127.83731
[241]	validation_0-mae:2128.48261
[242]	validation_0-mae:2128.75887
[243]	validation_0-mae:2128.52007
[244]	validation_0-mae:2128.32307
[245]	validation_0-mae:2128.05319
[246]	validation_0-mae:2128.28121
[247]	validation_0-mae:2128.67491
[248]	validation_0-mae:2128.48287
[249]	validation_0-mae:2126.25019
[250]	validation_0-mae:2126.08619
[251]	validation_0-mae:2126.64678
[252]	validation_0-mae:2127.05858
[253]	validation_0-mae:2124.97913
[254]	validation_0-mae:2125.33586
[255]	validation_0-mae:2123.82830
[256]	validation_0-mae:2123.68727
[257]	validation_0-mae:2123.73470
[258]	validation_0-mae:2122.97707
[259]	validation_0-mae:2123.11239
[260]	validation_0-mae:2123.24724
[261]	validation_0-mae:2122.98658
[262]	validation_0-mae:2123.21025
[263]	validation_0-mae:2123.26686
[264]	validation_0-mae:2123.25816
[265]	validation_0-mae:2123.64383
[266]	validation_0-mae:2122.19901
[267]	validation_0-mae:2121.35326
[268]	validation_0-mae:2121.82325
[269]	validation_0-mae:2122.19641
[270]	validation_0-mae:2121.07372
[271]	validation_0-mae:2120.32481
[272]	validation_0-mae:2120.50184
[273]	validation_0-mae:2120.11775
[274]	validation_0-mae:2120.51332
[275]	validation_0-mae:2120.18039
[276]	validation_0-mae:2119.91711
[277]	validation_0-mae:2119.91458
[278]	validation_0-mae:2119.69978
[279]	validation_0-mae:2119.59811
[280]	validation_0-mae:2119.24869
[281]	validation_0-mae:2119.09168
[282]	validation_0-mae:2118.49787
[283]	validation_0-mae:2118.18165
[284]	validation_0-mae:2118.25844
[285]	validation_0-mae:2117.22261
[286]	validation_0-mae:2116.97447
[287]	validation_0-mae:2116.90571
[288]	validation_0-mae:2116.74024
[289]	validation_0-mae:2116.86616
[290]	validation_0-mae:2116.38809
[291]	validation_0-mae:2116.84548
[292]	validation_0-mae:2117.22785
[293]	validation_0-mae:2117.25955
[294]	validation_0-mae:2116.99394
[295]	validation_0-mae:2117.22138
[296]	validation_0-mae:2117.12579
[297]	validation_0-mae:2116.32742
[298]	validation_0-mae:2116.06830
[299]	validation_0-mae:2114.85390
[300]	validation_0-mae:2114.67355
[301]	validation_0-mae:2112.51724
[302]	validation_0-mae:2113.08786
[303]	validation_0-mae:2112.80055
[304]	validation_0-mae:2112.24330
[305]	validation_0-mae:2112.30722
[306]	validation_0-mae:2112.49720
[307]	validation_0-mae:2112.00914
[308]	validation_0-mae:2111.39265
[309]	validation_0-mae:2110.63067
[310]	validation_0-mae:2110.84934
[311]	validation_0-mae:2110.12584
[312]	validation_0-mae:2110.07047
[313]	validation_0-mae:2109.95179
[314]	validation_0-mae:2110.04893
[315]	validation_0-mae:2110.55074
[316]	validation_0-mae:2110.34548
[317]	validation_0-mae:2109.87929
[318]	validation_0-mae:2109.95977
[319]	validation_0-mae:2107.97913
[320]	validation_0-mae:2108.13634
[321]	validation_0-mae:2108.32892
[322]	validation_0-mae:2108.11494
[323]	validation_0-mae:2107.71299
[324]	validation_0-mae:2107.54749
[325]	validation_0-mae:2107.74168
[326]	validation_0-mae:2107.76227
[327]	validation_0-mae:2108.27850
[328]	validation_0-mae:2107.78112
[329]	validation_0-mae:2107.68977
[330]	validation_0-mae:2107.60971
[331]	validation_0-mae:2107.30450
[332]	validation_0-mae:2107.35097
[333]	validation_0-mae:2106.94344
[334]	validation_0-mae:2107.31660
[335]	validation_0-mae:2106.49460
[336]	validation_0-mae:2106.24560
[337]	validation_0-mae:2105.73721
[338]	validation_0-mae:2105.57733
[339]	validation_0-mae:2105.42625
[340]	validation_0-mae:2105.84042
[341]	validation_0-mae:2105.00103
[342]	validation_0-mae:2104.54809
[343]	validation_0-mae:2104.71418
[344]	validation_0-mae:2104.91982
[345]	validation_0-mae:2104.49274
[346]	validation_0-mae:2104.94848
[347]	validation_0-mae:2104.73279
[348]	validation_0-mae:2105.40652
[349]	validation_0-mae:2105.38678
[350]	validation_0-mae:2105.85151
[351]	validation_0-mae:2105.23002
[352]	validation_0-mae:2104.67559
[353]	validation_0-mae:2104.22645
[354]	validation_0-mae:2104.27627
[355]	validation_0-mae:2104.23483
[356]	validation_0-mae:2103.75544
[357]	validation_0-mae:2103.53779
[358]	validation_0-mae:2103.74223
[359]	validation_0-mae:2103.36608
[360]	validation_0-mae:2103.23006
[361]	validation_0-mae:2103.75181
[362]	validation_0-mae:2103.70749
[363]	validation_0-mae:2103.43392
[364]	validation_0-mae:2103.71801
[365]	validation_0-mae:2103.89658
[366]	validation_0-mae:2104.17423
[367]	validation_0-mae:2104.43912
[368]	validation_0-mae:2105.10865
[369]	validation_0-mae:2104.88171
[370]	validation_0-mae:2105.15157
[371]	validation_0-mae:2106.05582
[372]	validation_0-mae:2106.15623
[373]	validation_0-mae:2105.92756
[374]	validation_0-mae:2106.38342
[375]	validation_0-mae:2106.68683
[376]	validation_0-mae:2106.82986
[377]	validation_0-mae:2106.59605
[378]	validation_0-mae:2106.42377
[379]	validation_0-mae:2106.92451
[380]	validation_0-mae:2106.78489
[381]	validation_0-mae:2106.51004
[382]	validation_0-mae:2106.50484
[383]	validation_0-mae:2106.59518
[384]	validation_0-mae:2106.49045
[385]	validation_0-mae:2106.75076
[386]	validation_0-mae:2106.57689
[387]	validation_0-mae:2106.47654
[388]	validation_0-mae:2106.67586
[389]	validation_0-mae:2106.43703
[390]	validation_0-mae:2106.17424
[391]	validation_0-mae:2106.46239
[392]	validation_0-mae:2106.31559
[393]	validation_0-mae:2105.99657
[394]	validation_0-mae:2105.83376
[395]	validation_0-mae:2105.31878
[396]	validation_0-mae:2105.58190
[397]	validation_0-mae:2105.56674
[398]	validation_0-mae:2105.47065
[399]	validation_0-mae:2105.35898
[400]	validation_0-mae:2105.11179
[401]	validation_0-mae:2104.35119
[402]	validation_0-mae:2104.04298
[403]	validation_0-mae:2104.20350
[404]	validation_0-mae:2104.60055
[405]	validation_0-mae:2104.67793
[406]	validation_0-mae:2104.64877
[407]	validation_0-mae:2105.33135
[408]	validation_0-mae:2105.04034
[409]	validation_0-mae:2104.63146
[410]	validation_0-mae:2104.46629
[411]	validation_0-mae:2104.46605
[412]	validation_0-mae:2104.65230
[413]	validation_0-mae:2105.18745
[414]	validation_0-mae:2105.18191
[415]	validation_0-mae:2105.44672
[416]	validation_0-mae:2105.72880
[417]	validation_0-mae:2106.17404
[418]	validation_0-mae:2106.03214
[419]	validation_0-mae:2105.76473
[420]	validation_0-mae:2105.57583
[421]	validation_0-mae:2105.15315
[422]	validation_0-mae:2105.07736
[423]	validation_0-mae:2104.66936
[424]	validation_0-mae:2104.45773
[425]	validation_0-mae:2103.97197
[426]	validation_0-mae:2103.01642
[427]	validation_0-mae:2102.95020
[428]	validation_0-mae:2102.92018
[429]	validation_0-mae:2102.55814
[430]	validation_0-mae:2102.29829
[431]	validation_0-mae:2101.74162
[432]	validation_0-mae:2101.59329
[433]	validation_0-mae:2101.47414
[434]	validation_0-mae:2101.00496
[435]	validation_0-mae:2100.85467
[436]	validation_0-mae:2100.74809
[437]	validation_0-mae:2100.81730
[438]	validation_0-mae:2100.98262
[439]	validation_0-mae:2100.99334
[440]	validation_0-mae:2101.05811
[441]	validation_0-mae:2100.65223
[442]	validation_0-mae:2100.24110
[443]	validation_0-mae:2100.14084
[444]	validation_0-mae:2100.04522
[445]	validation_0-mae:2099.75698
[446]	validation_0-mae:2099.67181
[447]	validation_0-mae:2098.59209
[448]	validation_0-mae:2098.45973
[449]	validation_0-mae:2098.35642
[450]	validation_0-mae:2098.25624
[451]	validation_0-mae:2097.84008
[452]	validation_0-mae:2098.01281
[453]	validation_0-mae:2098.08676
[454]	validation_0-mae:2098.24427
[455]	validation_0-mae:2098.30354
[456]	validation_0-mae:2098.03785
[457]	validation_0-mae:2097.94983
[458]	validation_0-mae:2097.26254
[459]	validation_0-mae:2097.29217
[460]	validation_0-mae:2097.32066
[461]	validation_0-mae:2096.84766
[462]	validation_0-mae:2096.82584
[463]	validation_0-mae:2096.83632
[464]	validation_0-mae:2097.04822
[465]	validation_0-mae:2097.36126
[466]	validation_0-mae:2097.43173
[467]	validation_0-mae:2097.37344
[468]	validation_0-mae:2097.50988
[469]	validation_0-mae:2097.55523
[470]	validation_0-mae:2097.88057
[471]	validation_0-mae:2097.99046
[472]	validation_0-mae:2098.04862
[473]	validation_0-mae:2098.02166
[474]	validation_0-mae:2098.17699
[475]	validation_0-mae:2098.26416
[476]	validation_0-mae:2098.17899
[477]	validation_0-mae:2098.13922
[478]	validation_0-mae:2098.02036
[479]	validation_0-mae:2097.94177
[480]	validation_0-mae:2097.63486
[481]	validation_0-mae:2097.40511
[482]	validation_0-mae:2096.93480
[483]	validation_0-mae:2096.71498
[484]	validation_0-mae:2096.43531
[485]	validation_0-mae:2096.47379
[486]	validation_0-mae:2096.14268
[487]	validation_0-mae:2095.66704
[488]	validation_0-mae:2095.25700
[489]	validation_0-mae:2095.31588
[490]	validation_0-mae:2095.28068
[491]	validation_0-mae:2095.15167
[492]	validation_0-mae:2094.34632
[493]	validation_0-mae:2094.19095
[494]	validation_0-mae:2093.99117
[495]	validation_0-mae:2094.11251
[496]	validation_0-mae:2093.82669
[497]	validation_0-mae:2093.59808
[498]	validation_0-mae:2093.93691
[499]	validation_0-mae:2093.85936
[500]	validation_0-mae:2093.83783
[501]	validation_0-mae:2093.34970
[502]	validation_0-mae:2093.11082
[503]	validation_0-mae:2092.95545
[504]	validation_0-mae:2092.48437
[505]	validation_0-mae:2092.23687
[506]	validation_0-mae:2091.14618
[507]	validation_0-mae:2090.94429
[508]	validation_0-mae:2090.64908
[509]	validation_0-mae:2090.72609
[510]	validation_0-mae:2091.16277
[511]	validation_0-mae:2091.54912
[512]	validation_0-mae:2091.24760
[513]	validation_0-mae:2090.99254
[514]	validation_0-mae:2090.93945
[515]	validation_0-mae:2091.51521
[516]	validation_0-mae:2091.61454
[517]	validation_0-mae:2091.01577
[518]	validation_0-mae:2091.09669
[519]	validation_0-mae:2090.98478
[520]	validation_0-mae:2090.98272
[521]	validation_0-mae:2091.16105
[522]	validation_0-mae:2091.14099
[523]	validation_0-mae:2091.14413
[524]	validation_0-mae:2090.62009
[525]	validation_0-mae:2090.67183
[526]	validation_0-mae:2090.31023
[527]	validation_0-mae:2090.45108
[528]	validation_0-mae:2090.54546
[529]	validation_0-mae:2090.57471
[530]	validation_0-mae:2090.58362
[531]	validation_0-mae:2091.19508
[532]	validation_0-mae:2091.27829
[533]	validation_0-mae:2091.47606
[534]	validation_0-mae:2091.64836
[535]	validation_0-mae:2091.72099
[536]	validation_0-mae:2091.72286
[537]	validation_0-mae:2091.80153
[538]	validation_0-mae:2091.60908
[539]	validation_0-mae:2091.89816
[540]	validation_0-mae:2091.87468
[541]	validation_0-mae:2091.85377
[542]	validation_0-mae:2091.90008
[543]	validation_0-mae:2090.86825
[544]	validation_0-mae:2090.87191
[545]	validation_0-mae:2090.63880
[546]	validation_0-mae:2090.15291
[547]	validation_0-mae:2089.85108
[548]	validation_0-mae:2089.59273
[549]	validation_0-mae:2089.46915
[550]	validation_0-mae:2089.31346
[551]	validation_0-mae:2089.55686
[552]	validation_0-mae:2089.41897
[553]	validation_0-mae:2089.59540
[554]	validation_0-mae:2089.09606
[555]	validation_0-mae:2089.30904
[556]	validation_0-mae:2088.47092
[557]	validation_0-mae:2088.53733
[558]	validation_0-mae:2088.69123
[559]	validation_0-mae:2088.53509
[560]	validation_0-mae:2088.14223
[561]	validation_0-mae:2087.27307
[562]	validation_0-mae:2087.62124
[563]	validation_0-mae:2087.76229
[564]	validation_0-mae:2087.61698
[565]	validation_0-mae:2087.13747
[566]	validation_0-mae:2086.35092
[567]	validation_0-mae:2086.40101
[568]	validation_0-mae:2086.34726
[569]	validation_0-mae:2086.48162
[570]	validation_0-mae:2086.48016
[571]	validation_0-mae:2086.39184
[572]	validation_0-mae:2086.42128
[573]	validation_0-mae:2086.47717
[574]	validation_0-mae:2086.52903
[575]	validation_0-mae:2086.59435
[576]	validation_0-mae:2086.61415
[577]	validation_0-mae:2086.42413
[578]	validation_0-mae:2086.97475
[579]	validation_0-mae:2087.34310
[580]	validation_0-mae:2087.23487
[581]	validation_0-mae:2087.35386
[582]	validation_0-mae:2087.64933
[583]	validation_0-mae:2087.74646
[584]	validation_0-mae:2087.47927
[585]	validation_0-mae:2087.90903
[586]	validation_0-mae:2087.82647
[587]	validation_0-mae:2087.63169
[588]	validation_0-mae:2087.46117
[589]	validation_0-mae:2087.24628
[590]	validation_0-mae:2087.15504
[591]	validation_0-mae:2086.60213
[592]	validation_0-mae:2086.67541
[593]	validation_0-mae:2086.61940
[594]	validation_0-mae:2086.68691
[595]	validation_0-mae:2086.69939
[596]	validation_0-mae:2086.73607
[597]	validation_0-mae:2086.60314
[598]	validation_0-mae:2086.83605
[599]	validation_0-mae:2086.72200
[600]	validation_0-mae:2086.44018
[601]	validation_0-mae:2086.35696
[602]	validation_0-mae:2086.47661
[603]	validation_0-mae:2086.51446
[604]	validation_0-mae:2086.48281
[605]	validation_0-mae:2086.27952
[606]	validation_0-mae:2085.92225
[607]	validation_0-mae:2085.89326

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[37]	validation_0-mae:3449.66498
[38]	validation_0-mae:3393.51018
[39]	validation_0-mae:3343.84079
[40]	validation_0-mae:3297.05150
[41]	validation_0-mae:3258.25398
[42]	validation_0-mae:3220.46316
[43]	validation_0-mae:3172.06363
[44]	validation_0-mae:3136.01306
[45]	validation_0-mae:3101.85858
[46]	validation_0-mae:3069.65523
[47]	validation_0-mae:3037.75909
[48]	validation_0-mae:3015.54363
[49]	validation_0-mae:2981.41547
[50]	validation_0-mae:2952.97878
[51]	validation_0-mae:2929.01339
[52]	validation_0-mae:2906.91043
[53]	validation_0-mae:2880.56386
[54]	validation_0-mae:2864.77041
[55]	validation_0-mae:2837.62557
[56]	validation_0-mae:2810.15756
[57]	validation_0-mae:2791.55924
[58]	validation_0-mae:2778.16239
[59]	validation_0-mae:2753.26206
[60]	validation_0-mae:2738.26605
[61]	validation_0-mae:2720.12778
[62]	validation_0-mae:2706.56706
[63]	validation_0-mae:2696.85211
[64]	validation_0-mae:2685.38071
[65]	validation_0-mae:2656.51459
[66]	validation_0-mae:2636.14986
[67]	validation_0-mae:2617.67446
[68]	validation_0-mae:2610.63739
[69]	validation_0-mae:2600.61677
[70]	validation_0-mae:2585.70774
[71]	validation_0-mae:2571.14582
[72]	validation_0-mae:2560.85319
[73]	validation_0-mae:2549.62950
[74]	validation_0-mae:2539.81111
[75]	validation_0-mae:2530.27897
[76]	validation_0-mae:2520.33888
[77]	validation_0-mae:2509.67619
[78]	validation_0-mae:2503.35619
[79]	validation_0-mae:2491.41985
[80]	validation_0-mae:2486.54020
[81]	validation_0-mae:2478.48626
[82]	validation_0-mae:2468.51041
[83]	validation_0-mae:2463.41675
[84]	validation_0-mae:2459.65144
[85]	validation_0-mae:2454.94118
[86]	validation_0-mae:2450.14769
[87]	validation_0-mae:2438.13777
[88]	validation_0-mae:2426.13395
[89]	validation_0-mae:2419.60526
[90]	validation_0-mae:2413.05905
[91]	validation_0-mae:2410.63729
[92]	validation_0-mae:2406.69635
[93]	validation_0-mae:2402.85788
[94]	validation_0-mae:2397.93744
[95]	validation_0-mae:2384.10996
[96]	validation_0-mae:2377.92617
[97]	validation_0-mae:2375.62019
[98]	validation_0-mae:2368.75178
[99]	validation_0-mae:2364.09734
[100]	validation_0-mae:2358.19534
[101]	validation_0-mae:2358.00642
[102]	validation_0-mae:2357.42559
[103]	validation_0-mae:2351.52020
[104]	validation_0-mae:2348.73596
[105]	validation_0-mae:2345.11986
[106]	validation_0-mae:2345.68176
[107]	validation_0-mae:2337.73021
[108]	validation_0-mae:2331.45585
[109]	validation_0-mae:2327.00332
[110]	validation_0-mae:2321.01784
[111]	validation_0-mae:2320.73946
[112]	validation_0-mae:2312.66439
[113]	validation_0-mae:2311.20052
[114]	validation_0-mae:2308.04989
[115]	validation_0-mae:2302.90429
[116]	validation_0-mae:2300.45098
[117]	validation_0-mae:2296.27328
[118]	validation_0-mae:2289.71418
[119]	validation_0-mae:2288.00264
[120]	validation_0-mae:2283.85258
[121]	validation_0-mae:2281.39518
[122]	validation_0-mae:2279.76123
[123]	validation_0-mae:2276.56580
[124]	validation_0-mae:2269.54695
[125]	validation_0-mae:2266.14862
[126]	validation_0-mae:2264.37289
[127]	validation_0-mae:2262.52736
[128]	validation_0-mae:2259.72717
[129]	validation_0-mae:2253.11007
[130]	validation_0-mae:2248.99452
[131]	validation_0-mae:2247.38104
[132]	validation_0-mae:2241.75248
[133]	validation_0-mae:2240.59708
[134]	validation_0-mae:2240.16326
[135]	validation_0-mae:2237.03235
[136]	validation_0-mae:2235.58401
[137]	validation_0-mae:2235.68457
[138]	validation_0-mae:2233.65299
[139]	validation_0-mae:2232.29676
[140]	validation_0-mae:2228.90617
[141]	validation_0-mae:2226.87775
[142]	validation_0-mae:2226.51356
[143]	validation_0-mae:2224.50493
[144]	validation_0-mae:2224.24599
[145]	validation_0-mae:2222.00185
[146]	validation_0-mae:2220.61032
[147]	validation_0-mae:2218.41364
[148]	validation_0-mae:2217.61721
[149]	validation_0-mae:2215.77015
[150]	validation_0-mae:2210.44837
[151]	validation_0-mae:2209.64081
[152]	validation_0-mae:2207.57546
[153]	validation_0-mae:2208.46326
[154]	validation_0-mae:2208.75673
[155]	validation_0-mae:2206.37846
[156]	validation_0-mae:2205.88758
[157]	validation_0-mae:2203.27416
[158]	validation_0-mae:2202.30711
[159]	validation_0-mae:2199.59973
[160]	validation_0-mae:2198.09219
[161]	validation_0-mae:2195.55148
[162]	validation_0-mae:2196.20130
[163]	validation_0-mae:2195.62354
[164]	validation_0-mae:2195.13034
[165]	validation_0-mae:2193.97190
[166]	validation_0-mae:2193.36603
[167]	validation_0-mae:2192.32464
[168]	validation_0-mae:2191.08461
[169]	validation_0-mae:2188.51415
[170]	validation_0-mae:2188.36143
[171]	validation_0-mae:2187.37990
[172]	validation_0-mae:2186.52293
[173]	validation_0-mae:2185.39536
[174]	validation_0-mae:2185.30935
[175]	validation_0-mae:2183.40051
[176]	validation_0-mae:2182.00015
[177]	validation_0-mae:2180.57535
[178]	validation_0-mae:2178.92310
[179]	validation_0-mae:2176.31231
[180]	validation_0-mae:2175.78699
[181]	validation_0-mae:2175.43109
[182]	validation_0-mae:2176.03405
[183]	validation_0-mae:2173.16116
[184]	validation_0-mae:2173.61272
[185]	validation_0-mae:2174.33293
[186]	validation_0-mae:2173.87847
[187]	validation_0-mae:2174.38479
[188]	validation_0-mae:2174.80296
[189]	validation_0-mae:2175.53564
[190]	validation_0-mae:2173.81910
[191]	validation_0-mae:2172.87847
[192]	validation_0-mae:2171.37050
[193]	validation_0-mae:2170.60358
[194]	validation_0-mae:2169.75561
[195]	validation_0-mae:2168.09570
[196]	validation_0-mae:2167.73190
[197]	validation_0-mae:2167.12660
[198]	validation_0-mae:2165.78980
[199]	validation_0-mae:2165.00857
[200]	validation_0-mae:2163.94602
[201]	validation_0-mae:2160.21356
[202]	validation_0-mae:2159.11027
[203]	validation_0-mae:2159.53511
[204]	validation_0-mae:2157.95124
[205]	validation_0-mae:2156.36754
[206]	validation_0-mae:2155.78910
[207]	validation_0-mae:2156.15977
[208]	validation_0-mae:2156.48511
[209]	validation_0-mae:2153.26896
[210]	validation_0-mae:2150.98495
[211]	validation_0-mae:2151.75505
[212]	validation_0-mae:2152.11192
[213]	validation_0-mae:2151.35001
[214]	validation_0-mae:2150.52802
[215]	validation_0-mae:2149.71713
[216]	validation_0-mae:2149.61262
[217]	validation_0-mae:2149.62637
[218]	validation_0-mae:2149.02788
[219]	validation_0-mae:2148.00626
[220]	validation_0-mae:2147.03613
[221]	validation_0-mae:2146.64179
[222]	validation_0-mae:2146.82788
[223]	validation_0-mae:2146.50251
[224]	validation_0-mae:2146.37233
[225]	validation_0-mae:2146.29332
[226]	validation_0-mae:2146.62698
[227]	validation_0-mae:2146.80127
[228]	validation_0-mae:2146.78853
[229]	validation_0-mae:2145.78468
[230]	validation_0-mae:2147.27557
[231]	validation_0-mae:2147.03441
[232]	validation_0-mae:2147.67976
[233]	validation_0-mae:2147.28422
[234]	validation_0-mae:2145.63705
[235]	validation_0-mae:2143.58455
[236]	validation_0-mae:2143.20698
[237]	validation_0-mae:2142.94494
[238]	validation_0-mae:2143.54990
[239]	validation_0-mae:2144.14221
[240]	validation_0-mae:2142.86613
[241]	validation_0-mae:2143.40490
[242]	validation_0-mae:2144.18241
[243]	validation_0-mae:2143.40652
[244]	validation_0-mae:2142.78613
[245]	validation_0-mae:2142.27426
[246]	validation_0-mae:2142.43057
[247]	validation_0-mae:2142.70976
[248]	validation_0-mae:2142.39343
[249]	validation_0-mae:2143.17519
[250]	validation_0-mae:2141.11778
[251]	validation_0-mae:2141.47622
[252]	validation_0-mae:2140.85522
[253]	validation_0-mae:2139.91623
[254]	validation_0-mae:2139.10377
[255]	validation_0-mae:2139.18944
[256]	validation_0-mae:2137.81730
[257]	validation_0-mae:2138.15198
[258]	validation_0-mae:2138.63242
[259]	validation_0-mae:2139.29928
[260]	validation_0-mae:2139.32682
[261]	validation_0-mae:2139.67515
[262]	validation_0-mae:2138.14585
[263]	validation_0-mae:2138.23607
[264]	validation_0-mae:2137.73165
[265]	validation_0-mae:2136.60137
[266]	validation_0-mae:2135.88404
[267]	validation_0-mae:2135.70197
[268]	validation_0-mae:2134.95949
[269]	validation_0-mae:2134.45761
[270]	validation_0-mae:2133.23298
[271]	validation_0-mae:2131.75525
[272]	validation_0-mae:2131.86002
[273]	validation_0-mae:2131.11488
[274]	validation_0-mae:2130.71588
[275]	validation_0-mae:2130.54202
[276]	validation_0-mae:2130.62779
[277]	validation_0-mae:2130.35956
[278]	validation_0-mae:2129.75102
[279]	validation_0-mae:2130.15722
[280]	validation_0-mae:2130.47662
[281]	validation_0-mae:2130.90874
[282]	validation_0-mae:2131.04094
[283]	validation_0-mae:2130.59823
[284]	validation_0-mae:2129.86842
[285]	validation_0-mae:2130.20638
[286]	validation_0-mae:2129.80486
[287]	validation_0-mae:2129.37174
[288]	validation_0-mae:2129.56815
[289]	validation_0-mae:2130.27003
[290]	validation_0-mae:2130.52521
[291]	validation_0-mae:2130.76687
[292]	validation_0-mae:2130.66610
[293]	validation_0-mae:2130.75704
[294]	validation_0-mae:2130.46752
[295]	validation_0-mae:2129.94183
[296]	validation_0-mae:2129.97516
[297]	validation_0-mae:2129.42562
[298]	validation_0-mae:2129.75474
[299]	validation_0-mae:2129.28708
[300]	validation_0-mae:2127.72221
[301]	validation_0-mae:2126.69596
[302]	validation_0-mae:2127.00309
[303]	validation_0-mae:2127.31655
[304]	validation_0-mae:2128.49306
[305]	validation_0-mae:2128.43036
[306]	validation_0-mae:2127.85738
[307]	validation_0-mae:2128.06993
[308]	validation_0-mae:2127.68576
[309]	validation_0-mae:2127.84682
[310]	validation_0-mae:2126.35652
[311]	validation_0-mae:2125.22741
[312]	validation_0-mae:2125.03855
[313]	validation_0-mae:2125.01451
[314]	validation_0-mae:2124.18603
[315]	validation_0-mae:2124.06617
[316]	validation_0-mae:2123.84819
[317]	validation_0-mae:2123.44374
[318]	validation_0-mae:2123.29962
[319]	validation_0-mae:2123.98291
[320]	validation_0-mae:2124.26634
[321]	validation_0-mae:2124.60657
[322]	validation_0-mae:2124.19585
[323]	validation_0-mae:2123.33707
[324]	validation_0-mae:2123.33675
[325]	validation_0-mae:2123.92057
[326]	validation_0-mae:2123.65474
[327]	validation_0-mae:2123.68186
[328]	validation_0-mae:2123.40196
[329]	validation_0-mae:2122.34060
[330]	validation_0-mae:2121.59784
[331]	validation_0-mae:2120.70294
[332]	validation_0-mae:2120.45437
[333]	validation_0-mae:2118.77827
[334]	validation_0-mae:2118.75912
[335]	validation_0-mae:2118.59840
[336]	validation_0-mae:2118.85929
[337]	validation_0-mae:2117.67748
[338]	validation_0-mae:2117.36113
[339]	validation_0-mae:2116.88354
[340]	validation_0-mae:2117.12774
[341]	validation_0-mae:2117.25159
[342]	validation_0-mae:2116.63889
[343]	validation_0-mae:2116.46794
[344]	validation_0-mae:2116.35338
[345]	validation_0-mae:2116.21155
[346]	validation_0-mae:2114.77042
[347]	validation_0-mae:2114.88209
[348]	validation_0-mae:2115.40482
[349]	validation_0-mae:2115.37830
[350]	validation_0-mae:2115.59309
[351]	validation_0-mae:2115.23343
[352]	validation_0-mae:2115.30574
[353]	validation_0-mae:2115.41325
[354]	validation_0-mae:2116.41163
[355]	validation_0-mae:2117.09517
[356]	validation_0-mae:2117.25102
[357]	validation_0-mae:2117.17065
[358]	validation_0-mae:2117.26548
[359]	validation_0-mae:2117.45633
[360]	validation_0-mae:2117.22424
[361]	validation_0-mae:2117.06198
[362]	validation_0-mae:2116.80029
[363]	validation_0-mae:2117.25327
[364]	validation_0-mae:2116.92515
[365]	validation_0-mae:2116.72447
[366]	validation_0-mae:2116.73873
[367]	validation_0-mae:2116.91569
[368]	validation_0-mae:2116.66923
[369]	validation_0-mae:2115.61845
[370]	validation_0-mae:2115.01171
[371]	validation_0-mae:2114.65682
[372]	validation_0-mae:2114.85300
[373]	validation_0-mae:2114.34143
[374]	validation_0-mae:2114.61973
[375]	validation_0-mae:2114.15330
[376]	validation_0-mae:2113.88573
[377]	validation_0-mae:2114.00726
[378]	validation_0-mae:2113.44491
[379]	validation_0-mae:2113.30684
[380]	validation_0-mae:2112.16696
[381]	validation_0-mae:2111.88613
[382]	validation_0-mae:2111.63854
[383]	validation_0-mae:2110.43095
[384]	validation_0-mae:2110.12717
[385]	validation_0-mae:2109.65185
[386]	validation_0-mae:2109.42916
[387]	validation_0-mae:2109.45804
[388]	validation_0-mae:2109.37595
[389]	validation_0-mae:2109.36581
[390]	validation_0-mae:2109.08141
[391]	validation_0-mae:2109.41581
[392]	validation_0-mae:2110.00632
[393]	validation_0-mae:2109.84886
[394]	validation_0-mae:2110.31430
[395]	validation_0-mae:2110.02246
[396]	validation_0-mae:2109.78833
[397]	validation_0-mae:2110.07091
[398]	validation_0-mae:2110.12508
[399]	validation_0-mae:2110.19842
[400]	validation_0-mae:2110.07395
[401]	validation_0-mae:2109.89592
[402]	validation_0-mae:2110.02556
[403]	validation_0-mae:2109.37461
[404]	validation_0-mae:2109.76674
[405]	validation_0-mae:2109.54789
[406]	validation_0-mae:2109.43183
[407]	validation_0-mae:2109.43468
[408]	validation_0-mae:2109.30011
[409]	validation_0-mae:2109.30826
[410]	validation_0-mae:2109.48597
[411]	validation_0-mae:2109.60540
[412]	validation_0-mae:2109.91473
[413]	validation_0-mae:2109.89044
[414]	validation_0-mae:2109.54198
[415]	validation_0-mae:2109.55687
[416]	validation_0-mae:2109.35816
[417]	validation_0-mae:2108.94159
[418]	validation_0-mae:2108.50706
[419]	validation_0-mae:2108.69422
[420]	validation_0-mae:2108.33210
[421]	validation_0-mae:2108.15962
[422]	validation_0-mae:2108.36023
[423]	validation_0-mae:2108.31362
[424]	validation_0-mae:2107.86684
[425]	validation_0-mae:2107.66138
[426]	validation_0-mae:2107.64267
[427]	validation_0-mae:2107.13572
[428]	validation_0-mae:2106.93762
[429]	validation_0-mae:2105.96500
[430]	validation_0-mae:2105.73627
[431]	validation_0-mae:2105.86240
[432]	validation_0-mae:2105.82081
[433]	validation_0-mae:2105.94674
[434]	validation_0-mae:2105.96272
[435]	validation_0-mae:2106.53588
[436]	validation_0-mae:2106.51753
[437]	validation_0-mae:2106.94457
[438]	validation_0-mae:2106.62236
[439]	validation_0-mae:2106.09305
[440]	validation_0-mae:2105.82730
[441]	validation_0-mae:2106.23680
[442]	validation_0-mae:2106.43309
[443]	validation_0-mae:2106.21786
[444]	validation_0-mae:2105.41578
[445]	validation_0-mae:2104.94334
[446]	validation_0-mae:2104.93878
[447]	validation_0-mae:2104.76934
[448]	validation_0-mae:2104.64522
[449]	validation_0-mae:2104.45120
[450]	validation_0-mae:2104.20147
[451]	validation_0-mae:2104.04968
[452]	validation_0-mae:2102.91142
[453]	validation_0-mae:2102.78839
[454]	validation_0-mae:2102.98144
[455]	validation_0-mae:2103.38005
[456]	validation_0-mae:2103.40406
[457]	validation_0-mae:2103.68079
[458]	validation_0-mae:2103.66326
[459]	validation_0-mae:2103.55360
[460]	validation_0-mae:2103.09350
[461]	validation_0-mae:2103.13733
[462]	validation_0-mae:2102.87536
[463]	validation_0-mae:2103.12389
[464]	validation_0-mae:2102.65521
[465]	validation_0-mae:2102.70796
[466]	validation_0-mae:2102.84427
[467]	validation_0-mae:2103.14269
[468]	validation_0-mae:2103.26787
[469]	validation_0-mae:2103.01242
[470]	validation_0-mae:2102.58713
[471]	validation_0-mae:2102.83070
[472]	validation_0-mae:2102.29791
[473]	validation_0-mae:2102.24286
[474]	validation_0-mae:2101.81544
[475]	validation_0-mae:2101.70825
[476]	validation_0-mae:2101.61746
[477]	validation_0-mae:2101.19077
[478]	validation_0-mae:2100.84383
[479]	validation_0-mae:2100.51983
[480]	validation_0-mae:2100.21322
[481]	validation_0-mae:2100.04265
[482]	validation_0-mae:2099.76707
[483]	validation_0-mae:2099.52272
[484]	validation_0-mae:2099.75925
[485]	validation_0-mae:2099.68703
[486]	validation_0-mae:2100.27123
[487]	validation_0-mae:2100.30277
[488]	validation_0-mae:2100.00584
[489]	validation_0-mae:2099.77087
[490]	validation_0-mae:2099.58758
[491]	validation_0-mae:2099.50267
[492]	validation_0-mae:2099.19753
[493]	validation_0-mae:2099.14830
[494]	validation_0-mae:2099.28115
[495]	validation_0-mae:2098.72319
[496]	validation_0-mae:2099.00690
[497]	validation_0-mae:2098.85243
[498]	validation_0-mae:2098.19460
[499]	validation_0-mae:2098.20119
[500]	validation_0-mae:2098.02691
[501]	validation_0-mae:2098.11794
[502]	validation_0-mae:2098.10537
[503]	validation_0-mae:2097.94446
[504]	validation_0-mae:2097.92125
[505]	validation_0-mae:2097.37057
[506]	validation_0-mae:2097.11752
[507]	validation_0-mae:2097.24684
[508]	validation_0-mae:2097.34091
[509]	validation_0-mae:2097.37608
[510]	validation_0-mae:2097.48191
[511]	validation_0-mae:2097.29772
[512]	validation_0-mae:2097.67395
[513]	validation_0-mae:2097.78850
[514]	validation_0-mae:2097.94169
[515]	validation_0-mae:2098.26167
[516]	validation_0-mae:2098.15897
[517]	validation_0-mae:2097.76680
[518]	validation_0-mae:2097.86558
[519]	validation_0-mae:2097.79029
[520]	validation_0-mae:2097.73841
[521]	validation_0-mae:2097.13494
[522]	validation_0-mae:2097.51100
[523]	validation_0-mae:2097.54092
[524]	validation_0-mae:2097.66646
[525]	validation_0-mae:2097.41900
[526]	validation_0-mae:2097.44564
[527]	validation_0-mae:2097.18672
[528]	validation_0-mae:2096.89260
[529]	validation_0-mae:2096.90306
[530]	validation_0-mae:2097.09261
[531]	validation_0-mae:2096.55629
[532]	validation_0-mae:2096.57302
[533]	validation_0-mae:2095.99666
[534]	validation_0-mae:2095.77212
[535]	validation_0-mae:2095.84777
[536]	validation_0-mae:2096.14052
[537]	validation_0-mae:2095.88986
[538]	validation_0-mae:2095.76718
[539]	validation_0-mae:2095.92294
[540]	validation_0-mae:2095.70770
[541]	validation_0-mae:2095.96444
[542]	validation_0-mae:2096.09429
[543]	validation_0-mae:2096.02823
[544]	validation_0-mae:2095.68235
[545]	validation_0-mae:2094.93153
[546]	validation_0-mae:2095.16105
[547]	validation_0-mae:2094.88853
[548]	validation_0-mae:2094.28478
[549]	validation_0-mae:2094.18425
[550]	validation_0-mae:2094.04296
[551]	validation_0-mae:2094.22306
[552]	validation_0-mae:2094.25387
[553]	validation_0-mae:2094.46586
[554]	validation_0-mae:2094.59574
[555]	validation_0-mae:2094.73441
[556]	validation_0-mae:2094.63800
[557]	validation_0-mae:2094.59258
[558]	validation_0-mae:2094.44594
[559]	validation_0-mae:2094.58523
[560]	validation_0-mae:2094.70552
[561]	validation_0-mae:2094.78730
[562]	validation_0-mae:2094.75512
[563]	validation_0-mae:2094.57008
[564]	validation_0-mae:2094.69572
[565]	validation_0-mae:2094.64316
[566]	validation_0-mae:2094.30191
[567]	validation_0-mae:2094.44974
[568]	validation_0-mae:2094.41403
[569]	validation_0-mae:2094.22317
[570]	validation_0-mae:2094.25641
[571]	validation_0-mae:2094.17716
[572]	validation_0-mae:2093.95114
[573]	validation_0-mae:2093.86953
[574]	validation_0-mae:2094.03013
[575]	validation_0-mae:2094.22977
[576]	validation_0-mae:2093.96360
[577]	validation_0-mae:2093.96733
[578]	validation_0-mae:2094.03553
[579]	validation_0-mae:2094.07885
[0]	validation_0-mae:12386.62553
[1]	validation_0-mae:11606.57981
[2]	validation_0-mae:10899.04036
[3]	validation_0-mae:10269.41911
[4]	validation_0-mae:9707.75529
[5]	validation_0-mae:9198.94560
[6]	validation_0-mae:8728.74041
[7]	validation_0-mae:8333.11212
[8]	validation_0-mae:7931.33652
[9]	validation_0-mae:7573.60777
[10]	validation_0-mae:7259.40687
[11]	validation_0-mae:6936.47104
[12]	validation_0-mae:6641.76905
[13]	validation_0-mae:6391.42468
[14]	validation_0-mae:6141.07922
[15]	validation_0-mae:5885.95041
[16]	validation_0-mae:5676.15621
[17]	validation_0-mae:5467.83059
[18]	validation_0-mae:5263.00437
[19]	validation_0-mae:5080.70253
[20]	validation_0-mae:4936.25629
[21]	validation_0-mae:4770.42184
[22]	validation_0-mae:4640.12590
[23]	validation_0-mae:4497.47028
[24]	validation_0-mae:4374.73784
[25]	validation_0-mae:4260.98485
[26]	validation_0-mae:4151.83620
[27]	validation_0-mae:4035.13200
[28]	validation_0-mae:3942.54601
[29]	validation_0-mae:3853.73650
[30]	validation_0-mae:3771.60267
[31]	validation_0-mae:3695.03898
[32]	validation_0-mae:3622.67337
[33]	validation_0-mae:3564.19685
[34]	validation_0-mae:3498.58185
[35]	validation_0-mae:3438.96888
[36]	validation_0-mae:3387.35280
[37]	validation_0-mae:3338.17379

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[38]	validation_0-mae:3294.64042
[39]	validation_0-mae:3246.54143
[40]	validation_0-mae:3210.59298
[41]	validation_0-mae:3170.80573
[42]	validation_0-mae:3133.66408
[43]	validation_0-mae:3086.21885
[44]	validation_0-mae:3056.78982
[45]	validation_0-mae:3032.65516
[46]	validation_0-mae:3000.84753
[47]	validation_0-mae:2978.37509
[48]	validation_0-mae:2955.29770
[49]	validation_0-mae:2928.49064
[50]	validation_0-mae:2909.31706
[51]	validation_0-mae:2893.70897
[52]	validation_0-mae:2866.12648
[53]	validation_0-mae:2843.25755
[54]	validation_0-mae:2833.17487
[55]	validation_0-mae:2820.23175
[56]	validation_0-mae:2810.93225
[57]	validation_0-mae:2799.14437
[58]	validation_0-mae:2784.82397
[59]	validation_0-mae:2756.85945
[60]	validation_0-mae:2747.09446
[61]	validation_0-mae:2723.42334
[62]	validation_0-mae:2713.00209
[63]	validation_0-mae:2691.09179
[64]	validation_0-mae:2659.46449
[65]	validation_0-mae:2652.73310
[66]	validation_0-mae:2630.77934
[67]	validation_0-mae:2623.99886
[68]	validation_0-mae:2610.92791
[69]	validation_0-mae:2602.76002
[70]	validation_0-mae:2582.14221
[71]	validation_0-mae:2562.86341
[72]	validation_0-mae:2545.91083
[73]	validation_0-mae:2538.00285
[74]	validation_0-mae:2535.46812
[75]	validation_0-mae:2529.61216
[76]	validation_0-mae:2522.78321
[77]	validation_0-mae:2518.20939
[78]	validation_0-mae:2501.11483
[79]	validation_0-mae:2495.21773
[80]	validation_0-mae:2482.71288
[81]	validation_0-mae:2476.70406
[82]	validation_0-mae:2473.64750
[83]	validation_0-mae:2469.00783
[84]	validation_0-mae:2457.72214
[85]	validation_0-mae:2449.49274
[86]	validation_0-mae:2439.14719
[87]	validation_0-mae:2437.66175
[88]	validation_0-mae:2431.84699
[89]	validation_0-mae:2425.30571
[90]	validation_0-mae:2418.64914
[91]	validation_0-mae:2411.32805
[92]	validation_0-mae:2404.59045
[93]	validation_0-mae:2399.24852
[94]	validation_0-mae:2384.95033
[95]	validation_0-mae:2378.39701
[96]	validation_0-mae:2372.10507
[97]	validation_0-mae:2359.54662
[98]	validation_0-mae:2352.73877
[99]	validation_0-mae:2348.80339
[100]	validation_0-mae:2345.32582
[101]	validation_0-mae:2343.28790
[102]	validation_0-mae:2339.58901
[103]	validation_0-mae:2331.94357
[104]	validation_0-mae:2330.44946
[105]	validation_0-mae:2328.36640
[106]	validation_0-mae:2326.12405
[107]	validation_0-mae:2322.35330
[108]	validation_0-mae:2316.89603
[109]	validation_0-mae:2313.97963
[110]	validation_0-mae:2315.42822
[111]	validation_0-mae:2304.98783
[112]	validation_0-mae:2300.53167
[113]	validation_0-mae:2297.63528
[114]	validation_0-mae:2295.65699
[115]	validation_0-mae:2294.55889
[116]	validation_0-mae:2290.66119
[117]	validation_0-mae:2289.52596
[118]	validation_0-mae:2287.96163
[119]	validation_0-mae:2283.98698
[120]	validation_0-mae:2281.78061
[121]	validation_0-mae:2277.73082
[122]	validation_0-mae:2273.70353
[123]	validation_0-mae:2272.74426
[124]	validation_0-mae:2270.49009
[125]	validation_0-mae:2269.74022
[126]	validation_0-mae:2271.35784
[127]	validation_0-mae:2267.98187
[128]	validation_0-mae:2263.81862
[129]	validation_0-mae:2260.40254
[130]	validation_0-mae:2259.06922
[131]	validation_0-mae:2255.06288
[132]	validation_0-mae:2255.07815
[133]	validation_0-mae:2251.70889
[134]	validation_0-mae:2250.01580
[135]	validation_0-mae:2250.43267
[136]	validation_0-mae:2249.07107
[137]	validation_0-mae:2245.75601
[138]	validation_0-mae:2245.45889
[139]	validation_0-mae:2244.38109
[140]	validation_0-mae:2243.22569
[141]	validation_0-mae:2242.33230
[142]	validation_0-mae:2239.98698
[143]	validation_0-mae:2239.49149
[144]	validation_0-mae:2239.55630
[145]	validation_0-mae:2238.03231
[146]	validation_0-mae:2236.90685
[147]	validation_0-mae:2237.26142
[148]	validation_0-mae:2235.58004
[149]	validation_0-mae:2235.53447
[150]	validation_0-mae:2232.71555
[151]	validation_0-mae:2231.49025
[152]	validation_0-mae:2229.15159
[153]	validation_0-mae:2226.34713
[154]	validation_0-mae:2225.25136
[155]	validation_0-mae:2223.77303
[156]	validation_0-mae:2223.26610
[157]	validation_0-mae:2222.32829
[158]	validation_0-mae:2220.07977
[159]	validation_0-mae:2218.73668
[160]	validation_0-mae:2218.75803
[161]	validation_0-mae:2218.55783
[162]	validation_0-mae:2217.56696
[163]	validation_0-mae:2215.42372
[164]	validation_0-mae:2217.73637
[165]	validation_0-mae:2217.54598
[166]	validation_0-mae:2216.72235
[167]	validation_0-mae:2214.67285
[168]	validation_0-mae:2215.66970
[169]	validation_0-mae:2210.94683
[170]	validation_0-mae:2210.37159
[171]	validation_0-mae:2208.65441
[172]	validation_0-mae:2207.83074
[173]	validation_0-mae:2208.11639
[174]	validation_0-mae:2206.69149
[175]	validation_0-mae:2207.29882
[176]	validation_0-mae:2206.33172
[177]	validation_0-mae:2207.43433
[178]	validation_0-mae:2208.08471
[0]	validation_0-mae:12432.82174
[1]	validation_0-mae:11687.01603
[2]	validation_0-mae:11011.86440
[3]	validation_0-mae:10413.09942
[4]	validation_0-mae:9877.80101
[5]	validation_0-mae:9384.62300
[6]	validation_0-mae:8956.46275
[7]	validation_0-mae:8555.60171
[8]	validation_0-mae:8202.50468
[9]	validation_0-mae:7841.66885
[10]	validation_0-mae:7549.17091

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[0]	validation_0-mae:12444.17507
[1]	validation_0-mae:11720.22549
[2]	validation_0-mae:11047.84193
[3]	validation_0-mae:10430.88308
[4]	validation_0-mae:9887.53988
[5]	validation_0-mae:9395.05008
[6]	validation_0-mae:8942.92044
[7]	validation_0-mae:8527.00250
[8]	validation_0-mae:8149.95279
[9]	validation_0-mae:7798.11370
[10]	validation_0-mae:7479.99822
[11]	validation_0-mae:7189.62107
[12]	validation_0-mae:6921.72027
[13]	validation_0-mae:6664.96344
[14]	validation_0-mae:6400.65691
[15]	validation_0-mae:6172.51199
[16]	validation_0-mae:5967.46360
[17]	validation_0-mae:5736.55369
[18]	validation_0-mae:5529.77047
[19]	validation_0-mae:5366.99088
[20]	validation_0-mae:5205.32872
[21]	validation_0-mae:5046.14716
[22]	validation_0-mae:4891.40663
[23]	validation_0-mae:4735.26165
[24]	validation_0-mae:4597.82302
[25]	validation_0-mae:4484.90429
[26]	validation_0-mae:4383.26782
[27]	validation_0-mae:4271.53624
[28]	validation_0-mae:4173.54177
[29]	validation_0-mae:4074.11762
[30]	validation_0-mae:3991.10818
[31]	validation_0-mae:3912.36656
[32]	validation_0-mae:3820.44474
[33]	validation_0-mae:3747.90315
[34]	validation_0-mae:3684.16285
[35]	validation_0-mae:3623.93412
[36]	validation_0-mae:3557.61552
[37]	validation_0-mae:3492.89656
[38]	validation_0-mae:3434.75145
[39]	validation_0-mae:3392.56383
[40]	validation_0-mae:3331.68793
[41]	validation_0-mae:3283.43395
[42]	validation_0-mae:3249.72587
[43]	validation_0-mae:3210.26112
[44]	validation_0-mae:3158.03467
[45]	validation_0-mae:3123.56673
[46]	validation_0-mae:3087.78333
[47]	validation_0-mae:3059.59673
[48]	validation_0-mae:3034.68506
[49]	validation_0-mae:3010.87423
[50]	validation_0-mae:2981.97358
[51]	validation_0-mae:2944.24756
[52]	validation_0-mae:2908.00446
[53]	validation_0-mae:2885.70742
[54]	validation_0-mae:2868.44782
[55]	validation_0-mae:2847.56380
[56]	validation_0-mae:2822.28981
[57]	validation_0-mae:2802.67703
[58]	validation_0-mae:2773.09810
[59]	validation_0-mae:2755.63089
[60]	validation_0-mae:2741.69401
[61]	validation_0-mae:2725.50118
[62]	validation_0-mae:2710.42045
[63]	validation_0-mae:2684.94426
[64]	validation_0-mae:2663.63450
[65]	validation_0-mae:2653.16788
[66]	validation_0-mae:2642.76770
[67]	validation_0-mae:2629.73840
[68]	validation_0-mae:2617.10584
[69]	validation_0-mae:2606.20106
[70]	validation_0-mae:2586.12927
[71]	validation_0-mae:2580.59153
[72]	validation_0-mae:2564.41898
[73]	validation_0-mae:2547.46605
[74]	validation_0-mae:2538.67607
[75]	validation_0-mae:2535.12229
[76]	validation_0-mae:2530.11438
[77]	validation_0-mae:2524.22972
[78]	validation_0-mae:2512.56817
[79]	validation_0-mae:2500.37261
[80]	validation_0-mae:2492.96694
[81]	validation_0-mae:2487.66170
[82]	validation_0-mae:2477.17753
[83]	validation_0-mae:2465.46913
[84]	validation_0-mae:2457.55635
[85]	validation_0-mae:2451.37613
[86]	validation_0-mae:2444.56855
[87]	validation_0-mae:2438.21971
[88]	validation_0-mae:2430.74218
[89]	validation_0-mae:2423.86563
[90]	validation_0-mae:2413.75928
[91]	validation_0-mae:2409.86921
[92]	validation_0-mae:2403.18612
[93]	validation_0-mae:2396.97014
[94]	validation_0-mae:2388.13083
[95]	validation_0-mae:2381.27743
[96]	validation_0-mae:2376.16581
[97]	validation_0-mae:2370.26338
[98]	validation_0-mae:2363.65819
[99]	validation_0-mae:2357.04752
[100]	validation_0-mae:2349.26678
[101]	validation_0-mae:2343.51231
[102]	validation_0-mae:2338.29094
[103]	validation_0-mae:2328.57089
[104]	validation_0-mae:2324.42673
[105]	validation_0-mae:2321.15904
[106]	validation_0-mae:2316.73443
[107]	validation_0-mae:2312.50984
[108]	validation_0-mae:2309.05812
[109]	validation_0-mae:2307.35031
[110]	validation_0-mae:2302.02530
[111]	validation_0-mae:2298.45379
[112]	validation_0-mae:2293.51693
[113]	validation_0-mae:2290.80925
[114]	validation_0-mae:2286.04090
[115]	validation_0-mae:2282.70207
[116]	validation_0-mae:2277.81535
[117]	validation_0-mae:2274.34133
[118]	validation_0-mae:2271.97702
[119]	validation_0-mae:2267.20254
[120]	validation_0-mae:2263.78753
[121]	validation_0-mae:2261.72650
[122]	validation_0-mae:2260.50173
[123]	validation_0-mae:2257.58453
[124]	validation_0-mae:2252.19775
[125]	validation_0-mae:2246.27316
[126]	validation_0-mae:2242.49318
[127]	validation_0-mae:2240.66971
[128]	validation_0-mae:2238.20223
[129]	validation_0-mae:2237.67890
[130]	validation_0-mae:2236.76644
[131]	validation_0-mae:2234.79634
[132]	validation_0-mae:2230.08372
[133]	validation_0-mae:2226.00929
[134]	validation_0-mae:2224.68197
[135]	validation_0-mae:2221.78081
[136]	validation_0-mae:2219.26252
[137]	validation_0-mae:2216.59615
[138]	validation_0-mae:2214.37536
[139]	validation_0-mae:2212.32374
[140]	validation_0-mae:2209.42224
[141]	validation_0-mae:2207.71912
[142]	validation_0-mae:2205.73969
[143]	validation_0-mae:2203.32024
[144]	validation_0-mae:2201.29951
[145]	validation_0-mae:2199.73538
[146]	validation_0-mae:2196.71149
[147]	validation_0-mae:2196.42882
[148]	validation_0-mae:2193.48504
[149]	validation_0-mae:2192.37095
[150]	validation_0-mae:2190.81815
[151]	validation_0-mae:2188.71373
[152]	validation_0-mae:2187.39108
[153]	validation_0-mae:2185.10831
[154]	validation_0-mae:2181.72524
[155]	validation_0-mae:2180.60157
[156]	validation_0-mae:2179.18080
[157]	validation_0-mae:2178.00614
[158]	validation_0-mae:2175.67757
[159]	validation_0-mae:2173.74892
[160]	validation_0-mae:2172.40962
[161]	validation_0-mae:2171.55573
[162]	validation_0-mae:2169.81130
[163]	validation_0-mae:2166.49700
[164]	validation_0-mae:2166.48983
[165]	validation_0-mae:2164.96733
[166]	validation_0-mae:2162.75029
[167]	validation_0-mae:2162.50497
[168]	validation_0-mae:2161.32445
[169]	validation_0-mae:2159.50204
[170]	validation_0-mae:2158.31677
[171]	validation_0-mae:2159.01138
[172]	validation_0-mae:2157.59473
[173]	validation_0-mae:2156.80737
[174]	validation_0-mae:2155.89931
[175]	validation_0-mae:2154.13248
[176]	validation_0-mae:2154.93141
[177]	validation_0-mae:2153.14362
[178]	validation_0-mae:2153.12470
[179]	validation_0-mae:2153.29449
[180]	validation_0-mae:2151.70238
[181]	validation_0-mae:2151.81426
[182]	validation_0-mae:2151.15250
[183]	validation_0-mae:2150.48995
[184]	validation_0-mae:2149.81556
[185]	validation_0-mae:2149.05025
[186]	validation_0-mae:2147.19812
[187]	validation_0-mae:2147.33548
[188]	validation_0-mae:2145.91775
[189]	validation_0-mae:2142.99154
[190]	validation_0-mae:2141.03395
[191]	validation_0-mae:2140.35291
[192]	validation_0-mae:2139.55611
[193]	validation_0-mae:2137.66559
[194]	validation_0-mae:2137.10312
[195]	validation_0-mae:2136.07613
[196]	validation_0-mae:2134.63914
[197]	validation_0-mae:2134.66208
[198]	validation_0-mae:2132.29286
[199]	validation_0-mae:2130.25267
[200]	validation_0-mae:2128.79383
[201]	validation_0-mae:2126.07108
[202]	validation_0-mae:2124.50317
[203]	validation_0-mae:2124.09416
[204]	validation_0-mae:2122.59622
[205]	validation_0-mae:2121.18001
[206]	validation_0-mae:2120.86144
[207]	validation_0-mae:2119.09725
[208]	validation_0-mae:2118.08674
[209]	validation_0-mae:2117.71842
[210]	validation_0-mae:2118.05789
[211]	validation_0-mae:2118.55784
[212]	validation_0-mae:2117.87303
[213]	validation_0-mae:2117.58609
[214]	validation_0-mae:2116.10311
[215]	validation_0-mae:2115.24770
[216]	validation_0-mae:2114.92830
[217]	validation_0-mae:2114.58175
[218]	validation_0-mae:2115.20903
[219]	validation_0-mae:2115.14973
[220]	validation_0-mae:2115.15859
[221]	validation_0-mae:2114.00182
[222]	validation_0-mae:2113.66938
[223]	validation_0-mae:2112.56048
[224]	validation_0-mae:2112.44883
[225]	validation_0-mae:2112.89267
[226]	validation_0-mae:2113.45452
[227]	validation_0-mae:2113.75606
[228]	validation_0-mae:2113.31284
[229]	validation_0-mae:2111.66841
[230]	validation_0-mae:2111.11968
[231]	validation_0-mae:2109.58191
[232]	validation_0-mae:2109.46363
[233]	validation_0-mae:2108.88181
[234]	validation_0-mae:2108.01795
[235]	validation_0-mae:2106.87150
[236]	validation_0-mae:2105.77455
[237]	validation_0-mae:2105.06856
[238]	validation_0-mae:2105.72363
[239]	validation_0-mae:2105.50074
[240]	validation_0-mae:2105.08071
[241]	validation_0-mae:2105.54165
[242]	validation_0-mae:2105.57195
[243]	validation_0-mae:2105.63702
[244]	validation_0-mae:2105.82824
[245]	validation_0-mae:2105.38956
[246]	validation_0-mae:2105.53516
[247]	validation_0-mae:2104.93966
[248]	validation_0-mae:2105.01646
[249]	validation_0-mae:2104.11970
[250]	validation_0-mae:2104.12088
[251]	validation_0-mae:2102.48824
[252]	validation_0-mae:2101.70269
[253]	validation_0-mae:2101.05932
[254]	validation_0-mae:2101.61719
[255]	validation_0-mae:2099.09967
[256]	validation_0-mae:2097.10084
[257]	validation_0-mae:2096.97326
[258]	validation_0-mae:2095.37688
[259]	validation_0-mae:2096.02119
[260]	validation_0-mae:2095.59499
[261]	validation_0-mae:2096.23277
[262]	validation_0-mae:2095.39911
[263]	validation_0-mae:2095.30321
[264]	validation_0-mae:2095.74676
[265]	validation_0-mae:2096.04911
[266]	validation_0-mae:2094.91665
[267]	validation_0-mae:2094.74759
[268]	validation_0-mae:2094.64086
[269]	validation_0-mae:2093.72006
[270]	validation_0-mae:2092.97319
[271]	validation_0-mae:2093.12332
[272]	validation_0-mae:2093.17062
[273]	validation_0-mae:2092.45499
[274]	validation_0-mae:2092.74048
[275]	validation_0-mae:2092.55750
[276]	validation_0-mae:2091.98006
[277]	validation_0-mae:2091.90138
[278]	validation_0-mae:2091.58016
[279]	validation_0-mae:2091.54363
[280]	validation_0-mae:2092.51596
[281]	validation_0-mae:2091.57005
[282]	validation_0-mae:2091.45323
[283]	validation_0-mae:2092.28711
[284]	validation_0-mae:2092.17532
[285]	validation_0-mae:2092.17884
[286]	validation_0-mae:2092.46424
[287]	validation_0-mae:2092.07378
[288]	validation_0-mae:2092.41779
[289]	validation_0-mae:2088.84887
[290]	validation_0-mae:2088.62653
[291]	validation_0-mae:2089.58000
[292]	validation_0-mae:2090.04250
[293]	validation_0-mae:2090.25757
[294]	validation_0-mae:2089.50335
[295]	validation_0-mae:2090.10013
[296]	validation_0-mae:2090.72989
[297]	validation_0-mae:2090.71317
[298]	validation_0-mae:2088.49689
[299]	validation_0-mae:2088.65839
[300]	validation_0-mae:2088.56031
[301]	validation_0-mae:2087.45499
[302]	validation_0-mae:2088.23561
[303]	validation_0-mae:2088.07862
[304]	validation_0-mae:2087.86565
[305]	validation_0-mae:2086.78286
[306]	validation_0-mae:2086.74597
[307]	validation_0-mae:2085.29978
[308]	validation_0-mae:2084.34355
[309]	validation_0-mae:2084.39509
[310]	validation_0-mae:2084.83613
[311]	validation_0-mae:2084.27322
[312]	validation_0-mae:2083.41027
[313]	validation_0-mae:2083.47035
[314]	validation_0-mae:2082.28585
[315]	validation_0-mae:2082.07118
[316]	validation_0-mae:2082.41964
[317]	validation_0-mae:2081.42107
[318]	validation_0-mae:2080.94413
[319]	validation_0-mae:2079.33815
[320]	validation_0-mae:2079.66330
[321]	validation_0-mae:2079.65334
[322]	validation_0-mae:2079.72445
[323]	validation_0-mae:2079.59790
[324]	validation_0-mae:2079.69856
[325]	validation_0-mae:2080.30756
[326]	validation_0-mae:2079.57588
[327]	validation_0-mae:2078.95166
[328]	validation_0-mae:2078.38708
[329]	validation_0-mae:2078.67501
[330]	validation_0-mae:2078.37093
[331]	validation_0-mae:2078.65650
[332]	validation_0-mae:2078.65072
[333]	validation_0-mae:2078.34512
[334]	validation_0-mae:2078.20192
[335]	validation_0-mae:2077.77344
[336]	validation_0-mae:2077.17476
[337]	validation_0-mae:2076.03174
[338]	validation_0-mae:2074.79541
[339]	validation_0-mae:2074.61188
[340]	validation_0-mae:2074.61207
[341]	validation_0-mae:2074.55806
[342]	validation_0-mae:2074.07656
[343]	validation_0-mae:2073.04642
[344]	validation_0-mae:2072.57195
[345]	validation_0-mae:2072.15901
[346]	validation_0-mae:2072.12968
[347]	validation_0-mae:2071.31588
[348]	validation_0-mae:2071.38184
[349]	validation_0-mae:2071.01651
[350]	validation_0-mae:2070.78001
[351]	validation_0-mae:2070.47658
[352]	validation_0-mae:2070.32498
[353]	validation_0-mae:2069.42395
[354]	validation_0-mae:2069.43568
[355]	validation_0-mae:2069.12273
[356]	validation_0-mae:2068.59153
[357]	validation_0-mae:2069.01751
[358]	validation_0-mae:2068.16474
[359]	validation_0-mae:2066.86003
[360]	validation_0-mae:2066.39315
[361]	validation_0-mae:2066.46472
[362]	validation_0-mae:2065.84637
[363]	validation_0-mae:2065.73100
[364]	validation_0-mae:2065.50394
[365]	validation_0-mae:2065.61279
[366]	validation_0-mae:2064.89765
[367]	validation_0-mae:2065.00065
[368]	validation_0-mae:2064.31823
[369]	validation_0-mae:2064.33564
[370]	validation_0-mae:2064.37972
[371]	validation_0-mae:2063.69670
[372]	validation_0-mae:2063.92212
[373]	validation_0-mae:2064.21314
[374]	validation_0-mae:2063.17805
[375]	validation_0-mae:2063.60520
[376]	validation_0-mae:2063.66716
[377]	validation_0-mae:2063.76580
[378]	validation_0-mae:2063.79894
[379]	validation_0-mae:2063.52659
[380]	validation_0-mae:2064.02635
[381]	validation_0-mae:2063.16731
[382]	validation_0-mae:2062.74346
[383]	validation_0-mae:2062.60975
[384]	validation_0-mae:2062.56896
[385]	validation_0-mae:2062.45631
[386]	validation_0-mae:2061.76348
[387]	validation_0-mae:2061.17755
[388]	validation_0-mae:2060.98112
[389]	validation_0-mae:2060.62053
[390]	validation_0-mae:2060.99834
[391]	validation_0-mae:2060.74430
[392]	validation_0-mae:2060.80236
[393]	validation_0-mae:2060.25322
[394]	validation_0-mae:2060.05564
[395]	validation_0-mae:2059.31966
[396]	validation_0-mae:2059.43718
[397]	validation_0-mae:2059.46871
[398]	validation_0-mae:2059.34975
[399]	validation_0-mae:2059.73277
[400]	validation_0-mae:2059.04712
[401]	validation_0-mae:2059.31345
[402]	validation_0-mae:2059.84131
[403]	validation_0-mae:2059.88523
[404]	validation_0-mae:2059.39689
[405]	validation_0-mae:2059.59524
[406]	validation_0-mae:2059.24486
[407]	validation_0-mae:2059.24358
[408]	validation_0-mae:2058.88805
[409]	validation_0-mae:2058.45513
[410]	validation_0-mae:2058.54753
[411]	validation_0-mae:2058.05118
[412]	validation_0-mae:2056.69845
[413]	validation_0-mae:2056.45561
[414]	validation_0-mae:2055.71818
[415]	validation_0-mae:2056.02494
[416]	validation_0-mae:2055.97265
[417]	validation_0-mae:2055.29653
[418]	validation_0-mae:2055.00915
[419]	validation_0-mae:2054.82782
[420]	validation_0-mae:2054.74781
[421]	validation_0-mae:2054.61220
[422]	validation_0-mae:2054.64394
[423]	validation_0-mae:2054.20419
[424]	validation_0-mae:2054.55948
[425]	validation_0-mae:2054.36247
[426]	validation_0-mae:2054.64477
[427]	validation_0-mae:2054.59962
[428]	validation_0-mae:2054.66247
[429]	validation_0-mae:2054.12767
[430]	validation_0-mae:2053.80113
[431]	validation_0-mae:2053.74948
[432]	validation_0-mae:2052.98264
[433]	validation_0-mae:2052.78656
[434]	validation_0-mae:2053.47658
[435]	validation_0-mae:2053.54761
[436]	validation_0-mae:2053.59997
[437]	validation_0-mae:2053.86713
[438]	validation_0-mae:2053.93693
[439]	validation_0-mae:2053.79667
[440]	validation_0-mae:2054.32751
[441]	validation_0-mae:2054.62955
[442]	validation_0-mae:2054.79942
[443]	validation_0-mae:2054.56951
[444]	validation_0-mae:2054.07424
[445]	validation_0-mae:2053.74486
[446]	validation_0-mae:2054.00868
[447]	validation_0-mae:2053.80595
[448]	validation_0-mae:2054.05489
[449]	validation_0-mae:2054.05015
[450]	validation_0-mae:2054.17212
[451]	validation_0-mae:2054.35630
[452]	validation_0-mae:2054.49091
[453]	validation_0-mae:2053.72764
[454]	validation_0-mae:2054.01367
[455]	validation_0-mae:2054.56446
[456]	validation_0-mae:2054.68900
[457]	validation_0-mae:2054.12103
[458]	validation_0-mae:2053.38841
[459]	validation_0-mae:2053.71880
[460]	validation_0-mae:2053.11980
[461]	validation_0-mae:2052.93899
[462]	validation_0-mae:2053.48215
[463]	validation_0-mae:2053.85629
[464]	validation_0-mae:2053.87132
[465]	validation_0-mae:2053.38412
[466]	validation_0-mae:2053.09516
[467]	validation_0-mae:2052.45502
[468]	validation_0-mae:2052.57317
[469]	validation_0-mae:2052.36746
[470]	validation_0-mae:2052.31370
[471]	validation_0-mae:2052.03769
[472]	validation_0-mae:2051.88449
[473]	validation_0-mae:2051.92847
[474]	validation_0-mae:2051.14059
[475]	validation_0-mae:2051.05464
[476]	validation_0-mae:2050.60541
[477]	validation_0-mae:2050.77420
[478]	validation_0-mae:2050.65450
[479]	validation_0-mae:2050.78453
[480]	validation_0-mae:2051.18480
[481]	validation_0-mae:2051.44282
[482]	validation_0-mae:2051.68079
[483]	validation_0-mae:2051.68475
[484]	validation_0-mae:2051.31145
[485]	validation_0-mae:2051.65977
[486]	validation_0-mae:2051.12029
[487]	validation_0-mae:2050.70683
[488]	validation_0-mae:2049.90869
[489]	validation_0-mae:2049.82389
[490]	validation_0-mae:2049.09964
[491]	validation_0-mae:2049.13772
[492]	validation_0-mae:2049.25667
[493]	validation_0-mae:2049.05547
[494]	validation_0-mae:2048.96381
[495]	validation_0-mae:2048.70547
[496]	validation_0-mae:2048.94702
[497]	validation_0-mae:2049.17728
[498]	validation_0-mae:2049.18530
[499]	validation_0-mae:2049.16849
[500]	validation_0-mae:2048.33299
[501]	validation_0-mae:2048.32153
[502]	validation_0-mae:2048.56297
[503]	validation_0-mae:2048.77826
[504]	validation_0-mae:2048.95759
[505]	validation_0-mae:2047.85375
[506]	validation_0-mae:2047.80950
[507]	validation_0-mae:2047.70943
[508]	validation_0-mae:2047.26616
[509]	validation_0-mae:2047.29154
[510]	validation_0-mae:2047.56718
[511]	validation_0-mae:2047.62387
[512]	validation_0-mae:2047.38215
[513]	validation_0-mae:2047.39471
[514]	validation_0-mae:2047.23739
[515]	validation_0-mae:2047.67175
[516]	validation_0-mae:2047.69256
[517]	validation_0-mae:2047.75480
[518]	validation_0-mae:2047.75542
[519]	validation_0-mae:2047.68654
[520]	validation_0-mae:2047.63564
[521]	validation_0-mae:2047.08654
[522]	validation_0-mae:2046.89891
[523]	validation_0-mae:2046.57126
[524]	validation_0-mae:2046.71385
[525]	validation_0-mae:2046.73155
[526]	validation_0-mae:2046.41043
[527]	validation_0-mae:2046.29857
[528]	validation_0-mae:2046.57278
[529]	validation_0-mae:2046.56114
[530]	validation_0-mae:2046.17405
[531]	validation_0-mae:2046.54569
[532]	validation_0-mae:2046.16337
[533]	validation_0-mae:2046.37118
[534]	validation_0-mae:2046.25116
[535]	validation_0-mae:2046.02095
[536]	validation_0-mae:2045.69760
[537]	validation_0-mae:2044.69974
[538]	validation_0-mae:2044.73531
[539]	validation_0-mae:2044.28147
[540]	validation_0-mae:2044.15373
[541]	validation_0-mae:2044.11050
[542]	validation_0-mae:2044.42762
[543]	validation_0-mae:2044.22172
[544]	validation_0-mae:2044.36305
[545]	validation_0-mae:2044.56174
[546]	validation_0-mae:2044.56988
[547]	validation_0-mae:2044.31915
[548]	validation_0-mae:2044.06480
[549]	validation_0-mae:2043.67421
[550]	validation_0-mae:2043.94397
[551]	validation_0-mae:2043.93025
[552]	validation_0-mae:2044.04697
[553]	validation_0-mae:2044.20954
[554]	validation_0-mae:2044.08382
[555]	validation_0-mae:2043.59101
[556]	validation_0-mae:2043.29624
[557]	validation_0-mae:2043.21366
[558]	validation_0-mae:2043.32642
[559]	validation_0-mae:2043.12848
[560]	validation_0-mae:2043.09876
[561]	validation_0-mae:2043.35370
[562]	validation_0-mae:2043.17624
[563]	validation_0-mae:2042.59423
[564]	validation_0-mae:2042.76113
[565]	validation_0-mae:2042.93390
[566]	validation_0-mae:2043.07986
[567]	validation_0-mae:2043.16149
[568]	validation_0-mae:2043.32689
[569]	validation_0-mae:2043.20402
[570]	validation_0-mae:2043.10091
[571]	validation_0-mae:2043.20105
[572]	validation_0-mae:2042.76760
[573]	validation_0-mae:2042.38554
[574]	validation_0-mae:2042.36525
[575]	validation_0-mae:2042.48057
[576]	validation_0-mae:2042.33432
[577]	validation_0-mae:2042.35552
[578]	validation_0-mae:2042.64964
[579]	validation_0-mae:2042.63610
[580]	validation_0-mae:2042.43847
[581]	validation_0-mae:2041.97462
[582]	validation_0-mae:2042.39758
[583]	validation_0-mae:2042.22408
[584]	validation_0-mae:2042.39193
[585]	validation_0-mae:2042.32758
[586]	validation_0-mae:2041.89646
[587]	validation_0-mae:2042.07187
[588]	validation_0-mae:2042.09293
[589]	validation_0-mae:2041.91982
[590]	validation_0-mae:2041.76987

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[0]	validation_0-mae:12463.40460
[1]	validation_0-mae:11729.21746
[2]	validation_0-mae:11077.20791
[3]	validation_0-mae:10498.36667
[4]	validation_0-mae:9982.44513
[5]	validation_0-mae:9523.50788
[6]	validation_0-mae:9089.99075
[7]	validation_0-mae:8728.80349
[8]	validation_0-mae:8397.86720
[9]	validation_0-mae:8085.10285
[10]	validation_0-mae:7813.67305
[0]	validation_0-mae:12422.89785
[1]	validation_0-mae:11686.06575
[2]	validation_0-mae:11002.06235
[3]	validation_0-mae:10377.24364
[4]	validation_0-mae:9842.22905
[5]	validation_0-mae:9346.64583
[6]	validation_0-mae:8909.12591
[7]	validation_0-mae:8509.96218
[8]	validation_0-mae:8151.21131
[9]	validation_0-mae:7819.70251
[10]	validation_0-mae:7485.41008
[11]	validation_0-mae:7206.28496
[12]	validation_0-mae:6933.13713
[13]	validation_0-mae:6648.78697
[14]	validation_0-mae:6381.45904
[15]	validation_0-mae:6149.03212
[16]	validation_0-mae:5948.48099
[17]	validation_0-mae:5753.28032
[18]	validation_0-mae:5554.78747
[19]	validation_0-mae:5374.81345
[20]	validation_0-mae:5206.98543
[21]	validation_0-mae:5027.97701
[22]	validation_0-mae:4879.52028
[23]	validation_0-mae:4738.33049
[24]	validation_0-mae:4606.28842
[25]	validation_0-mae:4475.58886
[26]	validation_0-mae:4362.84062
[27]	validation_0-mae:4250.10416
[28]	validation_0-mae:4141.86708
[29]	validation_0-mae:4036.18253
[30]	validation_0-mae:3950.16629
[31]	validation_0-mae:3864.59322
[32]	validation_0-mae:3782.90324
[33]	validation_0-mae:3716.46528
[34]	validation_0-mae:3645.31649
[35]	validation_0-mae:3584.95888
[36]	validation_0-mae:3521.07382
[37]	validation_0-mae:3476.38470
[38]	validation_0-mae:3418.76841
[39]	validation_0-mae:3355.61726

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[40]	validation_0-mae:3307.14207
[41]	validation_0-mae:3261.80976
[42]	validation_0-mae:3224.27664
[43]	validation_0-mae:3185.74965
[44]	validation_0-mae:3152.52679
[45]	validation_0-mae:3125.04857
[46]	validation_0-mae:3099.48869
[47]	validation_0-mae:3072.11094
[48]	validation_0-mae:3025.67501
[49]	validation_0-mae:3002.90080
[50]	validation_0-mae:2979.32352
[51]	validation_0-mae:2947.31518
[52]	validation_0-mae:2911.21287
[53]	validation_0-mae:2890.29957
[54]	validation_0-mae:2864.54584
[55]	validation_0-mae:2850.61074
[56]	validation_0-mae:2828.06350
[57]	validation_0-mae:2807.43041
[58]	validation_0-mae:2793.31423
[59]	validation_0-mae:2774.46165
[60]	validation_0-mae:2757.20480
[61]	validation_0-mae:2743.11760
[62]	validation_0-mae:2732.54813
[63]	validation_0-mae:2720.40352
[64]	validation_0-mae:2706.90031
[0]	validation_0-mae:12456.47833
[1]	validation_0-mae:11732.40682
[2]	validation_0-mae:11080.47573
[3]	validation_0-mae:10451.95816
[4]	validation_0-mae:9912.46979
[5]	validation_0-mae:9408.86041
[6]	validation_0-mae:8962.02467
[7]	validation_0-mae:8573.16306
[8]	validation_0-mae:8200.43206
[9]	validation_0-mae:7853.08498
[10]	validation_0-mae:7527.56451
[11]	validation_0-mae:7235.82732

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[0]	validation_0-mae:12405.32016
[1]	validation_0-mae:11651.32729
[2]	validation_0-mae:10951.70482
[3]	validation_0-mae:10295.00787
[4]	validation_0-mae:9742.66555
[5]	validation_0-mae:9233.94801
[6]	validation_0-mae:8767.44603
[7]	validation_0-mae:8364.31275
[8]	validation_0-mae:7985.16709
[9]	validation_0-mae:7622.91378
[10]	validation_0-mae:7297.67763
[11]	validation_0-mae:7005.55129
[12]	validation_0-mae:6714.98780
[13]	validation_0-mae:6481.59296
[14]	validation_0-mae:6236.67759
[15]	validation_0-mae:5987.06561
[16]	validation_0-mae:5784.99533
[17]	validation_0-mae:5554.09333
[18]	validation_0-mae:5365.66491
[19]	validation_0-mae:5188.08904
[20]	validation_0-mae:5027.00751
[21]	validation_0-mae:4866.85006
[22]	validation_0-mae:4710.52310
[23]	validation_0-mae:4595.80399
[24]	validation_0-mae:4466.12274
[25]	validation_0-mae:4343.33066
[26]	validation_0-mae:4233.29567
[27]	validation_0-mae:4135.86991
[28]	validation_0-mae:4055.81187
[29]	validation_0-mae:3960.61864
[30]	validation_0-mae:3866.86662
[31]	validation_0-mae:3782.11417
[32]	validation_0-mae:3699.99691
[33]	validation_0-mae:3639.95805
[34]	validation_0-mae:3573.28946
[35]	validation_0-mae:3516.13115
[36]	validation_0-mae:3450.06991
[37]	validation_0-mae:3382.74545
[38]	validation_0-mae:3329.59355
[39]	validation_0-mae:3282.39756
[40]	validation_0-mae:3240.55204
[41]	validation_0-mae:3205.76528
[42]	validation_0-mae:3146.90664
[43]	validation_0-mae:3107.41269
[44]	validation_0-mae:3074.36374
[45]	validation_0-mae:3032.87648
[46]	validation_0-mae:2998.89844
[47]	validation_0-mae:2972.70411
[48]	validation_0-mae:2941.42796
[49]	validation_0-mae:2909.09352
[50]	validation_0-mae:2887.53644
[51]	validation_0-mae:2867.55510
[52]	validation_0-mae:2844.65065
[53]	validation_0-mae:2823.84529
[54]	validation_0-mae:2805.23760
[55]	validation_0-mae:2785.98726
[56]	validation_0-mae:2778.36378
[57]	validation_0-mae:2759.78867
[58]	validation_0-mae:2741.59023
[59]	validation_0-mae:2730.59584
[60]	validation_0-mae:2716.13347
[61]	validation_0-mae:2700.99475
[62]	validation_0-mae:2676.85938
[63]	validation_0-mae:2661.77520
[64]	validation_0-mae:2638.29303
[65]	validation_0-mae:2627.32579
[66]	validation_0-mae:2604.33336
[67]	validation_0-mae:2598.62703
[68]	validation_0-mae:2588.48362
[69]	validation_0-mae:2573.14773
[70]	validation_0-mae:2565.17819
[71]	validation_0-mae:2556.58077
[72]	validation_0-mae:2549.89347
[73]	validation_0-mae:2543.79757
[74]	validation_0-mae:2539.14210
[75]	validation_0-mae:2521.33056
[76]	validation_0-mae:2507.55693
[77]	validation_0-mae:2497.87645
[78]	validation_0-mae:2485.27239
[79]	validation_0-mae:2469.99100
[80]	validation_0-mae:2462.74342
[81]	validation_0-mae:2456.31047
[82]	validation_0-mae:2451.10037
[83]	validation_0-mae:2445.57070
[84]	validation_0-mae:2441.13188
[85]	validation_0-mae:2436.31350
[86]	validation_0-mae:2431.70428
[87]	validation_0-mae:2422.51982
[88]	validation_0-mae:2413.68262
[89]	validation_0-mae:2405.90090
[90]	validation_0-mae:2400.65840
[91]	validation_0-mae:2393.83214
[92]	validation_0-mae:2387.81609
[93]	validation_0-mae:2384.61855
[94]	validation_0-mae:2373.27165
[95]	validation_0-mae:2369.65966
[96]	validation_0-mae:2365.43927
[97]	validation_0-mae:2360.89221
[98]	validation_0-mae:2354.78539
[99]	validation_0-mae:2353.44698
[100]	validation_0-mae:2347.83357
[101]	validation_0-mae:2345.03146
[102]	validation_0-mae:2337.70534
[103]	validation_0-mae:2333.42585
[104]	validation_0-mae:2325.42266
[105]	validation_0-mae:2321.41925
[106]	validation_0-mae:2317.12634
[107]	validation_0-mae:2310.77634
[108]	validation_0-mae:2307.42743
[109]	validation_0-mae:2301.75681
[110]	validation_0-mae:2297.46541
[111]	validation_0-mae:2294.50404
[112]	validation_0-mae:2291.99624
[113]	validation_0-mae:2284.61348
[114]	validation_0-mae:2283.00969
[115]	validation_0-mae:2284.11637
[116]	validation_0-mae:2284.45706
[117]	validation_0-mae:2284.96975
[118]	validation_0-mae:2276.88347
[119]	validation_0-mae:2272.96634
[120]	validation_0-mae:2269.27986
[121]	validation_0-mae:2265.07179
[122]	validation_0-mae:2261.41996
[123]	validation_0-mae:2257.00718
[124]	validation_0-mae:2255.35289
[125]	validation_0-mae:2251.49454
[126]	validation_0-mae:2250.22821
[127]	validation_0-mae:2247.34859
[128]	validation_0-mae:2244.43103
[129]	validation_0-mae:2242.97339
[130]	validation_0-mae:2243.30770
[131]	validation_0-mae:2239.23951
[132]	validation_0-mae:2237.24878
[133]	validation_0-mae:2236.81389
[134]	validation_0-mae:2234.23818
[135]	validation_0-mae:2230.50223
[136]	validation_0-mae:2229.31799
[137]	validation_0-mae:2228.20216
[138]	validation_0-mae:2226.75906
[139]	validation_0-mae:2224.69556
[140]	validation_0-mae:2222.33998
[141]	validation_0-mae:2220.94532
[142]	validation_0-mae:2216.80417
[143]	validation_0-mae:2214.27696
[144]	validation_0-mae:2212.40364
[145]	validation_0-mae:2212.28307
[146]	validation_0-mae:2210.95352
[147]	validation_0-mae:2210.24448
[148]	validation_0-mae:2210.28903
[149]	validation_0-mae:2209.95062
[150]	validation_0-mae:2206.16917
[151]	validation_0-mae:2205.52181
[152]	validation_0-mae:2205.65210
[153]	validation_0-mae:2204.56686
[154]	validation_0-mae:2203.80316
[155]	validation_0-mae:2204.48026
[156]	validation_0-mae:2203.56340
[157]	validation_0-mae:2202.88441
[158]	validation_0-mae:2203.33367
[159]	validation_0-mae:2202.28216
[160]	validation_0-mae:2200.64471
[161]	validation_0-mae:2199.41212
[162]	validation_0-mae:2196.72468
[163]	validation_0-mae:2195.64470
[164]	validation_0-mae:2195.28069
[165]	validation_0-mae:2192.50501
[166]	validation_0-mae:2192.19018
[167]	validation_0-mae:2190.51240
[168]	validation_0-mae:2188.29831
[169]	validation_0-mae:2188.50134
[170]	validation_0-mae:2186.61046
[171]	validation_0-mae:2185.60723
[172]	validation_0-mae:2182.82205
[173]	validation_0-mae:2181.83402
[174]	validation_0-mae:2179.33659
[175]	validation_0-mae:2180.07812
[176]	validation_0-mae:2179.70577
[177]	validation_0-mae:2179.91114
[178]	validation_0-mae:2179.64319
[179]	validation_0-mae:2178.70406
[180]	validation_0-mae:2178.56867
[181]	validation_0-mae:2177.45490
[182]	validation_0-mae:2176.73130
[183]	validation_0-mae:2175.94348
[184]	validation_0-mae:2174.16347
[185]	validation_0-mae:2172.69842
[186]	validation_0-mae:2170.05226
[187]	validation_0-mae:2170.08843
[188]	validation_0-mae:2169.93218
[189]	validation_0-mae:2169.15120
[190]	validation_0-mae:2168.63090
[191]	validation_0-mae:2166.94013
[192]	validation_0-mae:2165.52375
[193]	validation_0-mae:2165.31038
[194]	validation_0-mae:2164.88123
[195]	validation_0-mae:2163.28237
[196]	validation_0-mae:2163.20733
[197]	validation_0-mae:2162.66629
[198]	validation_0-mae:2162.38668
[199]	validation_0-mae:2161.88645
[200]	validation_0-mae:2161.17807
[201]	validation_0-mae:2160.70372
[202]	validation_0-mae:2161.67645
[203]	validation_0-mae:2159.77807
[204]	validation_0-mae:2159.42705
[205]	validation_0-mae:2158.73597
[206]	validation_0-mae:2158.84295
[207]	validation_0-mae:2156.99018
[208]	validation_0-mae:2157.22850
[209]	validation_0-mae:2155.28022
[210]	validation_0-mae:2154.33648
[211]	validation_0-mae:2153.84608
[212]	validation_0-mae:2154.64238
[213]	validation_0-mae:2154.17281
[214]	validation_0-mae:2151.05278
[215]	validation_0-mae:2149.45008
[216]	validation_0-mae:2148.14277
[217]	validation_0-mae:2148.05965
[218]	validation_0-mae:2147.59996
[219]	validation_0-mae:2146.02434
[220]	validation_0-mae:2145.40856
[221]	validation_0-mae:2143.27734
[222]	validation_0-mae:2141.42884
[223]	validation_0-mae:2140.33145
[224]	validation_0-mae:2138.83926
[225]	validation_0-mae:2138.48880
[226]	validation_0-mae:2137.65574
[227]	validation_0-mae:2136.21309
[228]	validation_0-mae:2136.21316
[229]	validation_0-mae:2135.84966
[230]	validation_0-mae:2134.18007
[231]	validation_0-mae:2134.63281
[232]	validation_0-mae:2134.31705
[233]	validation_0-mae:2132.83360
[234]	validation_0-mae:2132.11113
[235]	validation_0-mae:2131.88183
[236]	validation_0-mae:2132.01738
[237]	validation_0-mae:2132.45808
[238]	validation_0-mae:2130.84366
[239]	validation_0-mae:2131.03762
[240]	validation_0-mae:2130.52373
[241]	validation_0-mae:2131.12604
[242]	validation_0-mae:2131.15548
[243]	validation_0-mae:2130.07219
[244]	validation_0-mae:2128.66549
[245]	validation_0-mae:2127.58507
[246]	validation_0-mae:2127.32656
[247]	validation_0-mae:2126.61188
[248]	validation_0-mae:2125.20575
[249]	validation_0-mae:2124.05483
[250]	validation_0-mae:2123.53097
[251]	validation_0-mae:2121.51164
[252]	validation_0-mae:2120.00601
[253]	validation_0-mae:2120.12203
[254]	validation_0-mae:2119.43553
[255]	validation_0-mae:2120.07285
[256]	validation_0-mae:2119.76516
[257]	validation_0-mae:2121.67415
[258]	validation_0-mae:2120.70258
[259]	validation_0-mae:2121.89257
[260]	validation_0-mae:2121.97069
[261]	validation_0-mae:2121.48479
[262]	validation_0-mae:2120.86010
[263]	validation_0-mae:2120.39333
[264]	validation_0-mae:2120.72226
[265]	validation_0-mae:2120.58731
[266]	validation_0-mae:2119.92314
[267]	validation_0-mae:2120.10015
[268]	validation_0-mae:2119.22176
[269]	validation_0-mae:2118.49616
[270]	validation_0-mae:2117.99080
[271]	validation_0-mae:2117.86641
[272]	validation_0-mae:2116.52841
[273]	validation_0-mae:2117.71177
[274]	validation_0-mae:2116.97445
[275]	validation_0-mae:2117.75841
[276]	validation_0-mae:2118.71888
[277]	validation_0-mae:2118.50552
[278]	validation_0-mae:2118.92598
[279]	validation_0-mae:2118.42334
[280]	validation_0-mae:2118.74668
[281]	validation_0-mae:2118.50366
[282]	validation_0-mae:2118.59445
[283]	validation_0-mae:2118.00172
[284]	validation_0-mae:2117.90549
[285]	validation_0-mae:2117.26541
[286]	validation_0-mae:2116.98977
[287]	validation_0-mae:2116.92693
[288]	validation_0-mae:2116.43136
[289]	validation_0-mae:2116.82639
[290]	validation_0-mae:2116.97350
[291]	validation_0-mae:2117.12022
[292]	validation_0-mae:2116.59334
[293]	validation_0-mae:2116.03193
[294]	validation_0-mae:2116.28741
[295]	validation_0-mae:2115.87765
[296]	validation_0-mae:2114.73560
[297]	validation_0-mae:2114.37890
[298]	validation_0-mae:2113.36520
[299]	validation_0-mae:2113.27515
[300]	validation_0-mae:2112.29501
[301]	validation_0-mae:2111.57606
[302]	validation_0-mae:2111.12721
[303]	validation_0-mae:2111.98516
[304]	validation_0-mae:2110.83200
[305]	validation_0-mae:2110.45897
[306]	validation_0-mae:2110.86072
[307]	validation_0-mae:2110.22533
[308]	validation_0-mae:2109.95819
[309]	validation_0-mae:2109.71026
[310]	validation_0-mae:2109.08871
[311]	validation_0-mae:2108.61074
[312]	validation_0-mae:2108.74585
[313]	validation_0-mae:2109.28038
[314]	validation_0-mae:2110.24902
[315]	validation_0-mae:2110.30954
[316]	validation_0-mae:2110.34663
[317]	validation_0-mae:2110.28566
[318]	validation_0-mae:2110.28170
[319]	validation_0-mae:2110.06474
[320]	validation_0-mae:2109.87356
[321]	validation_0-mae:2110.54970
[322]	validation_0-mae:2110.50519
[323]	validation_0-mae:2110.53650
[324]	validation_0-mae:2110.82274
[325]	validation_0-mae:2111.05920
[326]	validation_0-mae:2111.14085
[327]	validation_0-mae:2110.67491
[328]	validation_0-mae:2110.59194
[329]	validation_0-mae:2110.20728
[330]	validation_0-mae:2110.38790
[331]	validation_0-mae:2110.10864
[332]	validation_0-mae:2110.44726
[333]	validation_0-mae:2109.53947
[334]	validation_0-mae:2109.42878
[335]	validation_0-mae:2109.65213
[336]	validation_0-mae:2108.88420
[337]	validation_0-mae:2108.39724
[338]	validation_0-mae:2107.98402
[339]	validation_0-mae:2107.04577
[340]	validation_0-mae:2107.32941
[341]	validation_0-mae:2107.62029
[342]	validation_0-mae:2107.18300
[343]	validation_0-mae:2106.67460
[344]	validation_0-mae:2106.33037
[345]	validation_0-mae:2106.13337
[346]	validation_0-mae:2106.41116
[347]	validation_0-mae:2106.67315
[348]	validation_0-mae:2106.36897
[349]	validation_0-mae:2105.56179
[350]	validation_0-mae:2105.36777
[351]	validation_0-mae:2105.48054
[352]	validation_0-mae:2104.77177
[353]	validation_0-mae:2103.87752
[354]	validation_0-mae:2103.98908
[355]	validation_0-mae:2103.41817
[356]	validation_0-mae:2103.33860
[357]	validation_0-mae:2102.81661
[358]	validation_0-mae:2102.19440
[359]	validation_0-mae:2101.72025
[360]	validation_0-mae:2099.69892
[361]	validation_0-mae:2098.32282
[362]	validation_0-mae:2098.18127
[363]	validation_0-mae:2097.80816
[364]	validation_0-mae:2097.10269
[365]	validation_0-mae:2096.98264
[366]	validation_0-mae:2097.01484
[367]	validation_0-mae:2096.55496
[368]	validation_0-mae:2096.86467
[369]	validation_0-mae:2097.11926
[370]	validation_0-mae:2097.78749
[371]	validation_0-mae:2097.13911
[372]	validation_0-mae:2097.71689
[373]	validation_0-mae:2097.60211
[374]	validation_0-mae:2097.65461
[375]	validation_0-mae:2097.66005
[376]	validation_0-mae:2097.66953
[377]	validation_0-mae:2098.24898
[378]	validation_0-mae:2098.04393
[379]	validation_0-mae:2098.26332
[380]	validation_0-mae:2098.10132
[381]	validation_0-mae:2098.40854
[382]	validation_0-mae:2098.36345
[383]	validation_0-mae:2098.42891
[384]	validation_0-mae:2097.96221
[385]	validation_0-mae:2098.10137
[386]	validation_0-mae:2098.53583
[387]	validation_0-mae:2098.34226
[388]	validation_0-mae:2098.09171
[389]	validation_0-mae:2098.36783
[390]	validation_0-mae:2097.71677
[391]	validation_0-mae:2096.42969
[392]	validation_0-mae:2095.03991
[393]	validation_0-mae:2094.87210
[394]	validation_0-mae:2094.31937
[395]	validation_0-mae:2093.81220
[396]	validation_0-mae:2093.56314
[397]	validation_0-mae:2093.37540
[398]	validation_0-mae:2093.67780
[399]	validation_0-mae:2093.92812
[400]	validation_0-mae:2093.92457
[401]	validation_0-mae:2094.02942
[402]	validation_0-mae:2093.65291
[403]	validation_0-mae:2093.85885
[404]	validation_0-mae:2093.64114
[405]	validation_0-mae:2093.70142
[406]	validation_0-mae:2094.03014
[407]	validation_0-mae:2094.21670
[408]	validation_0-mae:2094.81229
[409]	validation_0-mae:2094.97485
[410]	validation_0-mae:2095.10964
[411]	validation_0-mae:2095.20302
[412]	validation_0-mae:2095.15594
[413]	validation_0-mae:2095.43851
[414]	validation_0-mae:2095.62870
[415]	validation_0-mae:2095.71318
[416]	validation_0-mae:2095.49589
[417]	validation_0-mae:2095.67771
[418]	validation_0-mae:2095.83766
[419]	validation_0-mae:2095.25839
[420]	validation_0-mae:2094.74780
[421]	validation_0-mae:2095.01119
[422]	validation_0-mae:2094.83825
[423]	validation_0-mae:2094.91738
[424]	validation_0-mae:2094.97330
[425]	validation_0-mae:2094.11926
[426]	validation_0-mae:2093.84792
[427]	validation_0-mae:2094.46637
[428]	validation_0-mae:2094.45369
[429]	validation_0-mae:2094.67060
[430]	validation_0-mae:2095.24400
[431]	validation_0-mae:2095.57796
[432]	validation_0-mae:2095.79712
[433]	validation_0-mae:2095.41838
[434]	validation_0-mae:2095.56922
[435]	validation_0-mae:2095.90682
[436]	validation_0-mae:2095.89230
[437]	validation_0-mae:2095.54699
[438]	validation_0-mae:2096.00869
[439]	validation_0-mae:2095.91742
[440]	validation_0-mae:2095.71135
[441]	validation_0-mae:2095.33882
[442]	validation_0-mae:2095.10410
[443]	validation_0-mae:2095.12408
[444]	validation_0-mae:2094.81839
[445]	validation_0-mae:2093.57421
[446]	validation_0-mae:2092.76849
[447]	validation_0-mae:2092.40743
[448]	validation_0-mae:2092.21773
[449]	validation_0-mae:2091.74496
[450]	validation_0-mae:2091.13827
[451]	validation_0-mae:2090.95553
[452]	validation_0-mae:2090.82571
[453]	validation_0-mae:2090.27508
[454]	validation_0-mae:2090.70410
[455]	validation_0-mae:2090.94905
[456]	validation_0-mae:2090.84183
[457]	validation_0-mae:2090.31138
[458]	validation_0-mae:2090.12132
[459]	validation_0-mae:2090.30090
[460]	validation_0-mae:2090.28481
[461]	validation_0-mae:2091.01645
[462]	validation_0-mae:2090.68775
[463]	validation_0-mae:2090.48493
[464]	validation_0-mae:2090.62200
[465]	validation_0-mae:2090.40746
[466]	validation_0-mae:2090.51762
[467]	validation_0-mae:2090.24038
[468]	validation_0-mae:2090.62670
[469]	validation_0-mae:2090.89441
[470]	validation_0-mae:2091.07087
[471]	validation_0-mae:2091.00630
[472]	validation_0-mae:2091.31660
[473]	validation_0-mae:2091.14434
[474]	validation_0-mae:2091.26383
[475]	validation_0-mae:2091.26197
[476]	validation_0-mae:2091.22188
[477]	validation_0-mae:2090.76587
[478]	validation_0-mae:2091.12989
[479]	validation_0-mae:2090.88507
[480]	validation_0-mae:2090.91752
[481]	validation_0-mae:2090.81822
[482]	validation_0-mae:2090.19456
[483]	validation_0-mae:2089.59966
[484]	validation_0-mae:2088.99204
[485]	validation_0-mae:2089.02864
[486]	validation_0-mae:2088.78067
[487]	validation_0-mae:2089.19966
[488]	validation_0-mae:2089.31887
[489]	validation_0-mae:2089.57157
[490]	validation_0-mae:2089.27311
[491]	validation_0-mae:2089.38185
[492]	validation_0-mae:2088.89096
[493]	validation_0-mae:2088.35451
[494]	validation_0-mae:2088.14766
[495]	validation_0-mae:2087.54152
[496]	validation_0-mae:2087.85253
[497]	validation_0-mae:2087.89216
[498]	validation_0-mae:2088.20154
[499]	validation_0-mae:2088.23433
[500]	validation_0-mae:2088.44519
[501]	validation_0-mae:2088.65298
[502]	validation_0-mae:2088.14751
[503]	validation_0-mae:2087.65060
[504]	validation_0-mae:2087.59995
[505]	validation_0-mae:2087.38297
[506]	validation_0-mae:2087.48634
[507]	validation_0-mae:2087.15260
[508]	validation_0-mae:2087.00309
[509]	validation_0-mae:2087.13569
[510]	validation_0-mae:2086.91823
[511]	validation_0-mae:2086.80813
[512]	validation_0-mae:2086.87547
[513]	validation_0-mae:2087.02194
[514]	validation_0-mae:2086.61805
[515]	validation_0-mae:2086.39640
[516]	validation_0-mae:2086.62928
[517]	validation_0-mae:2086.53335
[518]	validation_0-mae:2086.43431
[519]	validation_0-mae:2086.30835
[520]	validation_0-mae:2085.89457
[521]	validation_0-mae:2085.75580
[522]	validation_0-mae:2085.84363
[523]	validation_0-mae:2085.71546
[524]	validation_0-mae:2085.39611
[525]	validation_0-mae:2085.59274
[526]	validation_0-mae:2085.78760
[527]	validation_0-mae:2085.94432
[528]	validation_0-mae:2085.59903
[529]	validation_0-mae:2085.72427
[530]	validation_0-mae:2085.66508
[531]	validation_0-mae:2085.51082
[532]	validation_0-mae:2085.47893
[533]	validation_0-mae:2085.07295
[534]	validation_0-mae:2085.07922
[535]	validation_0-mae:2085.10762
[536]	validation_0-mae:2084.98343
[537]	validation_0-mae:2084.87475
[538]	validation_0-mae:2084.80072
[539]	validation_0-mae:2084.76305
[540]	validation_0-mae:2084.93347
[541]	validation_0-mae:2084.89111
[542]	validation_0-mae:2084.13981
[543]	validation_0-mae:2084.11989
[544]	validation_0-mae:2084.30871
[545]	validation_0-mae:2084.55181
[546]	validation_0-mae:2084.91705
[547]	validation_0-mae:2085.13356
[548]	validation_0-mae:2085.11324
[549]	validation_0-mae:2084.80466
[550]	validation_0-mae:2084.70640
[551]	validation_0-mae:2084.82017
[552]	validation_0-mae:2084.44069
[553]	validation_0-mae:2084.16733
[554]	validation_0-mae:2084.17812
[555]	validation_0-mae:2084.02132
[556]	validation_0-mae:2083.81343
[557]	validation_0-mae:2083.81685
[558]	validation_0-mae:2083.93462
[559]	validation_0-mae:2084.41534
[560]	validation_0-mae:2084.51273
[561]	validation_0-mae:2084.64543
[562]	validation_0-mae:2084.57803
[563]	validation_0-mae:2084.48715
[564]	validation_0-mae:2084.79763
[565]	validation_0-mae:2084.48176
[566]	validation_0-mae:2084.50181
[567]	validation_0-mae:2084.73175
[568]	validation_0-mae:2084.44511
[569]	validation_0-mae:2084.44418
[570]	validation_0-mae:2084.31480
[571]	validation_0-mae:2084.27381
[572]	validation_0-mae:2084.25319
[573]	validation_0-mae:2084.16015
[574]	validation_0-mae:2084.19464
[575]	validation_0-mae:2083.42188
[576]	validation_0-mae:2083.18361
[577]	validation_0-mae:2083.34422
[578]	validation_0-mae:2083.15559
[579]	validation_0-mae:2082.82562
[580]	validation_0-mae:2082.68841
[581]	validation_0-mae:2082.62905
[582]	validation_0-mae:2082.33255
[583]	validation_0-mae:2082.08740
[584]	validation_0-mae:2082.25254
[585]	validation_0-mae:2082.11206
[586]	validation_0-mae:2082.06398
[587]	validation_0-mae:2081.88599
[588]	validation_0-mae:2081.87156
[589]	validation_0-mae:2081.79404
[590]	validation_0-mae:2081.44386

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[39]	validation_0-mae:3312.93428
[40]	validation_0-mae:3265.37037
[41]	validation_0-mae:3221.90251
[42]	validation_0-mae:3179.73426
[43]	validation_0-mae:3143.50335
[44]	validation_0-mae:3118.02647
[45]	validation_0-mae:3088.08392
[46]	validation_0-mae:3063.39066
[47]	validation_0-mae:3035.08725
[48]	validation_0-mae:3010.46277
[49]	validation_0-mae:2956.27693
[50]	validation_0-mae:2924.06732
[51]	validation_0-mae:2887.71319
[52]	validation_0-mae:2869.05130
[53]	validation_0-mae:2840.42291
[54]	validation_0-mae:2820.47823
[55]	validation_0-mae:2792.86774
[56]	validation_0-mae:2770.83365
[57]	validation_0-mae:2750.51873
[58]	validation_0-mae:2734.55820
[59]	validation_0-mae:2713.75389
[60]	validation_0-mae:2698.50298
[61]	validation_0-mae:2684.62239
[62]	validation_0-mae:2677.82933
[63]	validation_0-mae:2665.74402
[64]	validation_0-mae:2649.39238
[65]	validation_0-mae:2632.85238
[66]	validation_0-mae:2620.20783
[67]	validation_0-mae:2609.87664
[68]	validation_0-mae:2604.39288
[69]	validation_0-mae:2591.82677
[70]	validation_0-mae:2581.05890
[71]	validation_0-mae:2571.81449
[72]	validation_0-mae:2554.79725
[73]	validation_0-mae:2540.59213
[74]	validation_0-mae:2525.29035
[75]	validation_0-mae:2520.84660
[76]	validation_0-mae:2508.67965
[77]	validation_0-mae:2500.34088
[78]	validation_0-mae:2493.53613
[79]	validation_0-mae:2481.19207
[80]	validation_0-mae:2476.06647
[81]	validation_0-mae:2471.14018
[82]	validation_0-mae:2460.26849
[83]	validation_0-mae:2449.65873
[84]	validation_0-mae:2445.32943
[85]	validation_0-mae:2440.44837
[86]	validation_0-mae:2436.32119
[87]	validation_0-mae:2425.95631
[88]	validation_0-mae:2423.39380
[89]	validation_0-mae:2414.48630
[90]	validation_0-mae:2406.28795
[91]	validation_0-mae:2401.91997
[92]	validation_0-mae:2399.68403
[93]	validation_0-mae:2390.48245
[94]	validation_0-mae:2389.91604
[95]	validation_0-mae:2384.07020
[96]	validation_0-mae:2378.00537
[97]	validation_0-mae:2372.01845
[98]	validation_0-mae:2367.17008
[99]	validation_0-mae:2357.71035
[100]	validation_0-mae:2353.98824
[101]	validation_0-mae:2351.04527
[102]	validation_0-mae:2345.21708
[103]	validation_0-mae:2340.49357
[104]	validation_0-mae:2335.22513
[105]	validation_0-mae:2330.05013
[106]	validation_0-mae:2327.04167
[107]	validation_0-mae:2322.76126
[108]	validation_0-mae:2319.32924
[109]	validation_0-mae:2311.33645
[110]	validation_0-mae:2306.57895
[111]	validation_0-mae:2305.49360
[112]	validation_0-mae:2304.17091
[113]	validation_0-mae:2303.45125
[114]	validation_0-mae:2302.13989
[115]	validation_0-mae:2299.54658
[116]	validation_0-mae:2298.85605
[117]	validation_0-mae:2294.65151
[118]	validation_0-mae:2295.30394
[119]	validation_0-mae:2292.03374
[120]	validation_0-mae:2289.67885
[121]	validation_0-mae:2284.34776
[122]	validation_0-mae:2282.58792
[123]	validation_0-mae:2282.09307
[124]	validation_0-mae:2282.33329
[125]	validation_0-mae:2277.16393
[126]	validation_0-mae:2277.00208
[127]	validation_0-mae:2273.31506
[128]	validation_0-mae:2270.98696
[129]	validation_0-mae:2268.69108
[130]	validation_0-mae:2268.50842
[131]	validation_0-mae:2267.04302
[132]	validation_0-mae:2265.45196
[133]	validation_0-mae:2263.80605
[134]	validation_0-mae:2263.63488
[135]	validation_0-mae:2263.10043
[136]	validation_0-mae:2258.05534
[137]	validation_0-mae:2255.04004
[138]	validation_0-mae:2254.27672
[139]	validation_0-mae:2249.51194
[140]	validation_0-mae:2249.45613
[141]	validation_0-mae:2246.33982
[142]	validation_0-mae:2244.64599
[143]	validation_0-mae:2242.15695
[144]	validation_0-mae:2241.25698
[145]	validation_0-mae:2240.23266
[146]	validation_0-mae:2235.10889
[147]	validation_0-mae:2236.09590
[148]	validation_0-mae:2237.34210
[149]	validation_0-mae:2235.61788
[150]	validation_0-mae:2235.59629
[151]	validation_0-mae:2233.64633
[152]	validation_0-mae:2231.57339
[153]	validation_0-mae:2229.76602
[154]	validation_0-mae:2229.80947
[155]	validation_0-mae:2229.58928
[156]	validation_0-mae:2228.29059
[157]	validation_0-mae:2227.31079
[158]	validation_0-mae:2224.77013
[159]	validation_0-mae:2223.12839
[160]	validation_0-mae:2223.37796
[161]	validation_0-mae:2221.89400
[162]	validation_0-mae:2220.89638
[163]	validation_0-mae:2219.76338
[164]	validation_0-mae:2220.63944
[165]	validation_0-mae:2218.61885
[166]	validation_0-mae:2217.08554
[167]	validation_0-mae:2216.83878
[168]	validation_0-mae:2216.32142
[0]	validation_0-mae:12503.04583
[1]	validation_0-mae:11825.27272
[2]	validation_0-mae:11186.27545
[3]	validation_0-mae:10609.56992
[4]	validation_0-mae:10088.86584
[5]	validation_0-mae:9621.12839
[6]	validation_0-mae:9180.44740
[7]	validation_0-mae:8792.50176
[8]	validation_0-mae:8437.84363
[9]	validation_0-mae:8105.21738
[0]	validation_0-mae:12435.92133

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[1]	validation_0-mae:11692.67421
[2]	validation_0-mae:11020.76374
[3]	validation_0-mae:10381.31991
[4]	validation_0-mae:9845.27280
[5]	validation_0-mae:9332.22786
[6]	validation_0-mae:8873.78349
[7]	validation_0-mae:8456.27553
[8]	validation_0-mae:8071.59215
[9]	validation_0-mae:7738.25828
[10]	validation_0-mae:7416.53840
[11]	validation_0-mae:7137.24544
[12]	validation_0-mae:6839.02232
[13]	validation_0-mae:6567.54875
[14]	validation_0-mae:6341.10540
[15]	validation_0-mae:6120.42572
[16]	validation_0-mae:5884.87638
[17]	validation_0-mae:5690.96903
[18]	validation_0-mae:5508.04485
[19]	validation_0-mae:5341.44839
[20]	validation_0-mae:5190.63629
[21]	validation_0-mae:5024.25261
[22]	validation_0-mae:4879.96749
[23]	validation_0-mae:4737.32053
[24]	validation_0-mae:4622.62817
[25]	validation_0-mae:4484.01338
[26]	validation_0-mae:4360.40274
[27]	validation_0-mae:4249.89102
[28]	validation_0-mae:4135.18883
[29]	validation_0-mae:4043.25571
[30]	validation_0-mae:3957.01764
[31]	validation_0-mae:3867.66964
[32]	validation_0-mae:3793.37816
[33]	validation_0-mae:3726.54358
[34]	validation_0-mae:3656.72606
[35]	validation_0-mae:3598.59808
[36]	validation_0-mae:3546.26352
[37]	validation_0-mae:3489.78292
[38]	validation_0-mae:3424.81556
[39]	validation_0-mae:3368.18943
[40]	validation_0-mae:3316.19309
[41]	validation_0-mae:3273.57393
[42]	validation_0-mae:3229.05808
[43]	validation_0-mae:3196.24046
[44]	validation_0-mae:3155.00309
[45]	validation_0-mae:3127.12603
[46]	validation_0-mae:3093.71870
[47]	validation_0-mae:3061.38719
[48]	validation_0-mae:3038.86545
[49]	validation_0-mae:3009.27415
[50]	validation_0-mae:2984.15960
[51]	validation_0-mae:2943.95552
[52]	validation_0-mae:2918.10724
[53]	validation_0-mae:2883.31697
[54]	validation_0-mae:2852.92525
[55]	validation_0-mae:2836.30946
[56]	validation_0-mae:2821.02437
[57]	validation_0-mae:2799.02310
[58]	validation_0-mae:2772.51838
[59]	validation_0-mae:2755.24975
[60]	validation_0-mae:2738.13520
[61]	validation_0-mae:2720.69402
[62]	validation_0-mae:2707.09012
[63]	validation_0-mae:2686.78243
[64]	validation_0-mae:2674.99664
[65]	validation_0-mae:2658.33888
[66]	validation_0-mae:2648.00600
[67]	validation_0-mae:2629.04331
[68]	validation_0-mae:2620.29369
[69]	validation_0-mae:2601.90992
[70]	validation_0-mae:2591.68904
[71]	validation_0-mae:2582.66985
[72]	validation_0-mae:2574.15817
[73]	validation_0-mae:2558.87680
[74]	validation_0-mae:2551.28741
[75]	validation_0-mae:2534.62720
[76]	validation_0-mae:2524.95951
[77]	validation_0-mae:2514.34130
[78]	validation_0-mae:2507.99644
[79]	validation_0-mae:2503.63397
[80]	validation_0-mae:2493.27384
[81]	validation_0-mae:2481.56934
[82]	validation_0-mae:2473.86882
[83]	validation_0-mae:2463.44363
[84]	validation_0-mae:2457.56041
[85]	validation_0-mae:2446.25192
[86]	validation_0-mae:2443.10316
[87]	validation_0-mae:2434.77616
[88]	validation_0-mae:2428.81246
[89]	validation_0-mae:2420.36755
[90]	validation_0-mae:2416.13427
[91]	validation_0-mae:2408.89832
[92]	validation_0-mae:2401.89416
[93]	validation_0-mae:2394.07647
[94]	validation_0-mae:2383.64499
[95]	validation_0-mae:2375.30144
[96]	validation_0-mae:2372.76391
[97]	validation_0-mae:2369.58165
[98]	validation_0-mae:2364.78664
[99]	validation_0-mae:2356.07635
[100]	validation_0-mae:2353.52777
[101]	validation_0-mae:2346.80095
[102]	validation_0-mae:2339.81799
[103]	validation_0-mae:2335.60069
[104]	validation_0-mae:2331.36363
[105]	validation_0-mae:2326.71682
[106]	validation_0-mae:2322.08135
[107]	validation_0-mae:2316.31326
[108]	validation_0-mae:2310.99721
[109]	validation_0-mae:2309.33190
[110]	validation_0-mae:2305.30848
[111]	validation_0-mae:2301.64297
[112]	validation_0-mae:2300.13595
[113]	validation_0-mae:2296.35048
[114]	validation_0-mae:2294.49612
[115]	validation_0-mae:2292.83360
[116]	validation_0-mae:2289.31607
[117]	validation_0-mae:2288.04979
[118]	validation_0-mae:2285.26741
[119]	validation_0-mae:2281.65992
[120]	validation_0-mae:2275.57238
[121]	validation_0-mae:2272.21045
[122]	validation_0-mae:2267.98031
[123]	validation_0-mae:2265.54027
[124]	validation_0-mae:2262.20204
[125]	validation_0-mae:2259.36312
[126]	validation_0-mae:2258.02686
[127]	validation_0-mae:2254.30880
[128]	validation_0-mae:2251.84343
[129]	validation_0-mae:2250.43598
[130]	validation_0-mae:2246.80262
[131]	validation_0-mae:2245.64443
[132]	validation_0-mae:2246.08795
[133]	validation_0-mae:2243.35572
[134]	validation_0-mae:2241.97566
[135]	validation_0-mae:2238.34440
[136]	validation_0-mae:2235.78693
[137]	validation_0-mae:2234.23573
[138]	validation_0-mae:2234.62017
[139]	validation_0-mae:2233.09755
[140]	validation_0-mae:2228.59876
[141]	validation_0-mae:2227.18048
[142]	validation_0-mae:2224.53759
[143]	validation_0-mae:2223.70611
[144]	validation_0-mae:2219.61668
[145]	validation_0-mae:2216.28984
[146]	validation_0-mae:2213.55881
[147]	validation_0-mae:2213.29590
[148]	validation_0-mae:2210.58992
[149]	validation_0-mae:2209.68845
[150]	validation_0-mae:2208.64215
[151]	validation_0-mae:2205.80678
[152]	validation_0-mae:2205.71128
[153]	validation_0-mae:2204.08816
[154]	validation_0-mae:2201.86389
[155]	validation_0-mae:2199.85229
[156]	validation_0-mae:2198.63186
[157]	validation_0-mae:2198.91897
[158]	validation_0-mae:2197.85853
[159]	validation_0-mae:2195.91894
[160]	validation_0-mae:2194.27846
[161]	validation_0-mae:2192.03441
[162]	validation_0-mae:2191.41314
[163]	validation_0-mae:2190.08521
[164]	validation_0-mae:2188.54919
[165]	validation_0-mae:2188.24058
[166]	validation_0-mae:2186.98093
[167]	validation_0-mae:2187.01038
[168]	validation_0-mae:2185.84124
[169]	validation_0-mae:2185.32218
[170]	validation_0-mae:2184.88084
[171]	validation_0-mae:2182.56811
[172]	validation_0-mae:2180.43285
[173]	validation_0-mae:2181.09769
[174]	validation_0-mae:2179.10057
[175]	validation_0-mae:2178.10870
[176]	validation_0-mae:2176.65038
[177]	validation_0-mae:2174.49938
[178]	validation_0-mae:2175.42049
[179]	validation_0-mae:2174.19865
[180]	validation_0-mae:2174.86251
[181]	validation_0-mae:2175.48860
[182]	validation_0-mae:2175.45872
[183]	validation_0-mae:2175.16654
[184]	validation_0-mae:2173.93298
[185]	validation_0-mae:2174.46157
[186]	validation_0-mae:2173.15678
[187]	validation_0-mae:2172.59277
[188]	validation_0-mae:2172.29316
[189]	validation_0-mae:2172.99388
[190]	validation_0-mae:2172.81243
[191]	validation_0-mae:2173.32003
[192]	validation_0-mae:2172.64487
[193]	validation_0-mae:2171.29703
[194]	validation_0-mae:2171.37918
[195]	validation_0-mae:2171.09444
[196]	validation_0-mae:2170.18733
[197]	validation_0-mae:2168.37711
[198]	validation_0-mae:2168.11977
[199]	validation_0-mae:2167.69977
[200]	validation_0-mae:2167.48191
[201]	validation_0-mae:2168.26052
[202]	validation_0-mae:2167.92562
[203]	validation_0-mae:2166.88825
[204]	validation_0-mae:2166.67641
[205]	validation_0-mae:2166.09411
[206]	validation_0-mae:2167.00136
[207]	validation_0-mae:2164.80347
[208]	validation_0-mae:2165.42197
[209]	validation_0-mae:2164.95504
[210]	validation_0-mae:2165.31192
[211]	validation_0-mae:2164.85328
[212]	validation_0-mae:2162.89287
[213]	validation_0-mae:2161.90239
[214]	validation_0-mae:2163.05122
[215]	validation_0-mae:2162.88176
[216]	validation_0-mae:2162.66470
[217]	validation_0-mae:2163.07791
[218]	validation_0-mae:2162.03672
[219]	validation_0-mae:2161.06464
[220]	validation_0-mae:2160.00989
[221]	validation_0-mae:2159.17032
[222]	validation_0-mae:2159.15840
[223]	validation_0-mae:2158.16506
[224]	validation_0-mae:2156.79938
[225]	validation_0-mae:2156.95565
[226]	validation_0-mae:2156.18465
[227]	validation_0-mae:2156.28266
[228]	validation_0-mae:2156.70796
[229]	validation_0-mae:2154.84799
[230]	validation_0-mae:2154.13459
[231]	validation_0-mae:2153.63690
[232]	validation_0-mae:2152.49893
[233]	validation_0-mae:2152.65216
[234]	validation_0-mae:2152.56576
[235]	validation_0-mae:2153.33359
[236]	validation_0-mae:2154.04454
[237]	validation_0-mae:2152.92108
[238]	validation_0-mae:2152.65098
[239]	validation_0-mae:2152.60336
[240]	validation_0-mae:2152.00201
[241]	validation_0-mae:2151.94543
[242]	validation_0-mae:2151.59631
[243]	validation_0-mae:2152.80903
[244]	validation_0-mae:2150.76660
[245]	validation_0-mae:2149.59604
[246]	validation_0-mae:2149.23132
[247]	validation_0-mae:2149.32488
[248]	validation_0-mae:2148.43812
[249]	validation_0-mae:2148.53310
[250]	validation_0-mae:2147.64029
[251]	validation_0-mae:2146.74162
[252]	validation_0-mae:2146.67145
[253]	validation_0-mae:2147.56175
[254]	validation_0-mae:2147.39214
[255]	validation_0-mae:2147.65299
[256]	validation_0-mae:2147.14642
[257]	validation_0-mae:2147.64328
[258]	validation_0-mae:2149.12133
[259]	validation_0-mae:2148.56785
[260]	validation_0-mae:2147.57380
[261]	validation_0-mae:2146.91649
[262]	validation_0-mae:2146.70908
[263]	validation_0-mae:2148.38386
[264]	validation_0-mae:2149.06795
[265]	validation_0-mae:2148.16777
[266]	validation_0-mae:2147.16782
[267]	validation_0-mae:2145.59364
[268]	validation_0-mae:2143.47584
[269]	validation_0-mae:2141.74540
[270]	validation_0-mae:2140.80474
[271]	validation_0-mae:2140.20269
[272]	validation_0-mae:2139.19359
[273]	validation_0-mae:2139.23355
[274]	validation_0-mae:2136.53890
[275]	validation_0-mae:2136.85308
[276]	validation_0-mae:2135.61557
[277]	validation_0-mae:2135.61664
[278]	validation_0-mae:2136.31027
[279]	validation_0-mae:2135.44130
[280]	validation_0-mae:2136.00249
[281]	validation_0-mae:2134.91520
[282]	validation_0-mae:2134.95051
[283]	validation_0-mae:2133.10493
[284]	validation_0-mae:2133.64844
[285]	validation_0-mae:2133.69112
[286]	validation_0-mae:2133.35222
[287]	validation_0-mae:2133.51177
[288]	validation_0-mae:2132.88842
[289]	validation_0-mae:2132.81547
[290]	validation_0-mae:2132.35593
[291]	validation_0-mae:2131.79148
[292]	validation_0-mae:2130.85543
[293]	validation_0-mae:2129.92872
[294]	validation_0-mae:2129.72887
[295]	validation_0-mae:2128.44560
[296]	validation_0-mae:2128.26484
[297]	validation_0-mae:2127.95818
[298]	validation_0-mae:2127.66962
[299]	validation_0-mae:2126.55546
[300]	validation_0-mae:2126.14388
[301]	validation_0-mae:2125.40629
[302]	validation_0-mae:2124.86370
[303]	validation_0-mae:2123.60764
[304]	validation_0-mae:2122.74241
[305]	validation_0-mae:2123.01594
[306]	validation_0-mae:2122.74825
[307]	validation_0-mae:2122.01816
[308]	validation_0-mae:2121.31523
[309]	validation_0-mae:2120.70871
[310]	validation_0-mae:2121.41503
[311]	validation_0-mae:2121.32690
[312]	validation_0-mae:2121.66155
[313]	validation_0-mae:2121.59698
[314]	validation_0-mae:2121.47062
[315]	validation_0-mae:2121.22846
[316]	validation_0-mae:2121.00361
[317]	validation_0-mae:2121.15779
[318]	validation_0-mae:2120.38025
[319]	validation_0-mae:2119.76546
[320]	validation_0-mae:2118.95642
[321]	validation_0-mae:2118.77720
[322]	validation_0-mae:2118.86952
[323]	validation_0-mae:2118.18233
[324]	validation_0-mae:2117.91284
[325]	validation_0-mae:2116.87318
[326]	validation_0-mae:2116.57889
[327]	validation_0-mae:2116.68265
[328]	validation_0-mae:2116.16635
[329]	validation_0-mae:2116.31660
[330]	validation_0-mae:2116.10546
[331]	validation_0-mae:2116.09661
[332]	validation_0-mae:2115.22491
[333]	validation_0-mae:2115.22520
[334]	validation_0-mae:2115.22040
[335]	validation_0-mae:2114.99577
[336]	validation_0-mae:2114.71852
[337]	validation_0-mae:2114.21110
[338]	validation_0-mae:2114.57266
[339]	validation_0-mae:2114.46480
[340]	validation_0-mae:2113.35224
[341]	validation_0-mae:2112.86389
[342]	validation_0-mae:2112.61147
[343]	validation_0-mae:2112.22971
[344]	validation_0-mae:2112.52882
[345]	validation_0-mae:2112.40008
[346]	validation_0-mae:2111.64224
[347]	validation_0-mae:2111.72501
[348]	validation_0-mae:2112.25343
[349]	validation_0-mae:2112.40273
[350]	validation_0-mae:2112.04734
[351]	validation_0-mae:2111.78649
[352]	validation_0-mae:2111.96090
[353]	validation_0-mae:2112.17468
[354]	validation_0-mae:2111.67784
[355]	validation_0-mae:2111.69838
[356]	validation_0-mae:2111.64546
[357]	validation_0-mae:2111.49429
[358]	validation_0-mae:2111.32582
[359]	validation_0-mae:2111.19168
[360]	validation_0-mae:2110.40074
[361]	validation_0-mae:2110.61103
[362]	validation_0-mae:2110.07157
[363]	validation_0-mae:2110.21002
[364]	validation_0-mae:2110.69642
[365]	validation_0-mae:2110.70397
[366]	validation_0-mae:2110.15480
[367]	validation_0-mae:2109.73552
[368]	validation_0-mae:2109.67283
[369]	validation_0-mae:2109.70564
[370]	validation_0-mae:2109.65803
[371]	validation_0-mae:2109.82564
[372]	validation_0-mae:2110.22793
[373]	validation_0-mae:2109.60853
[374]	validation_0-mae:2109.73605
[375]	validation_0-mae:2108.59383
[376]	validation_0-mae:2108.15028
[377]	validation_0-mae:2108.12010
[378]	validation_0-mae:2108.64186
[379]	validation_0-mae:2108.59095
[380]	validation_0-mae:2108.94736
[381]	validation_0-mae:2109.53140
[382]	validation_0-mae:2109.18338
[383]	validation_0-mae:2109.21273
[384]	validation_0-mae:2109.50580
[385]	validation_0-mae:2109.72538
[386]	validation_0-mae:2109.74483
[387]	validation_0-mae:2109.33589
[388]	validation_0-mae:2108.19973
[389]	validation_0-mae:2107.94423
[390]	validation_0-mae:2108.60279
[391]	validation_0-mae:2108.01062
[392]	validation_0-mae:2108.38370
[393]	validation_0-mae:2108.70067
[394]	validation_0-mae:2107.79110
[395]	validation_0-mae:2107.90835
[396]	validation_0-mae:2107.78347
[397]	validation_0-mae:2108.03457
[398]	validation_0-mae:2108.20346
[399]	validation_0-mae:2107.47829
[400]	validation_0-mae:2108.00612
[401]	validation_0-mae:2107.03015
[402]	validation_0-mae:2107.04376
[403]	validation_0-mae:2105.52151
[404]	validation_0-mae:2105.73362
[405]	validation_0-mae:2105.90610
[406]	validation_0-mae:2106.39125
[407]	validation_0-mae:2105.82237
[408]	validation_0-mae:2105.94158
[409]	validation_0-mae:2105.98255
[410]	validation_0-mae:2106.14678
[411]	validation_0-mae:2105.49032
[412]	validation_0-mae:2105.85718
[413]	validation_0-mae:2106.24054
[414]	validation_0-mae:2106.52071
[415]	validation_0-mae:2106.83709
[416]	validation_0-mae:2106.52204
[417]	validation_0-mae:2106.87562
[418]	validation_0-mae:2105.94936
[419]	validation_0-mae:2106.46943
[420]	validation_0-mae:2105.33806
[421]	validation_0-mae:2105.28346
[422]	validation_0-mae:2105.20892
[423]	validation_0-mae:2105.58812
[424]	validation_0-mae:2105.51257
[425]	validation_0-mae:2105.52650
[426]	validation_0-mae:2105.43801
[427]	validation_0-mae:2105.24528
[428]	validation_0-mae:2104.64811
[429]	validation_0-mae:2104.29739
[430]	validation_0-mae:2104.34604
[431]	validation_0-mae:2104.08783
[432]	validation_0-mae:2103.32103
[433]	validation_0-mae:2103.20515
[434]	validation_0-mae:2102.54272
[435]	validation_0-mae:2102.02866
[436]	validation_0-mae:2102.49816
[437]	validation_0-mae:2102.22006
[438]	validation_0-mae:2102.19806
[439]	validation_0-mae:2102.68473
[440]	validation_0-mae:2102.90000
[441]	validation_0-mae:2103.27038
[442]	validation_0-mae:2103.24995
[443]	validation_0-mae:2103.06972
[444]	validation_0-mae:2103.29306
[445]	validation_0-mae:2103.32036
[446]	validation_0-mae:2102.83363
[447]	validation_0-mae:2102.73071
[448]	validation_0-mae:2102.77223
[449]	validation_0-mae:2102.94034
[450]	validation_0-mae:2102.83795
[451]	validation_0-mae:2102.92697
[452]	validation_0-mae:2103.07119
[453]	validation_0-mae:2102.86908
[454]	validation_0-mae:2102.78215
[455]	validation_0-mae:2103.00681
[456]	validation_0-mae:2103.16867
[457]	validation_0-mae:2103.64995
[458]	validation_0-mae:2103.93679
[459]	validation_0-mae:2104.15067
[460]	validation_0-mae:2103.56516
[461]	validation_0-mae:2103.73316
[462]	validation_0-mae:2103.90542
[463]	validation_0-mae:2103.87007
[464]	validation_0-mae:2104.00115
[465]	validation_0-mae:2104.23268
[466]	validation_0-mae:2104.25714
[467]	validation_0-mae:2104.56434
[468]	validation_0-mae:2103.45523
[469]	validation_0-mae:2102.00912
[470]	validation_0-mae:2101.76563
[471]	validation_0-mae:2101.60765
[472]	validation_0-mae:2101.57299
[473]	validation_0-mae:2101.53346
[474]	validation_0-mae:2101.44674
[475]	validation_0-mae:2101.13837
[476]	validation_0-mae:2101.23582
[477]	validation_0-mae:2100.86528
[478]	validation_0-mae:2101.15173
[479]	validation_0-mae:2101.06006
[480]	validation_0-mae:2101.13093
[481]	validation_0-mae:2101.07137
[482]	validation_0-mae:2101.01194
[483]	validation_0-mae:2100.38784
[484]	validation_0-mae:2100.42213
[485]	validation_0-mae:2099.82611
[486]	validation_0-mae:2099.76085
[487]	validation_0-mae:2100.11775
[488]	validation_0-mae:2099.63125
[489]	validation_0-mae:2099.66847
[490]	validation_0-mae:2099.75827
[491]	validation_0-mae:2099.64184
[492]	validation_0-mae:2099.68035
[493]	validation_0-mae:2099.99072
[494]	validation_0-mae:2100.01631
[495]	validation_0-mae:2100.07509
[496]	validation_0-mae:2100.05661
[497]	validation_0-mae:2100.59141
[498]	validation_0-mae:2100.17029
[499]	validation_0-mae:2100.01716
[500]	validation_0-mae:2099.52752
[501]	validation_0-mae:2099.92013
[502]	validation_0-mae:2100.11700
[503]	validation_0-mae:2100.19749
[504]	validation_0-mae:2099.94784
[505]	validation_0-mae:2100.08279
[506]	validation_0-mae:2100.15748
[507]	validation_0-mae:2100.34735
[508]	validation_0-mae:2100.29776
[509]	validation_0-mae:2100.15533
[510]	validation_0-mae:2100.11286
[511]	validation_0-mae:2099.94169
[512]	validation_0-mae:2099.23044
[513]	validation_0-mae:2098.71093
[514]	validation_0-mae:2098.33273
[515]	validation_0-mae:2097.79643
[516]	validation_0-mae:2097.75727
[517]	validation_0-mae:2097.53588
[518]	validation_0-mae:2096.97198
[519]	validation_0-mae:2096.92609
[520]	validation_0-mae:2097.15695
[521]	validation_0-mae:2097.23821
[522]	validation_0-mae:2097.25905
[523]	validation_0-mae:2096.65179
[524]	validation_0-mae:2096.24233
[525]	validation_0-mae:2096.25187
[526]	validation_0-mae:2096.18214
[527]	validation_0-mae:2096.10559
[528]	validation_0-mae:2096.20402
[529]	validation_0-mae:2096.09290
[530]	validation_0-mae:2096.56467
[531]	validation_0-mae:2096.45297
[532]	validation_0-mae:2096.50812
[533]	validation_0-mae:2096.10417
[534]	validation_0-mae:2096.45346
[535]	validation_0-mae:2096.74340
[536]	validation_0-mae:2096.84672
[537]	validation_0-mae:2096.56150
[538]	validation_0-mae:2096.51605
[539]	validation_0-mae:2096.67623
[540]	validation_0-mae:2096.62531
[541]	validation_0-mae:2096.85158
[542]	validation_0-mae:2097.24486
[543]	validation_0-mae:2097.12209
[544]	validation_0-mae:2095.88859
[545]	validation_0-mae:2095.95914
[546]	validation_0-mae:2095.36767
[547]	validation_0-mae:2095.22067
[548]	validation_0-mae:2094.30982
[549]	validation_0-mae:2094.29505
[550]	validation_0-mae:2094.45302
[551]	validation_0-mae:2094.70496
[552]	validation_0-mae:2094.40291
[553]	validation_0-mae:2094.00926
[554]	validation_0-mae:2093.99484
[555]	validation_0-mae:2094.15940
[556]	validation_0-mae:2093.61389
[557]	validation_0-mae:2093.06751
[558]	validation_0-mae:2092.84234
[559]	validation_0-mae:2092.75256
[560]	validation_0-mae:2092.43357
[561]	validation_0-mae:2092.40719
[562]	validation_0-mae:2092.05853
[563]	validation_0-mae:2092.17059
[564]	validation_0-mae:2092.21911
[565]	validation_0-mae:2092.39803
[566]	validation_0-mae:2091.97640
[567]	validation_0-mae:2092.07396
[568]	validation_0-mae:2092.08793
[569]	validation_0-mae:2092.37823
[570]	validation_0-mae:2091.94927
[571]	validation_0-mae:2091.96747
[572]	validation_0-mae:2092.15000
[573]	validation_0-mae:2091.67215
[574]	validation_0-mae:2091.87174
[575]	validation_0-mae:2092.11715
[576]	validation_0-mae:2092.12710
[577]	validation_0-mae:2092.18142
[578]	validation_0-mae:2092.00467
[579]	validation_0-mae:2091.85111
[580]	validation_0-mae:2091.81770
[581]	validation_0-mae:2092.13725
[582]	validation_0-mae:2091.87140
[583]	validation_0-mae:2091.94177
[584]	validation_0-mae:2091.75170
[585]	validation_0-mae:2091.55032
[586]	validation_0-mae:2091.54390
[587]	validation_0-mae:2091.68312
[588]	validation_0-mae:2091.84617
[589]	validation_0-mae:2091.49170
[590]	validation_0-mae:2091.50268
[591]	validation_0-mae:2091.54844

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[0]	validation_0-mae:12503.75548
[1]	validation_0-mae:11815.47242
[2]	validation_0-mae:11176.20343
[3]	validation_0-mae:10584.26069
[4]	validation_0-mae:10058.81289
[5]	validation_0-mae:9595.27938
[6]	validation_0-mae:9173.92104
[7]	validation_0-mae:8781.08857
[8]	validation_0-mae:8420.80095
[9]	validation_0-mae:8097.15716
[10]	validation_0-mae:7748.66987
[0]	validation_0-mae:12463.90565
[1]	validation_0-mae:11729.50273
[2]	validation_0-mae:11099.25300
[3]	validation_0-mae:10508.21112
[4]	validation_0-mae:9992.52439
[5]	validation_0-mae:9518.04089
[6]	validation_0-mae:9112.93936
[7]	validation_0-mae:8723.62484
[8]	validation_0-mae:8377.52392
[9]	validation_0-mae:8023.26028
[10]	validation_0-mae:7707.25356

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[0]	validation_0-mae:12398.85441
[1]	validation_0-mae:11642.27292
[2]	validation_0-mae:10938.24257
[3]	validation_0-mae:10271.28665
[4]	validation_0-mae:9703.07008
[5]	validation_0-mae:9176.22966
[6]	validation_0-mae:8712.59642
[7]	validation_0-mae:8296.82829
[8]	validation_0-mae:7926.42276
[9]	validation_0-mae:7571.38226
[10]	validation_0-mae:7257.73710
[11]	validation_0-mae:6954.79109
[12]	validation_0-mae:6674.70397
[13]	validation_0-mae:6418.80651
[14]	validation_0-mae:6160.95238
[15]	validation_0-mae:5936.68156
[16]	validation_0-mae:5719.67394
[17]	validation_0-mae:5550.33822
[18]	validation_0-mae:5362.25331
[19]	validation_0-mae:5198.72669
[20]	validation_0-mae:5020.45790
[21]	validation_0-mae:4862.97761
[22]	validation_0-mae:4706.55148
[23]	validation_0-mae:4579.73164
[24]	validation_0-mae:4445.74409
[25]	validation_0-mae:4322.52596
[26]	validation_0-mae:4215.07127
[27]	validation_0-mae:4121.89874
[28]	validation_0-mae:4015.00051
[29]	validation_0-mae:3915.16684
[30]	validation_0-mae:3809.98594
[31]	validation_0-mae:3740.58217
[32]	validation_0-mae:3677.15249
[33]	validation_0-mae:3614.97361
[34]	validation_0-mae:3549.14111
[35]	validation_0-mae:3487.35587
[36]	validation_0-mae:3429.28436
[37]	validation_0-mae:3376.97566
[38]	validation_0-mae:3326.69647
[39]	validation_0-mae:3288.88237
[40]	validation_0-mae:3242.93335
[41]	validation_0-mae:3203.28570
[42]	validation_0-mae:3160.02155
[43]	validation_0-mae:3123.11769
[44]	validation_0-mae:3085.21973
[45]	validation_0-mae:3056.51226
[46]	validation_0-mae:3028.81672
[47]	validation_0-mae:3005.02265
[48]	validation_0-mae:2963.01626
[49]	validation_0-mae:2939.87279
[50]	validation_0-mae:2910.63212
[51]	validation_0-mae:2883.92507
[52]	validation_0-mae:2859.32352
[53]	validation_0-mae:2840.04277
[54]	validation_0-mae:2822.25992
[55]	validation_0-mae:2797.46449
[56]	validation_0-mae:2787.02819
[57]	validation_0-mae:2776.73352
[58]	validation_0-mae:2762.47040
[59]	validation_0-mae:2724.52261
[60]	validation_0-mae:2698.67236
[61]	validation_0-mae:2681.01852
[62]	validation_0-mae:2663.70248
[63]	validation_0-mae:2638.06871
[64]	validation_0-mae:2630.82585
[65]	validation_0-mae:2622.08764
[66]	validation_0-mae:2607.78912
[67]	validation_0-mae:2595.96937
[68]	validation_0-mae:2587.25871
[69]	validation_0-mae:2577.41121
[70]	validation_0-mae:2565.86619
[71]	validation_0-mae:2553.40808
[72]	validation_0-mae:2546.29135
[73]	validation_0-mae:2535.17433
[74]	validation_0-mae:2516.73365
[75]	validation_0-mae:2500.85181
[76]	validation_0-mae:2495.52081
[77]	validation_0-mae:2486.39333
[78]	validation_0-mae:2477.32628
[79]	validation_0-mae:2465.88037
[80]	validation_0-mae:2451.41989
[81]	validation_0-mae:2444.36230
[82]	validation_0-mae:2437.60486
[83]	validation_0-mae:2426.25261
[84]	validation_0-mae:2420.94850
[85]	validation_0-mae:2415.84039
[86]	validation_0-mae:2408.42403
[87]	validation_0-mae:2394.50623
[88]	validation_0-mae:2387.13102
[89]	validation_0-mae:2380.22698
[90]	validation_0-mae:2374.68214
[91]	validation_0-mae:2368.49231
[92]	validation_0-mae:2368.18196
[93]	validation_0-mae:2360.33891
[94]	validation_0-mae:2359.48821
[95]	validation_0-mae:2353.56385
[96]	validation_0-mae:2350.12610
[97]	validation_0-mae:2345.52149
[98]	validation_0-mae:2337.44527
[99]	validation_0-mae:2330.96524
[100]	validation_0-mae:2326.76294
[101]	validation_0-mae:2320.36733
[102]	validation_0-mae:2312.87632
[103]	validation_0-mae:2312.56803
[104]	validation_0-mae:2307.92489
[105]	validation_0-mae:2304.46359
[106]	validation_0-mae:2300.99564
[107]	validation_0-mae:2298.81348
[108]	validation_0-mae:2293.03653
[109]	validation_0-mae:2289.85469
[110]	validation_0-mae:2285.43582
[111]	validation_0-mae:2280.20245
[112]	validation_0-mae:2280.32389
[113]	validation_0-mae:2276.38218
[114]	validation_0-mae:2275.80947
[115]	validation_0-mae:2274.46835
[116]	validation_0-mae:2273.29854
[117]	validation_0-mae:2272.32476
[118]	validation_0-mae:2267.22240
[119]	validation_0-mae:2264.32703
[120]	validation_0-mae:2262.00839
[121]	validation_0-mae:2260.76907
[122]	validation_0-mae:2258.07610
[123]	validation_0-mae:2257.95590
[124]	validation_0-mae:2253.86737
[125]	validation_0-mae:2253.07226
[126]	validation_0-mae:2249.08654
[127]	validation_0-mae:2246.98094
[128]	validation_0-mae:2244.80634
[129]	validation_0-mae:2243.68074
[130]	validation_0-mae:2241.14789
[131]	validation_0-mae:2238.83582
[132]	validation_0-mae:2237.29906
[133]	validation_0-mae:2237.61514
[134]	validation_0-mae:2236.13161
[135]	validation_0-mae:2234.87218
[136]	validation_0-mae:2232.76893
[137]	validation_0-mae:2230.99191
[138]	validation_0-mae:2228.65448
[139]	validation_0-mae:2229.67731
[140]	validation_0-mae:2226.08708
[141]	validation_0-mae:2225.99782
[142]	validation_0-mae:2224.06376
[143]	validation_0-mae:2222.94042
[144]	validation_0-mae:2220.51492
[145]	validation_0-mae:2220.44376
[146]	validation_0-mae:2217.88843
[147]	validation_0-mae:2217.18373
[148]	validation_0-mae:2216.29535
[149]	validation_0-mae:2213.61636
[150]	validation_0-mae:2214.77543
[151]	validation_0-mae:2211.58206
[152]	validation_0-mae:2206.81118
[153]	validation_0-mae:2204.23144
[154]	validation_0-mae:2204.08920
[155]	validation_0-mae:2200.81655
[156]	validation_0-mae:2200.36075
[157]	validation_0-mae:2197.55738
[158]	validation_0-mae:2198.61716
[159]	validation_0-mae:2196.86951
[160]	validation_0-mae:2197.50727
[161]	validation_0-mae:2193.50056
[162]	validation_0-mae:2194.53333
[163]	validation_0-mae:2195.08973
[164]	validation_0-mae:2194.30034
[165]	validation_0-mae:2192.83913
[166]	validation_0-mae:2193.77373
[167]	validation_0-mae:2192.81279
[168]	validation_0-mae:2192.13973
[169]	validation_0-mae:2192.34005
[170]	validation_0-mae:2191.54420
[171]	validation_0-mae:2189.07853
[172]	validation_0-mae:2186.72730
[173]	validation_0-mae:2186.13695
[174]	validation_0-mae:2184.13588
[175]	validation_0-mae:2183.45533
[176]	validation_0-mae:2182.73172
[177]	validation_0-mae:2180.18895
[178]	validation_0-mae:2176.91990
[179]	validation_0-mae:2175.72284
[180]	validation_0-mae:2175.79400
[181]	validation_0-mae:2175.37709
[182]	validation_0-mae:2175.34166
[183]	validation_0-mae:2175.03023
[184]	validation_0-mae:2174.31813
[185]	validation_0-mae:2175.08236
[186]	validation_0-mae:2174.42290
[187]	validation_0-mae:2174.48678
[188]	validation_0-mae:2172.81648
[189]	validation_0-mae:2170.50319
[190]	validation_0-mae:2169.52720
[191]	validation_0-mae:2168.85809
[192]	validation_0-mae:2168.52604
[193]	validation_0-mae:2166.97939
[194]	validation_0-mae:2165.23185
[195]	validation_0-mae:2164.90678
[196]	validation_0-mae:2164.88479
[197]	validation_0-mae:2163.47555
[198]	validation_0-mae:2162.77397
[199]	validation_0-mae:2161.32933
[200]	validation_0-mae:2159.99154
[201]	validation_0-mae:2159.05698
[202]	validation_0-mae:2159.64044
[203]	validation_0-mae:2161.13403
[204]	validation_0-mae:2161.49673
[205]	validation_0-mae:2160.89501
[206]	validation_0-mae:2160.33575
[207]	validation_0-mae:2158.56076
[208]	validation_0-mae:2158.02747
[209]	validation_0-mae:2156.23042
[210]	validation_0-mae:2156.19924
[211]	validation_0-mae:2156.21479
[212]	validation_0-mae:2156.40052
[213]	validation_0-mae:2155.54963
[214]	validation_0-mae:2155.46115
[215]	validation_0-mae:2154.33362
[216]	validation_0-mae:2155.40357
[217]	validation_0-mae:2155.21406
[218]	validation_0-mae:2154.70060
[219]	validation_0-mae:2154.62446
[220]	validation_0-mae:2154.87867
[221]	validation_0-mae:2152.91942
[222]	validation_0-mae:2152.19254
[223]	validation_0-mae:2152.43615
[224]	validation_0-mae:2150.13239
[225]	validation_0-mae:2151.76110
[226]	validation_0-mae:2151.49835
[227]	validation_0-mae:2151.35338
[228]	validation_0-mae:2149.20098
[229]	validation_0-mae:2149.39539
[230]	validation_0-mae:2149.15112
[231]	validation_0-mae:2148.81619
[232]	validation_0-mae:2149.18763
[233]	validation_0-mae:2148.65557
[234]	validation_0-mae:2146.08071
[235]	validation_0-mae:2144.29422
[236]	validation_0-mae:2144.08680
[237]	validation_0-mae:2143.97356
[238]	validation_0-mae:2143.28789
[239]	validation_0-mae:2143.71942
[240]	validation_0-mae:2142.74548
[241]	validation_0-mae:2142.13782
[242]	validation_0-mae:2140.35177
[243]	validation_0-mae:2139.70107
[244]	validation_0-mae:2139.71844
[245]	validation_0-mae:2140.09820
[246]	validation_0-mae:2140.08063
[247]	validation_0-mae:2138.06754
[248]	validation_0-mae:2138.59690
[249]	validation_0-mae:2138.10276
[250]	validation_0-mae:2138.09058
[251]	validation_0-mae:2138.68594
[252]	validation_0-mae:2137.58667
[253]	validation_0-mae:2137.60532
[254]	validation_0-mae:2136.20573
[255]	validation_0-mae:2137.22415
[256]	validation_0-mae:2137.11485
[257]	validation_0-mae:2136.43531
[258]	validation_0-mae:2134.43986
[259]	validation_0-mae:2133.95678
[260]	validation_0-mae:2132.96202
[261]	validation_0-mae:2131.79753
[262]	validation_0-mae:2131.62116
[263]	validation_0-mae:2130.27410
[264]	validation_0-mae:2130.23710
[265]	validation_0-mae:2129.16662
[266]	validation_0-mae:2128.57074
[267]	validation_0-mae:2128.35759
[268]	validation_0-mae:2128.36634
[269]	validation_0-mae:2127.57584
[270]	validation_0-mae:2126.61657
[271]	validation_0-mae:2127.44486
[272]	validation_0-mae:2127.75589
[273]	validation_0-mae:2128.00067
[274]	validation_0-mae:2126.81315
[275]	validation_0-mae:2127.36518
[276]	validation_0-mae:2127.70106
[277]	validation_0-mae:2127.25187
[278]	validation_0-mae:2127.35755
[279]	validation_0-mae:2126.89763
[280]	validation_0-mae:2125.32889
[281]	validation_0-mae:2125.29653
[282]	validation_0-mae:2124.99653
[283]	validation_0-mae:2125.19891
[284]	validation_0-mae:2125.03418
[285]	validation_0-mae:2124.96365
[286]	validation_0-mae:2124.25961
[287]	validation_0-mae:2123.07600
[288]	validation_0-mae:2122.77659
[289]	validation_0-mae:2122.51758
[290]	validation_0-mae:2122.67414
[291]	validation_0-mae:2122.33319
[292]	validation_0-mae:2122.06663
[293]	validation_0-mae:2122.12643
[294]	validation_0-mae:2122.58931
[295]	validation_0-mae:2122.20745
[296]	validation_0-mae:2122.62044
[297]	validation_0-mae:2121.93919
[298]	validation_0-mae:2122.13611
[299]	validation_0-mae:2122.22739
[300]	validation_0-mae:2120.81219
[301]	validation_0-mae:2120.62191
[302]	validation_0-mae:2121.30660
[303]	validation_0-mae:2119.47126
[304]	validation_0-mae:2119.66704
[305]	validation_0-mae:2119.76596
[306]	validation_0-mae:2120.54028
[307]	validation_0-mae:2120.52561
[308]	validation_0-mae:2119.75791
[309]	validation_0-mae:2120.11781
[310]	validation_0-mae:2119.90155
[311]	validation_0-mae:2118.41606
[312]	validation_0-mae:2116.90696
[313]	validation_0-mae:2116.82346
[314]	validation_0-mae:2117.09163
[315]	validation_0-mae:2117.54884
[316]	validation_0-mae:2117.37818
[317]	validation_0-mae:2118.05299
[318]	validation_0-mae:2118.14725
[319]	validation_0-mae:2117.57954
[320]	validation_0-mae:2117.57082
[321]	validation_0-mae:2117.51389
[322]	validation_0-mae:2117.88238
[323]	validation_0-mae:2118.05539
[324]	validation_0-mae:2117.94092
[325]	validation_0-mae:2117.42123
[326]	validation_0-mae:2116.88358
[327]	validation_0-mae:2116.49344
[328]	validation_0-mae:2116.81785
[329]	validation_0-mae:2116.28557
[330]	validation_0-mae:2116.16719
[331]	validation_0-mae:2115.16518
[332]	validation_0-mae:2114.95837
[333]	validation_0-mae:2114.92768
[334]	validation_0-mae:2114.06308
[335]	validation_0-mae:2113.99142
[336]	validation_0-mae:2113.60971
[337]	validation_0-mae:2113.53266
[338]	validation_0-mae:2113.38975
[339]	validation_0-mae:2113.02893
[340]	validation_0-mae:2113.35631
[341]	validation_0-mae:2112.71800
[342]	validation_0-mae:2112.73933
[343]	validation_0-mae:2112.50040
[344]	validation_0-mae:2112.91338
[345]	validation_0-mae:2112.17998
[346]	validation_0-mae:2111.51546
[347]	validation_0-mae:2111.69885
[348]	validation_0-mae:2112.49402
[349]	validation_0-mae:2112.40299
[350]	validation_0-mae:2113.19631
[351]	validation_0-mae:2113.05783
[352]	validation_0-mae:2111.56003
[353]	validation_0-mae:2111.58326
[354]	validation_0-mae:2111.16359
[355]	validation_0-mae:2111.00123
[356]	validation_0-mae:2110.53060
[357]	validation_0-mae:2109.77942
[358]	validation_0-mae:2109.45087
[359]	validation_0-mae:2108.98942
[360]	validation_0-mae:2108.93513
[361]	validation_0-mae:2108.56786
[362]	validation_0-mae:2107.84347
[363]	validation_0-mae:2107.98894
[364]	validation_0-mae:2108.96398
[365]	validation_0-mae:2107.71564
[366]	validation_0-mae:2107.75128
[367]	validation_0-mae:2107.97238
[368]	validation_0-mae:2108.71943
[369]	validation_0-mae:2108.38378
[370]	validation_0-mae:2108.45719
[371]	validation_0-mae:2107.59677
[372]	validation_0-mae:2108.02838
[373]	validation_0-mae:2108.46997
[374]	validation_0-mae:2108.78290
[375]	validation_0-mae:2107.92370
[376]	validation_0-mae:2108.30057
[377]	validation_0-mae:2108.64080
[378]	validation_0-mae:2108.84170
[379]	validation_0-mae:2108.93893
[380]	validation_0-mae:2108.91823
[381]	validation_0-mae:2109.38482
[382]	validation_0-mae:2110.07897
[383]	validation_0-mae:2110.42153
[384]	validation_0-mae:2110.43118
[385]	validation_0-mae:2110.47561
[386]	validation_0-mae:2110.42646
[387]	validation_0-mae:2110.91973
[388]	validation_0-mae:2110.66839
[389]	validation_0-mae:2111.03565
[390]	validation_0-mae:2111.01235
[391]	validation_0-mae:2110.30691
[392]	validation_0-mae:2110.26257
[393]	validation_0-mae:2111.15102
[394]	validation_0-mae:2110.73104
[395]	validation_0-mae:2111.46550
[396]	validation_0-mae:2111.46791
[397]	validation_0-mae:2111.65294
[398]	validation_0-mae:2111.75619
[399]	validation_0-mae:2112.20248
[400]	validation_0-mae:2112.49171
[401]	validation_0-mae:2112.32916
[402]	validation_0-mae:2111.80065
[403]	validation_0-mae:2112.16192
[404]	validation_0-mae:2111.92892
[405]	validation_0-mae:2111.86083
[406]	validation_0-mae:2111.44065
[407]	validation_0-mae:2111.36183
[408]	validation_0-mae:2111.26636
[409]	validation_0-mae:2111.47819
[410]	validation_0-mae:2111.67122
[411]	validation_0-mae:2112.07630
[412]	validation_0-mae:2112.44950
[413]	validation_0-mae:2112.71153
[414]	validation_0-mae:2113.10813
[415]	validation_0-mae:2113.26644
[416]	validation_0-mae:2113.77391
[417]	validation_0-mae:2113.49352
[418]	validation_0-mae:2113.37433
[419]	validation_0-mae:2113.58332
[420]	validation_0-mae:2113.52974
[421]	validation_0-mae:2112.76619
[422]	validation_0-mae:2113.09915
[423]	validation_0-mae:2113.16353
[424]	validation_0-mae:2112.70518
[425]	validation_0-mae:2112.65753
[426]	validation_0-mae:2112.30431
[427]	validation_0-mae:2112.42067
[428]	validation_0-mae:2112.76874
[429]	validation_0-mae:2113.03923
[430]	validation_0-mae:2113.38203
[431]	validation_0-mae:2113.02889
[432]	validation_0-mae:2112.92304
[433]	validation_0-mae:2113.33235
[434]	validation_0-mae:2112.52938
[435]	validation_0-mae:2112.54494
[436]	validation_0-mae:2111.06948
[437]	validation_0-mae:2110.32184
[438]	validation_0-mae:2110.38289
[439]	validation_0-mae:2110.38685
[440]	validation_0-mae:2110.59270
[441]	validation_0-mae:2110.97837
[442]	validation_0-mae:2111.08607
[443]	validation_0-mae:2110.95927
[444]	validation_0-mae:2110.99227
[445]	validation_0-mae:2111.04442
[446]	validation_0-mae:2111.13059
[447]	validation_0-mae:2110.96539
[448]	validation_0-mae:2111.47369
[449]	validation_0-mae:2111.51046
[450]	validation_0-mae:2111.35434
[451]	validation_0-mae:2111.19760
[452]	validation_0-mae:2110.79734
[453]	validation_0-mae:2111.08294
[454]	validation_0-mae:2111.12835
[455]	validation_0-mae:2111.54790
[456]	validation_0-mae:2111.55573
[457]	validation_0-mae:2111.59917
[458]	validation_0-mae:2111.38665
[459]	validation_0-mae:2110.88565
[460]	validation_0-mae:2110.98741
[461]	validation_0-mae:2110.05297
[462]	validation_0-mae:2109.66690
[463]	validation_0-mae:2110.16394
[464]	validation_0-mae:2109.80763
[465]	validation_0-mae:2109.55479
[466]	validation_0-mae:2109.79393
[467]	validation_0-mae:2109.70629
[468]	validation_0-mae:2109.67248
[469]	validation_0-mae:2109.33883
[470]	validation_0-mae:2109.33249
[471]	validation_0-mae:2109.57183
[472]	validation_0-mae:2109.92712
[473]	validation_0-mae:2110.00492
[474]	validation_0-mae:2110.78621
[475]	validation_0-mae:2110.40254
[476]	validation_0-mae:2110.62334
[477]	validation_0-mae:2109.68841
[478]	validation_0-mae:2109.75784
[479]	validation_0-mae:2109.47082
[480]	validation_0-mae:2108.57148
[481]	validation_0-mae:2108.38632
[482]	validation_0-mae:2108.04913
[483]	validation_0-mae:2108.26122
[484]	validation_0-mae:2108.31322
[485]	validation_0-mae:2107.76038
[486]	validation_0-mae:2107.95574
[487]	validation_0-mae:2107.92156
[488]	validation_0-mae:2108.40660
[0]	validation_0-mae:12381.15229
[1]	validation_0-mae:11600.94436
[2]	validation_0-mae:10888.42410
[3]	validation_0-mae:10248.00393
[4]	validation_0-mae:9680.40633
[5]	validation_0-mae:9143.36610
[6]	validation_0-mae:8692.61654
[7]	validation_0-mae:8285.68091
[8]	validation_0-mae:7901.04385
[9]	validation_0-mae:7556.04474
[10]	validation_0-mae:7247.60832
[11]	validation_0-mae:6950.27419
[12]	validation_0-mae:6658.18274
[13]	validation_0-mae:6404.03825
[14]	validation_0-mae:6134.42219
[15]	validation_0-mae:5911.27786
[16]	validation_0-mae:5713.44921
[17]	validation_0-mae:5510.75339
[18]	validation_0-mae:5312.03395
[19]	validation_0-mae:5125.54510
[20]	validation_0-mae:4969.63356
[21]	validation_0-mae:4813.16995
[22]	validation_0-mae:4684.95544
[23]	validation_0-mae:4549.91250
[24]	validation_0-mae:4428.46969
[25]	validation_0-mae:4309.48607
[26]	validation_0-mae:4199.82213
[27]	validation_0-mae:4091.52873
[28]	validation_0-mae:3995.12544
[29]	validation_0-mae:3898.53665
[30]	validation_0-mae:3813.33733
[31]	validation_0-mae:3744.22146
[32]	validation_0-mae:3668.97000
[33]	validation_0-mae:3604.84851
[34]	validation_0-mae:3541.94354
[35]	validation_0-mae:3490.86536
[36]	validation_0-mae:3445.13009

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[37]	validation_0-mae:3386.62007
[38]	validation_0-mae:3343.48964
[39]	validation_0-mae:3300.24862
[40]	validation_0-mae:3244.84952
[41]	validation_0-mae:3199.85957
[42]	validation_0-mae:3161.55205
[43]	validation_0-mae:3117.71084
[44]	validation_0-mae:3087.75529
[45]	validation_0-mae:3060.15151
[46]	validation_0-mae:3030.56168
[47]	validation_0-mae:3000.59638
[48]	validation_0-mae:2959.55207
[49]	validation_0-mae:2936.33355
[50]	validation_0-mae:2899.43779
[51]	validation_0-mae:2879.68576
[52]	validation_0-mae:2863.53496
[53]	validation_0-mae:2840.75285
[54]	validation_0-mae:2824.46594
[55]	validation_0-mae:2791.15370
[56]	validation_0-mae:2771.26331
[57]	validation_0-mae:2756.23661
[58]	validation_0-mae:2745.78674
[59]	validation_0-mae:2733.70920
[60]	validation_0-mae:2705.23815
[61]	validation_0-mae:2689.33667
[62]	validation_0-mae:2682.49341
[63]	validation_0-mae:2662.03607
[64]	validation_0-mae:2649.08303
[65]	validation_0-mae:2640.35651
[66]	validation_0-mae:2632.16519
[67]	validation_0-mae:2611.27636
[68]	validation_0-mae:2606.24328
[69]	validation_0-mae:2598.76547
[70]	validation_0-mae:2588.42067
[71]	validation_0-mae:2576.06920
[72]	validation_0-mae:2560.84129
[73]	validation_0-mae:2550.68587
[74]	validation_0-mae:2535.25637
[75]	validation_0-mae:2525.94665
[76]	validation_0-mae:2517.10901
[77]	validation_0-mae:2508.00582
[78]	validation_0-mae:2500.16797
[79]	validation_0-mae:2493.19626
[80]	validation_0-mae:2483.28106
[81]	validation_0-mae:2478.86347
[82]	validation_0-mae:2472.00221
[83]	validation_0-mae:2464.97306
[84]	validation_0-mae:2457.46458
[85]	validation_0-mae:2442.91998
[86]	validation_0-mae:2436.97505
[87]	validation_0-mae:2428.99491
[88]	validation_0-mae:2414.57150
[89]	validation_0-mae:2402.50567
[90]	validation_0-mae:2399.69928
[91]	validation_0-mae:2391.20848
[92]	validation_0-mae:2388.26068
[93]	validation_0-mae:2378.49382
[94]	validation_0-mae:2370.91698
[95]	validation_0-mae:2362.40869
[96]	validation_0-mae:2357.30781
[97]	validation_0-mae:2354.21145
[98]	validation_0-mae:2350.44467
[99]	validation_0-mae:2340.02765
[100]	validation_0-mae:2335.12148
[101]	validation_0-mae:2332.76629
[102]	validation_0-mae:2328.35514
[103]	validation_0-mae:2320.18224
[104]	validation_0-mae:2318.39071
[105]	validation_0-mae:2313.02888
[106]	validation_0-mae:2306.59930
[107]	validation_0-mae:2306.46893
[108]	validation_0-mae:2302.40820
[109]	validation_0-mae:2296.34763
[110]	validation_0-mae:2294.05257
[111]	validation_0-mae:2290.84068
[112]	validation_0-mae:2288.25715
[113]	validation_0-mae:2285.61019
[114]	validation_0-mae:2280.93496
[115]	validation_0-mae:2274.18650
[116]	validation_0-mae:2267.93085
[117]	validation_0-mae:2263.99031
[118]	validation_0-mae:2260.06208
[119]	validation_0-mae:2258.40401
[120]	validation_0-mae:2257.04190
[121]	validation_0-mae:2252.72715
[122]	validation_0-mae:2248.42110
[123]	validation_0-mae:2249.75721
[124]	validation_0-mae:2249.39839
[125]	validation_0-mae:2246.09097
[126]	validation_0-mae:2244.00629
[127]	validation_0-mae:2241.10206
[128]	validation_0-mae:2237.46646
[129]	validation_0-mae:2236.80779
[130]	validation_0-mae:2230.79203
[131]	validation_0-mae:2229.30051
[132]	validation_0-mae:2226.55391
[133]	validation_0-mae:2223.99174
[134]	validation_0-mae:2221.11158
[135]	validation_0-mae:2216.65428
[136]	validation_0-mae:2215.62555
[137]	validation_0-mae:2210.86298
[138]	validation_0-mae:2209.59297
[139]	validation_0-mae:2206.87451
[140]	validation_0-mae:2203.10953
[141]	validation_0-mae:2203.16849
[142]	validation_0-mae:2200.24851
[143]	validation_0-mae:2199.39866
[144]	validation_0-mae:2195.85518
[145]	validation_0-mae:2196.62278
[146]	validation_0-mae:2195.18654
[147]	validation_0-mae:2194.31902
[148]	validation_0-mae:2194.26069
[149]	validation_0-mae:2193.06704
[150]	validation_0-mae:2190.82663
[151]	validation_0-mae:2191.15393
[152]	validation_0-mae:2191.43035
[153]	validation_0-mae:2189.47505
[154]	validation_0-mae:2188.29891
[155]	validation_0-mae:2188.31386
[156]	validation_0-mae:2187.15800
[157]	validation_0-mae:2183.77181
[158]	validation_0-mae:2184.08274
[159]	validation_0-mae:2182.42912
[160]	validation_0-mae:2181.50093
[161]	validation_0-mae:2181.47396
[162]	validation_0-mae:2181.24212
[163]	validation_0-mae:2181.67214
[164]	validation_0-mae:2179.15324
[165]	validation_0-mae:2179.23333
[166]	validation_0-mae:2178.61502
[167]	validation_0-mae:2177.84469
[168]	validation_0-mae:2177.75556
[169]	validation_0-mae:2176.77894
[170]	validation_0-mae:2176.89598
[171]	validation_0-mae:2176.85864
[172]	validation_0-mae:2177.39888
[173]	validation_0-mae:2176.15610
[174]	validation_0-mae:2173.91436
[175]	validation_0-mae:2171.65010
[176]	validation_0-mae:2170.88054
[177]	validation_0-mae:2167.68103
[178]	validation_0-mae:2167.71241
[179]	validation_0-mae:2163.19951
[180]	validation_0-mae:2160.07007
[181]	validation_0-mae:2159.28724
[182]	validation_0-mae:2157.21637
[183]	validation_0-mae:2155.89240
[184]	validation_0-mae:2155.74797
[185]	validation_0-mae:2155.78064
[186]	validation_0-mae:2155.70571
[187]	validation_0-mae:2155.67556
[188]	validation_0-mae:2154.52923
[189]	validation_0-mae:2154.62067
[190]	validation_0-mae:2154.82074
[191]	validation_0-mae:2154.21525
[192]	validation_0-mae:2153.52169
[193]	validation_0-mae:2153.04258
[194]	validation_0-mae:2153.13907
[195]	validation_0-mae:2153.09576
[196]	validation_0-mae:2148.45286
[197]	validation_0-mae:2148.90195
[198]	validation_0-mae:2149.46676
[199]	validation_0-mae:2150.45012
[200]	validation_0-mae:2148.33548
[201]	validation_0-mae:2147.39255
[202]	validation_0-mae:2147.83825
[203]	validation_0-mae:2147.59488
[204]	validation_0-mae:2148.55501
[205]	validation_0-mae:2148.80556
[206]	validation_0-mae:2148.16503
[207]	validation_0-mae:2147.90581
[208]	validation_0-mae:2147.03323
[209]	validation_0-mae:2147.25623
[210]	validation_0-mae:2145.95398
[211]	validation_0-mae:2144.96420
[212]	validation_0-mae:2145.11753
[213]	validation_0-mae:2145.09053
[214]	validation_0-mae:2144.37858
[215]	validation_0-mae:2144.77160
[216]	validation_0-mae:2144.27148
[217]	validation_0-mae:2144.50556
[218]	validation_0-mae:2144.53310
[219]	validation_0-mae:2143.13345
[220]	validation_0-mae:2143.39157
[221]	validation_0-mae:2143.20393
[222]	validation_0-mae:2143.25340
[223]	validation_0-mae:2142.91328
[224]	validation_0-mae:2141.88909
[225]	validation_0-mae:2142.15485
[226]	validation_0-mae:2142.31773
[227]	validation_0-mae:2143.17630
[228]	validation_0-mae:2143.91783
[229]	validation_0-mae:2144.53974
[230]	validation_0-mae:2142.53743
[231]	validation_0-mae:2142.67944
[232]	validation_0-mae:2141.21693
[233]	validation_0-mae:2140.93787
[234]	validation_0-mae:2139.47022
[235]	validation_0-mae:2138.88969
[236]	validation_0-mae:2139.91136
[237]	validation_0-mae:2140.57430
[238]	validation_0-mae:2140.21447
[239]	validation_0-mae:2139.82365
[240]	validation_0-mae:2140.64700
[241]	validation_0-mae:2140.10701
[242]	validation_0-mae:2138.59270
[243]	validation_0-mae:2135.92802
[244]	validation_0-mae:2135.05807
[245]	validation_0-mae:2133.56172
[246]	validation_0-mae:2132.15347
[247]	validation_0-mae:2132.08157
[248]	validation_0-mae:2131.86477
[249]	validation_0-mae:2131.95514
[250]	validation_0-mae:2131.74719
[251]	validation_0-mae:2131.87068
[252]	validation_0-mae:2131.87422
[253]	validation_0-mae:2131.54262
[254]	validation_0-mae:2130.62586
[255]	validation_0-mae:2130.21115
[256]	validation_0-mae:2129.63411
[257]	validation_0-mae:2129.66944
[258]	validation_0-mae:2129.35428
[259]	validation_0-mae:2128.57610
[260]	validation_0-mae:2128.73935
[261]	validation_0-mae:2128.61720
[262]	validation_0-mae:2127.76527
[263]	validation_0-mae:2127.42485
[264]	validation_0-mae:2125.95964
[265]	validation_0-mae:2126.38692
[266]	validation_0-mae:2124.88952
[267]	validation_0-mae:2124.28977
[268]	validation_0-mae:2122.88495
[269]	validation_0-mae:2122.87101
[270]	validation_0-mae:2123.24701
[271]	validation_0-mae:2122.68588
[272]	validation_0-mae:2122.65432
[273]	validation_0-mae:2121.49294
[274]	validation_0-mae:2120.51498
[275]	validation_0-mae:2119.23681
[276]	validation_0-mae:2118.76880
[277]	validation_0-mae:2118.55481
[278]	validation_0-mae:2118.45658
[279]	validation_0-mae:2118.10852
[280]	validation_0-mae:2118.32146
[281]	validation_0-mae:2117.64154
[282]	validation_0-mae:2117.57022
[283]	validation_0-mae:2116.25166
[284]	validation_0-mae:2117.11886
[285]	validation_0-mae:2117.57306
[286]	validation_0-mae:2117.16213
[287]	validation_0-mae:2116.43604
[288]	validation_0-mae:2116.04370
[289]	validation_0-mae:2116.02884
[290]	validation_0-mae:2116.85319
[291]	validation_0-mae:2115.36496
[292]	validation_0-mae:2114.49480
[293]	validation_0-mae:2114.92499
[294]	validation_0-mae:2114.06757
[295]	validation_0-mae:2113.65934
[296]	validation_0-mae:2113.25397
[297]	validation_0-mae:2112.75146
[298]	validation_0-mae:2112.76769
[299]	validation_0-mae:2113.06261
[300]	validation_0-mae:2113.02974
[301]	validation_0-mae:2112.73433
[302]	validation_0-mae:2112.58237
[303]	validation_0-mae:2112.85399
[304]	validation_0-mae:2112.90006
[305]	validation_0-mae:2113.16912
[306]	validation_0-mae:2113.04281
[307]	validation_0-mae:2111.81586
[308]	validation_0-mae:2111.92437
[309]	validation_0-mae:2111.76153
[310]	validation_0-mae:2112.28810
[311]	validation_0-mae:2111.61320
[312]	validation_0-mae:2111.59120
[313]	validation_0-mae:2110.67378
[314]	validation_0-mae:2111.43431
[315]	validation_0-mae:2112.11963
[316]	validation_0-mae:2112.07164
[317]	validation_0-mae:2112.00105
[318]	validation_0-mae:2111.91630
[319]	validation_0-mae:2111.67413
[320]	validation_0-mae:2112.22328
[321]	validation_0-mae:2111.80261
[322]	validation_0-mae:2112.33305
[323]	validation_0-mae:2111.41345
[324]	validation_0-mae:2112.12562
[325]	validation_0-mae:2112.12288
[326]	validation_0-mae:2111.53619
[327]	validation_0-mae:2110.60564
[328]	validation_0-mae:2109.91444
[329]	validation_0-mae:2108.17880
[330]	validation_0-mae:2108.77162
[331]	validation_0-mae:2107.59199
[332]	validation_0-mae:2106.57203
[333]	validation_0-mae:2106.56056
[334]	validation_0-mae:2106.53106
[335]	validation_0-mae:2106.27107
[336]	validation_0-mae:2106.34210
[337]	validation_0-mae:2106.89857
[338]	validation_0-mae:2106.71087
[339]	validation_0-mae:2106.94722
[340]	validation_0-mae:2106.64800
[341]	validation_0-mae:2106.66586
[342]	validation_0-mae:2106.69653
[343]	validation_0-mae:2106.67663
[344]	validation_0-mae:2106.15700
[345]	validation_0-mae:2106.29238
[346]	validation_0-mae:2106.10272
[347]	validation_0-mae:2106.16512
[348]	validation_0-mae:2105.62689
[349]	validation_0-mae:2105.01353
[350]	validation_0-mae:2105.62488
[351]	validation_0-mae:2105.92952
[352]	validation_0-mae:2105.64460
[353]	validation_0-mae:2105.61876
[354]	validation_0-mae:2106.47766
[355]	validation_0-mae:2106.86825
[356]	validation_0-mae:2106.03853
[357]	validation_0-mae:2105.54638
[358]	validation_0-mae:2103.78256
[359]	validation_0-mae:2102.67184
[360]	validation_0-mae:2102.20351
[361]	validation_0-mae:2101.13176
[362]	validation_0-mae:2101.49902
[363]	validation_0-mae:2101.73244
[364]	validation_0-mae:2100.82658
[365]	validation_0-mae:2100.19832
[366]	validation_0-mae:2099.16488
[367]	validation_0-mae:2098.14835
[368]	validation_0-mae:2097.56965
[369]	validation_0-mae:2097.61513
[370]	validation_0-mae:2096.85727
[371]	validation_0-mae:2096.73432
[372]	validation_0-mae:2096.77013
[373]	validation_0-mae:2097.13903
[374]	validation_0-mae:2097.02457
[375]	validation_0-mae:2096.56717
[376]	validation_0-mae:2097.34142
[377]	validation_0-mae:2096.79660
[378]	validation_0-mae:2096.65872
[379]	validation_0-mae:2096.44309
[380]	validation_0-mae:2096.09834
[381]	validation_0-mae:2095.95747
[382]	validation_0-mae:2095.86402
[383]	validation_0-mae:2095.81827
[384]	validation_0-mae:2096.07168
[385]	validation_0-mae:2095.86060
[386]	validation_0-mae:2095.92324
[387]	validation_0-mae:2096.24974
[388]	validation_0-mae:2095.78293
[389]	validation_0-mae:2094.00329
[390]	validation_0-mae:2093.98484
[391]	validation_0-mae:2093.00144
[392]	validation_0-mae:2093.01248
[393]	validation_0-mae:2092.85160
[394]	validation_0-mae:2092.56702
[395]	validation_0-mae:2091.09893
[396]	validation_0-mae:2090.91944
[397]	validation_0-mae:2091.05142
[398]	validation_0-mae:2091.99128
[399]	validation_0-mae:2091.77561
[400]	validation_0-mae:2091.37861
[401]	validation_0-mae:2091.30846
[402]	validation_0-mae:2090.92105
[403]	validation_0-mae:2090.99961
[404]	validation_0-mae:2090.50266
[405]	validation_0-mae:2090.46496
[406]	validation_0-mae:2090.39626
[407]	validation_0-mae:2089.35039
[408]	validation_0-mae:2088.75511
[409]	validation_0-mae:2088.74270
[410]	validation_0-mae:2088.30995
[411]	validation_0-mae:2088.63200
[412]	validation_0-mae:2088.34971
[413]	validation_0-mae:2088.45145
[414]	validation_0-mae:2087.40988
[415]	validation_0-mae:2086.95942
[416]	validation_0-mae:2086.69592
[417]	validation_0-mae:2086.37544
[418]	validation_0-mae:2086.76355
[419]	validation_0-mae:2086.81859
[420]	validation_0-mae:2087.24426
[421]	validation_0-mae:2087.07359
[422]	validation_0-mae:2087.08182
[423]	validation_0-mae:2087.10267
[424]	validation_0-mae:2087.21538
[425]	validation_0-mae:2086.90813
[426]	validation_0-mae:2087.06294
[427]	validation_0-mae:2086.59486
[428]	validation_0-mae:2086.72408
[429]	validation_0-mae:2086.93434
[430]	validation_0-mae:2086.55254
[431]	validation_0-mae:2085.77860
[432]	validation_0-mae:2085.57607
[433]	validation_0-mae:2086.13506
[434]	validation_0-mae:2086.07218
[435]	validation_0-mae:2086.18072
[436]	validation_0-mae:2085.80110
[437]	validation_0-mae:2085.86682
[438]	validation_0-mae:2085.92593
[439]	validation_0-mae:2086.35244
[440]	validation_0-mae:2086.01340
[441]	validation_0-mae:2086.58627
[442]	validation_0-mae:2086.34391
[443]	validation_0-mae:2086.08485
[444]	validation_0-mae:2085.73558
[445]	validation_0-mae:2085.52257
[446]	validation_0-mae:2085.41931
[447]	validation_0-mae:2085.63565
[448]	validation_0-mae:2085.90753
[449]	validation_0-mae:2085.83932
[450]	validation_0-mae:2085.54430
[451]	validation_0-mae:2085.97799
[452]	validation_0-mae:2086.38518
[453]	validation_0-mae:2086.24360
[454]	validation_0-mae:2086.47765
[455]	validation_0-mae:2086.34942
[456]	validation_0-mae:2086.13768
[457]	validation_0-mae:2085.74474
[458]	validation_0-mae:2085.29195
[459]	validation_0-mae:2085.44654
[460]	validation_0-mae:2085.67795
[461]	validation_0-mae:2085.72040
[462]	validation_0-mae:2086.06719
[463]	validation_0-mae:2086.00226
[464]	validation_0-mae:2086.19413
[465]	validation_0-mae:2086.80012
[466]	validation_0-mae:2086.98582
[467]	validation_0-mae:2086.52192
[468]	validation_0-mae:2086.19914
[469]	validation_0-mae:2086.44671
[470]	validation_0-mae:2086.71160
[471]	validation_0-mae:2086.66682
[472]	validation_0-mae:2087.02292
[473]	validation_0-mae:2086.81532
[474]	validation_0-mae:2086.27802
[475]	validation_0-mae:2084.80147
[476]	validation_0-mae:2084.03019
[477]	validation_0-mae:2083.19288
[478]	validation_0-mae:2082.72119
[479]	validation_0-mae:2082.57638
[480]	validation_0-mae:2082.75020
[481]	validation_0-mae:2083.15446
[482]	validation_0-mae:2083.32674
[483]	validation_0-mae:2083.34335
[484]	validation_0-mae:2082.97869
[485]	validation_0-mae:2082.09857
[486]	validation_0-mae:2082.41210
[487]	validation_0-mae:2081.77019
[488]	validation_0-mae:2081.16161
[489]	validation_0-mae:2080.77931
[490]	validation_0-mae:2080.99801
[491]	validation_0-mae:2081.32897
[492]	validation_0-mae:2081.40607
[493]	validation_0-mae:2081.49491
[494]	validation_0-mae:2081.39509
[495]	validation_0-mae:2081.58847
[496]	validation_0-mae:2081.70129
[497]	validation_0-mae:2080.72040
[498]	validation_0-mae:2081.09894
[499]	validation_0-mae:2080.91148
[500]	validation_0-mae:2080.65815
[501]	validation_0-mae:2080.48745
[502]	validation_0-mae:2079.85710
[503]	validation_0-mae:2079.97965
[504]	validation_0-mae:2079.93158
[505]	validation_0-mae:2079.85040
[506]	validation_0-mae:2079.64575
[507]	validation_0-mae:2079.34272
[508]	validation_0-mae:2079.69457
[509]	validation_0-mae:2079.97841
[510]	validation_0-mae:2080.19647
[511]	validation_0-mae:2080.44188
[512]	validation_0-mae:2080.42360
[513]	validation_0-mae:2080.16705
[514]	validation_0-mae:2080.30116
[515]	validation_0-mae:2080.59319
[516]	validation_0-mae:2080.63527
[517]	validation_0-mae:2080.45112
[518]	validation_0-mae:2080.73448
[519]	validation_0-mae:2080.13920
[520]	validation_0-mae:2079.86067
[521]	validation_0-mae:2079.03442
[522]	validation_0-mae:2078.66613
[523]	validation_0-mae:2078.72280
[524]	validation_0-mae:2078.74659
[525]	validation_0-mae:2078.63651
[526]	validation_0-mae:2078.95403
[527]	validation_0-mae:2079.02193
[528]	validation_0-mae:2079.25804
[529]	validation_0-mae:2079.46709
[530]	validation_0-mae:2079.24702
[531]	validation_0-mae:2079.22177
[532]	validation_0-mae:2079.47640
[533]	validation_0-mae:2079.41878
[534]	validation_0-mae:2079.43963
[535]	validation_0-mae:2079.26642
[536]	validation_0-mae:2079.29582
[537]	validation_0-mae:2079.47269
[538]	validation_0-mae:2079.17423
[539]	validation_0-mae:2079.33315
[540]	validation_0-mae:2079.42755
[541]	validation_0-mae:2079.22798
[542]	validation_0-mae:2078.95356
[543]	validation_0-mae:2078.11256
[544]	validation_0-mae:2077.65230
[545]	validation_0-mae:2077.27965
[546]	validation_0-mae:2077.15593
[547]	validation_0-mae:2077.02181
[548]	validation_0-mae:2076.46807
[549]	validation_0-mae:2076.29569
[550]	validation_0-mae:2076.59902
[551]	validation_0-mae:2076.25699
[552]	validation_0-mae:2076.23021
[553]	validation_0-mae:2076.12126
[554]	validation_0-mae:2075.65945
[555]	validation_0-mae:2075.92568
[556]	validation_0-mae:2075.64387
[557]	validation_0-mae:2075.50078
[558]	validation_0-mae:2075.22754
[559]	validation_0-mae:2075.46005
[560]	validation_0-mae:2075.16585
[561]	validation_0-mae:2075.03328
[562]	validation_0-mae:2075.21811
[563]	validation_0-mae:2074.84114
[564]	validation_0-mae:2075.00900
[565]	validation_0-mae:2074.75388
[566]	validation_0-mae:2074.73951
[567]	validation_0-mae:2074.79510
[568]	validation_0-mae:2075.21500
[569]	validation_0-mae:2075.16039
[570]	validation_0-mae:2075.22346
[571]	validation_0-mae:2075.04738
[572]	validation_0-mae:2075.02539
[573]	validation_0-mae:2074.62744
[574]	validation_0-mae:2074.82896
[575]	validation_0-mae:2074.37957
[576]	validation_0-mae:2074.35413
[577]	validation_0-mae:2073.69483
[578]	validation_0-mae:2073.65369
[579]	validation_0-mae:2072.52890
[580]	validation_0-mae:2072.36377
[581]	validation_0-mae:2072.41064
[582]	validation_0-mae:2072.12289
[583]	validation_0-mae:2072.52367
[584]	validation_0-mae:2072.04034
[585]	validation_0-mae:2071.42533
[586]	validation_0-mae:2071.65208
[587]	validation_0-mae:2071.00075
[588]	validation_0-mae:2070.78103
[589]	validation_0-mae:2069.70379
[590]	validation_0-mae:2069.55966
[591]	validation_0-mae:2069.33539
[592]	validation_0-mae:2069.40248
[593]	validation_0-mae:2069.52966
[594]	validation_0-mae:2069.64378
[595]	validation_0-mae:2069.68044
[596]	validation_0-mae:2069.68134
[597]	validation_0-mae:2069.58419
[598]	validation_0-mae:2069.63746
[599]	validation_0-mae:2069.87105
[600]	validation_0-mae:2070.23359
[601]	validation_0-mae:2070.09559
[602]	validation_0-mae:2070.20533
[603]	validation_0-mae:2070.18324
[604]	validation_0-mae:2070.07965
[605]	validation_0-mae:2069.89573
[606]	validation_0-mae:2069.94502
[607]	validation_0-mae:2069.90022
[608]	validation_0-mae:2069.93563
[609]	validation_0-mae:2069.32575
[610]	validation_0-mae:2069.27772
[611]	validation_0-mae:2068.70724
[612]	validation_0-mae:2068.88762
[613]	validation_0-mae:2068.80266
[614]	validation_0-mae:2068.57153
[615]	validation_0-mae:2067.94768
[616]	validation_0-mae:2067.46537
[617]	validation_0-mae:2067.15880
[618]	validation_0-mae:2067.04805
[619]	validation_0-mae:2066.87968
[620]	validation_0-mae:2066.49462
[621]	validation_0-mae:2066.34458
[622]	validation_0-mae:2066.77378
[623]	validation_0-mae:2066.58331
[624]	validation_0-mae:2066.42368
[625]	validation_0-mae:2065.84112
[626]	validation_0-mae:2066.14271

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[41]	validation_0-mae:3189.07930
[42]	validation_0-mae:3154.62233
[43]	validation_0-mae:3105.18663
[44]	validation_0-mae:3070.40237
[45]	validation_0-mae:3030.58226
[46]	validation_0-mae:3006.79521
[47]	validation_0-mae:2975.80833
[48]	validation_0-mae:2945.56658
[49]	validation_0-mae:2919.31368
[50]	validation_0-mae:2875.44527
[51]	validation_0-mae:2844.66078
[52]	validation_0-mae:2814.06712
[53]	validation_0-mae:2803.09082
[54]	validation_0-mae:2782.40083
[55]	validation_0-mae:2765.81930
[56]	validation_0-mae:2747.14352
[57]	validation_0-mae:2728.87317
[58]	validation_0-mae:2711.53555
[59]	validation_0-mae:2698.37808
[60]	validation_0-mae:2682.97032
[61]	validation_0-mae:2666.67480
[62]	validation_0-mae:2647.84483
[63]	validation_0-mae:2634.57521
[64]	validation_0-mae:2621.50379
[65]	validation_0-mae:2609.49943
[66]	validation_0-mae:2597.14260
[67]	validation_0-mae:2583.14548
[68]	validation_0-mae:2564.36804
[69]	validation_0-mae:2550.22940
[70]	validation_0-mae:2540.59668
[71]	validation_0-mae:2527.30352
[72]	validation_0-mae:2517.96675
[73]	validation_0-mae:2506.38745
[74]	validation_0-mae:2502.06651
[75]	validation_0-mae:2489.71647
[76]	validation_0-mae:2480.45271
[77]	validation_0-mae:2471.20939
[78]	validation_0-mae:2462.47158
[79]	validation_0-mae:2451.44069
[80]	validation_0-mae:2442.89517
[81]	validation_0-mae:2437.63620
[82]	validation_0-mae:2432.43709
[83]	validation_0-mae:2423.38175
[84]	validation_0-mae:2415.63623
[85]	validation_0-mae:2407.49023
[86]	validation_0-mae:2405.15369
[87]	validation_0-mae:2396.57625
[88]	validation_0-mae:2389.56325
[89]	validation_0-mae:2383.97923
[90]	validation_0-mae:2376.86213
[91]	validation_0-mae:2368.44691
[92]	validation_0-mae:2364.19091
[93]	validation_0-mae:2360.33258
[94]	validation_0-mae:2356.29830
[95]	validation_0-mae:2351.41779
[96]	validation_0-mae:2342.20236
[97]	validation_0-mae:2341.13420
[98]	validation_0-mae:2338.35148
[99]	validation_0-mae:2335.79825
[100]	validation_0-mae:2332.25262
[101]	validation_0-mae:2325.87931
[102]	validation_0-mae:2318.89719
[103]	validation_0-mae:2315.65571
[104]	validation_0-mae:2311.88972
[105]	validation_0-mae:2308.82379
[106]	validation_0-mae:2304.09467
[107]	validation_0-mae:2302.91478
[108]	validation_0-mae:2298.30162
[109]	validation_0-mae:2295.40691
[110]	validation_0-mae:2294.50722
[111]	validation_0-mae:2294.24216
[112]	validation_0-mae:2291.98107
[113]	validation_0-mae:2288.00002
[114]	validation_0-mae:2281.44577
[115]	validation_0-mae:2278.11058
[116]	validation_0-mae:2276.38337
[117]	validation_0-mae:2276.88588
[118]	validation_0-mae:2274.77761
[119]	validation_0-mae:2270.67233
[120]	validation_0-mae:2271.57269
[121]	validation_0-mae:2270.88088
[122]	validation_0-mae:2267.04326
[123]	validation_0-mae:2261.29030
[124]	validation_0-mae:2261.04720
[125]	validation_0-mae:2257.52511
[126]	validation_0-mae:2259.41042
[127]	validation_0-mae:2257.82085
[128]	validation_0-mae:2255.77992
[129]	validation_0-mae:2253.04161
[130]	validation_0-mae:2248.14108
[131]	validation_0-mae:2245.81350
[132]	validation_0-mae:2241.79484
[133]	validation_0-mae:2240.11536
[134]	validation_0-mae:2238.22014
[135]	validation_0-mae:2237.43216
[136]	validation_0-mae:2235.48693
[137]	validation_0-mae:2234.78213
[138]	validation_0-mae:2234.11317
[139]	validation_0-mae:2232.29651
[140]	validation_0-mae:2233.48288
[141]	validation_0-mae:2233.41457
[142]	validation_0-mae:2230.83313
[143]	validation_0-mae:2226.67375
[144]	validation_0-mae:2223.99585
[145]	validation_0-mae:2222.47476
[146]	validation_0-mae:2220.75947
[147]	validation_0-mae:2220.16556
[148]	validation_0-mae:2219.12691
[149]	validation_0-mae:2217.40688
[150]	validation_0-mae:2215.03067
[151]	validation_0-mae:2213.89700
[152]	validation_0-mae:2213.02351
[153]	validation_0-mae:2212.37125
[154]	validation_0-mae:2209.93116
[155]	validation_0-mae:2210.37565
[156]	validation_0-mae:2208.47603
[157]	validation_0-mae:2209.10587
[158]	validation_0-mae:2209.50082
[159]	validation_0-mae:2209.77445
[160]	validation_0-mae:2211.16594
[161]	validation_0-mae:2211.11312
[162]	validation_0-mae:2209.71683
[163]	validation_0-mae:2210.32982
[164]	validation_0-mae:2208.65513
[165]	validation_0-mae:2207.01737
[166]	validation_0-mae:2208.22654
[167]	validation_0-mae:2205.75057
[168]	validation_0-mae:2202.17973
[169]	validation_0-mae:2202.14764
[170]	validation_0-mae:2200.95356
[171]	validation_0-mae:2200.37520
[172]	validation_0-mae:2199.17188
[173]	validation_0-mae:2197.90701
[174]	validation_0-mae:2195.83475
[175]	validation_0-mae:2194.75930
[176]	validation_0-mae:2195.09538
[177]	validation_0-mae:2194.92313
[178]	validation_0-mae:2193.37838
[179]	validation_0-mae:2193.44796
[180]	validation_0-mae:2193.13622
[181]	validation_0-mae:2192.13901
[182]	validation_0-mae:2190.94697
[183]	validation_0-mae:2190.92270
[184]	validation_0-mae:2189.03770
[185]	validation_0-mae:2188.79545
[186]	validation_0-mae:2188.58354
[187]	validation_0-mae:2187.83672
[188]	validation_0-mae:2186.47134
[189]	validation_0-mae:2186.96246
[190]	validation_0-mae:2187.40773
[191]	validation_0-mae:2185.47863
[192]	validation_0-mae:2182.89135
[193]	validation_0-mae:2180.40717
[194]	validation_0-mae:2180.78937
[195]	validation_0-mae:2180.81910
[196]	validation_0-mae:2180.66716
[197]	validation_0-mae:2178.89395
[198]	validation_0-mae:2178.06741
[199]	validation_0-mae:2175.85011
[200]	validation_0-mae:2174.12179
[201]	validation_0-mae:2173.18989
[202]	validation_0-mae:2171.42959
[203]	validation_0-mae:2167.94596
[204]	validation_0-mae:2168.38160
[205]	validation_0-mae:2167.39812
[206]	validation_0-mae:2168.63520
[207]	validation_0-mae:2168.50814
[208]	validation_0-mae:2166.99148
[209]	validation_0-mae:2166.91467
[210]	validation_0-mae:2166.13662
[211]	validation_0-mae:2165.37617
[212]	validation_0-mae:2164.86993
[213]	validation_0-mae:2164.45553
[214]	validation_0-mae:2164.58899
[215]	validation_0-mae:2163.66420
[216]	validation_0-mae:2161.83393
[217]	validation_0-mae:2161.81121
[218]	validation_0-mae:2160.29223
[219]	validation_0-mae:2160.14168
[220]	validation_0-mae:2159.71137
[221]	validation_0-mae:2159.25944
[222]	validation_0-mae:2157.50596
[223]	validation_0-mae:2158.06464
[224]	validation_0-mae:2157.97600
[225]	validation_0-mae:2157.45597
[226]	validation_0-mae:2157.13021
[227]	validation_0-mae:2156.35795
[228]	validation_0-mae:2155.66385
[229]	validation_0-mae:2156.12992
[230]	validation_0-mae:2156.15828
[231]	validation_0-mae:2154.20288
[232]	validation_0-mae:2151.95400
[233]	validation_0-mae:2151.95482
[234]	validation_0-mae:2152.07528
[235]	validation_0-mae:2151.76192
[236]	validation_0-mae:2151.22672
[237]	validation_0-mae:2151.67253
[238]	validation_0-mae:2152.06153
[239]	validation_0-mae:2152.20113
[240]	validation_0-mae:2151.90674
[241]	validation_0-mae:2150.52170
[242]	validation_0-mae:2150.96622
[243]	validation_0-mae:2150.27645
[244]	validation_0-mae:2150.65884
[245]	validation_0-mae:2149.16138
[246]	validation_0-mae:2148.40831
[247]	validation_0-mae:2148.22305
[248]	validation_0-mae:2148.23050
[249]	validation_0-mae:2146.57470
[250]	validation_0-mae:2146.25076
[251]	validation_0-mae:2146.35438
[252]	validation_0-mae:2147.23648
[253]	validation_0-mae:2148.25328
[254]	validation_0-mae:2148.02147
[255]	validation_0-mae:2147.78410
[256]	validation_0-mae:2147.25638
[257]	validation_0-mae:2147.02948
[258]	validation_0-mae:2145.25569
[259]	validation_0-mae:2144.72768
[260]	validation_0-mae:2144.44028
[261]	validation_0-mae:2145.13687
[262]	validation_0-mae:2145.39838
[263]	validation_0-mae:2145.24551
[264]	validation_0-mae:2144.79683
[265]	validation_0-mae:2145.17265
[266]	validation_0-mae:2144.23168
[267]	validation_0-mae:2145.15412
[268]	validation_0-mae:2144.89171
[269]	validation_0-mae:2144.98079
[270]	validation_0-mae:2144.65312
[271]	validation_0-mae:2143.92794
[272]	validation_0-mae:2141.63692
[273]	validation_0-mae:2141.71563
[274]	validation_0-mae:2140.54495
[275]	validation_0-mae:2139.75301
[276]	validation_0-mae:2139.46437
[277]	validation_0-mae:2139.38353
[278]	validation_0-mae:2139.66020
[279]	validation_0-mae:2140.02552
[280]	validation_0-mae:2140.42426
[281]	validation_0-mae:2140.26072
[282]	validation_0-mae:2139.92750
[283]	validation_0-mae:2140.19051
[284]	validation_0-mae:2140.23713
[285]	validation_0-mae:2140.36886
[286]	validation_0-mae:2139.94079
[287]	validation_0-mae:2138.38262
[288]	validation_0-mae:2138.10121
[289]	validation_0-mae:2138.58747
[290]	validation_0-mae:2138.60178
[291]	validation_0-mae:2138.24455
[292]	validation_0-mae:2137.79642
[293]	validation_0-mae:2137.65447
[294]	validation_0-mae:2137.65761
[295]	validation_0-mae:2138.11349
[296]	validation_0-mae:2138.18620
[297]	validation_0-mae:2138.25596
[298]	validation_0-mae:2136.61396
[299]	validation_0-mae:2136.40686
[300]	validation_0-mae:2136.69701
[301]	validation_0-mae:2136.07097
[302]	validation_0-mae:2135.45278
[303]	validation_0-mae:2135.10983
[304]	validation_0-mae:2135.01468
[305]	validation_0-mae:2135.59732
[306]	validation_0-mae:2136.10983
[307]	validation_0-mae:2135.80225
[308]	validation_0-mae:2134.39462
[309]	validation_0-mae:2134.87228
[310]	validation_0-mae:2134.95389
[311]	validation_0-mae:2134.72086
[312]	validation_0-mae:2134.65073
[313]	validation_0-mae:2133.95864
[314]	validation_0-mae:2133.38932
[315]	validation_0-mae:2133.89642
[316]	validation_0-mae:2134.79508
[317]	validation_0-mae:2133.77397
[318]	validation_0-mae:2133.73151
[319]	validation_0-mae:2134.08741
[320]	validation_0-mae:2134.68134
[321]	validation_0-mae:2134.84400
[322]	validation_0-mae:2135.37496
[323]	validation_0-mae:2136.24353
[324]	validation_0-mae:2135.76651
[325]	validation_0-mae:2135.96406
[326]	validation_0-mae:2135.91691
[327]	validation_0-mae:2135.80240
[328]	validation_0-mae:2136.13115
[329]	validation_0-mae:2136.43394
[330]	validation_0-mae:2136.46842
[0]	validation_0-mae:12340.77199
[1]	validation_0-mae:11534.74106
[2]	validation_0-mae:10793.72058
[3]	validation_0-mae:10118.21795
[4]	validation_0-mae:9536.59953
[5]	validation_0-mae:9035.44867
[6]	validation_0-mae:8582.51424
[7]	validation_0-mae:8148.69689
[8]	validation_0-mae:7785.59004
[9]	validation_0-mae:7443.10749
[10]	validation_0-mae:7128.01898
[11]	validation_0-mae:6819.77083
[12]	validation_0-mae:6552.92374
[13]	validation_0-mae:6287.43101
[14]	validation_0-mae:6036.45728
[15]	validation_0-mae:5802.34509
[16]	validation_0-mae:5566.84134
[17]	validation_0-mae:5382.30351
[18]	validation_0-mae:5190.39324
[19]	validation_0-mae:5015.73615
[20]	validation_0-mae:4862.07942
[21]	validation_0-mae:4703.64675
[22]	validation_0-mae:4586.57116
[23]	validation_0-mae:4432.44616
[24]	validation_0-mae:4315.55437
[25]	validation_0-mae:4207.07952
[26]	validation_0-mae:4108.08191
[27]	validation_0-mae:4009.75055
[28]	validation_0-mae:3911.13715
[29]	validation_0-mae:3817.41759
[30]	validation_0-mae:3741.44198
[31]	validation_0-mae:3666.92004
[32]	validation_0-mae:3596.12660

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[33]	validation_0-mae:3540.30698
[34]	validation_0-mae:3482.99256
[35]	validation_0-mae:3426.85936
[36]	validation_0-mae:3358.17614
[37]	validation_0-mae:3316.25499
[38]	validation_0-mae:3268.32074
[39]	validation_0-mae:3220.91880
[40]	validation_0-mae:3189.29103
[41]	validation_0-mae:3157.83365
[42]	validation_0-mae:3120.66064
[43]	validation_0-mae:3067.05534
[44]	validation_0-mae:3036.48186
[45]	validation_0-mae:3003.77174
[46]	validation_0-mae:2965.67449
[47]	validation_0-mae:2938.97668
[48]	validation_0-mae:2915.76270
[49]	validation_0-mae:2878.43089
[50]	validation_0-mae:2854.55549
[51]	validation_0-mae:2824.01744
[52]	validation_0-mae:2791.22491
[53]	validation_0-mae:2767.03716
[54]	validation_0-mae:2749.00273
[55]	validation_0-mae:2723.78099
[56]	validation_0-mae:2703.02020
[57]	validation_0-mae:2688.04439
[58]	validation_0-mae:2666.62468
[59]	validation_0-mae:2655.41038
[60]	validation_0-mae:2645.55966
[61]	validation_0-mae:2633.95801
[62]	validation_0-mae:2618.05132
[63]	validation_0-mae:2608.86845
[64]	validation_0-mae:2594.98418
[65]	validation_0-mae:2583.63991
[66]	validation_0-mae:2577.37119
[67]	validation_0-mae:2567.15155
[68]	validation_0-mae:2554.95327
[69]	validation_0-mae:2547.34677
[70]	validation_0-mae:2539.68918
[71]	validation_0-mae:2531.36240
[72]	validation_0-mae:2521.57559
[73]	validation_0-mae:2512.26826
[74]	validation_0-mae:2496.07423
[75]	validation_0-mae:2489.21219
[76]	validation_0-mae:2471.59128
[77]	validation_0-mae:2461.66481
[78]	validation_0-mae:2456.37953
[79]	validation_0-mae:2447.70127
[80]	validation_0-mae:2438.51180
[81]	validation_0-mae:2435.02905
[82]	validation_0-mae:2429.49059
[83]	validation_0-mae:2419.75193
[84]	validation_0-mae:2412.41890
[85]	validation_0-mae:2401.09596
[86]	validation_0-mae:2396.87021
[87]	validation_0-mae:2389.89240
[88]	validation_0-mae:2388.58550
[89]	validation_0-mae:2387.77785
[90]	validation_0-mae:2378.55857
[91]	validation_0-mae:2375.98124
[92]	validation_0-mae:2371.46978
[93]	validation_0-mae:2366.53750
[94]	validation_0-mae:2359.99899
[95]	validation_0-mae:2354.33640
[96]	validation_0-mae:2350.53130
[97]	validation_0-mae:2347.08025
[98]	validation_0-mae:2345.54779
[99]	validation_0-mae:2340.43419
[100]	validation_0-mae:2334.77981
[101]	validation_0-mae:2329.74589
[102]	validation_0-mae:2327.25882
[103]	validation_0-mae:2321.25701
[104]	validation_0-mae:2316.34430
[105]	validation_0-mae:2307.59915
[106]	validation_0-mae:2307.11762
[107]	validation_0-mae:2301.41339
[108]	validation_0-mae:2298.54733
[109]	validation_0-mae:2296.11315
[110]	validation_0-mae:2294.27544
[111]	validation_0-mae:2291.33779
[112]	validation_0-mae:2289.14706
[113]	validation_0-mae:2288.33287
[114]	validation_0-mae:2286.61513
[115]	validation_0-mae:2281.31135
[116]	validation_0-mae:2278.81289
[117]	validation_0-mae:2274.17713
[118]	validation_0-mae:2271.91890
[119]	validation_0-mae:2269.78677
[120]	validation_0-mae:2268.09727
[121]	validation_0-mae:2266.09566
[122]	validation_0-mae:2265.00561
[123]	validation_0-mae:2262.60084
[124]	validation_0-mae:2261.83823
[125]	validation_0-mae:2259.45651
[126]	validation_0-mae:2256.93354
[127]	validation_0-mae:2254.02614
[128]	validation_0-mae:2251.96518
[129]	validation_0-mae:2252.26897
[130]	validation_0-mae:2252.74563
[131]	validation_0-mae:2249.06982
[132]	validation_0-mae:2246.90718
[133]	validation_0-mae:2243.35991
[134]	validation_0-mae:2241.97724
[135]	validation_0-mae:2239.42788
[136]	validation_0-mae:2235.63476
[137]	validation_0-mae:2233.02656
[138]	validation_0-mae:2229.93886
[139]	validation_0-mae:2230.70691
[140]	validation_0-mae:2226.63548
[141]	validation_0-mae:2224.39013
[142]	validation_0-mae:2220.23580
[143]	validation_0-mae:2220.01135
[144]	validation_0-mae:2219.49205
[145]	validation_0-mae:2220.03604
[146]	validation_0-mae:2218.08041
[147]	validation_0-mae:2214.86071
[148]	validation_0-mae:2211.92560
[149]	validation_0-mae:2211.01014
[150]	validation_0-mae:2207.02489
[151]	validation_0-mae:2204.55085
[152]	validation_0-mae:2205.01899
[153]	validation_0-mae:2204.34242
[154]	validation_0-mae:2203.58159
[155]	validation_0-mae:2200.90169
[156]	validation_0-mae:2199.18560
[157]	validation_0-mae:2199.64373
[158]	validation_0-mae:2199.00181
[159]	validation_0-mae:2197.01666
[160]	validation_0-mae:2194.83599
[161]	validation_0-mae:2191.44492
[162]	validation_0-mae:2189.90915
[163]	validation_0-mae:2187.80754
[164]	validation_0-mae:2187.49675
[165]	validation_0-mae:2187.07492
[166]	validation_0-mae:2186.65487
[167]	validation_0-mae:2186.77595
[168]	validation_0-mae:2184.85456
[169]	validation_0-mae:2182.98809
[170]	validation_0-mae:2182.16262
[171]	validation_0-mae:2181.91460
[172]	validation_0-mae:2179.12187
[173]	validation_0-mae:2176.97728
[174]	validation_0-mae:2176.85987
[175]	validation_0-mae:2174.90437
[176]	validation_0-mae:2173.58107
[177]	validation_0-mae:2171.57801
[178]	validation_0-mae:2172.59726
[179]	validation_0-mae:2170.25008
[180]	validation_0-mae:2170.63647
[181]	validation_0-mae:2170.55072
[182]	validation_0-mae:2169.89934
[183]	validation_0-mae:2169.24952
[184]	validation_0-mae:2167.81216
[185]	validation_0-mae:2166.58284
[186]	validation_0-mae:2167.25858
[187]	validation_0-mae:2168.27107
[188]	validation_0-mae:2165.91070
[189]	validation_0-mae:2164.71735
[190]	validation_0-mae:2162.09725
[191]	validation_0-mae:2162.38416
[192]	validation_0-mae:2161.21766
[193]	validation_0-mae:2159.70902
[194]	validation_0-mae:2157.95419
[195]	validation_0-mae:2158.27415
[196]	validation_0-mae:2157.86399
[197]	validation_0-mae:2157.94962
[198]	validation_0-mae:2155.66551
[199]	validation_0-mae:2155.12352
[200]	validation_0-mae:2153.74944
[201]	validation_0-mae:2152.17341
[202]	validation_0-mae:2152.51278
[203]	validation_0-mae:2152.58386
[204]	validation_0-mae:2152.96697
[205]	validation_0-mae:2151.85334
[206]	validation_0-mae:2152.14008
[207]	validation_0-mae:2150.86868
[208]	validation_0-mae:2150.51488
[209]	validation_0-mae:2149.41448
[210]	validation_0-mae:2148.19025
[211]	validation_0-mae:2145.02990
[212]	validation_0-mae:2144.12800
[213]	validation_0-mae:2143.76436
[214]	validation_0-mae:2143.73552
[215]	validation_0-mae:2141.92995
[216]	validation_0-mae:2141.88271
[217]	validation_0-mae:2142.62538
[218]	validation_0-mae:2141.41434
[219]	validation_0-mae:2141.40948
[220]	validation_0-mae:2142.06477
[221]	validation_0-mae:2141.15481
[222]	validation_0-mae:2140.54788
[223]	validation_0-mae:2138.64660
[224]	validation_0-mae:2138.04609
[225]	validation_0-mae:2136.52557
[226]	validation_0-mae:2135.36319
[227]	validation_0-mae:2135.89621
[228]	validation_0-mae:2135.89400
[229]	validation_0-mae:2135.28274
[230]	validation_0-mae:2134.38535
[231]	validation_0-mae:2132.78564
[232]	validation_0-mae:2132.25116
[233]	validation_0-mae:2131.56342
[234]	validation_0-mae:2132.23017
[235]	validation_0-mae:2129.73522
[236]	validation_0-mae:2129.70522
[237]	validation_0-mae:2129.49208
[238]	validation_0-mae:2126.34339
[239]	validation_0-mae:2126.09776
[240]	validation_0-mae:2126.13450
[241]	validation_0-mae:2126.05470
[242]	validation_0-mae:2126.27835
[243]	validation_0-mae:2126.57754
[244]	validation_0-mae:2126.71322
[245]	validation_0-mae:2125.41619
[246]	validation_0-mae:2124.01767
[247]	validation_0-mae:2124.32143
[248]	validation_0-mae:2124.39501
[249]	validation_0-mae:2124.51926
[250]	validation_0-mae:2123.88999
[251]	validation_0-mae:2123.27907
[252]	validation_0-mae:2123.08172
[253]	validation_0-mae:2121.82298
[254]	validation_0-mae:2121.67243
[255]	validation_0-mae:2120.90101
[256]	validation_0-mae:2120.33846
[257]	validation_0-mae:2119.41695
[258]	validation_0-mae:2119.24198
[259]	validation_0-mae:2118.19796
[260]	validation_0-mae:2117.18749
[261]	validation_0-mae:2116.35636
[262]	validation_0-mae:2116.96196
[263]	validation_0-mae:2116.64935
[264]	validation_0-mae:2114.52605
[265]	validation_0-mae:2116.17200
[266]	validation_0-mae:2115.59622
[267]	validation_0-mae:2116.20030
[268]	validation_0-mae:2115.54495
[269]	validation_0-mae:2114.82225
[270]	validation_0-mae:2114.34710
[271]	validation_0-mae:2114.99358
[272]	validation_0-mae:2112.85574
[273]	validation_0-mae:2111.13228
[274]	validation_0-mae:2111.16738
[275]	validation_0-mae:2110.19765
[276]	validation_0-mae:2109.78935
[277]	validation_0-mae:2109.13945
[278]	validation_0-mae:2109.61501
[279]	validation_0-mae:2110.06033
[280]	validation_0-mae:2110.55609
[281]	validation_0-mae:2109.88307
[282]	validation_0-mae:2110.37967
[283]	validation_0-mae:2109.48386
[284]	validation_0-mae:2109.81363
[285]	validation_0-mae:2110.24126
[286]	validation_0-mae:2108.88973
[287]	validation_0-mae:2108.74295
[288]	validation_0-mae:2108.84497
[289]	validation_0-mae:2108.70790
[290]	validation_0-mae:2108.38132
[291]	validation_0-mae:2109.32020
[292]	validation_0-mae:2109.52299
[293]	validation_0-mae:2108.26255
[294]	validation_0-mae:2108.05747
[295]	validation_0-mae:2107.44820
[296]	validation_0-mae:2108.43019
[297]	validation_0-mae:2108.62886
[298]	validation_0-mae:2108.00491
[299]	validation_0-mae:2108.30602
[300]	validation_0-mae:2108.05152
[301]	validation_0-mae:2108.18477
[302]	validation_0-mae:2107.90231
[303]	validation_0-mae:2107.29363
[304]	validation_0-mae:2106.94632
[305]	validation_0-mae:2105.99532
[306]	validation_0-mae:2105.72871
[307]	validation_0-mae:2105.17430
[308]	validation_0-mae:2104.54504
[309]	validation_0-mae:2103.56144
[310]	validation_0-mae:2103.40053
[311]	validation_0-mae:2103.38660
[312]	validation_0-mae:2103.47382
[313]	validation_0-mae:2103.27133
[314]	validation_0-mae:2102.65800
[315]	validation_0-mae:2102.59192
[316]	validation_0-mae:2101.92580
[317]	validation_0-mae:2101.16163
[318]	validation_0-mae:2101.37071
[319]	validation_0-mae:2100.80377
[320]	validation_0-mae:2101.14362
[321]	validation_0-mae:2101.33594
[322]	validation_0-mae:2101.69755
[323]	validation_0-mae:2102.38077
[324]	validation_0-mae:2102.26607
[325]	validation_0-mae:2101.67218
[326]	validation_0-mae:2102.16020
[327]	validation_0-mae:2102.21662
[328]	validation_0-mae:2101.14734
[329]	validation_0-mae:2101.44792
[330]	validation_0-mae:2101.18726
[331]	validation_0-mae:2100.67602
[332]	validation_0-mae:2100.80302
[333]	validation_0-mae:2101.29114
[334]	validation_0-mae:2099.71957
[335]	validation_0-mae:2100.07801
[336]	validation_0-mae:2098.89165
[337]	validation_0-mae:2098.67413
[338]	validation_0-mae:2098.25059
[339]	validation_0-mae:2097.30803
[340]	validation_0-mae:2096.57475
[341]	validation_0-mae:2096.38233
[342]	validation_0-mae:2096.37012
[343]	validation_0-mae:2096.35037
[344]	validation_0-mae:2095.35523
[345]	validation_0-mae:2095.14327
[346]	validation_0-mae:2095.38513
[347]	validation_0-mae:2095.55469
[348]	validation_0-mae:2095.52349
[349]	validation_0-mae:2095.84709
[350]	validation_0-mae:2095.17033
[351]	validation_0-mae:2095.02841
[352]	validation_0-mae:2094.94056
[353]	validation_0-mae:2095.91161
[354]	validation_0-mae:2095.53172
[355]	validation_0-mae:2095.40035
[356]	validation_0-mae:2096.06580
[357]	validation_0-mae:2095.08072
[358]	validation_0-mae:2095.54659
[359]	validation_0-mae:2095.12419
[360]	validation_0-mae:2095.05284
[361]	validation_0-mae:2095.11367
[362]	validation_0-mae:2095.12255
[363]	validation_0-mae:2095.13280
[364]	validation_0-mae:2095.52678
[365]	validation_0-mae:2095.07344
[366]	validation_0-mae:2094.80410
[367]	validation_0-mae:2094.96704
[368]	validation_0-mae:2094.69289
[369]	validation_0-mae:2094.38071
[370]	validation_0-mae:2094.56117
[371]	validation_0-mae:2094.09510
[372]	validation_0-mae:2093.58902
[373]	validation_0-mae:2093.68530
[374]	validation_0-mae:2093.34547
[375]	validation_0-mae:2093.15991
[376]	validation_0-mae:2093.76197
[377]	validation_0-mae:2092.80037
[378]	validation_0-mae:2092.54059
[379]	validation_0-mae:2092.64119
[380]	validation_0-mae:2092.69487
[381]	validation_0-mae:2091.65025
[382]	validation_0-mae:2092.16952
[383]	validation_0-mae:2091.29786
[384]	validation_0-mae:2091.21786
[385]	validation_0-mae:2091.35368
[386]	validation_0-mae:2091.27004
[387]	validation_0-mae:2090.45960
[388]	validation_0-mae:2090.24869
[389]	validation_0-mae:2090.16264
[390]	validation_0-mae:2089.33889
[391]	validation_0-mae:2089.10350
[392]	validation_0-mae:2089.02361
[393]	validation_0-mae:2089.70954
[394]	validation_0-mae:2089.85930
[395]	validation_0-mae:2090.38021
[396]	validation_0-mae:2090.37955
[397]	validation_0-mae:2090.76768
[398]	validation_0-mae:2091.05324
[399]	validation_0-mae:2091.35028
[400]	validation_0-mae:2091.55309
[401]	validation_0-mae:2091.92981
[402]	validation_0-mae:2090.79789
[403]	validation_0-mae:2090.92752
[404]	validation_0-mae:2090.42281
[405]	validation_0-mae:2089.97929
[406]	validation_0-mae:2089.85572
[407]	validation_0-mae:2090.05692
[408]	validation_0-mae:2090.51707
[409]	validation_0-mae:2090.37933
[410]	validation_0-mae:2089.80397
[411]	validation_0-mae:2090.25214
[412]	validation_0-mae:2090.12977
[413]	validation_0-mae:2090.06502
[414]	validation_0-mae:2090.30096
[415]	validation_0-mae:2090.35617
[416]	validation_0-mae:2089.76262
[417]	validation_0-mae:2089.14867
[418]	validation_0-mae:2088.85771
[419]	validation_0-mae:2088.99560
[420]	validation_0-mae:2089.14254
[421]	validation_0-mae:2088.65489
[422]	validation_0-mae:2088.83812
[423]	validation_0-mae:2088.29478
[424]	validation_0-mae:2088.47072
[425]	validation_0-mae:2087.86183
[426]	validation_0-mae:2087.97435
[427]	validation_0-mae:2088.14747
[428]	validation_0-mae:2087.48257
[429]	validation_0-mae:2087.11264
[430]	validation_0-mae:2087.09150
[431]	validation_0-mae:2087.18818
[432]	validation_0-mae:2086.79816
[433]	validation_0-mae:2086.75236
[434]	validation_0-mae:2086.59780
[435]	validation_0-mae:2085.73817
[436]	validation_0-mae:2085.52926
[437]	validation_0-mae:2085.44637
[438]	validation_0-mae:2085.91031
[439]	validation_0-mae:2085.18605
[440]	validation_0-mae:2084.73132
[441]	validation_0-mae:2084.27616
[442]	validation_0-mae:2083.92459
[443]	validation_0-mae:2084.23141
[444]	validation_0-mae:2084.20631
[445]	validation_0-mae:2083.87665
[446]	validation_0-mae:2084.10582
[447]	validation_0-mae:2083.66072
[448]	validation_0-mae:2083.69052
[449]	validation_0-mae:2083.94631
[450]	validation_0-mae:2083.51701
[451]	validation_0-mae:2083.72429
[452]	validation_0-mae:2083.61873
[453]	validation_0-mae:2083.54242
[454]	validation_0-mae:2083.92125
[455]	validation_0-mae:2083.99709
[456]	validation_0-mae:2083.30476
[457]	validation_0-mae:2083.47986
[458]	validation_0-mae:2083.41115
[459]	validation_0-mae:2082.12447
[460]	validation_0-mae:2081.36986
[461]	validation_0-mae:2081.52814
[462]	validation_0-mae:2081.58491
[463]	validation_0-mae:2081.70750
[464]	validation_0-mae:2081.23683
[465]	validation_0-mae:2081.25370
[466]	validation_0-mae:2081.26246
[467]	validation_0-mae:2080.82145
[468]	validation_0-mae:2080.68401
[469]	validation_0-mae:2080.85245
[470]	validation_0-mae:2080.22144
[471]	validation_0-mae:2080.45820
[472]	validation_0-mae:2080.43877
[473]	validation_0-mae:2079.82431
[474]	validation_0-mae:2079.14012
[475]	validation_0-mae:2078.67031
[476]	validation_0-mae:2078.72762
[477]	validation_0-mae:2078.55017
[478]	validation_0-mae:2078.94674
[479]	validation_0-mae:2078.49483
[480]	validation_0-mae:2078.72839
[481]	validation_0-mae:2078.53734
[482]	validation_0-mae:2078.47667
[483]	validation_0-mae:2078.80624
[484]	validation_0-mae:2078.20140
[485]	validation_0-mae:2078.78816
[486]	validation_0-mae:2078.78923
[487]	validation_0-mae:2078.81783
[488]	validation_0-mae:2078.54548
[489]	validation_0-mae:2078.00714
[490]	validation_0-mae:2078.52263
[491]	validation_0-mae:2078.00202
[492]	validation_0-mae:2077.84223
[493]	validation_0-mae:2078.04226
[494]	validation_0-mae:2078.53704
[495]	validation_0-mae:2079.00428
[496]	validation_0-mae:2078.92781
[497]	validation_0-mae:2078.85748
[498]	validation_0-mae:2078.91051
[499]	validation_0-mae:2079.01942
[500]	validation_0-mae:2078.53282
[501]	validation_0-mae:2078.55133
[502]	validation_0-mae:2078.36156
[503]	validation_0-mae:2077.69381
[504]	validation_0-mae:2078.02783
[505]	validation_0-mae:2078.06910
[506]	validation_0-mae:2078.21099
[507]	validation_0-mae:2078.16021
[508]	validation_0-mae:2078.03787
[509]	validation_0-mae:2077.73317
[510]	validation_0-mae:2077.74702
[511]	validation_0-mae:2078.05782
[512]	validation_0-mae:2077.92692
[513]	validation_0-mae:2077.58937
[514]	validation_0-mae:2077.52434
[515]	validation_0-mae:2077.00090
[516]	validation_0-mae:2076.70740
[517]	validation_0-mae:2076.78694
[518]	validation_0-mae:2076.78346
[519]	validation_0-mae:2075.86244
[520]	validation_0-mae:2076.01193
[521]	validation_0-mae:2075.61629
[522]	validation_0-mae:2075.59913
[523]	validation_0-mae:2075.82067
[524]	validation_0-mae:2076.09460
[525]	validation_0-mae:2076.11245
[526]	validation_0-mae:2076.03751
[527]	validation_0-mae:2075.04238
[528]	validation_0-mae:2075.05642
[529]	validation_0-mae:2074.52850
[530]	validation_0-mae:2074.64036
[531]	validation_0-mae:2074.70792
[532]	validation_0-mae:2074.66369
[533]	validation_0-mae:2074.71795
[534]	validation_0-mae:2074.29444
[535]	validation_0-mae:2074.47640
[536]	validation_0-mae:2074.57342
[537]	validation_0-mae:2075.13425
[538]	validation_0-mae:2075.00419
[539]	validation_0-mae:2074.73913
[540]	validation_0-mae:2075.06185
[541]	validation_0-mae:2075.22187
[542]	validation_0-mae:2075.36968
[543]	validation_0-mae:2075.75781
[544]	validation_0-mae:2075.51585
[545]	validation_0-mae:2075.59391
[546]	validation_0-mae:2074.92592
[547]	validation_0-mae:2074.13642
[548]	validation_0-mae:2073.71680
[549]	validation_0-mae:2073.80403
[550]	validation_0-mae:2073.93631
[551]	validation_0-mae:2073.83176
[552]	validation_0-mae:2073.72601
[553]	validation_0-mae:2072.99805
[554]	validation_0-mae:2072.72202
[555]	validation_0-mae:2072.38068
[556]	validation_0-mae:2072.08441
[557]	validation_0-mae:2071.50055
[558]	validation_0-mae:2071.11107
[559]	validation_0-mae:2071.15916
[560]	validation_0-mae:2070.66417
[561]	validation_0-mae:2070.79409
[562]	validation_0-mae:2070.71630
[563]	validation_0-mae:2070.75877
[564]	validation_0-mae:2070.76199
[565]	validation_0-mae:2071.07841
[566]	validation_0-mae:2071.00224
[567]	validation_0-mae:2070.91249
[568]	validation_0-mae:2071.01343
[569]	validation_0-mae:2070.95063
[570]	validation_0-mae:2070.75383
[571]	validation_0-mae:2071.25301
[572]	validation_0-mae:2071.05727
[573]	validation_0-mae:2070.94041
[574]	validation_0-mae:2070.86643
[575]	validation_0-mae:2070.69816
[576]	validation_0-mae:2071.03225
[577]	validation_0-mae:2070.89903
[578]	validation_0-mae:2070.71675
[579]	validation_0-mae:2070.74516
[580]	validation_0-mae:2070.98493
[581]	validation_0-mae:2071.13432
[582]	validation_0-mae:2070.89875
[583]	validation_0-mae:2070.56653
[584]	validation_0-mae:2070.62040
[585]	validation_0-mae:2071.14778
[586]	validation_0-mae:2071.06792
[587]	validation_0-mae:2071.20113
[588]	validation_0-mae:2070.65607
[589]	validation_0-mae:2070.53048
[590]	validation_0-mae:2070.70766
[591]	validation_0-mae:2071.09195
[592]	validation_0-mae:2070.60992
[593]	validation_0-mae:2070.09257
[594]	validation_0-mae:2070.21074
[595]	validation_0-mae:2070.22416
[596]	validation_0-mae:2070.43800
[597]	validation_0-mae:2070.48909
[598]	validation_0-mae:2070.16978
[599]	validation_0-mae:2070.26804
[600]	validation_0-mae:2070.33055
[601]	validation_0-mae:2070.38795
[602]	validation_0-mae:2070.46584
[603]	validation_0-mae:2071.03476
[604]	validation_0-mae:2071.02758
[605]	validation_0-mae:2071.11102
[606]	validation_0-mae:2070.76636
[607]	validation_0-mae:2071.12642
[608]	validation_0-mae:2071.03495
[609]	validation_0-mae:2071.24161
[610]	validation_0-mae:2071.26267
[611]	validation_0-mae:2071.12024
[612]	validation_0-mae:2071.27490
[613]	validation_0-mae:2071.42170
[614]	validation_0-mae:2071.60912
[615]	validation_0-mae:2071.46533
[616]	validation_0-mae:2071.63445
[617]	validation_0-mae:2071.72851
[618]	validation_0-mae:2071.61995
[619]	validation_0-mae:2071.23510
[620]	validation_0-mae:2070.99546
[621]	validation_0-mae:2070.99235
[622]	validation_0-mae:2070.90408

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[36]	validation_0-mae:3388.23860
[37]	validation_0-mae:3334.41450
[38]	validation_0-mae:3273.35348
[39]	validation_0-mae:3226.98635
[40]	validation_0-mae:3187.80588
[41]	validation_0-mae:3149.23579
[42]	validation_0-mae:3121.19513
[43]	validation_0-mae:3075.13622
[44]	validation_0-mae:3041.42291
[45]	validation_0-mae:3001.19536
[46]	validation_0-mae:2976.86381
[47]	validation_0-mae:2948.01965
[48]	validation_0-mae:2921.23061
[49]	validation_0-mae:2901.46054
[50]	validation_0-mae:2882.58539
[51]	validation_0-mae:2856.06344
[52]	validation_0-mae:2825.89458
[53]	validation_0-mae:2812.36739
[54]	validation_0-mae:2793.07882
[55]	validation_0-mae:2774.71873
[56]	validation_0-mae:2763.19125
[57]	validation_0-mae:2748.76899
[58]	validation_0-mae:2720.73007
[59]	validation_0-mae:2713.57998
[60]	validation_0-mae:2693.01975
[61]	validation_0-mae:2677.10618
[62]	validation_0-mae:2653.99836
[63]	validation_0-mae:2648.13933
[64]	validation_0-mae:2640.51850
[65]	validation_0-mae:2625.95592
[66]	validation_0-mae:2613.15867
[67]	validation_0-mae:2605.99656
[68]	validation_0-mae:2595.09900
[69]	validation_0-mae:2575.35962
[70]	validation_0-mae:2558.43698
[71]	validation_0-mae:2549.66022
[72]	validation_0-mae:2540.65789
[73]	validation_0-mae:2532.48424
[74]	validation_0-mae:2522.60145
[75]	validation_0-mae:2511.28642
[76]	validation_0-mae:2500.41271
[77]	validation_0-mae:2493.60169
[78]	validation_0-mae:2485.86856
[79]	validation_0-mae:2479.36006
[80]	validation_0-mae:2477.80045
[81]	validation_0-mae:2468.04119
[82]	validation_0-mae:2457.35626
[83]	validation_0-mae:2449.72599
[84]	validation_0-mae:2441.62998
[85]	validation_0-mae:2436.12839
[86]	validation_0-mae:2431.62637
[87]	validation_0-mae:2425.54593
[88]	validation_0-mae:2421.83596
[89]	validation_0-mae:2416.44651
[90]	validation_0-mae:2412.61336
[91]	validation_0-mae:2408.51552
[92]	validation_0-mae:2404.34502
[93]	validation_0-mae:2403.51651
[94]	validation_0-mae:2393.74083
[95]	validation_0-mae:2390.35464
[96]	validation_0-mae:2387.26415
[97]	validation_0-mae:2383.39309
[98]	validation_0-mae:2380.85329
[99]	validation_0-mae:2375.21626
[100]	validation_0-mae:2373.91342
[101]	validation_0-mae:2371.45942
[102]	validation_0-mae:2359.55499
[103]	validation_0-mae:2354.95761
[104]	validation_0-mae:2354.11594
[105]	validation_0-mae:2345.59499
[106]	validation_0-mae:2342.94257
[107]	validation_0-mae:2338.11989
[108]	validation_0-mae:2337.89777
[109]	validation_0-mae:2335.04679
[110]	validation_0-mae:2331.34319
[111]	validation_0-mae:2331.79247
[112]	validation_0-mae:2327.19798
[113]	validation_0-mae:2326.72621
[0]	validation_0-mae:12544.63922
[1]	validation_0-mae:11867.84931
[2]	validation_0-mae:11275.31478
[3]	validation_0-mae:10768.96528
[4]	validation_0-mae:10325.01179
[5]	validation_0-mae:9886.68343
[6]	validation_0-mae:9484.12538
[7]	validation_0-mae:9135.86105
[8]	validation_0-mae:8800.59229
[9]	validation_0-mae:8491.51436
[10]	validation_0-mae:8199.74704

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[0]	validation_0-mae:12408.29142
[1]	validation_0-mae:11639.05270
[2]	validation_0-mae:10958.28131
[3]	validation_0-mae:10322.46777
[4]	validation_0-mae:9776.05969
[5]	validation_0-mae:9289.78365
[6]	validation_0-mae:8816.64292
[7]	validation_0-mae:8402.18727
[8]	validation_0-mae:8048.26474
[9]	validation_0-mae:7685.16263
[10]	validation_0-mae:7374.98209
[11]	validation_0-mae:7058.01989
[12]	validation_0-mae:6789.55732
[13]	validation_0-mae:6511.19608
[14]	validation_0-mae:6274.53905
[15]	validation_0-mae:6037.63542
[16]	validation_0-mae:5850.90947
[17]	validation_0-mae:5643.82850
[18]	validation_0-mae:5455.04079
[19]	validation_0-mae:5297.93251
[20]	validation_0-mae:5119.17911
[21]	validation_0-mae:4979.74221
[22]	validation_0-mae:4834.54679
[23]	validation_0-mae:4707.29474
[24]	validation_0-mae:4588.78512
[25]	validation_0-mae:4466.21340
[26]	validation_0-mae:4355.92985
[27]	validation_0-mae:4251.42925
[28]	validation_0-mae:4152.42697
[29]	validation_0-mae:4049.06677
[30]	validation_0-mae:3960.78245
[31]	validation_0-mae:3881.05166
[32]	validation_0-mae:3793.28973
[33]	validation_0-mae:3719.78768
[34]	validation_0-mae:3650.28897
[35]	validation_0-mae:3584.30705
[36]	validation_0-mae:3523.80255
[37]	validation_0-mae:3462.14711
[38]	validation_0-mae:3410.62252
[39]	validation_0-mae:3366.27206
[40]	validation_0-mae:3317.12686
[41]	validation_0-mae:3278.09889
[42]	validation_0-mae:3239.21558
[43]	validation_0-mae:3201.42977
[44]	validation_0-mae:3164.06472
[45]	validation_0-mae:3136.06855
[46]	validation_0-mae:3092.89838
[47]	validation_0-mae:3067.26264
[48]	validation_0-mae:3024.30647
[49]	validation_0-mae:2999.97946
[50]	validation_0-mae:2969.97246
[51]	validation_0-mae:2949.86751
[52]	validation_0-mae:2925.24916
[53]	validation_0-mae:2904.77511
[54]	validation_0-mae:2885.51015
[55]	validation_0-mae:2853.92308
[56]	validation_0-mae:2837.48194
[0]	validation_0-mae:12462.80594
[1]	validation_0-mae:11746.55566
[2]	validation_0-mae:11084.02799
[3]	validation_0-mae:10475.93761
[4]	validation_0-mae:9948.59859
[5]	validation_0-mae:9453.62343
[6]	validation_0-mae:9011.46591
[7]	validation_0-mae:8610.76057
[8]	validation_0-mae:8233.00696
[9]	validation_0-mae:7903.17703

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[0]	validation_0-mae:12351.13724
[1]	validation_0-mae:11561.22205
[2]	validation_0-mae:10834.10023
[3]	validation_0-mae:10163.84286
[4]	validation_0-mae:9574.55555
[5]	validation_0-mae:9063.10249
[6]	validation_0-mae:8616.42138
[7]	validation_0-mae:8181.63950
[8]	validation_0-mae:7819.83327
[9]	validation_0-mae:7471.53346
[10]	validation_0-mae:7136.20963
[11]	validation_0-mae:6815.04213
[12]	validation_0-mae:6530.21716
[13]	validation_0-mae:6273.51751
[14]	validation_0-mae:6029.90088
[15]	validation_0-mae:5777.11067
[16]	validation_0-mae:5584.63775
[17]	validation_0-mae:5383.52231
[18]	validation_0-mae:5201.26140
[19]	validation_0-mae:5030.97105
[20]	validation_0-mae:4867.31503
[21]	validation_0-mae:4704.67688
[22]	validation_0-mae:4561.13696
[23]	validation_0-mae:4428.18271
[24]	validation_0-mae:4298.81814
[25]	validation_0-mae:4188.82883
[26]	validation_0-mae:4097.21687
[27]	validation_0-mae:3980.30209
[28]	validation_0-mae:3873.65317
[29]	validation_0-mae:3785.37533
[30]	validation_0-mae:3704.88094
[31]	validation_0-mae:3625.66276
[32]	validation_0-mae:3562.08930
[33]	validation_0-mae:3495.45724
[34]	validation_0-mae:3422.79151
[35]	validation_0-mae:3367.10082
[36]	validation_0-mae:3323.45734
[37]	validation_0-mae:3277.75631
[38]	validation_0-mae:3231.79102
[39]	validation_0-mae:3186.71418
[40]	validation_0-mae:3147.55745
[41]	validation_0-mae:3115.61917
[42]	validation_0-mae:3080.98896
[43]	validation_0-mae:3053.16459
[44]	validation_0-mae:3022.86014
[45]	validation_0-mae:2998.94272
[46]	validation_0-mae:2960.74858
[47]	validation_0-mae:2935.92474
[48]	validation_0-mae:2903.78211
[49]	validation_0-mae:2881.01722
[50]	validation_0-mae:2857.09508
[51]	validation_0-mae:2831.87128
[52]	validation_0-mae:2810.31281
[53]	validation_0-mae:2795.26541
[54]	validation_0-mae:2783.72043
[55]	validation_0-mae:2758.24447
[56]	validation_0-mae:2734.24512
[57]	validation_0-mae:2708.88951
[58]	validation_0-mae:2698.19723
[59]	validation_0-mae:2684.07599
[60]	validation_0-mae:2670.64950
[61]	validation_0-mae:2661.29700
[62]	validation_0-mae:2650.53143
[63]	validation_0-mae:2632.43688
[64]	validation_0-mae:2610.14045
[65]	validation_0-mae:2596.49579
[66]	validation_0-mae:2587.46359
[67]	validation_0-mae:2575.32640
[68]	validation_0-mae:2563.07155
[69]	validation_0-mae:2547.47123
[70]	validation_0-mae:2540.21246
[71]	validation_0-mae:2526.60156
[72]	validation_0-mae:2520.99785
[73]	validation_0-mae:2503.77120
[74]	validation_0-mae:2492.26236
[75]	validation_0-mae:2481.10140
[76]	validation_0-mae:2475.10127
[77]	validation_0-mae:2467.12023
[78]	validation_0-mae:2453.75166
[79]	validation_0-mae:2447.24553
[80]	validation_0-mae:2436.09713
[81]	validation_0-mae:2430.96206
[82]	validation_0-mae:2425.26199
[83]	validation_0-mae:2413.78456
[84]	validation_0-mae:2400.67809
[85]	validation_0-mae:2393.26827
[86]	validation_0-mae:2382.46360
[87]	validation_0-mae:2379.89706
[88]	validation_0-mae:2373.30827
[89]	validation_0-mae:2370.43277
[90]	validation_0-mae:2362.33917
[91]	validation_0-mae:2352.22483
[92]	validation_0-mae:2346.71873
[93]	validation_0-mae:2337.60534
[94]	validation_0-mae:2334.63422
[95]	validation_0-mae:2330.28373
[96]	validation_0-mae:2326.11275
[97]	validation_0-mae:2316.54371
[98]	validation_0-mae:2310.80779
[99]	validation_0-mae:2307.19753
[100]	validation_0-mae:2300.77425
[101]	validation_0-mae:2293.53028
[102]	validation_0-mae:2288.65206
[103]	validation_0-mae:2285.02520
[104]	validation_0-mae:2282.42296
[105]	validation_0-mae:2279.15877
[106]	validation_0-mae:2275.23103
[107]	validation_0-mae:2272.73961
[108]	validation_0-mae:2269.81013
[109]	validation_0-mae:2265.63999
[110]	validation_0-mae:2259.90907
[111]	validation_0-mae:2255.61504
[112]	validation_0-mae:2252.91021
[113]	validation_0-mae:2249.23467
[114]	validation_0-mae:2246.94604
[115]	validation_0-mae:2244.50661
[116]	validation_0-mae:2243.53685
[117]	validation_0-mae:2241.50985
[118]	validation_0-mae:2236.28630
[119]	validation_0-mae:2228.91778
[120]	validation_0-mae:2225.82702
[121]	validation_0-mae:2221.69254
[122]	validation_0-mae:2220.78055
[123]	validation_0-mae:2215.22730
[124]	validation_0-mae:2212.28386
[125]	validation_0-mae:2207.45483
[126]	validation_0-mae:2203.87260
[127]	validation_0-mae:2202.24690
[128]	validation_0-mae:2200.88740
[129]	validation_0-mae:2199.72915
[130]	validation_0-mae:2196.10194
[131]	validation_0-mae:2193.54017
[132]	validation_0-mae:2192.46173
[133]	validation_0-mae:2191.03360
[134]	validation_0-mae:2189.96472
[135]	validation_0-mae:2188.71239
[136]	validation_0-mae:2186.37438
[137]	validation_0-mae:2186.46265
[138]	validation_0-mae:2185.41338
[139]	validation_0-mae:2185.96318
[140]	validation_0-mae:2184.28595
[141]	validation_0-mae:2181.62780
[142]	validation_0-mae:2181.79002
[143]	validation_0-mae:2177.23555
[144]	validation_0-mae:2176.19466
[145]	validation_0-mae:2175.01379
[146]	validation_0-mae:2172.52270
[147]	validation_0-mae:2171.36340
[148]	validation_0-mae:2169.14178
[149]	validation_0-mae:2167.03850
[150]	validation_0-mae:2165.41655
[151]	validation_0-mae:2166.11407
[152]	validation_0-mae:2164.71571
[153]	validation_0-mae:2162.83449
[154]	validation_0-mae:2160.87897
[155]	validation_0-mae:2159.70172
[156]	validation_0-mae:2157.79956
[157]	validation_0-mae:2157.36997
[158]	validation_0-mae:2157.03347
[159]	validation_0-mae:2152.01121
[160]	validation_0-mae:2150.17805
[161]	validation_0-mae:2148.72348
[162]	validation_0-mae:2147.96310
[163]	validation_0-mae:2146.23049
[164]	validation_0-mae:2143.87564
[165]	validation_0-mae:2143.11359
[166]	validation_0-mae:2142.65522
[167]	validation_0-mae:2142.00941
[168]	validation_0-mae:2141.06469
[169]	validation_0-mae:2139.92904
[170]	validation_0-mae:2139.40116
[171]	validation_0-mae:2138.02516
[172]	validation_0-mae:2137.27523
[173]	validation_0-mae:2136.91156
[174]	validation_0-mae:2137.40298
[175]	validation_0-mae:2133.70524
[176]	validation_0-mae:2133.57091
[177]	validation_0-mae:2133.88598
[178]	validation_0-mae:2132.62263
[179]	validation_0-mae:2133.49495
[180]	validation_0-mae:2133.09240
[181]	validation_0-mae:2133.01941
[182]	validation_0-mae:2133.44945
[183]	validation_0-mae:2133.12035
[184]	validation_0-mae:2133.11493
[185]	validation_0-mae:2133.27245
[186]	validation_0-mae:2132.93445
[187]	validation_0-mae:2133.88337
[188]	validation_0-mae:2130.24560
[189]	validation_0-mae:2130.96039
[190]	validation_0-mae:2131.07356
[191]	validation_0-mae:2128.88378
[192]	validation_0-mae:2128.32759
[193]	validation_0-mae:2126.70373
[194]	validation_0-mae:2125.26096
[195]	validation_0-mae:2125.06686
[196]	validation_0-mae:2123.51174
[197]	validation_0-mae:2122.25852
[198]	validation_0-mae:2120.37633
[199]	validation_0-mae:2121.51888
[200]	validation_0-mae:2121.67351
[201]	validation_0-mae:2123.21419
[202]	validation_0-mae:2121.64576
[203]	validation_0-mae:2122.09897
[204]	validation_0-mae:2122.53945
[205]	validation_0-mae:2122.23991
[206]	validation_0-mae:2121.57235
[207]	validation_0-mae:2120.44996
[208]	validation_0-mae:2119.79864
[209]	validation_0-mae:2117.75867
[210]	validation_0-mae:2116.04522
[211]	validation_0-mae:2115.48505
[212]	validation_0-mae:2114.33246
[213]	validation_0-mae:2115.24587
[214]	validation_0-mae:2113.80385
[215]	validation_0-mae:2113.21488
[216]	validation_0-mae:2113.58225
[217]	validation_0-mae:2114.56784
[218]	validation_0-mae:2114.71432
[219]	validation_0-mae:2114.73465
[220]	validation_0-mae:2114.20982
[221]	validation_0-mae:2115.22036
[222]	validation_0-mae:2117.11053
[223]	validation_0-mae:2117.02949
[224]	validation_0-mae:2117.22555
[225]	validation_0-mae:2116.01168
[226]	validation_0-mae:2115.26255
[227]	validation_0-mae:2113.85430
[228]	validation_0-mae:2113.98304
[229]	validation_0-mae:2113.74538
[230]	validation_0-mae:2113.05401
[231]	validation_0-mae:2112.96810
[232]	validation_0-mae:2112.48076
[233]	validation_0-mae:2110.89531
[234]	validation_0-mae:2110.26397
[235]	validation_0-mae:2110.81150
[236]	validation_0-mae:2111.01859
[237]	validation_0-mae:2109.87665
[238]	validation_0-mae:2109.85068
[239]	validation_0-mae:2109.55904
[240]	validation_0-mae:2108.90200
[241]	validation_0-mae:2110.08350
[242]	validation_0-mae:2109.07891
[243]	validation_0-mae:2108.45460
[244]	validation_0-mae:2107.59030
[245]	validation_0-mae:2107.55527
[246]	validation_0-mae:2106.93252
[247]	validation_0-mae:2106.53671
[248]	validation_0-mae:2106.30521
[249]	validation_0-mae:2106.66200
[250]	validation_0-mae:2105.91349
[251]	validation_0-mae:2105.52754
[252]	validation_0-mae:2105.34794
[253]	validation_0-mae:2104.77609
[254]	validation_0-mae:2103.71906
[255]	validation_0-mae:2103.82030
[256]	validation_0-mae:2104.02197
[257]	validation_0-mae:2103.95372
[258]	validation_0-mae:2103.38629
[259]	validation_0-mae:2102.93722
[260]	validation_0-mae:2101.84453
[261]	validation_0-mae:2100.01036
[262]	validation_0-mae:2098.83976
[263]	validation_0-mae:2099.16294
[264]	validation_0-mae:2098.41581
[265]	validation_0-mae:2098.15430
[266]	validation_0-mae:2097.92022
[267]	validation_0-mae:2096.63335
[268]	validation_0-mae:2096.14899
[269]	validation_0-mae:2095.96797
[270]	validation_0-mae:2094.64746
[271]	validation_0-mae:2093.89643
[272]	validation_0-mae:2093.05703
[273]	validation_0-mae:2093.33950
[274]	validation_0-mae:2093.11824
[275]	validation_0-mae:2092.58809
[276]	validation_0-mae:2092.81175
[277]	validation_0-mae:2093.00509
[278]	validation_0-mae:2093.55799
[279]	validation_0-mae:2093.71584
[280]	validation_0-mae:2094.42127
[281]	validation_0-mae:2093.91214
[282]	validation_0-mae:2092.70818
[283]	validation_0-mae:2092.72758
[284]	validation_0-mae:2092.42566
[285]	validation_0-mae:2092.33791
[286]	validation_0-mae:2092.43237
[287]	validation_0-mae:2091.90807
[288]	validation_0-mae:2090.98835
[289]	validation_0-mae:2090.00520
[290]	validation_0-mae:2089.68300
[291]	validation_0-mae:2089.87220
[292]	validation_0-mae:2089.62929
[293]	validation_0-mae:2087.52792
[294]	validation_0-mae:2087.44469
[295]	validation_0-mae:2085.85943
[296]	validation_0-mae:2083.77331
[297]	validation_0-mae:2081.70412
[298]	validation_0-mae:2082.04848
[299]	validation_0-mae:2080.61384
[300]	validation_0-mae:2080.51307
[301]	validation_0-mae:2080.53859
[302]	validation_0-mae:2078.66702
[303]	validation_0-mae:2078.09733
[304]	validation_0-mae:2078.06396
[305]	validation_0-mae:2076.56177
[306]	validation_0-mae:2076.76912
[307]	validation_0-mae:2077.31352
[308]	validation_0-mae:2076.51872
[309]	validation_0-mae:2077.56423
[310]	validation_0-mae:2077.19323
[311]	validation_0-mae:2077.48650
[312]	validation_0-mae:2077.51341
[313]	validation_0-mae:2077.45412
[314]	validation_0-mae:2077.98188
[315]	validation_0-mae:2077.20863
[316]	validation_0-mae:2077.45804
[317]	validation_0-mae:2078.44786
[318]	validation_0-mae:2078.00358
[319]	validation_0-mae:2078.47093
[320]	validation_0-mae:2078.19690
[321]	validation_0-mae:2076.36659
[322]	validation_0-mae:2076.18208
[323]	validation_0-mae:2075.01342
[324]	validation_0-mae:2074.86910
[325]	validation_0-mae:2074.95342
[326]	validation_0-mae:2074.03956
[327]	validation_0-mae:2073.69650
[328]	validation_0-mae:2072.86745
[329]	validation_0-mae:2072.57546
[330]	validation_0-mae:2072.98352
[331]	validation_0-mae:2072.30644
[332]	validation_0-mae:2071.67015
[333]	validation_0-mae:2070.42713
[334]	validation_0-mae:2070.73584
[335]	validation_0-mae:2070.22030
[336]	validation_0-mae:2069.12480
[337]	validation_0-mae:2069.41249
[338]	validation_0-mae:2069.57039
[339]	validation_0-mae:2069.74494
[340]	validation_0-mae:2068.76776
[341]	validation_0-mae:2067.65604
[342]	validation_0-mae:2066.68280
[343]	validation_0-mae:2066.77219
[344]	validation_0-mae:2067.05556
[345]	validation_0-mae:2065.89958
[346]	validation_0-mae:2065.87704
[347]	validation_0-mae:2066.23076
[348]	validation_0-mae:2066.86560
[349]	validation_0-mae:2066.57889
[350]	validation_0-mae:2065.99790
[351]	validation_0-mae:2065.58259
[352]	validation_0-mae:2065.24539
[353]	validation_0-mae:2065.07919
[354]	validation_0-mae:2065.27521
[355]	validation_0-mae:2065.04679
[356]	validation_0-mae:2065.02437
[357]	validation_0-mae:2065.38724
[358]	validation_0-mae:2065.47926
[359]	validation_0-mae:2064.05322
[360]	validation_0-mae:2063.74534
[361]	validation_0-mae:2064.10279
[362]	validation_0-mae:2063.56046
[363]	validation_0-mae:2063.64184
[364]	validation_0-mae:2063.27184
[365]	validation_0-mae:2063.70887
[366]	validation_0-mae:2063.48134
[367]	validation_0-mae:2063.54211
[368]	validation_0-mae:2063.09741
[369]	validation_0-mae:2062.71184
[370]	validation_0-mae:2062.75902
[371]	validation_0-mae:2062.57185
[372]	validation_0-mae:2062.70529
[373]	validation_0-mae:2062.60091
[374]	validation_0-mae:2062.72371
[375]	validation_0-mae:2062.44856
[376]	validation_0-mae:2061.23923
[377]	validation_0-mae:2060.79431
[378]	validation_0-mae:2061.20593
[379]	validation_0-mae:2061.60656
[380]	validation_0-mae:2062.09292
[381]	validation_0-mae:2061.04855
[382]	validation_0-mae:2060.79312
[383]	validation_0-mae:2060.82884
[384]	validation_0-mae:2060.68130
[385]	validation_0-mae:2061.25873
[386]	validation_0-mae:2061.21998
[387]	validation_0-mae:2061.54704
[388]	validation_0-mae:2060.94420
[389]	validation_0-mae:2059.91350
[390]	validation_0-mae:2059.72839
[391]	validation_0-mae:2059.30473
[392]	validation_0-mae:2058.92760
[393]	validation_0-mae:2056.86848
[394]	validation_0-mae:2056.60581
[395]	validation_0-mae:2055.45520
[396]	validation_0-mae:2054.63875
[397]	validation_0-mae:2054.38687
[398]	validation_0-mae:2053.17397
[399]	validation_0-mae:2052.24333
[400]	validation_0-mae:2052.21626
[401]	validation_0-mae:2052.16004
[402]	validation_0-mae:2053.03363
[403]	validation_0-mae:2053.10234
[404]	validation_0-mae:2052.64411
[405]	validation_0-mae:2053.38826
[406]	validation_0-mae:2053.07749
[407]	validation_0-mae:2052.50298
[408]	validation_0-mae:2052.69509
[409]	validation_0-mae:2052.71580
[410]	validation_0-mae:2052.89423
[411]	validation_0-mae:2052.04905
[412]	validation_0-mae:2051.97956
[413]	validation_0-mae:2052.02595
[414]	validation_0-mae:2051.89522
[415]	validation_0-mae:2051.94798
[416]	validation_0-mae:2051.88391
[417]	validation_0-mae:2052.18170
[418]	validation_0-mae:2052.43172
[419]	validation_0-mae:2052.19809
[420]	validation_0-mae:2051.65006
[421]	validation_0-mae:2051.52042
[422]	validation_0-mae:2051.01369
[423]	validation_0-mae:2050.85797
[424]	validation_0-mae:2050.80422
[425]	validation_0-mae:2050.62107
[426]	validation_0-mae:2050.06912
[427]	validation_0-mae:2049.78846
[428]	validation_0-mae:2049.16641
[429]	validation_0-mae:2049.87417
[430]	validation_0-mae:2049.82890
[431]	validation_0-mae:2049.63083
[432]	validation_0-mae:2049.04728
[433]	validation_0-mae:2048.87838
[434]	validation_0-mae:2049.13996
[435]	validation_0-mae:2049.02145
[436]	validation_0-mae:2049.27304
[437]	validation_0-mae:2049.38889
[438]	validation_0-mae:2049.80490
[439]	validation_0-mae:2049.86726
[440]	validation_0-mae:2050.22797
[441]	validation_0-mae:2050.55976
[442]	validation_0-mae:2049.90419
[443]	validation_0-mae:2049.48643
[444]	validation_0-mae:2049.78061
[445]	validation_0-mae:2049.24263
[446]	validation_0-mae:2049.13640
[447]	validation_0-mae:2048.97633
[448]	validation_0-mae:2048.91149
[449]	validation_0-mae:2048.98763
[450]	validation_0-mae:2048.74107
[451]	validation_0-mae:2048.37694
[452]	validation_0-mae:2048.72512
[453]	validation_0-mae:2048.41361
[454]	validation_0-mae:2048.49601
[455]	validation_0-mae:2047.93512
[456]	validation_0-mae:2047.70751
[457]	validation_0-mae:2047.37466
[458]	validation_0-mae:2046.68535
[459]	validation_0-mae:2046.87350
[460]	validation_0-mae:2047.19400
[461]	validation_0-mae:2046.92354
[462]	validation_0-mae:2046.62958
[463]	validation_0-mae:2046.63509
[464]	validation_0-mae:2046.81261
[465]	validation_0-mae:2046.33568
[466]	validation_0-mae:2046.19603
[467]	validation_0-mae:2046.24570
[468]	validation_0-mae:2046.37590
[469]	validation_0-mae:2046.70825
[470]	validation_0-mae:2046.70588
[471]	validation_0-mae:2046.49489
[472]	validation_0-mae:2046.29836
[473]	validation_0-mae:2046.17562
[474]	validation_0-mae:2046.29018
[475]	validation_0-mae:2046.34488
[476]	validation_0-mae:2045.95394
[477]	validation_0-mae:2045.92670
[478]	validation_0-mae:2045.90276
[479]	validation_0-mae:2045.66902
[480]	validation_0-mae:2045.59807
[481]	validation_0-mae:2045.98253
[482]	validation_0-mae:2046.49522
[483]	validation_0-mae:2046.85494
[484]	validation_0-mae:2046.47455
[485]	validation_0-mae:2046.83563
[486]	validation_0-mae:2045.58236
[487]	validation_0-mae:2045.68386
[488]	validation_0-mae:2045.67910
[489]	validation_0-mae:2046.05770
[490]	validation_0-mae:2045.90585
[491]	validation_0-mae:2045.63415
[492]	validation_0-mae:2045.63445
[493]	validation_0-mae:2046.18822
[494]	validation_0-mae:2045.97826
[495]	validation_0-mae:2045.95224
[496]	validation_0-mae:2046.02101
[497]	validation_0-mae:2045.73562
[498]	validation_0-mae:2045.96716
[499]	validation_0-mae:2045.84385
[500]	validation_0-mae:2046.21187
[501]	validation_0-mae:2046.08800
[502]	validation_0-mae:2046.03133
[503]	validation_0-mae:2045.63716
[504]	validation_0-mae:2045.66603
[505]	validation_0-mae:2045.39722
[506]	validation_0-mae:2045.21025
[507]	validation_0-mae:2045.02896
[508]	validation_0-mae:2044.75183
[509]	validation_0-mae:2044.61284
[510]	validation_0-mae:2044.90983
[511]	validation_0-mae:2045.12599
[512]	validation_0-mae:2044.87419
[513]	validation_0-mae:2045.17512
[514]	validation_0-mae:2044.72269
[515]	validation_0-mae:2044.34758
[516]	validation_0-mae:2044.47092
[517]	validation_0-mae:2044.53244
[518]	validation_0-mae:2044.72453
[519]	validation_0-mae:2044.50289
[520]	validation_0-mae:2044.77940
[521]	validation_0-mae:2044.95808
[522]	validation_0-mae:2045.33290
[523]	validation_0-mae:2044.89986
[524]	validation_0-mae:2045.05533
[525]	validation_0-mae:2044.98277
[526]	validation_0-mae:2045.20156
[527]	validation_0-mae:2045.15207
[528]	validation_0-mae:2044.38326
[529]	validation_0-mae:2044.59206
[530]	validation_0-mae:2044.95668
[531]	validation_0-mae:2044.80546
[532]	validation_0-mae:2044.64566
[533]	validation_0-mae:2043.72286
[534]	validation_0-mae:2042.59034
[535]	validation_0-mae:2042.63875
[536]	validation_0-mae:2042.73790
[537]	validation_0-mae:2042.74546
[538]	validation_0-mae:2042.65577
[539]	validation_0-mae:2041.74589
[540]	validation_0-mae:2041.97821
[541]	validation_0-mae:2042.01900
[542]	validation_0-mae:2041.95313
[543]	validation_0-mae:2041.22508
[544]	validation_0-mae:2041.25147
[545]	validation_0-mae:2041.01331
[546]	validation_0-mae:2041.16496
[547]	validation_0-mae:2041.19504
[548]	validation_0-mae:2041.20095
[549]	validation_0-mae:2041.05776
[550]	validation_0-mae:2041.39261
[551]	validation_0-mae:2041.66590
[552]	validation_0-mae:2041.64097
[553]	validation_0-mae:2041.79694
[554]	validation_0-mae:2041.23406
[555]	validation_0-mae:2041.23296
[556]	validation_0-mae:2041.15452
[557]	validation_0-mae:2041.07097
[558]	validation_0-mae:2040.91942
[559]	validation_0-mae:2040.28887
[560]	validation_0-mae:2040.47451
[561]	validation_0-mae:2040.45235
[562]	validation_0-mae:2040.50682
[563]	validation_0-mae:2040.57360
[564]	validation_0-mae:2040.61572
[565]	validation_0-mae:2040.60137
[566]	validation_0-mae:2040.44678
[567]	validation_0-mae:2039.84976
[568]	validation_0-mae:2040.08201
[569]	validation_0-mae:2040.04184
[570]	validation_0-mae:2039.52202
[571]	validation_0-mae:2039.32008
[572]	validation_0-mae:2039.26224
[573]	validation_0-mae:2038.94902
[574]	validation_0-mae:2039.04333
[575]	validation_0-mae:2039.04904
[576]	validation_0-mae:2039.12761
[577]	validation_0-mae:2038.77148
[578]	validation_0-mae:2038.96457
[579]	validation_0-mae:2039.03633
[580]	validation_0-mae:2039.09085
[581]	validation_0-mae:2039.28235
[582]	validation_0-mae:2039.45466
[583]	validation_0-mae:2039.32807
[584]	validation_0-mae:2039.00461
[585]	validation_0-mae:2039.08129
[586]	validation_0-mae:2039.08354
[587]	validation_0-mae:2039.32469
[588]	validation_0-mae:2039.50660
[589]	validation_0-mae:2039.38517
[590]	validation_0-mae:2039.43027

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[46]	validation_0-mae:2996.38050
[47]	validation_0-mae:2974.09977
[48]	validation_0-mae:2954.96253
[49]	validation_0-mae:2923.92424
[50]	validation_0-mae:2905.25059
[51]	validation_0-mae:2889.28698
[52]	validation_0-mae:2871.88625
[53]	validation_0-mae:2844.24691
[54]	validation_0-mae:2820.21569
[55]	validation_0-mae:2804.82567
[56]	validation_0-mae:2783.66961
[57]	validation_0-mae:2767.74798
[58]	validation_0-mae:2742.00736
[59]	validation_0-mae:2727.63937
[60]	validation_0-mae:2717.74669
[61]	validation_0-mae:2703.54181
[62]	validation_0-mae:2687.42257
[63]	validation_0-mae:2674.00769
[64]	validation_0-mae:2660.80791
[65]	validation_0-mae:2648.47345
[66]	validation_0-mae:2641.45538
[67]	validation_0-mae:2626.07764
[68]	validation_0-mae:2619.48456
[69]	validation_0-mae:2610.60147
[70]	validation_0-mae:2597.20674
[71]	validation_0-mae:2578.13886
[72]	validation_0-mae:2570.58472
[73]	validation_0-mae:2558.51161
[74]	validation_0-mae:2556.66478
[75]	validation_0-mae:2544.32098
[76]	validation_0-mae:2536.89693
[77]	validation_0-mae:2527.14155
[78]	validation_0-mae:2520.81782
[79]	validation_0-mae:2513.03488
[80]	validation_0-mae:2502.72127
[81]	validation_0-mae:2497.27920
[82]	validation_0-mae:2483.57512
[83]	validation_0-mae:2478.04925
[84]	validation_0-mae:2471.00041
[85]	validation_0-mae:2464.91422
[86]	validation_0-mae:2457.26774
[87]	validation_0-mae:2450.05121
[88]	validation_0-mae:2440.08133
[89]	validation_0-mae:2438.15804
[90]	validation_0-mae:2436.89196
[91]	validation_0-mae:2430.83808
[92]	validation_0-mae:2418.68563
[93]	validation_0-mae:2414.48231
[94]	validation_0-mae:2409.77530
[95]	validation_0-mae:2403.23320
[96]	validation_0-mae:2400.94426
[0]	validation_0-mae:12382.86545
[1]	validation_0-mae:11603.11279
[2]	validation_0-mae:10909.78054
[3]	validation_0-mae:10317.50778
[4]	validation_0-mae:9787.21537
[5]	validation_0-mae:9285.44134
[6]	validation_0-mae:8884.61274
[7]	validation_0-mae:8498.08211
[8]	validation_0-mae:8176.66472
[9]	validation_0-mae:7887.97654
[10]	validation_0-mae:7620.66386

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[0]	validation_0-mae:12393.48028
[1]	validation_0-mae:11615.07964
[2]	validation_0-mae:10906.13397
[3]	validation_0-mae:10266.70733
[4]	validation_0-mae:9702.62934
[5]	validation_0-mae:9171.66820
[6]	validation_0-mae:8741.81505
[7]	validation_0-mae:8318.76424
[8]	validation_0-mae:7940.87969
[9]	validation_0-mae:7611.61028
[10]	validation_0-mae:7292.19297
[11]	validation_0-mae:7009.64348
[12]	validation_0-mae:6728.42387
[13]	validation_0-mae:6479.89119
[14]	validation_0-mae:6254.42086
[15]	validation_0-mae:6014.88830
[16]	validation_0-mae:5830.37889
[17]	validation_0-mae:5613.06804
[18]	validation_0-mae:5414.80372
[19]	validation_0-mae:5241.12129
[20]	validation_0-mae:5058.51596
[21]	validation_0-mae:4898.49327
[22]	validation_0-mae:4748.51644
[23]	validation_0-mae:4619.87884
[24]	validation_0-mae:4494.83404
[25]	validation_0-mae:4398.86877
[26]	validation_0-mae:4282.05540
[27]	validation_0-mae:4175.77414
[28]	validation_0-mae:4082.20490
[29]	validation_0-mae:3976.70555
[30]	validation_0-mae:3888.85247
[31]	validation_0-mae:3798.92069
[32]	validation_0-mae:3725.11950
[33]	validation_0-mae:3656.16063
[34]	validation_0-mae:3585.56184
[35]	validation_0-mae:3517.39626
[36]	validation_0-mae:3460.26428
[37]	validation_0-mae:3415.34547
[38]	validation_0-mae:3364.31030
[39]	validation_0-mae:3300.19420
[40]	validation_0-mae:3259.78979
[41]	validation_0-mae:3217.28261
[42]	validation_0-mae:3165.69284
[43]	validation_0-mae:3131.84753
[44]	validation_0-mae:3104.77282
[45]	validation_0-mae:3073.23884
[46]	validation_0-mae:3030.62097
[47]	validation_0-mae:2989.65790
[48]	validation_0-mae:2968.72799
[49]	validation_0-mae:2948.73576
[50]	validation_0-mae:2923.54811
[51]	validation_0-mae:2897.43681
[52]	validation_0-mae:2875.93207
[53]	validation_0-mae:2861.29135
[54]	validation_0-mae:2842.48400
[55]	validation_0-mae:2807.92242
[56]	validation_0-mae:2795.86308
[57]	validation_0-mae:2779.08312
[58]	validation_0-mae:2769.27385
[59]	validation_0-mae:2753.77942
[60]	validation_0-mae:2738.24513
[61]	validation_0-mae:2730.83341
[62]	validation_0-mae:2709.00900
[63]	validation_0-mae:2692.26959
[64]	validation_0-mae:2682.27177
[65]	validation_0-mae:2665.51862
[66]	validation_0-mae:2658.29832
[67]	validation_0-mae:2647.51152
[68]	validation_0-mae:2629.68232
[69]	validation_0-mae:2623.39834
[70]	validation_0-mae:2611.86728
[71]	validation_0-mae:2592.10660
[72]	validation_0-mae:2584.33202
[73]	validation_0-mae:2574.89275
[74]	validation_0-mae:2560.13252
[75]	validation_0-mae:2550.15158
[76]	validation_0-mae:2542.95632
[77]	validation_0-mae:2532.68364
[78]	validation_0-mae:2517.48144
[79]	validation_0-mae:2512.62684
[80]	validation_0-mae:2501.03619
[81]	validation_0-mae:2491.07257
[82]	validation_0-mae:2483.51234
[83]	validation_0-mae:2468.66493
[84]	validation_0-mae:2459.88271
[85]	validation_0-mae:2456.99424
[86]	validation_0-mae:2450.02250
[87]	validation_0-mae:2442.88810
[88]	validation_0-mae:2434.22940
[89]	validation_0-mae:2426.41203
[90]	validation_0-mae:2421.65103
[91]	validation_0-mae:2416.74541
[92]	validation_0-mae:2414.82137
[93]	validation_0-mae:2408.31799
[94]	validation_0-mae:2397.59470
[95]	validation_0-mae:2391.07219
[96]	validation_0-mae:2385.66736
[97]	validation_0-mae:2378.39212
[98]	validation_0-mae:2371.33166
[99]	validation_0-mae:2364.06587
[100]	validation_0-mae:2357.37067
[101]	validation_0-mae:2351.99118
[102]	validation_0-mae:2349.45698
[103]	validation_0-mae:2344.72156
[104]	validation_0-mae:2343.50290
[105]	validation_0-mae:2338.40538
[106]	validation_0-mae:2334.18463
[107]	validation_0-mae:2328.48925
[108]	validation_0-mae:2325.79239
[109]	validation_0-mae:2324.81106
[110]	validation_0-mae:2323.90599
[111]	validation_0-mae:2320.40820
[112]	validation_0-mae:2315.80987
[113]	validation_0-mae:2310.11256
[114]	validation_0-mae:2309.00909
[115]	validation_0-mae:2301.51664
[116]	validation_0-mae:2297.89584
[117]	validation_0-mae:2293.25824
[118]	validation_0-mae:2287.31123
[119]	validation_0-mae:2286.58811
[120]	validation_0-mae:2285.20121
[121]	validation_0-mae:2280.21257
[122]	validation_0-mae:2275.63530
[123]	validation_0-mae:2272.88082
[124]	validation_0-mae:2269.18757
[125]	validation_0-mae:2268.97493
[126]	validation_0-mae:2265.80254
[127]	validation_0-mae:2260.72150
[128]	validation_0-mae:2258.86190
[129]	validation_0-mae:2255.60159
[130]	validation_0-mae:2251.99630
[131]	validation_0-mae:2251.90300
[132]	validation_0-mae:2249.01632
[133]	validation_0-mae:2247.90723
[134]	validation_0-mae:2242.83380
[135]	validation_0-mae:2237.09076
[136]	validation_0-mae:2236.36070
[137]	validation_0-mae:2237.09166
[138]	validation_0-mae:2233.14497
[139]	validation_0-mae:2229.71720
[140]	validation_0-mae:2230.39338
[141]	validation_0-mae:2225.69440
[142]	validation_0-mae:2225.92931
[143]	validation_0-mae:2225.92133
[144]	validation_0-mae:2225.06414
[145]	validation_0-mae:2224.49387
[146]	validation_0-mae:2223.28827
[147]	validation_0-mae:2220.63807
[148]	validation_0-mae:2217.01447
[149]	validation_0-mae:2216.21494
[150]	validation_0-mae:2215.08160
[151]	validation_0-mae:2212.53216
[152]	validation_0-mae:2210.96138
[153]	validation_0-mae:2210.44691
[154]	validation_0-mae:2210.22319
[155]	validation_0-mae:2207.76262
[156]	validation_0-mae:2205.15361
[157]	validation_0-mae:2203.97661
[158]	validation_0-mae:2202.28637
[159]	validation_0-mae:2200.67991
[160]	validation_0-mae:2198.38196
[161]	validation_0-mae:2196.43893
[162]	validation_0-mae:2194.40042
[163]	validation_0-mae:2193.32967
[164]	validation_0-mae:2191.94169
[165]	validation_0-mae:2190.27531
[166]	validation_0-mae:2189.42292
[167]	validation_0-mae:2187.85183
[168]	validation_0-mae:2184.50172
[169]	validation_0-mae:2182.66193
[170]	validation_0-mae:2179.72489
[171]	validation_0-mae:2179.69456
[172]	validation_0-mae:2178.17862
[173]	validation_0-mae:2177.71953
[174]	validation_0-mae:2177.58638
[175]	validation_0-mae:2177.85780
[176]	validation_0-mae:2178.72948
[177]	validation_0-mae:2178.39727
[178]	validation_0-mae:2177.22678
[179]	validation_0-mae:2177.03609
[180]	validation_0-mae:2173.55171
[181]	validation_0-mae:2174.06626
[182]	validation_0-mae:2171.90191
[183]	validation_0-mae:2171.64381
[184]	validation_0-mae:2170.82730
[185]	validation_0-mae:2170.85979
[186]	validation_0-mae:2172.05277
[187]	validation_0-mae:2172.96718
[188]	validation_0-mae:2170.81507
[189]	validation_0-mae:2170.55056
[190]	validation_0-mae:2170.92655
[191]	validation_0-mae:2171.03150
[192]	validation_0-mae:2170.84233
[193]	validation_0-mae:2168.09209
[194]	validation_0-mae:2167.86326
[195]	validation_0-mae:2165.58827
[196]	validation_0-mae:2163.62543
[197]	validation_0-mae:2161.11905
[198]	validation_0-mae:2160.32387
[199]	validation_0-mae:2159.69112
[200]	validation_0-mae:2158.85332
[201]	validation_0-mae:2158.01595
[202]	validation_0-mae:2158.16044
[203]	validation_0-mae:2157.29671
[204]	validation_0-mae:2158.10785
[205]	validation_0-mae:2156.88912
[206]	validation_0-mae:2156.49858
[207]	validation_0-mae:2155.33441
[208]	validation_0-mae:2155.10932
[209]	validation_0-mae:2155.65645
[210]	validation_0-mae:2153.44761
[211]	validation_0-mae:2153.14999
[212]	validation_0-mae:2152.33114
[213]	validation_0-mae:2151.64981
[214]	validation_0-mae:2150.81893
[215]	validation_0-mae:2151.04542
[216]	validation_0-mae:2151.03270
[217]	validation_0-mae:2151.30464
[218]	validation_0-mae:2149.77301
[219]	validation_0-mae:2148.45120
[220]	validation_0-mae:2148.49012
[221]	validation_0-mae:2148.81936
[222]	validation_0-mae:2149.27785
[223]	validation_0-mae:2148.51973
[224]	validation_0-mae:2145.74357
[225]	validation_0-mae:2146.47819
[226]	validation_0-mae:2146.34684
[227]	validation_0-mae:2144.34436
[228]	validation_0-mae:2144.16253
[229]	validation_0-mae:2144.22984
[230]	validation_0-mae:2143.11193
[231]	validation_0-mae:2142.32321
[232]	validation_0-mae:2142.41068
[233]	validation_0-mae:2140.56477
[234]	validation_0-mae:2138.20278
[235]	validation_0-mae:2136.89464
[236]	validation_0-mae:2136.45533
[237]	validation_0-mae:2137.42317
[238]	validation_0-mae:2137.50800
[239]	validation_0-mae:2137.61009
[240]	validation_0-mae:2136.54112
[241]	validation_0-mae:2137.49722
[242]	validation_0-mae:2137.22634
[243]	validation_0-mae:2137.64101
[244]	validation_0-mae:2136.19284
[245]	validation_0-mae:2134.43050
[246]	validation_0-mae:2134.02511
[247]	validation_0-mae:2133.02962
[248]	validation_0-mae:2132.77683
[249]	validation_0-mae:2132.58384
[250]	validation_0-mae:2132.85698
[251]	validation_0-mae:2131.71399
[252]	validation_0-mae:2131.59758
[253]	validation_0-mae:2131.82384
[254]	validation_0-mae:2131.46047
[255]	validation_0-mae:2130.57302
[256]	validation_0-mae:2130.63615
[257]	validation_0-mae:2128.94140
[258]	validation_0-mae:2129.21675
[259]	validation_0-mae:2128.03247
[260]	validation_0-mae:2128.10385
[261]	validation_0-mae:2126.00384
[262]	validation_0-mae:2126.36946
[263]	validation_0-mae:2126.29984
[264]	validation_0-mae:2126.12235
[265]	validation_0-mae:2126.52559
[266]	validation_0-mae:2126.42405
[267]	validation_0-mae:2126.59823
[268]	validation_0-mae:2125.98688
[269]	validation_0-mae:2125.59524
[270]	validation_0-mae:2125.04181
[271]	validation_0-mae:2125.12159
[272]	validation_0-mae:2124.97226
[273]	validation_0-mae:2124.32377
[274]	validation_0-mae:2123.91268
[275]	validation_0-mae:2124.63678
[276]	validation_0-mae:2125.11093
[277]	validation_0-mae:2125.45913
[278]	validation_0-mae:2125.81755
[279]	validation_0-mae:2125.83279
[280]	validation_0-mae:2125.71779
[281]	validation_0-mae:2125.35541
[282]	validation_0-mae:2125.00555
[283]	validation_0-mae:2124.57659
[284]	validation_0-mae:2125.19146
[285]	validation_0-mae:2125.37903
[286]	validation_0-mae:2125.38384
[287]	validation_0-mae:2124.62985
[288]	validation_0-mae:2124.91149
[289]	validation_0-mae:2124.61800
[290]	validation_0-mae:2124.01670
[291]	validation_0-mae:2124.41117
[292]	validation_0-mae:2124.36771
[293]	validation_0-mae:2124.70526
[294]	validation_0-mae:2124.36912
[295]	validation_0-mae:2124.35269
[296]	validation_0-mae:2125.05092
[297]	validation_0-mae:2124.20248
[298]	validation_0-mae:2124.92743
[299]	validation_0-mae:2123.75304
[300]	validation_0-mae:2123.79986
[301]	validation_0-mae:2123.59490
[302]	validation_0-mae:2124.05992
[303]	validation_0-mae:2124.06423
[304]	validation_0-mae:2123.49190
[305]	validation_0-mae:2123.86656
[306]	validation_0-mae:2124.71790
[307]	validation_0-mae:2124.67176
[308]	validation_0-mae:2124.06324
[309]	validation_0-mae:2124.08739
[310]	validation_0-mae:2124.47881
[311]	validation_0-mae:2124.36864
[312]	validation_0-mae:2124.09415
[313]	validation_0-mae:2124.55297
[314]	validation_0-mae:2123.88041
[315]	validation_0-mae:2123.69077
[316]	validation_0-mae:2123.24041
[317]	validation_0-mae:2122.15415
[318]	validation_0-mae:2120.21474
[319]	validation_0-mae:2120.26200
[320]	validation_0-mae:2121.15937
[321]	validation_0-mae:2121.22752
[322]	validation_0-mae:2121.04777
[323]	validation_0-mae:2121.83939
[324]	validation_0-mae:2120.38242
[325]	validation_0-mae:2120.31276
[326]	validation_0-mae:2119.86979
[327]	validation_0-mae:2120.04543
[328]	validation_0-mae:2120.35126
[329]	validation_0-mae:2119.36363
[330]	validation_0-mae:2118.94684
[331]	validation_0-mae:2117.93715
[332]	validation_0-mae:2118.34023
[333]	validation_0-mae:2117.42599
[334]	validation_0-mae:2116.08246
[335]	validation_0-mae:2114.95940
[336]	validation_0-mae:2114.33014
[337]	validation_0-mae:2114.33308
[338]	validation_0-mae:2114.23857
[339]	validation_0-mae:2114.17348
[340]	validation_0-mae:2114.44166
[341]	validation_0-mae:2114.12052
[342]	validation_0-mae:2114.11063
[343]	validation_0-mae:2113.82098
[344]	validation_0-mae:2113.68786
[345]	validation_0-mae:2113.64917
[346]	validation_0-mae:2113.93343
[347]	validation_0-mae:2111.95940
[348]	validation_0-mae:2112.19811
[349]	validation_0-mae:2110.94525
[350]	validation_0-mae:2110.75912
[351]	validation_0-mae:2110.71741
[352]	validation_0-mae:2110.19048
[353]	validation_0-mae:2110.40466
[354]	validation_0-mae:2108.40082
[355]	validation_0-mae:2108.74655
[356]	validation_0-mae:2108.55686
[357]	validation_0-mae:2107.19094
[358]	validation_0-mae:2106.67601
[359]	validation_0-mae:2106.07774
[360]	validation_0-mae:2105.30186
[361]	validation_0-mae:2103.71012
[362]	validation_0-mae:2104.01812
[363]	validation_0-mae:2103.58735
[364]	validation_0-mae:2103.26356
[365]	validation_0-mae:2102.97784
[366]	validation_0-mae:2102.79144
[367]	validation_0-mae:2102.66672
[368]	validation_0-mae:2102.08793
[369]	validation_0-mae:2102.02854
[370]	validation_0-mae:2101.19985
[371]	validation_0-mae:2101.28690
[372]	validation_0-mae:2100.88078
[373]	validation_0-mae:2100.29108
[374]	validation_0-mae:2100.13733
[375]	validation_0-mae:2099.05904
[376]	validation_0-mae:2099.20778
[377]	validation_0-mae:2098.60951
[378]	validation_0-mae:2098.82555
[379]	validation_0-mae:2098.01048
[380]	validation_0-mae:2097.04130
[381]	validation_0-mae:2097.44166
[382]	validation_0-mae:2097.82551
[383]	validation_0-mae:2097.48516
[384]	validation_0-mae:2097.34304
[385]	validation_0-mae:2097.32739
[386]	validation_0-mae:2096.73583
[387]	validation_0-mae:2097.12968
[388]	validation_0-mae:2097.01757
[389]	validation_0-mae:2096.26990
[390]	validation_0-mae:2096.03905
[391]	validation_0-mae:2095.46447
[392]	validation_0-mae:2095.89168
[393]	validation_0-mae:2095.36802
[394]	validation_0-mae:2095.41436
[395]	validation_0-mae:2094.86115
[396]	validation_0-mae:2094.51454
[397]	validation_0-mae:2095.15148
[398]	validation_0-mae:2095.39029
[399]	validation_0-mae:2095.76409
[400]	validation_0-mae:2096.54396
[401]	validation_0-mae:2096.91101
[402]	validation_0-mae:2097.58719
[403]	validation_0-mae:2097.00562
[404]	validation_0-mae:2095.85601
[405]	validation_0-mae:2096.16977
[406]	validation_0-mae:2096.03427
[407]	validation_0-mae:2096.25398
[408]	validation_0-mae:2096.45053
[409]	validation_0-mae:2096.57714
[410]	validation_0-mae:2096.73917
[411]	validation_0-mae:2096.84926
[412]	validation_0-mae:2095.67642
[413]	validation_0-mae:2095.31960
[414]	validation_0-mae:2095.13609
[415]	validation_0-mae:2095.60197
[416]	validation_0-mae:2095.88102
[417]	validation_0-mae:2095.78355
[418]	validation_0-mae:2095.84130
[419]	validation_0-mae:2095.93024
[420]	validation_0-mae:2095.79543
[421]	validation_0-mae:2095.48023
[422]	validation_0-mae:2095.97733
[423]	validation_0-mae:2096.55121
[424]	validation_0-mae:2097.06914
[425]	validation_0-mae:2095.74043
[426]	validation_0-mae:2095.70628
[427]	validation_0-mae:2095.14939
[428]	validation_0-mae:2095.20038
[429]	validation_0-mae:2094.30253
[430]	validation_0-mae:2094.53167
[431]	validation_0-mae:2094.89462
[432]	validation_0-mae:2094.69988
[433]	validation_0-mae:2094.81154
[434]	validation_0-mae:2095.02077
[435]	validation_0-mae:2094.82918
[436]	validation_0-mae:2095.04425
[437]	validation_0-mae:2095.39569
[438]	validation_0-mae:2095.43928
[439]	validation_0-mae:2095.12340
[440]	validation_0-mae:2095.41552
[441]	validation_0-mae:2095.24627
[442]	validation_0-mae:2095.26264
[443]	validation_0-mae:2095.14084
[444]	validation_0-mae:2095.69428
[445]	validation_0-mae:2095.69410
[446]	validation_0-mae:2095.65977
[447]	validation_0-mae:2095.54507
[448]	validation_0-mae:2095.53591
[449]	validation_0-mae:2095.45025
[450]	validation_0-mae:2095.09093
[451]	validation_0-mae:2094.90376
[452]	validation_0-mae:2094.57729
[453]	validation_0-mae:2094.66836
[454]	validation_0-mae:2094.73619
[455]	validation_0-mae:2094.73185
[456]	validation_0-mae:2094.58731
[457]	validation_0-mae:2094.59745
[458]	validation_0-mae:2095.03142
[459]	validation_0-mae:2094.91196
[460]	validation_0-mae:2094.45566
[461]	validation_0-mae:2094.38319
[462]	validation_0-mae:2094.35136
[463]	validation_0-mae:2094.46632
[464]	validation_0-mae:2094.56237
[465]	validation_0-mae:2094.53979
[466]	validation_0-mae:2093.61311
[467]	validation_0-mae:2092.89785
[468]	validation_0-mae:2092.95665
[469]	validation_0-mae:2092.70045
[470]	validation_0-mae:2093.15568
[471]	validation_0-mae:2093.12581
[472]	validation_0-mae:2092.77995
[473]	validation_0-mae:2092.73767
[474]	validation_0-mae:2092.81085
[475]	validation_0-mae:2093.04294
[476]	validation_0-mae:2093.40540
[477]	validation_0-mae:2093.73380
[478]	validation_0-mae:2094.05788
[479]	validation_0-mae:2094.24079
[480]	validation_0-mae:2094.18915
[481]	validation_0-mae:2093.85943
[482]	validation_0-mae:2093.67746
[483]	validation_0-mae:2093.79605
[484]	validation_0-mae:2093.42205
[485]	validation_0-mae:2093.48807
[486]	validation_0-mae:2093.46207
[487]	validation_0-mae:2093.38808
[488]	validation_0-mae:2093.28636
[489]	validation_0-mae:2093.73673
[490]	validation_0-mae:2093.08597
[491]	validation_0-mae:2093.16526
[492]	validation_0-mae:2093.51338
[493]	validation_0-mae:2093.77867
[494]	validation_0-mae:2094.06838
[495]	validation_0-mae:2094.10151
[496]	validation_0-mae:2094.18916
[497]	validation_0-mae:2094.07939
[498]	validation_0-mae:2094.26125
[499]	validation_0-mae:2093.99625
[500]	validation_0-mae:2093.31659
[501]	validation_0-mae:2093.78615
[502]	validation_0-mae:2093.03146
[503]	validation_0-mae:2092.72912
[504]	validation_0-mae:2092.83475
[505]	validation_0-mae:2092.66258
[506]	validation_0-mae:2093.08966
[507]	validation_0-mae:2093.14330
[508]	validation_0-mae:2093.04167
[509]	validation_0-mae:2093.06021
[510]	validation_0-mae:2092.70229
[511]	validation_0-mae:2093.00324
[512]	validation_0-mae:2092.89855
[513]	validation_0-mae:2092.40184
[514]	validation_0-mae:2092.73627
[515]	validation_0-mae:2092.93594
[516]	validation_0-mae:2092.75308
[517]	validation_0-mae:2092.64541
[518]	validation_0-mae:2092.79580
[519]	validation_0-mae:2093.05428
[520]	validation_0-mae:2092.81111
[521]	validation_0-mae:2092.87916
[522]	validation_0-mae:2092.86400
[523]	validation_0-mae:2093.02896
[524]	validation_0-mae:2093.15588
[525]	validation_0-mae:2093.22660
[526]	validation_0-mae:2093.05537
[527]	validation_0-mae:2093.14541
[528]	validation_0-mae:2092.64200
[529]	validation_0-mae:2091.99394
[530]	validation_0-mae:2091.83201
[531]	validation_0-mae:2091.95791
[532]	validation_0-mae:2091.35154
[533]	validation_0-mae:2091.48031
[534]	validation_0-mae:2091.10603
[535]	validation_0-mae:2091.24702
[536]	validation_0-mae:2091.51393
[537]	validation_0-mae:2091.17064
[538]	validation_0-mae:2091.35263
[539]	validation_0-mae:2091.42327
[540]	validation_0-mae:2091.38900
[541]	validation_0-mae:2091.41892
[542]	validation_0-mae:2091.14618
[543]	validation_0-mae:2091.22111
[544]	validation_0-mae:2091.04706
[545]	validation_0-mae:2091.20065
[546]	validation_0-mae:2091.20801
[547]	validation_0-mae:2091.34648
[548]	validation_0-mae:2091.38353
[549]	validation_0-mae:2091.62530
[550]	validation_0-mae:2091.73175
[551]	validation_0-mae:2091.98693
[552]	validation_0-mae:2091.49422
[553]	validation_0-mae:2091.81961
[554]	validation_0-mae:2090.46287
[555]	validation_0-mae:2090.46548
[556]	validation_0-mae:2090.61523
[557]	validation_0-mae:2090.52864
[558]	validation_0-mae:2090.53511
[559]	validation_0-mae:2090.41884
[560]	validation_0-mae:2090.62240
[561]	validation_0-mae:2090.67945
[562]	validation_0-mae:2090.76066
[563]	validation_0-mae:2090.64026
[564]	validation_0-mae:2090.32490
[565]	validation_0-mae:2090.11195
[566]	validation_0-mae:2090.55339
[567]	validation_0-mae:2090.69224
[568]	validation_0-mae:2090.29891
[569]	validation_0-mae:2090.58204
[570]	validation_0-mae:2090.09734
[571]	validation_0-mae:2089.76452
[572]	validation_0-mae:2090.14037
[573]	validation_0-mae:2090.54623
[574]	validation_0-mae:2090.78200
[575]	validation_0-mae:2090.99905
[576]	validation_0-mae:2090.85133
[577]	validation_0-mae:2090.85303
[578]	validation_0-mae:2090.32451
[579]	validation_0-mae:2090.27468
[580]	validation_0-mae:2090.47556
[581]	validation_0-mae:2090.14624
[582]	validation_0-mae:2090.33097
[583]	validation_0-mae:2090.33414
[584]	validation_0-mae:2090.42167
[585]	validation_0-mae:2089.96121
[586]	validation_0-mae:2090.06818
[587]	validation_0-mae:2089.97912
[588]	validation_0-mae:2089.59419
[589]	validation_0-mae:2089.53042
[590]	validation_0-mae:2089.65121

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[33]	validation_0-mae:3522.67699
[34]	validation_0-mae:3459.94828
[35]	validation_0-mae:3419.49741
[36]	validation_0-mae:3373.59646
[37]	validation_0-mae:3308.71720
[38]	validation_0-mae:3241.42897
[39]	validation_0-mae:3206.04772
[40]	validation_0-mae:3171.11611
[41]	validation_0-mae:3140.38849
[42]	validation_0-mae:3096.61597
[43]	validation_0-mae:3059.44757
[44]	validation_0-mae:3032.09973
[45]	validation_0-mae:2996.31512
[46]	validation_0-mae:2974.50985
[47]	validation_0-mae:2942.76834
[48]	validation_0-mae:2904.30777
[49]	validation_0-mae:2880.96587
[50]	validation_0-mae:2863.98814
[51]	validation_0-mae:2842.84132
[52]	validation_0-mae:2830.71873
[53]	validation_0-mae:2814.61520
[54]	validation_0-mae:2784.19578
[55]	validation_0-mae:2769.68978
[56]	validation_0-mae:2761.38687
[57]	validation_0-mae:2750.91006
[58]	validation_0-mae:2731.38486
[59]	validation_0-mae:2702.51749
[60]	validation_0-mae:2680.18142
[61]	validation_0-mae:2668.56396
[62]	validation_0-mae:2656.54797
[63]	validation_0-mae:2645.46973
[64]	validation_0-mae:2634.69226
[65]	validation_0-mae:2623.32542
[66]	validation_0-mae:2613.65345
[67]	validation_0-mae:2600.81643
[68]	validation_0-mae:2592.77863
[69]	validation_0-mae:2580.57957
[70]	validation_0-mae:2566.36968
[71]	validation_0-mae:2556.90532
[72]	validation_0-mae:2550.80873
[73]	validation_0-mae:2537.68925
[74]	validation_0-mae:2527.44471
[75]	validation_0-mae:2515.39523
[76]	validation_0-mae:2509.37194
[77]	validation_0-mae:2495.58082
[78]	validation_0-mae:2490.18601
[79]	validation_0-mae:2481.55428
[80]	validation_0-mae:2475.79094
[81]	validation_0-mae:2460.00272
[82]	validation_0-mae:2452.61075
[83]	validation_0-mae:2445.82864
[84]	validation_0-mae:2432.95350
[85]	validation_0-mae:2425.94517
[86]	validation_0-mae:2421.51123
[87]	validation_0-mae:2416.09665
[88]	validation_0-mae:2409.90237
[89]	validation_0-mae:2401.78618
[90]	validation_0-mae:2398.28735
[91]	validation_0-mae:2391.23934
[92]	validation_0-mae:2383.19209
[93]	validation_0-mae:2376.46464
[94]	validation_0-mae:2371.16689
[95]	validation_0-mae:2366.54045
[96]	validation_0-mae:2359.22270
[97]	validation_0-mae:2353.54074
[98]	validation_0-mae:2345.99949
[99]	validation_0-mae:2344.65453
[100]	validation_0-mae:2340.00898
[101]	validation_0-mae:2337.15186
[102]	validation_0-mae:2332.86185
[103]	validation_0-mae:2328.21211
[104]	validation_0-mae:2322.13136
[105]	validation_0-mae:2319.99172
[106]	validation_0-mae:2316.30766
[107]	validation_0-mae:2315.04105
[108]	validation_0-mae:2313.57832
[109]	validation_0-mae:2310.57658
[110]	validation_0-mae:2308.87352
[111]	validation_0-mae:2302.87461
[112]	validation_0-mae:2303.13157
[113]	validation_0-mae:2300.80847
[114]	validation_0-mae:2297.82282
[115]	validation_0-mae:2297.66020
[116]	validation_0-mae:2296.72735
[117]	validation_0-mae:2296.27027
[118]	validation_0-mae:2288.54650
[119]	validation_0-mae:2284.97419
[120]	validation_0-mae:2283.22662
[121]	validation_0-mae:2282.30530
[122]	validation_0-mae:2280.22564
[123]	validation_0-mae:2276.59459
[124]	validation_0-mae:2272.01360
[125]	validation_0-mae:2270.07475
[126]	validation_0-mae:2270.08046
[127]	validation_0-mae:2267.41243
[128]	validation_0-mae:2265.37656
[129]	validation_0-mae:2263.28512
[130]	validation_0-mae:2262.63819
[131]	validation_0-mae:2259.12167
[132]	validation_0-mae:2253.55357
[133]	validation_0-mae:2252.88098
[134]	validation_0-mae:2252.54294
[135]	validation_0-mae:2249.11664
[136]	validation_0-mae:2245.90872
[137]	validation_0-mae:2242.55091
[138]	validation_0-mae:2239.32096
[139]	validation_0-mae:2238.68270
[140]	validation_0-mae:2237.47476
[141]	validation_0-mae:2235.96421
[142]	validation_0-mae:2231.72241
[143]	validation_0-mae:2229.35311
[144]	validation_0-mae:2227.81593
[145]	validation_0-mae:2225.13269
[146]	validation_0-mae:2223.39413
[147]	validation_0-mae:2221.14349
[148]	validation_0-mae:2223.09781
[149]	validation_0-mae:2221.51476
[150]	validation_0-mae:2222.20750
[151]	validation_0-mae:2222.51998
[152]	validation_0-mae:2222.41758
[153]	validation_0-mae:2223.58285
[154]	validation_0-mae:2220.33181
[155]	validation_0-mae:2219.09085
[156]	validation_0-mae:2217.62201
[157]	validation_0-mae:2216.18380
[158]	validation_0-mae:2215.21247
[159]	validation_0-mae:2213.05982
[160]	validation_0-mae:2212.03130
[161]	validation_0-mae:2211.28619
[162]	validation_0-mae:2212.51842
[163]	validation_0-mae:2211.53628
[164]	validation_0-mae:2208.16053
[165]	validation_0-mae:2206.26995
[166]	validation_0-mae:2205.34680
[167]	validation_0-mae:2204.24187
[168]	validation_0-mae:2202.11108
[169]	validation_0-mae:2199.75366
[170]	validation_0-mae:2199.52812
[171]	validation_0-mae:2198.39303
[172]	validation_0-mae:2199.67060
[173]	validation_0-mae:2198.14798
[174]	validation_0-mae:2197.79926
[175]	validation_0-mae:2196.93970
[176]	validation_0-mae:2196.82958
[177]	validation_0-mae:2196.43216
[178]	validation_0-mae:2195.89406
[179]	validation_0-mae:2195.99937
[180]	validation_0-mae:2195.48575
[181]	validation_0-mae:2193.42568
[182]	validation_0-mae:2193.04487
[183]	validation_0-mae:2190.86686
[184]	validation_0-mae:2189.70404
[185]	validation_0-mae:2190.92191
[186]	validation_0-mae:2190.48794
[187]	validation_0-mae:2190.58831
[188]	validation_0-mae:2190.61576
[189]	validation_0-mae:2190.14472
[190]	validation_0-mae:2190.33602
[191]	validation_0-mae:2190.19537
[192]	validation_0-mae:2189.82723
[193]	validation_0-mae:2190.11456
[194]	validation_0-mae:2188.96676
[195]	validation_0-mae:2188.85104
[196]	validation_0-mae:2188.06344
[197]	validation_0-mae:2187.70836
[198]	validation_0-mae:2187.30998
[199]	validation_0-mae:2187.20473
[200]	validation_0-mae:2188.82114
[201]	validation_0-mae:2188.34105
[202]	validation_0-mae:2187.76572
[0]	validation_0-mae:12506.46082
[1]	validation_0-mae:11836.87621
[2]	validation_0-mae:11261.80023
[3]	validation_0-mae:10772.65932
[4]	validation_0-mae:10369.36267
[5]	validation_0-mae:10021.08709
[6]	validation_0-mae:9715.56023
[7]	validation_0-mae:9457.93908
[8]	validation_0-mae:9237.76525
[9]	validation_0-mae:9063.30031
[0]	validation_0-mae:12482.03135

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[1]	validation_0-mae:11782.89261
[2]	validation_0-mae:11114.52650
[3]	validation_0-mae:10565.33918
[4]	validation_0-mae:10058.48629
[5]	validation_0-mae:9615.30261
[6]	validation_0-mae:9232.47710
[7]	validation_0-mae:8882.63626
[8]	validation_0-mae:8602.39291
[9]	validation_0-mae:8319.87734
[0]	validation_0-mae:12397.66935
[1]	validation_0-mae:11629.08229
[2]	validation_0-mae:10932.16639
[3]	validation_0-mae:10297.98456
[4]	validation_0-mae:9731.42641
[5]	validation_0-mae:9224.89920
[6]	validation_0-mae:8795.18030
[7]	validation_0-mae:8369.76652
[8]	validation_0-mae:7982.76007
[9]	validation_0-mae:7659.79184
[10]	validation_0-mae:7309.82999
[11]	validation_0-mae:6994.67693
[12]	validation_0-mae:6739.21197
[13]	validation_0-mae:6478.63365
[14]	validation_0-mae:6207.53947
[15]	validation_0-mae:6001.19675
[16]	validation_0-mae:5751.79971
[17]	validation_0-mae:5542.45830
[18]	validation_0-mae:5350.92187
[19]	validation_0-mae:5184.68884
[20]	validation_0-mae:5019.04059
[21]	validation_0-mae:4859.73098
[22]	validation_0-mae:4717.04351
[23]	validation_0-mae:4583.27363
[24]	validation_0-mae:4468.32861
[25]	validation_0-mae:4352.80557
[26]	validation_0-mae:4237.40344
[27]	validation_0-mae:4141.74208
[28]	validation_0-mae:4051.83314
[29]	validation_0-mae:3951.52097
[30]	validation_0-mae:3860.51398
[31]	validation_0-mae:3775.28536
[32]	validation_0-mae:3690.32787
[33]	validation_0-mae:3631.55893
[34]	validation_0-mae:3561.73676
[35]	validation_0-mae:3507.62979
[36]	validation_0-mae:3449.69611
[37]	validation_0-mae:3398.09465
[38]	validation_0-mae:3328.25567

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[39]	validation_0-mae:3275.76231
[40]	validation_0-mae:3238.73472
[41]	validation_0-mae:3199.47696
[42]	validation_0-mae:3161.14040
[43]	validation_0-mae:3128.62061
[44]	validation_0-mae:3104.41121
[45]	validation_0-mae:3062.67690
[46]	validation_0-mae:3033.42122
[47]	validation_0-mae:3002.59823
[48]	validation_0-mae:2963.85582
[49]	validation_0-mae:2936.81935
[50]	validation_0-mae:2909.27467
[51]	validation_0-mae:2881.98791
[52]	validation_0-mae:2857.11760
[53]	validation_0-mae:2835.30158
[54]	validation_0-mae:2818.77860
[55]	validation_0-mae:2794.53102
[56]	validation_0-mae:2764.94993
[57]	validation_0-mae:2747.77207
[58]	validation_0-mae:2735.60296
[59]	validation_0-mae:2710.23451
[60]	validation_0-mae:2699.56228
[61]	validation_0-mae:2688.95116
[62]	validation_0-mae:2675.02230
[63]	validation_0-mae:2657.15182
[64]	validation_0-mae:2648.31070
[65]	validation_0-mae:2636.38959
[66]	validation_0-mae:2623.94608
[67]	validation_0-mae:2615.58598
[68]	validation_0-mae:2601.13329
[69]	validation_0-mae:2594.87327
[70]	validation_0-mae:2579.72120
[71]	validation_0-mae:2558.43989
[72]	validation_0-mae:2551.07500
[73]	validation_0-mae:2542.76994
[74]	validation_0-mae:2524.93109
[75]	validation_0-mae:2520.10131
[76]	validation_0-mae:2507.97941
[77]	validation_0-mae:2499.63084
[78]	validation_0-mae:2490.14161
[79]	validation_0-mae:2475.89901
[80]	validation_0-mae:2467.51401
[81]	validation_0-mae:2456.90788
[82]	validation_0-mae:2442.47708
[83]	validation_0-mae:2435.95946
[84]	validation_0-mae:2426.41215
[85]	validation_0-mae:2423.81390
[86]	validation_0-mae:2416.46081
[87]	validation_0-mae:2411.15260
[88]	validation_0-mae:2406.88868
[89]	validation_0-mae:2401.30224
[90]	validation_0-mae:2384.19163
[91]	validation_0-mae:2380.93178
[92]	validation_0-mae:2374.75947
[93]	validation_0-mae:2369.82087
[94]	validation_0-mae:2365.71986
[95]	validation_0-mae:2356.41879
[96]	validation_0-mae:2351.07129
[97]	validation_0-mae:2346.90562
[98]	validation_0-mae:2341.65835
[99]	validation_0-mae:2334.31754
[100]	validation_0-mae:2329.17245
[101]	validation_0-mae:2329.96004
[102]	validation_0-mae:2324.68680
[103]	validation_0-mae:2322.37501
[104]	validation_0-mae:2316.31195
[105]	validation_0-mae:2310.98940
[106]	validation_0-mae:2306.62726
[107]	validation_0-mae:2300.08095
[108]	validation_0-mae:2298.04877
[109]	validation_0-mae:2295.84602
[110]	validation_0-mae:2294.24344
[111]	validation_0-mae:2289.93082
[112]	validation_0-mae:2289.73957
[113]	validation_0-mae:2290.05112
[114]	validation_0-mae:2287.58409
[115]	validation_0-mae:2284.21351
[116]	validation_0-mae:2285.03221
[117]	validation_0-mae:2281.78571
[118]	validation_0-mae:2282.05419
[119]	validation_0-mae:2280.16560
[120]	validation_0-mae:2281.16232
[121]	validation_0-mae:2280.91187
[122]	validation_0-mae:2273.98292
[123]	validation_0-mae:2271.19725
[124]	validation_0-mae:2268.91112
[125]	validation_0-mae:2261.81209
[126]	validation_0-mae:2259.63281
[127]	validation_0-mae:2256.53078
[128]	validation_0-mae:2257.77529
[129]	validation_0-mae:2254.35084
[130]	validation_0-mae:2251.88150
[131]	validation_0-mae:2253.20404
[132]	validation_0-mae:2250.40986
[133]	validation_0-mae:2249.52796
[134]	validation_0-mae:2248.47005
[135]	validation_0-mae:2249.05504
[136]	validation_0-mae:2245.76597
[137]	validation_0-mae:2245.33131
[138]	validation_0-mae:2244.75760
[139]	validation_0-mae:2243.73039
[140]	validation_0-mae:2242.88116
[141]	validation_0-mae:2242.41587
[142]	validation_0-mae:2238.60903
[143]	validation_0-mae:2239.74206
[144]	validation_0-mae:2239.98488
[145]	validation_0-mae:2238.62464
[146]	validation_0-mae:2236.97058
[147]	validation_0-mae:2238.12063
[148]	validation_0-mae:2235.53033
[149]	validation_0-mae:2235.43419
[150]	validation_0-mae:2234.63767
[151]	validation_0-mae:2231.53483
[152]	validation_0-mae:2231.25860
[153]	validation_0-mae:2230.05250
[154]	validation_0-mae:2229.04271
[155]	validation_0-mae:2225.57199
[156]	validation_0-mae:2223.46103
[157]	validation_0-mae:2221.45365
[158]	validation_0-mae:2221.61466
[159]	validation_0-mae:2221.09405
[160]	validation_0-mae:2214.52092
[161]	validation_0-mae:2214.94610
[162]	validation_0-mae:2214.10099
[163]	validation_0-mae:2214.62080
[164]	validation_0-mae:2211.43426
[165]	validation_0-mae:2209.89312
[166]	validation_0-mae:2210.59249
[167]	validation_0-mae:2209.56415
[168]	validation_0-mae:2206.68043
[169]	validation_0-mae:2204.72712
[170]	validation_0-mae:2204.20797
[171]	validation_0-mae:2205.12686
[172]	validation_0-mae:2202.46926
[173]	validation_0-mae:2201.73654
[174]	validation_0-mae:2201.99481
[175]	validation_0-mae:2199.85861
[176]	validation_0-mae:2197.58742
[177]	validation_0-mae:2196.69728
[178]	validation_0-mae:2196.03630
[179]	validation_0-mae:2196.76098
[180]	validation_0-mae:2193.70915
[181]	validation_0-mae:2193.25410
[182]	validation_0-mae:2192.94709
[183]	validation_0-mae:2193.14168
[184]	validation_0-mae:2191.22523
[185]	validation_0-mae:2189.06724
[186]	validation_0-mae:2186.18826
[187]	validation_0-mae:2185.27854
[188]	validation_0-mae:2183.09695
[189]	validation_0-mae:2183.12655
[190]	validation_0-mae:2181.01790
[191]	validation_0-mae:2179.70712
[192]	validation_0-mae:2178.10474
[193]	validation_0-mae:2178.42895
[194]	validation_0-mae:2178.66524
[195]	validation_0-mae:2177.26669
[196]	validation_0-mae:2178.46287
[197]	validation_0-mae:2178.92866
[198]	validation_0-mae:2176.56676
[199]	validation_0-mae:2173.67392
[200]	validation_0-mae:2173.77771
[201]	validation_0-mae:2172.83144
[202]	validation_0-mae:2170.44488
[203]	validation_0-mae:2170.77360
[204]	validation_0-mae:2169.32800
[205]	validation_0-mae:2169.33851
[206]	validation_0-mae:2169.35682
[207]	validation_0-mae:2168.89581
[208]	validation_0-mae:2168.26719
[209]	validation_0-mae:2166.77756
[210]	validation_0-mae:2166.41996
[211]	validation_0-mae:2165.49992
[212]	validation_0-mae:2165.04569
[213]	validation_0-mae:2164.75734
[214]	validation_0-mae:2162.10205
[215]	validation_0-mae:2160.70650
[216]	validation_0-mae:2158.57154
[217]	validation_0-mae:2157.69790
[218]	validation_0-mae:2157.16832
[219]	validation_0-mae:2156.86047
[220]	validation_0-mae:2155.29083
[221]	validation_0-mae:2154.08294
[222]	validation_0-mae:2154.99838
[223]	validation_0-mae:2155.22218
[224]	validation_0-mae:2154.10077
[225]	validation_0-mae:2153.99921
[226]	validation_0-mae:2151.87106
[227]	validation_0-mae:2151.56183
[228]	validation_0-mae:2150.96062
[229]	validation_0-mae:2150.62927
[230]	validation_0-mae:2150.39468
[231]	validation_0-mae:2150.10002
[232]	validation_0-mae:2149.42977
[233]	validation_0-mae:2149.03606
[234]	validation_0-mae:2148.37682
[235]	validation_0-mae:2148.18114
[236]	validation_0-mae:2148.31418
[237]	validation_0-mae:2146.82552
[238]	validation_0-mae:2146.95747
[239]	validation_0-mae:2146.87357
[240]	validation_0-mae:2145.39070
[241]	validation_0-mae:2145.59247
[242]	validation_0-mae:2145.97960
[243]	validation_0-mae:2144.98478
[244]	validation_0-mae:2144.39500
[245]	validation_0-mae:2142.22775
[246]	validation_0-mae:2142.26009
[247]	validation_0-mae:2142.23078
[248]	validation_0-mae:2142.62950
[249]	validation_0-mae:2142.13853
[250]	validation_0-mae:2142.16805
[251]	validation_0-mae:2139.17902
[252]	validation_0-mae:2139.57779
[253]	validation_0-mae:2138.95794
[254]	validation_0-mae:2138.59256
[255]	validation_0-mae:2138.53983
[256]	validation_0-mae:2137.11532
[257]	validation_0-mae:2136.32410
[258]	validation_0-mae:2136.54141
[259]	validation_0-mae:2135.03164
[260]	validation_0-mae:2134.55825
[261]	validation_0-mae:2134.00590
[262]	validation_0-mae:2132.58117
[263]	validation_0-mae:2131.26876
[264]	validation_0-mae:2130.13439
[265]	validation_0-mae:2129.17298
[266]	validation_0-mae:2129.77567
[267]	validation_0-mae:2127.70239
[268]	validation_0-mae:2127.92412
[269]	validation_0-mae:2127.90723
[270]	validation_0-mae:2126.44783
[271]	validation_0-mae:2126.92074
[272]	validation_0-mae:2124.84031
[273]	validation_0-mae:2124.84192
[274]	validation_0-mae:2124.46621
[275]	validation_0-mae:2124.82718
[276]	validation_0-mae:2124.86507
[277]	validation_0-mae:2124.59195
[278]	validation_0-mae:2124.85562
[279]	validation_0-mae:2125.09508
[280]	validation_0-mae:2124.74053
[281]	validation_0-mae:2122.53932
[282]	validation_0-mae:2121.01405
[283]	validation_0-mae:2121.32433
[284]	validation_0-mae:2120.20321
[285]	validation_0-mae:2120.13418
[286]	validation_0-mae:2119.81210
[287]	validation_0-mae:2119.21991
[288]	validation_0-mae:2119.69656
[289]	validation_0-mae:2119.63621
[290]	validation_0-mae:2118.70366
[291]	validation_0-mae:2117.87853
[292]	validation_0-mae:2117.93130
[293]	validation_0-mae:2117.87529
[294]	validation_0-mae:2118.06970
[295]	validation_0-mae:2118.31066
[296]	validation_0-mae:2117.07410
[297]	validation_0-mae:2116.99781
[298]	validation_0-mae:2116.22380
[299]	validation_0-mae:2116.01564
[300]	validation_0-mae:2115.92191
[301]	validation_0-mae:2115.23381
[302]	validation_0-mae:2114.79587
[303]	validation_0-mae:2114.17673
[304]	validation_0-mae:2113.41272
[305]	validation_0-mae:2113.79868
[306]	validation_0-mae:2113.82274
[307]	validation_0-mae:2114.51021
[308]	validation_0-mae:2113.97802
[309]	validation_0-mae:2113.30087
[310]	validation_0-mae:2112.04819
[311]	validation_0-mae:2108.47437
[312]	validation_0-mae:2108.54844
[313]	validation_0-mae:2108.68226
[314]	validation_0-mae:2108.11020
[315]	validation_0-mae:2108.59777
[316]	validation_0-mae:2108.76475
[317]	validation_0-mae:2108.71336
[318]	validation_0-mae:2108.87668
[319]	validation_0-mae:2108.78109
[320]	validation_0-mae:2107.22842
[321]	validation_0-mae:2107.52720
[322]	validation_0-mae:2107.18446
[323]	validation_0-mae:2105.93727
[324]	validation_0-mae:2106.38718
[325]	validation_0-mae:2104.35761
[326]	validation_0-mae:2104.78221
[327]	validation_0-mae:2105.08129
[328]	validation_0-mae:2105.63771
[329]	validation_0-mae:2106.35938
[330]	validation_0-mae:2106.53558
[331]	validation_0-mae:2106.61620
[332]	validation_0-mae:2106.49774
[333]	validation_0-mae:2106.27394
[334]	validation_0-mae:2106.67497
[335]	validation_0-mae:2106.09448
[336]	validation_0-mae:2105.73650
[337]	validation_0-mae:2104.69053
[338]	validation_0-mae:2104.64220
[339]	validation_0-mae:2105.06922
[340]	validation_0-mae:2105.49134
[341]	validation_0-mae:2105.84054
[342]	validation_0-mae:2106.31506
[343]	validation_0-mae:2105.46846
[344]	validation_0-mae:2104.17939
[345]	validation_0-mae:2104.71232
[346]	validation_0-mae:2103.72745
[347]	validation_0-mae:2103.61179
[348]	validation_0-mae:2103.15159
[349]	validation_0-mae:2102.79089
[350]	validation_0-mae:2102.53488
[351]	validation_0-mae:2101.58567
[352]	validation_0-mae:2102.17781
[353]	validation_0-mae:2102.36159
[354]	validation_0-mae:2102.08467
[355]	validation_0-mae:2101.64331
[356]	validation_0-mae:2100.42750
[357]	validation_0-mae:2100.18183
[358]	validation_0-mae:2100.23425
[359]	validation_0-mae:2099.98560
[360]	validation_0-mae:2100.04666
[361]	validation_0-mae:2100.49677
[362]	validation_0-mae:2100.16329
[363]	validation_0-mae:2100.42054
[364]	validation_0-mae:2100.62527
[365]	validation_0-mae:2100.71588
[366]	validation_0-mae:2100.78665
[367]	validation_0-mae:2100.85064
[368]	validation_0-mae:2100.27613
[369]	validation_0-mae:2099.97091
[370]	validation_0-mae:2099.69848
[371]	validation_0-mae:2099.10929
[372]	validation_0-mae:2098.69700
[373]	validation_0-mae:2098.19190
[374]	validation_0-mae:2096.34366
[375]	validation_0-mae:2095.96367
[376]	validation_0-mae:2095.66597
[377]	validation_0-mae:2096.18206
[378]	validation_0-mae:2096.34322
[379]	validation_0-mae:2096.53823
[380]	validation_0-mae:2095.66536
[381]	validation_0-mae:2095.26071
[382]	validation_0-mae:2095.07662
[383]	validation_0-mae:2095.13157
[384]	validation_0-mae:2094.84700
[385]	validation_0-mae:2094.84413
[386]	validation_0-mae:2094.79294
[387]	validation_0-mae:2094.95123
[388]	validation_0-mae:2093.78538
[389]	validation_0-mae:2093.65069
[390]	validation_0-mae:2093.88844
[391]	validation_0-mae:2093.71303
[392]	validation_0-mae:2093.95390
[393]	validation_0-mae:2092.07662
[394]	validation_0-mae:2092.02344
[395]	validation_0-mae:2091.73125
[396]	validation_0-mae:2091.43747
[397]	validation_0-mae:2091.89343
[398]	validation_0-mae:2090.95074
[399]	validation_0-mae:2091.09181
[400]	validation_0-mae:2090.69510
[401]	validation_0-mae:2091.24489
[402]	validation_0-mae:2091.18553
[403]	validation_0-mae:2090.44658
[404]	validation_0-mae:2089.92451
[405]	validation_0-mae:2090.28603
[406]	validation_0-mae:2089.09587
[407]	validation_0-mae:2088.85631
[408]	validation_0-mae:2088.41099
[409]	validation_0-mae:2088.02736
[410]	validation_0-mae:2087.34567
[411]	validation_0-mae:2087.69900
[412]	validation_0-mae:2088.16763
[413]	validation_0-mae:2087.92828
[414]	validation_0-mae:2087.59406
[415]	validation_0-mae:2087.87170
[416]	validation_0-mae:2087.79894
[417]	validation_0-mae:2087.92739
[418]	validation_0-mae:2088.09910
[419]	validation_0-mae:2088.28947
[420]	validation_0-mae:2088.45581
[421]	validation_0-mae:2088.42609
[422]	validation_0-mae:2088.48612
[423]	validation_0-mae:2088.54712
[424]	validation_0-mae:2088.79489
[425]	validation_0-mae:2088.91982
[426]	validation_0-mae:2088.60478
[427]	validation_0-mae:2087.64352
[428]	validation_0-mae:2087.54933
[429]	validation_0-mae:2087.60533
[430]	validation_0-mae:2087.03623
[431]	validation_0-mae:2086.88851
[432]	validation_0-mae:2086.64705
[433]	validation_0-mae:2087.13727
[434]	validation_0-mae:2087.21212
[435]	validation_0-mae:2087.04178
[436]	validation_0-mae:2087.37925
[437]	validation_0-mae:2087.70233
[438]	validation_0-mae:2086.87559
[439]	validation_0-mae:2087.16677
[440]	validation_0-mae:2086.71424
[441]	validation_0-mae:2086.27392
[442]	validation_0-mae:2086.50745
[443]	validation_0-mae:2086.35427
[444]	validation_0-mae:2084.97786
[445]	validation_0-mae:2085.06122
[446]	validation_0-mae:2085.31931
[447]	validation_0-mae:2085.44860
[448]	validation_0-mae:2085.04996
[449]	validation_0-mae:2084.74189
[450]	validation_0-mae:2085.05566
[451]	validation_0-mae:2085.36865
[452]	validation_0-mae:2085.56119
[453]	validation_0-mae:2085.48619
[454]	validation_0-mae:2085.17089
[455]	validation_0-mae:2085.19955
[456]	validation_0-mae:2085.19197
[457]	validation_0-mae:2085.62690
[458]	validation_0-mae:2085.06270
[459]	validation_0-mae:2084.78395
[460]	validation_0-mae:2084.21770
[461]	validation_0-mae:2083.98047
[462]	validation_0-mae:2084.09742
[463]	validation_0-mae:2084.53739
[464]	validation_0-mae:2084.93745
[465]	validation_0-mae:2084.98375
[466]	validation_0-mae:2085.33637
[467]	validation_0-mae:2083.35392
[468]	validation_0-mae:2083.63006
[469]	validation_0-mae:2083.04215
[470]	validation_0-mae:2082.52375
[471]	validation_0-mae:2082.62292
[472]	validation_0-mae:2082.90387
[473]	validation_0-mae:2082.77441
[474]	validation_0-mae:2082.89272
[475]	validation_0-mae:2082.74459
[476]	validation_0-mae:2082.82254
[477]	validation_0-mae:2082.44911
[478]	validation_0-mae:2082.22409
[479]	validation_0-mae:2082.50072
[480]	validation_0-mae:2082.43120
[481]	validation_0-mae:2082.56833
[482]	validation_0-mae:2082.39796
[483]	validation_0-mae:2082.00803
[484]	validation_0-mae:2082.17429
[485]	validation_0-mae:2082.34118
[486]	validation_0-mae:2082.47578
[487]	validation_0-mae:2082.59591
[488]	validation_0-mae:2082.60354
[489]	validation_0-mae:2082.75580
[490]	validation_0-mae:2082.71689
[491]	validation_0-mae:2083.04471
[492]	validation_0-mae:2083.13078
[493]	validation_0-mae:2083.02344
[494]	validation_0-mae:2082.68269
[495]	validation_0-mae:2082.73311
[496]	validation_0-mae:2082.62761
[497]	validation_0-mae:2082.92146
[498]	validation_0-mae:2082.27382
[499]	validation_0-mae:2082.71100
[500]	validation_0-mae:2082.31195
[501]	validation_0-mae:2082.32927
[502]	validation_0-mae:2082.20802
[503]	validation_0-mae:2082.30713
[504]	validation_0-mae:2081.49043
[505]	validation_0-mae:2080.96219
[506]	validation_0-mae:2080.64288
[507]	validation_0-mae:2079.59850
[508]	validation_0-mae:2078.95272
[509]	validation_0-mae:2079.16865
[510]	validation_0-mae:2078.56187
[511]	validation_0-mae:2078.61037
[512]	validation_0-mae:2078.90842
[513]	validation_0-mae:2079.19970
[514]	validation_0-mae:2079.43777
[515]	validation_0-mae:2079.53837
[516]	validation_0-mae:2079.83493
[517]	validation_0-mae:2079.89797
[518]	validation_0-mae:2079.22620
[519]	validation_0-mae:2079.32413
[520]	validation_0-mae:2078.47175
[521]	validation_0-mae:2078.40975
[522]	validation_0-mae:2078.14629
[523]	validation_0-mae:2077.99449
[524]	validation_0-mae:2077.69510
[525]	validation_0-mae:2077.46773
[526]	validation_0-mae:2077.18200
[527]	validation_0-mae:2077.12650
[528]	validation_0-mae:2076.93325
[529]	validation_0-mae:2076.93950
[530]	validation_0-mae:2076.96682
[531]	validation_0-mae:2076.70039
[532]	validation_0-mae:2076.67656
[533]	validation_0-mae:2076.82140
[534]	validation_0-mae:2076.83513
[535]	validation_0-mae:2076.71035
[536]	validation_0-mae:2077.29285
[537]	validation_0-mae:2077.93465
[538]	validation_0-mae:2078.25639
[539]	validation_0-mae:2078.78357
[540]	validation_0-mae:2078.13203
[541]	validation_0-mae:2078.59447
[542]	validation_0-mae:2078.79658
[543]	validation_0-mae:2078.96412
[544]	validation_0-mae:2079.06370
[545]	validation_0-mae:2079.27359
[546]	validation_0-mae:2079.20123
[547]	validation_0-mae:2079.29201
[548]	validation_0-mae:2079.21910
[549]	validation_0-mae:2079.32797
[550]	validation_0-mae:2079.44871
[551]	validation_0-mae:2079.61223
[552]	validation_0-mae:2079.59642
[553]	validation_0-mae:2079.46516
[554]	validation_0-mae:2079.41271
[555]	validation_0-mae:2079.17589
[556]	validation_0-mae:2078.02590
[557]	validation_0-mae:2077.90306
[558]	validation_0-mae:2077.49327
[559]	validation_0-mae:2077.40987
[560]	validation_0-mae:2077.22376
[561]	validation_0-mae:2077.27804
[562]	validation_0-mae:2077.00491
[563]	validation_0-mae:2076.58203
[564]	validation_0-mae:2076.37791
[565]	validation_0-mae:2076.69128
[566]	validation_0-mae:2076.19258
[567]	validation_0-mae:2076.57715
[568]	validation_0-mae:2076.62589
[569]	validation_0-mae:2076.68515
[570]	validation_0-mae:2077.16917
[571]	validation_0-mae:2076.62704
[572]	validation_0-mae:2076.32065
[573]	validation_0-mae:2076.19902
[574]	validation_0-mae:2076.08990
[575]	validation_0-mae:2075.90288
[576]	validation_0-mae:2075.83964
[577]	validation_0-mae:2075.72990
[578]	validation_0-mae:2075.91434
[579]	validation_0-mae:2076.00265
[580]	validation_0-mae:2076.31296
[581]	validation_0-mae:2076.59659
[582]	validation_0-mae:2075.85039
[583]	validation_0-mae:2075.85149
[584]	validation_0-mae:2075.66161
[585]	validation_0-mae:2075.58078
[586]	validation_0-mae:2075.48152
[587]	validation_0-mae:2075.31378
[588]	validation_0-mae:2074.94234
[589]	validation_0-mae:2074.93413
[590]	validation_0-mae:2074.82966
[591]	validation_0-mae:2075.26055
[592]	validation_0-mae:2075.23688
[593]	validation_0-mae:2075.58929
[594]	validation_0-mae:2075.26677
[595]	validation_0-mae:2075.35903
[596]	validation_0-mae:2075.60661
[597]	validation_0-mae:2075.48102
[598]	validation_0-mae:2075.55218
[599]	validation_0-mae:2075.45572
[600]	validation_0-mae:2075.52349
[601]	validation_0-mae:2075.86099
[602]	validation_0-mae:2076.24766
[603]	validation_0-mae:2075.49344
[604]	validation_0-mae:2075.16599
[605]	validation_0-mae:2075.05103
[606]	validation_0-mae:2074.88049
[607]	validation_0-mae:2075.17437
[608]	validation_0-mae:2075.07700
[609]	validation_0-mae:2075.39373
[610]	validation_0-mae:2075.49445
[611]	validation_0-mae:2075.51152
[612]	validation_0-mae:2075.67555
[613]	validation_0-mae:2075.77722
[614]	validation_0-mae:2075.66002
[615]	validation_0-mae:2075.58670
[616]	validation_0-mae:2075.40958
[617]	validation_0-mae:2075.42333
[618]	validation_0-mae:2075.49026
[619]	validation_0-mae:2075.69392
[620]	validation_0-mae:2075.74130
[621]	validation_0-mae:2075.52127
[622]	validation_0-mae:2075.35405
[623]	validation_0-mae:2074.79674
[624]	validation_0-mae:2074.26309
[625]	validation_0-mae:2074.62992
[626]	validation_0-mae:2074.33622
[627]	validation_0-mae:2074.31834
[628]	validation_0-mae:2074.33729

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[39]	validation_0-mae:3339.59937
[40]	validation_0-mae:3302.31815
[41]	validation_0-mae:3258.66284
[42]	validation_0-mae:3219.79862
[43]	validation_0-mae:3184.99885
[44]	validation_0-mae:3139.48237
[45]	validation_0-mae:3108.28859
[46]	validation_0-mae:3077.85068
[47]	validation_0-mae:3051.56859
[48]	validation_0-mae:3011.06644
[49]	validation_0-mae:2984.40017
[50]	validation_0-mae:2949.00362
[51]	validation_0-mae:2926.02895
[52]	validation_0-mae:2906.11664
[53]	validation_0-mae:2885.15176
[54]	validation_0-mae:2863.57864
[55]	validation_0-mae:2846.36956
[56]	validation_0-mae:2816.91187
[57]	validation_0-mae:2789.12870
[58]	validation_0-mae:2772.17579
[59]	validation_0-mae:2759.85912
[60]	validation_0-mae:2744.36058
[61]	validation_0-mae:2735.41488
[62]	validation_0-mae:2711.08196
[63]	validation_0-mae:2700.01970
[64]	validation_0-mae:2686.45547
[65]	validation_0-mae:2660.49042
[66]	validation_0-mae:2642.73140
[67]	validation_0-mae:2628.74582
[68]	validation_0-mae:2606.15775
[69]	validation_0-mae:2600.13014
[70]	validation_0-mae:2589.93083
[71]	validation_0-mae:2573.30262
[72]	validation_0-mae:2557.87364
[73]	validation_0-mae:2553.63631
[74]	validation_0-mae:2543.38387
[75]	validation_0-mae:2535.12635
[76]	validation_0-mae:2528.89099
[77]	validation_0-mae:2520.33773
[78]	validation_0-mae:2509.84455
[79]	validation_0-mae:2501.89532
[80]	validation_0-mae:2488.91165
[81]	validation_0-mae:2483.38509
[82]	validation_0-mae:2470.45896
[83]	validation_0-mae:2461.23847
[84]	validation_0-mae:2453.15514
[85]	validation_0-mae:2449.90763
[86]	validation_0-mae:2440.28470
[87]	validation_0-mae:2430.88786
[88]	validation_0-mae:2418.94288
[89]	validation_0-mae:2409.92349
[90]	validation_0-mae:2406.13468
[91]	validation_0-mae:2400.35681
[92]	validation_0-mae:2392.52099
[93]	validation_0-mae:2387.41140
[94]	validation_0-mae:2379.09659
[95]	validation_0-mae:2366.77343
[96]	validation_0-mae:2359.55181
[97]	validation_0-mae:2355.26224
[98]	validation_0-mae:2347.71297
[99]	validation_0-mae:2344.79654
[100]	validation_0-mae:2337.77432
[101]	validation_0-mae:2328.70843
[102]	validation_0-mae:2323.96934
[103]	validation_0-mae:2317.16468
[104]	validation_0-mae:2314.57614
[105]	validation_0-mae:2309.63843
[106]	validation_0-mae:2305.97708
[107]	validation_0-mae:2302.33720
[108]	validation_0-mae:2298.98648
[109]	validation_0-mae:2293.47596
[110]	validation_0-mae:2289.52981
[111]	validation_0-mae:2287.86305
[112]	validation_0-mae:2286.01884
[113]	validation_0-mae:2284.96030
[114]	validation_0-mae:2280.38131
[115]	validation_0-mae:2275.31580
[116]	validation_0-mae:2270.13129
[117]	validation_0-mae:2269.24885
[118]	validation_0-mae:2265.50313
[119]	validation_0-mae:2263.01483
[120]	validation_0-mae:2259.80966
[121]	validation_0-mae:2260.35984
[122]	validation_0-mae:2257.57740
[123]	validation_0-mae:2254.04984
[124]	validation_0-mae:2248.51875
[125]	validation_0-mae:2249.77376
[126]	validation_0-mae:2245.72296
[127]	validation_0-mae:2246.61176
[128]	validation_0-mae:2245.19409
[129]	validation_0-mae:2244.04142
[130]	validation_0-mae:2243.14944
[131]	validation_0-mae:2239.85611
[132]	validation_0-mae:2238.20910
[133]	validation_0-mae:2236.41761
[134]	validation_0-mae:2234.37595
[135]	validation_0-mae:2234.08919
[136]	validation_0-mae:2231.14066
[137]	validation_0-mae:2227.55024
[138]	validation_0-mae:2225.55009
[139]	validation_0-mae:2222.56488
[140]	validation_0-mae:2221.54313
[141]	validation_0-mae:2219.27311
[142]	validation_0-mae:2218.09442
[143]	validation_0-mae:2215.68028
[144]	validation_0-mae:2212.40357
[145]	validation_0-mae:2211.02909
[146]	validation_0-mae:2208.95566
[147]	validation_0-mae:2204.49577
[148]	validation_0-mae:2202.14701
[149]	validation_0-mae:2201.21934
[150]	validation_0-mae:2198.71448
[151]	validation_0-mae:2195.82865
[152]	validation_0-mae:2194.74825
[153]	validation_0-mae:2194.08422
[154]	validation_0-mae:2193.03081
[155]	validation_0-mae:2191.94484
[156]	validation_0-mae:2190.03879
[157]	validation_0-mae:2188.06763
[158]	validation_0-mae:2188.77946
[159]	validation_0-mae:2187.95006
[160]	validation_0-mae:2186.46208
[161]	validation_0-mae:2184.91448
[162]	validation_0-mae:2185.41229
[163]	validation_0-mae:2183.54798
[164]	validation_0-mae:2179.91434
[165]	validation_0-mae:2178.40072
[166]	validation_0-mae:2178.01921
[167]	validation_0-mae:2174.43205
[168]	validation_0-mae:2173.70926
[169]	validation_0-mae:2171.74052
[170]	validation_0-mae:2170.64675
[171]	validation_0-mae:2168.89671
[172]	validation_0-mae:2168.06484
[173]	validation_0-mae:2168.66101
[174]	validation_0-mae:2167.52661
[175]	validation_0-mae:2163.23696
[176]	validation_0-mae:2162.25837
[177]	validation_0-mae:2160.56851
[178]	validation_0-mae:2160.71032
[179]	validation_0-mae:2158.29759
[180]	validation_0-mae:2158.08970
[181]	validation_0-mae:2154.86952
[182]	validation_0-mae:2155.24136
[183]	validation_0-mae:2153.59107
[184]	validation_0-mae:2153.16235
[185]	validation_0-mae:2152.06178
[186]	validation_0-mae:2152.24285
[187]	validation_0-mae:2151.31627
[188]	validation_0-mae:2150.46744
[189]	validation_0-mae:2148.99279
[190]	validation_0-mae:2146.97918
[191]	validation_0-mae:2146.74438
[192]	validation_0-mae:2147.51367
[193]	validation_0-mae:2144.52921
[194]	validation_0-mae:2144.20946
[195]	validation_0-mae:2143.49377
[196]	validation_0-mae:2143.42600
[197]	validation_0-mae:2141.16298
[198]	validation_0-mae:2138.32635
[199]	validation_0-mae:2136.82687
[200]	validation_0-mae:2134.86410
[201]	validation_0-mae:2135.66940
[202]	validation_0-mae:2135.71189
[203]	validation_0-mae:2133.39473
[204]	validation_0-mae:2133.02970
[205]	validation_0-mae:2132.61865
[206]	validation_0-mae:2132.29317
[207]	validation_0-mae:2129.25620
[208]	validation_0-mae:2128.21298
[209]	validation_0-mae:2129.39821
[210]	validation_0-mae:2128.08037
[211]	validation_0-mae:2127.63793
[212]	validation_0-mae:2127.69083
[213]	validation_0-mae:2125.35563
[214]	validation_0-mae:2123.13584
[215]	validation_0-mae:2123.32680
[216]	validation_0-mae:2123.32375
[217]	validation_0-mae:2122.50673
[218]	validation_0-mae:2121.88075
[219]	validation_0-mae:2120.27931
[220]	validation_0-mae:2119.67918
[221]	validation_0-mae:2118.32918
[222]	validation_0-mae:2118.57779
[223]	validation_0-mae:2118.40440
[224]	validation_0-mae:2118.49033
[225]	validation_0-mae:2118.26257
[226]	validation_0-mae:2118.48244
[227]	validation_0-mae:2115.66751
[228]	validation_0-mae:2115.10255
[229]	validation_0-mae:2113.83131
[230]	validation_0-mae:2113.41352
[231]	validation_0-mae:2113.40900
[232]	validation_0-mae:2114.37977
[233]	validation_0-mae:2114.23224
[234]	validation_0-mae:2114.52804
[235]	validation_0-mae:2113.00990
[236]	validation_0-mae:2112.06826
[237]	validation_0-mae:2111.51428
[238]	validation_0-mae:2110.62582
[239]	validation_0-mae:2111.11531
[240]	validation_0-mae:2110.45415
[241]	validation_0-mae:2110.65712
[242]	validation_0-mae:2111.18290
[243]	validation_0-mae:2110.95728
[244]	validation_0-mae:2108.70465
[245]	validation_0-mae:2107.91465
[246]	validation_0-mae:2107.73776
[247]	validation_0-mae:2107.53485
[248]	validation_0-mae:2107.15151
[249]	validation_0-mae:2104.84376
[250]	validation_0-mae:2104.86252
[251]	validation_0-mae:2104.66354
[252]	validation_0-mae:2105.26910
[253]	validation_0-mae:2105.19588
[254]	validation_0-mae:2105.32941
[255]	validation_0-mae:2105.59941
[256]	validation_0-mae:2104.64754
[257]	validation_0-mae:2104.15952
[258]	validation_0-mae:2101.45013
[259]	validation_0-mae:2101.73419
[260]	validation_0-mae:2099.89988
[261]	validation_0-mae:2097.27305
[262]	validation_0-mae:2096.49585
[263]	validation_0-mae:2097.81829
[264]	validation_0-mae:2098.11605
[265]	validation_0-mae:2097.69868
[266]	validation_0-mae:2096.06476
[267]	validation_0-mae:2095.71799
[268]	validation_0-mae:2096.23963
[269]	validation_0-mae:2096.43347
[270]	validation_0-mae:2096.12537
[271]	validation_0-mae:2096.28234
[272]	validation_0-mae:2096.49198
[273]	validation_0-mae:2095.19668
[274]	validation_0-mae:2095.05551
[275]	validation_0-mae:2094.70687
[276]	validation_0-mae:2093.75742
[277]	validation_0-mae:2092.72597
[278]	validation_0-mae:2092.66415
[279]	validation_0-mae:2092.55333
[280]	validation_0-mae:2092.95968
[281]	validation_0-mae:2093.52360
[282]	validation_0-mae:2092.17632
[283]	validation_0-mae:2092.64023
[284]	validation_0-mae:2093.00289
[285]	validation_0-mae:2093.48385
[286]	validation_0-mae:2093.59569
[287]	validation_0-mae:2092.73057
[288]	validation_0-mae:2092.89845
[289]	validation_0-mae:2090.63541
[290]	validation_0-mae:2089.67029
[291]	validation_0-mae:2088.73671
[292]	validation_0-mae:2088.22642
[293]	validation_0-mae:2088.08758
[294]	validation_0-mae:2088.43684
[295]	validation_0-mae:2087.38724
[296]	validation_0-mae:2087.65703
[297]	validation_0-mae:2087.55035
[298]	validation_0-mae:2086.50990
[299]	validation_0-mae:2085.96858
[300]	validation_0-mae:2085.50499
[301]	validation_0-mae:2085.66120
[302]	validation_0-mae:2085.45722
[303]	validation_0-mae:2084.97997
[304]	validation_0-mae:2082.91204
[305]	validation_0-mae:2082.50150
[306]	validation_0-mae:2081.51001
[307]	validation_0-mae:2080.07480
[308]	validation_0-mae:2080.23159
[309]	validation_0-mae:2078.85213
[310]	validation_0-mae:2077.26436
[311]	validation_0-mae:2076.18170
[312]	validation_0-mae:2076.60719
[313]	validation_0-mae:2076.48945
[314]	validation_0-mae:2075.81527
[315]	validation_0-mae:2076.02657
[316]	validation_0-mae:2074.85478
[317]	validation_0-mae:2073.97842
[318]	validation_0-mae:2073.96231
[319]	validation_0-mae:2074.11829
[320]	validation_0-mae:2074.21233
[321]	validation_0-mae:2073.38999
[322]	validation_0-mae:2072.99084
[323]	validation_0-mae:2072.44668
[324]	validation_0-mae:2070.87068
[325]	validation_0-mae:2071.00804
[326]	validation_0-mae:2071.14744
[327]	validation_0-mae:2071.34107
[328]	validation_0-mae:2071.83273
[329]	validation_0-mae:2071.88276
[330]	validation_0-mae:2071.64274
[331]	validation_0-mae:2071.28533
[332]	validation_0-mae:2069.15992
[333]	validation_0-mae:2068.98501
[334]	validation_0-mae:2067.04253
[335]	validation_0-mae:2067.20890
[336]	validation_0-mae:2066.20152
[337]	validation_0-mae:2066.18963
[338]	validation_0-mae:2065.81647
[339]	validation_0-mae:2065.18097
[340]	validation_0-mae:2064.71191
[341]	validation_0-mae:2064.77041
[342]	validation_0-mae:2063.61658
[343]	validation_0-mae:2063.24632
[344]	validation_0-mae:2063.28632
[345]	validation_0-mae:2062.18373
[346]	validation_0-mae:2060.47628
[347]	validation_0-mae:2059.96936
[348]	validation_0-mae:2059.67141
[349]	validation_0-mae:2059.69991
[350]	validation_0-mae:2058.48664
[351]	validation_0-mae:2058.04637
[352]	validation_0-mae:2057.27353
[353]	validation_0-mae:2056.55839
[354]	validation_0-mae:2056.91139
[355]	validation_0-mae:2056.29246
[356]	validation_0-mae:2056.51918
[357]	validation_0-mae:2055.87840
[358]	validation_0-mae:2055.84146
[359]	validation_0-mae:2055.35427
[360]	validation_0-mae:2055.86075
[361]	validation_0-mae:2055.25741
[362]	validation_0-mae:2055.13014
[363]	validation_0-mae:2054.28294
[364]	validation_0-mae:2054.02241
[365]	validation_0-mae:2054.16383
[366]	validation_0-mae:2054.29772
[367]	validation_0-mae:2054.50059
[368]	validation_0-mae:2054.55569
[369]	validation_0-mae:2054.85231
[370]	validation_0-mae:2054.96634
[371]	validation_0-mae:2054.74548
[372]	validation_0-mae:2055.07483
[373]	validation_0-mae:2055.52976
[374]	validation_0-mae:2055.80992
[375]	validation_0-mae:2055.82306
[376]	validation_0-mae:2055.30698
[377]	validation_0-mae:2055.59946
[378]	validation_0-mae:2054.88061
[379]	validation_0-mae:2053.70806
[380]	validation_0-mae:2052.56434
[381]	validation_0-mae:2051.67881
[382]	validation_0-mae:2051.52966
[383]	validation_0-mae:2052.41333
[384]	validation_0-mae:2052.36425
[385]	validation_0-mae:2052.15076
[386]	validation_0-mae:2052.52024
[387]	validation_0-mae:2052.56434
[388]	validation_0-mae:2052.96541
[389]	validation_0-mae:2052.96689
[390]	validation_0-mae:2052.87658
[391]	validation_0-mae:2052.62480
[392]	validation_0-mae:2053.12742
[393]	validation_0-mae:2052.98931
[394]	validation_0-mae:2052.89871
[395]	validation_0-mae:2053.16786
[396]	validation_0-mae:2052.94112
[397]	validation_0-mae:2052.80526
[398]	validation_0-mae:2051.73276
[399]	validation_0-mae:2051.53335
[400]	validation_0-mae:2051.63218
[401]	validation_0-mae:2050.54046
[402]	validation_0-mae:2050.63757
[403]	validation_0-mae:2050.73919
[404]	validation_0-mae:2050.10600
[405]	validation_0-mae:2050.36504
[406]	validation_0-mae:2050.32276
[407]	validation_0-mae:2050.57282
[408]	validation_0-mae:2050.11272
[409]	validation_0-mae:2050.89928
[410]	validation_0-mae:2050.39643
[411]	validation_0-mae:2049.39142
[412]	validation_0-mae:2049.70643
[413]	validation_0-mae:2049.27777
[414]	validation_0-mae:2049.06935
[415]	validation_0-mae:2048.96938
[416]	validation_0-mae:2049.15859
[417]	validation_0-mae:2049.62182
[418]	validation_0-mae:2049.43321
[419]	validation_0-mae:2049.41088
[420]	validation_0-mae:2048.80710
[421]	validation_0-mae:2048.60542
[422]	validation_0-mae:2048.82371
[423]	validation_0-mae:2048.57030
[424]	validation_0-mae:2048.96266
[425]	validation_0-mae:2048.47932
[426]	validation_0-mae:2047.83262
[427]	validation_0-mae:2048.25739
[428]	validation_0-mae:2048.07071
[429]	validation_0-mae:2047.99088
[430]	validation_0-mae:2048.31961
[431]	validation_0-mae:2048.75597
[432]	validation_0-mae:2049.08472
[433]	validation_0-mae:2047.90499
[434]	validation_0-mae:2047.85695
[435]	validation_0-mae:2046.95623
[436]	validation_0-mae:2046.90072
[437]	validation_0-mae:2046.11020
[438]	validation_0-mae:2046.35975
[439]	validation_0-mae:2044.85565
[440]	validation_0-mae:2044.73570
[441]	validation_0-mae:2044.16276
[442]	validation_0-mae:2043.92483
[443]	validation_0-mae:2043.13305
[444]	validation_0-mae:2043.14215
[445]	validation_0-mae:2042.82095
[446]	validation_0-mae:2042.70563
[447]	validation_0-mae:2042.20914
[448]	validation_0-mae:2042.22843
[449]	validation_0-mae:2042.22293
[450]	validation_0-mae:2042.01336
[451]	validation_0-mae:2041.61424
[452]	validation_0-mae:2041.50487
[453]	validation_0-mae:2040.97543
[454]	validation_0-mae:2041.15228
[455]	validation_0-mae:2041.19179
[456]	validation_0-mae:2040.83139
[457]	validation_0-mae:2041.21876
[458]	validation_0-mae:2042.11958
[459]	validation_0-mae:2042.49895
[460]	validation_0-mae:2042.80696
[461]	validation_0-mae:2043.10619
[462]	validation_0-mae:2043.05494
[463]	validation_0-mae:2043.26598
[464]	validation_0-mae:2043.31528
[465]	validation_0-mae:2043.40653
[466]	validation_0-mae:2043.39808
[467]	validation_0-mae:2043.11325
[468]	validation_0-mae:2042.66054
[469]	validation_0-mae:2042.31764
[470]	validation_0-mae:2042.08379
[471]	validation_0-mae:2041.79545
[472]	validation_0-mae:2041.22938
[473]	validation_0-mae:2041.36706
[474]	validation_0-mae:2041.75735
[475]	validation_0-mae:2041.78974
[476]	validation_0-mae:2040.85482
[477]	validation_0-mae:2040.74286
[478]	validation_0-mae:2040.22365
[479]	validation_0-mae:2040.74982
[480]	validation_0-mae:2040.68691
[481]	validation_0-mae:2039.77543
[482]	validation_0-mae:2039.38244
[483]	validation_0-mae:2039.40119
[484]	validation_0-mae:2038.86746
[485]	validation_0-mae:2039.58878
[486]	validation_0-mae:2039.62762
[487]	validation_0-mae:2039.54605
[488]	validation_0-mae:2039.13203
[489]	validation_0-mae:2039.21606
[490]	validation_0-mae:2039.41595
[491]	validation_0-mae:2039.15045
[492]	validation_0-mae:2039.32180
[493]	validation_0-mae:2039.29742
[494]	validation_0-mae:2039.55860
[495]	validation_0-mae:2039.86869
[496]	validation_0-mae:2039.88915
[497]	validation_0-mae:2039.96908
[498]	validation_0-mae:2039.51141
[499]	validation_0-mae:2039.24938
[500]	validation_0-mae:2039.50739
[501]	validation_0-mae:2039.00228
[502]	validation_0-mae:2038.92960
[503]	validation_0-mae:2039.06950
[504]	validation_0-mae:2038.74842
[505]	validation_0-mae:2039.02541
[506]	validation_0-mae:2039.13572
[507]	validation_0-mae:2039.26754
[508]	validation_0-mae:2039.31023
[509]	validation_0-mae:2039.42894
[510]	validation_0-mae:2039.20469
[511]	validation_0-mae:2038.83283
[512]	validation_0-mae:2038.64149
[513]	validation_0-mae:2038.07393
[514]	validation_0-mae:2038.40175
[515]	validation_0-mae:2037.91151
[516]	validation_0-mae:2038.12717
[517]	validation_0-mae:2038.15715
[518]	validation_0-mae:2038.23521
[519]	validation_0-mae:2037.94805
[520]	validation_0-mae:2037.88546
[521]	validation_0-mae:2037.20527
[522]	validation_0-mae:2037.40747
[523]	validation_0-mae:2037.63615
[524]	validation_0-mae:2037.53636
[525]	validation_0-mae:2037.16598
[526]	validation_0-mae:2037.00398
[527]	validation_0-mae:2037.10730
[528]	validation_0-mae:2036.76977
[529]	validation_0-mae:2036.64068
[530]	validation_0-mae:2036.69177
[531]	validation_0-mae:2036.85865
[532]	validation_0-mae:2036.54046
[533]	validation_0-mae:2036.35165
[534]	validation_0-mae:2036.36395
[535]	validation_0-mae:2036.46441
[536]	validation_0-mae:2036.93792
[537]	validation_0-mae:2036.34480
[538]	validation_0-mae:2035.96466
[539]	validation_0-mae:2035.83370
[540]	validation_0-mae:2035.20110
[541]	validation_0-mae:2035.23393
[542]	validation_0-mae:2035.20731
[543]	validation_0-mae:2034.60329
[544]	validation_0-mae:2034.80217
[545]	validation_0-mae:2034.06903
[546]	validation_0-mae:2033.94538
[547]	validation_0-mae:2033.79386
[548]	validation_0-mae:2033.42330
[549]	validation_0-mae:2033.40203
[550]	validation_0-mae:2033.27414
[551]	validation_0-mae:2033.55506
[552]	validation_0-mae:2033.40476
[553]	validation_0-mae:2033.12272
[554]	validation_0-mae:2033.00239
[555]	validation_0-mae:2032.63812
[556]	validation_0-mae:2032.78919
[557]	validation_0-mae:2032.76132
[558]	validation_0-mae:2032.79955
[559]	validation_0-mae:2032.73795
[560]	validation_0-mae:2032.98171
[561]	validation_0-mae:2032.85870
[562]	validation_0-mae:2033.12256
[563]	validation_0-mae:2032.74423
[564]	validation_0-mae:2032.64344
[565]	validation_0-mae:2031.90745
[566]	validation_0-mae:2031.89251
[567]	validation_0-mae:2032.12407
[568]	validation_0-mae:2031.95449
[569]	validation_0-mae:2031.84266
[570]	validation_0-mae:2032.17670
[571]	validation_0-mae:2032.31020
[572]	validation_0-mae:2032.28915
[573]	validation_0-mae:2032.29687
[574]	validation_0-mae:2032.20359
[575]	validation_0-mae:2031.90262
[576]	validation_0-mae:2031.64480
[577]	validation_0-mae:2031.50527
[578]	validation_0-mae:2031.39526
[579]	validation_0-mae:2031.43780
[580]	validation_0-mae:2031.26656
[581]	validation_0-mae:2031.31242
[582]	validation_0-mae:2031.37637
[583]	validation_0-mae:2031.26487
[584]	validation_0-mae:2031.20302
[585]	validation_0-mae:2031.19445
[586]	validation_0-mae:2031.15175
[587]	validation_0-mae:2031.09548
[588]	validation_0-mae:2031.08500
[589]	validation_0-mae:2030.98505
[590]	validation_0-mae:2031.62225
[591]	validation_0-mae:2031.53451
[592]	validation_0-mae:2031.79121
[593]	validation_0-mae:2031.71775
[594]	validation_0-mae:2031.34112
[595]	validation_0-mae:2031.14484
[596]	validation_0-mae:2031.13713
[597]	validation_0-mae:2031.09355
[598]	validation_0-mae:2031.26706
[599]	validation_0-mae:2031.36656
[600]	validation_0-mae:2031.46664
[601]	validation_0-mae:2031.26975
[602]	validation_0-mae:2031.39223
[603]	validation_0-mae:2031.26407
[604]	validation_0-mae:2031.19504
[605]	validation_0-mae:2031.19667
[606]	validation_0-mae:2031.13593
[607]	validation_0-mae:2030.86609
[608]	validation_0-mae:2030.61032
[609]	validation_0-mae:2030.15687
[610]	validation_0-mae:2030.36548
[611]	validation_0-mae:2029.64592
[612]	validation_0-mae:2029.67451
[613]	validation_0-mae:2029.20134
[614]	validation_0-mae:2028.81015
[615]	validation_0-mae:2028.74342
[616]	validation_0-mae:2028.57591
[617]	validation_0-mae:2029.01291
[618]	validation_0-mae:2029.47649
[619]	validation_0-mae:2029.57550
[620]	validation_0-mae:2029.56874
[621]	validation_0-mae:2029.63485
[622]	validation_0-mae:2028.74707
[623]	validation_0-mae:2028.84301
[624]	validation_0-mae:2029.03402
[625]	validation_0-mae:2029.18781
[626]	validation_0-mae:2028.80078
[627]	validation_0-mae:2028.91107
[628]	validation_0-mae:2028.30751

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[41]	validation_0-mae:3244.99869
[42]	validation_0-mae:3198.67055
[43]	validation_0-mae:3158.08639
[44]	validation_0-mae:3105.73773
[45]	validation_0-mae:3068.29283
[46]	validation_0-mae:3036.26122
[47]	validation_0-mae:2993.64470
[48]	validation_0-mae:2967.91561
[49]	validation_0-mae:2929.00609
[50]	validation_0-mae:2901.31737
[51]	validation_0-mae:2870.01730
[52]	validation_0-mae:2846.41070
[53]	validation_0-mae:2828.84733
[54]	validation_0-mae:2806.36218
[55]	validation_0-mae:2785.22711
[56]	validation_0-mae:2761.92968
[57]	validation_0-mae:2732.07878
[58]	validation_0-mae:2718.14495
[59]	validation_0-mae:2699.13164
[60]	validation_0-mae:2675.42482
[61]	validation_0-mae:2663.07130
[62]	validation_0-mae:2649.32116
[63]	validation_0-mae:2639.70120
[64]	validation_0-mae:2624.66119
[65]	validation_0-mae:2611.69115
[66]	validation_0-mae:2602.01992
[67]	validation_0-mae:2593.04205
[68]	validation_0-mae:2584.23743
[69]	validation_0-mae:2574.00530
[70]	validation_0-mae:2563.10662
[71]	validation_0-mae:2555.87300
[72]	validation_0-mae:2536.90669
[73]	validation_0-mae:2523.16342
[74]	validation_0-mae:2512.53054
[75]	validation_0-mae:2502.13173
[76]	validation_0-mae:2491.67550
[77]	validation_0-mae:2481.53423
[78]	validation_0-mae:2477.11517
[79]	validation_0-mae:2468.62523
[80]	validation_0-mae:2457.32529
[81]	validation_0-mae:2448.53231
[82]	validation_0-mae:2441.69997
[83]	validation_0-mae:2430.05479
[84]	validation_0-mae:2422.14207
[85]	validation_0-mae:2417.09256
[86]	validation_0-mae:2412.58819
[87]	validation_0-mae:2406.87870
[88]	validation_0-mae:2404.17364
[89]	validation_0-mae:2394.73289
[90]	validation_0-mae:2389.04514
[91]	validation_0-mae:2381.73046
[92]	validation_0-mae:2371.68834
[93]	validation_0-mae:2361.44848
[94]	validation_0-mae:2357.75160
[95]	validation_0-mae:2352.88937
[96]	validation_0-mae:2341.67798
[97]	validation_0-mae:2334.98991
[98]	validation_0-mae:2329.86738
[99]	validation_0-mae:2326.14262
[100]	validation_0-mae:2323.87581
[101]	validation_0-mae:2318.63332
[102]	validation_0-mae:2309.50763
[103]	validation_0-mae:2306.10026
[104]	validation_0-mae:2303.23246
[105]	validation_0-mae:2299.54489
[106]	validation_0-mae:2290.08166
[107]	validation_0-mae:2284.14472
[108]	validation_0-mae:2280.13138
[109]	validation_0-mae:2273.28972
[110]	validation_0-mae:2266.79388
[111]	validation_0-mae:2258.70891
[112]	validation_0-mae:2256.64112
[113]	validation_0-mae:2255.91470
[114]	validation_0-mae:2253.81854
[115]	validation_0-mae:2247.45734
[116]	validation_0-mae:2246.58338
[117]	validation_0-mae:2239.88143
[118]	validation_0-mae:2235.80815
[119]	validation_0-mae:2233.56797
[120]	validation_0-mae:2231.77065
[121]	validation_0-mae:2228.93624
[122]	validation_0-mae:2226.74969
[123]	validation_0-mae:2222.63146
[124]	validation_0-mae:2221.88520
[125]	validation_0-mae:2220.51253
[126]	validation_0-mae:2217.53335
[127]	validation_0-mae:2213.37893
[128]	validation_0-mae:2209.51909
[129]	validation_0-mae:2207.55938
[130]	validation_0-mae:2206.18015
[131]	validation_0-mae:2202.59847
[132]	validation_0-mae:2203.62862
[133]	validation_0-mae:2198.64328
[134]	validation_0-mae:2198.42906
[135]	validation_0-mae:2198.14413
[136]	validation_0-mae:2197.68207
[137]	validation_0-mae:2197.07737
[138]	validation_0-mae:2195.68729
[139]	validation_0-mae:2192.30909
[140]	validation_0-mae:2188.23783
[141]	validation_0-mae:2186.23217
[142]	validation_0-mae:2182.63420
[143]	validation_0-mae:2182.26479
[144]	validation_0-mae:2179.66396
[145]	validation_0-mae:2180.02851
[146]	validation_0-mae:2178.22642
[147]	validation_0-mae:2174.03611
[148]	validation_0-mae:2174.22614
[149]	validation_0-mae:2173.34929
[150]	validation_0-mae:2170.68089
[151]	validation_0-mae:2168.28545
[152]	validation_0-mae:2165.73716
[153]	validation_0-mae:2165.68323
[154]	validation_0-mae:2166.05459
[155]	validation_0-mae:2165.53144
[156]	validation_0-mae:2164.82362
[157]	validation_0-mae:2161.90774
[158]	validation_0-mae:2157.96442
[159]	validation_0-mae:2157.19356
[160]	validation_0-mae:2155.80645
[161]	validation_0-mae:2152.32579
[162]	validation_0-mae:2152.03947
[163]	validation_0-mae:2151.79473
[164]	validation_0-mae:2150.19084
[165]	validation_0-mae:2147.03810
[166]	validation_0-mae:2145.66902
[167]	validation_0-mae:2142.74102
[168]	validation_0-mae:2141.73904
[169]	validation_0-mae:2140.64608
[170]	validation_0-mae:2138.27068
[171]	validation_0-mae:2138.64834
[172]	validation_0-mae:2139.07149
[173]	validation_0-mae:2138.20942
[174]	validation_0-mae:2137.81399
[175]	validation_0-mae:2137.30206
[176]	validation_0-mae:2136.07868
[177]	validation_0-mae:2134.81425
[178]	validation_0-mae:2134.06312
[179]	validation_0-mae:2131.86582
[180]	validation_0-mae:2129.01037
[181]	validation_0-mae:2127.79432
[182]	validation_0-mae:2127.94148
[183]	validation_0-mae:2129.15808
[184]	validation_0-mae:2127.16894
[185]	validation_0-mae:2127.75673
[186]	validation_0-mae:2126.80335
[187]	validation_0-mae:2126.64901
[188]	validation_0-mae:2125.62923
[189]	validation_0-mae:2124.62815
[190]	validation_0-mae:2124.85219
[191]	validation_0-mae:2123.05976
[192]	validation_0-mae:2123.11870
[193]	validation_0-mae:2123.35843
[194]	validation_0-mae:2121.58194
[195]	validation_0-mae:2122.50467
[196]	validation_0-mae:2118.90187
[197]	validation_0-mae:2120.28693
[198]	validation_0-mae:2117.60792
[199]	validation_0-mae:2117.85757
[200]	validation_0-mae:2117.49627
[201]	validation_0-mae:2118.34515
[202]	validation_0-mae:2117.67758
[203]	validation_0-mae:2118.42711
[204]	validation_0-mae:2117.69875
[205]	validation_0-mae:2118.13385
[206]	validation_0-mae:2116.79002
[207]	validation_0-mae:2115.71690
[208]	validation_0-mae:2114.57813
[209]	validation_0-mae:2114.38303
[210]	validation_0-mae:2113.84006
[211]	validation_0-mae:2113.34110
[212]	validation_0-mae:2113.45580
[213]	validation_0-mae:2112.67869
[214]	validation_0-mae:2111.59320
[215]	validation_0-mae:2111.81893
[216]	validation_0-mae:2112.16765
[217]	validation_0-mae:2111.75578
[218]	validation_0-mae:2110.23282
[219]	validation_0-mae:2107.84014
[220]	validation_0-mae:2107.09141
[221]	validation_0-mae:2108.47158
[222]	validation_0-mae:2108.71714
[223]	validation_0-mae:2106.68963
[224]	validation_0-mae:2106.04024
[225]	validation_0-mae:2104.44099
[226]	validation_0-mae:2103.78242
[227]	validation_0-mae:2102.67089
[228]	validation_0-mae:2102.94436
[229]	validation_0-mae:2102.63296
[230]	validation_0-mae:2101.96876
[231]	validation_0-mae:2101.42069
[232]	validation_0-mae:2101.41637
[233]	validation_0-mae:2102.07144
[234]	validation_0-mae:2102.92224
[235]	validation_0-mae:2103.42162
[236]	validation_0-mae:2103.93316
[237]	validation_0-mae:2102.14208
[238]	validation_0-mae:2101.79201
[239]	validation_0-mae:2101.24447
[240]	validation_0-mae:2099.96557
[241]	validation_0-mae:2099.29640
[242]	validation_0-mae:2099.34988
[243]	validation_0-mae:2099.29759
[244]	validation_0-mae:2098.89958
[245]	validation_0-mae:2099.31629
[246]	validation_0-mae:2100.19828
[247]	validation_0-mae:2100.21825
[248]	validation_0-mae:2099.87793
[249]	validation_0-mae:2099.11630
[250]	validation_0-mae:2099.54609
[251]	validation_0-mae:2099.13628
[252]	validation_0-mae:2098.59076
[253]	validation_0-mae:2097.90908
[254]	validation_0-mae:2098.19423
[255]	validation_0-mae:2098.09979
[256]	validation_0-mae:2098.23149
[257]	validation_0-mae:2097.32517
[258]	validation_0-mae:2096.61683
[259]	validation_0-mae:2096.39670
[260]	validation_0-mae:2097.58805
[261]	validation_0-mae:2097.04042
[262]	validation_0-mae:2096.64742
[263]	validation_0-mae:2095.72348
[264]	validation_0-mae:2095.58138
[265]	validation_0-mae:2095.77762
[266]	validation_0-mae:2096.17734
[267]	validation_0-mae:2094.15984
[268]	validation_0-mae:2093.28400
[269]	validation_0-mae:2093.71124
[270]	validation_0-mae:2093.43723
[271]	validation_0-mae:2091.67931
[272]	validation_0-mae:2091.66749
[273]	validation_0-mae:2090.55015
[274]	validation_0-mae:2090.40190
[275]	validation_0-mae:2089.67275
[276]	validation_0-mae:2087.78616
[277]	validation_0-mae:2088.07515
[278]	validation_0-mae:2087.82099
[279]	validation_0-mae:2086.85716
[280]	validation_0-mae:2087.39399
[281]	validation_0-mae:2087.66407
[282]	validation_0-mae:2087.99227
[283]	validation_0-mae:2088.49610
[284]	validation_0-mae:2087.90207
[285]	validation_0-mae:2087.85186
[286]	validation_0-mae:2088.29965
[287]	validation_0-mae:2088.62237
[288]	validation_0-mae:2088.20092
[289]	validation_0-mae:2088.30986
[290]	validation_0-mae:2088.98652
[291]	validation_0-mae:2088.94278
[292]	validation_0-mae:2088.67834
[293]	validation_0-mae:2088.80659
[294]	validation_0-mae:2089.20941
[295]	validation_0-mae:2088.86771
[296]	validation_0-mae:2087.20935
[297]	validation_0-mae:2087.44441
[298]	validation_0-mae:2087.68530
[299]	validation_0-mae:2087.34198
[300]	validation_0-mae:2087.23506
[301]	validation_0-mae:2087.21731
[302]	validation_0-mae:2087.15450
[303]	validation_0-mae:2085.48338
[304]	validation_0-mae:2084.38342
[305]	validation_0-mae:2082.22141
[306]	validation_0-mae:2081.62210
[307]	validation_0-mae:2081.92519
[308]	validation_0-mae:2081.43634
[309]	validation_0-mae:2080.93118
[310]	validation_0-mae:2080.55830
[311]	validation_0-mae:2080.90342
[312]	validation_0-mae:2080.67757
[313]	validation_0-mae:2080.82785
[314]	validation_0-mae:2080.45887
[315]	validation_0-mae:2080.25368
[316]	validation_0-mae:2080.22373
[317]	validation_0-mae:2080.32900
[318]	validation_0-mae:2080.18764
[319]	validation_0-mae:2080.09319
[320]	validation_0-mae:2080.15647
[321]	validation_0-mae:2079.31044
[322]	validation_0-mae:2078.81526
[323]	validation_0-mae:2078.65460
[324]	validation_0-mae:2077.24021
[325]	validation_0-mae:2077.32523
[326]	validation_0-mae:2077.74001
[327]	validation_0-mae:2077.27332
[328]	validation_0-mae:2077.04422
[329]	validation_0-mae:2076.12017
[330]	validation_0-mae:2076.09808
[331]	validation_0-mae:2075.96786
[332]	validation_0-mae:2076.73789
[333]	validation_0-mae:2076.47664
[334]	validation_0-mae:2074.68658
[335]	validation_0-mae:2075.35238
[336]	validation_0-mae:2075.55429
[337]	validation_0-mae:2074.43679
[338]	validation_0-mae:2073.85698
[339]	validation_0-mae:2073.74657
[340]	validation_0-mae:2074.19762
[341]	validation_0-mae:2073.71401
[342]	validation_0-mae:2072.53200
[343]	validation_0-mae:2072.11796
[344]	validation_0-mae:2072.03330
[345]	validation_0-mae:2071.73024
[346]	validation_0-mae:2070.59644
[347]	validation_0-mae:2070.87196
[348]	validation_0-mae:2070.79419
[349]	validation_0-mae:2069.70545
[350]	validation_0-mae:2069.76404
[351]	validation_0-mae:2070.00344
[352]	validation_0-mae:2070.62310
[353]	validation_0-mae:2069.52654
[354]	validation_0-mae:2070.01473
[355]	validation_0-mae:2070.27935
[356]	validation_0-mae:2070.01591
[357]	validation_0-mae:2068.85978
[358]	validation_0-mae:2068.85473
[359]	validation_0-mae:2069.34916
[360]	validation_0-mae:2069.68440
[361]	validation_0-mae:2069.86020
[362]	validation_0-mae:2069.78741
[363]	validation_0-mae:2069.26556
[364]	validation_0-mae:2068.80458
[365]	validation_0-mae:2068.74938
[366]	validation_0-mae:2068.96421
[367]	validation_0-mae:2069.25266
[368]	validation_0-mae:2069.10067
[369]	validation_0-mae:2068.53995
[370]	validation_0-mae:2068.57536
[371]	validation_0-mae:2069.02743
[372]	validation_0-mae:2068.21537
[373]	validation_0-mae:2067.60534
[374]	validation_0-mae:2067.87892
[375]	validation_0-mae:2066.12673
[376]	validation_0-mae:2065.62123
[377]	validation_0-mae:2065.48496
[378]	validation_0-mae:2065.14564
[379]	validation_0-mae:2065.15129
[380]	validation_0-mae:2065.26497
[381]	validation_0-mae:2065.77306
[382]	validation_0-mae:2065.98799
[383]	validation_0-mae:2065.52648
[384]	validation_0-mae:2065.42714
[385]	validation_0-mae:2064.90914
[386]	validation_0-mae:2064.86704
[387]	validation_0-mae:2064.65517
[388]	validation_0-mae:2063.90196
[389]	validation_0-mae:2064.09267
[390]	validation_0-mae:2064.18298
[391]	validation_0-mae:2063.63656
[392]	validation_0-mae:2063.86770
[393]	validation_0-mae:2064.10396
[394]	validation_0-mae:2064.60518
[395]	validation_0-mae:2064.45896
[396]	validation_0-mae:2064.17502
[397]	validation_0-mae:2063.79368
[398]	validation_0-mae:2062.81229
[399]	validation_0-mae:2062.57459
[400]	validation_0-mae:2061.84668
[401]	validation_0-mae:2061.86660
[402]	validation_0-mae:2060.85472
[403]	validation_0-mae:2060.65145
[404]	validation_0-mae:2061.06433
[405]	validation_0-mae:2060.83050
[406]	validation_0-mae:2060.97370
[407]	validation_0-mae:2061.20277
[408]	validation_0-mae:2061.21006
[409]	validation_0-mae:2061.12807
[410]	validation_0-mae:2060.47851
[411]	validation_0-mae:2060.26768
[412]	validation_0-mae:2060.36768
[413]	validation_0-mae:2059.20598
[414]	validation_0-mae:2059.19226
[415]	validation_0-mae:2059.39879
[416]	validation_0-mae:2058.51363
[417]	validation_0-mae:2057.43364
[418]	validation_0-mae:2057.31875
[419]	validation_0-mae:2057.81355
[420]	validation_0-mae:2057.37651
[421]	validation_0-mae:2056.63396
[422]	validation_0-mae:2057.30285
[423]	validation_0-mae:2057.31220
[424]	validation_0-mae:2056.69277
[425]	validation_0-mae:2055.53781
[426]	validation_0-mae:2055.89057
[427]	validation_0-mae:2056.04469
[428]	validation_0-mae:2056.28330
[429]	validation_0-mae:2055.83667
[430]	validation_0-mae:2055.38548
[431]	validation_0-mae:2055.65314
[432]	validation_0-mae:2055.09894
[433]	validation_0-mae:2054.77517
[434]	validation_0-mae:2054.53770
[435]	validation_0-mae:2053.77741
[436]	validation_0-mae:2051.99318
[437]	validation_0-mae:2052.00585
[438]	validation_0-mae:2051.97761
[439]	validation_0-mae:2052.35221
[440]	validation_0-mae:2052.47490
[441]	validation_0-mae:2051.94041
[442]	validation_0-mae:2051.73067
[443]	validation_0-mae:2051.73002
[444]	validation_0-mae:2051.67128
[445]	validation_0-mae:2051.62154
[446]	validation_0-mae:2051.39456
[447]	validation_0-mae:2050.85876
[448]	validation_0-mae:2050.41570
[449]	validation_0-mae:2050.85577
[450]	validation_0-mae:2050.97653
[451]	validation_0-mae:2050.82287
[452]	validation_0-mae:2050.23874
[453]	validation_0-mae:2050.16376
[454]	validation_0-mae:2049.52075
[455]	validation_0-mae:2048.99614
[456]	validation_0-mae:2048.93682
[457]	validation_0-mae:2048.48997
[458]	validation_0-mae:2048.24800
[459]	validation_0-mae:2046.99980
[460]	validation_0-mae:2046.11777
[461]	validation_0-mae:2045.30138
[462]	validation_0-mae:2045.18028
[463]	validation_0-mae:2045.26149
[464]	validation_0-mae:2044.54590
[465]	validation_0-mae:2044.46146
[466]	validation_0-mae:2044.33817
[467]	validation_0-mae:2043.89648
[468]	validation_0-mae:2044.30760
[469]	validation_0-mae:2044.03345
[470]	validation_0-mae:2043.86735
[471]	validation_0-mae:2043.99938
[472]	validation_0-mae:2043.75931
[473]	validation_0-mae:2043.93033
[474]	validation_0-mae:2043.65020
[475]	validation_0-mae:2043.64893
[476]	validation_0-mae:2042.95699
[477]	validation_0-mae:2043.13363
[478]	validation_0-mae:2043.21367
[479]	validation_0-mae:2042.40778
[480]	validation_0-mae:2042.13113
[481]	validation_0-mae:2042.24946
[482]	validation_0-mae:2042.53183
[483]	validation_0-mae:2042.96014
[484]	validation_0-mae:2043.10912
[485]	validation_0-mae:2043.57112
[486]	validation_0-mae:2043.20731
[487]	validation_0-mae:2043.51585
[488]	validation_0-mae:2043.55237
[489]	validation_0-mae:2043.48640
[490]	validation_0-mae:2043.60480
[491]	validation_0-mae:2043.51987
[492]	validation_0-mae:2043.43801
[493]	validation_0-mae:2043.06267
[494]	validation_0-mae:2042.93749
[495]	validation_0-mae:2042.66914
[496]	validation_0-mae:2042.77495
[497]	validation_0-mae:2043.06812
[498]	validation_0-mae:2043.17148
[499]	validation_0-mae:2042.79330
[500]	validation_0-mae:2042.50604
[501]	validation_0-mae:2042.68265
[502]	validation_0-mae:2042.62572
[503]	validation_0-mae:2042.54178
[504]	validation_0-mae:2042.43305
[505]	validation_0-mae:2042.28282
[506]	validation_0-mae:2042.10903
[507]	validation_0-mae:2041.94032
[508]	validation_0-mae:2041.60908
[509]	validation_0-mae:2041.80311
[510]	validation_0-mae:2042.06669
[511]	validation_0-mae:2041.83715
[512]	validation_0-mae:2041.85059
[513]	validation_0-mae:2041.78344
[514]	validation_0-mae:2041.25360
[515]	validation_0-mae:2041.39142
[516]	validation_0-mae:2041.51936
[517]	validation_0-mae:2041.64974
[518]	validation_0-mae:2041.91436
[519]	validation_0-mae:2042.16668
[520]	validation_0-mae:2041.92039
[521]	validation_0-mae:2041.83683
[522]	validation_0-mae:2042.10976
[523]	validation_0-mae:2041.96347
[524]	validation_0-mae:2042.24864
[525]	validation_0-mae:2042.31098
[526]	validation_0-mae:2042.59254
[527]	validation_0-mae:2042.44822
[528]	validation_0-mae:2042.25744
[529]	validation_0-mae:2042.26795
[530]	validation_0-mae:2042.12758
[531]	validation_0-mae:2042.43607
[532]	validation_0-mae:2042.26625
[533]	validation_0-mae:2042.38671
[534]	validation_0-mae:2042.01534
[535]	validation_0-mae:2041.63952
[536]	validation_0-mae:2041.46695
[537]	validation_0-mae:2041.54009
[538]	validation_0-mae:2040.83471
[539]	validation_0-mae:2040.42466
[540]	validation_0-mae:2040.24585
[541]	validation_0-mae:2040.24005
[542]	validation_0-mae:2040.18916
[543]	validation_0-mae:2040.50336
[544]	validation_0-mae:2040.11348
[545]	validation_0-mae:2040.27776
[546]	validation_0-mae:2040.27709
[547]	validation_0-mae:2039.53951
[548]	validation_0-mae:2039.95412
[549]	validation_0-mae:2040.25875
[550]	validation_0-mae:2039.66412
[551]	validation_0-mae:2039.74447
[552]	validation_0-mae:2039.76162
[553]	validation_0-mae:2039.72108
[554]	validation_0-mae:2039.43472
[555]	validation_0-mae:2039.49667
[556]	validation_0-mae:2039.29732
[557]	validation_0-mae:2039.81986
[558]	validation_0-mae:2039.92436
[559]	validation_0-mae:2040.07769
[560]	validation_0-mae:2040.05538
[561]	validation_0-mae:2040.11437
[562]	validation_0-mae:2040.20423
[563]	validation_0-mae:2039.51416
[564]	validation_0-mae:2039.54375
[565]	validation_0-mae:2039.74239
[566]	validation_0-mae:2039.10890
[567]	validation_0-mae:2038.87262
[568]	validation_0-mae:2038.36161
[569]	validation_0-mae:2037.96891
[570]	validation_0-mae:2037.59078
[571]	validation_0-mae:2037.38382
[572]	validation_0-mae:2037.03580
[573]	validation_0-mae:2036.76017
[574]	validation_0-mae:2036.72724
[575]	validation_0-mae:2036.79946
[576]	validation_0-mae:2036.67059
[577]	validation_0-mae:2036.74521
[578]	validation_0-mae:2036.56396
[579]	validation_0-mae:2036.94541
[580]	validation_0-mae:2036.89591
[581]	validation_0-mae:2036.95294
[582]	validation_0-mae:2037.09976
[583]	validation_0-mae:2037.31229
[584]	validation_0-mae:2036.99479
[585]	validation_0-mae:2037.07741
[586]	validation_0-mae:2037.08165
[587]	validation_0-mae:2037.13867
[588]	validation_0-mae:2036.76146
[589]	validation_0-mae:2036.82273
[590]	validation_0-mae:2036.77524
[591]	validation_0-mae:2036.67615
[592]	validation_0-mae:2036.83945
[593]	validation_0-mae:2036.69158
[594]	validation_0-mae:2036.87326
[595]	validation_0-mae:2036.45293
[596]	validation_0-mae:2036.12932
[597]	validation_0-mae:2036.16574
[598]	validation_0-mae:2036.18348
[599]	validation_0-mae:2036.23956
[600]	validation_0-mae:2036.26899
[601]	validation_0-mae:2036.20520
[602]	validation_0-mae:2036.26241
[603]	validation_0-mae:2036.41169
[604]	validation_0-mae:2036.45487
[605]	validation_0-mae:2036.63515
[606]	validation_0-mae:2036.95628
[607]	validation_0-mae:2036.80296
[608]	validation_0-mae:2036.55538
[609]	validation_0-mae:2036.56126
[610]	validation_0-mae:2036.55864
[611]	validation_0-mae:2036.49019
[612]	validation_0-mae:2036.35944
[613]	validation_0-mae:2036.26500
[614]	validation_0-mae:2036.32440
[615]	validation_0-mae:2036.31126
[616]	validation_0-mae:2036.20122
[617]	validation_0-mae:2036.17911
[618]	validation_0-mae:2036.39856
[619]	validation_0-mae:2036.62882
[620]	validation_0-mae:2036.73782
[621]	validation_0-mae:2036.81977
[622]	validation_0-mae:2036.87395
[623]	validation_0-mae:2036.48588
[624]	validation_0-mae:2036.64925
[625]	validation_0-mae:2036.88123
[626]	validation_0-mae:2036.91880
[627]	validation_0-mae:2037.14185
[628]	validation_0-mae:2037.21832
[629]	validation_0-mae:2037.02843

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[36]	validation_0-mae:3514.08993
[37]	validation_0-mae:3470.65462
[38]	validation_0-mae:3420.13008
[39]	validation_0-mae:3379.80719
[40]	validation_0-mae:3321.97165
[41]	validation_0-mae:3278.42323
[42]	validation_0-mae:3240.77238
[43]	validation_0-mae:3205.26655
[44]	validation_0-mae:3169.70057
[45]	validation_0-mae:3116.88865
[46]	validation_0-mae:3084.26509
[47]	validation_0-mae:3054.97023
[48]	validation_0-mae:3023.25832
[49]	validation_0-mae:2992.19873
[50]	validation_0-mae:2969.62394
[51]	validation_0-mae:2945.03019
[52]	validation_0-mae:2922.67362
[53]	validation_0-mae:2890.82123
[54]	validation_0-mae:2868.26579
[55]	validation_0-mae:2845.92599
[56]	validation_0-mae:2817.45164
[57]	validation_0-mae:2801.94775
[58]	validation_0-mae:2784.95855
[59]	validation_0-mae:2769.22820
[60]	validation_0-mae:2747.23494
[61]	validation_0-mae:2729.71671
[62]	validation_0-mae:2710.26545
[63]	validation_0-mae:2699.18292
[64]	validation_0-mae:2684.01464
[65]	validation_0-mae:2675.26169
[66]	validation_0-mae:2661.45364
[67]	validation_0-mae:2647.04265
[68]	validation_0-mae:2637.20730
[69]	validation_0-mae:2627.88346
[70]	validation_0-mae:2614.40192
[71]	validation_0-mae:2598.13343
[72]	validation_0-mae:2591.06176
[73]	validation_0-mae:2580.53515
[74]	validation_0-mae:2572.90827
[75]	validation_0-mae:2557.00757
[76]	validation_0-mae:2544.35281
[77]	validation_0-mae:2531.65587
[78]	validation_0-mae:2524.74960
[79]	validation_0-mae:2517.52637
[80]	validation_0-mae:2510.74089
[81]	validation_0-mae:2504.42252
[82]	validation_0-mae:2496.47899
[83]	validation_0-mae:2487.87716
[84]	validation_0-mae:2479.80855
[85]	validation_0-mae:2468.02628
[86]	validation_0-mae:2455.80229
[87]	validation_0-mae:2449.73168
[88]	validation_0-mae:2444.27305
[89]	validation_0-mae:2437.52317
[90]	validation_0-mae:2434.08418
[91]	validation_0-mae:2429.14606
[92]	validation_0-mae:2421.87618
[93]	validation_0-mae:2417.62238
[94]	validation_0-mae:2411.68313
[95]	validation_0-mae:2407.79809
[0]	validation_0-mae:12362.28965
[1]	validation_0-mae:11559.92055
[2]	validation_0-mae:10837.74676
[3]	validation_0-mae:10179.36663
[4]	validation_0-mae:9605.81640
[5]	validation_0-mae:9096.39144
[6]	validation_0-mae:8622.68158
[7]	validation_0-mae:8234.93340
[8]	validation_0-mae:7846.21408
[9]	validation_0-mae:7504.41753
[10]	validation_0-mae:7172.24495
[11]	validation_0-mae:6862.83639
[12]	validation_0-mae:6564.92024
[13]	validation_0-mae:6305.86025
[14]	validation_0-mae:6079.38952
[15]	validation_0-mae:5863.79630
[16]	validation_0-mae:5663.81096
[17]	validation_0-mae:5443.58771
[18]	validation_0-mae:5262.00613
[19]	validation_0-mae:5100.72069
[20]	validation_0-mae:4928.67893
[21]	validation_0-mae:4780.06882
[22]	validation_0-mae:4636.45897
[23]	validation_0-mae:4490.67861
[24]	validation_0-mae:4394.33028
[25]	validation_0-mae:4272.98302
[26]	validation_0-mae:4174.73729
[27]	validation_0-mae:4074.21623
[28]	validation_0-mae:3973.74660
[29]	validation_0-mae:3884.35357
[30]	validation_0-mae:3797.05653
[31]	validation_0-mae:3720.70651
[32]	validation_0-mae:3639.68720
[33]	validation_0-mae:3572.97764
[34]	validation_0-mae:3504.89428
[35]	validation_0-mae:3452.48488
[36]	validation_0-mae:3405.40872
[37]	validation_0-mae:3353.18721
[38]	validation_0-mae:3306.84646
[39]	validation_0-mae:3258.07663
[40]	validation_0-mae:3217.98843
[41]	validation_0-mae:3184.43083

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[42]	validation_0-mae:3119.10330
[43]	validation_0-mae:3086.35983
[44]	validation_0-mae:3037.69877
[45]	validation_0-mae:3008.09885
[46]	validation_0-mae:2971.24914
[47]	validation_0-mae:2934.13033
[48]	validation_0-mae:2907.73173
[49]	validation_0-mae:2887.38440
[50]	validation_0-mae:2863.89764
[51]	validation_0-mae:2834.82114
[52]	validation_0-mae:2800.97342
[53]	validation_0-mae:2783.05005
[54]	validation_0-mae:2763.86536
[55]	validation_0-mae:2745.19087
[56]	validation_0-mae:2728.49029
[57]	validation_0-mae:2717.93072
[58]	validation_0-mae:2690.42568
[59]	validation_0-mae:2678.93688
[60]	validation_0-mae:2658.67867
[61]	validation_0-mae:2641.04753
[62]	validation_0-mae:2629.21059
[63]	validation_0-mae:2624.89016
[64]	validation_0-mae:2613.38105
[65]	validation_0-mae:2605.95710
[66]	validation_0-mae:2594.76728
[67]	validation_0-mae:2581.10499
[68]	validation_0-mae:2574.42181
[69]	validation_0-mae:2556.76876
[70]	validation_0-mae:2548.55711
[71]	validation_0-mae:2542.34588
[72]	validation_0-mae:2533.48305
[73]	validation_0-mae:2528.20321
[74]	validation_0-mae:2515.11419
[75]	validation_0-mae:2502.35115
[76]	validation_0-mae:2497.27582
[77]	validation_0-mae:2490.31449
[78]	validation_0-mae:2484.96514
[79]	validation_0-mae:2475.58073
[80]	validation_0-mae:2469.62836
[81]	validation_0-mae:2464.63688
[82]	validation_0-mae:2453.90921
[83]	validation_0-mae:2446.89611
[84]	validation_0-mae:2441.92775
[85]	validation_0-mae:2435.15604
[86]	validation_0-mae:2431.05675
[87]	validation_0-mae:2424.64182
[88]	validation_0-mae:2421.89932
[89]	validation_0-mae:2414.56804
[90]	validation_0-mae:2411.37165
[91]	validation_0-mae:2397.88890
[92]	validation_0-mae:2394.76433
[93]	validation_0-mae:2391.22548
[94]	validation_0-mae:2386.35045
[95]	validation_0-mae:2379.30547
[96]	validation_0-mae:2374.85603
[97]	validation_0-mae:2368.50678
[98]	validation_0-mae:2363.72051
[99]	validation_0-mae:2358.37058
[100]	validation_0-mae:2354.60194
[101]	validation_0-mae:2349.91376
[102]	validation_0-mae:2343.71283
[103]	validation_0-mae:2341.45610
[104]	validation_0-mae:2338.13595
[105]	validation_0-mae:2334.15338
[106]	validation_0-mae:2331.43565
[107]	validation_0-mae:2328.06487
[108]	validation_0-mae:2323.94061
[109]	validation_0-mae:2322.78147
[110]	validation_0-mae:2316.49240
[111]	validation_0-mae:2311.66212
[112]	validation_0-mae:2307.68587
[113]	validation_0-mae:2306.49707
[114]	validation_0-mae:2304.42279
[115]	validation_0-mae:2297.35231
[116]	validation_0-mae:2294.83619
[117]	validation_0-mae:2292.02344
[118]	validation_0-mae:2288.99131
[119]	validation_0-mae:2286.00274
[120]	validation_0-mae:2282.58325
[121]	validation_0-mae:2282.09265
[122]	validation_0-mae:2280.00494
[123]	validation_0-mae:2278.16849
[124]	validation_0-mae:2279.46968
[125]	validation_0-mae:2275.15690
[126]	validation_0-mae:2273.32016
[127]	validation_0-mae:2273.02177
[128]	validation_0-mae:2265.44279
[129]	validation_0-mae:2264.49730
[130]	validation_0-mae:2264.34650
[131]	validation_0-mae:2262.58333
[132]	validation_0-mae:2260.92141
[133]	validation_0-mae:2257.21861
[134]	validation_0-mae:2256.05028
[135]	validation_0-mae:2254.28089
[136]	validation_0-mae:2250.30515
[137]	validation_0-mae:2249.04268
[138]	validation_0-mae:2248.68572
[139]	validation_0-mae:2247.60403
[140]	validation_0-mae:2246.25819
[141]	validation_0-mae:2244.34489
[142]	validation_0-mae:2241.55548
[143]	validation_0-mae:2237.63981
[144]	validation_0-mae:2236.70174
[145]	validation_0-mae:2234.63588
[146]	validation_0-mae:2231.65755
[147]	validation_0-mae:2231.88238
[148]	validation_0-mae:2228.41912
[149]	validation_0-mae:2227.49259
[150]	validation_0-mae:2224.27743
[151]	validation_0-mae:2223.68970
[152]	validation_0-mae:2223.94351
[153]	validation_0-mae:2222.31736
[154]	validation_0-mae:2220.29001
[155]	validation_0-mae:2218.24891
[156]	validation_0-mae:2217.71700
[157]	validation_0-mae:2218.04709
[158]	validation_0-mae:2216.34413
[159]	validation_0-mae:2216.63478
[160]	validation_0-mae:2216.96773
[161]	validation_0-mae:2214.09095
[162]	validation_0-mae:2214.08944
[163]	validation_0-mae:2213.42524
[164]	validation_0-mae:2211.49082
[165]	validation_0-mae:2209.53151
[166]	validation_0-mae:2207.33979
[167]	validation_0-mae:2206.68018
[168]	validation_0-mae:2203.64663
[169]	validation_0-mae:2202.16155
[170]	validation_0-mae:2201.69516
[171]	validation_0-mae:2201.85077
[172]	validation_0-mae:2200.27812
[173]	validation_0-mae:2199.15485
[174]	validation_0-mae:2198.05038
[175]	validation_0-mae:2199.01101
[176]	validation_0-mae:2197.35614
[177]	validation_0-mae:2196.79157
[178]	validation_0-mae:2196.75464
[179]	validation_0-mae:2194.19633
[180]	validation_0-mae:2194.37843
[181]	validation_0-mae:2192.53553
[182]	validation_0-mae:2192.16594
[183]	validation_0-mae:2192.08690
[184]	validation_0-mae:2192.74164
[185]	validation_0-mae:2191.77451
[186]	validation_0-mae:2190.92930
[187]	validation_0-mae:2190.16892
[188]	validation_0-mae:2188.84844
[189]	validation_0-mae:2186.23063
[190]	validation_0-mae:2185.45334
[191]	validation_0-mae:2185.07558
[192]	validation_0-mae:2184.99264
[193]	validation_0-mae:2185.14278
[194]	validation_0-mae:2185.34291
[195]	validation_0-mae:2185.06527
[196]	validation_0-mae:2183.54343
[197]	validation_0-mae:2184.12171
[198]	validation_0-mae:2184.06288
[199]	validation_0-mae:2184.80250
[200]	validation_0-mae:2183.70954
[201]	validation_0-mae:2181.17058
[202]	validation_0-mae:2177.30386
[203]	validation_0-mae:2175.77689
[204]	validation_0-mae:2176.61919
[205]	validation_0-mae:2173.90609
[206]	validation_0-mae:2172.52585
[207]	validation_0-mae:2173.29293
[208]	validation_0-mae:2173.34547
[209]	validation_0-mae:2174.47839
[210]	validation_0-mae:2174.53818
[211]	validation_0-mae:2173.03849
[212]	validation_0-mae:2172.87610
[213]	validation_0-mae:2172.81394
[214]	validation_0-mae:2172.63975
[215]	validation_0-mae:2172.88297
[216]	validation_0-mae:2172.49627
[217]	validation_0-mae:2171.48732
[218]	validation_0-mae:2169.30570
[219]	validation_0-mae:2168.48595
[220]	validation_0-mae:2168.60565
[221]	validation_0-mae:2168.22209
[222]	validation_0-mae:2168.42981
[223]	validation_0-mae:2168.48151
[224]	validation_0-mae:2168.63005
[225]	validation_0-mae:2168.82339
[226]	validation_0-mae:2167.72518
[227]	validation_0-mae:2168.16482
[228]	validation_0-mae:2168.78072
[229]	validation_0-mae:2169.23988
[0]	validation_0-mae:12428.34450
[1]	validation_0-mae:11672.08407
[2]	validation_0-mae:11004.76601
[3]	validation_0-mae:10405.46009
[4]	validation_0-mae:9877.86551
[5]	validation_0-mae:9409.85837
[6]	validation_0-mae:8976.53156
[7]	validation_0-mae:8609.71877
[8]	validation_0-mae:8281.86455
[9]	validation_0-mae:7991.25480

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[0]	validation_0-mae:12408.76970
[1]	validation_0-mae:11646.28962
[2]	validation_0-mae:10969.67615
[3]	validation_0-mae:10321.48030
[4]	validation_0-mae:9764.50710
[5]	validation_0-mae:9265.74360
[6]	validation_0-mae:8781.79012
[7]	validation_0-mae:8364.65482
[8]	validation_0-mae:7997.12372
[9]	validation_0-mae:7625.42207
[10]	validation_0-mae:7312.20297
[11]	validation_0-mae:7003.22978
[12]	validation_0-mae:6743.60582
[13]	validation_0-mae:6494.79807
[14]	validation_0-mae:6246.53590
[15]	validation_0-mae:5993.63754
[16]	validation_0-mae:5779.26003
[17]	validation_0-mae:5600.53812
[18]	validation_0-mae:5418.49411
[19]	validation_0-mae:5236.20061
[20]	validation_0-mae:5070.59881
[21]	validation_0-mae:4920.88808
[22]	validation_0-mae:4760.10640
[23]	validation_0-mae:4636.72234
[24]	validation_0-mae:4507.86432
[25]	validation_0-mae:4395.30066
[26]	validation_0-mae:4286.26721
[27]	validation_0-mae:4180.04174
[28]	validation_0-mae:4085.04667
[29]	validation_0-mae:3984.00295
[30]	validation_0-mae:3883.81400
[31]	validation_0-mae:3805.58757
[32]	validation_0-mae:3737.37472
[33]	validation_0-mae:3653.02224
[34]	validation_0-mae:3583.62881
[35]	validation_0-mae:3533.59319
[36]	validation_0-mae:3480.07430
[37]	validation_0-mae:3428.48866
[38]	validation_0-mae:3386.78345
[39]	validation_0-mae:3336.40563
[40]	validation_0-mae:3302.70561
[41]	validation_0-mae:3261.28026
[42]	validation_0-mae:3203.78504
[43]	validation_0-mae:3170.25029
[44]	validation_0-mae:3128.21905
[45]	validation_0-mae:3094.05077
[46]	validation_0-mae:3066.25532
[47]	validation_0-mae:3027.04745
[48]	validation_0-mae:2984.70260
[49]	validation_0-mae:2961.29272
[50]	validation_0-mae:2931.70768
[51]	validation_0-mae:2912.56723
[52]	validation_0-mae:2883.51524
[53]	validation_0-mae:2857.18284
[54]	validation_0-mae:2834.35921
[55]	validation_0-mae:2815.71511
[56]	validation_0-mae:2799.51635
[57]	validation_0-mae:2784.83361
[58]	validation_0-mae:2768.11183
[59]	validation_0-mae:2753.29278
[60]	validation_0-mae:2735.06961
[61]	validation_0-mae:2719.07926
[62]	validation_0-mae:2710.53483
[63]	validation_0-mae:2690.07919
[64]	validation_0-mae:2672.95952
[65]	validation_0-mae:2664.38140
[66]	validation_0-mae:2650.84923
[67]	validation_0-mae:2636.29277
[68]	validation_0-mae:2616.29087
[69]	validation_0-mae:2608.14490
[70]	validation_0-mae:2598.28573
[71]	validation_0-mae:2590.46943
[72]	validation_0-mae:2580.06113
[73]	validation_0-mae:2554.77257
[74]	validation_0-mae:2542.03686
[75]	validation_0-mae:2536.87601
[76]	validation_0-mae:2529.44260
[77]	validation_0-mae:2521.61613
[78]	validation_0-mae:2510.90629
[79]	validation_0-mae:2505.87892
[80]	validation_0-mae:2498.68402
[81]	validation_0-mae:2489.25634
[82]	validation_0-mae:2481.11424
[83]	validation_0-mae:2476.62137
[84]	validation_0-mae:2466.34548
[85]	validation_0-mae:2462.10888
[86]	validation_0-mae:2455.95151
[87]	validation_0-mae:2447.80523
[88]	validation_0-mae:2441.59141
[89]	validation_0-mae:2433.84314
[90]	validation_0-mae:2425.31216
[91]	validation_0-mae:2421.46153
[92]	validation_0-mae:2415.07635
[93]	validation_0-mae:2405.53691
[94]	validation_0-mae:2400.17208
[95]	validation_0-mae:2396.55092
[96]	validation_0-mae:2387.81211
[97]	validation_0-mae:2382.24989
[98]	validation_0-mae:2377.06293
[99]	validation_0-mae:2372.44213
[100]	validation_0-mae:2367.20590
[101]	validation_0-mae:2360.29020
[102]	validation_0-mae:2357.45621
[103]	validation_0-mae:2353.20054
[104]	validation_0-mae:2346.57633
[105]	validation_0-mae:2344.47662
[106]	validation_0-mae:2340.21824
[107]	validation_0-mae:2334.44380
[108]	validation_0-mae:2329.55446
[109]	validation_0-mae:2327.47924
[110]	validation_0-mae:2318.06036
[111]	validation_0-mae:2315.84796
[112]	validation_0-mae:2314.58520
[113]	validation_0-mae:2313.09331
[114]	validation_0-mae:2309.74942
[115]	validation_0-mae:2306.21978
[116]	validation_0-mae:2304.31663
[117]	validation_0-mae:2302.32101
[118]	validation_0-mae:2297.46382
[119]	validation_0-mae:2293.10841
[120]	validation_0-mae:2291.66585
[121]	validation_0-mae:2286.17790
[122]	validation_0-mae:2286.87253
[123]	validation_0-mae:2283.88848
[124]	validation_0-mae:2282.55066
[125]	validation_0-mae:2280.60725
[126]	validation_0-mae:2279.49354
[127]	validation_0-mae:2274.21402
[128]	validation_0-mae:2272.01705
[129]	validation_0-mae:2270.99764
[130]	validation_0-mae:2265.08397
[131]	validation_0-mae:2264.79128
[132]	validation_0-mae:2264.83304
[133]	validation_0-mae:2261.03673
[134]	validation_0-mae:2257.98421
[135]	validation_0-mae:2255.96644
[136]	validation_0-mae:2254.50136
[137]	validation_0-mae:2250.17351
[138]	validation_0-mae:2250.61593
[139]	validation_0-mae:2246.75308
[140]	validation_0-mae:2246.60436
[141]	validation_0-mae:2246.73259
[142]	validation_0-mae:2245.44496
[143]	validation_0-mae:2240.43837
[144]	validation_0-mae:2238.52753
[145]	validation_0-mae:2236.38042
[146]	validation_0-mae:2235.13488
[147]	validation_0-mae:2232.93625
[148]	validation_0-mae:2233.81137
[149]	validation_0-mae:2233.32735
[150]	validation_0-mae:2228.32578
[151]	validation_0-mae:2227.14122
[152]	validation_0-mae:2225.81976
[153]	validation_0-mae:2226.39333
[154]	validation_0-mae:2225.89468
[155]	validation_0-mae:2223.92560
[156]	validation_0-mae:2224.15700
[157]	validation_0-mae:2224.71696
[158]	validation_0-mae:2224.26879
[159]	validation_0-mae:2222.34687
[160]	validation_0-mae:2222.32950
[161]	validation_0-mae:2218.86773
[162]	validation_0-mae:2216.63052
[163]	validation_0-mae:2215.01814
[164]	validation_0-mae:2214.20733
[165]	validation_0-mae:2212.94186
[166]	validation_0-mae:2210.80739
[167]	validation_0-mae:2209.06569
[168]	validation_0-mae:2205.76659
[169]	validation_0-mae:2204.10250
[170]	validation_0-mae:2202.63422
[171]	validation_0-mae:2201.71027
[172]	validation_0-mae:2200.04585
[173]	validation_0-mae:2198.78473
[174]	validation_0-mae:2197.57467
[175]	validation_0-mae:2196.94005
[176]	validation_0-mae:2195.77681
[177]	validation_0-mae:2194.72510
[178]	validation_0-mae:2192.21912
[179]	validation_0-mae:2191.31912
[180]	validation_0-mae:2190.49526
[181]	validation_0-mae:2188.60942
[182]	validation_0-mae:2187.34411
[183]	validation_0-mae:2185.41560
[184]	validation_0-mae:2184.64163
[185]	validation_0-mae:2183.85161
[186]	validation_0-mae:2183.49104
[187]	validation_0-mae:2181.76614
[188]	validation_0-mae:2180.54673
[189]	validation_0-mae:2179.92645
[190]	validation_0-mae:2178.36915
[191]	validation_0-mae:2177.94039
[192]	validation_0-mae:2176.37753
[193]	validation_0-mae:2174.65581
[194]	validation_0-mae:2171.57256
[195]	validation_0-mae:2171.44802
[196]	validation_0-mae:2169.94208
[197]	validation_0-mae:2168.46481
[198]	validation_0-mae:2168.55613
[199]	validation_0-mae:2168.97067
[200]	validation_0-mae:2169.01869
[201]	validation_0-mae:2168.37878
[202]	validation_0-mae:2167.70702
[203]	validation_0-mae:2168.45351
[204]	validation_0-mae:2168.69266
[205]	validation_0-mae:2167.59422
[206]	validation_0-mae:2167.69177
[207]	validation_0-mae:2167.93739
[208]	validation_0-mae:2167.68728
[209]	validation_0-mae:2166.53911
[210]	validation_0-mae:2165.85487
[211]	validation_0-mae:2164.60986
[212]	validation_0-mae:2163.26256
[213]	validation_0-mae:2163.38661
[214]	validation_0-mae:2162.65366
[215]	validation_0-mae:2161.87144
[216]	validation_0-mae:2161.10218
[217]	validation_0-mae:2161.05862
[218]	validation_0-mae:2160.81441
[219]	validation_0-mae:2161.24892
[220]	validation_0-mae:2160.89301
[221]	validation_0-mae:2160.80587
[222]	validation_0-mae:2159.67802
[223]	validation_0-mae:2161.16151
[224]	validation_0-mae:2161.66005
[225]	validation_0-mae:2160.20073
[226]	validation_0-mae:2159.14722
[227]	validation_0-mae:2159.25864
[228]	validation_0-mae:2159.41095
[229]	validation_0-mae:2158.87230
[230]	validation_0-mae:2159.07972
[231]	validation_0-mae:2159.24125
[232]	validation_0-mae:2159.65806
[233]	validation_0-mae:2158.16033
[234]	validation_0-mae:2156.60934
[235]	validation_0-mae:2156.66406
[236]	validation_0-mae:2156.60080
[237]	validation_0-mae:2156.50507
[238]	validation_0-mae:2155.98669
[239]	validation_0-mae:2156.29105
[240]	validation_0-mae:2156.44269
[241]	validation_0-mae:2154.97821
[242]	validation_0-mae:2153.38548
[243]	validation_0-mae:2152.23613
[244]	validation_0-mae:2150.94832
[245]	validation_0-mae:2150.12555
[246]	validation_0-mae:2149.50395
[247]	validation_0-mae:2146.82474
[248]	validation_0-mae:2146.44887
[249]	validation_0-mae:2144.84274
[250]	validation_0-mae:2143.25070
[251]	validation_0-mae:2143.72426
[252]	validation_0-mae:2144.05885
[253]	validation_0-mae:2144.98473
[254]	validation_0-mae:2144.92355
[255]	validation_0-mae:2144.91062
[256]	validation_0-mae:2145.12664
[257]	validation_0-mae:2144.85981
[258]	validation_0-mae:2144.77052
[259]	validation_0-mae:2145.31386
[260]	validation_0-mae:2143.39815
[261]	validation_0-mae:2142.70810
[262]	validation_0-mae:2141.72999
[263]	validation_0-mae:2141.98877
[264]	validation_0-mae:2140.47805
[265]	validation_0-mae:2138.82445
[266]	validation_0-mae:2138.35991
[267]	validation_0-mae:2139.32718
[268]	validation_0-mae:2139.34400
[269]	validation_0-mae:2139.45484
[270]	validation_0-mae:2139.39455
[271]	validation_0-mae:2140.29692
[272]	validation_0-mae:2140.29870
[273]	validation_0-mae:2139.43391
[274]	validation_0-mae:2138.45907
[275]	validation_0-mae:2137.20983
[276]	validation_0-mae:2137.01309
[277]	validation_0-mae:2136.15205
[278]	validation_0-mae:2136.05414
[279]	validation_0-mae:2135.78968
[280]	validation_0-mae:2135.86529
[281]	validation_0-mae:2135.60163
[282]	validation_0-mae:2135.84839
[283]	validation_0-mae:2134.09917
[284]	validation_0-mae:2132.40173
[285]	validation_0-mae:2131.98949
[286]	validation_0-mae:2131.58092
[287]	validation_0-mae:2131.40064
[288]	validation_0-mae:2131.79103
[289]	validation_0-mae:2131.12650
[290]	validation_0-mae:2129.88171
[291]	validation_0-mae:2129.56991
[292]	validation_0-mae:2129.48666
[293]	validation_0-mae:2129.57841
[294]	validation_0-mae:2129.85834
[295]	validation_0-mae:2129.12983
[296]	validation_0-mae:2129.07628
[297]	validation_0-mae:2128.30149
[298]	validation_0-mae:2129.10493
[299]	validation_0-mae:2128.53827
[300]	validation_0-mae:2127.65292
[301]	validation_0-mae:2127.51812
[302]	validation_0-mae:2127.55262
[303]	validation_0-mae:2126.77034
[304]	validation_0-mae:2126.08126
[305]	validation_0-mae:2125.62807
[306]	validation_0-mae:2123.75130
[307]	validation_0-mae:2123.64317
[308]	validation_0-mae:2124.25979
[309]	validation_0-mae:2123.97906
[310]	validation_0-mae:2123.16578
[311]	validation_0-mae:2122.09071
[312]	validation_0-mae:2122.16472
[313]	validation_0-mae:2121.70023
[314]	validation_0-mae:2121.08722
[315]	validation_0-mae:2120.42590
[316]	validation_0-mae:2120.56741
[317]	validation_0-mae:2120.13396
[318]	validation_0-mae:2120.10726
[319]	validation_0-mae:2120.29866
[320]	validation_0-mae:2119.80349
[321]	validation_0-mae:2119.56487
[322]	validation_0-mae:2119.63684
[323]	validation_0-mae:2118.98727
[324]	validation_0-mae:2118.90267
[325]	validation_0-mae:2119.25204
[326]	validation_0-mae:2119.33408
[327]	validation_0-mae:2119.61445
[328]	validation_0-mae:2119.47033
[329]	validation_0-mae:2119.40857
[330]	validation_0-mae:2119.01668
[331]	validation_0-mae:2119.37484
[332]	validation_0-mae:2119.09416
[333]	validation_0-mae:2118.91008
[334]	validation_0-mae:2119.37842
[335]	validation_0-mae:2119.89962
[336]	validation_0-mae:2119.76585
[337]	validation_0-mae:2119.58181
[338]	validation_0-mae:2118.30008
[339]	validation_0-mae:2118.13016
[340]	validation_0-mae:2118.06382
[341]	validation_0-mae:2117.70496
[342]	validation_0-mae:2117.79871
[343]	validation_0-mae:2118.07131
[344]	validation_0-mae:2117.86132
[345]	validation_0-mae:2117.58073
[346]	validation_0-mae:2117.20846
[347]	validation_0-mae:2116.46493
[348]	validation_0-mae:2116.60354
[349]	validation_0-mae:2116.30621
[350]	validation_0-mae:2115.78266
[351]	validation_0-mae:2115.55515
[352]	validation_0-mae:2114.77357
[353]	validation_0-mae:2115.35077
[354]	validation_0-mae:2115.40842
[355]	validation_0-mae:2115.76257
[356]	validation_0-mae:2116.18271
[357]	validation_0-mae:2116.70711
[358]	validation_0-mae:2116.68933
[359]	validation_0-mae:2116.69356
[360]	validation_0-mae:2116.91178
[361]	validation_0-mae:2116.71283
[362]	validation_0-mae:2116.22928
[363]	validation_0-mae:2116.74812
[364]	validation_0-mae:2116.94136
[365]	validation_0-mae:2116.39511
[366]	validation_0-mae:2116.85902
[367]	validation_0-mae:2117.54814
[368]	validation_0-mae:2117.83076
[369]	validation_0-mae:2117.58694
[370]	validation_0-mae:2117.28484
[371]	validation_0-mae:2116.35307
[372]	validation_0-mae:2116.09868
[373]	validation_0-mae:2115.32340
[374]	validation_0-mae:2114.27192
[375]	validation_0-mae:2113.55487
[376]	validation_0-mae:2113.34735
[377]	validation_0-mae:2112.92053
[378]	validation_0-mae:2113.28334
[379]	validation_0-mae:2112.21389
[380]	validation_0-mae:2112.64765
[381]	validation_0-mae:2112.91230
[382]	validation_0-mae:2111.72836
[383]	validation_0-mae:2110.65627
[384]	validation_0-mae:2110.52818
[385]	validation_0-mae:2110.42862
[386]	validation_0-mae:2110.97632
[387]	validation_0-mae:2110.80196
[388]	validation_0-mae:2110.41909
[389]	validation_0-mae:2109.00124
[390]	validation_0-mae:2109.79189
[391]	validation_0-mae:2110.55594
[392]	validation_0-mae:2110.71924
[393]	validation_0-mae:2110.11416
[394]	validation_0-mae:2109.85856
[395]	validation_0-mae:2109.91663
[396]	validation_0-mae:2109.52823
[397]	validation_0-mae:2108.85858
[398]	validation_0-mae:2109.35407
[399]	validation_0-mae:2109.51874
[400]	validation_0-mae:2109.98339
[401]	validation_0-mae:2109.72637
[402]	validation_0-mae:2109.68490
[403]	validation_0-mae:2109.46360
[404]	validation_0-mae:2109.32652
[405]	validation_0-mae:2108.83433
[406]	validation_0-mae:2108.64481
[407]	validation_0-mae:2107.67982
[408]	validation_0-mae:2107.60690
[409]	validation_0-mae:2107.40898
[410]	validation_0-mae:2106.81929
[411]	validation_0-mae:2106.87722
[412]	validation_0-mae:2106.41424
[413]	validation_0-mae:2106.52127
[414]	validation_0-mae:2106.70583
[415]	validation_0-mae:2106.22419
[416]	validation_0-mae:2106.02402
[417]	validation_0-mae:2106.39624
[418]	validation_0-mae:2106.61093
[419]	validation_0-mae:2106.52277
[420]	validation_0-mae:2106.00773
[421]	validation_0-mae:2106.26807
[422]	validation_0-mae:2104.48618
[423]	validation_0-mae:2104.56764
[424]	validation_0-mae:2104.81105
[425]	validation_0-mae:2104.82073
[426]	validation_0-mae:2104.86714
[427]	validation_0-mae:2105.09997
[428]	validation_0-mae:2104.87496
[429]	validation_0-mae:2104.87668
[430]	validation_0-mae:2105.15756
[431]	validation_0-mae:2105.44720
[432]	validation_0-mae:2105.72790
[433]	validation_0-mae:2105.80882
[434]	validation_0-mae:2106.00458
[435]	validation_0-mae:2106.25344
[436]	validation_0-mae:2106.76091
[437]	validation_0-mae:2107.02735
[438]	validation_0-mae:2106.67783
[439]	validation_0-mae:2106.92168
[440]	validation_0-mae:2106.62344
[441]	validation_0-mae:2106.56281
[442]	validation_0-mae:2106.43336
[443]	validation_0-mae:2106.69575
[444]	validation_0-mae:2107.13318
[445]	validation_0-mae:2105.78248
[446]	validation_0-mae:2106.33331
[447]	validation_0-mae:2106.45051
[448]	validation_0-mae:2106.42379
[449]	validation_0-mae:2106.09039
[450]	validation_0-mae:2105.93482
[451]	validation_0-mae:2106.27051
[452]	validation_0-mae:2106.13404
[453]	validation_0-mae:2106.87485
[454]	validation_0-mae:2105.70127
[455]	validation_0-mae:2105.17537
[456]	validation_0-mae:2104.44017
[457]	validation_0-mae:2104.48539
[458]	validation_0-mae:2104.02664
[459]	validation_0-mae:2102.83506
[460]	validation_0-mae:2102.28361
[461]	validation_0-mae:2101.76344
[462]	validation_0-mae:2101.49587
[463]	validation_0-mae:2101.52904
[464]	validation_0-mae:2101.51982
[465]	validation_0-mae:2101.18341
[466]	validation_0-mae:2101.22592
[467]	validation_0-mae:2100.76976
[468]	validation_0-mae:2100.36913
[469]	validation_0-mae:2100.21981
[470]	validation_0-mae:2100.44610
[471]	validation_0-mae:2099.67551
[472]	validation_0-mae:2099.86601
[473]	validation_0-mae:2098.94417
[474]	validation_0-mae:2099.19220
[475]	validation_0-mae:2098.95368
[476]	validation_0-mae:2099.24790
[477]	validation_0-mae:2099.08731
[478]	validation_0-mae:2099.19704
[479]	validation_0-mae:2099.03584
[480]	validation_0-mae:2098.28122
[481]	validation_0-mae:2097.32514
[482]	validation_0-mae:2096.66064
[483]	validation_0-mae:2096.44153
[484]	validation_0-mae:2096.23038
[485]	validation_0-mae:2096.30840
[486]	validation_0-mae:2096.21298
[487]	validation_0-mae:2095.29323
[488]	validation_0-mae:2094.88593
[489]	validation_0-mae:2095.10228
[490]	validation_0-mae:2095.20334
[491]	validation_0-mae:2094.90066
[492]	validation_0-mae:2095.11363
[493]	validation_0-mae:2095.53672
[494]	validation_0-mae:2095.83564
[495]	validation_0-mae:2095.90872
[496]	validation_0-mae:2096.21708
[497]	validation_0-mae:2096.32642
[498]	validation_0-mae:2095.86853
[499]	validation_0-mae:2095.06635
[500]	validation_0-mae:2095.33563
[501]	validation_0-mae:2095.30989
[502]	validation_0-mae:2095.30913
[503]	validation_0-mae:2095.19100
[504]	validation_0-mae:2095.35160
[505]	validation_0-mae:2095.57125
[506]	validation_0-mae:2095.37996
[507]	validation_0-mae:2096.00505
[508]	validation_0-mae:2096.12626
[509]	validation_0-mae:2095.99727
[510]	validation_0-mae:2096.07761
[511]	validation_0-mae:2095.70682
[0]	validation_0-mae:12387.40555
[1]	validation_0-mae:11609.44681
[2]	validation_0-mae:10901.98701
[3]	validation_0-mae:10251.91323
[4]	validation_0-mae:9678.05201
[5]	validation_0-mae:9143.44776
[6]	validation_0-mae:8703.75434
[7]	validation_0-mae:8262.73980
[8]	validation_0-mae:7869.67357
[9]	validation_0-mae:7514.33558
[10]	validation_0-mae:7184.87389
[11]	validation_0-mae:6885.36599
[12]	validation_0-mae:6615.36656
[13]	validation_0-mae:6365.49815
[14]	validation_0-mae:6103.69557
[15]	validation_0-mae:5889.12603
[16]	validation_0-mae:5691.48590
[17]	validation_0-mae:5493.38287
[18]	validation_0-mae:5305.82776
[19]	validation_0-mae:5124.79952
[20]	validation_0-mae:4948.46324
[21]	validation_0-mae:4787.83247
[22]	validation_0-mae:4670.56414
[23]	validation_0-mae:4525.68614
[24]	validation_0-mae:4407.40573
[25]	validation_0-mae:4294.43917
[26]	validation_0-mae:4193.12829
[27]	validation_0-mae:4101.11967
[28]	validation_0-mae:4006.00796
[29]	validation_0-mae:3926.22390
[30]	validation_0-mae:3833.63551
[31]	validation_0-mae:3757.14904
[32]	validation_0-mae:3669.21524
[33]	validation_0-mae:3596.13358
[34]	validation_0-mae:3519.05377
[35]	validation_0-mae:3462.67210
[36]	validation_0-mae:3412.00732
[37]	validation_0-mae:3360.90044
[38]	validation_0-mae:3312.80003
[39]	validation_0-mae:3269.34255

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[40]	validation_0-mae:3213.80439
[41]	validation_0-mae:3174.47873
[42]	validation_0-mae:3134.35204
[43]	validation_0-mae:3100.23031
[44]	validation_0-mae:3058.77659
[45]	validation_0-mae:3032.21270
[46]	validation_0-mae:2999.74277
[47]	validation_0-mae:2973.40979
[48]	validation_0-mae:2945.79019
[49]	validation_0-mae:2921.49452
[50]	validation_0-mae:2895.19557
[51]	validation_0-mae:2879.15101
[52]	validation_0-mae:2843.02397
[53]	validation_0-mae:2814.04999
[54]	validation_0-mae:2795.54780
[55]	validation_0-mae:2762.90403
[56]	validation_0-mae:2748.24706
[57]	validation_0-mae:2732.60184
[58]	validation_0-mae:2716.08661
[59]	validation_0-mae:2699.66782
[60]	validation_0-mae:2687.97673
[61]	validation_0-mae:2668.42126
[62]	validation_0-mae:2640.56500
[63]	validation_0-mae:2633.43394
[64]	validation_0-mae:2618.57920
[65]	validation_0-mae:2600.96283
[66]	validation_0-mae:2582.16795
[67]	validation_0-mae:2577.41521
[68]	validation_0-mae:2562.28734
[69]	validation_0-mae:2555.55206
[70]	validation_0-mae:2546.60025
[71]	validation_0-mae:2528.73988
[72]	validation_0-mae:2521.34670
[73]	validation_0-mae:2515.58698
[74]	validation_0-mae:2506.73377
[75]	validation_0-mae:2497.40528
[76]	validation_0-mae:2484.99537
[77]	validation_0-mae:2477.07639
[78]	validation_0-mae:2471.05438
[79]	validation_0-mae:2462.97956
[80]	validation_0-mae:2453.07207
[81]	validation_0-mae:2444.38083
[82]	validation_0-mae:2438.70604
[83]	validation_0-mae:2432.22635
[84]	validation_0-mae:2426.72757
[85]	validation_0-mae:2419.34302
[86]	validation_0-mae:2410.79270
[87]	validation_0-mae:2403.94481
[88]	validation_0-mae:2400.63684
[89]	validation_0-mae:2398.21133
[90]	validation_0-mae:2394.66324
[91]	validation_0-mae:2389.00702
[92]	validation_0-mae:2382.89046
[93]	validation_0-mae:2377.70259
[94]	validation_0-mae:2371.47561
[95]	validation_0-mae:2363.41796
[96]	validation_0-mae:2362.56149
[97]	validation_0-mae:2353.23574
[98]	validation_0-mae:2346.94820
[99]	validation_0-mae:2341.60985
[100]	validation_0-mae:2336.46707
[101]	validation_0-mae:2332.85821
[102]	validation_0-mae:2327.79448
[103]	validation_0-mae:2321.91896
[104]	validation_0-mae:2316.84683
[105]	validation_0-mae:2313.94832
[106]	validation_0-mae:2307.82104
[107]	validation_0-mae:2303.08492
[108]	validation_0-mae:2299.19521
[109]	validation_0-mae:2293.10732
[110]	validation_0-mae:2288.37564
[111]	validation_0-mae:2282.63307
[112]	validation_0-mae:2278.67903
[113]	validation_0-mae:2274.52831
[114]	validation_0-mae:2271.24725
[115]	validation_0-mae:2268.82618
[116]	validation_0-mae:2266.58064
[117]	validation_0-mae:2262.25245
[118]	validation_0-mae:2258.67662
[119]	validation_0-mae:2255.88235
[120]	validation_0-mae:2253.31871
[121]	validation_0-mae:2252.93362
[122]	validation_0-mae:2251.43443
[123]	validation_0-mae:2246.12173
[124]	validation_0-mae:2242.52985
[125]	validation_0-mae:2237.54440
[126]	validation_0-mae:2235.62348
[127]	validation_0-mae:2233.58888
[128]	validation_0-mae:2229.26992
[129]	validation_0-mae:2225.79104
[130]	validation_0-mae:2224.03514
[131]	validation_0-mae:2219.61002
[132]	validation_0-mae:2218.23439
[133]	validation_0-mae:2216.84400
[134]	validation_0-mae:2215.00337
[135]	validation_0-mae:2214.73812
[136]	validation_0-mae:2214.65319
[137]	validation_0-mae:2213.16783
[138]	validation_0-mae:2212.57903
[139]	validation_0-mae:2211.28914
[140]	validation_0-mae:2210.23536
[141]	validation_0-mae:2206.51696
[142]	validation_0-mae:2206.11576
[143]	validation_0-mae:2203.70957
[144]	validation_0-mae:2201.04818
[145]	validation_0-mae:2201.57472
[146]	validation_0-mae:2200.78838
[147]	validation_0-mae:2198.58433
[148]	validation_0-mae:2197.12052
[149]	validation_0-mae:2195.44030
[150]	validation_0-mae:2193.37474
[151]	validation_0-mae:2189.83999
[152]	validation_0-mae:2189.57396
[153]	validation_0-mae:2186.39209
[154]	validation_0-mae:2183.75934
[155]	validation_0-mae:2184.04046
[156]	validation_0-mae:2183.74138
[157]	validation_0-mae:2182.99128
[158]	validation_0-mae:2183.89104
[159]	validation_0-mae:2181.27312
[160]	validation_0-mae:2178.46151
[161]	validation_0-mae:2179.13498
[162]	validation_0-mae:2177.34731
[163]	validation_0-mae:2178.18197
[164]	validation_0-mae:2175.17306
[165]	validation_0-mae:2172.56234
[166]	validation_0-mae:2170.37814
[167]	validation_0-mae:2168.39171
[168]	validation_0-mae:2166.94602
[169]	validation_0-mae:2166.47890
[170]	validation_0-mae:2167.84184
[171]	validation_0-mae:2167.87685
[172]	validation_0-mae:2168.83013
[173]	validation_0-mae:2168.13400
[174]	validation_0-mae:2168.57479
[175]	validation_0-mae:2168.67475
[176]	validation_0-mae:2168.53229
[177]	validation_0-mae:2167.04334
[178]	validation_0-mae:2164.98904
[179]	validation_0-mae:2163.45164
[180]	validation_0-mae:2162.77901
[181]	validation_0-mae:2160.69474
[182]	validation_0-mae:2158.56744
[183]	validation_0-mae:2157.64901
[184]	validation_0-mae:2158.81898
[185]	validation_0-mae:2159.11325
[186]	validation_0-mae:2158.77028
[187]	validation_0-mae:2157.61749
[188]	validation_0-mae:2157.53074
[189]	validation_0-mae:2156.52795
[190]	validation_0-mae:2156.46533
[191]	validation_0-mae:2156.42384
[192]	validation_0-mae:2154.35204
[193]	validation_0-mae:2152.86416
[194]	validation_0-mae:2151.74653
[195]	validation_0-mae:2150.37315
[196]	validation_0-mae:2150.06546
[197]	validation_0-mae:2147.75496
[198]	validation_0-mae:2147.13184
[199]	validation_0-mae:2146.05782
[200]	validation_0-mae:2144.06079
[201]	validation_0-mae:2145.33598
[202]	validation_0-mae:2145.82151
[203]	validation_0-mae:2145.06442
[204]	validation_0-mae:2145.02676
[205]	validation_0-mae:2144.80683
[206]	validation_0-mae:2141.54193
[207]	validation_0-mae:2140.48080
[208]	validation_0-mae:2140.19075
[209]	validation_0-mae:2141.13152
[210]	validation_0-mae:2137.63849
[211]	validation_0-mae:2137.05654
[212]	validation_0-mae:2136.26885
[213]	validation_0-mae:2134.44280
[214]	validation_0-mae:2134.44418
[215]	validation_0-mae:2134.17658
[216]	validation_0-mae:2133.90718
[217]	validation_0-mae:2132.36415
[218]	validation_0-mae:2133.02631
[219]	validation_0-mae:2132.79874
[220]	validation_0-mae:2130.80421
[221]	validation_0-mae:2128.96498
[222]	validation_0-mae:2128.68125
[223]	validation_0-mae:2128.58991
[224]	validation_0-mae:2129.20086
[225]	validation_0-mae:2129.00299
[226]	validation_0-mae:2127.52444
[227]	validation_0-mae:2128.34821
[228]	validation_0-mae:2127.67656
[229]	validation_0-mae:2127.42878
[230]	validation_0-mae:2126.61979
[231]	validation_0-mae:2125.35924
[232]	validation_0-mae:2122.36136
[233]	validation_0-mae:2122.54750
[234]	validation_0-mae:2122.04850
[235]	validation_0-mae:2120.64087
[236]	validation_0-mae:2118.76537
[237]	validation_0-mae:2119.37383
[238]	validation_0-mae:2119.24345
[239]	validation_0-mae:2118.89646
[240]	validation_0-mae:2119.19639
[241]	validation_0-mae:2118.23747
[242]	validation_0-mae:2119.16011
[243]	validation_0-mae:2119.01823
[244]	validation_0-mae:2119.35878
[245]	validation_0-mae:2119.67757
[246]	validation_0-mae:2119.75397
[247]	validation_0-mae:2120.48038
[248]	validation_0-mae:2120.33646
[249]	validation_0-mae:2120.38594
[250]	validation_0-mae:2119.30035
[251]	validation_0-mae:2120.01132
[252]	validation_0-mae:2120.44845
[253]	validation_0-mae:2120.99263
[254]	validation_0-mae:2121.36825
[255]	validation_0-mae:2119.75131
[256]	validation_0-mae:2119.47152
[257]	validation_0-mae:2119.91766
[258]	validation_0-mae:2119.18962
[259]	validation_0-mae:2118.27047
[260]	validation_0-mae:2117.72142
[261]	validation_0-mae:2117.82536
[262]	validation_0-mae:2118.16074
[263]	validation_0-mae:2116.65189
[264]	validation_0-mae:2115.66653
[265]	validation_0-mae:2116.04966
[266]	validation_0-mae:2115.17419
[267]	validation_0-mae:2113.53172
[268]	validation_0-mae:2113.51252
[269]	validation_0-mae:2113.15738
[270]	validation_0-mae:2112.80145
[271]	validation_0-mae:2113.42348
[272]	validation_0-mae:2113.49663
[273]	validation_0-mae:2113.64705
[274]	validation_0-mae:2113.53694
[275]	validation_0-mae:2113.48534
[276]	validation_0-mae:2112.27224
[277]	validation_0-mae:2112.65911
[278]	validation_0-mae:2112.32306
[279]	validation_0-mae:2112.07025
[280]	validation_0-mae:2111.63183
[281]	validation_0-mae:2110.30776
[282]	validation_0-mae:2110.36046
[283]	validation_0-mae:2110.23582
[284]	validation_0-mae:2110.85063
[285]	validation_0-mae:2111.34052
[286]	validation_0-mae:2111.67620
[287]	validation_0-mae:2111.40014
[288]	validation_0-mae:2110.51705
[289]	validation_0-mae:2108.97048
[290]	validation_0-mae:2108.87314
[291]	validation_0-mae:2108.27833
[292]	validation_0-mae:2107.67032
[293]	validation_0-mae:2107.40558
[294]	validation_0-mae:2107.21380
[295]	validation_0-mae:2106.69861
[296]	validation_0-mae:2106.91345
[297]	validation_0-mae:2106.63069
[298]	validation_0-mae:2106.67170
[299]	validation_0-mae:2106.20929
[300]	validation_0-mae:2105.88691
[301]	validation_0-mae:2105.65728
[302]	validation_0-mae:2104.86144
[303]	validation_0-mae:2105.13141
[304]	validation_0-mae:2105.11092
[305]	validation_0-mae:2105.61412
[306]	validation_0-mae:2105.17682
[307]	validation_0-mae:2104.87665
[308]	validation_0-mae:2103.75503
[309]	validation_0-mae:2103.03857
[310]	validation_0-mae:2103.04976
[311]	validation_0-mae:2102.82200
[312]	validation_0-mae:2101.75791
[313]	validation_0-mae:2101.54848
[314]	validation_0-mae:2101.09119
[315]	validation_0-mae:2101.09771
[316]	validation_0-mae:2101.14898
[317]	validation_0-mae:2099.61683
[318]	validation_0-mae:2098.42648
[319]	validation_0-mae:2097.43382
[320]	validation_0-mae:2098.07562
[321]	validation_0-mae:2098.80561
[322]	validation_0-mae:2098.91635
[323]	validation_0-mae:2099.20814
[324]	validation_0-mae:2097.16117
[325]	validation_0-mae:2097.18483
[326]	validation_0-mae:2096.08801
[327]	validation_0-mae:2095.44284
[328]	validation_0-mae:2095.44180
[329]	validation_0-mae:2094.66641
[330]	validation_0-mae:2093.93518
[331]	validation_0-mae:2094.78346
[332]	validation_0-mae:2094.99598
[333]	validation_0-mae:2094.88418
[334]	validation_0-mae:2094.36663
[335]	validation_0-mae:2093.99582
[336]	validation_0-mae:2094.62722
[337]	validation_0-mae:2094.55411
[338]	validation_0-mae:2095.48976
[339]	validation_0-mae:2095.27856
[340]	validation_0-mae:2094.71715
[341]	validation_0-mae:2094.20584
[342]	validation_0-mae:2093.93831
[343]	validation_0-mae:2093.58201
[344]	validation_0-mae:2092.68291
[345]	validation_0-mae:2093.13659
[346]	validation_0-mae:2092.77279
[347]	validation_0-mae:2092.40063
[348]	validation_0-mae:2092.62401
[349]	validation_0-mae:2091.57557
[350]	validation_0-mae:2091.69140
[351]	validation_0-mae:2091.10113
[352]	validation_0-mae:2090.88142
[353]	validation_0-mae:2090.32261
[354]	validation_0-mae:2090.27028
[355]	validation_0-mae:2090.29800
[356]	validation_0-mae:2090.12506
[357]	validation_0-mae:2090.54616
[358]	validation_0-mae:2089.86152
[359]	validation_0-mae:2089.57606
[360]	validation_0-mae:2089.37534
[361]	validation_0-mae:2089.08155
[362]	validation_0-mae:2088.66932
[363]	validation_0-mae:2088.27308
[364]	validation_0-mae:2088.88215
[365]	validation_0-mae:2088.89339
[366]	validation_0-mae:2088.75893
[367]	validation_0-mae:2088.87212
[368]	validation_0-mae:2088.78609
[369]	validation_0-mae:2088.99341
[370]	validation_0-mae:2088.95955
[371]	validation_0-mae:2088.96817
[372]	validation_0-mae:2089.44790
[373]	validation_0-mae:2090.46507
[374]	validation_0-mae:2090.90971
[375]	validation_0-mae:2091.69011
[376]	validation_0-mae:2091.74073
[377]	validation_0-mae:2091.75500
[378]	validation_0-mae:2091.77420
[379]	validation_0-mae:2092.01433
[380]	validation_0-mae:2091.90101
[381]	validation_0-mae:2091.94247
[382]	validation_0-mae:2092.45391
[383]	validation_0-mae:2092.44505
[384]	validation_0-mae:2092.18341
[385]	validation_0-mae:2092.21059
[386]	validation_0-mae:2091.47941
[387]	validation_0-mae:2091.85077
[388]	validation_0-mae:2092.17964
[389]	validation_0-mae:2091.88640
[390]	validation_0-mae:2091.58908
[391]	validation_0-mae:2091.90190
[392]	validation_0-mae:2092.03928
[393]	validation_0-mae:2091.40790
[394]	validation_0-mae:2090.77219
[395]	validation_0-mae:2090.57947
[396]	validation_0-mae:2090.82044
[397]	validation_0-mae:2090.92728
[398]	validation_0-mae:2090.95749
[399]	validation_0-mae:2091.31725
[400]	validation_0-mae:2091.70768
[401]	validation_0-mae:2092.12283
[402]	validation_0-mae:2092.39663
[403]	validation_0-mae:2090.26954
[404]	validation_0-mae:2090.71468
[405]	validation_0-mae:2090.21469
[406]	validation_0-mae:2089.43282
[407]	validation_0-mae:2088.62438
[408]	validation_0-mae:2088.75249
[409]	validation_0-mae:2089.02509
[410]	validation_0-mae:2089.15795
[411]	validation_0-mae:2088.39262
[412]	validation_0-mae:2088.42278
[413]	validation_0-mae:2087.96683
[414]	validation_0-mae:2087.66359
[415]	validation_0-mae:2087.84189
[416]	validation_0-mae:2088.51616
[417]	validation_0-mae:2088.30446
[418]	validation_0-mae:2086.97538
[419]	validation_0-mae:2086.72293
[420]	validation_0-mae:2085.97850
[421]	validation_0-mae:2085.85616
[422]	validation_0-mae:2086.07648
[423]	validation_0-mae:2085.75202
[424]	validation_0-mae:2085.73754
[425]	validation_0-mae:2085.86368
[426]	validation_0-mae:2086.05073
[427]	validation_0-mae:2085.79854
[428]	validation_0-mae:2085.83003
[429]	validation_0-mae:2085.81407
[430]	validation_0-mae:2085.28405
[431]	validation_0-mae:2085.29569
[432]	validation_0-mae:2085.34105
[433]	validation_0-mae:2085.67699
[434]	validation_0-mae:2085.94633
[435]	validation_0-mae:2085.70299
[436]	validation_0-mae:2086.04703
[437]	validation_0-mae:2086.23494
[438]	validation_0-mae:2086.26191
[439]	validation_0-mae:2086.22437
[440]	validation_0-mae:2085.56552
[441]	validation_0-mae:2085.48777
[442]	validation_0-mae:2085.55749
[443]	validation_0-mae:2085.67968
[444]	validation_0-mae:2085.17290
[445]	validation_0-mae:2085.23578
[446]	validation_0-mae:2085.69051
[447]	validation_0-mae:2085.71108
[448]	validation_0-mae:2085.90527
[449]	validation_0-mae:2086.11452
[450]	validation_0-mae:2086.28796
[451]	validation_0-mae:2086.38304
[452]	validation_0-mae:2086.51879
[453]	validation_0-mae:2086.53641
[454]	validation_0-mae:2086.79979
[455]	validation_0-mae:2087.19028
[456]	validation_0-mae:2086.81736
[457]	validation_0-mae:2086.96350
[458]	validation_0-mae:2087.29991
[459]	validation_0-mae:2086.73779
[460]	validation_0-mae:2087.01950
[461]	validation_0-mae:2087.04107
[462]	validation_0-mae:2086.89305
[463]	validation_0-mae:2087.11743
[464]	validation_0-mae:2087.01075
[465]	validation_0-mae:2086.80531
[466]	validation_0-mae:2086.71562
[467]	validation_0-mae:2086.78799
[468]	validation_0-mae:2087.08088
[469]	validation_0-mae:2086.97627
[470]	validation_0-mae:2086.74851
[471]	validation_0-mae:2086.77611
[472]	validation_0-mae:2086.67022
[473]	validation_0-mae:2086.77207
[474]	validation_0-mae:2086.82905
[475]	validation_0-mae:2086.94310
[476]	validation_0-mae:2086.70355
[477]	validation_0-mae:2086.44594
[478]	validation_0-mae:2086.35372
[479]	validation_0-mae:2086.64703
[480]	validation_0-mae:2086.72844
[481]	validation_0-mae:2087.17750
[482]	validation_0-mae:2087.60029
[483]	validation_0-mae:2087.74411
[484]	validation_0-mae:2087.83362
[485]	validation_0-mae:2088.11919
[486]	validation_0-mae:2088.60347
[487]	validation_0-mae:2088.03188
[488]	validation_0-mae:2088.21734
[489]	validation_0-mae:2088.66951
[490]	validation_0-mae:2088.73121
[491]	validation_0-mae:2088.29916
[492]	validation_0-mae:2088.10367
[493]	validation_0-mae:2087.90162
[494]	validation_0-mae:2087.62755
[495]	validation_0-mae:2087.43708
[496]	validation_0-mae:2086.69997
[497]	validation_0-mae:2086.39472
[498]	validation_0-mae:2086.18865
[499]	validation_0-mae:2086.08328
[500]	validation_0-mae:2086.15135
[501]	validation_0-mae:2086.20731
[502]	validation_0-mae:2086.21089
[503]	validation_0-mae:2086.46209
[504]	validation_0-mae:2086.43326
[505]	validation_0-mae:2086.01715
[506]	validation_0-mae:2086.11338
[507]	validation_0-mae:2085.97993
[508]	validation_0-mae:2086.03362
[509]	validation_0-mae:2085.34850
[510]	validation_0-mae:2084.89780
[511]	validation_0-mae:2084.68855
[512]	validation_0-mae:2084.67733
[513]	validation_0-mae:2084.76205
[514]	validation_0-mae:2084.53728
[515]	validation_0-mae:2084.28950
[516]	validation_0-mae:2084.17997
[517]	validation_0-mae:2084.19142
[518]	validation_0-mae:2084.35785
[519]	validation_0-mae:2084.69994
[520]	validation_0-mae:2084.78338
[521]	validation_0-mae:2084.48911
[522]	validation_0-mae:2084.61420
[523]	validation_0-mae:2084.74108
[524]	validation_0-mae:2084.84789
[525]	validation_0-mae:2084.98157
[526]	validation_0-mae:2084.85789
[527]	validation_0-mae:2084.75378
[528]	validation_0-mae:2084.66595
[529]	validation_0-mae:2084.95862
[530]	validation_0-mae:2085.26953
[531]	validation_0-mae:2084.87821
[532]	validation_0-mae:2084.62130
[533]	validation_0-mae:2084.57516
[534]	validation_0-mae:2084.31405
[535]	validation_0-mae:2084.36299
[536]	validation_0-mae:2084.54212
[537]	validation_0-mae:2084.59664
[538]	validation_0-mae:2084.65039
[539]	validation_0-mae:2084.80046
[540]	validation_0-mae:2084.75498
[541]	validation_0-mae:2084.62434
[542]	validation_0-mae:2084.30085
[543]	validation_0-mae:2084.49200
[544]	validation_0-mae:2084.31960
[545]	validation_0-mae:2084.75702
[546]	validation_0-mae:2084.77319
[547]	validation_0-mae:2084.87962
[548]	validation_0-mae:2084.82625
[549]	validation_0-mae:2084.90526
[550]	validation_0-mae:2084.67749
[551]	validation_0-mae:2084.68771
[552]	validation_0-mae:2084.73145
[553]	validation_0-mae:2084.78413
[554]	validation_0-mae:2085.15329
[555]	validation_0-mae:2085.17332
[556]	validation_0-mae:2085.50904
[557]	validation_0-mae:2085.91579
[558]	validation_0-mae:2085.00435
[559]	validation_0-mae:2084.31502
[560]	validation_0-mae:2084.32359
[561]	validation_0-mae:2084.48094
[562]	validation_0-mae:2084.70626
[563]	validation_0-mae:2084.49633
[564]	validation_0-mae:2084.38197
[565]	validation_0-mae:2084.42346
[566]	validation_0-mae:2083.23415
[567]	validation_0-mae:2083.25058
[568]	validation_0-mae:2083.30497
[569]	validation_0-mae:2082.75090
[570]	validation_0-mae:2082.92972
[571]	validation_0-mae:2083.11029
[572]	validation_0-mae:2082.92021
[573]	validation_0-mae:2083.02374
[574]	validation_0-mae:2082.88179
[575]	validation_0-mae:2082.98502
[576]	validation_0-mae:2083.13281
[577]	validation_0-mae:2083.00610
[578]	validation_0-mae:2082.69318
[579]	validation_0-mae:2082.58481
[580]	validation_0-mae:2082.16220
[581]	validation_0-mae:2082.05293
[582]	validation_0-mae:2082.20628
[583]	validation_0-mae:2082.30942
[584]	validation_0-mae:2082.51757
[585]	validation_0-mae:2081.67474
[586]	validation_0-mae:2081.47244
[587]	validation_0-mae:2080.85624
[588]	validation_0-mae:2080.84670
[589]	validation_0-mae:2080.92177
[590]	validation_0-mae:2080.77580
[591]	validation_0-mae:2080.65870
[592]	validation_0-mae:2080.49395
[593]	validation_0-mae:2080.56753
[594]	validation_0-mae:2080.70193
[595]	validation_0-mae:2080.82566
[596]	validation_0-mae:2080.54360
[597]	validation_0-mae:2080.57269
[598]	validation_0-mae:2080.50749
[599]	validation_0-mae:2080.12765
[600]	validation_0-mae:2080.07980
[601]	validation_0-mae:2080.14629
[602]	validation_0-mae:2080.14861
[603]	validation_0-mae:2080.42736
[604]	validation_0-mae:2080.11501
[605]	validation_0-mae:2080.11204
[606]	validation_0-mae:2079.81196
[607]	validation_0-mae:2079.99035
[608]	validation_0-mae:2079.54127
[609]	validation_0-mae:2079.40428
[610]	validation_0-mae:2079.34317
[611]	validation_0-mae:2078.95000
[612]	validation_0-mae:2078.80741
[613]	validation_0-mae:2079.07031
[614]	validation_0-mae:2078.97982
[615]	validation_0-mae:2079.00456
[616]	validation_0-mae:2078.52483
[617]	validation_0-mae:2078.62196
[618]	validation_0-mae:2078.47147
[619]	validation_0-mae:2078.20311
[620]	validation_0-mae:2078.20830
[621]	validation_0-mae:2078.04645
[622]	validation_0-mae:2077.83528
[623]	validation_0-mae:2077.84106
[624]	validation_0-mae:2077.53788
[625]	validation_0-mae:2077.41063
[626]	validation_0-mae:2077.58202
[627]	validation_0-mae:2077.62119
[628]	validation_0-mae:2077.56130
[629]	validation_0-mae:2077.38226

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[0]	validation_0-mae:12409.80983
[1]	validation_0-mae:11649.11829
[2]	validation_0-mae:10971.47942
[3]	validation_0-mae:10320.69232
[4]	validation_0-mae:9766.17715
[5]	validation_0-mae:9238.12168
[6]	validation_0-mae:8785.55062
[7]	validation_0-mae:8361.58266
[8]	validation_0-mae:7992.48503
[9]	validation_0-mae:7646.95262
[10]	validation_0-mae:7336.55975
[11]	validation_0-mae:7026.67481
[12]	validation_0-mae:6747.73909
[13]	validation_0-mae:6496.39427
[14]	validation_0-mae:6277.79953
[15]	validation_0-mae:6041.64032
[16]	validation_0-mae:5815.48696
[17]	validation_0-mae:5609.09342
[18]	validation_0-mae:5412.25243
[19]	validation_0-mae:5241.45324
[20]	validation_0-mae:5067.67418
[21]	validation_0-mae:4907.75395
[22]	validation_0-mae:4749.55410
[23]	validation_0-mae:4620.88748
[24]	validation_0-mae:4489.07892
[25]	validation_0-mae:4371.16066
[26]	validation_0-mae:4263.56239
[27]	validation_0-mae:4155.64385
[28]	validation_0-mae:4056.54219
[29]	validation_0-mae:3966.82866
[30]	validation_0-mae:3871.41210
[31]	validation_0-mae:3786.04466
[32]	validation_0-mae:3711.22370
[33]	validation_0-mae:3655.78460
[34]	validation_0-mae:3582.46594
[35]	validation_0-mae:3523.09120
[36]	validation_0-mae:3457.78377
[37]	validation_0-mae:3400.40927
[38]	validation_0-mae:3355.48440
[39]	validation_0-mae:3305.52616
[40]	validation_0-mae:3260.28939
[41]	validation_0-mae:3225.65827
[42]	validation_0-mae:3188.86715
[43]	validation_0-mae:3149.99424
[44]	validation_0-mae:3105.18037
[45]	validation_0-mae:3069.94820
[46]	validation_0-mae:3039.11970
[47]	validation_0-mae:3000.57543
[48]	validation_0-mae:2972.57198
[49]	validation_0-mae:2946.87025
[50]	validation_0-mae:2926.25882
[51]	validation_0-mae:2905.57069
[52]	validation_0-mae:2886.73061
[53]	validation_0-mae:2861.49598
[54]	validation_0-mae:2839.26684
[55]	validation_0-mae:2820.18258
[56]	validation_0-mae:2800.16085
[57]	validation_0-mae:2787.18584
[58]	validation_0-mae:2769.64624
[59]	validation_0-mae:2752.23375
[60]	validation_0-mae:2735.72746
[61]	validation_0-mae:2722.61526
[62]	validation_0-mae:2708.80542
[63]	validation_0-mae:2695.82720
[64]	validation_0-mae:2680.17908
[65]	validation_0-mae:2667.98010
[66]	validation_0-mae:2650.51875
[67]	validation_0-mae:2638.94446
[68]	validation_0-mae:2631.35403
[69]	validation_0-mae:2620.70786
[70]	validation_0-mae:2606.61673
[71]	validation_0-mae:2588.76151
[72]	validation_0-mae:2578.73725
[73]	validation_0-mae:2568.67126
[74]	validation_0-mae:2553.74990
[75]	validation_0-mae:2548.34012
[76]	validation_0-mae:2543.55667
[77]	validation_0-mae:2535.09041
[78]	validation_0-mae:2523.48598
[79]	validation_0-mae:2508.01590
[80]	validation_0-mae:2502.67054
[81]	validation_0-mae:2500.49601
[82]	validation_0-mae:2493.53210
[83]	validation_0-mae:2479.03626
[84]	validation_0-mae:2472.21015
[85]	validation_0-mae:2464.92901
[86]	validation_0-mae:2459.08011
[87]	validation_0-mae:2451.33935
[88]	validation_0-mae:2448.91271
[89]	validation_0-mae:2443.60762
[90]	validation_0-mae:2437.66145
[91]	validation_0-mae:2434.16885
[0]	validation_0-mae:12449.80009
[1]	validation_0-mae:11720.16418
[2]	validation_0-mae:11066.97136
[3]	validation_0-mae:10456.03164
[4]	validation_0-mae:9918.37035
[5]	validation_0-mae:9415.55171
[6]	validation_0-mae:8968.17023
[7]	validation_0-mae:8565.18109
[8]	validation_0-mae:8207.66477
[9]	validation_0-mae:7861.73870
[10]	validation_0-mae:7539.57080

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[0]	validation_0-mae:12393.33375
[1]	validation_0-mae:11619.29619
[2]	validation_0-mae:10916.22475
[3]	validation_0-mae:10275.90596
[4]	validation_0-mae:9712.86117
[5]	validation_0-mae:9189.34461
[6]	validation_0-mae:8747.77359
[7]	validation_0-mae:8337.86798
[8]	validation_0-mae:7958.92129
[9]	validation_0-mae:7622.00410
[10]	validation_0-mae:7303.71496
[11]	validation_0-mae:6993.50412
[12]	validation_0-mae:6722.39548
[13]	validation_0-mae:6440.08913
[14]	validation_0-mae:6173.49045
[15]	validation_0-mae:5967.71810
[16]	validation_0-mae:5768.04205
[17]	validation_0-mae:5538.27642
[18]	validation_0-mae:5378.31559
[19]	validation_0-mae:5196.19456
[20]	validation_0-mae:5044.33311
[21]	validation_0-mae:4921.08138
[22]	validation_0-mae:4778.74255
[23]	validation_0-mae:4631.88684
[24]	validation_0-mae:4498.71653
[25]	validation_0-mae:4379.46617
[26]	validation_0-mae:4295.11250
[27]	validation_0-mae:4191.29262
[28]	validation_0-mae:4086.89473
[29]	validation_0-mae:3975.88207
[30]	validation_0-mae:3881.73109
[31]	validation_0-mae:3800.43117
[32]	validation_0-mae:3723.53716
[33]	validation_0-mae:3667.94403
[34]	validation_0-mae:3602.53206
[35]	validation_0-mae:3557.18517
[36]	validation_0-mae:3485.38168
[37]	validation_0-mae:3433.95383
[38]	validation_0-mae:3394.08269
[39]	validation_0-mae:3359.14226
[40]	validation_0-mae:3321.30547
[41]	validation_0-mae:3280.17495
[42]	validation_0-mae:3228.74594
[43]	validation_0-mae:3192.43121
[44]	validation_0-mae:3133.65334
[45]	validation_0-mae:3093.39338
[46]	validation_0-mae:3065.17671
[47]	validation_0-mae:3037.49905
[48]	validation_0-mae:2999.60382
[49]	validation_0-mae:2971.72261
[50]	validation_0-mae:2933.56266
[51]	validation_0-mae:2912.17230
[52]	validation_0-mae:2887.72033
[53]	validation_0-mae:2868.19279
[54]	validation_0-mae:2854.42896
[55]	validation_0-mae:2825.19862
[56]	validation_0-mae:2812.56632
[57]	validation_0-mae:2797.22479
[58]	validation_0-mae:2782.56196
[59]	validation_0-mae:2766.87383
[60]	validation_0-mae:2752.37489
[61]	validation_0-mae:2734.98664
[62]	validation_0-mae:2723.64070
[63]	validation_0-mae:2701.70366
[64]	validation_0-mae:2685.22924
[65]	validation_0-mae:2673.92676
[66]	validation_0-mae:2666.05772
[67]	validation_0-mae:2644.93145
[68]	validation_0-mae:2632.71044
[69]	validation_0-mae:2619.30588
[70]	validation_0-mae:2600.20730
[71]	validation_0-mae:2588.86220
[72]	validation_0-mae:2580.13762
[73]	validation_0-mae:2570.23550
[74]	validation_0-mae:2559.42995
[75]	validation_0-mae:2551.86992
[76]	validation_0-mae:2541.79815
[77]	validation_0-mae:2534.06648
[78]	validation_0-mae:2528.79964
[79]	validation_0-mae:2515.03091
[80]	validation_0-mae:2506.03787
[81]	validation_0-mae:2499.51711
[82]	validation_0-mae:2489.50129
[83]	validation_0-mae:2475.68589
[84]	validation_0-mae:2466.41899
[85]	validation_0-mae:2461.09887
[86]	validation_0-mae:2453.29188
[87]	validation_0-mae:2447.05585
[88]	validation_0-mae:2441.51262
[89]	validation_0-mae:2430.29331
[90]	validation_0-mae:2420.61252
[91]	validation_0-mae:2418.77231
[92]	validation_0-mae:2407.15508
[93]	validation_0-mae:2402.17223
[94]	validation_0-mae:2395.99274
[95]	validation_0-mae:2388.76290
[96]	validation_0-mae:2381.81665
[97]	validation_0-mae:2377.92614
[98]	validation_0-mae:2372.10561
[99]	validation_0-mae:2367.92060
[100]	validation_0-mae:2363.35287
[101]	validation_0-mae:2360.61573
[102]	validation_0-mae:2353.32826
[103]	validation_0-mae:2347.44445
[104]	validation_0-mae:2339.94858
[105]	validation_0-mae:2334.66970
[106]	validation_0-mae:2330.79002
[107]	validation_0-mae:2324.80577
[108]	validation_0-mae:2321.41118
[109]	validation_0-mae:2318.51832
[110]	validation_0-mae:2317.42836
[111]	validation_0-mae:2314.04093
[112]	validation_0-mae:2310.81165
[113]	validation_0-mae:2308.02256
[114]	validation_0-mae:2300.48942
[115]	validation_0-mae:2298.63550
[116]	validation_0-mae:2296.84265
[117]	validation_0-mae:2292.81361
[118]	validation_0-mae:2289.59733
[119]	validation_0-mae:2288.59018
[120]	validation_0-mae:2286.77941
[121]	validation_0-mae:2283.74718
[122]	validation_0-mae:2277.72969
[123]	validation_0-mae:2279.24254
[124]	validation_0-mae:2279.63530
[125]	validation_0-mae:2279.88879
[126]	validation_0-mae:2277.66225
[127]	validation_0-mae:2273.99688
[128]	validation_0-mae:2269.65923
[129]	validation_0-mae:2264.05094
[130]	validation_0-mae:2259.87431
[131]	validation_0-mae:2258.72472
[132]	validation_0-mae:2255.11304
[133]	validation_0-mae:2250.60997
[134]	validation_0-mae:2247.89225
[135]	validation_0-mae:2246.56720
[136]	validation_0-mae:2243.77941
[137]	validation_0-mae:2241.29368
[138]	validation_0-mae:2238.93839
[139]	validation_0-mae:2236.09553
[140]	validation_0-mae:2237.65648
[141]	validation_0-mae:2234.71289
[142]	validation_0-mae:2233.04490
[143]	validation_0-mae:2232.25765
[144]	validation_0-mae:2231.35649
[145]	validation_0-mae:2230.98991
[146]	validation_0-mae:2229.56138
[147]	validation_0-mae:2228.96698
[148]	validation_0-mae:2227.74854
[149]	validation_0-mae:2226.52871
[150]	validation_0-mae:2225.61759
[151]	validation_0-mae:2221.14780
[152]	validation_0-mae:2220.26240
[153]	validation_0-mae:2218.98602
[154]	validation_0-mae:2217.64671
[155]	validation_0-mae:2217.81697
[156]	validation_0-mae:2215.40231
[157]	validation_0-mae:2215.46668
[158]	validation_0-mae:2212.59453
[159]	validation_0-mae:2210.80710
[160]	validation_0-mae:2209.66120
[161]	validation_0-mae:2209.18357
[162]	validation_0-mae:2208.88253
[163]	validation_0-mae:2208.39672
[164]	validation_0-mae:2207.75306
[165]	validation_0-mae:2208.13879
[166]	validation_0-mae:2207.93044
[167]	validation_0-mae:2208.36921
[168]	validation_0-mae:2205.39278
[169]	validation_0-mae:2202.05144
[170]	validation_0-mae:2201.35031
[171]	validation_0-mae:2199.83049
[172]	validation_0-mae:2200.23715
[173]	validation_0-mae:2198.71540
[174]	validation_0-mae:2195.98260
[175]	validation_0-mae:2196.05714
[176]	validation_0-mae:2194.66808
[177]	validation_0-mae:2193.56509
[178]	validation_0-mae:2193.68426
[179]	validation_0-mae:2192.37292
[180]	validation_0-mae:2192.34270
[181]	validation_0-mae:2190.87461
[182]	validation_0-mae:2190.93771
[183]	validation_0-mae:2190.34655
[184]	validation_0-mae:2191.31916
[185]	validation_0-mae:2190.33277
[186]	validation_0-mae:2187.65425
[187]	validation_0-mae:2184.09315
[188]	validation_0-mae:2183.98882
[189]	validation_0-mae:2183.66301
[190]	validation_0-mae:2182.88413
[191]	validation_0-mae:2182.67724
[192]	validation_0-mae:2181.89004
[193]	validation_0-mae:2180.52672
[194]	validation_0-mae:2180.93867
[195]	validation_0-mae:2180.12348
[196]	validation_0-mae:2179.43429
[197]	validation_0-mae:2179.77355
[198]	validation_0-mae:2178.26911
[199]	validation_0-mae:2179.12801
[200]	validation_0-mae:2177.78044
[201]	validation_0-mae:2177.77794
[202]	validation_0-mae:2177.56896
[203]	validation_0-mae:2178.11503
[204]	validation_0-mae:2177.71551
[205]	validation_0-mae:2178.23676
[206]	validation_0-mae:2177.39162
[207]	validation_0-mae:2176.96945
[208]	validation_0-mae:2175.19136
[209]	validation_0-mae:2173.21083
[210]	validation_0-mae:2171.63971
[211]	validation_0-mae:2170.29664
[212]	validation_0-mae:2168.66993
[213]	validation_0-mae:2168.68017
[214]	validation_0-mae:2166.57415
[215]	validation_0-mae:2165.85397
[216]	validation_0-mae:2166.53616
[217]	validation_0-mae:2163.98974
[218]	validation_0-mae:2163.40802
[219]	validation_0-mae:2162.52420
[220]	validation_0-mae:2162.83646
[221]	validation_0-mae:2162.89883
[222]	validation_0-mae:2164.20464
[223]	validation_0-mae:2163.85575
[224]	validation_0-mae:2163.32309
[225]	validation_0-mae:2163.99703
[226]	validation_0-mae:2163.29170
[227]	validation_0-mae:2163.61819
[228]	validation_0-mae:2160.90251
[229]	validation_0-mae:2160.57718
[230]	validation_0-mae:2160.02909
[231]	validation_0-mae:2160.48266
[232]	validation_0-mae:2160.27030
[233]	validation_0-mae:2158.80808
[234]	validation_0-mae:2158.91702
[235]	validation_0-mae:2158.90713
[236]	validation_0-mae:2158.79920
[237]	validation_0-mae:2156.31047
[238]	validation_0-mae:2155.23778
[239]	validation_0-mae:2154.74863
[240]	validation_0-mae:2154.31383
[241]	validation_0-mae:2154.08821
[242]	validation_0-mae:2154.30173
[243]	validation_0-mae:2153.67198
[244]	validation_0-mae:2153.78514
[245]	validation_0-mae:2153.95937
[246]	validation_0-mae:2154.22181
[247]	validation_0-mae:2153.52867
[248]	validation_0-mae:2152.76506
[249]	validation_0-mae:2153.26957
[250]	validation_0-mae:2153.51308
[251]	validation_0-mae:2153.42418
[252]	validation_0-mae:2153.51902
[253]	validation_0-mae:2153.28968
[254]	validation_0-mae:2153.40343
[255]	validation_0-mae:2152.36970
[256]	validation_0-mae:2152.71735
[257]	validation_0-mae:2152.47637
[258]	validation_0-mae:2152.54421
[259]	validation_0-mae:2152.88157
[260]	validation_0-mae:2152.63566
[261]	validation_0-mae:2152.36027
[0]	validation_0-mae:12430.70776
[1]	validation_0-mae:11676.95449
[2]	validation_0-mae:11005.53055
[3]	validation_0-mae:10362.94856
[4]	validation_0-mae:9807.77648
[5]	validation_0-mae:9300.40616
[6]	validation_0-mae:8837.85109
[7]	validation_0-mae:8414.30989
[8]	validation_0-mae:8053.83885
[9]	validation_0-mae:7708.30847
[10]	validation_0-mae:7400.91654
[11]	validation_0-mae:7098.44913
[12]	validation_0-mae:6838.71169
[13]	validation_0-mae:6598.64634
[14]	validation_0-mae:6336.13198
[15]	validation_0-mae:6094.09083
[16]	validation_0-mae:5865.87088
[17]	validation_0-mae:5645.52385
[18]	validation_0-mae:5461.58960
[19]	validation_0-mae:5281.09761
[20]	validation_0-mae:5121.83097
[21]	validation_0-mae:4978.83068
[22]	validation_0-mae:4848.89503
[23]	validation_0-mae:4698.77067
[24]	validation_0-mae:4559.35147
[25]	validation_0-mae:4440.08397
[26]	validation_0-mae:4323.11538
[27]	validation_0-mae:4226.39137
[28]	validation_0-mae:4136.29570
[29]	validation_0-mae:4055.87615
[30]	validation_0-mae:3963.86436
[31]	validation_0-mae:3866.12726
[32]	validation_0-mae:3790.77984
[33]	validation_0-mae:3723.34665
[34]	validation_0-mae:3648.17215
[35]	validation_0-mae:3590.08080
[36]	validation_0-mae:3532.65839

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[37]	validation_0-mae:3471.52643
[38]	validation_0-mae:3412.76883
[39]	validation_0-mae:3360.82473
[40]	validation_0-mae:3308.33241
[41]	validation_0-mae:3262.21246
[42]	validation_0-mae:3220.79578
[43]	validation_0-mae:3178.12776
[44]	validation_0-mae:3144.46378
[45]	validation_0-mae:3112.19801
[46]	validation_0-mae:3063.89181
[47]	validation_0-mae:3036.42694
[48]	validation_0-mae:3007.99623
[49]	validation_0-mae:2974.71576
[50]	validation_0-mae:2945.12484
[51]	validation_0-mae:2925.09127
[52]	validation_0-mae:2901.20092
[53]	validation_0-mae:2877.58212
[54]	validation_0-mae:2861.41588
[55]	validation_0-mae:2835.35561
[56]	validation_0-mae:2815.44779
[57]	validation_0-mae:2799.83716
[58]	validation_0-mae:2785.93422
[59]	validation_0-mae:2767.51610
[60]	validation_0-mae:2753.37036
[61]	validation_0-mae:2740.19906
[62]	validation_0-mae:2721.14739
[63]	validation_0-mae:2706.67097
[64]	validation_0-mae:2687.33695
[65]	validation_0-mae:2678.15192
[66]	validation_0-mae:2661.60121
[67]	validation_0-mae:2653.61727
[68]	validation_0-mae:2642.47842
[0]	validation_0-mae:12361.74879
[1]	validation_0-mae:11554.38861
[2]	validation_0-mae:10842.81642
[3]	validation_0-mae:10199.13880
[4]	validation_0-mae:9612.55225
[5]	validation_0-mae:9120.13294
[6]	validation_0-mae:8665.51212
[7]	validation_0-mae:8255.22922
[8]	validation_0-mae:7879.07702
[9]	validation_0-mae:7519.49661
[10]	validation_0-mae:7208.71705
[11]	validation_0-mae:6901.43003
[12]	validation_0-mae:6612.79384
[13]	validation_0-mae:6361.55021
[14]	validation_0-mae:6129.27252
[15]	validation_0-mae:5896.56849
[16]	validation_0-mae:5684.56044
[17]	validation_0-mae:5506.58767
[18]	validation_0-mae:5315.52158
[19]	validation_0-mae:5150.30452
[20]	validation_0-mae:4981.80590
[21]	validation_0-mae:4838.07164
[22]	validation_0-mae:4681.19704
[23]	validation_0-mae:4542.35984
[24]	validation_0-mae:4424.69563
[25]	validation_0-mae:4313.82271
[26]	validation_0-mae:4201.27211
[27]	validation_0-mae:4104.68210
[28]	validation_0-mae:4014.70642
[29]	validation_0-mae:3915.22833
[30]	validation_0-mae:3832.48658
[31]	validation_0-mae:3751.38667
[32]	validation_0-mae:3676.01297
[33]	validation_0-mae:3608.80807
[34]	validation_0-mae:3540.88238
[35]	validation_0-mae:3487.02062

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[36]	validation_0-mae:3430.93446
[37]	validation_0-mae:3366.98824
[38]	validation_0-mae:3318.23553
[39]	validation_0-mae:3274.69149
[40]	validation_0-mae:3232.35220
[41]	validation_0-mae:3185.25618
[42]	validation_0-mae:3150.16634
[43]	validation_0-mae:3112.87796
[44]	validation_0-mae:3081.24549
[45]	validation_0-mae:3047.61774
[46]	validation_0-mae:3022.76741
[47]	validation_0-mae:2989.74343
[48]	validation_0-mae:2962.07564
[49]	validation_0-mae:2927.62200
[50]	validation_0-mae:2904.12307
[51]	validation_0-mae:2870.20730
[52]	validation_0-mae:2849.57541
[53]	validation_0-mae:2831.74966
[54]	validation_0-mae:2814.89089
[55]	validation_0-mae:2792.47630
[56]	validation_0-mae:2776.89480
[57]	validation_0-mae:2748.08143
[58]	validation_0-mae:2737.48396
[59]	validation_0-mae:2731.34099
[60]	validation_0-mae:2710.17521
[61]	validation_0-mae:2695.46424
[62]	validation_0-mae:2683.72686
[63]	validation_0-mae:2670.32211
[64]	validation_0-mae:2655.39565
[65]	validation_0-mae:2638.03058
[66]	validation_0-mae:2628.58488
[67]	validation_0-mae:2612.53537
[68]	validation_0-mae:2600.56497
[69]	validation_0-mae:2587.12252
[70]	validation_0-mae:2580.64869
[71]	validation_0-mae:2573.28215
[72]	validation_0-mae:2551.09085
[73]	validation_0-mae:2545.41598
[74]	validation_0-mae:2533.70987
[75]	validation_0-mae:2518.08023
[76]	validation_0-mae:2510.61140
[77]	validation_0-mae:2495.75480
[78]	validation_0-mae:2489.26781
[79]	validation_0-mae:2477.67322
[80]	validation_0-mae:2469.94593
[81]	validation_0-mae:2462.71155
[82]	validation_0-mae:2449.24536
[83]	validation_0-mae:2442.85744
[84]	validation_0-mae:2435.68957
[85]	validation_0-mae:2428.95333
[86]	validation_0-mae:2426.27282
[87]	validation_0-mae:2418.03674
[88]	validation_0-mae:2411.96023
[89]	validation_0-mae:2404.28646
[90]	validation_0-mae:2395.46182
[91]	validation_0-mae:2390.67800
[92]	validation_0-mae:2387.18588
[93]	validation_0-mae:2382.17958
[94]	validation_0-mae:2381.42752
[95]	validation_0-mae:2377.33154
[96]	validation_0-mae:2372.15998
[97]	validation_0-mae:2367.01224
[98]	validation_0-mae:2362.98541
[99]	validation_0-mae:2360.71779
[100]	validation_0-mae:2352.48069
[101]	validation_0-mae:2345.44139
[102]	validation_0-mae:2343.76226
[103]	validation_0-mae:2337.03197
[104]	validation_0-mae:2332.25741
[105]	validation_0-mae:2328.64769
[106]	validation_0-mae:2324.38726
[107]	validation_0-mae:2322.19351
[108]	validation_0-mae:2313.89114
[109]	validation_0-mae:2311.83803
[110]	validation_0-mae:2305.72066
[111]	validation_0-mae:2301.55126
[112]	validation_0-mae:2296.42550
[113]	validation_0-mae:2291.09585
[114]	validation_0-mae:2284.95463
[115]	validation_0-mae:2281.71657
[116]	validation_0-mae:2280.05771
[117]	validation_0-mae:2277.43223
[118]	validation_0-mae:2273.37241
[119]	validation_0-mae:2272.33329
[120]	validation_0-mae:2267.82166
[121]	validation_0-mae:2263.40422
[122]	validation_0-mae:2259.43324
[123]	validation_0-mae:2256.79738
[124]	validation_0-mae:2252.43617
[125]	validation_0-mae:2249.80300
[126]	validation_0-mae:2248.56276
[127]	validation_0-mae:2247.81477
[128]	validation_0-mae:2247.45317
[129]	validation_0-mae:2245.21973
[130]	validation_0-mae:2245.15241
[131]	validation_0-mae:2241.64770
[132]	validation_0-mae:2240.48428
[133]	validation_0-mae:2238.88657
[134]	validation_0-mae:2234.64964
[135]	validation_0-mae:2233.87365
[136]	validation_0-mae:2233.89818
[137]	validation_0-mae:2232.24248
[138]	validation_0-mae:2232.30728
[139]	validation_0-mae:2231.73138
[140]	validation_0-mae:2227.74896
[141]	validation_0-mae:2227.19428
[142]	validation_0-mae:2225.37171
[143]	validation_0-mae:2222.99069
[144]	validation_0-mae:2221.64441
[145]	validation_0-mae:2219.45668
[146]	validation_0-mae:2216.02526
[147]	validation_0-mae:2215.48484
[148]	validation_0-mae:2214.85352
[149]	validation_0-mae:2213.13208
[150]	validation_0-mae:2209.94426
[151]	validation_0-mae:2206.63268
[152]	validation_0-mae:2207.56836
[153]	validation_0-mae:2205.27208
[154]	validation_0-mae:2204.59897
[155]	validation_0-mae:2201.97711
[156]	validation_0-mae:2201.13329
[157]	validation_0-mae:2201.45127
[158]	validation_0-mae:2201.56974
[159]	validation_0-mae:2198.20852
[160]	validation_0-mae:2195.48996
[161]	validation_0-mae:2196.17062
[162]	validation_0-mae:2194.64144
[163]	validation_0-mae:2194.47741
[164]	validation_0-mae:2193.32946
[165]	validation_0-mae:2190.65558
[166]	validation_0-mae:2188.26950
[167]	validation_0-mae:2186.82481
[168]	validation_0-mae:2184.88237
[169]	validation_0-mae:2183.08317
[170]	validation_0-mae:2180.91572
[171]	validation_0-mae:2181.06308
[172]	validation_0-mae:2177.60990
[173]	validation_0-mae:2176.15110
[174]	validation_0-mae:2174.66344
[175]	validation_0-mae:2175.12451
[176]	validation_0-mae:2173.41267
[177]	validation_0-mae:2172.20936
[178]	validation_0-mae:2171.08876
[179]	validation_0-mae:2170.36062
[180]	validation_0-mae:2169.47410
[181]	validation_0-mae:2168.19986
[182]	validation_0-mae:2168.09205
[183]	validation_0-mae:2167.36163
[184]	validation_0-mae:2165.83223
[185]	validation_0-mae:2164.31084
[186]	validation_0-mae:2164.32633
[187]	validation_0-mae:2162.09502
[188]	validation_0-mae:2160.75813
[189]	validation_0-mae:2160.54269
[190]	validation_0-mae:2159.92213
[191]	validation_0-mae:2159.63298
[192]	validation_0-mae:2157.80354
[193]	validation_0-mae:2158.20271
[194]	validation_0-mae:2158.54777
[195]	validation_0-mae:2155.69202
[196]	validation_0-mae:2154.77616
[197]	validation_0-mae:2154.48815
[198]	validation_0-mae:2154.24086
[199]	validation_0-mae:2153.11675
[200]	validation_0-mae:2152.95441
[201]	validation_0-mae:2152.69871
[202]	validation_0-mae:2151.63320
[203]	validation_0-mae:2148.38751
[204]	validation_0-mae:2146.52630
[205]	validation_0-mae:2145.93390
[206]	validation_0-mae:2146.36771
[207]	validation_0-mae:2145.24134
[208]	validation_0-mae:2144.18800
[209]	validation_0-mae:2144.25185
[210]	validation_0-mae:2142.62909
[211]	validation_0-mae:2142.48828
[212]	validation_0-mae:2141.09798
[213]	validation_0-mae:2140.97268
[214]	validation_0-mae:2141.14372
[215]	validation_0-mae:2140.20151
[216]	validation_0-mae:2139.27893
[217]	validation_0-mae:2137.72807
[218]	validation_0-mae:2138.12038
[219]	validation_0-mae:2136.75463
[220]	validation_0-mae:2135.93811
[221]	validation_0-mae:2135.77930
[222]	validation_0-mae:2134.58776
[223]	validation_0-mae:2134.60733
[224]	validation_0-mae:2134.37371
[225]	validation_0-mae:2133.91228
[226]	validation_0-mae:2134.70170
[227]	validation_0-mae:2134.54254
[228]	validation_0-mae:2133.77279
[229]	validation_0-mae:2134.84717
[230]	validation_0-mae:2134.84148
[231]	validation_0-mae:2132.60331
[232]	validation_0-mae:2133.21991
[233]	validation_0-mae:2133.15346
[234]	validation_0-mae:2132.78510
[235]	validation_0-mae:2133.41951
[236]	validation_0-mae:2133.19270
[237]	validation_0-mae:2133.12562
[238]	validation_0-mae:2133.57118
[239]	validation_0-mae:2132.78017
[240]	validation_0-mae:2132.73061
[241]	validation_0-mae:2131.99005
[242]	validation_0-mae:2130.79145
[243]	validation_0-mae:2130.58076
[244]	validation_0-mae:2129.60673
[245]	validation_0-mae:2129.58349
[246]	validation_0-mae:2127.59048
[247]	validation_0-mae:2128.05339
[248]	validation_0-mae:2127.98138
[249]	validation_0-mae:2127.72381
[250]	validation_0-mae:2128.13244
[251]	validation_0-mae:2127.59328
[252]	validation_0-mae:2126.91028
[253]	validation_0-mae:2126.16720
[254]	validation_0-mae:2125.26024
[255]	validation_0-mae:2125.40594
[256]	validation_0-mae:2124.21077
[257]	validation_0-mae:2123.95454
[258]	validation_0-mae:2123.79216
[259]	validation_0-mae:2124.77174
[260]	validation_0-mae:2125.28720
[261]	validation_0-mae:2124.92555
[262]	validation_0-mae:2124.83274
[263]	validation_0-mae:2125.43349
[264]	validation_0-mae:2122.19914
[265]	validation_0-mae:2121.21123
[266]	validation_0-mae:2121.02170
[267]	validation_0-mae:2121.43721
[268]	validation_0-mae:2120.81796
[269]	validation_0-mae:2120.60072
[270]	validation_0-mae:2120.16820
[271]	validation_0-mae:2120.30607
[272]	validation_0-mae:2120.20224
[273]	validation_0-mae:2121.21819
[274]	validation_0-mae:2121.57492
[275]	validation_0-mae:2122.31282
[276]	validation_0-mae:2121.33707
[277]	validation_0-mae:2121.23217
[278]	validation_0-mae:2121.20766
[279]	validation_0-mae:2120.42057
[280]	validation_0-mae:2120.33476
[281]	validation_0-mae:2118.60741
[282]	validation_0-mae:2118.85010
[283]	validation_0-mae:2117.60319
[284]	validation_0-mae:2115.72518
[285]	validation_0-mae:2114.86958
[286]	validation_0-mae:2113.61829
[287]	validation_0-mae:2111.91828
[288]	validation_0-mae:2111.26499
[289]	validation_0-mae:2111.20037
[290]	validation_0-mae:2110.85752
[291]	validation_0-mae:2111.58855
[292]	validation_0-mae:2111.87196
[293]	validation_0-mae:2111.33167
[294]	validation_0-mae:2111.21124
[295]	validation_0-mae:2110.93932
[296]	validation_0-mae:2109.23649
[297]	validation_0-mae:2110.05977
[298]	validation_0-mae:2110.53012
[299]	validation_0-mae:2109.58071
[300]	validation_0-mae:2107.84529
[301]	validation_0-mae:2107.75051
[302]	validation_0-mae:2107.91283
[303]	validation_0-mae:2106.44374
[304]	validation_0-mae:2106.36477
[305]	validation_0-mae:2106.49189
[306]	validation_0-mae:2106.13545
[307]	validation_0-mae:2105.40487
[308]	validation_0-mae:2104.41882
[309]	validation_0-mae:2104.24300
[310]	validation_0-mae:2102.39767
[311]	validation_0-mae:2102.41575
[312]	validation_0-mae:2101.49364
[313]	validation_0-mae:2100.88169
[314]	validation_0-mae:2101.49165
[315]	validation_0-mae:2101.36297
[316]	validation_0-mae:2100.54099
[317]	validation_0-mae:2099.32559
[318]	validation_0-mae:2099.23786
[319]	validation_0-mae:2099.98934
[320]	validation_0-mae:2100.37434
[321]	validation_0-mae:2098.00156
[322]	validation_0-mae:2098.19280
[323]	validation_0-mae:2098.49850
[324]	validation_0-mae:2099.08388
[325]	validation_0-mae:2098.65784
[326]	validation_0-mae:2098.92651
[327]	validation_0-mae:2098.89075
[328]	validation_0-mae:2098.76847
[329]	validation_0-mae:2099.10421
[330]	validation_0-mae:2097.79510
[331]	validation_0-mae:2096.56680
[332]	validation_0-mae:2097.16143
[333]	validation_0-mae:2096.26869
[334]	validation_0-mae:2095.95102
[335]	validation_0-mae:2094.41358
[336]	validation_0-mae:2094.17680
[337]	validation_0-mae:2094.52160
[338]	validation_0-mae:2094.10331
[339]	validation_0-mae:2094.77774
[340]	validation_0-mae:2093.81640
[341]	validation_0-mae:2092.94869
[342]	validation_0-mae:2091.69542
[343]	validation_0-mae:2092.98440
[344]	validation_0-mae:2093.18851
[345]	validation_0-mae:2093.67449
[346]	validation_0-mae:2093.48385
[347]	validation_0-mae:2093.05600
[348]	validation_0-mae:2092.22999
[349]	validation_0-mae:2092.06428
[350]	validation_0-mae:2090.24999
[351]	validation_0-mae:2087.46715
[352]	validation_0-mae:2086.61511
[353]	validation_0-mae:2086.29839
[354]	validation_0-mae:2086.32983
[355]	validation_0-mae:2085.49091
[356]	validation_0-mae:2085.69580
[357]	validation_0-mae:2085.56767
[358]	validation_0-mae:2085.74849
[359]	validation_0-mae:2085.84731
[360]	validation_0-mae:2085.69670
[361]	validation_0-mae:2085.98089
[362]	validation_0-mae:2086.04812
[363]	validation_0-mae:2085.59864
[364]	validation_0-mae:2085.39939
[365]	validation_0-mae:2085.21016
[366]	validation_0-mae:2085.03423
[367]	validation_0-mae:2085.57992
[368]	validation_0-mae:2084.68091
[369]	validation_0-mae:2084.70882
[370]	validation_0-mae:2085.18369
[371]	validation_0-mae:2084.53368
[372]	validation_0-mae:2084.38845
[373]	validation_0-mae:2083.88398
[374]	validation_0-mae:2084.22845
[375]	validation_0-mae:2084.18179
[376]	validation_0-mae:2083.63154
[377]	validation_0-mae:2083.77977
[378]	validation_0-mae:2083.21431
[379]	validation_0-mae:2083.11560
[380]	validation_0-mae:2082.84351
[381]	validation_0-mae:2082.88214
[382]	validation_0-mae:2083.31467
[383]	validation_0-mae:2083.56599
[384]	validation_0-mae:2084.20564
[385]	validation_0-mae:2084.27572
[386]	validation_0-mae:2084.59162
[387]	validation_0-mae:2084.09830
[388]	validation_0-mae:2084.11103
[389]	validation_0-mae:2084.57625
[390]	validation_0-mae:2084.64278
[391]	validation_0-mae:2084.21216
[392]	validation_0-mae:2083.80452
[393]	validation_0-mae:2084.36189
[394]	validation_0-mae:2083.55116
[395]	validation_0-mae:2082.72139
[396]	validation_0-mae:2083.12968
[397]	validation_0-mae:2083.36822
[398]	validation_0-mae:2082.56875
[399]	validation_0-mae:2082.93553
[400]	validation_0-mae:2082.86570
[401]	validation_0-mae:2082.83816
[402]	validation_0-mae:2082.69104
[403]	validation_0-mae:2082.83980
[404]	validation_0-mae:2082.89605
[405]	validation_0-mae:2083.64565
[406]	validation_0-mae:2083.18143
[407]	validation_0-mae:2083.57617
[408]	validation_0-mae:2083.35084
[409]	validation_0-mae:2083.06246
[410]	validation_0-mae:2083.19122
[411]	validation_0-mae:2082.89379
[412]	validation_0-mae:2082.70886
[413]	validation_0-mae:2082.92403
[414]	validation_0-mae:2082.53243
[415]	validation_0-mae:2082.59389
[416]	validation_0-mae:2082.37152
[417]	validation_0-mae:2082.62534
[418]	validation_0-mae:2082.62071
[419]	validation_0-mae:2081.72230
[420]	validation_0-mae:2080.33384
[421]	validation_0-mae:2080.72616
[422]	validation_0-mae:2080.89503
[423]	validation_0-mae:2080.63913
[424]	validation_0-mae:2080.25256
[425]	validation_0-mae:2080.44066
[426]	validation_0-mae:2080.30626
[427]	validation_0-mae:2080.42775
[428]	validation_0-mae:2080.70168
[429]	validation_0-mae:2080.50787
[430]	validation_0-mae:2080.62171
[431]	validation_0-mae:2081.15687
[432]	validation_0-mae:2081.69433
[433]	validation_0-mae:2081.90570
[434]	validation_0-mae:2082.15188
[435]	validation_0-mae:2082.28417
[436]	validation_0-mae:2082.76783
[437]	validation_0-mae:2082.78938
[438]	validation_0-mae:2082.58106
[439]	validation_0-mae:2082.34586
[440]	validation_0-mae:2082.06698
[441]	validation_0-mae:2082.63184
[442]	validation_0-mae:2082.52462
[443]	validation_0-mae:2081.98081
[444]	validation_0-mae:2082.01095
[445]	validation_0-mae:2082.14805
[446]	validation_0-mae:2082.50550
[447]	validation_0-mae:2082.87327
[448]	validation_0-mae:2083.14348
[449]	validation_0-mae:2083.03499
[450]	validation_0-mae:2083.01982
[451]	validation_0-mae:2083.00244
[452]	validation_0-mae:2082.61653
[453]	validation_0-mae:2082.85207
[454]	validation_0-mae:2083.21011
[455]	validation_0-mae:2083.55187
[456]	validation_0-mae:2083.99203
[457]	validation_0-mae:2083.88270
[458]	validation_0-mae:2083.79916
[459]	validation_0-mae:2084.16871
[460]	validation_0-mae:2084.30056
[461]	validation_0-mae:2084.20987
[462]	validation_0-mae:2083.43978
[463]	validation_0-mae:2082.82511
[464]	validation_0-mae:2082.39405
[465]	validation_0-mae:2082.47061
[466]	validation_0-mae:2082.20889
[467]	validation_0-mae:2081.32348
[468]	validation_0-mae:2080.91672
[469]	validation_0-mae:2080.95603
[470]	validation_0-mae:2080.67372
[471]	validation_0-mae:2080.68965
[472]	validation_0-mae:2080.76512
[473]	validation_0-mae:2079.90415
[474]	validation_0-mae:2079.50318
[475]	validation_0-mae:2079.36173
[476]	validation_0-mae:2078.70296
[477]	validation_0-mae:2078.09232
[478]	validation_0-mae:2078.18556
[479]	validation_0-mae:2077.71701
[480]	validation_0-mae:2077.96062
[481]	validation_0-mae:2077.38083
[482]	validation_0-mae:2077.25994
[483]	validation_0-mae:2077.22233
[484]	validation_0-mae:2077.25144
[485]	validation_0-mae:2077.30471
[486]	validation_0-mae:2077.14896
[487]	validation_0-mae:2076.78950
[488]	validation_0-mae:2076.69941
[489]	validation_0-mae:2076.77890
[490]	validation_0-mae:2077.19456
[491]	validation_0-mae:2077.36923
[492]	validation_0-mae:2077.52448
[493]	validation_0-mae:2077.13914
[494]	validation_0-mae:2077.04792
[495]	validation_0-mae:2077.36204
[496]	validation_0-mae:2077.74358
[497]	validation_0-mae:2077.75010
[498]	validation_0-mae:2077.39194
[499]	validation_0-mae:2077.57908
[500]	validation_0-mae:2077.72084
[501]	validation_0-mae:2077.87455
[502]	validation_0-mae:2077.55048
[503]	validation_0-mae:2077.21829
[504]	validation_0-mae:2077.43568
[505]	validation_0-mae:2077.55787
[506]	validation_0-mae:2077.53005
[507]	validation_0-mae:2077.53605
[508]	validation_0-mae:2077.05653
[509]	validation_0-mae:2077.01252
[510]	validation_0-mae:2076.68128
[511]	validation_0-mae:2076.97467
[512]	validation_0-mae:2076.27388
[513]	validation_0-mae:2075.54968
[514]	validation_0-mae:2075.36936
[515]	validation_0-mae:2075.49286
[516]	validation_0-mae:2074.97942
[517]	validation_0-mae:2074.89002
[518]	validation_0-mae:2074.70508
[519]	validation_0-mae:2074.14147
[520]	validation_0-mae:2074.04735
[521]	validation_0-mae:2073.65998
[522]	validation_0-mae:2073.74091
[523]	validation_0-mae:2073.79049
[524]	validation_0-mae:2073.96625
[525]	validation_0-mae:2074.20487
[526]	validation_0-mae:2074.52540
[527]	validation_0-mae:2074.46569
[528]	validation_0-mae:2074.09044
[529]	validation_0-mae:2074.37362
[530]	validation_0-mae:2074.20762
[531]	validation_0-mae:2074.16093
[532]	validation_0-mae:2074.17653
[533]	validation_0-mae:2074.53152
[534]	validation_0-mae:2074.76911
[535]	validation_0-mae:2075.74451
[536]	validation_0-mae:2075.86213
[537]	validation_0-mae:2075.69426
[538]	validation_0-mae:2075.52871
[539]	validation_0-mae:2075.70432
[540]	validation_0-mae:2075.74216
[541]	validation_0-mae:2075.41130
[542]	validation_0-mae:2075.54422
[543]	validation_0-mae:2075.66164
[544]	validation_0-mae:2075.35883
[545]	validation_0-mae:2075.48862
[546]	validation_0-mae:2075.99056
[547]	validation_0-mae:2075.10487
[548]	validation_0-mae:2074.96706
[549]	validation_0-mae:2075.09159
[550]	validation_0-mae:2075.07609
[551]	validation_0-mae:2075.32001
[552]	validation_0-mae:2075.23563
[553]	validation_0-mae:2075.39875
[554]	validation_0-mae:2075.39859
[555]	validation_0-mae:2075.33582
[556]	validation_0-mae:2075.18220
[557]	validation_0-mae:2075.23292
[558]	validation_0-mae:2075.29167
[559]	validation_0-mae:2074.71880
[560]	validation_0-mae:2074.94768
[561]	validation_0-mae:2074.77736
[562]	validation_0-mae:2074.61521
[563]	validation_0-mae:2074.63904
[564]	validation_0-mae:2074.72334
[565]	validation_0-mae:2074.37987
[566]	validation_0-mae:2074.37936
[567]	validation_0-mae:2074.52862
[568]	validation_0-mae:2074.57413
[569]	validation_0-mae:2074.34613
[570]	validation_0-mae:2074.61354
[571]	validation_0-mae:2074.68832
[572]	validation_0-mae:2074.73311
[573]	validation_0-mae:2074.55255
[574]	validation_0-mae:2075.01882
[575]	validation_0-mae:2074.93051
[576]	validation_0-mae:2075.12941
[577]	validation_0-mae:2074.96741
[578]	validation_0-mae:2074.89930
[579]	validation_0-mae:2074.72920
[580]	validation_0-mae:2074.82822
[581]	validation_0-mae:2074.96197
[582]	validation_0-mae:2075.13327
[583]	validation_0-mae:2074.87232
[584]	validation_0-mae:2074.60280
[585]	validation_0-mae:2074.69900
[586]	validation_0-mae:2074.86199
[587]	validation_0-mae:2074.86831
[588]	validation_0-mae:2075.07888
[589]	validation_0-mae:2074.67431
[590]	validation_0-mae:2074.14277
[591]	validation_0-mae:2074.00157
[592]	validation_0-mae:2073.85081
[593]	validation_0-mae:2073.89327
[594]	validation_0-mae:2073.81278
[595]	validation_0-mae:2073.78270
[596]	validation_0-mae:2073.88471
[597]	validation_0-mae:2073.89319
[598]	validation_0-mae:2073.75849
[599]	validation_0-mae:2073.81280
[600]	validation_0-mae:2074.05485
[601]	validation_0-mae:2073.69366
[602]	validation_0-mae:2074.03995
[603]	validation_0-mae:2073.95872
[604]	validation_0-mae:2073.83082
[605]	validation_0-mae:2073.78147
[606]	validation_0-mae:2074.10182
[607]	validation_0-mae:2074.18520
[608]	validation_0-mae:2074.27855
[609]	validation_0-mae:2074.47892
[610]	validation_0-mae:2074.45576
[611]	validation_0-mae:2074.43881
[612]	validation_0-mae:2074.36613
[613]	validation_0-mae:2074.58568
[614]	validation_0-mae:2074.71614
[615]	validation_0-mae:2075.18264
[616]	validation_0-mae:2075.56043
[617]	validation_0-mae:2075.59193
[618]	validation_0-mae:2075.62722
[619]	validation_0-mae:2075.52533
[620]	validation_0-mae:2074.98979
[621]	validation_0-mae:2075.17905
[622]	validation_0-mae:2074.71437
[623]	validation_0-mae:2074.83072
[624]	validation_0-mae:2074.91827
[625]	validation_0-mae:2074.75047

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[40]	validation_0-mae:3221.00262
[41]	validation_0-mae:3184.41235
[42]	validation_0-mae:3150.47814
[43]	validation_0-mae:3112.62770
[44]	validation_0-mae:3082.67410
[45]	validation_0-mae:3053.36094
[46]	validation_0-mae:3018.87822
[47]	validation_0-mae:2993.45656
[48]	validation_0-mae:2970.60261
[49]	validation_0-mae:2929.67513
[50]	validation_0-mae:2906.94762
[51]	validation_0-mae:2879.99114
[52]	validation_0-mae:2860.68155
[53]	validation_0-mae:2840.44910
[54]	validation_0-mae:2825.36450
[55]	validation_0-mae:2805.50918
[56]	validation_0-mae:2778.92100
[57]	validation_0-mae:2765.38710
[58]	validation_0-mae:2747.22280
[59]	validation_0-mae:2732.70064
[60]	validation_0-mae:2713.48955
[61]	validation_0-mae:2690.24043
[62]	validation_0-mae:2677.95891
[63]	validation_0-mae:2670.04346
[64]	validation_0-mae:2655.75759
[65]	validation_0-mae:2646.64981
[66]	validation_0-mae:2624.60573
[67]	validation_0-mae:2612.85707
[68]	validation_0-mae:2601.28388
[69]	validation_0-mae:2591.29375
[70]	validation_0-mae:2577.68008
[71]	validation_0-mae:2566.31642
[72]	validation_0-mae:2550.39539
[73]	validation_0-mae:2544.88542
[74]	validation_0-mae:2535.43593
[75]	validation_0-mae:2530.60039
[76]	validation_0-mae:2517.60816
[77]	validation_0-mae:2508.59358
[78]	validation_0-mae:2500.07814
[79]	validation_0-mae:2492.33200
[80]	validation_0-mae:2484.62602
[81]	validation_0-mae:2480.56367
[82]	validation_0-mae:2469.35010
[83]	validation_0-mae:2461.90109
[84]	validation_0-mae:2456.24003
[85]	validation_0-mae:2448.56256
[86]	validation_0-mae:2442.08651
[87]	validation_0-mae:2435.00773
[88]	validation_0-mae:2428.83538
[89]	validation_0-mae:2416.93369
[90]	validation_0-mae:2413.87371
[91]	validation_0-mae:2409.16430
[92]	validation_0-mae:2402.66908
[93]	validation_0-mae:2395.27445
[94]	validation_0-mae:2389.79066
[95]	validation_0-mae:2384.65272
[96]	validation_0-mae:2379.49500
[97]	validation_0-mae:2378.09114
[98]	validation_0-mae:2373.67758
[99]	validation_0-mae:2368.41040
[100]	validation_0-mae:2360.60472
[101]	validation_0-mae:2355.88753
[102]	validation_0-mae:2353.69282
[103]	validation_0-mae:2349.88555
[104]	validation_0-mae:2345.63726
[105]	validation_0-mae:2337.65818
[106]	validation_0-mae:2332.12639
[107]	validation_0-mae:2327.57786
[108]	validation_0-mae:2324.71658
[109]	validation_0-mae:2319.40065
[110]	validation_0-mae:2311.22734
[111]	validation_0-mae:2310.61720
[112]	validation_0-mae:2306.18996
[113]	validation_0-mae:2301.67592
[114]	validation_0-mae:2299.01265
[115]	validation_0-mae:2295.51956
[116]	validation_0-mae:2294.51443
[117]	validation_0-mae:2288.06982
[118]	validation_0-mae:2285.67587
[119]	validation_0-mae:2284.07169
[120]	validation_0-mae:2281.85404
[121]	validation_0-mae:2278.31747
[122]	validation_0-mae:2275.75837
[123]	validation_0-mae:2272.49590
[124]	validation_0-mae:2272.00483
[125]	validation_0-mae:2268.73275
[126]	validation_0-mae:2266.55046
[127]	validation_0-mae:2265.28561
[128]	validation_0-mae:2264.90755
[129]	validation_0-mae:2263.67868
[130]	validation_0-mae:2263.21469
[131]	validation_0-mae:2262.93451
[132]	validation_0-mae:2260.23487
[133]	validation_0-mae:2257.93080
[134]	validation_0-mae:2257.15429
[135]	validation_0-mae:2255.83207
[136]	validation_0-mae:2253.12184
[137]	validation_0-mae:2251.40359
[138]	validation_0-mae:2250.43279
[139]	validation_0-mae:2247.04971
[140]	validation_0-mae:2244.74108
[141]	validation_0-mae:2240.99787
[142]	validation_0-mae:2240.82640
[143]	validation_0-mae:2238.49611
[144]	validation_0-mae:2239.56621
[145]	validation_0-mae:2236.61012
[146]	validation_0-mae:2237.39445
[147]	validation_0-mae:2236.81941
[148]	validation_0-mae:2234.40562
[149]	validation_0-mae:2229.48708
[150]	validation_0-mae:2226.92474
[151]	validation_0-mae:2225.02741
[152]	validation_0-mae:2225.27436
[153]	validation_0-mae:2222.45547
[154]	validation_0-mae:2220.95590
[155]	validation_0-mae:2221.40468
[156]	validation_0-mae:2220.06030
[157]	validation_0-mae:2218.64823
[158]	validation_0-mae:2217.11688
[159]	validation_0-mae:2217.24561
[160]	validation_0-mae:2215.28280
[161]	validation_0-mae:2214.09945
[162]	validation_0-mae:2214.10989
[163]	validation_0-mae:2212.65593
[164]	validation_0-mae:2212.62314
[165]	validation_0-mae:2213.40067
[166]	validation_0-mae:2211.36436
[167]	validation_0-mae:2209.99280
[168]	validation_0-mae:2207.73345
[169]	validation_0-mae:2207.75886
[170]	validation_0-mae:2205.50643
[171]	validation_0-mae:2204.63645
[172]	validation_0-mae:2204.20997
[173]	validation_0-mae:2201.94107
[174]	validation_0-mae:2200.95923
[175]	validation_0-mae:2199.81233
[176]	validation_0-mae:2198.81563
[177]	validation_0-mae:2197.60625
[178]	validation_0-mae:2196.94232
[179]	validation_0-mae:2197.01610
[180]	validation_0-mae:2197.00869
[181]	validation_0-mae:2196.21188
[182]	validation_0-mae:2194.17463
[183]	validation_0-mae:2194.48685
[184]	validation_0-mae:2193.88413
[185]	validation_0-mae:2193.11573
[186]	validation_0-mae:2192.52323
[187]	validation_0-mae:2192.32322
[188]	validation_0-mae:2191.80526
[189]	validation_0-mae:2189.86404
[190]	validation_0-mae:2190.68432
[191]	validation_0-mae:2190.06127
[192]	validation_0-mae:2188.96911
[193]	validation_0-mae:2188.99577
[0]	validation_0-mae:12454.97082
[1]	validation_0-mae:11723.39166
[2]	validation_0-mae:11084.54255
[3]	validation_0-mae:10482.69984
[4]	validation_0-mae:9965.06495
[5]	validation_0-mae:9486.90492
[6]	validation_0-mae:9058.83955
[7]	validation_0-mae:8657.54497
[8]	validation_0-mae:8304.58140
[9]	validation_0-mae:7978.88040
[10]	validation_0-mae:7670.12929
[0]	validation_0-mae:12565.95070

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[1]	validation_0-mae:11943.56940
[2]	validation_0-mae:11392.29486
[3]	validation_0-mae:10944.74667
[4]	validation_0-mae:10547.05550
[5]	validation_0-mae:10207.92505
[6]	validation_0-mae:9908.77851
[7]	validation_0-mae:9659.10102
[8]	validation_0-mae:9438.61118
[9]	validation_0-mae:9241.52135
[0]	validation_0-mae:12469.55953
[1]	validation_0-mae:11754.31877
[2]	validation_0-mae:11107.38937
[3]	validation_0-mae:10506.04762
[4]	validation_0-mae:9974.11835
[5]	validation_0-mae:9476.29221
[6]	validation_0-mae:9036.19712
[7]	validation_0-mae:8626.90769
[8]	validation_0-mae:8263.81962
[9]	validation_0-mae:7910.07495
[0]	validation_0-mae:12374.94785

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[1]	validation_0-mae:11583.60250
[2]	validation_0-mae:10881.88827
[3]	validation_0-mae:10249.42009
[4]	validation_0-mae:9688.90043
[5]	validation_0-mae:9159.18795
[6]	validation_0-mae:8709.11881
[7]	validation_0-mae:8307.50601
[8]	validation_0-mae:7934.98810
[9]	validation_0-mae:7577.24942
[10]	validation_0-mae:7257.47183
[11]	validation_0-mae:6964.91204
[12]	validation_0-mae:6685.24740
[13]	validation_0-mae:6424.01270
[14]	validation_0-mae:6161.95591
[15]	validation_0-mae:5923.89942
[16]	validation_0-mae:5726.21159
[17]	validation_0-mae:5504.99106
[18]	validation_0-mae:5332.24144
[19]	validation_0-mae:5160.50312
[20]	validation_0-mae:4988.62057
[21]	validation_0-mae:4830.79681
[22]	validation_0-mae:4698.56472
[23]	validation_0-mae:4556.35968
[24]	validation_0-mae:4425.62916
[25]	validation_0-mae:4295.96858
[26]	validation_0-mae:4185.72412
[27]	validation_0-mae:4093.18455
[28]	validation_0-mae:4018.68398
[29]	validation_0-mae:3921.19557
[30]	validation_0-mae:3832.86474
[31]	validation_0-mae:3771.29430
[32]	validation_0-mae:3696.13079
[33]	validation_0-mae:3616.22587
[34]	validation_0-mae:3554.70205
[35]	validation_0-mae:3489.50474
[36]	validation_0-mae:3451.38374
[37]	validation_0-mae:3405.70960
[38]	validation_0-mae:3353.12432
[39]	validation_0-mae:3301.18349
[40]	validation_0-mae:3269.03809
[41]	validation_0-mae:3229.47880
[42]	validation_0-mae:3189.94092
[43]	validation_0-mae:3157.07711
[44]	validation_0-mae:3116.40050
[45]	validation_0-mae:3088.50080
[46]	validation_0-mae:3060.24808
[47]	validation_0-mae:3016.51975
[48]	validation_0-mae:2993.11228
[49]	validation_0-mae:2974.14990
[50]	validation_0-mae:2938.23774
[51]	validation_0-mae:2919.10888
[52]	validation_0-mae:2900.26211
[53]	validation_0-mae:2873.39915
[54]	validation_0-mae:2857.75250
[55]	validation_0-mae:2840.18331
[56]	validation_0-mae:2827.10364
[57]	validation_0-mae:2800.69962
[58]	validation_0-mae:2778.04687
[59]	validation_0-mae:2764.57765
[60]	validation_0-mae:2751.61916
[61]	validation_0-mae:2734.46363
[62]	validation_0-mae:2724.73892
[63]	validation_0-mae:2710.24018
[64]	validation_0-mae:2692.45655
[65]	validation_0-mae:2679.80425
[66]	validation_0-mae:2658.86908
[67]	validation_0-mae:2639.04537
[68]	validation_0-mae:2625.60192
[69]	validation_0-mae:2617.67501
[70]	validation_0-mae:2610.34190
[71]	validation_0-mae:2605.34054
[72]	validation_0-mae:2596.45127
[73]	validation_0-mae:2585.02054
[74]	validation_0-mae:2573.41914
[75]	validation_0-mae:2563.63423
[76]	validation_0-mae:2555.35551
[77]	validation_0-mae:2546.77787
[78]	validation_0-mae:2538.99766
[79]	validation_0-mae:2522.58484
[80]	validation_0-mae:2514.96794
[81]	validation_0-mae:2500.75343
[82]	validation_0-mae:2496.61099
[83]	validation_0-mae:2488.06081
[84]	validation_0-mae:2481.17335
[0]	validation_0-mae:12429.16295
[1]	validation_0-mae:11677.02807
[2]	validation_0-mae:11012.51240
[3]	validation_0-mae:10423.57684
[4]	validation_0-mae:9885.28506
[5]	validation_0-mae:9418.59682
[6]	validation_0-mae:9016.95605
[7]	validation_0-mae:8652.91294
[8]	validation_0-mae:8343.81006
[9]	validation_0-mae:8059.61559

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[0]	validation_0-mae:12525.83614
[1]	validation_0-mae:11867.89935
[2]	validation_0-mae:11312.22747
[3]	validation_0-mae:10841.72200
[4]	validation_0-mae:10433.30282
[5]	validation_0-mae:10091.12252
[6]	validation_0-mae:9792.64973
[7]	validation_0-mae:9525.53669
[8]	validation_0-mae:9305.42414
[9]	validation_0-mae:9119.27177
[0]	validation_0-mae:12455.56583
[1]	validation_0-mae:11731.73570
[2]	validation_0-mae:11079.14631
[3]	validation_0-mae:10451.51831
[4]	validation_0-mae:9912.00915
[5]	validation_0-mae:9409.23612
[6]	validation_0-mae:8954.82288
[7]	validation_0-mae:8523.43711
[8]	validation_0-mae:8122.56044
[9]	validation_0-mae:7784.72192
[10]	validation_0-mae:7478.74825

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[0]	validation_0-mae:12412.27395
[1]	validation_0-mae:11654.03523
[2]	validation_0-mae:10977.43453
[3]	validation_0-mae:10341.59695
[4]	validation_0-mae:9793.13603
[5]	validation_0-mae:9285.79965
[6]	validation_0-mae:8837.93924
[7]	validation_0-mae:8422.66703
[8]	validation_0-mae:8034.35979
[9]	validation_0-mae:7678.14165
[10]	validation_0-mae:7369.66097
[11]	validation_0-mae:7086.17030
[12]	validation_0-mae:6799.08636
[13]	validation_0-mae:6545.49625
[14]	validation_0-mae:6316.98438
[15]	validation_0-mae:6062.97634
[16]	validation_0-mae:5842.17013
[17]	validation_0-mae:5631.07361
[18]	validation_0-mae:5428.49182
[19]	validation_0-mae:5255.66004
[20]	validation_0-mae:5098.55856
[21]	validation_0-mae:4961.75219
[22]	validation_0-mae:4822.24323
[23]	validation_0-mae:4678.06913
[24]	validation_0-mae:4545.72734
[25]	validation_0-mae:4412.15290
[26]	validation_0-mae:4313.03801
[27]	validation_0-mae:4197.72497
[28]	validation_0-mae:4106.51333
[29]	validation_0-mae:4012.22541
[30]	validation_0-mae:3913.22639
[31]	validation_0-mae:3819.32898
[32]	validation_0-mae:3742.80978
[33]	validation_0-mae:3668.79933
[34]	validation_0-mae:3607.96743
[35]	validation_0-mae:3537.73381
[36]	validation_0-mae:3480.19938
[37]	validation_0-mae:3425.23401
[38]	validation_0-mae:3364.54076
[39]	validation_0-mae:3309.81712
[40]	validation_0-mae:3262.88773
[41]	validation_0-mae:3216.11387
[42]	validation_0-mae:3177.78181
[43]	validation_0-mae:3139.33876
[44]	validation_0-mae:3095.89829
[45]	validation_0-mae:3071.39747
[46]	validation_0-mae:3034.92923
[47]	validation_0-mae:2999.54455
[48]	validation_0-mae:2971.62278
[49]	validation_0-mae:2939.11803
[50]	validation_0-mae:2913.63167
[51]	validation_0-mae:2883.22022
[52]	validation_0-mae:2859.82527
[53]	validation_0-mae:2831.74822
[54]	validation_0-mae:2813.02145
[55]	validation_0-mae:2789.67146
[56]	validation_0-mae:2771.40496
[57]	validation_0-mae:2753.52820
[58]	validation_0-mae:2741.38597
[59]	validation_0-mae:2719.52886
[60]	validation_0-mae:2703.58406
[61]	validation_0-mae:2691.64272
[62]	validation_0-mae:2677.71535
[63]	validation_0-mae:2664.30346
[64]	validation_0-mae:2652.16656
[65]	validation_0-mae:2634.90571
[66]	validation_0-mae:2621.12114
[67]	validation_0-mae:2608.07964
[68]	validation_0-mae:2595.29105
[69]	validation_0-mae:2582.21963
[70]	validation_0-mae:2572.36353
[71]	validation_0-mae:2557.99246
[72]	validation_0-mae:2545.08615
[73]	validation_0-mae:2527.78617
[74]	validation_0-mae:2521.35364
[75]	validation_0-mae:2516.33914
[76]	validation_0-mae:2510.56773
[77]	validation_0-mae:2501.05526
[78]	validation_0-mae:2492.84556
[79]	validation_0-mae:2484.64796
[80]	validation_0-mae:2475.70368
[81]	validation_0-mae:2475.43475
[82]	validation_0-mae:2465.54642
[83]	validation_0-mae:2459.46351
[84]	validation_0-mae:2452.23134
[85]	validation_0-mae:2446.41776
[86]	validation_0-mae:2437.54986
[87]	validation_0-mae:2427.87453
[88]	validation_0-mae:2416.52469
[89]	validation_0-mae:2406.62133
[90]	validation_0-mae:2400.58317
[91]	validation_0-mae:2394.45001
[92]	validation_0-mae:2381.52490
[93]	validation_0-mae:2373.97771
[94]	validation_0-mae:2367.15066
[95]	validation_0-mae:2364.20459
[96]	validation_0-mae:2357.00671
[97]	validation_0-mae:2350.93911
[98]	validation_0-mae:2350.44512
[99]	validation_0-mae:2347.15518
[100]	validation_0-mae:2338.86077
[101]	validation_0-mae:2333.68635
[102]	validation_0-mae:2331.74505
[103]	validation_0-mae:2328.51055
[104]	validation_0-mae:2326.88523
[105]	validation_0-mae:2318.35876
[106]	validation_0-mae:2316.01562
[107]	validation_0-mae:2308.87271
[108]	validation_0-mae:2306.75647
[109]	validation_0-mae:2304.59678
[110]	validation_0-mae:2301.99937
[111]	validation_0-mae:2298.10486
[112]	validation_0-mae:2292.59784
[113]	validation_0-mae:2289.64110
[114]	validation_0-mae:2285.03652
[115]	validation_0-mae:2282.87764
[116]	validation_0-mae:2279.64323
[117]	validation_0-mae:2277.24610
[118]	validation_0-mae:2273.36860
[119]	validation_0-mae:2271.94076
[120]	validation_0-mae:2271.24953
[121]	validation_0-mae:2270.09706
[122]	validation_0-mae:2267.64742
[123]	validation_0-mae:2264.86687
[124]	validation_0-mae:2261.84149
[125]	validation_0-mae:2258.13981
[126]	validation_0-mae:2256.72431
[127]	validation_0-mae:2256.01511
[128]	validation_0-mae:2254.29567
[129]	validation_0-mae:2253.11351
[130]	validation_0-mae:2251.58123
[131]	validation_0-mae:2250.27756
[132]	validation_0-mae:2248.76696
[133]	validation_0-mae:2247.84324
[134]	validation_0-mae:2244.40123
[135]	validation_0-mae:2243.41822
[136]	validation_0-mae:2240.74737
[137]	validation_0-mae:2240.99556
[138]	validation_0-mae:2237.14494
[139]	validation_0-mae:2235.83171
[140]	validation_0-mae:2233.21079
[141]	validation_0-mae:2229.17100
[142]	validation_0-mae:2227.78996
[143]	validation_0-mae:2227.19577
[144]	validation_0-mae:2226.48598
[145]	validation_0-mae:2226.24267
[146]	validation_0-mae:2224.84920
[147]	validation_0-mae:2223.28720
[148]	validation_0-mae:2220.92656
[149]	validation_0-mae:2218.49030
[150]	validation_0-mae:2218.06363
[151]	validation_0-mae:2216.93658
[152]	validation_0-mae:2216.00691
[153]	validation_0-mae:2216.68597
[154]	validation_0-mae:2216.10104
[155]	validation_0-mae:2212.77452
[156]	validation_0-mae:2213.21525
[157]	validation_0-mae:2211.84183
[158]	validation_0-mae:2212.83265
[159]	validation_0-mae:2212.17925
[160]	validation_0-mae:2210.76370
[161]	validation_0-mae:2210.95075
[162]	validation_0-mae:2209.59366
[163]	validation_0-mae:2209.38230
[164]	validation_0-mae:2209.85577
[165]	validation_0-mae:2208.81415
[166]	validation_0-mae:2205.14553
[167]	validation_0-mae:2205.89911
[168]	validation_0-mae:2207.45982
[169]	validation_0-mae:2204.36872
[170]	validation_0-mae:2203.66017
[171]	validation_0-mae:2204.51450
[172]	validation_0-mae:2203.75314
[173]	validation_0-mae:2205.13881
[174]	validation_0-mae:2205.21487
[175]	validation_0-mae:2203.43348
[176]	validation_0-mae:2199.37733
[177]	validation_0-mae:2196.16654
[178]	validation_0-mae:2195.56696
[179]	validation_0-mae:2195.72573
[180]	validation_0-mae:2194.95603
[181]	validation_0-mae:2195.17334
[182]	validation_0-mae:2193.32255
[183]	validation_0-mae:2193.85655
[184]	validation_0-mae:2191.91834
[185]	validation_0-mae:2192.11893
[186]	validation_0-mae:2192.05171
[187]	validation_0-mae:2191.88299
[188]	validation_0-mae:2191.90186
[189]	validation_0-mae:2190.20067
[190]	validation_0-mae:2189.08001
[191]	validation_0-mae:2189.27820
[192]	validation_0-mae:2187.48115
[193]	validation_0-mae:2187.14098
[194]	validation_0-mae:2185.87344
[195]	validation_0-mae:2185.68389
[196]	validation_0-mae:2185.57673
[197]	validation_0-mae:2185.61224
[198]	validation_0-mae:2185.92015
[199]	validation_0-mae:2185.29563
[0]	validation_0-mae:12483.75042
[1]	validation_0-mae:11766.74644
[2]	validation_0-mae:11144.39465
[3]	validation_0-mae:10558.45924
[4]	validation_0-mae:10047.50636
[5]	validation_0-mae:9567.08737
[6]	validation_0-mae:9160.16090
[7]	validation_0-mae:8776.88217
[8]	validation_0-mae:8433.83782
[9]	validation_0-mae:8093.05437

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[0]	validation_0-mae:12365.43179
[1]	validation_0-mae:11570.75543
[2]	validation_0-mae:10852.29515
[3]	validation_0-mae:10181.28630
[4]	validation_0-mae:9589.37145
[5]	validation_0-mae:9071.37035
[6]	validation_0-mae:8616.82795
[7]	validation_0-mae:8191.41969
[8]	validation_0-mae:7808.83488
[9]	validation_0-mae:7449.53278
[10]	validation_0-mae:7137.55938
[11]	validation_0-mae:6849.17156
[12]	validation_0-mae:6571.25623
[13]	validation_0-mae:6300.50260
[14]	validation_0-mae:6052.36616
[15]	validation_0-mae:5835.75577
[16]	validation_0-mae:5613.94358
[17]	validation_0-mae:5403.01935
[18]	validation_0-mae:5222.56807
[19]	validation_0-mae:5053.74487
[20]	validation_0-mae:4890.08389
[21]	validation_0-mae:4737.72336
[22]	validation_0-mae:4599.19182
[23]	validation_0-mae:4456.19928
[24]	validation_0-mae:4320.84914
[25]	validation_0-mae:4212.69463
[26]	validation_0-mae:4116.67415
[27]	validation_0-mae:4009.99362
[28]	validation_0-mae:3926.57542
[29]	validation_0-mae:3835.96742
[30]	validation_0-mae:3745.94464
[31]	validation_0-mae:3668.07328
[32]	validation_0-mae:3583.64072
[33]	validation_0-mae:3515.30297
[34]	validation_0-mae:3452.15313
[35]	validation_0-mae:3395.62489
[36]	validation_0-mae:3342.95239
[37]	validation_0-mae:3292.24500
[38]	validation_0-mae:3252.46584
[39]	validation_0-mae:3211.42772
[40]	validation_0-mae:3170.44427
[41]	validation_0-mae:3127.38600
[42]	validation_0-mae:3091.71144
[43]	validation_0-mae:3042.38820
[44]	validation_0-mae:3009.26465
[45]	validation_0-mae:2976.93924
[46]	validation_0-mae:2931.02768
[47]	validation_0-mae:2899.09247
[48]	validation_0-mae:2873.87133
[49]	validation_0-mae:2847.18948
[50]	validation_0-mae:2828.94605
[51]	validation_0-mae:2813.44741
[52]	validation_0-mae:2792.63331
[53]	validation_0-mae:2767.04425
[54]	validation_0-mae:2742.39095
[55]	validation_0-mae:2729.67066
[56]	validation_0-mae:2715.23821
[57]	validation_0-mae:2700.77004
[58]	validation_0-mae:2686.29224
[59]	validation_0-mae:2674.98936
[60]	validation_0-mae:2661.47524
[61]	validation_0-mae:2651.14922
[62]	validation_0-mae:2641.32296
[63]	validation_0-mae:2625.37118
[64]	validation_0-mae:2619.48992
[65]	validation_0-mae:2607.57473
[66]	validation_0-mae:2598.39849
[67]	validation_0-mae:2584.58251
[68]	validation_0-mae:2571.24314
[69]	validation_0-mae:2562.20917
[70]	validation_0-mae:2554.05709
[71]	validation_0-mae:2541.25291
[72]	validation_0-mae:2530.66091
[73]	validation_0-mae:2518.67901
[74]	validation_0-mae:2503.90427
[75]	validation_0-mae:2494.76259
[76]	validation_0-mae:2482.91266
[77]	validation_0-mae:2472.88654
[78]	validation_0-mae:2469.10704
[79]	validation_0-mae:2460.90447
[80]	validation_0-mae:2454.46334
[81]	validation_0-mae:2450.17990
[82]	validation_0-mae:2446.44330
[83]	validation_0-mae:2438.76483
[84]	validation_0-mae:2432.57790
[85]	validation_0-mae:2426.64388
[86]	validation_0-mae:2425.29893
[87]	validation_0-mae:2411.81420
[88]	validation_0-mae:2407.39095
[89]	validation_0-mae:2402.12798
[90]	validation_0-mae:2398.76110
[91]	validation_0-mae:2395.55339
[92]	validation_0-mae:2389.70054
[93]	validation_0-mae:2382.53331
[94]	validation_0-mae:2376.49907
[95]	validation_0-mae:2372.31545
[96]	validation_0-mae:2369.41416
[97]	validation_0-mae:2360.40600
[98]	validation_0-mae:2356.34308
[99]	validation_0-mae:2353.32515
[100]	validation_0-mae:2348.77706
[101]	validation_0-mae:2346.96770
[102]	validation_0-mae:2339.51391
[103]	validation_0-mae:2333.41181
[104]	validation_0-mae:2331.75376
[105]	validation_0-mae:2329.13906
[106]	validation_0-mae:2323.43517
[107]	validation_0-mae:2317.64330
[108]	validation_0-mae:2313.24288
[109]	validation_0-mae:2310.75732
[110]	validation_0-mae:2307.52408
[111]	validation_0-mae:2300.85937
[112]	validation_0-mae:2296.46904
[113]	validation_0-mae:2293.25436
[114]	validation_0-mae:2292.19608
[115]	validation_0-mae:2290.37786
[116]	validation_0-mae:2285.66272
[117]	validation_0-mae:2282.14010
[118]	validation_0-mae:2280.51386
[119]	validation_0-mae:2276.65774
[120]	validation_0-mae:2274.11362
[121]	validation_0-mae:2272.07074
[122]	validation_0-mae:2268.54953
[123]	validation_0-mae:2266.21363
[124]	validation_0-mae:2264.15017
[125]	validation_0-mae:2262.98458
[126]	validation_0-mae:2262.31306
[127]	validation_0-mae:2260.78423
[128]	validation_0-mae:2258.62098
[129]	validation_0-mae:2256.49936
[130]	validation_0-mae:2252.55377
[131]	validation_0-mae:2250.99450
[132]	validation_0-mae:2248.75255
[133]	validation_0-mae:2246.28602
[134]	validation_0-mae:2246.62593
[135]	validation_0-mae:2245.71286
[136]	validation_0-mae:2244.64819
[137]	validation_0-mae:2240.71457
[138]	validation_0-mae:2237.43565
[139]	validation_0-mae:2235.69912
[140]	validation_0-mae:2234.47497
[141]	validation_0-mae:2232.70164
[142]	validation_0-mae:2232.64355
[143]	validation_0-mae:2232.81017
[144]	validation_0-mae:2232.48578
[145]	validation_0-mae:2232.17420
[146]	validation_0-mae:2229.98262
[147]	validation_0-mae:2227.93706
[148]	validation_0-mae:2224.03948
[149]	validation_0-mae:2222.55692
[150]	validation_0-mae:2220.30033
[151]	validation_0-mae:2218.60469
[152]	validation_0-mae:2217.75323
[153]	validation_0-mae:2217.77489
[154]	validation_0-mae:2216.06139
[155]	validation_0-mae:2216.40555
[156]	validation_0-mae:2216.77143
[157]	validation_0-mae:2216.17338
[158]	validation_0-mae:2215.00736
[159]	validation_0-mae:2215.60846
[160]	validation_0-mae:2213.63349
[161]	validation_0-mae:2211.77412
[162]	validation_0-mae:2211.44134
[163]	validation_0-mae:2212.32610
[164]	validation_0-mae:2211.41652
[165]	validation_0-mae:2209.72559
[166]	validation_0-mae:2206.24198
[167]	validation_0-mae:2206.60002
[168]	validation_0-mae:2204.62217
[169]	validation_0-mae:2204.58759
[170]	validation_0-mae:2203.64896
[171]	validation_0-mae:2203.26522
[172]	validation_0-mae:2201.99775
[173]	validation_0-mae:2199.93568
[174]	validation_0-mae:2198.25376
[175]	validation_0-mae:2197.01259
[176]	validation_0-mae:2195.45322
[177]	validation_0-mae:2192.49849
[178]	validation_0-mae:2191.08349
[179]	validation_0-mae:2189.50297
[180]	validation_0-mae:2188.52080
[181]	validation_0-mae:2189.17849
[182]	validation_0-mae:2188.42628
[183]	validation_0-mae:2186.44060
[184]	validation_0-mae:2184.46503
[185]	validation_0-mae:2182.52979
[186]	validation_0-mae:2183.36564
[187]	validation_0-mae:2181.86267
[188]	validation_0-mae:2181.46757
[189]	validation_0-mae:2180.87325
[190]	validation_0-mae:2180.58411
[191]	validation_0-mae:2180.34421
[192]	validation_0-mae:2178.76327
[193]	validation_0-mae:2178.32607
[194]	validation_0-mae:2177.32983
[195]	validation_0-mae:2178.43731
[196]	validation_0-mae:2177.08361
[197]	validation_0-mae:2178.18472
[198]	validation_0-mae:2177.98912
[199]	validation_0-mae:2178.54348
[200]	validation_0-mae:2178.62269
[201]	validation_0-mae:2178.00058
[202]	validation_0-mae:2176.48577
[203]	validation_0-mae:2175.78227
[204]	validation_0-mae:2174.75766
[205]	validation_0-mae:2172.08002
[206]	validation_0-mae:2171.58024
[207]	validation_0-mae:2170.49664
[208]	validation_0-mae:2171.61509
[209]	validation_0-mae:2171.31192
[210]	validation_0-mae:2170.25664
[211]	validation_0-mae:2170.01817
[212]	validation_0-mae:2169.51128
[213]	validation_0-mae:2168.07950
[214]	validation_0-mae:2167.14803
[215]	validation_0-mae:2167.39393
[216]	validation_0-mae:2167.34042
[217]	validation_0-mae:2166.30732
[218]	validation_0-mae:2165.89755
[219]	validation_0-mae:2165.18305
[220]	validation_0-mae:2163.45758
[221]	validation_0-mae:2163.71924
[222]	validation_0-mae:2162.56076
[223]	validation_0-mae:2161.23628
[224]	validation_0-mae:2160.42216
[225]	validation_0-mae:2160.99609
[226]	validation_0-mae:2160.51519
[227]	validation_0-mae:2161.23049
[228]	validation_0-mae:2161.01550
[229]	validation_0-mae:2160.81516
[230]	validation_0-mae:2159.75190
[231]	validation_0-mae:2159.84098
[232]	validation_0-mae:2160.08349
[233]	validation_0-mae:2158.99012
[234]	validation_0-mae:2158.73433
[235]	validation_0-mae:2157.35541
[236]	validation_0-mae:2157.74627
[237]	validation_0-mae:2158.74219
[238]	validation_0-mae:2157.89419
[239]	validation_0-mae:2158.64293
[240]	validation_0-mae:2158.56003
[241]	validation_0-mae:2155.15399
[242]	validation_0-mae:2155.77796
[243]	validation_0-mae:2156.61619
[244]	validation_0-mae:2156.92835
[245]	validation_0-mae:2156.33368
[246]	validation_0-mae:2154.89329
[247]	validation_0-mae:2154.90042
[248]	validation_0-mae:2154.98254
[249]	validation_0-mae:2153.48341
[250]	validation_0-mae:2153.35837
[251]	validation_0-mae:2152.44881
[252]	validation_0-mae:2151.29678
[253]	validation_0-mae:2150.13818
[254]	validation_0-mae:2151.17804
[255]	validation_0-mae:2150.26052
[256]	validation_0-mae:2149.86634
[257]	validation_0-mae:2148.89554
[258]	validation_0-mae:2147.18232
[259]	validation_0-mae:2147.57293
[260]	validation_0-mae:2147.24838
[261]	validation_0-mae:2147.08150
[262]	validation_0-mae:2147.38342
[263]	validation_0-mae:2147.32464
[264]	validation_0-mae:2147.21338
[265]	validation_0-mae:2147.61845
[266]	validation_0-mae:2147.57477
[267]	validation_0-mae:2146.58200
[268]	validation_0-mae:2146.46235
[269]	validation_0-mae:2146.69996
[270]	validation_0-mae:2146.75144
[271]	validation_0-mae:2145.32273
[272]	validation_0-mae:2145.37650
[273]	validation_0-mae:2145.30490
[274]	validation_0-mae:2146.46143
[275]	validation_0-mae:2144.91323
[276]	validation_0-mae:2144.61831
[277]	validation_0-mae:2144.04890
[278]	validation_0-mae:2143.95341
[279]	validation_0-mae:2144.38753
[280]	validation_0-mae:2144.29819
[281]	validation_0-mae:2144.22817
[0]	validation_0-mae:12497.00949
[1]	validation_0-mae:11801.40729
[2]	validation_0-mae:11179.21848
[3]	validation_0-mae:10627.23174
[4]	validation_0-mae:10130.50594
[5]	validation_0-mae:9674.56771
[6]	validation_0-mae:9249.22422
[7]	validation_0-mae:8872.80668
[8]	validation_0-mae:8546.64644
[9]	validation_0-mae:8199.77736

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[0]	validation_0-mae:12372.46823
[1]	validation_0-mae:11585.03371
[2]	validation_0-mae:10887.77216
[3]	validation_0-mae:10279.46201
[4]	validation_0-mae:9744.95438
[5]	validation_0-mae:9268.79409
[6]	validation_0-mae:8866.93007
[7]	validation_0-mae:8482.07098
[8]	validation_0-mae:8153.88335
[9]	validation_0-mae:7832.82845
[10]	validation_0-mae:7561.21796
[0]	validation_0-mae:12555.10915
[1]	validation_0-mae:11912.67767
[2]	validation_0-mae:11353.54114
[3]	validation_0-mae:10888.86999
[4]	validation_0-mae:10485.74414
[5]	validation_0-mae:10135.03334
[6]	validation_0-mae:9825.68912
[7]	validation_0-mae:9567.62230
[8]	validation_0-mae:9339.91895
[9]	validation_0-mae:9159.17303
[10]	validation_0-mae:9004.19930

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[0]	validation_0-mae:12986.69948
[1]	validation_0-mae:12687.31185
[2]	validation_0-mae:12411.52283
[3]	validation_0-mae:12139.90655
[4]	validation_0-mae:11879.94439
[5]	validation_0-mae:11627.49243
[6]	validation_0-mae:11384.31878
[7]	validation_0-mae:11152.76011
[8]	validation_0-mae:10928.08053
[9]	validation_0-mae:10718.01047
[10]	validation_0-mae:10511.40090
[0]	validation_0-mae:12516.65324
[1]	validation_0-mae:11828.64424
[2]	validation_0-mae:11213.78381
[3]	validation_0-mae:10641.69853
[4]	validation_0-mae:10145.81402
[5]	validation_0-mae:9686.89508
[6]	validation_0-mae:9258.13551
[7]	validation_0-mae:8864.07787
[8]	validation_0-mae:8523.46060
[9]	validation_0-mae:8174.57875
[10]	validation_0-mae:7841.80550

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[0]	validation_0-mae:12504.71453
[1]	validation_0-mae:11813.23755
[2]	validation_0-mae:11199.96868
[3]	validation_0-mae:10622.08471
[4]	validation_0-mae:10114.21844
[5]	validation_0-mae:9636.21699
[6]	validation_0-mae:9225.28409
[7]	validation_0-mae:8865.46706
[8]	validation_0-mae:8521.20522
[9]	validation_0-mae:8176.74590
[0]	validation_0-mae:12383.52269
[1]	validation_0-mae:11602.63612
[2]	validation_0-mae:10889.65102
[3]	validation_0-mae:10242.07625
[4]	validation_0-mae:9674.59361
[5]	validation_0-mae:9137.00068
[6]	validation_0-mae:8696.74500
[7]	validation_0-mae:8273.87823
[8]	validation_0-mae:7880.89749
[9]	validation_0-mae:7531.96653
[10]	validation_0-mae:7220.39226
[11]	validation_0-mae:6898.20162
[12]	validation_0-mae:6613.53723
[13]	validation_0-mae:6366.21375
[14]	validation_0-mae:6127.89157
[15]	validation_0-mae:5923.27660
[16]	validation_0-mae:5689.96131
[17]	validation_0-mae:5482.51189
[18]	validation_0-mae:5310.63328
[19]	validation_0-mae:5142.00631
[20]	validation_0-mae:4959.75235
[21]	validation_0-mae:4817.22321
[22]	validation_0-mae:4668.39962
[23]	validation_0-mae:4540.30248
[24]	validation_0-mae:4410.10244
[25]	validation_0-mae:4318.14295
[26]	validation_0-mae:4221.85435
[27]	validation_0-mae:4114.86849
[28]	validation_0-mae:4010.64009
[29]	validation_0-mae:3918.73420
[30]	validation_0-mae:3831.31637
[31]	validation_0-mae:3752.60364
[32]	validation_0-mae:3676.55769
[33]	validation_0-mae:3614.49691
[34]	validation_0-mae:3560.83897
[35]	validation_0-mae:3497.69324

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")
C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dt = pd.to_datetime(Xo["date"], errors="coerce")

[36]	validation_0-mae:3446.36357
[37]	validation_0-mae:3397.56184
[38]	validation_0-mae:3349.82494
[39]	validation_0-mae:3302.31796
[40]	validation_0-mae:3258.87054
[41]	validation_0-mae:3224.09230
[42]	validation_0-mae:3184.99546
[43]	validation_0-mae:3142.67572
[44]	validation_0-mae:3110.69672
[45]	validation_0-mae:3063.44612
[46]	validation_0-mae:3024.03781
[47]	validation_0-mae:2999.90916
[48]	validation_0-mae:2972.70300
[49]	validation_0-mae:2944.21180
[50]	validation_0-mae:2927.64919
[51]	validation_0-mae:2903.16500
[52]	validation_0-mae:2886.25916
[53]	validation_0-mae:2859.17688
[54]	validation_0-mae:2834.66869
[55]	validation_0-mae:2817.28779
[56]	validation_0-mae:2792.53434
[57]	validation_0-mae:2767.83575
[58]	validation_0-mae:2757.91319
[59]	validation_0-mae:2747.30721
[60]	validation_0-mae:2733.70774
[61]	validation_0-mae:2710.38544
[62]	validation_0-mae:2682.16284
[63]	validation_0-mae:2671.29319
[64]	validation_0-mae:2664.80995
[65]	validation_0-mae:2654.64302
[66]	validation_0-mae:2644.23745
[67]	validation_0-mae:2633.63736
[68]	validation_0-mae:2606.97094
[69]	validation_0-mae:2598.63685
[70]	validation_0-mae:2590.65652
[71]	validation_0-mae:2579.21074
[72]	validation_0-mae:2569.07431
[73]	validation_0-mae:2555.75735
[74]	validation_0-mae:2536.35688
[75]	validation_0-mae:2523.12436
[76]	validation_0-mae:2512.15885
[77]	validation_0-mae:2505.93861
[78]	validation_0-mae:2494.28079
[79]	validation_0-mae:2487.04130
[80]	validation_0-mae:2479.49636
[81]	validation_0-mae:2471.42062
[82]	validation_0-mae:2460.71256
[83]	validation_0-mae:2453.15582
[84]	validation_0-mae:2445.38340
[85]	validation_0-mae:2438.46310
[86]	validation_0-mae:2432.97965
[87]	validation_0-mae:2419.53532
[88]	validation_0-mae:2414.80703
[89]	validation_0-mae:2407.58040
[90]	validation_0-mae:2398.65705
[91]	validation_0-mae:2390.80437
[92]	validation_0-mae:2378.29086
[93]	validation_0-mae:2370.90779
[94]	validation_0-mae:2364.99151
[95]	validation_0-mae:2362.45327
[96]	validation_0-mae:2357.84288
[97]	validation_0-mae:2355.71481
[98]	validation_0-mae:2350.41121
[99]	validation_0-mae:2345.12357
[100]	validation_0-mae:2336.89074
[101]	validation_0-mae:2333.60618
[102]	validation_0-mae:2323.33642
[103]	validation_0-mae:2320.20551
[104]	validation_0-mae:2316.16745
[105]	validation_0-mae:2308.40865
[106]	validation_0-mae:2302.03129
[107]	validation_0-mae:2296.74339
[108]	validation_0-mae:2292.90753
[109]	validation_0-mae:2292.67680
[110]	validation_0-mae:2290.90544
[111]	validation_0-mae:2284.50216
[112]	validation_0-mae:2280.90377
[113]	validation_0-mae:2278.62977
[114]	validation_0-mae:2275.00468
[115]	validation_0-mae:2269.62966
[116]	validation_0-mae:2267.08254
[117]	validation_0-mae:2263.91113
[118]	validation_0-mae:2258.25424
[119]	validation_0-mae:2257.27796
[120]	validation_0-mae:2253.42710
[121]	validation_0-mae:2251.21063
[122]	validation_0-mae:2249.88487
[123]	validation_0-mae:2247.86107
[124]	validation_0-mae:2244.04722
[125]	validation_0-mae:2236.12322
[126]	validation_0-mae:2233.77916
[127]	validation_0-mae:2232.46437
[128]	validation_0-mae:2231.24161
[129]	validation_0-mae:2229.83349
[130]	validation_0-mae:2227.09982
[131]	validation_0-mae:2224.58079
[132]	validation_0-mae:2222.93742
[133]	validation_0-mae:2221.34389
[134]	validation_0-mae:2219.05864
[135]	validation_0-mae:2217.66131
[136]	validation_0-mae:2215.22268
[137]	validation_0-mae:2214.22739
[138]	validation_0-mae:2212.84693
[139]	validation_0-mae:2209.94001
[140]	validation_0-mae:2208.95816
[141]	validation_0-mae:2206.59341
[142]	validation_0-mae:2205.65910
[143]	validation_0-mae:2203.55923
[144]	validation_0-mae:2201.27785
[145]	validation_0-mae:2200.66931
[146]	validation_0-mae:2197.57923
[147]	validation_0-mae:2194.71075
[148]	validation_0-mae:2194.20891
[149]	validation_0-mae:2193.01812
[150]	validation_0-mae:2191.59459
[151]	validation_0-mae:2190.55708
[152]	validation_0-mae:2187.81794
[153]	validation_0-mae:2186.11958
[154]	validation_0-mae:2184.28018
[155]	validation_0-mae:2182.11308
[156]	validation_0-mae:2180.28120
[157]	validation_0-mae:2179.59403
[158]	validation_0-mae:2178.23685
[159]	validation_0-mae:2177.92838
[160]	validation_0-mae:2178.58297
[161]	validation_0-mae:2176.20026
[162]	validation_0-mae:2176.41365
[163]	validation_0-mae:2174.56434
[164]	validation_0-mae:2174.29547
[165]	validation_0-mae:2171.46573
[166]	validation_0-mae:2168.19952
[167]	validation_0-mae:2165.96417
[168]	validation_0-mae:2164.69893
[169]	validation_0-mae:2163.40022
[170]	validation_0-mae:2161.81371
[171]	validation_0-mae:2160.98035
[172]	validation_0-mae:2159.54188
[173]	validation_0-mae:2159.04813
[174]	validation_0-mae:2157.10798
[175]	validation_0-mae:2156.78484
[176]	validation_0-mae:2156.04400
[177]	validation_0-mae:2155.69889
[178]	validation_0-mae:2152.20240
[179]	validation_0-mae:2152.73052
[180]	validation_0-mae:2151.95120
[181]	validation_0-mae:2150.47365
[182]	validation_0-mae:2150.21441
[183]	validation_0-mae:2149.74260
[184]	validation_0-mae:2147.93270
[185]	validation_0-mae:2143.54040
[186]	validation_0-mae:2141.60070
[187]	validation_0-mae:2141.19571
[188]	validation_0-mae:2139.89096
[189]	validation_0-mae:2139.97459
[190]	validation_0-mae:2139.69523
[191]	validation_0-mae:2139.10584
[192]	validation_0-mae:2139.47841
[193]	validation_0-mae:2139.70299
[194]	validation_0-mae:2139.93000
[195]	validation_0-mae:2138.11991
[196]	validation_0-mae:2138.14123
[197]	validation_0-mae:2137.49774
[198]	validation_0-mae:2136.88671
[199]	validation_0-mae:2135.04602
[200]	validation_0-mae:2134.23888
[201]	validation_0-mae:2131.41644
[202]	validation_0-mae:2131.98778
[203]	validation_0-mae:2130.06113
[204]	validation_0-mae:2127.55782
[205]	validation_0-mae:2127.72827
[206]	validation_0-mae:2127.21905
[207]	validation_0-mae:2127.40024
[208]	validation_0-mae:2126.34487
[209]	validation_0-mae:2126.32212
[210]	validation_0-mae:2125.24424
[211]	validation_0-mae:2123.93479
[212]	validation_0-mae:2122.55477
[213]	validation_0-mae:2120.54095
[214]	validation_0-mae:2118.80066
[215]	validation_0-mae:2116.69698
[216]	validation_0-mae:2118.44088
[217]	validation_0-mae:2116.92626
[218]	validation_0-mae:2117.78800
[219]	validation_0-mae:2118.13411
[220]	validation_0-mae:2118.56305
[221]	validation_0-mae:2118.39978
[222]	validation_0-mae:2118.25506
[223]	validation_0-mae:2118.29575
[224]	validation_0-mae:2117.61725
[225]	validation_0-mae:2116.55220
[226]	validation_0-mae:2116.12508
[227]	validation_0-mae:2115.60899
[228]	validation_0-mae:2115.29171
[229]	validation_0-mae:2115.32161
[230]	validation_0-mae:2115.72404
[231]	validation_0-mae:2115.36503
[232]	validation_0-mae:2114.76355
[233]	validation_0-mae:2114.54865
[234]	validation_0-mae:2114.38602
[235]	validation_0-mae:2113.77004
[236]	validation_0-mae:2114.36977
[237]	validation_0-mae:2114.61865
[238]	validation_0-mae:2112.49188
[239]	validation_0-mae:2112.98305
[240]	validation_0-mae:2113.22448
[241]	validation_0-mae:2112.04438
[242]	validation_0-mae:2112.04852
[243]	validation_0-mae:2111.55758
[244]	validation_0-mae:2112.16491
[245]	validation_0-mae:2112.02057
[246]	validation_0-mae:2112.35211
[247]	validation_0-mae:2111.64486
[248]	validation_0-mae:2111.45939
[249]	validation_0-mae:2111.23598
[250]	validation_0-mae:2111.10513
[251]	validation_0-mae:2111.07475
[252]	validation_0-mae:2111.69147
[253]	validation_0-mae:2110.97827
[254]	validation_0-mae:2109.75127
[255]	validation_0-mae:2108.86141
[256]	validation_0-mae:2108.22828
[257]	validation_0-mae:2108.01356
[258]	validation_0-mae:2107.06444
[259]	validation_0-mae:2107.86582
[260]	validation_0-mae:2107.80834
[261]	validation_0-mae:2108.67806
[262]	validation_0-mae:2107.90607
[263]	validation_0-mae:2107.52059
[264]	validation_0-mae:2107.08065
[265]	validation_0-mae:2107.70527
[266]	validation_0-mae:2108.38511
[267]	validation_0-mae:2107.32405
[268]	validation_0-mae:2106.91540
[269]	validation_0-mae:2106.83019
[270]	validation_0-mae:2106.49566
[271]	validation_0-mae:2106.30062
[272]	validation_0-mae:2106.24191
[273]	validation_0-mae:2106.91639
[274]	validation_0-mae:2106.93252
[275]	validation_0-mae:2106.87377
[276]	validation_0-mae:2107.35353
[277]	validation_0-mae:2107.85569
[278]	validation_0-mae:2107.33670
[279]	validation_0-mae:2106.86584
[280]	validation_0-mae:2106.06819
[281]	validation_0-mae:2105.68047
[282]	validation_0-mae:2104.80065
[283]	validation_0-mae:2104.32531
[284]	validation_0-mae:2103.88260
[285]	validation_0-mae:2103.90375
[286]	validation_0-mae:2103.95051
[287]	validation_0-mae:2103.52200
[288]	validation_0-mae:2103.23458
[289]	validation_0-mae:2102.93471
[290]	validation_0-mae:2101.18878
[291]	validation_0-mae:2099.77592
[292]	validation_0-mae:2100.13928
[293]	validation_0-mae:2100.35771
[294]	validation_0-mae:2100.31789
[295]	validation_0-mae:2099.86904
[296]	validation_0-mae:2100.19292
[297]	validation_0-mae:2099.88591
[298]	validation_0-mae:2098.71407
[299]	validation_0-mae:2098.12204
[300]	validation_0-mae:2097.55934
[301]	validation_0-mae:2097.20510
[302]	validation_0-mae:2097.13716
[303]	validation_0-mae:2096.37770
[304]	validation_0-mae:2096.51429
[305]	validation_0-mae:2095.80488
[306]	validation_0-mae:2096.06060
[307]	validation_0-mae:2096.39252
[308]	validation_0-mae:2096.56212
[309]	validation_0-mae:2096.43626
[310]	validation_0-mae:2095.80510
[311]	validation_0-mae:2095.55978
[312]	validation_0-mae:2095.43235
[313]	validation_0-mae:2095.39844
[314]	validation_0-mae:2095.71336
[315]	validation_0-mae:2094.69797
[316]	validation_0-mae:2095.25663
[317]	validation_0-mae:2095.28800
[318]	validation_0-mae:2095.64924
[319]	validation_0-mae:2095.47654
[320]	validation_0-mae:2095.69837
[321]	validation_0-mae:2095.73736
[322]	validation_0-mae:2095.44308
[323]	validation_0-mae:2095.55196
[324]	validation_0-mae:2094.86237
[325]	validation_0-mae:2094.28490
[326]	validation_0-mae:2094.58245
[327]	validation_0-mae:2092.70169
[328]	validation_0-mae:2092.99749
[329]	validation_0-mae:2091.24638
[330]	validation_0-mae:2091.47604
[331]	validation_0-mae:2090.98380
[332]	validation_0-mae:2089.99162
[333]	validation_0-mae:2089.80785
[334]	validation_0-mae:2089.85711
[335]	validation_0-mae:2090.42688
[336]	validation_0-mae:2090.73283
[337]	validation_0-mae:2090.33129
[338]	validation_0-mae:2090.01197
[339]	validation_0-mae:2089.72644
[340]	validation_0-mae:2089.18828
[341]	validation_0-mae:2088.51976
[342]	validation_0-mae:2088.16414
[343]	validation_0-mae:2088.37218
[344]	validation_0-mae:2088.14676
[345]	validation_0-mae:2087.93621
[346]	validation_0-mae:2086.41847
[347]	validation_0-mae:2086.85022
[348]	validation_0-mae:2086.90538
[349]	validation_0-mae:2086.66081
[350]	validation_0-mae:2086.70422
[351]	validation_0-mae:2087.13833
[352]	validation_0-mae:2086.61893
[353]	validation_0-mae:2086.68369
[354]	validation_0-mae:2086.60286
[355]	validation_0-mae:2087.28221
[356]	validation_0-mae:2085.96992
[357]	validation_0-mae:2086.28515
[358]	validation_0-mae:2086.46353
[359]	validation_0-mae:2086.61450
[360]	validation_0-mae:2086.84494
[361]	validation_0-mae:2086.18937
[362]	validation_0-mae:2086.14539
[363]	validation_0-mae:2086.26116
[364]	validation_0-mae:2086.20122
[365]	validation_0-mae:2086.71510
[366]	validation_0-mae:2086.36451
[367]	validation_0-mae:2085.29498
[368]	validation_0-mae:2084.98781
[369]	validation_0-mae:2085.10087
[370]	validation_0-mae:2084.22217
[371]	validation_0-mae:2082.76441
[372]	validation_0-mae:2082.75995
[373]	validation_0-mae:2082.33269
[374]	validation_0-mae:2082.84448
[375]	validation_0-mae:2083.65591
[376]	validation_0-mae:2083.73730
[377]	validation_0-mae:2084.18766
[378]	validation_0-mae:2084.44927
[379]	validation_0-mae:2083.62500
[380]	validation_0-mae:2083.55134
[381]	validation_0-mae:2082.64580
[382]	validation_0-mae:2081.46457
[383]	validation_0-mae:2081.33412
[384]	validation_0-mae:2081.35537
[385]	validation_0-mae:2081.37319
[386]	validation_0-mae:2080.48242
[387]	validation_0-mae:2080.04909
[388]	validation_0-mae:2079.81898
[389]	validation_0-mae:2080.27247
[390]	validation_0-mae:2080.38395
[391]	validation_0-mae:2079.92276
[392]	validation_0-mae:2079.76720
[393]	validation_0-mae:2079.78549
[394]	validation_0-mae:2079.81181
[395]	validation_0-mae:2079.55641
[396]	validation_0-mae:2079.07333
[397]	validation_0-mae:2079.39303
[398]	validation_0-mae:2078.56636
[399]	validation_0-mae:2078.46350
[400]	validation_0-mae:2078.76775
[401]	validation_0-mae:2078.69794
[402]	validation_0-mae:2078.48543
[403]	validation_0-mae:2078.43786
[404]	validation_0-mae:2077.99683
[405]	validation_0-mae:2078.15582
[406]	validation_0-mae:2077.87628
[407]	validation_0-mae:2077.73798
[408]	validation_0-mae:2077.11763
[409]	validation_0-mae:2077.34440
[410]	validation_0-mae:2077.52762
[411]	validation_0-mae:2077.14450
[412]	validation_0-mae:2077.08391
[413]	validation_0-mae:2075.30323
[414]	validation_0-mae:2074.41720
[415]	validation_0-mae:2074.24939
[416]	validation_0-mae:2073.80033
[417]	validation_0-mae:2073.81306
[418]	validation_0-mae:2073.75440
[419]	validation_0-mae:2073.82902
[420]	validation_0-mae:2073.78675
[421]	validation_0-mae:2073.54415
[422]	validation_0-mae:2073.56397
[423]	validation_0-mae:2073.29975
[424]	validation_0-mae:2073.42474
[425]	validation_0-mae:2073.71166
[426]	validation_0-mae:2073.84817
[427]	validation_0-mae:2073.59025
[428]	validation_0-mae:2073.21738
[429]	validation_0-mae:2073.43100
[430]	validation_0-mae:2073.17052
[431]	validation_0-mae:2073.48743
[432]	validation_0-mae:2073.37819
[433]	validation_0-mae:2073.06153
[434]	validation_0-mae:2072.11024
[435]	validation_0-mae:2071.73059
[436]	validation_0-mae:2072.05707
[437]	validation_0-mae:2071.90618
[438]	validation_0-mae:2071.32507
[439]	validation_0-mae:2071.25218
[440]	validation_0-mae:2071.36729
[441]	validation_0-mae:2071.40505
[442]	validation_0-mae:2070.85137
[443]	validation_0-mae:2071.15278
[444]	validation_0-mae:2070.69205
[445]	validation_0-mae:2070.54434
[446]	validation_0-mae:2070.19242
[447]	validation_0-mae:2068.91882
[448]	validation_0-mae:2068.69263
[449]	validation_0-mae:2068.37169
[450]	validation_0-mae:2068.40175
[451]	validation_0-mae:2068.38102
[452]	validation_0-mae:2068.61327
[453]	validation_0-mae:2068.60960
[454]	validation_0-mae:2068.71594
[455]	validation_0-mae:2068.89336
[456]	validation_0-mae:2068.67038
[457]	validation_0-mae:2069.02032
[458]	validation_0-mae:2068.97212
[459]	validation_0-mae:2069.13573
[460]	validation_0-mae:2068.80651
[461]	validation_0-mae:2068.60888
[462]	validation_0-mae:2068.74330
[463]	validation_0-mae:2068.61749
[464]	validation_0-mae:2068.81021
[465]	validation_0-mae:2068.54664
[466]	validation_0-mae:2068.25056
[467]	validation_0-mae:2068.35154
[468]	validation_0-mae:2068.33535
[469]	validation_0-mae:2068.02057
[470]	validation_0-mae:2067.64748
[471]	validation_0-mae:2067.16389
[472]	validation_0-mae:2067.16509
[473]	validation_0-mae:2067.26442
[474]	validation_0-mae:2067.74242
[475]	validation_0-mae:2067.90031
[476]	validation_0-mae:2067.92828
[477]	validation_0-mae:2067.44287
[478]	validation_0-mae:2066.57584
[479]	validation_0-mae:2066.35357
[480]	validation_0-mae:2066.95181
[481]	validation_0-mae:2066.79413
[482]	validation_0-mae:2066.76157
[483]	validation_0-mae:2066.48449
[484]	validation_0-mae:2066.32158
[485]	validation_0-mae:2066.20622
[486]	validation_0-mae:2066.05016
[487]	validation_0-mae:2065.58809
[488]	validation_0-mae:2066.24280
[489]	validation_0-mae:2066.39090
[490]	validation_0-mae:2066.31450
[491]	validation_0-mae:2066.39855
[492]	validation_0-mae:2066.57439
[493]	validation_0-mae:2066.54426
[494]	validation_0-mae:2066.39663
[495]	validation_0-mae:2065.89414
[496]	validation_0-mae:2065.85690
[497]	validation_0-mae:2066.17828
[498]	validation_0-mae:2066.00636
[499]	validation_0-mae:2065.91832
[500]	validation_0-mae:2065.45906
[501]	validation_0-mae:2064.99393
[502]	validation_0-mae:2065.00844
[503]	validation_0-mae:2065.21205
[504]	validation_0-mae:2065.62983
[505]	validation_0-mae:2065.49044
[506]	validation_0-mae:2065.76647
[507]	validation_0-mae:2065.71114
[508]	validation_0-mae:2065.96778
[509]	validation_0-mae:2065.58886
[510]	validation_0-mae:2065.18488
[511]	validation_0-mae:2065.00399
[512]	validation_0-mae:2064.72266
[513]	validation_0-mae:2064.52882
[514]	validation_0-mae:2064.50188
[515]	validation_0-mae:2064.36197
[516]	validation_0-mae:2064.08127
[517]	validation_0-mae:2063.91006
[518]	validation_0-mae:2063.89266
[519]	validation_0-mae:2063.74203
[520]	validation_0-mae:2064.37833
[521]	validation_0-mae:2064.35091
[522]	validation_0-mae:2064.71409
[523]	validation_0-mae:2064.46693
[524]	validation_0-mae:2064.55106
[525]	validation_0-mae:2064.86705
[526]	validation_0-mae:2065.48800
[527]	validation_0-mae:2065.40642
[528]	validation_0-mae:2065.32447
[529]	validation_0-mae:2065.62680
[530]	validation_0-mae:2065.48079
[531]	validation_0-mae:2065.06281
[532]	validation_0-mae:2064.57966
[533]	validation_0-mae:2064.82804
[534]	validation_0-mae:2065.09123
[535]	validation_0-mae:2065.12410
[536]	validation_0-mae:2065.36157
[537]	validation_0-mae:2065.37900
[538]	validation_0-mae:2065.58348
[539]	validation_0-mae:2065.95817
[540]	validation_0-mae:2065.99650
[541]	validation_0-mae:2065.78692
[542]	validation_0-mae:2065.95069
[543]	validation_0-mae:2065.59736
[544]	validation_0-mae:2065.68212
[545]	validation_0-mae:2065.52180
[546]	validation_0-mae:2065.05584
[547]	validation_0-mae:2065.22896
[548]	validation_0-mae:2065.66962
[549]	validation_0-mae:2065.52502
[550]	validation_0-mae:2065.70386
[551]	validation_0-mae:2066.11727
[552]	validation_0-mae:2066.31414
[553]	validation_0-mae:2066.41207
[554]	validation_0-mae:2066.22410
[555]	validation_0-mae:2066.44380
[556]	validation_0-mae:2065.18851
[557]	validation_0-mae:2065.05923
[558]	validation_0-mae:2065.04428
[559]	validation_0-mae:2065.04445
[560]	validation_0-mae:2064.78769
[561]	validation_0-mae:2064.67303
[562]	validation_0-mae:2064.76823
[563]	validation_0-mae:2064.93803
[564]	validation_0-mae:2064.79816
[565]	validation_0-mae:2064.34111
[566]	validation_0-mae:2064.20211
[567]	validation_0-mae:2063.93472
[568]	validation_0-mae:2064.10141
[569]	validation_0-mae:2064.29963
[570]	validation_0-mae:2064.49990
[571]	validation_0-mae:2064.29489
[572]	validation_0-mae:2064.28257
[573]	validation_0-mae:2064.47476
[574]	validation_0-mae:2064.67404
[575]	validation_0-mae:2064.25660
[576]	validation_0-mae:2064.02469
[577]	validation_0-mae:2063.49377
[578]	validation_0-mae:2063.59895
[579]	validation_0-mae:2063.24807
[580]	validation_0-mae:2063.56061
[581]	validation_0-mae:2063.76757
[582]	validation_0-mae:2063.97785
[583]	validation_0-mae:2063.93549
[584]	validation_0-mae:2063.74257
[585]	validation_0-mae:2063.50870
[586]	validation_0-mae:2063.26687
[587]	validation_0-mae:2063.27472
[588]	validation_0-mae:2063.10812
[589]	validation_0-mae:2063.13216
[590]	validation_0-mae:2063.22099
[591]	validation_0-mae:2063.57526
[592]	validation_0-mae:2063.29850
[593]	validation_0-mae:2063.18688
[594]	validation_0-mae:2063.16827
[595]	validation_0-mae:2063.13988
[596]	validation_0-mae:2063.21016
[597]	validation_0-mae:2063.19996
[598]	validation_0-mae:2062.92081
[599]	validation_0-mae:2063.10985
[600]	validation_0-mae:2063.12879
[601]	validation_0-mae:2063.22080
[602]	validation_0-mae:2063.40152
[603]	validation_0-mae:2063.53757
[604]	validation_0-mae:2063.53348
[605]	validation_0-mae:2063.63808
[606]	validation_0-mae:2063.73874
[607]	validation_0-mae:2063.65368
[608]	validation_0-mae:2063.82703
[609]	validation_0-mae:2063.88470
[610]	validation_0-mae:2063.65394
[611]	validation_0-mae:2063.11593
[612]	validation_0-mae:2063.05115
[613]	validation_0-mae:2063.28709
[614]	validation_0-mae:2063.23393
[615]	validation_0-mae:2062.96517
[616]	validation_0-mae:2062.95466
[617]	validation_0-mae:2062.70011
[618]	validation_0-mae:2062.33344
[619]	validation_0-mae:2062.22919
[620]	validation_0-mae:2062.09514
[621]	validation_0-mae:2061.99210
[622]	validation_0-mae:2061.18946
[623]	validation_0-mae:2061.03356
[624]	validation_0-mae:2060.65761
[625]	validation_0-mae:2060.36264

### 4.1 ¿Qué es pruning y cómo impacta en el entrenamiento?

El pruning (poda de trials) es una técnica de optimización que detiene tempranamente aquellas configuraciones de hiperparámetros que, según el desempeño parcial observado durante el entrenamiento, no tienen proyección de mejorar al mejor resultado actual.
Impacto esperado: reduce tiempo de cómputo y recursos al evitar terminar trials poco prometedores, permitiendo explorar más combinaciones útiles dentro del mismo presupuesto de tiempo (misma ventana de 5 minutos), sin cambiar la métrica objetivo ni el pipeline final.

### 4.4 ¿Cómo cambian sus resultados con respecto a la sección anterior? ¿A qué se puede deber esto?
Al incorporar la técnica de pruning en la optimización de hiperparámetros, se observó una ligera variación en los resultados en comparación con la búsqueda bayesiana tradicional. El nuevo modelo alcanzó un MAE de 2028.31, muy cercano al 2012.35 obtenido previamente con Optuna sin pruning. Si bien el error aumentó marginalmente, el número total de trials realizados fue menor (267 frente a 321), lo que evidencia que el pruning logró reducir el tiempo de cómputo descartando tempranamente combinaciones poco prometedoras.

Este pequeño aumento en el MAE puede atribuirse a que algunos trials con potencial de mejora fueron podados antes de completar su entrenamiento, o a la naturaleza aleatoria del muestreo bayesiano. Aun así, el modelo con pruning mantiene un desempeño prácticamente equivalente, mostrando que la técnica es efectiva para acelerar la búsqueda de hiperparámetros sin comprometer significativamente la calidad predictiva.

## 5. Visualizaciones (5 puntos)

<p align="center">
  <img src="https://media.tenor.com/F-LgB1xTebEAAAAd/look-at-this-graph-nickelback.gif">
</p>


Satisfecho con su trabajo, Fiu le pregunta si es posible generar visualizaciones que permitan entender el entrenamiento de su modelo.

A partir del siguiente <a href = https://optuna.readthedocs.io/en/stable/tutorial/10_key_features/005_visualization.html#visualization>enlace</a>, genere las siguientes visualizaciones:

1. Gráfico de historial de optimización [1 punto]
2. Gráfico de coordenadas paralelas [1 punto]
3. Gráfico de importancia de hiperparámetros [1 punto]

Comente sus resultados:

4. ¿Desde qué *trial* se empiezan a observar mejoras notables en sus resultados? [0.5 puntos]
5. ¿Qué tendencias puede observar a partir del gráfico de coordenadas paralelas? [1 punto]
6. ¿Cuáles son los hiperparámetros con mayor importancia para la optimización de su modelo? [0.5 puntos]

In [ ]:
# 5. Visualizaciones con Optuna
from optuna.visualization import plot_optimization_history, plot_parallel_coordinate, plot_param_importances
study_to_plot = study_pruned  # (de la parte 4)

# 5.1️ Gráfico de historial de optimización
fig1 = plot_optimization_history(study_to_plot)
fig1.show()

# 5.2️ Gráfico de coordenadas paralelas
fig2 = plot_parallel_coordinate(study_to_plot)
fig2.show()

# 5.3️ Gráfico de importancia de hiperparámetros
fig3 = plot_param_importances(study_to_plot)
fig3.show()

c:\Users\verga\AppData\Local\Programs\Python\Python310\lib\site-packages\kaleido\_sync_server.py:11: UserWarning:



Warning: You have Plotly version 6.1.0, which is not compatible with this version of Kaleido (1.1.0).

This means that static image generation (e.g. `fig.write_image()`) will not work.

Please upgrade Plotly to version 6.1.1 or greater, or downgrade Kaleido to version 0.2.1.

### 5.4 ¿Desde qué trial se empiezan a observar mejoras notables en los resultados?

A partir del gráfico de historial de optimización, se observa que las mejoras más marcadas en el valor objetivo (MAE) comienzan alrededor del trial 5 al 10, donde el error baja bruscamente desde valores superiores a 7000 hasta cerca de 2000.
Después de ese punto, las mejoras son graduales y se estabilizan en torno al MAE mínimo (~2000) a partir del trial 40, indicando que el optimizador ya había explorado una zona próxima al óptimo.

### 5.5 ¿Qué tendencias puede observar a partir del gráfico de coordenadas paralelas?

El gráfico de coordenadas paralelas muestra que los trials con menor error tienden a cumplir las siguientes condiciones:

learning_rate se mantiene en valores medios (~0.04 a 0.08), evitando tanto tasas demasiado bajas como altas.

max_depth y max_leaves alcanzan valores altos (cercanos a 8–10 y 80–100 respectivamente), lo que sugiere que una mayor complejidad del árbol ayuda al modelo a capturar patrones relevantes.

n_estimators suele ser elevado (600–900), reforzando que más iteraciones permiten una convergencia más fina.

reg_alpha y reg_lambda tienden a valores bajos, indicando que una regularización moderada o débil favorece el ajuste.

En conjunto, estas tendencias sugieren que el modelo rinde mejor cuando combina una tasa de aprendizaje intermedia con alta capacidad de modelado y regularización leve.

### 5.6 ¿Cuáles son los hiperparámetros con mayor importancia para la optimización de su modelo?

De acuerdo con el gráfico de importancia de hiperparámetros, los tres parámetros más influyentes en el rendimiento del modelo son:

ohe_min_frequency — representa el umbral mínimo de frecuencia de categorías en el OneHotEncoder. Su alta importancia (≈ 0.64) muestra que el tratamiento de variables categóricas tiene un fuerte impacto en la generalización.

learning_rate — controla la velocidad de aprendizaje del modelo (≈ 0.20), afectando directamente la convergencia y estabilidad del entrenamiento.

max_leaves — influye en la complejidad de los árboles generados (≈ 0.08), determinando la capacidad del modelo para capturar relaciones no lineales.

El resto de los hiperparámetros —como n_estimators, max_depth, reg_alpha, y reg_lambda— presentan una influencia menor, lo que sugiere que su ajuste fino tiene un impacto limitado frente a las variables mencionadas.

## 6. Síntesis de resultados (3 puntos)

Finalmente:

1. Genere una tabla resumen del MAE en el conjunto de validación obtenido en los 5 modelos entrenados desde Baseline hasta XGBoost con Constraints, Optuna y Prunning. [1 punto]
2. Compare los resultados de la tabla y responda, ¿qué modelo obtiene el mejor rendimiento? [0.5 puntos]
3. Cargue el mejor modelo, prediga sobre el conjunto de **test** y reporte su MAE. [0.5 puntos]
4. ¿Existen diferencias con respecto a las métricas obtenidas en el conjunto de validación? ¿Porqué puede ocurrir esto? [1 punto]

In [ ]:
# 6. Síntesis de resultados
# 6.1 Tabla resumen del MAE en validación
resultados_mae = pd.DataFrame({
    "Modelo": [
        "Baseline DummyRegressor",
        "XGBRegressor (Default)",
        "XGBRegressor (Monotonicidad)",
        "XGBRegressor (Optuna)",
        "XGBRegressor (Optuna + Prunning)"
    ],
    "MAE Validación": [
        13298.497767,   # obtenido anteriormente
        2413.171360,    # baseline XGB default
        2499.159773,    # XGB con monotonicidad
        2012.350371,    # mejor con Optuna
        2028.307507     # con Optuna + pruning
    ]
})

display(resultados_mae)

# 6.2 Identificacion del mejor modelo
mejor_modelo = resultados_mae.loc[resultados_mae["MAE Validación"].idxmin(), "Modelo"]
print(f"\nEl mejor rendimiento en validación lo obtiene: {mejor_modelo}")

# 6.3 Cargar el mejor modelo (Optuna) y evaluar en conjunto de test
modelo_final = joblib.load("xgb_optuna.pkl")
y_pred_test = modelo_final.predict(X_test)
mae_test = mean_absolute_error(y_test, y_pred_test)

print(f"\nMAE en conjunto de test (modelo Optuna): {mae_test:.4f}")

                             Modelo  MAE Validación
0           Baseline DummyRegressor    13298.497767
1            XGBRegressor (Default)     2413.171360
2      XGBRegressor (Monotonicidad)     2499.159773
3             XGBRegressor (Optuna)     2012.350371
4  XGBRegressor (Optuna + Prunning)     2028.307507

El mejor rendimiento en validación lo obtiene: XGBRegressor (Optuna)

MAE en conjunto de test (modelo Optuna): 2089.2285

C:\Users\verga\AppData\Local\Temp\ipykernel_49172\3878269409.py:36: UserWarning:

Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.

### 6.4 Análisis final

El modelo con mejor rendimiento en el conjunto de validación fue el XGBRegressor optimizado con Optuna, con un MAE de 2012.35.
En comparación con las demás configuraciones, este modelo logró reducir significativamente el error frente al XGB baseline (2413.17) y al modelo con restricción monotónica (2499.16).

Al evaluar el mejor modelo sobre el conjunto de test, se obtuvo un MAE de 2089.23, ligeramente superior al obtenido en validación.
Esta diferencia es esperable y normal, ya que el conjunto de test representa datos completamente nuevos que el modelo no ha visto durante el entrenamiento ni la optimización.

Estas pequeñas variaciones pueden deberse a:

Diferencias leves en la distribución de las variables entre validación y test.

Aleatoriedad en el muestreo y en la inicialización del modelo.

Un posible ajuste fino hacia el conjunto de validación debido al proceso de búsqueda de hiperparámetros.

En general, el resultado confirma que el modelo optimizado con Optuna mantiene una buena capacidad de generalización, siendo el más eficiente entre todas las versiones entrenadas.

# Conclusión
Exito!
<p align="center">
  <img src="https://i.pinimg.com/originals/55/3d/42/553d42bea9b10e0662a05aa8726fc7f4.gif">
</p>